### ISSUE TITLE
error when setting up cntk on linux

### ISSUE THREAD

**Issue by khuangaf** [Microsoft/CNTK#1003]
I follow the instruction of linux setup:
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#optional-boost-library
Under section OPTIONAL. CNTK v2 Python support.
It says 
`Afterwards, run make as you normally would, which will build the CNTK Python module inside bindings/python/cntk and also produce a package (.whl) in a subfolder python of your build output folder (e.g., build/gpu/release/python).`
I do:
make
in cntk root file, but it pops out error:
```
(cntk-py34) steeve@steeve-X550VC:~/Desktop/cntk$ make -j all
Makefile:60: *** Cannot find ./Config.make.  Please see CNTK Wiki at https://github.com/Microsoft/cntk/wiki for configuration instructions..  Stop.
```
Can anyone help me?

**Comment by n17s** [comment]
You have to first run configure before you run make. An example configuration that enables GPU and python is [here](https://github.com/fiskio/CNTK/blob/abb5aeed9a230e487c424601a6dd94acd5866d99/Tools/docker/CNTK-GPU-Image/Dockerfile#L176) 
Make sure you configure things according to your environment.
