### ISSUE TITLE
cound not found environment: cntk-py34

### ISSUE THREAD

**Issue by khuangaf** [Microsoft/CNTK#1004]
I follow the instruction on how to install cntk on windows with binary.
when I run the installation script .\install.ps1 -execute
it pops out the error:
```
Setting up CNTK-PY34 environment. Please be patient....
Setting up CNTK-PY34 environment. Please be patient.... ** Exit Code **:(1)
Setting up CNTK Wheel environment. Please be patient....
Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\main.py", line 48, in main
    activate.main()
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\activate.py", line 109, in main
    binpath = binpath_from_arg(sys.argv[3], shelldict=shelldict)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\activate.py", line 66, in binpath_from_arg
    prefix = prefix_from_arg(arg, shelldict=shelldict)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\conda\cli\activate.py", line 60, in prefix_from_arg
    raise ValueError('could not find environment: %s' % arg)
ValueError: could not find environment: cntk-py34
Exception caught - function main / failure - End time [11/05/2016 16:32:13]
System.Management.Automation.RuntimeException: Running 'C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts\conda.exe ..activate cmd.exe cntk-py34' failed with exit code 1
```

I have installed anaconda3 with python3.5 on my computer and i was wondering where i did it wrong?

**Comment by n17s** [comment]
If you type
conda info --envs
in the console what do you get?

**Comment by khuangaf** [comment]
Umm it cannot recognize conda... How do I add conda into PATH? I tried adding C:\local\Anaconda3-4.1.1-Windows-x86_64 into it, but it doesn't work.

**Comment by khuangaf** [comment]
well, it turns out that my python path was not pointing to the one in anaconda.
However, I got another error after setting the correct PATH.
`Setting up CNTK-PY34 environment. Please be patient....                                                                 Setting up CNTK-PY34 environment. Please be patient.... ** Exit Code **:(1)                                             Setting up CNTK Wheel environment. Please be patient....                                                                Failed to import the site module                                                                                        Traceback (most recent call last):                                                                                        File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Lib\site.py", line 72, in <module>                                          import os                                                                                                             File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Lib\os.py", line 708, in <module>                                           from _collections_abc import MutableMapping                                                                           File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Lib\_collections_abc.py", line 56                                           async def _coro(): pass                                                                                                         ^                                                                                                           SyntaxError: invalid syntax                                                                                             Exception caught - function main / failure - End time [11/05/2016 20:40:47]                                             System.Management.Automation.RuntimeException: Running 'pip install D:\cntk\cntk\Python\cntk-2.0.beta1.0-cp34-cp34m-win_amd64.whl' failed with exit code 1 `
what causes this error, then?

**Comment by wolfma61** [comment]
If you run the setup the way we describe it on our wiki from inside the powershell environment , it doesn't effect any previous installed anaconda environment.

Perhaps this is something you want to try?, remove the CNTK2 beta 1 bits from your machine (the zip file, the already unpacked file, as well as the Anaconda in c;\Local). Download beta2 and follow exactly the binary  install operations described in our wiki

this should give you a fresh start
and as I said, we are setting up a new anaconda environment on your maschine, this shouldn't effect anything you already have ...

thx
Wolfgang

**Comment by khuangaf** [comment]
@wolfma61 I did exactly what you said: remove cntk as well as Anaconda. I downloaded cntk binary again from your wiki. However, this still pops up:
Do you want to continue? (y/n)
y
Performing download operations
Downloading [https://repo.continuum.io/archive/Anaconda3-4.1.1-Windows-x86_64.exe], please be patient....
File [D:\cntk\Scripts\windows\InstallCache\Anaconda3-4.1.1-Windows-x86_64.exe] already exists
Download operations finished

```
Performing install operations
Installing Anaconda3-4.1.1. This will take several minutes. Please be patient ....
Setting up CNTK-PY34 environment. Please be patient....
Setting up CNTK-PY34 environment. Please be patient.... ** Exit Code **:(1)
Setup/Update of CNTK Wheel environment. Please be patient....
Failed to import the site module
Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Lib\site.py", line 72, in <module>
    import os
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Lib\os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\Lib\_collections_abc.py", line 56
    async def _coro(): pass
            ^
SyntaxError: invalid syntax

Fatal error during script execution!
 System.Management.Automation.RuntimeException: Running 'pip install D:\cntk\cntk\Python\cntk-2.0.beta2.0-cp34-cp34m-win_amd64.whl' failed with exit code 1
```
Is their any environment setting wrong?

**Comment by sayanpa** [comment]
Can you activate the py env from cmd prompt instead of power shell as per the instructions . Also from within the activated env, can you run Python?

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
