### ISSUE TITLE
Failed to load model computed with the GPU distribution using the CPU only distribution

### ISSUE THREAD

**Issue by Masuzu** [Microsoft/CNTK#1005]
Hi,

I have a network which I trained using the *CNTK for Windows v.2.0 Beta 2 GPU* distribution.
I successfully loaded with the C++ API using the EvalDll.lib provided with this distribution.
Now I am trying to load the same model using the *CNTK for Windows v.2.0 Beta 2 CPU only* distribution.
However, doing so I run into the following error:
```
Validating --> z.x.x.x.x.x.x.x._ = BatchNormalization (z.x.x.x.x.x.x.x._.x.c, model.arrayOfFunctions[1].arrayOfFunctions[0].arrayOfFunctions[1].scale, model.arrayOfFunctions[1].arrayOfFunctions[0].arrayOfFunctions[1].bias, model.arrayOfFunctions[1].arrayOfFunctions[0].arrayOfFunctions[1].runMean, model.arrayOfFunctions[1].arrayOfFunctions[0].arrayOfFunctions[1].runVariance) : [77 x 107 x 16 x *], [16 x 1], [16 x 1], [16 x 1], [16 x 1] -> [77 x 107 x 16 x *] FAILED
The code is compiled with CPUONLY macro.
```

Has anyone run into the same issue?

**Comment by Masuzu** [comment]
To test, add`deviceId = -1` in the model loading definition parameters.

**Comment by zhouwangzw** [comment]
BatchNormailization is only implemented on GPU, but not on CPU yet. However, you should be able to evaluate the model on CPU, even the model is trained on GPU.

**Comment by n17s** [comment]
We do have the forward computation of BatchNormalization on CPU. So evaluation should work. The problem must be elsewhere.

**Comment by zhouwangzw** [comment]
@Masuzu  Are you setting `engine = "cudnn"` in the config? Could you please try to change it to `useCntkEngine = true`? 
Sorry for the inconvenience.
Thanks.

**Comment by zhouwangzw** [comment]
The latest release 2.0-Beta8 supports to evaluate the model with BN on CPU; which is trained on GPU. The BN engine has now a fallback path from cuDNN engine to CNTK Engine if GPU is not available.

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to reopen it if needed.
