### ISSUE TITLE
Windows: Install succeeds but execution fails

### ISSUE THREAD

**Issue by martenlindblad** [Microsoft/CNTK#1008]
Get this error: 
(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34) c:\repos\CNTK\Examples\Other\Simple2d\Data>cntk configFile=../Config/Simple.cntk makeMode=false command=Simple_Demo_Train
CNTK 2.0.beta2.0 (HEAD ca352f, Nov  3 2016 09:48:54) on DESKTOP-HEG04RG at 2016/11/07 20:47:30

cntk  configFile=../Config/Simple.cntk  makeMode=false  command=Simple_Demo_Train
CNTK: Failed to load DLL 'Math.dll'.
CNTK: Caught Win32 exception 0xc06d007e: Module not found.

Windows 10 newly installed. VS2015 installed aswell as everything in the automated install script.

**Comment by wolfma61** [comment]
Hi -
You followed the steps in the binary installation ...

looks like MATH.DLL can't be loaded. The dll is part of the binary package you installed and should be inside <install-location>\cntk\cntk (beside the cntk.exe, eval-dll, mkl_cntk_p.dll and about a dozen more)?
That location should also be part of your PATH statement

You installed a GPU or CPU version of CNTK?
For GPU you have an NVidia card and the latest drivers installed?
the unpacked version of the binary package is part of you path statement?

sorry for the trouble, but these are the first things which come to my mind

thx
Wolfgang

**Comment by martenlindblad** [comment]
I'm using the GPU installation package with 1-bit SGD. Latest nVidia drivers (MSI 1080).
My %PATH% is as follows (after i run c:\local\cntk\scripts\cntkpy34.bat): 
`C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34;C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\Library\mingw-w64\bin;C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\Library\usr\bin;C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\Library\bin;C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\Scripts;C:\local\cntk\cntk;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Users\marte\AppData\Local\Microsoft\WindowsApps;`

My C:\local\cntk\cntk does include Math.dll.

**Comment by wolfma61** [comment]
>>>My C:\local\cntk\cntk does include Math.dll
 that doesn't sound right... take a look at the package you unzipped, there should be a math.dll

**Comment by wolfma61** [comment]
I just downloaded the zip file again ...

here the contents of cntk\cntk (including math.dll)
    Directory: C:\cntk\cntk


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/8/2016  12:41 PM                Python
-a----        11/8/2016  12:40 PM         237568 BinaryReader.dll
-a----        11/8/2016  12:40 PM         107878 CNTK.core.bs
-a----        11/8/2016  12:40 PM        6273024 CNTK.exe
-a----        11/8/2016  12:40 PM        6211584 CNTKLibrary-2.0.dll
-a----        11/8/2016  12:40 PM         196774 CNTKLibrary-2.0.lib
-a----        11/8/2016  12:40 PM         436224 CNTKTextFormatReader.dll
-a----        11/8/2016  12:40 PM         410624 CompositeDataReader.dll
-a----        11/8/2016  12:40 PM       23380600 cublas64_75.dll
-a----        11/8/2016  12:40 PM         360736 cudart64_75.dll
-a----        11/8/2016  12:40 PM       59752960 cudnn64_5.dll
-a----        11/8/2016  12:40 PM       45030520 curand64_75.dll
-a----        11/8/2016  12:41 PM       35830064 cusparse64_75.dll
-a----        11/8/2016  12:41 PM         185344 DSSMReader.dll
-a----        11/8/2016  12:41 PM        5239808 EvalDll.dll
-a----        11/8/2016  12:41 PM          11910 EvalDll.lib
-a----        11/8/2016  12:41 PM        1223680 EvalWrapper.dll
-a----        11/8/2016  12:41 PM         595456 HTKDeserializers.dll
-a----        11/8/2016  12:41 PM         681984 HTKMLFReader.dll
-a----        11/8/2016  12:41 PM         529408 ImageReader.dll
-a----        11/8/2016  12:41 PM        1177288 libiomp5md.dll
-a----        11/8/2016  12:41 PM         289792 LibSVMBinaryReader.dll
-a----        11/8/2016  12:41 PM         351744 LMSequenceReader.dll
-a----        11/8/2016  12:41 PM         344064 LUSequenceReader.dll
-a----        11/8/2016  12:41 PM          11264 ManagedEvalTests.dll
-a----        11/8/2016  12:41 PM       45216256 Math.dll
-a----        11/8/2016  12:41 PM       14570496 mkl_cntk_p.dll
-a----        11/8/2016  12:41 PM         817720 nvml.dll
-a----        11/8/2016  12:41 PM       44814336 opencv_world310.dll
-a----        11/8/2016  12:41 PM         189440 SparsePCReader.dll
-a----        11/8/2016  12:41 PM         333824 UCIFastReader.dll
-a----        11/8/2016  12:41 PM        7269376 V2LibraryDistributionTests.bsc
-a----        11/8/2016  12:41 PM          76288 zip.dll
-a----        11/8/2016  12:41 PM          77824 zlib1.dll

**Comment by martenlindblad** [comment]
As I said it DOES include Math.dll. It just seems the cntk binary can't locate it I guess.
My contents after unpacking and installing:  
```
Directory of c:\local\cntk\cntk

2016-11-07  20:43    <DIR>          .
2016-11-07  20:43    <DIR>          ..
2016-11-03  09:38           237 568 BinaryReader.dll
2016-11-02  23:51           107 878 CNTK.core.bs
2016-11-03  09:55         6 273 024 CNTK.exe
2016-11-03  09:45         6 211 584 CNTKLibrary-2.0.dll
2016-11-03  09:44           196 774 CNTKLibrary-2.0.lib
2016-11-03  09:38           436 224 CNTKTextFormatReader.dll
2016-11-03  09:38           410 624 CompositeDataReader.dll
2015-08-15  17:21        23 380 600 cublas64_75.dll
2015-08-15  17:21           360 736 cudart64_75.dll
2016-08-23  04:48        59 752 960 cudnn64_5.dll
2015-08-15  17:21        45 030 520 curand64_75.dll
2015-08-15  17:21        35 830 064 cusparse64_75.dll
2016-11-03  09:38           185 344 DSSMReader.dll
2016-11-03  09:51         5 239 808 EvalDll.dll
2016-11-03  09:50            11 910 EvalDll.lib
2016-11-03  09:53         1 223 680 EvalWrapper.dll
2016-11-03  09:38           595 456 HTKDeserializers.dll
2016-11-03  09:38           681 984 HTKMLFReader.dll
2016-11-03  09:40           529 408 ImageReader.dll
2016-02-05  06:51         1 177 288 libiomp5md.dll
2016-11-03  09:37           289 792 LibSVMBinaryReader.dll
2016-11-03  09:39           351 744 LMSequenceReader.dll
2016-11-03  09:39           344 064 LUSequenceReader.dll
2016-11-03  09:55            11 264 ManagedEvalTests.dll
2016-11-03  09:36        45 216 256 Math.dll
2016-09-06  03:53        14 570 496 mkl_cntk_p.dll
2016-09-04  15:35           817 720 nvml.dll
2015-12-18  07:18        44 814 336 opencv_world310.dll
2016-11-07  20:43    <DIR>          Python
2016-11-03  09:39           189 440 SparsePCReader.dll
2016-11-03  09:37           333 824 UCIFastReader.dll
2016-11-03  09:46         7 269 376 V2LibraryDistributionTests.bsc
2016-02-12  14:29            76 288 zip.dll
2016-02-12  14:14            77 824 zlib1.dll
```

**Comment by wolfma61** [comment]
sorry - scratching my head ;)
Let's please try the following ...
change into your c:\local\cntk\cnkt directory and from a command shell run 
      rundll32 math.dll test
The expected behavior is, that you see an error message that the entry point test wasn't found

to be sure ... you did run the powershell install script?, you have the vsruntimes 2012&2013, msmpi etc installed on your machine?

thx
Wolfgang

**Comment by martenlindblad** [comment]
Hi again!
I ran the powershell install script, and everyhing installed OK. I tried running it again and it said everything was installed but the installer ran the VS2013 installation again. It's installed and in my application list.
When I run `rundll32 math.dll test` I get an error that the module doesn't exist, even though I used autocomplete to run it.

**Comment by wolfma61** [comment]
sorry - to clarify... what error message did you receive:
 - there was a problem starting math.dll. The specified module could not be found
or 
 - error in math.dll ... missing entry: test

if it is the first one, do you also get the same message if you execute the command in the same directory as math.dll?

**Comment by martenlindblad** [comment]
Number one: there was a problem starting math.dll. The specified module could not be found




On Thu, Nov 10, 2016 at 9:37 AM +0100, "Wolfgang Manousek" <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry - to clarify... what error message did you receive:

  *   there was a problem starting math.dll. The specified module could not be found or
  *   error in math.dll ... missing entry: test

if it is the first one, do you also get the same message if you execute the command in the same directory as math.dll?

-
