### ISSUE TITLE
ResNet 18 layer occur out of memory

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#1009]
I run ResNet 18 default version in GPU : GeForce GTX 1060 3GB.
but that occur out of memomy, So I find some info.
I get 2 tips.
first, someone say : in the top of configfile, write this shareNodeValueMatrices=true then that can be run
second, write this maxTempMemSizeInSamples=1
But these two tips is not the solution.

When I try to reduce minibatchsize 256 to 32, that run well.

my question is what is the reason I need to set minibatchsize 32. I have lots of remaining memory.

**Comment by n17s** [comment]
Then you should try increasing your minibatch size to the largest value that does not run out of memory.

**Comment by wolfma61** [comment]
I fyou still have this issue with the most recent bits and the recommendation above, please reopen with more information (or create a new issue)
