### ISSUE TITLE
Compile error with MKL

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#101]
The makefile does not find all MKL libraries. It fails with finding libiomp5.* (liomp5 flag).

I fixed this by copying these to a used path, but it should be fixed by searching for the correct path. 

As an example for intel64 on Xeon:
MISSING_INTEL64_LIBS=$(find /opt/intel/compilers_and_libraries*/linux/compiler/lib/intel64_lin)

Repeat for MIC and IA32

**Comment by amitaga** [comment]
Thanks for reporting the issue. We are looking into it.

**Comment by mahilleb-msft** [comment]
@ldmtwo, as of today, CNTK supports MKL through a CNTK custom MKL library, which should also fix this error. Updated set up instructions are provided here, specifically in the section on "MKL":
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux
(and for Windows here: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows)
 Hope this helps, and please let us know if there's still an issue,

Mark

**Comment by ldmtwo** [comment]
Does this update include MKL based convolutions? See #530 @Alexey-Kamenev, is this the code update you were describing?

**Comment by mahilleb-msft** [comment]
Nope, sorry, not yet. This was basically an update on how we build with MKL. Let me if I can close this issue here.

Thanks, Mark

**Comment by ldmtwo** [comment]
Yes close it please. Thanks for getting this out there 

Sent by LD's TI-84 calculator
