### ISSUE TITLE
EvalClients problem running

### ISSUE THREAD

**Issue by harewei** [Microsoft/CNTK#1010]
I tried using the EvalClients C# solution under Examples/Evaluation (I removed the CPPEvalClient and CPPEvalV2Client since I don't need it for now.

It compiles without problem, but as soon as I run it, it gives me "C:\Users\Andy\Documents\Visual Studio 2013\Projects\Examples\Image\GettingStarted\.\Output\Models\01_OneHidden' not found"
so I went ahead and tried to debug, and changed
`string modelFilePath = Path.Combine(Environment.CurrentDirectory, @".\Output\Models\01_OneHidden");`
to 
`string modelFilePath = Path.Combine(Environment.CurrentDirectory, "01_OneHidden.cntk");`

The program is then able to move down, but at 
`model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: -1);`
it gives "error reading string or missing 0: No error"
so I went and gave in the cntk location directly by changing it to
`model.CreateNetwork(modelFilePath, deviceId: -1);`
Which gives me "Additional information: configparameters: required parameter missing: unknown:modelPath"

Could someone help me with this?

**Comment by zhouwangzw** [comment]
@harewei 01_OneHidden is a pre-trained model which is being used by the sample. Do you have this model trained? If not, you need first to train the model as described in [README.md](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/GettingStarted/README.md). After training, the model file should be placed in the directory expected by the sample, i.e. ..\..\Examples\Image\GettingStarted\Output\Models\01_OneHidden.

For your second question, the parameter to CreateNetwork is the string of network description which contains "modelPath=xxxx" to describe path to the model file, so it does not directly accept the model path as parameter. In addition, the model path has to be specified as a full path. Please see our [troubleshoot](https://github.com/Microsoft/CNTK/wiki/Troubleshoot-CNTK#i-can-build-my-application-using-evaldlllibdll-but-got-the-exception-like-below-when-running) for more information.

Thanks,
Zhou

**Comment by harewei** [comment]
@zhouwangzw oh right, I guess I got confused and though the C# program was meant to do the training as well rather than just evaluating.

Another problem popped up in the CreateNetwork when I now pass in the trained network model, where is says "Read: The model file has a newer format version (15) than this CNTK version can handle (14)."

**Comment by zhouwangzw** [comment]
@harewei  Thanks for reporting the issue. It turns out there is a mismatch of model version between the latest cntk binary and the Eval Nuget package. We will publish a new Nuget package in next few days. Sorry for inconvenience.

**Comment by zhouwangzw** [comment]
@harewei A new version (2.0-beta3) of CNTK Eval Nuget Package has been published, which should resolve your problem. When installing, please select the option "Include Prerelease" in "Manage Nuget Packages".

**Comment by harewei** [comment]
This issue has now been fixed, thanks.
