### ISSUE TITLE
Can't build with VC2015 and CUDA 8.0

### ISSUE THREAD

**Issue by ericmitt** [Microsoft/CNTK#1011]
When the solution will be available for 2015 and CUDA 8.0 ?

**Comment by wolfma61** [comment]
CUDA 8 should be available shortly (next week) as the default build option
as a next step we will move to VS2015, expect another week to iron out the wrinkles with all our dependencies ...

sorry for the delay, a lot of various request piling up ...

**Comment by ericmitt** [comment]
Sound really good! 
I want to add CNTK in the Vcpkg catalog: https://github.com/Microsoft/vcpkg/

**Comment by wolfma61** [comment]
I
