### ISSUE TITLE
how to call custom C++ function

### ISSUE THREAD

**Issue by bklooste** [Microsoft/CNTK#1012]
I couldnt see a forum but if i have a function in a c++ lib i want to use in brain script ,is the only way to add it to cntk and recompile. I see some support for actions. Obv Cpu only.

**Comment by n17s** [comment]
Yes.

**Comment by bklooste** [comment]
Would you accept a pull for this later ? Eg functions that calls another function  CallExternalFunction("dll/soName" ,"functionName" , &TensorView ) ?
CallExternalFunction("dll/soName" ,"functionName" , &float , xdim , ydim ) ?

**Comment by n17s** [comment]
Possibly (the best person to answer this is @chrisbasoglu).

**Comment by bklooste** [comment]
I had a crack at this as i need it and i see support for "Plugin"  via external call is this intended to support brain script node plugins ?  Anyway let me know if you want a pull as the quality would need to be higher than my own prototyping :-)

**Comment by eldakms** [comment]
Please have a look at V2 api, you can extend CNTK using external functions either in python or c++. More information here: https://cntk.ai/pythondocs/extend.html

**Comment by bklooste** [comment]
Any better doco on the C++ side ? I especially wanted the dlopen calls in the framework at it changes builds. I don't use python in my robotic work .

**Comment by bklooste** [comment]
@eldakms  This is awesome ,...I don't use python ( HW) , found the examples hidden in the solution  which are fine for my team.. You should publish this as it allows a lot more to be done and makes the low level framework more extensible. Obviously CPU to GPU transitions are an issue  but if people build a good enough use case that can be improved.,
