### ISSUE TITLE
How to visualize CNN filters?

### ISSUE THREAD

**Issue by kyu899** [Microsoft/CNTK#1013]
Could you please let me know some functions related to visualization of learned CNN filters?

For example, as seen here [http://sklearn-theano.github.io/auto_examples/plot_overfeat_layer1_filters.html](url)
I want to know whether there exist CNTK functions that can fetch weights and biases of filters in k-th layer, like "fetch_overfeat_weights_and_biases" function in Theano in the link above.
Or any tips for visualizing filters are fine. 

Thank you.

**Comment by cha-zhang** [comment]
With Python you can now use Tensorboard to visualize image features: 
https://docs.microsoft.com/en-us/cognitive-toolkit/Using-TensorBoard-for-Visualization
