### ISSUE TITLE
Can not get proper input nodes from C# wrapper

### ISSUE THREAD

**Issue by Worldexe** [Microsoft/CNTK#1014]
I have model built with:
```
message_map = Input((imageW:imageH:1))
features = message_map

type_result = Input(parameterDim)
to_predict = type_result

model = Sequential(
	...
)

p = model(features)
loss_function = CrossEntropyWithSoftmax(to_predict, p)

featureNodes    = (message_map)
labelNodes      = (type_result)
criterionNodes  = (loss_function)
evaluationNodes = (loss_function)
outputNodes     = (to_predict:p)
```

I am using C# wrapper like this:
```
m_cntkModel = new IEvaluateModelManagedF();
m_cntkModel.CreateNetwork(String.Format("modelPath=\"{0}\"", modelFilePath), deviceId: -1);
m_inputDimensions = m_cntkModel.GetNodeDimensions(NodeGroup.Input);
```

I expect to get `message_map` input name in `m_inputDimensions`, but I get `type_result` name instead.
What can be wrong?

I am using CNTK built from sources:
```
Build info:
Built time: Oct  4 2016 15:17:16
Last modified date: Tue Oct  4 15:11:26 2016
Build type: release
Build target: GPU
With 1bit-SGD: yes
Math lib: mkl
CUDA_PATH: /usr/local/cuda-7.5
CUB_PATH: /usr/local/cub-1.4.1
CUDNN_PATH: /usr/local/cudnn-5.1
Build Branch: master
Build SHA1: fcb3095e5f85581b54f8eef2755afefe3b748b4a
Build Path: /home/user/cntk
```
and c# wrapper:
```
1.7.2
```

**Comment by Worldexe** [comment]
Okay, I figured it out.
In `CNTKEval<ElemType>::GetNodeDimensions`, there is:
```
case nodeInput:
	...
	auto& nodes = this->m_net->InputNodes(outputNodes[0]);
```

But, it seems there should be `outputNodes[1]` for my case (because I specified `outputNodes     = (to_predict:p)`.
It seems I will have to reorder thigs in `outputNodes` and rebuild the model.

Anyway, I think this should be handled better in `CNTKEval<ElemType>::GetNodeDimensions`, so Im not closing the ticket.

**Comment by zhouwangzw** [comment]
@Worldexe Yes, this is a limitation in the IEvaluateManaged. If you want to have multiple output nodes, you can use the extended eval interface ModelEvaluationExtended, where you can get all output nodes from GetOutputSchema(). You can find examples in EvaluateExtendedNetworkSingleLayerNoInput() of CSEvalClientTest [here ](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CSEvalClient/Program.cs).

**Comment by Worldexe** [comment]
Got it, thanks.
