### ISSUE TITLE
error LNK1181: cannot open input file 'CNTKlibrary-2.0.lib'

### ISSUE THREAD

**Issue by BennyBlanco22** [Microsoft/CNTK#1015]
I can't build the project. I've cleaned it and closed vs2013 still same issue "error LNK1181: cannot open input file 'CNTKLibrary-2.0.lib'". The projects which are affected "V2LibraryTests" "NetworkTests" "V2LibraryDistributionTests" "CNTK". I've rebuilt it several times still the same issue. Hope somebody can help. These are my only errors when building.

**Comment by kyu899** [comment]
I also went through the same error. The solution is to strictly follow the procedures in [https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows](url). Please make sure that all the required SWs such as Protobuf, MKL, ... are successfully installed.

**Comment by BennyBlanco22** [comment]
ok thanks. I'll try and let you know.

**Comment by raaaar** [comment]
Also, take a look a the Build output, it should tell you exactly what's missing.

**Comment by BennyBlanco22** [comment]
Yes solved it. There was an error while setting up protobuf which I didn't recognize. Thank you
