### ISSUE TITLE
Forum request

### ISSUE THREAD

**Issue by snapo** [Microsoft/CNTK#102]
Hello Microsoft,
First of all i would say thank you, but i have troubles to get a project done but its not a problem from CNTK. So i would ask is there a forum where users can exchange and help each other? Because i think the CNTK Bugtracker is the wrong place ;=)
I could even setup something my own, but i dont want to do cross work....

Best regards

**Comment by wolfma61** [comment]
we are discussing this internally, for now keep using this 'issues' list for any issues, comments, concerns ....

thx
Wolfgang

**Comment by jfslocum** [comment]
Agreed: a forum would be great!

**Comment by wolfma61** [comment]
For now we will keep using 'Issues' here on GitHub and use this as a discussion forum.
We will re-evaluate in a few weeks if we have to many 'open threads' 

thx
Wolfgang
