### ISSUE TITLE
MaxUnpooling not same size as input to MaxPooling (Lack of documentation issue?)

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#1020]
I'm trying to do the inverse operation to MaxPooling (in BrainScript) to create a tensor the same size as the initial one:

e.g. 

```
   # pool  [128 x 256 x 64 x *] -> [64 x 128 x 64 x *]
    poolW = 2
    poolH = 2
    poolhStride = 2
    poolvStride = 2
    pool = MaxPooling(inp, pool3W, pool3H, pool3hStride, pool3vStride, imageLayout = "cudnn")    

    # Upsample #1 (undo pool) 
    # this does [64 x 128 x 64 x *], [128 x 256 x 64 x *] -> [127 x 255 x 64 x *]
   # I.e. not the same size as the original?? 
    us1 = MaxUnpooling(pool,inp, (2:2:1), stride=(2:2:1), )
```

I'm pretty much guessing on the parameters as I can't find any documentation, so I'm probably doing something wrong. An explanation of exactly how MaxUnpooling works would be good. I'd really like to do some other (convolution) stuff before updsampling. Is that ok? I'm a bit confused what it does with the inp variable (does it just use the size, or does it take values from it? if the latter why?).Also, how do I get the output to be 128x256x64?

Thanks a lot!

D.

**Comment by ebarsoumMS** [comment]
Try  us1 = MaxUnpooling(inp, pool (2:2) )

Here MaxUnpooling signature: 
    MaxUnpooling(unpoolInput, poolInput, kernelDims, stride=1, autoPadding = true, lowerPad = 0, upperPad = 0, imageLayout='CHW', tag='')

**Comment by dmagee** [comment]
Thanks, that gives an output of the right size, but:

a) What you've suggested (I added the comma after pool which I assume was missing) seems to have inp, and pool in the opposite order to the signature  unpoolInput, poolInput.

a) The output isn't what I'd expect as I'd expect 2x2 blocks in the output to have the same values, which they don't seem to.

Thanks 

D.

P.S. Using lates binary (1.7.2)

**Comment by dmagee** [comment]
Ok, so I've been investigating this more. I believe the signature is correct (the opposite way round as suggested generates some interesting, but fundamentally incorrect images). Further:

* Unpooling isn't just upsampling I discovered (by reading about it in the docs of another framework, as there is none for cntk). The idea is the pooled image is copied to the max location in the kernel area in the original image. Other output locations (i.e. 3/4 locations in a 2x2 stride) are set to zero. This is why you need the input image (to work out which of the 4 locations to copy the pooled pixel into, not just for the size which can anyway be determined by the stride).

* The reason for the Unpooled image being one pixel smaller in both directions relates (I believe) to padding. Despite there being an autoPadding option I do not believe the MaxUnpooling can be made to reconstruct the invalid rows/columns (I tried with/without padding, 2x2 and 3x3 kernels but cannot generate an image of the original size. This in itself is not a huge problem there is 1 row/column (the first of each .. for 3x3 anyway) that technically you can't calculate the pool (unless you zero pad)  => unpooling requires a special case too which seems buggy/unimplemented. However, just duplicating the first row/column of the Unpool result is no less valid (identical for 2x2 assuming 2x2 is [110 ; 110; 000] not [000 ; 011 ; 011; ] in which case we're talking last row/column).  

* I have (I think) discovered a bug though. While the pooled results are copied to the right 2x2 area I believe the max locations are from the completely wrong part of the input image. Test code:

'''
    pool = Pooling(inp, "max", (3:3:1), stride=(2:2:1), imageLayout = "cudnn", autoPadding = (false:false:false)) 
    
    # swap rgb so can tell we're using pooled pixels, not input pixels
    b = Slice(0,1,pool,axis=3)
    g = Slice(1,2,pool,axis=3)
    r = Slice(2,3,pool,axis=3)
    pool_rgb = Splice(r:g:b,axis=3)
    
    up = MaxUnpooling(pool_rgb, inp, (3:3:1),  stride=(2:2:1), imageLayout = "cudnn", autoPadding = (false:false:false))

'''
Applying this to a largely homogenious image with 3 circles (one red, one green, one blue) the colours are indeed inverted and the pixels are largely on a sparse grid in the correct locations (so mostly what is expected!). However, for a few locations in the form of warped ellipse outlines in completely the wrong place in the image the pixels are offset from the grid by a pixel (values still look ok, just wrong place within 2x2 region. I have a png of this (is that possible to add here??). To my mind this means it is taking the max location from completely the wrong part of the input image (inp).

**Comment by cha-zhang** [comment]
Not sure if this issue is still valid in Python API. And this has been 10 months old. Close it now. Please open a new issue if needed.
