### ISSUE TITLE
Is there a way to use Intel's Python with CNTK

### ISSUE THREAD

**Issue by blair0011** [Microsoft/CNTK#1021]
I am using Intel's distribution of python 3.5 for another project and since it is already installed I would like to just use it instead of having to install another python instance for CNTK. The main problem is that Intel's python has the latest mkl, daal, and TBB libraries already and the installer tries to download older libraries when it doesn't need to. Is there a way to tell the conda installer to skip the mkl install, and just use the existing one?

**Comment by wolfma61** [comment]
We only test/support Anaconda at this time
