### ISSUE TITLE
cannot find -lnvidia-ml

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1022]
In the road building CNTK V2.0, after fixing #1019, I get building error as follow:

>=-----------------------------------------------------------= 
creating /home/aj/CNTK/build/release/lib/libcntkmath.so for Linux with build type release
mpic++  -rdynamic -shared -L/usr/local/cuda-8.0/lib64 -L/usr/local/cudnn-5.1/cuda/lib64 -L/usr/local/CNTKCustomMKL/2/x64/parallel -L/usr/local/lib -L/usr/local/opencv-3.1.0/lib -L/usr/local/opencv-3.1.0/release/lib -L/usr/src/gdk/nvml/lib -Wl,-rpath,'$ORIGIN' -Wl,-rpath,/usr/local/cuda-8.0/lib64 -Wl,-rpath,/usr/local/cudnn-5.1/cuda/lib64 -Wl,-rpath,/usr/local/CNTKCustomMKL/2/x64/parallel -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/local/opencv-3.1.0/lib -Wl,-rpath,/usr/local/opencv-3.1.0/release/lib -o /home/aj/CNTK/build/release/lib/libcntkmath.so /home/aj/CNTK/build/release/.build/Source/Math/BatchNormalizationEngine.o /home/aj/CNTK/build/release/.build/Source/Math/BlockHandlerSSE.o /home/aj/CNTK/build/release/.build/Source/Math/CUDAPageLockedMemAllocator.o /home/aj/CNTK/build/release/.build/Source/Math/CPUMatrix.o /home/aj/CNTK/build/release/.build/Source/Math/CPURNGHandle.o /home/aj/CNTK/build/release/.build/Source/Math/CPUSparseMatrix.o /home/aj/CNTK/build/release/.build/Source/Math/ConvolutionEngine.o /home/aj/CNTK/build/release/.build/Source/Math/MatrixQuantizerImpl.o /home/aj/CNTK/build/release/.build/Source/Math/MatrixQuantizerCPU.o /home/aj/CNTK/build/release/.build/Source/Math/Matrix.o /home/aj/CNTK/build/release/.build/Source/Math/QuantizedMatrix.o /home/aj/CNTK/build/release/.build/Source/Math/DataTransferer.o /home/aj/CNTK/build/release/.build/Source/Math/RNGHandle.o /home/aj/CNTK/build/release/.build/Source/Math/TensorView.o /home/aj/CNTK/build/release/.build/Source/Math/NcclComm.o /home/aj/CNTK/build/release/.build/Source/Math/CuDnnBatchNormalization.o /home/aj/CNTK/build/release/.build/Source/Math/CuDnnCommon.o /home/aj/CNTK/build/release/.build/Source/Math/CuDnnConvolutionEngine.o /home/aj/CNTK/build/release/.build/Source/Math/CuDnnRNN.o /home/aj/CNTK/build/release/.build/Source/Math/GPUDataTransferer.o /home/aj/CNTK/build/release/.build/Source/Math/GPUMatrix.o /home/aj/CNTK/build/release/.build/Source/Math/GPUSparseMatrix.o /home/aj/CNTK/build/release/.build/Source/Math/GPUTensor.o /home/aj/CNTK/build/release/.build/Source/Math/GPUWatcher.o /home/aj/CNTK/build/release/.build/Source/Math/GPURNGHandle.o /home/aj/CNTK/build/release/.build/Source/Math/MatrixQuantizerGPU.o /home/aj/CNTK/build/release/.build/Source/Common/Config.o /home/aj/CNTK/build/release/.build/Source/Common/Globals.o /home/aj/CNTK/build/release/.build/Source/Common/DataReader.o /home/aj/CNTK/build/release/.build/Source/Common/DataWriter.o /home/aj/CNTK/build/release/.build/Source/Common/ExceptionWithCallStack.o /home/aj/CNTK/build/release/.build/Source/Common/Eval.o /home/aj/CNTK/build/release/.build/Source/Common/File.o /home/aj/CNTK/build/release/.build/Source/Common/TimerUtility.o /home/aj/CNTK/build/release/.build/Source/Common/fileutil.o /home/aj/CNTK/build/release/.build/Source/Common/Sequences.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/BlockRandomizer.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/Bundler.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/NoRandomizer.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/ChunkRandomizer.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/SequenceRandomizer.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/SequencePacker.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/TruncatedBpttPacker.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/PackerBase.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/FramePacker.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/ReaderBase.o /home/aj/CNTK/build/release/.build/Source/Readers/ReaderLib/ChunkCache.o -lcublas -lcudart -lcuda -lcurand -lcusparse -lnvidia-ml -lcudnn -lm -lmkl_cntk_p -liomp5 -lpthread -fopenmp
/usr/bin/ld: cannot find -lnvidia-ml
collect2: error: ld returned 1 exit status
make[1]: *** [/home/aj/CNTK/build/release/lib/libcntkmath.so] Error 1
make[1]: Leaving directory `/home/aj/CNTK'
make: *** [all] Error 2

how could I install nvidia-ml??

**Comment by mfuntowicz** [comment]
Hi hajix,  

When using Cuda,  Nvidia-ml should be located in (assuming Cuda installed in /usr/local/cuda) /usr/local/cuda/lib64/stubs. 

You need to append this Dir to the LD_LIBRARY_PATH and it should works.

Hope it helps, 
Morgan

**Comment by hajix** [comment]
Hi mfuntowicz;

True, I have libnvidia-ml in **/usr/local/cuda/lib64/stubs**. I also locate them, and it exists in the following paths too:

> /usr/lib/nvidia-367/libnvidia-ml.so
/usr/lib/nvidia-367/libnvidia-ml.so.1
/usr/lib/nvidia-367/libnvidia-ml.so.367.57
/usr/lib32/nvidia-367/libnvidia-ml.so
/usr/lib32/nvidia-367/libnvidia-ml.so.1
/usr/lib32/nvidia-367/libnvidia-ml.so.367.57
/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs/libnvidia-ml.so

I check gdk_nvml_lib_path. It was pointing to somewhere doesn't exist!! So I make it point to **/usr/local/cuda/lib64/stubs**. It solved the problem.

thank you so much mfuntowicz.
