### ISSUE TITLE
Is there a way to use FastRCNN with Ubuntu

### ISSUE THREAD

**Issue by rickkkk** [Microsoft/CNTK#1024]
I am using Ubuntu 14.04 and wants to use the fastRCNN example. But there are only the libs for Windows (cython_bbox.pyd and cython_nms.pyd). 
Is there a way to compile these libs for Ubuntu/ Linux?

**Comment by pkranen** [comment]
These are build from the original Fast R-CNN sources at [https://github.com/rbgirshick/fast-rcnn](https://github.com/rbgirshick/fast-rcnn) (see '3.Build the Cython modules' in the main Readme there).
