### ISSUE TITLE
How to get activation values while evaluation

### ISSUE THREAD

**Issue by dx80232** [Microsoft/CNTK#1025]
Now I would like to get the activation values for using.
Therefore, I work on modifying the _Evaluate_ in class _SimpleEvaluator_ so that I can get them while evaluation.
And I guess that after _ForwardProp_ of every mini-batch, these values will be stored in evalNodes.
But I just find it hard to actually get them.
Is there any insight about how to modify _Evaluate_ to get the activation values?
Thanks

**Comment by cha-zhang** [comment]
I assume you are evaluating features. Here is a brief example in Python: 
https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Evaluate-models-in-Python
