### ISSUE TITLE
bug Clip()?

### ISSUE THREAD

**Issue by hspark84** [Microsoft/CNTK#1026]
I tried to use clip function like y = clip(x, 0, 1), x is a column vector sequence.  However, when I checked the maximum value by ReduceMax(y), it returned the maximum value bigger than 1. I replace the clip function by ReLU(-ReLU(-x+1)+1). And I got the maximum value lower than 1. Is there a bug on Clip() function?

My CNTK version is 2.0.beta3.0+

**Comment by cha-zhang** [comment]
This should have been fixed by now. If issue remains, please open a new issue. Thanks!

**Comment by xforceco** [comment]
which version is the fix applied? My CNTK 2.1 does not seem working.
