### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by GuruMulay** [Microsoft/CNTK#1027]
This is more of a minor issue/suggestion/modification in the documentation pages. For instance, you might wanna update the version of .whl package (from beta1.0 to beta3.0) under "Step 3:  Install CNTK" on [this](https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Manual) page. It might help in avoiding unnecessary version comparability issues in future for users. Same goes for [https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Manual](url). I apologize, but I thought raising issue would be quicker than making PULL requests and changing in READMEs. :-)

**Comment by n17s** [comment]
Updated. Thanks!

**Comment by wolfma61** [comment]
Thanks for pointing these out ... we add them to list of required updates with a release ... somehow slipped through the cracks
