### ISSUE TITLE
Adding a couple of simple c++ samples

### ISSUE THREAD

**Issue by pisiiki** [Microsoft/CNTK#1028]
It would be nice to include some basic examples in C++. Figuring out how to build a network, train the model or how to run it with the current documentation or by looking at the cntk solution is quite difficult at the moment.

Regards.

**Comment by n17s** [comment]
You mean something more than [this](https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/V2LibraryTests/CifarResNet.cpp) and the other files in the same folder?

**Comment by arijit17** [comment]
Probably location and/or naming of the folders are confusing for someone new to figure out the examples?

**Comment by pisiiki** [comment]
Yes, I meant that. That will do the job. Thanks.

**Comment by n17s** [comment]
Regarding location/naming: this API will always be functional but low level. The "official" one, whenever we get to it will be more convenient. Thus this is not advertised.

**Comment by pisiiki** [comment]
So there is a higher level API for C++ in the works?

**Comment by n17s** [comment]
There is a plan for one. Don't be blocked on it though. If you want to get things done in C++ for the next few months, the low level API is the way to go.
