### ISSUE TITLE
A Forum for CNTK related help and discussion

### ISSUE THREAD

**Issue by datavizweb** [Microsoft/CNTK#1029]
Github issues are for raising issues related to Code, feature request, reporting bugs etc. Most of the issues reported now are more of help. Is there any official forum where in CNTK users can request for help and CNTK developers and expert users can offer help ?. What I feel is, there is lack of community support for CNTK which is determinant to the `CNTK's growth and acceptance.`

**Comment by arijit17** [comment]
Fully agree. We need a mailing list for getting help from expert users quickly.

**Comment by mfuntowicz** [comment]
Maybe I can take advantage of StackOverflow, using a the tag "cntk" ?

**Comment by arijit17** [comment]
Hi all!

For general discussions and ideas for improvement, I would really like a CNTK mailing list. This list would be for general discussions about CNTK development and directions.

Anyone willing to take the initiative to start that? 

Bugs, issues, etc. related to the CNTK codebase should be reported on GitHub as usual.

**Comment by omarx21** [comment]
I started a Google Group that is general purpose for different packages.  I'm hesitant to make it specific to any single product because I don't have any association with any of these companies.  If there's a better way to deal with these issues, please let me know. 

https://groups.google.com/forum/#!forum/machine-learning-software

**Comment by davidarh** [comment]
Hello,

Does anyone have an example of how to implement a leaky RELU activation function in python?  Thanks.  I found this example for brain script: LeakyReLU (x) = 0.1 * x + 0.9 * ReLU (x)

**Comment by wolfma61** [comment]
On this documentation page we list feedback chanels: 
https://review.docs.microsoft.com/en-us/cognitive-toolkit/feedback-channels

In addition a [Gitter Chat](https://gitter.im/Microsoft/CNTK) can be used for general questions and shorter programming questions.
The doc page will be updated to reflect this additional information

@davidarh - that question seems unrelated to the discussion. If it is still relevant, please ask the question on Stackoverflow

thx
Wolfgang
