### ISSUE TITLE
No examples for DSSM-related modules.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#103]
I wish there were examples utilizing the `DSSMReader` class.
I see `DSSMReader`, but not `DSSMWriter` or `DSSMConverter`. How can I get my data in?
I see the `CosDistanceWithNegativeSamples` function, but it generates the negative samples via shifts while I want to implement a classical DSSM net where I supply the concrete negative samples.

**Comment by mradmila** [comment]
A new example will be checked in a few weeks from now. Thanks for reporting it.
