### ISSUE TITLE
FeatureMVNLayer parameters

### ISSUE THREAD

**Issue by hspark84** [Microsoft/CNTK#1031]
Can I write down the mean and standard deviation parameter of FeatureMVNLayer{} into textfile?

When I get the normalized output feature from network, I want to change the normalized output to unnormalized one by using the mean and standard deviation.

**Comment by cha-zhang** [comment]
In python you can access the layer parameters: 
https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Read-Things-in-Python 

Closing this issue since it's been very old.
