### ISSUE TITLE
how to wirte output result in every epoch?

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#1033]
I want to write output in every epoch
but I cant find some hint
if you know tell me please

**Comment by datavizweb** [comment]
[EvalNode](https://github.com/Microsoft/CNTK/wiki/Special-Nodes) is called for end of every epoch. That can be used to trigger a function, but not sure hot to trigger write action from it. Should be easy with python API.

**Comment by Eomtaesan** [comment]
@datavizweb 


Um I make this write section,


Write=[
    action="write"
    modelpath="$ModelDir$/Spc"
    outputPath="$OutputDir$/Spc"
    outputNodeNames = outputnodes.z
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/Test.txt"
        input = [
            features = [
                dim = 50000
                format = "dense"
            ]
            labels = [
                dim = 1000
                format = "dense"
            ]
        ]
    ]
    format = [
        type = "real"
    ]  
]


And I refer VGG net cntk file & ndl file.


AddTop5Eval=[    
    action="edit"
    CurModel="$ModelDir$/VGG_A"
    NewModel="$ModelDir$/VGG_A.Top5"
    editPath="$ConfigDir$/CreateEvalModel.mel"
]
CE = CrossEntropyWithSoftmax(labels, ol, tag = Criteria)
Err = ClassificationError(labels, ol, tag = Eval)
OutputNodes = ol


I understand your comment as this : the command tag=eval is sending to AddTop5Eval in every epoch.
If I add writer node to eval node, then outputnode.z file will be made in every epoch?????

**Comment by eldakms** [comment]
Please try out v2 API, there you are able to control the minibatch loop explicitly and perform any type of validation/output at the end of the epoch. Closing the issue for now, please feel free to reopen. Thanks!

**Comment by xforceco** [comment]
Please give an example on how to accomplish this
I cannot find any documentation on output after each epoch in CNTK2
