### ISSUE TITLE
Can I use a seed value to generate same weight initialization? 

### ISSUE THREAD

**Issue by chhyun** [Microsoft/CNTK#1034]
Hello there
I'm using CNTK new version (2.0) and I wonder if I can use a seed value.
Cause I need to compare many experimental results on various parameter values for getting optimal network structure.

Is there a way?

**Comment by n17s** [comment]
Yes. See here 
https://github.com/Microsoft/CNTK/wiki/Parameters-And-Constants
(search for randomSeed)
Also, all other randomization that happen in CNTK (e.g. shuffling the dataset) is always using the same seed.
