### ISSUE TITLE
Print version info as part of Build info output

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#1036]
It would be helpful to have a build version info (same notation as used for marking releases. E.g. 'Build number: 2.0.0.1589') as part of 'Build info' output. We store this info along with our results - for future troubleshooting/reproducting purposes.
Currently the only piece of information the identifies version used is the build hash ('Build SHA1') - but one would need to cross check this with all versions to find out which version release  is the one used.

**Comment by junjieqian** [comment]
We have something similar defined already, and the output is like

    Build info: 
    **Built time: Nov 14 2016 23:50:45**
    **Last modified date: Mon Nov 14 20:21:09 2016**
    Build type: release
    Build target: GPU 
    With 1bit-SGD: no
    With ASGD: yes
    Math lib: mkl
    CUDA_PATH: /usr/local/cuda-7.5
    CUB_PATH: /usr/local/cub-1.4.1
    CUDNN_PATH: /usr/local/cudnn-5.1
    Build Branch: HEAD
    **Build SHA1: 6be43ec454b99caa99d51ae366afb2f67563b1fa**

And it is defined in https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/CNTK.cpp#L393.

**Comment by junjieqian** [comment]
The version information is included in the banner info, see [code](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/CNTK.cpp#L648). Because we are using release branches for different versions, it is hard to get the `version` number in master branch.

**Comment by jakrivan** [comment]
Understood. Currently added info is still very helpful - Tahnks!
