### ISSUE TITLE
Getting stuck at manual installation

### ISSUE THREAD

**Issue by floAr** [Microsoft/CNTK#1040]
Somehow I get stuck at Step 3 of the manual installation. I verified Anaconda set up a python 3.4.4 env but still get the 'wheel not supported' error.

```
C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts>activate C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34

(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34) C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts> pip install c:\local\cntk\cntk\python\cntk-2.0.beta3.0-cp34-cp34m-win_amd64.whl
cntk-2.0.beta3.0-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by wolfma61** [comment]
Hi 

you did a install from binary using the script?
you activated then the anaconda environment with the cntk-py34.bat file?
I assume you did not compile from source code?
if you type "pip --version" in the activated environment, what is the output?
something like this?
pip 8.1.2 from C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages (python 3.4)

thx
Wolfgang

**Comment by n17s** [comment]
You are probably picking up the wrong pip version because you are executing this in the Scripts directory of Anaconda. Move to a different directory so that the correct pip is not shadowed by a wrong pip.

**Comment by floAr** [comment]
@n17s assumption was correct. The pip --version noted python 3.5 as long as i was in the anaconda folder. cd'ing out of it resolved the issue and I was able install. 
Thanks for the quick help!

**Comment by huatianyao** [comment]
I met the same problem, but thanks to @n17s' correct assumption, I installed it successfully finally. Thanks for the help!
