### ISSUE TITLE
How to do simple 2D convolution with a constant 2D kernel

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#1042]
I want to do a simple convolution of a stack of 2D f-maps with a constant 2D kernel (e.g. [1 1 1; 1 1 1 ; 1 1 1] for averaging. The following brainscript code compiles:

    W = Constant(1,rows=3, cols=3) 
    c = Convolution(W, samesize, (3:3:1), mapDims=1, stride = (1:1:1), autoPadding=(true:true:false), sharing = (true:true:true), imageLayout = "cudnn")

and seemingly the convolution output is the right size/shape, but I get the error:

EXCEPTION occurred: cuDNN could not find suitable algorithm for the current convolution configuration.

I get the same issue if I try to do the same thing with a learnable parameter as the weight. I also tried mapDims=# fmaps (which seemed more logical to me) and that increased the number of fmaps. 3D learnable weights (Ii.e. each output is a function of all inputs) seem to work, but not this simpler case. Is it possible? If so how?

Thanks

D.

P.S. Using latest binary (1.7.2) on windows

**Comment by n17s** [comment]
Can you try
W=ConstantTensor(1, (3:3:1)) 
and let us know if it works?

**Comment by dmagee** [comment]
No, same error (also tried latest version compiled from code about 1 or two weeks ago):

EXCEPTION occurred: cuDNN could not find suitable algorithm for the current convolution configuration.

**Comment by cha-zhang** [comment]
Do you need to do reduction across the feature maps after your convolution?

**Comment by cha-zhang** [comment]
I assume you don't want to do reduction. Check the example here: 
https://github.com/Microsoft/CNTK/blob/chazhang/alexnet/Examples/Image/Classification/ConvNet/BrainScript/ConvNetLRN_CIFAR10_DataAug.cntk

**Comment by dmagee** [comment]
Thanks Cha! So to do a 2D convolution on a stack of 2D f-maps you convert the stack into a stack of 1 x 3D F-maps and do a 3D convolution using a 2D kernel. Not exactly intuative, but it seems to work. For the benefit of others:

    # reshape to insert a fake singleton reduction dimension after the 3rd axis
    inp_fake = SplitDimension(inp, 3, 1) 
    
    # Arbitrary 3x3 2D kernel
    W = ParameterTensor{(3:3:1:1), learningRateMultiplier = 0, initFromLiteral = '1 1 1
                                                                                  1 1 1
                                                                                  1 1 1'}
    c1 = Convolution (W, inp_fake, (3:3:1), mapDims = 1, stride = 1, sharing = true, autoPadding = true, lowerPad = 0, upperPad = 0, transpose = false, maxTempMemSizeInSamples = 0)
    
    # reshape back to remove the fake singleton reduction dimension
    c = FlattenDimensions(c1, 3, 2)  

I'm not sure the weights should be (1:3:3:1) - (is the first or last the output dimension?), but I don't think it matters in this case as (I think) ParameterTensors are stored as a 1D array anyway and resized to the shape needed (I may be wrong). It works anyway.

Thanks

Derek

**Comment by cha-zhang** [comment]
The reason for the fake dimension is by default Convolution does a reduction along the axis before the minibatch axis (accross the feature maps). In order to make sure there is no reduction, thus the feature map stay the same size, I need to insert a fake dimension. 

(3:3:1:1) is correct. It's W:H:C:K. 

I'm working to allow Convolution without reduction. Once that is done, there will be no need to insert the fake dimension.
