### ISSUE TITLE
Regression problem using Python API

### ISSUE THREAD

**Issue by alipacificfrase** [Microsoft/CNTK#1044]
I am junior in CNTK, so I could not do the regression task. 
First of all, i could not find any example about regression by Python using CNTK. If you know any available example I will appreciate your kind help.
Second, I tried to change one of the examples as the regression but it does not work. Any Idea about this code? what is the problem. 
########################  Main Code using Python  
import math
import numpy as np
from cntk.blocks import default_options, LSTM, Placeholder, Input        # building blocks
from cntk.layers import Embedding, Recurrence, Dense, BatchNormalization # layers
from cntk.models import Sequential                                       # higher level things
from cntk.utils import ProgressPrinter, log_number_of_parameters
from cntk.io import MinibatchSource, CTFDeserializer
from cntk.io import StreamDef, StreamDefs, INFINITELY_REPEAT, FULL_DATA_SWEEP
from cntk import future_value, combine, Trainer, cross_entropy_with_softmax, classification_error, splice
from cntk.learner import adam_sgd, learning_rate_schedule
import cntk.ops as OPT

########################### create model 2 ####################################
def create_model2():
    with default_options(initial_state=0.1):
        return Sequential([
            Dense(3),
            Recurrence(LSTM(10), go_backwards=False),
            Dense(1)
        ])
        
        

model2 = create_model2()
print(len(model2.layers))
print(model2.layers[0].W.shape)
print(model2.layers[2].b.value)

##################################  create_reader2   #################################
def create_reader2(path):
    return MinibatchSource(CTFDeserializer(path, StreamDefs(
         query         = StreamDef(field='X', shape=3,  is_sparse=False),
         slot_labels   = StreamDef(field='Y', shape=1,  is_sparse=False)
     )), randomize=False, epoch_size = INFINITELY_REPEAT)
    
    

reader2 = create_reader2("TrainData.txt")
reader2.streams.keys()
#
#################################### Train2 ################################## 
 
def train2(reader2, model2, max_epochs=16):
    
    labels = Placeholder()
    mserr   = OPT.squared_error (model2, labels)
       
    # training config
    epoch_size = 1000        # 18000 samples is half the dataset size 
    minibatch_size = 5
    
    lr_per_sample = [0.003]*4+[0.0015]*24+[0.0003]
    lr_schedule = learning_rate_schedule(lr_per_sample, units=epoch_size)
    
    # Momentum (could also be on a schedule)
    momentum_as_time_constant = 700
    
    learner = adam_sgd(mserr,
                       lr_per_sample=lr_schedule, momentum_time_constant=momentum_as_time_constant,
                       low_memory=True,
                       gradient_clipping_threshold_per_sample=15, gradient_clipping_with_truncation=True)

    # trainer
    trainer = Trainer(model2,mserr, learner)

    # process minibatches and perform model training
    log_number_of_parameters(model2)
    progress_printer = ProgressPrinter(tag='Training')
    #progress_printer = ProgressPrinter(freq=100, first=10, tag='Training') # more detailed logging

    t = 0
    for epoch in range(max_epochs):         # loop over epochs
        epoch_end = (epoch+1) * epoch_size
        while t < epoch_end:                # loop over minibatches on the epoch
            data = reader2.next_minibatch(minibatch_size)
            trainer.train_minibatch(data)                                     # update model with it
            t += data[mserr].num_samples                     # samples so far
            progress_printer.update_with_trainer(trainer, with_metric=True)   # log progress
        loss, metric, actual_samples = progress_printer.epoch_summary(with_metric=True)

    return loss, metric
################################################   do_train 
    
def do_train2():
    global model2
    model2 = create_model2()
    reader2 = create_reader2("TrainData.txt")
    train2(reader2, model2)
do_train2()

##########################################################################################################    Sample of TrainDataset.txt file

0 |X 0.0456606 0.0456606 0.0456606  |Y 0.052785
1 |X 0.0456606 0.0456606 0.052785  |Y 0.048899
2 |X 0.0456606 0.052785 0.048899  |Y 0.0385363
3 |X 0.052785 0.048899 0.0385363  |Y 0.0346503
4 |X 0.048899 0.0385363 0.0346503  |Y 0.0349741
5 |X 0.0385363 0.0346503 0.0349741  |Y 0.0349741
6 |X 0.0346503 0.0349741 0.0349741  |Y 0.0349741
7 |X 0.0349741 0.0349741 0.0349741  |Y 0.0372409
8 |X 0.0349741 0.0349741 0.0372409  |Y 0.0310881
9 |X 0.0349741 0.0372409 0.0310881  |Y 0.0249352

**Comment by n17s** [comment]
Can you be more specific on "it does not work"? An exception is raised? No exception is raised but diverges when training? No exception is raised but does loss does not decrease?

How was the data generated?

**Comment by alipacificfrase** [comment]
Thank you Dr. Nikos for you reply.
I run line be line to find the error, after running the bellow code..
 learner = adam_sgd(mserr,
                       lr_per_sample=lr_schedule, momentum_time_constant=momentum_as_time_constant,
                       low_memory=True,
                       gradient_clipping_threshold_per_sample=15, gradient_clipping_with_truncation=True)

The error is ....
"  File "<ipython-input-6-9ee63e435be6>", line 4, in <module>
    gradient_clipping_threshold_per_sample=15, gradient_clipping_with_truncation=True)

  File "c:\local\anaconda3-4.1.1-windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\learner.py", line 446, in adam_sgd
    gradient_clipping_with_truncation=gradient_clipping_with_truncation)

  File "c:\local\anaconda3-4.1.1-windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\utils\swig_helper.py", line 52, in wrapper
    result = f(*args, **kwds)

  File "c:\local\anaconda3-4.1.1-windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\learner.py", line 431, in fsadagrad
    varianceMomentum, additional_options)

RuntimeError: vector<T> too long "


Data is generated using Python,  data related to  a time series prices to predict the price. So, bellow is the code....
def saveToTxtFile(filename,trainX,look_back,trainY ):
    
   f = open(filename, 'w')
   for i in range(0,len(trainX)):
       f.write( str(i)+'   |X   ' )
       for j in range(0, look_back):
           f.write( str(trainX[i,j])+'  ' )
       f.write('  |Y  '+ str(trainY[i]))       
       f.write('\n')
   f.close()

**Comment by n17s** [comment]
I see.
While we are in beta, you should expect some breaking changes. 
As you can see here:
https://github.com/Microsoft/CNTK/blob/master/Examples/LanguageUnderstanding/ATIS/Python/LanguageUnderstanding.py#L77
momentum has to be passed in adam_sgd using momentum_as_time_constant_schedule()

If you get any other errors like that make sure you are using the latest beta version and you follow the same patterns as in the examples.

**Comment by alipacificfrase** [comment]
Thank you.
