### ISSUE TITLE
Support converting between sparse and dense

### ISSUE THREAD

**Issue by cmarschner** [Microsoft/CNTK#1046]
There are different situations when it is not clear whether the output of an operation should be in sparse or dense format. CNTK should allow one to specify this.
Proposal:

1. Implement a conversion operator that one uses to specify the desired tensor format. This would create a copy of the input for the time being.
2. In a later stage, use graph optimization and turn that conversion operator into a directive for the calling operator. If that operator then supports, e.g. outputting sparse, it could do this without going through the conversion step.

As for the operator itself, given that the end goal is supposed to be a hint, it should look similar to a data type declaration. In the end this could look like

`   A .* B   >>  As(format="dense")`

Or in other words,  `As(ElementTimes(A, B), format="dense")`
The operator could then also be used to indicate other hints, like quantization, index vectors and the like.

**Comment by cmarschner** [comment]
Also add an option for the gradient:
`As(gradientFormat="dense")`
The two could also be combined:
`As(format="sparse", gradientFormat="dense")`
At least one of them is mandatory.

**Comment by loripino21** [comment]
Why this has been closed?
Has it already been implemented?
