### ISSUE TITLE
Python:CNTK model is not recognized if I run python code other than $CNTK_HOME/bindings/python

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#1051]
I installed CNTK v2 as explained in instrunction and Tutorial example successfully ran as well.

My issue on python is that if I run on $CNTK_HOME/bindings/python, there is no problem. If I move to other directory, python cannot recognize location of CNTK python packages. 

I already set followings:

```
cd bindings/python
export PYTHONPATH=$PWD/bindings/python:$PYTHONPATH
export LD_LIBRARY_PATH=$PWD/cntk/libs:$LD_LIBRARY_PATH
```

I guess some sub directories inside bindings/python are needed for importing python but not sure. Could you give me some advice on this?

**Comment by n17s** [comment]
PYTHONPATH should contain the [cntk repo]/bindings/python directory but the way you set it seems to point to [cntk repo]/bindings/python/bindings/python
You can probably verify this with 
echo $PYTHONPATH 

Try this instead:
cd bindings/python
export PYTHONPATH=$PWD:$PYTHONPATH
export LD_LIBRARY_PATH=$PWD/cntk/libs:$LD_LIBRARY_PATH

**Comment by funguy74** [comment]
Thanks for your comment. I used path setting exactly described in setup page of CNTK, which apparently had bugs. Thanks for pointing out that and now, I can run python at any other place.
