### ISSUE TITLE
Remove block sparse type in backprop to A in Times(sparse A, B)

### ISSUE THREAD

**Issue by cmarschner** [Microsoft/CNTK#1054]
Block sparse is not supported in other places, and also doesn't follow the standard block sparse type. Hence the gradient is practically useless. Change this to CSC.

**Comment by frankseide** [comment]
This was the first implementation. It was found that the custom block representation is significantly more performant. Maybe libraries have improved by now, I'd love to get rid of this non-standard format.

**Comment by KeDengMS** [comment]
Block sparse is mainly to address sparse gradient aggregation for embeddings. What we really need is gather/scatter with index, and furthermore aggregation in distributed training

**Comment by KeDengMS** [comment]
Block sparse is very useful in backprop for gradient of big embedding matrix, and is more efficient for aggregation in distributed training. We should push it to be part of standard sparse matrix instead of removing it from CNTK.
