### ISSUE TITLE
Dockerfile missing a critical command

### ISSUE THREAD

**Issue by TheNetAdmin** [Microsoft/CNTK#1056]
In file Tools/docker/CNTK-GPU-Image/Dockerfile, line150
After `RUN git clone --depth=1 -b master https://github.com/Microsoft/CNTK.git . && \`
and before `git submodule update --init Source/Multiverso && \`
there should be a command like `cd CNTK`
or `git submodule update` will complain `fatal: Not a git repository (or any of the parent directories): .git`

**Comment by TheNetAdmin** [comment]
Sorry, my bad...
I haven't noticed the repo is cloned into current folder.
The latter command `git submodule ...` won't work on my machine due to some network issues, not the `cd CNTK` issue, the Dockerfile should work fine without this command.

**Comment by mahilleb-msft** [comment]
@TheNetAdmin  - I hope the network issue doesn't persist anymore? If no, can you tell us, which submodule is causing problems?

If everything works, we can probably close this here :)

Thanks, Mark

**Comment by TheNetAdmin** [comment]
Every problem during building is solved, thanks very much.

**Comment by mahilleb-msft** [comment]
Great, closing.
