### ISSUE TITLE
Install forces Anaconda into a folder named local

### ISSUE THREAD

**Issue by gue22** [Microsoft/CNTK#1057]
I found it more intuitive to keep the "cntk" name of the root folder of the zip of the Windows (b3) binary -- instead of renaming it to "local" which led to a minor consistency issue:
If one decides to go with C:\cntk (instead of C:\local) then the Anaconda install is forced into C:\local as the only folder, which is quite unelegant.

And: Contrary to  [documentation](https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script) the install.ps1 file is not in c:\local\cntk\Scripts\windows (if you named the thing local (instead of cntk)), but in c:\local\Scripts\windows, i.e. in a different part of the tree.

Thanks for providing what seems to be a viable TensorFlow alternative! ;-)
Cudos to Frank Seide´s talk which converted me!
G.

**Comment by wolfma61** [comment]
@gue22 
the script you found in the location is in the subdirectory Scripts\windows, which is part of the subdirectory cntk in the binary download (zip) file. I think it depends on how you 'unpack' the zip file

if you call the script file in powershell with 'get-help .\install.ps1 -full' you will see parameters which can be supplied to the install script. One of the parameters allows you to specify the location of the Anaconda install, ie., 

PS C:\>.\install.ps1 -Execute -AnacondaBasePath d:\cntkBeta                                                                         This will install Anaconda in the [d:\cntkBeta] directory.                                  


thx
Wolfgang

**Comment by gue22** [comment]
Thanks for the pointer to the AnacondaBasePath parameter. (So much to learn! ;-)
Guess a seemingly superfluous dir hierarchy or a bit dubious A. default too minor to follow up.

G.
