### ISSUE TITLE
Examples using multiple inputs for CNN and ImageReader?

### ISSUE THREAD

**Issue by markcraw** [Microsoft/CNTK#106]
Thanks for the toolkit!  Are there any examples showing how to load multiple inputs via the ImageReader for use in a CNN?

**Comment by dtmoodie** [comment]
Hi, I'm looking into the same thing, and unfortunately it doesn't look like it is supported.
I'm currently looking at the ImageReader data input plugin and from ImageConfigHelper.cpp line 38, it's pretty clear that only one input feature and one label is supported.
Furthermore from TrainActions.cpp line 158 it is pretty clear that only one reader object is allowed.

I'm trying to figure out what it would require to update ImageReader to support multiple files on a single line.  Any input on this would be great though.

**Comment by Ark-kun** [comment]
I think you can use multiple readers, but this is hacky right now. And think that random shuffling will desync the rows.
Here is how you can try to use multiple readers/inputs:
```
    reader # Prevent CNTK crash

    reader1 = [
        readerType = Bla1
        ...
        features1 = [ ... ]
    ]
    reader2 = [
        readerType = Bla2
        ...
        features2 = [ ... ]
    ]

    readers = (reader1, reader2) # 

```

**Comment by eldakms** [comment]
Hi,

Currently this is not yet supported. We are working on new readers that would allow you to combine several streams of input (not only different streams of images), but it is not yet there.
Thanks!

**Comment by dmagee** [comment]
I'm thinking about similar problems, One option might be to concatinate multiple signals (e.g. multiple images along the row) externally and then separate them once loaded. I noticed there is a RowStack() function to stack rows. I'm guessing there may be a method to extract a subset of rows also? (I've not found it yet though). With these and TransposeDimension() there is probably quite a lot of fllexibility already?

**Comment by dmagee** [comment]
To follow that up the command to extract a sub-signal is RowSlice( s t a r t R o w , numRows , matrix).
