### ISSUE TITLE
ImportError: No module named 'cntk'

### ISSUE THREAD

**Issue by NoSuchBoyException** [Microsoft/CNTK#1060]
hi, i install CNTK using the **manual** way in **windows 7**
and in 'Step 5 Verify the setup from Python', i got this issue **ImportError: No module named 'cntk'**

my system path like this:
PYTHONPATH: f:\Software\CNTK\bindings\python\examples
Path: c:\local\cntk\cntk;%PYTHONPATH%;

please help me know where i wrong, thx.

**Comment by NoSuchBoyException** [comment]
BTW, i googled and read the same issue opened here, **but no help.**

**Comment by cha-zhang** [comment]
PYTHONPATH should be f:\Software\CNTK\bindings\python?

**Comment by NoSuchBoyException** [comment]
i set the PYTHONPATH as the install guide said.i think it's not f:\Software\CNTK\bindings\python.
anyway, my solution is reinstall the os from win7 to win10, and i successfully install the CNTK.
hope is helpful to other guys meet this problem.
