### ISSUE TITLE
Test failed for CNTK in docker

### ISSUE THREAD

**Issue by TheNetAdmin** [Microsoft/CNTK#1061]
I've built a CNTK image in the docker-windows (on windows10), it finished with this 
```
Successfully built 1277d9f5a567
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```
But when I use `docker run --rm cntk nvidia-smi` to test it, it gives me an error 
```
docker: Error response from daemon: oci runtime error: exec: "nvidia-smi": executable file not found in $PATH.
```
I'm not sure how to deal with this.
And here is the images after build
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
cntk                latest              1277d9f5a567        About an hour ago   15.8 GB
nvidia/cuda         7.5-cudnn5-devel    886fbf107999        4 weeks ago         1.35 GB
```

**Comment by mahilleb-msft** [comment]
Hey @TheNetAdmin, can you try building and running the CPU-only image?
Docker on Windows doesn't support exposing GPU into the container (like nvidia-docker on Linux).

**Comment by mahilleb-msft** [comment]
@TheNetAdmin - I'm closing this for now, please re-open if there's an update (or open a new image).

Thanks, Mark
