### ISSUE TITLE
Some Python Examples are broken (specifically the learner!)

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#1062]
Dear friends and developers of CNTK:

I was reading Python examples given here:
https://github.com/Microsoft/CNTK/tree/master/Tutorials 

All the Python Examples work, except the following ones:
1. CNTK_101_LogisticRegression.ipynb
2. CNTK_102_FeedForward.ipynb
3. CNTK_103B_MNIST_FeedForwardNetwork.ipynb

I’m using Windows 10, built CNTK from source (day before yesterday) using VS 2013 using methods exactly as described here: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows

Other details:
CNTK_PY34_PATH C:\Users\abisw\AppData\Local\Continuum\Anaconda3\envs\cntk-py34
PYTHONPATH C:\src\cntk\bindings\python\;%PYTHONPATH%
SWIG_PATH C:\local\swigwin

Errors are exactly the same in all the cases, mentioned in #1058

-```
--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-78dcd8830e76> in <module>()
      1 # Instantiate the trainer object to drive the model training
      2 learning_rate = 0.02
----> 3 learner = sgd(z.parameters, lr=learning_rate)
      4 trainer = Trainer(z, loss, eval_error, [learner])

C:\src\cntk\bindings\python\cntk\utils\swig_helper.py in wrapper(*args, **kwds)
     54     @wraps(f)
     55     def wrapper(*args, **kwds):
---> 56         result = f(*args, **kwds)
     57         map_if_possible(result)
     58         return result

C:\src\cntk\bindings\python\cntk\learner.py in sgd(parameters, lr, l1_regularization_weight, l2_regularization_weight, gaussian_noise_injection_std_dev, gradient_clipping_threshold_per_sample, gradient_clipping_with_truncation)
    330         Networks: Tricks of the Trade: Springer, 2012.
    331     '''
--> 332     _verify_learning_rate_type(lr)
    333     gaussian_noise_injection_std_dev = \
    334         training_parameter_schedule(gaussian_noise_injection_std_dev, UnitType.minibatch)

C:\src\cntk\bindings\python\cntk\learner.py in _verify_learning_rate_type(learning_rate)
     62                          'learning_rate must be a training schedule '
     63                          '(output of learning_rate_schedule() function)'
---> 64                          % type(learning_rate))
     65 
     66 # an internal method to verify that the mometum schedule

ValueError: learning_rate type (<class 'float'>) not supported. learning_rate must be a training schedule (output of learning_rate_schedule() function)

```

Can someone please fix the issue or hint me at some workaround so that I finish looking into the Python examples?

Best Regards,
Arijit

**Comment by arijit17** [comment]
#1058

**Comment by wolfma61** [comment]
Thank you -
we are in the process of preparing beta4 and that should be available shortly.  one of the last steps right now is verifying  and adjusting the notebooks to some changes in functionality, as well as the location of some of the samples/turorials etc.

one clarification: did you build CNTK yourself or did you do the binary install?

thx
Wolfgang

**Comment by arijit17** [comment]
Hi Wolfgang:

Thank you.
Yes, I built it myself around 3-4 days ago.
BUT, I did a fresh check-out again today, built it myself again, and the examples work now. 
So, I'm closing this issue now. 

Regards,
Arijit

**Comment by arijit17** [comment]
Hi Wolfgang:

Reported Issue #985 still exists.

Best Regards,
Arijit

**Comment by simra** [comment]
I am using Beta 7 and hitting this learning rate error. What is the workaround?

**Comment by simra** [comment]
To answer my own question, this tutorial includes how the learning rate schedule should be created: https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_102_FeedForward.ipynb
