### ISSUE TITLE
Compiling evalwrapper using visual studio 12 compiler 

### ISSUE THREAD

**Issue by heroner** [Microsoft/CNTK#1063]
Hi, 

I was wondering if anyone has successfully compiled the EvalWrapper package using VS12? I have been able to compile it with VS 13 and 15 but not 12 and I need it to work with VS 12. When I try, I get template declaration/definition error coming from Eval.h. Moving to 13 or 15 is not an option. Below is output from the IDE. Thanks for your time. 

Eval.h(178): error C2988: unrecognizable template declaration/definition
Eval.h(178): error C2059: syntax error : 'using'
Eval.h(246): error C2988: unrecognizable template declaration/definition
Eval.h(246): error C2059: syntax error : 'using'
Eval.h(249): error C2065: 'ValueBuffer' : undeclared identifier
Eval.h(249): error C2974: 'std::vector' : invalid template argument for '_Ty', type expected
Eval.h(249): error C3203: 'VectorRef' : unspecialized class template can't be used as a template argument for template parameter '_Alloc', expected a real type
Eval.h(249): error C2955: 'Microsoft::MSR::CNTK::VectorRef' : use of class template requires template argument list

**Comment by zhouwangzw** [comment]
I have not tried with VS12. One thing should be mentioned is that in order to run EvalWrapper.dll, you need other dependencies, e.g. eval.dll and math.dll. So you probably have to build these dependencies under VS12 too.

**Comment by heroner** [comment]
Thank you. That explains it but then I will have to port the entire CNTK core to VS12 to generate those dlls. I'll give a try. Let me know if there is an easier way.

**Comment by zhouwangzw** [comment]
The following Dlls are needed for running Eval: EvalDll.dll, EvalWrapper.dll, Math.dll, libiomp5md.dll and mkl_cntk_p.dll. I am not sure whether the libiomp5md.dll and mkl_cntk_p.dll, which are provided as a part of MKL library (https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#mkl), can be linked under VS12.
I am wondering whether this could an option for you: running the Eval as a searpate application/service (so you can build it under VS 2013) and communicate with your application (still built with VS2012) through some interprocess communication mechanisms to exchange data/results. Of course it could have some communication overhead, depdening on the amount of data to be exchanged and the performance requirement you are having.

**Comment by heroner** [comment]
Thanks Wang. I don't think I can tolerate the overhead given the tight performance requirements. I'm trying to build an auto-classification engine for a real time machine vision application. Speed is the first and top requirement. I'll see if interfacing with CNTK using the native API without inter process communication will satisfy this requirement. The c# version wasn't terrible.

**Comment by zhouwangzw** [comment]
Closing it. Please open an new one, if you still have problems.
