### ISSUE TITLE
Add per-node profiling output

### ISSUE THREAD

**Issue by cmarschner** [Microsoft/CNTK#1064]
In many situations CNTK may perform poorly because a perf implication is not understood. 
Need the ability to output fine-grained per-node-instance timings to derive statistics on different parts of the graph.

**Comment by cmarschner** [comment]
A prototypical implementation is here, https://github.com/Microsoft/CNTK/tree/clemensm/profiler . It has a perf impact when turned off due to sprintf, hence it is not integrated at this point.

**Comment by n17s** [comment]
Why isn't this a pull request?

**Comment by cmarschner** [comment]
The branch is outdated at the moment. Keeping the issue around as reference for the time being.

**Comment by cha-zhang** [comment]
I believe we have a profiler now. Closing this issue.
