### ISSUE TITLE
C++ app using cntk

### ISSUE THREAD

**Issue by Arminea** [Microsoft/CNTK#1066]
Hi,
I would like to create an c++ app which will use cntk and then make an apache module. Input should be an image given by user through web form. The application should use cntk pretrained model and give me a number of class (just 0 or 1) for the input image. 
Could someone steer me in the right direction? Is there any tutorial for using pretrained models in user application?

**Comment by n17s** [comment]
There are no C++ tutorials at this point. Some people build web apps with Python or C# nowadays. This [wiki page](https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network) shows how to load a single image and obtain predictions in Python.

Some C++ resources:
For loading a pretrained model in C++, [this](https://github.com/Microsoft/CNTK/blob/110aac7f3caa020892b040067b5717de9debf46b/Examples/Evaluation/CPPEvalV2Client/EvalMultithreads.cpp#L138) is the only example we have right now. This only shows how to load and evaluate a simple model. Another useful example in C++ is [CifarResnet](https://github.com/Microsoft/CNTK/blob/110aac7f3caa020892b040067b5717de9debf46b/Tests/UnitTests/V2LibraryTests/CifarResNet.cpp) which shows one way to load images in C++.

**Comment by Arminea** [comment]
Using python instead of c++ seems to be easier to me at this point :) Thanks a lot
