### ISSUE TITLE
Epochtime is too long when training data is 80 hours

### ISSUE THREAD

**Issue by xqustc** [Microsoft/CNTK#1067]
Hi, when I use about 10 hours speech data to train a three hidden layers neural network, epochtime in log file is about 5 minutes. However, when training data is 80 hours, epochtime is almost two and a half hours. 
It takes too long time to finish an epoch. I wonder if I am doing something wrong. Here is my log file:
In SGD block:
epochSize=0
minibatchSize=128
Parameter values for the reader is in the following:
readerType=HTKMLFReader
readMethod=blockRandomize
miniBatchMode=Partial
randomize=1728000

I have three kinds of features in the input layer, and four kinds of targets in the output layer. Does the feature reading and error calculating take  so much time? Or am I doing something wrong during my training? GPU version is K40m. Thank you.

**Comment by pkranen** [comment]
Hi, please try again with the 2.0 release, perf has improved a lot. I'll close this one, please reopen if the issue remains with the latest bits. Thanks.
