### ISSUE TITLE
No Tutorials installed on most recent build.

### ISSUE THREAD

**Issue by superobservation** [Microsoft/CNTK#1069]
I recently installed CNTK from scripts - Everything went well with installation (great job you guys) . However, the tutorials didn't install. As far as I know, it's the only thing missing in my entire installation- anybody know what could've led to this ? 
![image](https://cloud.githubusercontent.com/assets/22134567/20484815/cf489b98-afad-11e6-92df-377357b2b971.png)

**Comment by mahilleb-msft** [comment]
Hey @superobversation - we've updated documentation in the Wiki regarding set up too early - it describes the new location of the Tutorials for the upcoming release :)
Please for now take a look for tutorials here: bindings/python/tutorials/
Or, expect an updated CNTK drop today or tomorrow, which includes many fixes to the tutorials.

Thanks, Mark

**Comment by wolfma61** [comment]
the updated release that Mark announced is available. That will fix this issue ...
