### ISSUE TITLE
makeMode in samples

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#107]
The video https://www.youtube.com/watch?v=jAyalvQTTyQ shows a possible problem with makeMode. It defaults to 'true'. MakeMode=true means that existing models are not overwritten; instead training restarts at the last checkpoint, or will do nothing if the previous training completed. This behavior can be surprising, if as in the video, the user changes the configuration and expects the model to be retrained upon rerunning CNTK. We should add a makeMode definition to all samples with a comment.

**Comment by wolfma61** [comment]
plesae taka a look at 2.0 ....
