### ISSUE TITLE
How to implement Sequence-to-Sequence with LSTM for chatbot

### ISSUE THREAD

**Issue by kennetham** [Microsoft/CNTK#1070]
Hi, could the team advise on how to use CNTK with Seq2seq with LSTM for conversational bots? Please advise.

**Comment by n17s** [comment]
We have a [sequence to sequence example](https://github.com/Microsoft/CNTK/blob/90ff04f25449a9ad44e795a3bf2d7cd37b05023d/Examples/SequenceToSequence/CMUDict/Python/Sequence2Sequence.py) with LSTM. However, we cannot assist you with how to turn this example into a conversational bot.

**Comment by kennetham** [comment]
Yes I understand, but could you advise, how can I use that example? Like Tensorflow, there are guides to know how to use it. It's such a new tool, hence as partners of Microsoft, if we are playing with it, we do need support.

**Comment by JimSEOW** [comment]
@kennetham  any update to your attempt to bring CNTK for chat bot? Google search easily list many links on how to do that with Tensorflow. Please share your feedback with this [discussion](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050), we would like to have an overview where are the gaps in CNTK wrt Tensorflow

**Comment by n17s** [comment]
The tutorials you are finding on chat bots are not written by the core Tensorflow team. Similarly the CNTK team does not have the resources to create such a tutorial at this time.

**Comment by kennetham** [comment]
@JimSEOW: @n17s is right. CNTK product team does not have the resource to create such a tutorial at this time, however, I would recommend the Sequence to sequence example provided by product team. The example shows basic encoding and decoding, similarly for chat bots, you could used the same technique to train. I haven't got any updates yet to bring CNTK for chat bots, I'll be catching up with DX team on CNTK soon and will let you know if there have been any success.
