### ISSUE TITLE
LSTM: online learning in CNTK?

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#1071]
Hello,

Could you please let me know how I could setup online learning of LSTM in CNTK?

In the current setup, I have to provide a training sample and a test sample, while I want to give just one sample and make CNTK to update LSTM parameters after every new observed input (or a mini-batch of inputs). Testing should be done by comparing LSTM output with the corresponding labels after a certain number of inputs have been observed. Please, let me know if it is possible to do it in CNTK and how I could do it.

Thank you very much for your help!

**Comment by svml** [comment]
Nobody knows if online learning is possible in CNTK? 

Since CNTK has SGD, it should be possible.

**Comment by cha-zhang** [comment]
With Python you have a lot of flexibility in feeding data to the trainer, and online learning is certainly achievable. 

This thread has been too old and it's unclear if the issue remain in the latest CNTK 2.0. I'm closing this now. Please reopen a new issue if needed. Thanks!
