### ISSUE TITLE
PYTHON Interface: Can I use Kaldi Reader?

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#1072]
I couldn't find tutorials/examples using readers defined in prior CNTK versions such as kaldi2 reader, htk reader, text reader, ...
I'm wondering current version of CNTK provide readers as python API, especially kaldi2 reader.

**Comment by eldakms** [comment]
kaldi2 is not exposed to python. It is very old and does not follow new interfaces, so it should be reimplemented completely. It is not yet in plans.
