### ISSUE TITLE
FeedForwardNetwork python tutorial and sparse labels

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#1075]
Hi, 
I'm using the FeedForwardNetwork tutorial as the basis for my model.  My input features and labels are both specified as sparse StreamConfigurations:
````
test_mb_source = text_format_minibatch_source(path, [
    StreamConfiguration(feature_stream_name, input_dim,is_sparse=True),
    StreamConfiguration(labels_stream_name, num_output_classes,is_sparse=True)])
features_si = mb_source[feature_stream_name]
labels_si = mb_source[labels_stream_name]
````

When I reach the evaluation stage, np.asarray silently rejects the sparse labels and returns an empty array.
````
mb = test_mb_source.next_minibatch(test_minibatch_size)
orig_label = np.asarray(mb[labels_si].m_data)
print("LabelShape: ",orig_label.shape)
````
yields `LabelShape:  ()`

What is the preferred way to convert a sparse minibatch to an array?

**Comment by cha-zhang** [comment]
This thread has been too old and it's unclear if the issue remain in the latest CNTK 2.0. I'm closing this now. Please reopen a new issue if needed. Thanks!
