### ISSUE TITLE
python: Iterate through all the data?

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#1076]
The python tutorials hard-code the number of minibatches to run, independent of the size of the data set.  How do I iterate through all the available data?  
Does my data set size have to be a integer multiple of the minibatch size?

**Comment by ebarsoumMS** [comment]
Which tutorial are you looking at? Look at https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ConvNet/Python/ConvNet_CIFAR10_DataAug.py

It show you how to iterate through all data, and not the data size doesn't have to be multiple of MB size, the last MB is usually smaller.

**Comment by simra** [comment]
Thanks, maybe I'm missing something but in this same the train data is sampled for a maximum of 80 epochs:
````
 for epoch in range(max_epochs):       
````
and the test data is evaluated over a single fixed-size epoch:
````
while sample_count < epoch_size:
````
It looks like this example is closer to what I'm looking for:
https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceClassification/SimpleExample/Python/SequenceClassification.py
where the constants INFINITELY_REPEAT and FULL_DATA_SWEEP are used to configure the reader during train and eval. There's no actual eval implementation in that example but I could assume that the size of next_minibatch is 0 once all the data is swept. Is this a correct assumption?

**Comment by ebarsoumMS** [comment]
For FULL_DATA_SWEEP yes.

**Comment by simra** [comment]
Thanks, this worked for me. 
One quick note is that the documentation for text_format_minibatch_source has a small bug: it specifies that 0 can be passed as epoch_size to take the full training set, but the API requires that you pass FULL_DATA_SWEEP. (Passing zero returns an error).
https://www.cntk.ai/pythondocs/cntk.io.html?highlight=text_format_minibatch_source#cntk.io.text_format_minibatch_source

This leads to one last question.  If epoch_size is FULL_DATA_SWEEP and next_minibatch returns an empty dict when you reach the end of the data, how do you tell the reader you want to run N epochs for N>1?  The best idea I have so far is to get_checkpoint_state() before reading any data, and reset the state for each pass. Maybe there's a better way?

**Comment by ebarsoumMS** [comment]
Thanks for reporting the doc issue. For N > 1, why do you want to use FULL_DATA_SWEEP instead of INFINITELY_REPEAT?

**Comment by simra** [comment]
Well that's an interesting question.  In the absence of any real stopping criterion, I'd like to do exactly K passes through the data.  But maybe it's more sensible to fix the epoch size and not worry about the size of the training set.  Intuitively, I think it's worth understanding how well you can learn from a training data set in a way that's agnostic to its size- controlling the number of passes seems like the best way to do this without overfitting on small data sets.
Put another way:  I want to ensure I learn over all the data when I have a big data set, and simultaneously avoid overfitting when I have a small data set.  I suppose the best way to do this is via a reasonable stopping criterion.
