### ISSUE TITLE
Starting RNN (converting simple network to RNN)

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#1077]
I have input data as integer that is sequence of time domain.

To train I can make this in DNN :

SimpleNetworkBuilder = [
    layerSizes        = 50000:50000:1
    trainingCriterion = SquareError
    evalCriterion     = SquareError
    layerTypes        = RectifiedLinear
]

I read some intro about RNN, document and example in cntk,
but I cant find solution how to train my data in RNN.
because my data is INTEGER, but all examples are TEXT.

5 3 7 2 6 8 9 13 17 14 13 13 13 9 10 11...
this is example of features
and label is one integer such as 4 or 8.

RNN train well to time domain data, so I want to make RNN.

I make  network more simple to understanding well

SimpleNetworkBuilder = [
    layerSizes        = 50000:1
    trainingCriterion = SquareError
    evalCriterion     = SquareError
    layerTypes        = RectifiedLinear
]

How to convert this DNN structure to RNN-LSTM?

**Comment by cha-zhang** [comment]
You may do it with the Python API. Check the tutorial here: https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_106A_LSTM_Timeseries_with_Simulated_Data.ipynb

This thread has been too old and it's unclear if the issue remain in the latest CNTK 2.0. I'm closing this now. Please reopen a new issue if needed. Thanks!
