### ISSUE TITLE
FastRCNN with CSEvalClient Rois question

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#1079]
Hi,

I'm working on CSEvalClient and I some questions regarding this piece of code:

EvaluateObjectDetectionModel(); 
https://github.com/Microsoft/CNTK/commit/7eefb18dce9a6f8bf4e020f0dde37acb403e16dd

1) This rois are the selective search rois from the original image projected to the resize image(1000x1000) and divide by 1000 to get the float values, right? The original image is WIN_20160803_11_28_42_Pro.jpg with 1080x1920

// parse rois: groups of 4 floats corresponding to (x, y, w, h) for an ROI 
string roiCoordinates = "0.219 0.0 0.165 0.29 0.329 0.025 0.07 0.115 0.364 0.0 0.21 0.13 …....

2) Where can I get the values of the rois obtain by?

outputs = model.Evaluate(inputs, outDims.First().Key);

	“Outcome for ROI 31: 6 (gerkin) …”

	I want the values left,top,width,heigth of ROI number 31!

Thks

**Comment by pmfcdb** [comment]
How can I use CSEvalClient and FAST R-CNN with the new version of CNTK 2.0 beta8?

Here is the problem that I mention in the first post:
https://www.youtube.com/watch?v=w6HyncJ8yzc&feature=youtu.be

Thks

**Comment by zhouwangzw** [comment]
@pmfcdb Do you mean to evaluate a FAST R-CNN model that is tranined with CNTK 2.0 beta8? In beta8, we have a new C# Eval API published.
This[ page ](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows#using-the-cntk-library-managed-api
) describes how to use the API. 
The examples can be found [here](https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation) , with [instructions](https://github.com/Microsoft/CNTK/wiki/CNTK-Eval-Examples). 
The new API also supports GPU.

**Comment by pmfcdb** [comment]
How can I define the inputVar "rois" of the "Fast-RCNN.model" ( CNTK2.0 beta8 ) and inputVar "roiLables" in the CNTKLibraryCSEvalGPUExamples ?

The error I get with only inputVar features: 
======== Evaluate model using C# GPU Build ========
Output map : ce errs z
Input map : features rois roiLabels
Features Input 1000 1000 3
Evaluate single image

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CNTK.CNTKLibPINVOKE.Function_Evaluate__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4)
   at CNTK.Function.Evaluate(UnorderedMapVariableValuePtr arguments, UnorderedMapVariableValuePtr outputs, DeviceDescriptor computeDevice)
   at CNTK.FunctionExtensions.Evaluate(Function func, Dictionary`2 arguments, Dictionary`2 outputs, DeviceDescriptor computeDevice)
   at CNTKLibraryCSEvalExamples.CNTKLibraryManagedExamples.EvaluationSingleImage(DeviceDescriptor device) in C:\Users\pbrito\Documents\CNTK-2-0-beta8-0-Windows-64bit-GPU\cntk\Examples\Evaluation\CNTKLibraryCSEvalCPUOnlyExamples\CNTKLibraryCSEvalExamples.cs:line 82
   at CNTKLibraryCSEvalExamples.Program.Main(String[] args) in C:\Users\pbrito\Documents\CNTK-2-0-beta8-0-Windows-64bit-GPU\cntk\Examples\Evaluation\CNTKLibraryCSEvalGPUExamples\Program.cs:line 19

**Comment by zhouwangzw** [comment]
@pmfcdb Could you please try the latest Nuget Package 2.0Beta9, which is published on the last Friday?

**Comment by pmfcdb** [comment]
Hello,

I ‘m using beta11 and I’m trying to evaluate FAST RCNN with CSEvalClient from this branch from pkranen :

https://github.com/Microsoft/CNTK/blob/pkranen/csevalFastrcnn/Examples/Evaluation/CSEvalClient/Program.cs

The method is : EvaluateObjectDetectionModel()

The code runs with no problem,  I can extract ROIs. I add OpenCvSahrp to see the string rois in the image and then after the model evaluation. 

Is this result correct?

Here is the result :

Only showing predictions for non-background ROIs…
roi max label[max] x y w h
31-6-gerkin-354-460-185-110-
33-6-gerkin-359-455-175-125-
62-8-ketchup-264-720-190-105-
63-8-ketchup-264-725-185-95-
71-6-gerkin-354-460-185-120-
72-6-gerkin-354-460-185-135-
88-12-tomato-314-710-155-115-
90-8-ketchup-264-720-225-100-
91-8-ketchup-264-720-225-105-
Number of background ROIs: 91 -
![untitled02](https://cloud.githubusercontent.com/assets/22818355/22982356/dab6c3c4-f396-11e6-9615-cff5495e421d.png)
![untitled01](https://cloud.githubusercontent.com/assets/22818355/22982367/e2369318-f396-11e6-9812-7c7f2a21d673.png)


The image with the blue rectangles are the initials rois and the image with the reds are the evaluation.

Thks

**Comment by pmfcdb** [comment]
Ok, I tested with several images with an implementation of selective search and its working!

Here is a video of the final result with the grocery dataset:

https://youtu.be/BEYgGUhrbLM

Thks

**Comment by yuanweilei** [comment]
@pmfcdb Can you tell me how to get rois using selective search by C# please? 
 // TODO: generate ROI proposals using an external library, e.g. selective search, 
 // TODO: project them to the 1000 x 1000 image size and compute (x, y, w, h) relative to the image dimensions.

**Comment by pmfcdb** [comment]
Hi, I used this project https://github.com/watanika/selective-search-cpp to generate rois in C#, my plan is to later on convert to C#. Also I create a method in C# that generate a grid to complement the roi generation in selective search as in A1_GenerateInputROIs.py ( getGridRois ).

**Comment by yuanweilei** [comment]
@pmfcdb Thank you very much!!

**Comment by yuanweilei** [comment]
@I am very sorry. Can I ask you another question please? I download https://github.com/watanika/selective-search-cpp and I want to use openCV3.0 nuget to run it but "can not open opencv_core300d.lib" was shown. Can you tell me how to compile this project using nuget?
(I do not want install openCV in my PC because I want to deploy this project to Azure and use it in a Bot.)

**Comment by yuanweilei** [comment]
@pmfcdb I am very sorry. Can I ask you another question please? I download https://github.com/watanika/selective-search-cpp and I want to use openCV3.0 nuget to run it but "can not open opencv_core300d.lib" was shown. Can you tell me how to compile this project using nuget?
(I do not want install openCV in my PC because I want to deploy this project to Azure and use it in a Bot.)

**Comment by pmfcdb** [comment]
Hi, I 'm using windows 10 x64 pro, visual studio 2015 community, and installed NuGet packages : opencv.win.native v310.3.0 and opencv.win.native.redist v310.3.0. After I installed the nuget packages I can compile and run the program.

**Comment by yuanweilei** [comment]
@pmfcdb Thank You! I run it !!! 
I installed NuGet packages: opencv3.1 before you tell me I should install opencv.win.native v310.3.0.

**Comment by wendy7707** [comment]
@pmfcdb  hello, I have one question, when I used the C# coding to evaluate the model, it just output as the following :"Number of background ROIs: 100", and I see the results of "outputs = model.Evaluate(inputs, outDims.First().Key)" are always the same. Would you please tell me how to solve this problem, thank you very much!

**Comment by pmfcdb** [comment]
Hi, here is a video with CNTK 2.0 release of CSEvalClient with the code for evaluate FASTRCNN in debug mode with results:
https://youtu.be/Gy82Nv2gAqs

**Comment by wendy7707** [comment]
@pmfcdb ， thank you very much for your reply, I used 2.1 Cntk nuget package, VS 2015 with update 3 and the same coding as you provided to me, but unsuccessful, so you means I should need 2.0 released cntk nuget package? right?

**Comment by wendy7707** [comment]
@pmfcdb Have you used CNTK 2.0 release to realize evaluate FASTRCNN in c#?

**Comment by pmfcdb** [comment]
Yes, right now I can't evaluate in 2.1

**Comment by wendy7707** [comment]
@pmfcdb  thank you so much! I just follow your suggestion, but the results is not good, I think after"outputs = model.Evaluate(inputs, outDims.First().Key);" the output should be same as "test.z" in python. But it is different, and the results are not same as too. would you please tell me how to solve this problem, did you have the same result? Thanks!

**Comment by pmfcdb** [comment]
Hi, are you using the same image and rois? Can you make a video in debug mode showing the results?

This example only works for this image because of rois value being a fix value for this image, if you change the image you have to calculate the rois for the new image.

**Comment by wendy7707** [comment]
Yes, I used "WIN_20160803_11_28_42_Pro.jpg" and the 0 in test.roi.txt ,I think it is the same image. The following the debug result of "outputs = model.Evaluate(inputs, outDims.First().Key)", and it is different with "test.z".Would you please help me how to solve this problem? 

- Thanks!
<img width="633" alt="2017-09-04 2 04 07" src="https://user-images.githubusercontent.com/30385554/30011456-b81dff26-917a-11e7-8bcf-5c1b91890a40.png">

**Comment by pmfcdb** [comment]
Hi, the values are different from mine, I get in CNTK 2.0 release this values:
![fastrcnn_outputs_cntk2](https://user-images.githubusercontent.com/22818355/30025127-f54c3dc4-916e-11e7-93fa-cb390296fc04.png)
Are you using the download model, Fast-RCNN_grocery100.model? 
The reference from CNTK is Cntk.Eval.Wrapper-2.0?

**Comment by vackup** [comment]
@pmfcdb can you please share the selective-search-cpp Wrapper with us? thanks!!

**Comment by pmfcdb** [comment]
Hi, I used this project https://github.com/watanika/selective-search-cpp to generate rois in C#.

**Comment by vackup** [comment]
Yep, I understood that.. what did you do? Did you migrate it to C# o wrap the c++ into a DLL? Thanks

**Comment by pmfcdb** [comment]
I migrated the code to c# and I used OpenCvSharp, but I can't share that code.

**Comment by vackup** [comment]
Ahhh, Ok.... np... but al least you let me know that is posible to migrate it to C#  ;) 

I tried to migrate this code https://www.learnopencv.com/selective-search-for-object-detection-cpp-python/ but they are some missing methods in OpenCvSharp.

Thanks!

**Comment by vackup** [comment]
In case someone need it, I've created a C++ CLI Wrapper for SelectiveSerach so it can be used in C#

https://github.com/vackup/CoreXimgprocSeg/
