### ISSUE TITLE
Can I get convolutional output value?

### ISSUE THREAD

**Issue by chhyun** [Microsoft/CNTK#1081]
Hi,  I'm using cntk 2.0 version and I want to know if I can get convolutional output from my network.

network is described below...
conv1 / pool1 / conv2 / pool2 / h1 / h2 / output  

now I can get hidden1, hidden2, and output layer's output.

but I need conv1's output  or conv2's..

here is my code I'm using in test part
   
   test = [
                 ...
              action = "write"
              outputPath = "my_test_code"
              outputNodeNames = (output.z)    # or outputNodeNames = (h1.z) 
              ]

I tried    outputNodeNames = (conv1.z) 
  but it didn't work 

can i get some advise?

**Comment by DanielMerget** [comment]
simply

`outputNodeNames = "conv1"`

should be sufficient. If not, you should check your (training) log file for the actual name of you convolution result. Afaik, you can also write multiple nodes at the same time using

`outputNodeNames = ("conv1":"conv2")`
