### ISSUE TITLE
MultiplyAndAdd(...,dense,..., sparse,..., blocksparse) is broken

### ISSUE THREAD

**Issue by thilow** [Microsoft/CNTK#1082]
The method 

GPUSparseMatrix<ElemType>::MultiplyAndAdd(...,dense,..., sparse,..., blocksparse)

does not work properly. The problem is that it doesn't accumulate the results in the output but overwrites it.

The problem shows up e.g. when we have e.g. a weight matrix receiving gradients from two nodes like

Times(weight, sampleSelector)
Times(weight, labels)

**Comment by KeDengMS** [comment]
This is fixed in [master: c12979b](https://github.com/Microsoft/CNTK/commit/c12979b245f7f7188567bf4c4d2644651ec5c5d8)
