### ISSUE TITLE
Input data randomization should not keep all data in memory

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#1083]
When one specifies _minibatchSize_ and requests randomization (_randomize=true_) and not explicitly requests all data to be in memory (_keepDataInMemory=true_), than data reader should not stuff whole data set into memory even if _randomizationWindow_ is not set.

This is also what I'd expect based on the documentation:
https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers 
"(...) Randomization method is identical to blockRandomize of the HTKMLFReader. (...)"

https://github.com/Microsoft/CNTK/wiki/HTKMLF-Reader 
"(...) The data in each block is read directly from the feature files, and released from RAM when it is no longer used (...)"

However, with minibatch set to 1024 samples (each samples ~15k floats) I saw CNTK process still growing pass the 13GB memory footprint before starting first minibatch:

![cntk_memory_issue_2](https://cloud.githubusercontent.com/assets/3809076/20605828/95549032-b26d-11e6-9231-5434bceaeca1.PNG)

CNTK version: 1-7-2

whole reader setting:

```
reader = [
        readerType = "CNTKTextFormatReader"
        file = "<...>"
        input = [
            features = [
                dim = 15996
                format = "dense"
                
            ]
            labels = [
			    alias = "target"
                dim = 3
                format = "dense"
            ]
        ]
    ]
```

**Comment by jakrivan** [comment]
Btw. even better would be to read _only_ the lines that needs to be read - by estimating (or requesting to be specified) number of entries in input file; then building randomized list of line numbers to be read, and then seeking in the file to those positions (reading-skipping to the next newline and then reading to the next newline).

With huge data files this can be a huge saver of time.

**Comment by raaaar** [comment]
Thanks for reporting. This is the case of a bad default -- the reader shuffles the data within a randomization  window, which by default is set to the full data size. We'll address this in a future release. Meanwhile, please specify  **randomizationWindow** in the reader section (e.g. `randomizationWindow  = 10240` -- to limit the window to the number of samples required to fill 10 minibatches).

**Comment by jakrivan** [comment]
Thanks raaaar for pointing to randomizationWindow - we'll give it a try.

As to my comment that randomization might need to just read the 'batchSize' lines from the file (or better to say - approximately 1.5*batchSize). This was my thought process (I might be completely wrong): 

you have an input file of size _szFile_ bytes, by reading first few lines (or even better few random lines) you get mean byte size of single line - _szLine_. Thus the file has approximately linesCount = _szFile_/_szLine_ lines. You generate sequence of _MinibatchSize_ random numbers from <1; linesCount>. Then for each number (_currentLineNumber_) in this sequence you seek into the file in the _currentLineNumber_ * _szLine_ position; read & skip the text on that position until hitting newline; then reading till next newline.

This way allways perform approximately same number of I/O opperations, regardless of the size of the file. It can be made even more efficient when also applying radnomizationWindow at the same time (due to data locality); but without that you'd still stay in reasonable number of I/O operations.

**Comment by raaaar** [comment]
As a thought exercise, what would you do in case of variable-length sequences? Also, you need to make sure that you don't miss any lines and don't return the same line twice in an epoch. So, overall you still need to do some extra bookkeeping, but it'd be interesting to find if your approach could beat ours (: To get to MinibatchSize lines distributed all over 300GB, you'd have spent some time doing seeks, I wonder what the total overhead would be.

**Comment by jakrivan** [comment]
I might be missing many important details - as from higher level everything looks easier.

variable-length sequences - yes this is makes it quite complicated. As I mentioned the line size would need to be just estimated (e.g. be readeing few random blocks of file and getting mean line length). For very non uniform data this might get quite off.
Also the list of line indexes for each minibatch would need to have matching list of actuall start ofsets from file (so that, due to some longer line, we dont end up reading same line for line# 3 and 4 since line 2 is quite huge and estimates of start offset of 3 and 4 falls both within line 2).

To conclude - all those improvements are very easy for uniform line legth. But might be a waste of efforts for textual files and especially variable length sequences - as those are not probably frequently used by folks anxious about performance or playing with big data.

Will try to come up with some uniform-binary-input reader.

Thanks for all the input!

**Comment by jakrivan** [comment]
Btw. we've created our own in-memory reader creating minibatches on demand and not keeping any data inside cntk process memory (only the actively used minibatches): https://github.com/KGTInv/CNTK/tree/master/Source/Readers/KgtMmfReader

**Comment by wolfma61** [comment]
thank you for the update - we will definitely take a look!
