### ISSUE TITLE
CNTK Examples: Image/Classification/ResNet/Brainscript model to CSEval

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#1084]
Hi,

I did the "cntk configFile=ResNet20_CIFAR10.cntk" and I got the results :

Minibatch[1-79]: errs = 8.270% * 10000; top5Errs = 0.220% * 10000
Final Results: Minibatch[1-79]: errs = 8.270% * 10000; top5Errs = 0.220% * 10000

But where is the *.model file to use with CSEvalClient?

I look in Image\Classification\ResNet\Output\Models but there are several files ResNet20_CIFAR10_DataAug, ResNet20_CIFAR10_DataAug0,....ResNet20_CIFAR10_DataAug159 and all with 1143kb. 

The model that I download to use with CSEvalClient -> ResNet_18.model is 64186kb.

Thks

**Comment by zhouwangzw** [comment]
The ResNet20_CIFAR10_DataAug is the final model file. ResNet20_CIFAR10_DataAug0..159 are checkpoint files saved after each epoch. 

Thanks.

**Comment by pmfcdb** [comment]
Hi, ok, I tried the model with CSEvalClient and changed the input value size to reflect data set model:

EvaluateImageClassificationModel()
...
  // Prepare input value in the appropriate structure and size
  var inDims = model.GetNodeDimensions(NodeGroup.Input);
 if (inDims.First().Value != 32 * 32 * 3)

and

var resized = bmp.Resize(32, 32, true);

But is not working because it gives me always "Outcome: 2", even with train images of different classes.

What am I doing wrong? Is there a model of ResNet20_CIFAR10.model that I can use, just to test?

Thks,

**Comment by zhouwangzw** [comment]
It seems that your trained the model using CuDnn BatchNormalization engine (if you have not changed the config file ResNet20_CIFAR10.cntk and Macro.bs file). However, the C# Eval Library currently is only support CPU-Only, so you have to train the model using CNTK BatchNormalization engine (by changing useCntkEngine to `true` in the line 
` BatchNormalizationLayer {spatialRank = 2, normalizationTimeConstant = bnTimeConst, useCntkEngine = false
`
of Macro.bs.
We are currently working on the new version of C# Eval which will support eval on GPU device. 
Thanks,

**Comment by pmfcdb** [comment]
Ok, thks, it worked, CSEval is now working with CIFAR-10 training model!
Training model CIFAR-10 results:
Minibatch[1-79]: errs = 8.110% * 10000; top5Errs = 0.280% * 10000
Final Results: Minibatch[1-79]: errs = 8.110% * 10000; top5Errs = 0.280% * 10000
