### ISSUE TITLE
CNTK reads through huge file despite minbatch set and randomization turned off

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#1085]
As a workaround to issue https://github.com/Microsoft/CNTK/issues/1083 we completely disabled randomization:

```
reader = [
        readerType = "CNTKTextFormatReader"
        file = "..."
		keepDataInMemory = false
		randomize = false
        input = [
            features = [
                dim = 15996
                format = "dense"
                
            ]
            labels = [
			    alias = "target"
                dim = 3
                format = "dense"
            ]
        ]
    ]
```

MiniBatch is set to 1024 sample. Our input file has some 300GBs; but with those settings I'd expect only some 15996 * 1024 * 4 bytes to be read (input vector size, minibatch size, float size).
Instead we can see cntk performing extensive disk reads:

![cntk_memory_issue](https://cloud.githubusercontent.com/assets/3809076/20606898/72bc747a-b274-11e6-9bbb-e2d29d3580be.PNG)

And reading huge amounts of data from the disk:

![diskreads](https://cloud.githubusercontent.com/assets/3809076/20606902/7feb38e8-b274-11e6-887e-67f2273d93e4.PNG)

Is there any setting we are missing that can revert effect of _keepDataInMemory = false_ and _randomize = false_?

**Comment by raaaar** [comment]
The reader needs to build an index of the input file and collect both chunk and sequence-level metadata (offsets, number of samples, etc). All of this happens during the initial pass over the input file, After that the data is processed in a chunk-by-chunk fashion, with the stale chunks offloaded from the memory. To fill out a minibatch size of  15996 * 1024 * 4 bytes, the reader needs to keep alive from a couple to a few dozen chunks depending on the shape of actual data (the default chunk size is 32 MB on disk). 

WRT memory consumption: for 300GB input the index can grow to be fairly large (especially, in the frame/non-sequence mode). Even though the index is not really needed with randomize=false, the reader itself does not distinguish between two modes, and creates the index irrespective of the configuration value. This is something we will address in the future release. Additionally, we are  looking into minimizing the index size, collecting only the strictly required metadata during the initial pass and lazy-loading the rest on demand. 

I'm not sure how to interpret "Read Bytes". When was this recorded? Depending on the config, the cntk might do a few passes over the input data, and the read bytes will keep on increasing with each new chunk/minibatch/epoch.

**Comment by jakrivan** [comment]
In another words - the whole file needs to be read through irrespective of the randomization and minibatch setting, correct?
This makes work with large input files very time consuming.

Btw. are there any plans for binary formats of input data? - as then (with fixed byte size of each line) there would be no need to read all data and build index - number of records and offset of each record would be quickly computable from single line size.

**Comment by raaaar** [comment]
During the initial pass we skip over the new-lines, only parsing sequence ids if they are present and the user didn't explicitly requested frameMode in the reader config. This should only take a fraction of time of the actual "reading" (also, there are a few optimizations that improve things in stand-alone mode, that will be included in beta 5.0 release).

Yes, a binary reader will soon be added. However, it's designed to support variable length sequences as well as sparse input (no assumptions on the sequence/sample length), as a result the index needs to be backed into the input itself. That said, you are welcome to contribute a binary deserializer tailored for fixed-length input (https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers), it will certainly be appreciated! Additionally, we're thinking about providing tools to build an external index for text files, so that the reader wouldn't have to create it every time from scratch.

**Comment by jakrivan** [comment]
Thanks raaaar,

Unfortunately performance of working with file is allways strongly dominated by I/O subsystem. So regardless if only number of lines in file are counted; or entire line is being parsed; this still needs to fetch everything from the disk.
Ok - we are definitely in need for a binary reader and going to code some prototype. We'll definitely try to make efforts to make it bit more general (but still tailoed for fixed width input) and create pull request for it

**Comment by raaaar** [comment]
Actually, the bulk of the time is spent in parsing, lifting stuff from disk is not that expensive. I just generated a fake 15GB input file with two inputs (with 15K and 3 floats) and timed the indexing -- it took 40 seconds. Not exactly non-negligible, but also not live threatening. Heavy-lifting is supposed to be done in binary anyways.

**Comment by raminia** [comment]
What's the status of the binary deserializer? Which branch contains the latest work?

**Comment by jakrivan** [comment]
Hi Raminia - we created our own private prototype as it is too proprietary to share at this point.

What we did was to create our own implementation of SequenceEnumerator and in CNTKTextFormatReader.cpp we replaced creation of TextParser and wrapping by randomizer (BlockRandomizer or NoRandomizer) simply by creation of our own implementation of SequenceEnumerator

**Comment by avader906** [comment]
@raaaar What is the optimal text reader configuration in the beta 8/9 to address large text input without need to randomize at any level ? frameMode = false, randomize = false ? anything else ?

**Comment by jakrivan** [comment]
Hello - I just wanted to mention that we've created our own reader that pushes data to CNTK via memory mapped file (and some event signaling). This way we've been able to greatly increase speed of learning (in our case it was by about one order).
Here is the commit in our fork: https://github.com/KGTInv/CNTK/commit/3976b781a4f1020adb345e5d15fdff3022daaac7
Any feedback or comments are greatly wellcome
