### ISSUE TITLE
Cannot open CNTK_204_Sequence_To_Sequence.ipynb notebook

### ISSUE THREAD

**Issue by leo-gan** [Microsoft/CNTK#1088]
Other notebooks like **CNTK_203_Reinforcement_Learning_Basics.ipynb** opened fine. Jupyther started at http://localhost:8888/

**Comment by wolfma61** [comment]
Hi 
I just tried with a fresh install of the just released beta5 binary package on Windows. It worked fine...
http://localhost:8888/notebooks/CNTK_203_Reinforcement_Learning_Basics.ipynb
http://localhost:8888/notebooks/CNTK_204_Sequence_To_Sequence.ipynb

or try the online version?
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_203_Reinforcement_Learning_Basics.ipynb

**Comment by leo-gan** [comment]
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb - is still not opening in Chrome! Other .ipynb - s opened.
