### ISSUE TITLE
Cant import UnitType from cntk.learner

### ISSUE THREAD

**Issue by Aceb1shmael** [Microsoft/CNTK#1089]
I have install cntk and follow https://www.cntk.ai/pythondocs/gettingstarted.html# .But when i go into First basic use section, it`s unable to import UnitType.
![2016-11-25 3](https://cloud.githubusercontent.com/assets/22240403/20617272/f7d08a58-b322-11e6-8e4f-c85ab7501e01.png)

**Comment by raaaar** [comment]
Could you please run `pip show cntk` and paste the output here?

**Comment by Aceb1shmael** [comment]
![2016-11-25 4](https://cloud.githubusercontent.com/assets/22240403/20629166/fe8befda-b364-11e6-8b43-a096e841ee65.png)
am i not running the right version?

**Comment by raaaar** [comment]
I'm afraid, not. Please, `pip uninstall cntk`, download beta 4.0 release from https://github.com/Microsoft/CNTK/releases and install it instead.

**Comment by Aceb1shmael** [comment]
oh, it works. thanks for the help
