### ISSUE TITLE
Split sequence data into subsequences

### ISSUE THREAD

**Issue by kongsgaard** [Microsoft/CNTK#1091]
Hi,

I have been looking around how to implement this in CNTK (with the python api), and i have not found anything to help me.

Say that i want to classify documents. Each document is between 1...N sentences.
My data would look like this:
```
DocId | Sentence num (sen)| word (w)
1|Sen 1 |w 102:1
1|Sen 1 |w 13:1
1|Sen 1 |w 72:1
1|Sen 1 |w 79:1
1|Sen 1 |w 54:1
1|Sen 2 |w 102:1
1|Sen 2 |w 96:1
2|Sen 1 |w 33:1
2|Sen 1 |w 65:1
2|Sen 1 |w 49:1
```

This means that document 1 contains two sentences with words
```
Sentence 1: 102, 13, 72, 79, 54
Sentence 2: 102, 96, 33
```
and document 2 
`Sentence 1: 33, 65, 49`
I already have a trained sequential model to create a n-dimensional embedding of a sentence (following seq2seq). I would like to train a new sequential model to classify documents based on sentence embeddings.
The question is mainly on how to extract the data properly from the file, and specify that the sequential embedding model for sentences (that is trained), should take the subsequence where Sen=1 first, then take the subsequence with Sen=2 afterwards?

In this example i have a "depth" of 2, but i would love a generic solution such that if i also had a paragraph values for my dataset the solution would scale.

**Comment by raaaar** [comment]
If modifying the input data is an option, you could change sequence ids (the very first column) from `DocId` to `DocId * 10000 + Sentence num` (assuming no document contains more than 9999 sentences).

**Comment by kongsgaard** [comment]
If i do that, the data would look like 
```
DocId | Sentence num (sen)| word (w)
10001|Sen 1 |w 102:1
10001|Sen 1 |w 13:1
10001|Sen 1 |w 72:1
10001|Sen 1 |w 79:1
10001|Sen 1 |w 54:1
10002|Sen 2 |w 102:1
10002|Sen 2 |w 96:1
20001|Sen 1 |w 33:1
20001|Sen 1 |w 65:1
20001|Sen 1 |w 49:1
```
Which seperates the information (sentences/words) from document 1 over multiple sequence id's. I would like to make a single classification based on two different data instance now (different sequence id's), which i don't think is possible?

**Comment by raaaar** [comment]
Not sure if that would really help with your training, but there're multiple ways to massage the input data:
1) encode the doc id into the sentence id:
```
DocId | Sentence num (sen)| word (w)
1|Sen 10001 |w 102:1
1|Sen 10001 |w 13:1
1|Sen 10001 |w 72:1
1|Sen 10001 |w 79:1
1|Sen 10001 |w 54:1
1|Sen 10002 |w 102:1
1|Sen 10002 |w 96:1
2|Sen 20001 |w 33:1
2|Sen 20001 |w 65:1
2|Sen 20001 |w 49:1
```
2) Use sentence id as a sequence id, maintaining a mapping to doc ids:
```
SentenceId | DocId (Doc) | word (w)
1|Doc 1 |w 102:1
1|Doc 1 |w 13:1
1|Doc 1 |w 72:1
1|Doc 1 |w 79:1
1|Doc 1 |w 54:1
2|Doc 1 |w 102:1
2|Doc 1 |w 96:1
3|Doc 2 |w 33:1
3|Doc 2 |w 65:1
3|Doc 2 |w 49:1
```
3) Enumerate all unique sentences, use sparse indices to encode their ids (same as for words), use values to reflect the sequence position in a doc:
```
DocId | Sentence num (sen)| word (w)
1|Sen 42:1 |w 102:1
1|Sen 42:1 |w 13:1
1|Sen 42:1 |w 72:1
1|Sen 42:1 |w 79:1
1|Sen 42:1 |w 54:1
1|Sen 127:2 |w 102:1
1|Sen 127:2 |w 96:1
2|Sen 314:1 |w 33:1
2|Sen 314:1 |w 65:1
2|Sen 314:1 |w 49:1
```

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Please reopen if further help is needed.
