### ISSUE TITLE
Surprised to see no CUDA prerequisite in the CNTK GPU version

### ISSUE THREAD

**Issue by gue22** [Microsoft/CNTK#1092]
This may be a somewhat naive question, but I´m surprised to see no CUDA / cuDNN installation prerequisite in the CNTK GPU version installs and the test example works just fine w/o. (at least on Windows)

I see quite a number of of references to CUDA in the issues (and CUDA installations?) referenced in Brain Scripts.

When I search the wiki it seems CUDA is compiled into CNTK?!

Where can I find any insights on that?

Thanks and a late Happy Thanksgiving!
G.

**Comment by wolfma61** [comment]
I'm not 100% sure what you are referring to .. This pages links to the description of various installation options on the platforms: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-your-machine
For the installation of the binary package, most components are included in the package, only some pre-requisites need to be installed (depending on your platform this might include graphics drivers etc)

If you want to build it from the source code, there are more components to be installed, also Cuda, cudnn, cub libraries , headers etc. You will find links to this on the page above. 

on a compute level you graphics card should at least support compute level 3, you will find that Nvidia Kepler, Maxwell and of course Pascal based cards satisfy this requirement. 

You will find more information here: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#gpu-specific-packages or here: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#gpu-specific-packages

Wolfgang

**Comment by gue22** [comment]
This is a great answer, Wolfgang, and I appreciate your expertise.

I used to work on the documentation of a very complex AppMon product with several tiers and supporting every conceivable tech -- and most inside people had no idea beyond a very high-level overview.

I´m trying to get a hang of the differences to and commonalities with TensorFlow. (CUDA,... prerequisite)

Cudos
G.
