### ISSUE TITLE
python APIs, adagrad -> RuntimeError: Microsoft::MSR::CNTK::GPUMatrix<ElemType>::Resize

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#1096]
Hi,
I am playing with SGD algorithms. 
momentum_sgd, adam_sgd, nesterov appear to work, but when I set up adagrad
adagrad(z.parameters, lr=lr_schedule)
then, at second or third call to 
trainer.train_minibatch({input : inputs[iprev:ik,], label : labels[iprev:ik,]})
I am getting
RuntimeError: Microsoft::MSR::CNTK::GPUMatrix<ElemType>::Resize: Cannot resize the matrix because it is a view.
iprev, ik move in tandem so each time their range provides next 50 cases.

Regards,
Slawek

**Comment by raaaar** [comment]
Thanks for reporting. There seems to be an bug in the GPU version of the adagrad -- it needs to pre-allocate smoothed gradients differently from the CPU version. Will be addressed shortly.
