### ISSUE TITLE
Integer divide by zero

### ISSUE THREAD

**Issue by amzador2** [Microsoft/CNTK#1097]
Thanks to the team for the rapid release of CNTK V2 beta 5. It is much appreciated.
The new code appears to be running reasonably smoothly and the Curand error is gone. Yay!

Two possibly minor issues:
1) When executing python FeedForwardNet.py in NumpyInterop I get the error 
          ImportError: cannot import name 'cntk_py'
and
2) When running the CIFAR10 set in ...\cntk\Examples\Image\Classification\ConvNet\BrainScript
I get an integer divide by zero error well into the training run.

Any help is always appreciated.
Andrew,
Waterloo

**Comment by wolfma61** [comment]
There have been many changes and improvement since the Beta5 release.

If this still occurs with the most recent released version, please reopen (or create a new issue) with sufficient information to reproduce the problem
