### ISSUE TITLE
Loading a test image using python API

### ISSUE THREAD

**Issue by rahul-anand** [Microsoft/CNTK#1098]
While testing on new image using python evaluation API should i use this

 pic = np.array(Image.open("foo.jpg"), dtype=np.float32).T

or 

 pic = np.array(Image.open("foo.jpg"), dtype=np.uint8).T

Given my training images are in range (0,255) or are in uint8 format

I believe it should be uint8 but just confirming in case CNTK does some internal conversion?

**Comment by eldakms** [comment]
it does not. please specify float. Thank!
