### ISSUE TITLE
Cannot import UnitType

### ISSUE THREAD

**Issue by GopikrishnanSasikumar** [Microsoft/CNTK#1101]
I installed cntk via manual installation.After successful installation there is no Tutorials/NumpyInterop in cntk root folder.Cloned the repository but still tutorials folder is not found.Downloaded it as zip file and copied the tutorial folder and on running python FeedForwardNet.py

Traceback (most recent call last):
  File "FeedForwardNet.py", line 12, in <module>
    from cntk.learner import sgd, learning_rate_schedule, UnitType
ImportError: cannot import name 'UnitType'
this error is showing
![2016-11-29 2](https://cloud.githubusercontent.com/assets/16781355/20699526/cc5472f0-b62d-11e6-9728-58dc89a362c1.png)

This is my cntk folder in C:\local\CNTK-2-0-beta1-0-Windows-64bit-GPU\cntk

**Comment by raaaar** [comment]
Please install the latest release instead: https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta5.0

**Comment by GopikrishnanSasikumar** [comment]
@raaaar  thank you !
