### ISSUE TITLE
CNN Text Classification

### ISSUE THREAD

**Issue by SivilTaram** [Microsoft/CNTK#1102]
Hi, thanks for your big effort on CNTK :) I want to apply CNTK in text classification using CNN. So I learned the usage of CNN from the example [Image](https://github.com/Microsoft/CNTK/blob/dd496e5111b8aa1d29e3974093d063e5eb4eab78/Examples/Image/Classification/ConvNet/BrainScript/ConvNet_MNIST.cntk). And I see the image shape is always like the format:
`28:28:1`, so I estimated it in text. I use the shape like this one:
`textshape: $seqlength$:$vocabsize$:1` ( If I ignore the `:1`, the ConvolutionalLayer will throw exception)

> seqlength is the max sequence length and the vocabsize is the size of vocabulary. The input uses one-hot encoding.

My input file's format like this:
```
0 |word 0:1 |label 1 0
0 |word 1:1
0 |word 2:1
0 |word 3:1
0 |word 4:1
0 |word 5:1
0 |word 0:1
1 |word 8935:1 |label 0 1
1 |word 23:1
1 |word 2698:1
1 |word 11:1
1 |word 5442:1
1 |word 18764:1
1 |word 18764:1
```
The input is like this:
```
t = DynamicAxis{}
features = Input (textShape,dynamicAxis=t,tag='feature')
```

The reader is like this:
```
reader = {
        readerType = "CNTKTextFormatReader"
        file = "review.ctf"
        input = {
            features = [
		alias = "word"
		dim = 131348 # 131348 = 7 * 18764, 7 is the length of max sequence, 18764 is the size of vocabulary
		format = "sparse"
	    ]
            labels =   [
		alias = "label"
		dim = 2
		format = "dense"
	    ]
        }
    }   
```

But now I have encountered the exception:
```
EXCEPTION occurred: zp ReconcileDynamicAxis operation discovered that z Plus operation produced an MB layout that is incompatible with that of labels InputValue.
```

I don't know how to edit the ConvolutionalLayer to fit the Text Classification. Do you have any advice? I'd appreciate it. Thanks a lot!

**Comment by cha-zhang** [comment]
This should have been resolved by the latest Python API. Closing it now. If issue remains, please open a new issue.
