### ISSUE TITLE
How to read and modify the training model weights using python API?

### ISSUE THREAD

**Issue by vgupta123** [Microsoft/CNTK#1103]
I want to read and modify the training weights according to my own update scheme. Please forward me to the python API calls or examples necessarily doing the same.

**Comment by mahilleb-msft** [comment]
Please checkout out https://cntk.ai/pythondocs/extend.html#user-defined-learners; feel free to re-open the issue (or file a new one) if this doesn't satisfy your needs.

Best, Mark
