### ISSUE TITLE
CNTK Examples: Image/Classification/ResNet/Brainscript new dataset?

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#1104]
Hi,

I did the "cntk configFile=ResNet20_imdb.cntk" (adapt from ResNet20_CIFAR10.cntk) with a new dataset but only worked if I set all the images to 32x32. I would like to work with a bigger size, maybe 512x512 or 256x256. 

What changes need I implement to achieve this? I already tried with 256 and 512 with some changes on ResNet20_imdb.cntk and on the imdb_mean.xml file but got errors.

Thks,

**Comment by KeDengMS** [comment]
ResNet*_ImageNet1K.cntk shows ResNet with input scaled to 224x224x3.

**Comment by pmfcdb** [comment]
So I adapted  and tested with ResNet50_ImageNet1K.cntk and I got an error: ResNet_50_BS_out ( I'm using CNTK-2-0-beta4-0-Windows-64bit-GPU ) 
- parallelTrain is false, but with parallelTrain=true is the same

Error LOG
---------------------------------------------------------------------
Build info: 
		Built time: Nov 21 2016 06:33:04
		Last modified date: Mon Nov 21 06:00:57 2016
		Build type: Release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
		CUB_PATH: c:\src\cub-1.4.1
		CUDNN_PATH: c:\NVIDIA\cudnn-5.1\cuda
		Build Branch: HEAD
		Build SHA1: 185c0cb6962c0cc0b252c65117073f3781d9ef67 (modified)
		Built by svcphil on liana-08-w
		Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
-------------------------------------------------------------------
-------------------------------------------------------------------
GPU info:
Device[0]: cores = 1920; computeCapability = 5.2; type = "GeForce GTX 970M"; memory = 6144 MB
.....
No PreCompute nodes found, or all already computed. Skipping pre-computation step.

Starting Epoch 1: learning rate per sample = 0.003906  effective momentum = 0.900000  momentum as time constant = 2429.8 samples

Starting minibatch loop.
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=DESKTOP-GRH4AIB ; expr=cudnnConvolutionBackwardFilter(*m_cudnn, &C::One, m_inT, ptr(in), m_outT, ptr(srcGrad), *m_conv, m_backFiltAlgo.Algo.algo, ptr(workspace), m_backFiltAlgo.Algo.memory, &C::One, *m_kernelT, ptr(kernelGrad))


[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - BaseThreadInitThunk
    - RtlUserThreadStart

EXCEPTION occurred: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=DESKTOP-GRH4AIB ; expr=cudnnConvolutionBackwardFilter(*m_cudnn, &C::One, m_inT, ptr(in), m_outT, ptr(srcGrad), *m_conv, m_backFiltAlgo.Algo.algo, ptr(workspace), m_backFiltAlgo.Algo.memory, &C::One, *m_kernelT, ptr(kernelGrad))

**Comment by cha-zhang** [comment]
It appears that you have run out of GPU memory. Could you try reducing the minibatch size?

**Comment by pmfcdb** [comment]
Ok, I lower the minibatchSize in adapted ResNet50_ImageNet1K.cntk from 256 to 16, and it worked! I tried several values 20,32,64,128 and all got the memory error. 

Is there a tool to calculate the mean.xml file of a dataset?

**Comment by cha-zhang** [comment]
Resnet152 certainly consumes more memory and it's necessary to run on hyperCompressMemory. 

We don't have an existing too compute the mean.xml file. We will create one later.

**Comment by pmfcdb** [comment]
Ok, thks for the help!
