### ISSUE TITLE
Python APIs: How to encode sequence information for a recurrent net?

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#1105]
Hi,
I am doing vector to vector regression and would like to learn how I could inform an LSTM network that, say, first 5 records belong to the sequence 1, and the next 15 to the sequence 2, etc.
In BS I used CNTKTextFormatReader, with first column of the data file providing this information. But how I can do it if I want to use numpy arrays (perhaps modified dynamically during the program run) as the data source?

Regards,
Slawek

**Comment by eldakms** [comment]
CNTKTextFormatDeserializer is available for python as well. Also please have a look at Manual/Manual_how_to_feed_data on the latest master. Thanks!
If this does not help feel free to reopen!
