### ISSUE TITLE
1BitSGD Error

### ISSUE THREAD

**Issue by such87** [Microsoft/CNTK#111]
When I am trying to clone the 1 Bit SGD code I get an error like this :

 CNTK]$ git submodule update --init --recursive

Cloning into 'Source/1BitSGD'...
fatal: unable to access 'https://git.codeplex.com/cntk1bitsgd/': The requested URL returned error: 500
Clone of 'https://git.codeplex.com/cntk1bitsgd' into submodule path 'Source/1BitSGD' failed

Please let me know what I maybe doing wrong here..

Thanks

**Comment by friskit-china** [comment]
I got the same error 5min ago

**Comment by friskit-china** [comment]
I think this may caused by the crash of CodePlex. All repository on CodePlex cannot checkout now.

**Comment by NickWeintraut** [comment]
Thanks! I was having the same error, glad to know it was most likely just a temporary crash.

**Comment by wolfma61** [comment]
I just tried ... it is working for me now..

**Comment by friskit-china** [comment]
@wolfma61 Thank you for your notification. It works now.
