### ISSUE TITLE
Truncated BPTT

### ISSUE THREAD

**Issue by karolkuna** [Microsoft/CNTK#1110]
Hello,
I am training an LSTM network on very long sequences (thousands of samples). I set truncated to true and truncationLength to 100 in my reader config, but I wasn't able to find any information on how exactly is the truncated BPTT implemented in CNTK.

Is it the true truncated BPTT which processes the sequence one step at a time and propagates error for up to truncationLength steps?
Is it epochwise BPTT which splits the sequence into subsequences of length truncationLength and then runs standard BPTT on them?
Or are the sequences simply truncated not to be longer than truncationLength?

Could someone clarify it, please?

**Comment by eldakms** [comment]
It is the true truncated BPTT (sequences are also split between minibatches)
