### ISSUE TITLE
Training a Fast R-CNN model with a GPU

### ISSUE THREAD

**Issue by tolisElectro** [Microsoft/CNTK#1111]
I have trained a Fast R-CNN model on my own data according to https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#run-the-toy-example and would like to train it on a GPU. Other than making the appropriate changes to the config file for enabling parallelism, do I have to change the python script  A2_RunCntk.py ?  Do I run it with mpiexec -n %num_workers% python A2_RunCntk.py ?

**Comment by cha-zhang** [comment]
No change needed as far as I'm aware of.

**Comment by tolisElectro** [comment]
Thank you for the immediate response !

**Comment by tolisElectro** [comment]
Do I actually need to set parallelTrain = true and use DataParallelSGD in the config file for one GPU , or it only concerns a multiple-GPU system ?

**Comment by cha-zhang** [comment]
Setting parallelTrain=true only if you have multiple GPUs.

**Comment by tolisElectro** [comment]
OK , thank you . So from what I understand there is no need for any change whatsoever. The "Auto" value in deviceId will choose the GPU , provided there is one cuda-compatible installed with all the necessary drivers.
