### ISSUE TITLE
when CTC will be available?

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1112]
Hi

CTC should be released on 1.8 release, but this version never have been released!! Is there any plan to implement and release CTC? If yes, please let us know about it.

regards.

**Comment by cha-zhang** [comment]
It's on our roadmap, but currently we don't have anyone working on it due to many other tasks. If anyone is willing to contribute, please help!

**Comment by mahilleb-msft** [comment]
Seems a duplicate of #1491, which is resolved, please checkout there.
