### ISSUE TITLE
GetMinibatchToTrainOrTest() warning during training

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1113]
#Hi

I get following warning during training LSTM on my speech dataset. What is the meaning of this?

> getbatch: getting utterances 27..27 (404 subset of 404 frames out of 512 requested) in sweep 0
getbatch: getting utterances 28..28 (486 subset of 486 frames out of 512 requested) in sweep 0
GetMinibatchToTrainOrTest(): WARNING: Packing a second utterance did still not fill all time slots; filling slots from 489 on as gaps.
getbatch: getting utterances 29..29 (423 subset of 423 frames out of 512 requested) in sweep 0
getbatch: getting utterances 30..30 (636 subset of 636 frames out of 512 requested) in sweep 0

My GPU utilization will degrade to about 60 percentages when this warning thrown out, and the problem is there is too much of them(about 14% of mini-batches have this problem).
Please guide me how to fix it? Any help is appreciated.
Regards

**Comment by eldakms** [comment]
Please set verbosity in the reader = 0. You also use old readers, we advise to switch to deserializers instead. Thanks!
