### ISSUE TITLE
Sequences vs randomization and minibatches

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#1114]
Hi all, apologies if these are FAQs- I didn't find any obvious answers in the docs or the code.

1. Is it safe to assume that input randomization preserves sequence sample locality and ordering? (ie sequenceID X is relocated in totality and its internal order is preserved).
2. Judging from the CNTKTextReader docs, a minibatch size indicates the number of samples to return, rather than the number of sequences to return, correct?
3. What is the effect of choosing a minibatch size that's smaller than some sequence length? 
4. Are sequences always sampled in totality for a minibatch operation?  That is, will a sequence ever be split across minibatches?

Thanks,
Rob

**Comment by eldakms** [comment]
sorry for the late response.
1) Yes if you use sequence mode (default), samples are not randomized inside a sequence, only sequences
2) Correct, minibatch size is always in samples
3) The reader always returns at least a single sequence even if its size > than mb_size. If there is already a sequence inside the minibatch and the newly added sequence will exceed it - then it is not added. For more information please have a look here: https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-epochsize-and-python-epoch_size-in-cntk
4) No, one sequence cannot be splitted between 2 different minibatches (i.e. half in one minibatch,half - in the other).
