### ISSUE TITLE
CNTKText: Move sequence indexing out of open()

### ISSUE THREAD

**Issue by cmarschner** [Microsoft/CNTK#1115]
Right now CNTKText does a full scan of the input file to detect sequence boundaries and creates an in memory index of them.
Since models change more often than input data in many cases, it would be desirable if this could become a separate process. E.g. the API should allow for creating that index and storing it on disk, or reusing it when the file is opened.

**Comment by mahilleb-msft** [comment]
@raaaar is on this...

**Comment by eldakms** [comment]
This will be included in the next release.
