### ISSUE TITLE
CNTK_202_Language_Understanding - run a sequence through - Error:tuple index out of range

### ISSUE THREAD

**Issue by anuazeez** [Microsoft/CNTK#1118]
I am running the sample program explained in CNTK_202_Language_Understanding. It is error ing out on line pred = model.eval({model.arguments[0]:onehot})
Further research took me to https://www.cntk.ai/pythondocs/_modules/cntk/ops/functions.html#Function.eval.

But the description here is also not help full to resolve it.
Please help

**Comment by anuazeez** [comment]
Looks like the input variable 'query' should be initialized as sparse, but it is set to sparse = false. Changing this to sparse= true. is now giving 'Microsoft::MSR::CNTK::Matrix<float>::FSAdagradUpdate  -> Feature Not Implemented.'

**Comment by anuazeez** [comment]
Finally I was able to get it working. Issue turn out to be some adjustments in the input variable shapes

**Comment by haricntk** [comment]
@anuazeez 
can you please post the code changes that you did.
