### ISSUE TITLE
Incompatible model format between Windows and Linux on latest model-v1 format (16).

### ISSUE THREAD

**Issue by wishstudio** [Microsoft/CNTK#1124]
The issue is in the commit [Properly checkpoint stateful nodes](https://github.com/Microsoft/CNTK/commit/ce0d0c7d4601ca2185cd6bb8464930951b3d8a95) which bumped the model format to 16.

In this commit two new fields (```seed```, ```offset```) are serialized for DropoutNode. However the ```seed``` field is defined as type ```unsigned long```. This will result in different byte length between the platforms as ```sizeof(unsigned long)``` is defined to be 4 on x64 Windows instead of 8 on Linux.

I found this issue when I'm trying to load and evaluate a model trained on a Linux machine. The model loading procedure immediately died when loading a node subsequent to the Dropout node.

By changing the line ```unsigned long seed;``` to ```unsigned long long seed;``` in 
(https://github.com/Microsoft/CNTK/commit/ce0d0c7d4601ca2185cd6bb8464930951b3d8a95#diff-317e37388100cc252ac54d6892a73432R289) and add a cast in the subsequent ```SetRngState``` call I can successfully load the model.

However this is just a dirty hot fix for my use case. Currently the cross platform format compatibility is completely broken and a more proper fix should be prepared.

**Comment by raaaar** [comment]
Thanks for reporting! We'll try to get this fixed in an upcoming release.
