### ISSUE TITLE
cntk python api   -   Is cntk.model.load_model functional?   I keep getting an error message   

### ISSUE THREAD

**Issue by thinus-potgieter** [Microsoft/CNTK#1129]

**Comment by thinus-potgieter** [comment]
The error message is

NotImplementedError: Wrong number or type of arguments....

**Comment by raaaar** [comment]
The current syntax is

from cntk.ops.functions import load_model
z = load_model("/path/to/the/model/file/mycnn.dnn")
Here's an example: https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network

**Comment by mahilleb-msft** [comment]
Closing; please re-open or open a new issue if it doesn't work for you. Thanks!
