### ISSUE TITLE
Error: internal error: invalid thread id

### ISSUE THREAD

**Issue by chivee** [Microsoft/CNTK#113]
Hi all,

is anyone encounter the problem "Error: internal error: invalid thread id" with LSTM model on TIMIT dataset.

I'm using the latest code (e1093b9) of master branch.

> Allocating matrices for forward and/or backward propagation.
> 
> Precomputing --> 3 PreCompute nodes found.
> 
>   NodeName: featNorm.xMean
>   NodeName: featNorm.xStdDev
>   NodeName: logPrior.Prior
> minibatchiterator: epoch 0: frames [0..1124823](first utterance at frame 0), data subset 0 of 1, with 1 datapasses
> requiredata: determined feature kind as 72-dimensional 'FBANK_D_A_Z' with frame shift 10.0 ms
> 
> Precomputing --> Completed.
> 
> Set Max Temp Mem Size For Convolution Nodes to 0 samples.
> Starting Epoch 1: learning rate per sample = 0.000100  effective momentum = 0.000000  momentum as time constant = 0.0 samples
> minibatchiterator: epoch 0: frames [0..1124823](first utterance at frame 0), data subset 0 of 1, with 1 datapasses
> 
> Starting minibatch loop.
> Error: internal error: invalid thread id

**Comment by wolfma61** [comment]
there have been many fixes and changes in this area since then. If you experience this problem with the most recent bits, please open a new issue...
