### ISSUE TITLE
LSTM only works with default arguments

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#1130]
Hi,
I have problem creating an LSTM net. I can only succeed if I use default arguments, e.g.
def createLSTMnet(input_var , hidden_layer_dim1, output_dim):
  r=l.Recurrence(l.LSTM(hidden_layer_dim1))(input_var)
  return linear_layer_withNoBias(r, output_dim)
but if I change anything, e.g
def createLSTMnet(input_var , hidden_layer_dim1, output_dim):
  r=l.Recurrence(l.LSTM(hidden_layer_dim1, cell_shape=output_dim))(input_var)
  return r
or
def createLSTMnet(input_var , hidden_layer_dim1, output_dim):
  r=l.Recurrence(l.LSTM(hidden_layer_dim1, 
    use_peepholes=True))(input_var)
  return linear_layer_withNoBias(r, output_dim)

and execute 
z = createLSTMnet(input , HIDDEN_DIM1, OUTPUT_SIZE)
I am getting 
CNTK Function expected 5 arguments, got 3

Regards,
Slawek

**Comment by eldakms** [comment]
Please try on the latest master/binaries(v2). Feel free to reopen if still relevant. Thanks!
