### ISSUE TITLE
Is any way to train a Word Embedding model by cntk

### ISSUE THREAD

**Issue by AllanYiin** [Microsoft/CNTK#1131]
althouth traditional Word2vec is good, but we want to try some research in Chinese w2v, and we want to include the "ordinal" of the context into custom word embedding. Is there any way to use exsiting stucture to train a similar one ? We want to try di-LSTM+Embedded , is ther any reference script or document for it?

**Comment by eldakms** [comment]
Please have a look at the tutorials. Closing the issue due to inactivity. Feel free to reopen.
