### ISSUE TITLE
Continue training a model

### ISSUE THREAD

**Issue by thinus-potgieter** [Microsoft/CNTK#1133]
I have run  the CNTK 203: Reinforcement Learning Basics python code>   How do I change  the code to save not restart but continue training the same model

(https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_203_Reinforcement_Learning_Basics.ipynb)

**Comment by raaaar** [comment]
Adding `agent.brain.model.restore_model('dqn.mod')` right after `agent = Agent()`  should allow you to reload a previously saved model, so that you can continue with the training.

**Comment by mahilleb-msft** [comment]
Closing this one as it is answered. Please re-open (or open a new issue) if the answer doesn't work for you. Thanks!
