### ISSUE TITLE
Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.cpp:134:76: error:format ‘%d’ expects argument of type ‘int’  

### ISSUE THREAD

**Issue by popoala** [Microsoft/CNTK#1135]
Hi, there.
I am building CNTK with " ../../configure --with-mkl=/usr/local/CNTKCustomMKL --with-nccl=/usr/local/nccl --with-kaldi=../../../../../kaldi-trunk --1bitsgd=yes".  And encountered with this error:
==========================> Here's the message <============================
mpic++ -c Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.cpp -o /home/name/develop/cntk/cntk-repo/cntk/build/release/.build/Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DUSE_MKL -DNDEBUG -DNO_SYNC -DCNTK_PARALLEL_TRAINING_SUPPORT -DASGD_PARALLEL_SUPPORT  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -DUSE_ZIP -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/CNTKv2LibraryDll/proto -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/local/protobuf-3.1.0/include -I/usr/local/CNTKCustomMKL/2/include -I../../../../../kaldi-trunk/src -I../../../../../kaldi-trunk/tools/ATLAS/include -I../../../../../kaldi-trunk/tools/openfst/include -ITests/UnitTests/V2LibraryTests -I/usr/local/boost-1.60.0/include -I/usr/local/include -I/usr/local/lib/libzip/include -I/usr/local/opencv-3.1.0/include -ISource/1BitSGD -ISource/Multiverso/include -I/usr/local/boost-1.60.0/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF /home/name/develop/cntk/cntk-repo/cntk/build/release/.build/Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.d

Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.cpp:134:76: error: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘Microsoft::MSR::CNTK::DeserializerType’ [-Werror=format=]
             RuntimeError("Unknown deserializer type %d requested.", desType);
                                                                            ^
cc1plus: all warnings being treated as errors
Makefile:1274: recipe for target '/home/name/develop/cntk/cntk-repo/cntk/build/release/.build/Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.o' failed
make[1]: *** [/home/name/develop/cntk/cntk-repo/cntk/build/release/.build/Source/Readers/CNTKBinaryReader/BinaryChunkDeserializer.o] Error 1
make[1]: Leaving directory '/home/name/develop/cntk/cntk-repo/cntk'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
========================> end message <=======================
I'm running this in Ubuntu 16.04 with cuda 8.0. Actually, I git clone the source code yesterday and can built CNTK with boost-1.62.0 and without asgd.  But I encountered this error with boost-1.60.0 and 1bit-SGD.

**Comment by junjieqian** [comment]
A quick fix can be `RuntimeError("Unknown deserializer type %d requested.", (int32_t)desType);`

**Comment by popoala** [comment]
Thanks to @junjieqian. It works. I wonder if it would cause any problem later.
