### ISSUE TITLE
if ... then conditionals in config file

### ISSUE THREAD

**Issue by diospyros** [Microsoft/CNTK#1136]
Trying to put together a master config file (*.cntk) that will allow me to select regression or classification via a variable flag but can't seem to get the if then conditionals to work the way I want them to. What am I missing?

Example blurb as follows taken from the .cntk file (using version 2.0):

command = TrainConvNet
makeMode = false ; traceLevel = 1
deviceId = 0
rootDir = ".."
#image_layout = cudnn
model_t = classification

if "$model_t$" == "classification" then
{
Fail ("1")
	#dataDir   = "$rootDir$/Data"
	dataDir = "C:/Users/stuff/Examples/Image/DataSets/MNIST" 
	configDir = "$rootDir$/Config"
	outputDir = "$rootDir$/Output"
	modelDir  = "$outputDir$/Models"

	lbl_num = 10
	img_width = 28
	img_height = 28
	img_channels = 1
	img_dim = 784  # w*h*channels
	data_file_name = Train-28x28_cntk_text.txt
	precision = "float"
	outputNodeNames = ScaledLogLikelihood

	numMBsToShowResult = 500
}
else if "$model_t$" == "regression" then
{
Fail ("2")
	dataDir  = "$rootDir$/DataSets/CIFAR-10"
	outputDir = "Output" ; modelDir = "$outputDir$/Models"
	modelPath = "$ModelDir$/RegrSimple_CIFAR10.cmf"
	
	image_shape = 32:32:3
	lbl_num = 3
}
else Fail ("Invalid model selector value.")

It doesn't seem to recognize the if ... then statement as a logical condition test. Is there a C-style preprocessor condition test that might work?

**Comment by eldakms** [comment]
Please switch to Python if possible. It is the way forward for CNTK. Closing the issue for now, feel free to reopen if still relevant. THanks!
