### ISSUE TITLE
Faster video object detection and classification using YOLO

### ISSUE THREAD

**Issue by robertvteci** [Microsoft/CNTK#1137]
Is there a way to port the concepts used in YOLO (You Only Look Once) to CNTK to get high performance using CNTK which matches or exceeds YOLO?

**Comment by cha-zhang** [comment]
Of course you can! :) We have limited resources, and we can't implement every algorithm out there. It would be great if you can contribute a recipe to do YOLO. If you encounter and issues or missing features, let us know an we will enable it on our side. Thanks!

**Comment by nadavbar** [comment]
+1 on this, I'll be happy to join the effort in case someone is already working on it

**Comment by eldakms** [comment]
Please contact wilrich-msft, he is working on this. When this becomes available there will be a separate announcement on the release notes. Feel free to reopen. Thanks!
