### ISSUE TITLE
build fail: cannot find -lmultiverso    /cntk/build/release/lib/libeval.so' failed

### ISSUE THREAD

**Issue by stjordanis** [Microsoft/CNTK#1138]
After:  ../../configure --with-mkl=/usr/local/CNTKCustomMKL  --with-swig=$HOME/swig-3.0.10/root --with-py34-path=$HOME/anaconda2/envs/cntk-py34  --asgd=yes
make all fails
I get:
collect2: error: ld returned 1 exit status
Makefile:556: recipe for target '/home/steliox/cntk/build/release/lib/libeval.so' failed
make[1]: *** [/home/steliox/cntk/build/release/lib/libeval.so] Error 1
make[1]: Leaving directory '/home/steliox/cntk'
Makefile:6: recipe for target 'all' failed

**Comment by junjieqian** [comment]
Did you clone recursively? Or, can you check `Multiverso` exists in `Source` dir?

**Comment by stjordanis** [comment]
I used the command:
 git clone https://github.com/Microsoft/cntk    
according to https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux

and then in the directory cntk/ , I used:
git submodule update --init Source/Multiverso
so, yes, Multiverso exists in Source dir (299 items, totalling 1,3 MB)

**Comment by stjordanis** [comment]
By the way, thank you very much for the prompt reply.

I am under the impression that the value of  lmultiverso  variable is not defined  anywhere within the make file (up to line 556, where it fails, but also afterwards in the make file).
I am not an expert in c++/make files to improvise passing values by tampering with the make file, though.

**Comment by stjordanis** [comment]
I also tried 
git clone --recursive https://github.com/Microsoft/CNTK
but the same problem persists.

**Comment by mkiernan** [comment]
I had the same issue; the workaround I'm using for now is --asgd=no: 
../../configure --1bitsgd=yes --asgd=no

**Comment by stjordanis** [comment]
@mkiernan thanks mate, this is it.....
 I hope they activate these features again, they sound interesting.... Kaldi reader is also not included in the instructions for the current linux version
