### ISSUE TITLE
ResNet Pretrained Model (ResNet_200 or ResNet_1K) for CNTK

### ISSUE THREAD

**Issue by jhalakpatel** [Microsoft/CNTK#1139]
Hi,

I am looking for PreTrained ResNet_200 or ResNet_1K model for CNTK. 
I also found that ResNet_200 for torch is available here : [https://github.com/facebook/fb.resnet.torch/tree/master/pretrained](url). Is there is any way to port the model for CNTK Evaluation Usages.

**Comment by mfuntowicz** [comment]
Hi @jhalakpatel , 

Previous versions of CNTK provided pretrained ResNet models : 
https://github.com/Microsoft/CNTK/tree/v1.7.2/Examples/Image/Miscellaneous/ImageNet/ResNet (bottom of the page)

It's using the old format CNTK model.

Hope it's help.
Morgan

**Comment by jhalakpatel** [comment]
Hi,

Does the new format CNTK model compatible with EvalDll APIs for Evaluation. I am working with [https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CSEvalClient](url) example for EvaluateInputImageUsingFeatureVector example which consumes a PreTrained Network?

Also, for newer model, I understand that we have [https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet152_ImageNet1K.cntk](url) brainscript to train for newer model. Do we have similar brainscript i.e. ResNet[200 or 1K] _ImageNet1K.cntk

**Comment by zhouwangzw** [comment]
@jhalakpatel  I am not sure about what you mean about "new format CNTK model" and "newer model.". Basically, any CNTK model trained with BrainScript can be loaded by EvalDll APIs. For models trained by CNTK V2 Python, we are currently working a new C# Eval API for evaluation, which will be available very soon.

**Comment by cha-zhang** [comment]
ResNet 200 or 1K can be written in Python or Brainscript following the ResNet152 example. We will post codes later when we train the models successfully ourselves.

**Comment by anijain2305** [comment]
@cha-zhang Are the models for Resnet200 and 1K available now?

**Comment by cha-zhang** [comment]
Haven't got chance to work on that. Will put this in our task list.

**Comment by anijain2305** [comment]
@cha-zhang Thanks! By any chance, do you have python model for resnet 110. There is Brainscript available for Resnet 110, but there isn't one for Python.

**Comment by cha-zhang** [comment]
The python script will train both resnet20 and resnet110. You can specify that with -n.

**Comment by anijain2305** [comment]
@cha-zhang Sorry, I meant resnet 152. Resnet 152 is only available for Brainscript. 

I am hunting for the deepest networks that are already implemented in Python in CNTK. Though having hyperparameters will be really helpful for the deeper networks, but as of now having a python model will be good enough for me.

**Comment by cha-zhang** [comment]
Since we already have the BrainScript file, and the CIFAR10 Python example, writing one is easy. But we always verify our scripts by an end-to-end training, and that takes some time. We will have someone working on it starting maybe next week.

**Comment by anijain2305** [comment]
@cha-zhang I understand. Thanks for replying so promptly. I will wait for the models.

**Comment by eldakms** [comment]
Closing the issue for now, please feel free to reopen if needed.
