### ISSUE TITLE
C# and Python bindings

### ISSUE THREAD

**Issue by ernestopedrosa** [Microsoft/CNTK#114]
Any idea when C# and Python packages will be available? BTW will the .net be compatible with .net core (i.e. cross platform)?

**Comment by BorisJineman** [comment]
So far as I Known, The EvalWapper project can be used to resolve your question, and the EvalWapper is an wapper of the CNTK's ExecutionEngine and it is implemented by C++/CLI. I think you can use this to implement some feature?

**Comment by frankseide** [comment]
Yes, the C# wrapper is meant to allow to use CNTK for evaluation from C# projects (which are trained with the CNTK command-line tool).

C++/CLI does not work on Linux though, so this is for now Windows-only.

**Comment by ernestopedrosa** [comment]
Thanks for your answers. BTW do you have any plans to release this as a Nuget package? If yes, will it be compatible with .Net Core? Thansk

**Comment by gaizkan** [comment]
Thank you for your inquiry. We currently don't have a plan to release a NuGet package. However, you are welcomed to submit a request for that. 

Best regards.
