### ISSUE TITLE
What parameters does the embedding layer learn? Otherwise where is the implementation in the source code?

### ISSUE THREAD

**Issue by malexan123** [Microsoft/CNTK#1140]
Hi,

I am trying to train only one layer to get word embeddings as the only output. 

- Can I use a single CNTK embedding layer for this purpose? What parameters does an embedding layer learn in general and how is the output vector calculated as a function of the input?

- Is there a word2Vec implementation on CNTK?

- If nobody knows or has no time to answer fully, could you point me to the source code location where I can find how the Embedding layer works? 

I am new to CNTK and I apologize in advance if what I am asking is something widely known.

Thank you

**Comment by arijit17** [comment]
read here:
https://www.cntk.ai/pythondocs/layerref.html#embedding

**Comment by malexan123** [comment]
I guess the question might have been confusing. I was wondering if the embeddings layer gets trained based on word context similarly to word2vec. Probably not so I will close it.
