### ISSUE TITLE
Compute LogisticNode error

### ISSUE THREAD

**Issue by rosrad** [Microsoft/CNTK#1141]
The ForwardPropNonLooping of LogisticNode is used to compute the value of Logistic(labels, prediction) .
I found that it show the computation expression as below in the code:
```
   // -sum(left * log(right) + (1-left)*log(1-right)) (optionally * weight)
    virtual void /*ComputationNodeNonLooping::*/ ForwardPropNonLooping() override

```
However I found that the log operation is applied after computing y*p + (1-y)*(1-p).
in code:
```

      /* Finally compute result = 2*y*p + (1-y) - p */
        m_result->AssignDifferenceOf(*m_result, classOneProbabilities);

        // compute the log, resulting in y*log(p) + (1-y)*log(1-p)
        m_temp->AssignLogOf(*m_result);
```

how can log(y*p + (1-y)*(1-p)) becomes y*log(p) + (1-y)*log(1-p)?

anyone could explain this? or is this an implement bugs?

code commit: e7edfa7 on master branch.

Thanks

**Comment by cha-zhang** [comment]
I believe y is either 0 or 1. Thus implementing it inside log will be faster than outside, it's probably also more stable numerically.
