### ISSUE TITLE
Sequence of sentences shuffling in CNN

### ISSUE THREAD

**Issue by SivilTaram** [Microsoft/CNTK#1142]
Hi, I have a question about sequence of sentences shuffling.

My task is to do classification in text using CNTK, and I want to use the example CNN Model [OneConvDropout](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/GettingStarted/03_OneConvDropout.cntk)  to do it.
The task of sentences are different from image and we should shuffle the sequence of sentences between epoch.

So I want to know whether the example CNN Model will shuffle the train data between two epochs? If not, how to solve the problem ? I'd appreciate it if you have any advice, thanks a lot!

**Comment by eldakms** [comment]
CNTKTextReader randomizes the sequences when sweep/(or epoch) is crossed. You can control this with randomize=True/False property.
