### ISSUE TITLE
Script install fails on miniconda base with exit code [1]

### ISSUE THREAD

**Issue by onebitbrain** [Microsoft/CNTK#1146]
Hello, 
This is only a minor annoyance but script install fails for some reason here when it probably shouldn't.  

>PS C:\local\cntk\Scripts\install\windows> .\install.ps1 -Execute -AnacondaBasePath "C:\Users\Sam Miller\Miniconda2"

>This script will setup the CNTK prequisites and the CNTK Python environment onto the machine.
More help is given by calling 'get-help .\install.ps1' in your powershell environment.

>The script will analyse your machine and will determine which components are required.
The required components will be downloaded in [C:\local\cntk\Scripts\install\windows\InstallCache]
Repeated operation of this script will reuse already downloaded components.

 >- If required VS2012 Runtime and VS2013 Runtime will be installed
 >- If required MSMPI will be installed
 - Anaconda3 will be installed into [C:\Users\Sam Miller\Miniconda2]  **#Why?**
 >- A CNTK-PY34 environment will be created or updated in [C:\Users\Sam Miller\Miniconda2\envs]
 >- CNTK will be installed or updated in the CNTK-PY34 environment

>1 - I agree and want to continue
Q - Quit the installation process

>1
>Determining Operations to perform. This will take a moment...

>The following operations will be performed:
> * Setup CNTK PythonEnvironment 3.4
 >* Setup/Update CNTK Wheel
 >* Create CNTKPY34 batch file

>Do you want to continue? (y/n)
y
Performing download operations
Download operations finished

>Performing install operations

>Fatal error during script execution!
 System.Management.Automation.RuntimeException: Running 'start-process  env create --file C:\local\cntk\Scripts\install\windows\conda-windows-cntk-py34-environment.yml --prefix C:\Users\Sam Miller\Miniconda2\envs\cntk-py34' failed with exit code [1]

**I was able to easily overcome it via manual install like so:**

> C:\Users\Sam Miller\Miniconda2\Scripts>conda env create --file c:\local\cntk\scripts\install\windows\conda-windows-cntk-py34-environment.yml

But this probably shouldn't be necessary.

**Comment by fcivardi** [comment]
I have a similar error, but because I had a previous CNTK 2.0 installed, the message is System.Management.Automation.RuntimeException: Running 'start-process env update --file............

**Comment by fcivardi** [comment]
The command I see is "start-process env  create", or, in my case "start process env update...". Should it be "start process conda env ..." ?

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
