### ISSUE TITLE
Custom Loss Functions in Python

### ISSUE THREAD

**Issue by paulsimmons999** [Microsoft/CNTK#1148]
Hi,

Is it possible to create custom loss functions in Python? Existing CNTK documentation specifies doing it in BrainScript but can't find a way to implement to Python API.

Thanks.

**Comment by cha-zhang** [comment]
Certainly you can in Python. An example would be: 
https://github.com/Microsoft/FERPlus 
It has custom loss functions here: 
https://github.com/Microsoft/FERPlus/blob/master/src/train.py

**Comment by paulsimmons999** [comment]
Thank you for your answer.

When I copy/paste the custom error to my model I get an error at reduce_sum. My final layer (z) is a dense layer with 2 outputs.

def my_loss(prediction, target):
    d = ct.negate(ct.reduce_sum(ct.element_times(target, ct.log(prediction)), axis=-1))
    return d
...
ce = my_loss(softmax(z), label_var)

The error I get is "RuntimeError: InnerProduct: Matrices a and b should have same dimension.". How can I learn the proper dimensions of prediction and target and access their elements?

**Comment by cha-zhang** [comment]
You can look at the log and it shall output the size of every node in your network.
