### ISSUE TITLE
ImportError: No module named 'past'

### ISSUE THREAD

**Issue by mogrysama** [Microsoft/CNTK#1149]
Trying to do the example "Object Detection using Fast R CNN" but I can´t go futher than the first part of "Quick guide". Trying to run "A1_GenerateInputROIs.py" in Spyder 3.0.0 but I get the error "ImportError: No module named 'past'". In "selectivesearch.py" line 3 "from past.builtins import cmp" is the source of "ImportError: No module named 'past'" I think. Can anybody help me, how to run this example?

**Comment by rtrahms** [comment]
pip install future

**Comment by samysammour** [comment]
I am using Visual Studio Code and receiving the same problem. I am both new to VSCode and to Python 
can anybody please explain how to install future package with steps?

**Comment by pkranen** [comment]
Open a command line (Windows key --> cmd), activate your python environment that you use (e.g. type `activate cntkdev-py34` if you installed CNTK using the devInstall tool), then type `pip install future`. That should do.

**Comment by Ayanzadeh93** [comment]
you just need to install following command
# pip install future

**Comment by mathpopo** [comment]
ONNX FATAL: Don't know how to translate op NonMaxSuppression
Traceback (most recent call last):
  File "/home/Desktop/maskrcnn-benchmark-onnx_stage-gpu/demo/test_onnx.py", line 6, in <module>
    prepared_backend = caffe2.python.onnx.backend.prepare(model)
  File "/home/anaconda3/envs/pytorch1.2gpu/lib/python3.7/site-packages/caffe2/python/onnx/backend.py", line 712, in prepare
    init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
  File "/home/anaconda3/envs/pytorch1.2gpu/lib/python3.7/site-packages/caffe2/python/onnx/backend.py", line 910, in _onnx_model_to_caffe2_net
    raise RuntimeError('ONNX conversion failed')
RuntimeError: ONNX conversion failed
