### ISSUE TITLE
Error training LSTM

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#1152]
Hi all,
I'm training a LSTM with a dynamic label axis.  I have about 9.9M sequences.  At some point deep into training I hit this error: `FrameRange's dynamic axis is inconsistent with matrix`.  Could someone outline what the error means?  I have verified that I have only one label per sequence ID.  Since we are deep into the training data, and the reader is randomized, I'm not sure where to go to look for data corruption issues.

The code is loosely based on https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceClassification/SimpleExample/Python/SequenceClassification.py

Here is the start of an example input sequence:
````
0 |S 0:1 |L 1 0
0 |S 104:1
0 |S 116:1
0 |S 116:1
0 |S 112:1
0 |S 58:1
...
````

Training halted after minibatch 18190, my minibatch size is 4096. The total number of discrete samples in the data is 1.5B, so it doesn't seem to be crashing at the end of the data.

Here's the full call stack:
````
Traceback (most recent call last):
  File "\\tsclient\c\data_rsim\repex\dnnTrain2\20161206_URLEmbed\trainEvalSequenceEx.py", line 152, in <module>
    error, _, (input_dim,num_output_classes,trainer,classifier_output) = train_sequence_classifier()
  File "\\tsclient\c\data_rsim\repex\dnnTrain2\20161206_URLEmbed\trainEvalSequenceEx.py", line 94, in train_sequence_classifier
    trainer.train_minibatch(mb)
  File "e:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\trainer.py", line 92, in train_minibatch
    updated = super(Trainer, self).train_minibatch(arguments, device)
  File "e:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\cntk_py.py", line 1584, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: Node '__v2libuid__Plus229__v2libname__Plus229' (Plus operation): DataFor: FrameRange's dynamic axis is inconsistent with matrix: {numTimeSteps:1, numParallelSequences:29, sequences:[ 
...
````

**Comment by wilrich-msft** [comment]
Hi simra,

could you share your adaptation in a minimal repro that produces this error?

Thanks,
wr

**Comment by raaaar** [comment]
Could you please try again with the latest master and let us know if you're still getting the same error?

**Comment by simra** [comment]
I am running from the binary releases- I'll try to stand up a binary from source and circle back.

**Comment by raaaar** [comment]
Alternatively, you could try the new beta [release](https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta6.0).

**Comment by eldakms** [comment]
Please check on the latest master/v2. Feel free to reopen if the issue is still relevant. Thanks!
