### ISSUE TITLE
How to make a trainer instance in C++ code?

### ISSUE THREAD

**Issue by kyu899** [Microsoft/CNTK#1153]
Hi.

    SGD = {
        epochSize = 50000
        minibatchSize = 64

        learningRatesPerSample = 0.0015625*10:0.00046875*10:0.00015625
        momentumAsTimeConstant = 0*20:607.44
        maxEpochs = 30
        L2RegWeight = 0.002

        numMBsToShowResult = 100
    }

what is the c++ code that is identical to the above BrainScript?
Especially, I want to know how to give learning rate and momentum-specific parameters in C++ code.

LearningRatePerSampleSchedule learningRatePerSample = ????
 size_t momentumTimeConstant = ???;
double momentumPerSample = ???;
AdditionalLearningOptions additionalOptions;
additionalOptions.l2RegularizationWeight = 0.002;

Trainer trainer(classifierOutput, trainingLoss, prediction, { MomentumSGDLearner(classifierOutput->Parameters(), learningRatePerSample, momentumPerSample , additionalOptions) });

const size_t minibatchSize = 64;
size_t numMinibatchesToTrain = 50000*30;
size_t numMBsToShowResult = 100;

Thank you.

**Comment by eldakms** [comment]
Unfortunately C++ docs are scares. Please have a look at the tests in the Tests folder I.e. something like that:
LearningRatePerSampleSchedule ls({ { 10 * 50000, 0015625 }, {10 * 50000, 0.00046875 }, { 1, 0.00015625}}, 50000);
MomentumAsTimeConstantSchedule ms({ {20 * 50000, 0}, {1, 607.44} }, 1)
