### ISSUE TITLE
where is bdn tools?

### ISSUE THREAD

**Issue by sumu1978** [Microsoft/CNTK#116]
I am trying to get dnn recipe runnning when I am given this error:
"EXCEPTION occurred: Acquire: Failed to open lock file ~/DBN.exe GPGPU querying lock: No such file or directory."

BTW: I have change CNTK/Source/Common/CrossProcessMutex.h a little bit following seide's #62 and still have this error, it seems that DBN.exe is a tool separated from cntk, where to aquire it?

**Comment by frankseide** [comment]
Hi, the problem you describe lies elsewhere. I think the ~ name in Linux is expanded by the shell, and not the OS. I don’t think you can use it from inside a C++ program directly. Would you like to try a different directory, such as /tmp?

Regarding the DBN.exe tool: That is a non-public tool I wrote that we used for training speech models prior to CNTK. CNTK’s lock-file name was chosen to be compatible with that old tool to allow concurrent execution of both tools on the same server.

Thanks,

Frank

**Comment by sumu1978** [comment]
I try /tmp, it works, thanks seide:)
another question....

so cntk tool does not support rbm-pretraining , and only support layer-wise pretraing?
it that right?

**Comment by frankseide** [comment]
Yes, that is correct. Are you interested in that? Maybe it is not too hard to implement it :) Instead of RBM-PT, you could also try a simple auto-encoder with square error, which is similar although not identical to RBM-PT.

**Comment by wolfma61** [comment]
I think we can safely close this one. If there are other open questions, please open a new issue

thx
Wolfgang

**Comment by housebaby** [comment]
@frankseide @wolfma61 
I have the same problem , shown as
"EXCEPTION occurred: Acquire: Failed to open lock file /var/lock/DBN.exe GPGPU querying lock: Permission denied" I am not quite clear about it. Can you explain it to be more clearly.
