### ISSUE TITLE
What's the best way to store and use large data sets?

### ISSUE THREAD

**Issue by dathbe** [Microsoft/CNTK#1163]
The project I'm working on collects new data each day.  After the first few weeks, I'm over a GB in total data (as stored in a txt file), and it's growing every day.  Some of the documentation mentions projects with 500 million data points (much bigger than what I have), so what's the best way to store and handle data sets of that size?  Is there a better format to store them in than txt to be used by CNTK?  Can CNTK train on multiple input files?  I've seen no documentation on how I would write a configuration file to specify two or more input files.
Thanks!

**Comment by eldakms** [comment]
The best way is to store aligned data in binary format using CNTKBinaryDeserializer(more documentation to come in the next couple of weeks). You can also combine data from different deserializers (input files) by using deserializer composition.
I am closing this for now, feel free to reopen. Thanks!
