### ISSUE TITLE
New style ImageReader not reading properly?

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#1165]
I've been using the old style image reader fine for a long time, using something like the following for training (and    similar for output):

   
```
reader=[
    readerType=ImageReader
    file=$ConfigDir$/TrainingData.txt
        randomize=Auto
        features=[
            width=1024
            height=1024
            channels=3 # RGB
        ]
        labels=[
            labelDim=3
        ]
    ] 
```

This works fine,  but I want to move over to the new reader to use a custom transform I've written. However, I can't seem to get the new reader to work on 1024x1024 images (not tried other sizes). This is the replacement code in the .cntk file:

```
    reader = [
        verbosity = 0
        randomize = false # Also tried without this
       
        # A list of deserializers to use.
        deserializers = (
            [   
                type = "ImageDeserializer"
                module = "ImageReader"
                file = "$ConfigDir$/TrainingData.txt"

                # Description of input streams
                input = [
                    features = [
                        transforms = (
                            
                        )
                        # Tried with/without the following, no difference
			#width=1024
			#height=1024
			#channels=3 # RGB						
                    ]
                    labels = [
                        labelDim = 3
                    ]
                ]
            ]
        )
    ] 

```

On investigation it seems the reader is reading a corrupted image. I've uploaded an example:
https://drive.google.com/open?id=0B4dreadgSUU4TjFlbGlBZXNvSUU
(left: input image(png), middle: input features variable written by cntk using old reader, right:  input features variable written by cntk using new reader. Same matlab code used for visualisation in both latter 2 cases).

Any suggestions, or is this a bug?

Thanks

Derek

**Comment by eldakms** [comment]
Hi Derek,

I will have a look and report to you shortly. Do you have some png data I can play with?
Thanks!

**Comment by eldakms** [comment]
Btw, by default the old read always puts Transpose transform. Could you please do the same? Thank you!

**Comment by dmagee** [comment]
Data: https://drive.google.com/open?id=0B4dreadgSUU4VnRUYjdqNlZ3ejg
Small.txt 
 `c:/whatever path/simple.png	0`

So you want me to put this in the new config...:

transforms(
 [
type = "Transpose"
]
)

Will do that now...

Thanks for the prompt response!

D.

**Comment by eldakms** [comment]
Sorry, maybe I was not clear enough try putting 
transforms = (
    [  type = "Transpose"  ]
)
in the new reader.

Thanks!

**Comment by dmagee** [comment]
In fact that fixed it! Thanks. I'm suspecting the current behaviour is less than ideal though.

**Comment by eldakms** [comment]
Probably we should hide Transpose as a transform altogether and apply it silently at the end ourselves. I will raise this to the team. Thanks!

**Comment by dmagee** [comment]
There's another related issue here I've found in that the "Transpose" must be AFTER other transforms or an error is thrown (for RGB images anyway). i.e

This works:
                            [ type = "MyCustomImageReaderTransform" ]:
                            [
                                type = "Transpose"
                            ]

But this doesn't:
                            [
                                type = "Transpose"
                            ]:
                            [ type = "MyCustomTransform" ]:

Giving error:

[CALL STACK]
    > CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - Concurrency::details::_UnrealizedChore::  _CheckTaskCollection
    - CRT_RTC_INITW
    - CRT_RTC_INITW
    - Concurrency::details::  _SetUnobservedExceptionHandler

EXCEPTION occurred: Unexpected sequence provided

N.B. It makes perfect sense why as OpenCV is reading the image fine (I checked that by displaying the image in the transform code) and passing through any other transforms, before finally transpose shapes it into something that isn't an image (I'm guessing) - but is compatible with brainscript (or rather back compatible with brainscript written for the old image reader) , so no subsequent processing that relies on the particular image representation used by OpenCV will work.

My suggestion would be to apply Transpose automatically at the end of the pipeline for RGB images and ignore any instances of Transpose in the pipeline. I'm not sure how it works for Greyscale images though as presumably it isn't an issue there? (I didn't check, but presume the new image reader isn't completely broken). And people may have already written code assuming a non-transposed image? I'd assume there is no code out there based on a non-transposed RGB image though, as that is broken.

I guess the solution depends on whether the brainscript convention for images is row or column major, or if that's up to the user. Obviously a convention was set by the old reader.

Derek

**Comment by eldakms** [comment]
This has been fixed for Python. We apply transpose by default there and do not allow specifying it. Because Python is CNTK's way forward and workaround exists for BrainScript, I am closing this feature for now. Feel free to reopen. Thanks!
