### ISSUE TITLE
ImageDeserializer MeanTransformer needs to scale the mean image

### ISSUE THREAD

**Issue by KeDengMS** [Microsoft/CNTK#1169]
Currently it silently skips the mean shift in MeanTransformer::Apply

    if (m_meanImg.size() == mat.size())
    {
        // If matrix has not been converted to the right type, do it now as maen requires floating point type.
        ConvertToFloatingPointIfRequired(mat);
        mat = mat - m_meanImg;
    }

**Comment by eldakms** [comment]
Currently there is a warning if the size does not match. It can be prescaled offline. 
Please fill free to submit a new feature request if prescaling offline is not an option. Thanks!
