### ISSUE TITLE
Building CNTK

### ISSUE THREAD

**Issue by keerthiskating** [Microsoft/CNTK#117]
I am trying to setup CNTK on my linux system(8GB RAM and Tesla C2050 GPU).Everything went smooth till "Building CNTK".
On reaching this step there's an instruction "../../configure".On executing it says to run "make -j all."After running the make command the system hangs .RAM is completely occupied.Please help me.Thanks in advance

**Comment by pineking** [comment]
try to use less threads to make, for example:
make -j 2

**Comment by keerthiskating** [comment]
Thanks it's executing now.But any idea of how much time it will take to execute ?

**Comment by keerthiskating** [comment]
Thanks for your help ! Could you also help me out further ?
