### ISSUE TITLE
Unable to locate boolean flag in Python API for specifying grayscale images as input for Image Reader

### ISSUE THREAD

**Issue by ahfant** [Microsoft/CNTK#1172]
Hi,
if I understand correctly, that the Image Reader currently supports gray scale images, as opposed to only being restricted to BGR channels.
There is also a unit test available to test out this functionality. However, the unit test is performed using BrainScript (.CNTK) 
See [https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/ReaderTests/Config/ImageReaderGrayscale_Config.cntk](https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/ReaderTests/Config/ImageReaderGrayscale_Config.cntk)

I have gone through the Python API but am unable to understand how I can provide this option using ImageDeserializer. Currently, if I were to use grayscale images as input to the network, the training fails terribly. The workaround I have now is to use the CTFDeserializer to feed the images as a flat array.

Thanks!

**Comment by eldakms** [comment]
did you try deserializer['grayscale']=true? Thanks!

**Comment by ahfant** [comment]
Thanks for the quick response! It works now.
Is this documented somewhere?
