### ISSUE TITLE
I can't find 'activate-cntk' file.

### ISSUE THREAD

**Issue by jongchul** [Microsoft/CNTK#1173]
Hi. I've reinstalled cntk beta 0.6 from beta 0.4 on my ubuntu machine using docker file. 
   
When I build beta0.4, I can use acitvate-cntk file which is located in root directory.

    1) https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Script
       Step 3: Verify the setup (Python)
       source "/home/username/cntk/activate-cntk"

    2) move to cntk installed dirctory
   

However I can not find acitvate-cntk file on beta0.6 version.   How I make proper cntk path for beta0.6  version. 
![cntk_pathj_error](https://cloud.githubusercontent.com/assets/6112016/21190526/6e2df022-c265-11e6-9906-f79f00e779bc.jpg)

**Comment by mahilleb-msft** [comment]
Hey, the screenshot you're showing looks like a Docker our source checkout? The instructions you were mentioning are fo installing a binary drop. Could you show what's the contents of the extracted drop now, after running install-CNTK.sh? (ls -l) . Did you activate the CNTK-py35 environment yourself?

Thanks, Mark

**Comment by jongchul** [comment]
It works!!!!!  I've attached screen shots. 

1. downloading the binary-drop and untar it
![cntk-1](https://cloud.githubusercontent.com/assets/6112016/21283351/3fd785e0-c444-11e6-91f5-5738a21e4fb7.jpg)

2. running  install-CNTK.sh
![cntk2](https://cloud.githubusercontent.com/assets/6112016/21283361/5f19922c-c444-11e6-8e28-a0e321b2341c.jpg)
