### ISSUE TITLE
Training vgg9  /w grayscale generates cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by wwindels** [Microsoft/CNTK#1174]
CNTK install: **CNTK-2-0-beta5-0-Windows-64bit-GPU**
Using the CNTK tutorial 201B I got 5 models working with the CIFAR-10 data.  I've since converted to use my .png data  which differs in size and color depth.  ie. (1, 128, 128) grayscale. All tutorial models work fine with my grayscale .png files **except vgg9**.
I get the following error:
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=???????? ; expr=cudnnConvolutionBackwardFilter(*m_cudnn, &C::One, m_inT, ptr(in), m_outT, ptr(srcGrad), *m_conv, m_backFiltAlgo.Algo.algo, ptr(workspace), m_backFiltAlgo.Algo.memory, &C::One, *m_kernelT, ptr(kernelGrad))
Traceback (most recent call last):
  File "PureTrainCNN.py", line 374, in <module>
    pred_vgg = train_and_evaluate(reader_train, reader_test, max_epochs=EPOCHS, model_func=create_vgg9_model)
  File "PureTrainCNN.py", line 249, in train_and_evaluate
    trainer.train_minibatch(data)  # update model with it
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\trainer.py", line 92, in train_minibatch
    updated = super(Trainer, self).train_minibatch(arguments, device)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\cntk_py.py", line 1644, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=???????? ; expr=cudnnConvolutionBackwardFilter(*m_cudnn, &C::One, m_inT, ptr(in), m_outT, ptr(srcGrad), *m_conv, m_backFiltAlgo.Algo.algo, ptr(workspace), m_backFiltAlgo.Algo.memory, &C::One, *m_kernelT, ptr(kernelGrad))

**Comment by cha-zhang** [comment]
Are you using the image reader? Check #1172

**Comment by wwindels** [comment]
I'm using the create_reader / ImageDesealizer etc from CNTK tutorial 201B.  I don't suspect the reader since I can successfully train the other 4 models in that tutorial with my same grayscale images.  It appears specific to the vgg9 model.

**Comment by cha-zhang** [comment]
Is it possible you run out of memory? Have you tried reducing your minibatch size?

**Comment by wwindels** [comment]
Minibatch size is very tiny (16 pictures) and is not the issue. I've run
against  CIFAR-10 with same code with large Minibatch  size. Also works
fine with any other model.

**Comment by eldakms** [comment]
do you pass grayscale=true when creating image deserializers?

**Comment by wwindels** [comment]
I've tried to set grayscale = true in the deserializer. There are lots of examples of how to do this in BS but none in python. If someone could post I would appreciate. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: eldakms <notifications@github.com> Date: 2016-12-15  12:40 AM  (GMT-08:00) To: Microsoft/CNTK <CNTK@noreply.github.com> Cc: wwindels <wwindels0@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Microsoft/CNTK] Training vgg9 /w grayscale generates cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED (#1174) 
do you pass grayscale=true when creating image deserializers?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/CNTK","title":"Microsoft/CNTK","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/CNTK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@eldakms in #1174: do you pass grayscale=true when creating image deserializers?"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/CNTK/issues/1174#issuecomment-267269641"}}}

**Comment by cha-zhang** [comment]
borrow from #1172, try: deserializer['grayscale']=true

**Comment by wwindels** [comment]
Here is my create_reader function.  This still produces the previous error.
So either I don't have the correct syntax yet for setting grayscale = True or there is another issue.
Also, changed minbatchsize = 4 to address previous comments about memory.

def create_reader(map_file, train):
    transforms = []
     deserializer = ImageDeserializer(map_file, StreamDefs(
        features=StreamDef(field='image', transforms=transforms),  # first column in map file is referred to as 'image'
        labels=StreamDef(field='label', shape=num_classes)  # and second as 'label'
    ))
    # CNTK Issue 1172 - did you try deserializer['grayscale']=true? Thanks!
    **deserializer['grayscale'] = True**
    return MinibatchSource(deserializer)

**Comment by wwindels** [comment]
Apologies, reducing the minibatch size from 16 down to 8 makes the error go away.
I have also removed the deserializer['grayscale']=True.  It is a red herring!
