### ISSUE TITLE
NuGet package for V2.0.0 Beta6

### ISSUE THREAD

**Issue by KolyaIvankov** [Microsoft/CNTK#1175]
Not an issue really, but when will the Beta6 version of NuGet package for evaluation be available? Alternatively, how am I to modify the model file if I want to make evaluations with a Beta6 model possible and not getting this exception:

> Read: The model file has a newer format version (16) than this CNTK version can handle (15).

Thanks in advance!

**Comment by zhouwangzw** [comment]
Sorry the trouble. We will publish a new Nuget Package next week. Meanwhile, are you able to use the Beta5 version to train your model?
Thanks,
