### ISSUE TITLE
Not working randomization

### ISSUE THREAD

**Issue by snurkabill** [Microsoft/CNTK#1178]
Hi!

We recently noticed that CNTK does not randomize and for same CNTK config we get the (absolutely) identical error function value. This is not expected from SGD. I also tried dropout (which should be also randomized) and it resulted in the same results. 
So it seems to me that there is: 

no random weights initialization
no randomized input vectors
no randomized dropout 

Maybe some bug about different random seed?  (CNTK version 2.0.6 beta CPU only) 

I provide my CNTK config file with output log of CNTK for completenes.  

CNTK CONFIG:
===========================================================================================

RootDir = /root
deviceId = -1
numCPUThreads = 8
shareNodeValueMatrices = true
command = train
precision = "float"
modelPath = "$RootDir$/CNTKModel"
traceLevel = 1
numMBsToShowResult = 500
initOnCPUOnly = true

```
train = [
    action = "train"
	    BrainScriptNetworkBuilder = [
		# number of features
        featDim = 685
        # number of outputs
        labelDim = 3

features = Input (featDim)
labels = Input (labelDim)

_hiddenDim1 = 32
_hiddenDim2 = 16
_hiddenDim3 = 8

_denseLayer1 = DenseLayer {_hiddenDim1, activation=ReLU, initValueScale=1, init="uniform"} (features)
_denseLayer1drop = Dropout (_denseLayer1)
_denseLayer2 = DenseLayer {_hiddenDim2, activation=ReLU, initValueScale=1, init="uniform"} (_denseLayer1drop)
_denseLayer2drop = Dropout (_denseLayer2)
_denseLayer3 = DenseLayer {_hiddenDim3, activation=Sigmoid, initValueScale=1, init="uniform"} (_denseLayer2drop)
_denseLayer3drop = Dropout (_denseLayer3)
_mojeVrstvicka = LinearLayer {labelDim, initValueScale=1, init="uniform"} (_denseLayer3drop)
_outputLayerPotential = Sigmoid (_mojeVrstvicka)
_lossFunction = SquareError (labels, _outputLayerPotential)
_errors = ErrorPrediction (labels, _outputLayerPotential)

featureNodes    = (features)
labelNodes      = (labels)
criterionNodes  = (_lossFunction)
evaluationNodes = (_errors)
outputNodes     = (_outputLayerPotential)
    ]

SGD = [
epochSize = 0
maxEpochs = 2
minibatchSize = 1
dropoutRate = 0.5
learningRatesPerMB = 0.1
momentumPerMB = 0.0
gradUpdateType = rmsProp
normWithAveMultiplier = true
 rms_wgt_inc = 1.2
 rms_wgt_dec = 0.75
 rms_wgt_max = 10.0
 rms_wgt_min = 0.1
 rms_gamma = 0.99
]

    reader = [
        readerType = "CNTKTextFormatReader"
        file = "/data"
		keepDataInMemory = false
		randomize = True
				randomizationWindow = 20000
		        input = [
            features = [
                dim = 685
                format = "dense"

            ]
            labels = [
			    alias = "target"
                dim = 3
                format = "dense"
            ]
        ]
    ]
]

```

**Comment by raaaar** [comment]
Could you please add the output log (with and without the dropout)?

**Comment by snurkabill** [comment]
The output is different when dropout is 0 or non-zero, but the more runs with same dropout result in same log, that was my point.

**Comment by raaaar** [comment]
The state of random generators is seeded deterministically, i.e., the same seed is chosen in each run, hence, the random sequence generated in each run is identical. 

There's a somewhat limited support for controlling the RNG initialization: some APIs allow to manually specify the seed ([parameters](https://github.com/Microsoft/CNTK/wiki/Parameters-And-Constants#parametertensor), for one, can be initialized using a specific seed), while others unfortunately do not expose this ability (they include DenseLayer and Dropout). If this is something you need in the short term -- you can easily rewrite [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs#L56), update the DenseLayer to accept a random seed, wire it up into the LinearLayer and pass over to ParameterTensors.

**Comment by snurkabill** [comment]
So is it considered as not a bug? It seems to me as a great feature to have a truly randomized process (if you training ensembles - same network topologies with different weights).

**Comment by raaaar** [comment]
I don't think anyone would consider 'reproducibility' as a bug (on the contrary, some say it's actually worth at least 2x speedup). 

If you want to have more knobs to control seeding behavior (in Dropout, etc.), please add a new feature request. Also, you might want to consider switching to python, which gives more fine-grained options for parameter initialization (take a look at [cntk.initializer](https://www.cntk.ai/pythondocs/cntk.html?highlight=initializer#module-cntk.initializer)).

**Comment by snurkabill** [comment]
I must disagree with you. Ofc that reproducibility is not a bug, that's clear to everybody, but it would be great to have posibility to switch between reproducible and production mode. For some serious work you need randomness everywhere. I doubt that Microsoft CNTK team uses same random seed.  This could help to a more people. I am afraid I have no capacity to implement it on my own.
