### ISSUE TITLE
Could you tell me when CNTK will wapper a pythonclient or java client？

### ISSUE THREAD

**Issue by wangchenwei2000** [Microsoft/CNTK#118]
Could you tell me when CNTK will wapper a pythonclient or java client？

**Comment by amitaga** [comment]
Python interfaces enabling constructing and executing CNTK computation networks in python, are currently in the works. Current there is no concrete ETA on the availability of this feature - please stay tuned for updates as we make progress on this front.

**Comment by ianupright** [comment]
I'd love to see a SWIG wrapper of sorts, and might even end up doing some of that myself (for Java).  Python is too slow computationally for me to be of much use.

**Comment by gembin** [comment]
+1 for java

**Comment by pkranen** [comment]
Python bindings have been released, Java bindings are work in progress.
