### ISSUE TITLE
Python API: Error when calling load_model and restart training the model

### ISSUE THREAD

**Issue by malexan123** [Microsoft/CNTK#1180]
Hi,

I am trying to load a model from a file and using the trained parameters as initial values continue training with new data. I do the following:
experiment = load_model("model.dnn") 
trainer = Trainer(experiment, ce, pe,
                      sgd(experiment.parameters, lr=lr_per_sample))

But I get the following error:
 sgd(experiment.parameters, lr=lr_per_sample))
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\trainer.py", line 45, in __init__
    parameter_learners)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\cntk_py.py", line 1637, in __init__
    this = _cntk_py.new_Trainer(*args)
ValueError: Trainer ctor: Union of the parameters covered by the specified parameterLearners should match the specified model's parameters

Am I using the API the wrong way? I searched online but could not find how to restart training in python.

Thanks

**Comment by ahfant** [comment]
I used the helper function **create_criterion_function** taken from here to remap the parameters for the cost function and error: [Hands-On Lab: Language Understanding with Recurrent Networks](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_202_Language_Understanding.ipynb)

It will look something like this. Hopefully it will solve your issue.
```
experiment = load_model("model.dnn")
criterion = create_criterion_function(experiment)
criterion.replace_placeholders({criterion.placeholders[0]: Input(num_labels)})
trainer = Trainer(
                          experiment, 
                          criterion.outputs[0], 
                          criterion.outputs[1],
                          sgd(experiment.parameters, lr=lr_per_sample)
                )
input_map = {
        criterion.arguments[0]: reader_train.streams.features,
        criterion.arguments[1]: reader_train.streams.labels
    }
```

**Comment by malexan123** [comment]
Thanks for your reply! Let me ask to see if I understand correctly. In the sample and while training a model (not loaded from a file) I see the following call:
criterion.replace_placeholders({criterion.placeholders[0]: Input(vocab_size),
                                    criterion.placeholders[1]: Input(num_labels)}) 

But you are saying when loading from a file to do the following instead:
criterion.replace_placeholders({criterion.placeholders[0]: Input(num_labels)})

Do you know how the above calls are different and why the second call is necessary when loading a model from a file?

Thanks again

**Comment by ahfant** [comment]
When you are creating your trainer in the initial step, you have to use the criterion placeholders. Then when you reload the model from file, remap using the criterion placeholders as shown above when re-creating the trainer.
