### ISSUE TITLE
Getting probabilities from C# Evaluation 

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#1183]
I'm trying to  evaluate a trained R-CNN model using the C# parser.

After tinkering around with the ROI's I finally got the same results as the B3_VisualizeOutputROIs.py script. 

One difference, however, is that I do not get the probabilities. Or I'm not sure how to calculate them probabilities properly. 

I use the following code after model.Evaluate

```
 for (int i = 0; i < numRois; i++)
 {
    var outputForRoi = outputs.Skip((i * numLabels)).Take(numLabels).ToList();

    int roiIndexStart = i * numLabels;

    // Retrieve the predicted label as the argmax over all predictions for the current ROI (background i 0)
    var max = outputForRoi.Select((value, index) => new { Value = value, Index = index })
     .Aggregate((a, b) => (a.Value > b.Value) ? a : b)
     .Index;

    var maxVal = outputForRoi.Select((value, index) => new { Value = value, Index = index }).Aggregate((a, b) => (a.Value > b.Value) ? a : b);

    if (max > 0)
    {
        Console.WriteLine("Outcome for ROI {0}: {1} \t({2}). Maxval: {3}", i, max, labels[max], maxVal);
    }
    ....

 }
```

Which results in the below image:
![image](https://cloud.githubusercontent.com/assets/7712296/21345082/00641808-c69f-11e6-987a-c4e9f5d9bb60.png)

How do I take the 4.68 and calculate a probability of, for instance, 0.76? Do I have to find the maximum for the category and divide or something like that?

Also, is there a way to perform non maxima supression in c# or do I have to code it myself?

Best regards
Morten

**Comment by mortengryning** [comment]
I made the c# maxima suppression myself. So only the probability side of the question needs answer :-)

**Comment by goodtogood** [comment]
@mortengryning  hi 
can you share your c# code for evaluating a RCNN model ?
thanks!

**Comment by amirubin87** [comment]
Any news here? I have a similar issue..

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by cha-zhang** [comment]
You can compute the probability by computing a softmax by yourself, which compute e^x for each element, and normalize to sum 1.
