### ISSUE TITLE
Cross validation during training with python API

### ISSUE THREAD

**Issue by malexan123** [Microsoft/CNTK#1187]
Hi,

I found some documentation here https://github.com/Microsoft/CNTK/wiki/Monitor-the-error-on-a-held-out-set-during-training-or-do-Cross-Validation-(CV)-during-training but I do not know how to do that in python API. Could you point me to some relevant samples?

Thank you

**Comment by eldakms** [comment]
Cross validation will be available in beta 11, which is due today. Please have a look at the training session class in python and convnet example(<CNTK>\Examples\Image\Classification\ConvNet\Python\ConvNet_CIFAR10_DataAug_Distributed.py)
