### ISSUE TITLE
CNTK 2.0 beta3.0 Linux-64bit-GPU fails to build from script installation

### ISSUE THREAD

**Issue by zeryx** [Microsoft/CNTK#1191]
Hey guys, while building inside of a 16.04 ubuntu docker image I'm getting a fun error error relating to our version pegged CNTK installation: `git clone https://git.codeplex.com/cntk1bitsgd/` throwing an http 500 error, which halts the `./install-cntk.sh` installation process.
Here's the rest of the stack trace:

```
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files: 100% (2207/2207), done.
Submodule 'Source/1BitSGD' (https://git.codeplex.com/cntk1bitsgd) registered for path 'Source/1BitSGD'
Cloning into 'Source/1BitSGD'...
fatal: unable to access 'https://git.codeplex.com/cntk1bitsgd/': The requested URL returned error: 500
Clone of 'https://git.codeplex.com/cntk1bitsgd' into submodule path 'Source/1BitSGD' failed
The command '/bin/sh -c cd /cntk &&     wget https://cntk.ai/BinaryDrop/CNTK-2-0-beta3-0-Linux-64bit-GPU.tar.gz &&     tar -xf * &&     cd /cntk/cntk/Scripts/linux &&     ./install-cntk.sh' returned a non-zero code: 1
```

Let me know if you guys need any more system specific info, for now we're going to fork this repo and host the 1BitSGD submodule somewhere else so we can version peg it.

**Comment by junjieqian** [comment]
Seems something is wrong with codeplex. You can try it again sometime later.

**Comment by zeryx** [comment]
I should also mention that this is docker container is used in a production environment; waiting around for git.codeplex.com to resume regular functionality is not a great solution

**Comment by junjieqian** [comment]
There is a problem with codeplex, https://codeplex.codeplex.com/wikipage?title=System%20Outage%20Report. You may try again later.

**Comment by zeryx** [comment]
As I mentioned that's not really going to work for us as this is in production; right now we've completely disabled CNTK building operations until this is fixed. I imagine this will become an issue into the future as well, I haven't checked the latest CNTK beta versions, but is it possible add host mirrors into the build operation?

**Comment by Joracosu** [comment]
I had the same issue and I couldn't build the solution. I overrided it downloading the 1BitSGD from an old repository: https://cntk1bitsgd.codeplex.com/SourceControl/latest#README.md
Donwnload the lastest source code solution and unzipit in [CNTK repo]/Source/1BitSGD
Thend build the CNTK solution as usual.
This worked for me
