### ISSUE TITLE
CNTK on Ubuntu error: RuntimeError: CUDA failure 2: out of memory

### ISSUE THREAD

**Issue by malexan123** [Microsoft/CNTK#1193]
Hi,

I am getting the following error when running on a GPU machine with Ubuntu. 

 File "/home/<user_name>/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/trainer.py", line 125, in test_minibatch
    return super(Trainer, self).test_minibatch(arguments, device)
  File "/home/<user_name>/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 1748, in test_minibatch
    return _cntk_py.Trainer_test_minibatch(self, *args)
RuntimeError: CUDA failure 2: out of memory ; GPU=0 ; hostname=<host> ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)

What is the recommended way to go to debug it? Is there a way to configure CNTK to choose a specific GPU? Are there any examples somewhere?

Thank you

**Comment by cha-zhang** [comment]
Which model are you training?

**Comment by malexan123** [comment]
My model definition is the following:

Sequential([
            Embedding(emb_dim),
            cntk.ops.sequence.last(Recurrence(LSTM(hidden_dim), go_backwards=False)), 
            Dense(num_labels)
        ])

with:
label_dim  = 8
emb_dim    = 150 
hidden_dim = 300 

The machine we are using is supposed to be very powerful for the purpose of training. When I tried to launch two training instances for the above model it ran out of memory. 

Please, let me know any best practices about how to configure CNTK to distribute the load on a machine to use all available resources/GPUs.

Thank you

**Comment by eldakms** [comment]
Hi maxelan123, 

If you need to pick up a particular gpu, you can use something like this:
    from cntk.device import set_default_device, gpu
    ...
    set_default_device(gpu(0)) # uses GPU with 0 id

For distributed training please have a look at:
https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines 

Some examples:
<CNTK>\Examples\Image\Classification\ConvNet\Python\ConvNet_CIFAR10_DataAug_Distributed.py
<CNTK>\Examples\Image\Classification\ResNet\Python\TrainResNet_CIFAR10_Distributed.py

**Comment by malexan123** [comment]
Thank you very much for your help
