### ISSUE TITLE
BS version of ResNet_CIFAR10 GPU performance 12.5% more samples/sec than python version

### ISSUE THREAD

**Issue by omencat** [Microsoft/CNTK#1195]
Using the Examples\Image\Classification\ResNet examples, I tested both the bs and python versions and noticed that the bs version trains at ~5880 samples per second, while the python version trains at ~5210 samples per second; a 12.5% training performance improvement over the python version.

The code appears to be structured differently between the two, but watching the GPU monitoring program (EVGA Precision X) I can see that when the BS version is running, GPU is at 100% usage, and is at 88% when the python version is running. The GPU is an Nvidia GeForce GTX 1080.

Any thoughts on why the python executed code is not running at the full 100% usage?

Thanks

**Comment by eldakms** [comment]
Hi omencat,

Which version are you using? Thanks!

**Comment by omencat** [comment]
version 2.0, beta 7

**Comment by eldakms** [comment]
Hi omencat,

If in the python you do not use progress_printer, do you see any change in the GPU utilization?
Thanks!

**Comment by omencat** [comment]
Confirmed after commenting out progress_printer lines the GPU utilization matches BS version ~95-96% and the stddev no longer fluctuates as much. 👍

**Comment by eldakms** [comment]
Thanks! I'm closing the issue then, we will work on optimizing the progress tracker.
