### ISSUE TITLE
how can I generate mean.xml file in cntk

### ISSUE THREAD

**Issue by zhandongdong** [Microsoft/CNTK#1196]
Some examples have mean.xml file. I wonder how these file are created. Is there any tool or function which can generate mean.xml easily?

reader = {
        verbosity = 0 ; randomize = true
        deserializers = ({
            type = "ImageDeserializer" ; module = "ImageReader"
            file = "$DataDir$/val_map.txt"
            input = {
                features = { transforms = (
                    { type = "Crop" ; cropType = "random" ; cropRatio = 0.8 ; jitterType = "uniRatio" } :
                    { type = "Scale" ; width = $ImageW$ ; height = $ImageH$ ; channels = $ImageC$ ; interpolations = "linear" } :
                    { type = "Mean" ; meanFile = "$ConfigDir$/ImageNet1K_mean.xml" } :
                    { type = "Transpose" }
                )}
                labels = { labelDim = $NumLabels$ }
            }
        })
    }

  ------------
All I have found is as below:
https://github.com/Microsoft/CNTK/wiki/Image-reader

Mean subtraction transform
meanFile parameter is a path to a file in OpenCV XML matrix format which contains per-pixel mean of the whole dataset. For example, for the input layer of size 224x224x3 the file will contain 150528 entries which will be subtracted during the training (or testing) from the input image. The same or similar effect can be achieved by using few other techniques, for example, Mean node or even just subtracting some fixed value, like 128, from the input.

**Comment by rold2007** [comment]
Did you look at #587 and #132 ?

You can create it using OpenCV, or simply use a hardcoded value (128) which gave very similar results in my case.

**Comment by zhandongdong** [comment]
@rold2007 Thanks for your advice. I will use the hard-coded value.

**Comment by zhandongdong** [comment]
@rold2007 I want to train model for human face recognition. The average value like 128 may not be appropriate for this situation. Mean value 128 is too dark to recognize human face, especially for eyes and  forehead. So mean value is still needed. Then I try to use the mean node mentioned in #132. The input looks like this:

        input = Input {imageShape}
        xMean = Mean(input)
        Normalize{f} = x =>  x - f
        inputNorm = Normalize{xMean}(input)

**Comment by rold2007** [comment]
I'm still using the old network format so I'm not familiar with your example input. In my case I simply applied a subtraction to the input as suggested by Alexey-Kamenev [here](https://github.com/Microsoft/CNTK/issues/132#issuecomment-185995047), although the code he pointed to is not available anymore.

It should look like this:
```
    features = ImageInput(ImageW, ImageH, ImageC, tag = feature, imageLayout = "cudnn")
    featOffs = Const(128)
    featScaled = Minus(features, featOffs)
```

I don't remember where I read this but the goal is that your image (minibatch?) mean become 0. So when you subtract 128, like you say the eyes will become negative (dark) while other part which were brighter will become light gray. It is true that your human faces might be brighter than other "normal" images so in your case you could try increasing the mean to subtract, maybe 192 would be more appropriate to you.

**Comment by cha-zhang** [comment]
We have a mean image computation example for CIFAR-10: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/DataSets/CIFAR-10/cifar_utils.py 
(in the function saveTrainImages(filename, foldername)).

**Comment by zhandongdong** [comment]
Thanks! @cha-zhang
