### ISSUE TITLE
Docker file crash with Python27 enabled

### ISSUE THREAD

**Issue by m3rik** [Microsoft/CNTK#1197]
Hi!

I wanted to install cntk in docker environment and with the latest commits where was added support for python 2.7, the docker configuration file will look for python 2.7 and will crash on setup because it will not have dependencies satisfied like python 3.4.

For this to work for you, you must add another option in CONFIGURE_OPTS.

This is how they look now in Dockerfile:

CONFIGURE_OPTS="\
      --with-cuda=/usr/local/cuda \
      --with-gdk-include=/usr/local/cuda/include \
      --with-gdk-nvml-lib=/usr/local/cuda/lib64/stubs \
      --with-kaldi=${KALDI_PATH} \
      --with-py34-path=/root/anaconda3/envs/cntk-py34 \
      --with-cudnn=/usr/local \
      --with-nccl=${NCCL_PATH}"

Just add:
      --with-py-versions=34

And it will work afterwards.

Best regards,
Paul

**Comment by relzhong** [comment]
Thanks
