### ISSUE TITLE
ANFIS in CNTK

### ISSUE THREAD

**Issue by tinyfx** [Microsoft/CNTK#1198]
Does anybody have an opinion about whether CNTK could be used to implement an ANFIS type network. I guess the answer is yes, but training it may be a problem. ?

**Comment by cha-zhang** [comment]
I believe you can if you use CNTK's low level Python APIs, although CNTK is not designed for this and you will need other packages such as skilearn. 

This thread has been too old and I'm closing this now. Please reopen a new issue if needed. Thanks!

**Comment by tinyfx** [comment]
It can be done by the way, with help of a 3rd party linear algebra library

**Comment by cha-zhang** [comment]
Great. Thanks!
