### ISSUE TITLE
How to fix the build errors? Any help is appreciated

### ISSUE THREAD

**Issue by jren2012** [Microsoft/CNTK#120]
Hi, everyone,

_**I am trying to setup CNTK on ubuntu 15.04(16GB RAM and Nvidia NVS 315 GPU).Everything went smooth till "Building CNTK".
1)On reaching this step there's an instruction "../../configure".On executing it says to run "make -j all." The output is below:**_
=--------------------------------------------------------------------=
jren@jren-HP-EliteDesk-800-G1-SFF:~/Repos/cntk/build/release $ ../../configure
Defaulting to --with-buildtype=release
Found cuda at /usr/local/cuda-7.0
Found gdk at /usr/.
Found CUB at /usr/local/cub-1.4.1
Found cuDNN at /usr/local/cudnn-4.0
Found OpenCV at /usr/local/opencv-3.0.0
Generating /home/jren/Repos/cntk/build/release/Config.make
Generating /home/jren/Repos/cntk/build/release/Makefile
run
>make -j all
to build

_**2)After running the make -j all command the error occured, the output error is below.**_
=--------------------------------------------------------------------=
creating /home/jren/Repos/cntk/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o for with build type release
mpic++ -c Source/Readers/ReaderLib/ReaderShim.cpp -o /home/jren/Repos/cntk/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/usr/local/opencv-3.0.0/include -MD -MP -MF /home/jren/Repos/cntk/build/release/.build/Source/Readers/ReaderLib/ReaderShim.d
Source/Readers/ReaderLib/ReaderShim.cpp:51:122: error: redeclaration of ‘void Microsoft::MSR::CNTK::ReaderShim<ElemType>::StartMinibatchLoop(size_t, size_t, size_t)’ may not have default arguments [-Werror=permissive]
 void ReaderShim<ElemType>::StartMinibatchLoop(size_t mbSize, size_t epoch, size_t requestedEpochSamples = requestDataSize)
                                                                                                                          ^
cc1plus: all warnings being treated as errors
Makefile:564: recipe for target '/home/jren/Repos/cntk/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o' failed
make[1]: *** [/home/jren/Repos/cntk/build/release/.build/Source/Readers/ReaderLib/ReaderShim.o] Error 1
make[1]: Leaving directory '/home/jren/Repos/cntk'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
=--------------------------------------------------------------------=
_**3)Any help is appreciated. thanks in advance?**

**Comment by raaaar** [comment]
Hm, the default argument shouldn't appear in the definition. 
Meanwhile, try changing 
`CXXFLAGS:= -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new`
in the Makefile to 
`CXXFLAGS:= -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Wno-error -fcheck-new`

**Comment by eldakms** [comment]
Hi,

due to the compiler version we are using (4.8.4) we have not seen this in our environment. This is being fixed now, the fix will be available soon.
Thank you!

**Comment by eldakms** [comment]
This has been fixed on the latest master (afbdff16). Closing.
