### ISSUE TITLE
how to get image feature vector from N-1 layer of ResNet model

### ISSUE THREAD

**Issue by civilman628** [Microsoft/CNTK#1202]
I want to get the feature vector of input image from deep model. In general, feature vector is the N-1 Layer's output, which before softmax.

How can I get such feature vector from ResNet model?

**Comment by cha-zhang** [comment]
This is in progress. We have a branch that's under code review: 
https://github.com/Microsoft/CNTK/tree/pkranen/featExtract/Examples/Image/FeatureExtraction 

It should be integrated into master soon.

**Comment by sayanpa** [comment]
HI Civilman628, would you mind posting your query on stackoverflow please. Would very much appreciate it.
The example can be found here:
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/FeatureExtraction

**Comment by civilman628** [comment]
I can close it now. thanks.
