### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by StephieX** [Microsoft/CNTK#1206]
I get the following errors when trying to build the CNTK package from source.  I'm building the CPU only version in Visual Stuido 2015.  The errors are relating to this this code in CPUMatrix.cpp.

template <class ElemType>
void CPUMatrix<ElemType>::VectorNorm1(CPUMatrix<ElemType>& c, const bool isColWise) const
{
    if (IsEmpty())
        LogicError("VectorNorm1: Matrix is empty.");

The only reason I'm building from source is to be able to make a custom deserializer.  I need ReaderLib.lib in order to do that, I think, and the lib isn't available in the binary packages.  Thanks.

2>c:\temp\cntk\source\math\cpumatrix.cpp(2924): error C4700: uninitialized local variable 'j' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2924): error C4700: uninitialized local variable 'i' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2924): error C4700: uninitialized local variable 'us' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2924): error C4700: uninitialized local variable 'j' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2924): error C4700: uninitialized local variable 'i' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2879): error C4700: uninitialized local variable 'j' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2879): error C4700: uninitialized local variable 'i' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2879): error C4700: uninitialized local variable 'j' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2879): error C4700: uninitialized local variable 'i' used
2>c:\temp\cntk\source\math\cpumatrix.cpp(2879): fatal error C1001: An internal error has occurred in the compiler.
2>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 246)
2>   To work around this problem, try simplifying or changing the program near the locations listed above.
2>  Please choose the Technical Support command on the Visual C++
2>   Help menu, or open the Technical Support help file for more information

**Comment by eldakms** [comment]
Hi StephieX,

Currently CNTK uses VS2013.
Support for VS2015 should be merged very soon. If you still want to work with VS2015 on your own please have a look at fmegen/vs2015/changing-project-files branch, everything should compile there.
Thanks!

**Comment by guoweiliu** [comment]
I make a clean clone of the code. When I use VS2015, I meet the same errors as StephieX. But when I switch to VS2013, I meet below error:

1>------ Skipped Rebuild All: Project: MathCUDA, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Rebuild All started: Project: Common (CNTK Core\Common), Configuration: Debug_CpuOnly x64 ------
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".
3>------ Rebuild All started: Project: Math, Configuration: Debug_CpuOnly x64 ------
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".
========== Rebuild All: 0 succeeded, 2 failed, 1 skipped ==========

Which VS should we use?

**Comment by eldakms** [comment]
Latest master is now using VS2015. Please follow this installation guide https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows
Thanks!
