### ISSUE TITLE
cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#1209]
Manual install of CNTK 2.0 beta 7 GPU with 1bit SGD, 

After installing Anaconda Python from the link and instructions provided on:
https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Manual

Step 3 (doc needs to change to reflect beta7 and not 6): 
pip install c:\localcntk\cntk\Python\cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl

givens the error:

C:pip install c:\localcntk\cntk\Python\cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl
cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform.
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by JJMEI** [comment]
hi i think you should go back to c:\local  ,here you can use this command
pip install c:\localcntk\cntk\Python\cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl
it should work done

**Comment by JJMEI** [comment]
do you finish it?


来自 魅蓝E

-------- 原始邮件 --------
发件人：avader906 <notifications@github.com>
时间：周三 12月28日 21:01
收件人：Microsoft/CNTK <CNTK@noreply.github.com>
抄送：JJMEI <mmeijunjie@163.com>,Comment <comment@noreply.github.com>
主题：Re: [Microsoft/CNTK] cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform (#1209)

**Comment by avader906** [comment]
yes it works.

The correct [Step 3] for the 2.0 beta 7 (https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Manual) is:

run: 
cd C:\local\cntk\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34
pip install c:\local\cntk\cntk\python\cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl

running pip from the envs\cntk-py34 directory is the solution
