### ISSUE TITLE
Image to Database for multi classification

### ISSUE THREAD

**Issue by snapo** [Microsoft/CNTK#121]
Hello CNTK Team,
I have around 80'000 images with a 300x100 format in png. also a text file with imagename.png , category 1, category 2, category3..... and so on till 64. The data per category is 1 or 0, it can also have multiple categorys where a 1 is. I wanna ask later the NN to which categorys the image falls in.
How do i convert the index text file and images to a format that CNTK can read and process. 
Only a question no BUG

**Comment by eldakms** [comment]
Hi snapo,

Please have a look at Tests/EndToEndTests/Image/AlexNet test. The mapping between the file -> label should be given in the map file and then specified in the configuration (as a sample see alexnet.cntk for configuration, train_map and val_map as mapping):

# Map file which maps images to labels using the following format:
# <full path to image><tab><numerical label (0-based class id)>
# Example:
# C:\Data\ImageNet\2012\train\n01440764\n01440764_10026.JPEG<tab>0

Hope this helps. Thanks!

**Comment by snapo** [comment]
Hello eldakms,
Thank you already for the very good hint, from what i see is that only 1 label is used. but i have multiple labels that need to be in the correct order.

**the train_map.txt file looks like this:**
~\CNTK\Projects\Weather\Data\imagename.jpg<tab>label1<tab>label2<tab>label3<tab>label4<tab>......... till 64

**Images are stored in:**
~\CNTK\Projects\Weather\Data\00000.jpg ..... 80000.jpg

The order of the labels is very important. So that means i can not change the train_map.txt to image<tab>single_label because if one label appears and another not, a third one needs to be true for example but only if the order is correct.

How would you take this train_map.txt if you first have the imagepathwithname and then tabbed 64 possible labels.
        labels = [
            start = 1      # Skip first one
            dim = 64        # One label dimension
            labelDim = 64   # 64 labels possible
            labelMappingFile = "$DataDir$/train_map.txt"
        ]

I know that i am a completly beginner... but i really do appreciate your help in this already. Maybe im able after this question to write my first tutorial on CNTK

**Comment by eldakms** [comment]
Hi snapo,

Currently the image reader unfortunately does not support multiple categories per sample, only a single one. Alexey Kamenev could probably provide more details when this scenario will be enabled.
Thanks!

**Comment by snapo** [comment]
Hello eldakms, thanks for the answer... in this case the question can be closed

**Comment by Alexey-Kamenev** [comment]
Hello,
Yes, this is correct, we currently do not support multi-label classification. Adding such support is in our plans but it will involve a bit more than just changing ImageReader.
