### ISSUE TITLE
Using multiple GPUs with Python

### ISSUE THREAD

**Issue by fcivardi** [Microsoft/CNTK#1210]
I'm using CNTK with Python, on a NC24 Azure Machine (4 GPUs K80). 
What should I do to use all 4 GPUs?
Simply : mpiexec -n 4 python training.py ? 
What should I put in training.py? Do I need a distributed learner?
with 1 GPU I have, in training.py
from cntk.device import set_default_device, gpu
set_default_device(gpu(0))
with more GPUs?
Thanks,
Francesco

**Comment by miguelgfierro** [comment]
You can follow this [example](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet/Python#trainresnet_cifar10_distributedpy). If you have installed the CUDA drivers correctly it should work. You'll see if it is using all the GPUs with the command: `watch NVidia-smi`

**Comment by fcivardi** [comment]
Thanks. Does  "watch nvidia-smi" works on Windows?

**Comment by miguelgfierro** [comment]
It won't. However you should have a `nvidia-smi.exe`

**Comment by eldakms** [comment]
More information about different distributed modes can be found here:
https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines 

I'm closing the issue for now, feel free to reopen if you bump into any issues. Thanks!
