### ISSUE TITLE
A mistake in the cntk python API document

### ISSUE THREAD

**Issue by Alan-Lee123** [Microsoft/CNTK#1214]
In python API for CNTK 2.0beta7
The function eval of Class Function
![image](https://cloud.githubusercontent.com/assets/11437976/21537468/f690a8f2-cdcc-11e6-91d1-b43b767b6666.png)
![image](https://cloud.githubusercontent.com/assets/11437976/21537473/00c888ee-cdcd-11e6-88d0-6917e4f51b60.png)
![image](https://cloud.githubusercontent.com/assets/11437976/21537476/07500b7e-cdcd-11e6-8277-6bb120d7c67a.png)
The document says that the return value of function eval is `True` if updates have been performed.
While, in the source code of function eval, the return value is definely something different. It is the result of the function forward.
![image](https://cloud.githubusercontent.com/assets/11437976/21537481/12fbb586-cdcd-11e6-99a2-aca686bfab67.png)

**Comment by bencherian** [comment]
I submitted a small pull request (#1227) that edits the docstring in the source code. I believe the API documentation is auto-generated from the docstrings.
