### ISSUE TITLE
SparseImageInput

### ISSUE THREAD

**Issue by 1026112881** [Microsoft/CNTK#1215]
I find there in an SparseImageInput in CNTK.core.bs. Is there anything reference on how to use it? I want to find some support on sparse input for convolutionlayer.

**Comment by 1026112881** [comment]
SparseImageInput(imageWidth, imageHeight, imageChannels, imageLayout='CHW', dynamicAxis='', tag='feature') = new ComputationNode [ operation = 'SparseInputValue' ; isImage = true /*plus the function args*/ ]

**Comment by cha-zhang** [comment]
SparseImageInput is deprecated. Sparse image input is not supported at this moment: 
https://docs.microsoft.com/en-us/cognitive-toolkit/Inputs 

This thread has been too old. I'm closing this now. Please reopen a new issue if needed. Thanks!
