### ISSUE TITLE
What does the cMap variable mean in CNN ndl (AlexNet) definition? 

### ISSUE THREAD

**Issue by heroner** [Microsoft/CNTK#1223]
In the following convolution layers (snippet of the AlexNet example) , how are the number of feature maps (cMap) determined? In particular, why do we have 256 maps in the second when the first is generating 384 maps? Is it user defined? If so then the framework must have a way of down sampling the feature maps? I was under the impression that the second would have at least 384. Thank you!

    # conv3
    kW3 = 3
    kH3 = 3
    cMap3 = 384
    hStride3 = 1
    vStride3 = 1
    # weight[cMap3, kW3 * kH3 * cMap2]
    conv3 = ConvReLULayer(pool2, cMap3, 1728, kW3, kH3, hStride3, vStride3, conv3WScale, conv3BValue)
    
    # conv4
    kW4 = 3
    kH4 = 3
    cMap4 = 256
    hStride4 = 1
    vStride4 = 1
    # weight[cMap4, kW4 * kH4 * cMap3]
    conv4 = ConvReLULayer(conv3, cMap4, 3456, kW4, kH4, hStride4, vStride4, conv4WScale, conv4BValue)

**Comment by cha-zhang** [comment]
Your model seems still the NDL version? 

Please use the BrainScript version instead: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/AlexNet/BrainScript 

It's been verified and achieves better accuracy than the Caffe AlexNet model.

**Comment by raaaar** [comment]
Closing this thread as it hasn't been update in a while. Feel free to open a new issue, if the question is still relevant.
