### ISSUE TITLE
wheels included in requirements.txt Fast-RNN Example

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/CNTK#1224]
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN 

Would be good if opencv and scikit-image could be included in requirements.  Is there a good reason they are not?  Do they really only ship via wheels?

**Comment by cha-zhang** [comment]
They only ship via wheels, and the site http://www.lfd.uci.edu/~gohlke/pythonlibs/ doesn't give direct link to the wheels. Sorry for the inconvenience.
