### ISSUE TITLE
cntk linux build error: undefined MPI references

### ISSUE THREAD

**Issue by rtrahms** [Microsoft/CNTK#1226]
Ubuntu 14.04 linux.  
Open MPI 2.0.1 (built and installed in /usr/local/mpi)
LD_LIBRARY_PATH updated to point to /usr/local/mpi/lib and PATH updated to point to /usr/local/mpi/bin

Configure step:
In cntk/build/release, call
../../configure --with-mkl=/usr/local/CNTKCustomMKL --1bitsgd=yes --asgd=no
and then
make all

Make gets all the way to link step, and then fails with:
=-----------------------------------------------------------=
building /home/rob/cntk/build/release/bin/v2librarytests for Linux with build type release
mpic++  -rdynamic -L/home/rob/cntk/build/release/lib -L/usr/local/CNTKCustomMKL/2/x64/parallel -L/usr/local/lib -L/usr/lib -L/usr/release/lib -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,/usr/local/CNTKCustomMKL/2/x64/parallel -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib -Wl,-rpath,/usr/release/lib -o /home/rob/cntk/build/release/bin/v2librarytests /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/FeedForwardTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/Main.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/Common.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/NDArrayViewTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/RecurrentFunctionTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/BlockTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/TensorTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/ValueTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/TrainerTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/CifarResNet.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/SerializationTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/LearnerTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/FunctionTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/SequenceClassification.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/Seq2Seq.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/TruncatedLSTMAcousticModel.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/DeviceSelectionTests.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/MinibatchSourceTest.o /home/rob/cntk/build/release/.build/Tests/UnitTests/V2LibraryTests/UserDefinedFunctionTests.o /home/rob/cntk/build/release/.build/Examples/Evaluation/CPPEvalV2Client/EvalMultithreads.o -lm -lmkl_cntk_p -liomp5 -lpthread -lcntklibrary-2.0 -lcntkmath -lperfprofiler
/home/rob/cntk/build/release/lib/libcntklibrary-2.0.so: undefined reference to `MPI_Iallreduce'
/home/rob/cntk/build/release/lib/libcntklibrary-2.0.so: undefined reference to `MPI_Iallgather'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/rob/cntk/build/release/bin/v2librarytests] Error 1
rm Source/CNTKv2LibraryDll/proto/CNTK.pb.cc
make[1]: Leaving directory `/home/rob/cntk'
make: *** [all] Error 2

I did note that, in the -L flags above, I didn't see /usr/local/mpi/lib (even though the $LD_LIBRARY_PATH has it first).  I can hard-code that in the generated cntk Makefile, but shouldn't have to.

Any idea what's going on here?
I have carefully followed the instructions on the wiki, so there must be something else I am missing.

**Comment by rtrahms** [comment]
I have carefully followed the instructions on the wiki, so there must be something else I am missing.

**Comment by junjieqian** [comment]
Please take a look at https://github.com/Microsoft/CNTK/issues/269#issuecomment-202529551. It is caused by different MPI version.

**Comment by rtrahms** [comment]
Too complicated to undo MPI installed with 14.04, so upgraded my image to 16.04 (which has Open MPI 1.10.2).   I no longer get this error.  Thanks.
