### ISSUE TITLE
Unsupported ComputationNode found when loading legacy CNTK model

### ISSUE THREAD

**Issue by prabhatp251** [Microsoft/CNTK#1229]
I trained CLASS-LSTM based language model with CNTK. I am now trying to load the model in Python and I am getting following runtime exception:

> Unsupported ComputationNode with OperationName='LookupTable' found when loading legacy CNTK model

Is there a way to convert legacy CNTK model to new format?

**Comment by sayanpa** [comment]
We have created a workitem to add this operation to Python API for future releases

**Comment by sayanpa** [comment]
Hi Prabhatp, could you please try out the recently released CNTK V2 API and see if the issue has been resolved. Please open an issue with the updated exception message should this needs further investigation.
