### ISSUE TITLE
Installation problem with pytest

### ISSUE THREAD

**Issue by Aceb1shmael** [Microsoft/CNTK#1230]
Hi
I got a message like  "Fatal Error during script execution!" - failed with exit code [1] when I trying to run install.ps1. Then I run conda create enveScripts>conda env create --file   in command, but it stop with an error about pytest.

![2017-01-02 1](https://cloud.githubusercontent.com/assets/22240403/21592274/167b0130-d147-11e6-9bc3-d5658cce311e.png)

**Comment by sayanpa** [comment]
Assuming you are trying to install CNTK. Is this command window a powershell environment?

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
