### ISSUE TITLE
C# Eval GPU support

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#1232]
Hi.

I want to use a custom trained RCNN model in a webservice. Even if the CNN model works as intended, the performance of the model (in C#) is slow with 3000-4000 ROI's on a CPU. It takes roughly 12-13 seconds + time to generate the regions of interest.

To accommodate the issue, I will buy a server with two dedicated high end GPU's. However, the latest patch notes states that the C# evaluation supports CPU only, and not GPU execution. 

When will the C# evalution support GPU evalution? Should I order the server now, or is GPU evulation not a current priority?

Best regards
MOrten

**Comment by zhouwangzw** [comment]
The current EvalDll C# Nuget Package supports CPU only. We are working on Eval V2 C# API which would support GPU. The V2 Eval C# API is based on the CNTK Library API for C++ and Python, and will be published soon.

**Comment by mortengryning** [comment]
Thank you for your quick answer. I will order the server then and await the new Eval :-)
