### ISSUE TITLE
Distributed Trainer Disapeared in v7?

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/CNTK#1236]
distributed.data_parallel_distributed_trainer() no longer appears to exist.  Where did it go?

**Comment by KeDengMS** [comment]
The concept of distributed trainer has retired and replaced with distributed learner.

Please refer to the updated [example](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10_Distributed.py). The new code would be like this:

`learner = distributed.data_parallel_distributed_learner(momentum_sgd(z.parameters, lr_schedule, mm_schedule,
                                              l2_regularization_weight = l2_reg_weight),
                                                                                        num_quantization_bits=num_quantization_bits,
                                                                                        distributed_after=distributed_after_samples)

trainer     = Trainer(z, ce, pe, learner)`
