### ISSUE TITLE
Image Reader / Eval / Transformation

### ISSUE THREAD

**Issue by wwindels** [Microsoft/CNTK#1237]
Using: CNTK for Windows v.2.0 Beta 5 GPU
Tutorial: [CNTK 201B: Hands On Labs Image Recognition](https://github.com/Microsoft/CNTK/blob/v2.0.beta7.0/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb)

I have modified the tutorial to train and evaluate B &W .png images.  (128H, 128W, 1C)
The post [Evaluate a saved convolutional network](https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network) indicates **mean** transform and image **transpose** are required to evaluate the image correctly with the model.

1. How do I (python please) replace  **ImageDeserializer.mean(mean_file)** with a constant mean **(128)**?
2. On Nov 18 the tutorial was updated, dropping the transpose in eval().  Now I'm confused.  Is transpose required?  Has something changed in CNTK to allow it to evaluate .png images loaded using PIL ? **Is there a detailed python centric post on this topic?**

Previously
```
def eval(pred_op, image_path):
    . . . 
    image_data   = np.array(Image.open(image_path), dtype=np.float32).T
```

**Comment by wwindels** [comment]
Referring to: [Issue 276 Conversion from HWC to CHW](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluate-Image-Transforms#layout-conversion-from-hwc-to-chw)

The post [Evaluate a saved convolutional network]( https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network) uses the following to transpose HWC to CHW.

```
pic = np.array(Image.open("foo.jpg"), dtype=np.float32) - 128
pic = np.ascontiguousarray(np.transpose(pic, (2, 0, 1)))
```
This is not the same as **x.T** previously given in tutorial 201B giving different results as shown below.
```
>>> y.shape
(3, 3, 1)
>>> y
array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

>>> y.T.shape
(1, 3, 3)
>>> y.T
array([[[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]])

>>> y.transpose(2,0,1).shape
(1, 3, 3)
>>> y.transpose(2,0,1)
array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])
>>>
```
I suspect **y.transpose(2,0,1)** is correct.

Please comment

**Comment by cha-zhang** [comment]
We have added transpose inside the reader for Python API, so users don't need to explicitly call transpose any more.

**Comment by sayanpa** [comment]
@wwindels: do you mind posting this question in StackOverflow please.

**Comment by wwindels** [comment]
@sayanpa  - do you have particular URL for a StackOverflow post?

**Comment by wwindels** [comment]
@cha-zhang - what version was that changed in? I'm using: CNTK for Windows v.2.0 Beta 5 GPU.
Also, Do you have a solution for my first question?

**Comment by sayanpa** [comment]
Just go tp stackoverflow.com. Cut paste your question if that works for you. Folks in the community get the benefit of you asking the question and us answering them.

For the first part you had it right. Subtract the constant from the image pixels.

**Comment by cha-zhang** [comment]
In Python you can take the input variable and subtract a mean or scale: 

```
input_var = cntk.ops.input_variable((num_channels, image_height, image_width), np.float32)
mean_input = cntk.ops.minus(input_var, 128)
scaled_input = cntk.ops.element_times(cntk.ops.constant(0.00390625), mean_input)
```

**Comment by wwindels** [comment]
@cha-zhang  you stated previously
**_We have added transpose inside the reader for Python API, so users don't need to explicitly call transpose any more._**

The eval() function in tutorial 201B does not appear to use the reader to load images.  The image is explicitly opened with PIL Image.open().  **Where is the transpose done that negates the need for the transpose here in eval()?**

**Comment by cha-zhang** [comment]
It might be a bug. We are investigating it.

**Comment by wwindels** [comment]
@cha-zhang  I see the tutorial 201B has been updated with the correct transpose(2, 0, 1) in eval().
Thanks for the help.  Please close.
