### ISSUE TITLE
Error when loading embeddings from file: 'Embedding: init and weights options are mutually exclusive'

### ISSUE THREAD

**Issue by malexan123** [Microsoft/CNTK#1238]
I just provide the weights from a file in my model definition and I hit the above error. 
My code calls:
Embedding(weights=np.loadtxt('embeddings.txt', delimiter=' '))

In https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/layers.py I see the following:
if init is not None or weights is not None:
        raise ValueError('Embedding: init and weights options are mutually exclusive')

The code might need an "and" instead of "or". But even if I fix the above locally, when I try to rerun it I hit the error:
UntestedBranchError("Embedding, from constant")

Are there any plans about fixing the issue? Or is there something I can do to help enable this code path so that we can use it for our experiments?

Thanks

**Comment by sayanpa** [comment]
This is a known issue that is being addressed.

**Comment by sayanpa** [comment]
malexan: could you please tag your question with "CNTK".

**Comment by abaheti95** [comment]
@sayanpa : Is this issue fixed now? 
I get the same error when I try to do this

	from cntk.layers import Embedding
	from cntk.initializer import uniform
	shared_embedding_layer = Embedding(G.embedding_dimension, uniform(scale=1.0/2.0/G.embedding_dimension))

> raise ValueError('Embedding: init and weights options are mutually exclusive')
ValueError: Embedding: init and weights options are mutually exclusive

**Comment by mahilleb-msft** [comment]
@abaheti95 - that last one seems to be working for me now.
Can you re-check if it's fixed for you? Please re-open if this issue persists.
Thanks, Mark
