### ISSUE TITLE
Windows install script has 10 minute download timeout

### ISSUE THREAD

**Issue by ed-alertedh** [Microsoft/CNTK#1239]
The 10 minute download timeout set in the Windows install script is too short for a slow internet connection. In particular, I couldn't download the ~400MB Anaconda installer within this timeframe before the script timed out and retried. At bare minimum, a longer timeout period would be nice. Although ideally it would at least have a basic download progress bar, e.g: https://blogs.msdn.microsoft.com/jasonn/2008/06/13/downloading-files-from-the-internet-in-powershell-with-progress/

Offending code:
Scripts/install/windows/_download.ps1:74
(as of commit 9f0d79bdd3df53e0d6a424eb1e454cc309d195cd)

**Comment by wolfma61** [comment]
there have been significant changes in this installer since then...
please open a new issue if you experience this in a more recent CNTK installation
