### ISSUE TITLE
FastRCNN error during A2_RunCntk.py

### ISSUE THREAD

**Issue by harewei** [Microsoft/CNTK#1242]
I'm currently following the tutorial for FastRCNN.  Everything works fine until the step that says "Run A2_RunCntk.py"
If I use "python A2_RunCntk.py" in cmd, it would simply give the following error
```
(cntk) C:\local\cntk\Examples\Image\Detection\FastRCNN>python A2_RunCntk.py
--------------------------------------------------------------
2017-01-04 09:31:29
PARAMETERS: datasetName = grocery
PARAMETERS: cntk_nrRois = 2000
cntk.exe configFile=C:\local\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:\local\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/ NumLabels=17 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=34000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=34000
Traceback (most recent call last):
  File "A2_RunCntk.py", line 41, in <module>
    pid = subprocess.Popen(cmdStr, cwd = cntkFilesDir)
  File "C:\Users\Andy Wei\Anaconda3\envs\cntk\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Andy Wei\Anaconda3\envs\cntk\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I'm currently using binary installed beta 7 GPU release

**Comment by Vedaevolution** [comment]
Is it possible you didn't add the cntk bin folder to your PATH variable?

Best Regards
Stephen

**Comment by harewei** [comment]
@Vedaevolution I noticed the tutorial said "The tutarial further assumes that the folder where cntk.exe resides is in your PATH environment variable.".  However, it does not tell me how.  Could you tell me how and what's the name for the variable?  e.g. setx  NAME C:\local\cntk\cntk
My cntk.exe is located at C:\local\cntk\cntk

Thank you.

**Comment by harewei** [comment]
Found the solution, you need to use set PATH=c:\local\cntk\cntk;%PATH% in cmd so cntk.exe can be detected.  I was able to finish the tutorial after this.

**Comment by abilash-c** [comment]
> Found the solution, you need to use set PATH=c:\local\cntk\cntk;%PATH% in cmd so cntk.exe can be detected. I was able to finish the tutorial after this.

I set my path but still get the same error. Is there any other workaround?
