### ISSUE TITLE
CNTK Load model not freeing up the CUDA context

### ISSUE THREAD

**Issue by rahul-anand** [Microsoft/CNTK#1244]
I want to use cuda specifically numbapro for some gpu operations from my python script along with CNTK but i am getting an error

`from numbapro import cuda, vectorize, guvectorize, check_cuda`    
` device = cuda.get_current_device()`
`    print(device)`
`    device = cuda.get_current_device()`
 `    print(device)`
 `   z = load_model('model_name.dnn')`
   ` device = cuda.get_current_device()`

Error : 
<CUDA device 0 'b'Tesla K40m''>
<CUDA device 0 'b'Tesla K40m''>

AssertionError: An unmanaged CUDA context is active.

Any help regarding this will be greatly appreciated.

Thanks

**Comment by KeDengMS** [comment]
Hi @rahul-anand, 
Thanks for reporting the issue. I just tried numba & CNTK and could not repro the issue:

>>> from numba import cuda
>>> device = cuda.get_current_device()
>>> print(device)
<CUDA device 0 'b'GeForce GTX TITAN X''>
>>> z = load_model('/home/ke/repos/CNTK/Examples/Image/Classification/ResNet/Output/Models/ResNet20_CIFAR10_DataAug.0')
>>> device = cuda.get_current_device()
>>> print(device)
<CUDA device 0 'b'GeForce GTX TITAN X''>

my numba version is 0.30.0. Could you share some more details about the issue?

Thanks,
Ke

**Comment by sayanpa** [comment]
It seems numbapro is deprecated in Anaconda:

https://docs.continuum.io/numbapro/

NUMBAPRO
NumbaPro has been deprecated, and its code generation features have been moved into open-source Numba
Please try numba and let us know if you hit any issues.

**Comment by rahul-anand** [comment]
Yeah i can confirm that issue is fixed with numba 0.30.0 as Ke Mentioned. This issue still exist with previous numba version 0.23.0.
Closing the issue now.
Thanks for your help

**Comment by drcrook1** [comment]
Did we verify also on this point that python kernels which crash due to memory outs also hold on to the cuda context?  May or may not be related.
