### ISSUE TITLE
Detection Example Error: No module named cython_bbox

### ISSUE THREAD

**Issue by rtrahms** [Microsoft/CNTK#1245]
Ubuntu 16.04 Linux
Have cntk built, CUDA 8 installed, have run a number of different cntk examples successfully before this, both with and without the GPU (NVidia GTX 1080).

Downloaded grocery data, create a virtual environment, and do a 'pip install -r requirements.txt'.
(BTW, have to do an additional 'pip install scikit-image' as well)
Also, for good measure, I did pip install cython.

Running 'python A1_GenerateInputROIs.py', results in an error:
Traceback (most recent call last):
  File "A1_GenerateInputROIs.py", line 5, in <module>
    import PARAMETERS
  File "/home/rob/cntk/Examples/Image/Detection/FastRCNN/PARAMETERS.py", line 2, in <module>
    from cntk_helpers import *
  File "/home/rob/cntk/Examples/Image/Detection/FastRCNN/cntk_helpers.py", line 7, in <module>
    from fastRCNN.nms import nms as nmsPython
  File "/home/rob/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/__init__.py", line 7, in <module>
    from .imdb import imdb
  File "/home/rob/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/imdb.py", line 17, in <module>
    from utils2_win64.cython_bbox import bbox_overlaps
ImportError: No module named cython_bbox

I am curious why the script is calling a  *_win64 script, especially since this is a linux box.  Any idea what is going on here?

Thanks,
Rob

**Comment by rtrahms** [comment]
I reran the python setup instructions, and fixed this problem.  Thanks.

**Comment by thaiat** [comment]
HI @rtrahms , i m having the same issue, what command did you use to solve it ?

**Comment by dimaxano** [comment]
Hi, @rtrahms, I have the same issue as you. What did you do to solve it?

**Comment by pkranen** [comment]
Did you follow these instructions [https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression](https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression)? If you're using Python 3.5 on Linux you need compile the binaries from the repo.

**Comment by dimaxano** [comment]
In my case, problem was in absence of GPU :(

**Comment by mvc12593** [comment]
Solution at URL mentioned by @pkranen  is now at following URL

https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression
