### ISSUE TITLE
how to freeze update of a part of network weights during training?

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#1248]
I want to train a student network from a teacher network. During training, teacher network weight should be fixed.

Could you let me know how to freeze part of network parameter updates? Could you explain it based on both MEL script and Brainscript? I want to know both methods because I still use legacy scripts.

**Comment by sayanpa** [comment]
Don't have something specifically for Brainscript. On the Cpp side you can look into FreezeParameters() function. Might give you some ideas how to surface that in Brainscript.

For Python, here is some documentation:
https://cntk.ai/pythondocs/cntk.ops.html?highlight=alias#cntk.ops.functions.CloneMethod

**Comment by avader906** [comment]
You could train a model with your teacher network. Then create another mode, clone all or parts of the teacher network (specifying to the parts to be trained or not) and re-use these parts in your student model. This mechanism could be used to adapt an already trained network as well.

https://github.com/Microsoft/CNTK/wiki/CloneFunction
https://github.com/Microsoft/CNTK/wiki/BS-Model-Editing

**Comment by funguy74** [comment]
I found a presentation material on CNTK: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/kaisheny-cntk-tutorial-icassp2015-20150419.pdf

Page 84 mentioned freezing or unfreezing parameters during training can be done by model editing language (MEL). Is there anybody who can elaborate further on this?

**Comment by avader906** [comment]
@funguy74 You freeze part of a teacher network via BrainScript using CloneFunction. In earlier CNTK versions MEL was used instead. 

MEL is documented inside the repository - have you checked it ? You experiment with both.

https://github.com/Microsoft/CNTK/blob/master/Documentation/Documents/Model%20Editing%20Language.md

**Comment by funguy74** [comment]
Thanks for your comment on BrainScript. For MEL, I looked into MEL document but I couldn't find any information to freeze or unfreeze parameters. Do you know any keyword function in MEL that is working on this?

**Comment by sayanpa** [comment]
Thanks "ghost" for answering the brainscript questions. MEL is no longer supported, there are remnants of legacy code in the source (deprecated), where you may want to search for any pointers. Sorry about that. 

Closing this issue for now. If you need help with BrainScript or Python API we are happy to help.
