### ISSUE TITLE
Unable to find OpenCV python whl file listed on wiki page "Object Detection using Fast R CNN"

### ISSUE THREAD

**Issue by relloyd** [Microsoft/CNTK#1249]
Hi All,

I was wondering if you could help me find the OpenCV python whl file "opencv_python-3.1.0-cp34-cp34m-win_amd64.whl" listed on the following CNTK wiki page:

https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN

I'm afraid I only see that opencv (currently at v3.2, public pre-built download) supports python 2.7 so I don't understand why cp34 is required or where it comes from.

Can anyone advise please?

Many thanks,
Richard

**Comment by drcrook1** [comment]
![image](https://cloud.githubusercontent.com/assets/6099287/21702037/2fdc9ec2-d377-11e6-88a1-9eaf2ac593f6.png)

Use the orange one highlighted.  I have tested and verified against CNTK v7

**Comment by relloyd** [comment]
Great, many thanks for the help!
