### ISSUE TITLE
should I add sentence begin symbols in text when training LMs?

### ISSUE THREAD

**Issue by zhangyike** [Microsoft/CNTK#1250]
I'd like to train a language model with CNTK LMSequenceReader. And should I add sentence begin/end symbol (<s> </s>) in training text? Or does CNTK automatically do this?

For example, original text is (1), and (2) is obtained by adding begin/end symbol in (1).
(1): hi um yeah i'd like to talk about how you dress for work 
(2): \<s\> hi um yeah i'd like to talk about how you dress for work \<\/s\>
Which one should I use when I train or eval language models?

**Comment by zhangyike** [comment]
(2):  </s> hi um yeah i'd like to talk about how you dress for work </s>

**Comment by zhangyike** [comment]
(2): \<s\> hi um yeah i'd like to talk about how you dress for work \<\/s\>

**Comment by sayanpa** [comment]
You can look into https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb for ideas. The later sounds more appropriate.
