### ISSUE TITLE
Fast R-CNN model on new images

### ISSUE THREAD

**Issue by harewei** [Microsoft/CNTK#1259]
Just adding two new questions based on #1093 
1.Did anyone actually get @pkranen 's branch for evaluation working?  I mean I can run the program, but everything is considered "ground" even by using the trained grocery 100 model as stated in the project comment.
2.Is there a way to evaluate new image just using the default python script?  I tried putting new image in "test" folder but during A2_RunCntk.py it requires me to create ROI and label them manually, otherwise it would just give an error, which makes the whole task pointless if I have to manually evaluate images first before the network can predict them.

**Comment by dkmorteng** [comment]
I evaluated new images by first training a model using the scripts (edit the dataset) and then wrote a c# evaluator. The evalutor call a custom python script (just modify the existing for ROI generation) to generate the ROI for a single image. It took some days but works well in a webservice :-)

**Comment by harewei** [comment]
@dkmorteng after the ROI generation (I assume it's a modified A1_GenerateInputROIs.py), did you still use A2_RunCntk.py to do the evaluation?  or were you able to conduct evaluation inside C#?

**Comment by mortengryning** [comment]
I'll try to describe it in more details:

**Making the model:**
I used the existing scripts and modified the data paths to my own images (positive, negative, and test). I edited the categories in the scripts to reflect my categories (3 only). I then ran A1, A2, A3 and generated the model. I tried different parameters for ROI and training until I was happy with the result.

**Using the model:**
Using the existing C# code I wrote a method that takes an image in base64 and returns an xml list of features. The C# code use the Process.Start to run a modified python script to generate the ROI file, reads this file, a use it to evaluate the model in C#. So I only use python for ROI generation, which I hope to avoid when a version of RCNN without external ROI generation is released.

**Comment by harewei** [comment]
@mortengryning thank you for the reply.  I have already done **Making the model** part, which also generates ROIs during A1.  The only part that I'm still struggling is how to **evaluate** now that I have a trained model and the ROIs for an image.

Here's the C# code I'm using based on @pkranen branch, which doesn't actually give me any ROI labels besides 0 (ground).  So I'm wondering if there's a mistake in the code, or at least an alternative way to do the evaluation for ROI labeling.
````
public static void EvaluateObjectDetectionModel()
        {
            try
            {
                // This example requires the Fast-RCNN_grocery100 model.
                // The model can be downloaded from <see cref="https://www.cntk.ai/Models/FRCN_Grocery/Fast-RCNN_grocery100.model"/>
                // The model is assumed to be located at: <CNTK>\Examples\Image\PretrainedModels\
                // It further requires the grocery image data set. 
                // Please run 'python install_fastrcnn.py' from <cntkroot>\Examples\Image\Detection\FastRCNN to get the data.
                string imageDirectory = Path.Combine(initialDirectory, @"..\..\Examples\Image\DataSets\grocery\testImages");
                string modelDirectory = Path.Combine(initialDirectory, @"..\..\Examples\Image\PretrainedModels");
                Environment.CurrentDirectory = initialDirectory;

                List<float> outputs;

                using (var model = new IEvaluateModelManagedF())
                {
                    string modelFilePath = Path.Combine(modelDirectory, "Fast-RCNN_grocery100.model");
                    ThrowIfFileNotExist(modelFilePath,
                        string.Format("Error: The model '{0}' does not exist. Please download the model from https://www.cntk.ai/Models/FRCN_Grocery/Fast-RCNN_grocery100.model " +
                                      "and save it under ..\\..\\Examples\\Image\\PretrainedModels.", modelFilePath));

                    model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: -1);

                    // Prepare input value in the appropriate structure and size
                    var inDims = model.GetNodeDimensions(NodeGroup.Input);
                    if (inDims.First().Value != 1000 * 1000 * 3)
                    {
                        throw new CNTKRuntimeException(string.Format("The input dimension for {0} is {1} which is not the expected size of {2}.", inDims.First(), inDims.First().Value, 1000 * 1000 * 3), string.Empty);
                    }

                    // Transform the image
                    string imageFileName = Path.Combine(imageDirectory, "WIN_20160803_11_28_42_Pro.jpg");
                    ThrowIfFileNotExist(imageFileName, string.Format("Error: The test image file '{0}' does not exist.", imageFileName));

                    Bitmap bmp = new Bitmap(Bitmap.FromFile(imageFileName));
                    // TODO: preserve aspect ratio while scaling and pad the remaining pixels with (114, 114, 114)
                    var resized = bmp.Resize(1000, 1000, true);
                    var resizedCHW = resized.ParallelExtractCHW();

                    // TODO: generate ROI proposals using an external library, e.g. selective search, 
                    // TODO: project them to the 1000 x 1000 image size and compute (x, y, w, h) relative to the image dimensions.
                    // TODO: Alternative workaround: run script 'A1_GenerateInputROIs.py' from <cntkroot>\Examples\Image\Detection\FastRCNN and read rois from file.

                    // parse rois: groups of 4 floats corresponding to (x, y, w, h) for an ROI
                    string roiCoordinates = "0.219 0.0 0.165 0.29 0.329 0.025 0.07 0.115 0.364 0.0 0.21 0.13 0.484 0.0 0.075 0.06 0.354 0.045 0.055 0.09 0.359 0.075 0.095 0.07 0.434 0.155 0.04 0.085 0.459 0.165 0.145 0.08 0.404 0.12 0.055 0.06 0.714 0.235 0.06 0.12 0.659 0.31 0.065 0.075 0.299 0.16 0.1 0.07 0.449 0.18 0.19 0.15 0.284 0.21 0.135 0.115 0.254 0.205 0.07 0.055 0.234 0.225 0.075 0.095 0.239 0.23 0.07 0.085 0.529 0.235 0.075 0.13 0.229 0.24 0.09 0.085 0.604 0.285 0.12 0.105 0.514 0.335 0.1 0.045 0.519 0.335 0.08 0.045 0.654 0.205 0.08 0.055 0.614 0.215 0.115 0.065 0.609 0.205 0.115 0.075 0.604 0.225 0.115 0.055 0.524 0.23 0.06 0.095 0.219 0.315 0.065 0.075 0.629 0.31 0.095 0.08 0.639 0.325 0.085 0.06 0.219 0.41 0.25 0.11 0.354 0.46 0.185 0.11 0.439 0.515 0.09 0.075 0.359 0.455 0.175 0.125 0.449 0.525 0.08 0.07 0.574 0.46 0.06 0.105 0.579 0.46 0.105 0.1 0.529 0.47 0.15 0.145 0.584 0.475 0.085 0.09 0.354 0.52 0.08 0.06 0.219 0.52 0.115 0.1 0.229 0.53 0.1 0.08 0.229 0.575 0.105 0.045 0.339 0.56 0.085 0.045 0.354 0.535 0.075 0.06 0.299 0.59 0.145 0.05 0.304 0.58 0.12 0.045 0.594 0.555 0.075 0.05 0.534 0.58 0.14 0.06 0.504 0.66 0.07 0.06 0.494 0.73 0.075 0.09 0.504 0.695 0.07 0.095 0.219 0.665 0.075 0.145 0.494 0.755 0.085 0.075 0.704 0.665 0.07 0.21 0.434 0.72 0.055 0.1 0.569 0.695 0.205 0.185 0.219 0.73 0.29 0.13 0.574 0.665 0.08 0.055 0.634 0.665 0.095 0.045 0.499 0.725 0.08 0.135 0.314 0.71 0.155 0.065 0.264 0.72 0.19 0.105 0.264 0.725 0.185 0.095 0.249 0.725 0.12 0.11 0.379 0.77 0.08 0.055 0.509 0.785 0.055 0.06 0.644 0.875 0.13 0.085 0.664 0.875 0.11 0.075 0.329 0.025 0.08 0.115 0.639 0.235 0.135 0.15 0.354 0.46 0.185 0.12 0.354 0.46 0.185 0.135 0.229 0.225 0.08 0.095 0.219 0.72 0.29 0.14 0.569 0.67 0.205 0.21 0.219 0.315 0.1 0.075 0.219 0.23 0.09 0.085 0.219 0.41 0.295 0.11 0.219 0.665 0.27 0.145 0.219 0.225 0.09 0.14 0.294 0.665 0.2 0.05 0.579 0.46 0.105 0.145 0.549 0.46 0.14 0.145 0.219 0.41 0.295 0.125 0.219 0.59 0.11 0.05 0.639 0.235 0.135 0.155 0.629 0.235 0.145 0.155 0.314 0.71 0.155 0.115 0.334 0.56 0.09 0.045 0.264 0.72 0.225 0.1 0.264 0.72 0.225 0.105 0.219 0.71 0.29 0.15 0.249 0.725 0.125 0.11 0.219 0.665 0.27 0.17 0.494 0.73 0.075 0.115 0.494 0.73 0.085 0.115 0.219 0.0 0.14 0.14 0.219 0.07 0.14 0.14 0.219 0.14 0.14 0.14";
                    var rois = roiCoordinates.Split(' ').Select(x => float.Parse(x)).ToList();

                    // inputs are the image itself and the ROI coordinates
                    var inputs = new Dictionary<string, List<float>>() { { inDims.First().Key, resizedCHW }, { inDims.Last().Key, rois } };

                    // We can call the evaluate method and get back the results (predictions per ROI and per class (no softmax applied yet!)...
                    var outDims = model.GetNodeDimensions(NodeGroup.Output);
                    outputs = model.Evaluate(inputs, outDims.First().Key);
                }

                // the object classes used in the grocery example
                var labels = new[] {"__background__",  
                   "avocado", "orange", "butter", "champagne", "eggBox", "gerkin", "joghurt", "ketchup",
                   "orangeJuice", "onion", "pepper", "tomato", "water", "milk", "tabasco", "mustard"};
                int numLabels = labels.Length;
                int numRois = outputs.Count / numLabels;

                Console.WriteLine("Only showing predictions for non-background ROIs...");
                int numBackgroundRois = 0;
                for (int i = 0; i < numRois; i++)
                {
                    var outputForRoi = outputs.Skip(i * numLabels).Take(numLabels).ToList();

                    // Retrieve the predicted label as the argmax over all predictions for the current ROI
                    var max = outputForRoi.Select((value, index) => new { Value = value, Index = index })
                        .Aggregate((a, b) => (a.Value > b.Value) ? a : b)
                        .Index;

                    if (max > 0)
                    {
                        Console.WriteLine("Outcome for ROI {0}: {1} \t({2})", i, max, labels[max]);
                    }
                    else
                    {
                        numBackgroundRois++;
                    }
                }

                Console.WriteLine("Number of background ROIs: {0}", numBackgroundRois);
            }
            catch (CNTKException ex)
            {
                OnCNTKException(ex);
            }
            catch (Exception ex)
            {
                OnGeneralException(ex);
            }
        }
````

**Comment by mortengryning** [comment]
Make a script to generate ROI for a single image and call it like:

ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "CMD.exe";
            start.Arguments = string.Format("{0} {1} {2}", "/C C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\Scripts\\activate.bat C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py34&python.exe C:\\local3\\cntk\\Examples\\Image\\Detection\\FastRCNN\\D1_GenerateSingleROI.py", imagePath, resultingRoiPath);
            start.UseShellExecute = false;
            start.WindowStyle = ProcessWindowStyle.Hidden;
            start.RedirectStandardOutput = true;
            start.RedirectStandardError = true;
            start.CreateNoWindow = true;

            string output = string.Empty;
            try
            {

                using (Process process = Process.Start(start))

etc.

**Comment by Quethrosar** [comment]
I can't load my model using beta 11 and this code. it was trained with beta 11. 


[CALL STACK]
    > Microsoft::MSR::CNTK::GetEvalExtended<double>  
    - Microsoft::MSR::CNTK::GetEvalExtended<double>  
    - Microsoft::MSR::CNTK::GetEvalExtended<double>  
    - Microsoft::MSR::CNTK::GetEval<double>  
    - 00007FFDC6DEAA23 (SymFromAddr() error: The specified module could not be found.)

**Comment by zhouwangzw** [comment]
@Quethrosar Could you please share code snippet for loading the model? Are you able to run examples [CPPEvalExtendClient](https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CPPEvalExtendedClient)?

**Comment by Quethrosar** [comment]
I got it working with the newer managed library.
I did the todo using emgucv such as generating rois and scaling the image with padding.

I would like to submit what I have done to help others who are layman like me trying to use the fast-rcnn. A lot of concepts aren't documented such as the color data needing to be all reds, all greens, then all blues, or how to use the results.

**Comment by zhouwangzw** [comment]
@Quethrosar Thanks! We would love to see your contirbution to make CNTK better. 

I am closing this issue. Please feel free to re-open it if needed.

**Comment by mwangimorris** [comment]
How do you actually run the Program.cs file?

**Comment by wendy7707** [comment]
@mortengryning Hello, you said you wrote a method that takes an image in base64 and returns an xml list of features? Would you please share this coding? Thanks. In addition, CNTK has no RCNN algorithm,right? Thanks.

**Comment by wendy7707** [comment]
@mortengryning hello, thank you for your reply, I have more question,  I'm also using based on @pkranen branch, which doesn't actually give me any ROI labels besides 0 (ground). May I ask what is the problem? Thanks!

**Comment by wendy7707** [comment]
@harewei I have the same problem with you ,would you please tell me how to solve it, thank you very much!

**Comment by wendy7707** [comment]
@Quethrosar Hello, I have the same problem with @harewei , would you please tell me how to solve it, thank you very much!
