### ISSUE TITLE
Unable to run unit tests on CPU

### ISSUE THREAD

**Issue by rold2007** [Microsoft/CNTK#126]
I tried running the unit tests using the Debug_CPU configuration and most of them fail.
I looked at the code and most use the "c_deviceIdZero" variable when selecting the device to allocate on. This is obviously wrong on CPU.
Also, I was quite surprised that while most tests fail, there is actually a GPU test which passes, but I don't even have a GPU on my machine ! The test is GPUSparseMatrixInnerProduct. I ignored the GPU test CPUMatrixDenseTimesSparseAsSparse since it doesn't do anything.
Maybe these issues will be resolved along with #98 .

**Comment by gaizkan** [comment]
Although some tests may run (and pass) on CPU builds, we currently only support Unit Tests for Windows Release GPU. We currently have a backlog item for this (CPU vs GPU tests)
