### ISSUE TITLE
A typo in installation tutorial

### ISSUE THREAD

**Issue by hzlclock** [Microsoft/CNTK#1260]
If you want to use Python Tools, CNTK, and Visual Studio:
First determine your path to Visual studio. For VS2013 it would be something like: "c:\Program Files (x86)\Microsoft Visual Studio 12.0". For [[[[[[VS2105]]]]]]]]]]], it would be something like: "c:\Program Files (x86)\Microsoft Visual Studio 14.0". Take that path and create an

**Comment by sayanpa** [comment]
Could you please provide the link where you observe this typo. Thanks.

**Comment by mahilleb-msft** [comment]
I found and fixed it.
Thanks!
