### ISSUE TITLE
A loss function for sequence to sequence processing

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#1262]
I'm doing a sequence-to-sequence model for phonemes alignment. Specifically my train data look like paired sequences (_phoneme_ - _length_), where _phoneme_ is a one-hot vector, and _length_ is a float.
So I want to feed the model with a _phoneme_ sequence and get a corresponding _length_ sequence.

My network is generally built like these:
```
model = Sequential(
	EmbeddingLayer{embeddingSize} : 
	RecurrentLSTMLayerStack {lstmDims} :
	LinearLayer{1}
)
```

The `LinearLayer{1}` should do a conversion from `lstmDims` to 1 if I get things right.
So when I feed the model with a sequence of length N, I should get a resulting sequence of length N as well.

Now I want to set up a proper loss function, which I think should be an average difference between the elements of a known result sequence and the model output. Averaging should be done through the time axis, so that sequence of different lengths could be managed.

I was planning to do something like 
```
objectives = Input(1) #actually a sequence here as stated in the reader
result = model(features)
errs = Abs(objectives - result)
loss_function = ReduceMean(errs)
criterionNodes  = (loss_function)
```
but in [Reduction Operations](https://github.com/Microsoft/CNTK/wiki/Reduction-Operations) it's explicitly stated that 

> These operations do not support reduction over sequences. Instead, you can achieve this with a recurrence. 

I'm not sure how to use recurrence for my task. And I'm also not sure if the whole concept is fine. Would be grateful for help and suggestions!

**Comment by sayanpa** [comment]
Could you please post this question on StackOverflow with CNTK tag.

**Comment by mikhail-barg** [comment]
@sayanpa sure, here you are: http://stackoverflow.com/questions/41562909/cntk-a-loss-function-for-sequence-to-sequence-processing
