### ISSUE TITLE
Wheel not supported issue in the 2.0Beta7 downloaded binary

### ISSUE THREAD

**Issue by epslong** [Microsoft/CNTK#1263]
Hi, 

As I work on updating to CNTK2.0Beta7 from Beta5 version (for which the python interface is working well), I encountered issue for the python environment. The instructions I followed were here:

https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Manual

I have python 3.5.2. So I created cntk-py35 environment using conda-windows-cntk-py35-environment.yml instead of the py34-environment as described in step 2. However, when following the wheel installation instruction in step 3, I encountered the error of "cntk-2.0.beta7.0-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform". My pip is up to date. 

I also tried updating the existing cntk-py35 environment with traceback errors.

**Comment by bencherian** [comment]
Python 3.5 is only supported on Linux right now. You need to create a Python 3.4 environment for use with CNTK on Windows. (You can see that the provided wheel only supports Python 3.4...note the "cp34" in the filename.)

**Comment by epslong** [comment]
Thanks! I switched back to py34 and it works now
