### ISSUE TITLE
where does exist abot CNTK2.cntk

### ISSUE THREAD

**Issue by JJMEI** [Microsoft/CNTK#1265]
now,i am trying Example/Speech/../AMI/cntk_config ..
but i don't find the file about CNTK2.cntk

**Comment by sayanpa** [comment]
AMI related files are located here: https://github.com/Microsoft/CNTK/tree/master/Examples/Speech/Miscellaneous/AMI/cntk_config

By the way some of the older NDL/MEL formats are deprecated unfortunately.

**Comment by JJMEI** [comment]
i think cntk should update for this example.  - _ -!!

**Comment by sayanpa** [comment]
We are adding more examples for speech. Recently CNTK 208 tutorial using CTC was added. 

As a part of the refactorization efforts this BS file is no longer valid. Closing this issue for now given it has been open for a long time. Please open issues with any further suggestion / feature requests you may have.
