### ISSUE TITLE
CNTKTextFormatReader - using same data as feature and label

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#1266]
Training an auto-encoder requires the same data to be represented as both features and labels. 

It is my understanding, that there is no way for CNTKTextFormatReader to use the same data as both - and would require the user to prepare a flat file with duplicate of data using different labeling, or use deserializer magic if supported.

- Does CNTKTextFormatReader support the new deserializer infrastructure [per #106 and #695 via example on https://github.com/Microsoft/CNTK/wiki/Deserializers-and-Transforms.] ?

- Is it as simple as using x2 the "CNTKTextFormatDeserializer" deserializer section per https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/ReaderTests/Config/ImageAndTextReaderSimple_Config.cntk ?

- Could the way to use the same data from one file as feature and lable be addressed/resolved in the future releases?

**Comment by sayanpa** [comment]
Could you please post this question on StackOverflow. We are going to release a Autoencoder tutorial very soon.

**Comment by avader906** [comment]
@sayanpa Why do we want feature requests or issue reports redirected to StackOverflow? Regarding tutorials, what your priority - cleaning up vs new? 

Suppose we have features (under i) and labels (under o)  in a text data file as follows:
```
|i {x} |o {y}
where {x} and {y} are space separated sequences of numeric values
```
Let's make sure that the reader reads the file and trains a network using the standard reader section:

```
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/someFile_train.txt"
        input = [
            i = [
                alias = "i"
		dim = <>        
                format = "dense"
            ]
            o = [
		alias = "o"
                dim = <>
                format = "dense"
            ]
        ]
    ]
```
If now we are to train an autoencoder layer using these 120 features as both input and output - this ***intuitive*** parametrization DOES NOT work: 
```
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/someFile_train.txt"
        input = [
            i = [
                alias = "i"
		dim = <>        
                format = "dense"
            ]
            o = [
		alias = "i"
                dim = <>
                format = "dense"
            ]
        ]
    ]
```
Let's try using deserializer infrastructure:
```
	reader = [
	randomize = false
	frameMode = true 
	keepDataInMemory = false
        verbosity = 0
        deserializers = (
            [
                type = "CNTKTextFormatDeserializer"
                module = "CNTKTextFormatReader"
                file = "$DataDir$/someFile_train.txt"
                input = [
                    i = [
			alias = "i"
                        dim = <>
                        format = "dense"
                    ]
                ]
            ]:
            [
                type = "CNTKTextFormatDeserializer"
                module = "CNTKTextFormatReader"
                file = "$DataDir$/someFile_train.txt"
                input = [
                     o = [
			alias = "i"
                        dim = <>
                        format = "dense"
                    ]
                ]
            ]
        )
    ]
```
This solution is currently unusable due to warnings printed out for each sample
```
WARNING: Unknown input ('o') at offset xyz in the input file. Input name 'o' was not specified
```
and due to the fact that it could potentially only works for small input datasets as the entire data file is loaded into RAM twice pre first epoch.

**Comment by sayanpa** [comment]
May be we can discuss offline the pros and cons about StackOverflow vs Github Issues. You do have a choice. Here is a link that talks about how vscode handles it.

Can you elaborate a bit more on the cleaning up tutorials? Are there specific tutorials you have in mind? Regarding new, we are constantly adding new tutorials. Speaking of which an Autoencoder tutorial is on the way where we use the data as the feature.

**Comment by avader906** [comment]
@sayanpa any suggestions on how to resolve the issue raised in this thread? you can get the feedback regarding the overall state of documentation by looking at the issues being raised by end users.

**Comment by sayanpa** [comment]
We do look at the issues posted and address them as soon as we have answers. This includes documentation / tutorials (for example: https://github.com/Microsoft/CNTK/issues/1279). If you have specific one that we have missed, would appreciate you letting us know.

Stay tuned for the Autoencoder tutorial (in python though) we use the same feature as input and output.  [CNTK 201 tutorial](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb) shows the use of Deserializers and Transforms currently supported in the context of images though.

We will take your inquiry as feedback and look into text deserializers for bugs/gaps. Thanks.

**Comment by avader906** [comment]
@sayanpa I can confirm that the deserializer solution for CNTKTextFormatReader described above works - if someone urgently needs it. Still requires to sit through warnings flood  #1282  and only practical for small datasets.

**Comment by avader906** [comment]
Warnings could be suppressed using
```
reader = [
...
	 deserializers = (
            [
                type = "CNTKTextFormatDeserializer"
                module = "CNTKTextFormatReader"
                file = "$DataDir$/somefile.txt"

--------------> traceLevel=0 <--------------

                input = [
                    i = [
			alias = "i"
                        dim = 120
			format = "dense"
                    ]
                ]
            ]
          )
]
```
as per #1282
