### ISSUE TITLE
Access to trained model data

### ISSUE THREAD

**Issue by thinus-potgieter** [Microsoft/CNTK#1267]
I have trained a model in CNTK using the Python API.   I would like to implement the network in code on an Android device.

Is there a way that I can access the network weights and then code the network directly without using the CNTK library?   

Can I get access to the model in human readable form?

**Comment by sayanpa** [comment]
This is a great question could you please post your question on StackOverflow. Will have the answer ready and post there.

**Comment by thinus-potgieter** [comment]
Thank you

**Comment by sayanpa** [comment]
Already answered in stackoverflow
