### ISSUE TITLE
JavaScript bindings

### ISSUE THREAD

**Issue by baloodevil** [Microsoft/CNTK#1269]
I'd like to see JavaScript bindings enabling us to write applications in JavaScript, in addition to Python, C#, etc.  More precisely, I would like to see Node.js bindings.  Although the word 'Node' in CNTK means something other than the server JavaScript engine.  Node.js bindings would make this accessible to another large community of developers; that don't necessarily have a deep learning background (and don't use python).  By the way, Caffe has [JavaScript bindings](https://github.com/chaosmail/caffejs) and [Node bindings](https://github.com/chaosmail/caffejs) through community projects.

**Comment by avader906** [comment]
What's wrong with using Caffe ?

**Comment by ritazh** [comment]
👍

**Comment by baloodevil** [comment]
Caffe is great!  I'm using it for another project.  
CNTK has several advertised advantages over Caffe.  I'd like to learn CNTK, but would prefer to be in a JavaScript environment while doing so.  And as I said, JavaScript/Node would open the toolset to a lot of other developers.

**Comment by bnookala** [comment]
Yes! Node bindings are invaluable.

**Comment by beary** [comment]
Yes, We need Javascript(or TypeScript) bindings.

**Comment by michaelinipop** [comment]
I am very interested in this feature and would love to explore the opportunity in providing  developer support in  creating this port.  The real question would be what would be the most collaborative way to make this  feature request a reality.  

Thank you , 

Michael Roberts

**Comment by ritazh** [comment]
@nadavbar created this: https://github.com/nadavbar/node-cntk

**Comment by michaelinipop** [comment]
Perfect , that is exactly what I was looking for.  I will go ahead and start playing around with it.

**Comment by cha-zhang** [comment]
This issue seems to have been resolved. I'm closing it now. Feel free to open a new one if needed.
