### ISSUE TITLE
Build from code with Python 3.5 does not build PythonBuildings project

### ISSUE THREAD

**Issue by AurelianoBuendia** [Microsoft/CNTK#1270]
Hello, everyone.
I have tried to build and install CNTK using a previous Anaconda installation with Python 3.5. It appeared to have built it fine, but Python integration was not working. The test with FeedForwardNet.py in the tutorial (https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows), “Optional. CNTK v2 Python Support”, “Step 4: Verify setup”, was giving the message "ImportError: no module named 'cntk'".
I went through this:
1.	I was getting the 45 projects were being built successfully, but then I tried to build PythonBuildings only and I noticed that it was being skipped, because in line 36 of vsbuild.bat (..\cntk\bindings\python) there is an if statement that defines a variable called nothingToBuild in the build script if Python version is not 2.7 or 3.4, so this if needs to be changed to include the version 3.5 of Python
2.	When the PythonBuildings project started to be built, I got an error because the linker was not able to open the file ucrt.lib, so I had to include the directory containing this library, which in my machine was in the folder C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10150.0\ucrt\x64, to the project’s VC++ Directories | Library Directories
3.	Then I got another linker error saying that “localeconv” was already defined in libcmt.lib file. Why this particular file came into play doesn’t seem relevant, the main cause was, as I could research online, some conflict on the Code Generation options from different dependencies. Since this configuration for the PythonBuildings project is made through Makefile, I had to change the file ..\bindings\python\setup.py to add this configuration to the extra_compile_args directive, on line 104: “/MD”,
After this the build of the PythonBuildings project succeeded, and given all the configuration steps, the FeedForwardNet.py script ran as expected.
 I hope this helps and you can check this integration with Python 3.5.
Thanks,

Artur

**Comment by sayanpa** [comment]
Python 3.5 support is currently for Linux only. Win 3.5 support is ion the works.

**Comment by wolfma61** [comment]
no follow-up for a long time, this has changed since then
please open a new issue if you experience this in a more recent CNTK installation
