### ISSUE TITLE
Got segmentation fault when running ResNet example

### ISSUE THREAD

**Issue by infwinston** [Microsoft/CNTK#1273]
Hi,

I was trying to run ResNet examples in the official [directory](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet/BrainScript).
I can run [ResNet20_CIFAR10.cntk](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet20_CIFAR10.cntk) without problems.
But when I tried [ResNet110_CIFAR10.cntk](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet110_CIFAR10.cntk), I got a segmentation fault error.

I used the following command to run the example (use CPU here for simplicity)
```
cntk configFile=ResNet110_CIFAR10.cntk deviceId="-1"
```
and got the error
```
....
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Segmentation fault (core dumped)
```
(check the whole logs [here](https://gist.github.com/infwinston/7f21ed6f417d46261c16f856531a85d1))

The difference between [ResNet20_CIFAR10.cntk](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet20_CIFAR10.cntk) and [ResNet110_CIFAR10.cntk](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet110_CIFAR10.cntk) is the parameter `numLayer`.
(`numLayer=3` for ResNet20, `numLayer=18` for ResNet110)

On my machine, if I specify `numLayer` to be greater than 3, then the segmentation fault will occur.
I can also reproduce the error on another machine, so I think there might be something wrong in CNTK?
Does anyone also face this problem?

I am using the pre-built CNTK version 2.0 Beta 6 with 1-bit sgd.
(on Ubuntu 14.04)

Thanks.

**Comment by infwinston** [comment]
I just found #1074 reported the same issue, but which seems to be unsolved.
Given that ResNet is an important benchmark, may I ask if there will be a fix for this issue in CNTK?
Thanks.

**Comment by mahilleb-msft** [comment]
Can you try after increasing the stack size in your shell session?
For example, `ulimit -s 65536` should be enough.
You can also check your current limits using `ulimit -a`.

If it works we should mention this in the README.

Thanks, Mark

**Comment by infwinston** [comment]
@mahilleb-msft 
Thanks for the quick fix. By increasing size to 65536, it works well now.
