### ISSUE TITLE
How to output per sample prediction if the samples come from reader.next_minibatch

### ISSUE THREAD

**Issue by MS-NLP** [Microsoft/CNTK#1275]
Hi all,
    Having trained a regression model using CNTK v2, I am trying to use the model to give prediction score for each sample in test set as follows:

```
        while True:
            data = reader.next_minibatch(self._mini_batch_size, input_map=input_map) # fetch minibatch
            if not data:
                break
            eval = self._trainer.test_minibatch(data)
            total_eval += eval
```

However, I found that the variable "eval" is a scalar describing the average eval metric of the current mini-batch, not the eval metric per sample. I am wondering whether there is any method to:
(1) fetch the prediction score, and 
(2) fetch the prediction score per sample

(In my code, I use the node self.prediction to represent the prediction score, I tried to use self.prediction.eval() method, but failed due to exception thrown. It seems that eval() method cannot take only nparray as input but not the object returned by reader.next_minibatch) 

Thanks!

**Comment by sayanpa** [comment]
May be you can try the eval function as shown in the following tutorial:
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_103B_MNIST_FeedForwardNetwork.ipynb
