### ISSUE TITLE
Predict value using existing model

### ISSUE THREAD

**Issue by ccsquare** [Microsoft/CNTK#1276]
In CNTK 2, how should I use the reloaded model to predict the value according to the input features. Namely the similar function to the following part in BrainScript:
output = {
    action = "write"

    reader = {
        readerType = "CNTKTextFormatReader"
        file = "$testFilePath$"

        input = {
            FeatureA = { dim = $LeftFeatures_Dim$; format = "sparse"}

            FeatureB = { dim = $RightFeatures_Dim$; format = "sparse" }
        }
    }
    outputPath = "$OutputDir$/predicted_results.txt"
}

**Comment by MS-NLP** [comment]
Solved in [this issue](https://github.com/Microsoft/CNTK/issues/1275)
