### ISSUE TITLE
CNTK on Windows and Visual Studio 2015

### ISSUE THREAD

**Issue by wolfma61** [Microsoft/CNTK#1277]
***2017-01-10.* CNTK for Windows supports Visual 2015**

If you pull or merge the master branch, CNTK will now require Visual Studio 2015 to build on Windows. There are two ways to move your development environment to Visual Studio 2015:

[Migrate VS2013 to VS2015](https://github.com/Microsoft/CNTK/wiki/Setup-Migrate-VS13-to-VS15):
This gives you a fine grained control over where components are installed 

[Script driven setup](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-with-script-on-Windows):
This gives you an mostly automated migration to Visual Studio 2015

thx
Wolfgang

**Comment by bencherian** [comment]
Why is this an issue?

**Comment by wolfma61** [comment]
not an issue - just increasing visibility, 
but should have been closed a long time ago ...
