### ISSUE TITLE
Tutorial2 wiki has broken links

### ISSUE THREAD

**Issue by ahoink** [Microsoft/CNTK#1279]
The links for the config files and shared functions (a total of six links) are broken and lead to a "404 Not Found" page. The wiki page in question is located here: https://github.com/Microsoft/CNTK/wiki/Tutorial2

**Comment by sayanpa** [comment]
Thanks for pointing out the missing links on a tutorial using now deprecated model specification language. The tutorial is replaced by an updated one: https://github.com/Microsoft/CNTK/wiki/Tutorials

**Comment by pkranen** [comment]
Thanks for pointing out. The broken links were pointing to a file called `Shared.bs` (and its ndl pendant) which contained macros for different layers. The layers are now defined in [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) and are widely used throughout the brain script examples and tutorials. For documentation of layers in brain script see also [the full function reference page](https://github.com/Microsoft/CNTK/wiki/Full-Function-Reference) and [the layers library page](https://github.com/Microsoft/CNTK/wiki/Layers-Library-Reference).
