### ISSUE TITLE
Unknown identifier 'RandomSample'

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1281]
I want to use 'RandomSample' in BrainScript which is defined in the source code of CNTK in 'TrainingNodes.h' as 'RandomSampleNode'.
But it says unknown identifier 'RandomSample'. Are there anything else to do to use this node? Or any replacement for RamdomSample in BrainScript?

**Comment by thilow** [comment]
The name of the BS operators is GetRandomSample. Please note that it is defined within the CNTK2 namespace.
Here is the definition from core.bs:
  ```
  // The value of GetRandomSample(weights /* vector of length nClasses */, numSamples, sampleWithReplacement) randomly samples numSamples using the specified sampling weights. 
    // The result is a sparse matrix of num samples one-hot vectors as columns.
    GetRandomSample(_ ,numSamples, sampleWithReplacement, tag='') = new ComputationNode [
                                                                                        operation = 'RandomSample' ;
                                                                                        sizeOfSampledSet = numSamples;
                                                                                        allowDuplicates = sampleWithReplacement;
                                                                                        inputs = _ /*plus the function args*/ ]


```

**Comment by yttdebaba2** [comment]
I change it to 'GetRandomSample', but it still says unknown identifier 'GetRandomSample'

**Comment by yttdebaba2** [comment]
`[CALL STACK]`
`  network = new ComputationNetwork [`
`                     4`
`          negEmbe = negembedding * negSamples`
`                                                       3 2`
`          negSamples = GetRandomSample(dicts, negDim, false)`
`                                  ^                              1`
`EXCEPTION occurred. while evaluating: BrainScriptNetworkBuilder(14): unknown identifier 'GetRandomSample'`

**Comment by thilow** [comment]
Try CNTK2.GetRandomSample(...)

**Comment by yttdebaba2** [comment]
It works. Thank you very much :)
