### ISSUE TITLE
CNTKTextFormatDeserializer verbosity = 0 does not suppress all warnings (2.0 b7 GPU 1bit binary)

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1282]
The deserializer gives a warning for ***each*** input sample despite verbosity = 0 parameter if not all inputs used:
```
WARNING: Unknown input ('o') at offset xyz in the input file. Input name 'o' was not specified
```

Data:
```
|i {x} |o {y}
where {x} and {y} are space separated sequences of numeric values
```
BS configuration:
```
reader = [
         verbosity = 0
...
	 deserializers = (
            [
                type = "CNTKTextFormatDeserializer"
                module = "CNTKTextFormatReader"
                file = "$DataDir$/somefile.txt"
                input = [
                    i = [
			alias = "i"
                        dim = 120
			format = "dense"
                    ]
                ]
            ]
          )
]

**Comment by sayanpa** [comment]
We have filed a bug for this. Thanks for reporting.

**Comment by avader906** [comment]
@sayanpa the issue still present in beta 8

**Comment by raaaar** [comment]
This extra output can be suppressed by setting the **traceLevel** to 0:

```
reader = [
...
	 deserializers = (
            [
                type = "CNTKTextFormatDeserializer"
                module = "CNTKTextFormatReader"
                file = "$DataDir$/somefile.txt"
                traceLevel=0
                input = [
                    i = [
			alias = "i"
                        dim = 120
			format = "dense"
                    ]
                ]
            ]
          )
]
```

**Comment by avader906** [comment]
@raaaar this does not solve the issue. traceLevel is a global flag while documentation refers to verbosity is the flag proper to the reader section and thus should suppress any and all warnings when set to 0.  why do we rely on the traceLevel to do that instead ?

**Comment by raaaar** [comment]
Actually, it's the other way around: verbosity is a global flag, traceLevel is the [CTF specific flag](https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader#reader-section). That said, having two flags do the same thing is somewhat confusing, especially since the CTF ignores the "verbosity" setting. Something we need to clean up.

**Comment by avader906** [comment]
@raaaar ROFL - so there are three different places where verbosity control is described and handled in the documentation:
```
https://github.com/Microsoft/CNTK/wiki/Top-level-configurations
https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers
https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader#reader-section
```
You mean ***verbosity*** is a global flag for reader sections?

By global I mean the flags described and used in top level configuration section - like ***precision*** and ***traceLevel*** - flags that are inherited and used as default for subsequent modules.

If the Readers design docs list ***verbosity*** flag as specifically regulating reader section - then its behavior across all readers should be consistent.

If CTF has it's own further parametrization, like maxErrors, the hierarchy and naming should avoid all confusion. Which in our case is confusing both in naming and behavior.

```
In order to force the reader to show a warning for each input error it ignores (in the sense of not raising an exception), non-default maxErrors value should be used in combination with the traceLevel set to 1 or above.
```

**Comment by raaaar** [comment]
"verbosity" is redundant, it was introduced in the composite reader mostly because its design was strongly influenced by the legacy HTK-MLF reader (so, in a sense, it was inherited). The rest of the codebase uses "traceLevel". So, we'll need to drop verbosity and use traceLevel instead.

**Comment by avader906** [comment]
how would traceLevel be resolved between global scope, action=[], action= [ reader [] ], action = [ reader [  deserializers (..) ] ] and action = [ reader [  deserializers ([...]:[...]) ] ]? 

inherited from level up scope unless overridden ? if there is no relationship or no inheritance of behavior from one scope to another, would naming a flag differently be a more logical approach ?

**Comment by raaaar** [comment]
Nested scopes inherit values from parent scopes, locally scoped values override globally scoped values. One flag to control the output verbosity should be enough.

**Comment by avader906** [comment]
Thank you. This is now all very clear. The issue is the documentation that needs consolidation and update.
