### ISSUE TITLE
How to load input from file as a single 2D tensor

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1283]
I am doing text processing using BrainScript, and save the dictionary in a .txt file. I use CNTKTextFormatReader to read the dictionary from file (the dictionary only have one line that store the frequencies of the words, as a dense vector). And an exception occurred:
`Node 'dicts' (InputValue operation): Minibatch data cannot be interpreted as a single 2D tensor.`

How can I load the dictionary from file as a single 2D tensor with BrainScript?

**Comment by avader906** [comment]
Have you tried something like this ?
```
dictShape = 50:50:1  #or any required x:y or x:y:z dimension
features = Input {dictShape}
```

**Comment by cha-zhang** [comment]
@ghost was right, Tutorials like https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_103B_MNIST_LogisticRegression.ipynb uses text reader to load image data. 

This thread has been too old. I'm closing this now. Please reopen a new issue if needed. Thanks!
