### ISSUE TITLE
Unsupported Computation Node when using CNTKlibrary-2.0

### ISSUE THREAD

**Issue by timolohrenz** [Microsoft/CNTK#1284]
Dear CNTK team,

For my research have trained a feedforward DNN model using the CNTK.exe built from beta7.0+. As it is a model for speech recognition purposes, I perform feature normalization at the models input. Therefore I use the Mean operation for normalization and to extract the prior knowledge from the training labels.

Now I am writing a script to evaluate this model in my code using the new CNTKLibrary-2.0 (also built from beta7.0+). Whenever I try to load the pre-existing model using 

`
		auto modelFuncPtr = CNTK::Function::LoadModel(modelPath, DeviceDescriptor::CPUDevice());
`
i get the following error message 

> What() is:Unsupported ComputationNode with OperationName='Mean' found when loading legacy CNTK model

This error even appears when I remove all 'Mean' nodes from the network. 

As stated in the Wiki, the CNTK.exe can up to now only generate the V1 models and is declared as legacy model. Might this be an issue?

**Comment by sayanpa** [comment]
Would it be possible for you to try loading the module using python APIs? There are some recipes in CNTK Github - How do I section.

**Comment by timolohrenz** [comment]
Hey there,
yes, finally I got the python API running and with the following minimal code   

`from cntk import load_model`
`model_path = "E:\\py_test_dnn.dnn"`
`loaded_model = load_model(model_path)`

i still get  "
> Unsupported ComputationNode with OperationName='Mean' found when loading legacy CNTK model"

Seen this error in some other issues, e.g.,  [https://github.com/Microsoft/CNTK/issues/1365](url). Can I somehow validate that the Mean node is still supported in the v2.0 library?

**Comment by cha-zhang** [comment]
We are looking into it. Please stay tuned.

**Comment by cha-zhang** [comment]
@timolohrenz , since #1365 has been resolved I believe this is also resolved. I'm closing it now. Feel free to open a new issue if needed.
