### ISSUE TITLE
Wrong output dimension on V2 Beta 7

### ISSUE THREAD

**Issue by rafael-aero** [Microsoft/CNTK#1285]
I'm implementing intent detection following the CNTK_202_Language_Understanding.ipynb, and when updating from the Beta 6 to Beta 7, the network output size changed from [num_labels] to [seq_size x num_labels]. 
Seems like the sequence reduction using apply_x = splice ([sequence.last(F(x)), sequence.first(G(x))]) is not working anymore. Is this a known issue?

**Comment by rafael-aero** [comment]
Perhaps related to this change:

> Sequences now have to be provided as single NumPy or Scipy sparse arrays. I.e., it is not any more allowed to provide a sequence as a list of NumPy arrays or Scipy sparse arrays.

**Comment by cha-zhang** [comment]
I hope this issue have been resolved by now. If not, please open a new issue. Thanks!
