### ISSUE TITLE
Random file read error 

### ISSUE THREAD

**Issue by minsikcho** [Microsoft/CNTK#1286]
I was trying the googlenet brainscript example in the latest cntk. I downloaded fresh imagenet set and made train_map.txt. Everything looked good util this point.

However, when I run cntk, it stops with exception as in the picture in a RANDOM manner. 
![1](https://cloud.githubusercontent.com/assets/19735183/21912171/e8a57d62-d8e9-11e6-9f6c-44450a6f552f.png)
![2](https://cloud.githubusercontent.com/assets/19735183/21912183/f28da21e-d8e9-11e6-8cc4-a39af6964715.png)

Everytime, I run, it stops with different file names and when I follow up with "ls", then file actually exists.

Any suggestion?

**Comment by eldakms** [comment]
did you specify full path in train_map.txt?

**Comment by eldakms** [comment]
There were some fixes in this area couple of months ago. Please try out the new binaries. If the issue still exists feel free to reopen. Thanks!
