### ISSUE TITLE
download failed on https://sourceforge.net/projects/boost/files/boost-binaries/1.60.0/boost_1_60_0-msvc-14.0-64.exe

### ISSUE THREAD

**Issue by loveJasmine** [Microsoft/CNTK#1291]

**Comment by junjieqian** [comment]
Can you give more details? The boost file can be downloaded on https://sourceforge.net/projects/boost/files/boost-binaries/1.60.0/.

**Comment by loveJasmine** [comment]
sorry, it's china net issue
