### ISSUE TITLE
Developer CNTK --> FastRCNN - EXCEPTION occurred while runing A2_RunCntk.py: Plugin not found: 'CompositeDataReader.dll'

### ISSUE THREAD

**Issue by Joracosu** [Microsoft/CNTK#1293]
I have Windows 10. I have followed the manual development setup and the migration from VS13 to VS15 to install CNTK in my computer.

While execution of FastRCNN A2_RunCntk.py, only and exception is reached with this final message: AssertionError: ERROR: cntk ended with exit code 1

See the complete execution of A2_RunCntk: [Log.txt](https://github.com/Microsoft/CNTK/files/705524/Log.txt). Please help

**Comment by pkranen** [comment]
This means the 'CompositeDataReader.dll cannot be loaded. Please make sure that the folder that contains 'CompositeDataReader.dll' is in your PATH environment variable. If not, you can add it using 'set PATH=C:\src\CNTK\x64\Release\;%PATH%' from a command line (assuming the dll is in 'C:\src\CNTK\x64\Release' on your machine).

**Comment by Joracosu** [comment]
First of all, thank you for your response.
I have already set the path to the cntk release folder. But the problem is that the mentioned dll is not anywhere in the cntk folder! 
I've followed carefully the instructions to install CNTK as a developer (https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows) but the dll doesn't appear to be added when build, I can't find it.

**Comment by eldakms** [comment]
if you select the CompositeDataReader in VS, right click and build it - could you please insert the output of the build process here?
Thanks!

**Comment by Joracosu** [comment]
Ok, I built  CompositeDataReader.dll
After that, I tried again A2_RunCntk.py and had to install also CNTKTextFormatReader
And once again I tried the example and again I had to install ImageReader.dll

In this point y get stuck with ImageReader.dll with the error LNK1201. Lots of problems. I think I have to reinstall OpenCV and also zlib and libzip, but will continue tomorrow.

NOTE: I was writing a reply when suddenly my computer turned off, so now I am giving much less details. Sorry about that

**Comment by Joracosu** [comment]
Finally I solve the problem: I used HP RecoveryManager to reset the PC and reinstalled CNTK but this time using the script-driven installation.
NOTE: FastRCNN Works fine with Python 3.4 but fails with Python 3.5, so you need to launch the script especifying the 3.4 version --> ./devinstall.ps1 -PyVersion 34 -Execute
