### ISSUE TITLE
Deserializers reader problem

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1294]
I read 2 files using deserializer reader in BrainScript. One is the feature-label file which contains multiple samples, the other is the dictionary file which contains only 1 vector that record the frequencies that the words appear.

Now in each epoch, CNTK only process 1 minibatch loop with 1 sample since the dictionary only contains 1 vector, although I set minibatchsize=1024 in SGD block.

The question is, how can I read the dictionary file repeatedly to match the size of the feature-label file? Since the dictionary is large and the disk memory is not enough to copy the dictionary vector so many times.

**Comment by avader906** [comment]
Please provide sufficient information to reproduce the issue you are facing. Sample code and error messages would help.

**Comment by yttdebaba2** [comment]
I used the following BrainScript:
`deserializers=([`
`----type = "CNTKTextFormatDeserializer"`
`----module = "CNTKTextFormatReader"`
`----file = "feature_label.txt"`
`----input = [`
`--------word=[`
`------------alias="w"`
`------------dim=$wordCount$`
`------------format="sparse"`
`--------]`
`--------label=[`
`------------alias="l"`
`------------dim=$wordCount$`
`------------format="sparse"`
`--------]`
`----]`
`]:`
`[`
`----type = "CNTKTextFormatDeserializer"`
`----module = "CNTKTextFormatReader"`
`----file = "feature_label.txt"`
`----input = [`
`--------dicts=[`
`------------alias="d"`
`------------dim=$wordCount$`
`------------format="dense"`
`--------]`
`----]`
`])`
to read the feature-label file (more than 30,000,000 lines):
`|w 3120:1 |l 21463:1`
`|w 125:1 |l 16341:1`
`...`
and read the dictionary file:
`|d 13682 13157 12098 10963 9782 ... (each number represent the frequency of the word in ascending order`

Now I set:
`SGD = [`
`        ----maxEpochs = 20`
`        ----minibatchSize = 1024`
`        ----gradUpdateType = "adagrad"`
`        ----learningRatesPerSample = 0.01`
`    ]
and I want to train the whole feature-label file with the help of the dictionary file.

But I got the following training message:
`Perf trace: Worker MB size = 1, Read = 0.00046s; Compute = 0.59169s; Parameter update = 4.5913s; Parameter sync = 3e-006s; Aggregate MB size = 1`
` Epoch[ 1 of 20]-Minibatch[   1-   1]: cr = 4.16113281 * 1; time = 5.1837s; samplesPerSecond = 0.4
Finished Epoch[ 1 of 20]: [Training] cr = 4.16191597 * 2050; totalSamplesSeen = 2050; learningRatePerSample = 0.0099999998; epochTime=108.203s`
`SGD: Saving checkpoint model 'work/wordembedding.1'`

`Perf trace: Worker MB size = 1, Read = 0.00046s; Compute = 0.59169s; Parameter update = 4.5913s; Parameter sync = 3e-006s; Aggregate MB size = 1`
` Epoch[ 2 of 20]-Minibatch[   1-   1]: cr = 4.16113281 * 1; time = 5.1837s; samplesPerSecond = 0.4
Finished Epoch[ 2 of 20]: [Training] cr = 4.16191597 * 2050; totalSamplesSeen = 2050; learningRatePerSample = 0.0099999998; epochTime=108.203s`
`SGD: Saving checkpoint model 'work/wordembedding.1'`

It seems that only 1 line in the feature-label file is trained in each epoch. Is it because of that the dictionary file only has 1 line? What can I do if I do not want to extend the dictionary file to fit the size of the feature-label file (more that 30,000,000 lines) since it will take about 60TB disk space to save the extended dictionary file.

**Comment by avader906** [comment]
Have you looked at loading the dictionary via ParameterTensor{} - as a sequence of model constants (with learningRateMultiplier=0.0) ?

https://github.com/Microsoft/CNTK/wiki/Parameters-And-Constants#parametertensor

If i understand correctly, you need the support for loading constants via the reader or by other means. Please correct me if wrong.

**Comment by yttdebaba2** [comment]
I used ParameterTensor and the dictionary file is:
`418391`
`1061396`
`593677`
`...`
however I get the following error message:
`WARNING: Empty input row at offset 8 in the input file (dict.txt).`
`WARNING: Could not read a row (# 1) while loading sequence (id = 418391) at offset 8 in the input file (dict.txt).`

When I add the id in each line:
`1 418391`
`2 1061396`
`3 593677`
`...`
the following error message occors:
`About to throw exception 'VerifySize: expected matrix size 50000 x 1, but it is 50000 x 2'`

What should the format of the dictionary file be? I cannot find an example on github.

**Comment by avader906** [comment]
from https://github.com/Microsoft/CNTK/wiki/Parameters-And-Constants#parametertensor
```
Reading initial values from files

The initial values can be read from a text file. To do this, pass a pathname for the optional parameter initFromFilePath. The text file is expected to consist of one line per matrix rows, which consist of space-separated numbers, one per column. The row and column dimensions in the file must match shape.
```
Maybe you can check it on a small file - make sure it loads the constants and you can work with them in your model. The issue could be line endings (\n or \r\n), or an empty row in your file.

If you add line numbers to your dictionary file, you must reflect the extra column in your tensor dimension - 50000x2 - the error makes sense.

**Comment by yttdebaba2** [comment]
thank you very much!
:)
