### ISSUE TITLE
How to get every column of  a matrix

### ISSUE THREAD

**Issue by luyamalu** [Microsoft/CNTK#1297]
Hi,I have a matrix A,how can I get every column of it?
In fact,now I want to realize the following formula:∑x`Bx.Here,B is another matrix,x is every column of A.
Thank you very much!

**Comment by cha-zhang** [comment]
CNTK supports Numpy like matrix operation, so you can refer to a matrix column as A[:,1]. 

This thread has been too old and I'm closing this now. Please reopen a new issue if needed. Thanks!
