### ISSUE TITLE
Need Label file for Image Regression Sample

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/CNTK#1299]
The file is pulled in here, but no indication as to how this file should be formatted.  It would be great to have the following items:

1.  Exact specification for exactly how that file must be formatted.
2.  That exact file.
3.  How to do this same exact sample, except with python.
      
      type = "CNTKTextFormatDeserializer" ; module = "CNTKTextFormatReader"
            file = "$dataDir$/train_regrLabels.txt"
            input = {
                regrLabels = { dim = 3 ; format = "dense" }
            }

Here is the example: https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Regression

**Comment by avader906** [comment]
@drcrook1 https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Regression has all the instructions you need to download the publicly available dataset. Please go over python tutorials to learn the syntax, be able to load a dataset and use CNTK in that environment.

**Comment by drcrook1** [comment]
@avader906 The label files included with cifar are the simple image classification, not the regression label files.  You reference the file train_regrLabels.txt in your sample, which is not included with the CIFAR-10 or CIFAR-100 data set.  I need that label file.

**Comment by avader906** [comment]
@drcrook1 read and follow the instuctions
```
To generate the ground truth labels for this regression task, the CIFAR-10 installation script in DataSets/CIFAR-10 will generate two additional files, train_regrLabels.txt and test_regrLabels.txt, for train and test respectively.
```
