### ISSUE TITLE
CNTK 1bit-SGD License not available

### ISSUE THREAD

**Issue by marcj** [Microsoft/CNTK#13]
In the wiki of this repo on the right hand side and at https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD is a link to "CNTK 1bit-SGD License" `https://github.com/Microsoft/CNTK-1bit-SGD/blob/master/LICENSE.md` which leads to a 404 because the repo doesn't exist yet :)

**Comment by mahilleb-msft** [comment]
Thanks, fixed with 0396da5e095176134a1398c42265d0ef5e7694d3 on https://github.com/Microsoft/CNTK.wiki.git.
