### ISSUE TITLE
How to get the trace of a matrix

### ISSUE THREAD

**Issue by luyamalu** [Microsoft/CNTK#1300]
Hi!I want to get the trace of a matrix.How can I do it?
Thank you very much!

**Comment by thilow** [comment]
One way that comes to my mind would be to reshape the matrix to a vector (i.e. shape (dim: dim)->(dim*dim: 1)), and also reshape an identity matrix to a vector then take scalar product of both vectors.

**Comment by luyamalu** [comment]
Thank you a million!But the question is that I do not know the dims of the matrix,so that solution dose not work.

**Comment by luyamalu** [comment]
Now I know the dims of the matrix .But the question is that how can I delimit an identity matrix in CNTK.
I am so sorry to trouble you again.Thank you very much!

**Comment by thilow** [comment]
One way would be to provide the unit matrix as a constant. In case you are using the Python api you can simply initialize the constant using a numpy array, like:
    m = C.Constant(np.eye(hidden_dim, dtype=np.float32))

In case you use brainscript you might read the constant from a file.

**Comment by luyamalu** [comment]
Thank you very much!!I will try it.:）
