### ISSUE TITLE
Generative Adversarial Nets implemented by CNTK

### ISSUE THREAD

**Issue by Feng-long** [Microsoft/CNTK#1301]
Hi,  I am just wondering whether GAN(Generative Adversarial Nets) can be implemented with CNTK? Could anyone give some suggestions?

Thanks very much.

**Comment by cha-zhang** [comment]
We are working on it. Should finish in a week or two.

**Comment by Feng-long** [comment]
Looking forward to seeing the wonderful implementation of GAN by CNTK :)

**Comment by raaaar** [comment]
Here's a [tutorial ](https://github.com/Microsoft/CNTK/blob/v2.0.beta10.0/Tutorials/CNTK_206_Basic_GAN.ipynb)that shows how to do that in Python.
