### ISSUE TITLE
report a GoogLeNet example script error

### ISSUE THREAD

**Issue by zhandongdong** [Microsoft/CNTK#1302]
In the original script:
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/GoogLeNet/BrainScript/InceptionV3.bs

    # Auxiliary
    # 8 x 8 x 1280
    aux_pool_1 = AveragePoolingLayer{(5:5), pad = false}(mixed_8)
    # 3 x 3 x 1280
    aux_conv_1 = ConvBNReLULayer{128, (1:1), (1:1), pad=true, bnTimeConst = bnTimeConst}(aux_pool_1)
    # 3 x 3 x 128
    aux_conv_2 = ConvBNReLULayer{768, (3:3), (1:1), pad=false, bnTimeConst = bnTimeConst}(aux_conv_1)

    aux = DenseLayer{labelDim}(aux_conv_2)

where mixed_8 is actually not 8 x 8 x 1280 but 17 x 17 x 768, which will lead to very big parameter number:

Node 'model.aux.arrayOfFunctions[0].W' (LearnableParameter operation) : [LabelDim x 11 x 11 x 768]

Two ways to resolve this error:

change mixed_8 to mixed_9 according to the intent of comments:

    # Auxiliary
    # 8 x 8 x 1280
    aux_pool_1 = AveragePoolingLayer{(5:5), pad = false}(mixed_9)
    # 3 x 3 x 1280
    aux_conv_1 = ConvBNReLULayer{128, (1:1), (1:1), pad=true, bnTimeConst = bnTimeConst}(aux_pool_1)
    # 3 x 3 x 128
    aux_conv_2 = ConvBNReLULayer{768, (3:3), (1:1), pad=false, bnTimeConst = bnTimeConst}(aux_conv_1)
    # 1 x 1 x 768
    aux = DenseLayer{labelDim}(aux_conv_2)

or change according to paper:
![image](https://cloud.githubusercontent.com/assets/8175748/21975475/c709f310-dc07-11e6-81fb-53e0bf7103ae.png)

    # Auxiliary
    # 17 x 17 x 768
    aux_pool_1 = AveragePoolingLayer{(5:5), stride = 3, pad = false}(mixed_8)
    # 5 x 5 x 768
    aux_conv_1 = ConvBNReLULayer{128, (1:1), (1:1), pad=true, bnTimeConst = bnTimeConst}(aux_pool_1)
    # 5 x 5 x 128
    aux_conv_2 = DenseLayer{1024}(aux_conv_1)
    # 1 x 1 x 1024
    aux = DenseLayer{labelDim}(aux_conv_2)

**Comment by ebarsoumMS** [comment]
Thank you for reporting the issue, here the correct implementation:

    # Auxiliary
    # 17 x 17 x 768
    aux_pool_1 = AveragePoolingLayer{(5:5), , stride = (3:3), pad = false}(mixed_8)
    # 5 x 5 x 768
    aux_conv_1 = ConvBNReLULayer{128, (1:1), (1:1), pad=true, bnTimeConst = bnTimeConst}(aux_pool_1)
    # 5 x 5 x 128
    aux_conv_2 = ConvBNReLULayer{768, (5:5), (1:1), pad=false, bnTimeConst = bnTimeConst}(aux_conv_1)
    # 1 x 1 x 768    
    aux = DenseLayer{labelDim}(aux_conv_2)

It matches the one implemented in TF (line 250): https://github.com/tensorflow/models/blob/master/inception/inception/slim/inception_model.py

**Comment by ebarsoumMS** [comment]
Fix in master.
