### ISSUE TITLE
Batch normalization training on CPU is not yet implemented (2.0 b7 GPU 1bit binary)

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1303]
Training CNN with BatchNormalization() results in:
```
EXCEPTION occurred: Batch normalization training on CPU is not yet implemented
```

Same script fails on the fresh 2.0 beta ***8*** GPU 1bit binary (with the same message as in b7 re Using CNTK batch normalization engine)

Any rough idea on ETA?

**Comment by KeDengMS** [comment]
Training support for batch normalization on CPU is on our TODO list. In the meanwhile, please train with GPU if possible.

**Comment by avader906** [comment]
@KeDengMS I understand your priorities. If this is not on TODO list, please consider it for the prioritization along other FEATURES REQUESTED list

Release notes for beta 8 mention this:
```
Batch normalization.

If cuDNN batch normalization engine is not available, 
 the CNTK batch normalization engine is used as a fall back.
A model trained with cuDNN batch normalization can now be inferred on CPU.
```

Is the fallback CPU only then? The fallback is not inclusive of training? This should be made blatantly clear.

There is a lot of OS code around for this. One in particular comes to mind: MKL-DNN under Apache license. https://github.com/01org/mkl-dnn

**Comment by KeDengMS** [comment]
Thanks for the reference implementation. We'll keep you posted on the progress of this issue.

**Comment by bencherian** [comment]
Any update on this? (Is it expected by 2.0 release?) It would be nice to verify code functionality on a CPU only system prior to taking up time on a GPU system.

**Comment by KeDengMS** [comment]
We are working with Intel to incorporate MKL DNN for CPU support on BN/conv/pooling after 2.0 release. In the meanwhile, we would be much appreciated on contribution from the community on this issue.

**Comment by bencherian** [comment]
Thanks for the update, that's probably a bit too large of a project to undertake myself, but I'm looking forward to it.

**Comment by philippgille** [comment]
This issue still exists, right?

I tried:
1. `docker run -it --rm -w /cntk/Examples/Image/DataSets/CIFAR-10 microsoft/cntk:2.0.rc3-cpu-python3.5`
2. `python install_cifar10.py`
3. `cd /cntk/Examples/Image/Classification/ResNet/Python`
4. `python TrainResNet_CIFAR10.py -n resnet20`

And I get:  
`RuntimeError: Batch normalization training on CPU is not yet implemented.`

All the resources about CNTK (GitHub wiki, website, Youtube videos, foreign articles) state that CNTK can be used with CPU. But this basic training doesn't work on a CPU.

Am I doing anything wrong or does model training simply not work with a CPU in CNTK? Why doesn't the README (`Examples\Image\Classification\ResNet\Python\README.md`) mention that?

**Comment by moprescu** [comment]
+1 I have the same issue

**Comment by ThiagoSousa** [comment]
+1 I have the same issue

**Comment by JimSEOW** [comment]
+1 today

**Comment by JimSEOW** [comment]
Can anyone share a link to  **ResNet_20.model**  ??

**Comment by KeDengMS** [comment]
@JimSEOW Uploaded [ResNet20_CIFAR10 model](https://www.cntk.ai/Models/CNTK_Pretrained/ResNet20_CIFAR10_Python.model)

**Comment by JimSEOW** [comment]
@KeDengMS  Big Thanks!

**Comment by KeDengMS** [comment]
[Fixed](https://github.com/Microsoft/CNTK/commit/1d3d1e8a2770b65a809f6bf7e6cde49047ffc0c6)
