### ISSUE TITLE
Weight decay regularization in BrainScript

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#1304]
I am trying to add a weight decay regularization in a BrainScript network description like this (let us assume that there is only one matrix `W `of parameters):

`regul = regulStrength*Sum(W.*W)`

but get the following error:

> EXCEPTION occurred. while evaluating: BrainScriptNetworkBuilder(127): unknown identifier 'Sum'

If I define:

`Sum(x) = BS.Sequences.FoldL(Plus, 0, x)`

I get this error:

>       Sum(x) = BS.Sequences.FoldL(Plus, 0, x)
>                                      1
>       FoldL (binaryOp, x0, x) = _Fold (PastValue,   binaryOp, x0, x)
>                                       0^
> EXCEPTION occurred. while evaluating: /path/to/CNTK-2.0.beta7.0/bin/cntk.core.bs(820): function expects 3 positional parameters, 4 were provided

Maybe, I am not understanding something... Could you please let me know how one could implement WeightDecay regularization in CNTK BrainScript network description?

Thank you!

**Comment by cha-zhang** [comment]
Have you tried using ReduceSum? 
https://github.com/Microsoft/CNTK/wiki/Reduction-Operations

**Comment by svml** [comment]
Thank you very much for your reply, @cha-zhang - I will try it. 

My understanding is that to sum elements of a 2D matrix, I need to "reduce" it twice (along each dimension).
