### ISSUE TITLE
Is there a 2.0 binary release for CPU only systems with 1bit-SGD

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#1308]
Why would the current CPU only binary release support ASGD but not 1bit SGD ?

https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines

**Comment by sayanpa** [comment]
CPU with 1 bit SGD is possible to build out of sources that you can try. We do not support that as our regular release builds.

**Comment by chrisbasoglu** [comment]
it is just a build/test decision.
