### ISSUE TITLE
LSTM for classification does not work

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#1309]
For some reason, using LSTM for classification does not work for me. For regression, I do:

`        outputs = W * LSTMoutput + b`
`        cr = SquareError(labels, outputs)`
`        criterionNodes  = (cr)`
`        outputNodes     = (outputs)`
 
and it works. However, 

`        outputs = Sigmoid(W * LSTMoutput + b)`
`        cr = Logistic(labels, outputs)`
`        criterionNodes  = (cr)`
`        outputNodes     = (outputs)`

always produces zero as output and there is no reduction of the loss function during training.

If possible, please, let me know if it is something CNTK can not do, or I am misunderstanding the meaning of the functions.

**Comment by sayanpa** [comment]
Would it be possible for you to please send us a repro. We certainly support classification.

**Comment by svml** [comment]
I have an indication of where the problem might be (for the tests below I used CNTK-2.0.beta6.0 since it seems to work better than CNTK-2.0.beta8.0). 

In both tests below:

`outputs = Sigmoid(W * LSTMoutput + b)`
`outputNodes     = (outputs)`

If I use

`cr = Logistic(labels, outputs)`
`criterionNodes  = (cr)`

then classification training fails. Here is a quick comparison of input file vs output (data sets: Traing=Test) - this is a diff of model output vs input:

> 0.000000    | |f -0.416147 0.540302 |l 0
> 0.000000    | |f -0.989992 -0.416147 |l 0
> 0.000000    | |f -0.653644 -0.989992 |l 1
> 0.000000    | |f 0.283662 -0.653644 |l 1
> 0.000000    | |f 0.96017 0.283662 |l 1
> 0.000000    | |f 0.753902 0.96017 |l 0
> 0.000000    | |f -0.1455 0.753902 |l 0
> 0.000000    | |f -0.91113 -0.1455 |l 0
> 0.000000    | |f -0.839072 -0.91113 |l 1
> 0.000000    | |f 0.0044257 -0.839072 |l 1
> 0.000000    | |f 0.843854 0.0044257 |l 1
> 0.000000    | |f 0.907447 0.843854 |l 1
> 0.000000    | |f 0.136737 0.907447 |l 0
> 0.000000    | |f -0.759688 0.136737 |l 0
> 0.000000    | |f -0.957659 -0.759688 |l 0
> 0.000000    | |f -0.275163 -0.957659 |l 1
> 0.000000    | |f 0.660317 -0.275163 |l 1
> 0.000000    | |f 0.988705 0.660317 |l 1
> 0.000000    | |f 0.408082 0.988705 |l 0
> 0.000000    | |f -0.547729 0.408082 |l 0
> 0.000000    | |f -0.999961 -0.547729 |l 0
> 0.000000    | |f -0.532833 -0.999961 |l 1
> 0.000000    | |f 0.424179 -0.532833 |l 1
> 0.000000    | |f 0.991203 0.424179 |l 1
> 0.000000    | |f 0.646919 0.991203 |l 0
> 0.000000    | |f -0.292139 0.646919 |l 0
> 0.000000    | |f -0.962606 -0.292139 |l 0
> ...

However, if I use

`cr = -( TransposeTimes(labels, Log(outputs)) + TransposeTimes(Constant(1)-labels, Log(Constant(1)-outputs)) )`
`criterionNodes  = (cr)`

then classification training works (strangely, though the output says "Training criterion:   cr = Negate") - this is a diff of model output vs input (again, data sets Training=Test):

> 0.000008    | |f -0.416147 0.540302 |l 0
> 0.001706    | |f -0.989992 -0.416147 |l 0
> 0.998426    | |f -0.653644 -0.989992 |l 1
> 0.998437    | |f 0.283662 -0.653644 |l 1
> 0.999983    | |f 0.96017 0.283662 |l 1
> 0.001461    | |f 0.753902 0.96017 |l 0
> 0.000000    | |f -0.1455 0.753902 |l 0
> 0.001617    | |f -0.91113 -0.1455 |l 0
> 0.874203    | |f -0.839072 -0.91113 |l 1
> 0.998437    | |f 0.0044257 -0.839072 |l 1
> 0.999983    | |f 0.843854 0.0044257 |l 1
> 0.999883    | |f 0.907447 0.843854 |l 1
> 0.000214    | |f 0.136737 0.907447 |l 0
> 0.000019    | |f -0.759688 0.136737 |l 0
> 0.002432    | |f -0.957659 -0.759688 |l 0
> 0.998437    | |f -0.275163 -0.957659 |l 1
> 0.999983    | |f 0.660317 -0.275163 |l 1
> 0.999980    | |f 0.988705 0.660317 |l 1
> 0.001317    | |f 0.408082 0.988705 |l 0
> 0.000008    | |f -0.547729 0.408082 |l 0
> 0.001729    | |f -0.999961 -0.547729 |l 0
> 0.998436    | |f -0.532833 -0.999961 |l 1
> 0.998445    | |f 0.424179 -0.532833 |l 1
> 0.999983    | |f 0.991203 0.424179 |l 1
> 0.001434    | |f 0.646919 0.991203 |l 0
> 0.000002    | |f -0.292139 0.646919 |l 0
> 0.001699    | |f -0.962606 -0.292139 |l 0
> ...

**Comment by sayanpa** [comment]
This should have been fixed. Could you please try out the example if possible with Python API as well. Please reopen if the problem persists.
