### ISSUE TITLE
CNTKLibraryEvalExample evaluation error

### ISSUE THREAD

**Issue by harewei** [Microsoft/CNTK#1310]
I'm running the CNTKLibraryEvalGPUExamples, which gives an error at the line
````
Function modelFunc = Function.LoadModel("z.model", device);
````
I assumed this is due to there is no z.model, so I replaced it with a network I have trained earlier that works with evaluation with nuget packages (CSEvalClient).
````
Function modelFunc = Function.LoadModel(@"C:\local\CNTK\Examples\Image\Classification\ConvNet\BrainScript\Output\Models\ConvNet_Test_DataAug", device);
````
While this pushes the program further, at the next line
````
Variable outputVar = modelFunc.Outputs.Where(variable => string.Equals(variable.Name, outputName)).Single();
````
it gives an error
````
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Core.dll

Additional information: Sequence contains no elements
````

**Comment by zhouwangzw** [comment]
The z.model is the model trained by Resnet using Cifar dataset. You can use your model for sure. However, you also need to adapt the code to match your model, like the name of output variable, input variable, and their dimensions. Have you replace the `outputName` with the one defined in your model?
> const string outputName = "Plus2060";
You can check modelFunc.Outputs for avaiable output variables of the loaded model, including name, shape, and etc.

**Comment by harewei** [comment]
Resnet with Cifar generates models such as ResNet20_CIFAR10.cntk, not z.model
Anyway, changing the outputName for my network worked, I would like to add that since lots of model have two arguments, I had to change the original 
````
Variable inputVar = modelFunc.Arguments.Single();
````
to
````
Variable inputVar = modelFunc.Arguments.First();
````

Another problem that has occurred when I use  EvaluationBatchOfImages() function is at line
````
inputVal = Value.CreateBatch(inputVar.Shape, seqData, device);
```` 
also sometimes at line
````
modelFunc.Evaluate(inputDataMap, outputDataMap, device);
````
which works the first time, but running it a second time (even after restarting program and closing visual studio) will give an error
````
An unhandled exception of type 'System.AccessViolationException' occurred in CNTKLibraryManaged-2.0.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
````
I'm wondering if the first time of evaluation is causing the folder which I have placed my images in to be locked?

**Comment by zhouwangzw** [comment]
@harewei Yes, you have to adapt the sample program to your own model, e.g. arguments, outputs, dimensions, and etc. Glad to know that you get your model work with the new API now. 

There is no lock for any images/data during evaluation. The exception looks like a memory issue. We will publish Beta 9 with some fixes today. Could you please try with the new Nuget package when it is available? 

Sorry for the inconvenience!

**Comment by harewei** [comment]
beta 9 seems to have solved the issue, as I have re-ran the program 10 times without encountering the problem again.  thank you.
