### ISSUE TITLE
some errors when outputnode

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1312]
I trained a model using BrainScript, in which a parameter is defined as:
`embedding = Parameter(embDim, inputDim, init = "uniform")`
And now I want to output this parameter. I used `action=write` and `outputNodeNames=embedding` to output this parameter.
However, I receive the following error message:
`Segmentation fault (core dumped)`

It is ok when I change to `outputNodeNames=cr` or `outputNodeNames=err`.
How can I output the parameter to the file?

**Comment by cha-zhang** [comment]
Would this solve your issue? 
https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Read-Things-in-Python 

This thread has been too old and I'm closing this now. Please reopen a new issue if needed. Thanks!
