### ISSUE TITLE
ImportError: No module named 'fastRCNN.utils3_win64.cython_bbox'

### ISSUE THREAD

**Issue by DavidBrayford** [Microsoft/CNTK#1313]
I am attempting to use the tutorial Fast R CNN on a DGX-1 using the nvcr.io/nvidia/cntk:16.11.1 image with the OS 4.4.0-45-generic GNU/Linux. However, when I execute the command python A1_GenerateInputROIs.py I get the following messages in the terminal window:

Traceback (most recent call last):
  File "A1_GenerateInputROIs.py", line 5, in <module>
    import PARAMETERS
  File "/workspace/Examples/Image/Detection/FastRCNN/PARAMETERS.py", line 2, in <module>
    from cntk_helpers import *
  File "/workspace/Examples/Image/Detection/FastRCNN/cntk_helpers.py", line 7, in <module>
    from fastRCNN.nms import nms as nmsPython
  File "/workspace/Examples/Image/Detection/FastRCNN/fastRCNN/__init__.py", line 7, in <module>
    from .imdb import imdb
  File "/workspace/Examples/Image/Detection/FastRCNN/fastRCNN/imdb.py", line 19, in <module>
    from .utils3_win64.cython_bbox import bbox_overlaps
ImportError: No module named 'fastRCNN.utils3_win64.cython_bbox'

Is the application python scripts correctly configured for a Linux system as the missing module is *_win64*?
Or do I have to install an additional package in my instance of the nvidia cntk image?

Thanks
David

**Comment by asnart** [comment]
I have the same issue

**Comment by Abimahesh** [comment]
I too have the same issue

**Comment by pkranen** [comment]
From [here](https://github.com/Azure/ObjectDetectionUsingCntk/issues/4#issuecomment-274887660):

You are getting this error since the 'cython_bbox' binaries are compiled for windows. A quick fix would be to switch to a VM which runs windows. Alternately, you could install and compile for Linux yourself. See the original fast R-CNN code for that, e.g. [https://github.com/rbgirshick/fast-rcnn/tree/master/lib/utils](https://github.com/rbgirshick/fast-rcnn/tree/master/lib/utils).

**Comment by starlord-daniel** [comment]
@pkranen Can you provide us with instructions how to do this? Is the original code on the Linux DSVM machine?

**Comment by jajoe** [comment]
You mean it's not possible to use Fast R-CNN with CNTK (without using a VM which runs Windows) ? Because I have the same issue too (Ubuntu 16.04).

**Comment by pkranen** [comment]
You can run CNTK Fast R-CNN on Linux, you need the `cython_bbox` and `cython_nms` binaries compiled for your environment. I added a section to the tutorial [here](https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression) on how to compile the required binaries from the original Fast R-CNN repository. The precompiled binaries for Windows (Python 3.4 and 3.5) as well as for Linux (Python 3.4) are in the master branch now in the folder `Examples\Image\Detection\FastRCNN\fastRCNN\utils`.

**Comment by jajoe** [comment]
Thanks you for the new section in the tuto.
I've done what you've written but I have a new problem when I run A1_GenerateInputROIs.py (I use my env cntk-py34)

Traceback (most recent call last):
  File "A1_GenerateInputROIs.py", line 5, in <module>
    import PARAMETERS
  File "/home/jajoe/cntk/Examples/Image/Detection/FastRCNN/PARAMETERS.py", line 2, in <module>
    from cntk_helpers import *
  File "/home/jajoe/cntk/Examples/Image/Detection/FastRCNN/cntk_helpers.py", line 7, in <module>
    from fastRCNN.nms import nms as nmsPython
  File "/home/jajoe/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/__init__.py", line 7, in <module>
    from .imdb import imdb
  File "/home/jajoe/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/imdb.py", line 19, in <module>
    from .utils3_win64.cython_bbox import bbox_overlaps
ImportError: /home/jajoe/cntk/Examples/Image/Detection/FastRCNN/fastRCNN/utils3_win64/cython_bbox.so: undefined symbol: _Py_ZeroStruct

Do you have an idea to solve this problem please ?

**Comment by Dezorian** [comment]
rename the appropriate file in Examples\Image\Detection\FastRCNN\fastRCNN\utils
for example:
cython_nms.cp34-win_amd64.pyd
to: 
cython_nms.pyd

**Comment by championoaks** [comment]
I am running on windows with 3.4 and renamed cython_nms.cp34-win_amd64.pyd as suggested above .
Still getting the same failure.
