### ISSUE TITLE
Fail to install CNTK on Power 8 (CentOS 7: 3.10.0-514.2.2.el7.ppc64le) with some error messages

### ISSUE THREAD

**Issue by Nathan-Hsu** [Microsoft/CNTK#1318]
Due to some reasons, I need to try to install CNTK on PowerPC.
The OS is CentOS 7 (Kernel: 3.10.0-514.2.2.el7.ppc64le).
I followed the steps from the site (https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux) and installed the required packages.
It was OK without error after executed the "configure" file (`./configure`).
And I commented out a line in Makefile because my machine is PowerPC.
`#SSE_FLAGS = -msse4.1 -mssse3`
But there were errors when running `make -j $(nproc) all`.

Here are the errors:

Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Math/BlockHandlerSSE.cpp:14:23: fatal error: xmmintrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory
Source/Common/Include/ssefloat4.h:15:23: fatal error: x86intrin.h: No such file or directory

Could someone help to guide if there is another way to install CNTK on PowerPC?

Thanks.

Nathan

**Comment by ebarsoumMS** [comment]
Sorry but PowerPC isn't supported, some of our components use SSE.

**Comment by Nathan-Hsu** [comment]
Hi ebarsoum,

Thank you for the reply
