### ISSUE TITLE
I suggest adding 'd' postfix to names of Debug mode libs/dlls.

### ISSUE THREAD

**Issue by taeguk-sualab** [Microsoft/CNTK#1319]
In current, Debug / Release libs and dlls' names are same.
It occurs that a user's mistake like #1317 . And it is so confusing.
So, I suggest adding a 'd' postfix to Debug mode libs/dlls.
For example, in debug mode "CNTKLibrary-2.0d" instead of "CNTKLibrary-2.0".

**Comment by sayanpa** [comment]
I have filed a bug to track this issue.

**Comment by mahilleb-msft** [comment]
Hi @taeguk-sualab - this was actually implemented a while back. Can you check here:

https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Shared-Libraries-Naming-Format

Closing this issue here, if there's additional feedback please open a new one.

Thanks, mark
