### ISSUE TITLE
Bug in grocery feature extraction example in Linux

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/CNTK#1321]
The [grocery example](https://github.com/Microsoft/CNTK/blob/v2.0.beta8.0/Examples/Image/DataSets/grocery/install_grocery.py) in Linux does not work because of the symbol `\` in `test.txt`:
```bash
0       testImages\WIN_20160803_11_28_42_Pro.jpg        0
1       testImages\WIN_20160803_11_42_36_Pro.jpg        0
2       testImages\WIN_20160803_11_46_03_Pro.jpg        0
3       testImages\WIN_20160803_11_48_26_Pro.jpg        0
4       testImages\WIN_20160803_12_37_07_Pro.jpg        0
```
An easy fix that would work in Linux and Windows is to remove the folder name `testImages` in the file and add it directly to the python code.

**Comment by pkranen** [comment]
Thanks, I'll have look.

**Comment by miguelgfierro** [comment]
Thanks, I'll close the issue. Feel free to open it in case you want
