### ISSUE TITLE
Build setup instructions + binaries for older CNTK versions?

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#1322]
Hello,

Question:

Are there setup instructions and binaries for older CNTK versions?
I'm trying to build CNTK 2.0 beta 6 and actually lost quite a bunch of time on fighting with build setup instruction that does not apply.
Also the matching prebuilded references per version would be also nic - e.g. build protbuf libraries apply only for versions that are to be build in VS 2015 (beta 8 and up)

Thanks
Jan

**Comment by sayanpa** [comment]
any reason you would not like to take the fixes in Beta 9 onwards. 

If you still need it, you have to brave it out a bit I guess. Here are some of my suggestions. You can get the old wheels from the release directory- https://github.com/Microsoft/CNTK/releases
You need the visual studio 2013 redist instead on VS15 and go back to older Cuda version 7.5. That I can think on top of my head.

**Comment by jakrivan** [comment]
Hello,

> any reason you would not like to take the fixes in Beta 9 onwards.

One from the reasons is that we have integration tests suite that we'd strongly like to be green - with beta 7 and up we have experienced almost identical issue to https://github.com/Microsoft/CNTK/issues/1307


> That I can think on top of my head.

As menitoned in my question - a reference assemblies are needed to be build in same version of MS CRT (otherwise it cannot be linked) - so it would be nice to have access to those also (e.g. protobuf etc.)

All in all - packed manual per release (along with keeping the reference shares valid) would be very nice and helpful

Thanks and regards
Jan

**Comment by sayanpa** [comment]
We have recently release V2 that should have address the issues on this thread. If you still are left wanting for more please provide us feedback on a new issue thread. Closing this one for now.
