### ISSUE TITLE
Numeric overflow and incorrect number format in minibatch/epoch logging (2.0 Beta 8 - all binary builds)

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1323]
should not be an int. correct to assume this is only the log output issue ? i see it's size_t all around?
```
LOGPRINTF(stderr, ... (int)totalTrainingSamplesSeen );
```
from output/logs example:
```
...; totalSamplesSeen = 2133003074;
```
next epoch:
```
...; totalSamplesSeen = -2128132799;
```

Same problem applies to other log items that are measured in samples. Examples:
```
...-Minibatch[..]  ...learning rate per sample = 0.000000  effective momentum = 0.000000
```
while the finished Epoch correctly displays it:
```
Finished Epoch....learningRatePerSample = 1.8750001e-008
```

**Comment by sayanpa** [comment]
Looks like a bug. If it is not too much of a bother, could you see if you see a similar overflow on Beta 9.

**Comment by avader906** [comment]
last commit was jan16 and the issue still in code:
```
 fprintf(stderr, "totalSamplesSeen = %d; learningRatePerSample = %.8g; epochTime=%.6gs\n", (int)totalTrainingSamplesSeen, learnRatePerSample, epochTime);
```

**Comment by sayanpa** [comment]
We have recently release V2.0 with it this problem should be resolved. If you are still observing the issue please open a new issue. Closing this one for now.
