### ISSUE TITLE
CNTK 2.0 in Python: failed to evaluate model on test data in a CPU-only environment

### ISSUE THREAD

**Issue by mawah** [Microsoft/CNTK#1327]
During training, my model makes use of BatchNormalization(). (Specifically, the model is a 20-layer ResNet created from [this CNTK repo example](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet/Python).) I would like to use my trained model in a CPU-only context for scoring.

The model appears to load correctly, but when I evaluate, I get this error:

>   File "/usr/bin/anaconda/envs/py35/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/functions.py", line 199, in eval
>     _, output_map = self.forward(arguments, self.outputs, device=device)
>   File "/usr/bin/anaconda/envs/py35/envs/cntk-py35/lib/python3.5/site-packages/cntk/utils/swig_helper.py", line 58, in wrapper
>     result = f(*args, **kwds)
>   File "/usr/bin/anaconda/envs/py35/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/functions.py", line 277, in forward
>     keep_for_backward)
>   File "/usr/bin/anaconda/envs/py35/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 1212, in _forward
>     return _cntk_py.Function__forward(self, *args)
> RuntimeError: The code is compiled with CPUONLY macro.

I noticed [another Git issue](https://github.com/Microsoft/CNTK/issues/1005) addressing this issue, but calling CNTK.exe from the command line. The recommendation was to set the deviceId parameter to -1. The Python [load_model](https://www.cntk.ai/pythondocs/graph.html?highlight=load_model#cntk.ops.functions.load_model) function has an optional `device` parameter, but it will not accept the value -1; it needs a DeviceDescriptor instead. I cannot figure out how to create a DeviceDescriptor to allow evaluation in CPU-only mode. Any suggestions?

**Comment by zhouwangzw** [comment]
This should be fixed recently. The latest release 2.0-Beta8 now has a fallback path to use CNTK BN engine on CPU. 
To specify cpu, you can use cpu_device(), as described by the [doc](https://www.cntk.ai/pythondocs/cntk.html?highlight=devicedescriptor#cntk.cntk_py.DeviceDescriptor).

**Comment by mawah** [comment]
Thanks, Zhou! Works like a charm!
