### ISSUE TITLE
What insights about the test data are observed on running the text example?

### ISSUE THREAD

**Issue by keerthiskating** [Microsoft/CNTK#133]
It outputs word, word_id, it's frequency and class of the word.Also I did not what exactly the class is.(there are about 50 classes).Better documentation could have been added about it.Can anyone answer my question ?

**Comment by kaishengyao** [comment]
The classes are generated based on occurrence counts. Words are sorted in their descending word occurrence counts. See reference in paper "Recurrent neural network based language model" by Tomas Mikolov. 
Basically, the classes are created much like bining on these words. Each bin has a set of words and the total word occurrence in this bin is approximately the same as the total word occurrence in the other bins.  For example, the first bin may only have word <s> and the second bin may only </s> as these two words are the most frequent word. Then the 3rd bin may have words such as "please" and "hi", which are also frequent but less frequent than <s> and </s>. The 50 classes in the example were created in the above way.
