### ISSUE TITLE
Why is there no "ImageMinibatchSource" in C++ API?

### ISSUE THREAD

**Issue by taeguk-sualab** [Microsoft/CNTK#1331]
In current, there is only "TextFormatMinibatchSource" in C++ API.
https://github.com/Microsoft/CNTK/blob/ef56278026e0922eeaea807ca61e07c33f381104/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L4012

There is a "Image Reader" in BrainScript or Python API. (https://github.com/Microsoft/CNTK/wiki/Image-reader)
But I can't use it in C++ API.
Because I really need it, I looked for source codes of CNTKv2LibraryDll.

https://github.com/Microsoft/CNTK/blob/ef56278026e0922eeaea807ca61e07c33f381104/Source/CNTKv2LibraryDll/MinibatchSource.cpp#L95
In source codes of CNTKv2LibraryDll, I can catch L"ImageDeserializer" and L"ImageReader".
Are everythings prepared for image reader only except C++ API header?
If I add "ImageMinibatchSource" in CNTKLibrary.h(C++ API header), can I use image reader? And does it work normally?
If yes, I have a mind to do that and contribute for other people.

**Comment by eldakms** [comment]
Hi taeguk,

Yes, if you add ImageMinibatchSource similar to the TextFormatMinibatchSource everything should work. Effectively, you just need to fill in the config dictionary and pass it to the composite minibatch source.
Thank you.

**Comment by taeguk** [comment]
I'm same person to @taeguk-sualab 
Okay, thank you. I will PR within a day.

**Comment by tangyuq** [comment]
Closed this issue for now. Feel free to reopen it if you have further comments.

**Comment by KeDengMS** [comment]
Can you follow [this](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/CNTKv2Library/EndToEndTests/CifarResNet.cpp#L12-L41) example to use ImageDeserializer and CreateCompositeMinibatchSource instead?
