### ISSUE TITLE
Using the new C# Managed Library for Evaluation - Dll not found

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#1332]
I'm trying to migrate from the old Evaluation library in C# to the new managed library (for GPU support).

When I try to load a model (regardless if the model exist or not) I get the following error:

![image](https://cloud.githubusercontent.com/assets/7712296/22149878/6eb02b64-df16-11e6-8727-981193ea9261.png)

I have added the Nuget package to the project so I cannot understand why the dll is not found. I have also attemped to copy the dll to the place where the application is run but no luck.

**Comment by zhouwangzw** [comment]
@mortengryning  Could you please check whether CNTKLibraryCSBinding.dll and CNTKManagedLibrary-2.0.dll available in the project output directory?

**Comment by mortengryning** [comment]
I somehow fixed it. I think it was something to do with the dll files as you suggested.
