### ISSUE TITLE
pandas_reader not installed in CNTK distribution

### ISSUE THREAD

**Issue by davidarh** [Microsoft/CNTK#1334]
I have been completing the CNTK tutorials, and got stuck for a while with tutorial: 

CNTK_104_Finance_Timeseries......

I got errors because pandas_reader is not installed in the default CNTK distribution. I am using the windows binary distribution of CNTK2. Please consider adding pandas_reader to the distribution.

**Comment by sayanpa** [comment]
you can install any python package from Jupyter "!pip install package" in future.

**Comment by davidarh** [comment]
Thanks.

That doesn't work on windows. That's why I was having problems.
