### ISSUE TITLE
gradient reversal layer

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#1337]
Hello

I'm wondering if CNTK supports gradient reversal layer (GRL). Basically, forward path is identity but backward path should be multiplied by -1, which is necessary for domain adversarial training.

If not, I would like to know if there is easy way to modify CNTK to implement GRL.

**Comment by cha-zhang** [comment]
We will be publishing a tutorial on GAN very soon. Stay tuned.

**Comment by vmazalov** [comment]
There are a couple GAN tutorials published that use model parameter sharing. 
In addition, to compute gradient reversal, one can use the `stop_gradient(x)` operation, e.g. 

    (1 + lambda) * stop_gradient(x) – lambda*x

In the fwd pass this will result in `x`, in the bwd pass: `-lambda * root_gradient.`

**Comment by funguy74** [comment]
Thanks for your information. Unfortunately, it is only supported for python library. I tried brainscript but it failed to recognize this function. Is there any way to achieve similar functionality in brainscript?

**Comment by vmazalov** [comment]
Sorry, I don't think there are plans support it in brainscript.
