### ISSUE TITLE
would it be possible to have a Python-3.6 wheel in cntk-2.0.rc2 ?

### ISSUE THREAD

**Issue by stonebig** [Microsoft/CNTK#1338]

**Comment by sayanpa** [comment]
We do not have any current plans. Would it be possible to have a 3.5 environment within your python setup. Will file for a feature request in our backlog for now.

**Comment by stonebig** [comment]
thanks for the backlog addition. I will wait for 3.6 to show up.

**Comment by stonebig** [comment]
I don't find any wheel in current rc2, only conda installers. Did I miss something ?

**Comment by stonebig** [comment]
ok, found. thanks
