### ISSUE TITLE
is it possible to have a Fast-style-transfer in cntk ?

### ISSUE THREAD

**Issue by stonebig** [Microsoft/CNTK#1339]
like the impressive https://github.com/lengstrom/fast-style-transfer 

(https://arxiv.org/abs/1603.08155)

with a lot of pre-created styles

**Comment by sayanpa** [comment]
Yes it is possible. There is a CNTK 205 Neuro Artistic Style tutorial. We are happy to take contributions :)

**Comment by tangyuq** [comment]
Closed this issue for now. Feel free to reopen it if you have further comments.
