### ISSUE TITLE
Return dense matrix in SparsePCReader

### ISSUE THREAD

**Issue by augusterodin** [Microsoft/CNTK#134]
I tried to set returnDense=true in SparsePCReader (for parallel training), it could work for CPU but fail for GPU. I got below errors:

[CALL STACK]
    >Microsoft::MSR::CNTK::TensorView<double>::DoTernaryOpOf
    -Microsoft::MSR::CNTK::GPUMatrix<float>::MultiplyAndWeightedAdd
    -Microsoft::MSR::CNTK::Matrix<float>::MultiplyAndWeightedAdd
    -Microsoft::MSR::CNTK::Matrix<float>::MultiplyAndAdd
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -BaseThreadInitThunk
    -RtlUserThreadStart

EXCEPTION occurred: VerifySize: expected matrix size 288 x 49292, but it is 0 x 0

Any help here? Thanks!

**Comment by bmitra-msft** [comment]
When ``returnDense=true`` is set for SparsePCReader it simply calls ``SwitchToMatrixType(MatrixType::DENSE, MatrixFormat::matrixFormatDense, true)`` before returning the matrices.

Is it possible to first validate your network training on CPU/GPU by setting ``returnDense=false``? I am asking because it's likely that the CPU/GPU difference you are noticing is not because of the reader but some other matrix operation (e.g., the ``MultiplyAndWeightedAdd`` method that actually seems to be throwing the exception according to the call stack).

**Comment by augusterodin** [comment]
@bmitra-msft It worked correctly when returnDense=false.

**Comment by bmitra-msft** [comment]
That is definitely odd.

Can you please share the particular network definition so that I can try to repro on my side?

**Comment by bmitra-msft** [comment]
@augusterodin and I took a look at this together and figured out that the issue was that in the BrainScript the input was specified as Sparse while the SparsePCReader settings requested the reader to return dense matrices. Changing the config fixed the issue.

However, I think there are couple of design issues / bugs here that we should follow up on,

- The reader config and the BrainScript are two possible places where one can specify sparse vs. dense input - these need to be in sync which seems wrong. I know this had come up in discussion before. (@frankseide / @dongyu888 : are the new reader design going to take care of this already?)
- Even if there was an inconsistency in the sparse/dense configuration CNTK shouldn't have crashed but exited more gracefully. Anyone want's to look into this?

Cheers,
Bhaskar

**Comment by frankseide** [comment]
The call stack is almost certainly wrong. MultiplyAndWeightedAdd() does not call into TensorView.

The error message is wicked and may indicate a problem elsewhere (mem sharing—sparse matrices cannot be mem-shared, but if the type gets changed, mem sharing may be decided on an incorrect basis). Bhaskar, I will follow up with you offline.

I will leave this Issue open to track this mem-sharing investigation.

**Comment by dongyu888** [comment]
So the problem is not caused by mem sharing but by the fact contradictory information is provided at the model and reader side. We will consider a solution for this.

**Comment by bmitra-msft** [comment]
> The call stack is almost certainly wrong.

We did look at the actual call stack under the debugger earlier. @augusterodin can you please paste the call stack that we did get during our repro?

**Comment by augusterodin** [comment]
Below are the full detailed callstack:

Math.dll!Microsoft::MSR::CNTK::DebugUtil::PrintCallStack() Line 24
Math.dll!Microsoft::MSR::CNTK::ThrowFormatted<std::logic_error>(const char * format, ...) Line 52
Math.dll!Microsoft::MSR::CNTK::LogicError<unsigned __int64 & __ptr64,unsigned __int64 & __ptr64,unsigned __int64,unsigned __int64>(const char * format, unsigned __int64 & <_Args_0>, unsigned __int64 & <_Args_1>, unsigned __int64 && <_Args_2>, unsigned __int64 && <_Args_3>) Line 68
Math.dll!Microsoft::MSR::CNTK::BaseMatrix<float>::VerifySize(unsigned __int64 rows, unsigned __int64 cols) Line 166
Math.dll!Microsoft::MSR::CNTK::GPUMatrix<float>::MultiplyAndWeightedAdd(float alpha, const Microsoft::MSR::CNTK::GPUMatrix<float> & a, const bool transposeA, const Microsoft::MSR::CNTK::GPUMatrix<float> & b, const bool transposeB, float beta, Microsoft::MSR::CNTK::GPUMatrix<float> & c) Line 3290
Math.dll!Microsoft::MSR::CNTK::Matrix<float>::MultiplyAndWeightedAdd(float alpha, const Microsoft::MSR::CNTK::Matrix<float> & a, const bool transposeA, const Microsoft::MSR::CNTK::Matrix<float> & b, const bool transposeB, float beta, Microsoft::MSR::CNTK::Matrix<float> & c) Line 4312
Math.dll!Microsoft::MSR::CNTK::Matrix<float>::MultiplyAndAdd(const Microsoft::MSR::CNTK::Matrix<float> & a, const bool transposeA, const Microsoft::MSR::CNTK::Matrix<float> & b, const bool transposeB, Microsoft::MSR::CNTK::Matrix<float> & c) Line 4353
CNTK.exe!Microsoft::MSR::CNTK::TimesNode<float>::BackpropTo(const unsigned __int64 inputIndex, const Microsoft::MSR::CNTK::FrameRange & fr) Line 199
CNTK.exe!Microsoft::MSR::CNTK::ComputationNode<float>::Backprop(const Microsoft::MSR::CNTK::FrameRange & fr, bool childrenInThisLoop, bool childrenInOuterLoop) Line 1273
CNTK.exe!Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::Backprop(const Microsoft::MSR::CNTK::FrameRange & fr, bool childrenInThisLoop, bool childrenInOuterLoop) Line 157
CNTK.exe!Microsoft::MSR::CNTK::ComputationNetwork::Backprop(const std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> rootNode) Line 78
CNTK.exe!Microsoft::MSR::CNTK::SGD<float>::TrainOneEpoch(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> net, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> refNet, const std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> & refNode, const int epochNumber, const unsigned __int64 epochSize, Microsoft::MSR::CNTK::IDataReader<float> * trainSetDataReader, const double learnRatePerSample, unsigned __int64 tunedMBSize, const std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > & featureNodes, const std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > & labelNodes, const std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > & criterionNodes, const std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > & evaluationNodes, std::map<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >,Microsoft::MSR::CNTK::Matrix<float> *,std::less<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > >,std::allocator<std::pair<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > const ,Microsoft::MSR::CNTK::Matrix<float> *> > > * inputMatrices, const std::list<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > & learnableNodes, std::list<Microsoft::MSR::CNTK::Matrix<float>,std::allocator<Microsoft::MSR::CNTK::Matrix<float> > > & smoothedGradients, double & epochCriterion, std::vector<double,std::allocator<double> > & epochEvalErrors, unsigned __int64 & totalSamplesSeen, std::basic_string<char,std::char_traits<char>,std::allocator<char> > prefixMsg) Line 916
CNTK.exe!Microsoft::MSR::CNTK::SGD<float>::TrainOrAdaptModel(int startEpoch, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> net, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> refNet, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> refNode, Microsoft::MSR::CNTK::IDataReader<float> * trainSetDataReader, Microsoft::MSR::CNTK::IDataReader<float> * validationSetDataReader) Line 425
CNTK.exe!Microsoft::MSR::CNTK::SGD<float>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> __cdecl(int)> createNetworkFn, int deviceId, Microsoft::MSR::CNTK::IDataReader<float> * trainSetDataReader, Microsoft::MSR::CNTK::IDataReader<float> * validationSetDataReader, const bool makeMode) Line 64
CNTK.exe!DoTrain<Microsoft::MSR::CNTK::ConfigParameters,float>(const Microsoft::MSR::CNTK::ConfigParameters & config) Line 222
CNTK.exe!DoCommands<float>(const Microsoft::MSR::CNTK::ConfigParameters & config) Line 222
CNTK.exe!wmainOldCNTKConfig(int argc, wchar_t * * argv) Line 620
CNTK.exe!wmain1(int argc, wchar_t * * argv) Line 661
CNTK.exe!wmain(int argc, wchar_t * * argv) Line 696
