### ISSUE TITLE
is it possible to have download progress information in notebooks ?

### ISSUE THREAD

**Issue by stonebig** [Microsoft/CNTK#1340]
see as example https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/download.py

**Comment by sayanpa** [comment]
This is a good suggestion. Will be taking this as feature work in our workstream. Really appreciate your pointer.

**Comment by sayanpa** [comment]
Item to be added to our feature backlog.

**Comment by sayanpa** [comment]
This feature can be to any python notebook by using the code found here: https://github.com/alexanderkuk/log-progress

Given our current downloads are fairly small, lowering the priority of this task. However, we are happy to take contributions, if you are interested in contributing back to the toolkit.

**Comment by sayanpa** [comment]
Closing this issue for now since we are looking forward to the possibility of contribution from the community based on the aforementioned solution or any other that emulates the behavior.
