### ISSUE TITLE
what is the minimum RAM requirement to run the tutorial CNTK_205_Artistic_Style_Transfer ?

### ISSUE THREAD

**Issue by stonebig** [Microsoft/CNTK#1341]
I see that example  CNTK_205_Artistic_Style_Transfer.ipynb eats all my memory on a 4gb PC, in cpu mode.

What is the minimal required ram to run it ?

It  seems that some other toolkits are more frugal (some other are apparently not)

**Comment by sayanpa** [comment]
Assuming you are using CPU, can you work with a smaller image for now. I have a 8GB RAM PC and it has worked well. Image processing does require more memory. In general reducing image sizes or minibatch sizes (when applicable ) typically helps circumvent the problem.

If you can spot areas where we can improve on memory usage we will love to factor that in our development plan. BTW, the tutorials are a tradeoff between teaching the features of the toolkit and the efficiency.

**Comment by stonebig** [comment]
Thanks: I didn't have any idea of the true minimal requirement.
