### ISSUE TITLE
the future of BrainScript 

### ISSUE THREAD

**Issue by jotarun** [Microsoft/CNTK#1342]
Just find out the new CNTK Library C#/.NET Managed Eval API supports only model-v2

Since there is no way to generate model-v2 with BrainScript, does that means BrainScript will be deprecated  in the future?

**Comment by zhouwangzw** [comment]
@jotarun Loading the model-v1 format (generated by BrainScript) is supported the new C#./NET Eval API. Some primitive node types in Brainscript might be deprecated in V2 though, so you need to adapt Brainscript or edit the model in this case. 
The model-V2 format is supported by Python or C++, but not by Brainscript.  Details are [here](https://github.com/Microsoft/CNTK/wiki/CNTK-model-format). So we strongly encourage you to swtich your Brainscript to Python. If you have any questions, please let us know.

**Comment by jotarun** [comment]
thx. so python will be the future.
