### ISSUE TITLE
RuntimeError: Unsupported ComputationNode with OperationName='CosDistanceWithNeg ativeSamples' found when loading legacy CNTK model

### ISSUE THREAD

**Issue by 1026112881** [Microsoft/CNTK#1343]
Hi, Cosmos Team,

I have train a model using CNTK BrainScript, but when I evaluate the model using Python API, there emerged such error on load_model(). 

>>> z=load_model("dssm.dnn.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\utils\swig_helper.py", line 58, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\site-packages\cntk\ops\functions.py", line 579, in load_model
    return cntk_py.Function.load_model(filename, device)
RuntimeError: Unsupported ComputationNode with OperationName='CosDistanceWithNegativeSamples' found when loading legacy CNTK model

BTW, my cntk version is:
-------------------------------------------------------------------
Build info:
                Built time: Dec 22 2016 01:45:54
                Last modified date: Thu Dec 22 01:35:08 2016
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
                CUB_PATH: c:\src\cub-1.4.1
                CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v5.1
                Build Branch: HEAD
                Build SHA1: 8e8b5ff92eff4647be5d41a5a515956907567126
                Built by svcphil on Philly-Pool3
                Build Path: C:\Jenkins\workspace\CNTK-Build-Windows\Source\CNTK\

Is there any solution? Thanks a lot.

**Comment by cha-zhang** [comment]
This thread has been too old and it's unclear if the issue remain in the latest CNTK 2.0. I'm closing this now. Please reopen a new issue if needed. Thanks!
