### ISSUE TITLE
Assertion error occur while running A2_RunCntk.py

### ISSUE THREAD

**Issue by Abimahesh** [Microsoft/CNTK#1345]
Can anyone help me out to solve this error?

2017-01-23 02:44:42
PARAMETERS: datasetName = grocery
PARAMETERS: cntk_nrRois = 2000
cntk.exe configFile=C:\Users\Downloads\CNTK-2-0-beta9-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:\Users\Downloads\CNTK-2-0-beta9-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/ NumLabels=17 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=34000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=34000
Time running cntk [s]: 0.015721
Traceback (most recent call last):
  File "A2_RunCntk.py", line 51, in <module>
    assert pid.returncode == 0, "ERROR: cntk ended with exit code {}".format(pid.returncode)
AssertionError: ERROR: cntk ended with exit code 3221225781

**Comment by pkranen** [comment]
Please try running the cntk.exe command with those parameters (`cntk.exe configFile=C:\Users\Downloads\CNTK-2-0-beta9-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:\Users\Downloads\CNTK-2-0-beta9-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/ NumLabels=17 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=34000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=34000`) from a command prompt and report errors here. pid just calls that same command from Python.

**Comment by Abimahesh** [comment]
Hi thank you, I had rectified error.

**Comment by wendy7707** [comment]
@Abimahesh hello, would you please tell me how to solve this problem, I have the same problem now, thanks!
