### ISSUE TITLE
CNTK Seg Faults instead of printing error message

### ISSUE THREAD

**Issue by rhoens** [Microsoft/CNTK#1348]
I believe I have an error in my network (see #1 in the backtrace), but instead of printing an error message the code segfaults. This is on the docker image:  microsoft/cntk:2.0.beta7.0-runtime-gpu-python3.4-cuda8.0-cudnn5.1

#0  Microsoft::MSR::CNTK::ComputationNodeBase::NodeDescription (this=this@entry=0x0) at Source/ComputationNetworkLib/ComputationNode.h:885
885     Source/ComputationNetworkLib/ComputationNode.h: No such file or directory.
(gdb) bt
#0  Microsoft::MSR::CNTK::ComputationNodeBase::NodeDescription (this=this@entry=0x0) at Source/ComputationNetworkLib/ComputationNode.h:885
#1  0x00007f09bf5a2c1b in As<Microsoft::MSR::CNTK::ComputationNode<float> > (this=0x0) at Source/ComputationNetworkLib/ComputationNode.h:859
#2  CNTK::CompositeFunction::PopulateComputationNodeValue<float> (variableValue=..., computationNode=...) at Source/CNTKv2LibraryDll/CompositeFunction.cpp:1007
#3  0x00007f09bf593868 in CNTK::CompositeFunction::PopulateNetworkInputs (this=this@entry=0x258abe0, arguments=...) at Source/CNTKv2LibraryDll/CompositeFunction.cpp:1030
#4  0x00007f09bf5980a5 in CNTK::CompositeFunction::Forward (this=this@entry=0x258abe0, arguments=..., outputs=..., computeDevice=..., outputsToRetainBackwardStateFor=...) at Source/CNTKv2LibraryDll/CompositeFunction.cpp:1280
#5  0x00007f09bf5f2266 in CNTK::Trainer::ExecuteForwardBackward (this=this@entry=0x256f300, arguments=..., outputsToFetch=..., computeDevice=..., parameterGradients=...) at Source/CNTKv2LibraryDll/Trainer.cpp:209
#6  0x00007f09bf5f314e in CNTK::Trainer::TrainLocalMinibatch (this=0x256f300, arguments=..., outputsToFetch=..., computeDevice=...) at Source/CNTKv2LibraryDll/Trainer.cpp:152
#7  0x00007f09bf5f3cf5 in CNTK::Trainer::TrainMinibatch (this=this@entry=0x256f300, arguments=..., outputsToFetch=..., computeDevice=...) at Source/CNTKv2LibraryDll/Trainer.cpp:141
#8  0x00007f09bf5f3da0 in CNTK::Trainer::TrainMinibatch (this=this@entry=0x256f300, arguments=..., computeDevice=...) at Source/CNTKv2LibraryDll/Trainer.cpp:135

Unfortunately I don't have the capability to debug this more thoroughly, but it looks like either NodeName() or OperationName() on line 885 of ComputationNode.h aren't defined, causing the segfault.

**Comment by tangyuq** [comment]
Need further details to diagnose the issue.  Please try the latest version. Feel free to reopen this issue, if you have further comments.
