### ISSUE TITLE
Image sequence reader

### ISSUE THREAD

**Issue by TichiunChang** [Microsoft/CNTK#1349]
Hi, we need to read image sequences with designated sequence ID (much like the sequence text input).
In the CNTK wiki (understanding and extending readers), we saw
"
ImageDeserializer options
•	file: a simple text file where each line contains a tab-separated mapping between logical sequence key, image file (e.g. JPEG, PNG etc) and 0-based label.
"
However, when we write the triple in the map file as
"SequenceId FullPathToImageFileName ImageLabel"
We encountered errors.
Is image sequence reader already supported? If yes, what should be the input format?
Thanks a lot!

**Comment by ebarsoumMS** [comment]
Hi Tichiun,

Is that python or brainscript?

**Comment by TichiunChang** [comment]
Hi Emad,

We used BrainScript, which doesn't seem to work.
We didn't try python.
Thanks for looking into this!

**Comment by eldakms** [comment]
The built-in image reader provided by CNTK does not support sequences of images. You can use Python API to read images/sequences and give them directly to the trainer, but this is not available in BrainScript.

**Comment by ebarsoumMS** [comment]
Here an example, how to pack sequence of images in Python: https://github.com/Microsoft/CNTK/tree/master/Examples/Video/GettingStarted

**Comment by TichiunChang** [comment]
Thanks for pointing to the example!
However, our plan is to use image sequence input, first go through convolutional layer, then further analyzed by LSTM. That example doesn't seem to fit exactly.

Additionally, we saw from CNTK Python API (https://www.cntk.ai/pythondocs/cntk.io.html):
----------------------------------------------
This class configures the image reader that reads images and corresponding labels from a file of the form:
<full path to image> <tab> <numerical label (0-based class id)>
or:
sequenceId <tab> path <tab> label
----------------------------------------------
So, we tried the following:

1. We modified [CNTK_root]\Examples\Image\DataSets\CIFAR-10\train_map.txt in the format of
sequenceId <tab> path <tab> label
and run the following example python code:
[CNTK_root]\Examples\Image\Classification\ConvNet\Python\ConvNet_CIFAR10_DataAug.py

The following error message will occur:
RunTimeError: Cannot parse label value on line 18050, second column, in file [CNTK_root]\Examples\Image\Classification\ConvNet\Python\..\..\..\DataSets\CIFAR-10\mytrain_map.txt.

2. We modified [CNTK_root]\Examples\Image\DataSets\CIFAR-10\train_map.txt in the format of
sequenceId <space> path <space> label
and run the following example python code:
[CNTK_root]\Examples\Image\Classification\ConvNet\Python\ConvNet_CIFAR10_DataAug.py
The following error message will occur:
RunTimeError: Cannot open file ‘1 [CNTK_root]\Examples\Image\DataSets\CIFAR-10\train\07761.png’

3. We also tried to modify "ConvNet_CIFAR10_DataAug.py" around the codes
--------------------------------------------------------------------------------------
# deserializer
return cntk.io.MinibatchSource(cntk.io.ImageDeserializer(map_file, cntk.io.StreamDefs(
        features = cntk.io.StreamDef(field='image', transforms=transforms), # first column in map file is referred to as 'image'
        labels   = cntk.io.StreamDef(field='label', shape=num_classes))),   # and second as 'label'
        randomize=is_training)
-------------------------------------------------------------------------------------------
E.g., seqId = cntk.io.StreamDef(field='sequenceID')
But also got error message.

**Comment by xforceco** [comment]
quick question, does "image seq" still not supported in brainscript?

**Comment by ebarsoumMS** [comment]
@xforceco  image sequence is not supported in BrainScript and Python. @ThiunChang you will need to write your own Python reader and the input need to be a sequence input (C,sequence.input_variable).
