### ISSUE TITLE
CNTK for Speech Recognition

### ISSUE THREAD

**Issue by thiagonautf** [Microsoft/CNTK#135]
Hi,

I'm trying to build a system of **automatic recognition of speech to the Portuguese of Brazil**. But I do not know where to start! I'm lost.

Does anyone have any guidance for me to continue studying?

Thank you.
Regards,
Thiago

**Comment by wolfma61** [comment]
Well Thiago, this is a difficult questions...
this is a topic of products development as well as advanced research. I don't know your background in this technology at all, there are several good links / resources if you pick the query engine of your choice, ie.
http://www.bing.com/search?q=speech+training+with+neural+networks
