### ISSUE TITLE
load_model broken

### ISSUE THREAD

**Issue by rhoens** [Microsoft/CNTK#1350]
When trying to load a model that I've previously saved, the "inputs" is not saved, making it impossible to evaluate the model.

For example:
import cntk as C
from cntk.ops import *
from cntk.ops.functions import load_model
from cntk.device import set_default_device, gpu
set_default_device(gpu(0))
input1 = [[[1,2]]]
input2 = [[[[1],[2]]]]
i1 = input_variable((1,2), name='i1')
i2 = input_variable((2,1), name='i2')
node1 = plus(i1,i2)
node2 = tanh(node1)
node2.eval({i1: input1, i2: input2})

""""
returns:

array([[[[ 0.96402758,  0.99505478],
         [ 0.99505478,  0.99932933]]]], dtype=float32)
"""

node2.save_model("temp")
node3 = load_model("temp")
node3.eval({i1: input1, i2: input2})

"""
returns:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/ops/functions.py", line 199, in eval
    _, output_map = self.forward(arguments, self.outputs, device=device)
  File "/root/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/utils/swig_helper.py", line 58, in wrapper
    result = f(*args, **kwds)
  File "/root/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/ops/functions.py", line 277, in forward
    keep_for_backward)
  File "/root/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/cntk/cntk_py.py", line 1212, in _forward
    return _cntk_py.Function__forward(self, *args)
ValueError: Function::Forward: Required arguments (i2, i1) values that the requested output(s) depend on has not been provided
"""

This is even worse when parameters are introduced, as their values don't get loaded and the number of "inputs" is the number of inputs + the number of parameters.

**Comment by amitaga** [comment]
The issue is that on loading the model, a complete new Function object gets created whose input object identities are different that the original model (i.e. the inputs of the loaded model are not the same objects as i1, i2). There are 2 alternates:

1)	Use “restore_model” which just restores the model’s parameters in the existing graph, instead of creating a new graph.
2)	Call “node3.eval({node3.arguments[0] : input1, node3.arguments[1] : input2}) which refers to the actual arguments of the newly loaded node3.

**Comment by rhoens** [comment]
Ok I see the issue now. All "parameters" are listed as inputs, and you have to reverse engineer the order of the inputs in order to evaluate.

I'll figure out how to get this to work with data returned from next_minibatch. Thanks.
