### ISSUE TITLE
How to install CNTK globally on Linux

### ISSUE THREAD

**Issue by kflu** [Microsoft/CNTK#1351]
I'm following [this installation instruction](https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Script) by using `install-cntk.sh`. However there's no way to install CNTK and anaconda somwhere globally that multiple users can share, for example, there's couple of issues:

1. the installation script hard coded to install anaconda to `$HOME/anaconda`. 
2. the permission is set up so it's only granted to the user who untar the installation package. 

What's the recommended way to install CNTK globally on Linux?

**Comment by mahilleb-msft** [comment]
Hi @kflu,

  these are fair comments about being able to override the installation locations. I'll work on fixing this, and we'll also check that we can install into Anaconda root environment.

  Wrt to global installation, for the CNTK binary (v1, non-Python) it should be fairly straightforward. For the Python side of things, you should note that Anaconda Python for now recommends per-users install (cf. https://docs.continuum.io/anaconda/install), and they are working on some form of multi-user support for upcoming versions (cf. here conda/conda#3614).
  I think what should be working fine for now, is if you setup an global environment (e.g., Anaconda with all default modules) plus the CNTK modules and dependencies pre-installed. Then, users should be able to use that. It may be more difficult, for example, if you want to give users the option to setup up their own environment, with CNTK installed. What usage are you expecting?

  Thanks, Mark

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
