### ISSUE TITLE
Cannot run C# Managed Evaluation in WCF

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#1352]
I have 3 projects right now:

1) Lab (C# Application)
2) WCF Web Service
3) Library for RCNN generation

When I call the library from my C# application I can evaluate a rcnn model (after having copied the CSbinding dll to the directory).

However when I call the library from the WCF application, I get the following error when I try to load the model:

![image](https://cloud.githubusercontent.com/assets/7712296/22251061/b92c53c6-e249-11e6-87f5-3f736405d3ea.png)

A bit deeper:

![image](https://cloud.githubusercontent.com/assets/7712296/22251106/e37cd790-e249-11e6-91a5-dcd99062c8e0.png)

All projects are running 64bit. I don't think it's a dll issue since the library works when called from the C# Application.

How can I fix this?

**Comment by Vedaevolution** [comment]
Is the CNTKLibraryCSBinding dll in your application folder?

Simply seems like it doesn't find the dll.

**Comment by zhouwangzw** [comment]
The problem seems that the directory containing CNTKLibraryCSBinding.dll is not in the search path for dlls in WCF environment. The [page](https://github.com/Microsoft/CNTK/wiki/Evaluate-a-model-in-an-Azure-WebApi) shows how to configure path in Azure environment. You can try to configure similar things in WCF Web Service.
 The code below assumes that all CNTK depedent dlls are uploaded to AppDomain.CurrentDomain.BaseDirectory\bin. 

```
We added the following code in the Application_Start() method in global.asax:
 string pathValue = Environment.GetEnvironmentVariable("PATH");
 string domainBaseDir = AppDomain.CurrentDomain.BaseDirectory;
 string cntkPath = domainBaseDir + @"bin\";
 pathValue += ";" + cntkPath;
 Environment.SetEnvironmentVariable("PATH", pathValue);
```

**Comment by dkmorteng** [comment]
Vedaevolution: Yes.

zhouwangzw: I have already added that code according to the guide :-)

What ultimately fixed it was to copy all of the dll's in the cntk folder for release 9 to the WCF folder. Then, finally, it worked.

**Comment by zhouwangzw** [comment]
@dkmorteng Great to know that it works. You probably do not need to copy all dlls in the cntk folder of the binary package, but just the dlls as described [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows#shipping-cntk-library-with-your-windows-application).

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by zhouwangzw** [comment]
I am closing the issue, since the issue has been resolved.  Please feel free to re-open it if needed.
