### ISSUE TITLE
running VGG in cpu-only mode not honoring numCPUThreads parameter

### ISSUE THREAD

**Issue by jahanzebmaqbool** [Microsoft/CNTK#1356]
I am trying to run VGG in host-only mode using MPI. However, the issue I have is that even though I specify numCPUThreads=X, it is using all the cores of the system. Doing top shows that each process is having max number of threads (all the cores). While running other models such as MLP, numCPUThreads is honored and works as expected. 

Any help is highly appreciated.

**Comment by KeDengMS** [comment]
We also use OpenMP in image deserializer. Can you try set multiThreadedDeserialization to false in your reader? Besides, when you run MLP and found numCPUThreads is honored, was it using image deserializer or just CTF files?

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Please reopen a new issue if needed. Thanks!
