### ISSUE TITLE
Model Editing fails when using Splice Function in Original Model

### ISSUE THREAD

**Issue by Martlgap** [Microsoft/CNTK#1359]
Hey guys, 
I realized a strange behaviour of CNTK when using the model edit action. 

In my original model I using Splice() function in order to stack 2 Sets of Images together. For example two Sets of FeatureMaps 41x41x32 and 41x41x32 are stacked together -> 41x41x64. I do this using the following line: 
out1s = Splice(out1_1:out1_2, axis = 3)

In Training this works fine. 

When I use the Model Edit Action and increase the size of the images for example to 512x512 I get the following error: 

Validating --> ol.out1s = RowStack (ol.out1_1, ol.out1_2) : [512 x 512 x 32 x *], [512 x 512 x 32 x *] -> [1024 x 512 x 32 x *]

It seems that CNTK does not use axis=3, because it stacks the two sets together in the first dimension not in the 3rd dimension. 

Any suggestion, what I could do to prevent this error?

**Comment by cha-zhang** [comment]
Did you try specifying the axis in RowStack? 
https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs#L578

**Comment by Martlgap** [comment]
Hi, 
thank you very much for your reply. 

Did you mean using RowStack() Instead of Splice()? If yes, I already tried that, same result. I prepared a minimum Working Example, which might help to better understand my issue and shows the error: 

```
#ConfigFilePath for VS: configFile="F:\03_Configs\MinWorkingExample.cntk"`


precision="float"
deviceId=-1 #Use CPU Only
parallelTrain="false"
numCPUThreads = 1

command=Train:Edit

# Configuration of Output in Report
traceLevel=2



#######################################
#  TRAINING CONFIG                    #
#######################################

Train=[
    action="train"
    modelPath="F:\03_Configs\MinWorkingExample\TestModel"
	BrainScriptNetworkBuilder = [
		# Read in Images
		features = ImageInput(41, 41, 1, tag="feature", imageLayout = "cudnn")
		labels = ImageInput(41, 41, 1, tag="label", imageLayout = "cudnn")
		
		# Convolution1
		w1 = ParameterTensor(32:3*3*1, init='heNormal', learningRateMultiplier=1.0)
		b1 = ParameterTensor(1:1:32, init='fixedValue', value=0.0, learningRateMultiplier=1.0)
		c1 = Convolution(w1, features, (3:3:1), mapDims=32, stride=(1:1:1), autoPadding=(true:true:false), transpose = false, imageLayout="cudnn")
		pls1 = Plus(c1,b1)
		out1 = RectifiedLinear(pls1)
		
		# Convolution2
		w2 = ParameterTensor(32:3*3*1, init='heNormal', learningRateMultiplier=1.0)
		b2 = ParameterTensor(1:1:32, init='fixedValue', value=0.0, learningRateMultiplier=1.0)
		c2 = Convolution(w2, features, (3:3:1), mapDims=32, stride=(1:1:1), autoPadding=(true:true:false), transpose = false, imageLayout="cudnn")
		pls2 = Plus(c2,b2)
		out2 = RectifiedLinear(pls2)
		
		#Splice or RowStacking
		out3 = Splice(out1:out2, axis=3)
		
		#Convolution3
		w3 = ParameterTensor(1:1*1*64, init='heNormal', learningRateMultiplier=1.0)
		b3 = ParameterTensor(1:1:1, init='fixedValue', value=0.0, learningRateMultiplier=1.0)
		c3 = Convolution(w3, out3, (1:1:64), mapDims=1, stride=(1:1:1), autoPadding=(true:true:false), transpose = false, imageLayout="cudnn")
		pls3 = Plus(c3,b3)
		ol = RectifiedLinear(pls3)
		
		# Loss Function
		se = SquareError(labels, ol)

		# Special Nodes
		featureNodes = (features)
		labelNodes = (labels)
		criterionNodes = (se)
		outputNodes = (ol)
    ]
    
    SGD = [
        epochSize = 0
        minibatchSize = 1
		learningRatesPerMB = 0.196*20:0.0196*20:0.00196*20:0.000196*20 
        momentumPerMB = 0.9
        maxEpochs = 2
	]
    
	reader = [
        randomize = false
        verbosity = 0
        deserializers = (
        [
            type = "ImageDeserializer"
            module = "ImageReader"
            file = "F:\03_Configs\features.txt"
			grayscale=true
            input = [
                features = [
					transforms = (
					[
						type = "Scale"
                        width = 41
                        height = 41
                        channels = 1
						]
						)
                ]
                ignored=[
                    labelDim=1
                ]
            ]
        ]:[
            type = "ImageDeserializer"
            module = "ImageReader"
            file = "F:\03_Configs\labels.txt"
			grayscale=true
            input = [
                labels = [
					transforms = (
					[
						type = "Scale"
                        width = 41
                        height = 41
                        channels = 1
						]
						)
                ]
				ignored=[
                    labelDim=1
				]
            ]
        ]
        )
    ]
]

Edit = {
  action = "edit"
  outputModelPath = "F:\03_Configs\MinWorkingExample\TestModel_edited"

  BrainScriptNetworkBuilder = (new ComputationNetwork {
    # Inputs
    features = ImageInput(81, 81, 1)

    # Load current model
    network = BS.Network.Load ("F:\03_Configs\MinWorkingExample\TestModel")
	model = BS.Network.CloneFunction (network.features, network.ol, parameters="constant")
	
    # Build high-res model
    ol = model (features )

    # Special Nodes
    featureNodes = (features)
    outputNodes = (ol)
  })
}
```
Running the above mentioned code give the attached output: 
[ErrorCode.txt](https://github.com/Microsoft/CNTK/files/741670/ErrorCode.txt)



I tried to use RowStack() in order to bypass the Splice Function, but the same error occured.
out1t = TransposeDimensions(out1,3,1)
out2t = TransposeDimensions(out2,3,1)
out3t= RowStack(out1t:out2t)
out3 = TransposeDimensions(out3t,1,3)
See the ErrorCode here: 
[ErrorCode2.txt](https://github.com/Microsoft/CNTK/files/741697/ErrorCode2.txt)

I also attach the required files for this example:
[features.txt](https://github.com/Microsoft/CNTK/files/741657/features.txt)
![image1](https://cloud.githubusercontent.com/assets/20643017/22461137/59874ed0-e7a8-11e6-90d5-4277c7612b3f.png)
![image2](https://cloud.githubusercontent.com/assets/20643017/22461136/5981fd40-e7a8-11e6-8a4c-f0d2dcc3158a.png)
[labels.txt](https://github.com/Microsoft/CNTK/files/741658/labels.txt)

I would be very happy to get some help. Maybe it is just a stupid error of myself :) 

Thank you in advance.

**Comment by cha-zhang** [comment]
Why is: w3 = ParameterTensor(1:1*1*64, init='heNormal', learningRateMultiplier=1.0)? Do you mean 1:1:1:64?

**Comment by cha-zhang** [comment]
Your Parameter tensor shape are specified as: 32:3*3*1, 1:1*1*64, the '*' is a typo? Do you really mean it?

**Comment by Martlgap** [comment]
I use the '*' for a multiplication. One could simply write 32:9 and 1:64 instead of 32:3*3*1 and 1:1*1*64. I use it for better understanding of the filter kernels. 

Have you tried my example on your machine?

**Comment by Martlgap** [comment]
```
I use the '*' for a multiplication. One could simply write 32:9 and 1:64 instead of 32:3*3*1 and 1:1*1*64. I use it for better understanding of the filter kernels.

Have you tried my example on your machine?
```

**Comment by Martlgap** [comment]
Do you need any more details on my report of that error?

**Comment by cha-zhang** [comment]
I need to access your original model file, and Image1.png.

**Comment by Martlgap** [comment]
Due to not supported upload file formats in Github I sent you an Email.

**Comment by cha-zhang** [comment]
This bug has been fixed and checked into master. Thanks for providing us the minimum working sample!

**Comment by Martlgap** [comment]
Thanks for fixing the issue that fast. You´re welcome!
