### ISSUE TITLE
Build time Error (LNK1181 : cannot open input file 'Math.lib')

### ISSUE THREAD

**Issue by yhnnstshy** [Microsoft/CNTK#136]
I followed the instructions found here https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows to set up all the environment variables and get all the downloads that I need. I am able to build CNTK with Release_cpuonly configuration, but when I try to build it for GPU usage with Release configuration, I get the linker error below.

Error	4	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\BinaryReader\LINK	BinaryReader
Error	14	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\CNTK\LINK	CNTK
Error	9	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\DSSMReader\LINK	DSSMReader
Error	11	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\EvalDll\LINK	EvalDll
Error	7	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Tests\UnitTests\EvalTest\LINK	EvalTest
Error	3	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\HTKMLFReader\LINK	HTKMLFReader
Error	12	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\ImageReader\LINK	ImageReader
Error	6	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\LibSVMBinaryReader\LINK	LibSVMBinaryReader
Error	8	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\LMSequenceReader\LINK	LMSequenceReader
Error	5	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\LUSequenceReader\LINK	LUSequenceReader
Error	1	error LNK1104: cannot open file 'MathCUDA.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Math\LINK	Math
Error	13	error LNK1181: cannot open input file 'htkmlfreader.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Tests\UnitTests\ReaderTests\LINK	ReaderTests
Error	10	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\SparsePCReader\LINK	SparsePCReader
Error	2	error LNK1181: cannot open input file 'Math.lib'	C:\Users\tsehayyk\Source\CNTKRepo\Source\Readers\UCIFastReader\LINK	UCIFastReader

Is there anything I can do to fix this? Thanks for your help.

**Comment by wolfma61** [comment]
Math.lib is generated during the build process. 
I assume you are building from inside VS2013? 

Did you try these steps?
Make sure you have set the configuration correctly (x64, release gpu)
Clean solution or rebuild solution from the build menue

The math.lib should be generated during the build steps, if not you should see error messages prior to the link errors. 

Following these steps, In the x64 directory in your CNTK repo, do you see any versions of math.lib?

thx
Wolfgang

**Comment by yhnnstshy** [comment]
Yes, I'm using VS2013. I have also made sure the configuration is set correctly to (x64, release and not release_nogpu). Again today, I used clean solution and tried to build it again. While building, I kept an eye on the x64 release folder to see if Math.lib is generated. But the library was not generated and I still end up with the same linker error. Furthermore, I didn't see an error message that shows up if math.lib fails to generate. However, I did find this error 
C:\Users\tsehayyk\Source\CNTKRepo\Source\Math\MathCUDA.vcxproj : error  : Unable to read the project file "MathCUDA.vcxproj".
C:\Users\tsehayyk\Source\CNTKRepo\Source\Math\MathCUDA.vcxproj(58,5): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I came across this when I tried to open MathCUDA from solution explorer. I followed the file path and went to BuildCustomizations under MSBuild and sure enough there is no CUDA 7.0.props. But I was able to find this file here, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\extras\visual_studio_integration\MSBuildExtensions. I simply copy pasted the contents of MSBuildExtensions under CUDA and attempted to rebuild. Now it works. 

Thanks for your help. 

yhnns

**Comment by eldakms** [comment]
Hi yhnns,

It seems the NVidia did not integrate with VS2013 properly. Are you sure you firstly installed VS update 5 and afterwards NVIDIA with integration to VS2013?

Thanks!

**Comment by yhnnstshy** [comment]
Hi eldakms, 

I think that may be the source of the problem. I have always had NVIDIA on my computer. Before CNTK, I was using VS2010 and am still using it for my other projects. It's Only recently that I installed VS2013. Do you think simply copy pasting the missing files might possibly complicate things for me in the future? Am I better off reinstalling everything in the correct order?

Thanks!

yhnns

**Comment by wolfma61** [comment]
For NVidia you should definitely install the VSUpdate before installing the Nvidia tools. Reinstalling NVidia might do the trick, definitely something I would try first before redoing the complete install ...

Wolfgang

**Comment by NmC** [comment]
I am struggling same problem. Updating VS and re installing Nvidia tools did solve your problem?

**Comment by yhnnstshy** [comment]
Hi NmC, 

Yes, updating and reinstalling solved it.
