### ISSUE TITLE
Python API: Embedding Layer:  mutually-exclusive check fails

### ISSUE THREAD

**Issue by isaias-sanchez-cortina** [Microsoft/CNTK#1360]
Dear all, 

In cntk.layers, mutually-exclusive check over "init" and "weights" is wrong:
"and" should be used instead of "or". 
Otherwise it will always fail whenever one of them is given.

Code:
def Embedding(shape=None, init=None, weights=None):
    if init is not None or weights is not None:
        raise ValueError('Embedding: init and weights options are mutually exclusive')

**Comment by sayanpa** [comment]
This is a known issue we have a bug we are tracking.

**Comment by tangyuq** [comment]
It is fixed in the latest version. Close this issue for now. Feel free to reopen it if you have further comments.
