### ISSUE TITLE
Sparse Input for C-DSSM network

### ISSUE THREAD

**Issue by ktsaurabh** [Microsoft/CNTK#1362]
Hi, 

I am trying to train a C-DSSM network using CNTK and following the wiki: https://github.com/Microsoft/CNTK/wiki/Train-a-DSSM-(or-a-convolutional-DSSM)-model 
I have a question regarding the input format for the C-DSSM network. What should be the input format for C-DSSM. According to the blog, wouldn't sparse format be problematic in identifying the word boundaries. For example, for the following input:
|L 1 |Q 2:1:5:1 6:1|D: ...
the last id could either be belonging to the word 1 or or word 2? It will be helpful if the expected input format for C-DSSM is available as well.

Thanks!
-SK

**Comment by bmitra-msft** [comment]
Let's assume you represent each word by a trigram hash vector of length 50K and your input consists of a max of 10 words (you can zero-pad if you have less than 10 words and if you have more than 10 words then you can sum the remaining word vectors with the 10th - check the DSSM paper for more details on this).

Then your input representation of the query (or document title) is a tensor of dimensions 10 x 1x 50K. That is, the count of the i<sup>th</sup> (0 <= i < 50K) trigram in the j<sup>th</sup> (0 <= i < 10) word should go to the (i * 10 + j)<sup>th</sup> position in the input vector. Please let me know if that answers your question.

Note: The only difference between sparse and dense formats is that the former doesn't store all the zero entries. So the above explanation applies to both the input formats.

Cheers,
Bhaskar

**Comment by ktsaurabh** [comment]
Thanks @bmitra-msft. This is clearer now.
