### ISSUE TITLE
Supplying negative examples in DSSM/C-DSSM

### ISSUE THREAD

**Issue by ktsaurabh** [Microsoft/CNTK#1363]
Hi, 

Is it possible to supply one's own negative examples for training a DSSM model (https://github.com/Microsoft/CNTK/wiki/Train-a-DSSM-(or-a-convolutional-DSSM)-model) corresponding to a positive example?

Thanks!
SK

**Comment by sayanpa** [comment]
One option would be to generate your own negative sample as a part of the reader input. If you are using brainscript, look at issue 1366.

**Comment by tangyuq** [comment]
Closed this issue for now. Please feel free to reopen it if you have further comments.
