### ISSUE TITLE
python load_model: Unsupported ComputationNode with OperationName='Mean'

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1365]
Hi

I trained my phone recognition model using BS successfully. As a common pre-processing, I do meanVar normalization on my features, as  defined [here](https://github.com/Microsoft/CNTK/blob/7c5fb2d7d806148b5cbd795407f7c7b6a1a64520/Examples/Speech/Miscellaneous/AMI/cntk_config/dnn_6layer_smbr.ndl). More specifically, I use `MeanVarNorm` function that is defined as follow:

> MeanVarNorm(x)
    {
        xMean = Mean(x)
        xStdDev = InvStdDev(x)
        xNorm=PerDimMeanVarNormalization(x,xMean,xStdDev)
    }

After training phase and in order to use model in python, I tried to load it using:
```
from cntk import load_model
mdl = load_model('my_model_name')
```
but get the following error:

>RuntimeError                              Traceback (most recent call last)
<ipython-input-8-b71955d9ef81> in <module>()
----> 1 mdl = load_model('cntkSpeech.dnn.39')
/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/utils/swig_helper.pyc in wrapper(*args, **kwds)
     56     @wraps(f)
     57     def wrapper(*args, **kwds):
---> 58         result = f(*args, **kwds)
     59         map_if_possible(result)
     60         return result
/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/ops/functions.pyc
 in load_model(filename, device)
    636     if not device:
    637         device = DeviceDescriptor.use_default_device()
--> 638     return cntk_py.Function.load_model(filename, device)
RuntimeError: Unsupported ComputationNode with OperationName='Mean' found when loading legacy CNTK model

What should I do to avoid this error? (I use CNTK V 2.0 Beta 8 Release)

regards

**Comment by gvoysey** [comment]
This error occurs while loading the  `Examples/Speech/AN4` pre-supplied model, too.  
ubuntu / python 3.5.

**Comment by zhouwangzw** [comment]
The support for BS Mean node has been added. The fix is now in master, and will be available in the binary download package of the next release (beta 11 perhaps). 

Sorry for the inconvenience!
