### ISSUE TITLE
Python API doesn't support CosDistanceWithNegativeSamples

### ISSUE THREAD

**Issue by sebastiankochman** [Microsoft/CNTK#1366]
We found CosDistanceWithNegativeSamples useful for DSSM-like networks (see https://github.com/Microsoft/CNTK/wiki/Train-a-DSSM-(or-a-convolutional-DSSM)-model ) - it would be great to bring it to the Python APIs as well (both for training and evaluation).

**Comment by sayanpa** [comment]
Thanks Sebastian. We will take this as a feature request.

**Comment by 1026112881** [comment]
Hi, @sayanpa , is there instruction on how to implement such layer in python?

**Comment by sayanpa** [comment]
This feature has been checked-in and now in master.
