### ISSUE TITLE
setup cntk on windows

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1368]
I tried to setup the latest cntk on windows. 
When I build cntk on vs2015, the following error occur:
`D:\cntk\src\cntk2\cntk\Tests\EndToEndTests\EvalClientTests\CNTKLibraryCSEvalExamplesTest\CNTKLibraryCSEvalExamplesTest.csproj : error MSB4057: The target "Build" does not exist in the project.`
What should I do?

**Comment by zhouwangzw** [comment]
Could you please share the complete output when building cntk.sln? How did you setup the dev environment, manually or using script? Could you please check whether SWIG is installed?

Thanks,

**Comment by yttdebaba2** [comment]
I fix the problem by installing SWIG 3.0.10, thank you very much
