### ISSUE TITLE
Evaluating a trained model with1-channel images.

### ISSUE THREAD

**Issue by whiteNoise92** [Microsoft/CNTK#1369]
Hi

I have trained the AlexNet (from your examples) model in BrainScript with two classess of 1-channel images. For example, classes are "cat" and "dog". Then I tried to evaluate some images on it.
Here is the code:

`z = load_model("AlexNet_1channel")`
`z_out = cntk.combine([z.outputs[3].owner])`
`y = softmax(z_out)`
`pic = np.array(Image.open("cat.bmp"), dtype=np.float32)`
`pic = np.ascontiguousarray(pic)`
`predictions = np.squeeze(y.eval({y.arguments[0] : [[pic]] }))`

But all net results was a "dog" class, even i put the "cat" images. All results was with 99-100% confidence.
But when i trained the network with 3-channel images it works correctly!( I just converted them in image editor)
Here is the code:

`z = load_model("AlexNet_3channel")`
`z_out = cntk.combine([z.outputs[3].owner])`
`y = softmax(z_out)`
`pic = np.array(Image.open("cat.bmp"), dtype=np.float32)`
`pic = np.ascontiguousarray(np.transpose(pic, (2, 0, 1)))`
`predictions = np.squeeze(y.eval({y.arguments[0] : [pic] }))`

What i'm doing wrong? Help me, please.

Regards

**Comment by cha-zhang** [comment]
To train with grayscale images I think you need to add ```grayscale=True``` in the cntk configure file.

**Comment by whiteNoise92** [comment]
@cha-zhang Thank you for the reply! I'll try it on monday.

**Comment by whiteNoise92** [comment]
@cha-zhang I tried as you told me and it works well. Thank you!
