### ISSUE TITLE
Examples\Image\GettingStarted\07_Deconvolution_Visualizer.py possible typo in line 77 and 91

### ISSUE THREAD

**Issue by Khoronus** [Microsoft/CNTK#1370]
Dear All,

  Thank you for the wonderful toolkit you are developing. 
I downloaded the latest version of the binary CNTK for Windows (2017-01-20. V 2.0 Beta 9 Release) and I tried to run the deconvolution sample.

After training and running the 07_Deconvolution_Visualizer.py I got the following error message:
Traceback (most recent call last):
  File "07_Deconvolution_Visualizer.py", line 77, in <module>
    loaded_model.find_by_name('z.p1').owner,
AttributeError: 'NoneType' object has no attribute 'owner'

If I'm not wrong, the model generated by 07_Deconvolution.cntk does not contain z.p1.
I modified the python code as follow and the problem seems solved (it generates the output images and txt files).
line 77 - loaded_model.find_by_name('z.p1').owner,
line 77 + loaded_model.find_by_name('z.pool1').owner,

line 91 - encoder_output = output_dict['z.p1']
line 91 + encoder_output = output_dict['z.pool1']

I hope these information can be helpful.

**Comment by cha-zhang** [comment]
I think this has been fixed in the latest master: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/GettingStarted/07_Deconvolution_Visualizer.py
