### ISSUE TITLE
make a constant high pass kernel

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1372]
Hi

I need to convolve an image with a constant high pass kernel. So I need to define a constant kernel as [1 x 9] vetor. How can I make some constant kernel like this: [1, 1, 1, 1, -8, 1, 1, 1, 1] ? Please note that my kernel must be constant and not learnable.

P.S. I tried something like: `KERNEL = Constant(1.0, rows=1, cols=9)`, But don't know how to change its middle element...

**Comment by cha-zhang** [comment]
Yes, you can use a numpy array to initialize a constant: 
```
constant_data = cntk.ops.constant([[1., 2.], [3., 4.], [5., 6.]]) 
```

**Comment by hajix** [comment]
thank for your answer but I need to build the kernel in ndl brain script, not in python...

**Comment by cha-zhang** [comment]
Yes, in NDL you need to load from files. NDL is being deprecated, please consider migrating to Python.

**Comment by hajix** [comment]
Thank for your answers and guide...
