### ISSUE TITLE
dump node problem

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1374]
I trained a model using the latest CNTK on windows, and save the model after training.
Now I want to output the value of a node called `embedding` in the model which is defined as:
`embedding = Parameter(embDim, inputDim, init = "uniform")`

So I use `dump`:
`WorkDir = work`
`makeMode = false`
`modelPath = $WorkDir$/wordembedding.1`
`command = Dump`
`Dump = [`
`    action = dumpnode`   
`    outputFile = "vector.txt"`
`    nodeName = embedding`
     `]`

the `train` action and the `dump` action are written in two different files. After I finished training, I try to run `dump` and the following error occurs:
`[CALL STACK]`
`    > Microsoft::MSR::CNTK::CreateStandardNode<float,int &` `__ptr64,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const & __ptr64>`
`    - Microsoft::MSR::CNTK::CreateNode<float,int &` `__ptr64,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> const & __ptr64>`
`    - Microsoft::MSR::CNTK::ComputationNetworkBuilder<float>::  NewNode`
`    - Microsoft::MSR::CNTK::ComputationNetwork::ReadPersistableParameters<float>`
`    - Microsoft::MSR::CNTK::ComputationNetwork::Read<float>`
`    - Microsoft::MSR::CNTK::ComputationNetwork::CreateFromFile<float>`
`    - DoDumpNodes<float>`
`    - DoCommands<float>`
`    - wmainOldCNTKConfig`
`    - wmain1`
`    - wmain`
`    - __scrt_common_main_seh`
`    - BaseThreadInitThunk`
`    - RtlUserThreadStart`

`EXCEPTION occurred: Attempted to instantiate undefined operation .`

What's wrong with the `dump` node since it works normally on Linux using the old version CNTK.

**Comment by cha-zhang** [comment]
@yttdebaba2 Does this issue still exist? I'm closing it now since it's been 9 months old. Please open a new issue if there is still a problem. Thanks!
