### ISSUE TITLE
what's the reason CNTK gets better performance than other tools on LSTM task?

### ISSUE THREAD

**Issue by pineking** [Microsoft/CNTK#1375]
Here is a benchmark: http://dlbench.comp.hkbu.edu.hk/
The results show that CNTK gets better performance than other tools on LSTM task, could anyone give some details based on the implementation of CNTK on training RNN/LSTM models?

**Comment by cha-zhang** [comment]
You can see some explanation here: 
https://www.youtube.com/watch?v=4NR-XmHiDJw 

Since this has been a very old question, I'm closing it now. Feel free to reopen a new issue if needed.
