### ISSUE TITLE
seq_starts parameter for train_minibatch

### ISSUE THREAD

**Issue by 5vision** [Microsoft/CNTK#1376]
There is good [seq2seq](https://github.com/Microsoft/CNTK/tree/master/Examples/SequenceToSequence/CMUDict) example, which demonstrate how CNTK framework allows to make a sequence model in minibatch agnostic way. Both versions (python, brainscript) uses build-in reader, but what happened if data will be feed from numpy arrays to `train_minibatch` function with `seq_starts` arguments?
Could you explain the benefits of the sequence begin markers? Is it somehow pre-cache data inside the engine (found interesting function `GetCNTKImplMatrixAndMBLayoutFromValueObject`), or this chunk of data will be immediately processed through the computation nodes? Maybe this relates with BPTT?

**Comment by tangyuq** [comment]
For feeding numpy arrays, please see [Manual: How to feed data](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_feed_data.ipynb).

**Comment by eldakms** [comment]
Markers say when to reset the state of the network. There is no pre-cached data inside the network, the minibatch is processed immediately.
