### ISSUE TITLE
error when using txt2ctf.py

### ISSUE THREAD

**Issue by gitgeekd** [Microsoft/CNTK#1377]
So, I keep getting this specific error when trying to create CTF file from my own data. File "new_sent_vybn5.txt" is encoded in UTF-8. What can be wrong here and how to avoid it?

`(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34) C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts>python C:/local/cntk/Scripts/txt2ctf.py --map C:/local/query.wl C:/local/intent.wl C:/local/slots.wl --annotated True --input C:/local/new_sent_vybn5.txt --output C:/local/atis.test3.ctf
Traceback (most recent call last):
  File "C:/local/cntk/Scripts/txt2ctf.py", line 91, in <module>
    convert([open(d, encoding="utf-8") for d in args.map], inputs, output, args.unk, args.annotated == "True")
  File "C:/local/cntk/Scripts/txt2ctf.py", line 45, in convert
    _convertSequence(dictionaries, columns, sequenceId, output, unk, annotated)
  File "C:/local/cntk/Scripts/txt2ctf.py", line 67, in _convertSequence
    output.write(" |# " + re.sub(r'(\|(?!#))|(\|$)', r'|#', token))
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 4: character maps to <undefined>`

![z6pjtzewncu](https://cloud.githubusercontent.com/assets/20352302/22406338/bcd07eb8-e662-11e6-9ebe-c6400332ed30.jpg)

**Comment by tangyuq** [comment]
'\ufeff' is  byte order mark (BOM).  It can not be decoded by 'utf-8' but 'utf-8-sig'. We will seek to incorporate this in the future versions. However, this will be of low priority as utf-8 is the specified supported encoding.
