### ISSUE TITLE
dears,we need cntk to support csharp ,does it support?

### ISSUE THREAD

**Issue by 564064202** [Microsoft/CNTK#1382]
dears,we need cntk to support csharp ,does it support?

**Comment by cha-zhang** [comment]
We support csharp for evaluating CNTK trained models.

**Comment by 564064202** [comment]
@cha-zhang how to use it,and are there some documents?
and what's your plan about csharp support?

**Comment by cha-zhang** [comment]
The eval examples are here: 
https://github.com/Microsoft/CNTK/wiki/CNTK-Eval-Examples 

C# for training is currently at low priority, unless we receive large amount of requests.

**Comment by zhouwangzw** [comment]
More information about C# API can be found in the following pages: [API Usage](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows), [API Doc](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Managed-API). General information about Eval is [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview).

**Comment by nuxai** [comment]
I vote for C# bindings on par with python bindings

**Comment by zhouwangzw** [comment]
Closing this issue, as the training support in .NET is discussed in #960.
