### ISSUE TITLE
Tutorial CNTK_202_Language_Understanding.ipynb  is incomplete

### ISSUE THREAD

**Issue by davidarh** [Microsoft/CNTK#1383]
Hello,

I am completing CNTK's  tutorials and have found that tutorial CNTK_202_Language_Understanding.ipynb is incomplete. The introduction of the tutorial states:

> We will start with a straight-forward embedding of the words followed by a recurrent LSTM. This will then be extended to include neighboring words and run bidirectionally. **Lastly, we will turn this system into an intent classifier.**

However, the intent classifier is nowhere to be found, except for the format in the data. Please check if this part of the tutorial is actually missing or if it is continued at a later tutorial, include a link.

**Comment by sayanpa** [comment]
Change integrated into master.
