### ISSUE TITLE
Runtime Error : next_minibatch with FULL_DATA_SWEEP . Feature Request: Read until end of data file and return the overall number of samples and sequences

### ISSUE THREAD

**Issue by isaias-sanchez-cortina** [Microsoft/CNTK#1387]
Hi all, 
Since version 2.0beta8 and 2.0beta9 the number within FULL_DATA_SWEEP (=2^64-3) constant yields the following error when reading with next_minibatch() :  
"       RuntimeError: Global and local size of the minibatch cannot exceed max int.                "
The error  has been reproduced on 64bit-linux, and also on windows over CPU, as well as GPU.

Please note that using next_minibatch(FULL_DATA_SWEEP)  for a MinibatchSource --initialized with FULL_DATA_SWEEP flag-- was the only way to evaluate a whole data set without knowing the number of samples in advance . Now, the work around is to count the lines with python.

Additionally, independently of whether next_minibatch(FULL_DATA_SWEEP)  is fixed again or not, 
I would like to suggest the addition of a function to read all the data until the end of the original data file. The current flag for the read minibatch indicating if the sweep was crossed is not useful in retrieving the remaining samples until the end.

Also, it would be nice to have a call or variable to get the whole number of samples, as well the whole number of sequences. This would greatly simplify the coding.

**Comment by eldakms** [comment]
Thanks for reporting, I will have a look and try to fix asap.

**Comment by avader906** [comment]
Can we please have these as options ? They severely impact performance unless requested. Hopefully the purpose behind these changes is to bring the capability to work with streams closer.

**Comment by eldakms** [comment]
It is not clear why you need this? 
"Please note that using next_minibatch(FULL_DATA_SWEEP) for a MinibatchSource --initialized with FULL_DATA_SWEEP flag-- was the only way to evaluate a whole data set without knowing the number of samples in advance "

next_minibatch with FULL_DATA_SWEEP will allocated a single the buffer for the complete data set -for sure this is not scalable on any real data set that does not fit in memory.

if you need to count the number of samples - use a loop on next_minibatch till it returns empty minibatch.

**Comment by eldakms** [comment]
In v2/latest master you can also limit your data by the number of sweeps (I.e. num_sweeps = 3 for three running the data on three sweeps). Closing this due to long inactivity. Feel free to reopen if still relevant. Thanks!

**Comment by nietras** [comment]
@eldakms how would looping over minibatch source work with minibatch size > 1 and the number of samples not being divisible by the minibatch size? `next_minibatch` always returns the requested minibatch size, so you can't count this in that way. The minibatch source will do different number of batches for different sweeps, which is not ideal, especially not for validation/test evaluation.

How do we tell the minibatch source to get **remaining** samples from a sweep and not the full minibatch size if there are not than many samples left in a sweep?
