### ISSUE TITLE
Restoring of saved model with UserFunction not working

### ISSUE THREAD

**Issue by schroederen** [Microsoft/CNTK#1388]
When using the Python interface and trying to save and restore a model (via node.save_model() and node.restore_model()) that incorporates a UserFunction, the following error is thrown upon restoring:

`File "C:\CNTK\bindings\python\cntk\cntk_py.py", line 1363, in restore_model
    return _cntk_py.Function_restore_model(self, modelFilePath)
RuntimeError: Required key 'version' is not found in the dictionary.`

This is reproducable with the simple MySigmoid function described in the docs (https://www.cntk.ai/pythondocs/extend.html).

**Comment by amitaga** [comment]
Serialization/Deserialization of UserFunctions is currently unsupported. This will become available in a few weeks.

**Comment by tangyuq** [comment]
As of CNTK 2.0,  Serialization/Deserialization of UserFunctions is supported now.  See the [updated document](https://www.cntk.ai/pythondocs/extend.html) for more information.

Close this issue for now. Please feel free to re-open it if you have further comments.
