### ISSUE TITLE
Build Errors on VS2013

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#1389]
I just did a git source  pull to check a bugfix and I'm getting lots of errors like:

Error	1	error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets	64	5	Common (CNTK Core\Common)

I'm assuming there is still a way of building on vs2013. However, I tried changing the platform toolset on every project (pretty tedious) and I'm still getting the errors. See:

https://drive.google.com/open?id=0B4dreadgSUU4b0hidzlhbVlEd28

Suggestions welcome.

Thanks

Derek

**Comment by wolfma61** [comment]
We move CNTK to VS2015 several weeks ago. The project files are not compatible with VS2015, so you will need to upgrade to VS2015.
The community edition of Visual Studio 2015 should work fine ...
see the release notes for Beta8 
https://github.com/Microsoft/CNTK/wiki/CNTK_2_0_beta_8_Release_Notes
and
https://github.com/Microsoft/CNTK/wiki/Setup-Migrate-VS13-to-VS15

Is there anything preventing to move to VS2015?

thx
Wolfgang

**Comment by dmagee** [comment]
Just upgrading to vs2015 may be easy enough if you're just building CNTK, but we're linking CNTK to a (C++) commercial application with about 20 other dependencies. Each one needs to be built again if you upgrade the compiler. This process takes about 2 days (not including rebuilding the cntk dependencies, cntk, or regression testing). This includes re-imaging machines (there are issues with installing multiple versions of vs on the same machine, that while rare mean it is best avoided and we always start with a clean machine). I know exactly how long as I did it around november when we upgraded to vs2013 Pro from vs2012 Pro (we chose this version as it was the only compiler supported by CNTK). Not one of these other dependencies is locked to a particular compiler (the odd one has dropped support for vs2010 or earlier). Imagine if they did? If everyone did this you'd have libraries that couldn't be used together. They tackle supporting multiple compilers in a variety of ways:

1) CMake - This by far the easiest and most widespread solution (about 70% of libraries we use use this to generate project files)
[N.B. There are other CMAKE-alike packages but I haven't found any others used in more than a handful of projects]
2) Supplying multiple project/solution files for different versions with different names (e.g. XXX.vs2013, XXXX.vs2015, etc.)
3) Just supplying an old version project file (e.g. vs2010, vs 2012) that upgrades effortlessly when loaded into a subsequent version.
4) Supplying a binary version that's compatible across compilers (I suspect this is achieved using a non-microsoft compiler, and not a great deal of use if you want a quick rebuild because of  bugfix).

I appreciate Microsoft is only a small organisation compared to say Kitware, Applied Informatics, Willow Garage etc. (sorry for the sarcasm), but just switching the only compiler you can use at zero notice and with no transition period is not exactly great for a lot of users who just did a pull to get a minor bugfix and test it. I'm seriously worried if you intend to keep doing this in the future. Would it hurt to use one of the methods above to maintain back compatability with a range of compilers? Option 2 should be fairly trivial.  I would however recommend option 1. It is the lowest maintenance in my experience in the long run. You only need a virtual machine to test the build once in a while.

Yours

D.

P.S. Before someone suggests compiling CNTK on 2015 and having some sort of a pipe between the vs2013 app and CNTK (as someone did in another thread), that's what we do now and the purpose of compiling it in is to get a performance increase, which I estimate could be considerable as I/O is the main time consuming element.

**Comment by wolfma61** [comment]
at this point we are on VS2015
CMAKE is on the long term wish list ... but no commitment yet, never been high enough on the priority list

we are not planning to support multiple project versions or support multiple compiler versions.

on the positive side: VS2017 is binary compatible to VS2015, that should make some of these problems go away. VS2017 won't be supported until NVidia supports VS17 for their CUDA tools out-of-the-box
