### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by such87** [Microsoft/CNTK#139]
Hi,

I am facing a new compilation issue in a latest checkout :

In file included from Source/Math/ConvolutionEngine.cpp:8:0:
Source/Math/CuDnnConvolutionEngine.h:34:47: error: ‘PoolDesc’ is not a class, namespace, or enumeration
     PoolDescPtr CreatePoolDescriptor(typename PoolDesc::PoolKind kind, size_t w, size_t h, size_t wStride, size_t hStride, size_t wPad, size_t hPad) override;

Any help is appreciated.

Thanks

**Comment by Alexey-Kamenev** [comment]
Hello,
I've just tried building the latest master (gcc 4.8.4) but did not have this problem. Can you please share a bit more info about your setup?

**Comment by such87** [comment]
Thanks for your reply. That was a separate issue which is now resolved. It was related to a wrong gcc path.

A new issue that I now see is this :

Source/Readers/LMSequenceReader/SequenceReader.cpp: In instantiation of ‘Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&)::<lambda(int)> [with ElemType = double]’:
Source/Readers/LMSequenceReader/SequenceReader.cpp:1795:18:   required from ‘struct Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = double; size_t = long unsigned int]::<lambda(int)>’
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:73:   required from ‘bool Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = double; size_t = long unsigned int]’
Source/Readers/LMSequenceReader/SequenceReader.cpp:2189:16:   required from here
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:48: error: integer overflow in expression [-Werror=overflow]
                 return (std::rand() * (RAND_MAX+1) + std::rand()) % i; });
                                                ^
I am using gcc 4.9.2

**Comment by wolfma61** [comment]
We have seen problems with different gcc versions, but haven't had the time to adopt.
we are currently using 4.8.4 to compile/build. We will move forward to a more recent version soon, although this hasn't been scheduled yet.
