### ISSUE TITLE
how to use cntk text format reader to train class-based LMs?

### ISSUE THREAD

**Issue by zhangyike** [Microsoft/CNTK#1390]
I'd like to train a LM with multiple inputs and multiple outputs using CNTKTextFormat-Reader. In order to speed up training, I'd like to use ClassBasedCrossEntropyWithSoftmax function. However, I have no idea how to include word class information in CNTKTextFormat files. Can anyone help me? Thank you.

**Comment by tangyuq** [comment]
Regarding multiple inputs and multiple outputs, it can be done by defining multiple streams in the reader.  See 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_202_Language_Understanding.ipynb for an example. 

Copying a slightly modified code snippet here:
import cntk as C
mbsource = C.io.MinibatchSource(C.io.CTFDeserializer(path, C.io.StreamDefs(
         query         = C.io.StreamDef(field='S0', shape=vocab_size,  is_sparse=True),
         intent_label = C.io.StreamDef(field='S1', shape=num_intents, is_sparse=True),  
         slot_labels   = C.io.StreamDef(field='S2', shape=num_labels,  is_sparse=True)
     )))
then you can feed these streams as inputs or outputs to training or evaluation by mapping them to the corresponding variables in the model.

Regarding ClassBasedCrossEntropyWithSoftmax function, it is not exposed to Python API yet, You will need to use C++ or BrainScript APIs.

I am closing this issue for now. Please feel free to re-open it if you have further comments.
