### ISSUE TITLE
Issue with FeatureExtraction Example

### ISSUE THREAD

**Issue by rahul-anand** [Microsoft/CNTK#1394]
There seems to be a couple of issues with FeatureExtraction example .

1.) python install_data_and_model.py 
writes "test.txt" file with "\\" instead of "/" for linux which causes the example to give error.

2.) print_all_node_names(model_file) 
 gives error as `NameError: name 'Function' is not defined`

**Comment by pkranen** [comment]
Thanks for pointing out, I fixed it and will check it in with the next commit.

**Comment by rahul-anand** [comment]
Thanks for your help. Can you please point me how to "print node names of model graph" using new syntax ?

**Comment by pkranen** [comment]
You can see it in the revised version of the FeatureExtraction example [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/FeatureExtraction/FeatureExtraction.py#L61).

**Comment by rahul-anand** [comment]
Its not working directly with beta10 release. so i guess i would have to just wait for new beta release or compile the code from source code.
Thanks anyways

**Comment by rahul-anand** [comment]
Still a couple of issues with latest feature extraction example.
1.) `    node_outputs = get_node_outputs(load_model(model_file))` 
gives error as 
AttributeError: Function does not have 'is_parameter' and it cannot be looked up in its outputs because it does not have exactly one

2.)`for out in node_outputs: `
    `print("{0} {1}".format(out.name, out.shape))`
This doesn't print any name only shape.  

3.) Small grammatical mistake in install_data_and_model.py. It should have "Grocery" instead of "grocery"

**Comment by pkranen** [comment]
Point 1. has been fixed in master, will be in next beta. Point 2.: for the model used in the feature extraction example you should see node names. Node naming in general is work in progress. 3. Note taken.

Thanks!
