### ISSUE TITLE
Native support for alternative activations (e.g., ELU, PReLU, etc.)

### ISSUE THREAD

**Issue by bencherian** [Microsoft/CNTK#1395]
Is there any planned native support in the near future for alternative activations like ELU and parametric ReLU? They could be defined in Python through the new API, but I imagine there would be a significant performance penalty.

**Comment by ebarsoumMS** [comment]
There shouldn't be a perf penalty if you define them purely using CNTK ops.

**Comment by bencherian** [comment]
Looks like this got added in beta12.

**Comment by ebarsoumMS** [comment]
Yes..
