### ISSUE TITLE
Wiki: wrong link to CPPEvalV2Client

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#1396]
Bottom of this page ```https://github.com/Microsoft/CNTK/wiki/Native-CNTK-Library-Eval-Interface``` contains a link to ```https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CPPEvalV2Client``` that does not exist (404).

Please replace with either CPPEvalExtendedClient or CPPEvalClient.

**Comment by zhouwangzw** [comment]
@avader906 Thanks for reporting it. It is now fixed. The correct link is [CNTKLibraryCPPEvalExamples](https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CNTKLibraryCPPEvalExamples).

Sorry for the inconvenience.
