### ISSUE TITLE
Feature request: implement GPU memory check for given minibatch size upon startup (inc MPI nodes)

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1397]
Current implementation does not explicitly check minibatch size vs available memory on nodes prior to readers parsing input - when the number of parameters is already known. In cases of large inputs CNTK crashes prior to first epoch after a long delay.

**Comment by KeDengMS** [comment]
Currently it's the user's responsibility to set the appropriate minibatch size for the first epoch. We may have auto tuning in the future to start training from minibatch_size of 1, but even with that you may still run OOM for big models like VGG on a GPU with small memory.
