### ISSUE TITLE
Feature request: including CNTKLibrary header files in binary distributions

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#1398]
Please include CNTKLibrary.h and CNTKLibraryInternals.h with binary distributions containing CNTKLibrary-2.0 LIB/DLL (as used in DLL compilation included with the distribution). This is for user convenience only - it is included with the release source code zip.

**Comment by wolfma61** [comment]
Hi -
are you asking for an easy way to have a distribution to use the libs/dlls from c / c++?
Linux and/or Windows?

thx
Wolfgang

**Comment by avader906** [comment]
This pertains to Windows platform. 

The end user can download the entire CNTK source tree and integrate CNTK Library API DLL compilation as the part of his/her build process. Alternatively, the end user can link the DLL provided with the release.

The latter requires CNTK Library API header files. Pulling header files from the current source code tree does not guarantee that interfaces match - given the rapid pace of development and releases in this alpha/beta stages. 

This leaves the user searching for the location of header files (which is not mentioned in the documentation) that match the binary release. This is not an issue, given the entire source code tree of the binary release is available.

However, it would be good form to include CNTKLibrary.h **and** CNTKLibraryInternals.h in the library directory (along with DLL) to simplify this process.

While we are on the subject of header files, please update the documentation to reference that CNTKLibrary.h **and** CNTKLibraryInternals.h **both** are required for C++ API use in the following pages:

```https://github.com/Microsoft/CNTK/wiki/CNTK-Library-API#c-api```
```https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows```
```https://github.com/Microsoft/CNTK/wiki/Native-CNTK-Library-Eval-Interface```

**Comment by zhouwangzw** [comment]
@avader906 The binary release package does contain both header files under Include directory. We will update the Wiki pages make them clearer.

**Comment by avader906** [comment]
@zhouwangzw thank you.
