### ISSUE TITLE
Prebuilt models for image classification

### ISSUE THREAD

**Issue by shethsh** [Microsoft/CNTK#140]
I am transitioning from Caffe and planning to use pre-built models for finetuning in CNTK. I am not able to find a model repository. Can somebody provide pre-built models for image classification?

**Comment by Alexey-Kamenev** [comment]
Hello,
We currently do not have pre-trained models available on GitHub. This is certainly something we plan to do, hopefully very soon.

**Comment by shethsh** [comment]
Hi,
Thanks for the response.
I wanted to know if we can stop and resume training a network.
I saw "adapt", but, it seems that we need to specify a ref node name and seems to be suitable only for Finetuning. But, if I want to train in parts, say, whenever I get new data, I will train and store the model. How can this be done?
Also, it will be great if you can provide more info on "adapt".

**Comment by frankseide** [comment]
Yes, you can. CNTK keeps checkpoints. You can always pick up a training after a completed epoch.

If this does not happen automatically, please say “makeMode = true” somewhere in the outer level of the main config (and make a backup of your model folder before you try this for the first time, just in case).

**Comment by shethsh** [comment]
Thanks. I am able to resume training from Epochs. Closing this issue
