### ISSUE TITLE
Use interfaces in the CNTK Library Managed API

### ISSUE THREAD

**Issue by jcsharp** [Microsoft/CNTK#1400]
The CNTK Library Managed API should use interfaces rather than classes. 

Specifically, the library API uses `List<T>` and `Dictionary<TKey,TValue>` pretty much everywhere. It should instead expose `IList<T>`, `IEnumerable<T>`, `IReadOnlyList<T>`, `IReadOnlyDictionary<TKey,TValue>` etc.

**Comment by jcsharp** [comment]
I'm trying to make this change myself, but I'm not sure how the code is generated in `CNTKLibraryManagedDll/SwigProxyClasses`. It contains many constructors like this one:

`  public BoolVector(global::System.Collections.ICollection c) : this() {`
`    foreach (bool element in c) { ...`

That code is not optimal, and it does not work with generic collection interfaces, so I would like this to be generated instead:

`  public BoolVector(global::System.Collections.Generic.IEnumerable<bool> c) : this() {`
`    foreach (bool element in c) { ...`

Any idea how to do it?

**Comment by zhouwangzw** [comment]
@jcsharp  Yes. We are working on replacing List<T> with IList<T>, together with optimization to reduce data copy between C++ and C#. One of disadvantage of IEnumerable<T> is no support for index operator, so we will probably stay with IList<>. 

If you want to change to List<T> to IList<T> by yourself, you can look into bindings\csharp\swig\cntk_cs.i. The BoolVector() is generated by swig.exe. If you want to change its interface to directly use IEnumerable<bool>, you need to change typemaps in swig. 

We are much appreciated if you can contribute to make CNTK better. 
Thank you!

**Comment by jcsharp** [comment]
Thanks @zhouwangzw,

I figured out how to modify the typemap to generate better constructors and submitted a pull request to the SWIG repository. 

Using this modified typemap allowed me to replace most of the `List<T>` and `Dictionary<T>` exposed in the CNTK Library Managed API with the corresponding interfaces. I left a couple of `List<T>` where performance would have been affected. 

[https://github.com/Microsoft/CNTK/compare/master...jcsharp:interfaces](https://github.com/Microsoft/CNTK/compare/master...jcsharp:interfaces) 

I you think the changes I've made are useful, I will submit a pull request.

JC

**Comment by nuxai** [comment]
thanks jcsharp, it would really be nice to have C# binding similar to Python, I hope to have time available soon to contribute myself

**Comment by zhouwangzw** [comment]
@jcsharp Thanks for your contribution. I have a couple of comments: 
1) The Extensiblity/EvalWrapper is the C# Eval V1 Library, which is directly written in Managed C++, instead of being generated by SWIG. As it is a legacy library, and being used in many production services, I would perfer to leave it as is, except there are some important reasons for change. The current Eval V2 library is in bindings/charp directory, which is generated by SWIG.
2) Regarding std_vector.i,  would it be sufficient to use SWIG_STD_VECTOR_ENHANCED() in the interface file? Have you made any other changes? If possible, I would use the standard one from SWIG, instead of customized one, so that we can automatically benefit from new features/bug fixes fom the SWIG community. 
3) IList<> for arguments/outputs and etc. looks fine. But List<IList<>> looks a little unusual. Is it due to performance reason? 

Thanks again for your efforts.

**Comment by jcsharp** [comment]
1. I agree we should leave the old eval lib alone.

2. I could not figure out how to override the `std::vector` typemap from the SWIG library to just add the new constructor in the proxy class, so I made a local copy of the entire file. I submitted this change to SWIG, so if they accept it, the local copy can be removed later. Do you know a cleaner way to do this?

3. There are `List<IList>` variables in CNTKLibraryCSEvalExamples.cs, because the changes I've made require an `IList<IList<T>>`, and `List<List<T>>` would not compile.

[https://github.com/Microsoft/CNTK/compare/master...jcsharp:interfaces2](https://github.com/Microsoft/CNTK/compare/master...jcsharp:interfaces2)

**Comment by zhouwangzw** [comment]
Sorry for late response. I will take a look.

**Comment by larcai** [comment]
i made some changes to swig to generate a lot more c# classes for the managed library
was not able to test, but the managed library compiles
i also added std_unordered_set.i to look and feel like System.Collections.Generic.ICollection
[https://github.com/Microsoft/CNTK/compare/master...larcai:master](url)

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by zhouwangzw** [comment]
Starting from 2.0RC1, the C# API has adopted IList<>, IDictionary<> interface instead of classes themselves. Please check the latest release 2.0 for details. So I am closing this issue and feel free to open a new issue if you have more suggestions and requests.
