### ISSUE TITLE
Program crashes after enumerating output variables

### ISSUE THREAD

**Issue by elevir** [Microsoft/CNTK#1401]
CNTK.GPU 2.0.0-beta 10 package
I was trying to print some information about output variables of model (code below), but after this enumeration program crashed without any information about exception (program executes in Debug mode). So, information about all of variables was printed. On beta 9 all work fine.
![image](https://cloud.githubusercontent.com/assets/8929511/22621458/494c1498-eb35-11e6-8c32-c112a73212ea.png)

```
class Program
    {
        static void Main(string[] args)
        {
            string modelPath = <path>;
            Function model = Function.LoadModel(modelPath, DeviceDescriptor.GPUDevice(0));
            foreach (var variable in model.Outputs)
            {
                Console.WriteLine($"Variable: {variable.Name}");
                Console.WriteLine($"Variable data type: {variable.DataType}");
                Console.WriteLine($"Is variable input: {variable.IsInput}");
                Console.WriteLine($"Is variable output: {variable.IsOutput}");
                Console.Write($"Variable dimensions: ");
                foreach (var dimension in variable.Shape.Dimensions)
                    Console.Write($"{dimension} ");
                Console.WriteLine();
                Console.WriteLine();
            }
        }
    }
```

**Comment by tangyuq** [comment]
Will need more details for diagnosis . Have you tried the latest release? 

Close this issue for now. Please feel free to re-open it if this issue persists in the newly release.
