### ISSUE TITLE
Predictions with ResNet_18.model incorrect

### ISSUE THREAD

**Issue by ilkarman** [Microsoft/CNTK#1405]
I am trying to load the trained ResNet model and run the classification on a random image. 

```
# Load model
z = load_model(MODEL_PATH)
z_out = ct.combine([z.outputs[3].owner])

# Load image and resize
img = cv2.cvtColor(cv2.imread(filename), cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (224, 224))
img = np.array(img, dtype=np.float32)
img = np.ascontiguousarray(np.transpose(img, (2, 0, 1)))
    
# Use last layer to make prediction
z_out = combine([z.outputs[3].owner])
result = np.squeeze(z_out.eval({z_out.arguments[0]:[img]}))

# Final probabilities
a = np.argsort(result)[::-1] 
```

[Here](https://github.com/ilkarman/Blog/blob/master/Flask%20Images/Predict-CNTK.ipynb) is a reproducible example.

The network seems to think this is a turkey. I don't think the model file is wrong as I tried both _18 and _152, however perhaps:

1. The labels txt is in a different order to the one I download (in which case where I can find the corresponding labels to the model)
2. The pre-processing should be different
3. The way the model is loaded is different.

**Comment by cha-zhang** [comment]
Could you try to follow the example here: 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb

**Comment by ilkarman** [comment]
I used the same set-up as the CIFAR example above:

```
    image_mean   = 133.0
    image_data   = np.array(Image.open(filename).resize((224, 224), Image.ANTIALIAS), dtype=np.float32)
    image_data  -= image_mean
    image_data   = np.ascontiguousarray(np.transpose(image_data, (2, 0, 1)))

    # Kept line since loading Brain Script model
    z_out = combine([z.outputs[3].owner])
    result = np.squeeze(z_out.eval({z_out.arguments[0]:[image_data]}))
    
    # Return top 3 results:
    top_count = 3
    result_indices = (-np.array(result)).argsort()[:top_count]
    
    for i in result_indices:
        print('probability=%f, class=%s, %i' % (result[i], LABELS[i], i))
```

However, it wasn't successful. This is the output when the picture is a donkey:

```
probability=9.380024, class=n00468299 shinny, shinney, 105
probability=8.516109, class=n00467995 field hockey, hockey, 104
probability=8.141252, class=n01560419 bulbul, 383
```

**Comment by cha-zhang** [comment]
Is it possible you run your test on an image in the training set? That shall verify if it's a code issue, or it's a model issue.

**Comment by spandantiwari** [comment]
Closing this now. Please reopen if you have additional information.
