### ISSUE TITLE
Feature request: implement MPI node restart on next epoch in fell out / connectivity problem

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1406]
Currently if one of the distributed nodes falls out during the epoch, training crashes. Please implement either graceful training shutdown with checkpoint save or continued training and with an attempt to restart the broken node on next minibatch / epoch.

**Comment by KeDengMS** [comment]
As long as user set up checkpoints correctly, termination of training should not be an issue. One can always restart from previous checkpoints using a script.
