### ISSUE TITLE
C# CreateBatchOfSequences results in exception

### ISSUE THREAD

**Issue by mikhail111777** [Microsoft/CNTK#1407]
Hi,

I had code which worked with beta 9, using this method:
public static Value CreateBatchOfSequences<T>(uint dimension, List<List<uint>> batchOfSequences, DeviceDescriptor device, bool readOnly = false);

After upgrading the library to beta 10 it fails with the error:
Error: System.ApplicationException: The first entry of a mask should be Valid or SequenceBegin
   at CNTK.Function.Evaluate(UnorderedMapVariableValuePtr arguments, UnorderedMapVariableValuePtr outputs, DeviceDescriptor computeDevice)
   at CNTK.Function.Evaluate(Dictionary`2 arguments, Dictionary`2 outputs, DeviceDescriptor computeDevice)

I've tried the second function, which accepts a list of bools (setting all to true), with the same results.

**Comment by mikhail111777** [comment]
If using batch containing only one sequence:

Error: System.ArgumentOutOfRangeException: Invalid sparse CSC format initial data specified for NDArrayView construction
   at CNTK.Value.CreateOneHotFloat(UInt32 vocabularySize, SizeTVectorVector oneHotSequences, BoolVector sequenceStartFlags, DeviceDescriptor device, Boolean readOnly)
   at CNTK.Value.Create[T](UInt32 dimension, List`1 sequences, List`1 sequenceStartFlags, DeviceDescriptor device, Boolean readOnly)

**Comment by zhouwangzw** [comment]
In Beta 10, we addd more checks to validate the value and mask when creating a Value object. However, I could not repo the error you have on our tests (evaluation of an ATIS model using one-hot vector format to create Sequence or BatchOfSequences). Would you mind to share a repo or more code snippet for further investigation?

**Comment by mikhail111777** [comment]
It appears that all these effects are caused by empty sequences. Basically, my model had 3 input sequences on different dynamic axes. When one of the sequences is empty, all these effects can occur. Fixed by adding a void vector to each empty sequence before calling CreateBatchOfSequences.

I suggest adding another check so that error output will be more easy to interpret.

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)
