### ISSUE TITLE
How to use this picture and text training text recognition?

### ISSUE THREAD

**Issue by HeMinzhang** [Microsoft/CNTK#1409]
![mnist_examples](https://cloud.githubusercontent.com/assets/2683269/22677835/c45f652a-ed30-11e6-8d62-5fade5adcc83.png)
Because of my poor English, I can not find a way to train for a week.

**Comment by spandantiwari** [comment]
@HeMinzhang this seems like the MNIST dataset, or at least very similar. We have several examples that work with MNIST dataset. You can find them under CNTK/Tutorials. In particular, the 
 CNTK/Tutorials/CNTK_103D_MNIST_ConvolutionalNeuralNetwork.ipynb tutorial may be of interest.
