### ISSUE TITLE
TimesNode: Sparse tensors are not supported unless they are 1D or 2D matrices

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1411]
I have 2 matrix. A=[I x J] and B=[J x K x *] where * represents the minibatch size.
A is a dense matrix and B is a sparse matrix.

Now I write: C= A * B in CNTK BrainScript, and got the following error message:
`[CALL STACK]`
    `> Microsoft::MSR::CNTK::TensorView<float>::  AsMatrix`
    `- Microsoft::MSR::CNTK::TensorView<float>::  DoMatrixProductOf`
    `- Microsoft::MSR::CNTK::TensorView<float>::  AssignMatrixProductOf`
    `- Microsoft::MSR::CNTK::TimesNodeBase<float,0>::  ForwardProp`
    `- Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp`
    `- Microsoft::MSR::CNTK::ComputationNetwork::  ForwardProp`
    `-Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>`
    `- Microsoft::MSR::CNTK::SGD<float>::  TrainOneEpoch`
    `- Microsoft::MSR::CNTK::SGD<float>::  TrainOrAdaptModel`
    `- Microsoft::MSR::CNTK::SGD<float>::  Train`
    `- DoTrain<Microsoft::MSR::CNTK::ConfigParameters,float>`
    `- DoCommands<float>`
    `- wmainOldCNTKConfig`
    `- wmain1`
    `- wmain`
    `- invoke_main`

`EXCEPTION occurred: AsMatrix: Sparse tensors are not supported unless they are 1D or 2D matrices.`

It seems that TimesNode does not support the implementation of 3D sparse matrix. And I do not want to transfer sparse matrix to dense since the computation will cost too much time.

So what can I do to solve this problem?

**Comment by KeDengMS** [comment]
Can you try with latest CNTK in python? We have added support for 2D sparse in recent builds.
