### ISSUE TITLE
Cudnn failure due to big mini-batch size when ASGD validate

### ISSUE THREAD

**Issue by zhengsx** [Microsoft/CNTK#1412]
Hi,

Mini-batch size will be enlarge n times when distributed training with n GPUs and distributed reader will automatically split the whole mini-batch size into each node . 

The distributed reader will be closed when using DataParallelASGD with validation, it leads to n times mini-batch size passing into validation reader and causes Cudnn failure.

@chivee can you help to look into this?
https://github.com/Microsoft/CNTK/blob/master/Source/SGDLib/SGD.cpp#L623 

Thanks

**Comment by avader906** [comment]
@zhengsx why did you close the issue ? Seems like validation can not be done on the same minibatch size as for the training.
