### ISSUE TITLE
broken link in documentation

### ISSUE THREAD

**Issue by NeuralDip** [Microsoft/CNTK#1416]
on page : [https://github.com/Microsoft/CNTK/blob/v2.0.beta10.0/Tutorials/CNTK_104_Finance_Timeseries_Basic_with_Pandas_Numpy.ipynb](https://github.com/Microsoft/CNTK/blob/v2.0.beta10.0/Tutorials/CNTK_104_Finance_Timeseries_Basic_with_Pandas_Numpy.ipynb)
at paragraph : "Number of passes through the data..."
the link to "L1 regularization" is broken. needs close parenthesis

**Comment by avader906** [comment]
Would be great to automatically check Wiki for broken links - tools exist ```https://validator.w3.org/checklink```

**Comment by mahilleb-msft** [comment]
Thanks, I've fixed this one an another one in the same notebook. I will merge that to master, and also cherry-pick it for the release branch for our current 2.0.beta10.0 release.

Good point about automatical link checking, we'll implement something like this in the future.

Best, Mark
