### ISSUE TITLE
pad problem in ConvLayer and PoolingLayer

### ISSUE THREAD

**Issue by PetrusKe** [Microsoft/CNTK#1417]
Hi, I met some strange problems while I training **ResNet20-Cifar10** in official examples.

First, I just add **'pad=true'** for AveragePoolingLayer in **_ResNet20_Cifar10.cntk_**. 
(AveragePoolingLayer {(8:8), pad=true, stride=1 }). 
Then I train the model, but train errs are very height(always greater than 90%), I paste a printscreen as follow:
![image](https://cloud.githubusercontent.com/assets/15672578/22729336/4a88f598-ee1d-11e6-958a-544fb202ced6.png)

If I delete 'pad=true', everything works well:
![image](https://cloud.githubusercontent.com/assets/15672578/22729580/545c3ee4-ee1e-11e6-9d31-1d640a903cf1.png)

Why this problem happened?

Second, I tried to modifiy **_ConvNet_Cifar10.cntk_** in the same way, no error occurs.

Then, I changed **'pad=true'** to **'pad=false'** for ConvLayer in ResNet's _**Macros.bs**_ file for test, a new problem arises, no matter how I adjusted lowerPad and upperPad, training process will always produce an error, prompt me: **EXCEPTION occurred: Convolution requires that kernel fills the entire space if auto-padding is disabled.**.

So what is the real explanation for parameter **pad**, **lowerPad** and **upperPad** ?  I have read cntk document but still not understand them clearly.
 
How can I set them to make my net work well?Just need to set **'pad=true'** in ConvLayer and **'pad=false'** in PoolingLayer?

By the way,  the cntk versions I use is **CNTK 2.0beta4.0+**.

Wish for your help.

**Comment by cha-zhang** [comment]
In ResNet, AveragePooling is actually a GlobalAveragePooling, so if the input to the pooling is 256x8x8, after pooling it's a vector of 256. When you change padding to true, output of pooling is still 256x8x8. The next layer's input is thus very big, and could cause issue for training. 

When you change pad to false for convolution, it changes the output shape size. As a result, when it reaches AveragePooling, the input size should be smaller than 8x8, and if you still do AveragePooling of size 8x8, it will not work. 

In Python API we have GlobalAveragePooling in the layers API that will automatically detect the input size. I suggest you try Python, and use the latest cntk version (beta 10.0).

**Comment by PetrusKe** [comment]
@cha-zhang Big thanks for your explanation! Now I know how to solve these two problems.

One more question, if in a caffe script. pad=0 be set in ConvLayer(or PoolingLayer), how to set pad's value for this layer when I transform this script to cntk?

**Comment by cha-zhang** [comment]
caffe pad=0 should map to CNTK with autoPad=false.

**Comment by PetrusKe** [comment]
@cha-zhang thanks for your help!
