### ISSUE TITLE
ImageReader does not accept multiple identical files in zip

### ISSUE THREAD

**Issue by DragomirYankov** [Microsoft/CNTK#1421]
Hi,
When I reference the same image file in my config from a zip with images ImageReader throws an error. The issue does not exist if the images are read from a directory instead of a zip file.

Repro:
I have a zip - images.zip with three images. I reference them inside my train.config:

images.zip@/Andorra.png	1
images.zip@/Barbados.png	0
images.zip@/Italy.png	1

This works fine with the Deserializer below. However, if I add another line:

images.zip@/Andorra.png	1
images.zip@/Barbados.png	0
images.zip@/Italy.png	1
images.zip@/Andorra.png	1

Then I get: 

  EXCEPTION occurred: Could not find file images.zip@/Andorra.png in the zip file, sequence id = 0

Here's my deserializer:
deserializers = (
            {
                type = "ImageDeserializer" ; module = "ImageReader"
                file = "$ConfigDir$/train.config"
                input = {
                    features0 = { transforms = (
                        { type = "Crop" ; cropType = "random" ; cropRatio = 0.8 ; jitterType = "uniRatio" } :
                        { type = "Scale" ; width = 256 ; height = 256 ; channels = 3 ; interpolations = "linear" } :
                        { type = "Transpose" }
                    )}
                    labels = { labelDim = 2 }
                }
            })

The only workaround I've found is to create different named copies of the images I need repeated.

Thanks,
dragomir

**Comment by avader906** [comment]
You can try to have a second deserializer so as to assign same images to different variables/nodes.

**Comment by eldakms** [comment]
Hi Dragomir,

Is this on Linux or Windows? Thanks!

**Comment by eldakms** [comment]
Should be fixed on the latest master (commit c934772aa1a5fd7248a2c4cac029a0d9cf7b47b9). Unfortunately, I was not on time, so the fix is not part of just released beta 11. It will be included in beta 12.

For now, please pull/rebuild from master. I am closing now, feel free to reopen if something is wrong.
Thank you for reporting this and sorry for the trouble.

**Comment by DragomirYankov** [comment]
Thanks for the quick fix! 

The problem was happening both on my Windows machine and on the philly cluster with the zip on hdfs.
