### ISSUE TITLE
MaxUnpooling not working for 07_Deconvolution_PY.py example

### ISSUE THREAD

**Issue by clintjcampbell** [Microsoft/CNTK#1422]
I am trying to run the example and can't get MaxUnpooling to be identified.  When I look at the file "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Lib\site-packages\cntk\layers.py", it clearly has MaxUnpooling.   I have CNTK 2.0.beta.10.0 installed from binaries

Any help would be great as I would like to figure out how to set up a deconvolutional autoencoder

 
Traceback (most recent call last):
  File "C:\local\cntk\Examples\Image\GettingStarted\07_Deconvolution_PY.py", line 134, in <module>
    deconv_mnist()
  File "C:\local\cntk\Examples\Image\GettingStarted\07_Deconvolution_PY.py", line 42, in deconv_mnist
    unpool1 = cntk.layers.MaxUnpooling ((4,4), (4,4))(pool1, conv1)
AttributeError: module 'cntk.layers' has no attribute 'MaxUnpooling'

**Comment by cha-zhang** [comment]
I tested on my installation and it works without an issue. Maybe consider reinstall CNTK?
