### ISSUE TITLE
Is "lapacke" really needed? 

### ISSUE THREAD

**Issue by deepim** [Microsoft/CNTK#1424]
Hi
I'm compiling CNTK-2.0.beta10.0 on linux now, and openblas is used instead of intel MKL. and found that lapacke.h is used in CPUMatrix.cpp. This introduces the dependency of lapacke and netlib's lapack. Not sure if this exists in previous release or not. but just wondering: 
1, is it possible to remove dependency of lapacke? using openblas only? 
2, if not, may be good to add notes in the doc. 

Kenneth

**Comment by mahilleb-msft** [comment]
Hi @lancerkz, as far as I can recall, you still need to have the header, however, the actual library / run-time dependency can from OpenBLAS, if you make sure to compile it with LAPACK LAPACKE. This should be automatically done when a Fortran compiler (e.g., gfortran) is present. Take a look at https://github.com/Microsoft/CNTK/blob/master/Tools/docker/CNTK-CPUOnly-Image/Dockerfile, where we also check for OpenBlas being configured as expected.

Hope that helps, Mark

**Comment by lancerkz** [comment]
Hi @mahilleb-msft 
I meant to get rid of LAPACKE otherwise, as you mentioned, gfortran is needed. Anyway, I got your idea. I can compile LAPACKE. and with some tricks I did in compiling I can compile CNTK too. not sure if I missed something. Here are my tricks.
1, I added '-fPIC' in LAPACKE makefile to avoid link errors from cntk. 
2, I explicitly added 'lapacke' in following part in CNTK makefile.


    ifeq ("$(MATHLIB)","openblas")
        INCLUDEPATH += $(OPENBLAS_PATH)/include
        LIBPATH += $(OPENBLAS_PATH)/lib
        LIBS_LIST += openblas m pthread lapacke
        CPPFLAGS += -DUSE_OPENBLAS
    endif

**Comment by mahilleb-msft** [comment]
Ok, good that that works for you. Alternatively, if you recompile OpenBlas now that you've got gfortran, I don't think you need to link to lapacke specifically, the OpenBlas library would include it.

Best, Mark

**Comment by lancerkz** [comment]
Hi Mark
thanks for quick response. 
it could be the reason. I remember that I installed gfortran after first link error. and use liblapacke.a directly afterwards. I was not aware that lapacke would be included in libopenblas if gfortran is installed. 

Kenneth
