### ISSUE TITLE
dev install issues on windows

### ISSUE THREAD

**Issue by szhaomsft** [Microsoft/CNTK#1425]
it fails in zlib source install steps 

Performing install operations
Installing zlib / libzip from source
Exception caught - function main / failure
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is
 null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProces
s)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by szhaomsft** [comment]
i have git installed.   

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Application     git.exe
Application     git.exe

**Comment by szhaomsft** [comment]
DEBUG:  560+      >>>> Write-Verbose "start-process [$command] with [$param]"
DEBUG:  562+     if ( >>>> -not $DoExecute) {
DEBUG:  567+     if ( >>>> -not $workingDir) {
DEBUG:  568+          >>>> $workingDir = $(get-location).Path
DEBUG:  568+         $workingDir = $( >>>> get-location).Path
DEBUG:     ! SET $workingDir = 'D:\szhao\CNTK\Tools\devInstall\Windows'.
DEBUG:  570+     if ( >>>> $requiresRunAs) {
DEBUG:  575+          >>>> $process = start-process -FilePath $command
-ArgumentList $param -Wait -PassThru -WorkingDirectory $workingDir
DEBUG:     ! SET $foreach = 'IEnumerator'.
DEBUG:     ! SET $foreach = ''.
DEBUG:  169+          >>>> Write-Host "Exception caught - function main /
failure"
Exception caught - function main / failure
DEBUG:  170+          >>>> Write-Host ($Error[0]).Exception
System.Management.Automation.RuntimeException: Cannot convert value to type Syst
em.String. ---> System.Management.Automation.PSInvalidCastException: Cannot conv
ert value to type System.String. ---> System.InvalidOperationException: Process
has exited, so the requested information is not available.

**Comment by szhaomsft** [comment]
what is the good way to debug it?

**Comment by wolfma61** [comment]
I don't understand your output output from the get-command operation.
Here is what this gives on my machine from powershell:
C:\repos\CNTK > get-command git.exe -CommandType Application

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.11.0.1   C:\Program Files\Git\cmd\git.exe


I would expect something similar from your machine.
From the exception I believe the problem is in the path to git ... but hard to tell

running the devinstall powershell script with the addition parameter -verbose should give you lot of additional output which might help

**Comment by wolfma61** [comment]
ok - markdown is screwing up the output ... here again the output from my get-command operation:
```
C:\repos\CNTK [wolfma/py ≡ +3 ~0 -0 !]> get-command git.exe -CommandType Application

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.11.0.1   C:\Program Files\Git\cmd\git.exe

```

**Comment by wolfma61** [comment]
@szhaomsft - thank you, we found a problem in the installer and there is a fix pending, hopefully this will address your issue ...
