### ISSUE TITLE
cntk: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Abimahesh** [Microsoft/CNTK#1426]
While running A2_RunCntk.py in linux machine, it shows this error. Can anyone please help me to solve this. Thanks in advance

**Comment by spandantiwari** [comment]
Looks like you are missing the OpenMPI binaries. Please make sure that you have OpenMPI installed. See [Setup on Linux](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Linux) page on how to install that. You can also use ```ldd``` to see missing dependencies.
