### ISSUE TITLE
AutoAdjust learning rate in python

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1430]
Hi

As @cha-zhang advised at #1372, I start to migrate to CNTK python API, but there are some inconvenience. The biggest one is that I couldn't find some brain script equivalents in python API. Lots of people use auto adjust learning rate as follow:

```
AutoAdjust = [
            autoAdjustLR = "adjustAfterEpoch"
            reduceLearnRateIfImproveLessThan = 0.001
            learnRateDecreaseFactor = 0.5
            # continueReduce = false
            continueReduce = true
            increaseLearnRateIfImproveMoreThan = 1000000000
            learnRateIncreaseFactor = 1.382
]
```

What is the equivalent for this BS code in python API?

**Comment by eldakms** [comment]
Hi hajix,

Currently this is not yet available in python. This will be implemented in the future, but no ETA as of yet unfortunately.
Thanks.

**Comment by hajix** [comment]
than you @eldakms.
