### ISSUE TITLE
c++ Eval language

### ISSUE THREAD

**Issue by andreyiva111** [Microsoft/CNTK#1432]
Hi. I try to use eval c++, but i have a error.
When i create model ( (*model).CreateNetwork(networkConfiguration); ) 
my networkConfiguration = "modelPath=\"" + n + "\"";
where n = "ConvNet_MNIST";
But here i got not this path
    virtual void CreateNetwork(const std::string& networkDescription) override
    {
        CNTKEvalBase<ElemType>::CreateNetwork(networkDescription);
    }
here networkDescription is trash
![Uploading error.png…]()

os - windows 7, system language - EN
Thank you!

**Comment by andreyiva111** [comment]
![error](https://cloud.githubusercontent.com/assets/22227545/22822310/ff8fbfbc-ef8f-11e6-9b38-e2534a70911d.png)

**Comment by andreyiva111** [comment]
![error](https://cloud.githubusercontent.com/assets/22227545/22822403/6b000662-ef90-11e6-8067-9cfa34f06b8b.png)

**Comment by andreyiva111** [comment]
![error](https://cloud.githubusercontent.com/assets/22227545/22823752/0ca6d13a-ef96-11e6-8ef6-f7395d0f813d.png)

**Comment by andreyiva111** [comment]
if solution cobfig. is debug, i have this error, but if solution config. id release all is work

**Comment by zhouwangzw** [comment]
@andreyiva111  yes, that is correct. For C++ library, you need to build debug vs debug, release vs release. The binary download package is the release one.

**Comment by zhouwangzw** [comment]
I am closing this issue, and please feel free to re-open it if needed.
