### ISSUE TITLE
EvalDLL and CNTK evalutions gives different results

### ISSUE THREAD

**Issue by Henry-White** [Microsoft/CNTK#1434]
Model is pretty simple: float[100] -> In, float[1] -> Out 
I made LSTM BS net config:
`    model = Sequential (
      RecurrentLSTMLayer {$stateDim$, usePeepholes = true} : #first LSTM
      DenseLayer {$labelDim$, bias=false}                    # followed by an adaptor layer (from LSTN output size to the output or label size)
    )
`
I trained the NET with 43310 samples by CNTK.exe.
After that I've made some minor modification with CPPEvalClient example:
- added loading NET-model I'd trained before;
- took some In-vectors passed them through the NET;
- and I got different results.

For examples:
Vector-1: CNTK=0.883557, EvalDll=-2.377818; 
Vector-2: CNTK=4.016681, EvalDll=-5.014029;

I checked all the types conversion (string -> float) under Debug-mode. Everything is seems to be ok. I had checked everything I could, but for nothing. I don't know, may be it's a my bug, may be EvalDll or may be something wrong with RecurrentLSTMLayer. I'm stuck... 
If you would give any suggestions I would very appreciated. Thanks.

**Comment by zhouwangzw** [comment]
@Henry-White  I believe that you are using IEvaluateModel interface? It has only limited support for LSTM model. We now have new C++ LibraryAPI, which should fully support LSTM, and has more features. Would you mind to have a try? Please find details [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview). 

If for any reason you have to stay with EvalDLL interface, please try with IEvaluateModelExtended interface. You find examples in [CPPEvalExtendedClient](https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CPPEvalExtendedClient).

**Comment by Henry-White** [comment]
Hi,
Thank you very much for the answer. As you advised I have made my own example based on CNTKLibraryCPPEvalExamples.cpp with minor changes. But I have got the same problem as I mentioned before.
I use the same vector in both cases. It is looks like ""|In -0.0458129926700013 -0.0338955938326502 -0.0217283255977756... ".
Evalution by CNTK.exe=0.269296
Evalution by CNTKLibrary= -1.807741
I do preparation of input data by:
std::vector<float> inputData(inputVar.Shape().TotalSize());
inputData[i] = static_cast<float>(r[i]), where float r[100]
as it shows in CNTKLibraryCPPEvalExamples.
I put elements from left to right (r[0]=-0.0458129926700013... r[99]=the last one in the row).
And by the way, in the previous example CNTKLibrary gives the same result as EvalDll:
Vector-1: CNTK.exe=0.883557, EvalDll=-2.377818, CNTKLibrary=-2.377818;
Vector-2: CNTK.exe=4.016681, EvalDll=-5.014029, CNTKLibrary=-5.014029;
Thanks for reading this.

**Comment by Henry-White** [comment]
One more... When I do and evaluation of TEST-data, result is depend on order of input vectors. For example, a TEST data is a set  of 100 vectors. Results are:
Vector[1]=0.304701
....
Vector[100]=0.314906
Then I removed from the data set all vectors except 1-th and 100-th and the results are not the same, as they was in the first set of vectors:
Vector[1]=0.269296
Vector[100]=0.370505
Of course there are no train actions was done between these evaluations.
Is it normal?

**Comment by Henry-White** [comment]
latest update (27.02), CNTKLibraryAPI
Execution LSTM with model loaded (auto modelFuncPtr = CNTK::Function::LoadModel(modelFilePath, device);)
crashed on:
evalFunc->Forward({{inputVar, inputValue}}, outputs, device);
Model, config, source and output are included here:
[https://drive.google.com/open?id=0B9DUjrGF_JqreC1uaE1pS19IX1U](url)

**Comment by zhouwangzw** [comment]
Thanks for reporting the issue. I will take a look.

**Comment by zhouwangzw** [comment]
@Henry-White I looked into the code you have shared. It seems that there are some mistakes in your code when preparing data. 
`int rsize = -1;
      int n = 0;
     float r[100];
    while (sscanf(sa, "%*[^0-9]%f%n", r + rsize, &n)) {
         sa += n;
         rsize++;
   }`
For me, the `rsize` should be 0, otherwise the` r+rsize `in `sscanf` access to r[-1] which could corrupt the stack. And since your input `sa`, has more than 100 float numbers, indeed 119,  the size of the array ` r` should be at least 119 (if your input changes, the array size needs to be adapted. Would std::vector  be a better choice for r, instead of array?) 

With the following change
`	int rsize = 0;
	int n = 0;
	float r[119];`
, I can run your example without problem. 
![image](https://cloud.githubusercontent.com/assets/19703521/23452152/81cf2a6c-fe63-11e6-8fcb-aa2c8a433608.png)

**Comment by Henry-White** [comment]
Hello Zhou Wang,

Thank you very much for your attention. I'm really sorry for this stupid mistake. Shame on me. Probably it was a trash from previous version...
Fix it to: 'int rsize = 0; float r[120] = { 0 };'
Actually the vector has a fixed size (100), but anyway I still get the crash on executing. I will check all environment again. May be I miss something (I updated all libs a couple of days ago).

But even if we will forget about the crash, the results from different APIs are different.

CNTK = 0.362003 ( vector is the same as I use in the example "test70-3.dat" with config XR5_LSTM-70-test3.cntk. All included with result Out.z )
EvalDll = 0.085463
CNTKLibrary= 0.085463   ( according to your result... It gives the same result as EvalDll above.)

And I think this issue is much more important than the first one.

Anyway, thanks a lot for your job and help.

**Comment by Henry-White** [comment]
Please, I ask you to suspend this issue for a while... You are right. Something wrong with my data :(

**Comment by Henry-White** [comment]
No. False alarm. Exactly 100.

**Comment by Henry-White** [comment]
The "different result" is not the issue any more. The reason: I'm idiot (wrong regex). I'm very very Sorry fellows that you had spent your time for this.

CNTKLibrary still crashing but this is another story... Looking for a problem.

**Comment by zhouwangzw** [comment]
@Henry-White For CNTK C++ library, please use release against release library and debug against release library. The binary drop package contains only release build. Recently, we also publish C++ library as Nuget package: CNTK.GPU and CNTK.CPUOnly at Nuget.org. The Nuget package contains both debug and release build. The latest version is beta12.
