### ISSUE TITLE
Wrap CNTK Networks into Applications

### ISSUE THREAD

**Issue by NexYY** [Microsoft/CNTK#144]
I've gone through the documentation of Microsofts OpenSource AI Library CNTK and did understand how to create and train neural networks. I've also understood, how to "save" the trainied results into an output directory.

However, I don't see a way to load the results into the neural network and even more compicated: how to I wrap my trained neural network into an application, so I can actually use it productive instead of just using it for academic research.

I want to integrate my neural network into my Python or C# application. How do I wrap it into such, and how do I create a interface towards its input and output?

Thanks.

**Comment by wolfma61** [comment]
Hi -

Take a look at CSEvalClient, a C# wrapper to run model evaluation. this should get you going?

thx
Wolfgang

**Comment by NexYY** [comment]
Hi. Thanks.
I kinda missed that.
