### ISSUE TITLE
Can't determine how to print the value of a "true" label during evaluation (in Python)

### ISSUE THREAD

**Issue by mawah** [Microsoft/CNTK#1440]
I am evaluating the performance of a trained model on a validation dataset. I would like to print output for each image tested containing true and predicted labels, e.g.:
```
Predicted: 1, True: 2
```
This information will help me construct a confusion matrix for my trained model. The problem is that I can't seem to get the true labels out of the MiniBatch in a printable form.

My Python code so far looks like the following:
```
def create_reader(map_file):
    transforms = [ImageDeserializer.scale(width=image_width,
                                          height=image_height,
                                          channels=num_channels,
                                          interpolations='linear')]
    return MinibatchSource(ImageDeserializer(map_file, StreamDefs(
        features = StreamDef(field='image', transforms=transforms),
        labels   = StreamDef(field='label', shape=num_classes))))

test_reader = create_reader(map_file)
input_var = input_variable((num_channels, image_height, image_width))
label_var = input_variable((num_classes))
input_map = {input_var: test_reader['features'],
	     label_var: test_reader['labels']}

for _ in range(num_images):
    data = test_reader.next_minibatch(1, input_map=input_map)
    predicted_label = argsoftmax(my_model.eval({my_model.arguments[0]: data[input_var]}).flatten())
    true_label = data[label_var].data.data()
    print('Predicted: {}, True: {}'.format(predicted_label, true_label))
return
```
...but the output from that code looks like the following:
```
Predicted: 1, True: <cntk.cntk_py.NDArrayView: proxy of <Swig Object of type 'CNTK::NDArrayViewPtr *' at 0x.....> >
```
I saw that NDArrayViews have a method called `to_ndarray()`, but when I tried to use it , I got an error:
```
Traceback (most recent call last):
...
File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 585,
 in to_ndarray
    return _cntk_py.NDArrayView_to_ndarray(self)
ValueError: only dense supported at the moment
```
What is CNTK's recommended approach for printing a value obtained from a MiniBatchSource? Is there a doc where I can read more about this?

**Comment by fcivardi** [comment]
I'm trying  to do the same just now (building a confusion matrix out of a MiniBatch) and I'm facing the same problem. If you find a solution, please post it, I'll do the same if I find one!

**Comment by fcivardi** [comment]
I'm trying  to apply to my case the example in the notebook "CNTK 103: Part B - Feed Forward Network with MNIST" where at the end labels and predictions are shown.
There the label is:
    img_label = data[label_var].value
This is indeed a standard numpy array, but in my case it has no shape, I don't understand why:
    print(type(data[label_var].value)) -> <class 'numpy.ndarray'>
    print(data[label_var].value.shape) -> ()

**Comment by ebarsoumMS** [comment]
Will that work: "label  = np.asarray(data[label_var].value)" ? Then you can print out label.

**Comment by ebarsoumMS** [comment]
Actually the above won't work, because label is sparse. You can multiply it by an identity matrix to convert it to dense.

**Comment by fcivardi** [comment]
But why does it  work in MNIST?
The same statements, in the MINST example (without having to convert, they are already np.arrays)
img_label = data[label_var].value
img_data = data[input_var].value
print(img_label.shape)
print(img_data.shape)
RETURN:
(25, 1, 10)
(25, 1, 784)
in CIFAR:
 ()
 (25, 1, 3, 32, 32)
I don't get an error like mawah, I get an empty array for the labels.

**Comment by ebarsoumMS** [comment]
Because MNIST uses different datareader.

**Comment by fcivardi** [comment]
>You can multiply it by an identity matrix to convert it to dense.
How? np.dot(label, np.eye(dim?))  
could you please post an example?

**Comment by mawah** [comment]
@ebarsoumMS, just gave this a shot. Tried this first:
```
print(np.eye(num_classes).dot(data[label_input].value))
```
That failed with an error that float and Value cannot be multiplied. So I tried to define/multiply with an identity matrix using CNTK's proprietary functions:
```
from cntk.ops import parameter, times
eye = parameter(shape=(num_classes, num_classes), init=np.eye(num_classes))
print(times(data[label_input], eye))
```
No error message, but the program stalled indefinitely when trying to evaluate this snippet. What is CNTK's recommended method for this? (I hope I will only need it temporarily...from the error message, it sounds like  extending `to_ndarray()` for sparse matrices is already planned.)

@fcivardi, I don't have your code handy, but isn't an ndarray of shape `()` a scalar? Could you convert your zero-dimensional ndarray to a label with `float(image_data)` ?

**Comment by fcivardi** [comment]
**@mawah ,** here is my code, where I try to see what's inside img_label and img_data, for the whole Minibatch. I'd expect img_label to be an array, not  a scalar.
(how do you insert the code here? with cut and paste it looses indentation)

`reader_eval = create_reader(os.path.join(data_path, 'test_map.txt'),os.path.join(data_path, 'CIFAR-10_mean.xml'), False)

eval_minibatch_size = 25
input_var = input_variable((num_channels, image_height, image_width))
label_var = input_variable((num_classes))

input_map = {
    input_var: reader_test.streams.features,
    label_var: reader_test.streams.labels
}

data = reader_test.next_minibatch(eval_minibatch_size, input_map = input_map)

img_data = data[input_var].value
img_label = data[label_var].value

print(img_label.shape)
print(img_data.shape)`

**Comment by fcivardi** [comment]
If I just
print(img_label), I get:
<cntk.cntk_py.Value; proxy of <Swig Object of type 'CNTK::ValuePtr *' at 0x000000235497D750> >
(while print(img_data) returns the array of images).

**Comment by fcivardi** [comment]
No way then to build a confusion matrix or, even better,  a ROC curve, evaluating all of the images in a minibatch in one shot? Should we then loop through every test image, and eval it, like in the Tutorial CNTK_201B_CIFAR-10_ImageHandsOn (where it has been done for just a single image)?

**Comment by mawah** [comment]
@fcivardi, if you do this, watch closely for differences in axis order and numbering. I noticed that I had to reverse the RGB channel order (as in, BGR) to use my trained model, as did the author of the `eval_single_image()` function in the [Transfer Learning example](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py). Evidently the RGB reversal wasn't done in the [CIFAR-10 tutorial](https://github.com/Microsoft/CNTK/blob/v2.0.beta11.0/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb) you mentioned. Wonder what the difference is?

**Comment by fcivardi** [comment]
I did it, and I got wrong results even in the training set. But my images are grayscale, I've found here on github similar issues with the same problem, the answer was to set grayscale to True in the reader. In python I tried datareader['grayscale']=True, but nothing changes. My binary classifier always gives the same response, class1 probability always around 0.

**Comment by pkranen** [comment]
Closing this one since there has not been an update since long. Please open a new issue if Problems remain with the latest bits. Thanks.
