### ISSUE TITLE
Evaluation on the training set in the Tutorial "CNTK 201B: Hands On Labs Image Recognition"

### ISSUE THREAD

**Issue by fcivardi** [Microsoft/CNTK#1442]
In the tutorial "CNTK 201B: Hands On Labs Image Recognition", before the evaluation:
data = reader_test.next_minibatch(current_minibatch, input_map=input_map)
the input.map has been not redefined to the reader_test, it is still:
    input_map = {
         input_var: reader_train.streams.features,
          label_var: reader_train.streams.labels
    }

I think it should be redefined  as: (or we should define a new test_input_map)
    input_map = {
           input_var: reader_test.streams.features,
           label_var: reader_test.streams.labels
    }

In the MNIST tutorial there is indeed a  test_input_map

**Comment by ebarsoumMS** [comment]
This mapping just map the column id to the variable which is the same for both training and test data. So the result wouldn't be affect. However, you are right we should use reader_test mapping, when we use reader_test.
