### ISSUE TITLE
How can I append data to MinibatchSource?

### ISSUE THREAD

**Issue by taeguk** [Microsoft/CNTK#1445]
https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L4230
Is there no way to append data to MinibatchSource??

I can't find the way.
If I create new MinibatchSource to append data, it is very inefficient.
I want that MinibatchSource can be "initialized" after creation and I can append data to MinibatchSource whose status is "initialized".

**Comment by eldakms** [comment]
You need to implement your own minibatch source. Or you can also implement your own DataDeserializer. Have a look at the Source/Readers/ReaderLib/DataDeserializer.h

For a sample how data deserializer can be implemented - have a look i.e. at ImageReader/ImageDeserialzier.h or ImageReader/Base64ImageDeserializer
