### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1446]
I encounter the following error when running cntk:

`cntk: symbol lookup error: cntk: undefined symbol: _ZNK9Microsoft3MSR4CNTK6MatrixIfE8GetIndexEv`

What is the problem?

**Comment by wilrich-msft** [comment]
You can unmangle the symbol as follows:
```
c:\>c++filt _ZNK9Microsoft3MSR4CNTK6MatrixIfE8GetIndexEv

Microsoft::MSR::CNTK::Matrix<float>::GetIndex() const
```
So it seems something went wrong in your compilation/linking process. Can you share more on how you installed CNTK and where this error occurred?

**Comment by yttdebaba2** [comment]
The problem is solved. CNTK v2 Python support needs to be installed.
