### ISSUE TITLE
CNTK Library Eval C++ in Visual Studio 2010 

### ISSUE THREAD

**Issue by andreyiva111** [Microsoft/CNTK#1447]
Hi!
Can i use CNTK Library Eval C++ in Visual Studio 2010 ?
When I try to do it, i have many errors.
![vs10](https://cloud.githubusercontent.com/assets/22227545/22877200/51fa4450-f1e5-11e6-8255-3b62f99b9ac7.png)
If i change Platform Toolset, all work.

**Comment by andreyiva111** [comment]
And one more question.
Can i create Library width CNTK Library Eval in Visual Studio 2015, and use this Library in Visual Studio 2010? (have error - "error c1007 unrecognized flag '-fitobjdata' in 'p2' ")
Thank you!

**Comment by zhouwangzw** [comment]
@andreyiva111 We have not tested whether CNTK could work with VS2010. If you want to stay with VS2010, I think the best way is to rebuild CNTK Eval related source and its dependencies in VS2010. You might have problems if you build Eval Library in VS2015 and use it in VS2010.

**Comment by andreyiva111** [comment]
OK, Thank you very much
