### ISSUE TITLE
Feature request: NumPy Reader

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#1449]
Hi,
I have a large collection of NumPy arrays saved on disk. I would like to read them efficiently and concurrently with the training. I can't load them all into memory at once - the data set is too large.
Also, it would be nice to apply some user defined transforms on the fly.

Slawek

**Comment by cha-zhang** [comment]
Please refer to: 
https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_feed_data.ipynb 
or: 
https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_create_user_minibatch_sources.ipynb

I'm closing this issue now. Feel free to open a new issue if needed.
