### ISSUE TITLE
How to resume training using previously trained model

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1452]
I accidentally interrupt the training, and have files named `xxx.7` and `xxx.7.ckp`.
How can I resume training using these two files?
Is there a simple command line to do this? Or do I need to change the CNTK BrainScript? (`modelPath = $WorkDir$/xxx`)

**Comment by junjieqian** [comment]
The wiki page describes how to continue training from a previously saved model, https://github.com/Microsoft/CNTK/wiki/Continue-training-from-a-previously-saved%20model.
