### ISSUE TITLE
Having difficulty understanding the output of CNTKLibraryCSEvalExample

### ISSUE THREAD

**Issue by Spiderixius** [Microsoft/CNTK#1453]
Hello, I have a difficulty understanding the output I get that I get from CNTKLibraryCSEvalExample. As seen in the image below there are 10 elements for each sample, but do not really understand what output means.

![image](https://cloud.githubusercontent.com/assets/10165995/22920682/a41f5444-f296-11e6-90c6-28a0a518b618.png)

Below is the source code, I make use f the EvaluationBatchOfImages method
Source code at: https://gist.github.com/Spiderixius/4f16f3b50ff325e87b6bbcba890b355e

Any help would be appreciated :)

**Comment by Spiderixius** [comment]
I have found out that the values help with classifying the test image into the objects from the model (boat, ship, cat and so on). I don't know what values (numbers) means exactly, but could we get the values as percentage.

**Comment by zhouwangzw** [comment]
The output of evaluation, e.g. dimension size and its semantic meaning, is defined by the model being evaluated. It seems that you are using the Classification\\ConvNet\\BrainScript\\Output\\Models\\ConvNet_CIFAR10 model for evaluation. Is this trained with the configuration in examples or with your own configuration? In examples, the model output is `LinearLayer {labelDim} `. If you want to have the value as percentage, either you need to change and retain the model, or you can have some post processing after evaluation.

**Comment by Spiderixius** [comment]
@zhouwangzw I am kind of a newb, but I am using the `const string outputName = "z";` which is I believe the configuration from the example. But eitherway I have not touched the configuration, so I assume it is just the default configuration.

**Comment by pkranen** [comment]
Hi Spiderixius, the output values that you get still have to be pushed through a Softmax to transform them to probabilities. You can see an example in the Python API [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py#L160), Softmax is available in BrainScript, too, see [here](https://github.com/Microsoft/CNTK/wiki/Activation-Functions). You can also easily softmax the values yourself, the [formula](https://en.wikipedia.org/wiki/Softmax_function) is simply:

```
p_j = e^(z_j) / \sum_k e^(z_k) 
```

where `p_j` is the resulting probability for class `j` and `z` is your output vector. Closing the issue, feel free to reopen.

**Comment by Spiderixius** [comment]
Ok thanks @pkranen I will check it out.
