### ISSUE TITLE
Reader/Inputs

### ISSUE THREAD

**Issue by mg64ve** [Microsoft/CNTK#1457]
Hi all,

consider the following example from the documentation:

```
precision="double"
reader = [
    readerType = "CNTKTextFormatReader" 
    file = "/home/mydata/SampleInput.txt" # See the first example for Windows style path example
    randomize = true
    randomizationWindow = 30
    skipSequenceIds = false
    maxErrors = 100
    traceLevel = 2
    chunkSizeInBytes = 1024
    keepDataInMemory = true
    frameMode = false
    input = [
        Some_very_long_input_name = [
            alias = "a"
            dim = 3 
            format = "dense"
        ]
        Some_other_also_very_long_input_name = [
            alias = "b"
            dim = 2 
            format = "dense"
        ]
    ]
]

```

Is it correct to use the following?

`inputs=Input{(3:2)}`

I am getting some errors.
Thanks.
Cheers.

**Comment by eldakms** [comment]
No, this correspond to two different inputs with dimension 3 and 2. Each input in the deserializer => an input node in the network.:
    some_very_long_input_name = Input(3)
    some_other_also_very_long_input_name = Input(2)

If you need to splice the data - you need to do that in the network (using the above two inputs):
Splice(some_very_long_input_name, some_other_also_very_long_input_name, ...)
