### ISSUE TITLE
Memory issue with c++ evaluation

### ISSUE THREAD

**Issue by julienlopez** [Microsoft/CNTK#1458]
Hi, I'm currently trying to use a model I trained successfully with the C++ library.
So I developed a little tool to compare all my trained model in C++, but I'm recently having issues with CUDA running out of memory after a good number of evaluations, so I'm assuming I'm doing something wrong (I also upgraded CNTK recently, maybe something changed).

After loading a model with CNTK::Function::LoadModel, I run the evaluation with the following code:

    std::vector<ElemType> forward(std::vector<ElemType> inputs)
    {
      assert(inputs.size() % (c_image_size * c_image_size) == 0);
      const std::size_t number_of_samples = inputs.size() / (c_image_size * c_image_size);
  
      std::vector<ElemType> res(2 * (inputs.size() / 1600));
  
      CNTK::NDShape inputShape = m_input.Shape().AppendShape({1, number_of_samples});
      CNTK::ValuePtr inputValue = CNTK::MakeSharedObject<CNTK::Value>(
          CNTK::MakeSharedObject<CNTK::NDArrayView>(inputShape, inputs, true));

      CNTK::ValuePtr outputValue;
      std::unordered_map<CNTK::Variable, CNTK::ValuePtr> outputs = {{m_output, outputValue}};
      m_model->Evaluate({{m_input, inputValue}}, outputs, m_device);
  
      outputValue = outputs[m_output];
      CNTK::NDShape outputShape = m_output.Shape().AppendShape({1, number_of_samples});
      std::vector<float> outputData(outputShape.TotalSize());
      CNTK::NDArrayViewPtr cpuArrayOutput
          = CNTK::MakeSharedObject<CNTK::NDArrayView>(outputShape, outputData, false);
      cpuArrayOutput->CopyFrom(*outputValue->Data());
      return outputData;
    }

Is there any obvious issue in this code I'm missing?

I can get rid of the issue by reducing the number of samples I provide for each forward pass, but since I'm running the same dataset on different iterations of the same model, if it works for one it should work for all of them, unless there's a memory leak somewhere.

On an unrelated note, while most of the examples use the CNTK::Function::Forward function, the saw in the header the CNTK::Function::Evaluate function which seems to be more efficient, so which one should I use?

**Comment by zhouwangzw** [comment]
@julienlopez The code looks fine. What is the number of samples (and the size of each sample) when you get the out of memory exception? The model size, e.g. number of parameters, and the GPU memory budget are also related. You can use nvidia-smi.exe to check GPU memory usage.

Regarding Forward vs. Evaluate: they are basically the same, Evaluate() calls Forward. :-).

**Comment by julienlopez** [comment]
First of all, the network:
It takes 1600 inputs (40x40 greyscale image) and outputs 2 classes (while training, I found a line giving me 848674 parameters
Here's the structure:

        BrainScriptNetworkBuilder = {
          imageShape = 40:40:1 # image dimensions, 1 channel only
          labelDim = 2
          featScale = 1/65536 # (2^16)
          Scale{f} = x => Constant(f) .* x
		
        bnTimeConst = 4096

        # define a custom layer with 3x3 convolution, batch norm, relu and 2x2 mean pooling
        ResConvBnReluPoolLayer {outChannels} = Sequential (
			ResNetBasic {outChannels, bnTimeConst} :
			MaxPoolingLayer {(2:2), stride = (2:2)} 
        )
        
        model = Sequential (
            Scale {featScale} :
            ResConvBnReluPoolLayer     {32} :
            ResConvBnReluPoolLayer     {32} :
            LinearLayer             {256} :
            BatchNormalizationLayer {} :
            ReLU :
            LinearLayer             {labelDim}
        )

Now for my tests, my program puts all the iterations produced while training (of this exact network) through a test of 38680 values, by batches of at most 100 samples (meaning the above forward function is never called with more than 1600*100 values).
If it were an issue with batch size, it should be the same for all iterations of the model right?

**Comment by julienlopez** [comment]
It seems pretty pretty reproducible though:
If I trained the above network for 60 epochs with CNTK.exe, and run my program on all the iterations produced (starting by the last one), it always seems to produce the error on the 14th iteration of the model, on the first call to forward (so with 100 samples).

I'm retraining it again as I'm writing to see if I can spot something going on during the 14th epoch of training.

**Comment by zhouwangzw** [comment]
Which CNTK version are you using? In the latest Beta 11, there are some new APIs which directly create input Value from input data, and after evaluation copy data from the output Value into output vector. 
For example, to create a Value for a batch input in the dense format: 
template <typename ElementType>
        CNTK_API static ValuePtr CreateBatch(const NDShape& sampleShape, const std::vector<ElementType>& batchData, const DeviceDescriptor& device, bool readOnly = false);
 
and get evaluation result from the output Value: 
template <typename ElementType>
        void CopyVariableValueTo(const Variable& outputVariable, std::vector<std::vector<ElementType>>& sequences)

You can find details in the [CNTKLibrary.h](https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h)

Could you please have a try?

Thanks,

**Comment by julienlopez** [comment]
I'm using CNTK straight from git right now, but I could try with the release beta11...

Here's what I tried following your suggestions (let me know if I made any mistakes), but it doesn't solve the problem:

	std::vector<std::vector<ElemType>> forward(std::vector<ElemType> inputs)
	{
		assert(inputs.size() % (c_image_size * c_image_size) == 0);
		const std::size_t number_of_samples = inputs.size() / (c_image_size * c_image_size);
		CNTK::ValuePtr inputValue = CNTK::Value::CreateBatch(m_input.Shape(), inputs, m_device, true));
		
		CNTK::ValuePtr outputValue;
		std::unordered_map<CNTK::Variable, CNTK::ValuePtr> outputs = {{m_output, outputValue}};
		m_model->Evaluate({{m_input, inputValue}}, outputs, m_device);
		
		outputValue = outputs[m_output];
            std::vector<std::vector<ElemType>> res;
		outputValue->CopyVariableValueTo(m_output, res);
		assert(res.size() == number_of_samples);
		return res;
	}

**Comment by zhouwangzw** [comment]
@julienlopez The git master has the latest code, and I did not spot any issue in the code. Would it be possible to share a repo for our investigation?

**Comment by julienlopez** [comment]
Sent you an invite to a private repo with the minimal stuff needed to reproduce the issue, let me know if you need anything.
In the mean time, I will try the same with the beta11 release

**Comment by julienlopez** [comment]
Hmmm, maybe there's something wrong with my machine, I tried to use the latest release but I can't get anything working, either my test program or CNTK.exe hangs just after starting and doesn't seem to do anything. Any idea what may cause this? I updated my nvidia drivers but it doesn't solve the issue.

**Comment by raaaar** [comment]
There was an issue (a reference cycle), which caused stale composite functions (i.e., models) to never be destroyed and linger around for pretty much ever or until an OOM. This has been fixed on master, so if you pull (or wait for the next beta), you shouldn't see memory issues any more.

**Comment by julienlopez** [comment]
Awesome, thanks a lot, I'm working with master for now so I'll just pull it, thank you.
