### ISSUE TITLE
Object Detection and draw bounding box around object

### ISSUE THREAD

**Issue by mrahmanWM** [Microsoft/CNTK#146]
Hi,

Let's say the training dataset I have has two classes: traffic sign (traffic sing covered the whole image) and background (no traffic sign). The test dataset contains large images with more than one traffic sign in every image. My goal is to detect those traffic signs from the test images and draw bounding boxes around those. I also want to know the coordinates of the detected traffic sign and  measure precision, recall and overlap percentage. I read the Alexnet configuration file and from there I understand what to do to read images. But unfortunately I did not find the configuration to output images with bounding boxes and also the coordinates, precision, recall etc. Any help? Please.

**Comment by mrahmanWM** [comment]
Hi,

I still could not figure it out? So, any idea about how can I get those things? Only coordinates will work.  Please.

**Comment by Alexey-Kamenev** [comment]
Hello,
We currently does not support such functionality. However, having something like R-CNN (its faster version, to be precise) is in our plans.

**Comment by Piso** [comment]
Any hopes in seeing faster-rcnn supported any time soon?

**Comment by n17s** [comment]
Yes it should arrive soon. All our development is public and you can easily search for branches that contain rcnn via the web interface.

**Comment by PatrickBue** [comment]
Fyi, Fast R-CNN is now part of CNTK:
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN

**Comment by mrahmanWM** [comment]
Excellent.

**Comment by mrahmanWM** [comment]
Excellent.

**Comment by AndreaPisoni** [comment]
Great to have fast-rcnn!

I might be pushing it a bit, but are there plans to get to the _faster_ rcnn as well? :)

**Comment by pkranen** [comment]
Yes, please stay tuned. Thanks for your interest!

**Comment by AndreaPisoni** [comment]
Awesome! 

I also found this on the docs:

```Other items for future work include:

Evaluating alternatives to the currently used selective search implementation.
Adding bounding box regression.
Implementation of faster R-CNN, i.e. performing ROI generation inside the DNN.
Using a more recent DNN topology such as ResNet instead of AlexNet.```

This is amazing!

**Comment by harish-geeky** [comment]
Try Playment.in.
