### ISSUE TITLE
How to reduce over all sequences

### ISSUE THREAD

**Issue by omiranda93** [Microsoft/CNTK#1460]
I found the following text on reducing sequences:
"Reducing over sequences
[...] Instead, you can achieve this with a recurrence. For example, to sum up all elements of a sequence x, you can say: sum = x + PastValue (0, sum, defaultHiddenActivation=0)" 

However, this does not solve the problem of reducing all sequences. How can I solve this problem in Python.

I have been trying this on my own, by using this sum function over its own result, in order to reduce all sequences, but it seems you are not jet giving support to this functionality. Am I correct?.

**Comment by Ark-kun** [comment]
You can use the the functions from cntk.ops.sequence.* to reduce the sequences https://cntk.ai/pythondocs/cntk.ops.sequence.html?highlight=reduce_sum#cntk.ops.sequence.reduce_sum

`cntk.ops.reduce_sum` can be used to reduce across the batch axis: https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=reduce#cntk.ops.reduce_sum

**Comment by n17s** [comment]
@Ark-kun is right. I'm closing the thread. Feel free to reopen.
