### ISSUE TITLE
cntk with nccl doesn't work with more than 9 GPUs

### ISSUE THREAD

**Issue by DemjanGrubic** [Microsoft/CNTK#1462]
Hi,

I have a problem when I run cntk with nccl with more then 9 instances nccl can't initialize, it just waits for init I guess, with no error.
When I use less than 10 instances, everything is fine.

Also, when I build without nccl everything runs normal.

I am using latest build, it doesn't matter if I use docker or not.
The machine contains 16 GPUs Nvidia Tesla K80.

Output is normal until the point when it should output "NcclComm: initialized" for the first time.

**Comment by junjieqian** [comment]
@nluehr , do you have any suggestions on this issue?

**Comment by nluehr** [comment]
I'll try to reproduce. @DemjanGrubic What is the NVIDIA driver version on the system?

**Comment by DemjanGrubic** [comment]
I think I have tried this on 2 NVIDIA driver versions, first one is 367.57, and second one is 375.20.

**Comment by nluehr** [comment]
Thanks. I am able to reproduce the hang. CUDA supports peer direct access to a maximum of 8 peer devices. When there are more than 9 GPUs attached to a single socket, this limit is exceeded. There appears to be a bug in NCCL's error-out path that results in the observed deadlock. I'll put a fix through in NCCL.

**Comment by DemjanGrubic** [comment]
@nluehr, Strange, I believe I was able to run it no 9 GPUs :)
Thanks for the help.
I guess we should leave this issue open until NCCL is fixed?

**Comment by nluehr** [comment]
@DemjanGrubic, NCCL master branch has been patched as of NVidia/nccl@899681193.
Let me know if you continue to see problems.

**Comment by DemjanGrubic** [comment]
I am not able currently to test this, but I will close this issue.
When I try again and if the problem persist, I will reopen this issue.
Thanks for your help.
