### ISSUE TITLE
speech example in python

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1463]
Hi

In the Examples/Speech directory, there is no speech example which is written in python!! While CNTK was started with speech examples, currently all speech examples are outdated. There is an abandoned example at Examples/Speech/Miscellaneous, named EndToEnd.py, but it has no changes from 3 month ago (actually the date which is created)!!

If CNTK team decided to migrate to python interface and NDL is depreciated (which it seems, as noted in #1372), so there is a big gap for a speech example in python.

regards

**Comment by cha-zhang** [comment]
We will have one speech example in beta 12, and more in preparation. Thanks!
