### ISSUE TITLE
CNTK Update Error

### ISSUE THREAD

**Issue by epslong** [Microsoft/CNTK#1465]
As I follow the direction on https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Manual to update my existing CNTK-py34 environment. Following the error message, I'm posting it here:

![image](https://cloud.githubusercontent.com/assets/11820260/23008782/e6a18a52-f409-11e6-838e-e1e1de909e00.png)

**Comment by spandantiwari** [comment]
Not sure what's going on here. Could you please follow the steps in [Setup CNTK for Python on Windows](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python) and report back if you have any errors.
