### ISSUE TITLE
Unclear of 'Continue training from a previously saved model'

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1466]
What does 'point your continued training to that folder.' mean in https://github.com/Microsoft/CNTK/wiki/Continue-training-from-a-previously-saved%20model

Suppose I have `modelPath = $WorkDir$/xxx` and two files `xxx.7` and `xxx.7.ckp`, and I moved these two files to a new work directory.

Do I need to set `modelPath = $NewWorkDir$/xxx.7`, or I need to set `modelPath = $NewWorkDir$/xxx` and rename the two files as `xxx.0` and `xxx.0.ckp`?

**Comment by cha-zhang** [comment]
No need to rename. Just move the files into the new folder should work.

**Comment by yttdebaba2** [comment]
thank you very much.
