### ISSUE TITLE
Beta11 cannot use Image Reader to write result anymore...

### ISSUE THREAD

**Issue by AllanYiin** [Microsoft/CNTK#1470]
After upgrade to beta 11, I found I cannot write result by image reader anymore (beta10 is ok), I try to reduce to minimabatch size and even use CPU mode,  still not work. ther is the eventlog recore by my computer (win 10 ,surfacebook)

失敗的應用程式名稱: CNTK.exe，版本: 0.0.0.0，時間戳記: 0x589da521
失敗的模組名稱: CompositeDataReader.dll，版本: 0.0.0.0，時間戳記: 0x589da333
例外狀況代碼: 0xc0000005
錯誤位移: 0x000000000002cbbe
失敗的處理程序識別碼: 0x42e0
失敗的應用程式開始時間: 0x01d2882f40084df6
失敗的應用程式路徑: C:\local\cntk\cntk\CNTK.exe
失敗的模組路徑: C:\local\cntk\cntk\CompositeDataReader.dll
報告識別碼: 8fe69981-0b05-4084-975a-c4d719369cbd
失敗的套件完整名稱: 
失敗的套件相關應用程式識別碼: 

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-02-16T08:34:19.946807400Z" /> 
  <EventRecordID>11777</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Allan-Surface</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>CNTK.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>589da521</Data> 
  <Data>CompositeDataReader.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>589da333</Data> 
  <Data>c0000005</Data> 
  <Data>000000000002cbd9</Data> 
  <Data>2b08</Data> 
  <Data>01d2882f6c161478</Data> 
  <Data>C:\local\cntk\cntk\CNTK.exe</Data> 
  <Data>C:\local\cntk\cntk\CompositeDataReader.dll</Data> 
  <Data>b7a5ba13-0d78-4144-9849-3de81bf42325</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by cha-zhang** [comment]
Are you using BrainScript or Python? Do you have a repo we can test on? Thanks!

**Comment by spandantiwari** [comment]
Please reopen if you are still seeing this issue.
