### ISSUE TITLE
How to look at intermediate outputs (node outputs) of a trained network in Python API

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#1471]
I wonder how I can look at a node output in a (trained) network when using Python API.
I'm a beginner in CNTK. I can't find any appropriate example for it. Please recommend useful materials.

**Comment by cha-zhang** [comment]
Check the example on feature extraction:  https://github.com/Microsoft/CNTK/tree/master/Examples/Image/FeatureExtraction

**Comment by 2wins** [comment]
@cha-zhang Thank you for your quick reply. By the way, I think it would be nice if there was a community for simple Q&A.
