### ISSUE TITLE
Microsoft.Cpp.Default.props not found.I use VS2017...

### ISSUE THREAD

**Issue by HeMinzhang** [Microsoft/CNTK#1475]
I found that there were problems with these items and there should be more。
https://github.com/Microsoft/CNTK/tree/master/Source/Extensibility/EvalWrapper
https://github.com/Microsoft/CNTK/tree/master/bindings/csharp/CNTKLibraryManagedDll

[`Error: The imported project “C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props” was not found`](http://stackoverflow.com/questions/22229548/error-the-imported-project-c-program-files-x86-msbuild-microsoft-cpp-v4-0-v)

I think the error comes from
```
 <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <Import Project="$(SolutionDir)\CNTK.Cpp.props" />
 <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />

```

**Comment by zhouwangzw** [comment]
@HeMinzhang Could you please try first "clean" and then "rebuild" the complete solution in Visual studio? Or you can remove the x64 directory under the repostory root directory (if there are anything from you except the build output from CNTK)?

**Comment by HeMinzhang** [comment]
@zhouwangzw 这个错误是我单独打开项目遇到了，我直接打开cntk项目没有报错， 能帮我看下另外2个ResNet错误吗，我春节开始研究cntk，到现在遇到那个错误7天了，，还是搞不明白，要不你给我一个你的支付宝，我给您一点辛苦费，不成敬意，

**Comment by HeMinzhang** [comment]
@zhouwangzw 冒昧问下，您是赵姐夫吗

**Comment by HeMinzhang** [comment]
@zhouwangzw Thanks a million.
