### ISSUE TITLE
Feature request: topologies

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#148]
I have a document* showing ImageNet % error for ILSVRC ... NEC America, Xerox, AlexNet, Clarifi, VGG, GoogleNet, and ResNet in descending order. Can you put the corresponding files somewhere in the examples directory or elsewhere in this repo? Otherwise, can you indicate why these cannot be made public? Thanks

*Src: CNTK-Tutorial-NIPS2015.pdf
"A Tutorial Given at NIPS 2015 Workshops" from Yu and Huang.

**Comment by dongyu888** [comment]
the slides are available on the same page as the CNTK book ( http://research.microsoft.com/apps/pubs/?id=226641), accessible from the GitHub wiki page.

**Comment by ldmtwo** [comment]
Let me clarify. I don't want the slides. I need the topology files (.cntk and .ndl) so that I can test and replicate the results.

**Comment by ldmtwo** [comment]
@dongyu888
