### ISSUE TITLE
[bug]ResNet101_ImageNet1K.cntk Convolution operation requires that kernel dim 3 <= input dim 2.

### ISSUE THREAD

**Issue by HeMinzhang** [Microsoft/CNTK#1480]
operation: Tensor shape was inferred as [512 x 1].
Node '_ol.x.x.x.b.arrayOfFunctions[0].arrayOfFunctions[0].arrayOfFunctions[1].runVariance' (LearnableParameter operation): Initializing Parameter[512 x 1] <- 0.000000.
Validating --> _ol.x.x.x.b.x.x._ = BatchNormalization (_ol.x.x.x.b.x.x._.x.c, _ol.x.x.x.b.arrayOfFunctions[0].arrayOfFunctions[0].arrayOfFunctions[1].scale, _ol.x.x.x.b.arrayOfFunctions[0].arrayOfFunctions[0].arrayOfFunctions[1].bias, _ol.x.x.x.b.arrayOfFunctions[0].arrayOfFunctions[0].arrayOfFunctions[1].runMean, _ol.x.x.x.b.arrayOfFunctions[0].arrayOfFunctions[0].arrayOfFunctions[1].runVariance, _ol.x.x.x.b.arrayOfFunctions[0].arrayOfFunctions[0].arrayOfFunctions[1].runCount) : [4 x 2 x 512 x *], [512 x 1], [512 x 1], [512 x 1], [512 x 1], [1] -> [4 x 2 x 512 x *]
Validating --> _ol.x.x.x.b.x.x = RectifiedLinear (_ol.x.x.x.b.x.x._) : [4 x 2 x 512 x *] -> [4 x 2 x 512 x *]
Validating --> _ol.x.x.x.b.x._.x.c = Convolution (_ol.x.x.x.b.arrayOfFunctions[1].arrayOfFunctions[0].arrayOfFunctions[0].W, _ol.x.x.x.b.x.x) : [3 x 3 x 0 x 512], [4 x 2 x 512 x *] -> [] FAILED
~MPIWrapper

[CALL STACK]
    > 000000013FF6D849 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF2C47F (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF2CC3C (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF2BCDF (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF2AC1E (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF1D4C4 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF1CA2C (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF49902 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF48425 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF3A43A (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF4AF24 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF4AEE6 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF4AEB9 (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FF4A6DC (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FD6429D (SymFromAddr() error: 试图访问无效的地址。)
    - 000000013FD5D153 (SymFromAddr() error: 试图访问无效的地址。)

EXCEPTION occurred: Convolution operation requires that kernel dim 3 <= input dim 2.

[ResNet101_ImageNet1K.cntk.txt](https://github.com/Microsoft/CNTK/files/782088/ResNet101_ImageNet1K.cntk.txt)
[ResNet_101_BS_out.txt](https://github.com/Microsoft/CNTK/files/782089/ResNet_101_BS_out.txt)

**Comment by cha-zhang** [comment]
ImageNet input resolution is 224x224x3, you have changed it to 100x40x3. Because there are pooling in the network, the output size will keep shrinking, until it's only 2 pixels. 

You should consider revise your network, reduce the number of pooling layers.

**Comment by HeMinzhang** [comment]
@cha-zhang Thanks a million.
