### ISSUE TITLE
Are this line correct?

### ISSUE THREAD

**Issue by StillKeepTry** [Microsoft/CNTK#1481]
[here](https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceClassification/SimpleExample/Python/SequenceClassification.py#L67) shall it be `ce, pe` not `(ce, pe)` ?

**Comment by hajix** [comment]
It seems you are right

**Comment by StillKeepTry** [comment]
This error exists in 2.0-beta-10, when update to 2.0-beta-11, this error will be solved.
