### ISSUE TITLE
Use network output or ground truth to eval and test Seq2Seq

### ISSUE THREAD

**Issue by zhengsx** [Microsoft/CNTK#1483]
Hi,

In [Seq2Seq](https://github.com/Microsoft/CNTK/blob/v2.0.beta11.0/Examples/SequenceToSequence/CMUDict/Python/Sequence2Sequence.py#L152) example line 152,

` # make a clone of the graph where the ground truth is replaced by the network output`
   `ng = z.clone(CloneMethod.share, {decoder_history_hook.output : net_output.output})`

we can see ng is a clone of z where the ground truth is replaced by network output for testing. And in line 224, ng is used for eval by `e = ng.eval(mb_valid)`.

However in line 234 and 247, it is `trainer` which pass into test_error function, why? (trainer is build from z rather than ng)

Thanks.

**Comment by sayanpa** [comment]
The example has been updated. There is also a tutorial CNTK 204 that has detailed explanation to the individual code blocks. Please refer to it. 

Closing this issue for now. In case you need further help, please open an issue and we will address your concerns.
