### ISSUE TITLE
Runtime Error! R6030 - CRT not initialized

### ISSUE THREAD

**Issue by mdmdmd9876** [Microsoft/CNTK#1485]
Hi, 
i have a problem with the new beta 11 release of CNTK Version 2. When i try to run the CNTK.exe for example via command prompt i receive the following error: Runtime Error! R6030 - CRT not initialized
things i have tried so far: 
-installed all new windows updates 
-i have tried it with the binaries version as well as with a self compiled version from source
-starting it as administrator 
I am using windows 7 and the old beta 9 release works without any issues.

**Comment by L-Ramos** [comment]
I had deadlock problems with the beta 2.0 version when using using windows 7. I tried to build the beta 2.11 but I also got the same message, waiting for an answer too.

**Comment by mdmdmd9876** [comment]
That's good to hear, i wasn't sure if the issue was due to some unique computer settings or sth. So I am not the only one with that problem.

**Comment by HeMinzhang** [comment]
You can test using win8.1 and win10.[Setup CNTK on your machine](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-your-machine)

**Comment by rafalfirlejczyk** [comment]
I have just installed the 2017-02-23.* V 2.0 Beta 12 Release of CNTK on my Win7/64 machine following exactly instruction - Setup CNTK on your machine. OK with one exception - I do not have Win8 or Win10.
I have the same Runtime error when executing the CNTK.exe - Runtime Error! R6030 - CRT not initialized.

**Comment by rafalfirlejczyk** [comment]
Additional finding:
You do not have this issue if you compile the code as Debug_CpuOnly.
![cpuonly](https://cloud.githubusercontent.com/assets/2536392/23458220/9b26c764-fe7b-11e6-8de2-b117242cdc29.PNG)

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation

**Comment by KGWANGMIN** [comment]
Hello! This problem can be solved by dynamically loading the CNTK dll or by dynamically loading the CUDA dll. I hope my comments will help others.

**Comment by jariahlstedt** [comment]
CNTK V 2.2 with Win7/64 GPU-compilations keep giving the CRT init error, but CPU-onlys don't. So it seems that it has something to do with CUDA.
KGWANGMING suggests dynamically loading CUDA.dll.
Now how do I do that???

**Comment by dmagee** [comment]
I can confirm this is still an issue with the very latest cntk 2.3 (cntk.exe) on Windows 7 compiled from source with no modifications (compiled using vs2015 on windows10). @KGWANGMIN are you using cntk.exe? Did you make some modifications to "dynamically load" the dlls at the start of the program?

**Comment by jlidbeck** [comment]
Still an issue with CNTK 2.4. Windows-64bit-GPU, running on Windows 8.1

**Comment by dmagee** [comment]
Sorry, I should have posted the fix before (as it's trivial). Building from source go to Project->Properties and then go to the Linker section and Input sub-section. There you'll see a box called "Delay Loaded Dlls". There are a couple of entries already, but finally the list should include:

Cntk.Math-xxx.dll
Cntk.PerformanceProfiler-xxx.dll
CntkCore-xxx.dll

where xxx is the version number (or macro for version ${CntkComponentVersion} )

I also seem to have a few other items there msmpi.dll, nvml.dll ${CudaRuntimeDll}. I forget if they were there originally or part of my trying to get it to work. As I remember it's the Cntk.XXX ones that fixed the problem.

**Comment by jakrivan** [comment]
Please reactivate this issue. It's still not resolved.
If it's resolved please provide the resolution/workaround.

Thanks
Jan
