### ISSUE TITLE
CRT not Initialized - Curand 201

### ISSUE THREAD

**Issue by L-Ramos** [Microsoft/CNTK#1486]
Hello guys, I've recently followed the tutorial to build CNTK from source code on Windows using Visual Studio 2015 (https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows).

After building it I got 0 errors and the CNTK.exe file was created in the release folder. I set my path variable to the release folder, opened the terminal and typed cntk, which gave me the following message:

Obs: I use windows 7, updating is not an option since the "work environment" wont let me.

![untitled](https://cloud.githubusercontent.com/assets/22447881/23072476/145c096c-f532-11e6-9975-d5efd26f815c.jpg)

I have been using the 1.7.2 version, which works most of the time, except when I try to use the dropout layer.
![untitled2](https://cloud.githubusercontent.com/assets/22447881/23072545/5e203f32-f532-11e6-802b-00e460bd8e8c.jpg)

When I try to use the dropout layer it runs for a few epochs, 2 or 3, and then it gives me the following message:

![untitled2](https://cloud.githubusercontent.com/assets/22447881/23073806/f3d40956-f536-11e6-98af-5033e076a344.jpg)

Without the dropout it runs perfectly fine until the end.

I googled it and it says thats its probably a cudnn 7.5 problem, since I have a Gforce 1080 I downloaded and installed cudnn 8.0.

I also found that building the version 1.7.2 is likely to work, but I can't find a tutorial for it and I believe it is quite different from building the latest version, I got many error messages when I tried to build 1.7.2 on my own.

Do you guys have any tips about what I should do?

Best regards, Lucas

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
