### ISSUE TITLE
Snap package for CNTK

### ISSUE THREAD

**Issue by anirudh2290** [Microsoft/CNTK#1488]
It would be nice to have a snap package for CNTK. https://snapcraft.io/
The advantage is that it is easy to install and supports multiple distributions.

**Comment by cha-zhang** [comment]
We are working on a pip install for CNTK. Should be ready by the end of the month. Please stay tuned...

**Comment by wolfma61** [comment]
pip install exists
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
