### ISSUE TITLE
Compiled binary version failed in the task 4 of "Hands On Labs Language Understanding"

### ISSUE THREAD

**Issue by johnny5550822** [Microsoft/CNTK#1489]
I followed this "https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-your-machine" to install the binary version of CNTK in my window machine, I did all first three tasks in this tutorial "https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Language-Understanding", but for some reason it failed in task 4 - Intent Classification (the error is like 96%). 

I used the same config file and input file.

Is there anyone facing the same issue? Anyone can check that?

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
