### ISSUE TITLE
Documentation request: Multiple CPU and multi-node

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#149]
Can you add documentation that would show someone how to use a multi-socket CPU (e.g. Intel Xeon E5 or E7) having 1/2/4 MPI processes per machine and how to adjust for multiple nodes of this configuration? I would also like know how to adjust for different numbers of cores rather than automatically adjusting to the total number of virtual cores (cores with hyperthreading) seen by the OS.  Thanks.

**Comment by ldmtwo** [comment]
Also, I have previously tried to run this on multiple machines (see issue #147) and I could adjust np (# processes) to any number, but I could not get that example to work on more than 2 nodes. Is it to due with the configuration used in that example? images/MNIST/01_hidenlayer.cntk

**Comment by Alexey-Kamenev** [comment]
Hello,
Have you tried manually setting `numCPUThreads` in your config/command line?
For example, this should tell CNTK to use not more than 4 threads for compute on CPU:
`numCPUThreads=4`

**Comment by mradmila** [comment]
We are looking at clarifying documentation around this issue. Thank you for reporting it.
