### ISSUE TITLE
Appreciation for ctc implementation

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1491]
Hi

Thanks a lot from all CNTK team for developing such a good deep learning toolkit. As the title denotes, today CTC criteria node is finally merged with the master branch, and that's an amazing news for whom waiting too long for CTC implementation (#1112 #451 #291 #235).

When the new binaries will be available? I'm excited to use CTC criteria for ASR task...

regards

**Comment by vmazalov** [comment]
CNTK now supports CTC training. Here is the end to end test and corresponding documentation:

https://github.com/Microsoft/CNTK/tree/master/Tests/EndToEndTests/Speech/LSTM_CTC_MLF
