### ISSUE TITLE
Could not map input 'inputNodes' to the reader.

### ISSUE THREAD

**Issue by Rekeyea** [Microsoft/CNTK#1492]
I'm learning how to use CNTK. I'm trying to use it with BrainScript.
My environment is:

Windows 10 Pro
Versión is 2.0 Beta 11

One line of the data file looks like the following:
`|features 546 332 |expected 1`

And the cntk config file is the following:

`traceLevel = 3
command = Train

Train = [
    action = "train"
    modelPath = "./Models/model.dnn"
    BrainScriptNetworkBuilder = (new ComputationNetwork {
        FeaturesDim = 2
        HiddenDim = 3
        ExpectedDim = 1

        model(features) = {
            W0 = ParameterTensor {(HiddenDim:FeaturesDim)}
            b0 = ParameterTensor {HiddenDim}
            W1 = ParameterTensor {(ExpectedDim:HiddenDim)}
            b1 = ParameterTensor {ExpectedDim}

            #model formula
            r = W0 * features + b0
            z = W1 * r + b1
        }.z

        features = Input {2}
        expected = Input {1}
        
        # model using actual features
        z = model(features)
        errs = SquareError (expected, z)

        # define cntk variables
        featureNodes = (features)
        inputNodes = expected
        criterionNodes = errs
        evaluationNodes = errs
        outputNodes = z
    })

    SGD = [
        modelPath = "./Models/model.dnn"
        epochSize = 10
        minibatchSize = 10
        maxEpochs = 10,
        learningRatesPerSample = 0.01
    ]

    reader = [
        readerType = "CNTKTextFormatReader"
        file = "./Data/training-set.txt"
        input = [
            features = [
                dim = 2
                format = "dense"
            ]
            expected = [
                dim = 1
                format = "dense"
            ]
        ]
    ]
]
`

The error i get is:

[CALL STACK]
    > 00007FF66307C8A1 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662EEC37E (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662F79DE9 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662F74CB1 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662F718EC (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662EBDFA6 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662E7F5F1 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662E1E9B2 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662E1F179 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF662E1F3DB (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF6630A0611 (SymFromAddr() error: Attempt to access invalid address.)
    - BaseThreadInitThunk
    - RtlUserThreadStart

EXCEPTION occurred: Could not map input 'inputNodes' to the reader. Reader outputs only ["expected", "features"].

Regards

**Comment by spandantiwari** [comment]
"Expected" are your labels, correct? Can you try changing this line ```inputNodes = expected``` to ```labelNodes = expected```.
