### ISSUE TITLE
Install powershell error in China.

### ISSUE THREAD

**Issue by HeMinzhang** [Microsoft/CNTK#1495]
[Setup Windows Binary Script](https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script)
I installed CNTK in windows10 with the above tutorial.
Because I in China,I can't install CNTK use powershell.Can you give the download address for all files?I think it will help a lot of people in China.Thanks a million.

**Comment by wolfma61** [comment]
The manual installation script contains all the direct links for the downloads. https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Binary-Manual

please open a new issue if you experience this in a more recent CNTK installation
