### ISSUE TITLE
ResNet110_CIFAR10.cntk error Cannot parse label value on line 0, second column,

### ISSUE THREAD

**Issue by HeMinzhang** [Microsoft/CNTK#1497]
TrainConvNet = {
    action = "train"

    BrainScriptNetworkBuilder = {
        include "$configDir$/Macros.bs"
	
        imageShape = 100:40:3
        labelDim = 100

        featScale = 1/256
        Normalize{f} = x => f .* x

        cMap = 16:32:64
        bnTimeConst = 4096
        numLayers = 18
		
        model = Sequential (
            Normalize {featScale} :
 reader = {
        verbosity = 0 ; randomize = true
        deserializers = ({
            type = "ImageDeserializer" ; module = "ImageReader"
            file = "$rootDir$/train_map.txt"
            input = {
                features = { transforms = (
                    { type = "Crop" ; cropType = "RandomSide" ; sideRatio = 0.8 ; jitterType = "UniRatio" } :
                    { type = "Scale" ; width = 100 ; height = 40 ; channels = 3 ; interpolations = "linear" } :
                    { type = "Mean" ; meanFile = "$dataDir$/CIFAR-10_mean.xml" } : 
                    { type = "Transpose" }
                )}
                labels = { labelDim = 100 }
            }
        })
    }

Map: 64, Stride: 1 x 1 x 64, Sharing: (1, 1, 1), AutoPad: (1, 1, 0), LowerPad: 0 x 0 x 0, UpperPad: 0 x 0 x 0.
Using CNTK batch normalization engine.
z.x: using GEMM convolution engine for geometry: Input: 25 x 10 x 64, Output: 18 x 3 x 64, Kernel: 8 x 8 x 1, Map: 1, Stride: 1 x 1 x 1, Sharing: (1, 1, 1), AutoPad: (0, 0, 0), LowerPad: 0 x 0 x 0, UpperPad: 0 x 0 x 0.

Post-processing network complete.

[CALL STACK]
    > Microsoft::MSR::CNTK::IDataReader::  SupportsDistributedMBRead
    - CreateDeserializer
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - CreateCompositeDataReader
    - Microsoft::MSR::CNTK::IDataReader::  operator=
    - Microsoft::MSR::CNTK::IDataReader::  operator=
    - CreateCompositeDataReader
    - 00007FF6A24C025B (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    - 00007FF6A230586B (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    - 00007FF6A23050BA (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    - 00007FF6A22FDDE9 (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    - 00007FF6A22BF5F1 (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    - 00007FF6A225E9B2 (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    - 00007FF6A225F179 (SymFromAddr() error: 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
EXCEPTION occurred: Cannot parse label value on line 0, second column, in file ./train_map.txt.

[MyEdit_ResNet110_CIFAR10.cntk.txt](https://github.com/Microsoft/CNTK/files/787619/MyEdit_ResNet110_CIFAR10.cntk.txt)

**Comment by cha-zhang** [comment]
Something wrong with your train_map.txt file? Can you attach that as well?

**Comment by HeMinzhang** [comment]
@cha-zhang 
[train_map.txt](https://github.com/Microsoft/CNTK/files/787830/train_map.txt)
[val_map.txt](https://github.com/Microsoft/CNTK/files/787832/val_map.txt)

**Comment by HeMinzhang** [comment]
[CNTk-ImagerReader](https://github.com/Microsoft/CNTK/wiki/Image-reader) 

train .txt can  only input the Numbers.
