### ISSUE TITLE
Build not copying all cuda-related dll files to build directory, causes 'Failed to load' error

### ISSUE THREAD

**Issue by NickWeintraut** [Microsoft/CNTK#150]
I just finished up set up according to the setup page, and built the release version. The Simple2d example works perfectly fine when using CPU as the device, but when running it on GPU, I get a 
`CNTK: Failed to load DLL 'curand64_70.dll'. `

My environment variables for CUDA_PATH and CUDA_PATH_V7_0 are both `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0`

and I was able to find curand64_70.dll in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin`

What should I check out to try to fix the issue?

**Comment by NickWeintraut** [comment]
Realized my Release build folder had its copies of cudart64_70.dll and cudnn64_70.dll, but not curand64_70.dll

Copied curand64_70.dll over to the directory and it worked properly (until it was missing cublas64_70.dll), so this is probably just a problem with building my solution. Would like to figure out why my build is not copying these files properly, though.

**Comment by wolfma61** [comment]
cudart64_70.dll is copied as part MATHcuda project in a Post-build-event to the output directory

xcopy /D /I /Y "$(CudaPath)\bin\cudart64_*.dll" $(OutputPath)
if exist "$(CuDnnDll)" (xcopy /Y "$(CuDnnDll)" $(OutputPath))

can you do a clean build?
can you check in your build log if the post-build is being executed?

thx
Wolfgang

**Comment by wolfma61** [comment]
looking into this right now, there seems to be something off ... hold on ;)

**Comment by wolfma61** [comment]
I checked in a new version of the matchcuda project file into master. This should fix the problem. Let me know if you still experience problems ... sorry about the oversight

thx
Wolfgang
