### ISSUE TITLE
need batch normalization on a cpu only laptop

### ISSUE THREAD

**Issue by bottle-watch** [Microsoft/CNTK#1501]
Hi all,

I want to use batch normalization in my network but I only have a cup only laptop and can't find anywhere to install cntk on a device with gpu. Does anyone else have same concern with me? 

Is it a good idea to write a custom batch normalization layer myself? Is that convenient with current cntk support?

**Comment by spandantiwari** [comment]
You can install CNTK on a cpu only device. Please look at this [Setup Windows Python]( https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python) for Windows and [Setup Linux Python](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-python) for Linux.
