### ISSUE TITLE
Minibatch from hdf5 in Python API

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#1502]
As I know, CNTK Python API provides a class `MinibatchSource` for fetching minibatches from an image list (*.txt). Is there any function for fetching minibatches loaded from hdf5 in Python API? or easy-to-use example code?

It is difficult to handle fetching a minibatch and scheduling a learning rate at once when I naively code like the following.

```
    pp = ProgressPrinter(0)    
    for i in range(num_minibatches_to_train):
         features = X_train[i*minibatch_size:(i+1)*minibatch_size]
         labels = Y_train[i*minibatch_size:(i+1)*minibatch_size]
         trainer.train_minibatch({network['feature']: features, network['label']: labels})
         pp.update_with_trainer(trainer)
```

**Comment by sayanpa** [comment]
You have different ways of feeding data to CNTK.  The following to tutorials are added to help feed data to CNTK:

https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_create_user_minibatch_sources.ipynb

https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_feed_data.ipynb

Given the issue has been open for a long time, I am closing the issue. If you need further assistance, please reach out. We are in the process of improve our turn around time for Github issues.
