### ISSUE TITLE
CTC Training (data segmentation problem)

### ISSUE THREAD

**Issue by MattGjdr** [Microsoft/CNTK#1503]
I am kinda new in this, so I might be wrong. 
But the major advantage of CTC training is that you do not need segmented data and in example (CNTK/Tests/EndToEndTests/Speech/LSTM_CTC/) you can see that you need them (CNTK/Tests/EndToEndTests/Speech/Data/ctc_glob_0000.mlf). 

Is there any option with no need for segmented .mlf file ?

**Comment by hajix** [comment]
Hi

As you noted, definitely that is not the CTC which was introduced the at ICML 2006 paper. I cannot understand why I should use labels which has :1 and :2 at trailing!? Also why the example use such aligned labels!! preparing such aligned labels will fully put CTC advantage away.

In current example, it seems that CNTK implements some new kind of CTC!!

Hope to correct in new releases...

**Comment by eldakms** [comment]
Could you please have a look at the newest sample at  CNTK/Tests/EndToEndTests/Speech/LSTM_CTC_MLF. This should not require a different mlf file. Thanks!

**Comment by hajix** [comment]
The problem is not the type of label file (mlf or ctf), but the segmentation of labels used in CTC example. CTC need no segmented labels to train model, but in these examples we must use segmented labels.

thanks for your answer
@eldakms

**Comment by vmazalov** [comment]
The label segments are actually ignored during training. The examples reference existing MLF files to be able to utilize the MLF reader that CNTK already has.
