### ISSUE TITLE
Potential Error/ Cuda Error 77

### ISSUE THREAD

**Issue by Vedaevolution** [Microsoft/CNTK#1505]
Dear Community,

i append a python file which tries do train a network in a way that for every image x a x_mask is produced which can be expressed as a regression problem. 

> mse = (z(x) - xmask)^2

where z is the network. To achieve that i'm loading x and x_mask as network inputs. In my eyes what i have coded should be okay but i get the following error:

> return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
> RuntimeError: cuDNN failure 7: CUDNN_STATUS_MAPPING_ERROR ; GPU=0 ; hostname=... ; expr=err
> cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)

The goal is to bring a 244 * 244 * 3 image down to an 56 * 56 * 3 image through convolutions with z(x) which can be substracted and squared with xmask (56 * 56 * 3).
  
[conv.txt](https://github.com/Microsoft/CNTK/files/790751/conv.txt)

Is this a bug or my bad for coding something wrong?

Thank you in advance

**Comment by n17s** [comment]
According to other projects that have run into this issue (see for example [here](https://github.com/tensorflow/tensorflow/issues/2190)) this may indicate a bug in the cudnn library. CNTK does not use texture memory so it is best to report this problem to NVidia.
