### ISSUE TITLE
linker error while building CNTK with ASGD 

### ISSUE THREAD

**Issue by Drjagz** [Microsoft/CNTK#1506]
~/Repos/cntk/build/release2/.build/Source/Multiverso/Test/unittests/test_array.o: In function `multiverso::test::MultiversoEnv::MultiversoEnv()':
~/Repos/cntk/Source/Multiverso/Test/unittests/multiverso_env.h:11: undefined reference to `void multiverso::MV_SetFlag<bool>(std::string const&, bool const&)'
~/Repos/cntk/Source/Multiverso/Test/unittests/multiverso_env.h:11: undefined reference to `void multiverso::MV_SetFlag<bool>(std::string const&, bool const&)'
~/Repos/cntk/build/release2/.build/Source/Multiverso/Test/unittests/test_kv.o: In function `multiverso::test::MultiversoEnv::MultiversoEnv()':
~/Repos/cntk/Source/Multiverso/Test/unittests/multiverso_env.h:11: undefined reference to `void multiverso::MV_SetFlag<bool>(std::string const&, bool const&)':
~/Repos/cntk/build/release2/.build/Source/Multiverso/Test/unittests/test_sync.o: In function `multiverso::test::SyncMultiversoEnv::SyncMultiversoEnv()':
~/Repos/cntk/Source/Multiverso/Test/unittests/multiverso_env.h:22: undefined reference to `void multiverso::MV_SetFlag<bool>(std::string const&, bool const&)'
collect2: error: ld returned 1 exit status
Makefile:988: recipe for target '~/Repos/cntk/build/release2/bin/multiversotests' failed

I can see in the code files this function is available but still this error. I am using MVAPICH2 with cuda toolkit 8.0. Thanks

**Comment by Drjagz** [comment]
Hi, my previous error occured because I compiled boost with different toolchain. It is resolved now but now I am stuck in another linker error.

/usr/bin/ld: /users/xx/cntk/CNTKCustomMKL/3/x64/parallel/libmkl_cntk_p.so: undefined reference to symbol 'dlopen@@GLIBC_2.2.5'
/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by chivee** [comment]
the MVAPICH2 will be supported at next version, and could you please check the GCC version you are using?

**Comment by spandantiwari** [comment]
This could be a GCC version issue. If you are still having this issue, please reopen this issue with your GCC version and info about the CNTK source commit hash that you are building.
