### ISSUE TITLE
AN4 LSTM example not loadable in python API.

### ISSUE THREAD

**Issue by gvoysey** [Microsoft/CNTK#1507]
After training `Examples/Speech/AN4` with `LSTM-NDL_ndl_deprecated.cntk`: 

```python
from cntk import load_model
load_model('cntkSpeechLSTM.dnn')
```

raises

`in load 
return cntk_py.Function.load_model(filename, device)
RuntimeError: Unsupported ComputationNode with OperationName='DiagTimes' found when loading legacy CNTK model`

CNTK info: 
```
-------------------------------------------------------------------
Build info: 

		Built time: Feb 10 2017 11:12:07
		Last modified date: Fri Feb 10 11:09:58 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: yes
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: /usr/local/cuda-8.0
		CUB_PATH: /usr/local/cub-1.4.1
		CUDNN_PATH: /usr/local/cudnn-5.1
		Build Branch: HEAD
		Build SHA1: bc81f3fb1d50d9799e84263147f7da6b8c9db8f8
		Built by Source/CNTK/buildinfo.h$$0 on 8a826d6bc647
		Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux
		MPI distribution: Open MPI
		MPI version: 1.10.3

```

on ubuntu 14.

**Comment by gvoysey** [comment]
for me this is resolved in beta 12.

**Comment by cha-zhang** [comment]
@gvoysey , you closed and reopened this issue. Has this been resolved? 

I'm closing this because the question has been 5 months old. If it still an issue for the latest 2.0 release, please open a new issue. Thanks!

**Comment by gvoysey** [comment]
@cha-zhang resolved here, iirc.  I think i re-opened it accidentally.  thanks for cleaning up!

**Comment by cha-zhang** [comment]
Great. Thanks!
