### ISSUE TITLE
CNTK and Reinforcement Learning

### ISSUE THREAD

**Issue by Disclosure** [Microsoft/CNTK#1508]
Is it possible to implement reinforcement learning in CNTK framework?

**Comment by 2wins** [comment]
Please refer to the following link: https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_203_Reinforcement_Learning_Basics.ipynb

**Comment by spandantiwari** [comment]
Closing this issue. Please reopen if you have any issues/questions in implementing reinforcement learning.
