### ISSUE TITLE
Segmentation with deconvolution converges to zeros

### ISSUE THREAD

**Issue by bulatGH** [Microsoft/CNTK#1509]
I was trying to adapt autoencoder example for segmentation. However, the weights of the network always converges to zeros. I think, this problem was raised several times here, but I was not able to find any answer.

Maybe there is some restriction about input values?
I am sending the architecture file and training data.

[temp_deconv.txt](https://github.com/Microsoft/CNTK/files/791863/temp_deconv.txt)
[segmentation.txt](https://github.com/Microsoft/CNTK/files/791861/segmentation.txt)

**Comment by cha-zhang** [comment]
We will offer some segmentation example soon. Please stay tuned.

**Comment by spandantiwari** [comment]
Please track issue #1613 for this request. Closing this one as duplicate.
