### ISSUE TITLE
can CNTK with NCCL enable  be used for multinodes training ? 

### ISSUE THREAD

**Issue by silverlining21** [Microsoft/CNTK#1510]
@fmegen  @chivee   @amitaga 
as for I know CNTK use MPI for multinodes training and NCCL wokrs only on single node. if with NCCL enable CNTK can use for multinodes trainning, how it works ?

regards.

**Comment by mahilleb-msft** [comment]
Sorry, at this stage NCCL support only applies to training on single hosts.

**Comment by silverlining21** [comment]
yeap, after reviewing the related code, I got the same conclusion.  thanks anyway.
