### ISSUE TITLE
How to use adam sgd in Brainscript

### ISSUE THREAD

**Issue by MihawkHu** [Microsoft/CNTK#1511]
I want to use adam sgd in Brainscript but I don't find any example or instruction about it. Can you show some examples for me?

**Comment by ujjwal-researcher** [comment]
No updates on this ?

**Comment by n17s** [comment]
Unfortunately, we do not plan to add Adam to Brainscript. Your options are either to use fsadagrad which is pretty close to Adam, or use the V2 APIs.

I'm closing this thread. Feel free to reopen.
