### ISSUE TITLE
Feature request: consider ring allreduce (MPI) implementation

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1512]
https://github.com/baidu-research/baidu-allreduce

**Comment by FDecaYed** [comment]
@avader906 
CNTK has NCCL support since months ago. It uses ring allreduce that is well optimized for GPU.
https://github.com/NVIDIA/nccl

**Comment by avader906** [comment]
@FDecaYed This is not the same as MPI ring allreduce

**Comment by FDecaYed** [comment]
@avader906 Can you be more specific? What is your use case?

**Comment by avader906** [comment]
@FDecaYed may I suggest you inform yourself by consulting the repository baidu made available and revert should you have any more questions. this is the idea taken from the NCCL (ring PCI traffic to reduce congestion on the bridge level) - and now implemented in MPI. tests show potential in reducing transmit queues / marginal increase in bandwidth (infiniband rdma environment) by routing intelligently between MPI ranks.

**Comment by FDecaYed** [comment]
It may help if you are looking at multi-node. But personally I wouldn't expect too much performance boost on MPI-based implementation on DL workload.

**Comment by avader906** [comment]
This means nothing to me: "MPI-based implementation on DL workload". We are talking about DataParallel SGD 1bit over MPI. The more nodes you have / the more GPUs per node, the more this will be useful for the gradient exchange and will make things scale a notch more.

**Comment by FDecaYed** [comment]
Since you mention 1 bit SGD. I think Ring allreduce won't help 1 bit much because of small size send/receive and bandwidth is not bottle neck for 1bit.

**Comment by avader906** [comment]
@FDecaYed Do you understand the difference between latency and bandwidth, and how it affects small (or large) packets throughput?  Maybe IOPS vs throughput is more familiar?

If you have a small network of 10mio parameters and need to propagate gradients to 24 hosts x 8 GPUs the issue is latency - not bandwidth. If you have the infrastructure or the testbed to appreciate this issue, I suggest you monitor infiniband congestion with ```ibqueryerrors```. PortXmitWait will indicate queue - large numbers congestion (before packets dropped).

**Comment by FDecaYed** [comment]
My opinion is implementation on top of MPI won't achieve full potential of ring collectives.

**Comment by spandantiwari** [comment]
@ghost The team will take a look.

**Comment by junjieqian** [comment]
We are working with Nvidia on testing NCCL2 which has similar ring allreduce implementation.

**Comment by spandantiwari** [comment]
FDecaYed, who seems to be from Nvidia, commented on this issue saying the same. But seems like this user is asking specifically for MPI ring allreduce.

Here’s the issue:
https://github.com/Microsoft/CNTK/issues/1512
