### ISSUE TITLE
How can I get test/inference time (Fast-R-CNN)? 

### ISSUE THREAD

**Issue by srinivasputta** [Microsoft/CNTK#1517]
I'm trying out Fast-R-CNN with A2_RunCntk.py , but test command doesn't print time it took for test phase. Could someone help for calculating images/sec for it and in general ?

**Comment by pkranen** [comment]
You can add something like the following around the for loop in `evaluate_fast_rcnn` (see [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/A2_RunWithPyModel.py#L190)):
```
import time
start_ms = int(time.time() * 1000)
for i in range(0, num_test_images):
    ...
total_ms = int(time.time() * 1000) - start_ms
print("milliseconds per image: {}".format(total_ms / num_test_images))
```
