### ISSUE TITLE
GPU Access Memory Errors and Out of Memory Errors

### ISSUE THREAD

**Issue by DigitalEd** [Microsoft/CNTK#1519]
Hey all,
  I'm having a problem running a variation of the [SLUHandsOn Example](https://github.com/Microsoft/CNTK/wiki/Hands-on-labs-Language-understanding) .

The training works and has a 4818 samples. The test data has 1204. If I try to run with the full test set I get the error (same issue as Issue #468). 
`CUDA failure 2: out of memory ; GPU=0 ; hostname=hostname; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)`

The solution to #468 doesn't resolve the issue. A minibatch setting of 1,2 and 5 all get the same error.

Reducing the number of test data samples to around 73 works. However, more than 73 (but less than the full set) yields a different memory error:

```
CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=hostname; expr=cudaFree((void*) bufferPtr)
cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)
cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)
terminate_this: aborting.
```
Any ideas on how to understand what's going on?

----- Ed

**Comment by L-Ramos** [comment]
Have you tried to run this with the CPU version to see if it gives you the same error?

**Comment by DigitalEd** [comment]
It works on the CPU but we have to remove the Batch Normalization since it has no CPU implementation.

**Comment by FDecaYed** [comment]
@DigitalEd What is `minibatchSize` setting in your Test or Eval section? I think you maybe just reducing minibatchSize to 1,2,5 in training but not in testing. This could explain the OOM error.

As for the cuda 77 failure. Could you provide more detail? config, error log, cntk build info...

**Comment by DigitalEd** [comment]
We are using CNTK 2.0.beta7.0 (HEAD 8e8b5f, Dec 22 2016 01:45:54).
The minibatchSize was set in the eval section but was put in the wrong place. It was put inside the reader block. Putting it in it's proper place and setting the value to 2 fixes the out of memory error.

As for the cuda 77 failure, I'm not sure how to get more information. However, with the minibatchSize setting in the right place (and set to 2) the error goes away.

**Comment by sayanpa** [comment]
We significant effort to fix these errors. Should have been resolved in V2. If not please reopen a new issue. Closing this one for now.

**Comment by rajarsheem** [comment]
It looks like in Notebook, as you execute the cells with CNTK eval code more, GPU memory gets more and more occupied. Any idea how to reset everything before the next run ?

**Comment by sayanpa** [comment]
Do you see the same thing happen if you run the code as python scripts? Trying to isolate it this is a notebook specific issue. Assuming you are using V2 or later version.

**Comment by rajarsheem** [comment]
I haven't checked but I guess it won't happen in that case since, analogously, restarting the kernel in notebook certainly clears the memory.

**Comment by sayanpa** [comment]
Sure. So as I understand in the notebook environment say you have the same reader and keep evaluating the same model in a loop the memory grows. When running python files, the same evaluation call does not cause memory to grow. Please correct me if I am mistaken.

**Comment by rajarsheem** [comment]
You are absolutely right. I have also observed that only running the notebook cell that just contains the model graph, and not any eval, also increases the GPU memory.

**Comment by sayanpa** [comment]
The notebooks are typically designed for educational / presentation purposes. There are discussion indicating running a notebook may not be ideal. We will keep an eye on this problem and fix anything that may be CNTK specific.
