### ISSUE TITLE
When I used CNN with automatic determine parameter W, exception occurred

### ISSUE THREAD

**Issue by hahatt** [Microsoft/CNTK#152]
EXCEPTION occurred: VerifySize: expected matrix size 0 x 1, but it is 0 x 0
/speechlab/users/tt123/src/cntk/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::GetCallStack()  + 0xc6  )  [0x7f1342717da6]
<88>  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormattedstd::logic_error(char const*, ...)  + 0xe0  )  [0x536f80]
<9D>  cntk                           ( Microsoft::MSR::CNTK::ComputationNode<float>::TensorAsMatrix(Microsoft::MSR::CNTK::Matrix<float>&)  + 0x54  )  [0x5601f4]

In NDL, my convolution layer is following

```
RCFFPadding(kW,kH,outputC,hS,vS, fIn){
    W = Parameter(0)
    B = Parameter(outputC, init=fixedvalue, value=0)
    C = Convolution(W, fIn, kW, kH, outputC, hS, vS, zeroPadding=true)
    P = Plus(C,B)
    S = RectifiedLinear(P)
}
```

This code can run on old version CNTK, such as version at 2015-11-12
The error occurred in Source/ComputationNetworkLib/ComputationNode.h

  1097     Matrix<ElemType>& TensorAsMatrix(Matrix<ElemType>& data)
  1098     {
  1099         size_t numRows = GetAsMatrixNumRows();
  1100         size_t numCols = GetAsMatrixNumCols();
  1101         // We only get here if the tensor indeed describes an 1D or 2D object. In that case, just verify the dimensions.
  1102         data.VerifySize(numRows, numCols);
  1103         return data;
  1104     }

**Comment by Alexey-Kamenev** [comment]
Hello,
Can you please try using ImageParameter for bias instead of Parameter:
`b = ImageParameter(1, 1, outputC, init=fixedvalue, value=0)`
?

**Comment by hahatt** [comment]
Hi,
I tried that, but the same EXCEPTION occurred.

**Comment by Alexey-Kamenev** [comment]
Hello,
Does this still happen with latest master sources?

**Comment by hahatt** [comment]
It works well now
