### ISSUE TITLE
Error in Fast RCNN example

### ISSUE THREAD

**Issue by rotimpe** [Microsoft/CNTK#1521]
I'm getting an error trying to run A2_RunCntk_py3.py from the image detection using fast rcnn example

```
Traceback (most recent call last):
  File "A2_RunCntk_py3.py", line 223, in <module>
    test_fast_rcnn(trained_model)
  File "A2_RunCntk_py3.py", line 186, in test_fast_rcnn
    num_classes, num_rois, base_path, "test")
  File "A2_RunCntk_py3.py", line 83, in create_mb_source
    image_source = ImageDeserializer(map_file)
TypeError: ImageDeserializer() missing 1 required positional argument: 'streams'
```

**Comment by PatrickBue** [comment]
+1

**Comment by srinivasputta** [comment]
+1 , please let me know if you found a workaround.. Thanks

**Comment by rotimpe** [comment]
I cloned the repo and made my changes [here](https://github.com/rotimpe/CNTK/blob/master/Examples/Image/Detection/FastRCNN/A2_RunCntk_py3.py)

I had trouble finding good documentation, so I'm not sure if I'm using the new API correctly.  But it at least runs.  I also made some other changes to match the tutorial more closely.  You should be able to use my version of the script with a pretrained model.  Just make sure to rename the model to frcn_py.model and change cntk_nrRois in PARAMETERS.py to 2000

**Comment by jessechoi** [comment]
@rotimpe i was able to run with learning with your new A2_RunCntk_py3, but facing following error:

Traceback (most recent call last):
  File "A2_RunCntk_py3.py", line 221, in <module>
    eval_model = combine([trained_model.outputs[2].owner])
IndexError: tuple index out of range

**Comment by rotimpe** [comment]
@jessechoi were you using one of the pre-trained models?  If not, you can probably just get rid of that line.

I added that line because the pre-trained model provided in the tutorial has outputs that depend on having labeled data, but the test_fast_rcnn function doesn't provide labels when it calls the model.  But if you train your own model using A2_RunCntk_py3.py then I don't think you'll run into that problem (not sure though since I haven't tried it).

**Comment by creiser** [comment]
Works with your fix as long as I use the original `test_fast_rcnn(trained_model)`.

**Comment by rtrahms** [comment]
+1, I am also getting the ImageDeserializer() error in A2_RunCntk_py3.py - 'streams' missing.

**Comment by JeffMuchine** [comment]
+1 
@rotimpe thank you for your help. But when I use your model and train with the original  test_fast_rcnn(trained_model). the result of Mean AP is just 0.667. the model miss Ketchup, onion, water, and tabasco 

AP for         avocado = 1.0000
AP for          orange = 1.0000
AP for          butter = 0.6667
AP for       champagne = 1.0000
AP for          eggBox = 0.7500
AP for          gerkin = 0.9000
AP for         joghurt = 1.0000
AP for         ketchup = 0.0000
AP for     orangeJuice = 1.0000
AP for           onion = 0.0000
AP for          pepper = 1.0000
AP for          tomato = 0.8000
AP for           water = 0.0000
AP for            milk = 0.5556
AP for         tabasco = 0.0000
AP for         mustard = 1.0000
Mean AP = 0.6670

**Comment by Wheele9** [comment]
I run into this issue as well. 
TypeError: ImageDeserializer() missing 1 required positional argument: 'streams'

**Comment by fcivardi** [comment]
Me too:
TypeError: ImageDeserializer() missing 1 required positional argument: 'streams'

**Comment by ideaplat** [comment]
me too

**Comment by fcivardi** [comment]
In  A2_RunCntk_py3.py:
 image_source = ImageDeserializer(map_file)
But in the API doc.  ImageDeserializer needs streams as well:
def ImageDeserializer(filename, streams):
 ...

**Comment by srinivasputta** [comment]
FYI if it helps, this issue doesn't appear with pre-built binary installation.

**Comment by pkranen** [comment]
This issue is fixed now in master.
