### ISSUE TITLE
Why don't you renew CNTK's web site and tutorial page?

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#1524]
CNTK does not seem to have a large number of users despite its excellent performance. As you know, there exist many other deep learning libraries including Google's TensorFlow, Facebook's Torch (and PyTorch), etc. The websites of such libraries are user friendly and accessible. Please compare CNTK's web pages with theirs (https://www.tensorflow.org/, http://pytorch.org).
In order to attract a lot of users, I think it is inevitable to renovate the website of CNTK and reorganize the tutorial pages. With easy installation of the library, user-friendly web pages will certainly help attract a lot of users.  I really hope that the number of users with CNTK will increase. Thank you.

**Comment by cha-zhang** [comment]
Thank you for your kind suggestion. We definitely need to improve our website and documentation. It's on our high priority to-do list.

**Comment by sayanpa** [comment]
We have taken your advice and made efforts to improve our pages. Though we have ways to go, here is our current page:
https://cntk.ai/pythondocs/tutorials.html

We have also added new content with working code for ease of use: https://github.com/Microsoft/CNTK/tree/master/Manual

We also have a new doc site and know about its limitations:
https://docs.microsoft.com/en-us/cognitive-toolkit/

Would it be possible for you to give us feedback on the new doc site. It would help us prioritize workitems on our side.

**Comment by cha-zhang** [comment]
I'm closing this issue for now. Please reopen it if needed. Documentation is of very high priority for the CNTK team.
