### ISSUE TITLE
OpenCV Error "String too long" for XML file used by ImageDeserializer.mean()

### ISSUE THREAD

**Issue by mawah** [Microsoft/CNTK#1525]
Hi folks,

I've created an XML file listing the mean values for each pixel/channel combination in my training set by following the [CIFAR-10 example](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet/Python) in this repo. I found that for my 3x224x224 images, if I write the RGB values in scientific notation as that example recommends, I get the following error when attempting to train my model:
```
OpenCV Error: Parsing error (E:\od\mean_images\train_ma.xml(9): Too long string
or a last string w/o newline) in icvXMLSkipSpaces, file C:\buildslave64\win64_am
docl\master_PackSlave-win64-vc14-shared\opencv\modules\core\src\persistence.cpp,
 line 1807
Traceback (most recent call last):
  File "train_alexnet_ma_withxmlmean.py", line 118, in <module>
    train_fast_rcnn()
  File "train_alexnet_ma_withxmlmean.py", line 64, in train_fast_rcnn
    minibatch_source = create_reader(map_file)
  File "train_alexnet_ma_withxmlmean.py", line 48, in create_reader
    labels   = StreamDef(field='label', shape=num_classes, is_sparse=False)))))
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\io\__init__.py", line
108, in __init__
    source = minibatch_source(reader_config)
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\utils\swig_helper.py",
 line 62, in wrapper
    result = f(*args, **kwds)
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\io\__init__.py", line
245, in minibatch_source
    return cntk_py.create_composite_minibatch_source(cntk_dict)
RuntimeError: Runtime exception
```
The string in question is the "data" subelement in the XML file, which is just all of the mean values concatenated together. The script does run without error if I round each mean value to an integer instead of using scientific notation, which makes the string slightly shorter. I suppose this means that someone designing a model with a slightly larger input image size would be unable to use ImageDeserializer.mean()...or is there a way to make OpenCV tolerate longer strings?

I also noticed that the RGB channels in the the [CIFAR-10 example](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet/Python) are not permuted to BGR before writing the XML file. My current understanding is that OpenCV expects data in BGR format...am I mistaken, or should this be changed?

Thanks in advance!

**Comment by cha-zhang** [comment]
Make sure you put a new line after each 4-5 elements of the vector(<data> 4 numbers crlf 4 numbers crlf…. </data>) Then the mean file should be parsed without problems.

**Comment by mawah** [comment]
Will do @cha-zhang!
