### ISSUE TITLE
Where is "CNTK/cntk"?

### ISSUE THREAD

**Issue by QinZibo** [Microsoft/CNTK#1526]
I can`t find the folders "CNTK/cntk",

# For a Python 3.5 based version:
pip install --upgrade ./cntk/python/cntk-2.0.beta12.0-cp35-cp35m-linux_x86_64.whl
# For a Python 3.4 based version:
pip install --upgrade ./cntk/python/cntk-2.0.beta12.0-cp34-cp34m-linux_x86_64.whl
# For a Python 2.7 based version:
pip install --upgrade ./cntk/python/cntk-2.0.beta12.0-cp27-cp27mu-linux_x86_64.whl

so,where is the cntk folder?

**Comment by alexeyo26** [comment]
I trust it you are installing v. 2.0 Beta 12 from Binary Download. Correct? If yes, then, if would be the top folder of the distribution. For example if you copy GPU distribution to /home, you have a file '/home/CNTK-2-0-beta12-0-Linux-64bit-GPU.tar.gz', then after extracting you'll get a folder `/home/cntk`. *Inside* that directory you will find everything, including the folder `/home/cntk/cntk/python`. So for the commands above to work you need to do something like 
```
cd /home/cntk
pip install --upgrade ./cntk/python/cntk-2.0.beta12.0-cp35-cp35m-linux_x86_64.whl
```
Hope it fixes it.

**Comment by QinZibo** [comment]
why in the branch master,I also don't find the folded **CNTK/cntk**? 
Because the network is not goog,I downloaded the binary zip file
from https://github.com/Microsoft/CNTK/archive/master.zip,.
Then following the page https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Manual.
But when I did the Step 3,the folder **cntk** wasn't found,I just could't going on the Step 3,

> IOError: [Errno 2] No such file or directory: '/home/qinzibo/CNTK-master/cntk/py                                                                               thon/cntk-2.0.beta12.0-cp27-cp27mu-linux_x86_64.whl'

**Comment by alexeyo26** [comment]
The file you have downloaded is a copy of the current CNTK ***code***-base. You may want to use it if you build CNTK from source code yourself.

The Wiki page you are referring to (https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Manual) explains how to install CNTK from a ***binary distribution package***. To get such package, please go to https://github.com/Microsoft/CNTK/releases and follow the instructions how to get the required version.

**Comment by QinZibo** [comment]
Thanks a lot! I am so careless!

**Comment by alexeyo26** [comment]
No problem. Enjoy CNTK!
