### ISSUE TITLE
Errors building CNTK.

### ISSUE THREAD

**Issue by cjliux** [Microsoft/CNTK#1527]
Today I believe environment variables have been well prepared and try to build cntk from source. I have follow the steps as is shown in `https://github.com/Microsoft/CNTK/wiki/Setup-Migrate-VS13-to-VS15`. But it failed. Following is the Error messages from vs2015:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	warning treated as error - no 'object' file generated	MathCUDA	c:\local\cub-1.6.4\cub\device\dispatch\dispatch_radix_sort.cuh	1081	

Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" --use-local-env --cl-version 2015 -Xcompiler /WX -ccbin "E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"  -IC:\local\cntk\Source\Common\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\local\cub-1.6.4" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"   -lineinfo --keep --keep-dir C:\local\cntk\x64\.build\Release\Source\Math\\MathCUDA -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=field_without_dll_interface" -Xcompiler "/wd 4819"   -use_fast_math -DNO_SYNC -DWIN32 -D_WINDOWS -D_USRDLL -DMATH_EXPORTS -DUSE_CUDNN -D_UNICODE -DUNICODE -DNDEBUG -Xcompiler "/EHsc /W4 /nologo /O2 /FS /Zi  /MD " -o C:\local\cntk\x64\.build\Release\Source\Math\\MathCUDA\GPUMatrix.cu.obj "C:\local\cntk\Source\Math\GPUMatrix.cu"" exited with code 2.	MathCUDA	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets	687	

Error	C1002	compiler is out of heap space in pass 2	Math	c:\local\cntk\source\math\cpumatrix.cpp	6443	

Error	D8040	error creating or communicating with child process	Math	C:\local\cntk\Source\Math\cl	1	

Error	LNK1181	cannot open input file 'Math.lib'	SparsePCReader	C:\local\cntk\Source\Readers\SparsePCReader\LINK	1	

and some other errors similar with the last one. I have checked the environment variables and they are just right. Where's the problem?

**Comment by sayanpa** [comment]
We made a bunch of changes since you reported this. Sorry it took a while to respond. We are making efforts to reduce our turnaround time. Would appreciate if you could try out V2 release. Please reopen the issue if it still persists.
