### ISSUE TITLE
cntk.io module can't support HTKFeatureDeserializer now?

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1528]
The wiki pages claim cntk in python version have all built-in readers.
But I can't import " HTKFeatureDeserializer and HTKMLFDeserializer" from " cntk.io".
In help(cntk.io), it seems current deserializer only have "CTFDeserializer" and "ImageDeserializer"?
is that true? 
and how can i read htkdata with python bindings as the same as using ndl or brainscript?(btw I use the linux binary of version2.0 with py=2.7)
Much thanks！

**Comment by staplesinLA** [comment]
I updated the beta11 to beta12, it can read htkdata now.
Previously with ndl/bs,  some ops like Mean(), Invstd(),PerDimMeanVarDeNormalization() are very convenient for my regression problem.  Now the python binding seems not have direct methods to do the same things.
Are there will be added in the future?  @cha-zhang 
Is there any way to have flexible control steam in BS (to build models like GAN)？
Thanks！

**Comment by cha-zhang** [comment]
It should not be difficult. Have you tried directly using numpy to do these ops? 

We already have a GAN example. Have you checked it out? 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206B_DCGAN.ipynb

**Comment by staplesinLA** [comment]
Thanks, I changed to python API and that's why I closed it.  But I still have a question about this example, I have addressed it in #1538. Hope you can give some suggestions.
