### ISSUE TITLE
Runtime error in restoring a model (function 'restore_from_checkpoint')

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#1533]
I've used `restore_from_checkpoint` method when restoring model. It worked well before but suddenly does not work now with the following error message:

> RuntimeError: Required key 'version' is not found in the dictionary. 
> [CALL STACK]
>     > CNTK::DeviceDescriptor::  UseDefaultDevice
>     - CNTK::DeviceDescriptor::  UseDefaultDevice
>     - CNTK::Function::  Deserialize
>     - CNTK::Function::  RestoreFromCheckpoint
>     - CNTK::Function::  RestoreModel
>     - CNTK::Trainer::  RestoreFromCheckpoint
>     - PyInit__cntk_py
>     - PyCFunction_Call
>     - PyEval_GetFuncDesc
>     - PyEval_EvalFrameEx
>     - PyEval_GetFuncDesc
>     - PyEval_GetFuncDesc
>     - PyEval_EvalFrameEx
>     - PyEval_EvalFrameEx
>     - PyEval_GetFuncDesc
>     - PyEval_GetFuncDesc

**Comment by 2wins** [comment]
When I use function `z.resotre_model`, the following similar error occurs

> ValueError: 'This' function parameters and restored function parameters do not have identical UIDs.
> [CALL STACK]
>     > CNTK::Function::  RestoreFromCheckpoint
>     - CNTK::Function::  RestoreModel
>     - PyInit__cntk_py
>     - PyCFunction_Call
>     - PyEval_GetFuncDesc
>     - PyEval_EvalFrameEx
>     - PyEval_GetFuncDesc
>     - PyEval_GetFuncDesc
>     - PyEval_EvalFrameEx
>     - PyEval_EvalFrameEx
>     - PyFunction_SetAnnotations
>     - PyObject_Call
>     - PyEval_GetFuncDesc
>     - PyEval_EvalFrameEx
>     - PyEval_EvalFrameEx
>     - PyEval_GetFuncDesc

**Comment by sayanpa** [comment]
Could you please repro the problem. Not knowing your setup. Please reopen the issue if it is not resolved with the V2 release.
