### ISSUE TITLE
cntk cannot even reshape a sparse tensor? Really?

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1534]
I define an explicitly **dense** input and try to reshape it from 2D to 1D.
What I actually get is an exception telling me that:
1) CNTK considers my input to be sparse, not dense
2) CNTK is unable to reshape a sparse tensor
3) Anything is going to be 3+D when you add the batch and sequence axes to it.

```
import numpy as np
import cntk as c

aSize = 4
bSize = 7
minibatchSize = 10

indices = np.random.choice(aSize, size=(minibatchSize, bSize))
oneHot = c.one_hot(indices, aSize)

input = c.input_variable(shape=(bSize, aSize), is_sparse = False)

reshaped = c.reshape(input, shape=(aSize * bSize)).eval({input: oneHot})

print(reshaped.shape)
```

> Traceback (most recent call last):
>   File "A:\_All\My.Creativity.ML\Notebooks\CNTK\VS\Scratch\Scratch\TensorReshape_problem.py", line 13, in <module>
>     reshaped = c.reshape(input, shape=(aSize * bSize)).eval({input: oneHot})
>   File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 221, in eval
>     _, output_map = self.forward(arguments, self.outputs, device=device)
>   File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\utils\swig_helper.py", line 62, in wrapper
>     result = f(*args, **kwds)
>   File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 299, in forward
>     keep_for_backward)
>   File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 1308, in _forward
>     return _cntk_py.Function__forward(self, *args)
> RuntimeError: AsMatrix: Sparse tensors are not supported unless they are 1D or 2D matrices.

**Comment by hajix** [comment]
Did you read the disclaimer at the first github page?

**Comment by Ark-kun** [comment]
> Do you read the disclaimer at the first github page?
Yes, I did. I understand that there might be bugs.
And they will be there forever unless we report them, just as I did.

**Comment by cha-zhang** [comment]
Thank you for reporting this. We are investigating it.

**Comment by sayanpa** [comment]
Please see the error message in V2 and reopen the issue. Appreciate your help. Closing this issue for now as the issue has been open for a while and the error message you get now is actionable.
