### ISSUE TITLE
Another crash.......

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1536]
```
input = c.input_variable(shape=(1))
result = (input * 1.0).eval({input: np.array([1.0, 2.0, 3.0]) })
```

**Comment by Master76** [comment]
Hi Ark-kun,
     I guess you mean this:
```python
     input = c.input_variable(shape=(1))
     result = (input * 1.0).eval({input: np.asarray([[1.0], [2.0], [3.0]], dtype=np.float32) })
```
     The data you provide is not in the correct shape.

**Comment by Ark-kun** [comment]
I know the workaround.
My point is that CNTK should never ever crash python or my PC.
When there is an error, the library needs to throw exception, not corrupt python heap memory.

**Comment by bklooste** [comment]
Is that possible ? Its non memory safe native code executing , python is just the wrapper. It would need every condition  /bug to be handled beforehand.

**Comment by Ark-kun** [comment]
It's possible to analyze the behavior of deterministic programs of length of less than 100 symbols and fix the issues detected.

**Comment by mahilleb-msft** [comment]
@ark-kun - with CNTK 2.0 a ValueError is raised. Please re-open if you're still seeing this...

Thanks, Mark
