### ISSUE TITLE
Can BS script support generative adversarial networks？

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1538]
Don't know whether bs has flexible control streams to build GAN.

**Comment by cha-zhang** [comment]
No. It's not flexible enough. Please use Python instead. 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206_Basic_GAN.ipynb

**Comment by staplesinLA** [comment]
Thanks @cha-zhang ! But I have a question about the GAN tutorial. A minus symbol is added in front of the D_loss which is different from the paper equation . 
I suppose it's convenient for the learner to minimize the loss, so in practice  the normal training process would have a decreasing D_loss.
Why the log in the tutorial shows that the D_loss increases from 0.327561 to 0.755113 ? Doesn't  it fail?

**Comment by sayanpa** [comment]
Closing this issue since it has been open for more than 3 months.
