### ISSUE TITLE
fatal error C1002: compiler is out of heap space in pass 2

### ISSUE THREAD

**Issue by ranigb** [Microsoft/CNTK#1542]
I am trying to build cntk on windows with VS2015 update 3. I am trying to build a x64 release, cpu-only, version of CNTK. The build files to generate Math.lib:

LINK : fatal error LNK1181: cannot open input file 'Math.lib'

Prior to this message, I see a message: 

...cntk\source\math\cpumatrix.cpp(6626): fatal error C1002: compiler is out of heap space in pass 2

I tried it several times on different machines with the same results. What can be done to overcome this issue?

Thanks

**Comment by aarotech** [comment]
I'm also encountering the same issue.  I've noticed that if I run it on a machine that is not running anything else while this file is compiled then sometimes it can be compiled without running out of heap space so it seems to be a memory space related problem.  It seems to take an excessive amount of memory to compile just that one file.  I presently think of this as a bug.

**Comment by ranigb** [comment]
I tried compiling on a box with 64GB Ram (56GB free) and I am getting the same response.

**Comment by aarotech** [comment]
Thin in your case you may be able to resolve this by using the /Zm parameter.

**Comment by mahilleb-msft** [comment]
Hey @aarotech  and @ranigb ,
  this should have been fixed with ed2f97311c738b106b06c293c1deb97d6db5309b a while back.
  Please re-open if you see it occurring on latest master; or open a new issues if you run into other problems.

  Thanks, Mark
