### ISSUE TITLE
BOOST install instructions were missing two key dependencies

### ISSUE THREAD

**Issue by yaronyg** [Microsoft/CNTK#1547]
I'm following https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux using Ubuntu 16.04 when I got to the section on boost I got two 'No such file or directory' errors, one for bzlib.h and the other for pyconfig.h. I was able to install these missing dependencies via:

```
sudo apt-get install libbz2-dev
sudo apt-get install python-dev
```

I would have just submitted a PR but near as I can tell there is no way for a non-contributor to edit the wiki (which seems kind of odd so I'm guessing I'm just missing something).

**Comment by chrisbasoglu** [comment]
Fixed
