### ISSUE TITLE
ImportError: No module named 'cntk._cntk_py'

### ISSUE THREAD

**Issue by PFSWcas** [Microsoft/CNTK#1549]
Today, After installation, when I try the CNTK Python API, I get the following error.

Traceback (most recent call last):
  File "D:\repos\cntk\bindings\python\cntk\cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\local\Anaconda3-4.2.0\envs\cntk-py35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FeedForwardNet.py", line 10, in <module>
    from cntk.device import cpu, set_default_device
  File "D:\repos\cntk\bindings\python\cntk\__init__.py", line 11, in <module>
    from .core import *
  File "D:\repos\cntk\bindings\python\cntk\core.py", line 10, in <module>
    from . import cntk_py
  File "D:\repos\cntk\bindings\python\cntk\cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "D:\repos\cntk\bindings\python\cntk\cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "C:\local\Anaconda3-4.2.0\envs\cntk-py35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed

Anybody know how to fix this?

**Comment by yaronyg** [comment]
I just got the identical error but on Linux:

![image](https://cloud.githubusercontent.com/assets/1480964/23484580/669b7042-fe8c-11e6-85b0-2a1fea0df2ce.png)

**Comment by PFSWcas** [comment]
Hello, @yaronyg, do you fix this problem? I tried to rebuild CNTK and reinstall anaconda3, but the problem still exits. I search the module, CNTK._cntk_py, but I do not find it.

**Comment by yaronyg** [comment]
How I resolved this:
Step 1 - Open a terminal window
Step 2 - Do all the Python building magic (I had issues with the instructions, see #1553 which also contains a link to the instructions I issued on my machine)
Step 3 - Make sure to run 'source activate cntk-py27' (or whatever version of python you are using)
Step 4 - IN THE SAME TERMINAL WINDOW, issue the python commands.

That is what worked for me.

**Comment by PFSWcas** [comment]
Thanks for your response, @yaronyg , but my operation system is Win 10. I read and try your solution, but the problem still exists. Do you have any other suggestions?

**Comment by yaronyg** [comment]
Sigh... unfortunately no. :( I'm 100% new to CNTK and have only tried it on Linux. It just seems so odd that you would get exactly the same error I got but not for the same reason.

**Comment by PFSWcas** [comment]
In the path C:\repos\cntk\bindings\python, I find a file named _cntk_py.cp35-win_amd64.pyd. Did you have a file named _cntk_py.py or _cntk_py.pyd in your building path? @yaronyg 
Thanks!

**Comment by yaronyg** [comment]
I searched for *cntk_py* in my repo and while I have a number of files that contain cntk_py none start with _. But I'm not much of a Python person. My guess is that there is some naming standard here that translates to the right file. But in my case only once I activate the right python environment.

**Comment by Swordsemperor** [comment]
Hi. @PFSWcas Did you solve the problem? I met the same error.

**Comment by HnlyWk** [comment]
![error](https://cloud.githubusercontent.com/assets/25994638/24533681/d54587f4-15fb-11e7-9663-452d342aec00.PNG)

**Comment by PFSWcas** [comment]
Yes, I fixed this problem. The solution is very easy. I add 'C:\repos\cntk\x64\Release' to the system variable PATH. Then it build successfully. @HnlyWk

**Comment by vmazalov** [comment]
This issue can also happen if you try to activate an environment that doesn't match your python version.

**Comment by HnlyWk** [comment]
@PFSWcas @vmazalov 
Thanks. I installed python 3.4 after uninstalling 3.5, and it works!

**Comment by ant0nsc** [comment]
I ran into the same issue, using CNTK on Win10. Just to confirm @PFSWcas, my python script ran fine after I added the path to the CNTK executable to the PATH system variable.

**Comment by sayanpa** [comment]
Looks like this issue is settled. Closing this since > 3 months of inactivity

**Comment by ANUDAVIS** [comment]
@PFSWcas 
I am using python 3.5 and cntk version of 2.5.1
I got the same error while doing in jupyter notebook in ubuntu.
How can I solve this error?
And how can I add that path to the system variable PATH.  I had cntk\Release folder with README.md file.
