### ISSUE TITLE
How to output node value?

### ISSUE THREAD

**Issue by bb2103** [Microsoft/CNTK#155]
i got trained model. 
But i cannot found a way to output network node value(DeepID)?
any ideas, the example of 2d is confused to me。

**Comment by frankseide** [comment]
By default, “write” will write nodes that are tagged as “output” in the network.

You can select that different nodes get output by the outputNodeNames option. Could you try to add an option like this:

    outputNodeNames = DeepID

Thanks,

Frank

**Comment by bb2103** [comment]
Sry, im mean how to call cntk to get output value.
In 2d example, its only add one output stage, you can just run it to get output.
I feel its hard to Understand.
Its there any steps like 'Caffe.FORWARD()'

**Comment by frankseide** [comment]
If you want to write values to a file, please use a “write” command. It is similar to the “test” command, but change action to “write” and add a parameter outputPath = “…” with your target pathname.

I added an example to Simple.cntk, but it may take until Monday to get merged. Here is a simplified version:

Simple_Demo_Output=[
    action = "write"

    # Parameter values for the reader
    reader = [
        readerType = "UCIFastReader"
        file = "$DataDir$/SimpleDataTest.txt"
        randomize = "none"

        features = [
            dim = 2
            start = 0
        ]

        labels = [
            start = 2
            dim = 1
            labelDim = 2
            labelMappingFile = "$DataDir$/SimpleMapping.txt"
        ]
    ]

    outputNodeNames = PosteriorProb : labels    # Select the nodes to print. If this is not given, the nodes tagged as "output" are printed instead.

    outputPath = "$OutputDir$/SimpleOutput"     # Path to write to. ".NODENAME" will be appended.
    #outputPath = "-"                           # As an alternative, this prints to stdout.
]

**Comment by bb2103** [comment]
3ks for ur patience.
The last question, is the ndl network file is needed?

**Comment by frankseide** [comment]
NDL allows you to define custom networks. For the most standard configurations, you can use the SimpleNetworkBuilder.

**Comment by pinzhang10** [comment]
@frankseide 

Hi, for the code " outputNodeNames = PosteriorProb : labels", is PosteriorProb defined in cntk file or ndl file? If I want to output some intermediate nodes like the nodes "A" between layers, how should I use the name in ndl file for outputNodeNames ?

Thank you!

**Comment by dongyu888** [comment]
You need to use the name in the model which may be different from the name in the ndl due to macros used. You can find the correct node name by checking the validation log or dumping the node names using the dumpnode command.

**Comment by pinzhang10** [comment]
@dongyu888 
Thank you so much for your quick reply. I got the node names by checking the validation log. Really appreciate your great help! 

Pin
