### ISSUE TITLE
Python API change in beta 12 Composite Reader

### ISSUE THREAD

**Issue by Vedaevolution** [Microsoft/CNTK#1552]
Dear Community,

i'm trying to create a composite reader and it worked in beta 11. In beta 12 it doesn't.

I imported the transforms so i can simply use "scale()".
The new version i tried after modfiying the script for version 12 is the following:

    scale_image = scale(width=width,
                                    height=height,
                                    channels=channels,
                                    scale_mode="pad",
                                    pad_value=114,
                                    interpolations='linear')
    scale_mask = scale(width=width_mask,
                                     height=height_mask,
                                     channels=channels,
                                     scale_mode="pad",
                                     pad_value=114,
                                     interpolations='linear')

    image_source = ImageDeserializer(os.path.join(path, "images_map.txt"), cntk.io.StreamDefs(
        features=cntk.io.StreamDef(field='image', shape=(224, 224, 3), transforms=[scale_image])
    ))

    #image_source.ignore_labels()
    #image_source.map_features('features')

    mask_source = ImageDeserializer(os.path.join(path, "images_mask_map.txt"), cntk.io.StreamDefs(
        features=cntk.io.StreamDef(field='image', shape=(224, 224, 3), transforms=[scale_mask])
    ))

    #mask_source.ignore_labels()
    #mask_source.map_features('mask')

    return MinibatchSource([image_source, mask_source]) #error line

With that i get the error:

    RuntimeError: Please specify the type of the 'features' stream. You can use 'Cast' transform for that.

What do i need to change? I can' find it in the documentation or an example.

Thank you very much
Stephen

**Comment by eldakms** [comment]
Hi Vedaevolution,

Could you please give different names to the feature streams, i.e.
image_source = ImageDeserializer(os.path.join(path, "images_map.txt"), cntk.io.StreamDefs(
    **features1**=cntk.io.StreamDef(field='image', shape=(224, 224, 3), transforms=[scale_image])
))
...
mask_source = ImageDeserializer(os.path.join(path, "images_mask_map.txt"), cntk.io.StreamDefs(
    **features2**=cntk.io.StreamDef(field='image', shape=(224, 224, 3), transforms=[scale_mask])
))

and then in the mapping:
input_map = {
   input_var1: source.streams.features1,
   input_var1: source.streams.features2,
}

The error message is cryptic though, I will make sure we correct this.
Thanks!

**Comment by eldakms** [comment]
I have corrected the error message to be explicit that streams with the same name are not allowed between different deserializers. The change has been integrated to master. Thanks!

**Comment by Vedaevolution** [comment]
Thank you very much!

I appriciate the CNTK Framework and this helps a lot.

Best Regards
vedaevolution
