### ISSUE TITLE
Needed fixes for Python instructions on Linux

### ISSUE THREAD

**Issue by yaronyg** [Microsoft/CNTK#1553]
This is really a continuation of #1547. In going through the Python section of https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux I ran into a few issues that caused unnecessary grief.

__Recursive GIT clone__ - In order to run the python instructions correctly one has to clone the CNTK repo. But the correct instructions for this are at the end of the document. Specifically, one has to do a recursive clone. I didn't realize this and it caused me time to figure it out. At a minimum it would be nice to call this problem out and please at least put a forward link to the section on how to do the clone inside of the Python instructions since the instructions on how to handle the clone properly come after the Python section.

__Missing PCRE Install__ - The instructions in step 1 say to run swig_install.sh but for that command to work one has to have PCRE installed, specifically 'sudo apt-get install libpcre3-dev' (or at least that fixed the problem for me). It would be good to throw in a mention of this.

__Mentioning how to install Anaconda would be nice__ - The file that is linked to is a sh file which is fine. And yes it's obvious it should be run but would it really hurt to help the overwhelmed reader out by pointing out that once one downloads the link one should run it with 'bash X' where X is the file name?

__Please explain 'activate' a bit more forcefully__ - I and a bunch of other people (see #1194, #1361 and #1549) have gotten confused over the fact that the Python logic only works if one runs it in a terminal window where the source activate command is running. It would be really useful to much more forcefully point out in the directions the necessity of getting this right.

__Better examples for configure would really be useful__ - The directions for step 3 "Build Python Package" were a bit confusing for me. It really would have helped if they were shown at a command line. In other words "CNTK/$ configure --with-swig=$HOME/swig-3.0.10/root --with-py35-path=$HOME/anaconda3/envs/cntk-py35"

__Missing instructions to set BOOST_ROOT__ - I suppose this really belongs in the section about the Boost Library but it didn't blow up on me until I tried to build Multiverso. We have to have BOOST_ROOT set to, in my case, /usr/local/boost-1.60.0. Ideally this should be in the .bashrc.

__Missing instructions to build Multiverso__ - The next step is to call make but that will fail if one hasn't built Multiverso. This happened to me when make failed on '/usr/bin/ld: cannot find -lmultiverso'. This led me to https://github.com/Microsoft/multiverso/wiki/Setup-Multiverso which led me to run:
```
cd ~/CNTK/Source/Multiverso
mkdir build && cd build
cmake .. && make && sudo make install
```
That fixed the missing library issue. Note that the need to build Multiverso isn't called out anywhere else in the doc.

__A clearer example for make would help too__ - In the final part of step 3 there is text about calling make but again it would make everything a lot clearer if there was an example like 'CNTK/$ make -j $(nproc) all'.

__Please remind people to put environment variables into ~/.bashrc__ - The current instructions just talk about exporting the PYTHONPATH and LD_LIBRARY_PATH variables but it would be good to mention that they should be added to the .bashrc and to specify them in a way that will work there ($PWD won't work in a .bashrc).

**Comment by yaronyg** [comment]
Just for documentation purposes [here](https://gist.github.com/yaronyg/6a9f7211aad7d8d73aee86386cdfc0ee) are the instructions I used to successfully set up my Python environment and run the test.

**Comment by kaisark** [comment]
Can you install without anaconda or mini conda by just using python virtual environments???

**Comment by vinbo** [comment]
I had the same problem, and have not seen any official response yet, still confusing

**Comment by thiagocrepaldi** [comment]
@kaisark Yes, you can. You can look at the YML file in the <cntk>/Scripts/install/{windows,linux}/conda-*.yml to get a list of dependencies you would need to install to run the tutorials examples
