### ISSUE TITLE
When to support C# API ?

### ISSUE THREAD

**Issue by hellolv** [Microsoft/CNTK#1556]
When to support C# API ?

**Comment by cha-zhang** [comment]
Are you looking for using C# to train, or evaluation? 

For evaluation, we already support C#: 
https://github.com/Microsoft/CNTK/wiki/CNTK-Eval-Examples

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by zhouwangzw** [comment]
Closing this issue, as the training for .NET is discussed in another issue #960
