### ISSUE TITLE
Feature Request: SquaredError with several axes 

### ISSUE THREAD

**Issue by mdmdmd9876** [Microsoft/CNTK#1558]
Hi guys,
I wrote a tool that evaluates pictures after loading an already trained model in a c++ mex file using the CNTKLibrary. The thing is that loading a trained model only works for models where the labels and outputs are in form of just one axis. When trying to load a model with label dimensions of something like 96x96 (for example when comparing to pictures with each other) the error: What() is:The shape of input operands for the SquaredError operation should have at most one axis is displayed. 
Would be great if the SquaredError Function would also support several axes. 
Thanks in advance 
Maximilian

**Comment by tilmanseide** [comment]
You can implement that yourself as a formula. For example:

diff = (y - x)
sqr = diff * diff   # element-wise product
err = reduce_sum(axis=2)  # will compute sum_k sqr[i,j,k]

**Comment by sayanpa** [comment]
Assuming tilmanseide's comment help close the issue. Closing this issue for now since it is over 3 months. Feel free to open new issue if help is needed.
