### ISSUE TITLE
Does parallel train support sparse matrix?

### ISSUE THREAD

**Issue by augusterodin** [Microsoft/CNTK#156]
Hi all,

When I tried to run CNTK with multiple GPU machines on sparse input data, I meet the error below. But for dense input data, it seems worked fine. Dose it mean CNTK do not support parallel train with GPU sparse matrix now?

[CALL STACK]
    >Microsoft::MSR::CNTK::TensorView<double>::DoTernaryOpOf
    -Microsoft::MSR::CNTK::GPUSparseMatrix<float>::Reshape
    -Microsoft::MSR::CNTK::Matrix<float>::Reshape
    -Microsoft::MSR::CNTK::Matrix<float>::Reshaped
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -BaseThreadInitThunk
    -RtlUserThreadStart

EXCEPTION occurred: GPUSparseMatrix::Reshape: Cannot Reshape since the buffer is managed externally.

I add ParallelTrain=true in the command line the add below parameter in SGD section in config file.
ParallelTrain=[
    parallelizationMethod=DataParallelSGD
]

@bmitra-msft @frankseide

**Comment by frankseide** [comment]
If your input is sparse (one-hot typically), then the gradient is block-sparse in that it stores non-zero columns.

1-bit SGD is only implemented for dense matrices indeed. This should be caught higher up and reported with a proper error message.

Several users have run into this, so I hope we can address this on our side. I have raised the issue. Until then, the only workaround is to use dense matrices, which will not be efficient, or model averaging.

**Comment by augusterodin** [comment]
@frankseide I didn't use 1-bit SGD, but still would meet such issue?

**Comment by wxm71** [comment]
@frankseide 

>  the only workaround is to use dense matrices, which will not be efficient, or model averaging.

I'm running LM with lstm, which matrix is the sparse one U refered? and, how to change it to a dense matrix? Should I seek reader defined in Source/Readers/LMSequenceReader?

**Comment by cha-zhang** [comment]
I'm closing this issue since it's been too old. Please update to the latest CNTK and see if your problem has been resolved. If not, please feel free to open a new issue.
