### ISSUE TITLE
if cntk only support win10?

### ISSUE THREAD

**Issue by ericyan71** [Microsoft/CNTK#1562]
hello, I donwload the lastest version of cntk, binary mode, when I run it, it report error:
crt not initialized, I search online and find somebody say that cntk need win10, I wonder if the cntk only run under win10, thanks!

**Comment by bencherian** [comment]
I think it isn't tested on Windows 7 but I've run with it on Win 7 without issues. Did you install everything in the prerequisites folder after unzipping the binary distribution? Based on your error, it sounds like you never installed VS2015 C++ runtime.

**Comment by pc2005** [comment]
I run into the same issue on Win7-64. 

My CNTK was working OK two weeks back, now it shows the CRT init error, after installing some updates of office.

@bencherian vcdist included in prerequisite folder is 14.0.23026, while I have 14.024215.1 already installed in my system.

**Comment by xjock** [comment]
It is so sad

**Comment by sayanpa** [comment]
I am sorry to hear about your setup not working. CNTK V2 released in early June has been extensively tested though not on Win7. You can try installing the python API's with ease. Please reopen this issue if you need help.
