### ISSUE TITLE
how to use cuda7.5 on cntk:CNTK for Linux v.2.0 Beta 12 GPU?

### ISSUE THREAD

**Issue by XiaotaoChen** [Microsoft/CNTK#1563]
All.
hi, i install cntk(CNTK for Linux v.2.0 Beta 12 GPU https://cntk.ai/dllg-2.0.beta12.0.html) on my service correctly,And the service had installed cuda7.5. i run several examples on cntk it exec correctly without using gpu. However, when run example with gpu:`cntk configFile=lr_bs.cntk makeMode=false command=Train device_Id=auto`
 it shows:
```
(/usr/local/softwares/Anaconda3/envs/cntk-py35) root@stack24-51:/usr/local/softwares/cntk/Tutorials/HelloWorld-LogisticRegression# cntk configFile=lr_bs.cntk makeMode=false command=Train device_Id=auto
CNTK 2.0.beta12.0 (HEAD bfd2a3, Feb 22 2017 13:30:38) on stack24-51 at 2017/03/04 13:18:19

cntk  configFile=lr_bs.cntk  makeMode=false  command=Train  device_Id=auto
-------------------------------------------------------------------
Build info: 

		Built time: Feb 22 2017 13:29:13
		Last modified date: Wed Feb 22 06:41:00 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: /usr/local/cuda-8.0
		CUB_PATH: /usr/local/cub-1.4.1
		CUDNN_PATH: /usr/local/cudnn-5.1
		Build Branch: HEAD
		Build SHA1: bfd2a348763305e37eca733cf9a659d22514eefd
		Built by Source/CNTK/buildinfo.h$$0 on 81c63f14ef8b
		Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux
		MPI distribution: Open MPI
		MPI version: 1.10.3
-------------------------------------------------------------------
No GPUs found

##############################################################################
#                                                                            #
# Train command (train action)                                               #
#                                                                            #
##############################################################################


Model has 9 nodes. Using CPU.
```
how can i solve it  to guide cntk use cuda7.5?

**Comment by alexeyo26** [comment]
If you use binary CNTK distribution, then it was compiled with CUDA 8.0. We have switched from CUDA 7.5 quite a while ago. I'm afraid that the only way to use CNTK in its latest state with CUDA 7.5 is to ***try*** and build it from sources using CUDA 7.5. I emphasize the word "try", because there is a chance that you bump into something, that it is in CNTK code today, but not supported by CUDA 7.5.

**Comment by alexeyo26** [comment]
Oh, and one more thing. If you have on your system CUDA 7.5 installed and you need it there, then maybe you can try our [Docker Images](https://github.com/Microsoft/CNTK/wiki/CNTK-Docker-Containers). Thus you will be able to use CNTK without affecting your current installation.

**Comment by XiaotaoChen** [comment]
i,clone the cntk from github,and compile it just now,firstly,i confgiure it by executing `../../configure --with-mkl=/usr/local/CNTKCustomMKL --asgd=no`
and it shows that:
```
Defaulting to --with-buildtype=release
Found cuda at /usr/local/cuda-7.5
Found GDK include at /usr/include/nvidia/gdk
Found GDK NVML library at /usr/src/gdk/nvml/lib
Found CUB at /usr/local/cub-1.4.1
Found cuDNN at /usr/local/cudnn-5.1
Found OpenCV at /usr
Found libzip at /usr/local
Cannot locate Kaldi files
Kaldi2Reader will NOT be built.
Found Boost at /usr
Found Protocol Buffers at /usr/local
Found MPI at /usr/local/mpi
Generating /usr/local/cntk/build/release/Config.make
Generating /usr/local/cntk/build/release/Makefile
run
>make -j $(nproc) all
to build
```
then make it executing:`make -j"$(($(nproc)  - 2))" all`
it tells many errors:
```
/usr/include/opencv2/core/mat.hpp: At global scope:
/usr/include/opencv2/core/mat.hpp:1220:28: error: ‘Mat’ does not name a type
     explicit MatExpr(const Mat& m);
                            ^
/usr/include/opencv2/core/mat.hpp:1220:34: error: only declarations of constructors can be ‘explicit’
     explicit MatExpr(const Mat& m);
....
make[1]: *** [/usr/local/cntk/build/release/.build/Source/Readers/ImageReader/Exports.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm Source/CNTKv2LibraryDll/proto/CNTK.pb.cc Source/CNTKv2LibraryDll/tensorboard/tensorboard.pb.cc
make[1]: Leaving directory `/usr/local/cntk'
make: *** [all] Error 2
```
i don't know why. maybe the current cntk must be used with cuda8.
###about the docker images.
Firstly,i pull the 'Microsoft/cntk:latest' images,and executed `nvidia-docker run --rm microsoft/cntk nvidia-smi`
it shows:
```
nvidia-docker | 2017/03/05 11:53:15 Error: unsupported CUDA version: driver 7.5 < image 8.0
```
Then,i go to find a image with cuda7.5.named:'microsoft/cntk:1.7.2-runtime-gpu-cuda7.5-cudnn5.1',and executed last code it work.however,this image have no anaconda, Ark-kun say that the cntk's version 1 did not have python API.so it didn't work for me.can you give me an cntk image include cuda7.5 and anaconda? thanks @alexeyo26

**Comment by alexeyo26** [comment]
@XiaotaoChen. we don't have public images of 2.0 with CUDA 7.5. The latest Linux version that we built and tested with CUDA 7.5 was 2.0 Beta 5. You may get it from [Release Page](https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta5.0).

If you want to build from sources, then you need to checkout the right tag, namely:
```
git checkout v2.0.beta5.0
```
and then do `configure` and `make`.

**Comment by XiaotaoChen** [comment]
@alexeyo26 i download the image,the tag is 'CNTK for Windows v.2.0 Beta 5 GPU'  
And i run this images it shows 
```
nvidia-docker | 2017/03/05 11:53:15 Error: unsupported CUDA version: driver 7.5 < image 8.0
```
i thought this image was built with cuda-8.0,not 7.5

**Comment by alexeyo26** [comment]
@XiaotaoChen I believe you have downloaded **binary package**, NOT docker image (we do not have Docker Images for 2.0 Beta 5).

Unpack it in your **host system**, go to `cntk/Scripts/install/linux` and execute `install-cntk.sh`

**Comment by alexeyo26** [comment]
@XiaotaoChen Do you still have the issue?
