### ISSUE TITLE
Cython binaries are missing for FastRCNN scenario with Python 3.5 on Linux 

### ISSUE THREAD

**Issue by nadavbar** [Microsoft/CNTK#1564]
When trying to run the FastRCNN code on the latest CNTK with python 3.5 installation, I get the following error message: 

```
/home/nadavbar/code/CNTK/Examples/Image/Detection/FastRCNN/fastRCNN/imdb.py in <module>()
     14 
     15 import sys
     16 from .utils.cython_bbox import bbox_overlaps
     17 
     18 class imdb(object):

ImportError: No module named 'fastRCNN.utils.cython_bbox'
```

When looking at the following path: https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN/fastRCNN/utils
It seems like the existing .so files are only supported for python 3.4

**Comment by cha-zhang** [comment]
Indeed. You need to recompile cython_bbox from the source for Python 3.5 yourself. Sorry for the trouble.

**Comment by nadavbar** [comment]
Thanks @cha-zhang, were can I find the source code for cython_bbox? It seems like the utils directory have only the compiled files.

**Comment by pkranen** [comment]
It is described in the tutorial here: https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression

**Comment by nadavbar** [comment]
@pkranen - Thanks for the clarification, I missed it for some reason..

**Comment by mvc12593** [comment]
Hi all,
I have just started into Python and DL recently and trying to run this example on Ubuntu 16.04.
I am seeing the same error " ImportError: No module named 'fastRCNN.utils.cython_bbox' " . I also checked the URL mentioned by @pkranen https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression but the page is empty now. 

Any help would be appreciated
Thanks

**Comment by mvc12593** [comment]
Solution at URL mentioned by @pkranen  is now at following URL

https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN#pre-compiled-binaries-for-bounding-box-regression-and-non-maximum-suppression
