### ISSUE TITLE
How to use per_dim_mean_variance in python? 

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1568]
How to use per_dim_mean_variance in python? I load the mean-invstd data from other files.
Where should use this function on?  The placeholder variable ? or the minibatch source?
As follows, I get an error:
NotImplementedError: Wrong number or type of arguments for overloaded function 'per_dim_mean_variance_normalize'.

——————————————————————————————————————————
fd = HTKFeatureDeserializer(StreamDefs(
    amazing_features = StreamDef(shape=feature_dim, context=(context,context), scp=features_file)))

ld = HTKFeatureDeserializer(StreamDefs(
    awesome_labels = StreamDef(shape=feature_dim, scp=labels_file)))

features = C.input_variable(((2*context+1)*feature_dim)) 
labels = C.input_variable((num_classes)) 
input_map={ features: reader.streams.amazing_features, labels: reader.streams.awesome_labels }

norm_feature = per_dim_mean_variance_normalize(fd, input_mean, input_invstd);
norm_labels = per_dim_mean_variance_normalize(ld, output_mean, output_invstd);
...
mb_data = reader.next_minibatch(mbsize, input_map=input_map)

**Comment by Master76** [comment]
Hi staplesinLA,

According to the BrainScript definition in CNTK.core.bs, as the following:
```BrainScript
PerDimMeanVarNormalization (x, mean, invStdDev) = (x - mean) .* invStdDev
```
i got the following for work around. I guess this may help you.
```python
def mean_variance_normalize(x):
    mean = C.reduce_mean(x)
    x0 = x - mean
    std = C.sqrt(C.reduce_mean(x0 * x0))
    inv_std_dev = 1 / std
    norm = per_dim_mean_variance_normalize(x0, inv_std_dev)
    return mean, inv_std_dev, norm

def per_dim_mean_variance_normalize(x0, inv_std_dev):
    return x0 * inv_std_dev
```

**Comment by staplesinLA** [comment]
@Master76 Thank a lot! The equations you write are exactly right.
What I don't understand is about the usage in Python API.
We want the global MVN through the whole corpus, so what the "x" is ?
How to present the whole corpus data (using built-in HTKreader)?

As I wrote above, is 'x' the "fd" and "ld", or is 'x' the mini-batch data?

**Comment by Master76** [comment]
@staplesinLA x is CNTK::Function or CNTK::Variable, for your case, it should be features and labels, I reckoned. 

You can also use like the following:
```python
h = c.layers.Dense(hidden_dim)(features) 
mean_h, inv_std_dev_h, norm_h = mean_variance_normalize(h)
# add other layers
```

**Comment by sayanpa** [comment]
There hasn't been any activity on this thread for a while. Closing this for now. Please reopen the issue if more help is needed.
