### ISSUE TITLE
PerDimMeanVarDeNormalization can not be found in v2 evaluation lib

### ISSUE THREAD

**Issue by boren-ms** [Microsoft/CNTK#1571]
When I am using the v2 c# interface to evaluate my previously trained model by BrainScript. I met the exception as below. It seems that the PerDimMeanVarDeNormalization function is not defined in the v2 interface.

unsupported ComputationNode with OperationName='PerDimMeanVarDeNormalization' found when loading legacy CNTK model.
This is likely a deprecated operation; loading Brainscript/NDL models that contain deprecated operations, is not supported in Python/C++ API.
Please refer to CNTK documentation and edit/modify your Brainscript model/script to replace the deprecated operation with a supported operation.

Any help will be appreciated.

**Comment by zhouwangzw** [comment]
As the error message indicated, PerDimMeanVarDeNormalization is a deprecated operation, loading BrainScript model containing deprectead operators is unsupported by V2 API. You may need to change your Brainscript to avoid using deprecated operations, or using the V1 EvalDll interface to evaluate the mode.

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Feel free to reopen it if needed. Thanks!
