### ISSUE TITLE
CURAND failure 105 and Python

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#1574]
Hi,
I am plagued by these errors. According to https://github.com/Microsoft/CNTK/issues/444, the solution is to do initialization on CPU, but this option disappeared from the Python APIs.

CURAND failure 105: (see curand.h & look for curandStatus or CURAND_STATUS_xxx) ; GPU=0 ; hostname=ROSIE ; expr=curandGenerateNormal(((curandGenerator_t*) s_curandGenerator)[0], reinterpret_cast<float*>(Data()), GetNumElements(), (float) mean, (float) sigma)
Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-37-ef862344a57f>", line 5, in <module>
    trainer.train_minibatch(data)                                   # update model with it
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\trainer.py", line 120, in train_minibatch
    arguments, device)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 2022, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: CURAND failure 105: (see curand.h & look for curandStatus or CURAND_STATUS_xxx) ; GPU=0 ; hostname=ROSIE ; expr=curandGenerateNormal(((curandGenerator_t*) s_curandGenerator)[0], reinterpret_cast<float*>(Data()), GetNumElements(), (float) mean, (float) sigma)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  SetGaussianRandomValue
    - Microsoft::MSR::CNTK::Matrix<float>::  SetGaussianRandomValue
    - CNTK::Internal::  ZeroesWithDynamicAxesLike
    - CNTK::Internal::  ZeroesWithDynamicAxesLike
    - CNTK::  SGDLearner
    - CNTK::TrainingParameterSchedule<unsigned __int64>::  Serialize
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch
    - CNTK::Trainer::  TrainMinibatch
    - PyInit__cntk_py
    - PyInit__cntk_py
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx
    - PyEval_EvalFrameEx

I have GTX 970, 4GB, running beta 12 on Win10.

Regards,
Slawek

**Comment by slaweks17** [comment]
Additional information: I noticed that the problem happens when I try to use any learner with gaussian_noise_injection_std_dev>0. Number of parameters in my model is odd (the output is a single sigmoid).

**Comment by slaweks17** [comment]
Any news? This is really annoying and forces me e.g. not to use stabilization with LSTMs.

**Comment by n17s** [comment]
This has been fixed. Feel free to reopen if not.
