### ISSUE TITLE
Weights initialization mechanism

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#1575]
What is taken in account when weights for virgin network are initialized? Ideally please point me to the code that is generating the weight based on something.

We've encountered funny behavior of our tests and determined that the sole changing of path to data is changing the results of training (while data themselves are still identical). Changing the path to data changes the results.
We'd be able to understand the behavior more closesly (and possibly influence it), since we are caching our data - rendering our experiments to search less efectively.

Thanks
Jan

**Comment by sayanpa** [comment]
Are you asking how to specify a fixed initialization for weights and bias parameters say in a linear_layer (Dense layer)?

**Comment by jakrivan** [comment]
I'm mainly asking to be pointed to the code that performs the seed initialization.

I need to understand how different path to identical data makes the learning behave differently. And then I'd ideally want to be able to influence the randomness (in order to make multiple runs with data in same location to be initialized differently).

In another words - randomness and distribution of randomness (in weights initialization, dropouts; minibatches selection etc. etc.) is very important part of the learning process and we want to have it under the control as much as possible (as oposed to have determinictic trainings but without ability to make them behave randomly - which is needed to beter investigate searched state space).

Thank
Jan

**Comment by sayanpa** [comment]
Sorry about the delay in responding. 

One option is that you initialize the components using the initializers with fixed seeds. You can also fix seeds for CNTK functions: cntk.cntk_py.set_fixed_random_seed(1).

**Comment by jakrivan** [comment]
Thanks sayanapa,

We've already workarounded this case somehow - I unfortunately do not remember how :-)

**Comment by jakrivan** [comment]
@sayanpa - Is there any C# API equivalent call to the one suggested?
LSS - how do we make training stochastic when using C# API?
