### ISSUE TITLE
In CNTK_106B_LSTM_Timeseries_with_IOT_Data how to save model and classify a small sequence?

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#1577]
Hi,

How can I save the model in the CNTK_106B_LSTM_Timeseries_with_IOT_Data and then classify a small sequence ( 2 or 3 days for example) to try to identify a pattern.

With Brainscript the trainig process generates a model that can be evaluated with CSEval.

Thanks,
Paulo

**Comment by sayanpa** [comment]
You can try to replicate the 106B tutorial in brain script if that is something you want to consider.

**Comment by pmfcdb** [comment]
Replicate 106B for now, in Brainscript is too time consuming for the task that I have to do.

So I'm using this documentation to help me, but there is a lot missing. 
https://www.cntk.ai/pythondocs/cntk.html?highlight=restore_model#cntk.cntk_py.Function.restore_model

For now I did this in CNTK_106B_LSTM_Timeseries_with_IOT_Data, add a new cell in the end, and code this:
# save model
z.save_model("lstm2.model")

# load model 
zz = C.cntk_py.Function.restore_model("C:/Users/pbrito/Documents/CNTK-2-0-beta11-0-Windows-64bit-GPU/cntk/Tutorials/lstm2.model")

I get this error:
TypeError: restore_model() missing 1 required positional argument: 'modelFilePath'

Can someone help me? The documentation is lacking in information.
Thks,
Paulo

**Comment by pmfcdb** [comment]
Ok, I advanced a lit more, but I not sure if I'm in right direction. The error is in the line pred=zz.eval({x: x_batch})  "ValueError: Function::Forward: Values for 1 required arguments (), that the requested output(s) depend on, have not been provided" 

Can anyone help?

The code so far: 

# save model
z.save_model("lstm2.model")

# load model 
from cntk.ops.functions import load_model 
zz = load_model("lstm2.model")

# predict again with loaded model
f, a = plt.subplots(2, 1, figsize=(12, 8))
for j, ds in enumerate(["val", "test"]):
    results = []
    for x_batch, _ in next_batch(X, Y, ds):
        pred = zz.eval({x: x_batch})
        results.extend(pred[:, 0])
    # because we normalized the input data we need to multiply the prediction
    # with SCALER to get the real values.
    a[j].plot((Y[ds] * NORMALIZE).flatten(), label=ds + ' raw');
    a[j].plot(np.array(results) * NORMALIZE, label=ds + ' pred');
    a[j].legend();

**Comment by guschmue** [comment]
The easiest way in python is maybe to use the trainer:
after training:
trainer.save_checkpoint("solar.dnn")

and when you want to restore/eval the model instead of training do:
trainer.restore_from_checkpoint("solar.dnn")

**Comment by pmfcdb** [comment]
Hi, when I do a restore of trainer I get : 
ValueError: 'This' function parameters and restored function parameters do not have identical UIDs.

I tested with the same model and with a new model (  same parameters but different names )

trainer.save_checkpoint("solar.dnn")
x1 = C.layers.Input(1)
z1 = create_model(x1)
l1 = C.layers.Input(1, dynamic_axes=z1.dynamic_axes, name="y")
lr_schedule = C.learning_rate_schedule(learning_rate, C.UnitType.minibatch)
loss1 = C.ops.squared_error(z1, l1)
error1 = C.ops.squared_error(z1, l1)
momentum_time_constant = C.learner.momentum_as_time_constant_schedule(BATCH_SIZE / -math.log(0.9)) 
learner1 = C.learner.adam_sgd(z1.parameters, lr = lr_schedule, momentum = momentum_time_constant)
trainer1 = C.Trainer(z1, (loss1, error1), [learner1])
ERROR--->trainer1.restore_from_checkpoint("solar.dnn")

f, a = plt.subplots(2, 1, figsize=(12, 8))
for j, ds in enumerate(["val", "test"]):
    results = []
    for x_batch, _ in next_batch(X, Y, ds):
        pred = z1.eval({x: x_batch})
        results.extend(pred[:, 0])
    # because we normalized the input data we need to multiply the prediction
    # with SCALER to get the real values.
    a[j].plot((Y[ds] * NORMALIZE).flatten(), label=ds + ' raw');
    a[j].plot(np.array(results) * NORMALIZE, label=ds + ' pred');
    a[j].legend();

**Comment by pmfcdb** [comment]
So, I tried this at the end of jupyter notebook CNTK-2-0-beta11-0-Windows-64bit-GPU (windows 10 pro) - CNTK_106B_LSTM_Timeseries_with_IOT_Data  :

z.save("lstm.model")
from cntk.ops.functions import load_model 
zz = C.load_model("lstm.model")

f, a = plt.subplots(2, 1, figsize=(12, 8))
for j, ds in enumerate(["val", "test"]):
    results = []
    for x_batch, _ in next_batch(X, Y, ds):
        pred = zz.eval({x: x_batch})
        results.extend(pred[:, 0])
    # because we normalized the input data we need to multiply the prediction
    # with SCALER to get the real values.
    a[j].plot((Y[ds] * NORMALIZE).flatten(), label=ds + ' raw');
    a[j].plot(np.array(results) * NORMALIZE, label=ds + ' pred');
    a[j].legend();

The error is on pred = zz.eval({x: x_batch}) and the message is:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-208a643ea776> in <module>()
     41     results = []
     42     for x_batch, _ in next_batch(X, Y, ds):
---> 43         pred = zz.eval({x: x_batch})
     44         results.extend(pred[:, 0])
     45     # because we normalized the input data we need to multiply the prediction

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py in eval(self, arguments, device)
    219         '''
    220 
--> 221         _, output_map = self.forward(arguments, self.outputs, device=device)
    222 
    223         if len(output_map) > 1:

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\utils\swig_helper.py in wrapper(*args, **kwds)
     60     @wraps(f)
     61     def wrapper(*args, **kwds):
---> 62         result = f(*args, **kwds)
     63         map_if_possible(result)
     64         return result

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py in forward(self, arguments, outputs, keep_for_backward, device)
    297 
    298         state = super(Function, self)._forward(in_var_map, output_map, device,
--> 299                                              keep_for_backward)
    300 
    301         for k in output_map:

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py in _forward(self, *args)
   1306 
   1307     def _forward(self, *args):
-> 1308         return _cntk_py.Function__forward(self, *args)
   1309 
   1310     def _infer_outputs(self, outputs):

ValueError: Function::Forward: Values for 1 required arguments (), that the requested output(s) depend on, have not been provided

**Comment by pmfcdb** [comment]
So I tried another approach, I used tutorial CNTK_106A_LSTM_Timeseries_with_Simulated_Data, changed the generate_data()  method to my input and I play with the values till I got some acceptable result ( see image). 

What I need to do is save this model and classify determined sequences from another input sequence ex: try to identify the sequence between 45 to 60 in first graph. Any inputs?

![cntk_106a_lstm_timeseries_with_simulated_data01](https://cloud.githubusercontent.com/assets/22818355/26411965/38c367ba-409f-11e7-8a35-db43d9d41222.png)

**Comment by pmfcdb** [comment]
So my goal is to create several models, I can save the model, but it gives me an error when I try to use it!
z.save("lstm_SD.model")
from cntk.ops.functions import load_model
zz = C.load_model("lstm_SD.model")

When I use zz to do:  pred = zz.eval({x: x1}) I get an ERROR!!! 

ValueError: Function::Forward: Values for 1 required arguments (), that the requested output(s) depend on, have not been provided

<ipython-input-20-297e6a084b88> in <module>()
     10     pred_total= []
     11     for x1, y1 in next_batch(X, Y, ds):
---> 12         pred = zz.eval({x: x1})
     13         pred_total.extend(pred[0, :])
     14         results.extend(pred[:, 0])

C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\ops\functions.py in eval(self, arguments, device)
    219         '''
    220 
--> 221         _, output_map = self.forward(arguments, self.outputs, device=device)
    222 
    223         if len(output_map) > 1:

C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\utils\swig_helper.py in wrapper(*args, **kwds)
     60     @wraps(f)
     61     def wrapper(*args, **kwds):
---> 62         result = f(*args, **kwds)
     63         map_if_possible(result)
     64         return result

C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\ops\functions.py in forward(self, arguments, outputs, keep_for_backward, device)
    297 
    298         state = super(Function, self)._forward(in_var_map, output_map, device,
--> 299                                              keep_for_backward)
    300 
    301         for k in output_map:

C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\cntk_py.py in _forward(self, *args)
   1306 
   1307     def _forward(self, *args):
-> 1308         return _cntk_py.Function__forward(self, *args)
   1309 
   1310     def _infer_outputs(self, outputs):

**Comment by lukaszaoralek** [comment]
Hi,

I had similar problem with restore model from checkpoint file. You can try my solution:
let's say you save your checkpoint to solar.dnn file (e.g. trainer.save_checkpoint("solar.dnn")),
now you can use:
trainer.restore_from_checkpoint('solar.dnn')
zz = trainer.model
...
pred = zz.forward({x: x1})

...let us know if does it work for you

**Comment by pmfcdb** [comment]
Thank you very much, it worked!!  

Now I just have to classify a sequence of numbers based on this example :
https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceClassification/SimpleExample/Python/SequenceClassification.py

Anyone can tell me how to map the data correctly to the Train.ctf format?

I already did this:
0 |y 1 0 0 |x 0.472840206189508 0.475350959245193 0.474390401129459 0.475590268830232 0.477114073775768 0.482543630633751 0.483127884858471 0.486958008341563 0.488951180136513 0.489165383425393 0.488129673967432 0.491554480009527 0.491279162780116 0.493250664352155 0.494451899476257 0.493525285424676
1 |y 0 1 0 |x 0.455061139867879 0.455635589073067 0.455480416671434 0.455380271030698 0.451905938826437 0.452300553928865 0.451159642020681 0.451367645797007 0.452469454521502 0.454424291999179 0.454753292123752 0.454778679056232 0.454042483042668 0.454056182195263 0.452962475101177 0.451856643765103
2...
3...

y is the class and x is a sequence of the graph (train raw)
The result is:
Minibatch: 0, Train Loss: 1.1007322692871093, Train Evaluation Criterion: 0.675
...
Minibatch: 240, Train Loss: 1.0765643310546875, Train Evaluation Criterion: 0.7
Minibatch: 250, Train Loss: 1.0700083923339845, Train Evaluation Criterion: 0.655
Error: 0.655000

**Comment by pmfcdb** [comment]
Ok, after search a little more about sequence classification I found this tutorial in CNTK
https://github.com/Microsoft/CNTK/blob/4080c0a5afb4d80ac16de049f7e9cb234527ae29/Tutorials/CNTK_202_Language_Understanding.ipynb

That helped a lot in understanding the input format and the classification of one sequence!

Final format:

Sequence 0 :0.472840206189508 0.475350959245193 0.474390401129459 0.475590268830232 0.477114073775768 0.482543630633751 0.483127884858471 0.486958008341563 0.488951180136513 0.489165383425393 0.488129673967432 0.491554480009527 0.491279162780116 0.493250664352155 0.494451899476257 0.493525285424676


0 |x 7:1 |#0.47 |y 1 0 0 
0 |x 7:1 |#0.47
0 |x 7:1 |#0.47
0 |x 7:1 |#0.47
0 |x 7:1 |#0.47
0 |x 8:1 |#0.48
0 |x 8:1...
0 |x 8:1...
0 |x 8:1...
0 |x 8:1...
0 |x 8:1...
0 |x 9:1
0 |x 9:1
0 |x 9:1
0 |x 9:1
0 |x 9:1
1 |x 5:1 |y 0 1 0
1 |x 5:1
...
