### ISSUE TITLE
OpenCl support for model evaluation?

### ISSUE THREAD

**Issue by bbuchika** [Microsoft/CNTK#1578]
Any plans for expanding hardware support to OpenCL for model evaluation? We are interested in deploying CNTK in edge computing devices that have Intel cpu's with integrated graphics (OpenCL) but no gpu.  Right now cpu evaluation is quite a burden on our prototype systems which is driving up the potential product cost.  
Thanks,
Brant

**Comment by zhouwangzw** [comment]
Currently there is no plan from our side to support OpenCL in near future, e.g. in the next 3 months. But we are appreciated for any contribution from community.

Thanks,

**Comment by bbuchika** [comment]
Okay, thank you for the prompt response. 
Best regards,
Brant

**Comment by zhouwangzw** [comment]
@bbuchika I am closing this thread. Please feel free to reopen it if needed.

**Comment by viper7882** [comment]
Hi @zhouwangzw ,

Hugh Perkins has created [Coriander](https://github.com/hughperkins/coriander-dnn) that could run NVIDIA® CUDA™ code on OpenCL 1.2 devices. You might want to take a look if that suits your need to connect your Deep Learning software to OpenCL 1.2 devices. Kindly attribute his name and his contribution in case if you plan to use his work.

**Comment by zhouwangzw** [comment]
Thanks for the update! We will take a look.

**Comment by viper7882** [comment]
I'm glad to hear that @zhouwangzw. Here's comment from @hughperkins himself:

- A partial implementation of NVIDIA® CUDA™ cuDNN API for OpenCL 1.2 is at https://github.com/hughperkins/coriander-dnn

- A partial implementation of NVIDIA® CUDA™ cuBLAS API for OpenCL1.2 is at https://github.com/hughperkins/coriander

- A compiler and runtime to run NVIDIA® CUDA™ code on OpenCL™ 1.2 devices is also at https://github.com/hughperkins/coriander
