### ISSUE TITLE
CNTK build failed on AWS EC2 instance

### ISSUE THREAD

**Issue by howardlinus** [Microsoft/CNTK#158]
Hi, 

i have tried a few times building a new CNTK on AWS ubuntu 14.04 EC2 instance and failed. It has something to do with the CuDnnConvolutionEngine. Please help.

thanks
Howard

____________________________________________________________________________
make -C /home/ubuntu/CNTK BUILD_TOP=/home/ubuntu/CNTK/build/release all
make[1]: Entering directory `/home/ubuntu/CNTK'
=-----------------------------------------------------------=
creating /home/ubuntu/CNTK/build/release/.build/Source/Math/CuDnnConvolutionEngine.o for with build type release
/usr/local/cuda-7.5/bin/nvcc -c Source/Math/CuDnnConvolutionEngine.cu -o /home/ubuntu/CNTK/build/release/.build/Source/Math/CuDnnConvolutionEngine.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DQUANTIZED_GRADIENT_AGGREGATION -m 64 -O3 -g -use_fast_math -lineinfo -gencode arch=compute_20,code=\"sm_20,compute_20\" -gencode arch=compute_30,code=\"sm_30,compute_30\" -gencode arch=compute_35,code=\"sm_35,compute_35\" -gencode arch=compute_50,code=\"sm_50,compute_50\" -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/home/ubuntu/cub-1.4.1 -I/usr/local/cuda-7.5/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/home/ubuntu/opencv-3.0.0/include -ISource/1BitSGD -Xcompiler "-fPIC -Werror"
Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "const float *" is incompatible with parameter of type "void *"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=float]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
(778): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "float *" is incompatible with parameter of type "cudnnTensorDescriptor_t"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=float]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
(778): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "double" is incompatible with parameter of type "void *"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=float]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
(778): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "const float *" is incompatible with parameter of type "void *"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=float]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
(778): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "const float *" is incompatible with parameter of type "double"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=float]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
(778): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: too few arguments in function call
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=float]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=float]"
(778): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "const double *" is incompatible with parameter of type "void *"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=double]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
(779): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "double *" is incompatible with parameter of type "cudnnTensorDescriptor_t"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=double]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
(779): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "double" is incompatible with parameter of type "void *"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=double]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
(779): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "const double *" is incompatible with parameter of type "void *"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=double]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
(779): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: argument of type "const double *" is incompatible with parameter of type "double"
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=double]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
(779): here

Source/Math/CuDnnConvolutionEngine.cu(507): error: too few arguments in function call
detected during:
instantiation of "void Microsoft::MSR::CNTK::CuDnnConvolutionEngine::BackwardNormalizeBatch(const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Tensor4D &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, __nv_bool, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, const Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &, Microsoft::MSR::CNTK::ConvolutionEngine::Mat &) [with ElemType=double]"
(275): here
instantiation of "Microsoft::MSR::CNTK::CuDnnConvolutionEngine::CuDnnConvolutionEngine(size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
Source/Common/Include/Platform.h(255): here
instantiation of "std::unique_ptr> std::make_unique(Args &&...) [with T=Microsoft::MSR::CNTK::CuDnnConvolutionEngine, Args=]"
(726): here
instantiation of "Microsoft::MSR::CNTK::ConvolutionEngineFactory::ConvEnginePtr Microsoft::MSR::CNTK::CuDnnConvolutionEngineFactory::CreateConvEngine(int, size_t, Microsoft::MSR::CNTK::BatchNormImpl) [with ElemType=double]"
(779): here

12 errors detected in the compilation of "/tmp/tmpxft_0001b5e1_00000000-16_CuDnnConvolutionEngine.compute_50.cpp1.ii".
make[1]: *** [/home/ubuntu/CNTK/build/release/.build/Source/Math/CuDnnConvolutionEngine.o] Error 2
make[1]: Leaving directory `/home/ubuntu/CNTK'
make: *** [all] Error 2

**Comment by amitaga** [comment]
Hi Howard,

What is the CuDNN version that your have installed on your system? Please confirm that our CuDNN version is same as the one specified in our build instructions in the Wiki.

Regards,
Amit

**Comment by howardlinus** [comment]
@amitaga, I use cudnn-4.0, not quite sure if it is from cudnn-7.0-linux-x64-v4.0-rc.tgz or cudnn-7.0-linux-x64-v4.0-prod.tgz, will that make a difference?

**Comment by Alexey-Kamenev** [comment]
Hi,
Please use cuDNN RC version, not prod. It does make a difference as prod version has some changes in API which will make the CNTK build fail. It will be fixed soon.

**Comment by howardlinus** [comment]
hi @Alexey-Kamenev , i just did it with cnDNN RC version (re-copy it to /usr/local/cudnn-4.0)  and the problem persist. Is there is any information i could provide to help diagnose this problem.? thanks
