### ISSUE TITLE
how to use multiple GPU for rnn in python

### ISSUE THREAD

**Issue by StillKeepTry** [Microsoft/CNTK#1583]
When I use `mpiexec` to run the rnn model in python with multiple gpu, it will raise the `RuntimeError : Aggregation for sparse matrices is currently not supported`. Can someone solve it ?

**Comment by sayanpa** [comment]
This is a feature gap. You can try two things as workaround:
- Pass a fixed embedding from previous sources or a single GPU training
- Pass a dense input instead of sparse

**Comment by StillKeepTry** [comment]
Thank you, your advice is very helpful.

I also want to ask you a problem. If i don't use training_session, and use a data_reader just like [data_reader.py](https://github.com/Microsoft/CNTK/blob/v2.0.beta15.0/Examples/Text/WordLMWithSampledSoftmax/data_reader.py). Does it will effect performance with multi-GPU? Because when i use Multi-GPU in language model, i find the speed don't be imporved with multi-GPU.

**Comment by sayanpa** [comment]
We have a richer set of manual to help you better understand the different options:
https://github.com/Microsoft/CNTK/tree/master/Manual

Given this issue has been open for a while and the answer above. I am closing this one, but feel free to reopen this one, or better even would be open a new one with an updated topic. Apologies for the delay.
