### ISSUE TITLE
Error during test run after fresh install

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1584]
Did a fresh install via scripts for windows binaries ( v 2 beta 12 with 1-bit SGD )

In Step 6 of the instructions to "verify setup for Branscript" -- I follow those instructions but I get a Visual C++ Runtime error that shows:

Program C:\local\CNTK...
R6030
- CRT not initialized

help?

**Comment by JohnCraigPublic** [comment]
Looks like this is same as reported by others ( #1485 ) -- so perhaps it is because I am on Win7-64

**Comment by wolfma61** [comment]
there has been changes to allow running Windows7, but please be aware that Windows7 is not an official support platform for CNTK
please open a new issue if you experience this in a more recent CNTK installation on a more up-to-date Window version
