### ISSUE TITLE
Default PYTHONPATH for the binary script CNTK

### ISSUE THREAD

**Issue by min6434** [Microsoft/CNTK#1587]
I recently installed CNTK using binary Script-driven installation.
So python is intalled at 'C:\local\Anaconda3-4.1.1-Windows-x86_64'
And the CNTK is installed at 'C:\local\CNTK-2-0-beta12-0-Windows-64bit-GPU\cntk'.
I accidently changed the environment variable PYTHONPATH into others and now it is 
'C:\local\CNTK-2-0-beta12-0-Windows-64bit-GPU\cntk\cntk\Python'
Is it correct location or not?
All the instructions on the web are about the source building installation and  say it should be 'c:\repos\cntk\bindings\python'. I don't have any binding forder.

**Comment by bencherian** [comment]
If you are not building from source, you should never need to set PYTHONPATH. In a default Anaconda environment it should be unset.

**Comment by min6434** [comment]
Thank you very much for your answer bencherian.
I thought I need to set this variable too.
Somehow my VS2013 doesn't recognize cntk modules.
I managed to import cntk by starting my VS2013 at the cmd.exe after starting the batch file 'cntkpy35.bat'.
However even though I can start my project using cntk, intellisense says there are no such thing called cntk.
How am I solve this problem?

**Comment by bencherian** [comment]
What are you trying to do? It's unclear to me why you need VS2013. Are you trying to make a C++ CNTK application or a Python one? Are you trying to use Python Tools for Visual Studio? If so, you need to setup the interpreter in the cntk-py35 environment.

**Comment by min6434** [comment]
Sorry I fixed the problem
I am trying to work with python CNTK application with VS2013
I updated the intellisense again, and VS2013 now acknowlege the cntk module and its functions too.

By the way, are there any other ways to use CNTK with VS2013, without starting the devenv.exe at the command prompt after executing the 'cntkpy35.bat' ?

![image](https://cloud.githubusercontent.com/assets/25948850/23777908/d43a1f00-057a-11e7-8cc6-cb953d7ba366.png)

![image](https://cloud.githubusercontent.com/assets/25948850/23777912/e7bb199e-057a-11e7-86bc-d0293e62454b.png)

**Comment by min6434** [comment]
I think using the command prompt is mandatory :)

**Comment by mdabros** [comment]
@min6434 I know the issues has been closed for some time now, but did you ever discover a way of using python CNTK with visual studio without starting devenv from the prompt?

**Comment by min6434** [comment]
I could not found a way out specifying the conda environment inside of the visual studio.
Also I changed my ide to visual studio code.
