### ISSUE TITLE
How to start the CNTK at the VS2013 and jupyter notebook

### ISSUE THREAD

**Issue by min6434** [Microsoft/CNTK#1588]
I am struggling with CNTK for VS2013 and the Jupiter. 
I found out I need to start my VS2013 at the cmd.exe after executing the batch file 'cntkpy35.bat'
Do I have to this procedure everytime when I need to open my VS2013?

Also how am I start jupiter notebook to use CNTK?
When I am trying to do the turorial 'CNTK_101_LogisticRegression.ipynb'.
I get error message says 'ImportError: No module named 'cntk' '.

p.s. I installed CNTK using binary script-driven installation.

**Comment by min6434** [comment]
I solved one problem.
You need to change the default python kernel to the cntk python kernel.
![image](https://cloud.githubusercontent.com/assets/25948850/23741920/24147896-04ee-11e7-87d6-839ab7216278.png)

**Comment by sayanpa** [comment]
the easiest way to do is from command prompt:
- activate CNTK-py35 
- jupyter notebook

The notebook will spawn and you should be able to test by running import CNTK in a cell. There is no involvement of VS2013. Let us know if that works for you. Assuming after activating the environment on your command prompt you can run:
-  python
- within the python shell you can run: import CNTK

This would ensure your installation is working well.

Thanks,
Sayan

**Comment by min6434** [comment]
Thank you.
Command prompt really works :)

**Comment by Hermes-MG** [comment]
I am also struggling with the same problem, but with an aditional detail. When  I try to import CNTK  as indicated it did not work and I received a message to upgrade pip install and when trying to upgrade pip install I again receive another error message as shown in the image.
![image](https://user-images.githubusercontent.com/41552327/50405501-3529d900-0794-11e9-9e52-9065a8b55823.png)

Thank you in advance for getting me out of this problem...
