### ISSUE TITLE
error while running 01_OneHidden for MNIST

### ISSUE THREAD

**Issue by Shabnam77** [Microsoft/CNTK#159]
I am trying to run 01_OneHidden for MNIST database on Ubuntu system. I am using the exact config and ndl files as in the example, however this exception occurs: **EXCEPTION occurred: No Criterion nodes specified**
The following special nodes are introduced in the ndl file:
  FeatureNodes=(features)
    LabelNodes=(labels)
    CriterionNodes=(ce)
    EvalNodes=(err)
    OutputNodes=(ol)

Any ideas??

<<<<<<<<<<<<<<<<<<<< PROCESSED CONFIG WITH ALL VARIABLES RESOLVED <<<<<<<<<<<<<<<<<<<<
command: train test 
precision = float
CNTKModelPath: ~/cntk/Examples/Image/MNIST/Output/Models/01_OneHidden
CNTKCommandTrainInfo: train : 30
CNTKCommandTrainInfo: CNTKNoMoreCommands_Total : 30
CNTKCommandTrainBegin: train
LockDevice: Capture device 1 and lock it for exclusive use
LockDevice: Capture device 0 and lock it for exclusive use
LockDevice: Capture device 1 and lock it for exclusive use
NDLBuilder Using GPU 1
reading uci file ~/cntk/Examples/Image/MNIST/Data/Train-28x28.txt
EXCEPTION occurred: No Criterion nodes specified

**Comment by pkranen** [comment]
Hm, this example runs as part of our test suite and passes. Can you try running it from the test driver:

python TestDriver.py run Examples/Image/MNIST/01_OneHidden/

The test driver is in CNTK/Tests/EndToEndTests. See https://github.com/Microsoft/CNTK/wiki/How-to-Test#end-to-end-tests for details about the test driver.
