### ISSUE TITLE
CUDA failure 2: out of memory( cntk2.12 GPU,run A2_RunCntk.py in ../example/detection/fastrcnn/)

### ISSUE THREAD

**Issue by sydtest** [Microsoft/CNTK#1591]
Starting minibatch loop.
CUDA failure 2: out of memory ; GPU=0 ; hostname=********* ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(All
ocatedElemType) * numElements)

i need a hand..................

**Comment by cha-zhang** [comment]
How much memory do you have on your machine? Have you tried reducing the minibatch sizes?

**Comment by afzalmushtaque** [comment]
I get the same error on this line:
learner = cntk.sgd(predicted_output.parameters,learning_rate_schedule)
My input shape is (10000x19x128)
My output shape is (10000x34x128)

**Comment by pkranen** [comment]
Closing this issue since not sufficient information was given since a long time. Please open a new issue if the problem still occurs with the latest bits. Thanks.

**Comment by rajarsheem** [comment]
I have the same problem. I am using Notebook, so more I run a cell with cntk model, more GPU memory gets occupied. Can we reset something before two consecutive runs ?
