### ISSUE TITLE
deactivate GPU locking with python

### ISSUE THREAD

**Issue by cstrub** [Microsoft/CNTK#1592]
Hi,

is there any way to deactivate the GPU-lock for exclusive usage when running cntk from the current python API (2.0 beta 12.0)? I.e. set the value for the "lockGPU" boolean checked by DeviceFromConfig( ) in BestGpu.cpp

Thanks in advance :)

**Comment by sayanpa** [comment]
Could you set the device explicitly using GPU id: cntk.device.set_default_device(cntk.device.gpu(0))

That way you can run multiple jobs on the same GPU. Does this work for you. 

This is a great question, would you mind asking this on StackOverflow.com with CNTK tag please.

**Comment by cstrub** [comment]
Hi,
great, this solved the Problem!
