### ISSUE TITLE
parameters order differ from layers order

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1594]
Hi

I create a model using: `model = Sequential([Recurrence(LSTM(128, use_peepholes=True)), Dense(40), Recurrence(LSTM(256, use_peepholes=True)), Dense(num_classes)])`

I print model's parameter name and shape (after training), but the order of parameters is shuffled (in other words differ from model order):

```
z = model(features)
for i in z.parameters:
        print(i.name, i.shape)
```

>(u'W', (256, 132))
(u'b', (132,))
(u'b', (1024,))
(u'W', (40, 1024))
(u'W', (128, 40))
(u'b', (40,))
(u'b', (512,))
(u'W', (33, 512))
(u'H', (128, 512))
(u'Co', (128,))
(u'Cf', (128,))
(u'Ci', (128,))
(u'H', (256, 1024))
(u'Co', (256,))
(u'Cf', (256,))
(u'Ci', (256,))

Is it normal or I do something wrong?

**Comment by sayanpa** [comment]
With the new layers library, you can attach a unique name to your node and retrieve the name and the parameters associate by name. BTW, this is currently in the master and is the next release should have this exposed via our release binaries.

**Comment by hajix** [comment]
thanks @sayanpa
