### ISSUE TITLE
Clone some layers of model

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1595]
Hi

I get an instance from this model `model1 = Sequential([Recurrence(LSTM(128, use_peepholes=True)), Dense(40), Recurrence(LSTM(256, use_peepholes=True)), Dense(num_classes)])` and trained it. How do I copy its first three layers parameters as constants to another model with the same shape/type? For example assume that the other model is `model2 = Sequential([Recurrence(LSTM(128, use_peepholes=True)), Dense(40), Recurrence(LSTM(256, use_peepholes=True)), Dense(40), Dense(num_classes2)])` and I need to model2 has the same parameters as model1 (in its fisrt three layers).

I read the doc about clone method but I did not find some example. Any suggestion?

P.S. If I manually copy weights, there is no option to force cntk not update parameters (not trainable parameters). I try to set `needs_gradient` to False but encountered with the error as follows:

> AttributeError: can't set attribute

**Comment by sayanpa** [comment]
Does following StackOverflow answer help you:
http://stackoverflow.com/questions/42695910/copy-parameters-as-constant-values/42707108#42707108

**Comment by hajix** [comment]
@sayanpa 
ouch... excuse me for replication, I did not check stackoverflow for answers.

The last question is that `needs_gradient` is a read only attribute?!? Is it a bug or it is as it should be?!?
regards

**Comment by sayanpa** [comment]
Not sure if I can see the context in which you are seeing needs_gradient. Can you please give a bit more information please. Also in SO please upvote if the answer helped you.

**Comment by hajix** [comment]
I'll check stackoverflow ASAP.

```
z1 = model1(feat)
z1.parameters[0].needs_gradient = True
```

thrown the following error:
> ---------------------------------------------------------------------------
>
>AttributeError                            Traceback (most recent call last)
><ipython-input-4-07eefa4200f8> in <module>()
>----> 1 z1.parameters[0].needs_gradient = True
>
>/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.pyc in <lambda>(self, >name, value)
 >  1064     for _s in [Variable]:
 > 1065         __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
>-> 1066     __setattr__ = lambda self, name, value: _swig_setattr(self, Parameter, name, value)
>  1067     __swig_getmethods__ = {}
> 1068     for _s in [Variable]:
>
>/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.pyc in _swig_setattr(self, class_type, name, value)
>     72 
>     73 def _swig_setattr(self, class_type, name, value):
>---> 74     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
>     75 
>     76 
>
>/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.pyc in _swig_setattr_nondynamic(self, class_type, name, value, static)
>     64     if (not static):
>     65         if _newclass:
>---> 66             object.__setattr__(self, name, value)
>     67         else:
>     68             self.__dict__[name] = value
>
>AttributeError: can't set attribute

**Comment by hajix** [comment]
I tried to clone weights with some code like in [here](https://github.com/Microsoft/CNTK/blob/77154a7f7288d4b119e415039be6471565fceccf/Examples/Image/TransferLearning/TransferLearning.py), but I get core dump when I want to use `cloned_layers`:

```
# model 1
def model1(feat):
    L1 = Recurrence(LSTM(10, use_peepholes=True))(feat)
    L1.set_name('L1')
    L2 = Dense(6, name='L2')(L1)
    L3 = Dense(8, name='L3')(L2)
    L4 = Dense(num_cls1, name='L4')(L3)
    return L4

feat1 = C.input_variable((feat_size))
lab1 = C.input_variable((num_cls1))

z1 = model1(feat1)
# train z1

# model 2
def create_model(feat2):
    feature_node = find_by_name(z1, 'L1')
    last_node = find_by_name(z1, 'L4')

    # Clone the desired layers with fixed weights
    # get core dump
    cloned_layers = combine([last_node.owner]).clone(CloneMethod.freeze, {feature_node: Placeholder(name='L1')})

    # Add new dense layer for class prediction
    cloned_out = cloned_layers(feat2)
    z = Dense(num_cls2)(cloned_out)

    return z

feat2 = C.input_variable((feat_size))
lab2 = C.input_variable((num_cls2))

z2 = create_model(feat2)
```
The other issue is that this example copy whole parameters of pre-trained model to new model, but I need just some layers to copy.

Please prepare a simple (for dummy) example in [How do I...](https://github.com/Microsoft/CNTK/wiki/How-do-I-in-Python) section.

regards
