### ISSUE TITLE
Eval from C++

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1599]
I believe the EvalDLL is available only in 64-bit.  Is this also true for the CNTK Library?  I have a 32-bit application in C++ and it would be very convenient if there is a way to Eval from my C++ code....

**Comment by avader906** [comment]
Eval DLL has 64bit dependencies and the (little) work required to communicate with 32bit application would have to be done on your end.

You could a 64bit IPC server (or RPC/named piped/dcom etc) that will communicate (receive/send) with your 32bit application and call Eval DLL from it's (64bit) process space.

**Comment by zhouwangzw** [comment]
Yes, CNTK currently requires 64-bit. It is feasible to build a solution communicating with 32-bit applications, but we do not have such a solution yet.
