### ISSUE TITLE
Cntk set_default_device(gpu(0)) gives "invalid device"

### ISSUE THREAD

**Issue by Deewrat** [Microsoft/CNTK#1600]
I just installed cntk and it all works OK except set_default_device(gpu(0)) gives "invalid device". This happens both in a command line environment and in Visual Studio 2017 (python version). Any ideas?

**Comment by sayanpa** [comment]
Can you try the other options with device specifications and see what works: https://cntk.ai/pythondocs/cntk.html?highlight=set_default_device#module-cntk.device and what doesn't.

**Comment by Deewrat** [comment]
I have tried "best", "all_devices", and "cpu". None work.

**Comment by TJett** [comment]
Have you tried `cntk.device.try_set_default_device(cntk.device.gpu(0))`? That seemed to work for me. My `device.py` doesn't contain a `best_device` attribute. 
However I am not very familiar with python, so this may not be the correct solution.

**Comment by Deewrat** [comment]
I have now tried that but get an error- cntk.device has no attribute "try_set_default_device".
What version of cntk did you use?

**Comment by TJett** [comment]
`cntk__version__` returns `'2.0.beta15.0+'`. I'm building from source.

**Comment by wolfma61** [comment]
Is this still an issue?
please open a new issue if you experience this in a more recent CNTK installation
