### ISSUE TITLE
Binary image classification

### ISSUE THREAD

**Issue by Arminea** [Microsoft/CNTK#1601]
Hi, I would like to know if I have a right direction in my work.

I trained a model for image binary classification. Class _1_ for target image and class _0_ for the rest.
Class _1_ has 2k images for training. I check all images myself manually. Class _0_ had 25k random images for training, downloaded from Flickr. The network achieved 3.907% classification error with 810030 total samples seen during training.
For test phase I used 200 images, 100 target and 100 non-target random images (I's probably not enough). The network achieved 15.942% classification error.
I made a web app where user can upload image and get back the classification result (via python script). I'm trying upload images but the result is always non-target even if I upload a target image.

Did I trained the model properly (with the bunch of random flickr images)? Or maybe could the problem be in image resizing? I resize image before processing with PIL `resize` function, not with the cntk python api.

**Comment by sayanpa** [comment]
I think you have class imbalance during training with more Class 0 than Class 1. You should balance your data set. Or Augment class 1. Also, I am assuming the input images that the images trained on the same size as the ones that you are passing in the app.

**Comment by Arminea** [comment]
Hi, 
thanks for answering. I balanced data sets as you suggested. The network achieved 13% classification error in test phase. Is there a way to log classification results for each image? I would like to know which image was classified correctly.
When I  run python test script for classification I get weird output. For every image (target and non-target) I get predictions like 
```
[ 3.58319283 -1.34806216]
[ 3.00725293 -1.07172883]
[ 3.50791407 -1.49666131]
[ 4.10697317 -1.84976065]
``` 
and then the class of image is always 0. My code is:
```
def prediction(pathToImage):
	size = 224, 224
	im = Image.open(pathToImage)
	im = remove_transparency(im)
	im = im.resize(size) # PIL.Image.NEAREST resampling

	rgb_image = np.asarray(im, dtype=np.float32) - 128
	bgr_image = rgb_image[..., [2, 1, 0]]
	pic = np.ascontiguousarray(np.rollaxis(bgr_image, 2))

	z = load_model("model.dnn")
	z_out = ct.combine([z.outputs[2].owner])
	predictions = np.squeeze(z_out.eval({z_out.arguments[0]:[pic]}))
	top_class = np.argmax(predictions)

	print(predictions)
	print(top_class)
```

**Comment by ebarsoumMS** [comment]
Can you share also the training code?

**Comment by Arminea** [comment]
Sure thing :) [https://1drv.ms/f/s!As_qGuBAm_dbiNldCItxglz_ELfz1A](url)

**Comment by ebarsoumMS** [comment]
May be I am missing it, I don't see in yours code that you substract the mean during training? So why are you substracting 128 during evaluation?

**Comment by Arminea** [comment]
Well, that could happen during my ctr+c and ctrl+v :D Do you have any suggestion what should I do better? Please :)

**Comment by ebarsoumMS** [comment]
The data fed to your evaluator need to match what was fed to your model during training. So if you trainer doesn't normalize the input, then you need to change "rgb_image = np.asarray(im, dtype=np.float32) - 128
" to "rgb_image = np.asarray(im, dtype=np.float32)".

**Comment by Arminea** [comment]
That actually makes sense. Thank you for your time :) And if I would want to normalize the input in reader I would just add the `minibatchSize=128` line to train block?

**Comment by ebarsoumMS** [comment]
minibatchSize has nothing to do with input normalization. Here an example:

https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet20_CIFAR10.cntk 

Look at those 2 lines:
        featScale = 1/256
        Normalize{f} = x => f .* x

**Comment by Arminea** [comment]
Thanks, I'll look into it :)

**Comment by pkranen** [comment]
If you want to build your own image classifier I'd recommend to also try transfer learning as described here: [https://github.com/Microsoft/CNTK/wiki/Build-your-own-image-classifier-using-Transfer-Learning](https://github.com/Microsoft/CNTK/wiki/Build-your-own-image-classifier-using-Transfer-Learning).

**Comment by Arminea** [comment]
@pkranen Thanks, I'll definitly try it :)
