### ISSUE TITLE
when will we be able to build CNTK with Visual Studio 2017

### ISSUE THREAD

**Issue by Rekodr** [Microsoft/CNTK#1603]

**Comment by avader906** [comment]
What are the issues you have experienced?

**Comment by Rekodr** [comment]
for some reason, my vs2017 is failing to load all the projects in the solution("they appear as unavailable") as you can see on the screen shot. 
<img width="216" alt="cntk_vs2017" src="https://cloud.githubusercontent.com/assets/11841183/23865653/b9f8be02-07ec-11e7-95aa-1e5c5e9fdc13.PNG">
en shot

**Comment by sayanpa** [comment]
Based on #1941
