### ISSUE TITLE
Not able to uninstall cntk

### ISSUE THREAD

**Issue by Chunde** [Microsoft/CNTK#1604]
Hello, at some point I try to uninstall cntk in order to reinstall it from other source. My initial installation is from the build using source code. I have some issue when using VS2015 as the auto-completion does not work for the build, but works for the case when cntk is installed from the online build. 
I use pip command to uninstall the cntk, but it says: 
```
(cntk-py35) C:\Users\Chunde>pip uninstall cntk
Can't uninstall 'cntk'. No files were found to uninstall.
```
I can see the cntk when use pip list command

```
(cntk-py35) C:\Users\Chunde>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
args (0.1.0)
Babel (2.3.4)
bleach (1.5.0)
clint (0.5.1)
cntk (2.0.beta12.0) <<------------------
colorama (0.3.7)
cycler (0.10.0)
decorator (4.0.11)
docutils (0.13.1)
entrypoints (0.2.2)
gym (0.5.2)
...
```

People say this may due to the method I install the cntk at very beginning,  I simply follow the instruction from CNTK(https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Manual)

I try to uninstall conda completely, and redo all the steps, but it never works. The strange thing is when I reinstall conda, I do not have to install cntk after installing  CNTK Python environment, it seems the cntk python package is not loaded from conda location.

I am till learning more about python, but not enough to figure out the issue so far. Help is needed, many thanks~

**Comment by Master76** [comment]
Hi @Chunde ,

Try the following commands(administrator):
```cmd
cd C:\local\Anaconda3-4.1.1-Windows-x86_64\scripts
activate C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35
cd C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35
pip install --upgrade --no-deps https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp35-cp35m-win_amd64.whl
```

Remember to close all related processes.

**Comment by Chunde** [comment]
Hello @Master76  Thanks for you reply, it seems the new package can be installed, but the same message shows up.  Anyway, at this point this is not a big issue now. 
```
Can't uninstall 'cntk'. No files were found to uninstall.
```
