### ISSUE TITLE
Errors in Tutorial CNTK_203

### ISSUE THREAD

**Issue by Chunde** [Microsoft/CNTK#1605]
Hi all,

These days I am trying to make the CNTK_203 works, but it seems there are many issues. If I install cntk from online source using pip, I may get different errors.  I already fixed some errors in this tutorials, but it more issues show up. Here I report on problem when running the tutorials, the exception is thrown at:
```Python
def predict(self, s):
        return self.model.eval(s) #--->this line throws exception
```
The error information is: 
```
TensorOp: The only permitted binary reduction operation is opSum.

[CALL STACK]


  > Microsoft::MSR::CNTK::GPUMatrix<float>::  TensorOp

    - Microsoft::MSR::CNTK::Matrix<float>::  TensorOp

    - Microsoft::MSR::CNTK::TensorView<float>::  DoBinaryOpOf

    - Microsoft::MSR::CNTK::PlusNode<float>::  ForwardProp

    - Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp

    - <lambda_258018e62e82ba6c7f6055b001fc29b8>::  operator  ()

    - Microsoft::MSR::CNTK::ComputationNetwork::TravserseInSortedGlobalEvalOrder<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>>  

    - CNTK::CompositeFunction::  Forward

    - CNTK::Function::  Forward

    - _wrap_Function__forward__SWIG_1

    - _wrap_Function__forward

    - PyCFunction_Call

    - PyEval_GetFuncDesc

    - PyEval_EvalFrameEx

    - PyEval_EvalFrameEx

    - PyEval_GetFuncDesc
```

But when I run on another computer with cntk from online source given by CNTK team, there is no such issue, but some other issues, which I will report later when solve this one, it may be good to have the topic on this tutorial open until we make it works without problem. Thx!

**Comment by Chunde** [comment]
If just use the Jupiter notebook, everything is good, I guess something is not setting properly for the PTVS.

**Comment by wendy7707** [comment]
@Chunde I have the same problem, would you please tell me how to solve this problem, thanks!
