### ISSUE TITLE
Feature Request: get used gpu memory over python api

### ISSUE THREAD

**Issue by dlahmad** [microsoft/CNTK#1606]
Dear Developers,

would it be possible to integrate the requested function? Basically cuda has an easy functionality to do so and it would be useful developing new models. A wrapper would be needed. Unfortunately i don't have the time to do it myself.

Best Regards
Vedaevolution

**Comment by KeDengMS** [comment]
An easier way is to invoke NVidia-smi and parse the GPU memory usage from its output. Putting an wrapper in CNTK on top of nvml does not seem to be the best solution.

**Comment by dlahmad** [comment]
Outdated
