### ISSUE TITLE
Does CNTK support CHW layout in CPU version?

### ISSUE THREAD

**Issue by xhzhao** [Microsoft/CNTK#161]
I'm trying to optimize CNTK for the CPU version.
In legacy engine type, default imageLayoutKind is HWC.
I want to change this default imageLayoutKind to CHW.
What should i do?
Should i change the config file or modify the source code?

![image](https://cloud.githubusercontent.com/assets/17486215/13340892/e66b40a4-dc6e-11e5-8877-7ca5af9f634b.png)

I have tried the following 2 ways, which do not work:
1.Add one more line in the config file:
	imageLayout = "CHW"
  But it does not work. The output is still HWC.
2.Change the source code of ConvolutionNode init function:
  m_imageLayoutKind: set default value to ImageLayoutKind::CHW
  Many errors when building.

Confused......

**Comment by frankseide** [comment]
The underlying CPU routines only support HWC. If you want to support CHW, you would need to implement a different set of routines.

You should not have build errors, but likely a runtime error, since the code currently prevents you from using it in the wrong mode.

**Comment by Alexey-Kamenev** [comment]
CHW layout on CPU will be supported soon.

**Comment by xhzhao** [comment]
@Alexey-Kamenev When will the new version be released? Is there any schedule?
Now, i have to write a function to transform the matrix data from HWC to CHW.

**Comment by xhzhao** [comment]
@frankseide yeah, it is a runtime error.

**Comment by ldmtwo** [comment]
@Alexey-Kamenev  Any update on this? I'm seeing this error. If you think this is not related to what CNTK allows on CPU only mode, then let me know and I'll create a new ticket. Thanks. Also, the dataset is ImageNet using AlexNet and ResNet as directly from the examples. No error on MNIST. 

`EXCEPTION occurred: Default convolution engine currently supports only HWC/legacy layout.`

**Comment by Alexey-Kamenev** [comment]
There is a CHW implementation for CPU in my ND convolution branch, `alexeyk/ndconv`. This is an experimental feature though, I don't know when (and if) it will be merged with master. Also, in the current form only reference implementation is supported which means it will be slow.

**Comment by ant0nsc** [comment]
Frank or Alexey, can you clarify the following: I have a setup where I would like to train CNTK models on images on a GPU cluster. The models should be deployed and evaluated in a CPU-only environment. It sounds from the comments that this is something that is currently impossible. Correct? If so, will Alexey's change enable it?

**Comment by Alexey-Kamenev** [comment]
This feature is in the master now.

**Comment by ant0nsc** [comment]
@Alexey-Kamenev : Kudos for turning that around so quickly, amazing to see how quickly you guys operate! This is such a super helpful feature when trying to test something on my desktop before deploying to the GPU cluster.
