### ISSUE TITLE
Optimizing GPU/CPU Eval library questions

### ISSUE THREAD

**Issue by PeterGriffioen** [Microsoft/CNTK#1612]
I'm running the .Net Eval Library over 100,000,000 or so small images. It takes a while (to say the least!). I have a few simple optimisation questions.

1) Can I thread GPU evaluation or does the Device = DeviceDescriptor.GPUDevice(0) require exclusive access to the GPU?

2) If the answer to 1) is yes, exclusive access is required then : Can I set up 2 threads that alternate execution of device.Evaluate(inputDataMap, outputDataMap, whichDevice) command such that all of the data loading for one can occur while the other is running. Or does there simply have to be only 1 device in use?

3) When I trained the networks I used labels read up in the text reader. eg.
  reader = {
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/Vert_Train_5.txt"
        input = {
        	features = { dim = 375; format = "dense" }
        	labels = { dim = 51; format = "sparse" }
        }

Now to run the model through the evaluation library, I must supply dummy labels for every image or else I get a runtime error. Is this necessary? If so, how do I supply a sparse matrix to the arguments section of the input structure?  Here's the relevant structures (Yes it's in VB!). 

'setting up the component of the input 
Dim ThisFunc As CNTK.Function
Dim inputVar As Variable = ThisFunc.Arguments(0)      
Dim labelsVar As Variable = ThisFunc.Arguments(1)

Dim theLabelsBatch = New List(Of Single) 'dummy labels vector goes here, set any value to 1
Dim theLabelsBatch 'ends up as a List(of List( of single))

Dim inputDataMap As Dictionary(Of Variable, Value)
...
   'later in the code add this vector
   theLabelsBatch.AddRange(labelsVect)
...
   'Create input data map
   inputVal = Value.CreateBatch(inputVar.Shape, theBatch, whichDevice) 
   labelsVal = Value.CreateBatch(labelsVar.Shape, theLabelsBatch, whichDevice)
....
   'set up the input structure
    inputDataMap = New Dictionary(Of Variable, Value)
    inputDataMap.Add(inputVar, inputVal) 'actual values to be evaluated
    inputDataMap.Add(labelsVar, labelsVal) 'dummy labels
....
   'Process
    ThisFunc.Evaluate(inputDataMap, outputDataMap, whichDevice)
    
4) I have the evaluation working fine on the GPU (issue #1354 notwithstanding, for which I came up with a workaround). However if I change the device to CPU, making no other changes, the network outputs the same value regardless of input. The networks use Batch Normalisation. Is this still an issue on CPU eval. i.e. Issue #1017 ? Or do I have to re-compile with the CPU version of the library? Or it may I'm missing some other library?

5) Finally is there any point threading the CPU eval except for speeding up the data loading? I imagine that it uses all of the CPUs while running the evaluation similar to the running of cntk.exe. Is that correct? 

Thanks in advance. I'm getting great results btw.

**Comment by zhouwangzw** [comment]
Great to know that you are making process and getting good results with CNTK. Thanks for the update. 
For your questions:
1) You can run multiple evaluation threads on the same device (CPU or a particular GPU device). No requirement for exclusive access. However, you need to "clone" the model instance for multiple concurrent evaluations. We have an example [`EvaluateMultipleImagesInParallel()`] (https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples/CNTKLibraryCSEvalExamples.cs) in C# demonstrates how to evaluate concurrent requests using CNTK C#/.NET Managed API.
2) You can run multile threads on the same device. Each threads needs to have its own model instance.
3) Which inputs are expected is defined by your model during training. I think the ouptut Function of your current model does require label as input, so you have to provide a dummy one as input. You probably can change your model to not use label in the output function, or you can also use FindByName to find the appropriate Function in the loaded model which provides the expected output but without using label.  
4) Which CNTK version are you using? The BN evaluation on CPU is supported in the latest version. If you change device for evaluation, you also need to change device specification in LoadModel, and Value.CreateBatch(), and etc.
5) As said before, you can also use multiple threads to evalute multiple requests in parallel on CPU. Just using Clone(). 

Thanks,
Zhou

**Comment by PeterGriffioen** [comment]
Thank you for your quick reply. It is amazing how fast the models run on the GPU (GTX1080). My main issue at this stage is that I can't keep it fed! I'm basically doing pixel by pixel image classification (image segmentation) by brute force over very large images (say 40000 x 24000 pixels and up to 75 layers from multiple sources) by breaking up the image into mini-images. A lot of data to throw around.

I'm not sure what is going on with the Device=CPU version as that is the only line I change.  I'm using the latest libraries (ver12) and I do propagate the device through the computation. I will track it down as my target system is a distributed CPU based system that I've had working for years. It will be hybrid GPU/CPU soon though!

Just quickly: Sparse matrix definition for input? Just a pair of values for each valid entry i.e. Index and Value similar to the text reader instead of a complete vector of (51 in my case) values for the 'Dim theLabelsBatch = New List(Of Single)" ?

**Comment by zhouwangzw** [comment]
We are working on sparse support for input in C#. It will be available soon.

**Comment by zhouwangzw** [comment]
The sparse input is supported now in C# starting from 2.0.RC1. Please let us know if you have questions.

Thanks

**Comment by zhouwangzw** [comment]
I am closing the thread. Please feel free to re-open it if needed.

**Comment by axmand** [comment]
This error also occurred under c# (v2.7.0). Here is my code：

```c#
  Parallel.For(0, 10000 , (i) =>
            {
                float[] raw = pRasterLayerCursorTool.PickRagneNormalValue( 10, 10,  9, 9);
                int cover = dqn.Predict(state);
            });
````
```c#
      public float[] Predict(float[] input)
        {
            using (Value inputsValue = Value.CreateBatch(inputVariable.Shape, input, device))
            {
                var inputDict = new Dictionary<Variable, Value>() { { inputVariable, inputsValue } };
                var outputDict = new Dictionary<Variable, Value>() { { classifierOutput.Output, null } };
                classifierOutput.Evaluate(inputDict, outputDict, device);
                IList<IList<float>> prdicts = outputDict[classifierOutput.Output].GetDenseData<float>(classifierOutput.Output);
                float[] result = prdicts[0].ToArray();
                return result;
            }
        }
```
