### ISSUE TITLE
Can I print out the network graph from C++

### ISSUE THREAD

**Issue by OleStauning** [Microsoft/CNTK#1614]
I have created a network graph, entirely by using the C++ API. How can I print out the internal structure of this graph? (for debugging purposes). I found a function, `DoTopologyPlot`, but that seems to require an argument that comes from parsing brain-script.

Best Regards
/Ole

**Comment by chdinh** [comment]
Even though it is WIP you might find this interesting:
https://github.com/mne-tools/mne-cpp/blob/master/examples/ex_deep_model_viewer/main.cpp

![image](https://cloud.githubusercontent.com/assets/912787/24298941/ef5a8546-107d-11e7-8884-3bdf73b69e78.png)

**Comment by sayanpa** [comment]
Closing this issue since there was a suggestion and no further communication on this thread. Please reopen the issue with details if you need a follow up.

**Comment by yusuf-gunaydin** [comment]
I have converted the Python plotting codes to a C++ class. It creates a .dot file that you can use to create a .png, .svg, ... file using Graphviz. It is only one header file and requires boost graph classes to be found in include path.

The codes are [here](https://gist.github.com/yusuf-gunaydin/3f1a02844f8070dd2b3ae7e68f44704d).
