### ISSUE TITLE
GetIndex() for sparse gpu matrix

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1617]
I want to get the index of the non-zero elements in sparse matrix, and I use
`int* index= sparsematrix.GetIndex() ;`
in my program. I find it works when running on CPU. However, it will cause `segmentation fault (core dumped)` when running on GPU. Does `GetIndex()` function support GPU sparse matrix? What else should I do if I want to get index when using GPU?

**Comment by KeDengMS** [comment]
When the matrix is in GPU, GetIndex() returns a pointer to the GPU memory so you cannot directly access from CPU. You should use cudaMemcpy to copy the memory from device to host first.
