### ISSUE TITLE
Install failed with 2.0 beta15, with invalid URL 

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1619]
When i use anaconda to create a python environment, it always crashes as:
         Fetching package metadata ..........Error: Could not find URL: https://repo.continuum.io/pkgs/free/linux-64/linux-64/
It seems the URL has some problem: 404 Not Found.

**Comment by mahilleb-msft** [comment]
Hi @staplesinLA, is this run as part of the automated binary drop install, or do you create a Python environment yourself [maybe as part of the Python only install]? In the former case, which drop is it exactly that you're installing? In the latter case, what is the exact command you're using? Which Anaconda version and which OS are you on?

Thanks, Mark

**Comment by staplesinLA** [comment]
Hi Mark, my OS is ubuntu 16.04, Anaconda3.
1.  I use the script driven installation of CNTK for Linux v.2.0 Beta 15 GPU with 1bit-SGD:
 ./install-cntk.sh --py-version 27 --anaconda-basepath /root/anaconda3
It returns:
_...
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ..........Error: Could not find URL: https://repo.continuum.io/pkgs/free/linux-64/linux-64/
+ rm -rf /root/anaconda3/envs/cntk-py27
+ die 'Creating Anaconda environment failed.'
+ set +x
Creating Anaconda environment failed.
Go to https://github.com/Microsoft/CNTK/wiki/Setup-Linux-Binary-Script for help.
_

**Comment by staplesinLA** [comment]
The problem command in "install-cntk.sh" is located at:
/root/anaconda3/bin/conda env create --file /root/cntk/Scripts/install/linux/conda-linux-cntk-py27-environment.yml --prefix /root/anaconda3/envs/cntk-py27

**Comment by staplesinLA** [comment]
I use the manual installation and it works now. Thanks for help.
