### ISSUE TITLE
Do you have any example for autoencoder with UCIFReader?

### ISSUE THREAD

**Issue by jchung2050** [Microsoft/CNTK#162]
I would like to test autoencoder using CNTK.
Though there is an example of autoencoder whose input data is in scpFile, I'd like to do that with UCIF files. When I use UCIF files, it seems that I should prepare the label file which is not needed for training autoencoder.
If someone has working config file as an example for it, please share it.

**Comment by frankseide** [comment]
I have not tried it, but looking at the code, you should be able to simply leave out the labels section, or have a labels section with labelType = "none". Could you try that?

Both are supported by the code, but I don't know when that was last used, so please do let me know if this does not work, then it'd be a bug that we need to fix.

I will close this Issue for now, but please do reopen it if this does not work.
