### ISSUE TITLE
Anaconda 4.3.1 and Python 3.6  w/ CNTK? Install issue

### ISSUE THREAD

**Issue by arunkumarwa** [Microsoft/CNTK#1622]
Hello,  I am new - so please bear.  Just installed Anaconda 4.3.1 and Python 3.6 and am getting this error below:

The CNTK install site has instructions for Python 3.5 (I think) so I made a leap of faith assuming a whl exists for 3.6.  Can someone help ?

OR: if you suggest should I just go back to Python 3.5 with Anaconda 3 (?) to keep it easy. I want to get over the install, config issues as quickly to get on with experimenting with the algorithms,models and flows themselves.

thx
arun
PS:  also please forgive if I am posting in the wrong place etc...first time here.

pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl
Collecting cntk==2.0.beta15.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl
  HTTP error 404 while getting https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl
  Could not install requirement cntk==2.0.beta15.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl
Could not install requirement cntk==2.0.beta15.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd64.whl for URL https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta15.0-cp36-cp36m-win_amd6

**Comment by bencherian** [comment]
There is no build configuration for python 3.6 yet. Just create a python 3.5 environment for CNTK.

**Comment by arunkumarwa** [comment]
Thanks Benjamin...  after stumbling around I finally just found the scripts provided at the link below do the entire on stop installation:   Anaconda, python3.5 + packages install...plus setup the environment...  

https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script
