### ISSUE TITLE
How many parallel requests can i set?

### ISSUE THREAD

**Issue by yuanweilei** [Microsoft/CNTK#1623]
How many parallel requests can I set to maximalNumOfParallelRequests?

https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples/CNTKLibraryCSEvalExamples.cs

EvaluateMultipleImagesInParallel() 
 for (int i = 1; i < maximalNumOfParallelRequests; i++)
{
     Models.Add(rootFunc.Clone(ParameterCloningMethod.Share));
}

I trained a FastRCNN Model which is 220MB, and set maximalNumOfParallelRequests = 3 and use B1 App Service Plan to host it. When I upload more than 3 images at the same time, this app failed.

But if I set maximalNumOfParallelRequests = 2 and use the same B1 Plan, I can upload many images ( >3 ) at the same time. Max 2 images are evaluated at the same time, and 3rd~ images are evaluated after them (like queue).

When I use P3 Plan ( the highest), I can set maximalNumOfParallelRequests = 3 (or more).

**Comment by zhouwangzw** [comment]
With ParameterCloningMethod.Share, the cloned model instances share model parameters, and only private states are allocated in each model instance, so the memory overhead with clone should be quite small compared to model size. Our measurements also confirm that. Do you have any data about memory usage after cloning 1 or 2 models, and what is the image size  and memory usage during evaluation? What is the maximal memory limit for B1 and P3 Plan?

Thanks,

**Comment by yuanweilei** [comment]
@zhouwangzw Thank you!
In my PC, If maximalNumOfParallelRequests = 3 and after I evaluated 3 or more images, 1720MB memory usaged. If maximalNumOfParallelRequests = 2 and after I evaluated 2 or more images, 1270MB memory usaged. 
The memory limit for Azure App service Plan B1 is 1.75GB RAM and Azure App service Plan P3 is 7GB RAM.
So when I use  Plan B1 I can not set maximalNumOfParallelRequests = 3.

**Comment by zhouwangzw** [comment]
Would you mind to provide more details about memory usage, e.g. what is the memory usage after loading the first model, after cloning models, before evaluate an image, and after evaluation? It would be also helpful to know which consumes the most memory by using VS memory profiler.

**Comment by yuanweilei** [comment]
In Global.asax, I worte these : 
    public static BlockingCollection<Function> CNTKModels = new BlockingCollection<Function>();
    ......
    Function rootFunc = Function.LoadModel(modelFilePath, DeviceDescriptor.CPUDevice);
    CNTKModels.Add(rootFunc);
     for (int i = 1; i < maxParallelCNTKRequests; i++)
    {
         CNTKModels.Add(rootFunc.Clone(ParameterCloningMethod.Share));
    }

And I use the static CNTKModels in another class (MessagesController.cs) like this:
    1    var evaluatorFunc = WebApiApplication.CNTKModels.Take();
    ......
    2    var resized = bmp.Resize(1000, 1000, true);
    3    var resizedCHW = resized.ParallelExtractCHW();
    ......
    4    evaluatorFunc.Evaluate(inputDataMap, outputDataMap, DeviceDescriptor.CPUDevice);
    5    outputVal3.CopyVariableValueTo(outputVar2, outputBuffer);
    ......
    6    finally    {    WebApiApplication.CNTKModels.Add(evaluatorFunc);    }

After cloning model  (in row 1 at first time ):  250 MB memory are used.
in row 4 at first time: 370MB memory are used. (I created image bitmap, 500 rois list<float> and set them to inputDataMap) 
in row 5 at first time: 840MB memory are used. (and then I returned the results.)

When I upload 2nd image and in row 1 (2nd time): 840 MB memory are used.
and in row 5 at 2nd time: 1315 MB are used.

I upload 3rd image and in row 5 at 3rd time: 1700 MB are used.

So I think 450MB/clone are used.
Can I do something to release the memory when I get the result after row 5?

**Comment by yuanweilei** [comment]
@zhouwangzw Thank you very much! 
In Global.asax, I worte these :
    public static BlockingCollection CNTKModels = new BlockingCollection();
    ......
    Function rootFunc = Function.LoadModel(modelFilePath, DeviceDescriptor.CPUDevice);
    CNTKModels.Add(rootFunc);
    for (int i = 1; i < maxParallelCNTKRequests; i++)
    {
        CNTKModels.Add(rootFunc.Clone(ParameterCloningMethod.Share));
    }

And I use the static CNTKModels in another class (MessagesController.cs) like this:
    1 var evaluatorFunc = WebApiApplication.CNTKModels.Take();
    ......
    2 var resized = bmp.Resize(1000, 1000, true);
    3 var resizedCHW = resized.ParallelExtractCHW();
    ......
    4 evaluatorFunc.Evaluate(inputDataMap, outputDataMap, DeviceDescriptor.CPUDevice);
    5 outputVal3.CopyVariableValueTo(outputVar2, outputBuffer);
    ......
    6 finally { WebApiApplication.CNTKModels.Add(evaluatorFunc); }

After cloning model (in row 1 at first time ): 250 MB memory are used.
in row 4 at first time: 370MB memory are used. (I created image bitmap, 500 rois list and set them to inputDataMap)
in row 5 at first time: 840MB memory are used. (and then I returned the results.)

When I upload 2nd image and in row 1 (2nd time): 840 MB memory are used.
and in row 5 at 2nd time: 1315 MB are used.

I upload 3rd image and in row 5 at 3rd time: 1700 MB are used.
And then 1700MB are using during the app is running even I upload another image.
(Because I set maxParallelCNTKRequests = 3 ? )

So I think 450MB/clone are used.
Can I do something to release the memory when I get the result after row 5?

**Comment by zhouwangzw** [comment]
@yuanweilei As you said, after cloning model 250MB memory used, and your model is 220MB, that means the cloned models has very little memory overhead (30MB for 2 cloned instances). 
The most memory is used for image preprocessing, evaluation and output. I would recommend to use Visual Studio memory usage tool or profiler to identify which objects use the most memory and then check whether any optimization can be done.

**Comment by yuanweilei** [comment]
@zhouwangzw Thank you very much! I will try to reduce memory cost.
