### ISSUE TITLE
Customize library path pre-built binaries

### ISSUE THREAD

**Issue by cmpute** [Microsoft/CNTK#1624]
I've just downloaded the 2.0 beta 15 binaries and installed in my Windows 10 OS as the wiki said, all things go well till running the tutorials. But I find it that the cntk execution file does not able to detect my GPU. I believe it is because I did not install CUDA and cuDNN into the path described in the wiki, i.e. "c:/local/xxxx"

this is what it says when run cntk
![qq](https://cloud.githubusercontent.com/assets/9154441/24033619/c73d8842-0b28-11e7-9fc2-72fff2194fc0.png)
I have already set the environment variable to the path I install the libs, but it just did not recognize. 

But it is a bit awful that I didn't find a way to change the path which cntk uses, and now it seems I have to pull down the code and build the project by myself, which is a lot extra work.

I wish it will be able to customize the library path of the pre-built binaries.(or it's just that I didn't find the way?)

**Comment by wolfma61** [comment]
I'm not sure what problem you are describing 
please open a new issue if you experience this in a more recent CNTK installation
