### ISSUE TITLE
How to test model in Python?

### ISSUE THREAD

**Issue by FreedMana** [Microsoft/CNTK#1625]
I want to test the model trained in python. I follow the example in CNTK/Examples/Image/FeatureExtraction/FeatureExtraction.py , but i can't find my node name in my model. 

I use Sequential to build the training model:
>model = Sequential ([
>   For(range(3), lambda: \
>        Dense(2048, activation=C.sigmoid)),
>    Dense(257)
>])
>z = model(features) 

When testing,  i can't find exact node names:
>>>model_dnn= load_model("model.dnn")
>>>print ( get_node_outputs(model_dnn) )
>>>[Output('Block337_Output_0', [#, *], [257]), Output('Block322_Output_0', [#, *], [2048]), Output('Plus331_Output_0', [#, *], [257]), Output('Plus331_Output_0', [#, *], [257]), Output('Times329_Output_0', [#, *], [257]), Output('Block305_Output_0', [#, *], [2048]), Output('Sigmoid316_Output_0', [#, *], [2048]), Output('Plus314_Output_0', [#, *], [2048]), Output('Times312_Output_0', [#, *], [2048]), Output('Block288_Output_0', [#, *], [2048]), Output('Sigmoid299_Output_0', [#, *], [2048]), Output('Plus297_Output_0', [#, *], [2048]), Output('Times295_Output_0', [#, *], [2048]), Output('Sigmoid282_Output_0', [#, *], [2048]), Output('Plus280_Output_0', [#, *], [2048]), Output('Times278_Output_0', [#, *], [2048])]

>>>node_name = "Block337_Output_0"
>>>node_in_graph = model_dnn.find_by_name(node_name)
>>>print(node_in_graph)
>>>
This node_in_graph is empty value.  Why? Is it because i din't name every layer during training?

**Comment by cha-zhang** [comment]
You didn't name your model. You can double check it by using https://www.cntk.ai/pythondocs/cntk.logging.html?highlight=plot#cntk.logging.graph.plot.

**Comment by FreedMana** [comment]
@cha-zhang Thanks, I got it.
My test data are thousands of speech sequences. I use HTKFeature Reader in Python API .
Because i need the model output of each sentence. It's would be convenient to send in a precise number of frames in a minibatch to take care of variable-length sentences.
I got the same exception #1354  when i changed mbsize in reader.next_minibatch().

**Comment by sayanpa** [comment]
Could you please try adding a name explicitly say:
``Dense(257, name="my_Dense_257")``
Then you can access your model like mode ``model_dnn.my_Dense_257.shape`` or get the W or bias values.

**Comment by sayanpa** [comment]
Closing this for now. Please feel free to open new issues if you are still having issues.
