### ISSUE TITLE
Cannot find ''cntk-2.0.beta15.0-cp35-cp35m-win_amd64.whl'' in CNTK-2-0-beta15-0-Windows-64bit-GPU-1bit-SGD

### ISSUE THREAD

**Issue by xiangyang3131777** [Microsoft/CNTK#1626]
I can't  Install CNTK Python Environment because I find that there is no ''cntk-2.0.beta15.0-cp35-cp35m-win_amd64.whl'' in my downloaded ''CNTK-2-0-beta15-0-Windows-64bit-GPU-1bit-SGD''

**Comment by beci** [comment]
Same here, no any *.whl file in all package

**Comment by Quethrosar** [comment]
ditto

**Comment by cmpute** [comment]
the file can be fetched from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0.beta12.0-cp35-cp35m-win_amd64.whl or some kind of path like it.

**Comment by Quethrosar** [comment]
thanks.

is anyone else getting very bad results with things that worked before using the new beta 15? I was getting great detection in beta 11 but 15 doesn't detect much in my custom model.

**Comment by xiangyang3131777** [comment]
I find the solution by visiting "https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Python#installing-samples-and-tutorials"
