### ISSUE TITLE
bug or mistake? 

### ISSUE THREAD

**Issue by Feng-long** [Microsoft/CNTK#1627]
When I use the multitask function in cntk  as follows,

wtobjfcn(o1,w1,o2,w2)
	{
		A1 = Constant(w1)
		A2 = Constant(w2)
		T1 = Times(A1, o1)
		T2 = Times(A2, o2)
		O = Plus(T1, T2)
	}
criter2 =Log(posterior)
MSESqErr = SquareError(labels, output);
objfcn = wtobjfcn(MeanSqErr,1,criter2,1,tag=criteria)

The objfun is MeanSqErr\*10 + criter2\*1.  This only happens when the criter2 is Log(sth).  Anyone meet the same problem?

Thanks.

**Comment by DanielMerget** [comment]
You should try using ElementTimes() (or ".*") and not Times() ("*")

**Comment by sayanpa** [comment]
Closing this issue since there was a suggestion and no further communication on this thread. Please reopen the issue with details if you need a follow up.
