### ISSUE TITLE
C++ Library error - C2065: 'INTMAX_MAX' : undeclared identifier

### ISSUE THREAD

**Issue by Birky** [Microsoft/CNTK#1630]
Hey guys,

I have an existing trained model and I would like to evaluate it through the CNTK C++ Library.
I installed _Microsoft CNTK Eval CPUOnly-mkl_ and _Microsoft CNTK Eval CPUOnly-acml_ through NuGet manager. I also set up the include files path for the Visual Studio, but when I include the #include "CNTKLibrary.h" I got the following error after compilation:

> error C2065: 'INTMAX_MAX' : undeclared identifier

I googled a lot and I used the following solution:

```
#define INT64_MAX    _I64_MAX
#define INTMAX_MAX   INT64_MAX
```

but than a new error occured:

> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: enum CNTK::VariableKind __cdecl CNTK::Variable::Kind(void)const " (__imp_?Kind@Variable@CNTK@@QEBA?AW4VariableKind@2@XZ)
> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl CNTK::TrainingParameterSchedule<double>::TrainingParameterSchedule<double>(double,enum CNTK::TrainingParameterSchedule<double>::UnitType)" (__imp_??0?$TrainingParameterSchedule@N@CNTK@@QEAA@NW4UnitType@01@@Z)
> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl CNTK::TrainingParameterSchedule<double>::~TrainingParameterSchedule<double>(void)" (__imp_??1?$TrainingParameterSchedule@N@CNTK@@UEAA@XZ)
> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl CNTK::TrainingParameterSchedule<double>::TrainingParameterSchedule<double>(class CNTK::TrainingParameterSchedule<double> &&)" (__imp_??0?$TrainingParameterSchedule@N@CNTK@@QEAA@$$QEAV01@@Z)
> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) private: void __cdecl CNTK::MomentumAsTimeConstantSchedule::ConvertToPerSampleValues(void)" (__imp_?ConvertToPerSampleValues@MomentumAsTimeConstantSchedule@CNTK@@AEAAXXZ)
> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl CNTK::ThrowFormatted<class std::runtime_error>(char const *,...)" (__imp_??$ThrowFormatted@Vruntime_error@std@@@CNTK@@YAXPEBDZZ)
> 1>braintumoursegmentation.obj : error LNK2001: unresolved external symbol "public: virtual class CNTK::Dictionary __cdecl CNTK::TrainingParameterSchedule<double>::Serialize(void)const " (?Serialize@?$TrainingParameterSchedule@N@CNTK@@UEBA?AVDictionary@2@XZ)

What could be the problem? I am using Visual Studio 2013, does it requires 2015?

I also could not install _Microsoft CNTK, GPU Build 2.0.0-beta9_ neither _Microsoft CNTK, CPU-Only Build 2.0.0-beta9_ through NuGet manager. It said:

> Install failed. Rolling back...
> Could not install package 'CNTK.CPUOnly 2.0-beta9'. You are trying to install this package into a project that targets 'Native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any idea what is the problem or what am I doing wrong?

Thank you.

Best regards,
Robert

**Comment by zhouwangzw** [comment]
@Birky Visual Studio 2015 Update 3 is required to use the CNTK C++ Library, and the target platform should be set to **x64** in your project property. We would recommnd CNTK.CPUOnly or CNTK.GPU Library. 
After installing the Nuget package to your project, you should be able to use it without configuring include or library path (the Nuget package should have configured it). This[ page ](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows#using-the-c-cntk-library-api-for-evaluation) describes how to use the API. 
The examples [here](https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation) illustrate the usage pattern above. The [Eval Examples](https://github.com/Microsoft/CNTK/wiki/CNTK-Eval-Examples) page provides detailed steps about building and running examples.

ps. The CNTK Eval CPUOnly-mkl is the V1 Eval API, and CNTK Eval CPUOnly-acml is deprected. You can find more information [here 
](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview).

Thanks.
