### ISSUE TITLE
How to build a DRNN model with python?

### ISSUE THREAD

**Issue by xiangyang3131777** [Microsoft/CNTK#1634]
How to build a DRNN model which there are total 3 hidden layers and the 2nd hidden layer uses recurrent connections. In addition, how to define the input?

**Comment by sayanpa** [comment]
Can you provide a pointer to the DRNN model paper or doc where a bit more info on what the first & third hidden layer is better illustrated / described. CNTK 202 tutorial shows how to stack layers and how recurrence layer can be stacked within a model.

**Comment by xiangyang3131777** [comment]
Thanks for your help. I will try it again.

The structure of this model is defined as follow (it is used to be prediction):
[image](https://user-images.githubusercontent.com/25403572/28166602-1abf2f0e-680b-11e7-9f0a-3ecf30977c7e.png)

This is the relevant paper: 
https://arxiv.org/pdf/1502.04149.pdf

**Comment by sayanpa** [comment]
Something like this should work:
```
z = c.layers.Sequential([c.layers.Dense(10), \
                                      c.layers.For(range(3), lambda x: [c.layers.Recurrence(c.layers.LSTM(100))]), \
                                      c.layers.Dense(2)])
```
