### ISSUE TITLE
[Question] Any plans to support LDA?

### ISSUE THREAD

**Issue by Spiderixius** [Microsoft/CNTK#1637]
Hello, any plans to support [LDA](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) algorithm for topics?

**Comment by n17s** [comment]
We don't have any plans for LDA in CNTK in the near future. 

There are many good tools for LDA out there. We recommend [LightLDA](https://github.com/Microsoft/LightLDA), a very fast and scalable implementation by some of our colleagues (and contributors to CNTK). 

I'm closing this. Feel free to reopen if necessary.

**Comment by Spiderixius** [comment]
Thanks! I will give that a look.
