### ISSUE TITLE
Feature request: Multi GPU support for model evaluation

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/CNTK#1638]
As far as I was able to verify, the `write` action in CNTK (BrainScript) does not support using multiple GPUs, but always only uses a single GPU. For running vast amounts of images through a convolutional net, it would be super helpful to be able to use multiple GPUs. Currently, we batch up the test data and run multiple jobs, but that always feels awkward.

**Comment by avader906** [comment]
does the ```test``` action support multiple GPU evaluation ?

**Comment by KeDengMS** [comment]
Evaluator in python supports multiple GPUs. @eldakms, do you think it can be implemented for BS?

**Comment by eldakms** [comment]
eval command in brain script also performs evaluation on multiple gpus.

The initial question is about "write" though, which is always performed on the main worker.

**Comment by ebarsoumMS** [comment]
Please use Python.
