### ISSUE TITLE
Compilation error with the Kaldi-plugin

### ISSUE THREAD

**Issue by mirco86** [Microsoft/CNTK#164]
Hi, 
I would like to share with you some errors I had when compiling the latest CNKT code with the Kaldi plug in.

In particular I had an error when trying to compile "Source/Readers/Kaldi2Reader/DataWriter.cpp":

`mpic++ -c Source/Readers/Kaldi2Reader/DataWriter.cpp -o /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/home/mravanelli/cub-1.4.1 -I/home/mravanelli/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/home/mravanelli/kaldi-trunk/src -I/home/mravanelli/kaldi-trunk/tools/ATLAS/include -I/home/mravanelli/kaldi-trunk/tools/openfst/include -MD -MP -MF /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.d`

The error was this:

```
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::GetWriter(Microsoft::MSR::CNTK::IDataWriter<ElemType>**) [with ElemType = float]’:
Source/Readers/Kaldi2Reader/DataWriter.cpp:27:22:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:22:14: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’
     *pwriter = new HTKMLFWriter<ElemType>();
              ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   because the following virtual functions are pure within ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’:
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:14:0:
Source/Common/Include/DataWriter.h:65:18: note:         bool Microsoft::MSR::CNTK::IDataWriter<ElemType>::SupportMultiUtterances() const [with ElemType = float]
     virtual bool SupportMultiUtterances() const = 0;
                  ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::GetWriter(Microsoft::MSR::CNTK::IDataWriter<ElemType>**) [with ElemType = double]’:
Source/Readers/Kaldi2Reader/DataWriter.cpp:31:22:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:22:14: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’
     *pwriter = new HTKMLFWriter<ElemType>();
              ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   because the following virtual functions are pure within ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’:
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:14:0:
Source/Common/Include/DataWriter.h:65:18: note:         bool Microsoft::MSR::CNTK::IDataWriter<ElemType>::SupportMultiUtterances() const [with ElemType = double]
     virtual bool SupportMultiUtterances() const = 0;
                  ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::CNTK::ConfigParameters; ElemType = double]’:
Source/Common/Include/DataWriter.h:135:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::CNTK::ConfigParameters&) [with ElemType = double]’
Source/Readers/Kaldi2Reader/DataWriter.cpp:98:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’ has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::ScriptableObjects::IConfigRecord; ElemType = double]’:
Source/Common/Include/DataWriter.h:139:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::ScriptableObjects::IConfigRecord&) [with ElemType = double]’
Source/Readers/Kaldi2Reader/DataWriter.cpp:98:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’ has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::CNTK::ConfigParameters; ElemType = float]’:
Source/Common/Include/DataWriter.h:135:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::CNTK::ConfigParameters&) [with ElemType = float]’
Source/Readers/Kaldi2Reader/DataWriter.cpp:99:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’ has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::ScriptableObjects::IConfigRecord; ElemType = float]’:
Source/Common/Include/DataWriter.h:139:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::ScriptableObjects::IConfigRecord&) [with ElemType = float]’
Source/Readers/Kaldi2Reader/DataWriter.cpp:99:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’ has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
```

After a comparison with an older working version of CNTK, I have observed that the error can be simply avoided by commenting the line "virtual bool SupportMultiUtterances() const = 0;" of the file "Source/Common/Include/DataWriter.h". However, this generates other errors when compiling different sources (e.g., mpic++ -c ../CNTK-master3/Source/ActionsLib/EvalActions.cpp ...). 
It seems there are some issues related to the  "SupportMultiUtterances".

I finally was finally able to compile all by simply removing/adding the line SupportMultiUtterances when necessary, but this is clearly a bad idea.

Any idea about how to solve it?

Mirco

PS
I actually had a problem when comping HTKMLFReader.cpp

**Comment by yzhang87** [comment]
Hi,

I recently submit a pull request to fix the compile error. But I haven't
test the function for multi utterance.

thanks,
Yu

On Fri, Feb 26, 2016 at 11:48 AM, mirco86 <notifications@github.com> wrote:

> Hi,
> I would like to share with you some errors I had when compiling the latest
> CNKT code with the Kaldi plug in.
>
> In particular I had an error when trying to compile
> "Source/Readers/Kaldi2Reader/DataWriter.cpp":
>
> mpic++ -c Source/Readers/Kaldi2Reader/DataWriter.cpp -o
> /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o
> -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN
> -DUSE_ACML -DNDEBUG -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN
> -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400
> -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new
> -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math
> -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib
> -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript
> -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk
> -I/home/mravanelli/cub-1.4.1 -I/home/mravanelli/cuda-7.0/include
> -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include
> -I/home/mravanelli/kaldi-trunk/src
> -I/home/mravanelli/kaldi-trunk/tools/ATLAS/include
> -I/home/mravanelli/kaldi-trunk/tools/openfst/include -MD -MP -MF
> /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.d
>
> The error was this:
>
> Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::GetWriter(Microsoft::MSR::CNTK::IDataWriter<ElemType>**) [with ElemType = float]’:
> Source/Readers/Kaldi2Reader/DataWriter.cpp:27:22:   required from here
> Source/Readers/Kaldi2Reader/DataWriter.cpp:22:14: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’
>      *pwriter = new HTKMLFWriter<ElemType>();
>               ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   because the following virtual functions are pure within ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’:
>  class HTKMLFWriter : public IDataWriter<ElemType>
>        ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:14:0:
> Source/Common/Include/DataWriter.h:65:18: note:         bool Microsoft::MSR::CNTK::IDataWriter<ElemType>::SupportMultiUtterances() const [with ElemType = float]
>      virtual bool SupportMultiUtterances() const = 0;
>                   ^
> Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::GetWriter(Microsoft::MSR::CNTK::IDataWriter<ElemType>**) [with ElemType = double]’:
> Source/Readers/Kaldi2Reader/DataWriter.cpp:31:22:   required from here
> Source/Readers/Kaldi2Reader/DataWriter.cpp:22:14: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’
>      *pwriter = new HTKMLFWriter<ElemType>();
>               ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   because the following virtual functions are pure within ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’:
>  class HTKMLFWriter : public IDataWriter<ElemType>
>        ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:14:0:
> Source/Common/Include/DataWriter.h:65:18: note:         bool Microsoft::MSR::CNTK::IDataWriter<ElemType>::SupportMultiUtterances() const [with ElemType = double]
>      virtual bool SupportMultiUtterances() const = 0;
>                   ^
> Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::CNTK::ConfigParameters; ElemType = double]’:
> Source/Common/Include/DataWriter.h:135:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::CNTK::ConfigParameters&) [with ElemType = double]’
> Source/Readers/Kaldi2Reader/DataWriter.cpp:98:16:   required from here
> Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’
>      m_dataWriter = new HTKMLFWriter<ElemType>();
>                   ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’ has pure virtual functions
>  class HTKMLFWriter : public IDataWriter<ElemType>
>        ^
> Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::ScriptableObjects::IConfigRecord; ElemType = double]’:
> Source/Common/Include/DataWriter.h:139:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::ScriptableObjects::IConfigRecord&) [with ElemType = double]’
> Source/Readers/Kaldi2Reader/DataWriter.cpp:98:16:   required from here
> Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’
>      m_dataWriter = new HTKMLFWriter<ElemType>();
>                   ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<double>’ has pure virtual functions
>  class HTKMLFWriter : public IDataWriter<ElemType>
>        ^
> Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::CNTK::ConfigParameters; ElemType = float]’:
> Source/Common/Include/DataWriter.h:135:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::CNTK::ConfigParameters&) [with ElemType = float]’
> Source/Readers/Kaldi2Reader/DataWriter.cpp:99:16:   required from here
> Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’
>      m_dataWriter = new HTKMLFWriter<ElemType>();
>                   ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’ has pure virtual functions
>  class HTKMLFWriter : public IDataWriter<ElemType>
>        ^
> Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::ScriptableObjects::IConfigRecord; ElemType = float]’:
> Source/Common/Include/DataWriter.h:139:30:   required from ‘void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::ScriptableObjects::IConfigRecord&) [with ElemType = float]’
> Source/Readers/Kaldi2Reader/DataWriter.cpp:99:16:   required from here
> Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’
>      m_dataWriter = new HTKMLFWriter<ElemType>();
>                   ^
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type ‘Microsoft::MSR::CNTK::HTKMLFWriter<float>’ has pure virtual functions
>  class HTKMLFWriter : public IDataWriter<ElemType>
>
> After a comparison with an older working version of CNTK, I have observed
> that the error can be simply avoided by commenting the line "virtual bool
> SupportMultiUtterances() const = 0;" of the file
> "Source/Common/Include/DataWriter.h". However, this generates other errors
> when compiling different sources (e.g., mpic++ -c
> ../CNTK-master3/Source/ActionsLib/EvalActions.cpp ...).
> It seems there are some issues related to the "SupportMultiUtterances".
>
> I finally was finally able to compile all by simply removing/adding the
> line SupportMultiUtterances when necessary, but this is clearly a bad idea.
>
> Any idea about how to solve it?
>
> Mirco
>
> PS
> I actually had a problem when comping HTKMLFReader.cpp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/CNTK/issues/164>.
>



-- 
Yu Zhang
Computer Science and Artificial Intelligence Laboratory (CSAIL)
Massachusetts Institute of Technology

**Comment by atuxhe** [comment]
Hi,

In Source/Readers/Kaldi2Reader/HTKMLFReader.cpp

a "}" was deleted at the end of function HTKMLFReader<ElemType>::DataEnd()

and then add a line,

virtual bool SupportMultiUtterances() const { return false; };

in file Source/Readers/Kaldi2Reader/HTKMLFWriter.h

It's should be OK .

**Comment by mirco86** [comment]
Guys,
I tried to compile the latest version of the code, but unfortunately there is another error when compiling the kaldi plug-in:

```
creating /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o for with build type release
mpic++ -c Source/Readers/Kaldi2Reader/DataWriter.cpp -o /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/home/mravanelli/cub-1.4.1 -I/usr/local/cuda-7.0//include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/home/mravanelli/kaldi-trunk//src -I/home/mravanelli/kaldi-trunk//tools/ATLAS/include -I/home/mravanelli/kaldi-trunk//tools/openfst/include -MD -MP -MF /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.d
```
```
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:17:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:45:32: error: expected nested-name-specifier before ‘IDataWriter’
     using LabelType = typename IDataWriter<ElemType>::LabelType;
                                ^
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:45:32: error: ‘Microsoft::MSR::CNTK::IDataWriter’ is not a template
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:46:34: error: expected nested-name-specifier before ‘IDataWriter’
     using LabelIdType = typename IDataWriter<ElemType>::LabelIdType;
                                  ^
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:46:34: error: ‘Microsoft::MSR::CNTK::IDataWriter’ is not a template
make[1]: *** [/home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o] Error 1
make[1]: Leaving directory `/hardmnt/oktem0/home/mravanelli/CNTK-master'
make: *** [all] Error 2
```
Any idea?

Mirco

**Comment by yzhang87** [comment]
Fixed on my branch. Will send a pull request after I finish the test.

thanks,
Yu

On Fri, Mar 4, 2016 at 3:43 PM, mirco86 <notifications@github.com> wrote:

> Guys,
> I tried to compile the latest version of the code, but unfortunately there
> is another error when compiling the kaldi plug-in:
>
> creating /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o for with build type release
> mpic++ -c Source/Readers/Kaldi2Reader/DataWriter.cpp -o /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/home/mravanelli/cub-1.4.1 -I/usr/local/cuda-7.0//include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/home/mravanelli/kaldi-trunk//src -I/home/mravanelli/kaldi-trunk//tools/ATLAS/include -I/home/mravanelli/kaldi-trunk//tools/openfst/include -MD -MP -MF /home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.d
>
> In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:17:0:
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:45:32: error: expected nested-name-specifier before ‘IDataWriter’
>      using LabelType = typename IDataWriter<ElemType>::LabelType;
>                                 ^
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:45:32: error: ‘Microsoft::MSR::CNTK::IDataWriter’ is not a template
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:46:34: error: expected nested-name-specifier before ‘IDataWriter’
>      using LabelIdType = typename IDataWriter<ElemType>::LabelIdType;
>                                   ^
> Source/Readers/Kaldi2Reader/HTKMLFWriter.h:46:34: error: ‘Microsoft::MSR::CNTK::IDataWriter’ is not a template
> make[1]: *** [/home/mravanelli/CNTK-master/build/release/.build/Source/Readers/Kaldi2Reader/DataWriter.o] Error 1
> make[1]: Leaving directory `/hardmnt/oktem0/home/mravanelli/CNTK-master'
> make: *** [all] Error 2
>
> Any idea?
>
> Mirco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/CNTK/issues/164#issuecomment-192460299>.
>



-- 
Yu Zhang
Computer Science and Artificial Intelligence Laboratory (CSAIL)
Massachusetts Institute of Technology

**Comment by dongyu888** [comment]
pull request merged.
