### ISSUE TITLE
User Functions and SSD

### ISSUE THREAD

**Issue by Vedaevolution** [Microsoft/CNTK#1640]
Dear Developers,

at the moment i'm trying to implement SSD in cntk. It is a pain to formulate the error function in cntk blocks so it's a good thing to have the new user functions.

I'm aware of the concept with forward and backward pass for gradient descent. I know what i need to do there. 

I have two problems: 
1.) I'm not sure how to correctly handle multiple inputs.
2.) I don't know how to handle the dynamic axis in the "infer_outputs" method.

Would it be possible to create or code a more sepcific example concerning user functions?
I don't need much help but a little more explanation than there is in the python doc right now would be great.

**Edit:** There is another question. The user functions example in the python api doc uses numpy. This seems to mean that at least the user function is computed on the cpu. Is the rest of the network computed on the gpu or is everything a cpu computation when using user functions?

Best regards

**Comment by whaozl** [comment]
Do you work well?

**Comment by pkranen** [comment]
Hi Vedaevolution, 

you can see examples for user functions with multiple inputs and outputs in this branch: [https://github.com/Microsoft/CNTK/tree/pkranen/cntkrpn/Examples/Image/Detection/FasterRCNN/lib/rpn](https://github.com/Microsoft/CNTK/tree/pkranen/cntkrpn/Examples/Image/Detection/FasterRCNN/lib/rpn). I'd suggest to look at [SmoothL1](https://github.com/Microsoft/CNTK/blob/pkranen/cntkrpn/Examples/Image/Detection/FasterRCNN/lib/rpn/cntk_smoothL1_loss.py) or [ProposalTargetLayer](https://github.com/Microsoft/CNTK/blob/pkranen/cntkrpn/Examples/Image/Detection/FasterRCNN/lib/rpn/proposal_target_layer.py). Let me know if that answers your questions.

**Comment by whaozl** [comment]
@pkranen , Hi, I had seen two branch: pkranen/rpn and pkranen/bboxregression In microsoft/cntk. The pkranen/bboxregression and SmoothL1 is used by ssd(object detection). This means the cntk-ssd will release? Thank you very much!

**Comment by whaozl** [comment]
@pkranen , Hi, I had seen two branch: pkranen/rpn and pkranen/bboxregression In microsoft/cntk. The pkranen/bboxregression and SmoothL1 is used by ssd(object detection). This means the cntk-ssd will release? Thank you very much!

**Comment by n17s** [comment]
For the followup question: the rest of the network executes on the GPU. You can even have the user function execute on the GPU (if you write code that manipulates the underlying NDArrayViews). But the user function will execute on the CPU if it uses NumPy.

Closing this. Feel free to reopen if there are additional questions. Also, if you got Single Shot Detector working on CNTK, we appreciate pull requests.
