### ISSUE TITLE
Cannot build CPU image on docker

### ISSUE THREAD

**Issue by lburzawa** [Microsoft/CNTK#1642]
Hi,

I want to train and evaluate a deep network on CNTK through docker on a Mac. Am I correct in understanding that I should build a CNTK docker image first? I tried to build a CPU image but I got the error below. First I thought it's because I have clang rather than gcc but I got the same error after installing and activating gcc 4.8.5 through macports. Does anybody know what else could be an issue? I am very new to all three platforms MacOS, docker and CNTK and will appreciate advice.

g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_OPENBLAS -I /usr/local/openblas/include -I /usr/local/kaldi-c024e8aa/tools/openfst/include -Wno-sign-compare -DHAVE_OPENFST_GE_10400 -std=c++0x -g  -fPIC   -c -o transcripts-to-fsts.o transcripts-to-fsts.cc
g++: internal compiler error: Killed (program cc1plus)
g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_OPENBLAS -I /usr/local/openblas/include -I /usr/local/kaldi-c024e8aa/tools/openfst/include -Wno-sign-compare -DHAVE_OPENFST_GE_10400 -std=c++0x -g  -fPIC   -c -o kws-search.o kws-search.cc
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[1]: *** [lattice-faster-online-decoder.o] Error 4
make[1]: *** Waiting for unfinished jobs....

**Comment by alexeyo26** [comment]
Hello! Would not it be easier just to use our [CNTK Images at Docker Hub](https://github.com/Microsoft/CNTK/wiki/CNTK-Docker-Containers#using-cntk-images-published-at-docker-hub)?
