### ISSUE TITLE
training_session can  not restore checkpoint while using preserve_all

### ISSUE THREAD

**Issue by boren-ms** [Microsoft/CNTK#1643]
while using training _session to train and restore from previous models, it can not catch the checkpoints if preserve_all = True given, in both windows and linux.

I have found that this maybe due to bugs in TrainingSession::RestoreFromCheckpoint.
 msra::files::get_all_files_from_directory(parent) can not find any files at least in windows 10 what I have checked.

any help will be appreciate

**Comment by eldakms** [comment]
Thank you very much for reporting!

I am looking into this. It will be fixed shortly (probably tomorrow). 

For now as a workaround you can use preserve_all=False, or copy the checkpoint with the <checkpointName><highest Id> and <checkpointName><highestId>.ckp to just <checkpointName> and <checkpointName>.ckp

**Comment by eldakms** [comment]
Hi,

this has been fixed in the eldak/fixingPreserveAll branch. It will soon be merged into master and available in the next release.

Thank you!

**Comment by rosrad** [comment]
Thanks

**Comment by n17s** [comment]
Closing. Feel free to reopen.
