### ISSUE TITLE
CTC Python

### ISSUE THREAD

**Issue by vaasily** [Microsoft/CNTK#1649]
I found a couple of examples of working with CTC via BrainScript. Is CTC support for Python implemented?

**Comment by igormq** [comment]
+1

**Comment by vmazalov** [comment]
You can refer to this tutorial https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_208_Speech_Connectionist_Temporal_Classification.ipynb

Keep in mind that it relies on some changes which are in master, but not in the official build. The next release is planned sometime in the end of July. You can try the tutorial now, if you build from master.
