### ISSUE TITLE
User defined Image transformations in CNTK

### ISSUE THREAD

**Issue by ujjwal-researcher** [Microsoft/CNTK#1650]
**Problem setting** 

- I have a dataset with `N` images.

- A certain network (e.g - Alexnet) has to be trained from scratch over this dataset.

- For each image, `10` augmented versions are to be produced. These augmentations involve resizing, cropping and flipping. For example - an image has to be resized with minimum dimension of `256` pixels and then a random crop of `224 x 224` of it is to be taken. Then it has to be flipped. `5` such random crops have to be taken and their flipped versions also have to be prepared.

- Those augmented versions have to go inside the network for training **instead of the original image**

- What would be additionally very beneficial is that, multiple images in the dataset are augmented in parallel and put in a queue or any container from where a` batchsize` number of samples are pushed into the GPU for training.

1. The reason is that we would not ideally like multiple augmented versions of the same image going into the network for training simultaneously. 

**Context**

1.  It is not a random feature requirement. There are some papers such as [OverFeat](https://arxiv.org/pdf/1312.6229.pdf) which involve such augmentations. Moreover such a random training can be a very good idea to improve the training of the network.

**My understanding**

To the best of my search, I could not find any framework inside CNTK that can do this.

**Questions**

1. Is it possible to achieve in CNTK ?

If it is a functionality not available in CNTK, a feature like that would be tremendously invaluable.

**Comment by pkranen** [comment]
crop_type=multiview10 does exactly this including spreading the augmentation across several mini batches. See also [here](https://www.cntk.ai/pythondocs/cntk.io.html?highlight=multiview10).
