### ISSUE TITLE
Image classification error

### ISSUE THREAD

**Issue by SherylZhou** [Microsoft/CNTK#1651]
Hi, 

I tried to debug the phython script AlexNet_ImageNet_Distributed.py in vs2015 and ran into an error:
..\Image\DataSets\ImageNet\train_map.txt' does not exist.
In the ImageNet folder, there are only two ImageNet1K_xxx.xml files. Any idea?

Thanks,
Sheryl

**Comment by cha-zhang** [comment]
We don't offer ImageNet dataset due to license issues. You need to download it yourself and construct train_map.txt yourself.

**Comment by SherylZhou** [comment]
Could you provide another python script using other available datasets later on? Anyway, I'll close the ticket for now. Thanks.

**Comment by cha-zhang** [comment]
Check https://github.com/Microsoft/CNTK/blob/master/Examples/Image/DataSets/CIFAR-10/install_cifar10.py for how to write train_map.txt files.
