### ISSUE TITLE
Nuget package silently fails to include the native libraries if the solution platform is not set to x64

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1652]
Create a new project.
The project and solution are set to "Any CPU" by default.
Install the CNTK.CpuOnly nuget package.
Try to build the project.
The compiler complains that the project platform is incompatible with the referenced library platform.
Go to the project properties and set the project platform target to x64.
Now the project builds, but fails in runtime.
The package silently failed to include the native libraries since the *solution* was not set to x64, even though the project was x64.

Two possible solutions to the problem (both can be used):
1. Show error instead of silently not including the native libraries.
2. Check the PlatformTarget and not Platform to detect the project platform target.

**Comment by zhouwangzw** [comment]
Thanks for reporting the issue. We will improve the error message and also check how to support X64 project within non-X64 solution.
