### ISSUE TITLE
Wrong number or type of arguments for overloaded function

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1657]
Hello, in Python API, i load the mean and inv_std files from numpy, and want to use built-in function  per_dim_mean_variance_normalize. But it crashes like:
NotImplementedError: Wrong number or type of arguments for overloaded function 'per_dim_mean_variance_normalize'.
I read the instructions of this function, did i offer it wrong type arguments? Thanks.
##features = Input(100)
##mean =np.loadtxt('mean.txt')
##std =np.loadtxt('inv_std.txt')
##norm_features = per_dim_mean_variance_normalize(features,mean,std)

**Comment by n17s** [comment]
The following works for me.
```
import cntk as C
import numpy as np
x = C.input_variable(2)
m = np.zeros(2).astype('f')
v = np.ones(2).astype('f')
z = C.per_dim_mean_variance_normalize(x,m,v)
print(z.eval({x:3*v}))
```
with result
```
[[ 3.,  3.]]
```
Feel free to reopen with more information.
