### ISSUE TITLE
Evaluate example does not work

### ISSUE THREAD

**Issue by aFuerst** [Microsoft/CNTK#1662]
The example located [here](https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network) does not work when I to run it exactly as in the example. It seems to be out of date, using Function.eval() which doesn't exist (I had to change it to Function.evaluate())

Even after making that change it throws this error:

  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 1363, in evaluate
    return _cntk_py.Function_evaluate(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Function_evaluate'.
  Possible C/C++ prototypes are:
    CNTK::Function::Evaluate(std::unordered_map< CNTK::Variable,CNTK::ValuePtr > const &,std::unordered_map< CNTK::Variable,CNTK::ValuePtr > &,CNTK::DeviceDescriptor const &)
    CNTK::Function::Evaluate(std::unordered_map< CNTK::Variable,CNTK::ValuePtr > const &,std::unordered_map< CNTK::Variable,CNTK::ValuePtr > &)

The documentation for Function.evaluate() doesn't list any arguments to I can't figure out what parameters I should be passing in.

**Comment by ebarsoumMS** [comment]
Hi,

Which version of CNTK are you using?

Thanks,
Emad

**Comment by aFuerst** [comment]
This is what i get from PIP
cntk (2.0.beta15.0)

**Comment by aFuerst** [comment]
@ebarsoumMS Have you had any luck looking into this?

**Comment by zhouwangzw** [comment]
I can run the following script to evaluate resnet_cifar10 model. The only change is add resize, as the model expects 32x32 input. Could you please try to run it? 

from cntk.ops.functions import load_model
from PIL import Image 
import numpy as np

z = load_model("resnet20.dnn")
img = Image.open("zebra.jpg")
resized = img.resize((32, 32), Image.ANTIALIAS)
rgb_image = np.asarray(resized, dtype=np.float32) - 128
bgr_image = rgb_image[..., [2, 1, 0]]
pic = np.ascontiguousarray(np.rollaxis(bgr_image, 2))

predictions = np.squeeze(z.eval({z.arguments[0]:[pic]}))
top_class = np.argmax(predictions)
print(top_class)

**Comment by aFuerst** [comment]
I ran it against the actual cifar10 example to separate it from my code. It runs and prints the number 7. 

What is the difference between cntk.cntk_py.Function.load_model and cntk.ops.functions.load_model?

**Comment by zhouwangzw** [comment]
cntk.ops.functions.load_model is the public API method. Internally, it calls cntk.cntk_py:Function.load_model plus some addtional pre-processing. You should use cntk.ops.functions.load_model.

**Comment by aFuerst** [comment]
That's an odd distinction, thanks for your assistance!

**Comment by aFuerst** [comment]
That's an odd distinction, thanks for your assistance!

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to reopen it needed.

**Comment by aFuerst** [comment]
What are the differences between these two way of evaluating images? They subtract different means from the input data but it doesn't say where they are determined, and each re-arrange the order of pixels being sent to the network. The first one mentions PIL loading data differently than the network expects but I can't find anything more about this elsewhere. When I try either of these approaches to do my own evaluations I always get 50% error rate and it thinks all my samples are the same.

https://github.com/Microsoft/CNTK/wiki/Evaluate-a-saved-convolutional-network
'''
rgb_image = np.asarray(Image.open("foo.jpg"), dtype=np.float32) - 128
bgr_image = rgb_image[..., [2, 1, 0]]
pic = np.ascontiguousarray(np.rollaxis(bgr_image, 2))
'''
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb
'''
    image_mean   = 133.0
    image_data   = np.array(PIL.Image.open(image_path), dtype=np.float32)
    image_data  -= image_mean
    image_data   = np.ascontiguousarray(np.transpose(image_data, (2, 0, 1)))
    
    result       = np.squeeze(pred_op.eval({pred_op.arguments[0]:[image_data]}))
'''
