### ISSUE TITLE
The evaluation results of c# and python are different.

### ISSUE THREAD

**Issue by xbgydxlq** [Microsoft/CNTK#1663]
I used python code and c# code to extract “z.x” layer of resnet18 model. But I got different results. I thought the reason may be caused by different preprocessing. I thought I have already align the preprocessing. The details are as below.

Python code:

https://github.com/Microsoft/CNTK/blob/master/Examples/Image/FeatureExtraction/FeatureExtraction.py,

The preprocessing of input file is included in:

def create_mb_source(image_height, image_width, num_channels, map_file):
	    transforms = [xforms.scale(width=image_width, height=image_height, channels=num_channels, interpolations='linear')]
	    return MinibatchSource(ImageDeserializer(map_file,
	       StreamDefs(features=StreamDef(field='image', transforms=transforms))), # first column  in map file is referred to as 'image'
	        randomize=False)  

The default layout of input in deserializer is HWC .

C＃ code:

                string modelFilePath = @"D:\CNTK-Samples-2-0-beta12-0\Examples\Image\PretrainedModels\ResNet_18.model";
                ThrowIfFileNotExist(modelFilePath, string.Format("Error: The model '{0}' does not exist. Please follow instructions in README.md in <CNTK>/Examples/Image/Classification/ResNet to create the model.", modelFilePath));
                Function modelFunc = Function.LoadModel(modelFilePath, device);
                Function interLayerFunc = modelFunc.FindByName("z.x");
                modelFunc = CNTKLib.AsComposite(interLayerFunc);
                Variable inputVar = modelFunc.Arguments.Single();

                // Get shape data for the input variable
                NDShape inputShape = inputVar.Shape;
                uint imageWidth = inputShape[0];
                uint imageHeight = inputShape[1];
                uint imageChannels = inputShape[2];
                uint imageSize = inputShape.TotalSize;

                Variable outputVar = modelFunc.Output;

                var inputDataMap = new Dictionary<Variable, Value>();
                var outputDataMap = new Dictionary<Variable, Value>();
              
                string sampleImage = @"D:\CNTK-Samples-2-0-beta12-0\Examples\Image\DataSets\Grocery\testImages\WIN_20160803_11_28_42_Pro.jpg";
                ThrowIfFileNotExist(sampleImage, string.Format("Error: The sample image '{0}' does not exist. Please see README.md in <CNTK>/Examples/Image/DataSets/CIFAR-10 about how to download the CIFAR-10 dataset.", sampleImage));
                Bitmap bmp = new Bitmap(Bitmap.FromFile(sampleImage));
                var resized = bmp.Resize((int)imageWidth, (int)imageHeight, true);
                List<float> resizedCHW = resized.ParallelExtractHWC ();

                // Create input data map
                var inputVal = Value.CreateBatch(inputVar.Shape, resizedCHW, device);
                inputDataMap.Add(inputVar, inputVal);
                outputDataMap.Add(outputVar, null);

                // Start evaluation on the device
                modelFunc.Evaluate(inputDataMap, outputDataMap, device);

                // Get evaluate result as dense output
                var outputBuffer = new List<List<float>>();
                var outputVal = outputDataMap[outputVar];
                outputVal.CopyVariableValueTo(outputVar, outputBuffer);

                PrintOutput(outputVar.Shape.TotalSize, outputBuffer);

I converted the image to HWC layout too.

The preprocessing of both code is: resize->convert to hwc. Is there anything else I missed? Is there any bug in my code? Can anyone give me some suggesions?

**Comment by mirero** [comment]
How to fix it?
