### ISSUE TITLE
No GPUs found on deployment machine

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#1664]
Hi,

Previously I've deployed CNTK on a machine other than the one I build it on by collecting CNTK.exe, all DLLs in the Release folder, Visual Studio DLLs (VC redistributable), and CNTK.core.bs and copying over to a new machine (my dev machine has no NVIDIA GPU). I haven't done this for a while (since about nov/dec 2016) and much has changed (VS2013->VS2015 for one, also Cuda 7.5->8). The strategy works still, but I can't run with GPU:

Latest:
-------------------------------------------------------------------
Build info: 

		Built time: Mar 27 2017 02:14:25
		Last modified date: Sun Mar 26 22:15:42 2017
		Build type: Release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
		CUB_PATH: c:\local\cub-1.4.1
		CUDNN_PATH: c:\local\cudnn-8.0-v5.1\cuda
		Build Branch: master
		Build SHA1: 2bd14b7026448a10700d9ceb02c5a1d68299eda8 (modified)
		Built by derek on DESKTOP-M8BR5NU
		Build Path: C:\repos\HGDL\Source\CNTKv2LibraryDll\
		MPI distribution: Microsoft MPI
		MPI version: 7.0.12437.6
-------------------------------------------------------------------
No GPUs found      <**********************

Old (exactly same pc, and problem):
-------------------------------------------------------------------
Build info: 

		Built time: Mar 14 2017 22:16:57
		Last modified date: Tue Mar 14 22:16:00 2017
		Build type: Release
		Build target: GPU
		With 1bit-SGD: no
		Math lib: mkl
		CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
		CUB_PATH: c:\src\cub-1.4.1\
		CUDNN_PATH: C:\NVIDIA\cudnn-5.1\cuda
		Build Branch: master
		Build SHA1: 624f6d8282cf6c36f8be40e1cea3dd338a2b1df2 (modified)
		Built by DerekR on DevMachine
		Build Path: C:\src\HGDL\Source\CNTK\
-------------------------------------------------------------------
-------------------------------------------------------------------
GPU info:

		Device[0]: cores = 384; computeCapability = 3.5; type = "GeForce GT 740M"; memory = 2048 MB
-------------------------------------------------------------------

I tried dependency walker and it identified two missing DLLs (nvml.dll and IESHIMS.dll). I suspected the former of being an issue, but copying from another location on the target machine results in the same output (i.e. no GPU). Now dependency walker doesn't report any issues. Any thoughts on what I've done wrong? Same result on a second PC (of similar age).

Thanks in advance

D.

**Comment by dmagee** [comment]
Files in deployment are:

Cntk.Composite-2.0beta16.dll
Cntk.Core-2.0beta16.dll
CNTK.core.bs
Cntk.Core.CSBinding-2.0beta16.dll
Cntk.Core.Managed-2.0beta16.dll
Cntk.Deserializers.Binary-2.0beta16.dll
Cntk.Deserializers.HTK-2.0beta16.dll
Cntk.Deserializers.Image-2.0beta16.dll
Cntk.Deserializers.TextFormat-2.0beta16.dll
Cntk.Eval-2.0beta16.dll
Cntk.Eval.Wrapper-2.0beta16.dll
Cntk.Math-2.0beta16.dll
Cntk.PerformanceProfiler-2.0beta16.dll
Cntk.Reader.Binary.Deprecated-2.0beta16.dll
Cntk.Reader.DSSM-2.0beta16.dll
Cntk.Reader.HTKMLF-2.0beta16.dll
Cntk.Reader.LMSequence-2.0beta16.dll
Cntk.Reader.LUSequence-2.0beta16.dll
Cntk.Reader.SparsePC-2.0beta16.dll
Cntk.Reader.SVMBinary-2.0beta16.dll
Cntk.Reader.UCIFast-2.0beta16.dll
CNTKBinaryReader.dll
concrt140.dll
cublas64_80.dll
cudart64_80.dll
cudnn64_5.dll
curand64_80.dll
cusparse64_80.dll
CNTK.exe
libiomp5md.dll
ManagedEvalTests.dll
Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
mkl_cntk_p.dll
msvcp140.dll
nvml.dll
opencv_world310.dll
vccorlib140.dll
vcomp140.dll
vcruntime140.dll
zip.dll
zlib.dll

**Comment by zhouwangzw** [comment]
Does nvidia-smi.exe on your machine show which GPUs are available? If yes, could you please try to copy nvml.dll from C:\Program Files\NVIDIA Corporation\NVSMI to the output directory (replacing the existing one), and then run cntk.exe?

**Comment by dmagee** [comment]
Ok, nvidia-smi.exe gives:


Tue Mar 28 09:23:17 2017
+------------------------------------------------------+
| NVIDIA-SMI 353.90     Driver Version: 353.90         |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 740M    WDDM  | 0000:01:00.0     N/A |                  N/A |
| N/A   67C    P0    N/A /  N/A |     54MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

I copied nvml.dll from C:\Program Files\NVIDIA Corporation\NVSMI, but still No GPUs found  in CNTK.

D

**Comment by dmagee** [comment]
In an attempt to track down the cause I downloaded the lastest binary release to see if that would work.. It doesn't...

-------------------------------------------------------------------
Build info: 

		Built time: Mar 27 2017 02:14:25
		Last modified date: Sun Mar 26 22:15:42 2017
		Build type: Release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
		CUB_PATH: c:\local\cub-1.4.1
		CUDNN_PATH: c:\local\cudnn-8.0-v5.1\cuda
		Build Branch: master
		Build SHA1: 2bd14b7026448a10700d9ceb02c5a1d68299eda8 (modified)
		Built by derek on DESKTOP-M8BR5NU
		Build Path: C:\repos\HGDL\Source\CNTKv2LibraryDll\
		MPI distribution: Microsoft MPI
		MPI version: 7.0.12437.6
-------------------------------------------------------------------
No GPUs found

**Comment by dmagee** [comment]
Also, put some debug information in the compiled version and cudaGetDeviceCount() call in BestGpu.cpp is failing:

    cudaError_t err = cudaGetDeviceCount(&m_deviceCount);
	if (err != cudaSuccess) {
		std::cerr << "BestGpu::Init() cudaGetDeviceCount failed: " << err << std::endl;
		m_deviceCount = 0; // if this fails, we have no GPUs
	}

This returns an error code of 35,which means "CUDA driver version is insufficient for CUDA runtime version". I'm interpreting this as the GPU driver doesn't support Cuda8. I thought I had a pretty recent driver installed, but maybe not ...

**Comment by zhouwangzw** [comment]
Greate to know that it works with the latest driver. We will try to improve the error message. 

I am closing the issue. Please feel free to reopen it if needed.

Thanks.
