### ISSUE TITLE
how to add 1bit-SGD on TransferLearning example?

### ISSUE THREAD

**Issue by roger77** [Microsoft/CNTK#1665]
I'm just getting started and the TransferLEarning is a great example for me. I'd like to add 1bit-SGD but all the example I find do not seem to apply to this case.

Thanks

**Comment by n17s** [comment]
Typically going distributed is as simple as wrapping your local learner with a distributed learner 
e.g.
```
parameter_learner = block_momentum_distributed_learner(local_learner, block_size=block_size)
```
or 
```
parameter_learner = data_parallel_distributed_learner(local_learner, num_quantization_bits=num_quantization_bits, distributed_after=warm_up)
```
If that's not working for you in the TransferLearning example, feel free to reopen this with followup questions.
