### ISSUE TITLE
Evaluate costume graph in c#

### ISSUE THREAD

**Issue by gilzo** [Microsoft/CNTK#1666]
Hello. I implemented a custom operator in pure Python as described in https://www.cntk.ai/pythondocs/extend.html. It works great in python but when I try to load the graph in C# I get an error. Is it possible to create a new operator in pure python and then evaluate in C# or C++ ?

Thanks

**Comment by zhouwangzw** [comment]
This is currently not supported yet. But we are working on it.

**Comment by gilzo** [comment]
Thank you for your response.

Gil.

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by gilzo** [comment]
Thanks!.



2017-06-07 9:04 GMT+03:00 JimSw2016 <notifications@github.com>:

**Comment by zhouwangzw** [comment]
Closing it. Please free to reopen it if needed.
