### ISSUE TITLE
Setup location should be changed for consistency

### ISSUE THREAD

**Issue by harewei** [Microsoft/CNTK#1667]
In [https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script](url)

During Step 2 Run the installation script, it says 
````
cd c:\local\CNTK-2-0-beta15-0
cd cntk\Scripts\install\windows
install.bat
````
which is saying the folder structure is c:\local\CNTK-2-0-beta15-0\cntk\scripts

yet in the following Step 4 Verify the setup from Python (as well as Step 5), it says
````
cd c:\local\CNTK-2-0-beta15-0
cd scripts
cntkpy35.bat
````
which is now saying the folder structure is c:\local\CNTK-2-0-beta15-0\scripts

It's something minor, but I think you should keep them consistent

**Comment by wolfma61** [comment]
this has been changed since then
