### ISSUE TITLE
CustomMKL not recognizing Xeon Phi coprocessors

### ISSUE THREAD

**Issue by ils04** [Microsoft/CNTK#1672]
Hi

I have a box equipped with Intel(R) Xeon Phi(TM) Coprocessor and running CentOS 7.3
My environment looks like this:

cntk-2.0.beta15
Anaconda3-4.1.1
cntk-py35
mpss-3.8.1
CustomMKL-3

I can query the Coprocessors using micinfo, ssh into them, and stress-test them using micprun.  However, when I try to run any of CNTP Python examples (e.g. Tutorials/ImageHandsOn/CifarConverter.py), it only uses CPU, not Coprocessor.  

I tried export MKL_MIC_ENABLE=1, but it had no effect.  

I would appreciate any points as to how I can actually take advantage of the Coprocessor using CNTK Python.

Thanks,

Igor

**Comment by KeDengMS** [comment]
Xeon Phi automatic offload to coprocessor is enabled based on matrix size:
https://software.intel.com/en-us/articles/intel-mkl-automatic-offload-enabled-functions-for-intel-xeon-phi-coprocessors

CNTK uses MKL and it is up to MKL to decide when workloads go to coprocessor.

**Comment by n17s** [comment]
Closing. Feel free to reopen.
