### ISSUE TITLE
Need cntk source debug advice: Cntk.exe results do not agree with c# or c++ eval. 

### ISSUE THREAD

**Issue by bbuchika** [Microsoft/CNTK#1673]
My question is how to inspect the tensor data (image data) being passed into the network while debugging the cntk.exe source code. I'm here:

>	CNTK.exe!Microsoft::MSR::CNTK::SimpleOutputWriter<float>::WriteOutput()

I can see local variables like 
StreamMinibatchInputs inputMatrices = DataReaderHelpers::RetrieveInputMatrices(inputNodes);

but how do I get to the actual matrix data? If I could see the data feeding the network, I suspect that will reveal the problem. Unless there is a bug somewhere. 

Our project is stuck until we resolve this. Using Beta 15 for all operations (well, except the cntk.exe src which is the newest main branch updated today). We're analyzing images with Alexnet. Training goes well, with very low errors, but c# or c++ eval results makes no sense, with very high errors, no correlation to the cntk.exe write block results results. I can provide any files / test projects you would like. 

Thanks for any help you can provide. 
-Brant

**Comment by zhouwangzw** [comment]
@bbuchika If you are dealing with images, you probably need some image pre-processing before calling eval, since there is no image reader/deserilizer involved during evel. For example, for ResNet, the example [here ](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples/CNTKLibraryCSEvalExamples.cs) does resize and extractCHW before eval.

**Comment by bbuchika** [comment]
Thank you for your prompt response.  My critical need is to see the exact values passed into the network inside the cntk.exe source code.  I am familiar with that example (CNTKLibraryManagedExamples.EvaluationSingleImage), in fact that was the basis for my c# eval implementation.  Can you tell me how to see the float values passed into the network in the function:
CNTK.exe!Microsoft::MSR::CNTK::SimpleOutputWriter::WriteOutput()? 

I am able to see the values earlier on in the code inside ScaleTransformer::ScaleTransformer, and notice that my 8-bit grayscale image is upsampled to a 24-bit image, which is a bit interesting. I wonder if that could be part of the problem. 

So I know what I'm passing into the "features" variable in my c++ and c# implementations, but I need to see the exact values passed into the network inside the cntk.exe code. I suspect that will help me diagnose the problem. If the input values are different, that would explain the different results. 

Thanks again for your help.
-Brant

**Comment by bbuchika** [comment]
So I was able to get to the data via the following function / variable::
In function: bool DataReader::GetMinibatch(StreamMinibatchInputs& matrices)
matrices.inputs[L"features"].second.matrix[ptr].m_CPUMatrix[ptr]m_sob[ptr].m_pArray

So it looks like for some reason the data is bad. The upsampling corrupts the data. so my tensor which should be something like [14.0 15.0 21.0 ...] instead is [14.0 14.0 14.0 15.0 15.0 15.0 21.0 21.0 21.0 ....] and then the latter 2/3 of my image data is truncated. 

Either the image reader has a bug or I am not configuring the reader block correctly in my *.cntk file. I have an 8-bit grayscale image, is the following reader block correct?

    reader = {
        verbosity = 2
        randomize = false
#        randomizationWindow = 1

        deserializers = (
        {   
            type = "ImageDeserializer" ; module = "ImageReader"
            file = $pathWriteInput$
            input = {
                features = {
                    transforms = (
						{
                            type = "Scale"
							scaleMode="crop"
                            width = 240
                            height = 240
                            channels = 1
                            interpolations = "linear"
                        }
                    )
                }
                labels = {
                    labelDim = 2
                }
            }
        })
    }

**Comment by bbuchika** [comment]
I think I solved it.  We are using grayscale images but we did not specify that in our image reader:

grayscale = true

        deserializers = (
        {   
            type = "ImageDeserializer" ; module = "ImageReader"
            file = $pathWriteInput$
	        grayscale = true
            input = {
				# features = { transforms = () }
                features = {
                    transforms = (
						{
                            type = "Scale"
							scaleMode="crop"
                            width = 240
                            height = 240
                            channels = 1
                            interpolations = "linear"
                        }
                    )
                }
                labels = {
                    labelDim = 2
                }
            }
        })



Might be good to make sure that is documented on the wiki somewhere. 

Thanks,
Brant

**Comment by zhouwangzw** [comment]
Great to know that it works now. We will update wiki.

I am closing the issue. Please feel free to reopen it if needed.

Thanks.
