### ISSUE TITLE
File descriptor leak? (cntk fails to close some files)

### ISSUE THREAD

**Issue by nis8192** [Microsoft/CNTK#1675]
Hi

I installed CNTK-2-0-beta15-0-Linux-64bit-GPU.tar.gz on a machine running CentOS-7.

When I run cntk/Examples/Image/Classification/AlexNet/Python/AlexNet_ImageNet_Distributed.py on the machine,
python fails to close some file descriptors of training image files.
After a long run, the number of file descriptors used by the python process
gradually increase.
At last, the process crushes with a following error message:

RuntimeError: Cannot open file '/data/imagenet/train/n02488291/n02488291_4025.JPEG'

Using lsof, I figured out that most of the open file descriptors are associated with 
*.JPEG which are training images.

--shingo

**Comment by mahilleb-msft** [comment]
Hi @nis8192, we're using OpenCV for reading individual images. It sounds like it could be this bug with OpenCV 3.1:
https://github.com/opencv/opencv/issues/6162
We'll look at updating our OpenCV dependency soon... Until then, a potential work-around is to use Images within a .zip file, see https://github.com/Microsoft/CNTK/wiki/BrainScript-Image-reader.

Hope this helps,

Mark

**Comment by wolfma61** [comment]
this has been changed
please open a new issue if you experience this in a more recent CNTK installation

**Comment by anijain2305** [comment]
Hi,

Can you please point me to the commit that fixed this leak?
