### ISSUE TITLE
no select_last() function

### ISSUE THREAD

**Issue by kylemarkwilliams** [Microsoft/CNTK#1679]
The [Python Layers API documentation](https://www.cntk.ai/pythondocs/layerref.html) describes a select_last() function; however, I cannot find this function anywhere. Also, is there a select_first() function?

**Comment by whaozl** [comment]
I also don't find select_last. But I find you can use Fold layer. and don't need use Recurrent.

**Comment by Ark-kun** [comment]
Is [cntk.ops.sequence.last](https://www.cntk.ai/pythondocs/cntk.ops.sequence.html?highlight=last#cntk.ops.sequence.last) what you're looking for?

**Comment by Master76** [comment]
I guess they've just forgotten to update the example. The former implementation was here:
Note: the files in the 'common' folder are deprecated and will be replaced by the layer library.
[select_last()](https://github.com/Microsoft/CNTK/blob/master/Examples/common/nn.py#L69) at line 69.

**Comment by kylemarkwilliams** [comment]
@Ark-kun Yes, last does the trick as does the Fold layer suggested by @whaozl.

Thanks
