### ISSUE TITLE
Hi,I want to calculate the inverse of a matrix.Is there any corresponding function?How can I achieve it?

### ISSUE THREAD

**Issue by luyamalu** [Microsoft/CNTK#1682]

**Comment by cha-zhang** [comment]
Are you thinking of a node that does matrix inversion? I doubt we have it.

**Comment by luyamalu** [comment]
Yes,I want a node that does matrix inversion.But I have not found the node yet.I will try to continue looking for it.Thank you very much!

**Comment by cha-zhang** [comment]
You can do it in numpy as CNTK supports interop with numpy. I don't think we have a CNTK implementation of matrix inversion.

**Comment by n17s** [comment]
Yes the simplest way to do this right now is to use [CNTK extensibility](https://www.cntk.ai/pythondocs/extend.html) to write a function that uses Numpy to do the inversion.

Feel free to reopen if you have further questions.
