### ISSUE TITLE
CUDA CUBLAS_STATUS_ALLOC_FAILED 

### ISSUE THREAD

**Issue by cmarschner** [Microsoft/CNTK#1688]
>RuntimeError: CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; 
This should print out more information about the allocation attempt - how much memory was requested, how much was available etc. Right now there is no indication how to resolve the problem, or whether the bug might be in the code

**Comment by cha-zhang** [comment]
How is your network look like? Does it just contain fully connected layers?

**Comment by Vedaevolution** [comment]
CNTK indeed needs more information about such errors. I often had the problem that i spend some time on solving issues that where very easy to solve but i got no indication about the actual problem.

cntk rc. 2.0 debugging features are quite nice btw.
