### ISSUE TITLE
Non-deterministic MaxPooling layer

### ISSUE THREAD

**Issue by v-niveli** [Microsoft/CNTK#1690]
If I try the network in CNTK/Example/Image/GettingStarted/02_OneConv.cntk on a GPU with adding the flag "forceDeterministicAlgorithm = true" and run it several times I get always the same results.

If I then change the kernel size in MaxPooling layer to 3:3 (from 2:2) and run the same training several times I get different results every time, i.e. the training is not reproducible anymore.

Do you know why this is happening?

**Comment by cha-zhang** [comment]
Maxpooling is not always deterministic as it uses NVidia's convolution implementation and it's not always deterministic. 

Deterministic flag hasn't been working for anything related to convolution. We are actively working with NVidia to fix this issue. Expect this be ready in a few weeks.

**Comment by cha-zhang** [comment]
This should have been resolved after 2.2 release.
