### ISSUE TITLE
Problem with python transformations

### ISSUE THREAD

**Issue by patykov** [Microsoft/CNTK#1691]
Hi!

I'm doing some trainings with a ResNet50 using python and cntk 2.15 and I've noticed that if I don't use the scale transformation the code just don't execute. It doesn't show any errors or outputs, it simply stops!
For example, if I use:

`transforms = [
		xforms.crop(crop_type='randomarea', crop_size=224, jitter_type='uniratio'),
		xforms.scale(width=image_width, height=image_height, channels=num_channels, interpolations='linear'),
		xforms.mean(mean_file)]`

Everything works fine, but with:

`transforms = [
		xforms.crop(crop_type='randomarea', crop_size=224, jitter_type='uniratio'),
		xforms.mean(mean_file)
	]`

It stops and I have no idea why.

Another problem I had was with crop: If I do a scale to a bigger size and then a crop to the size i need, the image will stay in the scale size. 
For example, if i do:

`transforms = [
		xforms.crop(crop_type='randomarea', crop_size=224, jitter_type='uniratio'),
		xforms.mean(mean_file)]`

I won`t have an 224x224 image as result, i need to do:

`transforms = [
		xforms.crop(crop_type='randomarea', crop_size=224, jitter_type='uniratio'),
		xforms.scale(width=224, height=224, channels=num_channels, interpolations='linear'),
		xforms.mean(mean_file)]`.

To get a 224x224 image.

And something like:

`transforms = [
xforms.scale(width=256, height=256, channels=num_channels, interpolations='linear'),
		xforms.crop(crop_type='randomarea', crop_size=224, jitter_type='uniratio'),
		xforms.mean(mean_file)]`

Will give me a 256x256 image, not a 224x224.

Is this supposed to happen?

**Comment by cha-zhang** [comment]
When crop_size is specified, side_ratio, area_ratio and aspect_ratio will be ignored. Is this what you intend to do?

**Comment by patykov** [comment]
Yes, I want a 224x224 random crop from a 320x240 image, so I just need to specify the crop_size, right?

**Comment by cha-zhang** [comment]
Should be. It's not working?

**Comment by patykov** [comment]
I guess not, because when I only use the crop transformation I get an error about the image size saying that the network needs an 224x224 image and I am sending one of 320x240.

**Comment by cha-zhang** [comment]
Are all your images of size larger than 224x224? Is there any image in your collection that has width or height smaller than 224? If that's the case, then having crop_size=224 won't work.

**Comment by patykov** [comment]
Yes, I am sure. And I also tried: 

`transforms = [ xforms.scale(width=256, height=256, channels=num_channels, interpolations='linear'), xforms.crop(crop_type='randomarea', crop_size=224, jitter_type='uniratio'), xforms.mean(mean_file)]`

And it gives me a 256x256 image, not a 224x224.

I just got the new release candidate and it gives me the same errors:
- It does not work without scale
- Crop transfrom does not change the image size

**Comment by cha-zhang** [comment]
ok, we will investigate it. Thanks!

**Comment by cha-zhang** [comment]
I looked into the code, and realized that the crop transform doesn't have input to specify the number of channels for the input image. As a result, the exact output size (width, height, depth) can't be specified completely. Therefore even if you use crop_size, you are still expected to have a scale transform afterwards to specify the number of input channels. 

The additional cost of scale transform to an identical size should be low. So do make sure you always have a scale transform after crop transform.

**Comment by patykov** [comment]
Thank you!!!
