### ISSUE TITLE
Providing final LSTM state as input to another LSTM

### ISSUE THREAD

**Issue by kylemarkwilliams** [Microsoft/CNTK#1693]
I'm trying to build the following architecture:
Embeddings -> Forward LSTM -> Backward LSTM -> Concat Final States -> Concat external embedding -> LSTM

My code looks like this:

```i = Input(features)
e = Embedding(25)(i)

# Forward and backward LSTM
h_f = Recurrence(LSTM(25), go_backwards=False)(e)
h_b = Recurrence(LSTM(25), go_backwards=True)(e)

# Get the final states and splice
f = sequence.last(h_f)
b = sequence.first(h_b)
e1 = splice(f, b)

# Get the other embedding and concat
i2 = Input(100)
e2 = Embedding(100)(wi)
e2 = sequence.first(word_embedding)
e3 = splice(e1, e2)

# Input concatenated embedding to new LSTM
r = Recurrence(LSTM(50))(e3)
```

When I do this I get the following error: 
`Input operand 'Output('Block1994_Output_0', [#], [50])' with #dynamic axes != 2 (1 sequence axis and 1 batch axis) is not supported.`

If I do not get the final state of my first bidirectional LSTM then it works fine, but that's not what I want. Any ideas?

**Comment by kylemarkwilliams** [comment]
As a simpler example, the same error occurs if one tries this:

`i = Input(features)
e = Embedding(25)(i)
h_f = Fold(LSTM(25), go_backwards=False)(e)
s = Recurrence(LSTM(25))(h_f)
`
This is the error: 
`RuntimeError: PastValue/FutureValue Function 'PastValue: Output('Block1174_Output_0', [#], [25]) -> Output('PastValue1106_Output_0', [???], [???])': Input operand 'Output('Block1174_Output_0', [#], [25])' with #dynamic axes != 2 (1 sequence axis and 1 batch axis) is not supported.`

**Comment by mawah** [comment]
Hi Kyle,

I'm a bit confused by the goal but hope this will help. Some of your variables (`wi`, `word_embedding`) are not defined in the original code snippet, but I'll assume you meant to write something like:
```
i2 = Input(100)
e2 = Embedding(100)(i2)
e2 = sequence.first(e2)
```
If so, note that the output of e3 is not a sequence. Presumably the outputs of `f`, `b`, and `e2` are vectors, and you want to iterate over their contents in triplets? If so, I think you'll need to write your own function to define how to create a triplet sequence from the output value of `e3`. I'd check out the [`UnfoldFrom`](https://www.cntk.ai/pythondocs/cntk.layers.html?highlight=fold#cntk.layers.sequence.UnfoldFrom) function for that purpose.

**Comment by n17s** [comment]
@mawah is right. It does not make sense to run a recurrence on the last output because it is not itself a sequence. Feel free to reopen if you have more questions.
