### ISSUE TITLE
Error in building with Kaldi2Reader

### ISSUE THREAD

**Issue by tz579** [Microsoft/CNTK#1696]
There are multiple error messages similar to the one as below when building with Kaldi2Reader:

    creating .build/Source/Readers/Kaldi2Reader/KaldiSequenceTrainingDerivative.o for Linux with build type release
    /usr/lib/openmpi/bin/mpic++ -c Source/Readers/Kaldi2Reader/KaldiSequenceTrainingDerivative.cpp -o .build/Source/Readers/Kaldi2Reader/KaldiSequenceTrainingDerivative.o -DHAS_MPI=1 -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_MKL -DNDEBUG -DNO_SYNC -DCNTK_PARALLEL_TRAINING_SUPPORT -DASGD_PARALLEL_SUPPORT  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -DCNTK_COMPONENT_VERSION="2.0beta16" -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/CNTKv2LibraryDll/proto -ISource/../Examples/Extensibility/CPP -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -ISource/PerformanceProfilerDll -I/usr/local/protobuf/include -I/usr/local/cuda/include -I/usr/local/cub -I/usr/local/cuda/include -I/usr/local/cuda/include -I/usr/local/mkl/3/include -I/home/Applications/kaldi/src -I/home/Applications/kaldi/tools/ATLAS/include -I/home/Applications/kaldi/tools/openfst/include -I/usr/local/boost/include -I/usr/local/opencv/include -ISource/1BitSGD -ISource/Multiverso/include -ITests/EndToEndTests/CNTKv2Library/Common -I/usr/local/boost/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF .build/Source/Readers/Kaldi2Reader/KaldiSequenceTrainingDerivative.d
    In file included from Source/Readers/Kaldi2Reader/minibatchiterator.h:13:0,
                     from Source/Readers/Kaldi2Reader/rollingwindowsource.h:13,
                     from Source/Readers/Kaldi2Reader/DataReader.cpp:18:
    Source/Readers/Kaldi2Reader/ssematrix.h:1729:1: error: ‘pair’ does not name a type
     pair<unsigned int, unsigned int> printmatvaluedistributionf(const char *name, const M &m)

The configuration variables shown in Config.make is as below:

    BUILDTYPE=release
    MATHLIB=mkl
    MKL_PATH=/usr/local/mkl
    MKL_THREADING=parallel
    CNTK_CUSTOM_MKL_VERSION=3
    HAS_MPI=1
    CUDA_PATH=/usr/local/cuda
    GDK_INCLUDE_PATH=/usr/local/cuda/include
    GDK_NVML_LIB_PATH=/usr/local/cuda/lib64/stubs
    CUB_PATH=/usr/local/cub
    CUDNN_PATH=/usr/local
    KALDI_PATH=/home/Applications/kaldi
    OPENCV_PATH=/usr/local/opencv
    CNTK_ENABLE_1BitSGD=true
    BOOST_PATH=/usr/local/boost
    PROTOBUF_PATH=/usr/local/protobuf
    MPI_PATH=/usr/lib/openmpi
    CNTK_ENABLE_ASGD=true

The versions of some building dependencies are listed as below:

    gcc 4.8.5
    openmpi 2.0.2
    cntkcustommkl 3
    cuda 8.0
    cudnn 5.1 for cuda 8.0
    cub 1.5.2
    opencv 3.2.0
    boost 1.63.0
    protobuf 3.2.0
    kaldi trunk (a version in March 14)

Thanks!

**Comment by mahilleb-msft** [comment]
Hi @tz579, we are using a specific Kaldi version to build against, and do not track Kaldi's master.
Please check out the Linux Dockerfile:
https://github.com/Microsoft/CNTK/blob/master/Tools/docker/CNTK-CPUOnly-Image/Dockerfile#L105-L125

Best, Mark

**Comment by weijianwen** [comment]
@tz579 thank you. Similar issues happen then it hass been resolved by installing the specific version of Kaldi required by CNTK. This issue can be closed now.

**Comment by tz579** [comment]
@weijianwen @mahilleb-msft Thank you all. I am closing this one now.
