### ISSUE TITLE
What exactly are dynamic axes in cntk? Documentation missing!

### ISSUE THREAD

**Issue by Vedaevolution** [Microsoft/CNTK#1699]
I can't find any documentation about dynamic axes but the term is used widely.

Best regards

**Comment by mahilleb-msft** [comment]
Hi @Vedaevolution, would this help:
  https://cntk.ai/pythondocs/sequence.html
?

Best, Mark

**Comment by Vedaevolution** [comment]
@mahilleb-msft Thank you very much. I simply did not find this. My bad.
