### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by edran** [Microsoft/CNTK#17]
As per [Github guide](https://help.github.com/articles/setting-guidelines-for-repository-contributors/), you can set a `CONTRIBUTING.md` to help the community write pull requests or reviewing their commits. This should include preferred code style per language, commit messages guidelines and other related preferences.

**Comment by chrisbasoglu** [comment]
Hi edran.  Our contribution processes will be placed in CONTRIBUTING.md  within a few days.

**Comment by veikkoeeva** [comment]
I'd be interested to know if any contributions would be OK, however small and if it is OK to introduce non-backwards compatible changes and newer C++ constructs. If it's OK to advertise something, I think [Orleans](https://github.com/dotnet/orleans) and [F#](https://github.com/fsharp/fsharp) have nicely flowing contribution style.

**Comment by chrisbasoglu** [comment]
@veikkoeeva, contributions are OK, for breaking changes, please have a discussion with us first.  We have not published our contribution guidelines yet because we are still working to get our external build-and-test infrastructure deployed.  We expect that to be ready soon.

**Comment by veikkoeeva** [comment]
@chrisbasoglu Sure thing that about discussion. I know virtually nothing about deep learning, but I noticed I could, perhaps, help improve the code a here and there a bit purely on technical basis. I hope I can make actual time in the future and learn about the subject matter itself.

As a layman, it strikes to me, by the way, there could be synergy to be had here with integrating with [Multiverso](https://github.com/Microsoft/multiverso), maybe even with [Prajna](https://github.com/MSRCCS/Prajna) (via P/Invoke). Maybe worth considering.

**Comment by alexeyo26** [comment]
Just to re-confirm. We're working on Contribution guidelines and will publish them really soon.

Thank you,
Alexey

**Comment by alexeyo26** [comment]
Contributions guidelines are now published in [Wiki](../wiki/Contributing-to-CNTK)
