### ISSUE TITLE
MNIST convolution example doesn't converge if ReLU used in NDL file instead of Macro file

### ISSUE THREAD

**Issue by Likhit** [Microsoft/CNTK#170]
*\* **Using current binary release for Windows** **
First off, on CPU, the MNIST example for the convolution doesn't converge with the default learning rate of 0.5; changing it to 0.05 makes it converge (as mentioned in another thread), although learning rate of 0.5 works on GPU for some reason.

Second, if remove the ReLu unit from the macros file and use it in the NDL file, the network fails to converge with either of the above learning rates, on both CPU, and GPU. To illustrate, the current code is for the form:

**Macro file**

```
ConvReLULayer(inp, outMap, inWCount, kW, kH, hStride, vStride, wScale, bValue) = [
    convW = Parameter(outMap, inWCount, init="uniform", initValueScale=wScale)
    convB = ImageParameter(1, 1, outMap,     init="fixedValue", value=bValue, imageLayout=$imageLayout$)
    conv = Convolution(convW, inp, kW, kH, outMap, hStride, vStride, zeroPadding=false, imageLayout=$imageLayout$)
    convPlusB = Plus(conv, convB);
    act = RectifiedLinear(convPlusB);
]
```

**NDL file**

```
conv1_act = ConvReLULayer(featScaled, cMap1, 25, kW1, kH1, hStride1, vStride1, 10, 1)
conv2_act = ConvReLULayer(pool1, cMap2, 400, kW2, kH2, hStride2, vStride2, 10, 1)
```

This works on GPU with the default learning rate, but gets stuck at TrainingLossPerSample of ~0.89 on CPU. Works if learning rate is decreased to 0.05. But if we change the code a bit so:

**Macro file**

```
ConvLayer(inp, outMap, inWCount, kW, kH, hStride, vStride, wScale, bValue) = [
    convW = Parameter(outMap, inWCount, init="uniform", initValueScale=wScale)
    convB = ImageParameter(1, 1, outMap,     init="fixedValue", value=bValue, imageLayout=$imageLayout$)
    conv = Convolution(convW, inp, kW, kH, outMap, hStride, vStride, zeroPadding=false, imageLayout=$imageLayout$)
    convPlusB = Plus(conv, convB);
]
```

**NDL file**

```
conv1_act = RectifiedLinear(ConvLayer(featScaled, cMap1, 25, kW1, kH1, hStride1, vStride1, 10, 1))
conv2_act = RectifiedLinear(ConvLayer(pool1, cMap2, 400, kW2, kH2, hStride2, vStride2, 10, 1))
```

It will fail to converge at either learning rates, on both CPU and GPU. I can't figure out what the difference is between the two.

**Comment by frankseide** [comment]
Could you compare the Validation output for both cases?

We did have a bug in the parameter parsing for nested expressions in the past, so it is possible that there are more errors. We have already reimplemented the parameter/NDL parser ("BrainScript"), which will have likely addressed this error, but it has not been fully integrated or documented yet.

For now, the workaround is to avoid nested expressions.

**Comment by Likhit** [comment]
The validation outputs look the same for both, only difference seems to be the naming of conv1_act.act to unnamed66, which I guess is alright and expected.
Attaching both logs for reference, stderr is for the original config, stderr2 is for the new config (with relu moved to the NDL file).
[stderr.txt_train_test.txt](https://github.com/Microsoft/CNTK/files/150437/stderr.txt_train_test.txt)
[stderr2.txt_train_test.txt](https://github.com/Microsoft/CNTK/files/150436/stderr2.txt_train_test.txt)

**Comment by pkranen** [comment]
NDL is deprecated by now. Please try the Python API and the latest bits, thanks.
