### ISSUE TITLE
Ordering problem after convolutional layers

### ISSUE THREAD

**Issue by Vedaevolution** [Microsoft/CNTK#1700]
Dear community,

suppose a have i an 224 * 244 * 3  (w, h, c) input image i feed into a network and do some convolutions.
Furthermore let's suppose i would use padding for those convolutions. The results of those operations would be a: 

    (filter number of last convoution operation, for example 64) * 224 * 224 

tensor.

If i would want to get the filtered values of a concrete position in the image (x,y) from the top left corner, i'd need to do something like this:

    values = output[ : , y : y + 1, x : x + 1]

Is that correct? With that i should get all the results in an 64 * 1 * 1 tensor of all 64 filters set on position (x, y) in the image. 

Than i do a reshape so i get a a 64 elements vector 

    values = cntk.ops.reshape(values, (64,))

and use this vector for further computations in the network. Can i do this or have i made  a mistake here?
Somehow it seems i don't get the filter results for the right position (x, y) doing it that way. I need to get it because i want to make use of the receptive fields of the convolutions. 

Best regards

**Comment by cha-zhang** [comment]
This seems ok to me. What makes you think you don't get the right results? Was your output you get after ReLU?

**Comment by Vedaevolution** [comment]
@cha-zhang Well basically i'm trying to implement something like yolo. 

I defined a network like described in the yolo v2 paper. 

      with default_options(activation=leaky_relu, pad=True):
        net1 = Sequential([
            #Feature Extraction

            Convolution((3, 3), 32, strides=(1, 1), pad=True), MaxPooling((2, 2), strides=(2, 2)),

            Convolution((3, 3), 64, pad=True), MaxPooling((2, 2), strides=(2, 2)),

            Convolution((3, 3), 128, pad=True), Convolution((1, 1), 64, pad=True), Convolution((3, 3), 128, pad=True),
            MaxPooling((2, 2), (2, 2), pad=True),

            Convolution((3, 3), 256, pad=True), Convolution((1, 1), 128, pad=True),
            Convolution((3, 3), 256, pad=True),
            MaxPooling((2, 2), (2, 2), pad=True),

            Convolution((3, 3), 512, pad=True), Convolution((1, 1), 256, pad=True),
            Convolution((3, 3), 512, pad=True), Convolution((1, 1), 256, pad=True),
            Convolution((3, 3), 512, pad=True)

            MaxPooling((2, 2), strides=(2, 2)),

            Convolution((3, 3), 1024, pad=True), Convolution((1, 1), 512, pad=True),
            Convolution((3, 3), 1024, pad=True), Convolution((1, 1), 512, pad=True),
            Convolution((3, 3), 1024, pad=True)

            Convolution((3, 3), 1024, pad=True), Convolution((3, 3), 1024, pad=True),
            Convolution((1, 1), ((n_classes + 5) * n_bounding_boxes), activation=leaky_relu)


which outputs an ((n_classes + 5) * n_bounding_boxes) * 13 * 13 tensor.  That is the tensor i slice above to create a network structure for an error function. 

I'm aware that this is not efficient computationally but for the beginning i'm just interested in making it work.
    
    //n_grid = 13 
    for y in range(n_grid):
    for x in range(n_grid):
            centroid_values = network[:, y:y + 1, x: x + 1]
            centroid_values = cntk.ops.reshape(centroid_values, (centroid_value_number,))

            for i in range(n_bounding_boxes):
                box_index = i * (n_classes + 5)

                #coords

                coords = cntk.ops.slice(centroid_values, 0, box_index, box_index + 2)
                offset = cntk.ops.constant(np.array([x * grid_width, y * grid_width], dtype=np.float32))
                scale = cntk.ops.constant(np.array([grid_width, grid_width], dtype=np.float32))
                coords = cntk.ops.plus(cntk.ops.element_times(cntk.ops.sigmoid(coords), scale), offset)


                #scales

                scales = cntk.ops.slice(centroid_values, 0, box_index + 2, box_index + 4)
                scale = cntk.ops.constant(np.array([grid_width*anchor_box_scales[i].width_scale, grid_width*anchor_box_scales[i].height_scale], dtype=np.float32))

                scales = cntk.ops.element_times(cntk.ops.exp(scales), scale)

                #confs

                confs = cntk.ops.slice(centroid_values, 0, box_index + 4, box_index + 5)
                confs = cntk.ops.sigmoid(confs)


                #classes

                classes = cntk.ops.slice(centroid_values, 0, box_index + 5, box_index + 5 + n_classes)


                #box

                box = cntk.ops.splice(coords, scales, confs, classes)


                box_list.append(box)

    result = cntk.ops.splice(*box_list)

    return result

To this function a pass the network created above to create a new network output which is list of anchor boxes for the image, with box coords, box scales, objectness and class probabiltity. 

The last thing i do is taking the result and using it for:
    
    err = cntk.ops.minus(result, nroi_input)
    sq_err = cntk.ops.element_times(err, err) 
    sc_err = cntk.ops.element_times(sq_err, scale_input)
    mse = cntk.ops.reduce_sum(sc_err)

where i use the nroi_input as reference with the correct rois and probs and so on. Furthermore i use scale_input to scale the diffrent error's like one can read in the yolo paper. 

Sadly this doesn't converge. Even if i set the scale in a way where only objectness is important. To say it again i know that this is by far not the most effiecient way to do it. Nevertheless that's not the point. It should still work. Inefficient or not.

**Comment by Vedaevolution** [comment]
To clarify the matter. To set the nroi_input i use this index computation:
     
    ind = x * 100 + y * 100 * 13 + b * (20 + 5) + pos

where (x,y) are positons in the 13 * 13 grid, b is the number of the bounding box and pos the position of the paramter of a bounding box. 

I'm trying this on the VOC2007 Dataset so i have 20 class confidences and 5 coordinates (x,y,width,height, objectness) for each box. I have 4 anchor boxes for each of the 13 * 13 grid.

**Comment by pkranen** [comment]
Hi Vedaevolution, could you share the entire script somewhere? We're also interested in Yolo v2 and could debug into your script. Thanks!

**Comment by Vedaevolution** [comment]
@pkranen I can surely do this. At first i will clean the code a bit. I changed so much in order to find my mistake that the code doesn't look that well right know. 

I think i will upload the cleaned version with some comments to github in a few hours. 

Thanks!

**Comment by Vedaevolution** [comment]
@pkranen 

As i promised, although it took a little bit longer, i created a repo.

[https://github.com/Vedaevolution/YOLO-V2-CNTK](url)

I tried to comment most of the code. If there are questions feel free to ask.

**Comment by pkranen** [comment]
Thanks, we'll take a look and come back to you.

**Comment by pkranen** [comment]
We have a work in progress implementation of Yolo v2 in the branch pkranen/yolo. I'll close this issue, please try yolo once it is in master.
