### ISSUE TITLE
Cannot use load_model in CNTK 2.0 RC1 with model created in CNTK 2.0 beta

### ISSUE THREAD

**Issue by mawah** [Microsoft/CNTK#1701]
I have just upgraded from CNTK 2.0 beta 15 to CNTK 2.0 RC1 and am updating a Python script that was previously functional. The script uses transfer learning to retrain an existing image classification model: the pretrained model is the [version of AlexNet shared in the CNTK repo](https://www.cntk.ai/Models/AlexNet/AlexNet.model), which the script loads with the `load_model()` function.

CNTK 2.0 RC1 seems unable to load this model file with `load_model()`. I receive the following error: "RuntimeError: Required key 'version' is not found in the dictionary." A full stack trace appears below. How can I load this pretrained model file in CNTK 2.0 RC1?
```
Traceback (most recent call last):
  File "retrain.py", line 114, in <module>
    train_fast_rcnn()
  File "retrain.py", line 76, in train_fast_rcnn
    frcn_output = frcn_predictor(image_input, num_classes)
  File "retrain.py", line 51, in frcn_predictor
    loaded_model = load_model(model_file)
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.p
y", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", lin
e 1095, in load_model
    return Function.load(filename, device)
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.p
y", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Anaconda\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", lin
e 1088, in load
    return cntk_py.Function.load_model(filename, device)
RuntimeError: Required key 'version' is not found in the dictionary.

[CALL STACK]
    > CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::Function::  Deserialize
    - CNTK::Function::  LoadModel
    - PyInit__cntk_py
    - PyInit__cntk_py
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx
    - PyEval_EvalFrameEx
    - PyFunction_SetAnnotations
    - PyObject_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx
    - PyEval_EvalFrameEx
    - PyEval_GetFuncDesc
```

**Comment by pkranen** [comment]
I just tried it and it works for me. Please try from a cntk python environment the following and report the outcome:
```
>>> import cntk
>>> y = cntk.load_model("AlexNet.model")
>>> y
```
It should output this
```
Composite(Combine): Input('features', [#, ], [3 x 224 x 224]), Input('labels', [#, ], [1000]) -> Output('CE', [], []), Output('Err', [], []), Output('OutputNodes.z', [#, ], [1000])
```

**Comment by mawah** [comment]
Same results for me. If it helps, I installed CNTK v2 RC1 for GPU via script-based install on a fresh "DL toolkit for DSVM" GPU VM.

I was able to get around this issue by loading the model in CNTK v2 beta 15 and immediately saving it. The output model was slightly different in size and could be loaded in CNTK v2 RC1.

**Comment by cha-zhang** [comment]
Please try this Caffe-converted AlexNet model instead: 
https://www.cntk.ai/Models/Caffe_Converted/AlexNet_ImageNet.model

**Comment by mawah** [comment]
Hi @cha-zhang,

That model file also works for me -- thank you!
```
cntk.load_model('D:\\AlexNet_ImageNet.model')
Composite(Combine): Input('data', [#], [3 x 227 x 227]) -> Output('prob', [#], [
1000])
```
