### ISSUE TITLE
Can not run App using CNTK-GPU

### ISSUE THREAD

**Issue by yuanweilei** [Microsoft/CNTK#1702]
It fail when run this code:
using (var device = DeviceDescriptor.GPUDevice(0))

error message:
IIS express worker process has stopped working.

**Comment by zhouwangzw** [comment]
@yuanweilei Thank you for reporting the issue. Do you have the same issue when using CPUDevice? If not, does the process have access to GPU?

**Comment by yuanweilei** [comment]
Thank you! 
I can run my program yesterday. I run it on a Azure NC6 VM.

**Comment by zhouwangzw** [comment]
Thanks. I am closing the issue. Please feel free to re-open it if needed.

**Comment by yuanweilei** [comment]
And when I use  
var device = DeviceDescriptor.CPUDevice
it run.

**Comment by yuanweilei** [comment]
@zhouwangzw I am sorry, I can not run it now but I can run my program yesterday.

**Comment by zhouwangzw** [comment]
@yuanweilei Could it be an issue in system when access GPU, since you program ran yesterday but not today? Are you able to run navida-smi.exe to check whether and which GPU is available? In 2.0RC1 (published yesterday), you can also use DeviceDescriptor.AllDevices() to get a list of available devices.

**Comment by yuanweilei** [comment]
@zhouwangzw 
It failed when I use DeviceDescriptor.AllDevices() ; (2.0RC1)

**Comment by zhouwangzw** [comment]
Then the problem could be that your application does not have access to GPU, and the GPU device driver does not support Cuda 8.0?

**Comment by yuanweilei** [comment]
@zhouwangzw Thank you very much! I can run my app now.
Yesterday I missed step 3 as follow: 

1. Buy a NC6 VM machine on Azure.
2. Install GPU dirver.
3. (Important!) Install CNTK-GPU-v2.0
    If you do not do step 3, you can not access GPU device using C# CNTK-GPU nuget 
    (DeviceDescriptor.GPUDevice(0)))
4. Create a C# project and use CNTK-GPU nuge

**Comment by zhouwangzw** [comment]
@yuanweilei You do not need to install CNTK-GPU-V2.0 to run your Eval application. What you need is to install Visual C++ Redistributable Package for Visual Studio 2015, which is a pre-requisite as the Wiki page says. MPI is not required though for running Eval application.

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to re-open it if needed.
