### ISSUE TITLE
How can I use GPU on a Azure VM (like NC6)

### ISSUE THREAD

**Issue by yuanweilei** [Microsoft/CNTK#1705]
I created a WebAPI C# project and use GPU like this.
`var device = DeviceDescriptor.GPUDevice(0)` 
Then I published it to IIS, and I can use the WebAPI in another PC. 

When I restarted the Azure VM, I found that I can not access the WebAPI.
But if I published it again to IIS, I can access it again.

I think the IP of the GPU device was changed when I restarted the Azure VM.
So please tell me can I use another code (not  DeviceDescriptor.GPUDevice(0)) to get GPU device even I restart my Azure VM?

**Comment by yuanweilei** [comment]
If I set the IP of the Azure VM to static, I can run my WebAPI even I restart the Azure VM.
But if possible, I want to know can I use other codes to get the default GPU Device when IP was changed.

**Comment by zhouwangzw** [comment]
@yuanweilei probably you problem is not related to CNTK, but to your Azure WebAPI configuration. Getting default GPU device does not rely on any network connectivity, but just queries the NVIDIA driver on the host to get result. 

What do you mean by "I cannot access the WebAPI"? Do you have a public DNS for the VM hosting the WebAPI? If yes, can you use the dns name to access WebAPI after restarting the VM?

**Comment by yuanweilei** [comment]
@zhouwangzw Thank you.
What do you mean by "I cannot access the WebAPI"? 
⇒ I am sorry, I mean I can access the WebAPI using DNS, but it failed on 
`var device = DeviceDescriptor.GPUDevice(0)`

Now I use set the IP of the Azure VM to static IP and it works even I restart the VM.

**Comment by zhouwangzw** [comment]
This is weird. I do not think that GPUDevice(0) relies on IP address of your host. What is the error message you got?

**Comment by yuanweilei** [comment]
@zhouwangzw 
Thank you. I set the IP of  the Azure VM to static IP but today when I restart the VM and the WebAPI faild.
So as you say, GPUDevice(0) do not rely on IP address.
If I republish the WebAPI, it works again. Some thing (binding?) updated when the WebAPI project is republished/rebuilded I think but I don know what there are.
