### ISSUE TITLE
installing cntk at a different hard drive

### ISSUE THREAD

**Issue by min6434** [Microsoft/CNTK#1706]
I am trying to install cntk at H or D drive.
However cntk doesnt work when the folder is not located at the C:\users\myid\local.
Is it possible to install at the different location?

**Comment by Vedaevolution** [comment]
Basically yes.... the installation script located in the scripts folder should do the work. Maybe you need to set some paths manually but that should happen via script.

**Comment by wolfma61** [comment]
For the binary install you can identify the location for the Anaconda installation by using the AnacondaBasePath parameter, see details [here](https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script). Before that, you can unzip to whatever drive/location you desire.

If you are looking at a developer setup, I would also suggest the script driven installation. Here also are options to pick the Anaconda environment and also the loacation of the local directory (InstallLocation)
more information about dev-install-script-options: https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Devinstall-Script-Option

thx
Wolfgang

**Comment by min6434** [comment]
Thank you very much they indeed have all the information I need.
Thank you very much
