### ISSUE TITLE
Version 2.0 rc1 Unable to load DLL 'Cntk.Core.CSBinding-2.0rc1.dll'

### ISSUE THREAD

**Issue by PeterGriffioen** [Microsoft/CNTK#1708]
Upgrading to version 2.0 rc1 has caused this error to appear when trying to initialise the Device while using the CS eval library. I use Nuget to drop back to my previous version (Beta 12) and everything is found just fine. I try manually copying the above DLL to possible other search locations to no avail and cannot add it to the project as I think it is unmanaged. Here's the full exception text

The type initializer for 'CNTK.UtilsPINVOKE' threw an exception.System.TypeInitializationException: The type initializer for 'CNTK.UtilsPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Cntk.Core.CSBinding-2.0rc1.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at CNTK.UtilsPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Utils(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at CNTK.UtilsPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at CNTK.UtilsPINVOKE.SWIGExceptionHelper..ctor()
   at CNTK.UtilsPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at CNTK.UtilsPINVOKE.DeviceDescriptor_GPUDevice(UInt32 jarg1)
   at CNTK.DeviceDescriptor.GPUDevice(UInt32 deviceId)
   at DeepPredict.DPMainForm.RunModel() 

Any ideas as to how I can get around this problem?

Thanks

**Comment by zhouwangzw** [comment]
@PeterGriffioen There is a name change in DLLs, as described [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Shared-Libraries-Naming-Format). Have you updated your Nuget package to RC1 version? Probably you need a clean build, and remove the "packages" directory in your solution directory? After the clean build, you should be able to find 'Cntk.Core.CSBinding-2.0rc1.dll' and other dlls in the project output directory.

**Comment by PeterGriffioen** [comment]
My code works fine if placed in the CNTK release bin directory with CNTK.exe, so it's just a matter of finding the DLLs. I added c:\local\cntk\cntk to the path and all is well. However when using Procmon.exe to see which DLL are being called I noticed that nvml.dll is called. Maybe this needs to be added to the Wiki on "Shipping CNTK Library with your Windows Application". 

Thanks again for your quick response

**Comment by zhouwangzw** [comment]
Thanks, @PeterGriffioen! I have updated the Wiki to include nvml.dll.

**Comment by shantha-Ekanayake** [comment]
I am getting same error in IIS8.5 windows 2012R2 after deploying the web application to server. I had same issue with VS 2015 when running with IIS express locally, and got it corrected after adding the path fix in the global.asax file as instructed in one of the git hub site. Now I am facing same after deploying same application to IIS in server.

[DllNotFoundException: Unable to load DLL 'CNTKLibraryCSBinding': The specified module could not be found. (Exception from HRESULT: 0x8007007E)]
   CNTK.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_CNTKLib(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate) +0
   CNTK.SWIGExceptionHelper..cctor() +1044

[TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.]
   CNTK.SWIGExceptionHelper..ctor() +0
   CNTK.CNTKLibPINVOKE..cctor() +28

[TypeInitializationException: The type initializer for 'CNTK.CNTKLibPINVOKE' threw an exception.]
   EmISearch.CNTKLibraryManagedExamples1.EvaluationSingleSequenceUsingOneHot(String input) +4234
   EmISearch.home1.buildresults(String input) +761
   EmISearch.home1.Page_Load(Object sender, EventArgs e) +367
   System.Web.UI.Control.LoadRecursive() +71
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3178

Can any one comment why this issue, I have kept the global.asax as it's in VS 2015 while deploying as well.

**Comment by zhouwangzw** [comment]
CNTK requires 64-bit platform, so your IIS should run in 64-bit mode. 
And which CNTK version are you using? Starting from CNTK 2.0RC1, dll names are slightly different than previous versions, as described [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Shared-Libraries-Naming-Format). However, if you use Nuget package and deploy your service vis VS, the dlls should be deployed automatically.

**Comment by mayuanyang** [comment]
I am getting the same problem after i deployed to Azure app, i am using rc2 deploy via Publish from visual studio

**Comment by zhouwangzw** [comment]
Besides 64-bit, the PATH should include the directory hosting native dlls required by CNTK. One way is to add the following code in the Application_Start() method in global.asax:
 ```
  string pathValue = Environment.GetEnvironmentVariable("PATH");
   string domainBaseDir = AppDomain.CurrentDomain.BaseDirectory;
   string cntkPath = domainBaseDir + @"bin\";
   pathValue += ";" + cntkPath;
   Environment.SetEnvironmentVariable("PATH", pathValue);

```
as described in the page https://github.com/Microsoft/CNTK/wiki/Evaluate-a-model-in-an-Azure-WebApi#deploy-through-aspnet

**Comment by tkauf15k** [comment]
hi,
i have the same problem with v2.1.0 with VS2017 and VS2015 update 3. Platform is set to x64. Surprisingly, the example project works, but i cannot figure out a difference... Since the example project works, i think that my environment is set up correclty as well (anaconda3 4.4.0)

Any ideas how i can fix this?

kind regards

**Comment by albertwoo** [comment]
I was using CNTK2.2.0 to evaluate my generated model and faced the same issue when I publish my asp.net application to my remote virtual machine (windows server 2012 and iis8.5). It take me couple of days to solve this.
I used Procmon.exe and identified that the root cause is missing vcruntime140.dll. So I downloaded and installed "Visual C++ Redistributable for Visual Studio 2015", then the issue got fixed finally.

**Comment by fastlater** [comment]
I was having the same problem and I solved the error following @albertwoo  advice from
https://msdn.microsoft.com/en-us/library/ms185328.aspx
Plus, I added all the dll files in the debug folder. I don't know copy dlls was necessary (I did it before find this post) but now it is running.

**Comment by viraptor** [comment]
I'm running into this same issue in VS 2019. (the CSBinding version is current 2.7 though) CNTK is installed
I'm installing CPUOnly CNTK and the CSBinding dll is not found. When trying to include it directly as a reference, the error claims:
```
A reference to '...\Cntk.Core.CSBinding-2.7d.dll' could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component.
```
Since this is happening with Nuget installed package, should I reopen this / open a new bug @zhouwangzw ?
