### ISSUE TITLE
Custom image transform in Python

### ISSUE THREAD

**Issue by ivan-alles** [Microsoft/CNTK#1709]
I'm training a convnet that should be invariant to rotations of the object around the image center. I've done this in torch by creating minibatches with rotated images. I also need scaling and translation, and it boils down to just one function call which makes an affine transform.

I'm looking for a way to do this in CNTK and Python. I could not find a transform for rotations. I could write a whole new reader as described here https://github.com/Microsoft/CNTK/blob/master/Examples/Video/GettingStarted/Python/Conv3D_UCF11.py.  But actually all I need is a new transform, where I could call cv2.warpAffine() on my images. 

Is there a way to create a custom image transform in Python?

**Comment by cha-zhang** [comment]
It's on our list, but we don't have it now. 

Have you looked at: 
https://github.com/Microsoft/FERPlus 
There the input images go through affine warping (rotate, skew, scale, etc.), which might be what you are looking for?

**Comment by ivan-alles** [comment]
Ok, so for now I need to write a custom reader. It's ok too.
