### ISSUE TITLE
Problem in Convolution3D.

### ISSUE THREAD

**Issue by akamotaco** [Microsoft/CNTK#1710]
I try to train multi-channel images on CNTK.
But it doesn't working.
After some test, I found a weird thing in the CNTK layers.

(following results tested on ubuntu 16.04, anaconda based ipython3.6 and CNTK 2.0RC1)

-------------------------------------------------------------------------------------------
In [3]: C.layers.Convolution((1,1,1),1)(C.input((1,1,1)))
Out[3]: Composite(Convolution): Input('Input59', [#], [1 x 1 x 1]) -> Output('Block69_Output_0', [#], [1 x 1 x 1 x 1])

In [4]: C.layers.Convolution((1,1,1),1)(C.input((2,1,1)))
Out[4]: Composite(Convolution): Input('Input98', [#], [2 x 1 x 1]) -> Output('Block108_Output_0', [#], [1 x 2 x 1 x 1])

In [5]: C.layers.Convolution((1,1,1),1)(C.input((2,1,10)))
Out[5]: Composite(Convolution): Input('Input137', [#], [2 x 1 x 10]) -> Output('Block147_Output_0', [#], [1 x 2 x 1 x 10])

In [6]: C.layers.Convolution((1,1,1),1)(C.input((2,2,10)))
Out[6]: Composite(Convolution): Input('Input176', [#], [2 x 2 x 10]) -> Output('Block186_Output_0', [#], [1 x 2 x 18446744073709551614 x 10])

In [7]: C.__version__
Out[7]: '2.0rc1'

-------------------------------------------------------------------------------------------

As you see, it looks like OK on first and third number.
But when I change the second number to 2, the outputs had 18446744073709551614 instead 2.

Is it just my problems?

Thanks.

**Comment by cha-zhang** [comment]
If you want to do convolution over 3D data, try this: 
C.layers.Convolution((2,3,3), 64)(C.input((3,3,3,10))) 
Note the input is 4D where the first dim is channel dim. You will get: 
Composite(Convolution): Input('Input251', [#], [3 x 3 x 3 x 10]) -> Output('Block261_Output_0', [#], [64 x 2 x 1 x 8])
