### ISSUE TITLE
Feature request: lock GPU by per-running-train-instance basis

### ISSUE THREAD

**Issue by Worldexe** [Microsoft/CNTK#1711]
The scenario is: I have machine with multiple GPUs installed. I'd like to run several training tasks in parallel; each of the tasks should be split across all the GPUs.
The reason is: a single task never loads the GPU 100% all the time (because of data transfers/sync between minibatches - idk); so I would like to run both training tasks on all the GPUs.
Right now it is not possible, because if I set deviceId=auto, it uses global (per-system) interprocess lock; so the task I run first lock GPUs, the second task gets CPU-ed.

I think, it would be good to add some configuration setting (like, 'gpuLockTag', for ex.), and use it inside 
`GetDeviceLock(int deviceId)` 
like 
`string name = "CNTK_exclusive_lock_for_GPU_" + to_string(deviceId) + "_" + gpuLockTag;`

This will ensure that mpi-run processes within one configuration will get their unique devices; and another configuration' processes will also auto-distribute the same GPUs for themselves.

What do you think?

**Comment by n17s** [comment]
The behavior you want can be accomplished today with the V2 API using 
[TrySetDefaultDevice]
(https://github.com/Microsoft/CNTK/blob/v2.0/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L239-L256)
or the equivalent `try_set_default_device` in Python.

Unfortunately, we are not adding any new features to Brainscript for the time being. Feel free to reopen if you have more questions.

**Comment by mikhail-barg** [comment]
@n17s 

> Unfortunately, we are not adding any new features to Brainscript for the time being. Feel free to reopen if you have more questions.

Does this mean that Brainscript is not considered to be the primary language for CNTK anymore?
