### ISSUE TITLE
[Enh] MKL DNN integration with CNTK

### ISSUE THREAD

**Issue by e-thereal** [Microsoft/CNTK#1713]
The MKL DNN, intel has introduced a CPU-based library of high performance deep learning primitives similar to cuDNN. Although training using GPUs is often not an issue, many real-world applications require a CPU-only solution. It would be therefore high desirable to benefit from a fast CPU-based implementation for model evaluation and the intel MKL DNN library seems to be a suitable library for that task. Can you please comment if this is an enhancement that will likely be considered for a future release? Thanks!

**Comment by cha-zhang** [comment]
Yes, absolutely. We are going to work on this immediately after v2.0 official release.

**Comment by e-thereal** [comment]
Thanks a lot.
