### ISSUE TITLE
How to release GPU memory in Python?

### ISSUE THREAD

**Issue by akamotaco** [Microsoft/CNTK#1720]
Is it possible to release all resources after computation?
CNTK is working well in my system.
But after I have tried to change several networks, GPU ram was out.
Sometimes 'gc.collect()' was working but not always.

for example
`for i in range(10):
    model  = new_CNTK_model()
    training(model,minibatch)
    del model
    gc.collect()`

Is Python based CTNK supports memory management?

**Comment by n17s** [comment]
In general, 
del model 
and 
gc.collect() 
should reclaim all resources. We have fixed a couple memory leaks since the date of your post. I suggest you try with the latest version, and reopen this if there is still an issue.
