### ISSUE TITLE
FastRcnn reader rois.txt formatting

### ISSUE THREAD

**Issue by awscodu** [Microsoft/CNTK#1721]
Hello. I'm having some difficulty translating ROIs I have acquired to the "dense" format required by the reader. 
For example, I want to translate the ROI with the coordinates 100 600 310 780 (x, y, w, h) into the "dense" format that looks like this...

 0 |rois 0.2185 0.0 0.165 0.29 0.3285 0.025 0.06 0.115 0.3635 0.0 0.21 0.135 0.4835

What calculations are required to accomplish this?

**Comment by awscodu** [comment]
Correct me if I'm wrong but after going through more of the python scripts I believe the fractions are just the (x, y, w, h) / size of the image.

**Comment by JakobMadsenICP** [comment]
If have been looking at this and could not find an easy solution. I have been working with the cntk_helpers.py
And have come up with the following transformations. If you have a better solution pls. post.

```
# all rois need to be scaled + padded to cntk input image size
imgWidth=1080
imgHeight=1920
cntk_padWidth=1000
cntk_padHeight=1000
targetw, targeth, w_offset, h_offset, scale = roiTransformPadScaleParams(imgWidth, imgHeight,cntk_padWidth, cntk_padHeight)

print("The roi from train.roi.txt")
roi=[ 0.6165 ,0.213 ,0.106 ,0.083]
roiInLineFormat=[roi[0],roi[1],roi[2]+roi[0],roi[3]+roi[1]]
print("From rois.txt")
print(repr(roi))
print("In line format:")
print(repr(roiInLineFormat))

print("\n")

result=getAbsoluteROICoordinates(roiInLineFormat,1080,1920,1000,1000)
print("The absolute coordinates")
print(repr(result))
print("\n")


rect = roiTransformPadScale(result, w_offset, h_offset, scale)
boxesStr = getCntkRoiCoordsLine(rect, cntk_padWidth, cntk_padHeight)

print(repr(rect))
print("And back to the ctnk roi format")
print(repr(boxesStr))
```
