### ISSUE TITLE
Is it possible to infer size of the output dimension in a layer?

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#1723]
I am looking towards creating implementation of [Highway network](https://arxiv.org/abs/1505.00387) layer which is essentially a dense layer plus weighted input. The feature is that the output of the layer has the same dimensions as an input. So I'd like it to be automatically inferred, but there's not much info on how the  inference works.

Here's what I'm trying:

```
HighwayLayer {init='glorotUniform', initValueScale=1, initBias=0} = {
	l = LinearLayer{Inferred, init = init, initValueScale = initValueScale, initBias = initBias}
	apply (x) = l(x) + x
}.apply
```

Which results in `PlusArgs[0].PlusArgs[0] Times operation: The outputRank (1) dimensions in left argument's shape [0 x 0] must not be 0.
`

How to do it properly?

**Comment by n17s** [comment]
Unfortunately I don't see how to do this in a generic way in Brainscript. One posibility would be to incorporate this into the previous layer e.g. DenseWithHighway{256} would create a Dense layer of output 256 followed by optional nonlinearity followed by your construction.

By the way, this is possible to do with the Python API.

Feel free to reopen if you have additional questions.
