### ISSUE TITLE
NameError: name 'cross_entropy_with_softmax' is not defined

### ISSUE THREAD

**Issue by arunkumarwa** [Microsoft/CNTK#1725]
Hello

I am trying to get one of the CNTK tutorials (LogisticRegression) working inside a Spyder 2.0 IDE.  Having an issue with (what I think are CNTK) error functions.  Suspect paths / env variables might not be set correctly.  Note that inside a jupyter notebook I am able to run the python code i.e it is able to find the cross_entropy_with_softmax()....

sys.path inside an iPython console looks like this:

Out[2]: 
['',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35\\DLLs',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35\\Lib',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35\\Library\\bin',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35\\Scripts',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35\\Lib\\site-packages',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\python35.zip',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\DLLs',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\lib',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64',
 'c:\\local\\anaconda3-4.1.1-windows-x86_64\\lib\\site-packages\\setuptools-23.0.0-py3.5.egg',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\lib\\site-packages',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\lib\\site-packages\\Sphinx-1.4.1-py3.5.egg',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\lib\\site-packages\\win32',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\lib\\site-packages\\win32\\lib',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\lib\\site-packages\\Pythonwin',
 'C:\\local\\Anaconda3-4.1.1-Windows-x86_64\\envs\\cntk-py35\\Lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\akumar3\\.ipython']

can anyone point out what might be the issue?

**Comment by n17s** [comment]
Have you been able to fix this?

**Comment by arunkumarwa** [comment]
yes...apologies for not closing this.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
