### ISSUE TITLE
from cntk.utils import get_train_eval_criterion, get_train_loss ???

### ISSUE THREAD

**Issue by arunkumarwa** [Microsoft/CNTK#1726]
Hello

does anyone know where the equivalents to these functions from cntk.utils ended up?  I saw a reference that cntk.utils was no longer around and the existing functions have been included in other modules? 

from cntk.utils import get_train_eval_criterion, get_train_loss

**Comment by PatrickBue** [comment]
+1

**Comment by vladT0** [comment]
I have the same issue ! Please help.

**Comment by ebarsoumMS** [comment]
You can use the below attributes from your trainer object:
    trainer.previous_minibatch_loss_average
    trainer.previous_minibatch_evaluation_average

**Comment by PatrickBue** [comment]
thanks, that's working.
