### ISSUE TITLE
Model output performance

### ISSUE THREAD

**Issue by bcbrock** [Microsoft/CNTK#1729]
During the course of evaluating CNTK on X86 and POWER systems, I noticed a great disparity in the performance of the checkpointing operations between training epochs. Looking into the issue, I found that this is caused in my case by the following routine in GPUMatrix.h: 

``` 
friend File& operator<<(File& stream, const GPUMatrix<ElemType>& us) { stream.PutMarker(fileMarkerBeginSection, std::wstring(L"BMAT")); stream << sizeof(ElemType);

        // TODO: This is now ignored on input, so we can should change to an empty string. This might break parsing, and must be tested first
        std::wstring s = std::wstring(L"unnamed");
        int format = us.GetFormat();
        stream << s << format;

        stream << us.m_numRows << us.m_numCols;
        ElemType* pArray = us.CopyToArray();
	for (size_t i = 0; i < us.GetNumElements(); ++i)
                stream << pArray[i];
        
        delete[] pArray;

        stream.PutMarker(fileMarkerEndSection, std::wstring(L"EMAT"));
        return stream;
    }
```

Although output of the model is well-abstracted, it is also extremely inefficient, as each instance of `stream << pArray[i]` eventually becomes a unique instance of the `fwrite()` library call via `fwriteOrDie()`. [It takes 61 million `fwriteOrDie()` calls to output the ResNet152 model for example.]

A quick hack of the routine to handle the entire `pArray` with a single call of `fwriteOrDie()` improves performance of checkpointing ResNet152 by 9X on my X86 box (4s -> 450ms) and 50X on my POWER8 system (13s -> 250ms).

Is there any interest in improving model I/O performance? I realize that for many applications these few seconds are inconsequential; the nature of my tests happened to make it stand out.

**Comment by KeDengMS** [comment]
Thanks for the report @bcbrock. Are you using BrainScript (a.k.a. V1)? This code does look inefficient and could be improved as a combined fwrite. If model saving/loading speed is crucial for you, you may want to try the newer python version of CNTK (a.k.a. V2)that uses protobuf for model serialization. We are currently focused on V2 so this may not be our top priority in bugs. If possible, can you submit a PR to help improving BrainScript? We would greatly appreciate community effort to make CNTK better.

**Comment by bcbrock** [comment]
@KeDengMS Thanks for the response. Yes, I was running a Brainscript example. I will look into the Python approach, and also prepare a PR to address the issue in Brainscript.

**Comment by n17s** [comment]
Closing this for now. Feel free to reopen.
