### ISSUE TITLE
CNTK with KaldiReader compilation error

### ISSUE THREAD

**Issue by vmswork** [Microsoft/CNTK#173]
Hi,

I'm trying to build cntk from source with kaldi integration enabled (--with-kaldi option) and get this error

`Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of 'void Microsoft::MSR::CNTK::GetWriter(Microsoft::MSR::CNTK::IDataWriter<ElemType>**) [with ElemType = float]':
Source/Readers/Kaldi2Reader/DataWriter.cpp:27:22:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:22:14: error: cannot allocate an object of abstract type 'Microsoft::MSR::CNTK::HTKMLFWriter<float>'
     *pwriter = new HTKMLFWriter<ElemType>();
              ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   because the following virtual functions are pure within 'Microsoft::MSR::CNTK::HTKMLFWriter<float>':
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:14:0:
Source/Common/Include/DataWriter.h:65:18: note:         bool Microsoft::MSR::CNTK::IDataWriter<ElemType>::SupportMultiUtterances() const [with ElemType = float]
     virtual bool SupportMultiUtterances() const = 0;
                  ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of 'void Microsoft::MSR::CNTK::GetWriter(Microsoft::MSR::CNTK::IDataWriter<ElemType>**) [with ElemType = double]':
Source/Readers/Kaldi2Reader/DataWriter.cpp:31:22:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:22:14: error: cannot allocate an object of abstract type 'Microsoft::MSR::CNTK::HTKMLFWriter<double>'
     *pwriter = new HTKMLFWriter<ElemType>();
              ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   because the following virtual functions are pure within 'Microsoft::MSR::CNTK::HTKMLFWriter<double>':
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:14:0:
Source/Common/Include/DataWriter.h:65:18: note:         bool Microsoft::MSR::CNTK::IDataWriter<ElemType>::SupportMultiUtterances() const [with ElemType = double]
     virtual bool SupportMultiUtterances() const = 0;
                  ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::CNTK::ConfigParameters; ElemType = double]':
Source/Common/Include/DataWriter.h:135:30:   required from 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::CNTK::ConfigParameters&) [with ElemType = double]'
Source/Readers/Kaldi2Reader/DataWriter.cpp:98:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type 'Microsoft::MSR::CNTK::HTKMLFWriter<double>'
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type 'Microsoft::MSR::CNTK::HTKMLFWriter<double>' has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::ScriptableObjects::IConfigRecord; ElemType = double]':
Source/Common/Include/DataWriter.h:139:30:   required from 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::ScriptableObjects::IConfigRecord&) [with ElemType = double]'
Source/Readers/Kaldi2Reader/DataWriter.cpp:98:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type 'Microsoft::MSR::CNTK::HTKMLFWriter<double>'
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type 'Microsoft::MSR::CNTK::HTKMLFWriter<double>' has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::CNTK::ConfigParameters; ElemType = float]':
Source/Common/Include/DataWriter.h:135:30:   required from 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::CNTK::ConfigParameters&) [with ElemType = float]'
Source/Readers/Kaldi2Reader/DataWriter.cpp:99:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type 'Microsoft::MSR::CNTK::HTKMLFWriter<float>'
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type 'Microsoft::MSR::CNTK::HTKMLFWriter<float>' has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/DataWriter.cpp: In instantiation of 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::InitFromConfig(const ConfigRecordType&) [with ConfigRecordType = Microsoft::MSR::ScriptableObjects::IConfigRecord; ElemType = float]':
Source/Common/Include/DataWriter.h:139:30:   required from 'void Microsoft::MSR::CNTK::DataWriter<ElemType>::Init(const Microsoft::MSR::ScriptableObjects::IConfigRecord&) [with ElemType = float]'
Source/Readers/Kaldi2Reader/DataWriter.cpp:99:16:   required from here
Source/Readers/Kaldi2Reader/DataWriter.cpp:38:18: error: cannot allocate an object of abstract type 'Microsoft::MSR::CNTK::HTKMLFWriter<float>'
     m_dataWriter = new HTKMLFWriter<ElemType>();
                  ^
In file included from Source/Readers/Kaldi2Reader/DataWriter.cpp:15:0:
Source/Readers/Kaldi2Reader/HTKMLFWriter.h:15:7: note:   since type 'Microsoft::MSR::CNTK::HTKMLFWriter<float>' has pure virtual functions
 class HTKMLFWriter : public IDataWriter<ElemType>
       ^
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp: In member function 'virtual bool Microsoft::MSR::CNTK::HTKMLFReader<ElemType>::DataEnd()':
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp:2011:1: error: a template declaration cannot appear at block scope
 template <class ElemType>
 ^
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp:2024:1: error: expected ';' before 'template'
 template <class ElemType>
 ^
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp:2047:5: error: expected '}' at end of input
 } } }
     ^
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp: At global scope:
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp:2047:5: error: expected '}' at end of input
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp:2047:5: error: expected '}' at end of input
Source/Readers/Kaldi2Reader/HTKMLFReader.cpp:2047:5: error: expected '}' at end of input
`
Without that option everithing is fine.
Kaldi is compiled with openfst 1.4.1 with --shared key/

I've tried to donwload cntlk binaries for linux but kaldiReadier was not present lin lib directory.
My OS is Ubuntu 14.04

**Comment by alexeyo26** [comment]
Hello! Please, see #154 We're currently reviewing the fix proposed, but you're free to try  it right away.

Thank you,
Alexey

**Comment by alexeyo26** [comment]
@vmswork, did it help?

Thank you,
Alexey

**Comment by vmswork** [comment]
Hi Alex,

It did help. Thank you very much.
I wanted to write here after checking the whole CNTK training procedure with Kaldi data but got stuck with this
[https://github.com/Microsoft/CNTK/issues/184](url)

**Comment by alexeyo26** [comment]
Great! I will close this issue then (and for sure someone will pick up the next one!)
