### ISSUE TITLE
What is the order of ND reading

### ISSUE THREAD

**Issue by bulatGH** [Microsoft/CNTK#1731]
Let's say I want to read ND object for cntk:

imageShape = size1:size2:size3:1
features = Input {imageShape}

What will be the correct order of writing objects into the file.
Would this be the correct order?
for(int i = 0; i < size1; i++)
 for(int i = 0; i < size2; i++)
   for(int i = 0; i < size3; i++)
      write(image[i, j, k]);

**Comment by n17s** [comment]
I believe the correct order is
or(int k = 0; k < size3; k++)
for(int j = 0; j < size2; j++)
for(int i = 0; i < size1; i++)
write(image[i, j, k]);
