### ISSUE TITLE
A3_ParseAndEvaluateOutput

### ISSUE THREAD

**Issue by HHHNEO** [Microsoft/CNTK#1732]
PARAMETERS: datasetName = hibi
PARAMETERS: cntk_nrRois = 100
Parsing CNTK output for image set: test
Parsing cntk output file, image 0 of 7
Parsing cntk output file, image 1 of 7
Parsing cntk output file, image 2 of 7
Parsing cntk output file, image 3 of 7
Parsing cntk output file, image 4 of 7
Parsing cntk output file, image 5 of 7
Traceback (most recent call last):
  File "C:/Users/xxx/Documents/Work/DeepLearning/CNTK-master/Examples/Image/Detection/FastRCNN/A3_ParseAndEvaluateOutput.py", line 35, in <module>
    saveCompressed = True, skipCheck = True)
  File "C:\Users\xxx\Documents\Work\DeepLearning\CNTK-master\Examples\Image\Detection\FastRCNN\cntk_helpers.py", line 224, in parseCntkOutput
    assert len(values) == cntkNrRois * outputDim, "ERROR: expected dimension of {} but found {}".format(cntkNrRois * outputDim, len(values))
AssertionError: ERROR: expected dimension of 300 but found 0

A1_GenerateInputROIs and A2_RunCntk_py3 completed successfully, but when you run A3_ParseAndEvaluateOutput, you get the error shown above.
Frcn_py.model and proc are generated, please tell me what the problem is.

**Comment by HHHNEO** [comment]
A2_RunCntk and A2_RunCntk_py3 ended normally, but when A3_ParseAndEvaluateOutput was executed, the above error occurred.
Frcn_py.model and proc are generated, please tell me what the problem is.

**Comment by sp00n5** [comment]
I had this problem.
Make sure you have this cntk_helpers.py https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/cntk_helpers.py

**Comment by sp00n5** [comment]
check and make sure ALL your positive and testimages have bboxes.tsv and bboxes.labels.tsv files

**Comment by HHHNEO** [comment]
I confirmed that bboxes.tsv, bboxes.labels.tsv was generated for all photos except negative folders.

**Comment by sp00n5** [comment]
hmm.. i did have this problem also, I thought that was how i fixed it up.  Maybe not.  I will try and remember..

**Comment by HHHNEO** [comment]
I appreciate your help.

**Comment by sp00n5** [comment]
have a look at this file ..\cntk\Examples\Image\Detection\FastRCNN\proc\[yourDataSet]\cntkFiles\test.txt
see where it gets up to and that should tell you which test image it is having a problem with.

Been a while since i looked at this stuff..

**Comment by HHHNEO** [comment]
0	C:/DataSets/hibi/testImages\18.jpg	0
1	C:/DataSets/hibi/testImages\19.jpg	0
2	C:/DataSets/hibi/testImages\t1.jpg	0
3	C:/DataSets/hibi/testImages\t2.jpg	0
4	C:/DataSets/hibi/testImages\t3.jpg	0
5	C:/DataSets/hibi/testImages\t4.jpg	0
6	C:/DataSets/hibi/testImages\t5.jpg	0

**Comment by HHHNEO** [comment]
PARAMETERS.py
Successful execution after changing cntk_num_test_images = 5 to 7

However, we can not recognize from the results below.

PARAMETERS: datasetName = hibi
PARAMETERS: cntk_nrRois = 100
Parsing CNTK output for image set: test
Parsing cntk output file, image 0 of 7
Parsing cntk output file, image 1 of 7
Parsing cntk output file, image 2 of 7
Parsing cntk output file, image 3 of 7
Parsing cntk output file, image 4 of 7
Parsing cntk output file, image 5 of 7
Parsing cntk output file, image 6 of 7
Test.cache ss roidb loaded from C: \ Users \ xxx \ Documents \ Work \ DeepLearning \ CNTK-master \ Examples \ Image \ Detection \ FastRCNN / proc / hibi_100 / cntkFiles / test.cache_selective_search_roidb.pkl
    Processing image 0 of 7 ..
Number of rois before non-maxima surpression: 558
Number of rois after non-maxima surpression: 162
Evaluating detections
AP for hibi = 0.0000
AP for normal = 0.0000
Mean AP = .0000
DONE.
