### ISSUE TITLE
Evaluating detections is 0

### ISSUE THREAD

**Issue by HHHNEO** [Microsoft/CNTK#1734]
PARAMETERS: datasetName = catdog
PARAMETERS: cntk_nrRois = 100
Parsing CNTK output for image set: test
Parsing cntk output file, image 0 of 7
Parsing cntk output file, image 1 of 7
Parsing cntk output file, image 2 of 7
Parsing cntk output file, image 3 of 7
Parsing cntk output file, image 4 of 7
Parsing cntk output file, image 5 of 7
Parsing cntk output file, image 6 of 7
test.cache ss roidb loaded from C:\Users\xxx\Documents\Work\DeepLearning\CNTK-master\Examples\Image\Detection\FastRCNN/proc/catdog_100/cntkFiles/test.cache_selective_search_roidb.pkl
   Processing image 0 of 7..
Number of rois before non-maxima surpression: 558
Number of rois  after non-maxima surpression: 179
Evaluating detections
AP for             cat = 0.0000
AP for             dog = 0.0000
Mean AP = 0.0000
DONE.

Evaluating detections is 0
Please tell us the cause.

**Comment by pkranen** [comment]
It is not that simple. Please try varying the parameters (learning rates, number of epochs, ROI generation parameters, etc.). How many training images do you have? Also, please share parts of the output that shows the statistics ('Finished Epoch ...'). Thanks.

**Comment by cha-zhang** [comment]
I'm closing this issue due to lack of response. Please reopen this issue if needed. Thanks!
