### ISSUE TITLE
Incorrect use of BLAS(ATLAS) in CNTK

### ISSUE THREAD

**Issue by weijianwen** [microsoft/CNTK#1735]
Both CNTK itself and Kaldi reuqire a same cosnsitent BLAS lib setting. However, `Makefile` seems to use unsupported `HAVE_ATLAS` flag which is NOT supported by CNTK yet and may lead to build failures of KaldiReader. Beside that, instructions for building KaidiReader (https://github.com/Microsoft/CNTK/blob/master/Source/Readers/KaldiReaderReadme) uses the vanilla Intel MKL, which may be confused with the  **customized** MKL in CNTK.  OpenBLAS is the BLAS lib officially supported by CNTK and Kaldi, seeming a good choice.

I propose to:

1. Replace `HAVE_ATLAS` with `HAVE_OPENBLAS` in `Makefile`.
2. Repalce MKL with OpenBLAS in KaldiReader doc https://github.com/Microsoft/CNTK/blob/master/Source/Readers/KaldiReaderReadme .

**Comment by n17s** [comment]
Can you send a pull request?
