### ISSUE TITLE
CNTK_205_Artistic_Style_Transfer.ipynb

### ISSUE THREAD

**Issue by edtruji** [Microsoft/CNTK#1737]
I have to remove **not** from if not os.path.exists(path): otherwise the tutorial was giving me an h5py.File(path) error.
```
if not os.path.exists(path):
    # If not there we might be running in CNTK's test infrastructure
    if is_test():
        path = os.path.join(os.environ[envvar],'PreTrainedModels','Vgg16','v0',path)
    else:
```

I'm running the tutorial on my CPU desktop.
3.5.2 |Anaconda 4.3.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
The scikit-learn version is 0.18.1.
The cntk version is 2.0rc1.

**Comment by liqunfu** [comment]
the reason for **not** is to avoid load data from remote path the second time. 
Regarding the error you got, it might be that something was corrupted in vgg16_weights.bin. In this case, delete the file and rerun the notebook section.
