### ISSUE TITLE
Cannot access DSSM article

### ISSUE THREAD

**Issue by lburzawa** [Microsoft/CNTK#1740]
There was an example on how to make a DSSM model under article "Train a DSSM (or convolutional DSSM) Model". But now clicking the article takes me to wiki home page. The example doesn't show up through google search anymore too. Will it be returned to the wiki page?

**Comment by mahilleb-msft** [comment]
Was is this one: https://github.com/Microsoft/CNTK/wiki/How-do-I-Train-Models-in-BrainScript#train-a-dssm-or-a-convolutional-dssm-model ?
It was integrated into a different page...

**Comment by mahilleb-msft** [comment]
Closing here. Please re-open if it isn't the right link.
