### ISSUE TITLE
Strange grid after image reconstruction by autoencoder

### ISSUE THREAD

**Issue by elevir** [Microsoft/CNTK#1741]
Hello!
I want to use autoencoder for pixel-wise classification. I built autoencoder which takes input raw image and output marked image, I expected that the autoencoder will give something like marked image, but result was image with strange grid consisting of nine cells, which contains in cells overlapped parts of input image. Also I tried to use net with one convolutional layer and there was same problem.  Maybe I made something wrong? Can anybody help me?
There is a sample of autoencoder output and configuration file.
![snapshot](https://cloud.githubusercontent.com/assets/8929511/25020320/84e039da-2096-11e7-9ca3-3e1a367c3f38.jpg)
[Autoencoder.txt](https://github.com/Microsoft/CNTK/files/920621/Autoencoder.txt)

**Comment by AllanYiin** [comment]
chackboard effect is every common in convolutional network, u can reference this article `, and u can use unpooling layer to minimize this issue
http://distill.pub/2016/deconv-checkerboard/

**Comment by elevir** [comment]
AllanYiin thanks for answer.
I found problem. There was problem in image representation. I used OpenCV for reading images and there image represented as "(B, G, R) (B, G, R) ...", but in config file I made shape of image as 640x480x3, that means format of image "B B B .... G G G .... R R R .... ".
