### ISSUE TITLE
When run from x86 cmd.exe, the Windows setup do not see the x64 installed programs (C++ runtime and MPI)

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1742]
The `LoadWinProduct` function returns different results when run from under x86 and x64 cmd.exe consoles.
I wish the installation script was able to work when started from any app.

**Comment by wolfma61** [comment]
thank you for reporting 
the dev installer already checks for 64bit, the binary installer will do the same (post rc2)
