### ISSUE TITLE
Error adding cntk dlls to .NET project

### ISSUE THREAD

**Issue by SourabhMakker** [Microsoft/CNTK#1744]
Hi

As per the link https://github.com/Microsoft/CNTK/wiki/EvalDll-Evaluation-on-Windows#shipping-evaldll-library-with-your-windows-application

I am trying to add the dlls to my application but I get the error:
![image](https://cloud.githubusercontent.com/assets/26872587/25041121/624d3a72-212b-11e7-9543-e2f5c84a2aa9.png)

![image](https://cloud.githubusercontent.com/assets/26872587/25041141/8154c548-212b-11e7-9e4c-ed2923ccc23f.png)

**Comment by zhouwangzw** [comment]
@SourabhMakker The target platform should be X64, instead of AnyCPU. And it would be easier to use Nuget package than directly adding reference.

**Comment by SourabhMakker** [comment]
Thanks.
