### ISSUE TITLE
Problem in image cropping using cntk.io.transforms

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#1749]
I'd like to crop input images, which have been normalized with the same size, using a bounding box but I think this kind of function is not provided.
Considering this situation, I tried to crop the images with different widths and heights as follows:
```
        transforms += [
            xforms.crop(crop_type='center', crop_size=128:138)
        ]
```

However, it results in a syntax error.

```
  File "<ipython-input-3-3e0114f22541>", line 15
    xforms.crop(crop_type='center', crop_size=128:138)
                                                 ^
SyntaxError: invalid syntax
```

p.s. I'm using Python API for CNTK 2.0rc1.

**Comment by n17s** [comment]
128:138 is brainscript syntax. In Python you can use a tuple `crop_size=(128,138)`

**Comment by 2wins** [comment]
@n17s after change, I found a different error message

NotImplementedError: Wrong number or type of arguments for overloaded function 'reader_crop'.
  Possible C/C++ prototypes are:
    CNTK::ReaderCrop(wchar_t const *,int,float,float,float,wchar_t const *)
    CNTK::ReaderCrop(wchar_t const *,int,float,float,float)
    CNTK::ReaderCrop(wchar_t const *,int,float,float)
    CNTK::ReaderCrop(wchar_t const *,int,float)
    CNTK::ReaderCrop(wchar_t const *,int)
    CNTK::ReaderCrop(wchar_t const *)
    CNTK::ReaderCrop()

**Comment by liqunfu** [comment]
ReaderCrop API has been changed in v2. The error message was still from old ReaderCorp which is inconsistent with Python Api. Please updated to v2 release.
