### ISSUE TITLE
Inconsistency of input for LSTM

### ISSUE THREAD

**Issue by playgithub** [Microsoft/CNTK#1753]
In the tutorials

1.
CNTK 106: Part A, the features' shape is [sample_count, feature_count, 1], for example:
```
[
 [
  [1], [2], [3], [4], [5]
 ],
 [
  [1], [2], [3], [4], [5]
 ]
]
```
It's 3D

2.
CNTK 206: Part B, the features' shape is [sample_count, feature_count(variable)], for example:
```
[
 [1],
 [2, 3],
 [4, 5, 6]
]
```
It's 2D

Is it inconsistent?

**Comment by liqunfu** [comment]
@playgithub Please give more detail.

**Comment by playgithub** [comment]
Sorry, long time away. I'll post pull request when I'm back.
