### ISSUE TITLE
Creating Custom Model in C# API

### ISSUE THREAD

**Issue by Kakalig** [Microsoft/CNTK#1755]
Hi All, 
I am a newbie in CNTK. Can we create a custom model in C# API? Is it possible to save the model in database? 
Thanks in advance.

**Comment by zhouwangzw** [comment]
The C# API currently supports only model evaluation/inference. For training, creating or saving a model, you need to use Python or C++. 

Thanks,

**Comment by Kakalig** [comment]
Thanks a lot

**Comment by whitmark** [comment]
I was sorry to see model building under C# did not make the cut in the release candidate.   Is there any timeline for this functionality going forward in a future release.

**Comment by larcai** [comment]
I find it ironic that a Microsoft person create C# bindings for Tensorflow and not for CNTK.
https://github.com/migueldeicaza/TensorFlowSharp
Some timeline from MS will be nice.

**Comment by skynode** [comment]
@larcai I was also particularly surprised by this. I expected some kind of deep integration between CNTK and C#/F# from Microsoft.

**Comment by JimSEOW** [comment]
@larcai Microsoft future for AI must be, in addition to Azure cloud, the wide presence (cross platform) of mobile AI is equally critical. 

I see both CNTK for .NET and tensorflowSharp (some challenge right now) to play an important role in that. 

=> With mobile cellular PC : WinOnArm, it would be great to start seeing the performance of CNTK on ARM (Native)

**Comment by JimSEOW** [comment]
@larcai Just saw your [PR ](https://github.com/Microsoft/CNTK/pull/1459). Do you have working example for C# doing what python is doing for those tutorials illustrated through the jupyter notebooks?

**Comment by larcai** [comment]
that was some time ago
I'll see what I can do with the latest v2.0 release and make an new PR

**Comment by cha-zhang** [comment]
We are working on C#/.NET support. Will close this thread for now. Please follow our iteration plan: 
https://github.com/Microsoft/CNTK/wiki/Iteration-Plans 
to track progress.

**Comment by deepakkumar1984** [comment]
Could be a useful project to use for developing model and training them: https://github.com/deepakkumar1984/SiaNet

A c# wrapper on CNTK backend for easy stacking of neural network.
