### ISSUE TITLE
Simple Cntk example error at Function.Evaluate()

### ISSUE THREAD

**Issue by SourabhMakker** [Microsoft/CNTK#1757]
I have trained a model in cntk and created .dnn file.

The training file looks like this:
![image](https://cloud.githubusercontent.com/assets/26872587/25093281/2fa7b90e-23af-11e7-818e-3a62f167b54f.png)

The cntk file looks like this

[lr_bs.cntk.txt.txt](https://github.com/Microsoft/CNTK/files/925898/lr_bs.cntk.txt.txt)

We ran the cntk exe to generate the .dnn file.

We are consuming the .dnn file in the .NET application like 
![image](https://cloud.githubusercontent.com/assets/26872587/25093409/d2f208da-23af-11e7-9d58-e449987743de.png)

The error comes at line 
modelFunc.Evaluate(inputDataMap, outputDataMap, device);

**Comment by zhouwangzw** [comment]
What is the error message? The C# is using double for input data, what is precision in your Brainscript?

**Comment by liqunfu** [comment]
Close this issue until further response from the issue creator becomes available.
