### ISSUE TITLE
Training on multiple machines

### ISSUE THREAD

**Issue by bansungmin** [Microsoft/CNTK#1758]
I am trying to run CNTK on 2 machines with 4 GPUs on each machine. 
When running below command, training is succeeded or failed according to hostfile.

mpiexec -np 2 -hostfile hostfile cntk configFile=globals.config configFile=cntk.config

1) If hostfile contains only 1 machine such as
      hostfile : `machine1 slots=2 ` or 
      hostfile : `machine2 slots=2 `

   , training has been succeeded no matter at which machine the command is executed.
   exp/log file exists at the machine indicated by hostfile.

2) If hostfile contains 2 machines, training has been failed.
      hostfile : 
                      `machine1 slots=1` 
                      `machine2 slots=1`  

   exp/log is not exists at both machines and below message is printed.
   Config files are attached, somebody has any idea what's wrong? 

   Thank you.
   
==================================================================

   CNTK 2.0.beta15.0+ (master fd5786, Mar 30 2017 16:34:15) on GPU-H07-115 at 2017/04/18 08:52:44

   cntk  configFile=conf/globals.config  configFile=conf/cntk.config

   CNTK 2.0.beta15.0+ (master e68b17, Mar 30 2017 15:43:43) on GPU-H07-114 at 2017/04/18 08:53:29

   cntk  configFile=conf/globals.config  configFile=conf/vad_multi_gpu_dataPa.config

   ping [requestnodes (before change)]: 2 nodes pinging each other
   ping [requestnodes (before change)]: 2 nodes pinging each other

==================================================================

**Comment by avader906** [comment]
Can you please try updating to RC1 (you only need to rename old ..\cntk folder and replace it with the new - if you want just to test the solution). Make sure you have the required MSMPI version installed supplied with CNTK (or you can download the newer one). 

Assuming you will launch the training on machine1 and cntk is locally installed in c:\localcntk, please:
- disable firewall on both hosts (if the solution works then you can read msmpi docs and configure firewall appropriately)
- make sure each host can ping another one by using the host name you use to launch the training. if you can not ping, please manually include the both hostnames with ips into the windows host file on both nodes
- make sure that ```c:\localcntk``` or other path you have is mapped and accessible under both machines. if you have deployed CNTK on machine1 in ```"c:\localcntk"``` then under machine2 you need to ***create directory "c:\localcntk" and map it/create remote share pointing to the machine1 via net use command***. 
- launch ```smpd -d 1``` on each machine (the daemon/service used for the distributed communication). make sure the user account you launch smpd can access ```"c:\localcntk"``` and its content
- test mpiexec functionality by launching from **machine1** (it should print hostnames of both machines)
```
mpiexec.exe /hosts 2 localhost 1 machine2 1  hostname
```
- test mpiexec functionality by launching from **machine2**
```
mpiexec.exe /hosts 2 localhost 1 machine1 1  hostname
```
- create a subdirectory for your log files under ```c:\localcntk\..```. In your Brainscript model, please include the line ```stderr = "c:\localcntk\path\to\whereyouwantyour\log"``` pointing to that subdirectory
- launch the distributed training with
```
mpiexec.exe /hosts 2 localhost 2 machine2 2 genv MPICH_CONNECTIVITY_TABLE "1" /genv MPIEXEC_HOSTNAME "machine1" /genv MPICH_NETMASK "xxx.yyy.zzz.qqq 255.255.0.0" \localcntk\cntk\CNTK.exe configfile=../config/yourscript.cntk makeMode=true deviceId=auto
```
where ```xxx.yyy.zzz.qqq``` is machine1 ip address. mpiexec docs can be found here [mpiexec](https://msdn.microsoft.com/en-us/library/cc947675(v=ws.10).aspx)

Upon launch CNTK will display something like (in this example training is done using 3 nodes):
```
ping [requestnodes (before change)]: 3 nodes pinging each other
ping [requestnodes (after change)]: 3 nodes pinging each other
ping [requestnodes (after change)]: 3 nodes pinging each other
ping [requestnodes (after change)]: 3 nodes pinging each other
requestnodes [MPIWrapperMpi]: using 3 out of 3 MPI nodes on multiple hosts (3 requested); we (0) are in (participating)
ping [mpihelper]: 3 nodes pinging each other
requestnodes [MPIWrapperMpi]: using 3 out of 3 MPI nodes on multiple hosts (3 requested); we (2) are in (participating)
requestnodes [MPIWrapperMpi]: using 3 out of 3 MPI nodes on multiple hosts (3 requested); we (1) are in (participating)
ping [mpihelper]: 3 nodes pinging each other
ping [mpihelper]: 3 nodes pinging each other
```
That output indicates that MPI engines communicate without any issues.
One logfile per host will be created in the the directory you had specified with filenames ```log``` and ```log.rank1```. you can check them for any errors / information.

At the end of training a connectivity table will be printed with the following information (again this is example from 3 node setup)
```
MPI Connectivity Table

Rank:Node Listing
------------------------------------------------------------
0: (machine1)
1: (machine2)
2: (machine3)

Connectivity
------------------------------------------------------------
SourceRank:[Indicators for all TargetRanks]
  Where +=Shared Memory, @=Network Direct, S=Socket, .=Not Connected

  0
0:.@@
1:@.@
2:@@.

Summary
------------------------------------------------------------
Total Ranks:          3
Total Connections:    3
  Shared Memory:      0
  Network Direct:     3
  Socket:             0
```
If these instructions do not resolve your issue, please describe the platform you are using (OS, gfx cards) and provide extracts of the log files. We need to establish if this is the problem with MPI setup or with CNTK.

**Comment by bansungmin** [comment]
Thank you for your kind reply. 
Following your guide, CNTK is updated to RC1. (OS is Linux)
After that, when running below commands, the problem still remains. 

`mpiexec -hostfile hostfile cntk configFile=globals.config configFile=cntk.config`


Reffering https://github.com/Microsoft/CNTK/issues/214,
The problem is resolved with below commands. It is an issue about open MPI. 

`mpiexec --mca btl_tcp_if_include bond0 -hostfile hostfile cntk configFile=globals.config configFile=cntk.config`

Thank you

**Comment by liqunfu** [comment]
Close this issue - according to @bansungmin's last comment, the issue was solved with posted mpiexec command.
