### ISSUE TITLE
How to add the ELU activation function in the BrainScript?

### ISSUE THREAD

**Issue by newoneincntk** [Microsoft/CNTK#1759]
The ELU activation function has been added in the beta12, but I dont know how to use it in the  BrainScript.
And I wonder whether the BrainScript will be deprecated in the future?

**Comment by avader906** [comment]
@cha-zhang this seems trivial to add?

**Comment by ebarsoumMS** [comment]
Currently, ELU isn't exposed through Brainscript, however, it should be easy to implement using CNTK expression directly. There is no plan to deprecate BS.

**Comment by avader906** [comment]
@ebarsoumMS i see there is ELU node in API which is exposed to the lib dll and python. what would be the performance penalty of doing it through brainscript vs expose it to BS users?

**Comment by ebarsoumMS** [comment]
It should be very minimum if any. There are a lot of nodes that are implemented this way internally.

**Comment by avader906** [comment]
@ebarsoumMS You need to be very careful with what you advance. Do you have an order of magnitude number? Yes, some of functions are in in CNTK.core.bs and not handled by nodes - but this is not the reason to speculate.

**Comment by ebarsoumMS** [comment]
I am not speculating, ELU can be implemented with a couple of CNTK nodes (i.e. If(x >= 0, x, exp(x) - 1)) this subgraph should be very close in performance with the build-in ELU.

**Comment by newoneincntk** [comment]
@ebarsoumMS @avader906 Thank you very much for your useful discussion. 
To implement the GAN, I have tried PYTHON, and I think compared to BS, PYTHON is more flexible but more complex, not easy to get started and bulid the model. is it possible to implement the GAN in BS?

**Comment by ebarsoumMS** [comment]
It is more flexible and easier to debug, we have 2 simple GAN tutorials in python:
    https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206A_Basic_GAN.ipynb 
    https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206B_DCGAN.ipynb

You can start with the above and modify it to match your need. Sadly, you can't do GAN in Brainscript, there is no random generator, you can't alternate between D and G...etc.

**Comment by newoneincntk** [comment]
@ebarsoumMS Thank you for your immediate reply
