### ISSUE TITLE
integer overflow in expression

### ISSUE THREAD

**Issue by dimon777** [Microsoft/CNTK#176]
Trying to compile on 64 bit linux and getting this error:

```
=-----------------------------------------------------------=
creating /data/src/CNTK/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.o for with build type release
mpic++ -c Source/Readers/LMSequenceReader/SequenceReader.cpp -o /data/src/CNTK/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/opt/gdk/usr/include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/opt/cuda-7.0/include -I/opt/cudnn70.rc/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/usr/include -MD -MP -MF /data/src/CNTK/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.d
Source/Readers/LMSequenceReader/SequenceReader.cpp: In instantiation of âMicrosoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&)::<lambda(int)> [with ElemType = double]â:
Source/Readers/LMSequenceReader/SequenceReader.cpp:1795:18:   required from âstruct Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = double; size_t = long unsigned int]::<lambda(int)>â
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:73:   required from âbool Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = double; size_t = long unsigned int]â
Source/Readers/LMSequenceReader/SequenceReader.cpp:2189:16:   required from here
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:48: error: integer overflow in expression [-Werror=overflow]
                 return (std::rand() * (RAND_MAX+1) + std::rand()) % i; });
                                                ^
Source/Readers/LMSequenceReader/SequenceReader.cpp: In instantiation of âMicrosoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&)::<lambda(int)> [with ElemType = float]â:
Source/Readers/LMSequenceReader/SequenceReader.cpp:1795:18:   required from âstruct Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = float; size_t = long unsigned int]::<lambda(int)>â
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:73:   required from âbool Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = float; size_t = long unsigned int]â
Source/Readers/LMSequenceReader/SequenceReader.cpp:2190:16:   required from here
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:48: error: integer overflow in expression [-Werror=overflow]
=-----------------------------------------------------------=

```

**Comment by frankseide** [comment]
Thanks! I will fix this tomorrow. I wonder why our build config did not catch it. Did you change th makefile?

Sent from Outlook Mobile<https://aka.ms/sdimjr>




On Sun, Feb 28, 2016 at 8:57 PM -0800, "dimon777" <notifications@github.com<mailto:notifications@github.com>> wrote:


Trying to compile on 64 bit linux and getting this error:

=-----------------------------------------------------------=
creating /data/src/CNTK/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.o for with build type release
mpic++ -c Source/Readers/LMSequenceReader/SequenceReader.cpp -o /data/src/CNTK/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/opt/gdk/usr/include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/opt/cuda-7.0/include -I/opt/cudnn70.rc/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -I/usr/include -MD -MP -MF /data/src/CNTK/CNTK/build/release/.build/Source/Readers/LMSequenceReader/SequenceReader.d
Source/Readers/LMSequenceReader/SequenceReader.cpp: In instantiation of ?Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&)::<lambda(int)> [with ElemType = double]?:
Source/Readers/LMSequenceReader/SequenceReader.cpp:1795:18:   required from ?struct Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = double; size_t = long unsigned int]::<lambda(int)>?
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:73:   required from ?bool Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = double; size_t = long unsigned int]?
Source/Readers/LMSequenceReader/SequenceReader.cpp:2189:16:   required from here
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:48: error: integer overflow in expression [-Werror=overflow]
                 return (std::rand() * (RAND_MAX+1) + std::rand()) % i; });
                                                ^
Source/Readers/LMSequenceReader/SequenceReader.cpp: In instantiation of ?Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&)::<lambda(int)> [with ElemType = float]?:
Source/Readers/LMSequenceReader/SequenceReader.cpp:1795:18:   required from ?struct Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = float; size_t = long unsigned int]::<lambda(int)>?
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:73:   required from ?bool Microsoft::MSR::CNTK::BatchSequenceReader<ElemType>::GetMinibatchData(size_t&) [with ElemType = float; size_t = long unsigned int]?
Source/Readers/LMSequenceReader/SequenceReader.cpp:2190:16:   required from here
Source/Readers/LMSequenceReader/SequenceReader.cpp:1796:48: error: integer overflow in expression [-Werror=overflow]
=-----------------------------------------------------------=



-

**Comment by dimon777** [comment]
Yes, I did change Config.make to point to different locations for cuDNN and cuda. Since CNTK doesn't go well with the most recent nvidia libraries. Thanks for looking.

**Comment by dimon777** [comment]
I've done make clean then
../../configure --with-cudnn=/opt/cudnn70.rc --with-cuda=/opt/cuda-7.0

My Config.make now looks proper:
#Configuration file for cntk
BUILDTYPE=release
MATHLIB=acml
ACML_PATH=/opt/acml5.3.1/ifort64_mp
CUDA_PATH=/opt/cuda-7.0
GDK_PATH=/opt/gdk/usr
CUB_PATH=/usr/local/cub-1.4.1
CUDNN_PATH=/opt/cudnn70.rc
OPENCV_PATH=/usr

And yet, the same error during make.

**Comment by frankseide** [comment]
Thanks much for reporting this! This code was meant to extend the number of bits on Windows, where RAND_MAX = 32767. It 2^31 for gcc, so this expression is (1) unnecessary, (2) wrong (overflow), and (3) I one case where random_shuffle() has uncaught out-of-bounds access due to this. Fixed as:

            std::random_device rd;
            std::mt19937 g(rd());
            std::shuffle(m_parser.mSentenceIndex2SentenceInfo.begin(), m_parser.mSentenceIndex2SentenceInfo.end(), g);

This will land with in master soon, pending code review.

**Comment by ianupright** [comment]
Maybe you're building with a different version of gcc?  Because gcc 4.8.5 on my system does not issue this error, but I believe later versions may.

**Comment by frankseide** [comment]
This was the cause of Isse #124, which is now fixed in master. Thanks for reporting it and for helping to track it down!

**Comment by ianupright** [comment]
I can confirm that this builds on 4.9.3 for me just fine.  I didn't originally open this issue, but I believe last week when I tried to build with 4.9.3 it failed on the same error and I had to downgrade to 4.8.5 in order to compile it.  However, now that 4.9.3 compiles just fine, I opened up Issue #188

**Comment by frankseide** [comment]
Thanks!!
