### ISSUE TITLE
How to see the gradient values in DNN training?

### ISSUE THREAD

**Issue by basilabraham123** [Microsoft/CNTK#1760]
I used the following commands in SGD to obtain the gradients. However, i am getting an error as given below.

# Gradient check
         gradientCheck = true
         sigFigs = 6

EXCEPTION occurred: The slice (0+256) is out of range of the source matrix (1).
# Finished at Tue Apr 18 15:41:56 IST 2017 with status 1

How to obtain/dump the gradients in cntk?.

**Comment by n17s** [comment]
From Python you can use [debug_model](https://www.cntk.ai/pythondocs/cntk.debugging.debug.html#module-cntk.debugging.debug) to see both forward values and gradients.
