### ISSUE TITLE
c#.Net NuGet for lower version of .Net Framework

### ISSUE THREAD

**Issue by tcmxx** [Microsoft/CNTK#1761]
Hello, 
I am new to CNTK and I am trying to use the C# eval api in the game engine Unity. However, Unity uses an older version of Mono which is basically .Net 3.5. Just wanna ask is there a way to built a NuGet that support .Net 3.5?
Thank you !

**Comment by zhouwangzw** [comment]
CNTK C# API is built and tested with .NET 4.5. We have not built and tested it with .NET 3.5.

**Comment by tcmxx** [comment]
@zhouwangzw Thanks for your reply! Unity is currently working on upgrading to .NET 4.5 so I will just wait for them! Hope CNTK will have full API for C# in the future~

**Comment by zhouwangzw** [comment]
Great! Hope that you will get the new Unity version soon. 

I am closing the issue. Please feel free to re-open it if needed.

Thanks,
