### ISSUE TITLE
[Python API] Losing Reference to ProgressPrinter when Leaving the Function Scope

### ISSUE THREAD

**Issue by Netzeband** [Microsoft/CNTK#1762]
Hi

I found a strange behavior when working with progress printers for a trainer.

The code looks like this:
```python
# some learner definition before, they seem to be unrelated to this issue

    ProgressPrinter = cntk.logging.ProgressPrinter(tag='Training', num_epochs=Configuration.NumberOfEpochs)
    Trainer = cntk.train.Trainer(Structure['Network'],
                                (Structure['Loss'], Structure['ClassificationError']),
                                Learner,
                                ProgressPrinter) 
``` 

When I call 

```python
Trainer.train_minibatch(...)
``` 
in the same function, everything works. But when I call it from another Function (Trainer object is passed to this function), I receive the following SWIG error:

```
AttributeError: 'method-wrapper' object has no attribute 'on_training_update_end'
Traceback (most recent call last):
  File "train.py", line 67, in <module>
    main()
  File "train.py", line 63, in main
    Model.train(Configuration, DataReader, IsRestart = Arguments.restart)
  File "CModel.py", line 67, in train
    self._Network.trainIteration(Trainer, Data, Iteration)
  File "CNetwork.py", line 80, in trainIteration
    self._trainInteration(Trainer, self._Structure, Data, IterationNumber)
  File "CAlexNet.py", line 167, in _trainInteration
    Trainer.train_minibatch({Structure['Features']: Data[0], Structure['Labels'] : Data[1]})
  File "trainer.py", line 170, in train_minibatch
    device)
  File "cntk_py.py", line 2251, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: SWIG director method error.
```

When I store the `ProgressPrinter` Object to a global variable instead of a local one, it works also from another function. Thus I think the instance of `ProgressPrinter` is deleted when leaving the scope of the function which creates the `Trainer` object. Even if the object is passed to the trainer and the instance should be hold by it.

Maybe the trainer constructor call is directly passed to the constructor inside the C/C++ API, thus python does not notice that the reference of `ProgressPrinter` is hold by the trainer. Thus it thinks the object is not needed anymore and deletes it's memory. Just a guess.

Best regars

**Comment by Netzeband** [comment]
Some more information about my version:
```
Build info: 

		Built time: Apr  3 2017 07:05:03
		Last modified date: Mon Apr  3 07:04:17 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: yes
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: /usr/local/cuda-8.0
		CUB_PATH: /usr/local/cub-1.4.1
		CUDNN_PATH: /usr/local/cudnn-5.1
		Build Branch: HEAD
		Build SHA1: 7661e81777360d3222a26dcb969973ce1d4c513f
		Built by Source/CNTK/buildinfo.h$$0 on 6d89486cb788
		Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux
		MPI distribution: Open MPI
		MPI version: 1.10.3
```

It is V 2.0 Release Candidate 1 of CNTK for Ubuntu 14.04.

**Comment by raaaar** [comment]
This has been fixed by adding` __disown()__` to the [ProgressPrinter init() method](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/logging/progress_print.py#L98). Thanks for reporting!
