### ISSUE TITLE
Testing single image in Object Detection example using Fast-R-CNN 

### ISSUE THREAD

**Issue by DHOFM** [Microsoft/CNTK#1765]
I have sucessfully trained the Pascal Voc example. How could i evaluate new images for example a single image with 2 cars, where both cars are recognized like the car test images from the pascal data set during test.  Would this be the correct way:
1. Run the ROI Generation (A1_GenerateInputROI)
2. Run a Script like A2_RunCNTK with a modified Brainscript for one file ?

Is there a more comfortable way (like the C# Client ) ?
Kind regards,
Dirk

**Comment by pkranen** [comment]
That would be one way to do it, but I'd suggest to load the model once and then push single images through. You can see how it is done for Fast R-CNN in [this tutorial](https://github.com/Microsoft/CNTK/blob/nadavbar/fastrcnn_eval_python_notebook/Examples/Image/Detection/FastRCNN/CNTK_FastRCNN_Eval.ipynb). The transfer learning example has also a concise example of ho to evaluate a single image: [https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py#L140](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py#L140).

**Comment by mrnameless123** [comment]
@pkranen  I don't see anything on the link you provided. can you please update the link?

**Comment by DHOFM** [comment]
@pkranen: Thanks a lot - i found the first tutorial also but not the transferlearning Example, which was new. What i have noticed is, that the grocery tutorial works as described with the pretrained model but with the self trained from your tutorial which i ran on a DSVM (NC6 / K80) some 2 objects are not found. I guess i is because of the default iterations ? Would it get more accurate with more learning time ???

@mrnameless123: The link worked formerly but here you find the descriped tutorial: https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/CNTK_FastRCNN_Eval.ipynb

This code is a little different to the one i downloaded - anyway to get it work i had to change the z node indexer 'z' to 'z_output' 
Hope this will help

Kind regards,
Dirk
