### ISSUE TITLE
Example of SetDropoutRate using the CNTK C++ library v. 2.0?

### ISSUE THREAD

**Issue by OleStauning** [Microsoft/CNTK#1766]
It would be great if someone could provide an example of how to change the dropout rate of a node when using the API in C++. Unfortunately the method does not seem to be public in the CNTKLibrary.h / libcntklibrary-2.0.so files. Why is that? - I get all sorts of problems if I try to include and link with other files.

**Comment by raaaar** [comment]
You can use [SetAttribute](https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L3314) to change the dropout rate. Here's an [example](https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/V2LibraryTests/FunctionTests.cpp#L1042).
