### ISSUE TITLE
Fixing "CUDA failure 2:Out of memory..." issue without rebooting the computer. 

### ISSUE THREAD

**Issue by min6434** [Microsoft/CNTK#1769]
I tried to increase the size of the convolution kernel and the cntk showed cuda failure error.
After I resized the kernel size, the result still shows out of memory error. 
Also nvidia-smi shows no memery usage.
How do I fix this problem?

![image](https://cloud.githubusercontent.com/assets/25948850/25217203/f52f0b40-25e0-11e7-93ea-4fd695c05b4b.png)

CUDA failure 2: out of memory ; GPU=0 ; hostname=MSI ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
Traceback (most recent call last):
  File "D:\Source\Repos\CNTK_sources\CNTK_Breast\CNNbreast\CNNbreast\CNNbreast.py", line 38, in <module>
    model_func=create_basic_model_with_batch_normalization)
  File "D:\Source\Repos\CNTK_sources\CNTK_Breast\CNNbreast\CNNbreast\CNNFunctions.py", line 213, in train_and_evaluate
    trainer.train_minibatch(data)                                   # update model with it
  File "H:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\train\trainer.py", line 167, in train_minibatch
    arguments, device)
  File "H:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 2248, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: CUDA failure 2: out of memory ; GPU=0 ; hostname=MSI ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)

**Comment by avader906** [comment]
You can find some solutions here [stackoverflow - resetting GPU after cuda error](http://stackoverflow.com/questions/10871412/resetting-gpu-and-driver-after-cuda-error) - ```To reset the graphics stack in Windows, press Win+Ctrl+Shift+B.```

Generally try to google for the solution first - this is not CNTK specific, even though resetting GPUs via CUDA where supported could be a nice CNTK feature 
[Manually resetting GFX drivers in Windows](https://superuser.com/questions/178692/how-does-one-manually-restart-graphics-drivers)
[Resetting GPU without reboot](https://devtalk.nvidia.com/default/topic/417728/resetting-gpu-without-reboot-/)

**Comment by min6434** [comment]
I tried to find the answer but maybe my keywords were wrong. Sorry for the dumb question and thank you very much for the nice answer.

**Comment by jakrivan** [comment]
Is there any other reasone, except for low GPU memory or low available physical RAM (or small continuous block), for this error to occur?
We are starting to see this recently despite having planty of free RAM and low GPU memory utilization.
Any ideas how to rootcause this?

**Comment by evo11x** [comment]
I have the same problem with RTX 3060 12GB if the input data is larger than 512, and with RTX 2060 6GB I don't get this error
