### ISSUE TITLE
How to save shared model in Python?

### ISSUE THREAD

**Issue by akamotaco** [Microsoft/CNTK#1770]
In CNTK, a model can be saved/load by 'model.save(load)_model' function.

`model.save_model('filename')
model = C.load_model('filename')`

But it does not working on shared clone model. (python CNTK rc1)

`temp1 = Dense(2)(input(1))
temp2 = temp1.clone(method='share')
temp3 = C.splice(temp1,temp2,axis=0)

temp1.save_model('temp1.model')

\# try 1
\# temp1.load_model('temp1.model') # not working

\# try 2
\# temp1 = C.load_model('temp1.modle')
\# temp3 = C.splice(temp1,temp2,axis=0) # duplicated name error

temp3.eval({temp1.arguments[0]:np.array([1.0]).reshape(1,1),
                        temp2.arguments[0]:np.array([1.0]).reshape(1,1)})`

How can I save/load these shared model?
(Specially, in this case we can load the model by re-cloning from loaded model.
But I want to know general purpose method such as a case of an extended model based on a shared model.)

**Comment by liqunfu** [comment]
Use save() call to save the model. When loading a model, if you see message like "Cannot load a model that is neither a file nor a byte buffer." it may be related to this fix: https://github.com/Microsoft/CNTK/commit/4c15653eb577dc4fed92bfdb28faa3466916de08?diff=split
