### ISSUE TITLE
[C++ Eval API] Error when loading configuration: unmatched bracket found in parameters

### ISSUE THREAD

**Issue by Netzeband** [Microsoft/CNTK#1775]
Hi

I'm working on Ubuntu with the precompiled CNTK 2.0rc1 library.

The following simple application does produce an error when loading configuration files with the EvalDLL Interface:

```cpp
#include <iostream>
#include <Eval.h>

using namespace Microsoft::MSR;

int main()
{
  //auto Function = CNTK::Function::LoadModel(L"Model.dnn");
  // we use a model with float numbers
  CNTK::IEvaluateModel<float> *pModel;

  std::cout << "Create Model-Object..." << std::endl;
  CNTK::GetEvalF(&pModel);

  std::cout << "Load Model..." << std::endl;
  std::string ModelFile = "/home/robot/cntk/Examples/Image/GettingStarted/Output/Models/01_OneHidden";
  std::string NetworkDescription;
  NetworkDescription += "modelPath=\"" + ModelFile + "\"";
  std::cout << NetworkDescription << std::endl;
  pModel->CreateNetwork(NetworkDescription);

  std::cout << "Destroy Model-Object..." << std::endl;
  pModel->Destroy();

  std::cout << "Good Bye..." << std::endl;
  return 0;
}
```

The model file exists and basically this is exactly the same situation like explained here: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CPPEvalClient/CPPEvalClient.cpp#L77
(Same model file and same network description string)

The error output is:
```
 Create Model-Object...
Load Model...
modelPath="/home/robot/projects/deepdriving/thesis/cntk/Examples/Image/GettingStarted/Output/Models/01_OneHidden"
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
  what():  unmatched bracket found in parameters
Aborted (core dumped)
```

Is the eval-API still functional with the current version?

**Comment by Netzeband** [comment]
One additional note:
If I compile the CPPEvalClient.cpp example and run it, I receive the same error.

Maybe some settings are missing in my Makfile? For Linux there is no makefile provided for the samples 
(together with the precompiled library version).

**Comment by zhouwangzw** [comment]
Which GCC version are you using? The pre-compiled library is using GCC 4.8, as described here https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux

**Comment by Netzeband** [comment]
I'm using Gcc 5.4.0. Do you think this happens due to an incompability of the compilers?

**Comment by zhouwangzw** [comment]
Yes, it is an issue. Docker Containers (https://github.com/Microsoft/CNTK/wiki/CNTK-Docker-Containers) could be an option if you do not want to change compiler on your host.

**Comment by Netzeband** [comment]
I see :(
I want to integrate CNTK into a bigger project with a complex build system. Thus changing the compiler is not an option.
Docker Containers are not option due to performance and missing GPU support.
So I think compiling the library directly on my system seems to be the only solution... 

Anyway thanks for your answer.

**Comment by zhouwangzw** [comment]
Sure, building the library from source is certainly feasible. 
btw, Docker does support Nvidia GPU, and performance should not be a problem based on our experience.

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to re-open it if needed.

**Comment by Netzeband** [comment]
Thanks for your suggestions. I will try to compile the library.
I really did not know, that docker can access the host GPU, goot to know.
