### ISSUE TITLE
Clarifications about (C-)DSSM model input

### ISSUE THREAD

**Issue by jplu** [Microsoft/CNTK#1776]
Hi,

I'm struggling to well understand the [(C-)DSSM](https://github.com/Microsoft/CNTK/wiki/How-do-I-Train-Models-in-BrainScript#train-a-dssm-or-a-convolutional-dssm-model) explanations about the input data. It is difficult to well understand to what correspond the sample. Here what I have understood.

Let's imagine we want to model the following pair query-document:

```
CNTK-Microsoft Cognitive Toolkit
```

This pair gives me the following word hash vocabulary vector:

```
[#cn, cnt, tk#, #mi, mic, icr, cro, rof, oft, ft#, #co, cog, ogn, gni, nit, iti, tiv, ive, ve#, #to, too, ool, olk, lki, kit, it#]
```

With that, we can create the following input for a DSSM model:

```
|L 1 |Q 0:1 1:1 2:1 |D 3:1 4:1 5:1 6:1 7:1 8:1 9:1 10:1 11:1 12:1 13:1 14:1 15:1 16:1 17:1 18:1 19:1 20:1 21:1 22:1 23:1 24:1 25:1
```

But for a C-DSSM we have to create one vector per word and then concatenate them. Is this logic handled by the network definition? If yes, I suppose that the input is the same does not matter if we do a C-DSSM or just DSSM network, right?

If what I said is ok, it is not clear in the "tutorial" how I can modify my input in order to use another feature vector with the word hash one. For example, let's assume I have a vector that represents the topics of my search query and my document:

```
[topic1, topic2, topic3, topic4, topic5]
```

A solution I can see is to concat the two vectors in order to get:

```
[#cn, cnt, tk#, #mi, mic, icr, cro, rof, oft, ft#, #co, cog, ogn, gni, nit, iti, tiv, ive, ve#, #to, too, ool, olk, lki, kit, it#, topic1, topic2, topic3, topic4, topic5]
```

And the input becomes:

```
|L 1 |Q 0:1 1:1 2:1 26:1 |D 3:1 4:1 5:1 6:1 7:1 8:1 9:1 10:1 11:1 12:1 13:1 14:1 15:1 16:1 17:1 18:1 19:1 20:1 21:1 22:1 23:1 24:1 25:1 26:1
```

Is it a good idea? If not how can I proceed? If yes it might not work in case of a C-DSSM model as it uses concatenation of words, so how should I represent my input in this case?

Thanks in advance for the help you can provide me.

**Comment by jplu** [comment]
Hello,

Any plan to improve the tutorial to make it clearer about what I raised in my previous post?

thanks!

**Comment by jplu** [comment]
Any update ?

**Comment by jplu** [comment]
Still nobody on this? :(

**Comment by n17s** [comment]
For the CDSSM case, you just create two inputs. One with the topics and the original one. You can then give the topics to a dense layer and the original one to the convolutional layer. Then you can splice the outputs of these together. 

The above approach might also work for the DSSM case. I haven't tried it but your proposal is also  OK for the DSSM case. The difference is whether you think interactions between topics and trigrams matter (that depends on the domain and the amount of data you have, so it's hard to say).

**Comment by jplu** [comment]
Thanks for your answer @n17s!!

So here what I understand from your suggestion:

* Create two different inputs: one with the trigrams, and another one with the topics
* Make two different networks one DSSM with the trigrams and one CDSSM with the topics
* merge the output of the two networks

Am I well understanding what you suggest?

**Comment by jplu** [comment]
More precisely I'm trying to take inspiration of the model proposed here https://arxiv.org/pdf/1504.07678.pdf

**Comment by jplu** [comment]
Ok got it to work as expected. Thanks for your help :)
