### ISSUE TITLE
How to use the BOOST_AUTO_TEST_* function?

### ISSUE THREAD

**Issue by xhzhao** [Microsoft/CNTK#178]
I have write a new convolution routine optimized for intel CPU, and need to verify my code.
I found there are many test functions in ConvolutionEngineTest.cpp, such us:
![image](https://cloud.githubusercontent.com/assets/17486215/13388429/c73b6464-defa-11e5-96ab-c440ce028839.png)

Can i use this function to verify my new code with a little modification?
How to use this function? (ConvolutionEngineTest.cpp is not included by the make file.)
There is no instruction about this in the CNTK book.

**Comment by Alexey-Kamenev** [comment]
Hello,
We currently run unit test only as a part of Windows build. You can, of course, use Boost unit test framework in Linux, it's just we haven't enabled it yet. For your scenario, the best way to test that would be to compare output of your implementation with some baseline, like cuDNN. See `BatchNormalizationForwardInferenceCpu` test for the example of such approach.
