### ISSUE TITLE
Optimize multi-gpu training

### ISSUE THREAD

**Issue by achhibbar** [Microsoft/CNTK#1780]
I am using ResNet50 to classify images. I have made some minor modifications to the brainscript examples provided, but the SGD parameters remain the same; DataParallelSGD. I am definitely seeing training time reduce when I compare 4 GPUs to just 1 GPU, but the time hasn't come down at the level I was expecting.

What parameters do you recommend altering to make better use of the additional GPUs? I have seen learningRatesPerMB mentioned as well as automatic mini batch scaling.

Thanks,
Ash

**Comment by avader906** [comment]
are all GPUs on one node/machine? what is the memory load vs minibatch size and GPU load look like?

**Comment by achhibbar** [comment]
The GPU's are all on one machine/node and the configuration is x16, x8, x8, x8.
I have mini batch size set to 64, which is the highest I can go given the network type and number of images I am training with. Any higher and I start to get out of memory errors. Each GPU has 8GB of memory.

Can you provide any tips on monitoring the GPUs to see if they are being used optimally?

**Comment by avader906** [comment]
@achhibbar on linux or windows? SSD / raid as disk system?

The recent (feb17) benchmarking for multiple GPUs is [here (paper)](https://arxiv.org/abs/1608.07249v6) and [here (benchmarks)](http://dlbench.comp.hkbu.edu.hk/). You can see if you get the same level of performance vs batch size vs number of GPUs and also check their logs and configurations (they have resnet-50). Please use version-7 of the results as it has multiple GPU setup data. It does not look like resnet is particularly scalable model wise - but there are lots of things in CNTK you can try - including different parallel processing algorithms etc.

**Comment by achhibbar** [comment]
Seems like the issue mainly had to do with mini batch size.
