### ISSUE TITLE
Broken link on Wiki

### ISSUE THREAD

**Issue by mathias-brandewinder** [Microsoft/CNTK#1781]
In the following page:
https://github.com/Microsoft/CNTK/wiki/BrainScript-Network-Builder
The links to BrainScript Basic Concepts are broken. Instead of pointing to
https://github.com/Microsoft/CNTK/wiki/BrainScript-Basic-Concepts 
they incorrectly point to BS-Basic-Concepts
... which redirects to the main index.

**Comment by mahilleb-msft** [comment]
Thanks @mathias-brandewinder , I've hopefully addressed all these instances.

Best, Mark
