### ISSUE TITLE
Did anyone write a CNTK K-means clustering algorithm?

### ISSUE THREAD

**Issue by PFSWcas** [Microsoft/CNTK#1782]
I see a TensorFlow K-means clustering algorithm in [https://esciencegroup.com/2016/01/05/an-encounter-with-googles-tensorflow/](url). The K-means process with Tensorflow is clear. However when I try to write a 
 CNTK K-means clustering algorithm, I find it is a little difficult. Did anyone write a CNTK K-means clustering algorithm and give me some hints?

**Comment by avader906** [comment]
@PFSWcas what is the dimensionality of your inputs? One way to use CNTK would be to train autoencoder (or stacked autoencoder) to reduce the dimensionality of your inputs and then use you similarity metric on the resulting vector (output of autoencoder) and followed by your favorite clustering algorithm outside of CNTK (for instance in Python).

**Comment by liqunfu** [comment]
Close. @PFSWcas may re-open if there are further update.
