### ISSUE TITLE
Possible bug in MaxPooling layer on GPU?

### ISSUE THREAD

**Issue by arniwesth** [Microsoft/CNTK#1785]
Hello,

This model:

def create_model(h):
        h = MaxPooling((2,), strides=1, pad=True)(h)
        last_layer = Dense(1, activation=None)
        return last_layer(h)

runs as expected on CPU. However, switching to GPU I get the following error message:

Traceback (most recent call last):

  File "<ipython-input-3-f722a2bdfaa7>", line 63, in <module>
    trainer.train_minibatch({feature : train_features, label : train_labels})

  File "C:\Anaconda\lib\site-packages\cntk\train\trainer.py", line 171, in train_minibatch
    device)

  File "C:\Anaconda\lib\site-packages\cntk\cntk_py.py", line 2327, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)

RuntimeError: cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=CNTK ; expr=cudnnSetTensorNdDescriptor(m_tensor, dataType, (int)dims.size(), dims.data(), strides.data())

[CALL STACK]
    > Microsoft::MSR::CNTK::TensorView<float>::~TensorView<float>  
    - Microsoft::MSR::CNTK::GPUDataTransferer::  WaitForCopyCPUToGPUAsync
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::ConvolutionEngine<float>::  Create
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen

I have verified that e.g a simple Dense layer runs just fine on the GPU so the culprit seems to be the MaxPooling layer - but maybe there is something I'm not getting. FYI I ran this on an Azure NC6 Standard VM (EDIT: Using the "Deep Learning toolkit for Data Science VM").

**Comment by arniwesth** [comment]
UPDATE; 
I tried installing Anaconda3 4.3.1 and used the 3.6 wheel. I also checked that cuDNN is v5.1 for CUDA 8.0. 
I am however still getting the same error,

**Comment by cha-zhang** [comment]
It's very rare to see people using maxpooling with stride 1. This issue is caused by a bug in cuDNN not handling asymmetric padding correctly when lower pad is less than upper pad. 

Are you sure you want max pooling with stride 1?

**Comment by arniwesth** [comment]
I tried different combinations of stride size, kernel size and pad=True/False. But in each case I still get the error above. I suspect this might be caused by using 1-rank tensors as input to the MaxPooling layer. I don't think I have seen a single example of this anywhere.

To answer your question: I'm experimenting with implementing a simple "Maxout" layer [(Goodfellow et al.)](https://arxiv.org/abs/1302.4389) and there seem to be some confusion about how this should/could be done. Arguably stride should be >1, but I have some cases where stride=1 empirically gives better results.

**Comment by cha-zhang** [comment]
Are you doing it on 1D data? We are fixing a bug that 1D convolution doesn't work for cuDNN, and it might be related.

**Comment by arniwesth** [comment]
Yes, it is 1D data,

**Comment by arniwesth** [comment]
Hello,

It looks like there still are problems with MaxPooling in RC3:

System: Server 2012 R2 with NVIDIA GRID K520

Python script:
`v = np.array([1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4], dtype="float32").reshape(4,4)
x = C.input_variable(v.shape)
C.pooling(x, C.MAX_POOLING, (2,2)).eval({x: [v]})`

Execute on CPU:
array([[[ 2.,  3.,  4.],
        [ 2.,  3.,  4.],
        [ 2.,  3.,  4.]]], dtype=float32)

Execute on GPU:
Traceback (most recent call last):

  File "<ipython-input-3-075dc83012be>", line 3, in <module>
    C.pooling(x, C.MAX_POOLING, (2,2)).eval({x: [v]})

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 626, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 760, in forward
    keep_for_backward)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 1569, in _forward
    return _cntk_py.Function__forward(self, *args)

RuntimeError: cuDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=WIN-IFNGB6K8UMB ; expr=cudnnPoolingForward(*m_cudnn, *(m_pool), &C::One, m_inT, ptr(in), &C::Zero, m_outT, ptr(out))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2 (x2)
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::Function::  Forward
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyFunction_FastCallDict
    - PyEval_EvalFrameDefault (x2)
    - PyEval_GetFuncDesc (x2)

**Comment by arniwesth** [comment]
Please note that the error does not seem to be caused by setting strides = 1. The following script will cause the same error as reported above:

```
v = np.array([1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4], dtype="float32").reshape(4,4)
x = C.input_variable(v.shape)
C.pooling(x, C.MAX_POOLING, (2,2), strides=(2,2)).eval({x: [v]})
```

**Comment by cha-zhang** [comment]
On GPU, cuDNN has a more rigorous check on the size of matrices. In your case, the engine considers the size of input and pooling kernel incompatible because it assumes input should have a depth dimension. The follow code works: 
```
v = np.array([1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4], dtype="float32").reshape(1,4,4)
x = C.input_variable(v.shape)
C.pooling(x, C.MAX_POOLING, (2,2)).eval({x: [v]})
```
We could introduce a reduction_rank parameter for pooling (as done in convolution) in the future.

**Comment by arniwesth** [comment]
Thanks for clarifying this. It would be a good idea to include a reduction_rank parameter for pooling to make it similar to convolution.
