### ISSUE TITLE
trained cntk model can be shared by python and brainscript?

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#1786]
brainscript generates model.nnet for each epoch training. I'm wondering this model can be used for inference or training in python interface? Or do I need to convert model format?

**Comment by Ark-kun** [comment]
A V1 model should load fine in V2-aware readers (like Python's one). Not sure about the checkpoints. Just try it.

**Comment by liqunfu** [comment]
close as there is no remaining issues.
