### ISSUE TITLE
How to control memory usage in python? 

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1789]
In python, I set randomization_window_in_samples with different values. But the memory usage is still very high. Is there a efficient way to reduce the RAM usage? 
BTW, CNTK seems do well in reducing GPU-memory utilization.
Thanks!

**Comment by cha-zhang** [comment]
Does your network has convolution with large kernel?

**Comment by cha-zhang** [comment]
Closing this issue for lack of response. Please open a new issue if needed.
