### ISSUE TITLE
Please add MPI data parallel example

### ISSUE THREAD

**Issue by dimon777** [Microsoft/CNTK#179]
Please add MPI data parallel example which showcases CNTK on the algorithms which use data parallelism for GPUs across different nodes. My understanding Multigpu.cntk uses multiple GPUs on the same node. Thanks for a nice toolkit.

**Comment by Alexey-Kamenev** [comment]
CNTK uses MPI for multi-GPU training so it does not really care about intra-node vs cross-node. Try something like this: `mpiexec -machinefile hosts.txt cntk configFile=../Config/Multigpu.cntk`
