### ISSUE TITLE
Install CNTK binary on Windows without internet connection

### ISSUE THREAD

**Issue by ebaas** [Microsoft/CNTK#1792]
Is there a CNTK binary package that doesn't require an internet connection? In some situations, the server to which to install CNTK don't have internet connections for security reason.

**Comment by mahilleb-msft** [comment]
We do not provide separate packages for offline installation; in the installer an Anaconda environment is created, which requires an Internet connection.
You can do this manually, by installing the Python package into an existing Anaconda root environment, cf. 
https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Python.

Hope this helps, Mark

**Comment by ebaas** [comment]
Okay, thanks.
