### ISSUE TITLE
cannot open input file 'Cntk.Deserializers.HTK-2.0rc2.lib'

### ISSUE THREAD

**Issue by PFSWcas** [Microsoft/CNTK#1794]
The last version of CNTK in my PC is 2.0beta12. Today, I update the repos through 'git pull'. Then I built CNTK. But an error exist:

Error	LNK1181	cannot open input file 'Cntk.Deserializers.HTK-2.0rc2.lib'	ReaderTests	C:\repos\cntk\Tests\UnitTests\ReaderTests\LINK	1	

Does anybody know how I can fix this?

**Comment by liqunfu** [comment]
@PFSWcas  Cntk.Deserializers.HTK-2.0rc2.lib is referenced by the ReaderTests. Please check if Cntk.Deserializers.HTK-2.0rc2.lib is build successfully, otherwise there should be other error proceeding this error. 
Also did you do a clean build after getting the last version?
