### ISSUE TITLE
Can I use CNTK C++ API to train now?

### ISSUE THREAD

**Issue by playgithub** [Microsoft/CNTK#1796]
I've tried to search some keywords in `CNTKLibrary.h` like "dense", "sigmoid", but found nothing.

**Comment by KeDengMS** [comment]
Please refer to [test code](https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/V2LibraryTests/FeedForwardTests.cpp)
for C++ API training.

**Comment by playgithub** [comment]
I think I'll try C++ later, it seems only FullyConnectedNetwork is supported, no CNN and RNN supports.
And GPU and CPU are not abstracted yet, just not focus enough on deep learning.
Thanks all the same.

**Comment by KeDengMS** [comment]
All python APIs are built on top of C++ implementation in CNTK. Here are [C++ examples on RNN](https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/V2LibraryTests/RecurrentFunctionTests.cpp), [example on CNN](https://github.com/Microsoft/CNTK/blob/b7d4945a8e604268b344e6286e8993bacdba6e5c/Tests/EndToEndTests/CNTKv2Library/EndToEndTests/CifarResNet.cpp)
