### ISSUE TITLE
Train on real time generated data

### ISSUE THREAD

**Issue by tobyclh** [Microsoft/CNTK#1798]
Hello I am trying to augment my data set real time on the CPU.
Can anyone please tell me where I should look at or start reading?
Thank you.

**Comment by avader906** [comment]
Custom minibatch source in Python

**Comment by avader906** [comment]
@tobyclh why not consider [user defined minibatch sources](https://cntk.ai/pythondocs/extend.html#user-defined-minibatch-sourcesl) as the mechanism to feed the real time (probably buffered) data

**Comment by tobyclh** [comment]
I will look it up,
Thank you.
