### ISSUE TITLE
Commit messages don't follow git guidelines

### ISSUE THREAD

**Issue by edran** [Microsoft/CNTK#18]
A quick look at the history of the repository shows that most of the past commits don't comply with git's standard commit guidelines (see [here](https://git-scm.com/book/ch5-2.html)), which you might want to follow to make reading logs a bit easier and clean up the history if you are looking for external contributors.

Some examples:
* 53de59c1c74b4307bd945ceb6df7724d4bc8bdc1 uses past tense and mostly repeats its content.
* 198d64dd64f170bac83decb0b5a15df1db416d24 uses past tense and line is too long (and gets split by Github or text editors depending on configuration)

**Comment by alexeyo26** [comment]
Thank you. Gut input for contribution guidelines. (see #17)
