### ISSUE TITLE
The system cannot find the batch label specified - sphinx_ok

### ISSUE THREAD

**Issue by bianliu1013** [Microsoft/CNTK#1800]
got below issue when try to run **cntk\bindings\python\doc\build.bat:**

_C:\projects\cntk\bindings\python\doc>.\make.bat html 
.\build.bat : The system cannot find the batch label specified - sphinx_ok
At line:2 char:1
+ .\build.bat
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The system cann...ied - sphinx_ok:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: The system cannot find the batch label specified - sphinx_ok_

I am using a VM (Windows Server 2012 R2) on Azure.

**Comment by liqunfu** [comment]
@bianliu1013 I am not able to repro this. Your local make.bat may get changed. Please refresh from cntk source.
