### ISSUE TITLE
CNTK Python support installation problem

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/CNTK#1802]
I want to install CNTK v2 python support.
I followed all the steps in wiki. And when I build CNTK, an error occurs:
` No such file or directory: '~/src/myCNTK/CNTK/bindings/python/cntk/libs/libcudart.so.7.5'`
however, I find libcudart.so.7.5 in `~/src/myCNTK/CNTK/bindings/python/build/lib.linux-x86_64-3.4/cntk/libs/libcudart.so.7.5`

Can someone tell me what to do to solve this problem?

**Comment by youssefhb** [comment]
did you activate anaconda environment  cntk-py  ?

**Comment by yttdebaba2** [comment]
I reinstalled the latest CNTK, and the problem is solved.
