### ISSUE TITLE
Porting issue: Are BlockHandler[SSE,AVX] deprecated?

### ISSUE THREAD

**Issue by bcbrock** [Microsoft/CNTK#1805]
@jayfurmanek and I are involved in an effort to port CNTK to the POWER platform. The main codebase is straightforward - we simply follow along with ARM and compile-switch-out X86 intrinsic headers in a couple of places.

However we still fail the unit tests because of the intrinsic header #includes in BlockMultiplier.h. Looking into this further I see that the BlockHandler/BlockMultipler objects are not used in the main code at all, only in the tests. CNTK builds fine without compiling Source/Math/BlockHandlerSSE.cpp.

I assume that these facilities have either been deprecated, or perhaps were experiments that never made it into production. When we submit a proposed POWER port can we eliminate them altogether, or do we need to provide a portable or POWER-specific versions?

I believe @anthonyaue may be the author of this code.

**Comment by KeDengMS** [comment]
Seems dead code to me. Mark can you comment?

**Comment by mahilleb-msft** [comment]
Thanks, it's gone now.
