### ISSUE TITLE
Dense, map_rank option not implemented

### ISSUE THREAD

**Issue by sebastiankochman** [Microsoft/CNTK#1806]
Would it be possible to remove the following error from the code base:

https://github.com/Microsoft/CNTK/blob/4e987c030b018befc98f32f20f15f1dcd1a92726/bindings/python/cntk/layers/layers.py#L97

    if input_rank is not None:
        infer_input_rank_to_map = -1 # means map_rank is not specified; input_rank rules
    elif map_rank is None:
        infer_input_rank_to_map = 0  # neither given: default to 'infer W to use all input dims'
    else:
        UntestedBranchError("Dense, map_rank option not implemented")
        infer_input_rank_to_map = map_rank  # infer W to use all input dims except the first static 'map_rank' ones

map_rank parameter on the Dense layer is very useful, e.g. in the NLP scenarios. From my limited experiments, it works as expected (when I comment out that line myself).

**Comment by liqunfu** [comment]
fixed in master
