### ISSUE TITLE
How to read input data from multiple nodes

### ISSUE THREAD

**Issue by wangsiyu** [Microsoft/CNTK#1808]
Hello cntk community,

I want to read data of total batch size 512 in data parallelism mode by using 2 nodes . Each node has 2 GPUs. So I must split my dataset into 4 subset accross different nodes. So the problem is how to configure that in BrainScript? Need I split my dataset into different replicas before my training task？ I didn't find any document or wiki in this repo.

Thanks.

**Comment by eldakms** [comment]
hi wangsiyu,

Could you please share you config? Which reader do you use?
CNTK readers split data without user interaction, all data should be available to all workers though. Just make sure the data is available on some distributed file system, (i.e. hdfs, or share)

**Comment by wangsiyu** [comment]
Hi  eldakms,
This is my reader config for AlexNet. I want to use this reader to read data accross multi nodes. And my data is  not on hdfs. So does it mean I can place my data on every node without splitting data? Then cntk will read data according to their mpi rank number? 

# Reader
    reader = {
        verbosity = 0
        randomize = true
        randomizationWindow = 1

        deserializers = (
        {
            type = "ImageDeserializer" ; module = "ImageReader"
            file = "$DataDir$/train_map_tab.txt"
            input = {
                features = {
                    transforms = (
                        {
                            type = "Crop"
                            cropType = "RandomSide"
                            sideRatio = 0.88671875
                            jitterType = "UniRatio"
                        }:{
                            type = "Scale"
                            width = 227
                            height = 227
                            channels = 3
                            interpolations = "linear"
                        }:{
                            type = "Transpose"
                        }
                    )
                }
                labels = {
                    labelDim = 1000
                }
            }
        })
    }

**Comment by wangsiyu** [comment]
It seems that no one knows this........

**Comment by avader906** [comment]
@wangsiyu you do not need to split the data. CNTK takes care of sending appropriate data to every worker on every node (MPI ranks). 

The exact way it does it is through randomizing chunks of the inputs data and evaluating them across ranks. There are different ways it can aggregate gradients [(wiki link)](https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines)

Same data file should be accessible from both nodes. It is possible to put the same input data file into a local directory - or to share it across network share from one of the nodes.

**Comment by wangsiyu** [comment]
@avader906  I would place the same input data in the same path on both nodes.Thank you for your answer! It solves my problem!

**Comment by liqunfu** [comment]
According to @wangsiyu this issue is solved.
