### ISSUE TITLE
failed to open val1024.zip 

### ISSUE THREAD

**Issue by jerremy1336** [Microsoft/CNTK#1811]
I put the val1024.zip and train_map.txt, val_map.txt files in cntk/Example/Image/Datasets/ImageNet, and run python AlexNet_ImageNet_Distributed.py, but I got RuntimeError: Failed to open val1024.zip, zip library error: No such file. I can unzip val1024.zip, so it should be OK. Should I put the zip file in other directory? Thanks!

**Comment by cha-zhang** [comment]
How does your train_map.txt look like?

**Comment by jerremy1336** [comment]
I just copied it from CNTK/Tests/EndToEndTests/Image/Alexnet/Train_map.txt:

val1024.zip@/ILSVRC2012_val_00000001.JPEG
val1024.zip@/ILSVRC2012_val_00000002.JPEG
val1024.zip@/ILSVRC2012_val_00000003.JPEG
val1024.zip@/ILSVRC2012_val_00000004.JPEG
val1024.zip@/ILSVRC2012_val_00000005.JPEG
...

**Comment by cha-zhang** [comment]
Most like the path to data is not correct. If you are using AlexNet_ImageNet_Distributed.py, have you tried to explicitly specify datadir as an argument?

**Comment by jerremy1336** [comment]
I have already tried to specify the datadir, but it got the same error. Besides, I think it is not necessary to specify the datadir since I put the data in DataSets/ImageNet, because it should look for the data from it by default.

**Comment by cha-zhang** [comment]
Try to use the attached map file instead. It has been tested and should work. The ".../" at the beginning of each row tells CNTK the zip file exist in the same folder as the map file. 
[val1024_map.txt](https://github.com/Microsoft/CNTK/files/966814/val1024_map.txt)

**Comment by jerremy1336** [comment]
It works now, thanks so much for your help!
