### ISSUE TITLE
Tutorial CNTK_103C_MNIST_MultiLayerPerceptron.ipynb: incorrect eval_error reported

### ISSUE THREAD

**Issue by MarekOzana** [Microsoft/CNTK#1829]
I believe there is a typo in Tutorial CNTK_103C_MNIST_MultiLayerPerceptron.ipynb.
The variable eval_error inside of def print_training_progress(): in cell "In[14]" should be calculated as
_eval_error = trainer.previous_minibatch_evaluation_average_
and not as 
_eval_error = trainer.previous_minibatch_loss_average_
As of now the Tutorial reports error as just 100*loss.
Thank you for your time spend with tutorials, it is incredible piece of work!
 /marek

**Comment by sayanpa** [comment]
Yes. Marek.  Thanks for your kind words. 

Thanks for reporting the bug. We have a Code Review in progress to fix the bug and other enhancements, in this branch.

https://github.com/Microsoft/CNTK/blob/sayanpa/tutfix/Tutorials/CNTK_103C_MNIST_MultiLayerPerceptron.ipynb

**Comment by liqunfu** [comment]
fix checked in
