### ISSUE TITLE
division operation

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#183]
Rookie here. Is there any possible methods to implement ‘division’ using all current computation nodes? Or i should to follow the guide to add a new node ? Thx!

**Comment by frankseide** [comment]
You mean an element-wise quotient?

We would have to add a new node, but it should be easy. But please don’t follow the guide, it is probably outdated ☹ . Instead, follow example nodes.

You could copy class ElementTimesNode or PlusNode in LinearAlgebraNodes.h.

There is a tensor operation called {Assign,Add}ElementwiseQuotientOf(); its actual implementation is defined in TensorOps.h, DefBinaryOp(ElementwiseQuotient, ClippedQuotient(a, b));

You can implement ForwardProp() easily, by just changing –ElementWiseProduct- to –ElementwiseQuotient-.

BackpropTo() may be harder, as you may need extra memory for temporaries.

A workaround would be to use Log and Exp ☺ But this will fail for negative numbers or zero.

Thanks,

Frank

**Comment by staplesinLA** [comment]
@frankseide  my goal is to slightly modify the objective function, now i will try to solve it . Thanks for your kind reply.

**Comment by staplesinLA** [comment]
I just notice that the new version of CNTK book deletes the chapter of "extending the CNTK"..lol.. So how to achieve its flexibility?

**Comment by frankseide** [comment]
This is mostly because we have made many changes recently, so that this chapter will require a major rewrite. We are also working on a librarified version of CNTK with Python and .Net bindings, which will yet again change much of this information.

**Comment by staplesinLA** [comment]
sorry,i don't familiar with the entire code framework. except for following the example nodes to make a "elementwise-quotient" node, the corresponding ForwardProp() and BackprotTo() should be modified too?
Thanks for your patience.

**Comment by dongyu888** [comment]
Yes, that’s the key.
