### ISSUE TITLE
GPU vs CPU Eval witn CNTKLibrary

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1830]
Sorry if these simple questions have answers somewhere in your documentation, but I haven't found them.

Using CNTK.GPU versus CNTK.CPUOnly from NuGet with 2-0-rc2 and VS2015 writing in C++.   I got my code working to evaluate my network in CPU mode. Yeah, great!  Now I am trying to get evaluation going on GPU.  My network takes about 6 seconds to evaluate with CPU.   I know my GPU works because I use it in training with great results (epoch in 15 seconds instead of 22 mins on CPU!).

With NuGet I uninstalled CNTK.CPUOnly and installed CNTK.GPU, changed my code to ask for DeviceDescriptor::GPUDevice(0) and re-built.   Ran the eval code -- works, but still takes 6 seconds.

Questions:

1) Is there way I can check that the GPU was actually being used?
2) Maybe its normal - for one single eval it takes time to load up the GPU so maybe it takes 6 secs?  I would have to be pushing several input cases thru the same net to see the speed up?  Or?
3) If I set my code up for GPU, if it runs on a machine with no GPU will it "degrade gracefully" and run on the CPU?  Or is it up to me to figure out if GPU is there, and call eval with correct device?
4) Can I (should I?) have *both* NuGet packages installed at the same time?

As a possibly related question - as a newcomer to NuGet -- is it flakey?  Sometimes installing a NuGet package takes 1 seconds, and sometimes 45 seconds.   In one case I also am pretty sure that it did not place Cntk.Eval-2.0rc2.lib in the required folder -- I put it there manually, then all worked.   So, NuGet, which seems fantastic in theory, has glitches?

Thanks

**Comment by zhouwangzw** [comment]
@JohnCraigPublic Greate to know that you make both CPU and GPU work with your project. Regarding your qeustions: 
1) nvidia-smi.exe (usually installed in the folder "Program Files\NVIDIA Corporation\NVSMI") can show you the GPU usuage.
2) It is very depenent on your model. The data needs to be transfered from CPU to GPU, which is an addtional overhead for using GPU. 
3) if you use UseDefaultDevice() when specifying the device parameter (e.g. in LoadModel(), CreateValue() and Evaluate()), it will choose a GPU device if it is available, and a CPU device on machine without GPU. But if you explictly specify GPUDevice(0) or CPUDevice(), only the specified device is used.
4) The GPU package covers both GPU and CPU. You should only install one Nuget package. The GPU package contains addtional dlls for CUDA/CUDNN, so it is much bigger in size, and might take longer time for installation.

Thanks,
Zhou

**Comment by JohnCraigPublic** [comment]
Thanks!

**Comment by JohnCraigPublic** [comment]
Thanks
