### ISSUE TITLE
cntk_helpers.py:809: RuntimeWarning: overflow encountered in exp   e = np.exp(w)

### ISSUE THREAD

**Issue by evgenibers** [Microsoft/CNTK#1834]
After running A3_ParseAndEvaluateOutput.py I've got this:

C:\local\CNTK-2-0-beta8-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\F
astRCNN\cntk_helpers.py:809: RuntimeWarning: overflow encountered in exp
  e = np.exp(w)
C:\local\CNTK-2-0-beta8-0-Windows-64bit-CPU-Only\cntk\Examples\Image\Detection\F
astRCNN\cntk_helpers.py:810: RuntimeWarning: invalid value encountered in true_d
ivide
  dist = e / np.sum(e, axis=1)[:, np.newaxis]

Before this w was: [[ 183.77772522 -126.88010406  -33.41016769  -25.5818882 ]
 [ 183.77772522 -126.88010406  -33.41016769  -25.5818882 ]]

And also "Mean AP = 0.0000" after this.

Can someone explain why it happen and how to solve it? Thanks.

**Comment by cha-zhang** [comment]
We used to have some unstable ops. They should have been resolved by now. Closing this issue. If problem remains, please open a new issue. Thanks!
