### ISSUE TITLE
How to get truncated value?

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1837]
When i trained a truncated LSTM, i want to do MVN to minibatch_data. It crashed.
RuntimeError: Cannot create an unpacked Value object from packed data where one or more sequences are truncated.

**Comment by KeDengMS** [comment]
Some sequence operations that unpacks sequence do not support truncated data, like sequence.reduce*.

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Please reopen if needed.
