### ISSUE TITLE
Softmax computation

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1839]
The last part of my net is  p = softmax(z)  and all works well.
Then, I wrote my own Softmax function, and changed my network to just output "z" and then I apply my own Softmax to that z.   Also works, but my Softmax values differ from those computed by CNTK.   My values also sum to 1.0 and do always return the same 'most likely' element, but values are different.  

Question: Is the Softmax in CNTK somehow not the normal one?  Is it scaled, or log-of instead of not, or something that is understood?

Or, is my Softmax code wrong?  Here it is...

CdoubleArray* Softmax(CdoubleArray* pInputs)
{
	CdoubleArray* pOutputs = new CdoubleArray();

	int i, j, n;
	n = pInputs->GetSize();

	// output will be same size as input
	pOutputs->SetSize(n);

	// get maximum of inputs and store in 'm'...
	double m = pInputs->GetAt(0);
	for (i = 1; i < n; i++)
	{
		if (pInputs->GetAt(i) > m) m = pInputs->GetAt(i);
	}

	// compute term that is independent of output j   (  log{sum_i{exp(zi-m)}})  ) 
	double term;
	double sum = 0.0;
	for (i = 0; i < n; i++)
	{
		double zi = pInputs->GetAt(i);
		double expzim = exp(zi - m);
		sum = sum + expzim;
	}
	term = log(sum);  

	// compute outputs       ( oj = exp (zj - m - log{sum_i{exp(zi-m)}})  )
	for (j = 0; j < n; j++)
	{
		double oj = exp(pInputs->GetAt(j) - m - term);
		pOutputs->SetAt(j, oj);
	}

	return pOutputs;
}

**Comment by KeDengMS** [comment]
You can find CNTK softmax CPU implementation [here](https://github.com/Microsoft/CNTK/blob/master/Source/Math/CPUMatrixImpl.h#L2377). If you are comparing with CNTK CPU device result, it might due to non-determinism in OpenMP. Please try set OMP_NUM_THREADS=1 in environment and see if you can get matching numbers.
