### ISSUE TITLE
Failed to train AMI IHM model from Kaldi data

### ISSUE THREAD

**Issue by vmswork** [Microsoft/CNTK#184]
Hi,

I'm trying to train an acoustic model with CNTK and Kaldi with this script https://github.com/Microsoft/CNTK/blob/master/Examples/Speech/Miscellaneous/AMI/train_cntk2.sh

After preparing the data and  moving Truncated=false in CNTK2.cntk from reader into top (TrainDNN) section I got this error: 
`[CALL STACK]
  /home/superuser/lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::CollectCallStack(std::function<void (std::string)> const&, std::function<void ()> const&)  + 0x101 )  [0x7fda7fa7f5e1]
  /home/superuser/lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::PrintCallStack()  + 0x88  )  [0x7fda7fa7fa78]
  /home/superuser/bin/cntk       ( void Microsoft::MSR::CNTK::ThrowFormatted<std::runtime_error>(char const*, ...)  + 0xe2  )  [0x541192]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::NDLScript<float>::ParseDefinition(std::string const&)  + 0x26d )  [0x59eb1d]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::NDLScript<float>::ParseValue(std::string const&, unsigned long, unsigned long)  + 0x46e )  [0x59fd1e]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::ConfigParser::Parse(std::string const&, unsigned long)  + 0x264 )  [0x5433f4]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::NDLScript<float>::FileParse(std::string const&)  + 0x1a4 )  [0x576954]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::NDLBuilder<float>::LoadFromConfig(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)  + 0x19f )  [0x59adbf]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::NDLBuilder<float>::BuildNetworkFromDescription(Microsoft::MSR::CNTK::ComputationNetwork*)  + 0x29  )  [0x59b019]
  /home/superuser/bin/cntk       ( std::_Function_handler<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int), void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)::{lambda(int)#2}>::_M_invoke(std::_Any_data const&, int)  + 0x12  )  [0x73ecd2]
  /home/superuser/bin/cntk       ( Microsoft::MSR::CNTK::SGD<float>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*, bool)  + 0x49a )  [0x72c7da]
  /home/superuser/bin/cntk       ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x22c )  [0x74853c]
  /home/superuser/bin/cntk       ( void DoCommands<float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x804 )  [0x596bb4]
  /home/superuser/bin/cntk       ( wmainOldCNTKConfig(int, wchar_t**)        + 0x909 )  [0x53aae9]
  /home/superuser/bin/cntk       ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53b140]
  /home/superuser/bin/cntk       ( main                                      + 0xd8  )  [0x52fdb8]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf5  )  [0x7fda7e6e4ec5]
  /home/superuser/bin/cntk       (                                                   )  [0x533b84]
EXCEPTION occurred: function 'FF' already defined`

Can anyone help with this?

Regards, 
Valentin

**Comment by dongyu888** [comment]
EXCEPTION occurred: function 'FF' already defined

 

This means the macro ‘FF’ has been defined twice in your script. It’s possible that you included a macro file that contains the same macro.

**Comment by vmswork** [comment]
Thank you for the reply.

I cloned from master and applied this fix https://github.com/yzhang87/CNTK/commit/367db5e76e5d11f78b8222baf90caa3fbc73bd35 in order to be able to build CNTK. No other changes in the source have been made.

Regards.
Valentin

**Comment by yzhang87** [comment]
Hi,

Please remove the duplicated "FF" in dnn_6layer.ndl. It already defined in Examples/Speech/Miscellaneous/AMI/cntk_config/default_macros.ndl.

thanks,
Yu

**Comment by vmswork** [comment]
Thanks, Yu.

There were several other macroses duplicated in dnn_6layer.ndl.
Should I commit fixed  dnn_6layer.ndl. after successful training?

Regards.
Valentin

**Comment by mradmila** [comment]
Yes, please do.
