### ISSUE TITLE
CNTK (Transfer learning) not working with remote desktop

### ISSUE THREAD

**Issue by Bishwa-Subedi** [Microsoft/CNTK#1841]
I am trying to implement transfer learning concept (https://github.com/Microsoft/CNTK/wiki/Build-your-own-image-classifier-using-Transfer-Learning). 
We have set up an Remote GPU machine and I want to access it using MS remote desktop from my laptop. While running TransferLearning.py it says "Specified device id (0) is invalid". 
While trying to run it on CPU instead of GPU it says "Batch Normalization training on CPU is not yet implemented"

I found that GPU features are disabled when using MS remote desktop. Is above error "Specified device id (0) is invalid" is due to the fact that I am using remote desktop? Is there any workaround for it?

Thanks a lot in advance.
Bishwa

**Comment by Sadler2** [comment]
Yes, this is the property of RDP: 

> On the server, RDP uses its own video driver to render display output by constructing the rendering information into network packets by using RDP protocol and sending them over the network to the client.
https://msdn.microsoft.com/en-us/library/aa383015.aspx

The only workaround I may suggest as an ordinary user of CNTK is to close your RDP session during the whole learning proccess or at least during device initialization phase.

**Comment by Bishwa-Subedi** [comment]
Hi Sadler2,

Thanks for your reply. 
I could not understand your workaround. My GPU machine is few hundreds kilometer away from me and I am accessing GPU machine through RDP. In order to run TransferLearning.py in GPU machine. I should create a RDP session between my laptop and remote machine. 

How can I run any script on remote by closing an RDP session? Am I missing any fundamental point about RDP here?

Thanks a lot in advance.
Bishwa

**Comment by Sadler2** [comment]
Well, it's as easy as `ping 127.0.0.1 -n 10 && your_command`, you will have around 10 seconds to close your remote session. Not too elegant, but it works. Also you might think about replacing RDP with another remote desktop solution (e.g. VNC).

**Comment by avader906** [comment]
RDP 8.0 remoting to a node with GPUs works fine - you may need to update your client or investigate the issue further.

**Comment by Bishwa-Subedi** [comment]
Hi Sadler2,

Thanks for the solution, but still I am facing "Specified device id (0) is invalid".

Thanks,
Bishwa

**Comment by cha-zhang** [comment]
One workaround is to use VNC, although I seem to be able to use RDP for GPU tasks without any problem. Maybe it's a driver issue?

**Comment by avader906** [comment]
@Bishwa-Subedi if you use RDP version 8.0+ on the host and client, GPU should be accessible without any issues via **Remote Desktop**. 

- For GTX cards, the setup we have is Windows 2012 R2 ***hosts*** and NVIDIA driver version 21.21.13.7290 (3.7230). 
- Both Windows 7 (with updated RDP client), Windows 10 and Windows 2012 ***clients*** have access to the host and its GPU via **Remote Remote desktop** feature. You would need to configure the registry to eliminate TDR timeout for the GTX card.

If you want to access the host through **Remote Desktop Services**/***RDS*** - you would need Tesla card (TCC mode) as the GPU needs to be virtualized properly via RemoteFX/vGPU.

**Comment by Bishwa-Subedi** [comment]
Hi cha-zhang, avader906

Thanks a lot for your suggestion. I will try your solutions next week and let you know the result.

Once again, Thanks a lot for your time.

Bishwa

**Comment by avader906** [comment]
@Bishwa-Subedi the easiest would be uninstall Remote Desktop Services Role/Feature from the server, check NVIDIA driver version and enable the simple Remote Desktop access. Then you would need to disable TDR timeout [(documentation here)](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys) on the server via regedit.exe and modifying ***TdrLevel*** key to 0 (please read the documentation and disclaimer about editing registry settings).
