### ISSUE TITLE
CUBLAS_STATUS_NOT_INITIALIZED  error thrown

### ISSUE THREAD

**Issue by snurkabill** [Microsoft/CNTK#1843]
Hello, 

CUDA specific error has come up, not sure how to fix this. It's not easily reproducible, but happens sometimes. 

CUBLAS failure 1: CUBLAS_STATUS_NOT_INITIALIZED ; GPU=1 ; hostname=TERATORNIS ; expr=cublasCreate(&cuHandle)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  GetCublasHandle
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::Matrix<float>::  MultiplyAndWeightedAdd
    - Microsoft::MSR::CNTK::TensorView<float>::  DoMatrixProductOf
    - Microsoft::MSR::CNTK::TensorView<float>::  AssignMatrixProductOf
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
    - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2

According to some issue threads found on internet, this is CUDA specific error. Do you have any idea how to fix this for windows/cntk platform? I've found out that it could happen during memory copying from GPU -> CPU. Is it possible that due to lack of free RAM such error can be thrown? 

Env. Info: 

Build info: 

        Built time: Jan 16 2017 05:00:17
        Last modified date: Mon Jan 16 04:49:45 2017
        Build type: Release
        Build target: GPU
        With 1bit-SGD: no
        With ASGD: yes
        Math lib: mkl
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
        CUB_PATH: c:\src\cub-1.4.1
        CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v5.1
        Build Branch: HEAD
        Build SHA1: 66f4d8d594cab128f5fe160ade2adfd04a164004
        Built by svcphil on Philly-Pool3
        Build Path: C:\Jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
        MPI distribution: Microsoft MPI
        MPI version: 7.0.12437.6

CNTK 2.0.beta8.0 (HEAD 66f4d8, Jan 16 2017 05:00:17) on TERATORNIS at 2017/05/04 16:39:28

NVIDIA GPU Computing Toolkit: v8.0
CUB: cub-1.4.1
CUDNN: cudnn-8.0-windows10-x64-v5.1

**Comment by avader906** [comment]
@snurkabill Could you please try the update to RC2 from beta 8 ?

**Comment by wolfma61** [comment]
If you still run into this issue with the latest released bits, please open a new issue ...
