### ISSUE TITLE
Training stops to load extra chunk despite prefetch = true (CNTKTextFormatReader)

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1847]
The asynch data pre-fetch for each node does not seem to happen with ASGD over N nodes. 
Node stops computation until data is fetched. No randomization and data chunk size is 15GB.

Relevant BS configuration:
```
parallelTrain = true
prefetch = true
numCPUThreads = 0
....
SGD = [
    ....
    parallelTrain = [
        parallelizationMethod = "DataParallelASGD"
        usePipeline = true
        ....
    ]
]
reader = [
        readerType = "CNTKTextFormatReader"
        frameMode = false
        randomize = false
        chunkSizeInBytes = 16106127360 #15 GB chunks
        keepDataInMemory = false
        ...
]

**Comment by eldakms** [comment]
hi avader906,

Unfortunately, chunk prefetch is not yet implemented in case of no randomization. I cannot currently provide ETA on this :(

**Comment by avader906** [comment]
@eldakms on RC1 / data parallel 1bit SGD, when MB < chunksize < window size < epoch < training corpus; I still see that training stops on all nodes when the end of training corpus is reached (and rolled). For instance here:
```
 Epoch[ 2 of 4]-Minibatch[16561-16570, 33.14%]: ce = 1.10538800 * 14000; errs = 37.057% * 14000; time = 1.7779s; samplesPerSecond = 7874.6
Actual gradient aggregation time: 0.0375315
 Epoch[ 2 of 4]-Minibatch[16571-16580, 33.16%]: ce = 1.10230363 * 12830; errs = 36.352% * 12830; time = 573.9380s; samplesPerSecond = 22.4
Actual gradient aggregation time: 0.0395972
 Epoch[ 2 of 4]-Minibatch[16581-16590, 33.18%]: ce = 1.11050152 * 14000; errs = 37.271% * 14000; time = 1.7817s; samplesPerSecond = 7857.8
Actual gradient aggregation time: 0.0529107
```
You can see the impact in terms of samples per second. I though that it was done on a separate thread and thus should not slow down the training. Is this expected?

**Comment by eldakms** [comment]
IT is due to decimation happening on randomized chunk ids. So when the end of the sweep is reached - rerandomization happens and different workers got different chunk ids (not from the previous sweep). This was changed in python, but not for BS. For BS you can use keepDataInmemory flag.
