### ISSUE TITLE
ASGD - suggestions for the overall algo improvement

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#1849]
@chivee Why does cross-validation (at the end of epoch) is being evaluated on the same data over all nodes? Would it not be more logical and less wasteful to create chunk index and to distribute evaluation in minibatches across all nodes (and synchronize pre cv)?

For fine tuning, ASGD really needs per rank MB and Epoch size. This would allow fine-tuning execution over large clusters. GPU/CPU and some other metric could be hashed and used as ID for a rank and its parameters. Alternatively, synchronization needs to be rethought - avoiding wait for Epoch completion on all nodes.

**Comment by chivee** [comment]
@avader906 , because of the eval logic  wasn't compatible with ASGD training logic which doesn't hold any workers considering the stagger's existence.

actually, we are trying to add such feature for every rank.

**Comment by avader906** [comment]
@chivee thank you for your prompt reply. i will close this - if i understand correctly these have been addressed.
