### ISSUE TITLE
computation distribution

### ISSUE THREAD

**Issue by mbz** [Microsoft/CNTK#185]
<< Please excuse me if this is not the right place fo asking questions. I couldn't find any forum or maiiling list to do so. >>

I'm wondering how CNTK distributes the computation between multiple machines? 

Does it follow the same approach as [Google's DistBelief](http://papers.nips.cc/paper/4687-large-scale-distributed-deep-networks.pdf) (asynchronous distributed gradient decent) that also has been utilized by [CMU Parameter Server](http://parameterserver.org/)?

Or it actually distributes the CN (Computational Networks) between multiple IExecutionEngines?
Or any other method?

Thanks

**Comment by frankseide** [comment]
Thanks for your interest! Yes, the Issues section is currently the right place to ask questions.

CNTK uses data parallelism on a minibatch basis, using our “1-bit SGD” technique described in this paper:

http://research.microsoft.com/apps/pubs/?id=230137

which builds on this paper:

http://research.microsoft.com/apps/pubs/default.aspx?id=217322

In additionl, CNTK also implements model averaging.

Thanks,

Frank

**Comment by wolfma61** [comment]
closing ....
