### ISSUE TITLE
UserFunction with sequence reduce does not work

### ISSUE THREAD

**Issue by boeddeker** [Microsoft/CNTK#1855]
I am interested in the function `cntk.sequence.reduce_mean`, since it is not implemented in c++ and 
```
sequence_length = cntk.sequence.reduce_sum(cntk.reduce_sum(x)*0+1)
mean = cntk.sequence.reduce_sum(x) / sequence_length
```
require to many computation power, I tried to use a UserFunction, but it looks like that the UserFunction does not support a reduction above a sequence axis.

Here is my code:
```
import numpy as np
import cntk
from cntk import user_function
from cntk.ops.functions import UserFunction
from cntk import output_variable

x0 = np.random.normal(size=(1, 4, 3)).astype(np.float32)
x = cntk.sequence.input(shape=(3), name='in_data', needs_gradient=True)

class MySequenceSum(UserFunction):
    def __init__(self, arg1, axis=0, name='f1'):
        super().__init__([arg1], name=name)
        self.axis = axis

    def forward(self, arguments, device=None, outputs_to_retain=None):
        mean = np.sum(arguments[0], axis=self.axis, keepdims=False)
        print(arguments[0].shape, mean.shape)
        return None, mean

    def backward(self, state, root_gradients):
        raise NotImplementedError()

    def infer_outputs(self):
        return [output_variable(
                    self.inputs[0].shape, 
                    self.inputs[0].dtype, 
                    self.inputs[0].dynamic_axes[:-1]
       )]
    
def my_sequence_sum(arg1, axis):
    return user_function(MySequenceSum(arg1, axis))

x_sum_cn = cntk.sequence.reduce_sum(x)
x_sum_my = my_sequence_sum(x, axis=-2)

print(x)
print(x_sum_cn)
print(x_sum_my)
x_sum_cn.eval({x: x0})
x_sum_my.eval({x: x0})
```
and the last line breaks with
```
  File ".../CNTK/bindings/python/cntk/cntk_py.py", line 1559, in _forward
    return _cntk_py.Function__forward(self, *args)

RuntimeError: The MBLayout of the output ({numTimeSteps:1, numParallelSequences:1, sequences:[{seqId:0, s:0, begin:0, end:1}]}) computed by the external function (f1) does not match the expected MBLayout ({numTimeSteps:0, numParallelSequences:1, sequences:[]})
```
where I modified the error msg to `LogicError("The MBLayout of the output (%s) computed by the external function (%S) does not match the expected MBLayout (%s)", std::string(*outputMatrixAndLayout.second).c_str(), m_externalFunction->Name().c_str(), std::string(*this->m_outputsMBLayout[i]).c_str());`.

Is there a Bug in my code or does UserFunction does not support sequence reduce?
Maybe sequence reduce mean is a good example for the documentation?

**Comment by wilrich-msft** [comment]
Hi @boeddeker ,

Thanks for reporting this. A fix is in master now, but before you try it out, there are a couple of issues with your user function...

1. If your user function is supposed to only get one input, then the argument pass to forward() is the data already. If it is taking more inputs, then we pass a tuple of arguments. In your case, you already get the data directly so we have `def forward(self, argument, device=None, outputs_to_retain=None)` and `argument` holding the full minibatch for the only input.

2. In your version your input variable has a sequence axis, which means that your individual minibatch samples can be of varying lengths. That's we you should not assume the minibatch to be a NumPy array, but instead a list of NumPy arrays, representing individual sequences (if you store varying sized arrays into a NumPy array, its dtype will be 'object' and you can't use it really).

3.  Your infer_outputs() sets the shape ignoring the axis argument in the constructor, which might lead to surprises. Better not let axis be set in the constructor, but rather fix it.

I've attached an updated version:
```
import numpy as np
import cntk
from cntk import user_function
from cntk.ops.functions import UserFunction
from cntk import output_variable

x0 = np.random.normal(size=(4, 3)).astype(np.float32)
x = cntk.sequence.input(shape=(3,), name='in_data', needs_gradient=True)

class MySequenceSum(UserFunction):
    def __init__(self, arg1, name='f1'):
        super().__init__([arg1], name=name)

    def forward(self, argument, device=None, outputs_to_retain=None):
        summed = np.sum(argument, axis=1, keepdims=False)
        print(argument)
        print(summed)
        return None, summed

    def backward(self, state, root_gradients):
        raise NotImplementedError()

    def infer_outputs(self):
        return [output_variable(
                    self.inputs[0].shape, 
                    self.inputs[0].dtype, 
                    self.inputs[0].dynamic_axes[0:1]
       )]
    
def my_sequence_sum(arg1):
    return user_function(MySequenceSum(arg1))

x_sum_cn = cntk.sequence.reduce_sum(x)
x_sum_my = my_sequence_sum(x)

print(x)
print(x_sum_cn)
print(x_sum_my)
print('---')
print(x_sum_cn.eval({x: [x0]}))
print('---')
print(x_sum_my.eval({x: [x0]}))
```

**Comment by boeddeker** [comment]
Thanks for the fix, the explanation and the new example code. I thought the list in arguments is for the input and not for the minibatch. 

To 3: This code is a simplification of my desired function. I want to have a sequence mean (currently not supported in cntk), where I can select the dynamic axis, because I will later have more than 2 dynamic axis.
 
I find it weird, that in the init is [arg1] and in the forward argument. 
I was expecting an interface like the following (Look at `arg1 `in `super().__init__` and the second `forward` arg):
```python
class MySequenceSum(UserFunction):
    def __init__(self, arg1, name='f1'):
        super().__init__(arg1, ...)

    def forward(self, argument, ...):
        ...
```
```python
class MySequenceSum(UserFunction):
    def __init__(self, arg1, name='f1'):
        super().__init__([arg1], ...)

    def forward(self, arguments, ...):
        ...
```
```python
class MySequenceSum(UserFunction):
    def __init__(self, arg1, name='f1'):
        super().__init__([arg1], ...)

    def forward(self, *arguments, ...):
        ...
```
