### ISSUE TITLE
Failing to load pre-trained ResNet ImageNet model for retraining

### ISSUE THREAD

**Issue by DerMascha** [Microsoft/CNTK#1859]
I'm trying to retrain the pre-trained ResNet model with a custom data set.

But when I use clone function like this:
```
net = BS.Network.Load("...\Models\ResNet152_ImageNet.model")
	
network = BS.Network.CloneFunction((net.features), net.ol, parameters="learnable")
```

it fails with "unknown error" when loading the model file.

**Comment by cha-zhang** [comment]
Is this the Caffe converted ResNet152 model?

**Comment by wolfma61** [comment]
closing due to lack of feedback
please create a new issue with more information if this is still open...
