### ISSUE TITLE
too many ResNet stacks crash with CNTK.exe on linux

### ISSUE THREAD

**Issue by julienlopez** [Microsoft/CNTK#1860]
Hi, I'm trying to train a network made mostly of ResNet stacks, but on my ubuntu (16.10) machine, with the RC2 GPU release (on a GTX 1080 TI 11Gb), CNTK.exe crashes when I add more stacks:
For example:
cMap = 8:16:32:64:128:256:512
model = Sequential (
            ResNetBasicInc {cMap[0], (2:2), bnTimeConst} :
            ResNetBasic {cMap[0], bnTimeConst} :
            ResNetBasicInc {cMap[1], (2:2), bnTimeConst} :
            ResNetBasic {cMap[1], bnTimeConst} :
            ResNetBasicInc {cMap[2], (2:2), bnTimeConst} :
            ResNetBasic {cMap[2], bnTimeConst} :
            ResNetBasicInc {cMap[3], (2:2), bnTimeConst} :
            ResNetBasic {cMap[3], bnTimeConst} :
            ResNetBasicInc {cMap[4], (2:2), bnTimeConst} :
            ResNetBasic {cMap[4], bnTimeConst} :
            ResNetBasicInc {cMap[5], (2:2), bnTimeConst} :
            # ResNetBasic {cMap[5], bnTimeConst} :
            ResNetBasicInc {cMap[6], (2:2), bnTimeConst} :
            # ResNetBasic {cMap[6], bnTimeConst} :
            ConvBNReLULayer {$labelDim$, (3:3), (1:1), bnTimeConst} :
            BatchNormalizationLayer {spatialRank = 2, normalizationTimeConstant = bnTimeConst, useCntkEngine = false}
)

crashes on model creation: (and this is not a CUDA out of memory error)

Creating virgin network.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 1] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 512] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 512] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 256] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 256] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 128] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 128] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 128] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 128] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 64] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 32] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 32] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 32] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 32] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 16] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 16] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 16] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 16] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 8] as heNormal later when dimensions are fully known.
Node '<placeholder>' (LearnableParameter operation): Initializating Parameter[3 x 3 x 0 x 8] as heNormal later when dimensions are fully known.
Erreur de segmentation (core dumped)

While if I just remove the line ResNetBasic {cMap[4], bnTimeConst}, it works.
Is this a known issue? Am I doing something wrong here? 
Let me know if you need any help

Edit: apparently, this is not an issue on Windows (same version of CNTK, different machine though)

**Comment by cha-zhang** [comment]
Yes, this is a known issue. Increasing your stack size to 64MB will likely resolve the issue. 

Python API doesn't have this issue, although we are yet to write the Python script for ResNet for ImageNet.

**Comment by cha-zhang** [comment]
I'm closing this issue for now. Please reopen it if needed. Thanks!
