### ISSUE TITLE
Tutorial for translation using seq2seq api.

### ISSUE THREAD

**Issue by PratsBhatt** [Microsoft/CNTK#1861]
I did find a wiki page describing the translation problem and experiences using seq2seq. 
Can this code be made available to do a dry run?
Thanks for the info. Nice work!

Link: https://github.com/Microsoft/CNTK/wiki/Sequence-to-Sequence-%E2%80%93-Deep-Recurrent-Neural-Networks-in-CNTK-%E2%80%93-Part-2

**Comment by cha-zhang** [comment]
Please also check our tutorial on sequence to sequence here: 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb 

I'm closing this for now. If you have new issues regarding seq2seq, feel free to open a new issue. Thanks!
