### ISSUE TITLE
[Doc] Unclear if PBStat command overwrites saved models

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1864]
[https://github.com/Microsoft/CNTK/wiki/Top-level-commands#pbn-command](https://github.com/Microsoft/CNTK/wiki/Top-level-commands#pbn-commandl) described the post training update of layer-wise BN values. Is the trained model over-written? That is not clear from the documentation

- there is a broken link to the "Reader" section within Top-level-commands#pbn-command wiki
- [https://github.com/Microsoft/CNTK/wiki/Post-Batch-Normalization-Statistics#post-batch-normalization-statistics](https://github.com/Microsoft/CNTK/wiki/Post-Batch-Normalization-Statistics#post-batch-normalization-statistics) does not say of the model is over-written with new BN values under "Flow" section

**Comment by KeDengMS** [comment]
PBN is part of training process, so yes the in-memory model BN stats would be updated after this. If you chose to save model, then the saved model would have the updated BN stats after PBN.
I couldn't find the dead link in reader section. Could you give a url?

**Comment by cha-zhang** [comment]
See #1035. 

Closing this for now. Thanks!
