### ISSUE TITLE
FastRCNN C++ Evaluation input layer(s)

### ISSUE THREAD

**Issue by awscodu** [Microsoft/CNTK#1865]
I have two vectors. One contains the formatted bitmap of the image and the second contains the ROIs. I want to insert these into the inputLayer for evaluation but they must be ordered properly. 

According to the C code for evaluation, the inputs are separated with the image first and then the ROIs.
 
C code for constructing inputs:
` // inputs are the image itself and the ROI coordinates
                    var inputs = new Dictionary<string, List<float>>() { { inDims.First().Key, resizedCHW }, { inDims.Last().Key, rois } };`

Predicted C++ code:

`map<wstring, vector<float>> inputs = { {inDims.begin()->first, imgVector },{inDims.end()->first, roisVector} }`
`Layer outputLayer;
        auto outputLayerName = outDims.begin()->first;
        outputLayer.insert(MapEntry(outputLayerName, &outputs));`
`// and then`
`model->Evaluate(inputs, outputLayer);`

How is this accomplished correctly in C++ ?

**Comment by zhouwangzw** [comment]
@awscodu For mulitple inputs, you basically need to create a map that associates each input variable with its corresponding Value. Same for the oruput Varaibles, like below:  
```
inputValue = Value::CreateBatch(.....); // Or using other methods to create the Value object using your input data
labelValue = Value::CreateValue();
std::unordered_map<Variable, ValuePtr> inputMap = {{inputVar, inputValue}, {labelsVar, labelValue}}; 
// same to create ouput map
// Then call Evaluate() 
ffNet->Evaluate(inputMap, outputMap, computeDevice);

```

You can find C++ example for evaluation [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCPPEvalCPUOnlyExamples/EvalMultithreads.cpp). The function CreateFunctionAndEvaluateWithSharedParameters() shows how to create input and output with multiple variables.

Thanks,
