### ISSUE TITLE
Can't test models with multiple inputs

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#1866]
I trained a model with two inputs. But when test, i don't know how to specify two kinds of inputs in order to feed the model.
model_dnn= load_model("dnn.model")
>>>Composite(Dense): Input('Input3', [#, *], [257]), Input('Input5', [#, *], [2048]) -> Output('g_out', [#, *], [257])

Is there any examples?

**Comment by awscodu** [comment]
#1865

**Comment by awscodu** [comment]
https://github.com/Microsoft/CNTK/issues/1865#issuecomment-300741862
