### ISSUE TITLE
LAB 201B: The Library Cntk.Deserializers.Image-2.0rc2.dll not fount in CNTK

### ISSUE THREAD

**Issue by AlexV-T** [Microsoft/CNTK#1868]
I compiled the CNTK 2.0 RC2. Everything was fine except Multiverso components were missing (I took them from RC1). I tried the LAB 201 (Image Recognition) from the Tutorials. Part A went flawless, but Part B does not work.

Python returns an error saying:
RuntimeError: Plugin not found: 'Cntk.Deserializers.Image-2.0rc2.dll'

It turns out that this file is indeed missing. However, there are several other Deserializers in
\cntk\x64\Release_CpuOnly folder.

I would very appreciate any suggestions. I'm new to CNTK, and so far, this thing drives me crazy...
Thank you in advance.

**Comment by bencherian** [comment]
This DLL should be getting built by the ImageReader project in the Reader Plugins folder of your CNTK solution. When you try building that project by itself, do you get any errors?

**Comment by AlexV-T** [comment]
CNTK was built with no errors, but the Reader Plugins folder is NOT in the CNTK solution at all. Should I install CUDA components? I don't have a compatible GPU, so, I didn't...

**Comment by bencherian** [comment]
I'm not sure why the Reader Plugins solution is missing from your solution...it's in the CNTK 2.0rc2 source zip file download (I just checked) and it will be included if you cloned the repository directly. The ImageReader plugin will not build unless you have OpenCV installed and environment variables setup according to [the instructions](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#optional-opencv). You need both OpenCV and zlib/libzip setup to build ImageReader.

**Comment by AlexV-T** [comment]
Thank you very much, Bencherian! This was exactly the problem. OpenCV and zlob/libzip must be installed for Image Reader. So, it works. My only concern is that it is very slow. Quad-core CPU, 2 GHz, 97-100% loading on the full frequency. Average speed is about 65-67 pictures/sec. A good thing is that all the cores are used. I believe that 32 cores would make the process reasonably fast. Thanks again.
