### ISSUE TITLE
Parameters for PascalVoc

### ISSUE THREAD

**Issue by DHOFM** [Microsoft/CNTK#1869]
Hello,
regarding pkranens Tutorial here:
https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN

i always thougt all ROIs are created in the same way, by only varying the parameters, But for the PASCALvoc dataset Microsoft has it´s own class in CNTK called pascal_voc. In this class pre-computed ROIs are loaded from ..\Datasets\Pascal\selective_search_data and then recalculated for use in CNN. 
I would like to evaluate new images against the trained model, e.g. like nadavbar does in his code, but for that i need the parameters for region creation. Because the parameters in the above case are loaded from matlab files for the training images, they are not documented, how they were created. Anynone knows where to find the parameters, like ssSigma and so on for that case ? Please see a detailed discussion here:
https://github.com/CatalystCode/CNTK-FastRCNNDetector/issues/1
if you wonder what i am looking for.

Kind regards,

Dirk

**Comment by pkranen** [comment]
The pre-computed ROIs that we are using are the ones that were published by the author of the original paper. As described in the tutorial that you are pointing to (see https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN#run-pascal-voc):

- Download and unpack the precomputed ROIs to DataSets/Pascal/selective_search_data

The url changed, the file is now available at  https://dl.dropboxusercontent.com/s/orrt7o6bp6ae0tc/selective_search_data.tgz?dl=0CHECKSUM=7078c1db87a7851b31966b96774cd9b9, we'll update the tutorial with the new url. These ROIs were likely precomputed with a different code (Matlab), we also do not know the parameters for their creation.
