### ISSUE TITLE
Read data from memory

### ISSUE THREAD

**Issue by Mushroom-Head** [Microsoft/CNTK#187]
Hi,

I'd like to test CNN in a realtime imaging application.
This application needs to directly read the data from memory.
How can I do that in CNTK?  Are there any useful APIs to read the data? 

Thanks

**Comment by wolfma61** [comment]
I assume you want to run a model against a life image stream? 
Perhaps the C# eval wrapper is a starting point? 
but on top of that most image analysis requires preprocessing of the image (resolution adjustment, finding hot-spots, flipping or mirroring), all this is happening before evaluation ....

**Comment by rold2007** [comment]
@Mushroom-Head I did succeed to integrate my model/images with the C# wrapper, see #160 as it could help you resolve some issues I had.

**Comment by Mushroom-Head** [comment]
My test data is written on memory from camera. So, they have no file name(data is not jpg, png or other image formats). However, I think ImageReader needs the image file name list. 
I expect BinaryReader can be used to this application. But I cannot find any documents about BinaryReader. 
I want to know a method to read binary data from memory.

**Comment by mradmila** [comment]
Can you please take a look at this file and see if this is what you want? https://github.com/Microsoft/CNTK/blob/master/Source/Readers/ImageReader/ByteReader.h
Basically, you would provide another flavor of ByteReader, where bytes are coming from memory.
