### ISSUE TITLE
CNTK_Reinforcement example input_variable not found in cntk.ops.sequence

### ISSUE THREAD

**Issue by JulesVerny** [Microsoft/CNTK#1871]
The Reinforcement Learnig example fails at the following:

ImportError                               Traceback (most recent call last)
<ipython-input-6-30adf19fea40> in <module>()
      6 from cntk import *
      7 from cntk.layers import *
----> 8 from cntk.ops.sequence import input_variable
      9 # Select the right target device when this notebook is being tested:
     10 if 'TEST_DEVICE' in os.environ:

ImportError: cannot import name 'input_variable'

Presume the article example should state input not input_variable

**Comment by n17s** [comment]
Right, sequence.input_variable is a new thing in master. If you use notebooks from master, then you need to use cntk from master. If you use a tagged version of cntk, e.g. v2.0.rc2 then you need to use the corresponding tagged notebook (e.g. for v2.0.rc2 it would be [this](https://github.com/Microsoft/CNTK/blob/v2.0.rc2/Tutorials/CNTK_203_Reinforcement_Learning_Basics.ipynb))
