### ISSUE TITLE
"failed to lock GPU for exclusive use"

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#1872]
Intermittently, when I launch a run ( RC2 with GTX1080 ) -- I find that its using the CPU, and in the transcript it the message "failed to lock GPU for exclusive use".   This only happens perhaps 10% of the time when I launch a run.   Something has a hold of the GPU?  As far as I know, nothing is running on the PC when this happens.  My solution has been to restart the PC and try again, and then it always succeeds to find and use the GPU as it should.  Ideas?

**Comment by wolfma61** [comment]
We have run into issues like this on rare occasions and not reproducible. We something found stale process  hanging on to GPU resource, but origin/creator of these process was not always discover-able. Killing that process or rebooting helped - but no root cause could be determined.
