### ISSUE TITLE
cudaStreamDestroy fails due to address misalignment

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/CNTK#1873]
CUDA failure 74: misaligned address ; GPU=0 ; hostname=LOST-PC ; expr=cudaMemset(Data(), 0, N * sizeof(ElemType))
cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): misaligned address (cuda error 74)

CNTK's info:
```
-------------------------------------------------------------------
Build info:

                Built time: Apr 21 2017 01:37:43
                Last modified date: Fri Apr 21 01:22:28 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
                CUB_PATH: c:\local\cub-1.4.1
                CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v5.1
                Build Branch: HEAD
                Build SHA1: f190457aecbfe07c3fe27c89f36108bc2488727b
                Built by svcphil on DPHAIM-25
                Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTKv2LibraryDll\
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
-------------------------------------------------------------------
GPU info:

                Device[0]: cores = 5376; computeCapability = 6.1; type = "GeForce GTX 1080 Ti"; total memory = 11264 MB; free memory = 8917 MB
-------------------------------------------------------------------
```
I have rather unusual dimension sizes: featDim = 31 * 51 labelDim = 55

Training 654855 parameters in 4 out of 4 parameter tensors and 10 nodes with gradient:

        Node 'h1.W' (LearnableParameter operation) : [400 x 1581]
        Node 'h1.b' (LearnableParameter operation) : [400 x 1]
        Node 'ol.W' (LearnableParameter operation) : [55 x 400]
        Node 'ol.b' (LearnableParameter operation) : [55 x 1]

**Comment by KeDengMS** [comment]
Which build were you running on? If it still happens on latest master, please share a repro. Thanks!

**Comment by cha-zhang** [comment]
Closing this due to lack of response. Please reopen if needed. Thanks!
