### ISSUE TITLE
error no match for 'operator []'

### ISSUE THREAD

**Issue by nichongjia** [Microsoft/CNTK#1874]
Source/CNTKv2LibraryDll/Serialization.cpp:241:31: error: no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<CNTK::proto::DictionaryValue>’ and ‘int’)
             Copy((src.value())[i], dst->at(i));

**Comment by wolfma61** [comment]
All code in master passed build and test in our infrastructure
 If you run into problems we need more information to understand your build environment,
