### ISSUE TITLE
How to initialize a constant identity matrix in .ndl file?

### ISSUE THREAD

**Issue by SkTim** [Microsoft/CNTK#1876]
Hi,

I'm building a network with .ndl scripts. Could someone tell me how to initialize a constant identity matrix?

Thanks,
Hongyin

**Comment by cha-zhang** [comment]
Use a text file. 

Please consider moving to Python API as ndl are deprecated.

**Comment by SkTim** [comment]
Successfully loaded matrix from a text file. Thank you for help!
