### ISSUE TITLE
Optimizing module imports in CNTK_101_LogisticRegression.ipynb

### ISSUE THREAD

**Issue by michhar** [Microsoft/CNTK#1877]
For better accordance with Python best practices and to speed up imports, `from foo import *` should be avoided and instead specific submodules should be specified.

So, I'd suggest changing this block:

```python
# Import the relevant components
from __future__ import print_function
import numpy as np
import sys
import os
from cntk import *

# Select the right target device when this notebook is being tested:
if 'TEST_DEVICE' in os.environ:
    import cntk
    if os.environ['TEST_DEVICE'] == 'cpu':
        cntk.device.try_set_default_device(cntk.device.cpu())
    else:
        cntk.device.try_set_default_device(cntk.device.gpu(0))
```

to (also, removing an unnecessary `import cntk`):

```python
# Import the relevant components
from __future__ import print_function
import numpy as np
import sys
import os
from cntk import device, input_variable, parameter, times, \
                 cross_entropy_with_softmax, classification_error, \
                 learning_rate_schedule, sgd, Trainer, UnitType, \
                 softmax
    

# Select the right target device when this notebook is being tested:
if 'TEST_DEVICE' in os.environ:
    if os.environ['TEST_DEVICE'] == 'cpu':
        device.try_set_default_device(device.cpu())
    else:
        device.try_set_default_device(device.gpu(0))
```

The entire jupyter notebook as been run and tested on Windows using CNTK '2.0rc2' version for CPU with miniconda Python version 3.5.

**Comment by michhar** [comment]
This is now incorporated into a [PR](https://github.com/Microsoft/CNTK/pull/1883).  I'll close if/when the PR gets merged.

**Comment by KeDengMS** [comment]
Good suggestions, we have been working on changing import * from samples, and there are lots of changes in import cntk since rc2. The PR seems closed. Do you want to start a new one based on latest master?

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Please feel free to reopen this if needed. Thanks!
