### ISSUE TITLE
Feature request:  common vector math as transforms in CNTKTextFormatDeserializer

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1878]
Currently tensor math is implemented as part of the brainscript API. Maybe it makes sense to have some matrix functionality proper to readers as it was done with image transforms. Or alternatively, have reader access the tensor calcs API but run it on own thread.

**Comment by KeDengMS** [comment]
Python would give you more flexibility than BrainScript. You can build your own data reader and use a CNTK graph in it to do math transforms. Currently we have no plan to add new features to BrainScript.

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Feel free to reopen it if needed. Thanks!
