### ISSUE TITLE
CNTK ConvolutionTranspose2D Weight initialization error

### ISSUE THREAD

**Issue by zhijiewang1982** [Microsoft/CNTK#1879]
Based on the Python API for CNTK 2.0rc2 (https://www.cntk.ai/pythondocs/cntk.layers.layers.html?highlight=convolutiontranspose#cntk.layers.layers.ConvolutionTranspose2D), ConvolutionTranspose2D accepts an optional parameter "init" (scalar or NumPy array or cntk.initializer) which defines the initial value of weights W. I am trying to specify this parameter with a NumPy array and got an error "TypeError: in method 'random_initializer_with_rank', argument 1 of type 'CNTK::ParameterInitializer const &'.

I am using Anaconda with python 3.5 on Windows 7. Here's my dummy code line:

tpConv = cntk.layers.ConvolutionTranspose2D((4,4), 1, activation=cntk.layers.identity, init=np.ones((1,1,2,2),dtype=np.float32), strides=(2, 2), bias=False)

Anyone knows what my problem is? Thanks.

**Comment by cha-zhang** [comment]
Your kernel is 4x4 and you are initializing it with 2x2 numpy matrix?

**Comment by zhijiewang1982** [comment]
Thanks. Let me double check quickly.

**Comment by zhijiewang1982** [comment]
I just checked a different size numpy matrix, and it's the same error. I forgot whether that's an typo. I will double check.

tpConv = cntk.layers.ConvolutionTranspose2D((4,4), 1, activation=cntk.layers.identity, init=np.ones((1,1,4,4),dtype=np.float32), strides=(2, 2), bias=False)

**Comment by zhijiewang1982** [comment]
I double checked and it was a typo. You can just run that single line and I think you will see my error. 

tpConv = cntk.layers.ConvolutionTranspose2D((4,4), 1, activation=cntk.layers.identity, init=np.ones((1,1,4,4),dtype=np.float32), strides=(2, 2), bias=False)

**Comment by cha-zhang** [comment]
Here's the issue. Numpy initialization for weights only works if reduction_rank=0. Otherwise the weight matrix has an inferred dimension and can't be initialized. 

For ConvolutionTranspose2D, the case of reduction_rank=0 hasn't been implemented.

**Comment by zhijiewang1982** [comment]
Ok. Thanks a lot for your reply.
