### ISSUE TITLE
Some 404 in documenation because MIST is missed under Examples/Image

### ISSUE THREAD

**Issue by abokov** [Microsoft/CNTK#1882]
Hi folks
There's some minor bugs in docs (MIST isn't really exists under github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST) so we have some amount of 404 errors : please take a look onto doc https://github.com/Microsoft/CNTK/wiki/Tutorial2 
In sections "Putting it all Together" links are broken:
1)"The main configuration file, including the BrainScript"  |  https://github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST/Config/01_OneHidden_ndl_deprecated.cntk
2)"A few BrainScript functions" | https://github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST/Config/Shared.bs
3) "The main configuration file incl. network definition" | https://github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST/Config/02_Convolution_ndl_deprecated.cntk
4) "The shared functions" | https://github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST/Config/Shared.bs
5) "The main configuration file" | https://github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST/Config/03_ConvBatchNorm_ndl_deprecated.cntk
6)  "The shared functions" | https://github.com/Microsoft/CNTK/blob/master/Examples/Image/MNIST/Config/Shared.bs

Thanks

**Comment by wolfma61** [comment]
closing this, hope this got caught in the recent document update
