### ISSUE TITLE
A2_RunWithBSModel  Error in running subprocess  

### ISSUE THREAD

**Issue by UTTAM2311** [Microsoft/CNTK#1884]
Trying to run the A2_RunWithBSModel for the Grocery dataset .
Throwing an Exception .
     
          PARAMETERS: datasetName = Grocery
          PARAMETERS: cntk_nrRois = 2000
          cntk configFile=/home/uttam/projects/CNTK/Examples/Image/Detection/FastRCNN /proc/Grocery_2000/cntkFiles/fastrcnn.cntk currentDirectory=/home/uttam/projects/CNTK/Examples/Image/Detection/FastRCNN/proc/Grocery_2000/cntkFiles NumLabels=17 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=34000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=34000
         Traceback (most recent call last):
          File "A2_RunWithBSModel.py", line 60, in <module>
          run_fastrcnn_with_config_file()
         File "A2_RunWithBSModel.py", line 44, in run_fastrcnn_with_config_file
         pid = subprocess.Popen(cmdStr.split(" "), cwd=p.cntkFilesDir)
         File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
         restore_signals, start_new_session)
         File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
         raise child_exception_type(errno_num, err_msg)
         FileNotFoundError: [Errno 2] No such file or directory: 'cntk'

@ivrodr-msft  Not sure Why its happening can u help me out with this issue.

**Comment by ivrodr-msft** [comment]
Hi @UTTAM2311,
how did you install CNTK? the binary location should be included in your PATH.
(you can do that by e.g. export PATH=/home/username/cntkbin/cntk/bin:$PATH)

Let me know if it works. Thanks!
