### ISSUE TITLE
Failed to load a model trained in python from C++.

### ISSUE THREAD

**Issue by ivan-alles** [Microsoft/CNTK#1885]
I trained a model in python and save it. It is a very simple convnet classifier with 2 conv/maxpooling layers, 2 fully connected layers and a dropout. 

I'm trying to evaluate the model using the example CPPEvalClient. It fails in the call model->CreateNetwork(networkConfiguration). The error depends on the build configuration:
in Debug: "unmatched bracket found in parameters"
in Release: "unknown error".

I can run the original model from the C++ example (01_OneHidden) without problems. 

My environment:

Python (3.5): CNTK 2.0rc2, gpu (I tried to train and save the model both with try_set_default_device(cpu) and try_set_default_device(gpu(0)).

C++: Visual Studio 2013, CNTK 2.0rc2 cpu-only.

**Comment by zhouwangzw** [comment]
@ivan-alles The model trained with Python has to be evaluated with CNTKLibrary API, but not the EvalDll API. Please find detailed description of CNTK Eval [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview). CPPEvalClient is using the EvalDll API, so it can not deal with models trained with Python. Please [use CNTKLibrary C++ API ](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows#using-cntk-library-c-api-for-evaluation) to evaluate the Python model. You can find examples [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCPPEvalCPUOnlyExamples/EvalMultithreads.cpp#L135). 

You can also install appropriate [Nuget packages ](https://github.com/Microsoft/CNTK/wiki/NuGet-Package) to use CNTKLlibrary API. For C++, you need VS2015, as the pre-built libraries are built with VS2015.

**Comment by ivan-alles** [comment]
Is it possible/feasible to build and use CNTKLibrary API with VS2013? I need to migrate a big solution to VS2015 because of this.

**Comment by zhouwangzw** [comment]
@ivan-alles It should be possible to build CNTKLibrary API from source with VS2013. We were using VS2013 before upgrading to VS2015 a couple of months ago. But you might have to resolve some build issues.
