### ISSUE TITLE
NuGet error: package(s) missing

### ISSUE THREAD

**Issue by Brekel** [Microsoft/CNTK#1886]
Somehow when I try to compile any of the C++ (and C#) CNTK Eval Examples I always get the following error:

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.
For more information, see http://go.microsoft.com/fwlink/?LinkID=322105.
The missing file is ..\packages\CNTK.CPUOnly.2.0.0-rc2\build\native\CNTK.CPUOnly.targets.

I'm not all that familiar with NuGet to be honest but I have done this:
- make sure I'm using Visual Studio 2015 update 3
- manually run "Install-Package CNTK.CPUOnly -Pre" from the Package Manager Console as depicted on the NuGet link from the example documentation webpage
- confirmed that the mentioned file exists "packages\CNTK.CPUOnly.2.0.0-rc2\build\native\CNTK.CPUOnly.targets"
- confirm "CNTK.CPUOnly" v2.0.0-rc2 shows up with a green icon under "Manage Nuget Packages for Solution..."
- make sure "Allow Nuget to download missing packages" option is ON
- make sure "Automatically check for missing packages during build in Visual Studio" option is ON
- downloaded the Nuget commandline executable and ran "nuget restore" in my project folder which returns:
	MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
	All packages listed in packages.config are already installed.
- same thing with the C++ and C# examples, both CPU & GPU

Any ideas, probably something stupid I'm missing I suppose?

**Comment by Brekel** [comment]
Nevermind, turned out something stupid indeed :)

Initially I loaded the individual projects, just noticed there was a master solution in "CNTK-master\Examples\Evaluation" which does not have the NuGet issues.

EvalClients.sln works, however in the projects from CNTKLibraryEvalExamples.sln I get this error:
'Load': is not a member of 'CNTK::Function'

**Comment by zhouwangzw** [comment]
@Brekel We have two different versions of Eval API: EvalDll is the V1 API which only works with models trained with BrainScript, and CNTKLibrary API is the current V2 API which provides more ability and features. You can find details [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview). EvalClients.sln is examples for EvalDll V1 API, which needs Microsoft.Research.CNTK.CpuEval-mkl Nuget installed, and CNTKLibraryEvalExamples.sln is for CNTKLibrary V2 API, which needs CNTK.CPUOnly and CNTK.GPU nuget packages for CPU and GPU devices respectively. Description about Nuget packages is in [this page](https://github.com/Microsoft/CNTK/wiki/NuGet-Package).

Can you run sample projects included in the CNTKLibraryEvalExamples.sln? 

Thanks,

**Comment by Brekel** [comment]
Thanks for getting back so quickly with usefull information!
I had not seen that page in the documentation.


When trying to compile CNTKLibraryEvalExamples, I unfortunately get these errors:

For C++ CPU:

1>------ Rebuild All started: Project: CNTKLibraryCPPEvalCPUOnlyExamples, Configuration: Debug x64 ------
1>  CNTKLibraryCPPEvalCPUOnlyExamples.cpp
1>  EvalMultithreads.cpp
1>EvalMultithreads.cpp(138): error C2039: 'Load': is not a member of 'CNTK::Function'
1>  C:\code\CNTK\CNTK-master\Examples\Evaluation\packages\CNTK.CPUOnly.2.0.0-rc2\build\native\include\CNTKLibrary.h(2834): note: see declaration of 'CNTK::Function'
1>EvalMultithreads.cpp(138): error C3861: 'Load': identifier not found
1>EvalMultithreads.cpp(147): error C2227: left of '->Clone' must point to class/struct/union/generic type
1>  EvalMultithreads.cpp(147): note: type is 'unknown-type'


For C++ GPU:

1>------ Rebuild All started: Project: CNTKLibraryCPPEvalGPUExamples, Configuration: Debug x64 ------
1>  EvalMultithreads.cpp
1>  CNTKLibraryCPPEvalGPUExamples.cpp
1>..\CNTKLibraryCPPEvalCPUOnlyExamples\EvalMultithreads.cpp(138): error C2039: 'Load': is not a member of 'CNTK::Function'
1>  C:\code\CNTK\CNTK-master\Examples\Evaluation\packages\CNTK.GPU.2.0.0-rc2\build\native\include\CNTKLibrary.h(2834): note: see declaration of 'CNTK::Function'
1>..\CNTKLibraryCPPEvalCPUOnlyExamples\EvalMultithreads.cpp(138): error C3861: 'Load': identifier not found
1>..\CNTKLibraryCPPEvalCPUOnlyExamples\EvalMultithreads.cpp(147): error C2227: left of '->Clone' must point to class/struct/union/generic type
1>  ..\CNTKLibraryCPPEvalCPUOnlyExamples\EvalMultithreads.cpp(147): note: type is 'unknown-type'
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========


(similar errors for the C# versions btw)

**Comment by zhouwangzw** [comment]
Are you using the code from master? The code master might contain changes that are newer than Nuget Package 2.0.0RC2. Could you please try examples from the binary release package https://github.com/Microsoft/CNTK/releases?

**Comment by Brekel** [comment]
Ah you're right, I was using the master, the release seems to compile without any issues.
Sorry for the n00b questions, but awesome to see such an active and helpful community here!!
