### ISSUE TITLE
ImportError: No module named 'cntk._cntk_py'

### ISSUE THREAD

**Issue by tacarllo** [Microsoft/CNTK#1887]
Hi, 

After following the set up instructions (https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Python),  I tried: 
(cntk-py35) D:\> python -c "import cntk; print(cntk.__version__)"

as a quick test that the installation succeeded but I got this error:

 

Traceback (most recent call last):
  File "D:\src\cntk\bindings\python\cntk\cntk_py.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Anaconda3\envs\cntk-py35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\src\cntk\bindings\python\cntk\__init__.py", line 11, in <module>
    from . import ops
  File "D:\src\cntk\bindings\python\cntk\ops\__init__.py", line 7, in <module>
    from . import sequence
  File "D:\src\cntk\bindings\python\cntk\ops\sequence\__init__.py", line 6, in <module>
    from ...utils import sanitize_input, sanitize_shape, get_data_type, typemap
  File "D:\src\cntk\bindings\python\cntk\utils\__init__.py", line 11, in <module>
    from .. import cntk_py
  File "D:\src\cntk\bindings\python\cntk\cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "D:\src\cntk\bindings\python\cntk\cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "D:\Anaconda3\envs\cntk-py35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : D:\Anaconda3  (writable)
  default environment : D:\Anaconda3\envs\cntk-py35
     envs directories : D:\Anaconda3\envs
        package cache : D:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

PYTHONPATH=D:\src\cntk\bindings\python;

I have seen other issues like mine but none of the solutions have been succeed in my case. 

Can anyone help me with this issue?

Thanks & regards

**Comment by gsrungarapu** [comment]
I did face similar issues. Most of them are related to incorrect PATH. 
I followed the below Script-driven installation steps which actually does it all for you. (steps mentioned in the below link)

They are just 2 scripts to run(*run with proper privileges)
1.  install.bat  (located in installation <CNTK-2-0-rc2\cntk>\cntk\Scripts\install\windows)
2. cntkpy35.bat (located in CNTK-2-0-rc2\scripts)

https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Binary-Script

**Comment by tacarllo** [comment]
HI @gsrungarapu, 

Thanks for your reply.
I have already tried that as well and I got the same error. I've tried adding to the environment variable the paths I found here and there that would be needed but no success so far.
Can anyone list all the paths that have to be included in the system variable "PATH" and in "PYTHONPATH"?
Does anyone have another guess of what could be happening?

Thanks,

**Comment by ant0nsc** [comment]
I had a similar problem when setting up the Python bindings for a local build directly from source. What worked for me was:

- Build CNTK in Release mode
- Ensure that `PATH` points to your CNTK executable in Release mode, I think for you that would be `d:\src\CNTK\x64\Release`
- Ensure that `PYTHONPATH` points to `d:\src\cntk\binding\python`
- Then refresh the Python environment by running `conda env update --file d:\src\CNTK\Scripts\install\windows\conda-windows-cntk-py35-environment.yml`

After those steps, running `python -c "import cntk"` succeeded.

**Comment by tacarllo** [comment]
Hi both, 

Thanks for your replies. 
I have solved the issue by deleting cntk\bindings\Python from the variable PYTHONPATH and setting it to Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Lib\site-packages

Regards,

**Comment by ChongWu-Biostat** [comment]
I think this does not work.

**Comment by boltomli** [comment]
The official docker image is bad as well.

**Comment by wesyao** [comment]
@boltomli @KeDengMS 
here is a work around until they push out a new image:
1) go here and install [Python wheels](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-python?tabs=cntkpy22#quick-installation-test). If you're using it in a container with Ubuntu 14, apt-get won't work for the prerequisite
2) Remove cntk build files (or rename)
```bash
mv /cntk/cntk/lib /cntk/cntk/lib-old
```
3) pip install --upgrade <cpu only wheels>
