### ISSUE TITLE
scale jitter via python causing syntax error

### ISSUE THREAD

**Issue by achhibbar** [Microsoft/CNTK#1891]
I am trying to create an image transform that features both side and aspect ratio jitter with the following code. 

`transforms = []`
    `transforms += [xforms.crop(crop_type='randomside', side_ratio=0.45:1.0,aspect_ratio=0.75:1.0, jitter_type='uniratio')]`
    `transforms += [xforms.scale(width=image_width, height=image_height, channels=num_channels, interpolations='linear')] `

I am modifying the TransferLearning.py example.
The transform is something I have previously done using brainscript, but doesn't seem to be working in python. I get syntax errors. Removing the colon delimited values and just using a single value works fine. I've also changed 0.45:1.0 to '0.45:1.0' which I had seen in a VGG python example, but this didn't work either.
*I meant crop jitter in the title

**Comment by ebarsoumMS** [comment]
It is a bug, thank you for reporting it.

**Comment by achhibbar** [comment]
Thanks for the response.

Is there a way to get around this in the meantime? I would like to replicate the transforms I have used extensively in brainscript via the python API.
Also what is the best way for me to track when this issue is addressed?

**Comment by ebarsoumMS** [comment]
This issue is fixed already, please use tuple instead of colon for python API,
