### ISSUE TITLE
CNTK convolution_transpose consumes  way more memory than Tensorflow

### ISSUE THREAD

**Issue by zhijiewang1982** [Microsoft/CNTK#1892]
I am using the "convolution_transpose" operator to upsample a downsampled image. I observed huge amount of memory consumption compared to my Tensorflow implementation. The followings are my test code. I have a dummy image with 15 channels and 500x200 size. I downsampled it by applying a (16x16) strides maxpooling operation, and then upsampled it back to original size by applying a (16x16) strides convolution_transpose operation. In my actual code I used a properly computed bilinear_upsample kernel, but here I am using a dummy kernel with the same size only for memory testing purpose. In this test, the following CNTK code consumed about 5G memory, but the same function I implemented with Tensorflow used definitely less than 1G memory. Can anybody confirms whether this is a problem with CNTK convolution_transpose operation or a problem of my implementation? Thanks. 

img = np.ones((15,500,200), dtype = np.float32)
x = cntk.ops.input(img.shape)
xpool = cntk.layers.MaxPooling((16,16), (16,16))(x)
upsampleFilter = np.ones((15,15,32,32),dtype = np.float32)
kernel = cntk.ops.constant(value = upsampleFilter)
upsampleResult = cntk.ops.convolution_transpose(kernel, xpool, strides=(1,16,16))
upsampleResult.eval({x : [img]})

**Comment by cha-zhang** [comment]
I tested your code on my machine and it consumes about 200MB.

**Comment by zhijiewang1982** [comment]
Really? What is your environment? I am using Anaconda with python 3.5 on Windows 7.

**Comment by zhijiewang1982** [comment]
I will try different environment.

**Comment by cha-zhang** [comment]
I'm using Anaconda with Python 3.5 on Win 10.

**Comment by zhijiewang1982** [comment]
I tested it in Windows Server 2008, and memory usage is still 5G. I will test it on Windows 10 now.

**Comment by zhijiewang1982** [comment]
I tested it in Windows 10 and still get a memory usage 5G. I am using CNTK 2.0 RC2. Are you using the same version CNTK?

**Comment by zhijiewang1982** [comment]
I retried on Windows 7 by following the cntk python setup tutorial page https://github.com/Microsoft/CNTK/wiki/Setup-Windows-Python. 

The followings are what I did:
(1) I created a new python 3.5 environment by running "conda create --name cntk-py35 python=3.5 numpy scipy h5py jupyter".
(2) activate cntk-py35
(3) pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0rc2-cp35-cp35m-win_amd64.whl
(4) run "Python"
(5) In Python, I ran the following lines and the memory quickly increased 5G.
import numpy as np
import cntk
img = np.ones((15,500,200), dtype = np.float32)
x = cntk.ops.input(img.shape)
xpool = cntk.layers.MaxPooling((16,16), (16,16))(x)
upsampleFilter = np.ones((15,15,32,32),dtype = np.float32)
kernel = cntk.ops.constant(value = upsampleFilter)
upsampleResult = cntk.ops.convolution_transpose(kernel, xpool, strides=(1,16,16))
upsampleResult.eval({x : [img]})

For your information, I even tried python 3.6. The same memory usage issue. Could you please try and see whether you can reproduce my issue on either Windows 7 or Windows 10 machine? If you don't see it, I really would like to know your setup steps. Thanks a lot.

**Comment by cha-zhang** [comment]
Oh, I was checking the GPU memory rather than CPU memory. I'll check it again tomorrow about CPU version.

**Comment by zhijiewang1982** [comment]
Hi Cha, for your further information. I did try to install the GPU version and the GPU memory did only increase about 200M as you said. However, in the CPU version case, the CPU memory increased about 5G in my Anaconda 3  4.3.1 + python 3.6 environment.

**Comment by cha-zhang** [comment]
CNTK's CPU implementation of convolution uses unwrapping, thus the amount of memory required is related to the filter size. In your case the filter is (15,15,32,32), which is unusually large. 

We will be migrating the CPU convolution to MKL-DNN in the near future. That should address your problem.

**Comment by zhijiewang1982** [comment]
For your information, I tried the CNTK.CPUOnly v2.0.0-rc3 Nuget package in Visual Studio, and the C++ API   behaves with the same problem when I evaluate the model pre-trained using python GPU version.

**Comment by zhijiewang1982** [comment]
Do you have a rough idea when this problem will be solved?

**Comment by cha-zhang** [comment]
Actually Intel is helping us integrate MKL-DNN to CNTK, and we are waiting for them. Not ETA yet but my estimate is about 1 month, at most 2 months.

**Comment by zhijiewang1982** [comment]
Ok, thanks.

**Comment by zhijiewang1982** [comment]
Then I will close it now.

**Comment by zhijiewang1982** [comment]
Has this problem been solved yet? I tried the latest CNTK release 2.0, apparently the cpu version still suffers from the the same problem. This problem is really critical for me, because not everybody uses my code will have access to GPU. Therefore, any update on this problem is really appreciated.

**Comment by cha-zhang** [comment]
The MKL integrate went slower than I expected mostly because the person working at Intel is not familiar with CNTK enough. We will try to get this in as soon as possible.

**Comment by zhijiewang1982** [comment]
Thanks a lot. What's the best way for me to get informed if this happens?

**Comment by cha-zhang** [comment]
I’ll keep you updated. If needed, you can always ping me directly view email chazhang@microsoft.com<mailto:chazhang@microsoft.com>.

**Comment by zhijiewang1982** [comment]
It will be really appreciated if you can keep me updated. Thanks again.

**Comment by nietras** [comment]
I have been observing some rather large memory usage in `CPU` mode as well, as this issue been resolved. I am running CNTK 2.5.1 via managed API. E.g. memory usage was 4GB for a network of ~120000 parameters with input size of 160 x 80 x 3 and batch size of 64. That's very little. Probably ~100MB for parameters. Yet, it consumes 4GB ?

**Comment by zhijiewang1982** [comment]
I don't think this problem is solved. I could be wrong, because I just used
GPU and never checked CPU version since I posted this issue. I hope CNTK
can solve this problem, but sadly I don't think they consider it as a
priority.
