### ISSUE TITLE
CNTK on Hololens?

### ISSUE THREAD

**Issue by ncullen93** [Microsoft/CNTK#1898]
Does anyone know if CNTK would work on the HoloLens, at least for evaluation? What is the best way to go about this? Thanks!

**Comment by zhouwangzw** [comment]
We have not tried to run Evaluation on HoloLens yet. We are very appreciated for community contribution.
Thanks,

**Comment by JimSEOW** [comment]
@ncullen93 Hololens is running 32bit Windows 10 and the official C# support is Unity3D. Others have done it through SharpDX.

Please follow the [discussion here on .NET Deep Learning ](https://github.com/Microsoft/CNTK/issues/960#issuecomment-313934734)on how CNTK is being used for Unity3D (hence HoloLens)
