### ISSUE TITLE
Resnet20.dnn

### ISSUE THREAD

**Issue by amarkatti** [Microsoft/CNTK#1899]
I am trying to run cognitive toolkit example in visual studio but system throws an error saying that resnet20.dnn does not exists. How and from where do I get this file?

**Comment by cha-zhang** [comment]
With resnet20 I assume this is for CIFAR10 size (32x32)? You could train it yourself (takes less than an hour on a reasonable GPU) with: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10.py

**Comment by phamquanghung263** [comment]
Hi, I train it for my self (both BS and Python). In Model folder i found the files name resnet20_1.dnn, resnet20_2.dnn.... , but no resnet20.dnn file
So, what i'm doing wrong? Please help.

**Comment by cha-zhang** [comment]
The last stored model is the one you want. You can rename it to resnet20.dnn if needed.

**Comment by phamquanghung263** [comment]
Thank you, it worked.

**Comment by helloguo** [comment]
One quick question: I downloaded the pre-trained model from here https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md#resnet. The downloaded file  is `ResNet20_CIFAR10_CNTK.model`. Does this mean I just need to rename it to `resnet20.dnn`? Or how do I open `ResNet20_CIFAR10_CNTK.model`?

**Comment by musicrainie** [comment]
Either renaming the downloaded **ResNet20_CIFAR10_CNTK.model** to **resnet20.dnn** or changing **const wchar_t* resnet20Model = L"resnet20.dnn";** to **const wchar_t* resnet20Model = L"ResNet20_CIFAR10_CNTK.model";** is ok. Just for anyone who may still be confused.
