### ISSUE TITLE
Dropout issue

### ISSUE THREAD

**Issue by mirco86** [Microsoft/CNTK#190]
Hi,
I'm trying to train with dropout a DNN of 6 sigmoid-based hidden units for speech recognition purposes. 
I'm using the following command:

`$cn_gpu configFile=${expdir}/Base.config configFile=${expdir}/CNTK2_new_lrkaldi_dropout.config DeviceNumber=0 action=TrainDNN ndlfile=$ndlfile`

The config file contains the following SGD lines:

```
    SGD=[
        epochSize=0         
        minibatchSize=256
        #learningRatesPerMB=0.1:1
        learningRatesPerSample=0.008
        #momentumPerMB=0:0.9
        momentumPerSample=0
        dropoutRate=0.5
        maxEpochs=20
        numMBsToShowResult=100
    

        #settings for Auto Adjust Learning Rate
        AutoAdjust=[
            reduceLearnRateIfImproveLessThan=0.01
            loadBestModel=true
            increaseLearnRateIfImproveMoreThan=1000000000
            learnRateDecreaseFactor=0.5
            autoAdjustLR=AdjustAfterEpoch
            learnRateAdjustInterval=1
        ]
```
The training finished without errors. However, the speech recognition results when dropoutRate=0.0, dropoutRate=0.5, dropoutRate=0.5*10:0.2 are exactly the same (also the DNNs are exactly the same). It seems the dropout parameter is completely neglected. 

Am I doing something wrong somewhere?

Mirco

**Comment by Alexey-Kamenev** [comment]
Hello,
Do you see a different results (accuracy) in the logs when you use different dropout values?

**Comment by mirco86** [comment]
Yes, all is exactly the same.
I tried to change other parameters (e.g., momentum) and, as expected, I
have different results for different momentum. For dropout something silly
happens

Mirco

**Comment by frankseide** [comment]
Do you see this log message:

        fprintf(stderr, "Switching dropout rate to %.8g.\n", dropoutRate);

**Comment by frankseide** [comment]
and possibly this warning:

            fprintf(stderr, "WARNING: there is no dropout node.\n");

**Comment by mirco86** [comment]
Thank you guys!


The problem is actually "WARNING: there is no dropout node.".

To enable dropout I simply add "dropoutRate=0.5" inside the SGD of the
config file.

Should I do something else in the .ndl file?



Mirco

**Comment by dongyu888** [comment]
If you are using NDL, you can add dropout operation to any node on which you want to apply dropout. For example, if you have something like

 

Layer1=MacroOrFunctionName(some parameters)

Layer2= AnotherMacroOrFunctionName (layer1, some other parameters)

 

You can apply dropout to just Layer1 by doing

 

Layer1=MacroOrFunctionName(some parameters)

Layer1DO = DropOut(Layer1)

Layer2= AnotherMacroOrFunctionName (layer1DO, some other parameters)

 

Similarly, you can add dropout to any nodes as you want or include it as part of the macro so eveytime the macro is called it is used. This allows for finer control of dropout. In the default macro file we already have several macros that uses dropout.

 

Thanks,

 

Dong Yu (俞栋)

**Comment by mirco86** [comment]
Thank you,
now the use of DropOut is much more clear.
I will try it as soon as possible!

Mirco

**Comment by wolfma61** [comment]
closing ....
