### ISSUE TITLE
The parallel training :epochTime  

### ISSUE THREAD

**Issue by Sampson1107** [Microsoft/CNTK#1903]
1、When I training CNTK Alexnet model with val1024 dataset, I found that running serial one like this：
cntk configFile=AlexNet_ImageNet.cntk 
I will get the result of about 600 images per second.
2、While I run the cntk with parallel one such as:
mpiexec  -np 1 cntk  configFile=AlexNet_ImageNet.cntk  stderr=Models/log  parallelTrain=true
I will get the result of about 180 images per second.
3、When I run the model with six GPUs：
mpiexec   -np 6 cntk  configFile=AlexNet_ImageNet.cntk6  stderr=Models/log  parallelTrain=true
I get the log like this:
Finished Epoch[ 3 of 20]: [Training] ce = 6.90484852 * 1024; errs = 99.707% * 1024; totalSamplesSeen = 3072; learningRatePerSample = 0.00013020834; epochTime=1.4305s
Is the epochTime  the cost of all GPUs or One GPU?
How can I get the number of the training images per second? Is it 1024/1.4305 or 1024/1.4305*6?
     
If I want to training the Imagenet1K dataset,  how to convert the dataset to the format inputs of CNTK? I want to get the files of train_map.txt and val_map.txt.

**Comment by KeDengMS** [comment]
I got similar speed with or without parallelTrain with train_map.txt. Please check your data and run with [profilerEnabled=true](https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-and-python-performance-profiler) to further investigate performance issues.
As for ImageNet1K dataset, CNTK can read standard image formats like jpg/png, no conversion is needed.

**Comment by cha-zhang** [comment]
No response in 3 weeks, and I'm closing this issue. Feel free to reopen it if needed. Thanks!
