### ISSUE TITLE
Error while running A2_RunWithPyModel.py

### ISSUE THREAD

**Issue by yashfujifilm** [Microsoft/CNTK#1904]
I get the following error while running the code

(py35) C:\repos\cntk\Examples\Image\Detection\FastRCNN>python A2_RunWithPyModel.py
Traceback (most recent call last):
  File "A2_RunWithPyModel.py", line 13, in <module>
    from cntk.layers import placeholder, Constant
ImportError: cannot import name 'placeholder'

**Comment by fct-edilberto** [comment]
try to install or update last version CNTK in pip:
[https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python)

**Comment by yashfujifilm** [comment]
Did it, works fine. Thanks.

**Comment by abilash-c** [comment]
I upgraded to the latest version of CNTK using pip. The error still persists.
