### ISSUE TITLE
Error while running A2_RunCntk_py3.py

### ISSUE THREAD

**Issue by yashfujifilm** [Microsoft/CNTK#1906]
(cntk-py35) C:\repos\CNTK-Samples-2-0rc1\Examples\Image\Detection\FastRCNN>pytho
n A2_RunCntk_py3.py
--------------------------------------------------------------
2017-05-23 17:18:12
PARAMETERS: datasetName = Grocery
PARAMETERS: cntk_nrRois = 100
-------------------------------------------------------------------
Build info:

                Built time: Apr  3 2017 00:16:53
                Last modified date: Mon Apr  3 00:08:19 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8
.0
                CUB_PATH: c:\local\cub-1.4.1
                CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v5.1
                Build Branch: HEAD
                Build SHA1: 7661e81777360d3222a26dcb969973ce1d4c513f
                Built by svcphil on DPHAIM-25
                Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTKv
2LibraryDll\
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
Training Fast R-CNN model for 20 epochs.
Training 54603793 parameters in 6 parameter tensors.
CUDA failure 2: out of memory ; GPU=0 ; hostname=IW-LOG-HOST ; expr=cudaMalloc((
void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
Traceback (most recent call last):
  File "A2_RunCntk_py3.py", line 212, in <module>
    trained_model = train_fast_rcnn()
  File "A2_RunCntk_py3.py", line 168, in train_fast_rcnn
    trainer.train_minibatch(data)                                    # update mo
del with it
  File "C:\Users\i\Anaconda3\envs\cntk-py35\lib\site-packages\cntk\train\trainer
.py", line 167, in train_minibatch
    arguments, device)
  File "C:\Users\i\Anaconda3\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py",
line 2248, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *ar
gs)
RuntimeError: CUDA failure 2: out of memory ; GPU=0 ; hostname=IW-LOG-HOST ; exp
r=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize
    - Microsoft::MSR::CNTK::Matrix<float>::  Resize
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch
    - CNTK::Trainer::  TrainMinibatch
    - PyInit__cntk_py
    - PyInit__cntk_py
    - PyCFunction_Call

cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): out of memory (cuda e
rror 2)
cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): out of memory (cuda e
rror 2)

**Comment by cha-zhang** [comment]
Which pre-trained model you are using and how much GPU memory do you have?

**Comment by DHOFM** [comment]
To me it looks like a small Graphics Card, because the error message says out of memory. Which card do you use `? You can try to train cpu - only, instead

**Comment by yashfujifilm** [comment]
I had no GPU, so it was giving error. Got GPU machine then tried it. Works fine.
