### ISSUE TITLE
I need help in training my own data.

### ISSUE THREAD

**Issue by yashfujifilm** [Microsoft/CNTK#1909]
I am getting the following error after running the code. 
My file structure is Datasets/Baseball/positive , /negative, /testImages

![2](https://cloud.githubusercontent.com/assets/28887079/26385089/201b87aa-4078-11e7-87ca-deae2c887af1.png)

**What is running wrong in my code?**
I run these two codes C1_DrawBboxesOnImages.py & C2_AssignLabelsToBboxes.py on postive images. I made the respective changes in my PARAMETERS.py 

**datasetName = "Baseball"**

**elif datasetName.startswith("Baseball"):
    
    classes = ('__background__',  # always index 0
               'gloves','bat','ball','leg-guard', 'chest-guard','helmet','cap')

    # roi generation
    roi_minDimRel = 0.04
    roi_maxDimRel = 0.4
    roi_minNrPixelsRel = 2    * roi_minDimRel * roi_minDimRel
    roi_maxNrPixelsRel = 0.33 * roi_maxDimRel * roi_maxDimRel

    # model training / scoring
    classifier = 'nn'
    cntk_num_train_images = 25
    cntk_num_test_images = 5
    cntk_mb_size = 5
    cntk_max_epochs = 20
    cntk_momentum_time_constant = 10

    # postprocessing
    nmsThreshold = 0.01

    # database
    imdbs = dict()      # database provider of images and image annotations
    for image_set in ["train", "test"]:
        imdbs[image_set] = imdb_data(image_set, classes, cntk_nrRois, imgDir, roiDir, cntkFilesDir, boAddGroundTruthRois = (image_set!='test'))**

(cntk-py35) C:\repos\CNTK-Samples-2-0rc1\Examples\Image\Detection\FastRCNN>pytho
n  A3_ParseAndEvaluateOutput.py
--------------------------------------------------------------
2017-05-24 11:51:41
PARAMETERS: datasetName = Baseball
PARAMETERS: cntk_nrRois = 100
Parsing CNTK output for image set: test
Parsing cntk output file, image 0 of 10
Traceback (most recent call last):
  File "A3_ParseAndEvaluateOutput.py", line 35, in <module>
    saveCompressed = True, skipCheck = True)
  File "C:\repos\CNTK-Samples-2-0rc1\Examples\Image\Detection\FastRCNN\cntk_help
ers.py", line 224, in parseCntkOutput
    assert len(values) == cntkNrRois * outputDim, "ERROR: expected dimension of
{} but found {}".format(cntkNrRois * outputDim, len(values))
AssertionError: ERROR: expected dimension of 800 but found 1700

**Comment by cha-zhang** [comment]
We need a bit more information to track the issue. Would you mind share a small repro with data? Thanks!

**Comment by BenjaminAkera** [comment]
This issue is resolved by:
First removing the Model file from FastRCN/output
then run A2_RunWithPyModel.py again
And then Run A3_ParseAndEvaluateOutput.py 

Hope this fixes your issue.
