### ISSUE TITLE
Inaccuracy in CNTK book (page 14 )

### ISSUE THREAD

**Issue by vmswork** [Microsoft/CNTK#191]
Hi,

There is a paragraph on the page 14 in [CNTK-book](http://research.microsoft.com/pubs/226641/CNTKBook-20160217..pdf) which states 

> Output: The TIMIT data is labeled with 61 different phonemes, and the network
is trained to recognize tri-phones. Thus there are 61x3=183 output nodes.

Obviously, network is actually trained  to discriminate phone states. There are 3 states per phone, so 183 output nodes.  
There are 61 to the power of 3 tri-phones and that is a much larger number than 183.

Regards,
Valentin

**Comment by dongyu888** [comment]
Good catch!

 

Thanks,
