### ISSUE TITLE
Using CNTK for simple optimization tasks

### ISSUE THREAD

**Issue by kokostek** [Microsoft/CNTK#1910]
Lets say I wanna find the extremum of gaussian function using CNTK. I know there is more suitable tools for that, like scipy.optimize in Python, or NLopt for C/C++, but still...

Here is the code sample:
``` python
import cntk as C
x = C.parameter(shape=(), init=1.0, dtype='float32')
f = C.exp(-C.square(x))  # f(x) = e**{-x**2}

lr = C.learning_rate_schedule(0.1, C.UnitType.minibatch)
learner = C.sgd(f.parameters, lr)
trainer = C.Trainer(f, [-f], [learner])

print(trainer.train_minibatch({}))
print(x.value)
```
It outputs this:
```
False
1.0
```

It seems like the problem is empty arguments list in `trainer.train_minibatch({})` call. There is a workaround: adding some inputs to the model:
``` python
import cntk as C
x = C.parameter(shape=(), init=1.0, dtype='float32')
s = C.input(shape=(), dtype='float32')
f = C.exp(-C.square(x/s) * 0.5)  # f(x) = e**{-x**2/s**2/2}

lr = C.learning_rate_schedule(0.1, C.UnitType.minibatch)
learner = C.sgd(f.parameters, lr)
trainer = C.Trainer(f, [-f], [learner])

print(trainer.train_minibatch({s: array(1.0, dtype='float32')}))
print(x.value)
```
Now the output is:
```
True
0.9393469095230103
```
which indicates that optimization step was successful.

I cant find any examples or tutorial on simple optimization task, even thought it seems clearly to me that CNTK can do it. Maybe I'm not using it right?

**Comment by tobyclh** [comment]
Hello, what exactly is your problem right now if it works?

**Comment by Ark-kun** [comment]
`train_minibatch` performs 1 iteration. To do more iterations either use it in a python loop or use a training session.

**Comment by kokostek** [comment]
@Ark-kun The question isn't about a loop, it's about why `train_minibatch` needs non-empty arguments, when model does not have any inputs.

**Comment by KeDengMS** [comment]
Empty input has special meaning in CNTK in distributed training, as some node may have empty inputs towards end of the training while other nodes have valid inputs. I believe your workaround is the right way to go.

**Comment by cha-zhang** [comment]
It seems this issue has been resolved. Will close this issue. Feel free to reopen if needed.
