### ISSUE TITLE
REQUEST: Python tutorials for Faster RCNN and YOLO

### ISSUE THREAD

**Issue by Arvinds-ds** [Microsoft/CNTK#1916]
Hi,

I am greatly impressed by quality of your tutorials. Could you point me to or add tutorials on implementing Faster RCNN/ YOLO with CNTK using Python. I notice a Fast RCNN code in brain script but I am new to CNTK and would want to learn the python bindings.

**Comment by cha-zhang** [comment]
In the FastRCNN example (https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN), if you run A2_RunWithPyModel.py, you will be using the Python bindings to perform the task. 

We are working on FasterRCNN and Yolo v2. Some components are ready and checked into master, e.g., 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/utils 

Full FasterRCNN pipeline should be ready in a month or so. Thanks!

**Comment by Arvinds-ds** [comment]
Thank you

**Comment by itsayush** [comment]
@cha-zhang Looking forward to getting the YOLO implementation.

**Comment by DHOFM** [comment]
@cha-zhang Will there be support for Faster R CNN in the official repo soon - or is it "safe" to use the tools here: https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/utils In my case for object detection with faster r cnn intead of selective search ROI Finding
