### ISSUE TITLE
CNTK Docker - Run cntk - libnvidia-ml.so.1 error

### ISSUE THREAD

**Issue by AlexDag** [Microsoft/CNTK#1917]
hi,
I  downloaded CNTK Docker image, inside docker container I downloaded github CNTK project, 
run HelloWorld-LogisticRegression and show >
` cntk: error while loading shared libraries: libnvidia-ml.so.1: cannot open shared object file: No such file or directory`
Are there some options to stop the use GPU?
thanks

**Comment by wilderrodrigues** [comment]
I have the same issue. I'm running on Docker, in a MacBook.

![image](https://cloud.githubusercontent.com/assets/5129209/26720690/83b1dcde-4789-11e7-8b7d-5bcd00a77621.png)

**Comment by wilderrodrigues** [comment]
I was using Beta 15... changed for the release version and and will check it out again.

```
https://hub.docker.com/r/microsoft/cntk/

2.0-cpu-python2.7 (/ubuntu-14.04/version_2/cpu/runtime/python-2/Dockerfile)
```

**Comment by wilderrodrigues** [comment]
Okay, it is not longer an issue for me.

**Comment by KeDengMS** [comment]
This error comes from missing NVIDIA libraries in your docker container. Please use NVidia-docker to run the container, and verify GPU works in container by running nvidia-smi first.

**Comment by hellosaumil** [comment]
I also ran into this error. I followed docker installation for Mac with `cntk:2.2-cpu-python2.7`, but when I run `import cntk` I get the following errors.

Err 1 : `ImportError: No module named 'cntk._cntk_py'`

Err 2 : `ImportError: libnvidia-Machine Learning.so.1: cannot open shared object file: No such file or directory`

Issue should be **Re-Opened**!!!

**Comment by KeDengMS** [comment]
If you are running GPU docker image, please use [NVidia-docker](https://github.com/NVIDIA/nvidia-docker). For CPU docker image, currently there is a known issue with the built-in python wheel. Please install the [CPU-Only Python wheels](https://github.com/NVIDIA/nvidia-docker) using pip install --upgrade. This bug would be fixed in next release.

**Comment by hellosaumil** [comment]
Yeah, I noticed that it had done issues in the wheel itself. Even though I downloaded the CPU container for Python 2.7 the environment created said py35...

Hence, upgrading to python 3.5 wheel solved the issue!

**Comment by hellosaumil** [comment]
There is one problem that I'm encountering. When do the above procedure in shell inside docker container...It works as long it is `Running`. But as soon as I `Stop/Restart` the container the information is lost and I have to repeat this process.

**Comment by KeDengMS** [comment]
Can you use 'docker ps -a' to find previously stopped container, and 'docker start <container name>' to start it, instead of 'docker run'. Then you should not need to repeat the fix.

**Comment by hellosaumil** [comment]
@KeDengMS I'm actually using Kitematic to Start or Stop Container...but I'll check this out and respond whether it retains the state.

**Comment by hellosaumil** [comment]
@KeDengMS Docker Start/Stop works instead of running/restarting from KinteMatic Docker App on macOS. Thanks! 👍

**Comment by hellosaumil** [comment]
@KeDengMS There is one more issue after this fix. 

I was able to run cant perfectly in Python Interpreter or even in Jupyter Notebook.

But when I tried to create Brainscript using command `cntk configFile=01_OneHidden_ndl_deprecated.cntk` from [CNTK usage overview](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-usage-overview)...

OR 

Just write `cntk` in bash of the docker container.

I ran into the same error as before:
`cntk: error while loading shared libraries: libnvidia-ml.so.1: cannot open shared object file: No such file or directory`

**Comment by hellosaumil** [comment]
Updating to CNTK v2.3 resolved this issue.

@KeDengMS @AlexDag You can close this issue now! 👍

**Comment by cameronblandford** [comment]
When I try to `mv /cntk/cntk/lib /cntk/cntk/lib-old` inside the container, my entire Docker instance freezes up, and any attempts to `docker ps` hang indefinitely until i restart Docker in its entirety. I'm still having this problem with the newest version of CNTK and `microsoft/cntk:latest`
