### ISSUE TITLE
Dumping intermediate layers feature maps

### ISSUE THREAD

**Issue by anijain2305** [Microsoft/CNTK#1918]
Hi,

I am a new user of CNTK. I need to dump the intermediate feature maps for all the layers in the network to perform data analysis like sparsity etc. Is there a quick way of doing this? 

Note that this is not just checkpoints. It is weights, bias along with intermediate feature maps like output of a convolution layer.

**Comment by cha-zhang** [comment]
Have you checked the feature extraction example? 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/FeatureExtraction

**Comment by anijain2305** [comment]
@cha-zhang Thanks for pointing to the example. 

The example you pointed out is for inference. I am looking for something like train_and_write. 

I will start looking from the example you pointed out, hopefully the changes should be easy. However, if you have similar example for training as well, that will be very useful.

**Comment by cha-zhang** [comment]
You can save the model during training, and then perform data analysis on that. If the training process need to be modified based on your analysis, I believe it's also doable.

**Comment by anijain2305** [comment]
Hi, Sorry I got busy with something else. 

So, when you say "save the model" during training, do you mean saving weights and biases OR do you mean intermediate layer outputs as well? 

To be concrete, I want to check how does the sparsity of each layer output changes while training. Different epochs will result in different sparsity for the same layer and same minbatch. I need a way to dump the output of each layer say at the end of 100 mini batches in a file.

**Comment by cha-zhang** [comment]
You save the model, and feed your data through the saved models via eval dll and record their sparsity. That should be very doable.

**Comment by anijain2305** [comment]
@cha-zhang I see. Yes, this will be helpful. 

For now, I needed higher control over the nodes to control how training is done. Therefore, I started looking into source code base and found the relevant code at ComputationNode.h. I will build it up from there.
