### ISSUE TITLE
Training and Evaluate simplified API

### ISSUE THREAD

**Issue by Arvinds-ds** [Microsoft/CNTK#1922]
I am new to CNTK. While model creation is a breeze, there seems to be a lot of boilerplate code for training and testing models. Is there a Keras like fit, evaluate, predict api for CNTK? . If not, can some one post their code for us to use. The API needs to work for CNTK readers as well as numpy arrays. Sorry of this has already been posted/addressed.

**Comment by cha-zhang** [comment]
Yes. Check this tutorial: 
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_200_GuidedTour.ipynb

**Comment by Arvinds-ds** [comment]
Great!. I also noticed today that there is a Keras API. How do these 2 compare? Which do you think should a beginner focus on..CNTK functional API or Keras API? Are there any features which are fundamentally not supported in keras API

**Comment by cha-zhang** [comment]
Yes, we have to sacrifice performance to comply with Keras API. If you care about speed, use native CNTK API. 

Keras API is in beta, so we are continuing working on it.
