### ISSUE TITLE
Transfer Learning Tutorial does not work

### ISSUE THREAD

**Issue by Fusight** [Microsoft/CNTK#1927]
I tried to do the [transfer learning tutoria](https://github.com/Microsoft/CNTK/wiki/Build-your-own-image-classifier-using-Transfer-Learning)l  but in the file [TransferLearning.py,](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning.py) the program crashed on line 195, due to the fact that np.savetxt got a 3d array, not a 2d one. To fix this I changed the function call from  `np.savetxt(results_file, probs[np.newaxis], fmt="%.3f")`  to `np.savetxt(results_file, probs, fmt="%.3f")`. I do not know if this is the correct way to solve this issue. 
![image](https://cloud.githubusercontent.com/assets/26835074/26576499/5a2b2e2c-4529-11e7-90f5-c10c43106eda.png)

The [TransferLearning_Extended.py](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/TransferLearning/TransferLearning_Extended.py) also has an issue. The numpy function column_stack on line 56, fails as the two arrays are of different shapes. Therefor I changed the line from `class_probs = np.column_stack((probs, class_mapping)).tolist()` to `class_probs = np.column_stack((probs[0], class_mapping)).tolist()`. Again I do not know if this is the correct way to solve it.
![image](https://cloud.githubusercontent.com/assets/26835074/26576836/a191c478-452a-11e7-90ba-9dbe49fd0373.png)

**Comment by pkranen** [comment]
Which version of CNTK are you using?

**Comment by Fusight** [comment]
I am using version '2.0rc2'

**Comment by pkranen** [comment]
There was a regression in this example, it is now tested regularly and is fixed in RC3 and later.

**Comment by Fusight** [comment]
Ok. I will close this issue.
