### ISSUE TITLE
ProgressPrinter Heartbeat

### ISSUE THREAD

**Issue by vignesh-m** [Microsoft/CNTK#1928]
Currently, when the gen_heartbeat parameter is set to True in a ProgressPrinter, all that is printed is PROGRESS : 0.00%. 

This happens when Examples/Image/Classification/ConvNet/Python/ConvNet_CIFAR10_DataAug_Distributed.py is executed, for example.

This is caused by the code in [progress_print.py:250](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/logging/progress_print.py#L250)

Since the ProgressPrinter.update method is deprecated, trainers do not update the self.epochs variable. One solution I could make work was to set self.epochs when [on_write_training_summary](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/logging/progress_print.py#L391) is called. Then, we can use this and the self.num_epochs to give an epoch progress.

This can be a great improvement as running this on a platform like philly will give accurate progress rather than just 0%.

**Comment by cha-zhang** [comment]
Sure. Could you please create a pull request for this? Thanks!

**Comment by vignesh-m** [comment]
I have created the pull request #1929

**Comment by cha-zhang** [comment]
Philly no longer need progress print. Thus we will take this issue as resolved. Thanks!
