### ISSUE TITLE
Make a C++ API

### ISSUE THREAD

**Issue by Sherif89** [Microsoft/CNTK#193]
Hi, thanks for making CNTK. Do you plan to make a C++ API? It has the following features:
1. CNTK's in C++, so it may not be hard.
2. It may make it easier to use it from other languages. Instead of making a new API for each language, you can make a C++ binding.
3. C++ is very common, so more people may contribute to CNTK, after they find it easy to integrate it in their applications.

**Comment by amitaga** [comment]
Thanks for the suggestion. Yes this is already in the works - details will be shared in a few weeks.

**Comment by frankseide** [comment]
Let me add, the challenge is not to expose the current classes to C++. You can already use the existing CNTK C++ classes from any C++ program if you spend the effort to figure out how to build and link everything.

The reason we are working on redesigning the API is that the current C++ classes are highly interdependent and not well-designed for general use.

**Comment by Sherif89** [comment]
Thanks.

**Comment by Sherif89** [comment]
@wolfma61 , why did you close it? Did new API come?

**Comment by frankseide** [comment]
There are several requests for APIs, so we closed this specific one. It is not off the TODO list!

**Comment by Sherif89** [comment]
OK.
