### ISSUE TITLE
Any tool for monitoring the memory comsumption of the GPU

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/CNTK#1930]
I was wondering if there is something available in CNTK python for monitoring the memory consumption in real time. I took a look at [get_gpu_properties](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/device.py#L167), but it gives me the total memory of the GPU

**Comment by fct-edilberto** [comment]
Maybe you could use Msi afterburner to do this

**Comment by Brekel** [comment]
On Windows GPU-Z will show "Memory Used", not sure on Linux.
https://www.techpowerup.com/gpuz

**Comment by FDecaYed** [comment]
You can do something like `nvidia-smi -l 1` to monitor your memory usage outside the application.
You could also decorate the code(c++) to see memory usage information at a specific spot, but it will require re-compilation. There is no such API in python that I know of exposed this functionality to user, though I may be wrong.

**Comment by avader906** [comment]
The easiest would be to implement a feature to display stats on the first MB done by cntk - tensor sizes/number of parameters do not change during the training.

For linux - ```nvidia-smi``` will not provide details of consumer grade geforce cards. You would have to manually query [nvidia-settings](http://manpages.ubuntu.com/manpages/precise/man1/alt-nvidia-current-settings.1.html) or use monitoring tools built on top of that utility.
