### ISSUE TITLE
Error with cross_entropy_with_softmax

### ISSUE THREAD

**Issue by sripar** [Microsoft/CNTK#1932]
There seems to be an error with cross_entropy_with_softmax function when the arguments are vectors.

ValueError: DoMatrixProductOf: Ranks [4]' * [4] -> [1] mismatch.

**Comment by n17s** [comment]
I can't repro this with the latest master. Can you share a repro?

**Comment by n17s** [comment]
Closing this. Feel free to reopen if you have a repro.
