### ISSUE TITLE
Error while using TransferLearning model for evaluation (deploying model in Azure)

### ISSUE THREAD

**Issue by yashfujifilm** [Microsoft/CNTK#1933]
I get the following error if I open **http://localhost:3469/api/values** after following the tutorial **CNTKAzureTutorial01** for deploying models on Azure.

_<ArrayOfstring><string>domainBase directory C:\Users\imageworks\Desktop\CNTKSamples\CopySamples\CNTK-Samples-2-0rc2\Examples\Evaluation\CNTKAzureTutorial01\CNTKAzureTutorial01\, workingDirectory C:\Program Files\IIS Express, exception details: Microsoft.MSR.CNTK.Extensibility.Managed.CNTKRuntimeException: section name mismatch 
   at Microsoft.MSR.CNTK.Extensibility.Managed.IEvaluateModelManaged<float>.CreateNetwork(String networkDescription)
   at Microsoft.MSR.CNTK.Extensibility.Managed.IEvaluateModelManaged<float>.CreateNetwork(String networkDescription, Int32 deviceId, List`1 outputNodeNames)
   at CNTKAzureTutorial01.Controllers.ValuesController.<EvaluateCustomDNN>d__5.MoveNext() in C:\Users\imageworks\Desktop\CNTKSamples\CopySamples\CNTK-Samples-2-0rc2\Examples\Evaluation\CNTKAzureTutorial01\CNTKAzureTutorial01\Controllers\ValuesController.cs:line 85.</string></ArrayOfstring>_

Nuget Package namely **Microsoft CNTK CPU-only Model Evaluation Libraries (no GPU required)** is installed. TransferLearning model is based on GPU. So is it required for me to install GPU based Nuget package?

**My code for ValuesController.cs**
`    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Web.Http;
    using Swashbuckle.Swagger.Annotations;
    using Microsoft.MSR.CNTK.Extensibility.Managed;
    using System.Threading.Tasks;
    using System.IO;
    using System.Drawing;

    namespace CNTKAzureTutorial01.Controllers
    {
        public class ValuesController : ApiController
        {
            // GET api/values
            [SwaggerOperation("GetAll")]
            public async Task<IEnumerable<string>> Get()
            {
                return await this.EvaluateCustomDNN("http://3.bp.blogspot.com/-Mwr4UZALiA0/TWBt-3vFR8I/AAAAAAAAA4Y/0tXjI-NhVPM/s1600/j0262568.jpg");
            }

            // GET api/values/5
            [SwaggerOperation("GetById")]
            [SwaggerResponse(HttpStatusCode.OK)]
            [SwaggerResponse(HttpStatusCode.NotFound)]
            public string Get(int id)
            {
                return "value";
            }

            // POST api/values
            [SwaggerOperation("Create")]
            [SwaggerResponse(HttpStatusCode.Created)]
            public void Post([FromBody]string value)
            {
            }

            // PUT api/values/5
            [SwaggerOperation("Update")]
            [SwaggerResponse(HttpStatusCode.OK)]
            [SwaggerResponse(HttpStatusCode.NotFound)]
            public void Put(int id, [FromBody]string value)
            {
            }

            // DELETE api/values/5
            [SwaggerOperation("Delete")]
            [SwaggerResponse(HttpStatusCode.OK)]
            [SwaggerResponse(HttpStatusCode.NotFound)]
            public void Delete(int id)
            {
            }

            public async Task<string[]> EvaluateCustomDNN(string imageUrl)
            {
                string domainBaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
                string workingDirectory = Environment.CurrentDirectory;

                try
                {
                    // This example requires the RestNet_18 model.
                    // The model can be downloaded from <see cref="https://www.cntk.ai/resnet/ResNet_18.model"/>
                    int numThreads = 1;
                    List<float> outputs;

                    using (var model = new IEvaluateModelManagedF())
                    {
                        // initialize the evaluation engine
                        // TODO: initializing the evaluation engine should be one only once at the beginning
                        var initParams = string.Format("numCPUThreads={0}", numThreads);
                        model.Init(initParams);

                        // load the model
                        string modelFilePath = Path.Combine(domainBaseDirectory, @"CNTK\Models\TransferLearning.model");
                        var modelOption = string.Format("modelPath=\"{0}\"", modelFilePath);
                        model.CreateNetwork(modelOption, deviceId: -1);

                        // Prepare input value in the appropriate structure and size
                        var inDims = model.GetNodeDimensions(NodeGroup.Input);
                        if (inDims.First().Value != 512 * 512 * 3)
                        {
                            throw new CNTKRuntimeException(string.Format("The input dimension for {0} is {1} which is not the expected size of {2}.", inDims.First(), inDims.First().Value, 512 * 512* 3), string.Empty);
                        }

                        // Transform the image
                        System.Net.Http.HttpClient httpClient = new HttpClient();
                        Stream imageStream = await httpClient.GetStreamAsync(imageUrl);
                        Bitmap bmp = new Bitmap(Bitmap.FromStream(imageStream));

                        var resized = bmp.Resize(512, 512, true);
                        var resizedCHW = resized.ParallelExtractCHW();
                        var inputs = new Dictionary<string, List<float>>() { { inDims.First().Key, resizedCHW } };

                        // We can call the evaluate method and get back the results (single layer output)...
                        var outDims = model.GetNodeDimensions(NodeGroup.Output);
                        outputs = model.Evaluate(inputs, outDims.First().Key);
                    }

                    List<string> o = new List<string>();

                    foreach (float f in outputs)a
                    {
                        o.Add(f.ToString());
                    }

                    return o.ToArray<string>();
                }
                catch (Exception ex)
                {
                    return new string[] { string.Format("domainBase directory {0}, workingDirectory {1}, exception details: {2}.", domainBaseDirectory, workingDirectory, ex.ToString()) };
                }
            }
        }
    }
`

While using ResNet_18,model everything worked fine and I got the expected output, but while using my custom model I am not getting the necessary output. I need help!`

**Comment by yashfujifilm** [comment]
This is my ValuesController.cs file


using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Swashbuckle.Swagger.Annotations;

using Microsoft.MSR.CNTK.Extensibility.Managed;
using System.Threading.Tasks;
using System.IO;
using System.Drawing;


namespace CNTKAzureTutorial01.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        [SwaggerOperation("GetAll")]
        public async Task<IEnumerable<string>> Get()
        {
            return await this.EvaluateCustomDNN("http://3.bp.blogspot.com/-Mwr4UZALiA0/TWBt-3vFR8I/AAAAAAAAA4Y/0tXjI-NhVPM/s1600/j0262568.jpg");
        }

        // GET api/values/5
        [SwaggerOperation("GetById")]
        [SwaggerResponse(HttpStatusCode.OK)]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        [SwaggerOperation("Create")]
        [SwaggerResponse(HttpStatusCode.Created)]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [SwaggerOperation("Update")]
        [SwaggerResponse(HttpStatusCode.OK)]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [SwaggerOperation("Delete")]
        [SwaggerResponse(HttpStatusCode.OK)]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        public void Delete(int id)
        {
        }



        public async Task<string[]> EvaluateCustomDNN(string imageUrl)
        {
            string domainBaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            string workingDirectory = Environment.CurrentDirectory;

            try
            {
                // This example requires the RestNet_18 model.
                // The model can be downloaded from <see cref="https://www.cntk.ai/resnet/ResNet_18.model"/>
                int numThreads = 1;
                List<float> outputs;

                using (var model = new IEvaluateModelManagedF())
                {
                    // initialize the evaluation engine
                    // TODO: initializing the evaluation engine should be one only once at the beginning
                    var initParams = string.Format("numCPUThreads={0}", numThreads);
                    model.Init(initParams);

                    // load the model
                    string modelFilePath = Path.Combine(domainBaseDirectory, @"CNTK\Models\TransferLearning.model");
                    var modelOption = string.Format("modelPath=\"{0}\"", modelFilePath);
                    model.CreateNetwork(modelOption, deviceId: -1);

                    // Prepare input value in the appropriate structure and size
                    var inDims = model.GetNodeDimensions(NodeGroup.Input);
                    if (inDims.First().Value != 512 * 512 * 3)
                    {
                        throw new CNTKRuntimeException(string.Format("The input dimension for {0} is {1} which is not the expected size of {2}.", inDims.First(), inDims.First().Value, 512 * 512* 3), string.Empty);
                    }

                    // Transform the image
                    System.Net.Http.HttpClient httpClient = new HttpClient();
                    Stream imageStream = await httpClient.GetStreamAsync(imageUrl);
                    Bitmap bmp = new Bitmap(Bitmap.FromStream(imageStream));

                    var resized = bmp.Resize(512, 512, true);
                    var resizedCHW = resized.ParallelExtractCHW();
                    var inputs = new Dictionary<string, List<float>>() { { inDims.First().Key, resizedCHW } };

                    // We can call the evaluate method and get back the results (single layer output)...
                    var outDims = model.GetNodeDimensions(NodeGroup.Output);
                    outputs = model.Evaluate(inputs, outDims.First().Key);
                }

                List<string> o = new List<string>();

                foreach (float f in outputs)
                {
                    o.Add(f.ToString());
                }

                return o.ToArray<string>();
            }
            catch (Exception ex)
            {
                return new string[] { string.Format("domainBase directory {0}, workingDirectory {1}, exception details: {2}.", domainBaseDirectory, workingDirectory, ex.ToString()) };
            }
        }
    }
}

**Comment by zhouwangzw** [comment]
@yashfujifilm How was your custom model trained, with Python or with Brainscript? If it is trained with Python, you need to use [CNTK Library API  ](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Library-Evaluation-on-Windows). The Microsoft.MSR.CNTK.Extensibility.Managed.IEvaluateModelManaged is part of Eval V1 API, and can only evaluate models trained via BrainScript. You can find more details about evaluation [here](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Evaluation-Overview). The Azure evaluation tutorial is still referencing Eval V1 API, and we will update it to use the new CNTK Library API very soon.

**Comment by hat22u** [comment]
I revised this tutorial to adapt to Eval V2 API.
Please take a look at below sample.
https://github.com/hat22u/CNTKAzureTutorial01withV2API

**Comment by zhouwangzw** [comment]
@hat22u Great to know it works. Thanks!

I am closing this issue. Please feel free to re-open it if needed.
