### ISSUE TITLE
how does one print a model's layers in order to determine the names of the hidden layers/feature layer?

### ISSUE THREAD

**Issue by ckalas** [Microsoft/CNTK#1935]
I've been trying to look around the api and tutorials for the last 2 hours but can't find anything. This is related to the TL example where ResNet18 is loaded and the layer names are seemingly out of nowhere / don't seem to relate to the paper.

On a related note, is there a proper way to view the available pretrained models? the model_utils.py only has 4 models hardcoded in, but I for example was able to download the unlisted ResNet_34 with wget.

**Comment by anijain2305** [comment]
I have a similar doubt. I have been hacking CompositeFunction.cpp file to get the names of hidden layers/feature layer. But, it is not straightforward to map that to the DNN specified in the python files. I would also love to know if there is a simple way.
