### ISSUE TITLE
CTC exception

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1937]
Hi

I try to use CTC as my criterion node in ndl file like:

```
	graph = LabelsToGraph(labels)
	cr = ForwardBackward(graph, FFL6, 30, delayConstraint=3, tag="criterion")
	Err = EditDistanceError(labels, FFL6, squashInputs=true, tokensToIgnore = 30, tag="evaluation")
```
But I get the following exception:

> EXCEPTION occurred: ForwardBackward operation 'cr' expects 2 inputs (given: 3)

I used ForwardBackward node as it was used in CTC example at [here](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/Speech/LSTM_CTC_MLF/lstm.bs).
```
        graph = LabelsToGraph(labels)
        cr = ForwardBackward(graph, LSTMoutputW, 132, delayConstraint=3, tag="criterion") 
        Err = EditDistanceError(labels, LSTMoutputW, squashInputs=true, tokensToIgnore = 132, tag="evaluation") 
```
In this example exactly the same parameters are passed to ForwardBackward node but the example runs without any problem! The only different between these two is that I use ForwardBackward node in my ndl file and the following example used it inside BrainScriptNetworkBuilder block. Does the difference cause the exception or I must use ForwardBackward node in some different manner?

regards

**Comment by vmazalov** [comment]
NDL is not supported anymore. You are advised to use python or brainscript version.
