### ISSUE TITLE
Can CNTK be built in Visual Studio 2017?

### ISSUE THREAD

**Issue by playgithub** [Microsoft/CNTK#1941]

**Comment by cha-zhang** [comment]
Not yet. cuDNN is not ready for VS 2017.

**Comment by veikkoeeva** [comment]
Cross-referencing https://github.com/Microsoft/CNTK/issues/1603.

**Comment by FlashTek** [comment]
Are there now any plans when CNTK will support the recently released CUDA 9.0 and cuDNN 7?

**Comment by cha-zhang** [comment]
We are working on that. ETA this iteration (Nov. 3).
