### ISSUE TITLE
Since RC3, learning outcomes are different.

### ISSUE THREAD

**Issue by KGWANGMIN** [Microsoft/CNTK#1944]
Hello. If you compare RC2 version and RC3 version, Train of Convolution goes differently. Is there anything that I do not know that was fixed in RC3? Because of this issue, we are working on everything with RC2.

**Comment by cha-zhang** [comment]
Can you elaborate what's different? Can you give us a repro?

**Comment by ebarsoumMS** [comment]
Please reactivate with more details.
