### ISSUE TITLE
cntk-2.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by amapss** [Microsoft/CNTK#1949]
While trying to install CNTK on Windows 10 with pip v9.0.1 on Python 3.6 using "pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl" gives an error "cntk-2.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform".

**Comment by tijmen** [comment]
You're trying to install the "p35" or python 3.5 version on a python 3.6 installation.

**Comment by amapss** [comment]
Thanks, is there a version available for Python 3.6 ?

**Comment by mahilleb-msft** [comment]
Please go with https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl for a CPU-only version.
Cf. https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python.
Best, Mark

**Comment by amapss** [comment]
That didn't work either. So, I setup a v3.5 environment with anaconda and installed the cntk-2.0-cp35-cp35m-win_amd64.whl . Thanks.
