### ISSUE TITLE
Where to set USE_MKL?

### ISSUE THREAD

**Issue by dawiehyman** [Microsoft/CNTK#195]
I'm trying to compile on VS 2013, and CPUSparseMatrix.cpp among others are looking for acml.h, but I am opting for MKL.   I note in install instructions, to specify USE_MKL in the math library, and I suppose its a #defiine directive? But my question is where do I do this?  (I did set Intel MKL in the configuraiton settings) Downstream I see that math.lib does not compile and I suspect it has to do with this.

**Comment by xhzhao** [comment]
In linux version, I use the command：../../configure --with-mkl=/opt/intel.
Hope this will help.

**Comment by dawiehyman** [comment]
Thanks xhzhao.  I built it on Ubuntu using that very same switch and it worked beautufilly.  My question is, how to do the same thing on VS 2013.  I might just lack some key bit of info on how to compile in VS..  Still searching!

**Comment by mradmila** [comment]
Please take a look at Math.vcxproj:

<UseIntelMKL>No</UseIntelMKL>
