### ISSUE TITLE
copy loaded model in memory.

### ISSUE THREAD

**Issue by pbplugge** [Microsoft/CNTK#1950]
I am new to CNTK. I just loaded my model in my c++ project. What i want is 100 instances of the same model. But i don't want to load them all from disk. I also can not use the single instance 100 times because recurrent networks would be messed up.
Is there a way to make duplicates of the original in the memory?

**Comment by bencherian** [comment]
Use the clone method of the loaded model. You can specify if you want the model parameters to be cloned shared or frozen depending on how you want to use the cloned models.

```cpp
/// Clones 'this' Function. The parameters of the Function are either cloned, shared or frozen as specified by the parameterCloneMethod argument and
/// any variable replacements requested are applied in the cloned Function instance.
///
CNTK_API FunctionPtr Clone(ParameterCloningMethod parameterCloneMethod = ParameterCloningMethod::Clone, const std::unordered_map<Variable, Variable>& replacements = {}) const;
```

**Comment by zhouwangzw** [comment]
Yes. Clone is the right method to create multiple instances of the same model. If the loaded model is just used for evaluation, you can specify `Share` for `parameterCloneMethod`, which enables parameter sharing and thus reduce memory usage.

I am closing the issue, and feel free to reopen it if needed.
