### ISSUE TITLE
Resnet vs Convnet giving NaN as output when evaluating

### ISSUE THREAD

**Issue by clintjcampbell** [Microsoft/CNTK#1953]
I have been trying different example networks on my dataset but am having issues evaluating the resnet model.  The Convnet model evaluates fine, but all I get for all inputs for the Resnet20 or 110 model is NaN for all outputs.  
I am using the distributed python codes to [ConvNet_CIFAR10_DataAug_Distributed.py](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ConvNet/Python/ConvNet_CIFAR10_DataAug_Distributed.py) and [TrainResNet_CIFAR10_Distributed.py](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10_Distributed.py )
I save the model after training using `network['output'].save_model(MyModel)`
During training it shows the loss and metric being good.  I use the same Image Deserializers, transforms, and handle the data the same for evaluating. 

in evaluation I load the model
predictions = np.squeeze(z.eval({z.arguments[0]:[pic]}))

Do I need to pull out something specific for the ResNet models to evaluate or do I need to dig deeper for hidden issues in my code?

Also is it possible to use the load model for a checkpoint file and evaluate from it directly instead of saving out a separate model file?

**Comment by clintjcampbell** [comment]
I evaluated my dataset.  Not all come out as NaN, but some occasionally come out to very large numbers- 10^30 or -10^30.

**Comment by cha-zhang** [comment]
When you evaluate, did you scale you input by 0.00390625, as here: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ConvNet/Python/ConvNet_CIFAR10_DataAug_Distributed.py#L67

**Comment by clintjcampbell** [comment]
Yes, i tried that later yesterday and still did not have success. Maybe i
need a smaller number?

**Comment by cha-zhang** [comment]
Sorry I just realize you said in the first post that ConvNet is ok. For ResNet you shouldn't need to scale the input. 

Could you post your complete eval code, say on the first image of the test set in CIFAR10?

**Comment by wolfma61** [comment]
Closing this due to lack of feedback. 
Please open a new issue if you still experience this problem with the latest released version of CNTK
