### ISSUE TITLE
Tutorial about ImageInput with dynamicAxis

### ISSUE THREAD

**Issue by hongjiedai** [Microsoft/CNTK#1958]
I have found the nice tutorial about using  dynamic axis with Input at 
https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Language-Understanding

Is there any example to demonstrate the way of using dynamic axis with Imageinput?

**Comment by ebarsoumMS** [comment]
Currently, we don't support more than one dynamic axis.
