### ISSUE TITLE
No module named 'menuinst'

### ISSUE THREAD

**Issue by MrMYHuang** [Microsoft/CNTK#1959]
I installed CNTK 2.0 with Python 3.6 on my Windows 10 PC. The install.bat script creates a link 'Jupyter Notebook (cntk-py36)' in my App List. However, the link fails to open Jupyter Notebook. I tried to run the link command in cmd.exe, but I got this error:
```
D:\win10\Anaconda3\envs\cntk-py36\python.exe
 D:\win10\Anaconda3\cwp.py d:\win10\Anaconda3\envs\cntk-py36 "d:/win10/Anaconda3/envs/cntk-py36/python.exe" "d:/win10/An
aconda3/envs/cntk-py36/Scripts/jupyter-notebook-script.py" %USERPROFILE%
Traceback (most recent call last):
  File "D:\win10\Anaconda3\cwp.py", line 9, in <module>
    from menuinst.knownfolders import FOLDERID, get_folder_path, PathNotFoundException
ModuleNotFoundError: No module named 'menuinst'
```
Then, I find a workaround for this issue by installing menuinst to cntk-py36:
```
conda install -n cntk-py36 menuinst
```
Please fix this bug.

**Comment by wolfma61** [comment]
Unfortunately your report isn't very detailed regarding the steps you took. 
if you used the INSTALL.BAT script to install CNTK into your environment, you will need to add the `AnacondaBasePath` and `PyVersion` parameter to install CNTK correctly ... did you do so?

https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-binary-script-options

Our internal tests run with the default path, and work correctly

thx
Wolfgang

**Comment by wolfma61** [comment]
please reopen with a detailed repo scenario if you experience the problem
