### ISSUE TITLE
Can I load a part of weights learned previous training?

### ISSUE THREAD

**Issue by tapdo** [Microsoft/CNTK#196]
I'd like use weights learned prevuous training in a part of the net. How do I load it?
Rest of the weights should be random initializatin.

**Comment by Alexey-Kamenev** [comment]
I would suggest to take a look at MEL (Model Editing Language) which allows model modification. For example, you can load your previous model, do some modifications (add/remove nodes) and train that new model which will have some of the parameters from the old one. Refer to CNTK book for more details on MEL.

**Comment by dongyu888** [comment]
Check section 4.2.1.3 in the CNTK book for information on how to copy values of nodes. you can also find an example MEL file under CNTK\Examples\Speech\Miscellaneous\TIMIT\config

**Comment by tapdo** [comment]
Thank you for replay. I got it.
