### ISSUE TITLE
Installing whl: Read Timed Out

### ISSUE THREAD

**Issue by jhave** [Microsoft/CNTK#1960]
Using instructions from https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-python
`$ conda create --name cntk-py34 python=3.4 numpy scipy h5py jupyter
$ activate cntk-py34
$ pip install https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp34-cp34m-linux_x86_64.whl`

Repeatedly encountered timeout during setup: 

`File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cntk.ai', port=443): Read timed out.`

Checked my internet connection. Speed fine. 5.9mb/s down, 28ms ping. 8 mb/s up.

Full error here:

`Collecting cntk==2.0 from https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp34-cp34m-linux_x86_64.whl
  Downloading https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp34-cp34m-linux_x86_64.whl (278.1MB)
    2% |▉                               | 7.4MB 4.0kB/s eta 19:01:59Exception:
Traceback (most recent call last):
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/http/client.py", line 537, in read
    return super(HTTPResponse, self).read(amt)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/http/client.py", line 576, in readinto
    n = self.fp.readinto(b)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/ssl.py", line 748, in recv_into
    return self.read(nbytes, buffer)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/download.py", line 605, in _download_url
    consume(downloaded_chunks)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/utils/__init__.py", line 852, in consume
    deque(iterator, maxlen=0)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jhave/anaconda3/envs/cntk-py34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cntk.ai', port=443): Read timed out.`

**Comment by jhave** [comment]
Addendum, to check i made a new conda environment, and tried again, conda dependencies installed super quick, cntk.ai server is SO slow:

`python-3.6.1-2 100% |###############################################################################################################################################################################################| Time: 0:00:07   2.40 MB/s
decorator-4.0. 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.67 MB/s
entrypoints-0. 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.15 MB/s
ipython_genuti 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.97 MB/s
jedi-0.10.2-py 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.88 MB/s
jsonschema-2.6 100% |###############################################################################################################################################################################################| Time: 0:00:00   3.79 MB/s
markupsafe-0.2 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.37 MB/s
mistune-0.7.4- 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.74 MB/s
numpy-1.12.1-p 100% |###############################################################################################################################################################################################| Time: 0:00:03   2.42 MB/s
pandocfilters- 100% |###############################################################################################################################################################################################| Time: 0:00:00   4.42 MB/s
path.py-10.3.1 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.63 MB/s
ptyprocess-0.5 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.94 MB/s
pygments-2.2.0 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.68 MB/s
pyzmq-16.0.2-p 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.27 MB/s
setuptools-27. 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.86 MB/s
simplegeneric- 100% |###############################################################################################################################################################################################| Time: 0:00:00  23.85 MB/s
sip-4.18-py36_ 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.51 MB/s
six-1.10.0-py3 100% |###############################################################################################################################################################################################| Time: 0:00:00  11.76 MB/s
testpath-0.3.1 100% |###############################################################################################################################################################################################| Time: 0:00:00  29.14 MB/s
tornado-4.5.1- 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.77 MB/s
wcwidth-0.1.7- 100% |###############################################################################################################################################################################################| Time: 0:00:00   8.46 MB/s
wheel-0.29.0-p 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.69 MB/s
h5py-2.7.0-np1 100% |###############################################################################################################################################################################################| Time: 0:00:01   2.50 MB/s
html5lib-0.999 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.40 MB/s
jinja2-2.9.6-p 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.77 MB/s
pexpect-4.2.1- 100% |###############################################################################################################################################################################################| Time: 0:00:00   3.23 MB/s
pickleshare-0. 100% |###############################################################################################################################################################################################| Time: 0:00:00  26.32 MB/s
pip-9.0.1-py36 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.68 MB/s
prompt_toolkit 100% |###############################################################################################################################################################################################| Time: 0:00:00   1.73 MB/s
python-dateuti 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.46 MB/s
scipy-0.19.0-n 100% |###############################################################################################################################################################################################| Time: 0:00:15   2.40 MB/s
terminado-0.6- 100% |###############################################################################################################################################################################################| Time: 0:00:00   1.78 MB/s
traitlets-4.3. 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.85 MB/s
bleach-1.5.0-p 100% |###############################################################################################################################################################################################| Time: 0:00:00   3.60 MB/s
ipython-6.1.0- 100% |###############################################################################################################################################################################################| Time: 0:00:00   1.80 MB/s
jupyter_core-4 100% |###############################################################################################################################################################################################| Time: 0:00:00   1.60 MB/s
jupyter_client 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.13 MB/s
nbformat-4.3.0 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.86 MB/s
ipykernel-4.6. 100% |###############################################################################################################################################################################################| Time: 0:00:00   3.27 MB/s
nbconvert-5.2. 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.71 MB/s
pyqt-5.6.0-py3 100% |###############################################################################################################################################################################################| Time: 0:00:02   2.49 MB/s
jupyter_consol 100% |###############################################################################################################################################################################################| Time: 0:00:00   3.09 MB/s
notebook-5.0.0 100% |###############################################################################################################################################################################################| Time: 0:00:02   2.36 MB/s
qtconsole-4.3. 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.51 MB/s
widgetsnbexten 100% |###############################################################################################################################################################################################| Time: 0:00:00   2.59 MB/s
ipywidgets-6.0 100% |###############################################################################################################################################################################################| Time: 0:00:00   3.13 MB/s
jupyter-1.0.0- 100% |###############################################################################################################################################################################################| Time: 0:00:00  10.76 MB/s
#
# To activate this environment, use:
# > source activate cntk-py36
#
# To deactivate this environment, use:
# > source deactivate cntk-py36
#

jhave@jhave-Ubuntu:~$ source activate cntk-py36
(cntk-py36) jhave@jhave-Ubuntu:~$ pip install https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp36-cp36m-linux_x86_64.whl
Collecting cntk==2.0 from https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp36-cp36m-linux_x86_64.whl
  Downloading https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp36-cp36m-linux_x86_64.whl (278.1MB)
    2% |▋                               | 5.6MB 37kB/s eta 2:02:38Exception:
Traceback (most recent call last):  ... Read timed out.
`

**Comment by cha-zhang** [comment]
@jhave , very sorry for the late response. Has this issue be resolved?

**Comment by ebarsoumMS** [comment]
Please reactivate if the issue still repro.

**Comment by yshean** [comment]
I also have this issue. Seems to only be a problem when attempting to pip install and wget. Downloading the whl file via browser is quick.

**Comment by tchemineau** [comment]
Same here:
<img width="947" alt="capture d ecran 2017-09-12 a 18 59 30" src="https://user-images.githubusercontent.com/361517/30338681-b40bdb88-97ec-11e7-97a8-f19d8a2b315c.png">

The speed varies a lot, from 80KB/S to 35MB/s. This is not enough stable, and regularly breaks automatic jobs (eg, jobs crash with timeout errors).
