### ISSUE TITLE
07_Deconvolution_Visualizer.py  list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by Robird** [Microsoft/CNTK#1964]
(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35) D:\AI\CNTK-2-0-Windows-64bit-GPU\Examples\Image\GettingStarted>python 07_Deconvolution_Visualizer.py
Selected GPU[0] GeForce GTX 1070 as the process wide default device.
Traceback (most recent call last):
  File "07_Deconvolution_Visualizer.py", line 127, in <module>
    generate_visualization(use_brain_script_model)
  File "07_Deconvolution_Visualizer.py", line 107, in generate_visualization
    in_values = (encoder_input[0,0].flatten())[np.newaxis]
TypeError: list indices must be integers or slices, not tuple

**Comment by pkranen** [comment]
The code in the latest master for that line looks as follows:
```
in_values = (encoder_input[0][0].flatten())[np.newaxis]
```
That should fix it, I tried it just now and it works fine. Please try again with the latest bits. I'll close this issue, feel free to reopen if that does not fix it for you. Thanks.
