### ISSUE TITLE
Using CNTK with Unity

### ISSUE THREAD

**Issue by tobyclh** [Microsoft/CNTK#1966]
Hello there!
I have integrated a few Unity class and GUI elements and some basics for people who want to use CNTK in their game / experience. [Take a look if it sounds interesting to you.](https://github.com/tobyclh/UnityCNTK) It is still very immature, but I can get VGG16 evaluating a screenshot captured by the webcam and so on! However, I am trying to reproduce https://github.com/Microsoft/FERPlus in game as a example but I can't really get the preprocess done in Unity. Is there anyone who know of a better idea?

**Comment by aiunderstand** [comment]
Hi Toby! 

Have a look at this [repo](https://github.com/codec-abc/Electron-Unity-FFI-Playground). Also, i'll be updating [my repo](https://github.com/aiunderstand/unity-cntk) on Unity CNTK integration this weekend, it uses the same basic image preprocessing facilities provided with the tutorials on this CNTK repo. For more advanced libraries have look at EmguCV and Accord.NET, i've used both in my MSc thesis work with CNTK.

A sneak peak on a Desktop (Oculus/Vive ready) build, WebGL build and with a Hololens (UWP) build on the way:
![desktop](https://cloud.githubusercontent.com/assets/6376127/26830784/44abb098-4aca-11e7-971b-d94cd68843a7.jpg)
![main](https://cloud.githubusercontent.com/assets/6376127/26830795/4a4ea69a-4aca-11e7-871c-70a309c36d58.jpg)

I hope all this effort will trigger MS to acknowledge C# training support is the single most coolest feature for CNTK in production code. Happy coding with Unity & CNTK, great to see more like minded!

**Comment by aiunderstand** [comment]
Also, please state your opinion on C# training support in [this forum](https://github.com/Microsoft/CNTK/issues/960), we need more people :D

**Comment by tobyclh** [comment]
I did consider using accord for the application, but in terms of AR/ VR application, I suspect it will be the best if we can provide an end to end model to content creators who don't want to deal with the fuss and for better performance. That's why I was wondering whether I can embed the processing within the network somehow.  
Your project looks awesome! Can't wait to see when it comes out!
I will absolutely head to support once I get some free time later today

**Comment by aiunderstand** [comment]
I agree, we need some basic (image/speech/etc) processing tools build in. However, for more advanced users integration of tools like accord and opencv are IMHO better as they do what they do best. Thanks for your interest, I still have to clean my code a bit and upload it asap. Maybe you can mention your VR usecase specifically in the #960 thread, the CNTK team will love to hear how .net is or can be used in practice.

**Comment by JimSEOW** [comment]
@aiunderstand  thanks for bringing people to #960  Now we have CNTK's attention to update us at e.g. "**Insider Fast Ring**" regularity, Let us do our part.

**Comment by wolfma61** [comment]
closing this - .net is being discussed in different issues and internal ;)
