### ISSUE TITLE
Train model in C#

### ISSUE THREAD

**Issue by MgSam** [Microsoft/CNTK#1967]
Are there any plans to provide a C# interface for training a CNTK model? 

This would be really helpful so that we don't have to drop to a different language for this part of the process.

**Comment by aiunderstand** [comment]
Could you also voice your opinion about C# training in this [thread](https://github.com/Microsoft/CNTK/issues/960 )? The more people that vote for this, the more priority it gets.

**Comment by vermorel** [comment]
FYI, we have just released an early draft of [CNTKSharp](https://github.com/Lokad/cntksharp). This is precisely intended to bring model training to C#.

**Comment by JimSEOW** [comment]
@wolfma61 It is great that you keep closing the old issues from 750 down to 650 within a few days [Please keep going to close more], HOWEVER, please keep #950 open. Thank you.
