### ISSUE TITLE
CNTK Eval support for Intel integrated graphics (using open source clDNN)

### ISSUE THREAD

**Issue by bbuchika** [Microsoft/CNTK#1968]
This is a feature request.

Does Microsoft have any plans to add eval (not training) support for [clDNN](https://www.codeproject.com/Articles/1190101/Accelerate-Deep-Learning-Inference-with-Intel-Proc)? This would allow edge computing devices (i.e., small form factor PC's ) running CNTK models to utilize the extra processing power of integrated graphics- which is crucial for reducing product cost. 

Thanks,
Brant

**Comment by wolfma61** [comment]
difficult to comment something concrete ... although we are with this feature request!

non-intel (win/lin) is pretty high on the to-do-list, especially smaller form-factor and non-PC.
We need to set priorities and need to create/publish some kind of roadmap how we want to attack the issue
This would also mean increased support for math packages like mkl, mkl cudnn, openblas, ...
I don't think we can promised something for end-of-july ...

**Comment by bbuchika** [comment]
Thank you Mr. Manousek, for the update and the interest. We would use this feature the moment it became available, as it would significantly help with both performance and costs of products we are currently developing. 
Thanks again,
Brant
