### ISSUE TITLE
Can CNTK support hybrid speech recognition in English and Chinese?

### ISSUE THREAD

**Issue by gaoxuesong** [Microsoft/CNTK#1970]
Hi , how to make CNTK speech support hybrid speech recognition in English and Chinese Mandarin?

Thanks.

**Comment by cha-zhang** [comment]
This is not really a CNTK question. You need an algorithm/model to do hybrid speech recognition. Unfortunately we don't have an example like this. 

If you know a particular model that can do that, feel free to add your comments here and we may implement it in CNTK as an example.

**Comment by ebarsoumMS** [comment]
Please move this question to stackoverflow, this isn't a CNTK issue.

**Comment by gaoxuesong** [comment]
OK
