### ISSUE TITLE
CNTK library evaluation of recurrent model

### ISSUE THREAD

**Issue by vmazalov** [Microsoft/CNTK#1972]
The available evaluation docs are not clear about how to reset memory cells in RNNs. For example, given the standard way of feeding sequence of frames to the model as shown below, tutorial needs clarification whether CNTK resets memory automatically after each sequence. What if `CreateBatch` is used instead of `CreateSequence`?
```
        CNTK::ValuePtr inputSeq = CNTK::Value::CreateSequence<float>(m_inputVar.Shape(), evalInput, 
        CNTK::DeviceDescriptor::CPUDevice(), true);
        CNTK::ValuePtr outputSeq;

        unordered_map<CNTK::Variable, CNTK::ValuePtr >  inputs = { {m_inputVar, inputSeq } };
        unordered_map<CNTK::Variable, CNTK::ValuePtr >  outputs = { { m_outputVar, outputSeq } };

        m_modelFuncPtr->Forward(inputs, outputs, CNTK::DeviceDescriptor::CPUDevice());
        
        outputSeq = outputs[m_outputVar];

        CNTK::NDShape outputShape = m_outputVar.Shape().AppendShape({ nFrames, 1 });
        std::vector<float> outputData(outputShape.TotalSize()*nFrames);
        CNTK::NDArrayViewPtr cpuArrayOutput = CNTK::MakeSharedObject<CNTK::NDArrayView>(outputShape, outputData, false);
        cpuArrayOutput->CopyFrom(*outputSeq->Data());```

**Comment by zhouwangzw** [comment]
Each new sequnce will reset the memory. If you do not want to reset the memory, you can specify thethe parameter `bool sequenceStartFlag ` to `false` when calling CreateSequence(). 
CreateBatch treats each sample as a new seqeunce, i.e. creates a batch of sequences and each sequence has a length of 1.
