### ISSUE TITLE
1bit-SGD + Keras

### ISSUE THREAD

**Issue by minimaxir** [Microsoft/CNTK#1975]
How do use the 1bit-SGD optimizer in Keras w/ the CNTK backend? I am not seeing any documentation in that particular area.

Does just setting the normal SGD() optimizer do the trick?

**Comment by minimaxir** [comment]
Actually, just testing it, when setting the optimizer to `'sgd`' instead of `adam` for example in Keras, the optimization doesn't work at all.

**Comment by n17s** [comment]
It depends what you want to do:
* If you want to define the model with Keras, then "steal it" and train with CNTK, it should be possible to do it with the existing functionality.
* if you want to train with Keras APIs, it would be more appropriate if you opened an issue on Keras supporting distributed training.

**Comment by minimaxir** [comment]
The latter.

The maintainer of Keras noted that [Microsoft is responsible for the CNTK backend](https://github.com/fchollet/keras/pull/6800#pullrequestreview-41845918), which is why I commented here first.

**Comment by cha-zhang** [comment]
I don't think Keras has options to extend and use CNTK native features, and I agree with @n17s that this is not a CNTK issue. 

I'm going to close this for now. Feel free to reopen it if you think this is important.
