### ISSUE TITLE
How to Build CNTK for ARM64?

### ISSUE THREAD

**Issue by jerremy1336** [Microsoft/CNTK#1976]
I'm trying to benchmark Alexnet with CNTK on ARM64, I have installed openmpi and openblas on the arm64 server, and removed "SSE_FLAGS = -msse4.1 -mssse3" from Makefile, but I still got errors when building CNTK for ARM64. Here is the error info: fatal error: lapacke.h: No such file or directory. As mentioned in issue #1185, there are some specific configuration are required for supporting ARM64, can you tell me how?

**Comment by zhouwangzw** [comment]
you need to install liblapacke-dev:
`sudo apt-get install liblapacke-dev`
