### ISSUE TITLE
CNTK v2.0: Excessive CPU utilization from libiomp5.so running BrainScript

### ISSUE THREAD

**Issue by bcbrock** [Microsoft/CNTK#1986]
I am going to ask and answer my own question here in order to create a record that may be useful to others in the future. 

# Question

I am running image classification training using a BrainScript version of ResNet152 on CNTK v2.0 and see excessive amounts of CPU utilization. The example is running on a 2-socket server with 4 local GPUs. This training example was launched as

    mpiexec -n 4 cntk configFile=phase2.cntk makeMode=false

Below is an image from `htop` showing every thread in this 2-socket server heavily utilized. This condition persists for almost the entire time of the training:
![screen shot 2017-06-09 at 11 24 37 am](https://user-images.githubusercontent.com/11968347/26995609-43e1b2be-4d33-11e7-8bee-b0ef8b54ebeb.png)

A system-wide `oprofile` trace shows that the culprit is a routine from `libiomp5.so`. This is an Intel-specific version of OpenMP support distributed by Microsoft as part of `CNTKCustomMKL`.
```
CPU: Intel Broadwell microarchitecture, speed 3400 MHz (estimated)
Counted CPU_CLK_UNHALTED events (Clock cycles when not halted) with a unit mask of 0x00 (No unit mask) count 2000000
samples  %        image name               app name                 symbol name
742414   60.0258  libiomp5.so              cntk                     __kmp_hyper_barrier_release(barrier_type, kmp_info*, int, int, int, void*)
122716    9.9219  libjpeg.so.8.0.2         cntk                     /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
111355    9.0033  libcuda.so.375.39        cntk                     /usr/lib/x86_64-linux-gnu/libcuda.so.375.39
29418     2.3785  libiomp5.so              cntk                     __kmp_hyper_barrier_gather(barrier_type, kmp_info*, int, int, void (*)(void*, void*), void*)
24482     1.9794  libopencv_imgcodecs.so.3.1.0 cntk                     icvCvt_BGR2RGB_8u_C3R(unsigned char const*, int, unsigned char*, int, CvSize)
14736     1.1914  libiomp5.so              cntk                     __kmp_yield
12576     1.0168  mca_btl_vader.so         cntk                     /usr/lib/openmpi/lib/openmpi/mca_btl_vader.so
```
How can this excessive CPU time be reduced?

# Answer

I believe that this condition is caused by an "optimization" in the Intel library to _hot idle_ non-busy MPI threads, to reduce latency once work becomes available. Note that on another system we use the standard OpenMPI libraries and do not see this excessive CPU consumption.

This condition can be fixed by explicitly setting the `numCPUThreads` variable in the BrainScript file, e.g.:

    numCPUThreads=2

The above setting only allows each CNTK process to use 2 hardware threads, and dramatically reduces non-productive overhead.

To be fair, however, the hot idle optimization does appear to improve throughout in our example by low single-digit percentages compared to setting `numCPUThreads` to 1 or 2.

**Comment by cha-zhang** [comment]
@bcbrock thank you for asking the question and answering it yourself! I'm closing this issue now.
