### ISSUE TITLE
Grayscale Images with Image Reader

### ISSUE THREAD

**Issue by breckerm** [Microsoft/CNTK#1987]
Related to Issue #263, the Image Reader still does not seem to be working correctly with 8-bit grayscale images. I am using the latest release (CNTK v2.0).

The following code was used for the Image Reader and to get the pixel data from the minibatch data:

```
size_t TestImageReader(int width, int height, int numChannels, std::wstring& mapFile, int labelDim, std::wstring& dstFile)
{ 
     std::vector<CNTK::ImageTransform> transforms;
     CNTK::ImageTransform scaleTransform = CNTK::ReaderScale(width, height, numChannels, L"linear");
     transforms.emplace_back(scaleTransform);
     CNTK::Deserializer imgDeserializer = CNTK::ImageDeserializer(mapFile, L"labels", labelDim, L"features", transforms);
     CNTK::MinibatchSourceConfig mbConfig({imgDeserializer});
     mbConfig.maxSamples = CNTK::MinibatchSource::InfinitelyRepeat;
     CNTK::MinibatchSourcePtr mbSrcPtr = CNTK::CreateCompositeMinibatchSource(mbConfig);
     auto mbData = mbSrcPtr->GetNextMinibatch(1, CNTK::DeviceDescriptor::CPUDevice());
     
     size_t totalSize = mbData[mbSrcPtr->StreamInfo(L"features")].data->Shape().TotalSize();
     float* pixelData = mbData[mbSrcPtr->StreamInfo(L"features")].data->Data()->WritableDataBuffer<float>();

     std::fstream outFile{ dstFile, fstream::out };
     for(int i = 0; i < totalSize; i++)
     {
          outFile << pixelData[i] << " ";
     }
     outFile.close();
     return totalSize;
}
```

Using the function above and a 5x5 grayscale image, I got the following results:

Original Image Data
![testimage](https://user-images.githubusercontent.com/10854405/26997995-a8223618-4d4c-11e7-937c-cd741669f7ae.png) <---Here is the actual PNG
10  11  12  13  14
15  16  17  18  19
20  21  22  23  24
25  26  27  28  29
30  31  32  33  34

Pixel Data After Image Reader with 1 Channel
`TestImageReader(5, 5, 1, L"mapFile.txt", 2, "dstFile.txt");`
10  10  10  11  11
11  12  12  12  13
13  13  14  14  14
15  15  15  16  16

Pixel Data After Image Reader with 3 Channels
`TestImageReader(5, 5, 3, L"mapFile.txt", 2, "dstFile.txt");`
10  11  12  13  14
15  16  17  18  19
20  21  22  23  24
25  26  27  28  29
30  31  32  33  34
10  11  12  13  14
15  16  17  18  19
20  21  22  23  24
25  26  27  28  29
30  31  32  33  34
10  11  12  13  14
15  16  17  18  19
20  21  22  23  24
25  26  27  28  29
30  31  32  33  34

Observations:
With 1 channel, each pixel seems to be repeated 3 times and only the top third portion of the image is preserved since the total size is 25 as it should be. If I were to only write every third pixel value to a file and create a png from that file, I can clearly see that it is the top third portion of the image.
With 3 channels, the entire image is repeated 3 times, so the total size is 75. This contains all of the correct pixel values, but repeats all of it 3 times. If I were to write the pixel data to a file, I can create a correct png of the image. However, it is tripling the amount of data necessary for the image.

Am I using the Image Reader incorrectly, or is there still an issue with using it with grayscale images? On a related note, I was wondering if the scale transform (or any other transform) is required for the image reader? If I try to use the Image Reader without any transforms, a runtime exception occurs when calling the CreateCompositeMinibatchSource function.

Thanks,
Michael

**Comment by eldakms** [comment]
Could you please try specifying:
imgDeserializer[L"grayscale"] = true?

Thank you!

**Comment by breckerm** [comment]
Thanks for your time and reply! That did seem to fix the issue. I did not see that that flag was available. I'll go ahead and close the issue.

Thanks!
Michael

**Comment by tomekjaworski** [comment]
Hi,
This problem still exists in Python API.

Best regards,
TJ
