### ISSUE TITLE
Visual Studio 2015 compiles CNTK project error

### ISSUE THREAD

**Issue by zzf123000** [Microsoft/CNTK#1988]
Visual Studio 2015 compiles CNTK project error

------ 已启动生成: 项目: MathCUDA, 配置: Release x64 ------
1>Compiling CUDA source file GPUMatrix.cu...
1>
1>F:\file_doc\CNTK-master\CNTK-master\Source\Math>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_50,code=\"sm_52,compute_50\" --use-local-env --cl-version 2015 -Xcompiler /WX -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\x86_amd64"  -I"F:\file_doc\CNTK-master\CNTK-master\Source\Common\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"G:\develop_kit\cub-1.6.4\cub-1.6.4" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"   -lineinfo --keep --keep-dir F:\file_doc\CNTK-master\CNTK-master\x64\.build\Release\Source\Math\\MathCUDA -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=field_without_dll_interface" -Xcompiler "/wd 4819"   -use_fast_math -DNO_SYNC -DWIN32 -D_WINDOWS -D_USRDLL -DMATH_EXPORTS -DUSE_CUDNN -D_UNICODE -DUNICODE -DNDEBUG -D"CNTK_COMPONENT_VERSION=\"2.0\"" -DHAS_MPI=1 -Xcompiler "/EHsc /W4 /nologo /O2 /FS /Zi  /MD " -o F:\file_doc\CNTK-master\CNTK-master\x64\.build\Release\Source\Math\\MathCUDA\GPUMatrix.cu.obj "F:\file_doc\CNTK-master\CNTK-master\Source\Math\GPUMatrix.cu"
1>GPUMatrix.cu
1>CUDACOMPILE : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 8.0.targets(689,9): error MSB3722: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe" -gencode=arch=compute_50,code=\"sm_52,compute_50\" --use-local-env --cl-version 2015 -Xcompiler /WX -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\bin\x86_amd64"  -I"F:\file_doc\CNTK-master\CNTK-master\Source\Common\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"G:\develop_kit\cub-1.6.4\cub-1.6.4" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"   -lineinfo --keep --keep-dir F:\file_doc\CNTK-master\CNTK-master\x64\.build\Release\Source\Math\\MathCUDA -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=field_without_dll_interface" -Xcompiler "/wd 4819"   -use_fast_math -DNO_SYNC -DWIN32 -D_WINDOWS -D_USRDLL -DMATH_EXPORTS -DUSE_CUDNN -D_UNICODE -DUNICODE -DNDEBUG -D"CNTK_COMPONENT_VERSION=\"2.0\"" -DHAS_MPI=1 -Xcompiler "/EHsc /W4 /nologo /O2 /FS /Zi  /MD " -o F:\file_doc\CNTK-master\CNTK-master\x64\.build\Release\Source\Math\\MathCUDA\GPUMatrix.cu.obj "F:\file_doc\CNTK-master\CNTK-master\Source\Math\GPUMatrix.cu"”已退出，返回代码为 5。请验证您是否拥有运行此命令的足够权限。
1>已完成生成项目“MathCUDA.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

1>CUDACOMPILE : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)

According to the analysis is probably CUB :: DeviceRadixSort problems, see https://github.com/NVlabs/cub/issues/90
Ask how to amend?

**Comment by zzf123000** [comment]
In fact, set C / C + + CUDA -> Code Generation: compute_35, sm_35, will be able to successfully generated. How can I set the Code Generation: compute_50, sm_50; compute_52, sm_52 configuration can also succeed in the gtx 970 maxwell Compute Capability 5.2?

**Comment by bencherian** [comment]
You are using CUB 1.6.4. The documentation explicitly says that only CUB 1.4.1 is supported. I've had the same problem when I decided to try building with CUB 1.6.4 to see if it would work, but I don't know enough (or really anything) about CUDA to troubleshoot these issues. I imagine it's a compiler bug, because even invalid source code shouldn't cause nvcc to crash.

**Comment by Eths33** [comment]
bencherian, thanks your reply helped me too. 
I can't find where on their page or gethub that they say that. 
Would be good to know to watch if it changes in the future.

**Comment by wolfma61** [comment]
CUB1.6 should work with the master bits, it will be officially enabled in the next release.

In master we currently build the release version with compute_50,sm_50, compute_60,sm_60, compute_62,sm_62

In addition you can set environment variables for your build: 


| Environment Variable | |
|:------------|:-------------|
|CNTK_CUDA_CODEGEN_DEBUG CNTK_CUDA_CODEGEN_RELEASE | With these environment variables you can define the NVidia Compiler target architectures. For example, setting a variable to `compute_35,sm_35;compute_50,sm_50` will only build level 3.5 and 5.0 compatible cubin and PTX information. For detailed information about this refer to the NVidia Compiler documentation.
