### ISSUE TITLE
need a way to execute precompute actions only

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#199]
To be able to use the Mean node to precompute a mean and store it in a file (cf. Issue #132), it would be desirable to be able to run SGD until after precomputation and then stop. I.e. the result of this SGD would be to the model after precomputation. A natural way would be to set maxEpochs = 0. However, this will currently terminate the training early, even before checking for precomputation.

**Comment by wolfma61** [comment]
shouldn't the added extensibility and new feature cover this? If you still require this, please open a new issue with a detailed requirement specification
