### ISSUE TITLE
No GPUs found on deployment node with GPUs, when CNTK was compiled on a node with no GPUs

### ISSUE THREAD

**Issue by ujjwal-researcher** [Microsoft/CNTK#1990]
So, I compiled CNTK successfully (GPU build) on a node on a server - that node had no GPUs. Then I just allocated a GPU node for testing the distribution - it could not detect any  GPU. 
However, when I compiled on the GPU node and tested on it, it worked perfectly. I am just trying to get an insight into this behavior and if it is normal.

Below, I give the description for the case when I compiled on the Non-GPU node. For the GPU node, everything remained exactly the same. So, I don't understand this behavior.

**OS Release and distro**
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core)
Release:	7.2.1511
Codename:	Core

```
**Kernel version**
`3.10.0-327.22.2.el7.x86_64`

**Installation type**

- Installed from sources

- Commit hash of the source : `274924836b6aea688f0a5225334862168c40acea`

- Python version : `3.6.0`

- Anaconda distribution version : `conda 4.3.21`

- CUDA version : `8.0` 

- CUDA driver version : `367.48`

- CUDNN version : `5.1.5`

**CNTK Build info**
```
Build info:

		Built time: Jun 11 2017 02:09:03
		Last modified date: Fri Jun  9 10:55:23 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: yes
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: /misc/opt/cuda/8.0
		CUB_PATH: /home/uujjwal/cntk/cub-1.4.1
		CUDNN_PATH: /misc/opt/cudnn/5.1-cuda-8.0
		Build Branch: master
		Build SHA1: 274924836b6aea688f0a5225334862168c40acea (modified)
		Built by Source/CNTK/buildinfo.h$$0 on nef-devel2
		Build Path: /home/uujjwal/cntk/CNTK
		MPI distribution: Open MPI
		MPI version: 1.10.3
```
**Output of `cntk configFile=lr_bs.cntk makeMode=false deviceId=auto
` in `$CNTK_CLONE_DIR/Tutorials/HelloWorld-LogisticRegression`**
```

-------------------------------------------------------------------
No GPUs found

##############################################################################
#                                                                            #
# Train command (train action)                                               #
#                                                                            #
##############################################################################


Model has 9 nodes. Using CPU.
<Rest is the result log of the CPU output>
```

**Comment by junjieqian** [comment]
One quick questions regarding
`		CUDA_PATH: /misc/opt/cuda/8.0;
CUB_PATH: /home/uujjwal/cntk/cub-1.4.1;
CUDNN_PATH: /misc/opt/cudnn/5.1-cuda-8.0`

Do you have the same lib paths on both machines (for building and testing)?

**Comment by ujjwal-researcher** [comment]
Yes. They are the same. Infact entire configuration is exactly the same on both the nodes. The difference is only in the availability of GPUs.

**Comment by junjieqian** [comment]
Hmm, I do not think the presence of GPU is essential in building here. I will try it on my local devbox to see if I can repro this.

**Comment by ujjwal-researcher** [comment]
Yes. GPU presence is not essential. Library presence. What is weird however is, that in my case, unless I compiled on the machine with a GPU, it did not work (the libraries being exactly the same across the two nodes). 

I will also check that with the present setup can I use cntk on some other node (with the same libraries) but a different GPU. If it does not work, then something has to be looked very deep into the CNTK configuration.

**Comment by ujjwal-researcher** [comment]
**Update**

I tested the present setup on another node which has the same libraries but different GPU (GTX 1080 (Pascal) ) , and it seems to work.

You can see the present configuration down. It also shows that the build was done on nefgpu10. Just repeating my original observation that when I built CNTK using the same libraries but not on a GPU node, it did not work on nefgpu10.
```

Build info:

		Built time: Jun 11 2017 03:27:41
		Last modified date: Fri Jun  9 10:55:23 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: yes
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: /misc/opt/cuda/8.0
		CUB_PATH: /home/uujjwal/cntk/cub-1.4.1
		CUDNN_PATH: /misc/opt/cudnn/5.1-cuda-8.0
		Build Branch: master
		Build SHA1: 274924836b6aea688f0a5225334862168c40acea (modified)
		Built by Source/CNTK/buildinfo.h$$0 on nefgpu10
		Build Path: /home/uujjwal/cntk/CNTK
		MPI distribution: Open MPI
		MPI version: 1.10.3
-------------------------------------------------------------------
-------------------------------------------------------------------
```

**Comment by wolfma61** [comment]
Independent of your hardware you can build CPU or GPU versions of CNTK, you will need to follow the instructions to set all your depencies/libraries correctly. 

For execution, if you have a GPU machine matching the requirements, installed CUDA/cuDNN correctly, you will be able to run a GPU version. If I understand correctly, your created binaries run on one machine correctly using GPU, check installation on the secondary machine and make sure MPI, CUDA, cuDNN libraries are up-to-date and accessible.

**Comment by wolfma61** [comment]
closing - please reopen if you still experience the issue
