### ISSUE TITLE
Can't run FAST RCNN Sample python A1_GenerateInputROIs.py, numpy boolean subtract, the `-` operator, is deprecated

### ISSUE THREAD

**Issue by alexiip** [Microsoft/CNTK#1991]
I am trying to run the FAST RCNN sample on Windows with Python35 and CNTK 2.0. When I run the  A1_GenerateInputROIs.py file I get the below error:

`...\selectivesearch\selectivesearch.py", line 238, in mycmp
    return cmp(x[1],y[1])
...

return (x > y) - (x < y)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.`

**Comment by martinezmiranda** [comment]
I've run into the same problem, which seems to come from an import of the past.builtings module (http://python-future.org/_modules/past/builtins/misc.html) which is using that deprecated operator.

It seems modifying line 235 in selectivesearch.py with *return int(x > y) - int(x < y)* does the trick

**Comment by FDecaYed** [comment]
It is introduced by numpy 1.13.0
[https://docs.scipy.org/doc/numpy-dev/release.html](url)
'subtract(bool_, bool_), TypeError when subtracting boolean from boolean.'

I agree with the solution @martinezmiranda suggested.
I did not notice line 235 is the only place cmp() being used so I write an cmp() function exactly `return int(x > y) - int(x < y)` at the time.

**Comment by kyoro1** [comment]
Tentatively, I downgrade the version of `numpy` to `1.11.0`, I have succeeded in executing A1:

```sh
(py35)
$ pip install numpy==1.11.0
Collecting numpy==1.11.0
  Downloading numpy-1.11.0-cp35-none-win_amd64.whl (7.6MB)
Installing collected packages: numpy
  Found existing installation: numpy 1.13.0
    Uninstalling numpy-1.13.0:
      Successfully uninstalled numpy-1.13.0
Successfully installed numpy-1.11.0
(py35)
$ python A1_GenerateInputROIs.py
--------------------------------------------------------------
2017-07-26 10:28:50
PARAMETERS: datasetName = Grocery
PARAMETERS: cntk_nrRois = 100
0 20 positive WIN_20160803_11_29_07_Pro.jpg
Calling selective search..
  :
```

**Comment by cha-zhang** [comment]
Closing this for now since we now use dlib selective search in FastRCNN example.
