### ISSUE TITLE
Old (3+ months) python wheels in CNTK docs (new ones needed for Keras compatibility)

### ISSUE THREAD

**Issue by tjrileywisc** [Microsoft/CNTK#1993]
Can the wheels here be updated? The article was posted in early April, so I'd assume the wheels are about that old or older.

https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python

Thanks!

**Comment by wolfma61** [comment]
these are the latest wheels matching the 2.0 release. These are the up-to-date / most recent wheel files

thx
Wolfgang

**Comment by SNCI** [comment]
https://cntk.ai/PythonWheel/GPU/cntk-2.0-cp35-cp35m-win_amd64.whl
is not a supported wheel on this platform

I am using conda with p3.5.2 and CUDA 8 (works for Tensorflow)
Anyone else having this problem?

**Comment by wolfma61** [comment]
Please take a look here: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python

>>>We have been testing CNTK with Anaconda3 4.1.1 (64-bit) and Python versions 2.7, 3.4, 3.5, as well as Anaconda3 4.3.1 with Python version 3.6. If you do not have a Anaconda3 Python installation, install Anaconda3 4.1.1 Python for Windows (64-bit).

I'm going to close this issue, since the original issue was solved.
Please open a new issue if you have further problems

thx
Wolfgang
