### ISSUE TITLE
create CNTK binary download

### ISSUE THREAD

**Issue by wolfma61** [Microsoft/CNTK#2]
binary download from Codeplex is out-of-date. 
 Need a new binary download for current version of CNTK build

**Comment by polidore** [comment]
+1

**Comment by digulla** [comment]
The Wiki page https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration promises that the release page contains a package with `cntk.exe` but there isn't one. Please fix this (even when the current release is only a beta) for users which just want to try out the tool.

**Comment by pannous** [comment]
+10e100 

wasting an hour with compilation errors is not encouraging

**Comment by eldakms** [comment]
Try https://github.com/Microsoft/CNTK/releases

**Comment by digulla** [comment]
@eldakms This is a source-only release. The binaries are missing.

**Comment by chrisbasoglu** [comment]
@digulla, the windows binary (including cntk.exe) was placed at https://github.com/Microsoft/CNTK/releases in listed zip file.

**Comment by eldakms** [comment]
It will become public in a short time :) Being drafted.

**Comment by alexeyo26** [comment]
The first release is published. We have a small issue with building Linux binaries, so I leave this issue open for a while. We will update the release with Linux binaries soon.

**Comment by alexeyo26** [comment]
Linux bits are also there.

**Comment by digulla** [comment]
Can you please also create a CPU-only build? Should I open a new bug for this?

**Comment by alexeyo26** [comment]
We working on CPU bits. Will take some days. Then we will publish and notify everybody.

**Comment by gaizkan** [comment]
CPU-only is now available for building. Can someone make the bits available?

**Comment by digulla** [comment]
Thanks :+1:
