### ISSUE TITLE
renderCmd not working on Linux?

### ISSUE THREAD

**Issue by jnbntz** [Microsoft/CNTK#200]
Hi.  I'm running Ubuntu 14.04 and the renderCmd doesn't seem to be working properly.  I have a topoplot block defined as follows:

```
topoplot = [
  action = "plot"
  outputdotFile="model.dot"
  outputFile="model.jpg"
  renderCmd="/usr/bin/dot -Tjpg <IN> -o<OUT>"
] # end topoplot
```

Then when I run CNTK, the following is from the output.

```
Output network description in dot language to model.dot
Executing a third-part tool for rendering dot:

Done
COMPLETED
```

The "model.dot" file is generated properly but the JPG file is not generated.  In fact the command isn't even printed to the screen.  It seems "rescmd" from Source/ActionsLib/OtherActions.cpp is possibly not being set properly?

**Comment by frankseide** [comment]
Does it generate the .dot file correctly? I.e. can you view it manually?

**Comment by jnbntz** [comment]
Yes the dot file is generated correctly.

**Comment by yqwangustc** [comment]
It is confirmed that regex before gcc 4.9.0 is buggy (http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions) and in this case, it causes the issue. 

I have submitted a code review to change std::regex to std::replace. It will commit into master after reviewing and testing.
