### ISSUE TITLE
Is there any way using CNTK to recognize numbers in an image? 

### ISSUE THREAD

**Issue by yashfujifilm** [Microsoft/CNTK#2000]
I have tried [Microsoft OCR API](https://westus.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fc) to recognize numbers but I want better results? Is there any way using CNTK?
I have read about Keras. Is it useful in my case? I want to use the trained model (trained on MNIST dataset) for reading the digits present in images. 
Need some suggestions.

**Comment by Spiderixius** [comment]
Try checking some of the examples in under [Image](https://github.com/Microsoft/CNTK/tree/master/Examples/Image).
