### ISSUE TITLE
New data transformation protocols : What do developers think ?

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#2001]
In CNTK random flipping or color distortions can be introduced. There are however other data augmentation protocols as well, such as in the following paper -

> Sermanet, Pierre, et al. "Overfeat: Integrated recognition, localization and detection using convolutional networks." arXiv preprint arXiv:1312.6229 (2013).

To summarise it does the following -

1. The smaller dimension of each input image is resized to 256 pixels.
2. 5 random crops are then taken from the image and their flipped versions are also taken.
3. These are then fed as the input to the network. 

You can see that if this protocol is used and then random color distortions are used then a huge augmentation based diversity can be achieved during the training. Of course this increases the time taken to traverse through an epoch, but it also provides for a huge sampling of the dataset probability distribution.

For my work, I am currently implementing this method in CNTK and it seems that CNTK source code level changes need to be introduced.

Would it be a good idea to introduce such new protocols in the library ? I want to know the thoughts of the core team, so that I know whether it is good to send in a pull request for that. 

**NOTE** 
This protocol is missing from all other libraries I know and many people I know, do think that such a protocol is needless. Hence, I want to gather the thoughts of the core team on this matter, if it is good to introduce such protocols in the codebase.

**Comment by JohnCraigPublic** [comment]
I do all image transformations (for augmentation and other reasons) outside of CNTK and its environment, and then convert and write out the images in a format so that the CTNK Text format reader can read them.
It seems odd to me to want to rely on CNTK having all sort of features for imaging -- that is available from other sources.  CNTK has enough to focus on with its core mission.  My opinion FWIW.

**Comment by ujjwal-researcher** [comment]
In the situation I described, augmentation is dynamic. So, Augmentation has to take place during the training. So, one needs augmentation facilities to be a part of CNTK

**Comment by cha-zhang** [comment]
cntk.io.transforms.crop, you can specify crop_type = 'multiview10'. 

We have a multiview crop test in BrainScript here: 
https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/ReaderTests/Config/ImageReaderMultiView_Config.cntk 

We don't seem to have an example for that in Python.

**Comment by spandantiwari** [comment]
@ujjwal-researcher Could you explain what you mean by "augmentation is dynamic"? I am just trying to understand this better. Is there something that blocks you from doing it outside of CNTK as @JohnCraigPublic is suggesting? Or are you thinking about speed/performance issues related to doing outside the CNTK graph?

**Comment by spandantiwari** [comment]
Closing this for now. Please reopen with more info (see above) if needed.

**Comment by dashesy** [comment]
@spandantiwari In the current FasterRCNN example, after each epoch the images could be flipped. I think that may be an example of "dynamic augmentation"
