### ISSUE TITLE
Can we do beam search decoding in CNTK v2.0 with Python?

### ISSUE THREAD

**Issue by meijiesky** [Microsoft/CNTK#2006]
I know that beam search can be done in BrainScript. I am using Python and I can only have the greedy decoder. However, I want to generate multiple output sequences using seq2seq model. I am wondering how I can achieve that. Thank you so much!

**Comment by n17s** [comment]
Note that beam search will still output a single answer. The only difference is that the answer is better than the greedy search in terms of (the model's) joint probability. To output multiple answers you just need to replace the `hardmax` operation in the seq2seq tutorial with a `sampling` operation. To sample you can use the  so gumbel-max trick:
```python
@C.Function
def sampling(x):
    perturbed_x = x + C.random.gumbel_like(x)
    return C.hardmax(perturbed_x)
```
Replacing `hardmax` with `sampling` will sample different sequences each time you run the evaluation. If you want even more diversity you can shrink `x` a little e.g. by multiplying with a number less than 1.

I'm closing this thread, feel free to reopen.
