### ISSUE TITLE
How to initialize parameters using normal distribution

### ISSUE THREAD

**Issue by wd929** [Microsoft/CNTK#2008]
If I want to initialize parameters using normal distribution N(0,1), how can I do in CNTK? I am confused about fan-in and fan-out as it is not very easy to understand.

**Comment by ebarsoumMS** [comment]
Is that for python or BrainScript? For Python, it will be something like the below.

import CNTK as C

W = C.parameter((...), init=C.normal(1.0), name='W')

**Comment by wd929** [comment]
I am using BrainScript. How can I do this?

**Comment by cha-zhang** [comment]
In BrainScript you can do: 

ConvolutionalLayer {384, (3:3), pad = true, init='normal', initValueScale=0.01}
