### ISSUE TITLE
Exception Thrown Midway Through Video Example

### ISSUE THREAD

**Issue by mikemanski** [Microsoft/CNTK#2009]
**Are there any known issues with the video Python example?** 

I followed all the steps for setting up CNTK 2.0 in Python (GPU version, no 1-bit SGD). I ran the quick installation test & everything seems to check out. 
When I followed all the directions in the video example, it trains until about the 6th epoch, and then an exception is thrown at line 480 of ffmeg.py (OSError: Could not load meta information). I looked at the video clip that corresponded with self._filename at the point the exception was thrown, and it's there, correctly named, and plays just fine. So I don't think it's a problem with that particular video clip.

If it helps, I'm running Windows 7 x64, Anaconda3 (4.4) w/ Python 3.6. I'm running all the the commands through the Anaconda3 prompt, since there's an installation of Anaconda2 w/ Python 2.7 in my PATH environment variable that I don't want to get mixed up with. My GPU is the Quadro K2200, which I confirmed is compatible with CUDA 8.0.

I had the GPU & CPU versions of CNTK 1.7 building from source & working on this machine about a while back, in case that's important.
I'd really appreciate any advice on this; I'm pretty stuck. And I'm not well-versed in Python, so debugging this issue is very difficult. 

**This was the output:**
```
Selected CPU as the process wide default device.

Build info:

                Built time: May 31 2017 11:06:01
                Last modified date: Sun May 21 10:32:51 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
                CUB_PATH: c:\local\cub-1.4.1
                CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v5.1
                Build Branch: HEAD
                Build SHA1: ade8bc05d30e61160da729aee078e22f8bd4fced
                Built by svcphil on DPHAIM-22
                Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTKv2LibraryDll\
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6


Training 15986507 parameters in 20 parameter tensors.

Learning rate per sample: 0.01
Momentum per sample: 0.9997558891748972
Finished Epoch[1 of 30]: [Training] loss = 2.393175 * 1291, metric = 87.22% * 12
91 7008.756s (  0.2 samples/s);
Finished Epoch[2 of 30]: [Training] loss = 2.380563 * 1291, metric = 85.90% * 12
91 6988.824s (  0.2 samples/s);
Finished Epoch[3 of 30]: [Training] loss = 2.341270 * 1291, metric = 83.89% * 12
91 6992.700s (  0.2 samples/s);
Finished Epoch[4 of 30]: [Training] loss = 2.247387 * 1291, metric = 77.92% * 12
91 6976.637s (  0.2 samples/s);
Finished Epoch[5 of 30]: [Training] loss = 2.230730 * 1291, metric = 78.39% * 12
91 6988.481s (  0.2 samples/s);
Traceback (most recent call last):
  File "Conv3D_UCF11.py", line 245, in <module>
    conv3d_ucf11(train_reader, test_reader)
  File "Conv3D_UCF11.py", line 211, in conv3d_ucf11
    videos, labels, current_minibatch = train_reader.next_minibatch(train_minibatch_size)
  File "Conv3D_UCF11.py", line 90, in next_minibatch
    inputs[idx - self.batch_start, :, :, :, :] = self._select_features(self.video_files[index])
  File "Conv3D_UCF11.py", line 101, in _select_features
    video_reader = imageio.get_reader(video_file, 'ffmpeg')
  File "C:\Users\mwilmanski\AppData\Local\Continuum\Anaconda3\lib\site-packages\imageio\core\functions.py", line 129, in get_reader
    return format.get_reader(request)
  File "C:\Users\mwilmanski\AppData\Local\Continuum\Anaconda3\lib\site-packages\imageio\core\format.py", line 169, in get_reader
    return self.Reader(self, request)
  File "C:\Users\mwilmanski\AppData\Local\Continuum\Anaconda3\lib\site-packages\imageio\core\format.py", line 218, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Users\mwilmanski\AppData\Local\Continuum\Anaconda3\lib\site-packages\imageio\plugins\ffmpeg.py", line 327, in _open
    self._load_infos()
  File "C:\Users\mwilmanski\AppData\Local\Continuum\Anaconda3\lib\site-packages\imageio\plugins\ffmpeg.py", line 480, in _load_infos
    raise IOError(fmt % err2)
OSError: Could not load meta information
=== stderr ===
```

**Comment by mikemanski** [comment]
I fixed this. I'm pretty certain the thing that made the biggest difference was upgrading the driver, since the output now says "Selected GPU[0] Quadro K2200 as the process wide default device" instead of CPU. I upgraded to "Release 375 from the ‘Optimal Drivers for Enterprise’ [ODE] branch" for Quadro cards.
This wasn't something I initially thought to do since I've used the old driver version on other examples & previous CNTK versions & never had a problem.

### Below are the exact steps I took when fixing this 

I uninstalled Anaconda3 & reinstalled. I then added the Anaconda3 directories to my default user Path environment variable and got rid of the parts that pointed to Anaconda2 - **this is so I could run the Python commands from regular command prompt instead the Anaconda prompt** (I had read there were issues with using the Anaconda prompt for other scenarios).

Then, I reinstalled the GPU version of CNTK via Python.

Then, I updated my GPU driver as described above and restarted my computer to apply various updates.

I re-followed the video example steps (this time using regular cmd, not Anaconda prompt), and it started working as it's supposed to.

**Comment by xforceco** [comment]
I encounter `IOError: Could not load meta information` in video example.
And fix it by, `pip install --upgrade pip` and `pip install --upgrade imageio`

**Comment by imriss** [comment]
It might be because of a short timeout setting. Upstream PR in imageio to increase the timeout interval:
https://github.com/imageio/imageio/pull/282
