### ISSUE TITLE
CNTK centos6.2 build error(CuDnnConvolutionEngine.o)

### ISSUE THREAD

**Issue by HyacinthJingjing** [Microsoft/CNTK#201]
Hi,
I would like to build cntk with cuda 7.0 on centos6.2. However, i have tried a few times building a new CNTK and failed. It seems to have something to do with the CuDnnConvolutionEngine. Please help.
Thanks.

=-----------------------------------------------------------=
mpic++ -c Source/ComputationNetworkLib/ComputationNetworkBuilder.cpp -o /root/CNTK/build/release/.build/Source/ComputationNetworkLib/ComputationNetworkBuilder.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/CNTK/build/release/.build/Source/ComputationNetworkLib/ComputationNetworkBuilder.d
creating /root/CNTK/build/release/.build/Source/ComputationNetworkLib/ComputationNetworkScripting.o for with build type release
mpic++ -c Source/ComputationNetworkLib/ComputationNetworkScripting.cpp -o /root/CNTK/build/release/.build/Source/ComputationNetworkLib/ComputationNetworkScripting.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/CNTK/build/release/.build/Source/ComputationNetworkLib/ComputationNetworkScripting.d
=-----------------------------------------------------------=
In file included from Source/Math/ConvolutionEngine.cpp:8:0:
Source/Math/CuDnnConvolutionEngine.h:34:47: error: 'PoolDesc' is not a class, namespace, or enumeration
     PoolDescPtr CreatePoolDescriptor(typename PoolDesc::PoolKind kind, size_t w, size_t h, size_t wStride, size_t hStride, size_t wPad, size_t hPad) override;
                                               ^
creating /root/CNTK/build/release/.build/Source/SGDLib/Profiler.o for with build type release
Source/Math/ConvolutionEngine.cpp: In member function 'void Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::ForwardCore(const typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Tensor4D&, const typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Mat&, const typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Filter&, const typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Mat&, const typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::ConvDesc&, const typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Tensor4D&, typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Mat&, typename Microsoft::MSR::CNTK::DefaultConvolutionEngine<ElemType>::Base::Mat&)':
Source/Math/ConvolutionEngine.cpp:271:44: error: invalid use of qualified-name '::ConvolveAndWeightedAdd'
                 Mat::ConvolveAndWeightedAdd(1, filter, false, inputSubBatch, false, 0, outputSubBatch,
                                            ^
Source/Math/ConvolutionEngine.cpp:287:31: error: invalid use of qualified-name '::Multiply'
                 Mat::Multiply(filter, false, workspace, false, outputSubBatch);
                               ^
=-----------------------------------------------------------=
Source/Math/ConvolutionEngine.cpp: In member function 'void Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::ForwardCore(const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Tensor4D&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Mat&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::PoolDesc&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Tensor4D&, typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Mat&)':
Source/Math/ConvolutionEngine.cpp:564:32: error: 'PoolDesc' is not a class, namespace, or enumeration
         if (poolDesc.kind() == PoolDesc::PoolKind::Max)
                                ^
Source/Math/ConvolutionEngine.cpp:570:37: error: 'PoolDesc' is not a class, namespace, or enumeration
         else if (poolDesc.kind() == PoolDesc::PoolKind::Average)
                                     ^
Source/Math/ConvolutionEngine.cpp: In member function 'void Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::BackwardCore(const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Tensor4D&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Mat&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Mat&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::PoolDesc&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Tensor4D&, const typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Mat&, typename Microsoft::MSR::CNTK::DefaultPoolingEngine<ElemType>::Base::Mat&)':
Source/Math/ConvolutionEngine.cpp:582:32: error: 'PoolDesc' is not a class, namespace, or enumeration
         if (poolDesc.kind() == PoolDesc::PoolKind::Max)
                                ^
Source/Math/ConvolutionEngine.cpp:589:37: error: 'PoolDesc' is not a class, namespace, or enumeration
         else if (poolDesc.kind() == PoolDesc::PoolKind::Average)
                                     ^
Source/Math/ConvolutionEngine.cpp: At global scope:
Source/Math/ConvolutionEngine.cpp:637:47: error: 'PoolDesc' is not a class, namespace, or enumeration
     PoolDescPtr CreatePoolDescriptor(typename PoolDesc::PoolKind kind, size_t w, size_t h, size_t wStride, size_t hStride, size_t wPad, size_t hPad) override
                                               ^
mpic++ -c Source/SGDLib/Profiler.cpp -o /root/CNTK/build/release/.build/Source/SGDLib/Profiler.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/CNTK/build/release/.build/Source/SGDLib/Profiler.d
creating /root/CNTK/build/release/.build/Source/SGDLib/SGD.o for with build type release
mpic++ -c Source/SGDLib/SGD.cpp -o /root/CNTK/build/release/.build/Source/SGDLib/SGD.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/CNTK/build/release/.build/Source/SGDLib/SGD.d
=-----------------------------------------------------------=
creating /root/CNTK/build/release/.build/Source/ActionsLib/TrainActions.o for with build type release
=-----------------------------------------------------------=
mpic++ -c Source/ActionsLib/TrainActions.cpp -o /root/CNTK/build/release/.build/Source/ActionsLib/TrainActions.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/CNTK/build/release/.build/Source/ActionsLib/TrainActions.d
creating /root/CNTK/build/release/.build/Source/ActionsLib/EvalActions.o for with build type release
mpic++ -c Source/ActionsLib/EvalActions.cpp -o /root/CNTK/build/release/.build/Source/ActionsLib/EvalActions.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/CNTK/build/release/.build/Source/ActionsLib/EvalActions.d
=-----------------------------------------------------------=
...

**Comment by wolfma61** [comment]
We don't support centOs, we test on Ubuntu with gcc 4.8.4

in addition there are different versions of cuDnn available, and you should make sure you installed the correct one (see issue #127 and issue #130 )

**Comment by HyacinthJingjing** [comment]
Thanks for your reply.
The problem above has been solved after compiling on centos with gcc 4.8.4. Originally the version of gcc is 4.8.0.
