### ISSUE TITLE
how to write cntk output in a binary file format?

### ISSUE THREAD

**Issue by ShagReza** [Microsoft/CNTK#2012]
I'm working on a classification problem. the number of classes is about 6000.
because of big amount of test data, the output text file will be so large
 Therefore I rather to write  the outputs in binary format versus text.
Is it possible in cntk?

**Comment by eldakms** [comment]
If python - you can use whatever format you need. If BrainScript, you can use HTKMLFWriter to write in htk binary format. binarywriter is legacy with a proprietary format , I would not recommend using it.
