### ISSUE TITLE
Segmentation fault after running `python FeedForwardNet.py`

### ISSUE THREAD

**Issue by budiryan** [Microsoft/CNTK#2013]
![image](https://user-images.githubusercontent.com/16099586/27256078-1ee8036c-53de-11e7-9043-b32a000d6da1.png)

**Comment by cha-zhang** [comment]
Is FeedForwardNet your own model? Could you share the model?

**Comment by ebarsoumMS** [comment]
Can you provide  repro steps and which platform did you run on, then reactivate the issue?
