### ISSUE TITLE
Failed to lock GPU 0 for Exclusive Use

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#2014]
Sometimes, on my shiny new Alienware laptop with a NVIDia GTX1080 GPU, when I run my training BrainScript, I get the message "Failed to lock GPU 0 for Exclusive Use" and the training defaults to CPU.

What is the meaning of this error message?   What would cause it to "Fail to Lock"?

In the past, when this happened, I could re-boot the PC and try again, and it would always then use the GPU without issue.  But today, that trick has stopped working -- even after a reboot I get this message, and I am stuck in CPU land.   

Any ideas?

**Comment by JohnCraigPublic** [comment]
So, now I tried launching my train with specification of the DeviceID, as in:

cntk configFile=Foo.cntk DeviceID=0

and it worked!  It selected the GPU without issue.  Hmm... was that just random luck?

I have been running BrainScripts for months now and never needed to specify DeviceID and now, today, I have to.    Hmmm....

**Comment by meijiesky** [comment]
Yesterday, I set traceLevel = 0 and the whole process got stuck. However, when I change traceLevel to 1 it runs. Interesting............
