### ISSUE TITLE
FFT

### ISSUE THREAD

**Issue by cschuelke** [Microsoft/CNTK#2016]
Hello,

Is there a way to perform FFT on the GPU using CNTK? I haven't found anything about this in the documentation.

Thanks in advance,
Christophe

**Comment by ebarsoum** [comment]
Sadly, this isn't implemented yet.  Can you provide more details on your scenario?

**Comment by cschuelke** [comment]
Thanks for your answer!
I'm working on problems in medical imaging, where the Fourier transform is ubiquitous. I will use TF for the time being...
