### ISSUE TITLE
Control over threads number in Evaluation API

### ISSUE THREAD

**Issue by krzysztof-nowak** [Microsoft/CNTK#2017]
I wrote a C++ program to evaluate my pretrained network. I had based my implemetation on CNTKLibraryCPPEvalCPUOnlyExamples/EvalMultithreads.cpp file, in particular RunEvaluationOneHidden(...) function. I do not use any threading explicitly and run the linux version of the library.

My model is created by:
`CNTK::FunctionPtr model = CNTK::Function::Load("mymodel")`

I noticed that a call to
`model->Forward({{input_var, input_val}}, outputs, CNTK::DeviceDescriptor::CPUDevice());`
tries to utilize all available threads, but this is not desirable in my setup. Is there a way to limit usage to only one thread?

**Comment by eldakms** [comment]
Did you try uing cntk_py.set_max_num_cputhreads(1)? (SetMaxNumCPUThreads in c++)

**Comment by krzysztof-nowak** [comment]
Thank you, this answers my question. It is working well now.
