### ISSUE TITLE
Load Pretrained Caffe Converted Models Failed

### ISSUE THREAD

**Issue by SamaraRen** [Microsoft/CNTK#2018]
Hi,

Is there any example script for running the caffe converted AlexNet model under CNTK/Examples/Image/Classification/AlexNet. I was able to run the CNTK Pre-trained model, but when I tried to load the caffe-converted in the same way, I got segmentation fault. 

I tried modifying the stack size to 65536 kb but it didn't help.

System Specs:
Ubuntu 16.04
Python 3.5
CNTK 2.0

Thank you!

**Comment by yuxiaoguo** [comment]
Hi, @SamaraRen 

We tested loading converted AlexNet model in Windows and seemed on problem. Indeed, the converted AlexNet from Caffe model zoo has some difference with that of CNTK. The original AlexNet uses Group in convolution layer. In CNTK, we need to use a combination of splice/slice/convolution to simulate the operation. Thus, the converted model has more ops than that of CNTK. This maybe the reason to cause your segmentation fault in Linux.

I think you may try to load a ResNet-152 in your environment. If you can't load the model either, it should be the stack size issue.
