### ISSUE TITLE
no module named cntk._cntk_py on Python 3.4.5 (CentOS 6.9)

### ISSUE THREAD

**Issue by ChongWu-Biostat** [Microsoft/CNTK#2019]
This issue is similar to #1361 

I am running cntk-2.0 on Python 3.4.5 on CentOS 6.9. The installation process using PIP is Ok. However, I got the following error messages when I try to load it:

In [1]: import cntk
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/panwei/wuxx0845/.local/lib/python3.4/site-packages/cntk/cntk_py.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

/panfs/roc/itascasoft/python3/3.4-conda/lib/python3.4/importlib/__init__.py in import_module(name, package)
    108             level += 1
--> 109     return _bootstrap._gcd_import(name[level:], package, level)
    110 

/panfs/roc/itascasoft/python3/3.4-conda/lib/python3.4/importlib/_bootstrap.py in _gcd_import(name, package, level)

/panfs/roc/itascasoft/python3/3.4-conda/lib/python3.4/importlib/_bootstrap.py in _find_and_load(name, import_)

/panfs/roc/itascasoft/python3/3.4-conda/lib/python3.4/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ImportError: No module named 'cntk._cntk_py'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-6b467b8c6865> in <module>()
----> 1 import cntk

/home/panwei/wuxx0845/.local/lib/python3.4/site-packages/cntk/__init__.py in <module>()
      8 import numpy as np
      9 
---> 10 from . import cntk_py
     11 
     12 #

/home/panwei/wuxx0845/.local/lib/python3.4/site-packages/cntk/cntk_py.py in <module>()
     19         except ImportError:
     20             return importlib.import_module('_cntk_py')
---> 21     _cntk_py = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):

/home/panwei/wuxx0845/.local/lib/python3.4/site-packages/cntk/cntk_py.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_cntk_py')
     21     _cntk_py = swig_import_helper()
     22     del swig_import_helper

/panfs/roc/itascasoft/python3/3.4-conda/lib/python3.4/importlib/__init__.py in import_module(name, package)
    107                 break
    108             level += 1
--> 109     return _bootstrap._gcd_import(name[level:], package, level)
    110 
    111 

ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory

**Comment by mahilleb-msft** [comment]
Hi @ChongWu-Biostat ,
  our current CNTK binaries requires OpenMPI as a dependency, even for a Python-only installation. Please see [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python#prerequisites). If no suitable binary package is available on CentOS, you may need to build from source.
  Let me know if this helps.

  Best, Mark

**Comment by BrendonLynch** [comment]
didn't work on CentOS with python-only installation,even with openMPI installed
