### ISSUE TITLE
Failed to perform sequence training with Kaldi example

### ISSUE THREAD

**Issue by vmswork** [Microsoft/CNTK#202]
Hi,

When trying to run sequence training this exception occurs:
EXCEPTION occurred: NotifyFunctionValuesMBSizeModified: objectives InputValue operation had its col dimension 256 changed by the reader to 1, but different from MBLayout.

> Starting minibatch loop.
> 
> [CALL STACK]
>   /home/superuser/lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::logic_error>::CollectCallStack(std::function<void (std::string)> const&, std::function<void ()> const&)  + 0x101 )  [0x7f4999ccce41]
>   /home/superuser/lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::logic_error>::PrintCallStack()  + 0x88  )  [0x7f4999ccd2d8]
>   cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::logic_error>(char const*, ...)  + 0xe2  )  [0x5439e2]
>   cntk                           ( Microsoft::MSR::CNTK::ComputationNode<float>::NotifyFunctionValuesMBSizeModified()  + 0x496 )  [0x544a36]
>   cntk                           ( bool Microsoft::MSR::CNTK::DataReaderHelpers::GetMinibatchIntoNetwork<float>(Microsoft::MSR::CNTK::IDataReader<float>&, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, bool, bool, std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<float>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<float>*> > >&, unsigned long&)  + 0x1f7 )  [0x71f777]
>   cntk                           ( Microsoft::MSR::CNTK::SGD<float>::TrainOneEpoch(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&, int, unsigned long, Microsoft::MSR::CNTK::IDataReader<float>*, double, unsigned long, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::map<std::basic_string<wchar_t, s  cntk                           ( Microsoft::MSR::CNTK::SGD<float>::TrainOrAdaptModel(int, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, bool, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*)  + 0x1218)  [0x72a908]
>   cntk                           ( Microsoft::MSR::CNTK::SGD<float>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*, bool)  + 0x424 )  [0x72c764]
>   cntk                           ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x22c )  [0x74853c]
>   cntk                           ( void DoCommands<float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x804 )  [0x596bb4]
>   cntk                           ( wmainOldCNTKConfig(int, wchar_t**)        + 0x909 )  [0x53aae9]
>   cntk                           ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53b140]
>   cntk                           ( main                                      + 0xd8  )  [0x52fdb8]
>   /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf5  )  [0x7f4998931ec5]
>   cntk                           (                                                   )  [0x533b84]
> EXCEPTION occurred: NotifyFunctionValuesMBSizeModified: objectives InputValue operation had its col dimension 256 changed by the reader to 1, but different from MBLayout.
> 

I suppose this may be related with this fixed bug  https://github.com/Microsoft/CNTK/issues/65.
Can anyone help with this?

**Comment by yzhang87** [comment]
Are you using the latest version?

**Comment by vmswork** [comment]
I cloned from master last sunday and applied https://github.com/Microsoft/CNTK/pull/154 to build with kaldi support.
numUttsPerMinibatch  is 1

**Comment by chenguoguo** [comment]
I think we know what's the problem now. I will work on a patch, but it will be Monday -- I only have network access through my mobile phone right now...

**Comment by chenguoguo** [comment]
I have created a patch for @yzhang87 to test. He will submit a pull request soon.

**Comment by yzhang87** [comment]
@vmswork Send a pull request. You can fork my branch if you need it now.

**Comment by vmswork** [comment]
Thanks. Training seems to work, but It hasn't finished yet.

**Comment by vmswork** [comment]
Sequence training is finished and has resulted the expected performance gain.

**Comment by frankseide** [comment]
Thanks so much!
