### ISSUE TITLE
How to convert sequence variable to variable?

### ISSUE THREAD

**Issue by lmatt-bit** [Microsoft/CNTK#2021]
for example: 

```
hid_state = C.sequence.input_variable(hid)
input = C.input_variable((sequence_length, hid)) # sequence_length equals to the sequence length of hid_state
gru_layer = C.layers.GRU(hid)
output = gru_layer(input, hid_state)
```

Is there any way to covert hid_state to match the dims of input? so that i can get the result of gru_layer(input, hid_state) as variable instead of sequence.

**Comment by n17s** [comment]
A few clarifications are in order here:
- GRU is just a recurrent *unit*, i.e. it is only computing a single step
- To use it in a recurrence you have to wrap it in a function such as layers.Recurrence (returns the output at each time step) or layers.Fold (returns the output at the last time step).
- To use a recurrence the input must have a sequence axis. If you use C.sequence.input_variable you have a sequence axis. If you use C.input_variable you do not.
- There are ways to convert a variable with a sequence axis to another variable with an additional leading static axis and vice versa. The functions that do this are C.to_sequence (and C.to_sequence_like) and C.sequence.unpack.

**Comment by lmatt-bit** [comment]
@n17s Thanks for you answer, that should resolve my question.
