### ISSUE TITLE
Object detection using Fast R-CNN: TypeError: roipooling() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by StuartRucker** [Microsoft/CNTK#2023]
Upon following the installation directions for python in the "Object detection using Fast R-CNN," (https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN) I was able to run A1_GenerateInputROIs.py, but then when I run A2_RunWithPyModel.py, I encounter this error: 

~~~~File "A2_RunWithPyModel.py", line 213, in <module>
    trained_model = train_fast_rcnn()
  File "A2_RunWithPyModel.py", line 145, in train_fast_rcnn
    frcn_output = frcn_predictor(image_input, roi_input, num_classes, model_path)
  File "A2_RunWithPyModel.py", line 113, in frcn_predictor
    roi_out   = roipooling(conv_out, rois, C.MAX_POOLING, (roi_dim, roi_dim), 0.0625)
  File "C:[my local path]\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds) 
TypeError: roipooling() takes from 3 to 4 positional arguments but 5 were given

**Comment by StuartRucker** [comment]
I found a workaround, which is to simply use the A2_RunWithBSModel.py instead (after ofcourse, following these installation directions A2_RunWithPyModel.py). However, I still am uncertain about the answer

**Comment by cha-zhang** [comment]
Seems to be a version issue. Which CNTK version are you using?

**Comment by StuartRucker** [comment]
Installed from `https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl` for python 3.5 on windows. 


> Built time: May 31 2017 11:18:33
>                 Last modified date: Sun May 21 10:47:00 2017
>                 Build type: Release
>                 Build target: CPU-only
>                 With 1bit-SGD: no
>                 With ASGD: yes
>                 Math lib: mkl
>                 Build Branch: HEAD
>                 Build SHA1: ade8bc05d30e61160da729aee078e22f8bd4fced
>                 Built by svcphil on LIANA-09-w
>                 Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTKv2LibraryDll\
>                 MPI distribution: Microsoft MPI
>                 MPI version: 7.0.12437.6

```

**Comment by Aki1987** [comment]
I had same problem. my anaconda version 3 4.4.0, python 3.6, cntk- Cpu-Gpu. When I run A2_RunWithBSModel.py, problem has takeplaced. I dont know why, please help!!!

**Comment by StuartRucker** [comment]
^ I am using Anaconda 3 too, with python 3.5

**Comment by pkranen** [comment]
There has been an update to the roi pooling layer in master. It is now the same as in caffe. If you are using the latest A2 script from master but you did not compile the latest master code then there is a mismatch between the two. The new roi pooling signature is `roipooling(operand, rois, pooling_type, output_shape, spatial_scale, name='')` where `spatial_scale` is the new argument corresponding to the ratio between the resolution of the input operand (i.e. the convolutional feature map) and the original image input. For AlexNet and VGG it is 1/16 in both cases. Another important thing to know is that now the roi pooling layer expects rois in absolute pixel coordinates of the form `(x_min, y_min, x_max, y_max)`, again same as caffe.

**Comment by Aki1987** [comment]
Thanks pkranen.
It means that I should reinstall caffe version included in fast-r-cnn right?

**Comment by Aki1987** [comment]
I have run the older version of fast-r-cnn with none error.
https://github.com/Azure/ObjectDetectionUsingCntk
Thanks so much!

**Comment by jinwonkim93** [comment]
i am also having the same error. how did you able to solve the problem?

**Comment by cha-zhang** [comment]
You can resolve it by installing binary version of CNTK 2.0 GA, or you can sync the current master to build yourself, or you can wait till end of July for the next release. 

Sorry for the inconvenience. The current master always contains new things that may not be compatible with the latest official release.

**Comment by Aki1987** [comment]
Did you run fast-r-cnn in right folder.
Please carefully unzip cntk-master.zip (C:\local\cntk-2-0). After that, run cmd as manager that all.

**Comment by jinwonkim93** [comment]
cha-zhang i am trying to find binary version of CNTK 2.0 GA could you give me a link to its install tutorial site?

**Comment by jinwonkim93** [comment]
aki1987 i have tried to start all over again but it is still not working.

**Comment by wolfma61** [comment]
@jinwonkim93 See our documentation site: https://docs.microsoft.com/en-us/cognitive-toolkit/
'getting started' section

**Comment by kushsi** [comment]
Try this installation method
https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Binary-Script
This works for me.
