### ISSUE TITLE
How to stack vectors in CNTK?

### ISSUE THREAD

**Issue by irrawaddy28** [Microsoft/CNTK#2024]
Suppose there are N column vectors v1, v2, ..., vN, each of size Dx1. Is there a way to create a matrix V such that  V = [v1 v2 ... vN] where V = D x N matrix?

**Comment by irrawaddy28** [comment]
Assume v1, v2, ..., vN are distinct compute nodes.

**Comment by boeddeker** [comment]
If I remember correct, cntk.ops.splice can do that.

**Comment by irrawaddy28** [comment]
If I am using BS and N = 5, will it look something like this?
V = Splice (v1:v2:v3:v4:v5, axis=2)    # axis = 2 for column stack

**Comment by irrawaddy28** [comment]
Thanks, that works
