### ISSUE TITLE
Feature request for adding Image Data to TensorBoard using CNTK

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#2026]
Many times it is necessary to visualize filter behaviors during training to assess the training quality, as well as to do some basic hyper-parameter adjustments. Adding Image summaries to TensorBoard would be a great feature. Unfortunately this feature is not yet available in CNTK. 

I request some action to be taken for this important feature. 
I am willing to work on it, if someone can give me appropriate pointers to approach in the right direction.

**Comment by duli2012** [comment]
We are working on TensorBoard image support, and will ship it in our next release. You are certainly welcome to contribute to it once our first implementation is out. 
Thanks.

**Comment by duli2012** [comment]
The TensorBoard image support is released in CNTK 2. I close this issue now.
