### ISSUE TITLE
How to add a layer to a trained DNN

### ISSUE THREAD

**Issue by wd929** [Microsoft/CNTK#2027]
I want to use the trained DNN as an initialization and add a new layer to it and train them together. How can I use MEL or brainscript to do this?

**Comment by hajix** [comment]
I know solution in both python and mel. The mel solution is as follow:

1- add `copy_weight` to command list, which is defined like:

```
copy_weight = [
    action = edit
    raw_model = $ModelDir$/your_new_model_instance/cntkSpeech.dnn
    pretrained_model = $ModelDir$/path_to_pretrained_model/cntkSpeech.dnn
    new_model = $ModelDir$/where_new_model_will_be_saved/cntkSpeech.dnn.0

    editPath = $ConfigDir$/path_to_mel_script/copy_layers.mel
]
```
2- create mel script like:

```
# load models
raw_model_param = LoadModel($raw_model$, format="cntk")
pretrained_model_param = LoadModel($pretrained_model$, format="cntk")
SetDefaultModel(raw_model_param)

# copy nodes from pretrained models to raw model
# layer 1
Copy(pretrained_model_param.FFL1.BFF.*, raw_model_param.FFL1.BFF.*, copy=value)
# if need to fix parameters, turn needsGradient off
SetProperty(raw_model_param.FFL1.BFF.*, needsGradient, false)

# save model
SaveModel(raw_model_param, $new_model$, format="cntk")
```

python solution is too simple. After loading model, you can find your specified layer by its name and set its value:

```
In [1]: import cntk

In [2]: model = cntk.load_model('Model/model_3_epoch.cntk')
Selected GPU[0] GeForce GTX 1060 6GB as the process wide default device.

In [3]: import numpy as np

In [4]: model.L1.W
Out[4]: Parameter('W', [], [165 x 128])

In [5]: model.L1.W.value = np.random.random((165, 128))
```

**Comment by wd929** [comment]
I do not have a "raw_model_param". I have a trained 6 layer DNN, and I want to get the first 5 layers' parameters as an initialization and create a new bottleneck layer and train them together. How can I do this? And I also try to use cloneFuction in brainscript but it seem that because my node name contains [ ], the node can not be found. :(

**Comment by wd929** [comment]
I do not have a "raw_model_param". I have a trained 6 layer DNN, and I want
to get the first 5 layers' parameters as an initialization and create a new
bottleneck layer and train them together. How can I do this? And I also try
to use cloneFuction in brainscript but it seem that because my node name
contains [ ], the node can not be found. :(

2017-06-23 21:01 GMT+08:00 mohammad hasan sohan ajini <
notifications@github.com>:

**Comment by cha-zhang** [comment]
Did you look at the fast RCNN example: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN 

In https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/fastrcnn.cntk the model is edited inside BrainScript.
