### ISSUE TITLE
Using the trained model in CNTK Fast R-CNN ?

### ISSUE THREAD

**Issue by kshivam26** [Microsoft/CNTK#2034]
Sir,
I have trained the model and I want to know on how can i use the trained model to test on new images.

**Comment by DHOFM** [comment]
Have a look here: https://github.com/CatalystCode/CNTK-FastRCNNDetector

**Comment by kshivam26** [comment]
Thanks for the link sir. But even if there are more than one objects of class A, it is able to detect only one object of that particular class.

**Comment by kshivam26** [comment]
Adding update to the issue, 'applyNonMaximaSuppression' function returns the indices of the rois but the list returned contains only one index and this is resulting in only one object detection in the image provided.

**Comment by DHOFM** [comment]
I guess you are testing the Pascal VOC Dataset and are running into the same problem like me. See the discussion with nadav here: https://github.com/CatalystCode/CNTK-FastRCNNDetector/issues/1 That could solve your problem...
