### ISSUE TITLE
Faster R CNN

### ISSUE THREAD

**Issue by DHOFM** [Microsoft/CNTK#2037]
Will there be support for Faster R CNN in the official repo soon - or is it "safe" to use the tools here: https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/utils ? In my case for object detection with faster r cnn intead of selective search ROI Finding

**Comment by cha-zhang** [comment]
It's safe to use the tools. They have been verified to be identical to Caffe implementation. We are working on Faster RCNN and ETA mid-July, maybe sooner.

**Comment by DHOFM** [comment]
@cha-zhang Thanks for the response. So if you are still working on Faster RCNN - will there be more improvements referring to the tools above or is it only migrating the tools into the next official release of cntk ?

**Comment by cha-zhang** [comment]
There won't be improvements because the tools above matches with Caffe implementation exactly. 

We have all the modules for Faster RCNN in CNTK, we are working hard to match the accuracy numbers on Pascal VOC. As a CNTK tradition, we do our best to verify our scripts before officially releasing them.

**Comment by DHOFM** [comment]
@cha-zhang Thanks again for your response. So if i test the tools on Pascal Voc should i retrain the model with the new ROIs found by the Faster R CNN before evaluating new images against the model with the new code ?

**Comment by cha-zhang** [comment]
Yes, I think so. 

The latest Faster RCNN code is in a branch: pkranen/fasterRcnn. It's not finalized though.
