### ISSUE TITLE
Emit warnings for deprecated BrainScript syntax

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2038]
BrainScript is very nice, and is evolving toward a more consistent syntax. However, it's not always clear what is the _recommended_ syntax. For example:

* `Parameter` vs `ParameterTensor`
* `SparseInput` vs `Input{HDim, sparse=true}`
* `ErrorPrediction` vs `ClassificationError`
* using `()` rather than `{}`
* etc

Supporting the old syntax, at least for a while, is mostly a good thing, but it would be much better if `cntk.exe` what hinting, through warnings, that some bits are considered as deprecated.

**Comment by wolfma61** [comment]
It is not planned to remove syntax at this point. 
On top of that, it is `policy` to have at least one point release cycle of 'deprecated' notice on API which are going to change/remove. We are trying to stick with it ;)
