### ISSUE TITLE
How to load existing model??

### ISSUE THREAD

**Issue by edwardcho** [Microsoft/CNTK#2041]
Hello All,
I used ImageNet sample of GoogLeNet (python code).
In train_and_test(), model file was saved.

So I had tried this model file.
At first, in create_bn_inception_by_exist_model()
I used "z = load_model()", instead of "z = bn_inception_model()"
And, I called evaluation functions of train_and_test().
--
    while sample_count < test_epoch_size:
        current_minibatch = min(test_minibatch_size, test_epoch_size - sample_count)
        # Fetch next test min batch.
        data = test_source.next_minibatch(current_minibatch, input_map=input_map)
        # minibatch data to be trained with
        metric_numer += trainer.test_minibatch(data) * current_minibatch
--

But, I met some error.
The message of error is as follows,
    metric_numer += trainer.test_minibatch(data) * current_minibatch
  File "/home/mirero/anaconda2/lib/python2.7/site-packages/cntk/train/trainer.py", line 223, in test_minibatch
    return super(Trainer, self).test_minibatch(arguments, device)
  File "/home/mirero/anaconda2/lib/python2.7/site-packages/cntk/cntk_py.py", line 2466, in test_minibatch
    return _cntk_py.Evaluator_test_minibatch(self, *args)
ValueError: Values for 1 required arguments 'Input('Input3', [#], [3 x 224 x 224])', that the requested output(s) 'Output('aggregateEvalMetric', [], []), Output('Block58191_Output_0', [#], [1])' depend on, have not been provided.
...

What's the matter?? Should I do modify it??

Thanks.

**Comment by raaaar** [comment]
Input variables used by the loaded models are different from the ones that were originally used to construct the model (when model is being inflated all variables and functions are created anew as independent objects that have different identify from the primitives in the original model). To use the loaded model you need to redefine the input map using new inputs variables (the way it's done [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/A2_RunWithPyModel.py#L182)):

input_map = {
        z.arguments[0]: test_source[first_input_stream_name],
        z.arguments[1]: test_source[second_input_stream_name],
        ... etc ...
    }

**Comment by edwardcho** [comment]
Thank you for your response, raaaar.
But for this problem, I did not closed.

According to your comments, I modified my source.
....
#    input_map = {
#        network['feature']: train_source.streams.features,
#        network['label']: train_source.streams.labels
#    }
    test_input_map = {                     # <<- I made this for testing.
         network['feature']: test_source.streams.features,
         network['label']: test_source.streams.labels
    }
...
# data = train_re_source.next_minibatch(current_minibatch, input_map=input_map)      # old
data = train_re_source.next_minibatch(current_minibatch, input_map=test_input_map)   # new code...

I'm sorry but the error same..
...
metric_numer += trainer.test_minibatch(data) * current_minibatch
File "/home/mirero/anaconda2/lib/python2.7/site-packages/cntk/train/trainer.py", line 223, in
    return super(Trainer, self).test_minibatch(arguments, device)
  File "/home/mirero/anaconda2/lib/python2.7/site-packages/cntk/cntk_py.py", line 2466, in test_
    return _cntk_py.Evaluator_test_minibatch(self, *args)
ValueError: Values for 1 required arguments 'Input('Input3', [#], [3 x 224 x 224])', that the reput('aggregateEvalMetric', [], []), Output('Block4979_Output_0', [#], [1])' depend on, have not ..

**Comment by woskii** [comment]
Same error.Do you fix it?
