### ISSUE TITLE
Incorrect hierarchy in public documentation around the 'Convolution' page

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2042]
The page [Convolution](https://docs.microsoft.com/en-us/cognitive-toolkit/Convolution) acts as a page hierarchy  ; however most inner pages are not relevant to the _convolution_ topic. For example, [Dropout](https://docs.microsoft.com/en-us/cognitive-toolkit/Dropout) is placed as sub-topic of _convolution_ while it obviously isn't.

It would probably make sense to _flatten_ most of this hierarchy. This would make this part of the documentation a lot more discoverable.

**Comment by sayanpa** [comment]
Thanks for the feedback. We have updated the documentation. It is one of the priority areas for the team.
