### ISSUE TITLE
Inconsistent data type specification for the binary reader

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2046]
In the file `ctf2bin.py`, at line 47, we have:

        output.write(struct.pack('B', self.get_matrix_type()))

This indicates that the matrix type is treated as 1-byte encoding.

Then in the [online documentation](https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-CNTKBinary-Reader) the same field is specified as type `int32_t`.

There is also the same problem for:

        output.write(struct.pack('B', self.element_type))

Could you clarify which option should be considered as the correct one?

**Comment by raaaar** [comment]
Unfortunately, the binary format documentation is a little stale and not reflect the most recent format overhaul. It should be updated fairly soon. Stay tuned.
