### ISSUE TITLE
Clarify BinaryReader vs. CNTKBinaryReader

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2048]
I am trying to write a .NET/C# writer that match the binary data format of CNTK. I am, however, a bit at a loss when considering `BinaryReader` vs `CNTKBinaryReader`. The `CNTKBinaryReader` seems to be the most recent implementation, but the underlying motivation is very unclear to me.

It would really help if I could get a few questions answered:

* What is the go-to option in CNTK for the binary data format?
* What was the underlying motivation for this format? (vs. the previous one)

**Comment by raaaar** [comment]
- `BinaryReader` is a (monolithic) legacy reader, [this page](https://github.com/Microsoft/CNTK/blob/master/Documentation/Documents/Configuration%20Files.md#binaryreader) provides some info on the format and the intended usage scenarios.  
- `CNTKBinaryReader` is a deserializer designed according to the new reader architecture, which basically means that it can be combined with stand-alone randomizers, packers, transformers (i.e., standard components that are included in the ReadersLib). It's meant to be the go-to option for binary format and we're working to make it available in Python in the near future.
