### ISSUE TITLE
Would there be appetite for Gitter chat?

### ISSUE THREAD

**Issue by veikkoeeva** [Microsoft/CNTK#2049]
Hi!

I didn't see a mention of a chat channel of any kind. Would there be appetive for something like [Gitter](https://gitter.im/)? Gitter seem to be popular in GH and even MS project, one example being [Orleans](https://github.com/dotnet/orleans).

It might be so that the core people could become ovewhelmed, but having a discussion channel is also a great way to stay _on the pulse of the community_ so to speak.

**Comment by cha-zhang** [comment]
We just created one: 
https://gitter.im/Microsoft/CNTK
