### ISSUE TITLE
Convert text into one hot vectors using LUSequenceReader

### ISSUE THREAD

**Issue by Likhit** [Microsoft/CNTK#205]
Hi,
From the examples given, I'm not able to understand how I can convert a set of sentences into a matrix of one-hot vectors. For example, I want a file containing sentences made of tab separated words in the form:

```
<SENT_START> <word1> <word2> ... <SENT_END> <label>
<SENT_START> <word1> <word2> ... <SENT_END> <label>
...
```

to be read just like a `UCIFastReader` would read a similar file with numbers instead, and convert each sentence into a matrix of one-hot vector (each word representing a row). This way I'll be able to apply a convolution net on top of this (like in this [article](http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/)).

**Comment by wolfma61** [comment]
By now the UCIFastReader has been deprecated. The CNTK Text Format Reader is the recommended reader (https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-cntktextformat-reader), in addition the reader architecture has been completely redesigned with an efficient exensibility option.

If you still experience problems, I would recommend StackOverflow as the ideal place for general CNTK questions (https://docs.microsoft.com/en-us/cognitive-toolkit/Feedback-Channels)
