### ISSUE TITLE
CNTK binary writer in C#, need help for code review

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2050]
Below, an early tentative of mine to port `ctf2bin.py` to C#/.NET. The code seems to work, but without covering all scenarios. The documentation for the CNTK binary format is absent, I proceeded through pure reverse engineering. Support to debug this early piece of logic would be highly appreciated. The code is stand-alone.

```
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace CNTKIO
{
    public enum CNTKMatrixEncodingType : byte
    {
        Dense = 0, 
        SparseCSC = 1,
    }

    public enum CNTKElementType : byte
    {
        Float = 0,
        Double = 1,
    }

    public class CNTKMatHeader
    {
        public string Name { get; }

        public CNTKMatrixEncodingType MatrixEncodingType { get; }

        public CNTKElementType ElementType { get; }

        public int SampleDimension { get; }

        public CNTKMatHeader(string name, 
            CNTKMatrixEncodingType matrixEncodingType, 
            CNTKElementType elementType, 
            int sampleDimension)
        {
            Name = name;
            MatrixEncodingType = matrixEncodingType;
            ElementType = elementType;
            SampleDimension = sampleDimension;
        }
    }

    /// <summary>Chunked columnar data storage.</summary>
    public class CNTKBinaryWriter
    {
        const ulong MagicNumber = 0x636e746b5f62696e;
        const int CbfVersion = 1;

        class Chunk
        {
            /// <summary>One writer per input stream.</summary>
            private readonly BinaryWriter[] _writers;
            private int _sequenceCount;
            private int _sampleCount;
            
            public Chunk(int inputStreamCount)
            {
                _writers = new BinaryWriter[inputStreamCount];
                for (var i = 0; i < inputStreamCount; i++)
                {
                    _writers[i] = new BinaryWriter(new MemoryStream());
                }

                _sequenceCount = 0;
                _sampleCount = 0;
            }

            public void WriteDense(int streamIndex, float[] values)
            {
                var writer = _writers[streamIndex];

                writer.Write(values.Length);
                for (var i = 0; i < values.Length; i++)
                {
                    writer.Write(values[i]);
                }

                _sampleCount += values.Length;
            }

            public void WriteSparse(int streamIndex, float value, int rowIndex)
            {
                var writer = _writers[streamIndex];

                writer.Write(1); // number of sub-sequences (numSamples)
                writer.Write(1); // number of non-zero values (nnz)
                writer.Write(value);
                writer.Write(rowIndex);
                writer.Write(1); // condensed column index

                _sampleCount += 1;
            }

            public void FinalizeSequence()
            {
                _sequenceCount++;
            }

            public ChunkStat FinalizeAndClear(BinaryWriter output)
            {
                output.Flush();
                var offset = output.BaseStream.Position;

                // intended as the number of samples within each sequence
                for (var i = 0; i < _sequenceCount; i++)
                {
                    // HACK: we are approximating the number of samples here
                    output.Write(_writers.Length);
                }

                // columnar data layout inside the chunk
                for (var i = 0; i < _writers.Length; i++)
                {
                    var writer = _writers[i];
                    var stream = (MemoryStream)writer.BaseStream;
                    stream.Position = 0;
                    stream.CopyTo(output.BaseStream);
                }

                // collect the stats
                var stat = new ChunkStat(offset,
                    /* num_sequences */ _sequenceCount,
                    /* num_samples*/ _sampleCount);

                // clear the chunk
                for (var i = 0; i < _writers.Length; i++)
                {
                    var writer = _writers[i];
                    var stream = (MemoryStream)writer.BaseStream;
                    stream.SetLength(0);
                }
                _sequenceCount = 0;
                _sampleCount = 0;

                return stat;
            }
        }

        public class ChunkStat
        {
            public long Offset { get; }

            public int NumSequences { get; }

            public int NumSamples { get; }

            public ChunkStat(long offset, int numSequences, int numSamples)
            {
                Offset = offset;
                NumSequences = numSequences;
                NumSamples = numSamples;
            }
        }

        private readonly BinaryWriter _writer;

        private readonly Chunk _currentChunk;

        private readonly List<ChunkStat> _chunkStats;

        public CNTKBinaryWriter(Stream stream, int inputStreamCount)
        {
            _writer = new BinaryWriter(stream, Encoding.ASCII, true);
            _currentChunk = new Chunk(inputStreamCount);

            _writer.Write(MagicNumber);
            _writer.Write(CbfVersion);
            _chunkStats = new List<ChunkStat>();
        }

        public void WriteDense(int streamIndex, float[] values)
        {
            _currentChunk.WriteDense(streamIndex, values);
        }

        public void WriteSparse(int streamIndex, float value, int rowIndex)
        {
            _currentChunk.WriteSparse(streamIndex, value, rowIndex);
        }

        public void FinalizeSequence()
        {
            _currentChunk.FinalizeSequence();
        }

        public void FinalizeChunk()
        {
            _chunkStats.Add(_currentChunk.FinalizeAndClear(_writer));
        }

        public void FinalizeFile(CNTKMatHeader[] headers)
        {
            _writer.Flush();
            var headerOffset = _writer.BaseStream.Position;

            _writer.Write(MagicNumber);
            _writer.Write(_chunkStats.Count); // number of chunks

            _writer.Write((int)headers.Length); // number of inputs
            foreach (var header in headers)
            {
                _writer.Write((byte)header.MatrixEncodingType);

                _writer.Write(header.Name.Length);
                foreach (var c in header.Name)
                {
                    _writer.Write(c);
                }

                _writer.Write((byte)header.ElementType);

                _writer.Write(header.SampleDimension);
            }

            // write chunk table table
            foreach (var stat in _chunkStats)
            {
                _writer.Write(stat.Offset);
                _writer.Write(stat.NumSequences);
                _writer.Write(stat.NumSamples);
            }

            // ZIP-style offset
            _writer.Write(headerOffset);
        }
    }
}
```

**Update 1:** After closer inspection of the C++ code, I have realized that the format is actually chunked and **columnar**. This brings a lot of changes to the C# code which was incorrectly adopting a tabular data layout. Yet, the problem remains that the binary data produce by the code above is still crashing `cntk.exe`, no error message given.

**Update 2:** After further inspection of the C++ code, I managed to get the C#/.NET logic (pasted above) working! So now, the binary output is processed by `cntk.exe`, and at first glance, results seem to make sense. 

More questions:

* what is the purpose of the array of integers at the very beginning of each chunk? Overall, this seems wasteful, as this data can be re-inferred by simply reading the chunk.
* is there a real net gain in using CSC format for sparse data? It's not even clear to me that we need sparse _matrices_, instead of mere sparse _vectors_ (but I might be wrong).

**Comment by veikkoeeva** [comment]
@vermorel Would it be possible to have this as a PR or somesuch for easier commenting?

**Comment by raaaar** [comment]
I'm sorry you had to reverse-engineer the format. The [binary format documentation](https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-CNTKBinary-Reader) is terribly out-of-date and the new format is not yet officially released (updating the docs is actually one of the last major milestones). 

Integers at the beginning of each chunk are sequence lengths in samples, which is clear from the comments in the [ctf2bin.py](https://github.com/Microsoft/CNTK/blob/master/Scripts/ctf2bin.py#L176). The reason to have them there is exactly that it allows to retrieve all metadata required by the reader (i.e., the number of samples for each sequence in a chunk, number of sequences in each chunk, see SequenceDescriptor and ChunkDescriptor in [Indexer.h](https://github.com/Microsoft/CNTK/blob/master/Source/Readers/ReaderLib/Indexer.h)) without having to parse the input. This is one of the constraints imposed by the current randomization implementation -- to create a schedule of when each chunk should be loaded, it first needs to construct a global timeline, which requires all this metainfo. It's possible to omit the number of samples when writing the actual sequence data, but the amount of space saved this way is too negligible to justify the bookkeeping overhead.

CSC is probably a misnomer in the context of binary sparse format, what we write are sparse samples (values + indices), size of each sample, total NNZ count and the number of samples in the sequence. I don't see how the space can be used more efficiently to encode sparse data.

PS. While all community contributions are welcomed and appreciated, I'm struggling to understand the point of this exercise? ctf2bin.py is an standalone tool that allows ctf data to be converted into the binary format, what value would implementing the same functionality in a different language add?

**Comment by veikkoeeva** [comment]
@raaaar Having all the tooling in .NET is one of the easiest go / no-go gateway decision points. One of the reasons is that every and each new tool to include adds maintenance burden (not to mention cognitive tax). A bit in the same sense that in MSDN C++ blogs one of the compiler guys wrote that every switch added accrues hundreds of thousands of dollars of maintenance costs over its lifetime.

With regards to larger community involvement, it's a rallying cry to have a good set of "native tools". It's your digital mold, if you will. If you look over at the TensorFlow castle, plenty of folks are going there since the _grokkability_ of the code base there is good and you can build on the work of others. Taking this particular example, someone well versed with C# and leisurely reading this piece of code could, over time, easily submit ad-hoc ten minutes worth of work (for an expert) and prevent bit rot, for instance. So even if the docs wouldn't be all up to date, someone could with little cognitive burden read the code. Maybe even submit a system do that. I'm serious, talk with @sergeybykov (summoning, but I don't want to come across the wrong way here, just pinging a guy who does a good job at promoting a project at Microsoft and see if he could help here) and guys. Or the F# people. I want this to work. :)

**Comment by raaaar** [comment]
All the general points you raised here are good and valid, however I tend to disagree with the specifics: 

1. As long as you cannot run .NET tooling under linux with minimal investment, having *all the tooling in .NET* is probably a no-go.  
2. There's already a tool that works on all platforms and can be easily compiled into a native executable. Why replicate the same tool in a different tech stack that is only supported by a single platform? More so, since, as you rightfully mentioned, extra tooling will put a maintenance burden. What exactly is the benefit here?

**Comment by vermorel** [comment]
@raaaar Thank you very much by you follow-up. Your explanations are very appreciated.

` ctf2bin.py` is a no-go for a .NET-driven software company. You do not want to put Python on your production server. Period. [More details on my blog](http://blog.vermorel.com/journal/2017/6/5/net-first-strategy-for-cntk.html).

Then, without even considering the tech stack angle, using ` ctf2bin.py` is about two orders of magnitude too slow for our requirements. The data is already available under high compact binary form, we cannot rely on text-format as a middleman for the conversion, that would be massively wasteful.

**Comment by raaaar** [comment]
Point taken, this is not a replica, but a proprietary tool that outputs cntk binary. Makes sense. I'm going to close this for now, but feel free to reach out if you have any questions.

**Comment by veikkoeeva** [comment]
@raaaar 
> Why replicate the same tool in a different tech stack that is only supported by a single platform? 
There is .NET Mono and .NET Standard that's cross-platform standard with .NET Core as cross-platform implementation (Linux and *BSD). I don't have extensive experience other platforms than Windows (for which I really would like to have .NET tooling), but I think the selling point of Microsoft and .NET is to run it well on all platforms. In any event, I don't want to give a feeling I'm rubbing this other than to raise a point that I feel having a good .NET story is important for choosing a library if one is developing on .NET (or MS platforms).

**Comment by vermorel** [comment]
@raaaar Thank you very for your follow-up. It goes without saying that the piece of code that I have posted above should be considered a public domain material (or MIT license if can help).

**Comment by wolfma61** [comment]
as was suggested, you should make it a pull request and that will take care of the licensing ....

**Comment by veikkoeeva** [comment]
@wolfma61 Not to mention easier commenting on improvements on the code. :)

**Comment by douglas125** [comment]
Would anyone mind giving a simple example of how to use this to write a binary file from, say, a list<float[]> of features/labels?

**Comment by vermorel** [comment]
@douglas125 I would suggest to keep an eay on #2271 . It's a better form of this early attempt. I will try to provide an example.
