### ISSUE TITLE
' Recurrence ' method is so weird

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#2051]
I will give an example.

First I built a model in which an LSTM cell is created and trained, then I save this model.

Then I load this model and get that LSTM cell from it.

Finally, I try to apply ' Recurrence' on the LSTM cell like:  f = C.layers.Recurrence(LSTM)

And I got error ' TypeError: positional argument 0 has a known shape, and cannot be passed a Variable of unknown shape'

Isn't it weird?????

**Comment by cha-zhang** [comment]
Could you post your complete code? There should be plenty of LSTM models in examples/tutorials. Did you try them?

**Comment by DabiaoMa** [comment]
@cha-zhang  

 Maybe I have figured it out the reason, I do dot know whether it is correct.

The 'LSTM' function I loaded from trained model is already signature-updated, so it has no placeholders.

But the method 'Recurrence' requires the step function to be not signature-updated, due to the use of ' 
ForwardDeclaration.resolve_to' which is just 'ForwardDeclaration.owner.replace_placeholders'.

So maybe the class 'Function' could have the method to transform a signature-updated function to one with only placeholders?

**Comment by n17s** [comment]
It is very hard to get back the original LSTM. Does the following workaround work for you? 
First, create your new recurrence with a new LSTM. Then copy the parameters from the original LSTM.
```python
original_lstm = C.layers.Recurrence(LSTM(200))(x)
# train....
# now let's say we want the recurrence to return the full state as well
new_lstm = C.layers.Recurrence(LSTM(200), return_full_state=True)(x)
for po, pn in zip(original_lstm.parameters, new_lstm.parameters)
    pn.value = po.value
```

**Comment by n17s** [comment]
Closing. Feel free to reopen.
