### ISSUE TITLE
cntk-2.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by telezhnaya** [Microsoft/CNTK#2055]
I've done everything strictly as in [this instruction](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python).
I have installed Python 3.6, pip 9.0.1 and Anaconda.

```
C:\Users\oltelezh>python3 -V
Python 3.6.1
```

```
C:\Users\oltelezh>python3 -m pip -V
pip 9.0.1 from C:\Users\oltelezh\AppData\Local\Programs\Python\Python36-32\lib\site-packages (python 3.6)
```

I do this:
```
python3 -m pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
```

And the result is:
```
cntk-2.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

Please help me to solve this issue. Thanks!

**Comment by wolfma61** [comment]
what version of Anaconda did you install? for Python 3.6 we tested with Anaconda3 4.3.1. I did a fresh install of that version on my machine - this is what I get:
```
C:\Anaconda343>python3
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\Anaconda343>python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
```
Your output looks very different, aren't you running in Anaconda? I don't have any path set to Anaconda, so to install I have to do this:
```
C:\Anaconda343>cd Scripts

C:\Anaconda343\Scripts>pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
Collecting cntk==2.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
  Downloading https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl (33.0MB)
    100% |████████████████████████████████| 33.0MB 34kB/s
Requirement already satisfied: scipy>=0.17 in c:\anaconda343\lib\site-packages (from cntk==2.0)
Requirement already satisfied: numpy>=1.11 in c:\anaconda343\lib\site-packages (from cntk==2.0)
Installing collected packages: cntk
Successfully installed cntk-2.0
```

I hope this helps ...

Wolfgang

**Comment by telezhnaya** [comment]
I have both python2 and python3 on my computer, if I write `python`, I invoke Python 2.7. So that's why I am writing `python3`.
If I write `pip`, I invoke pip for Python 2.7. That's why I am writing `python3 -m pip`. It works fine, I have tested it just today with `numpy` library.

See screenshot proof of the problem:

![image](https://user-images.githubusercontent.com/11246099/27626027-388d5678-5bef-11e7-8730-655bdd7b5417.png)

**Comment by wolfma61** [comment]
Hard to debug remotely, I would assume some environment variables on your computer which throw the installer off? pyversion, path, something like this?

with no python specific environment it works, so the WHL file is fine IMO ...
```
C:\Anaconda343>python -m pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
Collecting cntk==2.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
  Using cached https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: scipy>=0.17 in c:\anaconda343\lib\site-packages (from cntk==2.0)
Requirement already satisfied: numpy>=1.11 in c:\anaconda343\lib\site-packages (from cntk==2.0)
Installing collected packages: cntk
Successfully installed cntk-2.0
```

**Comment by telezhnaya** [comment]
I can delete any variables (by the way, I have no suspicious variables, in my opinion). 
I can give all logs (but I haven't any because CNTK provides me with only one phrase that you have seen).
I believe that in your computer everything works fine, but I does not solve my problem.

Is it possible to install CNTK for Python3 without deleting Python2?
I need both versions for different projects and everything works fine except CNTK library.

**Comment by telezhnaya** [comment]
And it's a common situation to name Python 3.6 as `python3` in command prompt. It is not just for me, I know really many people who name it this way.

**Comment by wolfma61** [comment]
I'm sorry that I don't have the solution for this. All I can say is that I have NO environment variable pointing to any python installation, and no python installation is in the path or anywhere else referenced. And with this setup I can't repo the problem ...

perhaps some other lurker has already experienced the issues and has a solution ...

**Comment by telezhnaya** [comment]
I have paths both to python2 and python3 executables in `PATH`, I usually use them from the command prompt, that's why I need it. Can it be a reason of the problem?

**Comment by wolfma61** [comment]
that was my theory - try with a clean environment, no pythonpath or other environment variables, a clean environment or an environment which only refers to the python you want to use

**Comment by telezhnaya** [comment]
The problem solved, you were right.
Developer can't use any other python installations. I have to delete everything from path about Python (So I can't use Python 2.7 now in appropriate way from console) and installation after it was successful.

**Comment by vickylance** [comment]
@telezhnaya I am also facing this issue but I dont have any other python installations or anything on my path except pointing to Anaconda installation.But I am still facing this issue.
