### ISSUE TITLE
Reader's symbols not loaded under 'Debug' configuration

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2057]
I am trying to run CNTK under the Visual Studio 2015 debugger to inspect what's happening within the reader's, and more specifically within `CNTKBinaryReader`. 

When I try to run `CNTK.exe` under the `Debug` mode, the break points are never reached because the symbols are not loaded. Indeed, in the `/Debug` folder, there is no `.pdb` to be found for the reader's library. 

When I attempt the same under the `Release` mode, the `.pdb` are generated and found, hence allowing me to debug the solution.

It's not overly clear what's missing in the `Debug` configuration, but it would make a lot of the sense to have all the elements required for debugging purposes, because this configuration should be the go-to configuration for troubleshooting purposes.

**Comment by eldakms** [comment]
Hi vermorel,

Do you build CNTK yourself? If yes - all pdbs should be located in CNTK/x64/Debug, including ones for the CNTKBinaryReader like on the picture below:
![image](https://user-images.githubusercontent.com/12430061/27677533-5d82f2bc-5cb2-11e7-8213-1d6bb799be92.png)

If you simply take the binary drop - we do not have debug version in there, we only ship release.
Thanks!

**Comment by vermorel** [comment]
@eldakms Yes, thanks to the support on the CNTK team, I did manage to build CNTK myself.

Yet, the picture that I have for the output of the build is quite different:

![cntk-debug](https://user-images.githubusercontent.com/932309/27705847-933529cc-5d0f-11e7-8bbd-e46cf7a2e42e.png)

I haven't touched the options of the `cntk.exe` project, and running the console app does work though.

Any idea what is going on?

**Comment by eldakms** [comment]
Did you rebuild the complete solution? Or only CNTK project? please build the whole solution, from the compilation point of view CNTK does not require readers to be build. Or right click on the readers you need and say Build. Thanks!

**Comment by vermorel** [comment]
@eldakms Thanks! It did work.

There was two gotchas. (1) Rebuild all is needed because, as you rightly point out there is no direct dependency for the readers for CNTK. (2) Symbols for the reader library are _not_ loaded immediately. Hence, in the debugger in Visual Studio, they will first appear with the warning _Symbols not loaded_; but the warning goes away when the reader library is finally dynamically loaded.
