### ISSUE TITLE
Guidance requested: .NET writer for CNTK binary data format and .NET reader for DNN models

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2058]
Two important pieces for .NET (see #960) are:

* a reader and a writer for the CNTK binary data format
* a reader and a writer for the CNTK model format

My team and I would be interested in making those contributions to the CNTK project. Matter of fact, this would be a C#/.NET library project (plus a second project for the unit tests) . Would it be possible to have this contribution part of the CNTK project?

If yes,

* Where to put the project folder? in `/bindings/csharp`?
* Where to put the test folder? in `/Tests/csharp`?

I would prefer to gather some feedback from the CNTK team before engaging in large pull request. Thanks!

@cha-zhang @wolfma61 I would love to have your feedback on this one.

**Comment by cha-zhang** [comment]
@vermorel is there any reason you don't want to use the current C# eval library to read/write CNTK models?

**Comment by vermorel** [comment]
@cha-zhang The goal is to be able to access the raw values of the learnable parameters themselves. I may have missed something the Eval C# API though.

**Comment by vermorel** [comment]
@wolfma61 Thank you very much for confirming the status of the access to learnable parameters. It's very appreciated. Then, indeed, the initial goal, as you rightly point out would be to have sample but working code. The intended usage would probably be to copy and paste the code; rather than shoot for a full blown Nuget package.

**Comment by wolfma61** [comment]
just a simple solution with a readme and some sample data would probably do it. Again, not sure where it makes sense from the layout of the cntk github project. ```script``` would be logical, although it is not a script. But we can figure this out. I believe you are also still waiting to have us publishing the binary format. as @raaar said, this is coming shortly ...

**Comment by vermorel** [comment]
@wolfma61 Agreed `/Script` makes sense as it hints non-core.

**Comment by JimSEOW** [comment]
@vermorel thanks for suggesting this very useful .net feature
