### ISSUE TITLE
Read CSV? (UCIFastReader now Deprecated)

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/CNTK#2060]
Hey Folks,

I have data in a .csv file, 'c:/data/experiment/train.csv'  I'm trying to figure out how to read this in using the CTFDeserializer or whatever the latest deserializer is for .csv files.  The data is of the format:

Columns: Feature1, Feature2, ..., FeatureN, Label1, Label2, ..., LabelN

guidance, pointers, samples are greatly appreciated.  I found that I can put the data into the following format:

|features stuff |labels stuff

But I already have .csv files and much of the data I get in is in .csv format.  Here are some sample rows:
2	9160	8AM-10AM	Fri	0.462264	0.545455	0.358974	116	11 5 9.2
3	4929	11AM-12PM	Fri	0.509434	0.363636	0.538462	179	3 7 11.12
4	5008	3PM-4PM	Fri	0.481132	0.204545	0.461538	67	3 9 8.7

Thanks!

**Comment by raaaar** [comment]
CSV with arbitrary data types (i.e., dates) is not supported. But it should be fairly straight-forward to convert your data to a format CNTK understands (say, CTF). Take a look at [uci2ctf.py](https://github.com/Microsoft/CNTK/blob/master/Scripts/uci2ctf.py), it should get you started.
