### ISSUE TITLE
CTC example

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#2062]
Hi

Please develop an example in python API using forward_backward node as its criterion node.

@vmazalov 
regards

**Comment by vmazalov** [comment]
Here we go https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_208_Speech_Connectionist_Temporal_Classification.ipynb

**Comment by delzac** [comment]
For anyone looking for a CTC Encoder to convert your labels into the ctc data format that cntk will accept you can check out my extension library [cntkx](https://github.com/delzac/cntkx), it has a `CTCEncoder` to help do just that.
