### ISSUE TITLE
Adam optimizer parameters are not clear

### ISSUE THREAD

**Issue by ujjwal-researcher** [Microsoft/CNTK#2063]
Adam optimizer's parameters are not clear in CNTK
While beta1 = 0.9 can be set as momentum parameter, 

how does one set the beta2 parameter ?

**Comment by cha-zhang** [comment]
Alpha is the learning_rate
Beta1 is momentum parameter
Beta2 is variance_momentum parameter

**Comment by ujjwal-researcher** [comment]
That makes it a little weird.

The default setup for Beta2 in CNTK is momentum_as_time_constant_schedule(720000) 

This value is way too high as compared to the default values proposed by the ADAM authors. 

Why is this the case ? Or is it that there is some non-linear relationship between the two values ? 

When I set momentum_as_time_constant_schedule(0.999), none of my networks converge. The default CNTK value however works okay. Is there some non-linear relationship I am missing ?

**Comment by cha-zhang** [comment]
You misunderstand momentum as constant. There is momentum_as_time_constant_schedule and momentum_schedule. If you want to use 0,999, you should use momentum_schedule. Check reference here: 
https://cntk.ai/pythondocs/cntk.learners.html?highlight=momentum#cntk.learners.momentum_as_time_constant_schedule

**Comment by cha-zhang** [comment]
We will soon post a manual here: 
https://github.com/Microsoft/CNTK/tree/master/Manual 
which will explain in more detail.

**Comment by ujjwal-researcher** [comment]
Thank you. This reminder was very helpful. Thank you again.
