### ISSUE TITLE
undifiined reference to boost library

### ISSUE THREAD

**Issue by berlloon** [Microsoft/CNTK#2066]
I wanna compile CNTK via source code. folloing the [tutorial ](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Linux).
Everything works fun until the make procedure. The terminal outputs thousand of error information like

undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'

But I indeed compiled boost as tutorial does. I installed the boost in /home/software/ml/cntk_20170628/Dependencies/boost_1_60_0

and specify the location via the following in configure
--with-boost=/home/software/ml/cntk_20170628/Dependencies/boost_1_60_0

I also tried export LD_LIBRARY_PATH=/home/software/ml/cntk_20170628/Dependencies/boost_1_60_0:$LD_LIBRARY_PATH, nothing changed.
Any suggestions? Thanks very much.

**Comment by mahilleb-msft** [comment]
Hi @berlloon, sorry for the trouble...
Could you compile with "make -j 1" (i.e., not in parallel) and include a log for the compilation errors? Also, you should have a file Config.make in your build directory, can you paste its contents, too?
Just double-checking - for boost you followed these compilation steps (except for changing `--prefix` ?):
```
sudo apt-get install libbz2-dev
sudo apt-get install python-dev
wget -q -O - https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz/download | tar -xzf - 
cd boost_1_60_0 
./bootstrap.sh --prefix=/usr/local/boost-1.60.0
sudo ./b2 -d0 -j"$(nproc)" install
```
I.e., you included the install in the end.

Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing for now... Please feel to re-open when you can share more details! Thanks...
