### ISSUE TITLE
CNTK Resnet trained model loading issue 

### ISSUE THREAD

**Issue by hariprasad4c9** [Microsoft/CNTK#2067]
I got following exception when tried to load one of the Resnet model trained with adaption mechanism.
Error: Unknown error.
Native CallStack:
[CALL STACK]
    > Microsoft::MSR::CNTK::GetEvalExtended(double)
    - Microsoft::MSR::CNTK::GetEvalExtended(double)   (x3)
    - Microsoft::MSR::CNTK::GetEval(double)
    - 00007FFAEB05A4B3 (SymFromAddr() error: The specified module could not be found.)

 Inner Exception: No Inner Exception

This is happened  when I am trying to load the model using IEvaluateModelManaged(float).CreateNetwork method provided in Cntk.Eval.Wrapper-2.0

**Comment by zhouwangzw** [comment]
@hariprasad4c9 Is your model trained with BrainScript or Python? and with float or double precision? I see both "double" and "float" in your message. The same precision should be used as the training time.

**Comment by zhouwangzw** [comment]
I hope that the issue has been resolved. I am closing the issue due to lack of responses. Please feel free to open an issue, if you still have questions/problems.
