### ISSUE TITLE
C# Eval Error Unknown DataType

### ISSUE THREAD

**Issue by JeffScherrer** [Microsoft/CNTK#2068]
I've created/trained a model in Python. The model expects sequence data, like the language understanding tutorial. I'm now trying to evaluate my trained model in C#, and I'm following the CNTKLibraryCSEvalCPUOnlyExamples sequence example. I've tried both the onehot and the sparse example. The error I get when I call Function.Evaluate is:

```
Unknown DataType.

[CALL STACK]
    > CNTK::TrainingParameterSchedule<unsigned __int64>::  Serialize
    - CNTK::DeviceDescriptor::  UseDefaultDevice (x2)
    - CNTK::Function::  Forward
    - CNTK::Function::  Evaluate
    - CSharp_CNTK_Function__Evaluate__SWIG_0
    - 00007FFB040DC6BE (SymFromAddr() error: The specified module could not be found.)
```

- I can load the trained model into python and evaluate. That works fine.
- The vocabulary size of the only input argument is -2. Not sure if that's correct, but it says the same when I load the model in python. However, in python I'm creating the input variable based off of the actual size of the vocabulary, not what's been loaded from the model.
- Both the input variable and the output variable shape has IsUnknown = true. Is this expected?

**Comment by zhouwangzw** [comment]
The shape of input and output variables should not be unknown, and a negative number for vocabulary size sounds also wrong. What is the variable shapes when the model was loaded with Python?

**Comment by JeffScherrer** [comment]
`z.arguments[0].shape`
`(-2,)`

This is the case after loading the model in Python from a file, as well as before I save the model to the file.

**Comment by JeffScherrer** [comment]
Here's the function that defines my model. All of the variables I'm using have positive values.

'''
def BiRecurrence(fwd, bwd):
    F = C.layers.Recurrence(fwd)
    G = C.layers.Recurrence(bwd, go_backwards=True)
    x = C.placeholder()
    apply_x = C.splice(F(x), G(x))
    return apply_x

def create_model():
    with C.layers.default_options(initial_state=0.1):
        return C.layers.Sequential([
                C.layers.Embedding(embedding_dim, name='embed'),
                C.layers.BatchNormalization(),
                BiRecurrence(
                    C.layers.LSTM(hidden_dim//2),
                    C.layers.LSTM(hidden_dim//2)),
                C.layers.BatchNormalization(),
                C.layers.Dense(label_vocab_dim, name='classify')
            ])
'''

**Comment by zhouwangzw** [comment]
I forwarded the issue to the team and we are investigating it.

**Comment by zhouwangzw** [comment]
@JeffScherrer Would it be possible to share the scrpt which you used to save the model, and the saved model for investigation?

Thanks,

**Comment by zhouwangzw** [comment]
@JeffScherrer Checked the repo you sent and found the input of the model created by create_model() is Placeholder, instead of Input variable. You need to replace Placehold with correct input varialbes.

Thanks,

**Comment by n17s** [comment]
Closing. Feel free to reopen.
