### ISSUE TITLE
Applying transforms to composite readers.

### ISSUE THREAD

**Issue by Tacklebox** [Microsoft/CNTK#2073]
I am attempting to create a solution for the Udacity self driving car simulator using CNTK and I have come across this issue.

I found that when using ImageDeserializer, I can use crop with randomside to randomly flip an image horizontally during training like so:

cntk.io.transforms.crop(crop_type='randomside')

Unfortunately I need to also swap the sign of the associated steering angle being read from the CTFDeserializer whenever the image flips. Is there a way to do this?

**Comment by pkranen** [comment]
This is currently not supported out of the box. You'd have to implement a UserMinibatchSource (see https://cntk.ai/pythondocs/cntk.io.html?highlight=userminibatchsource#cntk.io.UserMinibatchSource) that does the transformations on both the image and the annotation. There is an example that reads images and bounding box annotations and that does scaling and flipping [here](https://github.com/Microsoft/CNTK/blob/pkranen/fasterRcnn/Examples/Image/Detection/FasterRCNN/od_mb_source.py).
