### ISSUE TITLE
CNN training on speech signal

### ISSUE THREAD

**Issue by saadirtza** [Microsoft/CNTK#2074]
Hi,

I have switched from tensorflow to CNTK. I am trying to train CNN network on spectrogram of speech.

My input is 1000(samples) *128 (dim). I want to apply filter on these features such that after max pooling resultant feature dimension is 500 (samples) * (64 dim) * (number of channels).

I have gone through the MNIST convnet example and sort of stuck to reshape my input accordingly.

Any help in this regard is much appreciated

Regards
Saad

**Comment by cha-zhang** [comment]
If you use the high-level API Convolution(), you may set reduction_rank=0, which should not need you to reshape the input. 

Another way is to follow the AlexNet Python example: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/AlexNet/Python/AlexNet_ImageNet_Distributed.py 
and insert a fake dimension before calling convolution.

**Comment by saadirtza** [comment]
Thanks Zhang for help.
Currently, i am using BrainScriptNetworkBuilder as its mentioned in CNTK documentation that its new and more powerful. In this scripting i am using ConvolutionalLayer and MaxPoolingLayer functions. Any advise how to achieve the above task using these functions?

However i will also try high level API. Thanks

Regards
Saad

**Comment by cha-zhang** [comment]
BrainScript doesn't support reductionrank yet. If you don't have any special reason, please use Python API.

**Comment by cha-zhang** [comment]
I'm closing this issue since there's no response for 4 weeks. Feel free to reopen this issue if needed. Thanks!
