### ISSUE TITLE
What are reserved keywords

### ISSUE THREAD

**Issue by mhng1580** [Microsoft/CNTK#208]
I happened to name a variable _contextWindow_ without knowing that it's a reserved keywords, which took me quite a while to figure out what actually resulted in the error  _InputValue operation had its row dimension 1411 changed by the reader to 9877_.
Is there anyway to know which words are reserved?
Thanks!

**Comment by frankseide** [comment]
Not currently, although it would be a good idea to create an index that simply lists any and all parameters across all modules, sorted by parameter name and listing all modules that consume that parameter.

'contextWindow' is not a reserved word in the classic programming-language sense. Parameter names are defined by each individual code module, by the line of C++ that reads out a specific parameter; there is no declaration section at present. Particularly for the readers, different reader implementations may even differ in their parameters.

The problem you ran into is that parameters can be defined at the scope they are used, but also in outer scopes. It is like scoping in most programming languages, except that you cannot see from the config what variables are used.

**Comment by mhng1580** [comment]
Thanks. I misused the term reserved word.

I guess the problem is that HTKMLFReader uses the variable of the same name. However, the point is that I don't know this variable name is already used in some cntk modules and it's not documented in CNTK book either.

**Comment by dongyu888** [comment]
Yes, 'contextWindow'  is a config parameter in HTKMLFReader.  We will document this in wiki.
