### ISSUE TITLE
Is it possible to write our own attention model????

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#2081]
I do not have deep understanding of the cntk concept 'dynamic_axis'

it seems like to implement an attention model, we have to deal with different dynamic axes between encoder and decoder, since it is not allowed to add two outputs with different dynamic axes instances.

**Comment by cha-zhang** [comment]
Have you checked tutorial 204 for attention model?

**Comment by DabiaoMa** [comment]
Yes and I have figured out how to do that, 

I need to use the method ' PastValueWindow' to transform a variable with dynamic sequence axis to one with only batch axis, and now it can be broadcast to another variable with different dynamic axis.
