### ISSUE TITLE
Possible implementation error in the source code for cntk.layers.models.attention

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#2083]
In the source code  'cntk.layer.models.attention.AttentionModel.attention' :
h_att = C.reduce_sum(C.element_times(h_enc_proj, attention_weights), axis=attention_axis)

Here attention_weights is applied on the projected h_enc_proj. 
But according to Bahdanau's paper " Neural machine translation by jointly learning to align and translate.", attention weight is applied on the h_enc before projection.

The output of this function is something like " SequenceOver[][Tensor[1,shape]]", the output has an unnecessary dimension "1" due to the funcion " cntk.reduce_sum() "

**Comment by cha-zhang** [comment]
Yes, this seems to be a bug. We will fix it.

**Comment by ebarsoum** [comment]
Thank you for reporting the issue.

**Comment by wolfma61** [comment]
oops ;) will close with a PR ;)

**Comment by n17s** [comment]
This has been fixed in 2.2 (and a little earlier). Forgot to add "closes #2083" in the commit message. Thanks for reporting it.
