### ISSUE TITLE
How to use ctf2bin.py?

### ISSUE THREAD

**Issue by nliu86** [Microsoft/CNTK#2084]
Can someone provide an example?
For example, if we have the following training data:
|features 5.170871 -1.020567 |labels 0 0 1
|features 4.327523 -0.815642 |labels 0 0 1
|features 2.678905 0.434324 |labels 0 0 1

How do we use ctf2bin.py and how to config the binary reader?

**Comment by raaaar** [comment]
```
>>python ctf2bin.py --help
usage: ctf2bin.py [-h] --input INPUT --header HEADER --chunk_size CHUNK_SIZE
                  --output OUTPUT [--precision {float,double}]

Transforms a CNTK Text Format file into CNTK binary format given a header.

optional arguments:
  -h, --help            show this help message and exit
  --input INPUT         CNTK Text Format file to convert to binary.
  --header HEADER       Header file describing each stream in the input.
  --chunk_size CHUNK_SIZE
                        Chunk size in bytes.
  --output OUTPUT       Name of the output file, stdout if not given
  --precision {float,double}
                        Floating point precision (double or float). Default is
                        float
```
Assuming you store your training data in input.ctf and you put together a header.config with the following content ([`<name>    <alias>  <input format>  <sample size>` per line](https://github.com/Microsoft/CNTK/blob/master/Scripts/ctf2bin.py#L6)):
```
features features dense 2
labels labels dense 3
```
All you need to do now is:

`python ctf2bin.py --input input.ctf --header header.config --chunk_size 33554432 --output input.cbf`

At the moment, the binary reader is only available in BrainScript ([here're a few examples](https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/ReaderTests/Config/CNTKBinaryReader/test.cntk)), but we're working to expose it in Python as well.
