### ISSUE TITLE
Reinforcement Learning on dialogue generation with CNTK

### ISSUE THREAD

**Issue by meijiesky** [Microsoft/CNTK#2087]
Recently, many researchers have been using reinforcement learning to generate dialogue based on the encoder-decoder architecture. I looked at some of the programs on GitHub and find that most were written using Torch or Theano.

There is a simple RL tutorial in the repository but I am just wondering whether there would be a guideline or tutorial to use CNTK to do RL to generate dialogues.

Thank you so much.

**Comment by cha-zhang** [comment]
We are releasing an RL framework for CNTK really soon, hopefully by end of this month. 

It's in one of the branches now, but there could still be significant changes: https://github.com/Microsoft/CNTK/tree/maoyi/deeprl/bindings/python/cntk/contrib/deepRL

**Comment by meijiesky** [comment]
Hopefully, you could also release some examples or tutorials on RL. Looking forward to that!
