### ISSUE TITLE
error when compiling multiverso

### ISSUE THREAD

**Issue by anguoyang** [Microsoft/CNTK#2096]
hi, all,
i followed the tutorial:
https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows
step by step, all same with the tutorial, except for GPU(as i have no gpu, i didn't install cuda related software ), however, i got this error when building multiverso:
-----------------------------------------------------------------------------------------

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(349,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Release_NoOpt|x64.
--------------------------------------------------------------------------

**Comment by wolfma61** [comment]
It definitely contains this build option ... as you can check for yourself in Visual Studio ...

Make sure you enlisted also into the submodule Multiverso, so make sure your directory c:\repos\cntk\Multiverso contains a complete set of files as well a a Multiverso.sln
(see also https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows under the Headline: Enlisting in the CNTK GitHub repository)

As described there, you could also set CNTK_ENABLED_ASGD environment variable to avoid compiling Multiverso, in case you don't need it at all ...

**Comment by anguoyang** [comment]
sorry, i made a stupid mistake, set  CNTK_ENABLED_ASGD to false without looking through the description in detail
