### ISSUE TITLE
Compiling C++ CNTK code on Ubuntu 14.04

### ISSUE THREAD

**Issue by AymanKh** [Microsoft/CNTK#2098]
Good day,

I have installed CNTK from source on Ubuntu 14.04 (gcc 4.8) and I am currently trying to compile some .cpp files. How do I compile and run the code in `/cntk/Examples/Evaluation/CNTKLibraryCPPEvalCPUOnlyExamples` ?

I have tried 
`g++ -std=c++11 EvalMultithreads.cpp -I ~/cntk/Source/CNTKv2LibraryDll/API/ ~/cntk/build/debug/lib/*`
but that spits out the following:
`/usr/bin/ld: warning: libCntk.Math-2.0d.so, needed by /cntk/build/debug/lib/libCntk.Core-2.0d.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libCntk.PerformanceProfiler-2.0d.so, needed by /cntk/build/debug/lib/libCntk.Math-2.0d.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status`

Also, in general, how do I compile a C++ code utilizing CNTK on Linux ?

**Comment by wolfma61** [comment]
On this site: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Linux the manual development setup for Linux is described in detail.
The chapter https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Linux#building-cntk describes the steps to build CNTK

If you don't plan on changing the source code, you might want to use the precompiled binaries or a docker setup ... see: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-your-machine

Wolfgang

**Comment by AymanKh** [comment]
I appreciate your prompt reply. I intend to edit the source code, the instructions provided seem to be concerning building the whole CNTK library. Let me restate my questions:

1.  How can I write a single program using C++ that uses CNTK ? (i.e. any examples out there ?)
2. Once I write this program, How can I compile it and debug it ? (i.e. using g++ )

**Comment by zhouwangzw** [comment]
By "editing the source code", do you mean the code contributing to CNTK library itself, or samples that use the CNTK library? If you change code which is a part of CNTK library, you have to rebuild the whole CNTK library. If you just change the sample code which uses CNTK library, you can use precompiled binaries and make your application link to the CNTK library. 

Regarding the EvalMultithreads.cpp, it is not a standalone program. As described in `Makefile`, it is a part of CNTKLIBRARY_CPP_EVAL_EXAMPLES. The `Makefile` also contains a section about how to build CNTKLIBRARY_CPP_EVAL_EXAMPLES. 

```
$(CNTKLIBRARY_CPP_EVAL_EXAMPLES): $(CNTKLIBRARY_CPP_EVAL_EXAMPLES_OBJ) | $(CNTKLIBRARY_LIB) $(READER_LIBS)
	@echo $(SEPARATOR)
	@mkdir -p $(dir $@)
	@echo building $(CNTKLIBRARY_CPP_EVAL_EXAMPLES) for $(ARCH) with build type $(BUILDTYPE)
	$(CXX) $(LDFLAGS) $(patsubst %,-L%, $(LIBDIR) $(LIBPATH) $(GDK_NVML_LIB_PATH)) $(patsubst %,$(RPATH)%, $(ORIGINLIBDIR) $(LIBPATH)) -o $@ $^ $(LIBS) -l$(CNTKLIBRARY) $(L_READER_LIBS)

```
You probably need to customize library paths to point to the CNTK libraries you installed.

After compiling the program, you can debug it as usual C++ program. If you want to step into source code of CNTK libraries, you need to have CNTK source code installed on your machine.

Thanks,

**Comment by AymanKh** [comment]
Thanks ! that clears the issue. I am closing it :)
