### ISSUE TITLE
No release on release page

### ISSUE THREAD

**Issue by superphil0** [Microsoft/CNTK#21]
In the setup description in the wiki https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration

it says to download the latest release (link provided to https://github.com/Microsoft/CNTK/releases)
However there are currently no releases

**Comment by chrisbasoglu** [comment]
Hi superphil0, binary releases will be uploaded in about 48 hours.

**Comment by bobchennan** [comment]
@superphil0 
It seems to be released now.

**Comment by superphil0** [comment]
Yes it is, thanks for the hint @bobchennan
