### ISSUE TITLE
Listing of pre-trained models

### ISSUE THREAD

**Issue by zpbappi** [Microsoft/CNTK#2107]
In the transfer learning tutorials, pre-trained models are being downloaded from `https://www.cntk.ai/Models/*`. However, I can't find a listing of available pre-trained models that can be used in CNTK. Can you please add a page that will list the available models with some basic description (e.g. input shape, output, architecture, etc.)?

**Comment by wolfma61** [comment]
Is this what you are looking for?
https://www.microsoft.com/en-us/cognitive-toolkit/features/model-gallery/

**Comment by zpbappi** [comment]
Not really. Although the model gallery contains some examples of downloading a pre-trained models, they are mostly recipe/tutorial on how to design and train a particular type of network using CNTK. I was referring to list of pre-trained models to download and use in transfer learning (or, in other similar purposes). Some examples of this type of usages can be found in [here](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_301_Image_Recognition_with_Deep_Transfer_Learning.ipynb) and [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN#using-a-pre-trained-model). They are downloading the pre-trained models from [here](https://www.cntk.ai/Models/ResNet/ResNet_18.model) and [here](https://cntk.ai/Models/FRCN_Grocery/Fast-RCNN.model) respectively.

**Comment by cha-zhang** [comment]
Lots of the pre-trained models are downloadable in their respective example page. For example: 

AlexNet: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/AlexNet 
GoogLeNet: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/GoogLeNet 
ResNet: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet 
VGG: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/VGG 

Scroll to the bottom of these pages and you will see the models.

**Comment by zpbappi** [comment]
Thanks @cha-zhang, it is helpful. However, can we please have a wiki page (or, a documentation site page) which will list the pre-trained models with urls to download? It will be easier to find from a single page. This is just a suggestion.

**Comment by DHOFM** [comment]
What happened to the model gallery ? At the moment i only see a blank page

![grafik](https://user-images.githubusercontent.com/27775323/28569257-6a6d09c2-7139-11e7-9a21-82f671e0f90b.png)

**Comment by mahilleb-msft** [comment]
@dhofm - thanks, we're fixing this.

**Comment by cha-zhang** [comment]
I'm working on the single page for all pre-trained models. Should be available in a day or two.

**Comment by cha-zhang** [comment]
All models are now accessible from the same location: 
https://github.com/Microsoft/CNTK/tree/master/PretrainedModels 

Thanks!

**Comment by zpbappi** [comment]
Thanks @cha-zhang for compiling the list. Would you consider adding the link in some place like "Resources" section in the [official documentation site](https://docs.microsoft.com/en-us/cognitive-toolkit/)? It would be easier to find for someone who is looking for something like it.

**Comment by cha-zhang** [comment]
Link added to home page of GitHub. Thanks!

**Comment by hellosaumil** [comment]
@cha-zhang Hi, I'm learning CNTK and recently finished Sayan's Course on edX. 

I went over [CNTK Pre-trained Image Models](https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md). Though I don't know how to use these pre-trained model to directly evaluate local test images. It would be highly appreciated if you can direct me to do so.

Besides running Notebooks like `CNTK_301_Image_Recognition_with_Deep_Transfer_Learning` and `CNTK_201B_CIFAR-10_ImageHandsOn` yields `RuntimeError: Batch normalization` error. #2722 

Thank You.
