### ISSUE TITLE
It's really necessary to use STL containers in UNIX main function?

### ISSUE THREAD

**Issue by DGideas** [Microsoft/CNTK#2108]
In ```Source/CNTK/CNTK.cpp```, near line 907, is:
```c++
//......
int main(int argc, char* argv[])
{
    // TODO: change to STL containers
    wchar_t** wargs = new wchar_t*[argc];
    for (int i = 0; i < argc; ++i)
    {
        wargs[i] = new wchar_t[strlen(argv[i]) + 1];
        size_t ans = ::mbstowcs(wargs[i], argv[i], strlen(argv[i]) + 1);
        assert(ans == strlen(argv[i]));
    }
    int ret = wmain1(argc, wargs);
//......
```

I think the variable ```wargs``` just transfer the command argument to ```wmain1```function, so I think it's unnecessary to use STL to do it. How do you think?

**Comment by veikkoeeva** [comment]
@DGideas Maybe the comment means something to the effect
```
int wmain(int argc, whar_t* argv[])
{
    std::vector<std::wstring> allArgs(argv + 1, argv + argc);
    
    return EXIT_SUCCESS;
}
```

**Comment by ebarsoumMS** [comment]
We depend heavily on STL and boost, I don't know the history of this comment. But what the concern on switching to STL in main?

**Comment by DGideas** [comment]
@ebarsoumMS , I have review all possible commit about this, and this commit have really long history, in pervious version of CNTK(about 2 years ago), ```CNTK.cpp``` locate at ```/MachineLearning/CNTK/CNTK.cpp``` . And in [This commit](https://github.com/Microsoft/CNTK/commit/5afa3d73e523f8f4b41209a1e186269cd57a9ae2) (https://github.com/Microsoft/CNTK/commit/5afa3d73e523f8f4b41209a1e186269cd57a9ae2), ```// TODO: change to STL containers``` was added.
[This](https://github.com/Microsoft/CNTK/blob/6905080482f5d62e95b5f0663f7d8da46ae0d07f/MachineLearning/CNTK/CNTK.cpp#L1132) is the pervious version before https://github.com/Microsoft/CNTK/commit/5afa3d73e523f8f4b41209a1e186269cd57a9ae2, and in 5afa3d7, [CNTK.cpp](https://github.com/Microsoft/CNTK/blob/5afa3d73e523f8f4b41209a1e186269cd57a9ae2/MachineLearning/CNTK/CNTK.cpp#L1134) had been changed.

btw, I can't find any discussion about it in these 2 years. I have no concern about it, but I want to know if we change it to STL, what advantages can it gives us?

**Comment by ebarsoumMS** [comment]
The main advantage of using STL is to write cleaner and safer code.
