### ISSUE TITLE
Where is the Input(0) and Input(1) from?

### ISSUE THREAD

**Issue by xhzhao** [Microsoft/CNTK#211]
I'm writing a new convolution routine on CPU version.
When reading the code in ConvolutionalNodes.h, i don't know where the source data is from:
![image](https://cloud.githubusercontent.com/assets/17486215/13559288/83a82db0-e44d-11e5-9c6a-7617566f2917.png)
Is it a global variant?
Where is Input initialized?

How to initialize the input data to CHW layout for lengcy enginType or HWC layout for cudnn enginType?

**Comment by wolfma61** [comment]
its a member message in ComputationNode? or am I misunderstanding your question

**Comment by xhzhao** [comment]
@wolfma61 Thanks for your help, i found the Input() function definition in ComputationNodeBase.
Input(index) function returns m_inputs[index].But i still don't know where is m_inputs[] initialized.
I want to see where the m_input[] is initialized as CHW layout or HWC layout.

**Comment by Alexey-Kamenev** [comment]
Please take a look at `Source\ActionsLib\NDLNetworkBuilder.cpp`, in particular, how `InputValue` and `ImageInput`
