### ISSUE TITLE
How to debug CNTK internal error with ColumnSlice? 

### ISSUE THREAD

**Issue by rsharnag** [Microsoft/CNTK#2111]
Hey,
I am new to CNTK and facing issue with train_minibatch. Error is with GPUSparseMatrix<float> :: ColumnSlice method. I am hitting the error `ValueError: The slice (0+1200) is out of range of the source matrix (120).`. Looked at the code too. It's setting the GetColumnCount to 120, even when the specified vocab dimension is 20000 for sparse matrix. Tried to google it but couldn't figure out the cause. Can you please explain the error or meaning of those columns?

My input minibatch dimensions are `(12,10,20000)` and input_variable is stated like this `C.ops.input_variable(shape=(max_input_length, vocabsize), is_sparse=True, name="Query")` and reader is defined like 

        def create_reader(path, is_training, input_dim):
            randomization_win = 128
            return MinibatchSource(CTFDeserializer(path, StreamDefs(
                featuresQ=StreamDef(field='Q', shape=input_dim, is_sparse=True),
                featuresO=StreamDef(field='O', shape=input_dim, is_sparse=True),
                featuresN1=StreamDef(field='N1', shape=input_dim, is_sparse=True),
                featuresN2=StreamDef(field='N2', shape=input_dim, is_sparse=True),
                featuresN3=StreamDef(field='N3', shape=input_dim, is_sparse=True),
                featuresN4=StreamDef(field='N4', shape=input_dim, is_sparse=True),
                featuresN5=StreamDef(field='N5', shape=input_dim, is_sparse=True)
            )), randomize=is_training, randomization_window_in_chunks=randomization_win,
                                   max_sweeps=INFINITELY_REPEAT if is_training else 1)

here input_dim is set to vocab_size

**Comment by KeDengMS** [comment]
Note that python dimensions are reversed in C++ because python/numpy is row-major while C++ is column major. So the matrix in C++ is 12x10=120 columns for each sample, with echo column of dimension of 20000 in sparse. Where does the 1200 come from and what is you intention? Sharing a script that triggers the error might help us understand your problem better.
