### ISSUE TITLE
Evaluating LTSM one sequence step at a time (C++)

### ISSUE THREAD

**Issue by Worldexe** [Microsoft/CNTK#2112]
I have LSTM seq2seq model that I need to evaluate in C++ code.

Can I feed one sequence step-by-step, calling `Evaluate()` on the same `Function` object, as my data arrives? Does this keep internal LSTM state between `Evaluate()` calls?

I did not find any useful answer in tickets or documentation.

**Comment by cha-zhang** [comment]
You could look at our sequence to sequence example: 
https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/Python/Sequence2Sequence.py 

The key calls are 
Recurrence(LSTM(hidden_dim), return_full_state=True)
(or Fold(LSTM(hidden_dim), return_full_state=True))
and
RecurrenceFrom(…)

**Comment by Worldexe** [comment]
I can not find such calls in C++ API.
Can you please help me find how this can be done in C++?

**Comment by zhouwangzw** [comment]
You can use Value::Create() or Value::CreateSequence() by setting sequenceStartFlag(s) to false, and feed the created Value object to Evaluate(). When a new sequence starts, specify sequenceStartFlag to true.

**Comment by Worldexe** [comment]
Looks like this is what I need; thanks!
