### ISSUE TITLE
How to find the people who are not wearing helmet in the picture

### ISSUE THREAD

**Issue by laughsmile** [Microsoft/CNTK#2113]
Hello everyone.

I know how to using image detection to find whether there is helmet or not in the picture,
but I don't know how to find whether there is someone without wearing helmet.

Would you please tell me how to solve the problem?
Thanks in advance.
Ryu

**Comment by cha-zhang** [comment]
Instead of training with helmet images, you can train with person wearing helmet images. 

Alternatively, you can run a helmet detector and a face detector, and based on their proximity to decide if the face is actually wearing the helmet.

**Comment by laughsmile** [comment]
Mr Zhang

Thank you so much for your answer.

I have tried to train with my picture with and without helmet images (about 100 images each),
but the recognition rate is not good when using the trained model actually, sometimes the model can recognize well and sometimes it can NOT recognize correctly.
Are my images for training too few?

I also try to use the helmet detector and face detector to solve the problem.

Best regards and thank you again.
Ryu

**Comment by cha-zhang** [comment]
Yes, you might need more images for training. 

Are you using the Fast RCNN example: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN

**Comment by laughsmile** [comment]
Mr Zhang

Thank you so much!

I used CNN to train the model.
I will change to use  Fast RCNN or Faster RCNN and train the model with 300 images each.

Ryu

**Comment by ebarsoumMS** [comment]
Please move this question to stackoverflow with tag CNTK for follow up. And use github issue for CNTK related issues or missing feature.

**Comment by hasanalkholil** [comment]
Hi mr Laughsmile,, where you find the data from ?

**Comment by yasuo19** [comment]
> Hello everyone.
> 
> I know how to using image detection to find whether there is helmet or not in the picture,
> but I don't know how to find whether there is someone without wearing helmet.
> 
> Would you please tell me how to solve the problem?
> Thanks in advance.
> Ryu

Hi Ryu,
Can you please share the trained model to detect helmets so that it would be easier for people who don't have enough resources to train a model.

Thanks in advance
