### ISSUE TITLE
performance tuning for multiple GPUs parallel training 

### ISSUE THREAD

**Issue by nliu86** [Microsoft/CNTK#2115]
Hi,
I used 8 GPUs on a single machine to train a fully connected network. The network structure is 400:2048:512:2.

My training sample has 110 millions records with each record being 400 dimension dense vector. I transform the sample into binary format first (around 180GB) to speed up training.

Here are the performance based on profiler:

minibatchSize=8192:
[cntk_1024.txt](https://github.com/Microsoft/CNTK/files/1143643/cntk_1024.txt)

minibatchSize=16384:
[cntk_2048.txt](https://github.com/Microsoft/CNTK/files/1143645/cntk_2048.txt)

In both situations, the GPU utilization is not very high at about 60-70%. So with 8 GPUs, I achieved a speed up of 5x. Can I do better? I believe I used nccl, does those times for Gradient Aggregation look reasonable?

Here is the config:
[cntk.training.parallel.txt](https://github.com/Microsoft/CNTK/files/1143661/cntk.training.parallel.txt)

Thanks!

**Comment by cha-zhang** [comment]
Doesn't seem to bee normal. The max gradient aggregation time is 20 second, which is way too high. 

You started 1-bit SGD at epoch 2. I assume the numbers you reported are after the second epoch?

**Comment by nliu86** [comment]
Yes, I think it's after 2nd epoch. Maybe we should report after 3rd epoch since 2nd epoch usually uses more time than 3rd and 4th epoch.
Here is the training log:
[trainlog.txt](https://github.com/Microsoft/CNTK/files/1144160/trainlog.txt)

**Comment by KeDengMS** [comment]
The profile looks normal to me, although gradient aggregation StdDev is pretty big, probably due to the 32s max which may come from network glitches. With 16K minibatch, the aggregation cost is 6.283ms, while forward+backward takes 15.003ms. This indicates your model is not GPU intensive, which explains the low GPU utilization. To scale better you should try put more load on GPU, either by increasing the minibatch size, or by increasing model complexity.

**Comment by nliu86** [comment]
@KeDengMS If you compare the results between minibatchSize=8192 and minibatchSize=16384, you'll see that for minibatchSize=16384, it spends considerable time in prefetching minibatch(22ms) . It even needs to spend 3.4ms in "Get minibatch". Does it mean there is a bottleneck in getting the data? If we increase the minibatch size, I think the performance will be worse.

**Comment by nliu86** [comment]
I use 1-big SGD for data parallelization. If I use block momentum, will the aggregation time decrease?

**Comment by KeDengMS** [comment]
Yes block momentum would reduce aggregation time. One thing also worth trying is to use 32-bit aggregation instead of 1-bit, as the quantization to 1-bit takes extra computation cost. Gradient quantization is a balance between extra cost in quantization vs. saved communication cost.

The prefetch time increase from 8K to 16K is expected as you are feeding more data per minibatch. Prefetch Minibatch is done in a separate thread to load data to GPU asynchronously, so it is not a bottleneck unless the time cost exceeds Minibatch Iteration. The 3.4ms in Get minibatch is the wait in main computation thread for the async load, and it would be less if the forward+backward takes longer (so computation thread has more chance not waiting on async load). It seems your load is I/O intensive, so increasing minibatch size would increase both prefetch and forward-backword. I would try increase the model complexity, e.g. by using a higher hidden dimensions, if you want to achieve better scale up in speed.

**Comment by nliu86** [comment]
I tried 32-bit and noticed higher utilization of GPU and faster training. But it stops converging nicely as 1-big SGD. I'm wondering if there might be a bug. You can check the values of CrossEntropyWithSoftmax

32-bit:
Finished Epoch[21 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24285071 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1860666175; learningRatePerSample = 0.001; ep
ochTime=162.056s
Finished Epoch[22 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24280630 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1744747074; learningRatePerSample = 0.001; ep
ochTime=161.195s
Finished Epoch[23 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24280566 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1628827973; learningRatePerSample = 0.001; ep
ochTime=161.615s
Finished Epoch[24 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24283443 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1512908872; learningRatePerSample = 0.001; ep
ochTime=161.289s
Finished Epoch[25 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24279607 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1396989771; learningRatePerSample = 0.001; ep
ochTime=160.6s
Finished Epoch[26 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24273082 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1281070670; learningRatePerSample = 0.001; ep
ochTime=160.73s
Finished Epoch[27 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24272661 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1165151569; learningRatePerSample = 0.001; ep
ochTime=160.742s
Finished Epoch[28 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24273869 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -1049232468; learningRatePerSample = 0.001; epochTime=160.672s
Finished Epoch[29 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24273072 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -933313367; learningRatePerSample = 0.001; epochTime=161.688s
Finished Epoch[30 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24267456 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -817394266; learningRatePerSample = 0.001; epochTime=162.127s
Finished Epoch[31 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24266655 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -701475165; learningRatePerSample = 0.001; epochTime=160.606s
Finished Epoch[32 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24271103 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -585556064; learningRatePerSample = 0.001; epochTime=161.272s
Finished Epoch[33 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24265134 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -469636963; learningRatePerSample = 0.001; epochTime=161.639s
Finished Epoch[34 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24263113 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -353717862; learningRatePerSample = 0.001; epochTime=161.464s
Finished Epoch[35 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24266270 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -237798761; learningRatePerSample = 0.001; epochTime=161.082s
Finished Epoch[36 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24259596 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -121879660; learningRatePerSample = 0.001; epochTime=161.414s
Finished Epoch[37 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24259433 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = -5960559; learningRatePerSample = 0.001; epochTime=161.267s
Finished Epoch[38 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24260858 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = 109958542; learningRatePerSample = 0.001; epochTime=161.812s
Finished Epoch[39 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24258898 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = 225877643; learningRatePerSample = 0.001; epochTime=161.496s
Finished Epoch[40 of 1001]: [Training] CrossEntropyWithSoftmax = 0.24253014 * 115919101; EvalClassificationError = 0.06698406 * 115919101; totalSamplesSeen = 341796744; learningRatePerSample = 0.001; epochTime=161.624s

1-bit:
Finished Epoch[21 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23734319 * 115919101; EvalClassificationError = 0.06699114 * 115919101; totalSamplesSeen = -1860666175; learningRatePerSample = 0.001; ep
ochTime=166.786s
Finished Epoch[22 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23643211 * 115919101; EvalClassificationError = 0.06699415 * 115919101; totalSamplesSeen = -1744747074; learningRatePerSample = 0.001; ep
ochTime=171.722s
Finished Epoch[23 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23566624 * 115919101; EvalClassificationError = 0.06699626 * 115919101; totalSamplesSeen = -1628827973; learningRatePerSample = 0.001; ep
ochTime=156.995s
Finished Epoch[24 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23510237 * 115919101; EvalClassificationError = 0.06699473 * 115919101; totalSamplesSeen = -1512908872; learningRatePerSample = 0.001; ep
ochTime=155.84s
Finished Epoch[25 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23468850 * 115919101; EvalClassificationError = 0.06699446 * 115919101; totalSamplesSeen = -1396989771; learningRatePerSample = 0.001; epochTime=167.061s
Finished Epoch[26 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23430683 * 115919101; EvalClassificationError = 0.06699291 * 115919101; totalSamplesSeen = -1281070670; learningRatePerSample = 0.001; epochTime=160.032s
Finished Epoch[27 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23385833 * 115919101; EvalClassificationError = 0.06699198 * 115919101; totalSamplesSeen = -1165151569; learningRatePerSample = 0.001; epochTime=159.687s
Finished Epoch[28 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23358546 * 115919101; EvalClassificationError = 0.06699012 * 115919101; totalSamplesSeen = -1049232468; learningRatePerSample = 0.001; epochTime=174.535s
Finished Epoch[29 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23338573 * 115919101; EvalClassificationError = 0.06698990 * 115919101; totalSamplesSeen = -933313367; learningRatePerSample = 0.001; epochTime=165.567s
Finished Epoch[30 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23328906 * 115919101; EvalClassificationError = 0.06699237 * 115919101; totalSamplesSeen = -817394266; learningRatePerSample = 0.001; epochTime=157.878s
Finished Epoch[31 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23298130 * 115919101; EvalClassificationError = 0.06699113 * 115919101; totalSamplesSeen = -701475165; learningRatePerSample = 0.001; epochTime=168.966s
Finished Epoch[32 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23274987 * 115919101; EvalClassificationError = 0.06699065 * 115919101; totalSamplesSeen = -585556064; learningRatePerSample = 0.001; epochTime=176.534s
Finished Epoch[33 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23248236 * 115919101; EvalClassificationError = 0.06698943 * 115919101; totalSamplesSeen = -469636963; learningRatePerSample = 0.001; epochTime=175.927s
Finished Epoch[34 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23233717 * 115919101; EvalClassificationError = 0.06698940 * 115919101; totalSamplesSeen = -353717862; learningRatePerSample = 0.001; epochTime=163.832s
Finished Epoch[35 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23218053 * 115919101; EvalClassificationError = 0.06698795 * 115919101; totalSamplesSeen = -237798761; learningRatePerSample = 0.001; epochTime=164.629s
Finished Epoch[36 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23206143 * 115919101; EvalClassificationError = 0.06698903 * 115919101; totalSamplesSeen = -121879660; learningRatePerSample = 0.001; epochTime=169.242s
Finished Epoch[37 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23194025 * 115919101; EvalClassificationError = 0.06698806 * 115919101; totalSamplesSeen = -5960559; learningRatePerSample = 0.001; epochTime=170.241s
Finished Epoch[38 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23176262 * 115919101; EvalClassificationError = 0.06698819 * 115919101; totalSamplesSeen = 109958542; learningRatePerSample = 0.001; epochTime=159.482s
Finished Epoch[39 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23166869 * 115919101; EvalClassificationError = 0.06698743 * 115919101; totalSamplesSeen = 225877643; learningRatePerSample = 0.001; epochTime=200.259s
Finished Epoch[40 of 1001]: [Training] CrossEntropyWithSoftmax = 0.23154142 * 115919101; EvalClassificationError = 0.06698744 * 115919101; totalSamplesSeen = 341796744; learningRatePerSample = 0.001; epochTime=175.606s

**Comment by nliu86** [comment]
Thanks! That's good insight. For one GPU machine, which option is better for parallel training: nccl or mpi?

**Comment by KeDengMS** [comment]
NCCL is faster than MPI when you run multi-GPU distributed training. NCCL 1.3 only supports single machine. NCCL2 supports multi-machines and we are working on integrating it.
MPI works for both single machine and multi machine distributed training.
