### ISSUE TITLE
CNTK pip install error

### ISSUE THREAD

**Issue by sniceper** [Microsoft/CNTK#2116]
Hello,

I'm trying to install CNTK on my new Python environnment.

I'm using python 3.6 on a 64 Bits windows 10 machine

When performing the command `pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl`

I get those issues:

`Collecting cntk==2.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
  Using cached https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp36-cp36m-win_amd64.whl
Collecting scipy>=0.17 (from cntk==2.0)
  Using cached scipy-0.19.1.tar.gz
Requirement already satisfied: numpy>=1.11 in c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages (from cntk==2.0)
Installing collected packages: scipy, cntk
  Running setup.py install for scipy ... error
    Complete output from command "c:\users\shad'\appdata\local\programs\python\python36\python.exe" -u -c "import setuptools, tokenize;__file__=\"C:\\Users\\ShaD'\\AppData\\Local\\Temp\\pip-build-hxrxpttf\\scipy\\setup.py\";f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record "C:\Users\ShaD'\AppData\Local\Temp\pip-m5bdrxsi-record\install-record.txt" --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)

    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ["c:\\users\\shad'\\appdata\\local\\programs\\python\\python36\\lib", 'C:\\', "c:\\users\\shad'\\appdata\\local\\programs\\python\\python36\\libs"]
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ["c:\\users\\shad'\\appdata\\local\\programs\\python\\python36\\lib", 'C:\\', "c:\\users\\shad'\\appdata\\local\\programs\\python\\python36\\libs"]
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ["c:\\users\\shad'\\appdata\\local\\programs\\python\\python36\\lib", 'C:\\', "c:\\users\\shad'\\appdata\\local\\programs\\python\\python36\\libs"]
      NOT AVAILABLE

    c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ShaD'\AppData\Local\Temp\pip-build-hxrxpttf\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\ShaD'\AppData\Local\Temp\pip-build-hxrxpttf\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\ShaD'\AppData\Local\Temp\pip-build-hxrxpttf\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\shad'\appdata\local\programs\python\python36\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command ""c:\users\shad'\appdata\local\programs\python\python36\python.exe" -u -c "import setuptools, tokenize;__file__=\"C:\\Users\\ShaD'\\AppData\\Local\\Temp\\pip-build-hxrxpttf\\scipy\\setup.py\";f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record "C:\Users\ShaD'\AppData\Local\Temp\pip-m5bdrxsi-record\install-record.txt" --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ShaD'\AppData\Local\Temp\pip-build-hxrxpttf\scipy\`

From what i read, it looks like some libraries are missing, but i'm not sure if its correct, and how to correct it. Any idea?

Thank you very much in advance.

**Comment by mahilleb-msft** [comment]
Hi @sniceper - which Python distribution are you on? It seems it isn't Anaconda, [which we currently recommend](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python).
The reason for the failure is that some of our dependencies (in this case scipy) aren't available as a binary pip install on Windows, and build these from source in Windows is hard.
You could try to install scipy from Christian Gohlke's collection of pre-build Windows pacakages, cf. [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy), and then try again to your original `pip install`.
Let me know how this goes,
Mark

**Comment by sniceper** [comment]
Hello,

Thank you for your answer, i didn't think i could have any dependencies with an IDE. I will download Anaconda then..

Thank you.

**Comment by mahilleb-msft** [comment]
Thanks @sniceper. Please re-open this issue, if the problem persists with Anaconda.

Best, Mark

**Comment by Ark-kun** [comment]
Hello, @mahilleb-msft 

This is still a problem when installing under Anaconda:
See https://github.com/Microsoft/CNTK/issues/1896#issuecomment-321480268

**Comment by wolfma61** [comment]
the related #1896 has been solved
