### ISSUE TITLE
Speech lstm last output 

### ISSUE THREAD

**Issue by BitHashTech** [Microsoft/CNTK#2118]
Is there a way to consider only last output of lstm for training? 
Considering each utterance as a sequence of frames? I tried using HTKMLF format with framemode false and sequences.Last but can't get it to work right? Or there any other way?

**Comment by KeDengMS** [comment]
Can you share your script that does not work right? sequence.last should be the way to get the last output of LSTM, and it has nothing to do with input data format as long as the input is sequence. The [CNTK debug manual](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_debug.ipynb) may help you.

**Comment by sayanpa** [comment]
You can also look into the CNTK 106A/B tutorials for examples (not using speech data). Given we havn't heard back from you for over two weeks, I am closing the issue. Please feel free to reopen if you need help.
