### ISSUE TITLE
sampled softmax

### ISSUE THREAD

**Issue by ianupright** [Microsoft/CNTK#212]
Anyone have an implementation for doing sampled softmax for CNTK models?

**Comment by frankseide** [comment]
There seem to be at least two definitions of sampled softmax. Just to make sure we talk about the same thing, would you specify which one you mean?

**Comment by ianupright** [comment]
Like this one.  http://arxiv.org/abs/1412.2007

**Comment by dongyu888** [comment]
Sorry, this is not implemented in CNTK yet. Are you willing to implement it?

**Comment by deasuke** [comment]
Any update on this?

**Comment by wolfma61** [comment]
please check out the latest version of CNTK ...
