### ISSUE TITLE
Miss-classified page: Project a 1D input of dim ...

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2122]
The page https://docs.microsoft.com/en-us/cognitive-toolkit/project-a-1D-input-of-dim-inputDim-to-a-1D-output-of-dim-outputDim appears in the BrainScript section, while it's Python materials.

**Comment by KeDengMS** [comment]
Thanks for reporting this, we'll look into it.

**Comment by mahilleb-msft** [comment]
Thanks for reporting, this was addressed, the change will soon be live.
