### ISSUE TITLE
How to generate a confusion matrix using the Python API?

### ISSUE THREAD

**Issue by tomekjaworski** [Microsoft/CNTK#2123]
Hi,
I could not find any way to calculate confusion matrix for a trained model. Is there a way to do it?

**Comment by KeDengMS** [comment]
Can you use scikit [sklearn.metrics.confusion_matrix](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html) to compute confusion matrix?

**Comment by cha-zhang** [comment]
Closing this issue due to lack of response. Please reopen it if needed. Thanks!
