### ISSUE TITLE
Adding atrous/dilated convolution?

### ISSUE THREAD

**Issue by arniwesth** [Microsoft/CNTK#2124]
Is there a roadmap for adding atrous/dilated convolution to CNTK? 

It seems to be on the TODO list: https://www.cntk.ai/pythondocs/_modules/cntk/layers/layers.html

**Comment by KeDengMS** [comment]
Yes it's coming with CuDNN6. Please stay tuned.

**Comment by ebarsoumMS** [comment]
In master.
