### ISSUE TITLE
Documentation for BS.Network.Edit()

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2126]
The BrainScript function [BS.Network.Edit()](https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-Model-Editing) is left completely undocumented. It would be very nice to provide some documentation for this function. Our production use case would very much fit into this pattern. Thanks!

**Comment by KeDengMS** [comment]
Please find a more detailed doc on MEL [here](https://github.com/Microsoft/CNTK/blob/master/Documentation/Documents/Model%20Editing%20Language.md).
