### ISSUE TITLE
Couldn't find the specified README

### ISSUE THREAD

**Issue by Prasandhmcw** [Microsoft/CNTK#2128]
#Hi ,

I am trying to run one of the EndToEndTest - BatchNormalization/Spatial/CNTK on the linux build.
But , am getting an error log stating 

> Error: cannot find data. Please see Examples/Image/Miscellaneous/CIFAR-10/README.md for instructions to get it

I faced a similar problem in Non-Spatial tests and I read the corresponding README and downloaded the necessary DATASETS. But here , am unable to find any folder named "**MISCELLANEOUS**" itself.

The Source code doesn't contain such Folder. 
Any leads on how to overcome this small issue ?

**Comment by ujjwal-researcher** [comment]
You are probably looking for the following file 

https://github.com/Microsoft/CNTK/blob/master/Examples/Image/DataSets/CIFAR-10/README.md

**Comment by KeDengMS** [comment]
Thanks for pointing it out. The error message has been fixed. Please refer to [this](https://docs.microsoft.com/en-us/cognitive-toolkit/how-to-test) to set up CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY to run the test.

**Comment by Prasandhmcw** [comment]
Thanks @KeDengMS and @ujjwal-researcher .

@ujjwal-researcher Hey can you guide me the path where CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY should be pointing to ?

**Comment by Prasandhmcw** [comment]
@KeDengMS I would also suggest to change the path correspondingly in
 
[]([](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/BatchNormalization/Spatial/run-test-common#L12))
&
[](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/BatchNormalization/Spatial/run-test-common#L14)

Just a stale path fixing again and a cleaner code.

Thanks.

**Comment by KeDengMS** [comment]
@Prasandhmcw Those path in the script cannot be changed. You need to create a folder for CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY, and copy or link the CIFAR data under Image/CIFAR/v0. This is because that in our end-to-end test environment, test data are centralized under one folder.

**Comment by Prasandhmcw** [comment]
Ok. This being the case , I understand that the path needn't be changed.

For people , who are getting confused with CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY ,
Just create a folder specifically for the ExternalData and the necessary sub-folders , by looking into the test scripts and then copy/link the necessary data under the respective folders.
Dont forget to set the CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY environment variable.

Thanks for the info @KeDengMS .
