### ISSUE TITLE
install cntk on  CentOS 6.8 settled!

### ISSUE THREAD

**Issue by BrendonLynch** [Microsoft/CNTK#2129]
I have installed cntk on CentOS 6.8 systerm successfully, write down the steps :
install cntk according https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python
install Anaconda3 4.1.1 Python for Linux (64-bit).
pip install cntk
make sure install openmpi
sorry ,haven't finished

**Comment by KeDengMS** [comment]
Good to know that! I'll close this issue and please feel free to reopen or create a new one if you found anything.
