### ISSUE TITLE
PennTreebankExample with noiseContrastiveEstimation

### ISSUE THREAD

**Issue by ianupright** [Microsoft/CNTK#213]
When I run the PennTreebankExample with:

trainingCriterion = "noiseContrastiveEstimation"

It seems to work on GPU but it SegFaults on CPU.

**Comment by gaizkan** [comment]
Seems to be running on CPU. Didn't get a SegFault on a machine with GPU (but executing the Debug_CPUONLY build). I will try next on a machine without a GPU.

**Comment by gaizkan** [comment]
The example throws an assertion in CPUMatrix::LocateColumn. This is happens in a non-GPU machine.
Marking this as a bug.

**Comment by wolfma61** [comment]
please reopen if you still run into problem with the most recent bits.
