### ISSUE TITLE
User defined function used as layer crashes my Python interpreter

### ISSUE THREAD

**Issue by n17s** [Microsoft/CNTK#2132]
While [helping a user on StackOverflow](https://stackoverflow.com/questions/44565243/how-to-compose-custom-function-cntk) I found that the following code crashes my Python interpreter
```python
import cntk as C
import numpy as np
from cntk.ops.functions import UserFunction

class CustomFun(UserFunction):
    def __init__(self, *args, name='CustomFun'):
        otherStuff = args[-1]
        args = args[:-1]
        super(CustomFun, self).__init__(list(args), name=name)
        self.otherStuff = otherStuff
    def forward(self, arguments, outputs=None, keep_for_backward=None, device=None, as_numpy=True):
        return None,[x/2 for x in arguments]
    def backward(self, state, root_gradients, variables=None, as_numpy=True):
        #it's not important right now, just a test...
        return root_gradients
    def infer_outputs(self):
        #shape, type and dynamic axes of inputs are not changed by this function
        outputVar = [C.output_variable(self.inputs[idx].shape, self.inputs[idx].dtype,
            self.inputs[idx].dynamic_axes, name='out_quantLayer') for idx in range(len(self.inputs))]
        return outputVar
    def serialize(self):
        return {'otherStuff': self.otherStuff}
    @staticmethod
    def deserialize(inputs, name, state):
        return CustomFun(inputs, state['otherStuff'], name=name)

def f(x):
    @C.Function
    def model(x):
        return C.user_function(CustomFun(x, 'completelyDifferentStuff'))
    return model
nn = C.layers.Sequential([C.layers.Dense(100), f, C.layers.Dense(100)])
x = C.input_variable(10)
y = nn(x)
print(y)
```

**Comment by ebarsoumMS** [comment]
The below code work:

class CustomFun(UserFunction):
    def __init__(self, *args, name='CustomFun'):
        super(CustomFun, self).__init__(list(args), name=name)

    def forward(self, arguments, outputs=None, keep_for_backward=None, device=None, as_numpy=True):
        return None, [x/2 for x in arguments]

    def backward(self, state, root_gradients, variables=None, as_numpy=True):
        # it's not important right now, just a test...
        return root_gradients
        
    def infer_outputs(self):
        #shape, type and dynamic axes of inputs are not changed by this function
        return [C.output_variable(self.inputs[idx].shape, self.inputs[idx].dtype, self.inputs[idx].dynamic_axes) for idx in range(len(self.inputs))]
               
    @staticmethod
    def deserialize(inputs, name, state):
        return CustomFun(inputs, name=name)

def f(x):
    @C.Function
    def model(x):
        return C.user_function(CustomFun(x, name='completelyDifferentStuff'))
    return model
