### ISSUE TITLE
Strided convolution layer with 'sequential = True'

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#2133]
Are you planning to implement a strided convolution layer with 'sequential = True'?

Like f = C.layers.Convolution((2,2), sequential=True, strides = 2)??

**Comment by n17s** [comment]
Not currently.

One workaround which will be available in the next few days would be to use `sequence.unpack`, perform the convolution on the newly created static axis, then call `to_sequence` to get back a sequence if needed.

The item to monitor is 

>  Enable arbitrary input image size via free static axis for convolution

at the current iteration plan #2194

**Comment by n17s** [comment]
If you are in the current master you can now call `sequence.unpack`, `transpose` the tensor to bring the "channels" (features) first, perform regular `convolution` and, if necessary, `transpose` back, and convert it `to_sequence`.
