### ISSUE TITLE
Distributed Mini Batch Reading

### ISSUE THREAD

**Issue by mbz** [Microsoft/CNTK#214]
I am trying to enable distributed training over multiple machines. What we did was to sync everything on all the machines and tun the following command:

`mpiexec -hostfile ~/iplist -map-by ppr:1:node cntk configFile=../Config/test.cntk deviceId=-1 parallelTrain=True`

And it's working but it seems that all the instances are still going over all the data. Looking at the source code, it seems that the code should switch to `StartDistributedMinibatchLoop` in case of parallel training but it is bounded to the following conditions &&

`useParallelTrain &&
 m_enableDistributedMBReading &&
 trainSetDataReader->SupportsDistributedMBRead()`

and `m_enableDistributedMBReadin` is `false` by default and never changes to `true`.

What am I doing wrong?

**Comment by Alexey-Kamenev** [comment]
Hi Mohammad,
In the same file (SGD.cpp) please take a look at line 2546:
```
m_enableDistributedMBReading = configParallelTrain(L"distributedMBReading", false);
```
Did you set `distributedMBReading` to true in your config?
```
    SGD=[
...
        ParallelTrain=[
            parallelizationMethod=DataParallelSGD
            distributedMBReading=true
            parallelizationStartEpoch=1
            DataParallelSGD=[
                gradientBits=1
            ]
        ]
    ]
```

**Comment by mbz** [comment]
Thank you Alexey,

that was the missing line. here is my full config now:

```
    SGD = [
        epochSize = 10000
        minibatchSize = 100
        learningRatesPerMB = 0.01
        momentumPerMB = 0
        maxEpochs = 3
        parallelTrain=true

        parallelTrain=[
            parallelizationMethod=DataParallelSGD
            distributedMBReading=true
            parallelizationStartEpoch=1
            DataParallelSGD=[
                gradientBits=32
            ]
        ]
    ]

```

but now it stuck here:

`ping [requestnodes (before change)]: 2 nodes pinging each other`
`ping [requestnodes (before change)]: 2 nodes pinging each other`

any idea what's wrong?

**Comment by mbz** [comment]
I figured what the problem was. It was an mpi error and could be fixed with passing the following flag `--mca btl_tcp_if_include eth0` in our setting.

It all seems to be working now. I'm running it on two machines:
`Starting minibatch loop, DataParallelSGD training (MyRank = 1, NumNodes = 2, NumGradientBits = 32), distributed reading is ENABLED.`

just as a sanity check, is there anyway that I can confirm it's actually partitioning the data and each reader only reads its own partition?

Since there are only two machines with `epochSize=10000` and `maxEpochs = 3` each reader should only read `15000 = 5000 * 3` data samples. am I right? 
but in the logs I'm still seeing 30000.

```Finished Epoch[ 3 of 3]: [Training Set] TrainLossPerSample = 8.0048001; TotalSamplesSeen = 30000; EvalErrPerSample = 0.5003; AvgLearningRatePerSample = 9.9999997e-05; EpochTime=0.558199```


Thanks.
