### ISSUE TITLE
Any way to "unfreeze" layers that were once frozen in python?

### ISSUE THREAD

**Issue by ChunHsinWang** [Microsoft/CNTK#2144]
For example, I have trained a fully convolutional auto encoder - decoder network. The encoder part was copied with freeze parameter from a pre-trained vgg16 (up until the last convolutional layer), and only update the weights of the decoder parts ( a mirrored version of encoder, with transposed convolution and MaxUnPooling). 

After convergence, I would like to fine-tune the whole network since my image data are quite different from ImageNet. I tried to clone my network with clone parameter, yet the encoder parts are still "frozen" ( I knew this by looking at the number of parameters and tensors, and also in tensorboard graph). 

Is there any way that I can "unfreeze" the frozen layers? Or is there any way that I can only clone the decoder parts and connect it to vgg16? The example only shows how to clone the first few layers but not the last few)

**Comment by pkranen** [comment]
You can clone any subgraph of your network, you just need to know the names of the nodes that you want to start from and the names of the nodes that should be your outputs. To get the names I'd recommend to plot the graph of interest:

```
from cntk.logging.graph import plot
plot(my_network, my_image_file_path)
```

See [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FasterRCNN/FasterRCNN.py#L446) for an example. Once you know the names of you inputs ('from nodes') and your outputs ('to nodes') you can use the helper function shown below. For examples on how it is used see [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FasterRCNN/FasterRCNN.py#L246) or [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FasterRCNN/FasterRCNN.py#L308).

```
def clone_model(base_model, from_node_names, to_node_names, clone_method): 
     from_nodes = [find_by_name(base_model, node_name) for node_name in from_node_names] 
     if None in from_nodes: 
         print("Error: could not find all specified 'from_nodes' in clone. Looking for {}, found {}" 
               .format(from_node_names, from_nodes)) 
     to_nodes = [find_by_name(base_model, node_name) for node_name in to_node_names] 
     if None in to_nodes: 
         print("Error: could not find all specified 'to_nodes' in clone. Looking for {}, found {}" 
               .format(to_node_names, to_nodes)) 
     input_placeholders = dict(zip(from_nodes, [placeholder() for x in from_nodes])) 
     cloned_net = combine(to_nodes).clone(clone_method, input_placeholders) 
     return cloned_net 
```
