### ISSUE TITLE
using CNTK in python: counting total states in "label_mapping_file" 

### ISSUE THREAD

**Issue by TianyanZhou** [Microsoft/CNTK#2147]
Hi~
  When I use the ”HTKMLFDeserializer“ in python to read the "label_mapping_file", it seems that the command line output message "Total (101) state names in state list '..\file_path\file_name'" doesn't match my actual file. There are total 100 states plus a closing empty line in my "label_mapping_file". I also tried different number of states. But the output message is always one state greater than actual states. Also when I remove the last empty line from my file, CNTK will crash and exit. Is there any problem when CNTK reads the "label_mapping_file"?

**Comment by eldakms** [comment]
I think it is the current behavior (empty line is counted as state), same as in BrainScript and the old HTKmlfReader.
Does this lead to any problem?

**Comment by cha-zhang** [comment]
Closing this due to lack of response. Please open a new issue if problems remain.
