### ISSUE TITLE
Documentaion on data-parallel training

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#2158]
Hi all:

Is there a documentation on how to set-up multiple Windows 10 computer on a network, and then doing data-parallel training?
What are the requirements?

I want to try on 2-3 Windows machines, some with GPU and some without GPU.

**Comment by junjieqian** [comment]
There is a doc explaining how to run CNTK on multiple GPUs/machines, https://docs.microsoft.com/en-us/cognitive-toolkit/Multiple-GPUs-and-machines. Please reopen this issue, you need more information other than the linked doc. Thanks

**Comment by arijit17** [comment]
Thanks!

What about other requirements? For example:

Do I need to install exactly the same flavor (CPU-Only, GPU, GPU-1bit-SGD) and Python version of CNTK on all the Windows machines? Or can they be different?

**Comment by junjieqian** [comment]
Have not tested with different flavors. But in my understanding, both the flavor should be the same and the path (binary, configuration files, etc.) should be the same as well. The command to run is something like "mpiexec <options> python ....", so you should expect each GPU/CPU on different/same machines does exactly same thing.
