### ISSUE TITLE
Error：fr's MBLayout inconsistent with matrix,

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#216]
DataFor: fr's MBLayout inconsistent with matrix, for Err1_final Exp operation.
I don't know how to solve it. Thanks!

NDL: Err1=Minus_Log(Lsp_fenzi,normOut_Lsp) 
	 Err1_final=Exp(Err1)
log:   Validating --> Err1.a1 = Log(Lsp_fenzi[257, MBSize 0]) -> [257, MBSize 0]
        Validating --> normOut_Lsp = ElementTimes(featNormOut.yNorm[257, MBSize 0],                 featNormOut.yNorm[257, MBSize 0]) -> [257, MBSize 0]
        Validating --> Err1.b1 = Log(normOut_Lsp[257, MBSize 0]) -> [257, MBSize 0]
        Validating --> Err1.c = Minus(Err1.a1[257, MBSize 0], Err1.b1[257, MBSize 0]) -> [257, MBSize 0]
        Validating --> Err1_final = Exp(Err1.c[257, MBSize 0]) -> [257, MBSize 0]

**Comment by staplesinLA** [comment]
EXCEPTION occurred: DataFor: fr's MBLayout inconsistent with matrix, for "xxx" operation.

I changed my network several times , but it always warn like that with different parameter names.
Please tell me what's the meanning of this kind of warning.  Is it possible that CNTK can't understand how my network constitutes?  thanks.

**Comment by staplesinLA** [comment]
EXCEPTION occurred: DataFor: fr's MBLayout inconsistent with matrix, for "xxx" operation.

I changed my network several times , but it always warn like that with different parameter names.
Please tell me what's the meanning of this kind of warning. Is it possible that CNTK can't understand how my network constitutes when I want to build my own criteria with using too many seperate steps?  thanks.

**Comment by frankseide** [comment]
Criteria are formulas, you can build your own criterion with separate steps.

About the error, a user should never see that, so this indicates a bug. Could you please update to the latest and see if the problem is still there? The string “[257, MBSize 0]” shows that your version is a few months old.

To explain what it means: CNTK has built-in handling for variable-length sequences. Think of it as an additional tensor dimension. The error indicates that a node tried to combine two sequences that do not have the same length, or that one of the inputs is not a sequence where a sequence was expected. An actual such mismatch should be caught during the validation phase, you would see a different error message in that case.

As background, NDL expresses networks as a formula over individual samples, and infers loop structures from presence of time delays. Think of how digital-signal processing engineers would draw filters. This is different from other toolkits. If your input is a sequence, CNTK will manage that implicitly. If the samples in the sequence are independent, then CNTK will process them in parallel. If they are dependent (recurrent), then CNTK will automatically unroll the loop. For efficiency, CNTK will pack many sequences into a single minibatch, in order to use as large as possible CUDA launches. For this reason, CNTK must tightly keep track of sequence lengths and be prepared to encounter inconsistent sequence lengths, which is what the error message is for.

Now, from the NDL you pasted, I don’t see how that is the case. So this might simply be a software bug.

If updating the software does not fix the error, would you mind sharing the call stack that CNTK is printing?

**Comment by staplesinLA** [comment]
OK,it's very helpful.  i will try it in new version of cntk.
Thanks a lot!

**Comment by staplesinLA** [comment]
I try it in the verion of 20160208CNTK. Still, the program terminates. 
Error Message:
`Starting Epoch 1: learning rate per sample = 0.000008  effective momentum = 0.900000  momentum as time constant = 1214.9 samples
minibatchiterator: epoch 0: frames [0..2202442] (first utterance at frame 0), data subset 0 of 1, with 1 datapasses
getbatch: getting randomized frames [0..128] (128 frames out of 128 requested) in sweep 0; chunks [0..0] -> chunk window [0..25)
getbatch: getting randomized frames [128..256] (128 frames out of 128 requested) in sweep 0; chunks [0..0] -> chunk window [0..25)

Starting minibatch loop.
getbatch: getting randomized frames [256..384] (128 frames out of 128 requested) in sweep 0; chunks [0..0] -> chunk window [0..25)

[CALL STACK]
  /home/staples/CNTK-Sourcecode-2016-02-08/CNTK/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::PrintCallStack()  + 0xba  )  [0x7fb6d843009a]
  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::logic_error>(char const*, ...)  + 0xc5  )  [0x5426e5]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNode<float>::DataFor(Microsoft::MSR::CNTK::Matrix<float>&, Microsoft::MSR::CNTK::FrameRange const&)  + 0x5e  )  [0x56103e]
  cntk                           ( Microsoft::MSR::CNTK::SquareErrorNode<float>::ForwardPropNonLooping()  + 0xbb  )  [0x5632ab]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::ForwardProp(Microsoft::MSR::CNTK::FrameRange const&)  + 0xd3  )  [0x6b2fb3]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>)  + 0x7c  )  [0x6b54ec]
  cntk                           ( Microsoft::MSR::CNTK::SGD<float>::TrainOneEpoch(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&, int, unsigned long, Microsoft::MSR::CNTK::IDataReader<float>*, double, unsigned long, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<float>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<float>*> > >*, std::list<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::list<Microsoft::MSR::CNTK::Matrix<float>, std::allocator<Microsoft::MSR::CNTK::Matrix<float> > >&, double&, std::vector<double, std::allocator<double> >&, unsigned long&, std::string)  + 0xa65 )  [0x727315]
  cntk                           ( Microsoft::MSR::CNTK::SGD<float>::TrainOrAdaptModel(int, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, bool, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*)  + 0x1203)  [0x72c123]
  cntk                           ( Microsoft::MSR::CNTK::SGD<float>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*, bool)  + 0x41a )  [0x72df1a]
  cntk                           ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x219 )  [0x74d549]
  cntk                           ( void DoCommands<float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x81c )  [0x59551c]
  cntk                           ( wmainOldCNTKConfig(int, wchar_t**)        + 0x907 )  [0x539a57]
  cntk                           ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53a0b0]
  cntk                           ( main                                      + 0xd8  )  [0x597278]
  /lib64/libc.so.6               ( __libc_start_main                         + 0xfd  )  [0x3600a1ed5d]
  cntk                           (                                                   )  [0x532d05]`

**Comment by staplesinLA** [comment]
`ndlCreateNetwork=[

	feat1InDim=1799
	feat1TrainDim=257
	feat1OutDim=257
	
	hiddenDim=2500
	
	feat2InDim=41
	feat2TrainDim=41
	feat2OutDim=41
	
	
	#LSP data
	featIn=Input(feat1InDim,tag=feature)
	featTrain=Input(feat1TrainDim,tag=feature)
	featOut=Input(feat1OutDim,tag=feature)
			       			       
	#mfcc data
	featInMfcc41=Input(feat2InDim,tag=feature)
	featTrainMfcc41=Input(feat2TrainDim,tag=feature)
	featOutMfcc41=Input(feat2OutDim,tag=feature)
	
	 featNormIn  = MeanVarNorm(featIn)
	 featNormTrain  = MeanVarNorm(featTrain)
	 featNormOut = MeanVarNorm_new(featTrain,featOut)
	 A=Constant(0,rows=257,cols=1)
	 B=Constant(0,rows=41,cols=1)
	 
	 featNormInMfcc41  = MeanVarNorm(featInMfcc41)
	 featNormTrainMfcc41 = MeanVarNorm(featTrainMfcc41)
	 featNormOutMfcc41 = MeanVarNorm_new(featTrainMfcc41,featOutMfcc41)
	 
	 L1 = RBFF2(featNormIn,hiddenDim,feat1InDim,featNormInMfcc41,feat2InDim)
	 L2 = RBFF(L1,hiddenDim,hiddenDim)
	 L3 = RBFF(L2,hiddenDim,hiddenDim)
	 
	 #object function  1
	 MeanSqErr1 = MSEBFF(L3, feat1OutDim, hiddenDim, featNormOut)
	 Lsp_fenzi = SE(featNormOut,A)
	 Lsp_log= Minus_log(MeanSqErr1,Lsp_fenzi)
	 Err1= Exp(Lsp_log)
	 
	 #object function  2
	 MeanSqErr2 = MSEBFF(L3, feat2OutDim, hiddenDim, featNormOutMfcc41)
	 Mfcc_fenzi = SE(featNormOutMfcc41,B)
	 Mfcc_log	= Minus_log(MeanSqErr2,Mfcc_fenzi)
	 Err2= Exp(Mfcc_log)
	 

	 Alpha1=1
	 Alpha2=1
	 ObjFcn= WtObjFcn(Err1,Alpha1,Err2,Alpha2,tag=criteria)
	
	 Hlast = PerDimMeanVarDeNormalization(MeanSqErr1.BFF.FF.P, featNormTrain.xMean, featNormTrain.xStdDev)
 	 #to decoding
 	 OutputNodes=(Hlast)
	 EvalNodes=(ObjFcn)	 
]`

**Comment by staplesinLA** [comment]
Here i use minus_log() and Exp to realize element-wise quotient.  
`Minus_log(a,b)
   	{
   			a1=Log(a)
   			b1=Log(b)
    		c=Minus(a1,b1)
    }`

**Comment by staplesinLA** [comment]
The data is speech ,now it works in new version.Thanks a lot

**Comment by frankseide** [comment]
Great, thanks!
