### ISSUE TITLE
Compare distributed training performance with MXNet

### ISSUE THREAD

**Issue by futurely** [Microsoft/CNTK#217]
which is another popular deep learning framework.
https://github.com/dmlc/mxnet/tree/master/example/image-classification#distributed-training

**Comment by Alexey-Kamenev** [comment]
The benchmarks that I used to compare performance are [here](https://github.com/Alexey-Kamenev/Benchmarks). I'm not familiar with MXNet close enough but if you have time you can try running those benchmarks and share the results here.
Thanks!

**Comment by futurely** [comment]
http://www.cs.cmu.edu/~pengtaox/papers/poseidon_15.pdf
![image](https://cloud.githubusercontent.com/assets/9004594/13737344/6ad7f856-e9f7-11e5-9e0d-6a734fe49c35.png)

**Comment by futurely** [comment]
http://learningsys.org/papers/LearningSys_2015_paper_1.pdf
![image](https://cloud.githubusercontent.com/assets/9004594/13867042/32bcb126-ecf6-11e5-94f3-802148126024.png)
