### ISSUE TITLE
Python PIL module missing

### ISSUE THREAD

**Issue by qflgithub** [Microsoft/CNTK#2176]
under cntk\Tutorials\ImageHandsOn 

CifarConverter.py needs PIL  module, where to find it? 
--error message
Traceback (most recent call last):
  File "CifarConverter.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by liqunfu** [comment]
@qflgithub, please follow answers in this link to install the missing module. 
https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil
