### ISSUE TITLE
linux ubuntu 16.04 build from source with gcc 6.2 fails: Tests/UnitTests/V2LibraryTests/FunctionTests.cpp abs(double) ambiguous

### ISSUE THREAD

**Issue by David-Levinthal** [Microsoft/CNTK#2181]
both top of tree and setting the checkout to V.2.0
I did not see this issue with the default ubuntu 16.04 compiler
I had to upgrade the compiler to get better avx512 support for other investigations

                 from Tests/UnitTests/V2LibraryTests/FunctionTests.cpp:5:
Tests/UnitTests/V2LibraryTests/FunctionTests.cpp: In function 'void CNTK::Test::SetDropoutRate(const CNTK::DeviceDescriptor&)':
Tests/UnitTests/V2LibraryTests/FunctionTests.cpp:1043:87: error: call of overloaded "abs(double)" is ambiguous
         BOOST_TEST(abs(zeroCount(forwardFunc(dropout)) - dropoutRate*shape.TotalSize()) < 100);

this is fixed by adding 
#include <cmath>
and changing abs to fabs on the offending source line

v2.0 then hit
https://github.com/Microsoft/CNTK/issues/2025
https://github.com/Microsoft/CNTK/pull/2104

top of tree then builds fine
standard cntk script test stated in install instructions works

**Comment by eldakms** [comment]
Unfortunately we do not yet officially support gcc 6.2, currently supported version is 4.8. 
If it is not too cumbersome for you, could you please create a pull request with this fix? Thank you very much!
