### ISSUE TITLE
Problem of Seq2Seq Distributed Training Using BMUF

### ISSUE THREAD

**Issue by budiryan** [Microsoft/CNTK#2189]
When I run the default SequenceToSequence example with the default data provided by CNTK 
(https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/BrainScript/G2P.cntk) with BlockMomentum parallel training enabled for <b>4 workers</b>, the workers only sync once per epoch. Changing it to <b>3 workers</b> also didn't help. Only after we changed it to <b>2 workers</b>, the workers sync normally.

Here are some snapshots:
Parallel training 4 workers: (minibatch size: 288, epochSize: 10000)
![image](https://user-images.githubusercontent.com/16099586/28961012-535c7d2e-7933-11e7-972a-d0fd32b56b01.png)
Parallel training 3 workers: (minibatch size: 216, epochSize: 10000)
![image](https://user-images.githubusercontent.com/16099586/28961025-646def8a-7933-11e7-9413-8678313fbe1d.png)
Parallel training 2 workers: (minibatch size: 144, epochSize: 10000)
![image](https://user-images.githubusercontent.com/16099586/28961040-70ac4756-7933-11e7-80e4-b52d481b7798.png)

I did some modifications to the file to support parallel training:
```
SGD = {
        minibatchSize = 144
        learningRatesPerSample = 0.007
        momentumAsTimeConstant = 1100
        gradientClippingWithTruncation = true   # (as opposed to clipping the Frobenius norm of the matrix)
        clippingThresholdPerSample = 2.3   # visibly impacts objectives, but not final result, so keep it for safety
        maxEpochs = 50
        gradUpdateType = FSAdaGrad # TODO: Try FSAdaGrad?
        loadBestModel = false      # true # broken for some models (rereading overwrites something that got set by validation)

        dropoutRate = 0.0
        ParallelTrain = [
            parallelizationMethod = BlockMomentumSGD
            distributedMBReading = true
            BlockMomentumSGD=[
                syncPeriod = $period$
                resetSGDMomentum = true
                useNesterovMomentum = false
            ]
        ]

        # settings for Auto Adjust Learning Rate
        AutoAdjust = {
            autoAdjustLR = "adjustAfterEpoch"
            reduceLearnRateIfImproveLessThan = 0.001
            continueReduce = false
            increaseLearnRateIfImproveMoreThan = 1000000000
            learnRateDecreaseFactor = 0.5
            learnRateIncreaseFactor = 1.382
            numMiniBatch4LRSearch = 100
            numPrevLearnRates = 5
            numBestSearchEpoch = 1
        }
    }
```
I am using 4x Nvidia Tesla K80 GPUs. Thanks and have a good day!

**Comment by KeDengMS** [comment]
data may not be evenly distributed among workers especially when randomization is enabled and with a small minibatch size. This could leads to differences in sync frequency for BMUF. Please try turn off randomization in reader and see if the issue still occurs.

**Comment by budiryan** [comment]
You're right, thanks for the help
