### ISSUE TITLE
Questions on Decoder

### ISSUE THREAD

**Issue by meijiesky** [Microsoft/CNTK#2190]
I am doing some NLP work using CNTK with Python and I have some questions on the decoder.

1. Now there is no beam search decoder and I hope that it can be on your to-do list soon.

2. According to the tutorial 204, the greedy decoder will output the token with the maximum probability at each generation step. However, sometimes the token generated is "unk" (word out of vocabulary) so I think during decoding if the token with the largest probability is "unk", the token with the second largest probability should be generated. I am just wondering how I can do that in Python.

the greedy decoder looks like this.

```python
def create_model_greedy(s2smodel):
    # model used in (greedy) decoding (history is decoder's own output)
    @C.Function
    @C.layers.Signature(InputSequence[C.layers.Tensor[input_vocab_dim]])
    def model_greedy(input): # (input*) --> (word_sequence*)

        # Decoding is an unfold() operation starting from sentence_start.
        # We must transform s2smodel (history*, input* -> word_logp*) into a generator (history* -> output*)
        # which holds 'input' in its closure.
        unfold = C.layers.UnfoldFrom(lambda history: s2smodel(history, input) >> C.hardmax,
                            # stop once sentence_end_index was max-scoring output
                            until_predicate=lambda w: w[...,sentence_end_index],
                            length_increase=length_increase)
        
        return unfold(initial_state=sentence_start, dynamic_axes_like=input)
    return model_greedy
```

3. The last question is that in RL the token is sampled from the vocabulary according to the distribution at each generation step. How can I implement this sampling decoder in CNTK?
 
Any help is appreciated. Thank you.

**Comment by meijiesky** [comment]
@n17s Can I get some help please?

**Comment by n17s** [comment]
For beam search, I will see what can be done. The good thing from the development point of view is the functionality exists in V1.

For generating `unk`, I would expect the s2smodel has a Dense layer with a bias term as the last layer. See this thread #2200 for tips on how to navigate the graph to get to it. I would get to that bias term and do 
```python
# assuming bias is the last bias term added to the log probabilities
b = C.Variable.as_parameter(bias)
tmp = b.value # important to do things with a temporary. In-place slicing won't work
tmp[w2i['unk']] = -1e+10 # assuming w2i is a dictionary that maps tokens to indices
b.value = tmp
```

For the sampling question, see this thread #2047

**Comment by n17s** [comment]
Closing for now. Feel free to reopen.
