### ISSUE TITLE
Batch mean computation in CNTK/brainscript

### ISSUE THREAD

**Issue by pepetko80** [Microsoft/CNTK#2192]
I would like to subtract the minibatch mean from the input. This is performed along with variance normalization and affine transform by BatchNormalization. However, I'd like to isolate this specific operation. Simply put, how can I compute (gain access to) the minibatch mean (using a brainscript interface)?

Thank you!

**Comment by liqunfu** [comment]
@pepetko80 
Please take a look at this:
https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=reduce_mean#cntk.ops.reduce_mean

for example:
>>> m = C.reduce_mean(ii, axis=C.Axis.default_batch_axis())
>>> m.eval([[0,4],[1,5],[2,6]])
array([ 1.,  5.], dtype=float32)

**Comment by pepetko80** [comment]
Thank you Liqun! The provided example uses the Python interface. Can I assume that the first line of the (BrainScript) model description below will do what I need. It seems logical assuming the Reader puts a whole batch into the input ("features") variable.

model (features) = { 
h0 = (features - ReduceMean(features, axis=2))
h1 = DenseLayer {2048, activation=Sigmoid} (h0)
...
z = LinearLayer {labelDim} (h...)
}.z
