### ISSUE TITLE
Non-zero L2RegWeight causes 'Feature Not implemented' exception

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2193]
When using a non-zero value in BrainScript for `L2RegWeight` combined with sparse inputs, `cntk.exe` fails with the following error:

```
Inside File: C:/jenkins/workspace/CNTK-Build-Windows/Source/Math/GPUSparseMatrix.cu  Line: 2034  Function: Microsoft::MSR::CNTK::GPUSparseMatrix<ElemType>::ScaleAndAdd  -> Feature Not Implemented.
```

**Comment by liqunfu** [comment]
@vermorel 
This is a known limitation of CNTK - cannot use L2RegWeight with sparse inputs. I put a feature request for it. 
Thanks.
