### ISSUE TITLE
Custom Criterion Function in Python

### ISSUE THREAD

**Issue by diospyros** [Microsoft/CNTK#2195]
My current understanding of the criterion function for the Trainer module is a per sample computation .. 

How do I create a criterion function which is a function of all of the predictions in the data set?  For instance, if I have hierarchical groupings (specified as flags) and want to the objective function to be dependent upon the behavior of the predictions within these groupings, then I need to be able to scan through all predictions at the end of an epoch instead of on a per sample basis.

Cheers.

**Comment by Ark-kun** [comment]
Criterion can produce either a single value or a bigger tensor of values. In the latter case, the values are summed. If you want to use different aggregation, just apply some sequence or batch aggregations/reductions and use the resulting value as the criterion.

**Comment by n17s** [comment]
@Ark-kun is right. There are operations such as `C.reduce_{mean,min,max,log_sum_exp}(x, axis=C.Axis.default_batch_axis())` that can help with this. For sequence we have only exposed `sequence.reduce_max(x)` and `sequence.softmax(x)` (not really a reduction, but can help implement a non-uniform average) but all others are supported internally so it would be easy to expose them if youo need this functionality.

**Comment by n17s** [comment]
Closing. Feel free to reopen if necessary.
