### ISSUE TITLE
UWP ARM

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#2198]
HI.

I just wanted to (also) say that while the release of the UWP library is great, it really lacks the support for ARM.

What I would imagine many would use the new UWP evaluation library for, is training a model on the PC and then using the model on smart devices such as the Raspberry Pi 3/Arduino running Windows 10 IoT.

 So, like others, I'm looking forward to/hoping for the UWP library for ARM :-)

**Comment by cha-zhang** [comment]
We are not officially support ARM yet, but CNTK can be built with ARM64 as is today. This is how we run the 1-bit convolution code on Raspberry Pi. 

@sayanpa , @zhouwangzw , feel free to add more details.

**Comment by zhouwangzw** [comment]
We have prototype running CNTK on Linux (Ubuntu 14/16 or Debian) on boards like PINE64 or Qualcomm Dragonboard 410C. Unfortunately we have not tried that on Windows on ARM, neither on UWP platform. For building UWP library on ARM, you also need to build OpenBLAS for UWP on ARM.

**Comment by JimSEOW** [comment]
@zhouwangzw The Qualcomm Dragonboard 410C is W10 IoT Core compatible.

**Comment by zhouwangzw** [comment]
@JimSEOW Win10 IoT Core on ARM currently only supports 32-bit, and will extend to 64-bit perhaps by end of this year. When 64-bit support is available, it "should" be feasible to run CNTK UWP on ARM, assuming OpenBLAS could also be complied for UWP on ARM. Currently we do not have any TOA for that yet, and are very appreciated for contribution from you and other folks from the community.

**Comment by JimSEOW** [comment]
@zhouwangzw Perhaps this topic will appear in future TOA. :-) It is good to let the community know what they could contribute. => check if OpenBLAS can be compiled for ARM under VS2015/2017

**Comment by zhouwangzw** [comment]
@JimSEOW Thanks for your interest. Currently this is probably the only thing can do. We have contributed to [OpenBLAS to make it UWP compatible on X64](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#build-openblas-for-universal-windows-platform), but need to check whether it is also the case for UWP on ARM. 
When Win10 IoT on ARM64 is available, the commity can help to build the CNTK UWP for ARM. This could certainly accelarate the TOA, if we do not have enough resource/time.

**Comment by sayanpa** [comment]
Assuming @zhouwangzw's answer was satisfactory, closing this issue. Please reopen or create a new issue.
