### ISSUE TITLE
API to convert CSV to CTF format?

### ISSUE THREAD

**Issue by komal436** [Microsoft/CNTK#2199]
Do CNTK has an api to convert CSV/TSV file to a CTF format file?

**Comment by liqunfu** [comment]
will this work for you instead:
https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_feed_data.ipynb
or 
https://github.com/Microsoft/CNTK/blob/master/Scripts/txt2ctf.py

**Comment by eldakms** [comment]
Currently there is no such converter. For CSV user deserializer have a look at https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_write_a_custom_deserializer.ipynb

I am closing the issue for now, feel free to reopen if needed. Thanks!
