### ISSUE TITLE
Sparse Times/Parameter

### ISSUE THREAD

**Issue by caiom** [Microsoft/CNTK#22]
Hello there :)

I'm trying to create a sparse layer, for that I need sparse matrix multiplication and to define the sparse weight matrix. This is the only framework that has sparse matrix multiplication on GPU. But I could not find a way to use it with the NDL.

I guess the "wrappers" are missing. It also would be nice if you guys provide an example of using the library directly from C++, maybe from there I can access what I need?

Best regards,

Caio Mendes.

**Comment by dongyu888** [comment]
In most cases users would have sparse input but dense weight matrix. In the current version, sparse inputs with dense weight matrix is already supported. Can you tell us your scenario so that we can understand better what kind of sparse parameters are needed? 

Thanks,
Dong

**Comment by caiom** [comment]
Hello Dong, I see. I saw the sparse input code. 

Sure, so its a binary segmentation task where I wanna train a CNN end-to-end, i.e. one image = one sample. I also wanna have some kind of "global context", meaning that local layers (like a convolution, in a fully convolutional network) would not help me that much.

After the regular convolution-pooling layers, I could use a dense layer (fully connected) as my last layer but there would be a lot of weights in this case. So I wanna substitute this layer by a layer that follows a specific pattern of connections and this pattern is not rectangular so I can't use a convolution layer (or any other standard layer) to create it.

I was able to created this layer in theano, but there's no GPU implementation of what they call "sparse structured dot".

As for the pattern, it is inspired in semi-global stereo matching methods.

Best regards,
Caio Mendes

**Comment by simra** [comment]
Is there a pointer to a sparse input example?  I was looking at the UCI Fast Reader docs but didn't see how to configure and format for sparse inputs.

**Comment by frankseide** [comment]
Bing DSSM tasks use it. We were talking about making this an official test case and sample in the public repo.

Dong, do you happen to know if we already have DSSM in our set of samples? I don’t see it.

**Comment by dongyu888** [comment]
I think it’s not part of the examples. I have asked Bhaskar and Ryan whether they can provide an example.

 

Thanks,

 

Dong Yu (俞栋)

**Comment by cmarschner** [comment]
We are waiting to switch to the new CNTKTextReader reader first since we don't have an encoder on github for the readers that were used for it.

Clemens

Am 10.02.2016 um 01:37 schrieb Dong Yu <notifications@github.com<mailto:notifications@github.com>>:

I think it's not part of the examples. I have asked Bhaskar and Ryan whether they can provide an example.



Thanks,



Dong Yu (??)
