### ISSUE TITLE
CUDNN_STATUS_ALLOC_FAILED with ResNet & AlexNet

### ISSUE THREAD

**Issue by jrs53** [Microsoft/CNTK#220]
I have built CNTK using the Debug configuration following the instructions. The Simple2D example seems to work fine. I am trying to train the example ResNet or AlexNet networks on my own image sets. I made the following modifications to the config files:

Changed DataDir to point to the directory containing my images
Changed Reader...File to point to my map of filename<TAB>label
Changed labels...labelDim to match my number of labels
Changed LabelDim in the ndl file to match my number of labels.

I am trying to run using my GPU (NVIDIA Geforce GTX 960M) and in both cases get this error:

Starting minibatch loop.

About to throw exception 'cuDNN failure 2: CUDNN_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=PTNUWCL5099642 ; expr=finder(calgo, algoPerf)'
cuDNN failure 2: CUDNN_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=PTNUWCL5099642 ; expr=finder(calgo, algoPerf)

EXCEPTION occurred: cuDNN failure 2: CUDNN_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=PTNUWCL5099642 ; expr=finder(calgo, algoPerf)

Any help is much appreciated,

James

**Comment by Alexey-Kamenev** [comment]
Hello,
Try reducing mini-batch size, most likely you run out of GPU memory. AlexNet and ResNet are much, much larger than Simple2D sample.

**Comment by jrs53** [comment]
Ah of course - thanks very much
