### ISSUE TITLE
Read function parameters from a model

### ISSUE THREAD

**Issue by ivan-alles** [Microsoft/CNTK#2200]
I have a convnet loaded from a file and would like to compute some of its properties. To do that, I need to go through all the layers and get their types. I figured out how to do this. Now I need to find out some parameters of the layers. For example, for the MaxPooling and Convolution2d I need to know the filter shape and the stride. Is it possible to do this?

**Comment by cha-zhang** [comment]
https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Read-Things-in-Python

**Comment by ivan-alles** [comment]
As far as I understand, that allows me to read the shape of the kernel for the convolutions. How about stride of the convolution and kernel shape and stride of the MaxPooling (it has no weights in this sense)?

**Comment by eldakms** [comment]
You are using the python, correct? If I'm not mistaken they should be exposed in Function.attributes, are they not? Thanks!

**Comment by ivan-alles** [comment]
Yes, I'm using python. For both Convolution and MaxPooling Function.attributes are empty dictionaries.

**Comment by eldakms** [comment]
Then this is a bug, let me reassign this. All function attributes should be available to the outside world thru .attributes dictionary. Thanks!

**Comment by baozi-lala** [comment]
Have you solved this problem?the filter shape can be known by the weight shape,you can use model.parameters.W.shape.but I want to  know whether you get **strides**from model.

**Comment by ivan-alles** [comment]
No, I could not read the strides.

**Comment by baozi-lala** [comment]
oh,i just made it.you can use node.block_root.attributes,the strides is included in the output.if you have better way,please tell me.

**Comment by ivan-alles** [comment]
Strangely, node.block_root.attributes works for the MaxPooling, but not for the Convolution2d:

```
    input_var = cntk.ops.input_variable((1, 10, 10), name='input')
    model = cntk.layers.Convolution2D((3, 3), 16, strides=(4, 4), name='conv1')(input_var)
    model = cntk.layers.MaxPooling((2, 2), strides=(3, 3), name='pool1')(model)

    conv1 = model.find_by_name('conv1')
    pool1 = model.find_by_name('pool1')
    print(conv1.block_root.attributes) # prints  {}
    print(pool1.block_root.attributes) # prints {.... 'strides': (3, 3) ...}
```

**Comment by baozi-lala** [comment]
yes ,actually,I don't understand what is the meaning of block_root.

**Comment by ivan-alles** [comment]
Now I see. So, calls like `m = cntk.layers.Convolution2D(...)` actually add multiple nodes to the graph. This was not obvious to me.

**Comment by baozi-lala** [comment]
I tried to print conv1.block_root,then I get this:
`('layer', ReLU: Output('Plus36_Output_0', [#], [8 x 26 x 26]) -> Output('ReLU38_Output_0', [#], [8 x 26 x 26]))`
therefore the `conv1.block_root.input` has only one value which is 
`(Output('Plus36_Output_0', [#], [8 x 26 x 26]),))` 
and `conv1.block_root.input[0].owner` got the error `'tuple' object has no attribute 'owner'`
I guess that is the reason of activation function.So what should I do? @n17s

**Comment by n17s** [comment]
That message comes from Python and says that `conv1.block_root.input[0]` is a tuple. I'm not sure why, but if it is a tuple indeed you can take the first element like this: `conv1.block_root.input[0][0]`. That should give you an output variable that you can then call `.owner` on it

**Comment by ivan-alles** [comment]
Is it possible to get attributes from a UserFunction? I now get empty dictionaries:

```
# A copy from CNTK example.
class MySigmoid(cntk.ops.functions.UserFunction):
    def __init__(self, arg, name='MySigmoid'):
        super(MySigmoid, self).__init__([arg], name=name)

    def forward(self, argument, device=None, outputs_to_retain=None):
        sigmoid_x = 1 / (1 + np.exp(-argument))
        return sigmoid_x, sigmoid_x

    def backward(self, state, root_gradients):
        sigmoid_x = state
        return root_gradients * sigmoid_x * (1 - sigmoid_x)

    def infer_outputs(self):
        return [cntk.output_variable(self.inputs[0].shape, self.inputs[0].dtype,
            self.inputs[0].dynamic_axes)]

    @staticmethod
    def deserialize(inputs, name, state):
        return MySigmoid(inputs[0], name)

def user_attributes():
    # Create a simple model
    input_var = cntk.ops.input_variable((1, 4, 4), np.float32, name='input')
    my_function_orig = MySigmoid(input_var, name='UserFunction')
    user_function_orig = cntk.user_function(my_function_orig)
    model = cntk.ops.minus(user_function_orig, cntk.ops.constant(100))

    #Try to set attributes wherever possible
    my_function_orig.attributes['key'] = 'value'
    user_function_orig.attributes['key'] = 'value'

    # Try to recover attributes wherever possible
    user_function = model.find_by_name('UserFunction')
    print(user_function.attributes) # Prints {} ??????????????
    print(user_function.root_function.attributes) # Prints {} ??????????????
```

**Comment by baozi-lala** [comment]
when I tried
 `con1.block_root.inputs[0][0].owner.attributes`,
I got 
`{u'endIndex': 1L, u'beginIndex': 0L, u'axis': (u'ordered', u'static', 2L)}`
 I guess Because the operation of convolution is activation(w*x+b),in your example ,your last operation is plus.so your outputs is plus operation,while my last operation is activation function so my inputs is plus.  Is there any method that can let me into deeper operation to make my output operation is plus?.
Besides, I don't quite understand the composite function and block function you said. Can you give some examples to help me understand? @n17s @cha-zhang

**Comment by n17s** [comment]
@ivan-alles attributes for UserFunctions are not currently supported. This is typically not a problem since the Python UserFunction is a class and you can stuff in any attributes you want in the class' data members. If you have a use case where that's not sufficient, let us know.

**Comment by n17s** [comment]
@baozi-lala you can continue traversing the graph by asking of the inputs of the owner, asking for the owners of those inputs and so on. 

For your other question, the difference between a composite function and a block is that a composite contains all its dependencies while a block is typically a collection of primitive operations that logically belong together. As an example, if I have a 5 layer network of Dense layers, each Dense layer is a block function but if I ask for the composite network at the last layer I am going to get all five layers.

**Comment by ivan-alles** [comment]
Yes, I do have a problem with reading attributes of a UserFunction. I can access them inside the function (e.g. in forward()), but not outside it. I described it [here](https://github.com/Microsoft/CNTK/issues/2242).

**Comment by n17s** [comment]
Sorry it is not supported right now. I did add the feature request tag on your other issue #2242. Hopefully we can get to it in the next iteration.
