### ISSUE TITLE
Using other base models in faster rcnn

### ISSUE THREAD

**Issue by fathomson** [Microsoft/CNTK#2202]
By default the faster rcnn has a config for the AlexNet and VGG16 base models.  I tried to get it to work with ResNet however I was not able to find the correct config parameters. I've used print parameter and plot() to look for the required node names, however not successfull. 
How can I get faster rcnn to work with i.e. ResNet base model.

**Comment by pkranen** [comment]
ResNet is not yet supported since currently we only have ROI max pooling and not ROI average pooling.

**Comment by sooraj-citta** [comment]
The documentation (https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Faster-R-CNN) explains about only the models Alexnet & VGGnet. I can download the model file 'InceptionV3_ImageNet_CNTK' but where to get the configuration file for the inception.  Any hints would be helpful!
