### ISSUE TITLE
Unable to load may MyModel.dnn in C# 

### ISSUE THREAD

**Issue by Aminullah6264** [Microsoft/CNTK#2204]
i have train my object detection model on FastRCNN using python and save it using save_model("MyModel.dnn").
Now i try to wright script to evaluate it in C#. it throw an exception on following encircle line.
that Error: Sequence contains more than one element.
please help me to solve this problem problem.
This is my code for loading model, i have follow the steps, which is given in CNTK examples

![1](https://user-images.githubusercontent.com/15268491/29052095-a377b142-7c22-11e7-85fe-d87a1fdc1415.PNG)

**Comment by pkranen** [comment]
Fast R-CNN requires two inputs (hence "Sequence contains more than one element"), the first is the image and the second are the ROI proposals (see [this tutorial](https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Fast-R-CNN#algorithm-details) for more details). For evaluation in Python see `evaluate_fast_rcnn()` method in `A2_RunWithPyModel.py`:

```
    input_map = {
        model.arguments[0]: test_minibatch_source[features_stream_name],
        model.arguments[1]: test_minibatch_source[roi_stream_name],
    }
```

In C# you would need to create the ROI proposals yourself. We do not have a C# implementation.

**Comment by Aminullah6264** [comment]
Dear @pkranen 
i don't have ROIs for Test images.
i train my model on images of 10 videos 
now i want to test it for more videos in which i don't have ROIs
i want that model should predict ROIs for me

**Comment by pkranen** [comment]
The model does not predict ROIs, it requires ROIs as an input and predicts whether and which object is in the ROI. You can try [Faster R-CNN](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FasterRCNN) which has a region proposal network and does not require ROIs as an input. There will be a tutorial added on Faster R-CNN in the coming weeks, for now please use the Readme file in the above folder.

**Comment by Aminullah6264** [comment]
Dear @pkranen  
can i train FasterRCNN to detect ROIs using the following setups given in your Examples.
