### ISSUE TITLE
GPU Nvidia Quadro 6000 not detected by cntk.all_devices()

### ISSUE THREAD

**Issue by manolodepuerto** [Microsoft/CNTK#2208]
I have installed an Nvidia Quadro 6000 GPU on a PC with the latest driver updates, and it is not being detected by CNTK. I have installed the precompiled version of CNTK 2.1 for python 3.5 for GPU, installed CUDA and other dependencies. 

However, when using cntk.all_devices() I only get 1 device, CPU. Attempting to set the GPU as the default with try_set_default_device() subsequently fails since CNTK is not seeing the GPU. I have tried with CNTK 2.0 as well, updated drivers, reinstalled all dependencies (I reinstalled anaconda3 python and CUDA as well) and still nothing. I have verified that the GPU is working properly.

Thanks in advance for your help.

**Comment by ebarsoumMS** [comment]
What does NVidia-smi command show?
