### ISSUE TITLE
Documentation of ConvolutionalLayer

### ISSUE THREAD

**Issue by L-Ramos** [Microsoft/CNTK#2209]
I'm using the sample code from:
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ConvNet/BrainScript/ConvNet_CIFAR10.cntk

Here we have a ConvolutionalLayer function that I just can't find any documentation from.
I'm used to working with nld files and I had a Macros.nld where I was able to define the functions like this:

ConvBNLayerW(W, inp, outMap, kW, kH, hStride, vStride, bValue, scValue, bnTimeConst) = [
    b = LearnableParameter(outMap, 1, init=fixedValue, value=bValue)
    sc = LearnableParameter(outMap, 1, init=fixedValue, value=scValue)
    m = LearnableParameter(outMap, 1, init=fixedValue, value=0, learningRateMultiplier=0)
    isd = LearnableParameter(outMap, 1, init=fixedValue, value=0, learningRateMultiplier=0)   
    c = Convolution(W, inp, kW, kH, outMap, hStride, vStride, zeroPadding=true, imageLayout=$imageLayout$)
    y = BatchNormalization(c, sc, b, m, isd, eval=false, spatial=true, normalizationTimeConstant=bnTimeConst, imageLayout=$imageLayout$)
]

I believe this ConvolutionalLayer is a higher level function? I'd like to know where can I find the parameters for it. Are those the same from https://docs.microsoft.com/en-us/cognitive-toolkit/Convolution

**Comment by cha-zhang** [comment]
If you are using BrainScript, the reference is here: 
https://docs.microsoft.com/en-us/cognitive-toolkit/Using-CNTK-with-BrainScript 

In particular, ConvolutionLayer: 
https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-layers-reference#convolutionallayer

**Comment by L-Ramos** [comment]
Perfect, Thanks
