### ISSUE TITLE
Docker image not extracting on macOS as suggested

### ISSUE THREAD

**Issue by michhar** [Microsoft/CNTK#2210]
Hi,

I'd love to get this working as I like CNTK as a framework.  It has been suggested to use the docker image for macOS in [#43].  However, I'm getting an error extracting at one of the steps in the `docker pull` command.  I'm trying CNTK latest on macOS with the docker image according to [these](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Docker-Containers) instructions.  I'm on macOS Sierra 10.12.5 (latest macOS as of today).

I've done the following to create an environment and pull the docker image.

```
conda create --name cntk-py35 python
source activate cntk-py35
docker pull microsoft/cntk
```

With the pull producing the following output and error (which indicates this image will only work on Linux for now...correct me if I'm wrong please).

```
Using default tag: latest
latest: Pulling from microsoft/cntk
7ee37f181318: Pull complete
df5ffabe5e97: Pull complete
ae2040ed51a1: Pull complete
3ce7010d244b: Pull complete
2538b201d2a6: Pull complete
58f838b9bc8d: Pull complete
1f549555b9aa: Pull complete
d3a770680b16: Pull complete
5acca066722c: Pull complete
44c32d6c8456: Pull complete
2117305e3ae9: Extracting [==================================================>] 2.201 GB/2.201 GB
failed to register layer: Error processing tar file(exit status 1): write /root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/libs/libcublas.so.8.0: no space left on device
```

Shall I try manual install?  Or use a dockerfile to build an image?  Any suggestions?

**Comment by akzaidi** [comment]
Hey michhar :)

Looks like it may be due to lack of disk space:
`write /root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/libs/libcublas.so.8.0: no space left on device`

Could you check space first:
`df -h`

**Comment by ebarsoumMS** [comment]
Check your disk space, if that is not the issue please reopen the issue.

**Comment by michhar** [comment]
@akzaidi @ebarsoumMS Thank you.  I've got a similar issue still so not necessarily reopening, but am just wondering how big the docker image is for `microsoft/cntk` as I've freed up about 40 more gb of disk space and increased my docker machine's RAM to 16 gb which is max for my machine (probably not necessary, yes?).  I've also now tried not using a conda or virtualenv created Python environment and rather just pulling on my system python which is a Miniconda3 install (3.5.3).  Here's some of my commands and messages including checking disk usage:

```
umwhat:cntk micheleenharris$ docker-machine start
Starting "default"...
Machine "default" is already running.
umwhat:cntk micheleenharris$ docker pull microsoft/cntk
Using default tag: latest
latest: Pulling from microsoft/cntk
7ee37f181318: Pull complete
df5ffabe5e97: Pull complete
ae2040ed51a1: Pull complete
3ce7010d244b: Pull complete
2538b201d2a6: Pull complete
58f838b9bc8d: Pull complete
1f549555b9aa: Pull complete
d3a770680b16: Pull complete
5acca066722c: Pull complete
44c32d6c8456: Pull complete
2117305e3ae9: Extracting [==================================================>] 2.201 GB/2.201 GB
failed to register layer: Error processing tar file(exit status 1): write /root/anaconda3/lib/python3.5/site-packages/PyQt4/QtGui.so: no space left on device
umwhat:cntk micheleenharris$ df -h
Filesystem                          Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1                         465Gi  420Gi   45Gi    91% 2700309 4292266970    0%   /
devfs                              189Ki  189Ki    0Bi   100%     654          0  100%   /dev
map -hosts                           0Bi    0Bi    0Bi   100%       0          0  100%   /net
map auto_home                        0Bi    0Bi    0Bi   100%       0          0  100%   /home
localhost:/ogZSKP6RSWyOG3Za3fSNzl  465Gi  465Gi    0Bi   100%       0          0  100%   /Volumes/MobileBackups
/dev/disk0s3                       620Mi  552Mi   68Mi    90%      59 4294967220    0%   /Volumes/Recovery HD
```

**Comment by michhar** [comment]
I solved this by deleting my existing docker images, some of which were very large I came to find out. :)  Thanks for the help, again.
