### ISSUE TITLE
how to check cudnn version?

### ISSUE THREAD

**Issue by pallashadow** [Microsoft/CNTK#2218]
I installed cntk via miniconda. 
I installed cudnn 6 manually some days ago, and planning to update it to cudnn 7. 
is there any way to check whether cudnn in correctly installed?
and how can I print the cudnn version CNTK is currently using?

**Comment by ebarsoumMS** [comment]
You can' use cuDNN 7 with CNTK, unless you build CNTK from the source. It need to link with cuDNN lib.

**Comment by Metamorphus** [comment]
So how do I print the CUDNN version used by CNTK?

**Comment by adv-ai-tech** [comment]
So how do I print the CUDNN version used by CNTK?

**Comment by ebarsoumMS** [comment]
Each version of CNTK support only one cuDNN. There is no way to print which version of cuDNN CNTK uses.

**Comment by thiagocrepaldi** [comment]
CNTK expects cudnn 7.0, but there is no way to print this external/dynamic dependency. Follow https://docs.microsoft.com/en-us/cognitive-toolkit/setup-gpu-specific-packages-linux#cudnn for Linux and https://docs.microsoft.com/en-us/cognitive-toolkit/setup-gpu-specific-packages for Windows
