### ISSUE TITLE
Gradient quantization is unsupported

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#222]
When I run the speech example with command:
cntk configFile = ../config/cntk configFile=../Config/FeedForward.cntk
exception as follows occured.
...........................
EXCEPTION occurred: Gradient quantization is unsupported in CNTK binaries built without quantized gradient aggregation support!

**Comment by frankseide** [comment]
This is a submodule that you need to get the source code for from a different repository, as that is under a different license. This page on the CNKT Wiki contains the necessary information where and how to get it (it’s a single git submodule command to get the code and an environment variable you must set): https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD

**Comment by frankseide** [comment]
I will close this now. Please reopen if this does not solve it.

**Comment by amarkatti** [comment]
I have a single server CPU machine and no GPU, can I enable 1 bit SGD in my machine? Because I followed the above procedure and this does not seem to fix my issue.
