### ISSUE TITLE
ImportError: No module named 'cntk' on Ubuntu

### ISSUE THREAD

**Issue by cheers00** [Microsoft/CNTK#2220]
On Ubuntu, I followed the steps from https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-python?tabs=cntkpy21 and installed `CNTK and version check script python -c "import cntk; `print(cntk.__version__)" worked.

But with new putty session, I am getting `ImportError: No module named 'cntk' error`. How to setup CNTK environment again? 

Thanks

**Comment by frankibem** [comment]
For Python only installation:
1. If you installed CNTK without an environment, then importing it should work. Verify that you are running the version of python that you installed CNTK for i.e. python or python3

2. If you installed CNTK in a conda environment, then you must first activate that environment. Assuming the environment you created is "cntk-py35". You can run `activate cntk-py35`. Running `python` and importing cntk afterwards should work

For a scripted install, assuming your CNTK install directory is `/home/<username>/cntk`, you should:
- cd into `/home/<username>/cntk`
- run `source activate-cntk`

**Comment by n17s** [comment]
If the above answer has not resolved your problem please provide more information on the error.

**Comment by sayanpa** [comment]
It has been about a month since frankibem's suggestion. Assuming the issue has been resolved and closing it. Please reopen another one if you need further help.
