### ISSUE TITLE
read type of activation function from a model

### ISSUE THREAD

**Issue by baozi-lala** [Microsoft/CNTK#2221]
I have a convnet model loaded from a file and would like to compute some of its properties.How to read the **activation function** of each layer in **Python**. besides,for the MaxPooling and Convolution2d,I can know the filter shape by the shape of weight.but how can I know  the stride. Is it possible to do this?

**Comment by ebarsoumMS** [comment]
What you mean by "compute its properties"?

**Comment by baozi-lala** [comment]
sorry，I didn't describe it very well.my question is,
if I have a convnet model file,Can I get its network structure by loading the file?
Every convolution layer has an activation function, and can  I read this activation function.

**Comment by ebarsoumMS** [comment]
Yes, you can. Here CNTK code that iterate through the graph and plot the entire graph into a PNG or PDF file:
https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/logging/graph.py 

You can modify the code to match your need or use some of its functionalities, which u exposed though CNTK.logging package.

**Comment by baozi-lala** [comment]
thank you! i get the structure by C.logging.depth_first_search,but i don't know how to get the activation function of these layers.
