### ISSUE TITLE
Add serializable custom attributes to a model in python.

### ISSUE THREAD

**Issue by ivan-alles** [microsoft/CNTK#2222]
Is there a way to add some custom attributes to the model so that they can be saved and loaded with the rest of the model. For example:

model['build_time'] = '12:44'
model.save('file.dnn')
.....
model = cntk.load_model('file.dnn')
print(model['build_time'])

**Comment by ebarsoumMS** [comment]
Sadly, no.

**Comment by bencherian** [comment]
If something like this does get implemented it would be great if these attributes were accessible through the C++ API as well.

**Comment by ebarsoumMS** [comment]
If you guys want to help out, feel free to send us a pull request.

**Comment by ivan-alles** [comment]
I'm thinking about a workaround for this. I can add a UserFunction to the model. It can have a dictionary for custom attributes. I can give it a unique name. Then I can find it by name and read the attributes. What I do not know, is how to add the function so that it just hangs there. The only way I can think of now is an identity function, for example directly after the input variable.
