### ISSUE TITLE
what neural network model for the picture below are supported by cntk?

### ISSUE THREAD

**Issue by baozi-lala** [Microsoft/CNTK#2225]
what neural network model for the picture below are supported by cntk?
which of them are supported by higher level API,and which are supported by core or lower level only?
![dl](https://user-images.githubusercontent.com/21255466/29392852-e277751e-8332-11e7-92b4-bc1eb085bdc8.png)

**Comment by ebarsoumMS** [comment]
Which one you are interested in? You should be able to implement most of them. There is no strict delineation between low level and high level API.

Also, please move non-issue related question to stackoverflow with tag CNTK.
