### ISSUE TITLE
C++ CNTK::Function::Load() won't load models

### ISSUE THREAD

**Issue by Draghtnod** [Microsoft/CNTK#2230]
```
std::ifstream ifs( L"model_0.cmf", std::ifstream::in );
auto model = CNTK::Function::Load( ifs );
```

This causes a RuntimeError stating:

`Failed to parse Dictionary from the input stream.`

Same happens with `CNTK::Function::Load( buffer, length )`, but `CNTK::Function::Load( filepath )` gives `Unknown error.`.

The model is from the Examples, this also happens with my own models saved via python `cntk.ops.functions.Function.save()`
Tested with CNTK 2.0 and CNTK 2.1.

As I read these files should be in model-v2 format. If I'm not missing something, this isn't the expected behaviour, right?

**Comment by zhouwangzw** [comment]
The Function::Load() either takes the path to file as parameter, or the byte buffer as the first parameter, as described [here](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Library-Native-Eval-Interface#load-a-model). It does not support ifstream as paraemter. If use byte buffer, you should first read the model file into the byte buffer, and then call the Load() function.

**Comment by Draghtnod** [comment]
> It does not support ifstream as paraemter.

https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L3380-L3384

> If use byte buffer, you should first read the model file into the byte buffer, and then call the Load() function.

I did.

**Comment by edmBernard** [comment]
I don't test it but maybe you need to explicitly cast in istream : 
```cpp
std::ifstream ifs( L"model_0.cmf", std::ifstream::in );
std::istream&    s   = ifs;
auto model = CNTK::Function::Load( s );
```

**Comment by Draghtnod** [comment]
Negative, tested with same result. This cast happens automatically when the function is called.

I digged into the source code of this function. The stream is given directly to CNTK::Dictionary via the [>> operator](https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/Serialization.cpp#L780), which passes it to [CNTK::Serializer::Read()](https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/Serialization.cpp#L690) , which calls over a common Read() the [ParseMessage()](https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/Serialization.cpp#L654). When this funciton fails, the RuntimeError with the given message is thrown. Unfortunately, there are no explanaroty error messages within this funciton, so i have no clue at which point it fails. I'd guess [here](https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/Serialization.cpp#L687).

**Comment by Draghtnod** [comment]
I installed Googles Protocol Buffers and deserialized the model file manually. That worked and within the examples, i realized that the file stream has to be opened with the binary flag! That is not documented anywhere within CNTK Docs.

Finally this works:
```
std::ifstream ifs( L"model_0.cmf", std::ifstream::in | std::ifstream::binary );
auto model = CNTK::Function::Load( ifs );
```

I could not get the other two Load() versions to work. I'm not sure what's the problem there.

**Comment by Draghtnod** [comment]
Is was happy too early. The headaches continue.. `CNTK::Function::Load( istream )` throws no exception anymore, but the read Function seems to be broken. Trying to access anything of these:
```
auto arguments = model->Arguments();
auto attributes = model->Attributes();
auto constants = model->Constants();
auto inputs = model->Inputs();
auto outputs = model->Outputs();
auto parameters = model->Parameters();
auto str = model->AsString();
```
throws memory access exceptions because of seemingly broken internal pointers. If i look at the contents of the Function in the debugger, i see no senseful data:
```
+		m_inputs	{ size=0 }	std::vector<CNTK::Variable,std::allocator<CNTK::Variable> >
+		m_outputsInitFlag	{_Opaque=0x0000000000000000 }	std::once_flag
+		m_outputInitializingByThreadId	{_Id=50465552 }	std::thread::id
+		m_outputs	{ size=461168601842738587 }	std::vector<CNTK::Variable,std::allocator<CNTK::Variable> >
+		m_rootFunction	0x00540053004c0054 {m_inputs={ size=??? } m_outputsInitFlag={_Opaque=??? } m_outputInitializingByThreadId=...}	std::shared_ptr<CNTK::Function>
+		m_name	<Fehler beim Lesen der Zeichen der Zeichenfolge.>	std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >
+		m_uid	L""	std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >
+		m_attributes	{m_dictionaryData=empty }	CNTK::Dictionary
+		m_dirtyAttributes	{ size=8 }	std::unordered_set<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >,std::hash<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > >,std::equal_to<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > >,std::allocator<std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > > >
		m_native	true (176)	bool
```
No inputs and attributes and 461168601842738587 outputs can't be right..

**Comment by edmBernard** [comment]
can you test that this method (I don't have test it)
```cpp
class BufferFile
{
  public:
    std::string file_path_;
    int length_;
    char *buffer_;
    explicit BufferFile(std::string file_path) : file_path_(file_path)
    {
        std::ifstream ifs(file_path.c_str(), std::ios::in | std::ios::binary);
        if (!ifs)
        {
            std::cerr << "Can't open the file. Please check " << file_path
                      << ". \n";
            length_ = 0;
            buffer_ = NULL;
            return;
        }
        ifs.seekg(0, std::ios::end);
        length_ = ifs.tellg();
        ifs.seekg(0, std::ios::beg);
        std::cout << file_path.c_str() << " ... " << length_ << " bytes\n";
        buffer_ = new char[sizeof(char) * length_];
        ifs.read(buffer_, length_);
        ifs.close();
    }
    int GetLength() { return length_; }
    char *GetBuffer() { return buffer_; }
    ~BufferFile()
    {
        if (buffer_)
        {
            delete[] buffer_;
            buffer_ = NULL;
        }
    }
};
```
you can use it like that :
```cpp
BufferFile buff("model_0.cmf");
auto model = CNTK::Function::Load( buff.GetBuffer(), buff.GetLength() );
```

**Comment by Draghtnod** [comment]
Thanks for the code. I tested it. Reading the file buffer this way works for the `Load( buffer, size )` function. The resulting model is the same as the giving the ifstream to the Load() directly. Both broken. If you check out the [Load( buffer, length )](https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/Function.cpp#L481-L504), you can see that it puts the buffer back into an istream and feeds it to `Load( stream )`.

I have tried to feed the stream to the Dictionary manually. The resulting Dictionary is broken as well. If i feed the broken dictionary to `CNTK::Function::Deserialize()`, the resulting function is the exact same like it came from `Load( stream )`. The problem seems to be somewhere in the Dictonaries Serializer. That is used to [Read()](https://github.com/Microsoft/CNTK/blob/08b9b5a2d6754c97f7afff8c8ca4e9b8c2290cf6/Source/CNTKv2LibraryDll/Serialization.cpp#L690-L697) the istream. Unfortunately, i can't debug that function without the complete project sources.

**Comment by Draghtnod** [comment]
Ok that took many hours. I built the Libraries myself and realized, that the debug libraries work fine! Using the release libraries in my project in debug mode, does not and leads to the described effect. But using the release libraries (also the precompiled ones) in release mode works fine again. Very strange. There are no compiler or linker errors when compiling with the release libraries in debug mode. I could not determine the compiler or linker flag that causes the library not to funciton.

**Comment by wolfma61** [comment]
this could be due to incompatibility between STL in debug/release mode. You can't mix while using STL ....

**Comment by zhouwangzw** [comment]
I am closing the issue due to lack of response. Please open a new one if you still have questions.
