### ISSUE TITLE
How to set learning rate between epochs in Keras?

### ISSUE THREAD

**Issue by oxrider** [Microsoft/CNTK#2236]
I tried `model.optimizer.lr.set_value(1e-4)`, which resulted in 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cntk/cntk_py.py", line 1574, in set_value
    return _cntk_py.Parameter_set_value(self, value)
TypeError: in method 'Parameter_set_value', argument 2 of type 'CNTK::NDArrayViewPtr const &'

```

I'm using `keras.optimizers.SGD` as my optimizer

**Comment by souptc** [comment]
to customize the lr, you need pass the value when init the keras optimizer:
`model.compile(loss='categorical_crossentropy',
              optimizer=SGD(lr=1e-4),
              metrics=['accuracy'])`
