### ISSUE TITLE
FastRCNN gives Mean AP of 0.63 instead of > 0.9

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#2240]
FastRCNN in 2.1 (CPU/GPU/GPU 1-bit) all gives a score of 0.63.

The example have a Mean AP of > 0.90

![image](https://user-images.githubusercontent.com/7712296/29485677-0ff4a8a0-84d6-11e7-85da-e316fbd644a4.png)

**Comment by mortengryning** [comment]
Also: BS and PS gives different result (both > 0.6 < 0.7)

**Comment by mortengryning** [comment]
Using Python 3.4 or 3.5 makes no difference

**Comment by mortengryning** [comment]
Also, setting self.cntk_nrRois = 2000 (instead of 100) entails a mean AP of 0.9554. So I don't know if it's just that the nrRois was set to a value less than that of the example?

**Comment by spandantiwari** [comment]
It, most probably, is just that, as noted in the comment right where the parameter is set in FastRCNN/PARAMETERS.py (line # 20). Good to see that you are seeing the expected results.
