### ISSUE TITLE
Type or namespace 'IEvaluateModelManagedF' is missing.

### ISSUE THREAD

**Issue by amarkatti** [Microsoft/CNTK#2241]
Hello,

I am trying to build the CNTK in visual but it gives me the following error "The type or namespace name 'IEvaluateModelManagedF' could not be found (are you missing a using directive or an assembly reference? ". Any help would be really appreciated.

**Comment by zhouwangzw** [comment]
@amarkatti Do you mean build the cntk.sln from source by "build the CNTK in visual"? Currently, VS2015 Update 3 is required, and platform X64 is needed for configuration. You can instructions about development setup on Windows [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-development-environment).

Or you want to build your application using CNTK Library for model evaluation/inference? For that you need to install required your nuget packages. Please find more information in [this page](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Library-Evaluation-on-Windows).

**Comment by mortengryning** [comment]
You need the mkl nuget library if you're doing evaluation (compared to the other nuget libraries where you use the Function to load the model :-))

**Comment by wolfma61** [comment]
The CNTK Nuget package contains all the required dependencies to evaluate based on an existing CNTK trained model, No additional libraries (like MKL) need to be installed. The page Zhou mentions lists the dlls you would need to distribute with your application.

**Comment by mortengryning** [comment]
Sorry I was unclear.

I've experienced that there different CNTK nuget packages:

![image](https://user-images.githubusercontent.com/7712296/29494079-2516f5d0-85a3-11e7-8527-0e39f5cac41e.png)

It seems that the mkl one supports IEvaluateModelManagedF, whereas the CNTK.GPU/CNTK.CPU support Function.

**Comment by zhouwangzw** [comment]
Except that you have legacy applications that already used IEvaluateModelManageF, we recommend users to use Function interface provided by CNTK.GPU or CNTK.CPUOnly, as descrbided in the following sections: https://docs.microsoft.com/en-us/cognitive-toolkit/NuGet-Package#overview, and https://docs.microsoft.com/en-us/cognitive-toolkit/NuGet-Package#legacy-applications-using-cntk-evaldll-interface.

**Comment by amarkatti** [comment]
@zhouwangzw, thanks & I will check by installing the above mentioned nuget package. But im wondering why this was not part of list of instructions here : https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-development-environment. Also, shouldn't 'IEvaluateModelManageF' interface be part of source code (cntk.sln). when I open the cntk.sln in visual studio I can only see references to this interface but I do not see any code where this interface actually defined.

**Comment by zhouwangzw** [comment]
@amarkatti If you build from cntk.sln, you do NOT need to install the Nuget packages. (Only if you just want to use Eval library instead of build cntk.sln, you need Nuget packages, as said in my response above). This is also why nuget package installation is not a part of Setup-Developer-Environment instructions.

For build using cntk.sln, the IEvaluateModelManageF is defined in Extensibility/EvalWrapper/EvalWrapper.cpp. When did you get the error regarding IEvaluateModelManageF, which project, which configuration (Release/Debug/Debug_CPUOnly/Release_CPUOnly), which platform (must be X64)? And you need Visual Studio 2015 Update 3. Could you please share the build output?

**Comment by amarkatti** [comment]
Hello Zhou,
I am getting this error in CSEvalClient project.
I am using Debug_CPUOnly and 64-bit platform. Yes I am using the visual studio 2015 update 3.
Looks like I am doing some naïve mistake here because the Evaluation project itself is not getting loaded in the solution. 
See the attached screenshot below, I do not see any evaluation project inside the examples project.
![cntk error](https://user-images.githubusercontent.com/1284554/29655244-3c332698-8865-11e7-960a-91db5370ed27.PNG)

Here is the build output:
1>------ Skipped Build: Project: MathCUDA, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: Math, Configuration: Debug x64 ------
3>------ Build started: Project: Multiverso, Configuration: Debug x64 ------
3>C:\repos\cntk\Source\Multiverso\src\Multiverso.vcxproj(306,5): warning : DataParallelASGD was disabled.
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(349,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|x64.
2>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/PROFILE' specification
2>BatchNormalizationEngine.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification
2>LINK : fatal error LNK1104: cannot open file 'Cntk.Math.Cuda-2.0rc1d.lib'
4>------ Build started: Project: CNTKv2LibraryDll, Configuration: Debug x64 ------
5>------ Build started: Project: CNTKTextFormatReader, Configuration: Debug x64 ------
6>------ Build started: Project: LibSVMBinaryReader, Configuration: Debug x64 ------
7>------ Build started: Project: BinaryReader, Configuration: Debug x64 ------
6>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
5>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
8>------ Build started: Project: DSSMReader, Configuration: Debug x64 ------
9>------ Build started: Project: HTKMLFReader, Configuration: Debug x64 ------
7>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
8>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
10>------ Build started: Project: LMSequenceReader, Configuration: Debug x64 ------
11>------ Build started: Project: LUSequenceReader, Configuration: Debug x64 ------
9>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
12>------ Build started: Project: SparsePCReader, Configuration: Debug_CpuOnly x64 ------
11>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
13>------ Build started: Project: UCIFastReader, Configuration: Debug_CpuOnly x64 ------
12>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
14>------ Build started: Project: CNTKBinaryReader, Configuration: Debug x64 ------
10>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
13>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
15>------ Build started: Project: HTKDeserializers (Reader Plugins\HTKDeserializers), Configuration: Debug x64 ------
16>------ Build started: Project: ImageReader, Configuration: Debug x64 ------
14>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
17>------ Build started: Project: CompositeDataReader, Configuration: Debug x64 ------
17>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
16>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
15>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
4>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
18>------ Build started: Project: CNTKLibraryCSBinding, Configuration: Debug x64 ------
19>------ Build started: Project: CPPExtensibilityExamplesLibrary, Configuration: Debug x64 ------
20>------ Build started: Project: EvalDll, Configuration: Debug x64 ------
21>------ Build started: Project: CNTK, Configuration: Debug x64 ------
18>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/PROFILE' specification
18>LINK : fatal error LNK1181: cannot open input file 'Cntk.Core-2.0rc1d.lib'
19>LINK : fatal error LNK1104: cannot open file 'Cntk.Core-2.0rc1d.lib'
20>LINK : fatal error LNK1104: cannot open file 'Cntk.Math-2.0rc1d.lib'
22>------ Build started: Project: EvalWrapper, Configuration: Debug x64 ------
23>------ Build started: Project: CPPEvalClientTest, Configuration: Debug x64 ------
24>------ Build started: Project: CPPEvalExtendedClientTest, Configuration: Debug x64 ------
21>LINK : fatal error LNK1104: cannot open file 'Cntk.Core-2.0rc1d.lib'
25>------ Build started: Project: CNTKLibraryCPPEvalExamplesTest, Configuration: Debug x64 ------
23>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/PROFILE' specification
23>LINK : fatal error LNK1181: cannot open input file 'Cntk.Eval-2.0rc1d.lib'
24>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/PROFILE' specification
24>LINK : fatal error LNK1181: cannot open input file 'Cntk.Eval-2.0rc1d.lib'
25>LINK : fatal error LNK1104: cannot open file 'Cntk.Core-2.0rc1d.lib'
26>------ Build started: Project: V2LibraryEndToEndTests, Configuration: Debug_CpuOnly x64 ------
27>------ Build started: Project: CPPExtensibilityExamples, Configuration: Debug x64 ------
22>LINK : fatal error LNK1104: cannot open file 'Cntk.Eval-2.0rc1d.lib'
28>------ Build started: Project: CSEvalClientTest, Configuration: Debug x64 ------
29>------ Build started: Project: PythonBindings, Configuration: Debug x64 ------
27>LINK : fatal error LNK1104: cannot open file 'Cntk.Core-2.0rc1d.lib'
26>LINK : fatal error LNK1104: cannot open file 'Cntk.Core-2.0rc1d.lib'
28>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Cntk.Eval.Wrapper-2.0rc1d". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
28>C:\repos\cntk\Examples\Evaluation\CSEvalClient\ModelEvaluator.cs(34,26,34,48): error CS0246: The type or namespace name 'IEvaluateModelManagedF' could not be found (are you missing a using directive or an assembly reference?)
28>C:\repos\cntk\Examples\Evaluation\CSEvalClient\Program.cs(147,45,147,58): error CS0246: The type or namespace name 'CNTKException' could not be found (are you missing a using directive or an assembly reference?)
29>  Currently no Python build for Debug configurations, exiting.
========== Build: 1 succeeded, 27 failed, 9 up-to-date, 1 skipped ==========

**Comment by zhouwangzw** [comment]
It seems you have also errors when building Cntk.Math and Cntk.Core. The Cntk.Eval.Wrapper has a dependency on them. Could you please check why you can not build Math and CNTKv2Library projects successfully? The message above does not have any information about it. Please first check whether all dev setup steps described [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-development-environment) are complete, and then probably close VS2015 and restart it, then run "Clean Solution", then "Rebuild Solution". 

If you still have errors, please incldue detailed error messages for investigation.

**Comment by amarkatti** [comment]
Thanks Zhou for the help. I replaced the local cntk solution with new solution from GitHub and now I'm able to build the solution. 
New code from GitHub resolves the issue.

**Comment by zhouwangzw** [comment]
Great to know that you problem has been resolved. I am closing the issue, and feel free to open a new one if you have questions or need help.

Thanks,
