### ISSUE TITLE
find_by_name() changes type of user function to cntk.ops.functions.Function.

### ISSUE THREAD

**Issue by ivan-alles** [microsoft/CNTK#2242]
If I add a user function to a model, and then search for it with find_by_name(), the returned object has a different type (cntk.ops.functions.Function). The concrete problem with it is that if I add some attribute to my user function, they disappear after the search. The same effect is when searching with depth_first_search().

Code example:

```
class MySigmoid(cntk.ops.functions.UserFunction):
    ### Copy-paste from CNTK tutorial

def test_user_function():
    input_var = cntk.ops.input_variable((10, 10), np.float32, name='input')
    model = MySigmoid(input_var, name='MyNode')
    print(type(model))
    # prints <class '__main__.MySigmoid'>
    node = model.find_by_name('MyNode')
    print(type(node))
    # prints <class 'cntk.ops.functions.Function'>
```
**Update:**
I forgot to enclose the user function into user_function() call:
`model = cntk.user_function(MySigmoid(input_var, name='MyNode'))`
Then the type is changed right away. But the question remains: **is it possible to access my custom attributes from outside?**

**Comment by n17s** [comment]
There is no mechanism for setting and getting arbitrary attributes (CNTK has a big list of attribute names but still a predefined set). I have opened a feature request for attributes in user functions.

**Comment by ivan-alles** [comment]
I'm closing this issue as CNTK development is stopped.
