### ISSUE TITLE
UWP GPU Support

### ISSUE THREAD

**Issue by manuelelucchi** [Microsoft/CNTK#2243]
I've noticed that you have released an UWP binding of CNTK and is in your plan release an ARM64 version. But what about GPU support in UWP? It's on plans? 

Thanks for everybody answers me

**Comment by zhouwangzw** [comment]
For GPU support, UWP compatible Cuda/CuDnn libraries are required. We are now considering how to support GPU in UWP, but no ETA yet. We will publish it in our itreation paln, as soon as we have a more detailed plan.

**Comment by manuelelucchi** [comment]
thank you for the answer!

**Comment by zhouwangzw** [comment]
I am closing the issue. Please open a new if you still have questions.
