### ISSUE TITLE
problem of configure with openblas on centos 7

### ISSUE THREAD

**Issue by xiachsh** [Microsoft/CNTK#2248]
With default openblas (from Centos 7 ISO), the dir of header for openblase was located under /usr/include/openblase, and configure script was checking the header openblas_config.h under /usr/include,

[root@SZV1000239187 CNTK-master]# cat /etc/*-release
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core) 
[root@SZV1000239187 CNTK-master]# rpm -qa | grep openblas
openblas-openmp64-0.2.19-4.el7.x86_64
openblas-openmp-0.2.19-4.el7.x86_64
openblas-threads-0.2.19-4.el7.x86_64
openblas-serial64-0.2.19-4.el7.x86_64
openblas-openmp64_-0.2.19-4.el7.x86_64
openblas-threads64_-0.2.19-4.el7.x86_64
openblas-devel-0.2.19-4.el7.x86_64
openblas-0.2.19-4.el7.x86_64
ropenblas-serial64_-0.2.19-4.el7.x86_64
openblas-threads64-0.2.19-4.el7.x86_64
[root@SZV1000239187 CNTK-master]# rpm -ql openblas-devel-0.2.19-4.el7.x86_64
/usr/include/openblas
/usr/include/openblas/cblas.h
**/usr/include/openblas**/f77blas.h
/usr/include/openblas/lapacke.h
/usr/include/openblas/lapacke_config.h
/usr/include/openblas/lapacke_mangling.h
/usr/include/openblas/lapacke_utils.h
/usr/include/openblas/openblas_config.h
/usr/lib64/libopenblas.so
/usr/lib64/libopenblas64.so
/usr/lib64/libopenblas64_.so
/usr/lib64/libopenblaso.so
/usr/lib64/libopenblaso64.so
/usr/lib64/libopenblaso64_.so
/usr/lib64/libopenblasp.so
/usr/lib64/libopenblasp64.so
/usr/lib64/libopenblasp64_.so
[root@SZV1000239187 CNTK-master]# ./configure  --with-openblas=/usr
Invalid openblas directory /usr
[root@SZV1000239187 CNTK-master]#

**Comment by tangyuq** [comment]
Thank you for your inquiry. Our Linux build configuration is targeting Ubuntu: https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-linux.

For other Linux build, you should be able to set the environment variables C_INCLUDE_PATH and CPLUS_INCLUDE_PATH or change the Makefile accordingly: https://github.com/Microsoft/CNTK/blob/master/Makefile.

**Comment by xiachsh** [comment]
@tangyuq  thank for your reply
