### ISSUE TITLE
Evaluating Fast RCNN using CTNK.CPU in C# - Expecting labels??

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#2249]
Hi.

I'm trying to evaluate the Fast RCNN model using the CNTK.CPU

I'm just using the Grocery set to test it as I can see that model works when using the python scripts. I input the image and ROIS as floats.

When I evaluate an image, I get the following error: 

Additional information: Values for 1 required arguments 'Input('roiLabels', [17 x 2000], [, #])', that the requested output(s) 'Output('ce', [1 x 2000], [, #]), Output('errs', [1 x 1], [, #]), Output('z', [17 x 2000], [, #])' depend on, have not been provided.

Why does the network expect labels when I evaluate? I have no way to provide labels for the ROI because clearly I don't know them yet.

Should I edit something in the fastrcnn.cntk network to make it work?

**Comment by pkranen** [comment]
For inference you don't need labels, that is correct. Is your model trained with Python or cntk.exe? The A2_RunWithBSModel.py saves the model ready for inference. You can see how it is used from Python [here](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/A2_RunWithPyModel.py#L181). The error message that you pasted shows that the network yu are trying to evaluate contains the cross entropy node ('ce'), which is used for training and requires labels. There is two ways you can solve this: either use A2_RunWithBSModel.py, which gives you the eval model directly, or load the model you have and pick the correct output node you need (see `find_by_name` examples in A2_RunWithBSModel.py).

**Comment by mortengryning** [comment]
I could not get the python to work properly so I used BS - so that's properly why.

I solved it by use giving it an array of 0's as labels and it worked correctly :-)

**Comment by wendy7707** [comment]
@mortengryning ,hello, I see you did many useful jobs about cntk,would you please tell me if I have a training model, could I test it in C# based on Fast-rcnn.model, not including python coding. And you said you could convert the model file to XML, could you share your coding? Thanks so much!

**Comment by mortengryning** [comment]
@wendy7707 

RIght now, before FasterRCNN fully supports C# Evaluation, you either have to call a custom python script to make ROI's (Region of Interrest), or make an algorithm to make them yourself and input them into model. When FasterRCNN fully supports C#, you can do it in .net only :-). The rest of the model can be fully evaluated in C#.

I'm not sure what you mean by convert into XML.

**Comment by wendy7707** [comment]
@mortengryning Thanks for your reply, you means  after I get the test images' roi txt files, I can use the model file to run it in .net environment?  Would you please sharing your evaluated coding? Thank you so much!

**Comment by wendy7707** [comment]
@mortengryning Thanks, I have more more questions, when I used the C# coding to evaluation the fast-rcnn, which doesn't actually give me any ROI labels besides 0 (ground), and I saw the "outputs = model.Evaluate(inputs, outDims.First().Key) " always has the same results of each roi. Would you please tell me how to solve it, thanks!

**Comment by koushk7** [comment]
@mortengryning Hi, I am a student and i want to implement object detection task in CNTK (in c#).  Please share the c# code for fast R-CNN, it would help me a lot.
