### ISSUE TITLE
CIFAR-10 01_Convolution.ndl confusion..

### ISSUE THREAD

**Issue by Jreyno40** [Microsoft/CNTK#225]
Hello! I apologize if this is the wrong place, but I am unable to figure this out. 
We define a convolutional layer as follows:  "ConvReLULayer(featScaled, cMap1, 75, kW1, kH1, hStride1, vStride1, conv1WScale, conv1BValue)" However, I cannot figure out the actual size of this layer. Is it the same as the input image? (So 32 x 32 x 3)? Further, if I look at the macro definition for ConvReLULayer, it sets zeroPadding = true when it calls the convolution function. How much padding does this actually add, if any? If I have a 32x32x3, what does this get padded out to when I call the convolution function with zeroPadding = true?

**Comment by Alexey-Kamenev** [comment]
Hello,
In that particular case, **output** dimensions of the first convolutional layer will be 32 x 32 x 32. Input dimensions are the same as the input image (32 x 32 x 3). You can look in the CNTK log where it outputs all node dimensions, for example:
```
Validating --> conv1_act.c = Convolution(conv1_act.W[32 x 75], featScaled[3 x 32 x 32 x * {W=32, H=32, C=3}]) -> [32 x 32 x 32 x *]
```
zeroPadding essentially guarantees that no part of the input will be lost. In general, when padding is enabled, the size of the output for each dimension can be determined using this simple formula:
```
O = (I - 1) / S + 1
```
Where `I` is input dimension, `S` - stride and `O` - output. CNTK currently uses a slightly different formula, padding each side with `KernelSize / 2` so sometimes it may slightly "overpad" the input which is usually not a problem.

**Comment by Jreyno40** [comment]
Thank you! Is the number 75 for the weights matrix important or is it arbitrary? Also, Is there any way to get the convolutional layer to have a larger number of inputs while padding the input image? I want to pad the image by 32 on all sides & thus have a conv layer supporting this. Is there any way I can accomplish this easily with the padding? Can I define InputImage() to be larger than the actual image being input & enable padding on the layer? Essentially I want to have the original image in the middle of the convolution surrounded by padding.

**Comment by Alexey-Kamenev** [comment]
75 is the size of one filter in that layer: 5 * 5 * 3. For convolution filters, dimensions of corresponding LearnableParameter are `number_of_output_feature_maps x size_of_one_filter` so in that particular case of first convo layer, the weight matrix will have 32 rows and 75 columns.
As for the padding: currently CNTK does not support such kind of padding.
