### ISSUE TITLE
SELU not working

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#2251]
Selu (https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=selu#cntk.ops.selu)
doesn't work.

Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk as C
>>> C.selu([[-1, -0.5, 0, 1, 2]]).eval()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cntk' has no attribute 'selu'

**Comment by bencherian** [comment]
Are you sure you're running CNTK 2.1? It was only added in the latest CNTK release. You can check the version attribute after import (`C.__version__`) to verify that you have version 2.1 installed.

**Comment by arijit17** [comment]
Thanks for the hint! It should work now!
