### ISSUE TITLE
Fixed kernel weights in convolutions.

### ISSUE THREAD

**Issue by ivan-alles** [microsoft/CNTK#2256]
I'm implementing a semantic segmentation convnet in python (similar to [that one ](https://github.com/shelhamer/fcn.berkeleyvision.org)). I do upscaling with ConvolutionTranspose2D layers. I initialize these layers with bilinear kernels (cntk.initializer.bilinear). I would like to fix the weights of these (and only these) kernels during training. How could I do this?

**Comment by ebarsoum** [comment]
You can use the low level API for convolution transpose, and use constant instead of parameter as weight.:

kernel = C.constant(value = filter)
C.convolution_transpose(kernel , x)

**Comment by ivan-alles** [comment]
Thank you for your suggestion. It works. 

While implemented this, I found out something that was not obvious to me. I need to upscale a tensor with the shape `num_channels x height x width`. The result will be a tensor of `num_channels x 2*height x 2*width.` 
What I actually need is just to resize each channel as a 2d image by a factor of 2. I expected to have one deconvolution kernel of shape `4x4` per channel for it. 

Instead, both `ConvolutionTranspose2D` and `convolution_transpose `need `num_channels x num_channels`  kernels of shape `4x4`. So, it is a 'matrix' of kernels with non-zero kernels on the diagonal. 

This is similar to a regular convolution for extracting features from images, but is redundant for my use case.

In my model the number of channels is 128, and I have multiple such layers. So, the number of parameters is increased by factor 128. Instead of having about 10000 of parameters I have more than a million. 

Is this possible to do a channel-wise upscaling in an efficient way? I would be also interesting to compare fixed kernels with learned kernels, because learning now make more sense to me (learning 10 K parameters instead of 1M).

**Comment by ebarsoumMS** [comment]
The kernel shape of convolution transpose is: C.parameter(input_channels_shape + output_channels_shape + filter_shape, init=init, name='W'). Is 128 number of input or output channels, or both?

**Comment by ivan-alles** [comment]
In my use case 128 is the number of both input and output channels, because I just want to resize each input channel as a 2d image by a factor of 2.
As I see from this example, the shape of the parameter tensor is (channels, channels, k_height, k_width):
```
    channels = 128
    x = cntk.input_variable((channels, 4, 4))
    up = cntk.layers.ConvolutionTranspose2D((4, 4), channels, strides=2, init=cntk.initializer.bilinear(4, 4), bias=False, activation=None)(x)
    print(up.parameters[0].name)
    print(up.parameters[0].shape) # Prints (128, 128, 4, 4)
```

**Comment by rajat95** [comment]
I need similar functionality but C.constant doesnt accept an Initializer as value. Any workarounds for the same?

**Comment by spandantiwari** [comment]
@rajat95 - could you please open a new issue for your question, as it is different from the opening question of this thread.

**Comment by ivan-alles** [comment]
I'm closing this issue as CNTK development is stopped.
