### ISSUE TITLE
Missing models in CNTK Examples: Image/Classification/ResNet

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#2257]
Hi,

The example in CNTK2.1 - CNTK Examples: Image/Classification/ResNet is missing links for download of models: 

- ResNet20 for CIFAR-10
- ResNet110 for CIFAR-10

Link of example:
https://github.com/Microsoft/CNTK/tree/release/2.1/Examples/Image/Classification/ResNet

Click link message :
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

PB

**Comment by pkranen** [comment]
We consolidated all pre-trained models in a new top level folder 'PretrainedModels'. During that change the names of these two particular has been adapted. The changes are in master, but not reflected in the previous 2.1 documentation. Please find the model download links here

https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md

You can now also use the download script from latest master:

https://github.com/Microsoft/CNTK/tree/master/PretrainedModels/README.md
https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/download_model.py
