### ISSUE TITLE
CNTK 2.0 to CNTK 2.1 - error in EvaluationSingleImage - CNTKLibraryCSEvalGPUExamples

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#2260]
Hi, 

ERROR:
Error: Sequence contains more than one element
CallStack:    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at CNTKLibraryCSEvalExamples.CNTKLibraryManagedExamples.EvaluationSingleImageAGATHA(DeviceDescriptor device, String imagefp, String modelfp) in C:\local\cntk\Examples\Evaluation\CNTKLibraryCSEvalCPUOnlyExamples\CNTKLibraryCSEvalExamples.cs:line 49
 Inner Exception: No Inner Exception

//---------------------------------//

With debugging I found the line
         Line 49 : Variable inputVar = modelFunc.Arguments.Single();
and with a little more debug I found this:

//---------------------------------//
Error: Values for 1 required arguments 'Input('labels', [2], [, #])', that the requested output(s) 'Output('ce', [], [])' depend on, have not been provided.

[CALL STACK]
    > CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::Function::  Forward
    - CNTK::Function::  Evaluate
    - CSharp_CNTK_Function__Evaluate__SWIG_0
    - 00007FFEC33C28AE (SymFromAddr() error: The specified module could not be found.)

CallStack:    at CNTK.Function._Evaluate(UnorderedMapVariableValuePtr arguments, UnorderedMapVariableValuePtr outputs, DeviceDescriptor computeDevice)
   at CNTK.Function.Evaluate(IDictionary`2 inputs, IDictionary`2 outputs, Boolean createPersistentOutputValues, DeviceDescriptor computeDevice)
   at CNTK.Function.Evaluate(IDictionary`2 inputs, IDictionary`2 outputs, DeviceDescriptor computeDevice)
   at CNTKLibraryCSEvalExamples.CNTKLibraryManagedExamples.EvaluationSingleImageAGATHA(DeviceDescriptor device, String imagefp, String modelfp) in C:\local\cntk\Examples\Evaluation\CNTKLibraryCSEvalCPUOnlyExamples\CNTKLibraryCSEvalExamples.cs:line 86
 Inner Exception: No Inner Exception

//---------------------------------//

I was using this method : EvaluateImageInputUsingImageApi, from CSEval CNTK2.0 but now I can't evaluate my old models. Also I trained a new model with an adapted version of ResNet152_ImageNet1K.cntk ( CNTK2.1 ) and I have the same error. 

Any suggestions?

Thks,
PB

**Comment by zhouwangzw** [comment]
Does your model has more than one Arguments? if yes, modeFunc.Arguments.Single() will fail, as Single() requires that Arguments has only one element. In this case, you can either use indexer, like Arguments[0]/[1] to get the input variable you want, or if the variable has a name, use the following 
`Variable inputVar = modelFunc.Arguments.Where(variable => string.Equals(variable.Name, myInputVaraibleName)).Single();`
to get the variable.

**Comment by pmfcdb** [comment]
It has 2 arguments:

features Input('features', [224 x 224 x 3], [, #])
labels Input('labels', [2], [, #])

Obtain by :
    foreach(var elem in modelFunc.Arguments)
           Console.WriteLine(elem.Name + " " + elem.AsString());
    Variable inputVar = modelFunc.Arguments.FirstOrDefault();

How can I map them in input data map?
    // Create input data map
    var inputVal = Value.CreateBatch(inputVar.Shape, resizedCHW, device);
    inputDataMap.Add(inputVar, inputVal);

**Comment by zhouwangzw** [comment]
First you need to get each input variable by walking through the list returned by modelFunc.Arguments, then prepare data for each input variable, and add it to the input data map. Something like:
```
foreach (var elem in modelFunc.Arguments)
{
       // prepare data for each elem.
        var inputVal = Value.CreateBatch(elem.Shape, DataForThisElem, device);
        inputDataMap.Add(elem, inputVal);
}
```

**Comment by pmfcdb** [comment]
So when I run your code I get : "Process is terminated due to StackOverflowException." in line : 

`modelFunc.Evaluate(inputDataMap, outputDataMap, device);`

Do you have an example for evaluating in C# models created by ResNet152_ImageNet1K.cntk -
 Brainscript?

The "DataForThisElem" for the second input "labels" is a list with the values of the labels, correct?
Like this : 
`List<float> labels = new List<float> {0.0f,1.0f }; // I just have 2 labels, 0 and  1`

**Comment by zhouwangzw** [comment]
Unfortunatelly we have not tried with ResNet152_ImageNet1K.cntk model. If it is trained by BrainScript, you can try to use the V1 EvalDll library and see whether you have the same problem The V1 EvalDll library is described [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Archive/EvalDLL-Evaluation-on-Windows#using-the-evaldll-c-library), [API reference ](https://docs.microsoft.com/en-us/cognitive-toolkit/Archive/evaldll-managed-api) and [examples](https://docs.microsoft.com/en-us/cognitive-toolkit/Archive/evaldll-managed-api#example).
Sorry for the inconvenience.

**Comment by pmfcdb** [comment]
I have this working in CNTK 2.0 with 

###
     using Microsoft.MSR.CNTK.Extensibility.Managed;
     ...
     outputs = model.EvaluateRgbImage(resized, outputNodeName);

but in 2.1 I can't use the same code.
Do you plan to solve this situation? Or there is a workaround?
Thks

**Comment by zhouwangzw** [comment]
Why this one is not working in 2.1? Any error messages?

**Comment by pmfcdb** [comment]
Ok, I got it to work in 2.1 using LegacyEvalDll>EvalClients.

I was trying to use it in CNTKLibraryEvalExamples, that's why I couldn't use Microsoft.MSR.CNTK.Extensibility.Managed;
Thks.

**Comment by wendy7707** [comment]
@pmfcdb Hello, I have the same problem above, would you please tell me how to solve it and share the input two items' coding ? Thanks!

**Comment by pmfcdb** [comment]
In 2.1 I didn't get the same results that I got in 2.0, I opened a issue with a print from the values: 
###
     outputs = model.Evaluate(inputs, outDims.First().Key);

Here is the link to the new issue:

https://github.com/Microsoft/CNTK/issues/2291

**Comment by wendy7707** [comment]
I think it is the problem of ROI, in cntk 2.1, it is not (x,y,w,h), but （Xmin，Ymin，Xmax，Ymax）
