### ISSUE TITLE
step function for Recurrence

### ISSUE THREAD

**Issue by apayani** [Microsoft/CNTK#2261]
I am trying to use a custom step function for the Recurrence function , but any function I feed I get some kind of error. For example this simple python function : 
def fn(h,x):
 return h

y = C.layers.Recurrence(step_function=fn1 , return_full_state=True)( x)

causes this error 

File "D:\PROGS\Anaconda3\lib\site-packages\cntk\layers\sequence.py", line 395, in Recurrence
    step_function = _sanitize_function(step_function)
  File "D:\PROGS\Anaconda3\lib\site-packages\cntk\layers\sequence.py", line 161, in _sanitize_function
    f = Function(f)
  File "D:\PROGS\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 109, in __new__
    return Function._to_Function(*args, **kwargs)
  File "D:\PROGS\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 229, in _to_Function
    assert out_arg_names == arg_names, (out_arg_names, arg_names)
AssertionError: (['h'], ['h', 'x'])

**Comment by tangyuq** [comment]
Thank you for your question. In recurrence, the user function will need to make use of all the input. For example, the following will work:
def fn(h,x):
     return h + x - x

**Comment by apayani** [comment]
I still have problem. It seems that understanding the internal network is very tricky.

I have created my own cell, which generated a similar signature signal .
for example 


 self.r = C.layers.RecurrenceFrom(step_function=cell1, return_full_state=True)( self.init_state_h,self.init_state_c,self.x_onehot)
        self.r1 = C.layers.RecurrenceFrom(step_function=cell2, return_full_state=True)( self.init_state_h,self.init_state_c,self.x_onehot)


here cell is a standard LSTM cell 
cell1 = LSTM( hidden_size, hidden_size)

and cell2 is my own cell created to generate exactly the same signature as an lstm,

this is the print out of the self.r1 and self.r signatures 

Composite(Tensor[400], Tensor[400], Sequence[Tensor[1]]) -> Tuple[Sequence[Tensor[400]], Sequence[Tensor[400]]]
Composite(Tensor[400], Tensor[400], Sequence[Tensor[1]]) -> Tuple[Sequence[Tensor[400]], Sequence[Tensor[400]]]

and this is the signature of self.r[0] and self.r[1] as well as self.r1[0] and self.r1[1]

Output('Plus1733_Output_0', [#, *], [400])
Output('Plus1655_Output_0', [#, *], [400])
Output('Plus1733_Output_0', [#, *], [400])
Output('Plus1655_Output_0', [#, *], [400])


as you can see all all the exact same signature, however , when I feed the output of LSTM cell ( self.r signal ) to my softmax function everything works but when I feed the output of my own cell I get this error on execution of trainer.train_minibatch function 

RuntimeError: Function 'Composite(Combine): Input('Input6', [#], [400]), Input('Input5', [#], [400]), Input('Input3', [#, *], [1]), Input('Input4', [#, *], [1]) -> Output('out_pr
oj', [#, *], [205]), Output('ElementTimes1977_Output_0', [#, *], [1]), Output('aggregateLoss', [], []), Output('Block1992_Output_0', [#, *], [1]), Output('aggregateEvalMetric', [
], [])': The output Variable 'Output('StableSigmoid1603_Output_0', [#, *], [400])' shape '[400]' does not match the SampleLayout shape '[]' of the corresponding ComputationNode i
n the network.

[CALL STACK]
    > CNTK::DeviceDescriptor::  UseDefaultDevice
    - CNTK::DeviceDescriptor::  UseDefaultDevice (x2)
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyFunction_FastCallDict
    - PyEval_EvalFrameDefault (x2)
    - PyEval_GetFuncDesc (x2)
    - PyEval_EvalFrameDefault


This is difficult to debug and very counter intuitive. 
In general, CNTK has a cleaner syntax and nicer approach compared Tensorflow but understanding the way its internal network works is very tricky. As soon as you try to build something that does not exist as standard, you would face a lot of difficulties. and the documentation is poor. really really poor !!!

**Comment by tangyuq** [comment]
Can you post your cell2 definition (or the signature with input and output and their shapes)?

**Comment by apayani** [comment]
These are the signatures for cell1 and cell2 :

LSTM(dh: Sequence[tensor], dc: Sequence[tensor], x: Sequence[tensor]) -> Tuple[Sequence[tensor], Sequence[tensor]]
my_cell(h: Sequence[tensor], c: Sequence[tensor], x: Sequence[tensor]) -> Tuple[Sequence[tensor], Sequence[tensor]]

**Comment by apayani** [comment]
this is the sample function 
def gen_my_cell (hidden_sizes,name=''):
    ac=[]
    gf=[]
    go=[]
    for i in range(2):
        ac.append ( C.layers.Dense( hidden_size , activation = C.tanh, init=C.glorot_uniform(), bias=True,name='ac_{}'.format(i)) )
        gf.append ( C.layers.Dense( hidden_size , activation = C.sigmoid, init=C.glorot_uniform(), bias=True,name='gf_{}'.format(i)) )
        go.append ( C.layers.Dense( hidden_size , activation = C.sigmoid, init=C.glorot_uniform(), bias=True,name='go_{}'.format(i)) )

    def fn(h,c, x):
        state_out = [h,c] 
        for i in range(2):
            H = C.splice ( x ,  *state_out[:i+1]  , axis=0)
            _ac = ac[i]( H ) 
            _gf = gf[i]( H ) 
            _go = go[i]( H ) 
        
            state_out[i] =    state_out[i] * _gf +  _ac*_go
        return tuple(state_out)
    return C.BlockFunction( 'my_cell', name)(fn)

**Comment by tangyuq** [comment]
Will also need more information to debug further. Can you please provide the code and a subset of data so that we can reproduce the issue? Thanks.

**Comment by cha-zhang** [comment]
Close this issue due to lack of response.
