### ISSUE TITLE
stack / unstack

### ISSUE THREAD

**Issue by apayani** [Microsoft/CNTK#2262]
Is there anyway to do operations like stacking and unstacking ( like those in numpy or Tensorflow ) in CNTK ?
while you can access to a slice in a tensor , there is no obvious solution to modify that slice. Basically, I am looking for operation that can split a tensor in one axis into a list of tensors . 
While CNTK syntax and performance is OK , very simple tasks seem impossible . 
Another example is when I try to create a custom step function that behaves like LSTM but can accept a variable number of states , a Grid LSTM for example. So far I have not found any way to define such a simple recurrence network in CNTK while the same functionality can be implemented very simply in any other DeepLearning tool like Tensorflow, Theano, etc

**Comment by cha-zhang** [comment]
The function you are looking for is reshape: 
https://cntk.ai/pythondocs/cntk.ops.html?highlight=reshape#cntk.ops.reshape

**Comment by apayani** [comment]
I do not understand how reshape can split a tensor into a list of tensors . Reshape can only reshape the internal representation of a tenor.  Please look up the unstack or split function in tensorflow to see what I am looking for

**Comment by tangyuq** [comment]
#For stack:
x = C.input_variable((2,1))
y = C.input_variable((2,1))
z = C.splice(x, y, axis = 0)
Please check https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=splice#cntk.ops.splice for details.

#For unstack:
x = C.input_variable((4, 2, 1))
z = [C.slice(x, axis = 0, begin_index = i, end_index = i +1 ) for i in range(4)]

Please check  https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=slice#cntk.ops.slice  for details.

**Comment by tangyuq** [comment]
It is straightforward to implement Grid-LSTM and its variance in CNTK: 
x = C.sequence.input_variable((4,2))
mylstm0 = C.layers.LSTM(shape=20, cell_shape=20)
mylstm1 = C.layers.LSTM(shape=20, cell_shape=20)
def grid_lstm(H, M, x):
    H = C.reshape(H, 20)
    hh0, mm0 = mylstm0(H, C.slice(M, axis=0, begin_index = 0, end_index=1 ), x)
    hh1, mm1 =  mylstm1(H, C.slice(M, axis=0, begin_index = 1, end_index=2), x)
    #this is just an example, the shape/dimension of the hidden state is incorrect,
    #you will need to implement the LSTM function specificially to fit grid LSTM need
    return C.splice(hh0, hh1), C.splice(mm0, mm1)

s0 = C.Constant(np.zeros(20)) #just an example to construct the shape of the initial state, will you need to implement your own initialization
mygrid = C.layers.Recurrence(step_function=grid_lstm, initial_state=s0)(x)

**Comment by tangyuq** [comment]
Hope this can help.

**Comment by n17s** [comment]
Writing a custom step function for the Recurrence is documented in the docstring of cntk.layers.Recurrence

https://github.com/Microsoft/CNTK/blob/27611d9ae34dab453c5b3da9182a7d4ea7673f60/bindings/python/cntk/layers/sequence.py#L306-L327
