### ISSUE TITLE
Tutorials with Video

### ISSUE THREAD

**Issue by frankibem** [Microsoft/CNTK#2263]
Are there any CNTK tutorials that deal with video inputs or any plans to add some?

**Comment by cha-zhang** [comment]
Have you checked the simple example here: https://github.com/Microsoft/CNTK/tree/master/Examples/Video/GettingStarted

**Comment by frankibem** [comment]
@cha-zhang Thanks. I'll look harder next time.

**Comment by cha-zhang** [comment]
We definitely need to add more video examples. If there is any particular model you are interested in, let us know.

**Comment by frankibem** [comment]
@cha-zhang If feasible, I'm interested in a CNN-LSTM model. The UCF11 example you pointed me to was a good introduction to processing videos with LSTMs but I would like to combine that with a CNN.

**Comment by cha-zhang** [comment]
If you are looking for models like CNN-LSTM, you can find some more video examples in our CVPR tutorial: 
https://www.cntk.ai/Tutorials/CVPR2017/CVPR_2017_Tutorial_final.pdf
