### ISSUE TITLE
brainscript image sequence intent classification with lstm

### ISSUE THREAD

**Issue by xforceco** [Microsoft/CNTK#2265]
I modify the script from tutorial
[https://docs.microsoft.com/en-us/cognitive-toolkit/Hands-On-Labs-Language-Understanding](url) 
with 3-channel image sequence input

However, after many times of checking and trying, I still got this error:
`EXCEPTION occurred: Node 'z' (Plus operation): ColumnRangeWithMBLayoutFor: FrameRange's dynamic axis is inconsistent with matrix. They are compatible though--are you missing a ReconcileDynamicAxis operation?`

due to the use of `Splice (BS.Sequences.Last(F(x)):BS.Sequences.First(G(x)))` in the self-crafted BLSTM layer

However, `ReconcileDynamicAxis` is deprecated. Any idea for this?

**Comment by cha-zhang** [comment]
Can you post a repro?

**Comment by xforceco** [comment]
[https://github.com/xforceco/cntk_issue/blob/master/test.cntk](url)

Line 18 causes the problem

**Comment by xforceco** [comment]
I am sorry about all inconvenience caused.
This is due to mistakes in my input file: 
intent label should only appear once in every sequence

Issue close
