### ISSUE TITLE
Issue running A2_RunWithPyModel.py 

### ISSUE THREAD

**Issue by leangdamang** [Microsoft/CNTK#2266]
Hi,

I keep getting an issue when running the image detection example with the grocery dataset. 

After postprocessing I get the issue: 

> EXCEPTION occurred. while evaluating: BrainScriptNetworkBuilder(8): unknown identifier 'pool3'
> Time running cntk [s]: 2.918485
> Traceback (most recent call last):
>   File "A2_RunWithBSModel.py", line 61, in <module>
>     run_fastrcnn_with_config_file()
>   File "A2_RunWithBSModel.py", line 55, in run_fastrcnn_with_config_file
>     assert pid.returncode == 0, "ERROR: cntk ended with exit code {}".format(pid.returncode)
> AssertionError: ERROR: cntk ended with exit code 1

Running CNTK on an AWS instance. 

[Output file here](https://github.com/leangdamang/recipe-recommender/blob/master/error01.txt)

**Comment by pkranen** [comment]
It looks like the node names in your base model do not match the configuration. You can inspect the node names by plotting the model once you loaded it using `plot(model, 'filename.png')`. Which base model are you using for transfer learning? Please try this one [https://www.cntk.ai/Models/AlexNet/AlexNet.model](https://www.cntk.ai/Models/AlexNet/AlexNet.model).

**Comment by ebarsoumMS** [comment]
Please reactivate if the issue still there.
