### ISSUE TITLE
error code MSB8013 : This project doesn't contain the Configuration and Platform combination of Release|x64.

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#2267]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8013	This project doesn't contain the Configuration and Platform combination of Release|x64.	Multiverso	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets	349	

first, window reset
second, install vs2015 with update 3
I followed the Manual (https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows) and Enabling 1bit SGD.

But the error was occurred when build

//
also I tried that
first, window reset
second, install vs2015 with update 3
and run install script

but I have same error.

how do I fix it?

**Comment by tangyuq** [comment]
Have you checkout the Multiverso submodule? 

git clone https://github.com/Microsoft/cntk
cd cntk
git submodule update --init Source/Multiverso

**Comment by Eomtaesan** [comment]
thank you for the answer :)
yes I have the module and I tried the setting ASGD false and true both.

I will try one more time to window reset
