### ISSUE TITLE
having an error in Model Evaluation after NuGet Package Setup

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#2268]
I just try Load Function in main()

DeviceDescriptor device = DeviceDescriptor::GPUDevice ( 0 );
FunctionPtr FS = Function::Load ( L"C:\\repos\\cntk\\Curling\\FS\\Models\\Train.dnn" , device );

Unhandled exception at 0x00007FFBF0F39E08 in Test.exe: Microsoft C++ exception: Microsoft::MSR::CNTK::ExceptionWithCallStack<std::invalid_argument> at memory location 0x000000E0484BF250.

the Train.dnn file is made by lr_bs.cntk in HelloWorld-LogisticRegression of Tutorial

anyone know this error?
I have release version and source code version but both have same error

**Comment by zhouwangzw** [comment]
@Eomtaesan From your description it seems that your model was written in Brainscript. Which Nuget package were you using for evalaution? For C++, the same build flavor should be used in your application and the CNTK library: Release vs Release and Debug vs Debug. Were you able to run the examples shipped with CNTK release pacakges, as described [here](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Eval-Examples)?

**Comment by zhouwangzw** [comment]
I am closing the issue due to lack of response. Please open a new one if you still have questions.
