### ISSUE TITLE
is there some plan for .Net wrapper ?

### ISSUE THREAD

**Issue by goodtogood** [Microsoft/CNTK#227]
Hello! CNTK is great ! but I'm not familiar with cpp,
so is there some plan for .Net wrapper ?

**Comment by frankseide** [comment]
There is already a C# wrapper for evaluation.

For training itself, eventually yes. We are working on turning CNTK into a library, and that library will be accessible from both Python and .Net.

**Comment by syedmohsinbukhari** [comment]
Hi frankseide,
I am anxiously waiting for the library. Is there any alpha or beta version?

Thanks for the wrapper.

**Comment by wolfma61** [comment]
the latest 2.0Beta1 has the CNTK library version for Python and C++

support for the new APIs from C#  (for model evaluation) is in the works and coming soon
 the complete new library API accessible from .net will take a little bit more time, but coming ...

**Comment by zhouwangzw** [comment]
We have just released the beta version of CNTK Library .NET/C# Eval API (for model evaluation). https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta8.0.
