### ISSUE TITLE
Bug In PARAMETERS.py in  Examples/Image/Detection/FastRCNN/PARAMETERS.py

### ISSUE THREAD

**Issue by motamed** [Microsoft/CNTK#2276]
https://github.com/Microsoft/CNTK/blob/5e8bacb76cb4fc99a24a8ec0e53ebc34c94509db/Examples/Image/Detection/FastRCNN/PARAMETERS.py#L131

 wrong:    elif dataset.Name == "CustomDataset":

Correct :     elif datasetName == "CustomDataset":

no  Dot needed in dataset.Name

**Comment by cha-zhang** [comment]
This is a minor bug. Could you please send in a small PR? That way your contribution will be recorded.

**Comment by motamed** [comment]
Done :) @cha-zhang

**Comment by cha-zhang** [comment]
Merged. Thanks!
