### ISSUE TITLE
Examples for using own dataset in Image Classification

### ISSUE THREAD

**Issue by mortengryning** [Microsoft/CNTK#2277]
Hi.

Does documentation exist concerning how to use the networks in the Image/Classification folder on my own data? How do I prepare the JPG images (are there any python scripts that prepare the data for me?)

**Comment by pkranen** [comment]
Please follow this tutorial: [https://docs.microsoft.com/en-us/cognitive-toolkit/build-your-own-image-classifier-using-transfer-learning](https://docs.microsoft.com/en-us/cognitive-toolkit/build-your-own-image-classifier-using-transfer-learning).

**Comment by mortengryning** [comment]
Hi Pkranen.

Thank you for your answer. However, as far as I can see, Using Transfer Learning states that:

"Another aspect to keep in mind is that a particular base model might work very well for some transfer learning tasks and not as good for others. For example, the above ResNet_18 model was pretrained on the ImageNet corpus, which contains many images of animals, people, cars and many other every day objects. Using this base model in transfer..."

I would very much like to start from scratch. Are there really no documentation on how to use all of the models in the classification with my own data?
