### ISSUE TITLE
unknown identifier 'IsLast'

### ISSUE THREAD

**Issue by xforceco** [Microsoft/CNTK#2279]
BS.Sequences.IsLast() does not work

Tutorial: https://docs.microsoft.com/en-us/cognitive-toolkit/gather-and-scatter#isfirst-islast

**Comment by spandantiwari** [comment]
Could you provide more context and a repro?

**Comment by xforceco** [comment]
When I use BS.Sequences.IsLast()
I got "unknown identifier 'isLast' '

I am using CNTK-2.1, is this expected?

**Comment by spandantiwari** [comment]
As far as I know, nothing related to IsLast has changed in 2.1, so this is unexpected. Can you share the code and the error log?

**Comment by n17s** [comment]
All brainscript definitions are in the [cntk.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) file. From there we see that there's a `BS.Sequences.isLast` and the capitalization is the page you pointed at is a formatting error. Try with `BS.Sequences.isLast` and it should work.
