### ISSUE TITLE
Problem with Cntk.Core.Managed-2.1 from github

### ISSUE THREAD

**Issue by Yandychang1** [Microsoft/CNTK#2282]
I have installed both  CNTK  in python and the console application to use with brainscript. In python, I  trained a simple FeedForward neural network to classify vectors, and saved it. Now I am trying to load the network from C# with the example found in the tutorials/ tests. Used the Cntk.Core.Managed-2.1 package from GitHub, It compiles with no syntax errors, but when I run it, I get the following error:

Could not load file or assembly 'Cntk.Core.Managed-2.1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=21fff2ec8197defe' or one of its dependencies. An attempt was made to load a program with an incorrect format.
Are there any other assemblies that I need to reference in order to make it work?
Any idea why this may be happening?

**Comment by mortengryning** [comment]
Try to change the project type to use X64

**Comment by Yandychang1** [comment]
Thats the first thing I did, I set it up for x64, still get the same error...

**Comment by n17s** [comment]
Glad this was resolved. Closing. Feel free to reopen.

**Comment by JagathPrasad** [comment]
When I run my application it shows below error.

Could not load file or assembly 'Cntk.Core.Managed-2.7' or one of its dependencies. An attempt was made to load a program with an incorrect format.

I am using VS2017 with .Net Framework 4.7.1,
please help me.
