### ISSUE TITLE
How do I set up my initial weight and bias when building a CNN model

### ISSUE THREAD

**Issue by baozi-lala** [Microsoft/CNTK#2284]
I want to pass the weight and bias into the model directly  when I create CNN model,Is this possible?And how to do it.

**Comment by ebarsoumMS** [comment]
If you use Layer API (CNTK.layers.Convolution), then you can pass numpy array in the init argument, for low level API (CNTK.convolution),, you create the parameter manually, so you can init it with whatever you want.

Note: those questions are best asked in stackoverflow with CNTK label on them.

**Comment by baozi-lala** [comment]
but what shape of weight and bias should I pass into the convolution layer.
if I pass the weight read from a model
```
 for i in reversed(z.parameters):
        if i.name == 'W':
            weight_array.append(i.value)
        if i.name == 'b':
            bias_array.append(i.value)
```
that shape is
```
(u'b', (8, 1, 1))
(u'W', (8, 1, 3, 3))
(u'b', (16, 1, 1))
(u'W', (16, 8, 3, 3))
(u'b', (10,))
(u'W', (16, 2, 2, 10))
```
but i got the **error**
`raise ValueError("a constant initializer was passed that is of wrong shape")`
besides,what the meaning of the parameter `reduction_rank` in CNTK.layers.Convolution.why must I set it to 0 when I use weight and bias?

**Comment by baozi-lala** [comment]
How can I use low level API?Is there any examples?because I cannot understand the code well.

**Comment by baozi-lala** [comment]
@ebarsoumMS @n17s

**Comment by baozi-lala** [comment]
if I modify the weight shape,the error above can be solved.but when I reshape the weight shape to `(8,3,3)` and bias to `(8,1,1)` I got a new error
`ValueError: Convolution operation requires that kernel dim 8 <= input dim 1.`

**Comment by ebarsoumMS** [comment]
The below should work:

def conv2d(x, num_filters, filter_shape=(3,3), strides=(1,1), pad=True, nonlinearity=None, init=global_init):
    output_channels_shape = (num_filters,)
    x_channels_shape      = (x.shape[0],)
    paddings              = (False,) + (pad,)*len(filter_shape)

    W = C.parameter(output_channels_shape + x_channels_shape + filter_shape, init=init, name='W')
    b = C.parameter(output_channels_shape, name='b'); set_parameter(scope, 'b', b)

    y = C.convolution(W, x, strides=x_channels_shape + strides, auto_padding=paddings)

    if nonlinearity is not None:
        y = nonlinearity(y)
    return y

**Comment by baozi-lala** [comment]
I wonder what is the meaning of parameters such as reduction_rank, num_emulated_axes in the convolution layer. When I comment out these difficult parameters，such as
`        if num_inserted_axes != 1:
            # x: (in_depth, spatial_shape)
            x = reshape(x, (1,) * num_inserted_axes,    # e.g. (2000, 480, 640) -> (2000, 1, 480, 640)
                        begin_axis=-filter_rank_without_seq if filter_rank_without_seq != 0 else C.Axis.new_leading_axis(),
                        end_axis  =-filter_rank_without_seq if filter_rank_without_seq != 0 else None)`
,there is no error.So why add these confusing codes? and why not use` W = Parameter(init.shape, init=init, name='W')` directly.

**Comment by ebarsoumMS** [comment]
The code that I show is much simpler, so use that. reduce_rank is because cuDNN convolution always expect channel, if if you set reduce_rank to 0, mean no channel, we will add dummy one to satisfy cuDNN.

The complexity of the code in order to support convolution on sequence, 1d data and others.

**Comment by baozi-lala** [comment]
oh,I see. thank you very much.

**Comment by n17s** [comment]
Closing. Feel free to reopen.

**Comment by rajat95** [comment]
For those who still stumble on this can also take a look at this [tutorial] (cell 3) to set weights and bias (https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_205_Artistic_Style_Transfer.ipynb)

**Comment by baozi-lala** [comment]
It's been a long time, and I've rebuilt the network structure using the low level API (CNTK.convolution). But I still want to know how to set up my initial weight and bias using the  Layer API (CNTK.layers.Convolution)? the error I mentioned above still exists.

**Comment by delzac** [comment]
@baozi-lala You can check out [cntkx](https://github.com/delzac/cntkx), its a library i maintain and i have enabled initialising weights in Convolution layer. Its written in pure python so it should be totally compatible.
