### ISSUE TITLE
Plugin not found: 'Cntk.Composite-2.1d.dll

### ISSUE THREAD

**Issue by FlashTek** [Microsoft/CNTK#2287]
I tried to run the C++ test [MNISTClassifier.cpp](https://github.com/Microsoft/CNTK/blob/v2.1/Tests/EndToEndTests/CNTKv2Library/EndToEndTests/MNISTClassifier.cpp) using VS2017 with the CPUOnly NuGet package. Doing this, the code crashed in line 119 with this error message:

> Unhandled exception at 0x00007FFA88C39E08 in CNTKTests.exe: Microsoft C++ exception: Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error> at memory location 0x000000FC678FC7B0. occurred

and in the console I get this output

> About to throw exception 'Plugin not found: 'Cntk.Composite-2.1d.dll''
>About to throw exception 'Symbol 'CreateCompositeDataReader' not found in plugin 'Cntk.Composite-2.1d.dll''

Apparently I cannot use the `TextFormatMinibatchSource` with the CPUOnly NuGet package, but why is this so? Am I doing something wrong? Or does a workaround exist for this problem?
I saw that CNTK is only support VS2015 update 3 because of the cuDNN support - but I thought this can be solved by using the CPUOnly package (at least doing so the code can be compiled without a problem and all other functions can be called). Was this assumption wrong?

**Comment by zhouwangzw** [comment]
The current Nuget Package does not contain reader dlls, like Cntk.Composite-21d.dll. For running MNISTClassifier.cpp example, you can build CNTK.sln from source, and then you should be able to run the test. Please refer to [the page ](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-development-environment)for dev setup.

The next release of Nuget packages will probably include those dlls.
