### ISSUE TITLE
Classification :: ResNet 

### ISSUE THREAD

**Issue by edwardcho** [Microsoft/CNTK#2289]
I am testing ResNet110 network model using CNTK-sample python code.
For many times testing, I could not start ResNet110-Training.

My condition is as follows,
-. The reference code :
 https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10.py
-. Network Model : ResNet110
-. Image Information
    Original Image Size : 256 * 256 * 3-channels
    Resize : 224 * 224 * 3-channels
    num_classes : 10
-. minibatch_size : 16
-. GPU : nvidia Tesla K80 12GB
-. OS : Windows Server 2012 R2 64bit

[Result]

python> .\TrainResNet_CIFAR10.py --datadir C:\IRIS\CIFAR-10 -n  resnet110 
Selected GPU[1] Tesla K80 as the process wide default device. 
------------------------------------------------------------------- 
Build info:
                  Built time: Jul 31 2017 03:29:10
                 Last modified date: Wed Jul 26 04:19:54 2017
                 Build type: Release
                 Build target: GPU
                 With 1bit-SGD: no
                 With ASGD: yes
                 Math lib: mkl
                 CUDA_PATH: C:\Program Files\NVIDIA GPU Computing  Toolkit\CUDA\v8.0
                 CUB_PATH: c:\local\cub-1.4.1
                 CUDNN_PATH:  C:\local\cudnn-8.0-windows10-x64-v6.0.21\cuda
                 Build Branch: HEAD
                 Build SHA1: 5643a5619097b125f49e629f5bdbbc5a6ceedcf0 
                Built by svcphil on DPHAIM-25
                 Build Path:  C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTKv2LibraryDll\
                 MPI distribution: Microsoft MPI
                 MPI version: 7.0.12437.6 
------------------------------------------------------------------- 
Training 3266714 parameters in 335 parameter tensors. 

 CUDA failure 2: out of memory ; GPU=1 ; hostname=OPTICADEV1 ;  expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(Allocate dElemType) * AsMultipleOf(numElements, 2)) 
Traceback (most recent call last): 
  File ".\TrainResNet_CIFAR10.py", line 185, in <module>
     args['logdir'], args['tensorboard_logdir'], gen_heartbeat =  args['genheartbeat'])
   File ".\TrainResNet_CIFAR10.py", line 117, in train_and_evaluate
     trainer.train_minibatch(data)                                   #  update model with it
   File "C:\Anaconda2\lib\site-packages\cntk\train\trainer.py", line 170, in  train_minibatch
     arguments, device)
   File "C:\Anaconda2\lib\site-packages\cntk\cntk_py.py", line 2766, in  train_minibatch_overload_for_minibatchdata
     return  _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
 RuntimeError: CUDA failure 2: out of memory ; GPU=1 ; hostname=OPTICADEV1 ;  expr=cudaMalloc((void**) &deviceBufferPtr, s izeof(AllocatedElemType) * AsMultipleOf(numElements, 2))

  [CALL STACK]
     > Microsoft::MSR::CNTK::CudaTimer::  Stop
     - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
     - Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize
     - Microsoft::MSR::CNTK::Matrix<float>::  Resize
     - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2  (x3)
     - CNTK::DeviceDescriptor::  UseDefaultDevice
     - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
     - CNTK::DeviceDescriptor::  UseDefaultDevice
     - CNTK::Function::  Forward
     - CNTK::  CreateTrainer
     - CNTK::Trainer::  TotalNumberOfSamplesSeen
     - CNTK::Trainer::  TrainMinibatch (x2) 

P.S. When I change minibatch-size(value : 8) on Networks, this error was occurred.

[Questions]
I have some questions.
1. The supportable maximum image size of ResNet110-model ?
2. How many GPU memory size for training??

**Comment by spandantiwari** [comment]
It would seem that your GPU is running out of memory. Try reducing the minibatch further as a test to see if it works. Even not, then it may be some other issue.

**Comment by cha-zhang** [comment]
If you are training on ImageNet, for ResNet110 you should use bottleneck. We are sharing the ImageNet ResNet implementation very soon. 

The bottleneck implementation looks like this: 

```
def resnet_bottleneck(input, out_num_filters, inter_out_num_filters):
    c1 = conv_bn_relu(input, (1,1), inter_out_num_filters)
    c2 = conv_bn_relu(c1, (3,3), inter_out_num_filters)
    c3 = conv_bn(c2, (1,1), out_num_filters)
    p  = c3 + input
    return relu(p)

def resnet_bottleneck_inc(input, out_num_filters, inter_out_num_filters, stride1x1, stride3x3):
    c1 = conv_bn_relu(input, (1,1), inter_out_num_filters, strides=stride1x1)
    c2 = conv_bn_relu(c1, (3,3), inter_out_num_filters, strides=stride3x3)
    c3 = conv_bn(c2, (1,1), out_num_filters) 

    stride = np.multiply(stride1x1, stride3x3)
    s  = conv_bn(input, (1,1), out_num_filters, stride)
    p  = c3 + s
    return relu(p)

def resnet_bottleneck_stack(input, num_stack_layers, out_num_filters, inter_out_num_filters): 
    assert (num_stack_layers >= 0)
    l = input 
    for _ in range(num_stack_layers): 
        l = resnet_bottleneck(l, out_num_filters, inter_out_num_filters)
    return l
```

**Comment by cha-zhang** [comment]
```
def create_imagenet_model(input, num_stack_layers, num_classes, stride1x1, stride3x3):
    c_map = [64, 128, 256, 512, 1024, 2048]

    # conv1 and max pooling
    conv1 = conv_bn_relu(input, (7,7), c_map[0], strides=(2,2))
    pool1 = MaxPooling((3,3), strides=(2,2), pad=True)(conv1)

    # conv2_x
    r2_1 = resnet_bottleneck_inc(pool1, c_map[2], c_map[0], (1,1), (1,1))
    r2_2 = resnet_bottleneck_stack(r2_1, num_stack_layers[0], c_map[2], c_map[0])

    # conv3_x
    r3_1 = resnet_bottleneck_inc(r2_2, c_map[3], c_map[1], stride1x1, stride3x3)
    r3_2 = resnet_bottleneck_stack(r3_1, num_stack_layers[1], c_map[3], c_map[1])

    # conv4_x
    r4_1 = resnet_bottleneck_inc(r3_2, c_map[4], c_map[2], stride1x1, stride3x3)
    r4_2 = resnet_bottleneck_stack(r4_1, num_stack_layers[2], c_map[4], c_map[2])

    # conv5_x
    r5_1 = resnet_bottleneck_inc(r4_2, c_map[5], c_map[3], stride1x1, stride3x3)
    r5_2 = resnet_bottleneck_stack(r5_1, num_stack_layers[3], c_map[5], c_map[3])

    # Global average pooling and output
    pool = GlobalAveragePooling()(r5_2)
    z = Dense(num_classes, init=uniform(0.05))(pool)
    return z
```

**Comment by cha-zhang** [comment]
```
def create_resnet_network(network_name):
    # Input variables denoting the features and label data
    input_var = C.input_variable((num_channels, image_height, image_width))
    label_var = C.input_variable((num_classes))

    stride1x1 = (1,1)
    stride3x3 = (2,2)
    
    # create model, and configure learning parameters 
    if network_name == 'resnet18':
        z = create_imagenet_model_s(input_var, [2,1,1,2], num_classes)
    elif network_name == 'resnet34':
        z = create_imagenet_model_s(input_var, [3,3,5,2], num_classes)
    elif network_name == 'resnet50':
        z = create_imagenet_model(input_var, [2,3,5,2], num_classes, stride1x1, stride3x3)
    elif network_name == 'resnet101':
        z = create_imagenet_model(input_var, [2,3,22,2], num_classes, stride1x1, stride3x3)
    elif network_name == 'resnet152':
        z = create_imagenet_model(input_var, [2,7,35,2], num_classes, stride1x1, stride3x3)
    else: 
        return RuntimeError("Unknown model name!")

    # loss and metric
    ce = cross_entropy_with_softmax(z, label_var)
    pe = classification_error(z, label_var)

    return {
        'name' : network_name,
        'feature': input_var,
        'label': label_var,
        'ce' : ce,
        'pe' : pe,
        'output': z
    }
```

**Comment by n17s** [comment]
Closing. Feel free to reopen.
