### ISSUE TITLE
Cudnn on CPU machine

### ISSUE THREAD

**Issue by yzhang87** [Microsoft/CNTK#229]
Hi,

What happen if I trained a conv net on a GPU machine using cuDNN and then decode it on a CPU machine?

Right now it just crashed on the conv node.

thanks,
Yu

**Comment by dongyu888** [comment]
It will fail (or get incorrect results) since the cuDNN layout is not implemented in CPU yet.

**Comment by frankseide** [comment]
It should give an error message. Does it? We fixed that 1 or 2 weeks ago, before it was only an easy-to-miss warning.

**Comment by yzhang87** [comment]
I didn't get any error message. Probably KaldiWriter didn't catch the exception correctly.
