### ISSUE TITLE
FastRCNN with CSEvalClient in CNTK 2.1

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#2291]
Hi, I was trying to port FAST RCNN with CSEvalClient from this branch from pkranen that I have working in CNTK 2.0:

https://github.com/Microsoft/CNTK/blob/pkranen/csevalFastrcnn/Examples/Evaluation/CSEvalClient/Program.cs

Method : EvaluateObjectDetectionModel

And in CNTK 2.1 I don't get any results. Also as showed in attach images, I get diferrent values in this line of code:
###
     outputs = model.Evaluate(inputs, outDims.First().Key);

CNTK 2.1
![fastrcnn_outputs_cntk21](https://user-images.githubusercontent.com/22818355/29924141-d42077e6-8e53-11e7-80ff-06847a8dd0a7.png)

CNTK 2.0
![fastrcnn_outputs_cntk2](https://user-images.githubusercontent.com/22818355/29924154-e20c2e4a-8e53-11e7-9aca-4e038215e3a8.png)

Can you test please to confirm that it doesn't work in CNTK 2.1?
Thks

**Comment by wendy7707** [comment]
@pmfcdb Yes, I also got the different value and different results. Have you solved this problem? Thanks!

**Comment by cha-zhang** [comment]
Hope this has been resolved based on #2260. Closing this for now. Feel free to reopen if needed.

**Comment by pmfcdb** [comment]
I could not resolve this with suggestion  on #2260:

"I think it is the problem of ROI, in cntk 2.1, it is not (x,y,w,h), but （Xmin，Ymin，Xmax，Ymax）"

I converted the input roiCoordinates to that format and I didn't get any result, also the output  is repeating the values.(in both input foramts x,yw,h and Xmin, Ymin, Xmax, Ymax)

outputs = model.Evaluate(inputs, outDims.First().Key);
outputs =3.333971 0.1767028 0.3578066 0.3251713 -0.5732964 -0.5852491 -0.6720454 0.1473688 -0.3091967 -0.3862248 -0.6178113 0.01292216 0.8635525 0.1989018 -0.7314355 -0.4869511 -0.4000312
3.333971 0.1767028 0.3578066 0.3251713 -0.5732964 -0.5852491 -0.6720454 0.1473688 -0.3091967
-0.3862248 -0.6178113 0.01292216 0.8635525 0.1989018 -0.7314355 -0.4869511 -0.4000312 ....

**Comment by pmfcdb** [comment]
Please tell me something regarding this subject? Should I open a new issue?
