### ISSUE TITLE
YOLO model support?

### ISSUE THREAD

**Issue by wind-rider** [Microsoft/CNTK#2293]
I came across https://github.com/pjreddie/darknet/wiki/YOLO:-Real-Time-Object-Detection and it looks quite good; is there any chance that CNTK will get support for this approach?

**Comment by ebarsoumMS** [comment]
Still work in progress: https://github.com/Microsoft/CNTK/tree/t-makrei/YOLOv2/Examples/Image/Detection/YOLOv2

**Comment by wind-rider** [comment]
Nice to see that it's being worked on! Thank you for your reply!

**Comment by kodonnell** [comment]
Is there a status update on this @ebarsoumMS ? I'm not sure if that branch has been abandoned - if so, 
could reasons be given for why (so I can possibly use what's there)? If it's just incomplete, and 'nearly there', then I might have a look at understanding and 'completing' it.

cc @wilrich-msft (I'd cc `t-makrei` or `makrei` too, but can't seem to find that user)

**Comment by riverar** [comment]
Why is this closed? Support is still missing, from what I can see.

cc: @ebarsoumMS @wilrich-msft @KeDengMS

**Comment by JasonRuan5** [comment]
Yes, it would be really great to have Yolo2 supported in cntk! Thanks so much @ebarsoumMS
