### ISSUE TITLE
FastRCNN with CSEvalClient Rois question by CNTK 2.1

### ISSUE THREAD

**Issue by wendy7707** [Microsoft/CNTK#2298]
I just follow the steps as following, after "outputs = model.Evaluate(inputs, outDims.First().Key);" the result of output is different with "test.z" in python.,so it has different detection results with python environment. Please help me to solve this problem, I do not know how to fix it. Thanks!
<img width="633" alt="2017-09-04 2 04 07" src="https://user-images.githubusercontent.com/30385554/30011555-758d1b32-917b-11e7-9f09-67cfa839f405.png">
<img width="805" alt="2017-09-04 2 10 21" src="https://user-images.githubusercontent.com/30385554/30011557-81bcc1dc-917b-11e7-908d-b5f4f792d741.png">

**Comment by wendy7707** [comment]
The first image is the result of output in C#, the second image is the result of test.z. You can see it is different.

**Comment by spandantiwari** [comment]
I am not exactly able to see - is this the bounding boxes? Could the bounding boxes just be permuted? 

If you are still seeing this, send some more details please.
