### ISSUE TITLE
Errors in evalution by CNTK 2.1 

### ISSUE THREAD

**Issue by wendy7707** [Microsoft/CNTK#2299]
I tried to evalute the model by CNTK 2.1 based on CPU device, when I run the following coding:

 modelFunc.Evaluate(inputDataMap, outputDataMap, DeviceDescriptor.CPUDevice);

it will show an error"TensorOp (binary): The only permitted binary reduction operation is opSum." Would you please tell me how to solve this problem? Thanks!

**Comment by cha-zhang** [comment]
Can you post the modelFunc?

**Comment by cha-zhang** [comment]
Close this issue due to lack of response. Please reopen if needed.
