### ISSUE TITLE
Correct way of reading high dimension input

### ISSUE THREAD

**Issue by xforceco** [Microsoft/CNTK#2301]
For `CNTKTextFormatReader`, say I want to have `Input {4:5:3}`
In terms of image context, say an image with height=4, width=5, channel=3

How should I prepare my input file? What's the correct order of dimension?

**Comment by n17s** [comment]
The dimension that changes the fastest will be the height, followed by the width, followed by the channel.

**Comment by n17s** [comment]
Closing. Feel free to reopen.
