### ISSUE TITLE
Output gradients / distribution of weights during training using brainscript

### ISSUE THREAD

**Issue by L-Ramos** [Microsoft/CNTK#2303]
I built a shallow 3DCNN with 3 conv layers and I'd like to output the weights during training. Is that possible using brainscript?

**Comment by KeDengMS** [comment]
You can set traceLevel=1000000, to dump all nodes during computation. However if your network is big it might generate too many logs.

**Comment by cha-zhang** [comment]
Hope this has been resolved. Close due to inactivity. Please reopen if needed.
