### ISSUE TITLE
Are there any available state of the art machine translation models?

### ISSUE THREAD

**Issue by ArmageddonKnight** [Microsoft/CNTK#2305]
Hi there,

Could you please kindly tell me whether there is any available machine translation models (that could work on the `WMT` dataset), such as the well-known model in ` Neural Machine Translation by Jointly Learning to Align and Translate`?

**Comment by n17s** [comment]
The closest thing we have is the [sequence to sequence tutorial](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb). This tutorial contains all of the ingredients for training. For decoding, it is missing the beam search but it is not that hard to add.

**Comment by ArmageddonKnight** [comment]
Thanks for the reply.
