### ISSUE TITLE
Using Layers API to stack Multi-Input Functions

### ISSUE THREAD

**Issue by bencherian** [Microsoft/CNTK#2306]
I'm trying to create a custom "Layer" for use with the Layers API which takes two inputs. I'd like one of the inputs to stack when using the higher order layers like `Sequential` or `For`, and explicitly specify the other input to the layer. In this specific situation, I have a dropout-like function which I'd like to activate via an input to the model. The code below is an example of the layer I'd like to define.

```Python
def CustomDO(keep_prob:float=0.9, name:str=""):
    alpha = 1.6732632423543772
    scale = 1.0507009873554805
    dropout_rate = 1-keep_prob
    alphap = -scale * alpha
    a = np.sqrt(keep_prob + alphap**2 * keep_prob * dropout_rate)
    b = cntk.constant(-a * (dropout_rate * alphap), dtype=np.float32)
    a = cntk.constant(a, dtype=np.float32)


    @BlockFunction("CustomDO", name)
    def custom_do_f(x, activator):
        d = ctrand.bernoulli_like(x, mean=keep_prob)
        output_active_do = a * (x * d + alphap * (cntk.constant(1) - d)) + b
        output_inactive_do = a * x + b
        return cntk.element_select(activator, output_active_do, output_inactive_do)

    return custom_do_f
```

I'd like to stack this function with Dense layers (i.e., x is the output of a Dense layer), but still have the `activator` input fed by an Input variable. If I take the layer, and replace the placeholder for activator with an input and then try to stack it with Dense I get an error about mismatched number of arguments.
Is there a practical way to do what I'm trying to do? I think I could conceivably re-implement a lot of the higher order layers to achieve this, but if I'm missing out on a more generic solution (or if there are plans for one), that would be good to know...I imagine this would be useful for implementing newer CNNs like DenseNet.

**Comment by n17s** [comment]
If your activator is just "train" or not, then you can use dropout instead of bernoulli_like and drop the activator argument altogether. Also, there are some layers that take two arguments such as RecurrenceFrom, that maybe would be helpful to look at. By the way, we have something like DenseNet (search for SequentialClique) but we never finished it (it is adding rather than concatenating the outputs).

**Comment by bencherian** [comment]
I'm using a saved model with the C++ API for inference, and I want to be able to turn dropout on/off during inference in order to see the variation dropout induces with a given input. If there is a way to trick the C++ API (and Python API if possible) into thinking we are doing training to turn dropout on, that would suffice in this case as well...having an input for this seemed cleaner.

**Comment by n17s** [comment]
I believe the way to do that would be to specify `outputsToRetainBackwardStateFor` a non-empty dictionary in the `Forward` function.

**Comment by bencherian** [comment]
Ok, that's good to know.
Is there a `ones_like` function or something like that I can use in order to use dropout in this manner? The only way I can see of recreating this is to replace the `bernoulli_like` function with `dropout(x/x)` which seems like it would be rather computationally wasteful. (Floating point division on is not cheap.)

**Comment by n17s** [comment]
I have ones_like in a branch that I will try to get back to soon. In the meantime do something like 0*x+1 or x+1-x
