### ISSUE TITLE
Using AttentionModel with LSTM

### ISSUE THREAD

**Issue by abhimohta** [Microsoft/CNTK#2307]
Hey

I need help in running AttentionModel with my LSTM RNN. When I try to do this - 

Sequential([
            Embedding(hidden_size, name='embed'),
            Recurrence(AttentionModel(LSTM(hidden_size), attention_span=10, attention_axis=1)),
            C.sequence.last,
            Dense(out_size)
        ])(inp)

I get this error - 
KeyError: 'Slice for multioutput functions is not supported, the fallback to select to output requires that only one index is provided. arg: 2, self: LSTM(dh: Sequence[tensor], dc: Sequence[tensor], x: Sequence[tensor]) -> Tuple[Sequence[tensor], Sequence[tensor]]'

I do not find any documention/examples/tutorials of using AttentionModel. Can someone point me to the same, if any?

**Comment by abhimohta** [comment]
I have a single sequence(of variable length) as input - so my input is defined as cntk.sequence.input_variable(1). Correspondingly my attention axis I have set as 1.

**Comment by n17s** [comment]
We have an example on how to use this layer [in the sequence to sequence tutorial](https://github.com/Microsoft/CNTK/blob/v2.1/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb)

**Comment by n17s** [comment]
Closing. Feel free to reopen.
