### ISSUE TITLE
Transforms with a composite MinibatchSource

### ISSUE THREAD

**Issue by patykov** [Microsoft/CNTK#2309]
Hi, I am attempting to use a composite MinibatchSource with some ImageDeserializers and need to do some transforms like random crop and random flip. But in my case I need the transforms to be the same for all images with the same sequenceID. 
For example, if the first image (sequenceID = 0) of the first ImageDeserializer is flipped, then the first image (sequenceID = 0) of the second ImageDeserializer also needs to be flipped.

Is that possible? Will the transforms be the same for all ImageDeserializers in a composite reader?

**Comment by n17s** [comment]
To verify this,you can do the following: take the example code from [this SO thread](https://stackoverflow.com/questions/43151213/cntk-create-minibatchsource-from-numpy-array-for-multi-gpu-training), provide identical files to both readers, add some random transforms, to both sides, and create a "network" that just takes the two inputs and computes the squared error of their difference. If the output of the network is zero (or very close to zero) then it means that the same transforms are applied. If not, then let us know so we can fix it.

**Comment by ChunHsinWang** [comment]
The transforms (random cropping and flipping) will applied to both readers only when minibatch size is 1. For minibatch size > 1, the two readers does not get the same transforms.

**Comment by patykov** [comment]
I got to the same result: the random transform does not work for minibatch size > 1.  Will this be fixed?

**Comment by n17s** [comment]
We will try to address it in version 2.3 (version 2.2 will be released very soon)

**Comment by patykov** [comment]
Are there any updates on this bug? It wasn't fixed in the latest versions.
