### ISSUE TITLE
MinibatchSource's multithreaded_deserializer=None appears to not behave as expected

### ISSUE THREAD

**Issue by mawah** [Microsoft/CNTK#2311]
Hi folks,

I'm performing distributed training using Azure Batch AI Training. I have two NC6 VMs running CNTK 2.0 RC2 (the latest versionavailable for BAIT as of this writing) attempting to train using images stored on a shared NFS. We expected that there was no need to set the MinibatchSource's multithreaded_deserializer parameter because of [this description in the docs](https://www.cntk.ai/pythondocs/cntk.io.html?highlight=minibatchsource#cntk.io.MinibatchSource):

> multithreaded_deserializer (bool) – specifies if the deserialization should be done on a single or multiple threads. Defaults to None, which is effectively “auto” (multhithreading is disabled unless ImageDeserializer is present in the deserializers list). False and True faithfully turn the multithreading off/on.

Our training data is read into the MinibatchSource with an ImageDeserializer, so we expected that multithreading would be enabled by default:
```
cntk.io.MinibatchSource(cntk.io.ImageDeserializer(
	map_filename,
	cntk.io.StreamDefs(
		features=cntk.io.StreamDef(
			field='image', transforms=transforms, is_sparse=False),
		labels=cntk.io.StreamDef(
			field='label', shape=num_classes, is_sparse=False))))
```

However, we noticed a substantial performance increase when we explicitly set `multithreaded_deserializer=True`, implying that multithreading was otherwise disabled.

I can't seem to find docs for CNTK 2.0 RC2 specifically, so I can't confirm whether the CNTK 2.1 docs linked above are applicable here. Is there a way to find the relevant docs?

Is it possible that this parameter is not behaving as intended? (Maybe the presence of an ImageDeserializer is only checked if `deserializers` is a list?) To be sure, is there any way for us to confirm whether multithreaded deserialization was automatically enabled when we didn't specify `multithreaded_deserializer=True`?

Thanks a bunch!

**Comment by n17s** [comment]
Hi Mary, the old docs are at: https://cntk.ai/pythondocs-ver/2_0-rc2/ and according to https://cntk.ai/pythondocs-ver/2_0-rc2/cntk.io.html?highlight=multithreaded_deserializer
this valuew as by default False. So that explains the observed behavior and therefore I'm closing this.
