### ISSUE TITLE
CNTK objectdetection sample 4_trainSVM.py not running

### ISSUE THREAD

**Issue by netvinod** [Microsoft/CNTK#2314]
I am trying to build and run the ObjectDetectionUsingCNTK using grocery data set.

I am running into issues while running it.
The 1_, 2_ and 3_ files compile fine.  When i attempt to compile 4_TrainSVM, i run into the issue shown below:
Traceback (most recent call last):
  File "4_trainSvm.py", line 50, in <module>
    svm_targetNorm, svm_penality, svm_loss, svm_rngSeed)
  File "c:\Repo\ml_dl_practice\object_detection_cntk_svm\ObjectDetectionUsingCnt
k\fastRCNN\train_svms.py", line 45, in __init__
    self.feature_scale = self._get_feature_scale()
  File "c:\Repo\ml_dl_practice\object_detection_cntk_svm\ObjectDetectionUsingCnt
k\fastRCNN\train_svms.py", line 74, in _get_feature_scale
    total_norm / count, total_sum / count))
TypeError: unsupported format string passed to numpy.ndarray.__format__

Any pointers to fixing this issue? I see this issue both in python3.6 and python 3.5. If I comment the above line (its a print statement) it proceeds, but further down the line I run into issue shown below:

Traceback (most recent call last):
  File "4_trainSvm.py", line 51, in <module>
    svm.train()
  File "c:\Repo\ml_dl_practice\object_detection_cntk_svm\ObjectDetectionUsingCnt
k\fastRCNN\train_svms.py", line 187, in train
    self.get_pos_examples()
  File "c:\Repo\ml_dl_practice\object_detection_cntk_svm\ObjectDetectionUsingCnt
k\fastRCNN\train_svms.py", line 107, in get_pos_examples
    scores, boxes, feat = self.im_detect(self.net, i, gt_boxes, self.feature_sca
le, gt_inds, boReturnClassifierScore = False)
  File "c:\Repo\ml_dl_practice\object_detection_cntk_svm\ObjectDetectionUsingCnt
k\helpers.py", line 620, in im_detect
    if bboxIndices != None:
ValueError: The truth value of an array with more than one element is ambiguous.
 Use a.any() or a.all()

My numpy is  1.13 and running on a conda python installation on Windows  8

**Comment by kpierce8** [comment]
I don't know if it is right but I changed the line to
`if np.any(bboxIndices != None):`
And it ran.
Well it found a new error in scikit-learn which I'm now trying to track down.

**Comment by brunoprojects** [comment]
Same here, changed to np.any(), but now stuck with sklearn issue.  Any progress?

**Comment by kpierce8** [comment]
Ah, yes. Change line 69 in the parameters file to "balanced" from "auto"
