### ISSUE TITLE
ERROR WITH FEATURE TRANSFORM (KALDI)

### ISSUE THREAD

**Issue by mravanelli** [Microsoft/CNTK#232]
Hi,
I'm trying to apply some basic transformations to the kaldi features before feeding the NN. 
I'm using a working version of the kaldi plug-in and I'm trying to do a simple splicing in this way (I know there is another way to splice frames, but this is just an example of a possible transformation):

1) I have defined the transformation of my 120 features (40 fbank+delta+deltadelta) in this way (saved in $expdir/fea_splice):

```
<Nnet> 
<Splice> 2280 120 
[ -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 ]
</Nnet> 
```

2)  I wrote the basic configuration file in this way:

```
tee $expdir/Base.config <<EOF
ExpDir=$expdir
logFile=train_cntk
modelName=cntk.dnn

labelDim=${labelDim}
featDim=${featDim}
labelMapping=${expdir}/cntk_label.mapping
featureTransform=$expdir/fea_splice

inputCounts=${expdir}/cntk_train.counts
inputFeats=${expdir}/cntk_train.feats
inputLabels=${expdir}/cntk_train.labels

cvInputCounts=${expdir}/cntk_valid.counts
cvInputFeats=${expdir}/cntk_valid.feats
cvInputLabels=${expdir}/cntk_valid.labels
EOF
```

3)  I run the training

```
## training command ##
$cn_gpu configFile=${expdir}/Base.config configFile=${expdir}/CNTK2_new_lrkaldi.config DeviceNumber=0 action=TrainDNN ndlfile=$ndlfile
```

The problem is  this:

```
requiredata: 124 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 25 (frame range [2261209..2351457]), 26 resident in RAM
requiredata: 119 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 26 (frame range [2351458..2441471]), 27 resident in RAM
requiredata: 125 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 27 (frame range [2441472..2532709]), 28 resident in RAM
requiredata: 138 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 28 (frame range [2532710..2623547]), 29 resident in RAM
attempt: releasedata: called when data is not memory, retrying 2-th time out of 5...
attempt: releasedata: called when data is not memory, retrying 3-th time out of 5...
attempt: releasedata: called when data is not memory, retrying 4-th time out of 5...
attempt: releasedata: called when data is not memory, retrying 5-th time out of 5...
EXCEPTION occurred: releasedata: called when data is not memory
```

Any idea about what is going on here?

Thank you 

Mirco

**Comment by yzhang87** [comment]
Hi Mirco,

I have a very long time didn't use the kaldi transform. I will take a look. Right now you can write it to ark first (although it may waste lots of space).

btw, if you just do context expansion, the reader will do it automatically by setting contextWindow.

thanks,
Yu

**Comment by mirco86** [comment]
Hi Yu, 
please let me know if you also see this error and if you have an idea about it!

I know there are other ways to perform splicing and transformations but I think that giving the possibility to directly use Kaldi transformations could be a very useful features!

**Comment by yujunlhz** [comment]
Hey CNTK developers:

I came across the same issue. Is there a solution there? looks like all the feature trying to reside in the RAM.

**Comment by dongyu888** [comment]
you can set 

randomize=some_value

to limit the size of features loaded into the memory. A typical some_value, for example, is 8640000    # 24hr data
