### ISSUE TITLE
Issue to use SELU activation with Brainscript

### ISSUE THREAD

**Issue by jplu** [Microsoft/CNTK#2320]
Hello,

The SELU activation function has been integrated in the last 2.1 version, but when I try to use it in one of my Brainscript file, I get the following error:

```
EXCEPTION occurred. while evaluating: BrainScriptNetworkBuilder(18): unknown identifier 'SELU'
```

Are we able to use it only through Python?

Thanks.

**Comment by n17s** [comment]
Yes. We are encouraging people to move to use well supported languages including Python, C++, (and very  soon C#).

**Comment by n17s** [comment]
Closing. Feel free to reopen.
