### ISSUE TITLE
implement fastText on Cntk?

### ISSUE THREAD

**Issue by whaozl** [Microsoft/CNTK#2323]

**Comment by n17s** [comment]
fastText uses the following components:

- n-grams and hashing: you can do that when you process your input
- an embedding layer. We have many examples showing how to use that.
- hierarchical softmax: we don't have any plans for hierarchical softmax. You can check out our tutorial for sampled softmax or use noise contrastive estimation via the nce_loss built-in function.

It should be easy to put these components together so I'm closing this. Feel free to reopen if you have further questions.
