### ISSUE TITLE
transferlearning feature_node_name and last_hidden_node_name for googleNet

### ISSUE THREAD

**Issue by teresayao** [Microsoft/CNTK#2324]
Hi,
I am trying to use pre-trained GoogleNet (InceptionV3_ImageNet_CNTK.model) model to train my classifier and having difficulties to find feature_node_name and last_hidden_node_name. Printout only shows shape with no name? Any suggestions?
 (1000,)
 (1,)
aggregateLoss ()
 (1,)
aggregateEvalMetric ()
 (1000,)
 (2048, 1, 1)
.....

Thanks
Teresa

**Comment by tangyuq** [comment]
A workaround might be:
  nodes = C.logging.get_node_outputs(loaded_model)

Locate in this list your desired node.  You can also plot the graph to help identify the node: 
     C.logging.graph.plot(loaded_model, 'tmp.svg')

**Comment by teresayao** [comment]
thanks, workaround works
