### ISSUE TITLE
Looking for C# example for image classification

### ISSUE THREAD

**Issue by akegramener** [Microsoft/CNTK#2327]
Hi,

I am looking for a model evaluation example in c# where I can input an image and it will show what is the image, example plant species, animal species, e.t.c

**Comment by cha-zhang** [comment]
Did you check the examples under: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples

**Comment by akegramener** [comment]
In the CS examples, it does it show the image classification, the predictions only show probability but not what species they are for example

**Comment by cha-zhang** [comment]
Take the class with the highest probability and that's your species. The user app should handle this.

**Comment by cha-zhang** [comment]
Please check #2326.

**Comment by deepakkumar1984** [comment]
Try this example: https://github.com/deepakkumar1984/SiaNet/wiki/Example---Image-Classification
