### ISSUE TITLE
CNTK C++ - Slow Evaluation in Debug Mode and Incorrect Result.

### ISSUE THREAD

**Issue by darkoob12** [Microsoft/CNTK#2329]
I am using CNTK C++ API for License Plate Detection. My problem is that the code does not work in debug mode and it is very slow.
Here is my setup:
* i am using __Visual Studio 2015 Update 3__
* i have added __CNTK.CPUOnly__ nuget package
* i have trained the model in __Keras__ with CNTK back-end

```
cv::Mat AECropper::GetMask(cv::Mat img) {
	// pre-process and resize
	cv::Mat img_pp = Preprocess(img);

	// create network input from the image
	ValuePtr inVal;
	MatToInput(img_pp, inVal);
	
	// pointer for network output
	ValuePtr outVal;
	std::unordered_map<Variable, ValuePtr> inputs = { {inVar, inVal} };
	std::unordered_map<Variable, ValuePtr> outputs = { { outVar, outVal } };

	// compute the output for the given input
	model->Forward(inputs, outputs,DeviceDescriptor::CPUDevice());

	// create an image from network's output
	cv::Mat raw_mask = OutputToMat(outputs[outVar]);
	
	// resize back to the original size
	cv::Mat mask = Resize(raw_mask, img.size());

	return mask;
}
```
The call to the `Forward` method takes _**70** seconds in Debug mode_ and _**0.5** seconds in Release mode_ and their result is different.
### Release result:
![Release_mask](https://user-images.githubusercontent.com/1968642/30310981-7bf241a4-97a8-11e7-819f-80a152cd971c.jpg)
### Debug result:
![debug_mask](https://user-images.githubusercontent.com/1968642/30310998-9306ce1e-97a8-11e7-8954-cddefbd33020.jpg)
--
This makes debugging very hard for me. i cannot trace the code in the release mode.
Do you know why CNTK behaves very different in Debug?
Is there any way to fix it?
Thanks.

**Comment by ebarsoumMS** [comment]
Can you use Release_NoOpt?

**Comment by springkim** [comment]
Hi. Can you share your code?
I want to know "Preprocess" and "MatToInput".
Thanks.

**Comment by cha-zhang** [comment]
@darkoob12 has the issue been resolved?

**Comment by ebarsoumMS** [comment]
Please reactivate if the issue still there.
