### ISSUE TITLE
Image transform padding behaviour

### ISSUE THREAD

**Issue by tobyclh** [Microsoft/CNTK#2330]
I was trying the image transform scaling with padding, hoping to first rescale my image while keeping the aspect ratio to either the target_h or target_w, then pad the other dimension with value, so the result will be [target_h, target_w], while right now [the cpp source code](https://github.com/Microsoft/CNTK/blob/77d7f943b53b0accfe7e9804639c7d10b1bbee7e/Source/Readers/ImageReader/ImageTransformers.cpp) at line 402 only rescale 1 dimension of the image and pad the remaining dimension, which I am not sure why it is doing so, and I assume right now to achieve such effect i can only do it outside CNTK?
Thank you

**Comment by cha-zhang** [comment]
In release 2.2 we will support arbitrary input image size, so padding is no longer needed if you have a fully convolutional network.

**Comment by tobyclh** [comment]
Understood. Good work over there! Please feel free to close this.
