### ISSUE TITLE
CNN connecting to LSTM Layer

### ISSUE THREAD

**Issue by xforceco** [Microsoft/CNTK#2342]
I have a CNN that produces output size of `2x2x128`.
Connecting to LSTM of `32` nodes would give output `32x2x128` per time step.

What does this mean? What is the behavior of LSTM handling high dimension cases in CNTK?

**Comment by n17s** [comment]
The CNTK matrix multiplication inside the LSTM has some additional functionality that kicks in here. You probably want to flatten the input before feeding to LSTM. One way of doing that would be a reshape with a shape of (-1,).

**Comment by xforceco** [comment]
Thank you for the reply.
I have tried flattening and it is good.

However, I still want to know the underlying mechanism of high dimension input to lstm in cntk, can anyone give a brief description on this?

**Comment by n17s** [comment]
What's happening inside the LSTM is just matrix multiplication of the parameters with the inputs (there also some non-linearities which we can ignore for the purposes of shapes). Then the rules described here 
https://docs.microsoft.com/en-us/cognitive-toolkit/Times-and-TransposeTimes under "Extended interpretation of matrix product" apply.

**Comment by cha-zhang** [comment]
Seems this issue has been resolved. Close it now.
