### ISSUE TITLE
CropNode in Python

### ISSUE THREAD

**Issue by nitrif** [Microsoft/CNTK#2347]
Hi,

Do you plan to implement CropNode in Python?

```
template <class ElemType>
class CropNode : public ComputationNode<ElemType>, public TransformerNode
```

Our implementation of FCN semantic segmentation depends on it and keep us pinned on BrainScript.

Thanks,
Nikola

**Comment by ebarsoumMS** [comment]
Soon, it is in CR: https://github.com/Microsoft/CNTK/tree/nikmil/python_crop_cr
