### ISSUE TITLE
How to support Connectionist Temporal Claasification (CTC)

### ISSUE THREAD

**Issue by zengzengsun** [Microsoft/CNTK#235]
I want to implement a system of end to end ASR where the CTC is  crucial but not exist in CNTK. Can anyone give me some guildlines? very grateful!

**Comment by mradmila** [comment]
Hi,

Other people have expressed the same need for CTC, but we don't have it supported yet. It is in our plans, and I will reach out to the appropriate owners to try and get some ETA.

**Comment by zengzengsun** [comment]
Thanks a lot! 

I will implement it based on CNTK in those days.
But because CTC is a iterative algorithm which does not have good parallelism and i am not familiar with CNTK framework, i am afraid about the performance of it. 

Anyway, it is exciting that you are also consider it in your plans! thank you again!

**Comment by frankseide** [comment]
I worry that it may not be possible to represent CTC in today's CNTK. I believe you will need tensors with two variable-length dimensions (one for the #frames, and one for the #labels). CNTK currently only supports a single variable-length dimension.

**Comment by vmazalov** [comment]
CNTK now supports CTC training. Here is the end to end test and corresponding documentation:

https://github.com/Microsoft/CNTK/tree/master/Tests/EndToEndTests/Speech/LSTM_CTC_MLF

**Comment by lahirufano** [comment]
@vmazalov Does CNTK supports CTC beam decoding?  Thanks!

**Comment by delzac** [comment]
For anyone looking for a CTC Encoder to convert your labels into the ctc data format that cntk will accept you can check out my extension library [cntkx](https://github.com/delzac/cntkx), it has a `CTCEncoder` to help do just that.
