### ISSUE TITLE
Problems with broadcasting of plus operation

### ISSUE THREAD

**Issue by SimonRuehle** [Microsoft/CNTK#2351]
Hello together,
I have a scenario, were I have to add the bias after a convolution at a later point. Therefore I wanted to use a parameter and simply add it to the layers's output (basically some other operations are done inbetween).
The output I want the bias to be added to is of shape: **[11 x 215 x 510]**
My parameter has shape **[11]**. In Tensorflow there is the function bias_add, which seems to work perfectly, but in CNTK I could only find the '+' operator and the cntk.ops.plus function, which both fail. 
The error of the later one:
`RuntimeError: Binary elementwise operation Plus: Left operand 'Output('ElementTimes52_Output_0', [#], [11 x 215 x 510])' shape '[11 x 215 x 510]' is not compatible with right operand 'Parameter('Parameter55', [], [
11])' shape '[11]'.`
Can anybody show me a way how to solve this issue? If the full stack trace is needed, I can add it, but it doesn't seems really helpfull.

Yours sincerely,
Simon Rühle

**Comment by n17s** [comment]
We try to follow numpy semantics on broadcasting. What you do does not work on numpy and does not work on CNTK. If you reshape the bias to (11,1,1) it will work.
```python
>>> a=np.arange(11*215*510).reshape(11,215,510)
>>> b=np.arange(11)
>>> a.shape
(11, 215, 510)
>>> b.shape
(11,)
>>> c=a+b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (11,215,510) (11,)
>>> bb=b.reshape(11,1,1)
>>> c=a+bb
>>> ca=C.constant(a)
>>> cbb=C.constant(bb)
>>> cc=ca+cbb
>>> cc.eval().shape
(11, 215, 510)
```

**Comment by n17s** [comment]
Closing. Feel free to reopen.
