### ISSUE TITLE
How to make the result reproduceable in CNTK?

### ISSUE THREAD

**Issue by jkhlot** [Microsoft/CNTK#2355]
During training vgg model using CNTK, I find the result is different if I retrain the model.
I have already set the random seed using  random.seed(1), np.random.seed(1) ,but it seems useless 
Anyone has the same issue ? How to resolve it ?

**Comment by cha-zhang** [comment]
cntk.debug.force_deterministic().

**Comment by jkhlot** [comment]
great thx
