### ISSUE TITLE
How to get the intermedia layer output in CNTK

### ISSUE THREAD

**Issue by jkhlot** [Microsoft/CNTK#2356]
How to get the intermediate layer output in CNTK? I did not found any python api in wiki,great thanks for any advice

**Comment by cha-zhang** [comment]
Check the example here: https://github.com/Microsoft/CNTK/tree/master/Examples/Image/FeatureExtraction

**Comment by cha-zhang** [comment]
Hope this issue has been resolved. Closing it now.
