### ISSUE TITLE
NuGet Package Manager says same thing for GPU and CPU versions.

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [Microsoft/CNTK#2360]
Was ready to start installing 2.2 and trying the C# api and looked at the Nuget package manager in VS2017 and see this.

![image](https://user-images.githubusercontent.com/4176416/30512768-8274096c-9ac4-11e7-8262-b0ac7a1ea0b6.png)

Same description.

**Comment by liqunfu** [comment]
fixed
