### ISSUE TITLE
RuntimeError: cuDNN failure 8 with dilation=(2,) in Convolution1D

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#2361]
Hi!

For curiosity, I tried dilation=(2,) in Convolution1D, and I'm getting an error as shown below. dilation=(1,) works!

I'm using this CNTK version: https://cntk.ai/PythonWheel/GPU-1bit-SGD/cntk-2.2-cp36-cp36m-win_amd64.whl

I'm using "GPU[0] GeForce GTX 970 as the process wide default device".
CUDA: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
Latest CuDNN.

```
Build info:

                Built time: Sep 15 2017 07:42:32
                Last modified date: Fri Sep 15 04:28:56 2017
                Build type: Release
                Build target: GPU
                With 1bit-SGD: yes
                With ASGD: yes
                Math lib: mkl
                CUDA version: 8.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=DESKTOP-RBONKM8 ; expr=workspaceSizeFinder()
Traceback (most recent call last):
  File "test_cntk.py", line 417, in <module>
    profiling=args['profile'])
  File "test_cntk.py", line 355, in dct_exp
    train_and_test(network, trainer, reader_train, reader_test, minibatch_size, epoch_size, restore, profiling)
  File "test_cntk.py", line 302, in train_and_test
    test_config = TestConfig(test_source, minibatch_size=minibatch_size)
  File "C:\Users\testsys\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\testsys\Anaconda3\lib\site-packages\cntk\train\training_session.py", line 276, in train
    super(TrainingSession, self).train(device)
  File "C:\Users\testsys\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 3312, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=DESKTOP-RBONKM8 ; expr=workspaceSizeFinder()

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch
    - CNTK::TrainingSession::  Train
    - PyInit__cntk_py
    - PyCFunction_FastCallDict
    - PyCFunction_FastCallKeywords
```

**Comment by arijit17** [comment]
Interestingly, the examples provided in CNTK's convolution and convolution transpose [documentation](https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=convolution#cntk.ops.convolution) works with various dilation!  

So, what is wrong in my 1-D convolution?
```
convA   = C.layers.Convolution1D ((255,), 128, pad=True, activation=C.ops.relu,reduction_rank=0, dilation=2)(scaled_input)
    convA = C.layers.BatchNormalization(map_rank=1)(convA)
```

**Comment by arijit17** [comment]
Hello!

I did some more investigation with this issue and trying out an example as given [here](https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=convolution#cntk.ops.convolution)

```
img = np.reshape(np.arange(36.0, dtype = np.float32), (1, 6, 6))
x = C.input_variable(img.shape)
filter = np.reshape(np.array([2, -1, -1, 2, 2, 1, 1, 1, -1], dtype = np.float32), (1, 3, 3))
kernel = C.constant(value = filter)
np.round(C.convolution(kernel, x, auto_padding = [True],dilation=2).eval({x: [img]}),5)
```
I also get this error:
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=NUR-ABISW-DT-02 ; expr=workspaceSizeFinder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 631, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\ops\functions.py", line 765, in forward
    keep_for_backward)
  File "C:\Users\abisw\AppData\Local\Continuum\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 1876, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=NUR-ABISW-DT-02 ; expr=workspaceSizeFinder()

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc

**Comment by ebarsoumMS** [comment]
@arijit17 thank you for reporting the issue,  I will submit a fix soon.

**Comment by ebarsoumMS** [comment]
Thanks for reporting the issue, the fix is in master.

**Comment by arijit17** [comment]
Thank you @ebarsoumMS for taking care of this. 

So, to play with the fixed version, I need to simply re-install https://cntk.ai/PythonWheel/GPU-1bit-SGD/cntk-2.2-cp36-cp36m-win_amd64.whl
OR do I need to build it myself?

Sorry for asking this stupid question.

**Comment by ebarsoum** [comment]
@arijit17 sadly you need to build it from the source or wait for 2.3 release (we release each 6 weeks).

**Comment by arijit17** [comment]
Hello @ebarsoumMS : when is the 2.3 release? Or, is there some instructions to build from source? I'm used to using CNTK with Python API.

**Comment by ebarsoumMS** [comment]
It should be released around mid Nov.

**Comment by arijit17** [comment]
I can confirm the fix now :-)
