### ISSUE TITLE
CSTrainingCPUOnlyExamples: Missing Cntk.Core.CSBinding-2.2.dll

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#2363]
I can run the logistic regression solution with VS 2015 Update 3 in CPU mode in the downloaded repo folder, but when attempt to build a new solution in a new folder (copy Program.cs, LogisticRegression.cs, TestHelper.cs and load the CNTK.CPUOnly nuget to the new project) it seems to build okay, but I get runtime error missing Cntk.Core.CSBinding-2.2.dll.  

I see there is a:

- \packages\CNTK.CPUOnly.2.2.0\support\x64\Debug\Cntk.Core.CSBinding-2.2**d**.dll
- \packages\CNTK.CPUOnly.2.2.0\support\x64\Release\Cntk.Core.CSBinding-2.2.dll

I attempted to add the above release reference path to no avail.

System.DllNotFoundException occurred
  HResult=-2146233052
  Message=Unable to load DLL 'Cntk.Core.CSBinding-2.2.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=Cntk.Core.Managed-2.2
  TypeName=""
  StackTrace:
       at CNTK.CNTKLibPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_CNTKLib(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
       at CNTK.CNTKLibPINVOKE.SWIGExceptionHelper..cctor()
  InnerException:

**Comment by whitmark** [comment]
I compared the dlls in the repo (C:\repos\CNTK-master\x64\CNTKCSTrainingCPUOnlyExamples.Debug) with my new project output folder (Documents\Visual Studio 2015\Projects\wdcDLTTest1\wdcDLTTest1\bin\Debug) and incrementally copied each of the yellow/pink highlighted items below to get it to work.  Apparently, the absence of "opencv_world310.dll" was throwing the above error even though I was only running the LogisticRegression.cs code.  In addition to enhanced runtime messaging, it will be a useful reminder in the docs to not overlook the dlls highlighted in pink that are not included in the nuget load.

![dlls required in output path](https://user-images.githubusercontent.com/8396992/30522926-f6a98e6a-9ba5-11e7-8cf4-09a45f2ed7e8.png)

**Comment by liqunfu** [comment]
@whitmark Thanks for trying it out! Make sure you project is x64 - you build output suggested that it was not build for x64 platform. Other build platforms are not supported by CNTK.

**Comment by whitmark** [comment]
@liqunfu Thanks, I wondered why VS 2015 would not set the output path to bin/x64/Debug although I set the platform target to x64 in the configuration manager until I found this extra step:

https://msdn.microsoft.com/en-us/library/ms185328.aspx
