### ISSUE TITLE
"CUDNN_POOLING_MAX_DETERMINISTIC" is undefined MathCUDA

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2368]
I am trying to compile the main VS solution (`master` branch at present time) but the compilation fails with the following error message:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		identifier "CUDNN_POOLING_MAX_DETERMINISTIC" is undefined	MathCUDA	C:\code\cntk\Source\Math\CuDnnConvolutionEngine.cu	160	
```

Could someone help me getting this project to compile? Thanks!

**Comment by mfuntowicz** [comment]
Hi @vermorel 

CUDNN_POOLING_MAX_DETERMINISTIC requires cudnn v6, from the issue, I suspect you're still using v5.1.

Morgan

**Comment by vermorel** [comment]
Thanks! Yes, upgrading to cudnn v6 did the trick. It would be nice however to have a more user-friendly error message. There is quite a few dependencies for CNTK. It would really help to provide some support when one dependency is not featuring the right version.

**Comment by sayanpa** [comment]
Looks like this is resolved. Thanks @mfuntowicz
