### ISSUE TITLE
Evaluating FCN on images with different size

### ISSUE THREAD

**Issue by nitrif** [Microsoft/CNTK#2375]
I have trained a FCN model for semantic segmentation on 256x256 images. Is it possible to utilize fully-constitutional property and run the model on images of different size, e.g. 512x512 or 1024x1024?

In Caffe this is possible and resolved dynamically where the only constraint is the memory size. For my scenario it would work even if I could prepare/adapt the model in advance for the different image size. Is this possible to do?

Thanks,
Nikola

**Comment by ebarsoumMS** [comment]
Can you use C.FreeDimension as the high and width of the input? This should accept variable size images.

**Comment by nitrif** [comment]
Thanks, it seems to work.

I need additional clarification:
Obtaining tensor dimensions with x.shape[n] for FreeDimension now yields negative numbers, like -3. Is this just a random negative number or it has some meaning?
Is it possible to deduce the dimension in the runtime? E.g for producing a custom metrics function I would need to know WxH. Also, can I call reshape operation where I can divide one dimension by 2 while mltiplyintg the other by the same factor, etc.

**Comment by ebarsoumMS** [comment]
-3 is the constant value corresponding to FreeDimension. FreeDimension doesn't bind to any value, so it is always -3, and accept any value. You can know thg WH by intercepting the minibatch before feeding it to the network. Regarding changing the aspect ratio of the input that need to be done before feeding the image to the network.

**Comment by cha-zhang** [comment]
hope this has been resolved. Close the issue now. Feel free to reopen.
