### ISSUE TITLE
Bilinear deconvolution with immutable weights

### ISSUE THREAD

**Issue by nitrif** [Microsoft/CNTK#2379]
I would like this function to be excluded during weight updates. Is that possible?
```
def Deconvolution(x, kernel, num_filters, strides, pad):
    d = ConvolutionTranspose(
        filter_shape=(kernel, kernel),
        num_filters=num_filters,
        init=bilinear(kernel,kernel),
        pad=False,
        strides=(strides, strides))(x)
    return d
```
I found this solution:
```
kernel = C.constant(value = filter)
C.convolution_transpose(kernel , x)
```
but I still just don't know how to initialize the constant with bilinear initializer.

I also tried to use freeze copy but still not managed to make it work.

Thanks,
Nikola

**Comment by sayanpa** [comment]
You can take a close look at the GAN tutorials (CNTK 206 AB). There you will be able to find how you can selectively specify the parameters your learner should update.

https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206B_DCGAN.ipynb

**Comment by nitrif** [comment]
Thanks.
