### ISSUE TITLE
How to implement image captioning?

### ISSUE THREAD

**Issue by mahehu** [Microsoft/CNTK#238]
I'm trying to port an existing Theano-based implementation of image captioning into CNTK.
I have some kind of understanding how to setup the .ndl and .cntk files, but can not figure
out which DataReader to use. Or should I write my own from scratch?

I've tried UCIReader since it seems to support image input with multiple outputs, but training ends
at segfault while reading the data. I also have the feeling that UCIReader may not be the most efficient way (takes about an hour to prepare the data).

Any help is greatly appreciated.

**Comment by nguyenquyhy** [comment]
What is the format of your input and output data?

**Comment by frankseide** [comment]
The bad news is that CNTK currently has two limitations regarding this. We are working on addressing both, but it will be a few more weeks until this functionality is available:

* You can only use one DataReader at a time, i.e. you can only process text or images, but not both at once.
* For each input sequence you can have multiple streams (e.g. audio features and labels), but they must match in length. In your case, one input has length 1 (the image) and one has length N (N=#words in the caption).

**Comment by mahehu** [comment]
Thanks _frankseide_, this clarifies the issue.
Looking forward to the new features, since CNN+LSTM is a quite slow on Theano; could use some speedup from CNTK.
