### ISSUE TITLE
C# evaluation for multi-gpu model.

### ISSUE THREAD

**Issue by edwardcho** [Microsoft/CNTK#2382]
I succeed prediction result for single-gpu model.
 -. Training : single-gpu training, python-code.
 -. Evaluation (predict) : in C# code & python-code, I got prediction results.

And,
 -. Training : multi-gpu(2-gpu) training, python-code.
 -. Evaluation (predict) : I got prediction results on python.
                                     But, I could not get prediction result on C# API.
                                     (I already made evaluation API on C#).
                                     I met some error on my C# already evaluation code.

I don't know the reason for this status.
Can you guess this reason??

**Comment by sayanpa** [comment]
Can you provide more details on the error you are getting please.

**Comment by edwardcho** [comment]
Thank you for your response.

![image](https://user-images.githubusercontent.com/29569662/30689556-38df93b6-9efc-11e7-81a2-86326ec2ad8b.png)

The context of this error is as follows:
  "The sequence has more than one element"

Thanks,

**Comment by liqunfu** [comment]
Hi @edwardcho, would you please provide exception/error message and call stack from you C# evaluation code? Perhaps debugging using Visual Studio with your C# code? The message "The sequence has more than one element" does not seems to be from CNTK code. Thanks.

**Comment by edwardcho** [comment]
Hi @liqunfu,
Do you have C# evaluation sample code for multi-GPU training model??
(I modified C# evaluation code of CNTK sample code, 
 Just modified C# eval code was operated normally about single GPU training model,
       for multi-gpu training model, this evaluation code was occurred above error.)

P.S.
if possible, do you have softmax function for evaluation, please teach it to me..

Thanks.

**Comment by liqunfu** [comment]
@edwardcho may you provide a repro code with the model used? Thanks.

**Comment by edwardcho** [comment]
Hello cha-zhang,
As you know, our source code is same to your sample source code (C#).
Using your sample code, we had used it at our prediction.

**Comment by edwardcho** [comment]
Honesty, this problem did not solve it yet.
But I should solve it next time.
Anyway I do close this issue.
