### ISSUE TITLE
Is there a shallow clone?

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/CNTK#2383]
I am loading a trained model, now I want to test each node in isolation from the rest of the graph, and so I'm using the clone(CloneMethod.clone) method, but I'm finding this recreates the entire model.  For example, when I clone the BatchNormalization layer I get the graph shown below.  So how do I clone BatchNormalization but disconnected from the parent Minus node ?

![image](https://user-images.githubusercontent.com/18707114/30629123-fa4cf5b2-9d8e-11e7-89fe-013e53e13e1e.png)

**Comment by sayanpa** [comment]
Left a response to your question on StackOverflow: https://stackoverflow.com/questions/46311945/cloning-a-cntk-node-to-test-it-in-isolation/46333146#46333146

Closing this one as a duplicate for now.
