### ISSUE TITLE
Help with error message

### ISSUE THREAD

**Issue by Prasandhmcw** [Microsoft/CNTK#2384]
I made changes in the code and it builds fine. But when I try to run Unit tests , few tests are throwing the following error. I couldn’t deduce anything from the error message. Can someone help ?

**test run command :** ./bin/mathtests --run_test=MathTensorTests/ColumnSliceMultAndAdd

**error log :** 

Running 1 test case...
unknown location(0): fatal error: in "MathTensorTests/ColumnSliceMultAndAdd": C string: Unimplemented Type
Source/../Tests/UnitTests/MathTests/TensorTests.cpp(88): last checkpoint: "ColumnSliceMultAndAdd" entry.

*** 1 failure is detected in the test module "MathTests"

Is there any general cause for this error ?

**Comment by KeDengMS** [comment]
I think this is caused by some unimplemented code path which triggered an exception. Can you run the test in gdb to get the callstack?

**Comment by Prasandhmcw** [comment]
Yes @KeDengMS , thanks for the input.
It was due to an unimplemented code. Implemented it and now the test passes.
Thanks :)
