### ISSUE TITLE
C# Training API: Correct usage of Value class with in-memory arrays in the training loop

### ISSUE THREAD

**Issue by mdabros** [Microsoft/CNTK#2386]
First off, a big thanks for releasing the C# training API - this is a great step forward for deep learning in C#. 
Using the nuget package, I believe this was the quickest installation of a deep learning framework (GPU+CPU) I have experienced on Windows. It took only minutes from starting the installation to getting  examples running on both GPU and CPU. 

I have a question regarding correct usage and disposal of the Value class, when using in-memory arrays to provide feature and label values. Below is the training loop I am currently using. For the example, I am simply using empty arrays for features and labels:

```csharp
var featuresSize = minibatchSize * inputDim.Aggregate((v1, v2) => v1 * v2);
var labelsSize = minibatchSize * numberOfClasses;

for (int i = 0; i < numberOfBatchesToUse; i++)
{
    using (var batchFeatures = Value.CreateBatch<float>(inputDim, 
new float[featuresSize], device))
    using (var batchLabels = Value.CreateBatch<float>(new int[] { numberOfClasses }, 
new float[labelsSize], device))
    {
        var miniBatch = new Dictionary<Variable, Value>
        {
            { input, batchFeatures },
            { labels, batchLabels }
        };

        trainer.TrainMinibatch(miniBatch, device);
    }
}
```

With the approach above, the memory consumption of the process rises extremly quickly (both system  and GPU memory). This leads me to believe that the Value objects are not being disposed proberly, and the memory is never freed. My hope was, that the using statements would take care of freeing the memory after each minibatch, but this does not seem to be the case. 

This is what it looks like after a few minutes, when the process stops:

![image](https://user-images.githubusercontent.com/9001637/30663087-bfbbca98-9e49-11e7-9129-0c9a0298b11b.png)

What would be the correct pattern to use, so the memory of the Value objects is freed after each minibatch?

Using the CNTK MinibatchSource (from TextFormatMinibatchSource), there are no issues and the memory consumption is very stable. But this requires the data to be processed from a text file, which is not what I am trying to achieve.

let me know if you need any additional information.

**Comment by liqunfu** [comment]
Thanks @mdabros for your comments and issue report. I experimented on both GPU and CPU with CNTK example code similar to yours. I did not observe signs of memory leak. The example code I used is TrainAndEvaluateWithAnimalData where batch data are created with C# buffers. For CPU, you may use the LogisticRegression example and set inputDim to an extra large number (I used 300000) and numMinibatchesToTrain to unlimited large to see the memory usage.

Regarding you question on how to create and disposal a Value instance. The above example code is one way of doing it. I do not see it differs from your code though. Please let us know if you are still seeing the memory leak issue.

**Comment by mdabros** [comment]
@liqunfu Thanks for looking at the problem. I still see the memory issue, but I will try to modify my code
 according to the TrainAndEvaluateWithAnimalData example. If the memory leak is still present afterwards, I will create a repository with my example, for further investigation.

**Comment by mdabros** [comment]
After rewriting my example, I believe I found the cause of the memory leak. I wrote the initial code with the intention of reusing the minibatch arrays, containing the features and the labels, across all mini-batches. Therefore, I created the arrays outside the mini-batch loop:

```csharp
var features = new float[minibatchSize * inputDim.Aggregate((v1, v2) => v1 * v2)];
var oneOfNLabels = new float[minibatchSize * numberOfClasses];

for (int i = 0; i < numberOfBatchesToUse; i++)
{
    using (var batchFeatures = Value.CreateBatch<float>(inputDim, features, device))
    using (var batchLabels = Value.CreateBatch<float>(new int[] { numberOfClasses }, oneOfNLabels, device))
    {
        miniBatch.Add(input, batchFeatures);
        miniBatch.Add(labels, batchLabels);

        trainer.TrainMinibatch(miniBatch, device);
        miniBatch.Clear();
    }
}
```

What I found during the rewrite was, that moving the creation of the arrays inside the loop removes the memory leak:

```csharp
for (int i = 0; i < numberOfBatchesToUse; i++)
{
    var features = new float[minibatchSize * inputDim.Aggregate((v1, v2) => v1 * v2)];
    var oneOfNLabels = new float[minibatchSize * numberOfClasses];

    using (var batchFeatures = Value.CreateBatch<float>(inputDim, features, device))
    using (var batchLabels = Value.CreateBatch<float>(new int[] { numberOfClasses }, oneOfNLabels, device))
    {
        miniBatch.Add(input, batchFeatures);
        miniBatch.Add(labels, batchLabels);

        trainer.TrainMinibatch(miniBatch, device);
        miniBatch.Clear();
    }
}
```

My guess is that the Value objects, in the first example, are not being disposed after each mini-batch because they each have a reference to an array created outside the mini-batch loop/scope. 

@liqunfu, please let me know if you can confirm the behavior. 

From the documentation of the [value class](https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-library-managed-api#class-value), it states that the Value class holds a copy of the batch, so I would not expect a reference to the array.

**Comment by liqunfu** [comment]
@mdabros, could it be that .net GC failed to release memories promptly? I expect both your codes work without memory leak. I also constructed a CNTK C# example to be the same as yours in terms of buffer allocation. No memory issue was observed. 

BTW, may you remove the 2 'using's to see what happens?

Nevertheless, thank you so much for getting the tip above so we will keep this in mind once similar things happen.

**Comment by mdabros** [comment]
@liqunfu It might have been the .net GC that failed to release memory in time, because of excessive load on the process. 

Under all circumstances, I am now having troubles reproducing the issue myself, so I guess it must have been a combination of my setup/code and the .net GC. I will close the issue and reopen it again if the problem reappears - and if I can recreate it properly.

Thanks for taking the time to look in to the issue
