### ISSUE TITLE
No module named 'cntk.learner' !

### ISSUE THREAD

**Issue by farshidfaal** [Microsoft/CNTK#2387]
Hi,

I have installed CNTK properly (Anaconda envs) but I have received this error. Does anybody know how can I fix this issue?

Thanks

**Comment by n17s** [comment]
The learner module was at some point renamed to learners. Are you getting this error after you import cntk or during the import?

**Comment by farshidfaal** [comment]
Yes, the name of the module has been changed in v2.2. There are some modules that renamed or deleted from v2.0.
Thanks
