### ISSUE TITLE
update v2.0 to v2.2

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#2394]
I have implemented several projects with cntk version 2.0 and would like to update it to v2.2

It seems like some modules in v2.0 are renamed or deleted, and programs written in v2.0 are not fully compatible with v2.2. How can I deal with this problem?

**Comment by n17s** [comment]
Can you list some issues not covered by the breaking changes section of 2.2 release notes or 2.1 release notes?

**Comment by cha-zhang** [comment]
Close due to lack of response. The breaking change in v2.2 is not big, hope this has been resolved.
