### ISSUE TITLE
How to use Dropout during test stage ?

### ISSUE THREAD

**Issue by xiangyang3131777** [Microsoft/CNTK#2395]
Now, I'm training an GAN under the  python environment and I also want to
use the dropout strategy during the test stage.  What should I do ?

**Comment by n17s** [comment]
First you should look into the `cntk.random` module. These operations work the same way during training and testing. If you really really want to use dropout during testing, you need to call Function.forward manually and specify the `keep_for_backward` argument. e.g. 
```python
>>> model.forward(arg_to_value_map, keep_for_backward={model.output})
```

**Comment by xiangyang3131777** [comment]
Ok~
Thanks.

**Comment by sayanpa** [comment]
Closing this issue as the user is satisfied with the answer.
