### ISSUE TITLE
[Keras CNTK Backend] Force CPU Usage?

### ISSUE THREAD

**Issue by moderato** [Microsoft/CNTK#2396]
As the title says. My CNTK library is the (not 1-bit) "GPU" version. Is there any way to force it to run on CPU? Thanks!

**Comment by sayanpa** [comment]
If you install the CNTK with the CPU wheel. Have you tried it?

**Comment by moderato** [comment]
@sayanpa Not yet. I am just wondering if the GPU version can also run on CPU?

**Comment by sayanpa** [comment]
CNTK code can be run using CPU only. https://cntk.ai/pythondocs/cntk.device.html

**Comment by moderato** [comment]
Thanks! I create another virtual env in conda and install the CPU version for running CPU.
