### ISSUE TITLE
Perform calculations with the weights of a network

### ISSUE THREAD

**Issue by FlashTek** [Microsoft/CNTK#2397]
I am trying to perform arithmetical operations (adding them and multiplying with a scalar ) on all weights of a network using the C++ API. Are there builtin functions to do this internally? Or do I have to copy the CNTK Variables into a vector, manipulate the values and copy them back in the CNTK Variables? I didn't find anything like this in the `CNTKLibrary.h` header, but as I think this are often used functions, they are somehow implemented and available.

Edit: After searching deeper in the source I found the `GetWritableMatrix()` function of the `NDArrayView` class. I thought about using this function to get a writable matrix and then manipulating the values, but sadly this function is not accessible from outside CNTK.

**Comment by KeDengMS** [comment]
You can directly write a computation graph for that.

    >>> import cntk as C
    >>> i = C.input_variable((100,))
    >>> s = C.layers.Dense(10)(i)
    Selected GPU[0] GeForce GTX TITAN X as the process wide default device.
    >>> sum_p = C.reduce_sum(s.parameters[0])
    >>> import numpy as np
    >>> s.eval(np.random.random((10,1,100)).astype(np.float32))
    array([[ 0.96850383,  0.05426806,  0.07375737,  0.21046795, -0.60679317,
        -0.4193784 , -0.24891996,  0.02988207,  0.47455996,  0.9116745 ],
       [ 0.86395949,  0.22516164, -0.11292253, -0.61354494, -0.232894  ,
        -0.03626699, -0.07986298,  0.55146879,  0.7585184 ,  1.88231134],
       [ 0.34711072,  0.28432426, -0.07297415, -0.76703954, -0.42738259,
         0.22043896,  0.43316871,  0.68356943,  0.71169794,  0.67848241],
       [ 0.81426835,  0.06239885,  0.59192491,  0.1534645 , -0.70907152,
        -0.82767296,  0.27000698,  0.26197743,  0.7435028 ,  1.49762082],
       [ 0.93432271, -0.43630743,  0.019588  ,  0.00751555, -0.30872929,
        -0.57923961,  0.45348221,  0.85443127,  0.85994494,  0.69052649],
       [ 0.7246964 ,  0.44331193,  0.37661678,  0.40484929, -0.81032848,
         0.44266534,  0.54666305,  0.51827741,  0.20115951,  1.08815145],
       [ 0.32413885,  0.04873306,  0.08818904, -0.40387976, -0.93096185,
         0.60214263,  0.25194627, -0.05843592,  0.6050424 ,  1.02575767],
       [ 0.8397367 , -0.62741178, -0.32376444, -0.10334891, -0.45171097,
        -0.24060762, -0.03991115,  0.0779331 ,  0.02998854,  1.29471672],
       [ 1.03352439,  0.72337896, -0.18992905,  0.15383869, -1.38782907,
         0.03663242, -0.22149426,  0.29517931,  0.10454711,  1.52526987],
       [ 0.82627934,  0.43256921,  0.89353228, -0.29696023, -0.54298723,
         0.10828025, -0.31245437,  0.07333556,  0.38145417,  1.23514354]], dtype=float32)
    >>> sum_p.eval()
        array(3.5534510612487793, dtype=float32)

**Comment by FlashTek** [comment]
@KeDengMS I do not see how this is anyhow related to my question. On the one hand you are using `python` and on the other hand you are not performing any calculations with the weights of the layers.

**Comment by KeDengMS** [comment]
The python code is for illustration. The weights are called parameters in CNTK, and the code above uses CNTK graph sum_p to compute the sum of the weights in the dense layer. You can do similar things in C++.

**Comment by cha-zhang** [comment]
@FlashTek has your issue been resolved?

**Comment by mx-iao** [comment]
Closing due to no follow up, please reopen if you have further questions.
