### ISSUE TITLE
Incorrect settings for Visual Studio 2015

### ISSUE THREAD

**Issue by VictorJL** [Microsoft/CNTK#24]
Include directories shall point to $(WindowsSDK_IncludePath) for the proper architecture, 10, in this case, 8-8.1?, include directories with the VC++ additional include directories option are the best for doing so.

Project does not compile with Visual Studio 2015 and Windows 10 unless directories are fixed, (ctype.h, include errors, etcetera). 

Also, a nice README about CUDA, ACML and MPI would come in handy.

**Comment by mahilleb-msft** [comment]
Hi Victor,

  we are still on VS2013 at this time. Regarding a README, can you take a look here https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-your-machine and see if it has the information you're looking for?

  Thanks, Mark

**Comment by VictorJL** [comment]
Hi Mark. 

Yes. That is excellent. 

Best.

**Comment by mahilleb-msft** [comment]
Hi Victor,

  I've made VS2015 support a separate issue, #33, closing this one here.

  Thanks, Mark
