### ISSUE TITLE
required parameter missing: LR.cntk:Train:reader:labels:labelMappingFile

### ISSUE THREAD

**Issue by ningningG** [Microsoft/CNTK#240]
```
labels = [
    start = 2
    dim = 1
    labelType = regression
]
```

I have set the labelType = regression,why this error occurred?

**Comment by dongyu888** [comment]
Are you using the most recent master version or the pre-built binary? It should work with the current master branch.

**Comment by ningningG** [comment]
Yes,I use the CNTK Binary : CNTK-2016-02-08-Windows-64-bit-CPU-Only.The .cntk configuration file is the example(binary classification using the linear model Logistic Regression) in tutorial.

**Comment by ningningG** [comment]
Yes,I use the CNTK Binary : CNTK-2016-02-08-Windows-64-bit-CPU-Only.The .cntk configuration file is the example(binary classification using the linear model Logistic Regression) in tutorial. @dongyu888

**Comment by ningningG** [comment]
[LR.txt](https://github.com/Microsoft/CNTK/files/177934/LR.txt)
[Test.txt](https://github.com/Microsoft/CNTK/files/177933/Test.txt)
[Train.txt](https://github.com/Microsoft/CNTK/files/177932/Train.txt)
 The configuration file and data are here.

**Comment by dongyu888** [comment]
Yes, that binary does not have the fix. You will need to build a binary using the current master branch.
