### ISSUE TITLE
Custom loss functions in C#

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#2404]
Hi,
I am trying to use C# for learning and I hit a problem: writing own loss functions. 
In Python I could do e.g.
def sMAPELoss (forces, actuals):
  loss=o.reduce_mean(o.abs(actuals-forces)/(actuals+forces))*200
  return loss

But how to do it in C#? I imagine writing the function specification as
static CNTK.Function sMAPELoss(CNTK.Function forecs, CNTK.Variable actuals)
but how do I the basic things like calculating the difference: forces-actuals?

Thanks,
Slawek

**Comment by slaweks17** [comment]
Well, it turned out that I can use CNKLib functions on both functions and variables, e.g.
CNTK.CNTKLib.Abs(CNTK.CNTKLib.Minus(forecs, actuals))
so it can be done, at least it compiles.
I have not tested it fully yet, due to some unrelated problems, but I will close the issue now.

**Comment by IvoTops** [comment]
@slaweks17 Hi. I am trying to figure out how to do L1 or L2 regularization with a custom loss function. Any ideas?

**Comment by slaweks17** [comment]
Hi,
This is more complicated - you have to access the weights. 
I have abandoned the C# interface for the moment, as it is not useable for me, so I am not sure, but did you check what learning algorithms C# supports? Because almost every learner in Python has ability to specify L1 and L2 losses.

Regards,
Slawek

**Comment by IvoTops** [comment]
Many learners are available in C#. Adam, Adadelta, MomentumSGD and more

Op 3 dec. 2017 19:03 schreef "slaweks17" <notifications@github.com>:

**Comment by mdabros** [comment]
In case you haven't found a solution to specify L1 and L2 regularization, this can be done for all learners in C# by specifying the values on the `AdditionalOptions` argument. For instance

```csharp
var options = new AdditionalLearningOptions();
options.l1RegularizationWeight = 0.001;
options.l2RegularizationWeight = 0.01;

var learner = CNTKLib.AdamLearner(..., options);
```
best regards
Mads
