### ISSUE TITLE
C#: How to create batch of sequences of vectores?

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#2405]
Hi,
I am trying to write a program for time series forecasting in C#. So, I have a number of time series, that originally are sequences of float values, but after preprocessing, every point from a time series gets converted to a vector input and a vector output, so e.g. inputs of a single time series are sequences of float point vectors.
From what I can gather, to execute training, I need to convert my data into CNTK.Value. I tried to use
CNTK.Value.CreateBatchOfSequences<float[]>(ndshape, batchOfInputs, device);
where batchOfOutputs is List<List<float[]>>, so it is a mini_batch_size-long list of time series objects, each being a list of float vectors), but while it compiles, during execution exception appears saying that only simple float or double values are supported, not arrays.

Another path, through
ndArrayView=CNTK.NDArrayView(ndshape, dataBuffer, device);
value=new CNTK.Value(CNTK.NDArrayView data);
is perhaps possible, but here dataBuffer needs to be flattened float[], while my tensor is 3d (batch, sequence, input_size), so it is ugly and cumbersome.

Any help will be appreciated.
Slawek

**Comment by liqunfu** [comment]
CNTK.Value.CreateBatchOfSequences only accepts float or double as the template parameter. For number of time series, you may use CreateBatch. See TransferLearning for example. Or CreateBatchOfSequences.

**Comment by slaweks17** [comment]
Hi,
Thank you for your prompt answer.
CreateBatch - I will try to use it, but it is exactly this clumsy and ugly way I was talking about: I need to squash my 3d irregular tensor to a vector. Keep in mind that the series differ in length, so the second dimension varies. Is it possible at all?
I would suggests that CreateBatchOfSequences should be able to take float[]. In Python there are no issues like this one.

What did you mean by "Or CreateBatchOfSequences"?

Regards,
Slawek

**Comment by liqunfu** [comment]
I removed my typo of "Or CreateBatchOfSequences" from my previous comment. 
Have you looked at example of using EvaluationBatchOfSequencesUsingOneHot at https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CNTKLibraryCSEvalCPUOnlyExamples/CNTKLibraryCSEvalExamples.cs?

**Comment by liqunfu** [comment]
@slaweks17 there are some APIs at [ValueShim.cs]. Did you try them to see how it goes?(https://github.com/Microsoft/CNTK/blob/master/bindings/csharp/CNTKLibraryManagedDll/ShimApiClasses/ValueShim.cs)
I am closing this issue for now until your further queries.

**Comment by slaweks17** [comment]
Hi,
From what I can see nothing changed, the APIs are the same. I still can't create a sequence of float[]. And keep in mind each sequence in batch is likely to have a different size. How can I do it?
