### ISSUE TITLE
What is the format of image-mean for training/evaluation??

### ISSUE THREAD

**Issue by edwardcho** [Microsoft/CNTK#2406]
At first,
I tested same cases for my data on CNTK.
 1. Training python using image-net_mean, evaluation using image-net mean.
 2. Training python, using 128-mean, evaluation using 128-mean.
   (The 128-mean, we made this file that all field replaced 1.28e+02 on image-net_mean for testing.)
 Our data format is 3-channel of R,G,B.

In my cases,
 The evaluation accuracy of CASE2 is better than it of CASE1.
 Honesty, I can not understand this result. 
 Can you guess the reason of this result??

And, I found generating function for mean-file.
(https://stackoverflow.com/questions/41654814/how-to-compute-image-mean-for-a-set-of-image-files)
How to use it for my data-set??

P.S. Do you know the format of mean-file?? 
      How to generate the mean-file for my data-set??

**Comment by cha-zhang** [comment]
Check this file: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/DataSets/CIFAR-10/cifar_utils.py 
to see how to save mean. 

CASE 1 and 2, it really depends on the data. I expect the difference is small.

**Comment by edwardcho** [comment]
Hi, cha-zhang,
According to your code, I will change my-code and I will do re-training for my-dataset.

Thanks.
