### ISSUE TITLE
Error running training on a simple file: "label found in data not specified in label mapping file"

### ISSUE THREAD

**Issue by DavidRooney** [Microsoft/CNTK#241]
I am very new to all this and probably way over my head. i am trying to train a network on some data and I get the error "label found in data not specified in label mapping file". This is a personal project and In a nutshell I want to train a network to tell me if a course is a computing course based on the course name, department and institution. 

Any help is greatly appreciate as I am stumped. Hopefully it is a quick and easy fix!

**Example of a row in the data file:**
1;  116006; School Direct (Tuition Fee): Computing with IT; Institute of Education; UCL - University College London;

**Mapping data file:**
0
1

**Error message exactly:**
EXCEPTION occurred: label found in data not specified in label mapping file: School
[CALL STACK]
    > Microsoft::MSR::CNTK::UCIFastReader<float>::  GetMinibatchImpl
    - Microsoft::MSR::CNTK::UCIFastReader<float>::  GetMinibatch
    - Microsoft::MSR::CNTK::DataReader::  GetMinibatch
    - Microsoft::MSR::CNTK::DataReaderHelpers::GetMinibatchIntoNetwork<float>
    - Microsoft::MSR::CNTK::SGD<float>::  PreCompute
    - Microsoft::MSR::CNTK::SGD<float>::  TrainOrAdaptModel
    - Microsoft::MSR::CNTK::SGD<float>::  Train
    - DoTrainMicrosoft::MSR::CNTK::ConfigParameters,float
    - DoCommands<float>
    - wmainOldCNTKConfig
    - wmain1
    - wmain
    - __tmainCRTStartup
    - BaseThreadInitThunk
    - RtlUserThreadStart

**CNTK File (This is basically a copy of the Simple2d example):**
RootDir = ".."

ConfigDir = "$RootDir$/Config"
DataDir   = "$RootDir$/Data"
OutputDir = "$RootDir$/Output"
ModelDir  = "$OutputDir$/Models"

GPU is available
deviceId = -1

command = Example_Train:Example_Test:Example_Output

precision = "float"
traceLevel = 1
modelPath = "$ModelDir$/example_model"
outputNodeNames = ScaledLogLikelihood
###### 
# TRAINING CONFIG
###### 

Example_Train = [
    action = "train"

```
SimpleNetworkBuilder = [
    layerSizes = 2:50*2:2
    trainingCriterion = "CrossEntropyWithSoftmax"
    evalCriterion = "ErrorPrediction"
    layerTypes = "Sigmoid"
    initValueScale = 1.0
    applyMeanVarNorm = true
    uniformInit = true
    needPrior = true
]

SGD = [
    # epochSize = 0 means epochSize is the size of the training set 
    epochSize = 0 
    minibatchSize = 25  
    learningRatesPerMB = 0.5:0.2*20:0.1
    momentumPerMB = 0.9
    dropoutRate = 0.0
    maxEpochs = 10
]

# Parameter values for the reader
reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/computing_train_data.txt"
    customDelimiter = ";"
    randomize="auto"
    verbosity = 1

    features = [
        dim = 4 should be in the first or last column
        start = 1
    ]

    labels = [
        dim = 1
        start = 0 
        labelDim = 2 
        labelMappingFile = "$DataDir$/data_mapping.txt"
    ]
]
```

]
###### 
# TEST RESULTS
###### 

Example_Test = [
    action = "test"

```
reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/test_data.txt"
    randomize = "auto"  

    features = [
        dim = 4
        start = 1
    ]

    labels = [
        dim = 1
        start = 0
        labelDim = 2
        labelMappingFile = "$DataDir$/data_mapping.txt"
    ]
]
```

]
###### 
# OUTPUT RESULTS
###### 

Example_Output=[
    action = "write"

```
reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/test_data.txt"
    randomize = "auto"

    features = [
        dim = 4
        start = 1
    ]

    labels = [
        dim = 1
        start = 0
        labelDim = 2
        labelMappingFile = "$DataDir$/data_mapping.txt"
    ]
]

outputNodeNames = PosteriorProb : labels 

outputPath = "$OutputDir$/Output" 

format = [
    type = "category"                                
    labelMappingFile = "$DataDir$/data_mapping.txt" 
    sequenceEpilogue = "\t// %s\n"                   
]
```

]

**Comment by DavidRooney** [comment]
After a little reading I think I need to change the data so it is normalized and not just some pieces of text with a 1 or a 0 associated to it. Like i said, maybe I'm in over my head and just jumping straight in instead of doing general research about AI.

**Comment by mradmila** [comment]
Thanks David. We will work on updating our instructions, especially on the reader side.

**Comment by pkranen** [comment]
Readers and documentation hve been updated. Please try the latest bits, thanks.
