### ISSUE TITLE
[C#] DoubleVector's (FloatVector's etc) constructor takes non-generic ICollection. It should take IEnumerable<double> instead

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#2412]

**Comment by liqunfu** [comment]
DoubleVector, FloatVector and many other classes in CNTK\bindings\csharp\CNTKLibraryManagedDll\SwigProxyClasses\ are generated by swig. We are cleaning up code in ShimAPIClasses to hide these generated class from client code.
