### ISSUE TITLE
SSL verification error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by RenanRosa** [Microsoft/CNTK#2415]
I am trying to install CNTK with the script driven setup.
But i am getting the following error:

 'start-process C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts\conda.exe env create --file "C:\Users\Renan\Downloads\CNTK-2-2-Windows-64bit-CPU-Only\cntk\Scripts\install\windows\conda-windows-cntk-py36-environment.yml" --prefix "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py36"' failed with exit code [1]

if i try to execute the command below, the message "SSL verification error: [Errno 2] No such file or directory" appears.
C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts\conda.exe env create --file "C:\Users\Renan\Downloads\CNTK-2-2-Windows-64bit-CPU-Only\cntk\Scripts\install\windows\conda-windows-cntk-py36-environment.yml" --prefix "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py36"

**Comment by liqunfu** [comment]
Not sure what was causing this. Did you check whether those folder/files exist? As a work around, you may create another anaconda env with the follow these steps:
conda create -n cntk36 python=3.6 anaconda
activate cntk36
conda env update --file CNTK\Scripts\install\windows\conda-windows-cntk-py36-environment.yml --name cntk36 
pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.2-cp36-cp36m-win_amd64.whl
