### ISSUE TITLE
C# Web SEHException (0x80004005): An external component has an exception In CNTK2.2

### ISSUE THREAD

**Issue by whaozl** [Microsoft/CNTK#2417]
```
[SEHException (0x80004005): An external component has an exception(外部组件发生异常)。]
   CNTK.CNTKLibPINVOKE.Function__Load__SWIG_0(String jarg1, HandleRef jarg2) +0
   CNTK.Function._Load(String filepath, DeviceDescriptor computeDevice) +75
   DeepProject.DicosCNTK.EmotionS2SModel..ctor(String modelFilePath, String embeddingFilePath, Boolean IsGPU) in C:\DeepProject_Test\DeepProject.DicosCNTK\EmotionS2SModel.cs:26
   DeepProject.TestCNTK.Models.IsobarCenter..ctor() in C:\DeepProject_Test\DeepProject.DicosCNTK\Models\AnjCenter.cs:22
   DeepProject.TestWeb.RouteConfig..cctor() in C:\DeepProject_Test\DeepProject.TestWeb\App_Start\RouteConfig.cs:24
```
How to solve this problem?

**Comment by liqunfu** [comment]
@whaozl May I have this Model you are loading. Does it happen each time you load any model?
How comes it has to do with Web?

**Comment by whaozl** [comment]
@liqunfu I have solve this prolem, The reason is that cntk-dll has not been loaded. Thank you very much.

**Comment by oridayne** [comment]
Can you guys clarify what you mean by that the cntk-dll has not been loaded? I've made sure to manually add all the dlls as specified in this: https://github.com/Microsoft/CNTK/issues/2903
I'm pretty sure all the dlls are loaded, since I stopped getting those errors mentioned in that github post.

**Comment by whaozl** [comment]
@oridayne yeah, I add this path of cntk.dll to PATH of SYSTEM.
