### ISSUE TITLE
Checking time duration of the whole process

### ISSUE THREAD

**Issue by kyoro1** [Microsoft/CNTK#2420]
Occasionally, we need to measure how many minutes/hours it took in executing time, because it takes very long to train with CNTK scripts.

So, can we use it easily? With `python`, we use `datetime` library and here is a simple work-around to do it:

```py
import datetime
 :
start = datetime.datetime.now()
## main training process
## train()
## evaluate() etc...
end = datetime.datetime.now()
difference = end - start
print(difference)
```

It is bothersome to write this kind of codes for each script, and can we get them as common function/method in CNTK?

**Comment by n17s** [comment]
This kind of functionality is not specific to CNTK so I suggest you have a utils.py that contains things like this timing utility  
http://dabeaz.blogspot.com/2010/02/context-manager-for-timing-benchmarks.html
Then you just import it in your scripts and use it.

**Comment by kyoro1** [comment]
OK, I see. Close this item.
