### ISSUE TITLE
Python APIs: Bug in the Adam Optimizer description?

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#2421]
Hi,
https://www.cntk.ai/pythondocs/cntk.learners.html#cntk.learners.adam
lists parameters of the Adam optimizer. 
It says:
"momentum (float, list, output of momentum_schedule())  - momentum schedule. Note that this is the beta1 parameter in the Adam paper"
but then also:
"variance_momentum (float, list, output of momentum_schedule() or momentum_as_time_constant_schedule()) - variance momentum schedule. Note that this is the beta1 parameter in the Adam paper"
Probably you meant beta2, right?

Slawek

**Comment by n17s** [comment]
Yes you are right.

**Comment by tangyuq** [comment]
@slaweks17  Thank you for spotting the docstring error. I've corrected it in the latest master.
