### ISSUE TITLE
How could I find the cntk.tests.test_utils from the Python API for CNTK?

### ISSUE THREAD

**Issue by CalmDownForever** [Microsoft/CNTK#2428]
When I run the code of 'CNTK 103: Part B - Logistic Regression with MNIST' 
It says:
Traceback (most recent call last):
  File "logistic_regression.py", line 10, in <module>
    import cntk.tests.test_utils
  File "/usr/local/lib/python2.7/dist-packages/cntk/tests/test_utils.py", line 13, in <module>
    import pytest
ImportError: No module named pytest

So , how could I deal with it?

**Comment by cha-zhang** [comment]
Have you tried install pytest?

**Comment by CalmDownForever** [comment]
I got over it.
I think cntk has many ways to one problem which confusing me a lot.

**Comment by cha-zhang** [comment]
Sorry for the confusion. Let us know if you have more suggestions. Closing this issue for now.
