### ISSUE TITLE
Tutorial2 issues with CNTK-2016-02-08-Windows-64bit-CPU-Only.zip binary install

### ISSUE THREAD

**Issue by ScottSquash** [Microsoft/CNTK#243]
While 01_OneHidden runs properly using the binary install, 02_Convolution fails with the error "EXCEPTION occurred: ImageParameter should have 3 parameters [width, height, numChannels]."

Do I need to build CNTK from the latest source in order to run Tutorial2 without errors?

FYI: In order to run the first tutorial, I needed to add: labelMappingFile = "$DataDir$/SimpleMapping.txt." I suspect this is because I am using the older binary install.

**Comment by ScottSquash** [comment]
I was able to run the example from February 9 on GitHub with the current binary. It was rather frustrating that basic tutorials did not run properly with the suggested binary download. You can close this issue.

**Comment by ScottSquash** [comment]
Can you please post the latest binaries more frequently? The binaries from February 8 do not work with several of the examples and I would like to create a regression network with multiple outputs without having to build the binaries from source.

**Comment by mradmila** [comment]
@alexeyo26 Alexey, can you please check if it is possible to increase our binary release cadence?

**Comment by ScottSquash** [comment]
I finally broke down and built CNTK from source. Both examples from Tutorial 1 run properly. The first example from Tutorial 2 runs properly. When I run the Convolution example in Tutorial 2, I get an exception:

EXCEPTION occurred: Default convolution engine currently supports only HWC/legacy layout.
