### ISSUE TITLE
Gradient backprop through cntk.ops.greater

### ISSUE THREAD

**Issue by nitrif** [Microsoft/CNTK#2443]
Is gradient back-propagated through very non linear layers such as cntk.ops.greater? I want to test some GAN setups and I am not sure whether some of them will work.

Thanks,
Nikola

**Comment by n17s** [comment]
It is not. In general, if the function is discontinuous and/or constant almost everywhere, we don't backprop (the only exception is lambda_rank). 

If you want to have an operation g(x) which in the forward pass acts like f(x) and in the backward acts like the backward of b(x) you can do
```python
def g(x):
    return C.stop_gradient(f(x)-b(x))+b(x) 
```

**Comment by nitrif** [comment]
Thank you Nikos.
Could you please comment if the same applies for cntk.ops.argmax?

**Comment by n17s** [comment]
Sorry for the delayed response, I just saw this. Yes the same applies for argmax.
