### ISSUE TITLE
evaluation performance issue for faster r-cnn on python GPU

### ISSUE THREAD

**Issue by enhulu** [Microsoft/CNTK#2444]
I trained a faster r-cnn model with vgg16 + pascal. Then I try to evaluate the model with python GPU and noticed that it took around 20 seconds to get results from the following two lines.
    regressed_rois, cls_probs = od.evaluate_single_image(trained_model, img_path, cfg)
    bboxes, labels, scores = od.filter_results(regressed_rois, cls_probs, cfg)
I am using GPU is GTX960 with SSD on Xeon E5-2620 CPU with 32GB RAM.
I was wondering if there are any setup tips I missed?

**Comment by enhulu** [comment]
Using GPU implementation of non-maximum suppression (__C.USE_GPU_NMS = True) does not help either...

**Comment by enhulu** [comment]
And according to NVidia-smi, it is using GPU for computing while evaluating an image...

**Comment by cha-zhang** [comment]
20 seconds is a bit extreme. We will investigate this.

**Comment by enhulu** [comment]
thanks for investigating this, my OS is win10

**Comment by spandantiwari** [comment]
Are you still seeing 20 second evaluation on a single image? If you are, please reopen this issue and share some details such as the image you are using for evaluation, and if possible, the trained model that you are using.
