### ISSUE TITLE
Unhelpful message when calling Evaluate

### ISSUE THREAD

**Issue by cesarsouza** [Microsoft/CNTK#2453]
I am trying to evaluate a somewhat simple model, but that has been created using a bit of a complicated process. When calling:
```
Evaluate(input_dict, output_values, DeviceDescriptor.CPUDevice);
```

I am getting the exception:

> System.ArgumentOutOfRangeException: 'Reshape66 Reshape operation: Input (sub-)dimensions [13 x 1] incompatible with desired (sub-)dimensions [**18446744073709551613**]. Number of elements must be the same.
> 
> [CALL STACK]
>     > CNTK::Dictionary::  ~Dictionary
>     - CNTK::Dictionary::  ~Dictionary (x2)
>     - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
>     - CNTK::Dictionary::  ~Dictionary
>     - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
>     - CNTK::Function::  Forward
>     - CNTK::Function::  Evaluate
>     - CSharp_CNTK_Function__Evaluate__SWIG_0
>     - 00007FF813F31A4E (SymFromAddr() error: The specified module could not be found.)
> 

I am still trying to debug the issue, attempting to find more information about the problem and maybe post a reproducible test case here. However, there is clearly an issue with the debug message, or at least with some field being left uninitialized in CNTK such that it would believe that a reshape to 18446744073709551613 dimensions would even be possible.

I might update this issue with more details in the future, but any insights into debugging this issue would also be welcome (is there any way to detect where and when an operation called "Reshape66" would have been created?)

Regards,
Cesar

**Comment by cesarsouza** [comment]
So, it seems that this can happen if one variable in the graph happened to be created along the lines of
```
C.Reshape(x, NDShape.CreateNDShape(new[] { -3 }))); 
```
Naturally, this -3 came from a shape specification using NDShape.FreeDimension. Possibly CNTK could either validate the inputs of NDShape, or identify that the reshape operation is not trying to reshape it to 18446744073709551613, but instead notify that reshaping an array with only ```FreeDimension```s is illegal.

**Comment by cha-zhang** [comment]
You are using free static axis in the model? Is this C#?

**Comment by cesarsouza** [comment]
Hi @cha-zhang,

Thanks for the reply. Yes, it is C#. I was trying to convert some Python code to C#, and at some point my conversion code had passed a ```NDShape.FreeDimension``` to a reshape operation in the middle of the graph, which caused CNTK to raise the above exception when calling the Evaluate function.

I guess that passing a FreeDimension to a reshape operation could have been a mistake on my part. I am not completely sure yet about the real differences between a FreeDimension (-3) and InferredDimension (-1), and whether there are any other special values that can be passed to a shape besides those.

However, the actual problem that I wanted to report in this issue is about the generated error message. It is telling me that some reshape operation was trying to reshape a tensor to 18446744073709551613 dimensions, which is not true. In fact, what happened is that some of the reshape operations in the middle of the graph had a -3 in the shape specification, and it seems that this was an illegal operation.

If I remember correctly, the reshape operation was being used to remove all the extra dimensions after a ReduceMean operation in order to reduce the result to a scalar.

**Comment by liqunfu** [comment]
@cesarsouza may you give us a short repro in C#?
I did this:
var x = CNTKLib.InputVariable(new int[]{ 10, 10, 2 }, DataType.Float, "input");
Function model = CNTKLib.Reshape(x, new int[] { NDShape.FreeDimension});
which gave:
Additional information: NDShape::TotalSize: TotalSize cannot be determined for a NDShape '[*]' with one or more dimensions being InferredDimension or FreeDimension.
