### ISSUE TITLE
object detection used CNTK with FastRCNN run own data problem (windows platform, python 3.5)

### ISSUE THREAD

**Issue by sanamjan328** [Microsoft/CNTK#2457]
i depend on Microsoft CNTK  with FastRCNN used object detection guideline, i couldn't get result 
![1](https://user-images.githubusercontent.com/20106816/31283340-f617a38e-aabd-11e7-9f6c-68e3070c4575.png)

**Comment by cha-zhang** [comment]
Have you tried the example with the grocery dataset?

**Comment by sanamjan328** [comment]
HI Dear Cha Zhangi hope you doing well
i tried with grocery dataset, and result for it is successful. here problem is dataset, which i used my own dataset to perform CNTK with Fast-RCNN. unfortunately, result is 0. i was following CNTK with Fast-RCNN documentation, which provided by Microsoft. also i was create and setup my dataset following this document. i really cant solve this problem until now. if possible could you help me solve this problem? i will so happy and so appreciate with you kinds. 

I appreciate your kind consideration and look forward to the result
best regardssanam
 
 

    On Tuesday, October 10, 2017, 7:24:48 AM GMT+3, Cha Zhang <notifications@github.com> wrote:  
 
 
Have you tried the example with the grocery dataset?

**Comment by cha-zhang** [comment]
@sanamjan328 Which CNTK version are you using?

**Comment by sanamjan328** [comment]
CNTK 2.2, windows 8.1, python3.5
    On Friday, October 20, 2017, 6:48:53 AM GMT+3, Cha Zhang <notifications@github.com> wrote:  
 
 
@sanamjan328 Which CNTK version are you using?

**Comment by cha-zhang** [comment]
Do you have anything we can take a look? It's impossible to find out the issue without seeing what you are training with.

**Comment by ajaysharmahcl** [comment]
Have you annotated the image (to generate the ROI and labels) data set before running evaluation model on custom data set ?

**Comment by spandantiwari** [comment]
@ajaysharmahcl  - yes, you need to annotate the images for your own custom dataset.
