### ISSUE TITLE
Specified GPU device id (0) is invalid.

### ISSUE THREAD

**Issue by Yogurt928** [Microsoft/CNTK#2460]
Hi,
I installed cntk2.2 GPU version with environment Anaconda3-4.1.1.

I try to set the gpu as the defalut device:
C:\>python -c "import cntk as C; C.device.try_set_default_device(C.device.gpu(0)) "
but get the error: 
ValueError: Specified GPU device id (0) is invalid.

I tried to see the device list by using:
C:\>python -c "import cntk; cntk.logging.set_trace_level(2); cntk.all_devices()"
And I can get the gpu info:

 --------------------------------------
GPU info:

                Device[0]: cores = 448; computeCapability = 2.0; type = "Tesla S2050"; total memory = 2637MB; free memory = 2637 MB
                Device[1]: cores = 448; computeCapability = 2.0; type = "Tesla S2050"; total memory = 2637MB; free memory = 2637 MB
 ----------------------------------------

It seems that 0 is one of the GPU device id?But why did I get the above error ?How can I get the right id?

Thanks in advance.

**Comment by mrcabellom** [comment]
You can print the device descriptor of your GPU's using this script. Then you can use it to set the default device  `C.device.try_set_default_device(C.device.gpu(_default_device_id_))`

Take into account check the device type, in this case we are only showing the id of GPU's

`from cntk import device
    for dev in device.all_devices():
        if dev.type() == device.DeviceKind.GPU:
            print(dev.id())
`
Regards

**Comment by Yogurt928** [comment]
Thanks for your reply!
I tried the code:
------
import cntk as C
from cntk import device

C.logging.set_trace_level(2)
C.all_devices()

for dev in device.all_devices(): 
	print('dev-s')
	print(dev.type())
	print('dev-e')
	if dev.type() == device.DeviceKind.GPU: 
		print(dev.id())
------
But I just get one dev.id:

C:\>python test2.py
-------------------------------------------------------------------
GPU info:

                Device[0]: cores = 448; computeCapability = 2.0; type = "Tesla S2050"; total memory = 2637MB; free memory = 2637 MB
                Device[1]: cores = 448; computeCapability = 2.0; type = "Tesla S2050"; total memory = 2637MB; free memory = 2637 MB
-------------------------------------------------------------------
dev-s
0
dev-e

Is there any other thing I should try?Thanks!

**Comment by mrcabellom** [comment]
Is true the condition of check the GPU type? I can not see the print statement id in your output. I only see 

dev-s
0
dev-e

and 0 is the type od device, that in this case is CPU

**Comment by Yogurt928** [comment]
@mrcabellom 
Thanks for reply.
There is just one element in the return of device.all_devices(), so it just print one record as:
dev-s
0
dev-e
Because 0 is the CPU, it is not equal to device.DeviceKind.GPU, so there is no output dev.id()
Sorry for the wrong indented format in last reply, it should be like:
`import cntk as C
from cntk import device

C.logging.set_trace_level(2)
C.all_devices()

for dev in device.all_devices(): 
	print('dev-s')
	print(dev.type())
	print('dev-e')
	if dev.type() == device.DeviceKind.GPU: 
		print(dev.id())`

And I also tried to print the dev.id() directly:
`
for dev in device.all_devices(): 
	print(dev.id())
`
Just get a "0".

**Comment by mrcabellom** [comment]
It seems that device.all_devices() only detect the CPU. Are you using the last cntk version with GPU? I had a similar problem and I reinstalled cntk again.

I hope you solve the problem.

**Comment by Yogurt928** [comment]
@mrcabellom 
Yes, it is the last cntk version with GPU. 
I also installed cntk on another server and the GPU can be used normally.
I will reinstall it on the first server to check again. Thanks for your help :)

**Comment by bobuntu** [comment]
@Yogurt928 how did go? I'm kinda going through a similar issue. Using CNTK 2.2 **GPU**.
@mrcabellom is a re-install the only fix at the moment?

**Comment by m-wilczynski** [comment]
I've encountered this problem several times already and it seems that Windows host is preventing CNTK.GPU from detecting GPU devices. Host reboot (ouch!) fixed this problem every time so far.
