### ISSUE TITLE
ParameterTensor repeat along axis

### ISSUE THREAD

**Issue by xforceco** [Microsoft/CNTK#2463]
Suppose `A = ParameterTensor{(100:200)}` and `B = Splice(A:A:A,axis=1)`

Will CNTK handle this as "shallow copy" s.t. gradient descent will work correctly if it propagates along `B`?

**Comment by n17s** [comment]
The gradient will be correct, but currently the copy is not implemented as a shallow copy.

**Comment by xforceco** [comment]
Thank you on that info, I am closing the issue :)
