### ISSUE TITLE
Intermediate Layer Crash

### ISSUE THREAD

**Issue by csolorio** [Microsoft/CNTK#2464]
Hi,

I've downloaded and tested the C++ evaluation example. It compiles and runs with no problems until...
`EvaluateIntermediateLayer(resnet20Model, CNTK::DeviceDescriptor::GPUDevice(0));`

The line that causes the crash is:
`FunctionPtr modelFunc = AsComposite(interLayerPrimitiveFunc);`
Since the `findByName` invokation from the block:
`std::wstring intermediateLayerName = L"final_avg_pooling";
FunctionPtr interLayerPrimitiveFunc = rootFunc->FindByName(intermediateLayerName);`
return null. 
I downloaded the res20 model using the PreTrainedModel python app. 
Any suggestion to fix the problem?

Thanks in advance!

**Comment by liqunfu** [comment]
The resnet20 model shall be generated with instruction at https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification/ResNet/Python
specifically with this command:
python TrainResNet_CIFAR10.py -n resnet20

You need to install CNTK python package to run it.

**Comment by csolorio** [comment]
Ok. Just trained the model and that was effectively the issue. Thanks!

**Comment by csolorio** [comment]
Just one question more though. The valuation with the downloaded model is too slow. The evaluation with the trained model is incredibly fast. Model file sizes are pretty much the same. Is there any particular reason for it?

**Comment by liqunfu** [comment]
How did you evaluate the download model? I guess you evaluate both models for their outputs, not the intermediate layer. Did you see any difference between the evaluation results? If models are the same (so are their evaluation results), I do expect it take the same time to evaluate for the same output.
