### ISSUE TITLE
top_k operation

### ISSUE THREAD

**Issue by AdamStefan** [Microsoft/CNTK#2468]
Is the a top_k operation in cntk similar with the one from tensorflow? If not is there a way to obtain the same result?

**Comment by cha-zhang** [comment]
We don't have one. One may write a custom layer in pure Python to do this for now. I'm adding a feature request label.

**Comment by calledbymountains** [comment]
If it is meant for the purpose of computing classification error/accuracy, one has a `topN` argument in `cntk.metrics.classification_error()`. 
Can you tell if there are other use cases where this would be critically required ?

**Comment by cha-zhang** [comment]
If you are talking about classification error, topN should be working to my best knowledge. There is a remaining working item to have multiple topN arguments in Python API. We have it in BrainScript, but it's not supported in Python yet.
