### ISSUE TITLE
How to use minibatch data as a  matrix

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#247]
ERROR:minibatch data cannot be interpreted as  a single 2D tensor.
Though i know what number of minibatch size is , i cannot use it to do matrix operation?

**Comment by staplesinLA** [comment]
When use operator Scale, it immediately warns: Segmentation fault (core dumped).
Delete that single statement ,the program is OK. How that happens?  Thanks!

**Comment by frankseide** [comment]
CNTK is built around the idea that the formula you write describes a single time step (referring to previous and future values using PastValue() and FutureValue()). Users have no explicit access to the time dimension. This is very different from other toolkits. CNTK also processes multiple sequences in a single minibatch, and the user also has no explicit access to the sequence index. In the case of frame randomization (where every sample is independent, such as in image processing), CNTK sees each sample a one sequence of length 1.

CNTK has this design to allow a number of optimizations, such as denser packing of sequences that vary greatly in length in a single minibatch (unlike other toolkits, CNTK requires no bucketing, which has advantages for randomization and general cleanliness of design). For example, 3 sequences of length 100, 40, and 50 would be packed into a tensor with sequence dimension 2, not 3, where 40 and 50 sequence are concatenated and share the same tensor index. Special care is taken so that we still compute the correct values, i.e. at the transition between the 40 and 50 sequence, recurrent states and gradients are reset correctly.

"Minibatch data" in your error message refers to tensors with CNTK-managed time and sequence dimensions. Some operations require such data, for example PastValue, and some don't such as Plus. For those, all the user can specify if the non-managed dimensions. For example, if you specify an ImageInput of dimension [W x H x C], then inside it will have tensor dimension [W x H x C x S x T] where S is the number of parallel sequences and T the number of time steps.

Operations on such tensors with CNTK-managed time and sequence dimensions retain those dimensions. Imagine a matrix of size [H x T] where the column dimension is time. Multiplying this with a matrix [W x H] gives you a matrix [W x T]. The time dimension is retained. Such operation is possible.

There is one exception: Broadcasting allows to combine tensors where one has CNTK-managed time/sequence dimensions, and the other has not. In that case, for the one that does, broadcasting is used to duplicate it. That is what happens when you add a bias vector.

Your case looks like a bug or uncaught configuration. To track that down further, I need the call stack and the Validation output.

Thanks!

**Comment by frankseide** [comment]
The only known seg fault is in UCIFastReader when the epoch size is larger than the data size (which is on the list).

Does the seg fault happen during validation, or when it computes the first minibatch?

We have a flag inside CNTK for tracking evaluation. For now, that flag is a #define. I will see if we can turn that into a runtime-configurable flag. That will make it easier to exactly pinpoint which operation fails.

**Comment by staplesinLA** [comment]
THANKS! 
the validating:
`10 roots:
	E = Exp
	Hlast = PerDimMeanVarDeNormalization
	featNormIn.xMean = Mean
	featNormIn.xStdDev = InvStdDev
	featNormOut.xMean = Mean
	featNormOut.xStdDev = InvStdDev
	featNormTrain.xMean = Mean
	featNormTrain.xNorm = PerDimMeanVarNormalization
	featNormTrain.xStdDev = InvStdDev
	normMSE = SquareError
FormNestedNetwork: WARNING: Was called twice for E Exp operation
FormNestedNetwork: WARNING: Was called twice for Hlast PerDimMeanVarDeNormalization operation
FormNestedNetwork: WARNING: Was called twice for featNormIn.xMean Mean operation
FormNestedNetwork: WARNING: Was called twice for featNormIn.xStdDev InvStdDev operation
FormNestedNetwork: WARNING: Was called twice for featNormOut.xMean Mean operation
FormNestedNetwork: WARNING: Was called twice for featNormOut.xStdDev InvStdDev operation
FormNestedNetwork: WARNING: Was called twice for featNormTrain.xMean Mean operation
FormNestedNetwork: WARNING: Was called twice for featNormTrain.xNorm PerDimMeanVarNormalization operation
FormNestedNetwork: WARNING: Was called twice for featNormTrain.xStdDev InvStdDev operation
FormNestedNetwork: WARNING: Was called twice for normMSE SquareError operation


Validating network. 43 nodes to process in pass 1.

Validating --> scalermatrix = LearnableParameter -> [128 x 128]
Validating --> featOut = InputValue -> [257 x *]
Validating --> featTrain = InputValue -> [257 x *]
Validating --> featNormOut.xMean = Mean(featTrain[257 x *]) -> [257]
Validating --> featNormOut.xStdDev = InvStdDev(featTrain[257 x *]) -> [257]
Validating --> featNormOut.yNorm = PerDimMeanVarNormalization(featOut[257 x *], featNormOut.xMean[257], featNormOut.xStdDev[257]) -> [257 x *]
Validating --> A = TransposeTimes(featNormOut.yNorm[257 x *], featNormOut.yNorm[257 x *])`

the CALL STACK:
`/home/LAL/CNTK-Sourcecode-2016-02-08/CNTK/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::PrintCallStack()  + 0xba  )  [0x7f41d6c4609a]
  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::logic_error>(char const*, ...)  + 0xc5  )  [0x5426e5]
  cntk                           ( Microsoft::MSR::CNTK::TimesNodeBase<float, true>::Validate(bool)  + 0x824 )  [0x5d6304]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::ValidateNodes(std::list<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > >, bool, unsigned long&)  + 0x36a )  [0x6b402a]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::ValidateNetwork()  + 0x236 )  [0x6b4b16]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::CompileNetwork()  + 0x1fc )  [0x6b65fc]
  cntk                           ( Microsoft::MSR::CNTK::NDLBuilder<float>::LoadFromConfig(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)  + 0x205 )  [0x5999b5]
  cntk                           ( Microsoft::MSR::CNTK::NDLBuilder<float>::BuildNetworkFromDescription(Microsoft::MSR::CNTK::ComputationNetwork*)  + 0x29  )  [0x599ba9]
  cntk                           ( std::_Function_handler<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int), void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)::{lambda(int)#2}>::_M_invoke(std::_Any_data const&, int)  + 0x12  )  [0x7440d2]
  cntk                           ( Microsoft::MSR::CNTK::SGD<float>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*, bool)  + 0x49a )  [0x72df9a]
  cntk                           ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x219 )  [0x74d549]
  cntk                           ( void DoCommands<float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x81c )  [0x59551c]
  cntk                           ( wmainOldCNTKConfig(int, wchar_t**)        + 0x907 )  [0x539a57]
  cntk                           ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53a0b0]
  cntk                           ( main                                      + 0xd8  )  [0x597278]
  /lib64/libc.so.6               ( __libc_start_main                         + 0xfd  )  [0x3600a1ed5d]
  cntk                           (                                                   )  [0x532d05]
EXCEPTION occurred: CheckTensorIsMatrix: Minibatch data cannot be interpreted as a single 2D tensor.
[CALL STACK]
? /home/LAL/CNTK-Sourcecode-2016-02-08/CNTK/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::GetCallStack()  + 0xc6  )  [0x7f41d6c46336]
? cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::logic_error>(char const*, ...)  + 0xe0  )  [0x542700]
{  cntk                           ( Microsoft::MSR::CNTK::TimesNodeBase<float, true>::Validate(bool)  + 0x824 )  [0x5d6304]
  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::ValidateNodes(std::list<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > >, bool, unsigned long&)  + 0x36a )  [0x6b402a]
v  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::ValidateNetwork()  + 0x236 )  [0x6b4b16]
u  cntk                           ( Microsoft::MSR::CNTK::ComputationNetwork::CompileNetwork()  + 0x1fc )  [0x6b65fc]
? cntk                           ( Microsoft::MSR::CNTK::NDLBuilder<float>::LoadFromConfig(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)  + 0x205 )  [0x5999b5]
? cntk                           ( Microsoft::MSR::CNTK::NDLBuilder<float>::BuildNetworkFromDescription(Microsoft::MSR::CNTK::ComputationNetwork*)  + 0x29  )  [0x599ba9]
6  cntk                           ( std::_Function_handler<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int), void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)::{lambda(int)#2}>::_M_invoke(std::_Any_data const&, int)  + 0x12  )  [0x7440d2]
  cntk                           ( Microsoft::MSR::CNTK::SGD<float>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<float>*, Microsoft::MSR::CNTK::IDataReader<float>*, bool)  + 0x49a )  [0x72df9a]
? cntk                           ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x219 )  [0x74d549]
€  cntk                           ( void DoCommands<float>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x81c )  [0x59551c]
c  cntk                           ( wmainOldCNTKConfig(int, wchar_t**)        + 0x907 )  [0x539a57]
c  cntk                           ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53a0b0]
c  cntk                           ( main                                      + 0xd8  )  [0x597278]
g  /lib64/libc.so.6               ( __libc_start_main                         + 0xfd  )  [0x3600a1ed5d]
  cntk                           (                                                   )  [0x532d05]

-------------------------------------------------------------------
Usage: cntk configFile=yourConfigFile
For detailed information please consult the CNTK book
"An Introduction to Computational Networks and the Computational Network Toolkit"`

**Comment by staplesinLA** [comment]
And in the Seg Fault case,   i used HTKMLFReader.  It's fails before validation, no more information printed in log files.  
Thanks!

**Comment by frankseide** [comment]
This is the culprit:

`Validating --> A = TransposeTimes(featNormOut.yNorm[257 x *], featNormOut.yNorm[257 x *])`

The Times operation has a limitation that only the column dimensions can represent time. You are combining two minibatches with CNTK-managed time, so necessarily one of them must be in row dimension. That is not supported.

Unless I have not had enough coffee this morning, it should be possible to represent the same operation differently:

`A = SumColumnElements (ElementTimes (yNorm, yNorm))`

Could you [first double-check that this is mathematically equivalent and then] try that?

**Comment by frankseide** [comment]
OK, I did not have enough coffee. yNorm' * yNorm will give a [T x T] matrix. Is this your intention, or do you want to get yNorm'(t) * yNorm(t), which gives you a scalar sequence [1 x T]?

What I wrote above will give you the scalar sequence. If you want the [T x T] matrix, I need to understand better what you are trying to achieve. A [T x T] matrix cannot be represented by CNTK (we are actively working on a redesign that will address this, but that will not be ready for another few months).

**Comment by frankseide** [comment]
If your task is operating on individual independent samples (such as images), that means T=1. In that case, my formula should be correct.

**Comment by staplesinLA** [comment]
yes，first i want to get the T*T matrix， and the energy of every single frame will appear in the diagonal.
your eaqution can partly sovle it，at least i get a energy row.  Lastly  If the scale can works，i am sure to run the whole task. 
thanks !have a nice day

**Comment by frankseide** [comment]
Yes, my formula will give you that diagonal as a time sequence again.

The seg fault worries me. Could you share the last 10 lines of the log? And if you have a chance, run it in gdb and give me the stack trace from there, preferably a Debug build? Unfortunately, our Linux version does not collect a stack trace for seg faults.

**Comment by staplesinLA** [comment]
Use Scale:
`  A=Log(energyNormOut)
  B=Scale(-0.5,A)
  C=Exp(B)`
Log:
`reading script file /home/sunlei/SE/try_norm_config/timit_115NT_7SNRs_each190utts_devnoisy_lsp_be_random_linux.path ... 422 entries
reading script file /home/sunlei/SE/try_norm_config/timit_115NT_7SNRs_each190utts_devclean_lsp_be_random_linux.path ... 422 entries
reading script file /home/sunlei/SE/try_norm_config/timit_115NT_7SNRs_each190utts_devnoisy_lsp_be_random_linux.path ... 422 entries
.....................................................................................feature set 0: 79973 frames in 422 out of 422 utterances
minibatchutterancesource: 422 utterances grouped into 1 chunks, av. chunk size: 422.0 utterances, 79973.0 frames
.....................................................................................feature set 1: 79973 frames in 422 out of 422 utterances
minibatchutterancesource: 422 utterances grouped into 1 chunks, av. chunk size: 422.0 utterances, 79973.0 frames
.....................................................................................feature set 2: 79973 frames in 422 out of 422 utterances
minibatchutterancesource: 422 utterances grouped into 1 chunks, av. chunk size: 422.0 utterances, 79973.0 frames`

**Comment by staplesinLA** [comment]
without Scale:
`  A=Log(energyNormOut)
 # B=Scale(-0.5,A)
  C=Exp(A)`
Corresponding log:
`Validating --> energyNormOut = SumColumnElements(norm_lsp[257 x *]) -> [1 x *]
Validating --> A = Log(energyNormOut[1 x *]) -> [1 x *]
Validating --> C = Exp(A[1 x *]) -> [1 x *]
.......
`
It runs well.

**Comment by dongyu888** [comment]
Use 

 

Scale(Constant(-0.5), A)

**Comment by staplesinLA** [comment]
`B = ElementTimes(unnamed54[1 x 1], A[1 x *]) -> [1 x 1 x *]`
yes,I tried 'constant' before ,the form of "[1 x 1 x *] confused me if it performs as a scaler .

**Comment by frankseide** [comment]
Noted. If this passes Validation, your are good.

CNTK has a history of using matrices, which have recently been extended to tensors. Some places still use the matrix format, including Constant apparently. To get a proper 1-dim tensor, you can create a ImageParameter with 1 tensor dimension, and set its learningRateMultiplier to 0 to make it a constant. But first try if it passes Validation and if the dimensions look like expected. Additional 1-dimensions should not make a difference except for a matrix product.

**Comment by luyamalu** [comment]
OK, i have already known how Minibatch data works.  Last but not least,  the latest version of CNTK have the operator RowElementTimes(A,brow), will every element in A product the corresponding element in brow? In log file , it still states as ElementTimes, so i am not sure it works as i imagined. 
Thanks!

**Comment by staplesinLA** [comment]
OK, i have already known how Minibatch data works. Last but not least, the latest version of CNTK have the operator RowElementTimes(A,brow), will every element in A product the corresponding element in brow? In log file , it still states as ElementTimes, so i am not sure it works as i imagined. 
Thanks!

**Comment by frankseide** [comment]
It is ElementTimes with broadcasting. You can also directly use ElementTimes, it will make no difference.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Thu, Mar 17, 2016 at 10:50 PM -0700, "staplesinLA" <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, i have already known how Minibatch data works. Last but not least, the latest version of CNTK have the operator RowElementTimes(A,brow), will every element in A product the corresponding element in brow? In log file , it still states as ElementTimes, so i am not sure it works as i imagined.
Thanks!

-

**Comment by staplesinLA** [comment]
As you can see from above ,what i want to do is to calculate the energy of each frame, and let every element divide(by using Log and Exp)  corresponding frame energy.  now i know how to achieve it .
Thanks!!
May the good coffee be with you! ^_^

**Comment by frankseide** [comment]
Excellent! I hope it's OK for you if I close this Issue. Please do not hesitate to reopen or ask any new questions you may encounter in the future.

BTW we have just implemented an element-wise Reciprocal operation, which will allow you to do what you want without Log and Exp. It's not in master yet, probably in a day (NonlinearityNodes.h, line ~143).

And finally a quick explanation of RowElementTimes vs. ElementTimes: An older CNTK version used two different CUDA kernels to implement these. In the current version, ElementTimes implements broadcasting, so RowElementTimes is now just an alias for ElementTimes that we keep for backwards compatibility.

Getting that coffee now.
