### ISSUE TITLE
What's the ETA for VS 2017 support in CNTK?

### ISSUE THREAD

**Issue by 3DHDSoft** [Microsoft/CNTK#2473]
When **VS 2017** will be supported for Microsoft Cognitive Toolkit?

**Comment by ebarsoumMS** [comment]
To support VS2017, we need to first move to CUDA 9. This work is in progress, but we don't have an ETA yet.

**Comment by bencherian** [comment]
Will you continue to support builds in VS2015 after the transition to CUDA9? (I hope the answer is yes.)

**Comment by ebarsoumMS** [comment]
Is there a reason you want us to keep supporting VS2015? You can use 2017 community edition.

**Comment by bencherian** [comment]
Integration with an application that is currently built in VS2015 (for which transitioning to VS2017 would be prohibitively difficult).

**Comment by whitmark** [comment]
Can CNTK 2.2 binaries be used with VS 2017?

James McCaffrey is taking a run at it:
[https://jamesmccaffrey.wordpress.com/2017/10/06/writing-cntk-code-using-visual-studio-2017/](url)

Is this page accurate for VS 2017 (VS 15.0)?
[https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-python-tools-for-windows](url)

**Comment by 3DHDSoft** [comment]
A definite statement would be nice. That is great that VS 2015 will be still supported.
That implies that after CUDA 9 support, that I hope happens super fast, VS 2017 will be a supported.
The question still remains (since the vague answer):

## **When VS 2017 will be supported for CNTK, please?**

**Comment by Dozer3D** [comment]
> Is there a reason you want us to keep supporting VS2015?

Yes!!! Not all users of CNTK are researchers, academics, students... some of us are traditional windows developers who ship Windows products. In our case, every license of our product includes 1 Windows OS license as well, and the size of the code base is almost 1 millions lines. We use many third party libraries upgrading them all to the next version of VS is not a decision we take lightly and mixing versions can be awkward. Comparing with other commerical and non commercial libraries that I have used over the years for Windows development, dropping support for VS2015 so quickly would be going against the trend.

**Comment by 3DHDSoft** [comment]
And the alternative is that just follow the trend, migrate all your code to ,NET Core/Standard 2.0 using VS 2017 and beet your competition, before they beat you :-)

**Comment by ebarsoumMS** [comment]
@bencherian and @Dozer3D by moving to VS2017 we are moving the build part of the library. However, Nuget and CNTK binaries can still be used in VS2015. Is you scenario involve building CNTK from the source in your workflow.

@3DHDSoft sadly I don't have definite answer for now, we are working on it.

**Comment by 3DHDSoft** [comment]
Appreciate the valuable feedback. We wait patiently. Thx, Ivan

**Comment by bencherian** [comment]
@ebarsoumMS We build CNTK from source with slightly different DLL setup to avoid duplication of certain dependencies that are also used in other parts of the program.

**Comment by Dozer3D** [comment]
> @ebarsoumMS However, Nuget and CNTK binaries can still be used in VS2015.

There is a tendency to run into issues when mixing libraries from different versions of Visual studio, and it can mean shipping multiple VC run times. [For example](https://msdn.microsoft.com/en-us/library/bb531344.aspx?f=255&MSPPError=-2147217396), there can be undefinable problems when statically linking to libraries built with different versions of VC. I am not sure if these problems apply in the case of the eval DLLs. While there is always a workaround to any problem, there is a certain class of problems that often disappear when compiling the libraries with our chosen version of VS.

**Comment by dmagee** [comment]
I'm presuming vs2017 support is now here as the instructons say to install vs2017. Above, someone seemed to suggest back compatibility with 2015 would be maintained. Can someone confirm (or deny) this is the case (as there is no mention of vs2015 on the website).

**Comment by thiagocrepaldi** [comment]
As of CNTK 2.4+, only VS2017 is supported for compiling. VS2015 will only work for CNTK 2.3.1 and older. 

However, if you want to use pre-compiled packages of CNTK, you can still use VS2015 as you won't need to compile CNTK again.
