### ISSUE TITLE
System.AccessViolationException when acessing Output property of an empty Combine function

### ISSUE THREAD

**Issue by cesarsouza** [Microsoft/CNTK#2474]
The following code snippet throws a System.AccessViolationException:

```csharp
var update_func = CNTKLib.Combine(new VariableVector((ICollection)(new Variable[] { })));
var test = update_func.Output;
```

It would be better if CNTK could throw a more informative error message warning that the function does not have any outputs, or that a Combine function cannot be created when the list of input variables is empty.

Throwing System.AccessViolationExceptions causes VS to immediately terminate the debugger as soon as the user passes the mouse over the "update_func.Output" variable, which significantly degrades the debugging experience.

Regards,
Cesar

**Comment by liqunfu** [comment]
error message added for the error condition
