### ISSUE TITLE
EXCEPTION occurred: Plugin not found: 'KaldiReader-2.1.dll'

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#2475]
Please let me know why kaldiReader-2.1.dll plugin is not found.

**Comment by cha-zhang** [comment]
Are you using Python or BrainScript?

**Comment by eldakms** [comment]
To the best of my knowledge kaldi reader was not supported on Windows at all. Did this change recently? If not - there is no .dll generated, only .so, and you can use it only in BrainScript on Linux. 
Thanks!

**Comment by vidyatshetty** [comment]
@cha-zhang I am using brainscript

@eldakms thanks for writing. I didn't know kaldi reader was not supported on windows.

**Comment by cha-zhang** [comment]
Better Kaldi support in Python is something we wanted to work on but never had the time. Adding this as a feature request.
