### ISSUE TITLE
Dropout to high dimension Tensor by column

### ISSUE THREAD

**Issue by xforceco** [Microsoft/CNTK#2478]
I wonder if it is possible that the dropout can apply to a tensor of 2D column by column,
i.e. for Tensor `2*3` with dropout rate = `0.5`

I want something like [0,1,1;1,0,0] where `0` stands for dropout element

**Comment by n17s** [comment]
Can you specify how this operation works with a general shape and a general dropout rate?

**Comment by cha-zhang** [comment]
If I understand right, your are talking about a single dropout rate, then the current dropout node should support multi-dimensional tensor inputs.

**Comment by tangyuq** [comment]
If I understand your column-wise dropout need correctly, you can workaround this by: 
x = C.input_variable((2, 3))
drp_dummy = C.input_variable(3) # [1, 1, 1]
drp = C.dropout(drp_dummy, 0.5)
x_drp = x * drp
x_drp.eval({x: np.ones((5, 2,3)), drp_dummy: np.ones((5, 1,3))}) #5 is the size of the batch

**Comment by xforceco** [comment]
Thank you for the reply, the second one is what I need.
:)
I am closing the issue.
