### ISSUE TITLE
CBFDeserializer crashing issue

### ISSUE THREAD

**Issue by haixpham** [Microsoft/CNTK#2479]
I have been using CTFDeserializer with success so far. But with large datasets, the text file grows too big. I tried to switch to CBF, by converting CTF file to CBF with the "ctf2bin" tool, which reduces CTF file size from 16GB to CBF file size of 4GB. The reader is defined as: 

```python
def create_reader(path, is_training=True):
    return C.io.MinibatchSource(C.io.CBFDeserializer(path, C.io.StreamDefs(
        features = C.io.StreamDef(field='features', shape=input_dim, is_sparse=False),
        labels = C.io.StreamDef(field='labels', shape=label_dim, is_sparse=False)
    )), randomize=is_training, max_sweeps = C.io.INFINITELY_REPEAT if is_training else 1)
```

However, the training program crashes at specific times. E.g, if minibatch_size = 200, it crashes at 29th epoch, and at 2nd epoch when minibatch_size=300.

Note that the same training code with the same data loaded by CTFDeserializer works perfectly. So, the culprit would be somewhere in CBFDeserializer, or I didn't use it correctly.

In either case, can someone give me a workaround to handle big dataset?

edit: I'm using CTNK 2.2 GPU, Python 3.6 on Windows.

**Comment by tangyuq** [comment]
Can you please provide us your crash output to debug further?

**Comment by haixpham** [comment]
I'm not sure if CTNK did log something somewhere. If it does please tell me where to look for it.

I use Python API, so I couldn't trace the error. It is reported by Visual studio as Memory reading violation.

**Comment by frankibem** [comment]
I'm encountering a similar problem with a .cbf dataset that I'm working with. After reading a fixed number of minibatches, I get a segmentation fault with no other message/logs. However, training is working just fine with the .ctf format. I can provide access to the dataset in both formats if needed.
