### ISSUE TITLE
issue with shareNodeValueMatrices=true

### ISSUE THREAD

**Issue by mirco86** [Microsoft/CNTK#248]
Hi,
I'm trying to use CNTK with the Kaldi plug-in. I have trained a DNN of 6 hidden layers with CNTK (without any error using wsj5k data) and I'm trying now to use "decode_cntk2.sh" to decode the test signals using the following command:

`steps/nnet_cntk/decode_cntk2.sh --nj 6 --cmd run.pl --acwt 0.1 --beam 18 --latbeam 10.0 /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/tri4/graph_tgpr_5k /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/data-fmllr-tri4/sim_dev_onlyrev /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1/decode_cntk_sim_dev_onlyrev_gpu4 cntk configFile=conf/cntk_config//CNTK2_write.config DeviceNumber=-1 modelName=/home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1/cntk.dnn.29 labelDim=3288 featDim=40 action=write ExpDir=/home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1`

The obtained WER is 12.4%  which seems reasonable for a noisy+reverberated task and comparable to that obtained directly from Kaldi.

However I have observed a very weird behaviour when I add at the top of the the  CNTK2_write.config file the line: “**shareNodeValueMatrices=true**”. In this case the  WER drops to 21.4%. Note that there are no errors/warning occurring.

Are there some problems with shareNodeValueMatrices or am I doing something wrong?

Note that is I have the same problems with both  “DeviceNumber=-1” (CPU) and “DeviceNumber=0”  (GPU)

Mirco

**Comment by frankseide** [comment]
Thanks! Memory sharing is a tricky business and hard to test since knowledge is quite distributed (each node must communicate to the engine what constraints it has on memory sharing, e.g. will it need its inputs and/or its outputs during backpropagation). The flag shareNodeValueMatrices was added so that we can disable this specific form of memory sharing by default until we are confident that there are no errors.

You just found one.

I will pass this on. For now, please just run with shareNodeValueMatrices=false.

Yes, memory sharing is orthogonal to CPU vs. GPU.

**Comment by mirco86** [comment]
Thank you Frank! 
The problem is that right now I'm working with CNTK using a single GPU with only 2GB of memory. For this reason, if I do the decoding using  "DeviceNumber=0" (GPU) I have an "out of memory" error, which can be solved only imposing "shareNodeValueMatrices=true".  In other words the only configuaration which right now can work is to do the decoding with CPU only (DeviceNumber=0,shareNodeValueMatrices=false ), which is very slow.

Mirco

**Comment by amitaga** [comment]
Mirco, can you share the commit number that the CNTK build you are using is based off?

**Comment by mirco86** [comment]
Sorry, I cannot retrieve but i download it on March, 15.

**Comment by amitaga** [comment]
A candidate fix is on the branch amitaga/memshareFixes. Can you please try and let us know if it addresses your issue?

**Comment by mirco86** [comment]
Hi Amit,
with your fix everything seems to work now. After a preliminar test I have
obtained the same WER with both shareNodeValueMatrices=false and
shareNodeValueMatrices=true. I suggest to put this version of the code on
the master....

Mirco

**Comment by mradmila** [comment]
Thanks for reporting this issue. I will close this issue, but please reopen it if the problem persists.

**Comment by amitaga** [comment]
Thanks for testing the fix Mirco. The change is now in master.
