### ISSUE TITLE
No CNTK op for computing standard deviation ?

### ISSUE THREAD

**Issue by calledbymountains** [Microsoft/CNTK#2481]
I am trying to do a per image standardization in CNTK before feeding into the network.
For every image in the batch, I want to compute the mean of all the pixels in the image (done using `reduce_mean()`. 
However there is no function available to compute the standard deviation. 

What is the right way of doing it inside CNTK ?

**Comment by tangyuq** [comment]
@calledbymountains   Just to clarify your question: You want the mean and standard deviation of pixels within an image not the mean and the standard deviation of a pixel (of the same location) across all images in a minibatch. Is this correct? 

If my above understanding is correct, you should do: 
```python
reduce_mean(x, axis = [x_axis, y_axis])
```
The standard deviation can be computed as described in @mfuntowicz 's post but with x and y axes.

**Comment by calledbymountains** [comment]
Okay. Meanwhile I am trying to add an op for per_image_standardization ( as in TensorFlow) and a transform for resizing images. I will send a pull request as soon as possible
