### ISSUE TITLE
R: trouble with op_reduce_sum()

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#2492]
Hi,
I am trying to write my first R program to forecast time series, along the lines of my previous Python programs. So, I have a number of time series of varying length. Each point of each time series has been preprocessed to an input vector of length 6 and an output vector of similar length (INPUT_SIZE and OUPUT_SIZE respectively).
I want to code my own loss function sMAPE (see https://en.wikipedia.org/wiki/Symmetric_mean_absolute_percentage_error) . 
So I declare 
  input_var <- seq_input_variable(INPUT_SIZE, name = "input")
  output_var <- seq_input_variable(OUTPUT_SIZE, name = "label")
I create my network, e.g.
  r=Recurrence(LSTM(STATE_SIZE))(input_var)
  r=Dense(OUTPUT_SIZE, activation=op_softplus)(r)
  z=op_minus(r,1)
Now, I am writing sMAPE:
a=op_element_divide(op_abs(op_minus(z,output_var)), op_plus(op_abs(output_var),op_abs(z)))
loss=op_reduce_sum(a)
and the last line fails, with
"AttributeError: 'Variable' object has no attribute 'is_static_axis'"
I tried
loss=seq_reduce_sum(a)
this does not fail, but this is, I think, not what I want, the result is 
Composite(input: Sequence[Tensor[6]], label: Sequence[Tensor[6]]) -> Tensor[6]
so not scalar.
Actually I would like to average first over the output vector (length of 6), and only then make a second aggregation over sequences and batch members.
But how to do it?

Regards,
Slawek

**Comment by cha-zhang** [comment]
I'm not familiar with R, but I think you need to use sequence.reduce_sum instead of the regular reduce_sum.

**Comment by slaweks17** [comment]
Hi,
Thank you for your reply. But I tried it, and I do not think this is what I need. As I wrote:
"I tried
loss=seq_reduce_sum(a)
this does not fail, but this is, I think, not what I want, the result is
Composite(input: Sequence[Tensor[6]], label: Sequence[Tensor[6]]) -> Tensor[6]
so not scalar."
I tried also to use op_reduce_sum() on the result, and got the same "AttributeError: 'Variable' object has no attribute 'is_static_axis'"

Regards,
Slawek

**Comment by cha-zhang** [comment]
Can you provide the Python code you intend to implement? Does the Python code fail?

**Comment by slaweks17** [comment]
Hi.
No, Python works. Some code pieces:
def sMAPELoss (z, t):
  loss=o.reduce_mean(o.abs(t-z)/(t+z))*200
  return loss

def linear_layer(input_var, output_dim):
  input_dim = input_var.shape[0]
  times_param = o.parameter(shape=(input_dim, output_dim))
  bias_param = o.parameter(shape=(output_dim))
  t = o.times(input_var, times_param)
  return bias_param + t

  r=l.Recurrence(l.LSTM(hidden_layer_dim1, 
    use_peepholes=LSTM_USE_PEEPHOLES,
    enable_self_stabilization=LSTM_USE_STABILIZATION))(input_var)
 z= linear_layer(r, output_dim)
loss = sMAPELoss(z,label)

So, cntk.ops.o.reduce_mean() works and produces  loss that is 
Output('ElementTimes4266_Output_0', [#, *], [])

Regards,
Slawek

**Comment by cha-zhang** [comment]
Did you ask your question on CNTK-R repository?

**Comment by slaweks17** [comment]
No. I did not. I thought that this is the place to ask all CNTL languages questions 😊
OK. I will. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by akzaidi** [comment]
Closing here since it's being tracked Microsoft/CNTK-R#2.
