### ISSUE TITLE
Segmentation fault after roughly first epoch

### ISSUE THREAD

**Issue by frankibem** [Microsoft/CNTK#2494]
I'm trying to train an LSTM model for classification but I get a segmentation fault roughly after the first epoch with no other message. I've tried to increase the stack size to 65536 (and 131072) using 'ulimit -s' as suggested in #1273 but still get the error at exactly the same spot. I've looked over my training code and haven't found any obvious blunders so I'm not sure what else to try.

[Here's](https://github.com/frankibem/asllvd/blob/master/train.py) a link to my training script. I'm using CNTK v2.2 (GPU) running on an Azure NC6 series virtual machine (1 x K80 GPU).

If you'd like to reproduce this, I can provide links to download the CBF files (generated with ctf2bin.py) for the training and test datasets (~19GB).

**Comment by cha-zhang** [comment]
You might be out of memory because of some long sequences. Have you tried using smaller minibatch sizes?

**Comment by frankibem** [comment]
Not yet. I just realized that I set the epoch size based on the number of sequences as opposed to the number of samples. The current run has gone past the previous point so closing for now. I will update if it reoccurs (after trying a smaller minibatch size).
