### ISSUE TITLE
How to use' C.sequence.delay' with 'time_step=-1'?

### ISSUE THREAD

**Issue by DabiaoMa** [Microsoft/CNTK#2495]
I ran the following codes:

import cntk as C
a = C.sequence.input_variable(shape=(3))
b = C.sequence.delay(a, initial_state=0, time_step=-1)

The following error appear:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cntk/ops/sequence/__init__.py", line 152, in future_value
    return future_value(x, initial_state, time_step, name)
NotImplementedError: Wrong number or type of arguments for overloaded function 'future_value'.
  Possible C/C++ prototypes are:
    CNTK::FutureValue(CNTK::Variable const &,CNTK::Variable const &,size_t,std::wstring const &)
    CNTK::FutureValue(CNTK::Variable const &,CNTK::Variable const &,size_t)
    CNTK::FutureValue(CNTK::Variable const &,CNTK::Variable const &)
    CNTK::FutureValue(CNTK::Variable const &,size_t,std::wstring const &)
    CNTK::FutureValue(CNTK::Variable const &,size_t)
    CNTK::FutureValue(CNTK::Variable const &)

I am confused with this error' wrong number or type of arguments', I checked the Python API and found nothing wrong with arguments for 'future_value': future_value(x, initial_state=None, time_step=1, name='')

In the official implementation of RecurrenceFrom, something similar is used: 
prev_out_vars = [sequence.delay(out_var, initial_state=init, time_step=-1 if go_backwards else +1) for out_var, init in zip(out_vars_fwd, initial_state)]

**Comment by DabiaoMa** [comment]
I guess I found the reason.

For Function 'C.sequence.past_value', the argument 'initial_state' can be Constant, Variable, Parameter, or Function

But for Function 'C.sequence.future_value', the argument 'initial_state' should be Variable, Parameter or Function

I wonder why Constant like scalar or numpy ndarray can not be an option for 'future_value'?

And I think the document for 'C.sequence.future_value' also needs some modification.

**Comment by tangyuq** [comment]
Thank you for letting us know. It is a bug. Will have a fix soon.

**Comment by tangyuq** [comment]
A fix is already checked in master. Close this issue for now.
