### ISSUE TITLE
Evaluate trained network memory leak

### ISSUE THREAD

**Issue by navidnadery** [Microsoft/CNTK#2497]
I have trained a CNN and when I wanted to load and use it in python for Aurora2 clean test set as a feature extractor I ran to this error:

CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-8APAPT7 ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))
Traceback (most recent call last):
  File "FEClean1.py", line 8461, in <module>
    X=lm.lm(a)
  File "D:\Downloads\AuroraCompleteDey87\lm.py", line 20, in lm
    predictions=((np.squeeze(z_out.eval({z_out.arguments[0]:[np.float32(inputCont).reshape(len(inputCont), 1, 11, 26)]}))).tolist())
  File "C:\Python27\lib\site-packages\cntk\ops\functions.py", line 631, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  File "C:\Python27\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Python27\lib\site-packages\cntk\ops\functions.py", line 765, in forward
    keep_for_backward)
  File "C:\Python27\lib\site-packages\cntk\cntk_py.py", line 1876, in _forward
    return _cntk_py.Function__forward(self, *args)
RuntimeError: CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-8APAPT7 ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize
    - Microsoft::MSR::CNTK::Matrix<float>::  Resize
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x4)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - Microsoft::MSR::CNTK::DataTransferer::  operator=
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CreateDeserializer (x2)
    - PyCFunction_Call

Aurora2 Clean test set is consist of 8440 speech files, and I do some preprocessing on each before feeding it to CNTK module. I needed each file features separately.
I splitted 8440 files into 8 python files and I run each separately, this way it works well.

This problem is just when I using GPU, because using CPU does not have any error.

**Comment by cha-zhang** [comment]
Did you repeatedly load the model every time you process a new file?

**Comment by navidnadery** [comment]
Hi @cha-zhang and thank you for your reply.
Yes exactly.

**Comment by cha-zhang** [comment]
Then you probably shouldn't. Our eval library supports loading model once and eval multiple times.

**Comment by navidnadery** [comment]
Thank you very much.
