### ISSUE TITLE
what's matter

### ISSUE THREAD

**Issue by wyjzz** [Microsoft/CNTK#250]
when I run example ,cntk configfile=LSTM-NDL.cntk,the error was:

[CALL STACK]
    >Microsoft::MSR::CNTK::GetReader<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -_unDNameEx
    -_BuildCatchObjectHelper
    -RtlCaptureContext
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetReader<double>
    -00007FF6D2AC0A03 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2C09EA5 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2C08523 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2C06A3E (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?

EXCEPTION occurred: releasedata: called when data is not memory

**Comment by frankseide** [comment]
Which version is this? Could you share the first 20 lines of the log output, and the last 20 lines before the callstack?

**Comment by wyjzz** [comment]
The version is downloaded about one week. The sample of simple2d and penntreebank are success to run. Sample of AN4，configfile if  LSTM-NDL.cntk，has error as:

Validating --> LSTMoutput3.mt = ElementTimes(LSTMoutput3.ot[1024 x 1 x *], LSTMoutput3.unnamed169[1024 x 1 x *]) -> [1024 x 1 x *]
Validating --> LSTMoutput3.output = Times(LSTMoutput3.Wmr[512 x 1024], LSTMoutput3.mt[1024 x 1 x *]) -> [512 x *]
Validating --> unnamed174 = Times(W[132 x 512], LSTMoutput3.output[512 x *]) -> [132 x *]
Validating --> b = LearnableParameter -> [132 x 1]
Validating --> LSTMoutputW = Plus(unnamed174[132 x *], b[132 x 1]) -> [132 x 1 x *]
Validating --> logPrior.logPrior = Log(logPrior.prior[132]) -> [132]
Validating --> scaledLogLikelihood = Minus(LSTMoutputW[132 x 1 x *], logPrior.logPrior[132]) -> [132 x 1 x *]
Validating --> ce = CrossEntropyWithSoftmax(labels[132 x *], LSTMoutputW[132 x 1 x *]) -> [1]
Validating --> err = ErrorPrediction(labels[132 x *], LSTMoutputW[132 x 1 x *]) -> [1]

29 out of 113 nodes do not share the minibatch layout with the input data.

Post-processing network complete.

SGD using CPU.

Training criterion node(s):
        ce = CrossEntropyWithSoftmax

Evaluation criterion node(s):
        err = ErrorPrediction


Allocating matrices for forward and/or backward propagation.

Precomputing --> 3 PreCompute nodes found.

        NodeName: featNorm.xMean
        NodeName: logPrior.prior
        NodeName: featNorm.xStdDev
minibatchiterator: epoch 0: frames [0..252734] (first utterance at frame 0), data subset 0 of 1, with 1 datapasses

[CALL STACK]
    >Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetWriter<double>
    -Microsoft::MSR::CNTK::GetReader<double>
    -00007FF6D2AC0A03 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2C09EA5 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2C08523 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2C06A3E (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2BFB27E (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2B2AE8D (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?
    -00007FF6D2AF32E6 (SymFromAddr error : 璇曞浘璁块棶鏃犳晥鐨勫湴鍧€銆?

**Comment by tz579** [comment]
@wyjzz I encountered the same (or a similar) problem days ago. For several speech recognition examples including this Speech/AN4 one, if you run from data/ and specify configfile=../cfg/LSTM-NDL.cntk, the error would disappear. On the contrary, for Image/MNIST examples there is no such problems and thus running from cfg/ is OK.

I haven't checked the configuration files line by line though, and thus I have no idea what the true cause is for this problem.

Hope this can do some help for you.

**Comment by wyjzz** [comment]
That's true. Success to run according to you.Thank you.

**Comment by mradmila** [comment]
Thank you for reporting this issue. We will try to fix/standardize the samples, and provide better guidance.
