### ISSUE TITLE
cntk.edit_distance_error not running on multi-GPU

### ISSUE THREAD

**Issue by anupbera** [Microsoft/CNTK#2508]
Hi,
I tried to run cntk.edit_distance_error CTC implementation on 2 GPUs (nvidia Tesla M60 )  in Ubuntu 16.04 machine , but got following error :

Traceback (most recent call last):
  File "HTK_LSTM_CTC_Truncated_Distributed.py", line 200, in <module>
    cv_freq=args['cvfreq'])
  File "HTK_LSTM_CTC_Truncated_Distributed.py", line 149, in htk_lstm_truncated
    train_and_test(network, trainer, train_source, test_source, minibatch_size, epoch_size, restore, model_path, cv_freq)
  File "HTK_LSTM_CTC_Truncated_Distributed.py", line 116, in train_and_test
    model_inputs_to_streams = cv_input_map, frequency=cv_freq)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cntk/train/training_session.py", line 276, in train
    super(TrainingSession, self).train(device)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/cntk/cntk_py.py", line 3312, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
RuntimeError: SetDataLocation [CPUMatrix]: Cannot migrate the matrix between devices because it is a view.

======================================
Steps to Reproduce:
I have made some changes of the example https://github.com/Microsoft/CNTK/blob/master/Examples/Speech/AN4/Python/HTK_LSTM_Truncated_Distributed.py to working on CTC imlementation. Please find the attached python implementation. Please note that I have used the dataset at https://github.com/Microsoft/CNTK/tree/master/Examples/Speech/AN4/Data

run following commands from console:
$ download the zip file and data from the stated location. 
$ unzip the HTK_LSTM_CTC_Truncated_Distributed.zip
$ mpiexec --npernode 2 python HTK_LSTM_CTC_Truncated_Distributed.py

[HTK_LSTM_CTC_Truncated_Distributed.zip](https://github.com/Microsoft/CNTK/files/1393498/HTK_LSTM_CTC_Truncated_Distributed.zip)

Note: This code is running fine if we run it on single GPU

$ mpiexec --npernode 1 python HTK_LSTM_CTC_Truncated_Distributed.py

**Comment by anupbera** [comment]
Hi Cha,
Could you please let me know the expected timeline to resolve this issue.

**Comment by junjieqian** [comment]
Thanks for reporting! We have found the issue and will push a fix in sometime next week. Will update when the fix is in.
