### ISSUE TITLE
GPU Selection on Multi-GPU node

### ISSUE THREAD

**Issue by such87** [Microsoft/CNTK#251]
All,

I am trying to run CNTK on a GPU cluster with 4 GPUs on each node.

If I run the CNTK Benchmark (ffn) with 8 processes (4 ppn) I am seeing that
the first 4 on node 1 is selecting 4 GPUs but the next 4 one node 2 is not 
selecting any GPUs and running on CPUs only. Why is this so ?

I am using CUDA aware OpenMPI for running this.

mpirun -np 8 --hostfile hf ../../../bin/cntk configFile=ffn.config configName=ffn parallelTrain=true deviceId=auto

$cat hf
node1
node1
node1
node1
node2
node2
node2
node2

**Comment by mradmila** [comment]
Hi, we are testing this scenario in production all the time, so any bugs here would be extremely high priority for us (we also use CUDA aware OpenMPI). You have "auto" selected, which chooses the best GPU, or CPU if no usable GPU is available. Look at Source/Common/BestGpu.cpp to see details on GPU selection. My guess would be that on the node2, your GPUs are somehow not picked up as "usable" by CNTK. Do logs show any signs of why? Do you see something like this:

LockDevice: Locked GPU <num> to test availability.
LockDevice: Unlocked GPU <num> after testing.

Sharing logs could help us diagnose this. Also, make sure that GPUs drivers are properly installed by checking nvidia-smi output.

**Comment by such87** [comment]
Thanks for your reply.

On node1 the log files show this :
CNTKCommandTrainBegin: Train
LockDevice: Locked GPU 1 to test availability.
LockDevice: Unlocked GPU 1 after testing.
LockDevice: Locked GPU 0 to test availability.
LockDevice: Unlocked GPU 0 after testing.
LockDevice: Locked GPU 2 to test availability.
LockDevice: Unlocked GPU 2 after testing.
LockDevice: Failed to lock GPU 3 for exclusive use.
LockDevice: Locked GPU 1 for exclusive use.


On node2 the log files show this :

CNTKCommandTrainBegin: Train
LockDevice: Failed to lock GPU 0 for exclusive use.
LockDevice: Failed to lock GPU 1 for exclusive use.
LockDevice: Failed to lock GPU 2 for exclusive use.
LockDevice: Failed to lock GPU 3 for exclusive use.

All GPU drivers are loaded properly :

+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:05:00.0     Off |                    0 |
| N/A   33C    P0    61W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:06:00.0     Off |                    0 |
| N/A   30C    P0    71W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000:85:00.0     Off |                    0 |
| N/A   32C    P0    57W / 149W |     22MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000:86:00.0     Off |                    0 |
| N/A   28C    P0    73W / 149W |     22MiB / 11519MiB |     27%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

BTW, on CrossProcessMutex.h I have changed the lock file location from /var/lock
to a local destination so that there are no permission issues.

Please let me know what to do next.

**Comment by such87** [comment]
With some investigation I can figure this much that :
In BestGpu.cpp both ranks are trying to lock the same file.

In node 1 :

LOCKING /home/user34/cuda_cntk/DBN.exe GPGPU exclusive lock for device 0 
LOCKING /home/user34/cuda_cntk/DBN.exe GPGPU exclusive lock for device 1
LOCKING /home/user34/cuda_cntk/DBN.exe GPGPU exclusive lock for device 3
LOCKING /home/user34/cuda_cntk/DBN.exe GPGPU exclusive lock for device 2

Now once node1 gets the lock on these devices, the same files are use by node2
for locking GPUs 0,1,2,3 on node 2 which should be actually be using a global 
deviceId and not the local ones (as they are not unique).

Is this a possible reason ?

**Comment by mradmila** [comment]
Yes, we are using file system to lock the devices across a single node. If you use a shared directory for multiple nodes, this will not work.

**Comment by such87** [comment]
Still does not solve the problem.
So what is the solution for this ? Will you provide a patch for this ? 
As per my understanding, the code has to create a unique directory for each process ?

Although the file that is created by each process resides in its own address space so using a shared directory should work in principle.

**Comment by frankseide** [comment]
I am curious, how did you get the lock file to be in your home folder (/home/user34)? If I read the source code right, the lock directory is hard-coded to /var/lock, which is the UNIX standard and required to be machine-local.
```
    CrossProcessMutex(const std::string& name)
        : m_fd(-1),
          m_fileName("/var/lock/" + name)
    {
    }
```

**Comment by such87** [comment]
Yes.. If I leave it as is then there is an error stating "permission denied" to open the lock file
at /var/lock..

**Comment by frankseide** [comment]
Can you raise this with your sys admin? /var/lock must be writeable.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Mar 26, 2016 at 8:03 PM -0700, "such87" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes.. If I leave it as is then there is an error stating "permission denied" to open the lock file
at /var/lock..

-

**Comment by such87** [comment]
Unfortunately this is not possible. I work on a shared academic cluster where the admins will not allow this. I had raised this issue with them before.

Can you please shed some light on the issues that can happen if I lock on a local directory ?

**Comment by frankseide** [comment]
Please point your sysadmins to [https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard]:
```
/var/lock  |  Lock files. Files keeping track of resources currently in use.
```
I am not a Linux specials, but as I understand it, `/var/lock` implements the official Linux mechanism for global locks. If it is not writeable, no program that requires global locks can function in your environment.

Note that in the past, CNTK incorrectly used `/var/tmp` instead. Maybe your sysadmins refused to make /var/tmp accessible.

**Comment by saonim** [comment]
If you specify the deviceID, the problem with /var/lock permission will go away. Example:
`cntk configFile=AlexNet.cntk configName=AlexNet deviceId=0
`
However, I am not sure how specify multiple GPUs this way. @frankseide : any suggestion?

**Comment by frankseide** [comment]
Please first verify that /var/lock does not work. It really should. We may be talking about a left-over of an old bug where we used /var/tmp, for which we cannot generally assume it will be writeable. But we no longer use /var/tmp for this reason.

**Comment by saonim** [comment]
@frankseide 

the problem still exists. I am using the binary with the SHA1: 2f9a48c71dc0a6097498cb7e90ac3b151ab536dd 

I have the following permissions on my system:
lrwxrwxrwx  1 root root for /var/lock

drwxr-xr-x  6 root    root for /run/lock

Still I got the error:

EXCEPTION occurred: Acquire: Failed to open lock file /var/lock/DBN.exe GPGPU querying lock: Permission denied.

When I changed the permission to:
drwxrwxrwx  6 root    root for /run/lock

The program runs without problem or set the deviceId

**Comment by mahilleb-msft** [comment]
@saonim: can you provide the "ls -l /run/lock" output from your machine? Have you been by chancing, running CNTK from multiple users?

**Comment by frankseide** [comment]
```
drwxr-xr-x 6 root root for /run/lock
```
I am not super-familiar with Linux, but doesn't this mean that only root can create locks? If so, wouldn't that mean that any program using global locks will not work in your environment unless run as root? If so, this could mean that your specific environment is not conforming to the Linux [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). You may be able to convince your IT department to make your installation compliant.

**Comment by saonim** [comment]
@mahilleb-msft : Here is the output of `ls -l /run/lock`

```
drwxrwxr-x 2 root lock  40 Mar 23 17:24 lockdev
drwx------ 2 root root  40 Mar 23 17:24 lvm
drwxr-xr-x 2 root root  40 Mar 23 17:24 ppp
drwxr-xr-x 2 root root 120 Mar 24 09:17 subsys

```

**Comment by saonim** [comment]
@frankseide This is default behavior by CentOS - conforms to what redhat policy is. It would be easier for users if CNTK uses a better location (such as /tmp) which is usually writable across platforms.

**Comment by ant0nsc** [comment]
We have a similar issue on our Linux GPU cluster. here's as far as I've established the chain of events:
1) User A runs CNTK. Places the lock file "DBN.exe..." in /var/lock, with permissions -rw-r--r--, owned by user A
2) After user A's CNTK terminates, the file is still present in /var/lock
3) User B runs CNTK, setting deviceID explicitly to 1. This runs happily on GPU 1 (confirmed in the logs). This instance of CNTK does not create a new lock file?
Is this the expected behaviour?

Oh, and getting rid of this legacy name "DBN.exe..." would be very very welcome. When I first saw an exception where this lock file name was mentioned, I completely could not understand what this is about, the spaces in the filename made me think this is part of the error message.

**Comment by leonardoaraujosantos** [comment]
Hi, I've solved this by giving the write permission to the lock directory (Probably not the best), but works
sudo chmod -R a+w /run/lock

**Comment by kcgthb** [comment]
> Can you raise this with your sys admin? /var/lock must be writeable.

Definitely not, `/var/lock` should only be writable by a limited amount of accounts for security reasons. RHEL makes it writable by `root` and the `lock` group.
See https://bugzilla.redhat.com/show_bug.cgi?id=509938 for details

The recommended way is to create an application-specific subdirectory in `/var/lock` and give it the correct permissions. Or use some other writable directory. In any case, having a hard-coded path in the application is... not best practice.

**Comment by jbalma** [comment]
changing to /tmp worked for me up to 16 ranks with a single gpu per node. Edit the CrossProcessMutex.h definition:

CrossProcessMutex(const std::string& name)
        : m_fd(-1),
          m_fileName("/var/lock/" + name)

which becomes this:

CrossProcessMutex(const std::string& name)
        : m_fd(-1),
          m_fileName("/tmp/" + name)
 
...And then below that change the permissions for the resulting directory:

int fd = open(m_fileName.c_str(), O_WRONLY | O_CREAT, 0666);

This worked well up to 16 GPUs, but I had to remove deviceId="Auto" and set it to "0" instead to go beyond 16. Not sure why, but I hit the same file lock error when using Auto regardless of permissions in the created /tmp directories.

I think this might serve as a workaround if it's decided to stay in /var/lock, but I agree that it's probably better to use /tmp, at least on shared systems.

**Comment by ikzk** [comment]
One year passed. This problem is still unsolved.

**Comment by wolfma61** [comment]
Unfortunately this is true 
Closing this one
#62 is exactly about this problem
