### ISSUE TITLE
Is there a method to automatically convert grayscale images to BGR

### ISSUE THREAD

**Issue by calledbymountains** [Microsoft/CNTK#2512]
If a dataset has a mix of RGB (BGR for OpenCV) and gryascale images, sometimes it is preferable to convert grayscale to BGR by channel replication. 

Is there a way to specify this in the present build of CNTK ?

**Comment by cha-zhang** [comment]
Present build will just load images as RGB, even it's grayscale. This is actually taken care of by OpenCV.

**Comment by eldakms** [comment]
you need to specify "yourimagedeserializer['grayscale'] = true", if i'm not mistaken, so that OpenCV can read them correctly.

**Comment by calledbymountains** [comment]
Ohh bollocks... I misread the source code.... Apologies. Closing now.
