### ISSUE TITLE
imbalance on GPU processes

### ISSUE THREAD

**Issue by hpjeonGIT** [Microsoft/CNTK#2514]
Hi, 
I have been testing cntk (v2.2, source build) using openmpi 2.1.2 on centos7.3.
Using Examples/Image/Classification/GoogLeNet/InceptionV3/BrainScript/InceptionV3.cntk, I use command like:  time mpirun -n 4   --mca btl_sm_use_knem 0  cntk configFile=InceptionV3.cntk parallelTrain=true deviceId=auto stderr=4gpu

NVidia-smi shows that there are 7 (?) cntk sits on 4 gpus as shown below, with different gpu memory consumption. Sum of each gpu look same, showing balance on memory consumption but not sure why 7 cntk executable appear?  Benchmark using dlbench(https://github.com/hclhkbu/dlbench) shows one cntk per GPU. I am afraid that multiple cntks on each GPU may affect the performance? Any coments are appreciated.

Thanks,

Byoungseon

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       780    C   cntk                                          8464MiB |
|    0       781    C   cntk                                           273MiB |
|    0       782    C   cntk                                           273MiB |
|    0       783    C   cntk                                           273MiB |
|    1       782    C   cntk                                          8191MiB |
|    2       783    C   cntk                                          8191MiB |
|    3       781    C   cntk                                          8191MiB |
+-----------------------------------------------------------------------------+

**Comment by cha-zhang** [comment]
We have not noticed this before. Not sure how to proceed but maybe you can share more about your setup?

**Comment by hpjeonGIT** [comment]
Hi, Thanks for the reply.
I followed the instruction guide by MS and have same situations using openmpi 1.10.7, 2.1.2, 3.0.0, and intel impi 2018, finding same behavior for all cases. Configurations of openmpi/cntk are enlisted below. Any comments are appreciated.

Thanks,

Byoungseon
-------------------------------------------------------------------------------------------

1. OpenMPI configurations are:  ./configure --prefix=$HOME/2.1.2_cuda8 --with-cuda=/usr/local/cuda/8.0/include  --disable-dependency-tracking --disable-silent-rules --enable-binaries --enable-mpi-cxx --enable-mpi-cxx-seek --enable-shared --enable-openib-rdmacm --enable-fast-install --enable-mpi-thread-multiple --with-devel-headers --with-hwloc=internal --with-tm=/opt/pbs/ --with-verbs=yes --with-io-romio-flags=--with-file-system=ufs+nfs+lustre --enable-oshmem --with-knem=/opt/knem-1.1.2.90mlnx2 --with-mxm=/opt/mellanox/mxm --with-platform=contrib/platform/mellanox/optimized 

2. cntk configurations: ../../configure --cuda=yes --python=yes --mpi=yes --gdr=yes --with-cuda=/usr/local/cuda/8.0 --with-cub=/usr/local/cub/cub-1.4.1 --with-gdk-include=/usr/local/cuda/8.0/include --with-gdk-nvml-lib=/usr/lib64 --with-cudnn=/usr/local/cudnn/6.0/cuda_8.0/ --with-mkl=/usr/local/CNTKcustomMKL --with-kaldi=/usr/local/kaldi/kaldi-5.1 --with-opencv=/usr/local/opencv/330_p2_fastmath --with-libzip=/usr/local/libzip/1.3.0 --with-boost=/usr/local/boost/1.65 --with-protobuf=/usr/local/protobuf/3.4 --with-py-versions='27 36' --with-py27-path=/usr/local/python_data_analytics/2.7.13 --with-py36-path=/usr/local/python_data_analytics/3.6.2 --with-swig=/usr/local/swig/3.0.12 --with-mpi=/usr/local/openmpi/2.1.2_cuda8 --1bitsgd=yes

**Comment by hpjeonGIT** [comment]
Looks like this issue has been reported at: https://github.com/Microsoft/CNTK/issues/2442.
Just memcopy? I will close this issue.
