### ISSUE TITLE
Doesn't cuda9 support cntk?

### ISSUE THREAD

**Issue by CalmDownForever** [Microsoft/CNTK#2517]
Taday, I install a cuda9.0 in my linux computer. When I test cntk code, it seems that GPU doesn't work.
I added 'try_set_default_device(gpu(0))' in my code.But the result is:
Selected CPU as the process wide default device.
-------------------------------------------------------------------
Build info: 

                Built time: Sep 15 2017 07:30:54
                Last modified date: Fri Sep 15 04:28:48 2017
                Build type: release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA version: 9.0.0
                CUDNN version: 6.0.21
                Build Branch: HEAD
                Build SHA1: 23878e5d1f73180d6564b6f907b14fe5f53513bb
                MPI distribution: Open MPI
                MPI version: 1.10.7
-------------------------------------------------------------------
So what's gong on?
Thanks!

**Comment by cha-zhang** [comment]
CNTK doesn't support cuda 9.0 yet. This is something we are working on in this iteration, although we are encountering some driver issues. We will try to deliver it by the end of this iteration.

**Comment by CalmDownForever** [comment]
Okey！

**Comment by KeDengMS** [comment]
I have an ongoing work in branch kedeng/FP16 that enables CUDA 9 for CNTK. You can try it out if you only need float32 computation. That branch also has WIP for supporting FP16, but not mature yet. Please help yourself to build from source if you want to be the first user for CNTK in CUDA9.

**Comment by MMRohe** [comment]
Hey ! 
any update on this issue ? does CNTK now supports cuda 9.0 (I think it does not but I am not sure) and if not is there any ETA on the implementation ?

@KeDengMS I could not find the branch you are talking about, is it still available or would you have another branch that enables CUDA 9.0 ?

Thanks !

**Comment by KeDengMS** [comment]
I've squashed the changes into https://github.com/Microsoft/CNTK/tree/kedeng/preview24, and added build instructions. Please give it a try.

**Comment by KeDengMS** [comment]
CUDA 9 support is in latest master. Please check it out.
