### ISSUE TITLE
Group Convolution with learnable kernels

### ISSUE THREAD

**Issue by jeandebleau** [Microsoft/CNTK#2521]
Can we use this feature into a learnable convolutional layer ?

I cannot make it work in the case of a learnable convolutional layer. 

I would like to use a depthwise-separable convolutional layer. For instance , I would like to use a number of groups that equals the number of input channels ( 1 spatial kernel per channel ).
Is it a work in progress ?

**Comment by jeandebleau** [comment]
Can spandantiwari confirm than the group convolution feature is not usable with learnable kernels ? but simply as convolution with constant kernels ?

**Comment by spandantiwari** [comment]
@jeandebleau - What error are you seeing? I think this maybe related to a bug in group convolution that was fixed recently. Could you please try again with latest master or at least latest release CNTK 2.3.1 and see if it works. If not please share the error stack and re-open this issue.
