### ISSUE TITLE
BUILD error MSB3030 exited with code 9009

### ISSUE THREAD

**Issue by 1132520084** [Microsoft/CNTK#253]
I am trying to setup CNTK on my windows system(8GB RAM and Quadro K2000 GPU).Everything went smooth till "Building CNTK".I got the following errors:

Error	1	**error MSB3073**: The command "if exist "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cublas64_*.dll" (xcopy /Y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cublas64_*.dll" E:\cntk\CNTK-master\x64\Debug\)
if exist "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cusparse64_*.dll" (xcopy /Y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cusparse64_*.dll" E:\cntk\CNTK-master\x64\Debug\)
if exist "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\curand64_*.dll" (xcopy /Y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\curand64_*.dll" E:\cntk\CNTK-master\x64\Debug\)
if exist "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cudart64_*.dll" (xcopy /Y "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\cudart64_*.dll" E:\cntk\CNTK-master\x64\Debug\)
if exist "C:\NVIDIA\cudnn-4.0\cuda\bin\cudnn64_4.dll" (xcopy /Y "C:\NVIDIA\cudnn-4.0\cuda\bin\cudnn64_4.dll" E:\cntk\CNTK-master\x64\Debug\)

:VCEnd" **exited with code 9009**.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	MathCUDA
Error	2	**error MSB3073**: The command "xcopy /D /I /Y "C:\AMD\acml5.3.1\ifort64_mp\lib\*.dll" E:\cntk\CNTK-master\x64\Debug\
:VCEnd" **exited with code 9009**.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	Math
Warning	3	warning : ImageReader requires the OpenCV library to build. Please see https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#opencv for installation instructions.	E:\cntk\CNTK-master\Source\Readers\ImageReader\ImageReader.vcxproj	155	5	ImageReader
Warning	4	warning : zlib and libzip libraries were not found, ImageReader will be built without zip container support. Please see https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#libzip for installation instructions.	E:\cntk\CNTK-master\Source\Readers\ImageReader\ImageReader.vcxproj	156	5	ImageReader
Error	5	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libacml_mp_dll.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\MathTests\MathTests.vcxproj	164	5	MathTests
Error	6	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libifcoremd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\MathTests\MathTests.vcxproj	164	5	MathTests
Error	7	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libifportmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\MathTests\MathTests.vcxproj	164	5	MathTests
Error	8	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libmmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\MathTests\MathTests.vcxproj	164	5	MathTests
Error	9	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\svml_dispmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\MathTests\MathTests.vcxproj	164	5	MathTests
Error	10	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\svml_dispmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\MathTests\MathTests.vcxproj	164	5	MathTests
Error	11	error MSB3073: The command "if exist "%ProgramW6432%\NVIDIA Corporation\NVSMI" xcopy /I /D /Y "%ProgramW6432%\NVIDIA Corporation\NVSMI\nvml*.dll" E:\cntk\CNTK-master\x64\Debug\
:VCEnd" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	ComputationNetworkLib
Error	12	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libacml_mp_dll.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\ReaderTests\ReaderTests.vcxproj	195	5	ReaderTests
Error	13	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libifcoremd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\ReaderTests\ReaderTests.vcxproj	195	5	ReaderTests
Error	14	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libifportmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\ReaderTests\ReaderTests.vcxproj	195	5	ReaderTests
Error	15	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\libmmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\ReaderTests\ReaderTests.vcxproj	195	5	ReaderTests
Error	16	error MSB3030: Could not copy the file "E:\cntk\CNTK-master\x64\Debug\\UnitTests\..\svml_dispmd.dll" because it was not found.	E:\cntk\CNTK-master\Tests\UnitTests\ReaderTests\ReaderTests.vcxproj	195	5	ReaderTests
Error	17	error MSB3073: The command "if exist "%ProgramW6432%\NVIDIA Corporation\NVSMI" xcopy /I /D /Y "%ProgramW6432%\NVIDIA Corporation\NVSMI\nvml*.dll" E:\cntk\CNTK-master\x64\Debug\
:VCEnd" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	EvalDll
Error	18	error MSB3073: The command "if exist "%ProgramW6432%\NVIDIA Corporation\NVSMI" xcopy /I /D /Y "%ProgramW6432%\NVIDIA Corporation\NVSMI\nvml*.dll" E:\cntk\CNTK-master\x64\Debug\
:VCEnd" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	SGDLib
Error	19	error MSB3073: The command "if exist "%ProgramW6432%\NVIDIA Corporation\NVSMI" xcopy /I /D /Y "%ProgramW6432%\NVIDIA Corporation\NVSMI\nvml*.dll" E:\cntk\CNTK-master\x64\Debug\
:VCEnd" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	ActionsLib
Error	20	error MSB3073: The command "if exist "%ProgramW6432%\NVIDIA Corporation\NVSMI" xcopy /I /D /Y "%ProgramW6432%\NVIDIA Corporation\NVSMI\nvml*.dll" E:\cntk\CNTK-master\x64\Debug\
:VCEnd" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	CNTK

--------------------------
The paths of the CNTK is E:\cntk\CNTK-master, and the errors also go wrong when i set path to the root directory.
Any idea how to fix it? Thanks!!!(please ignore the error about the Image Reader)

**Comment by alexeyo26** [comment]
First immediate hunch is to check that your CUDA and ACML paths set via ```CUDA_PATH```, ```CUDA_PATH_V7_0``` and ```ACML_PATH``` correspond to where these components are installed on your system. See https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows

**Comment by 1132520084** [comment]
thank you
I have followed the setup instruction, and the path is same as that gived in the instruction.however, the error occurrs again...
finally i delete the code in

**Comment by 1132520084** [comment]
finally i delete the error code in Microsoft.CppCommon.targets.And i manually copy the dlls to the debug folder.
