### ISSUE TITLE
Convolution

### ISSUE THREAD

**Issue by csolorio** [Microsoft/CNTK#2531]
Hi.

I've been making small tests with some elements of CNTK. While testing convolution, I used a minimal model to test the actual workings of the layer.

I evaluated the following model on a RGB 32x32 image (1x3x32x32 input)
```
c = Convolution((1,1), 3, init=1.0, activation=None, pad=True, strides=(1,1), bias=False)(input)
```
After evaluating, I get a 3x32x32 output, yet the values are not what I was expecting. What is the layer doing exactly? I got as a result a grayscale image (due to the 3 32x32 matrix having the same values) when I was expecting exactly the same input. Am I misunderstanding what it's supposed to be doing?

Regards

**Comment by cha-zhang** [comment]
The padding may cause your boundary to look different. Center region should be constant.

**Comment by csolorio** [comment]
I'm evaluating the convolution using this minimal code and the definition above (changed Pad to false and get the same results, but with a 1,1 kernel, is padding even relevant??
```
input_var = C.input_variable((num_channels, image_height, image_width), name='features')
#Load image code ---
data = reader_train.next_minibatch(1, input_map=input_map)
 imgf = img_data[0][0]
 print(imgf.shape)
#prints the shape as expected
im1 = Image.fromarray(np.uint8(np.rollaxis(imgf, 0, 3)))
im1.save('test.jpg') #The image is exactly as the original

evaluated_data = c.eval(img_data[0]) 
```
The final data of the matrix is aproximately the triple of the values of the input and all 3 32x32 matrices. Why is that if the kernel is (1,1), there's no activation function and the padding is (or should be, I don't know) irrelevant (but still changed to false).  Am I doing something wrong?

**Comment by bencherian** [comment]
If the input image is 1 in every channel for every pixel, the output for your convolution will be 3 in every channel for every pixel. A convolutional layer is typically defined as fully connected across the channels...a 1x1 convolution is not a no-op. In your case, you have set the weight for each of the 3 input channels to 1, so output for each channel is (1*R + 1*B + 1*G).

**Comment by csolorio** [comment]
Aaaaah! Ok, now I get it! Thanks!
