### ISSUE TITLE
Is it possible to crop image to specific size/location using cntk.io.transforms?

### ISSUE THREAD

**Issue by ahoink** [Microsoft/CNTK#2534]
when creating a minibatch source you can perform transforms on the images. Is it possible to crop to a specific location? In cntk.io.transforms I see crop_type='center', 'randomside', and 'randomarea', but I want to crop to the top left corner, not the center, because my image set has distinct features in that area.

**Comment by calledbymountains** [comment]
No. In the present build, it is not possible. You would need to modify the CropTransformer

**Comment by ahoink** [comment]
That seems to be the case. Thanks, I'm closing the issue
