### ISSUE TITLE
Cuda 7.5 on linux?

### ISSUE THREAD

**Issue by jhludwig** [Microsoft/CNTK#254]
Any idea when CNTK will support cuda 7.5 on linux?

**Comment by mradmila** [comment]
Very soon :) Without committing to the exact date, I can say that we are actively working on that and a few other improvements. A few weeks would be a reasonable estimate.

**Comment by wolfma61** [comment]
closing this request ... 
yes, it is really going to happen .... soonish ....

**Comment by mahilleb-msft** [comment]
Closing, default CUDA is 8.0 by now :)
