### ISSUE TITLE
CRT init error on win7/64

### ISSUE THREAD

**Issue by jariahlstedt** [Microsoft/CNTK#2548]
I compiled CNTK 2.2 with win7 pro 64 (VS2015). CPU-only compilations run fine, but GPU-ones do not. Running cntk.exe raises CRT init error R6030.
Does anyone have a solution to this? I would much appreciate it.

**Comment by cha-zhang** [comment]
https://msdn.microsoft.com/en-us/library/9ecfyw6c.aspx This seems to be related to your security software?

**Comment by jariahlstedt** [comment]
I only have MS Security Essentials. It hasn't affected before, i.e. cntk 2.0 beta 11 worked fine with GPU.

**Comment by cha-zhang** [comment]
That's strange. For v2.2, we have added requirement for OpenCV. Is that something you were already using, or you added because of v2.2?

**Comment by jariahlstedt** [comment]
I wasn't using OpenCV until with v2.2 install. Earlier I installed the suggested components - if OpenCV wasn't on the install list in January, then I didn't install it then. So that could be the culprit?

**Comment by cha-zhang** [comment]
I don't know. We will investigate.

**Comment by jariahlstedt** [comment]
When installing cntk v2.2 three weeks ago, I installed latest versions of other prerequisites, also. That included inadvertent install of Win10 version of cuDNN (and CUDA 9.0, which was removed). Now that has been fixed, I installed Win7 version of cuDNN from Nvidia site manually. I also installed latest CUDA 8.0 with the cuDNN patch. Still the same error. I wonder if CUDA 9.0 mishap affects this somehow.
Build warnings and errors (Debug):
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning		The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).	MathCUDA	C:\repos\cntk\Source\Math\CUDACOMPILE	1	
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/PROFILE' specification	Math	C:\repos\cntk\Source\Math\LINK	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	Math	C:\repos\cntk\Source\Math\BatchNormalizationEngine.obj	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:ICF' specification	BrainScriptTests	C:\repos\cntk\Tests\UnitTests\BrainScriptTests\BrainScriptEvaluator.obj	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:ICF' specification	ReaderTests	C:\repos\cntk\Tests\UnitTests\ReaderTests\CNTKBinaryReaderTests.obj	1	
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/PROFILE' specification	CNTKLibraryCSBinding	C:\repos\cntk\bindings\csharp\Swig\LINK	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	CNTKLibraryCSBinding	C:\repos\cntk\bindings\csharp\Swig\cntk_cs_wrap.obj	1	
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/PROFILE' specification	CNTKLibraryJavaBinding	C:\repos\cntk\bindings\java\Swig\LINK	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	CNTKLibraryJavaBinding	C:\repos\cntk\bindings\java\Swig\cntk_java_wrap.obj	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	EvalWrapper	C:\repos\cntk\Source\Extensibility\EvalWrapper\Cntk.Common-2.2d.lib(MPIWrapper.obj)	1	
Warning	LNK4199	/DELAYLOAD:nvml.dll ignored; no imports found from nvml.dll	EvalTests	C:\repos\cntk\Tests\UnitTests\EvalTests\LINK	1	
Warning	LNK4199	/DELAYLOAD:cudart64_80.dll ignored; no imports found from cudart64_80.dll	EvalTests	C:\repos\cntk\Tests\UnitTests\EvalTests\LINK	1	
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/PROFILE' specification	CPPEvalClientTest	C:\repos\cntk\Tests\EndToEndTests\EvalClientTests\CPPEvalClientTest\LINK	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	CPPEvalClientTest	C:\repos\cntk\Tests\EndToEndTests\EvalClientTests\CPPEvalClientTest\CPPEvalClient.obj	1	
Warning	LNK4075	ignoring '/INCREMENTAL' due to '/PROFILE' specification	CPPEvalExtendedClientTest	C:\repos\cntk\Tests\EndToEndTests\EvalClientTests\CPPEvalExtendedClientTest\LINK	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification	CPPEvalExtendedClientTest	C:\repos\cntk\Tests\EndToEndTests\EvalClientTests\CPPEvalExtendedClientTest\CPPEvalExtendedClient.obj	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:ICF' specification	NetworkTests	C:\repos\cntk\Tests\UnitTests\NetworkTests\BrainScriptEvaluator.obj	1	
Warning	LNK4075	ignoring '/EDITANDCONTINUE' due to '/OPT:ICF' specification	V2LibraryTests (Tests\UnitTests\V2LibraryTests)	C:\repos\cntk\Tests\UnitTests\V2LibraryTests\BlockTests.obj	1

**Comment by jariahlstedt** [comment]
I ran cntk.exe (Debug build) in Safe Mode to exclude DLL-call trapping by any startup program, such as some security programs. Did not help.

The following was printed out before crash:
***** VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****

**Comment by cha-zhang** [comment]
We are working to remove dependency on OpenCV. Please stay tuned.

**Comment by jariahlstedt** [comment]
CNTK v2.3 didn't solve the issue, I built it without opencv, but same error persists.
However, I solved the problem by installing Win10, which was overdue anyway.

Thank you cha-zhang for the help!

**Comment by cha-zhang** [comment]
@jariahlstedt That's great to know. I thought in v2.3 we have removed the OpenCV hard dependency. Anyhow, glad it works now.

**Comment by ebarsoumMS** [comment]
Can you run Release_NoOpt instead of debug build?

**Comment by jariahlstedt** [comment]
Today I built Release and Release_NoOpt, which both failed to run. However Release_CpuOnly runs fine (Win7).
I will retain Win7 configuration of CNTK to try any furher suggestions - It would be nice to have a working Win7 CNTK, also.
