### ISSUE TITLE
CNTK for speaker recognition

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#2552]
Hi,
 
I am using cntk for speaker recognition. I am a beginner so please let me know whether I am on the right track. (I am using brainscript).I followed couple of speech examples in cntk tutorials.
Steps I followed,
1) I used htk toolkit and completed data preparation steps(i have .scp files and label files)
2) I used cntk and gave these input files and when I output the results using htkmlfwriter I got feature dimension data. 
I am confused why the network output is feature again. If i am not wrong I am using cntk to train the model using  feature and label files and I am expecting label for the given Test feature file. I used network dimensions as 492:512:3:463
where 492 is input
512:3 is hidden hidden layers and units
463 is number of speakers
Please let me know where I am going wrong. I posted couple of issues about the output interpretations and got a response saying you have to use softmax at the output (but I am getting feature as ouput )
Do I need to use htk again to get labels from the cntk output?
Is it like HTK at the first end fr feature extractio then CNTK for model and again HTK to decode labels?

I used cntk for data classification(where feature and labels are text format) and I got the expected label outputs(probabilities). But I am really having trouble understanding how to use cntk to get labels as  output. 
Any suggestion will do.
 [@frankseide I saw your comments on various speech problems. If you could give any comments for this particular issue would help me alot) 
Thanks

**Comment by cha-zhang** [comment]
what do you mean you are getting feature as output? Do you get a vector of 463 dimension, or something else? What do you expect the output should be?

**Comment by vidyatshetty** [comment]
@cha-zhang  Thanks for writing. 
This is how my scp file, mlf file , statelist  and config file looks like

[TrainingScp.txt](https://github.com/Microsoft/CNTK/files/1425721/TrainingScp.txt)
[TimitStateList.txt](https://github.com/Microsoft/CNTK/files/1425716/TimitStateList.txt)

[trainMlf.txt](https://github.com/Microsoft/CNTK/files/1425717/trainMlf.txt)

I am trying to follow the speech examples in example folder. I am labeling the entire feature file as one label(speaker id) in the MLF file. Please take a look at the files i have attached and let me know if i am on the right path(I am trying to give inputs to cntk in the same way as HTK toolkit). 
when I give one feature file to the testing network I am expecting the label as output .
but all I am getting is 429*463 dimension data written to the output file.(please look at my config file)
I want the output of the network to be label. is there anyway i could use label_lookup to output the label.(Please correct me if i am wrong).
I saw image classification example in the below link ,here in the eval function when the user gives the "truck image" as input to the testing network it outputs the label as "truck". I need something like this when I give the feature file to the testing network it should give output as label.
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_201B_CIFAR-10_ImageHandsOn.ipynb
 
Please let me know where i am going wrong.
Thanks

**Comment by cha-zhang** [comment]
Can you post your model training script?

**Comment by vidyatshetty** [comment]
@cha-zhang This is how my config file looks like.
[config2.txt](https://github.com/Microsoft/CNTK/files/1427745/config2.txt)

I have one more question I am trying to use python aswell. When I use HTKFeatureDeserializer and HTKMLFDeserializer I get the following error
    **train_data_reader = C.io.MinibatchSource([train_feature_stream, train_label_stream], frame_mode = False, randomize=True, randomization_window_in_chunks=0, randomization_window_in_samples=0, randomization_seed=0, )
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\io\__init__.py", line 226, in __init__
    source = cntk_py.create_composite_minibatch_source(config)
RuntimeError: parsedpath: this mode requires an input script with start and end frames given**


In brainscript if i specify readMethod=rollingwindow instead of readMethod=Blockrandomize the error will be gone . Is there any way while using HTKDeserializer  in python or in brainscript  i can specify readMethod as rollingwindow?

**Comment by cha-zhang** [comment]
I don't see any models defined in the config file you shared.

**Comment by diemmano** [comment]
Hi @vidyatshetty . Any hint on how you overcame the "RuntimeError: parsedpath : this mode requires an input script with start and end frames given"

**Comment by vidyatshetty** [comment]
@diemman The .mfc file requires just one new line . Please check if you have multiple new lines and delete them and see if that is the issue.

**Comment by vidyatshetty** [comment]
@diemmano  The .mfc file requires just one new line (after the end of all mfc entries). Please check if you have multiple new line try to delete them and see if this works.

**Comment by diemmano** [comment]
Thank you for your quick reply! Unfortunately that does not seem to be the issue for my case. Need to keep troubleshooting, thank you again.

**Comment by vidyatshetty** [comment]
Please check if you have set  readMethod=rollingWindow. Hope this helps.

**Comment by vidyatshetty** [comment]
Do you have a new line in the stateList file?

**Comment by diemmano** [comment]
Yes labelMap file has a new line at the end too. Going back to .mfc files,(I originally thought you were referring to the .mlf files actually):  are your .mfc files binary files or text files? I have mine saved as binaries and I wonder if that introduces issues outside BrainScript (i.e. when using Python)
