### ISSUE TITLE
How to define the MinibatchSource when using FreeDimension?

### ISSUE THREAD

**Issue by newoneincntk** [Microsoft/CNTK#2554]
Because the input is FreeDimension, What input_dim should be used in the MinibatchSource like following
        features  = StreamDef(shape=input_dim, is_sparse=False, scp=path1)

**Comment by cha-zhang** [comment]
In Faster-RCNN we feed data with Numpy arrays, as when FreeDimension is used, most likely we only train with one sample per image. 

Are you processing a different kind of data from images?

**Comment by newoneincntk** [comment]
Thank you for your reply, I used the HTK format for speech processing.  To build an utterance to utterance framework,  because the length of the utterance is varying, I think the FreeDimension axis should work. Is there so example to feed data using the MinibatchSource?

**Comment by cha-zhang** [comment]
If this is speech, why you don't use sequence processing? In CNTK we have dynamic axis for handling such cases. Check the simple example here: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Speech/AN4/Python/HTK_LSTM_Truncated_Distributed.py

**Comment by newoneincntk** [comment]
Thank you for your reply, Because I used the 2D-FFT feature of the speech, very similar to the image, and CNN is proved to be more effective.  Is there a simple example to feed Freedimension data? @cha-zhang

**Comment by cha-zhang** [comment]
Have you checked the faster-RCNN example? 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FasterRCNN/FasterRCNN_train.py

**Comment by newoneincntk** [comment]
Thank you! I see it use ObjectDetectionMinibatchSource, and it is too complex...

**Comment by spandantiwari** [comment]
@newoneincntk - I would recommend looking at the faster RCNN example under the chazhang/faster_rcnn branch because if shows the use of FreeDimension for 2D images: https://github.com/Microsoft/CNTK/tree/chazhang/faster_rcnn
