### ISSUE TITLE
Python offline installation

### ISSUE THREAD

**Issue by csolorio** [Microsoft/CNTK#2559]
Hi. 

I have access to a powerful server that - for security reasons that I cannot change - has not internet connection. Is there a way to install the python development environment without internet connection? Can I copy the downloaded anaconda package in an internet-connected pc to the server? Are there any other alternatives?

Best regards.

**Comment by bencherian** [comment]
Do you want an environment to build CNTK or just use it in Python? The second is easy enough...just download the Aanconda installer and put it on your server. Then install the wheel into the environment. Everything should just work.

**Comment by csolorio** [comment]
I just want to develop using python. So far, I've been doing the following:
1. Download, transfer and running the Anaconda installer to the server without internet connection.
2. Use the following command in the Anaconda prompt, from my pc with internet connection, to download the CNTK package and all its dependencies to separate dir:
``pip download -d U:\My\Path\To\Dir <CNTK_wheel_url>``.
Since the transfer is very slowly, It hasn't completed yet. The last step I'm going to do is:
3. Run the following command from the server. ``pip install --no-index --find-links=U:\Path\Where\Wheel\Was\Extracted cntk-2.2-cp27-cp27m-win_amd64.whl``

Do you think it will work?

**Comment by bencherian** [comment]
You can simply download the wheel and copy it to your server and run `pip install <name of wheel file>`

**Comment by csolorio** [comment]
Forgot to comment and close it, but yeah. It worked. Thanks!
