### ISSUE TITLE
value error while training with cross entropy

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#2563]
Hi

I get the following error while training my mode using cross entropy:

> Traceback (most recent call last):
  >File "ce_pretrained_ctc.py", line 121, in <module>
    trainer_ce.train_minibatch(mb_ce)
  File "/home/aspl/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/train/trainer.py", line 170, in train_minibatch
    arguments, device)
  File "/home/aspl/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.py", line 2804, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
ValueError: Different minibatch layouts detected (difference in sequence lengths or count or start flags) in data specified for the Function's arguments 'Input('label_ce', [#, *], [61])' vs. 'Input('feature', [#, *], [792])', though these arguments have the same dynamic axes '[#, *]'

**Comment by hajix** [comment]
the problem caused by non equal length of scp/mlf file.

**Comment by trudeaua** [comment]
@hajix I'm having the exact same error, but with a new version of CNTK i believe (i don't have SCP or MLF files). Do you know what the equivalent solution would be in CNTK 2.5.1? Thanks
