### ISSUE TITLE
Upgrade SoftMax() definition with ReduceLogSum()

### ISSUE THREAD

**Issue by vermorel** [Microsoft/CNTK#2565]
In `CNTK.Core.bs`, the implementation of `SoftMax()` is still the naive fraction. There is already a comment hinting that `ReduceLogSum()` should be used instead when it becomes available. `ReduceLogSum()` has been available for a while now. I would suggest to upgrade this implementation. The `SoftMax()` is used in many examples of CNTK and BrainScript is a very nice entry point.

**Comment by ebarsoumMS** [comment]
@vermorel can you submit a PR?

**Comment by KeDengMS** [comment]
Thanks @vermorel, the change has been merged into master
