### ISSUE TITLE
pycuda interpolation 

### ISSUE THREAD

**Issue by tobyclh** [Microsoft/CNTK#2567]
Hello, just get my hands dirty with some online images synthesis with rendering.
1. Is it possible directly pack array on nvidia cards as cntk array?
2. Is it possible to directly transfer array from 1 gpu to another
say I rendered with the first gpu and train my network with the second. Would be nice if I can just send it through directly.

**Comment by tobyclh** [comment]
if it doesn't exist, would be nice to have a direction for me to know where I should be looking at to implement this. Cheers.

**Comment by KeDengMS** [comment]
NDArrayView can represent a buffer in GPU memory, however I haven't explored interop with pycuda on it yet. Your contributions are welcome!
