### ISSUE TITLE
minibatch vs sentence-length learning

### ISSUE THREAD

**Issue by pnpetkov** [Microsoft/CNTK#2569]
In the context of ASR, I have noticed that when training a DNN acoustic model I get consistently higher performance when using a minibatch size, e.g., 256, instead of the full utterances (which can amount to 500-600 frames). In both cases the learning rate is defined per sample and is identical. 

I would like to know if this result is expected and, possibly, how to achieve equally high performance when training at the sentence level. My guess is that longer sentences are biasing the learning process. Therefore, I fixed the learning rate on the sentence level but this did not produce the improvement I was looking for. 

More specifically, for a 5x2048 DNN trained on about 16 hours of data, I get WER=27.64 using a minibatch size of 256 and WER=29.06 when the minibatch adapts to the duration of the sentence. This is for the case where the learning rate is defined on a per-sample basis.

**Comment by JashaDroppo** [comment]
This result is expected.

There is a high degree of overlap in the information among the frames of each utterance. You might have ten examples of a given speech label in the utterance, but they are all from the same acoustic environment, the same speaker, and the same context.

As a result, training on full utterances won't give you the same amount of information as pulling frames randomly from your corpus (frame mode == TRUE).

**Comment by pnpetkov** [comment]
Thank you for this response! I understand the logic behind it. 

Would it be possible to generalize this idea to LSTMs? Specifically, if I don't use truncation but operate over the whole utterance, I guess I would have a similar problem. If instead I truncate to, e.g., 250 frames, then (as above) I will be achieving better mixing. Given that it's unlikely for history beyond the 250 frames to have any effect, I should expect the truncated version to outperform the one that operates on full utterances. Would this be the right way to reason about it? Thank you!
