### ISSUE TITLE
HTKDeserializer error

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#2574]
Hi,

Is it possible to use HTKFeatureDeserializer  for features(MFCC) and CNTKTextFormatDeserializer for labels  in brainscript?
**I wrote something like this in my config file** 
deserializers = (
                [
                    type = "HTKFeatureDeserializer"
                    module = "HTKDeserializers"
                    input = [
                        # Description of input stream to feed the Input node named "features"
                        features = [
                            dim=33
                            scpFile = "C:\Users\vidya\CNTK\TIMIT_ASR_FINAL\Data\cntkScp.txt"
                            format = "dense"
                        ]
                    ]
                ]:
                [
                    type = "CNTKTextFormatDeserializer" 
                    module = "CNTKTextFormatReader"
                    file = "C:\Users\vidya\CNTK\TIMIT_ASR_FINAL\Data\cntkLabels.txt"
                    input = [
                          features = [
		            dim = 1
		            format = "dense"
                                  ]
                        labels = [
                            dim = 3
                            format="dense"
                            phoneBoundaries=true
                        ]
                    ]
                ]
            ) 

**The scp file looks like this,**
1.mfc=C:\Users\vidya\CNTK\Examples\Speech\AN4\Data\000000000.chunk[0,367]
2.mfc=C:\Users\vidya\CNTK\Examples\Speech\AN4\Data\000000000.chunk[368,805]
3.mfc=C:\Users\vidya\CNTK\Examples\Speech\AN4\Data\000000000.chunk[806,1173]
4.mfc=C:\Users\vidya\CNTK\Examples\Speech\AN4\Data\000000000.chunk[1174,1421]
5.mfc=C:\Users\vidya\CNTK\Examples\Speech\AN4\Data\000000000.chunk[1422,1669]

**The label file looks like this,**

1|labels 0 0 1
2|labels 0 0 1
3|labels 0 0 1
4|labels 0 0 1
5|labels 0 0 1
6|labels 0 0 1

**I got the following error**

EXCEPTION occurred: Could not reconcile data between different deserializers. Keys of logical sequences do not match.

Can anyone tell me is it possible to use CTF and HTKDeserializer for speech example?
If so how should my scp file and label file be like?
please let me know

Thanks

**Comment by eldakms** [comment]
Did you try putting useNumericKeys = true in the reader config section? Thanks!

**Comment by vidyatshetty** [comment]
@eldakms  Yes i did but nothing works.

Thanks
