### ISSUE TITLE
CNTK on GPU hangs on initializing Adam optimizer

### ISSUE THREAD

**Issue by vburca** [Microsoft/CNTK#2581]
I initially had a model trained using Python 3.6 and CNTK 2.2 for CPU. Everything was working and I wanted to upgrade it to the GPU version. I did that by running the following, within my Anaconda environment:

`pip install --upgrade --no-deps https://cntk.ai/PythonWheel/GPU/cntk-2.2-cp36-cp36m-win_amd64.whl`

Right now my code hangs while trying to initialize the Adam optimizer:

    alpha = C.learning_parameter_schedule(0.001, minibatch_size=1)
    beta1 = C.momentum_schedule(0.9)
    beta2 = C.momentum_schedule(0.999)

    learner = C.adam(z.parameters, lr=alpha, momentum=beta1, variance_momentum=beta2)

Specifically, the last line is hanging. I am running my code in a Jupyter Notebook, if it makes any difference.

I also tried enforcing the device used, by using the following:

```
C.device.try_set_default_device(C.device.gpu(0))
C.device.use_default_device()
```

which outputs my GPU
> GPU[0] GeForce GTX 1070

If, instead, I leave it use the default device (which in this case seems to be the CPU), or even force it to use the CPU with:
```
C.device.try_set_default_device(C.device.cpu())
C.device.use_default_device()
```

> CPU

then the Adam optimizer seems to successfully initialize, and the code is not hanging anymore.

If useful, the model parameters passed into the optimizer are those of a Sequential model of Dense layers.

Does anyone know what could be the issue with this, and what is a possible fix?

Thank you!

**Comment by tobyclh** [comment]
you can check the usage of memory / usage of GPU with nvidia-smi
if it runs out of memory it could cause hanging (I think I encountered this once.)

**Comment by vburca** [comment]
I think I figured out what the issue is, but not sure if this is intended. Initially, I ran the above code in a Jupyter notebook, and the call to initialize the Adam optimizer was making the notebook's kernel halt and then crash.

I now tried the same code within a regular python file and everything seemed to work as intended.

Is the problem with Jupyter notebooks and CNTK on GPU a known issue?

**Comment by KeDengMS** [comment]
I think it's more likely a Jupyter notebook environment issue, since regular python file works. We have not dealt with any bug specific to Jupyter notebook. Please share your findings if any, thanks!
