### ISSUE TITLE
Build CNTK on windows without opencv

### ISSUE THREAD

**Issue by rajat95** [Microsoft/CNTK#2587]
Is it possible to build CNTK without Opencv support? Docs dont list Opencv as a requirement to ship windows based cntk apps, but the evaluation examples won't compile without the related Opencv dll.

**Comment by cha-zhang** [comment]
Starting CNTK v2.2 we have a hard dependency on OpenCV due to Tensorboard support. We are working to soften this dependency.

**Comment by manikjindal** [comment]
This has been fixed in CNTK v2.3. [Release notes](https://docs.microsoft.com/en-us/cognitive-toolkit/ReleaseNotes/CNTK_2_3_Release_Notes)
