### ISSUE TITLE
Convolution in C++ (Ver. 2.2)

### ISSUE THREAD

**Issue by adaber** [Microsoft/CNTK#2594]
Hi,

I am having a problem getting my code, that worked with the previous CNTK versions, to work with the latest CNTK version.

So, the first thing I noticed was that the shape format of an RGB image had changed from [W x H x C] to [C x W x H].

My problem is that I cannot get the convolution function to work correctly which could be due to this difference. I am not sure how to create the convolution and stride maps properly anymore.

This is how I used to do the convolution step:

// Create the convolution map
`auto convParams = CNTK::Parameter ({ KernelWidth, KernelHeight, numInputFeatPlanes, numOutputFeatPlanes } ... );`

// Convolution call
`auto convolution = CNTK::Convolution(convParams , inputLayer, { HStride, VStride, numInputFeatPlanes }, ...);`

So, if the input image/tensor is, say, [1024 x 320 x 3] and the number of output feature planes is 16, the convolution call will produce a [1024 x 320 x 16] tensor.

I cannot seem to figure out how to get this to work with the new tensor format ([C x W x H]). I don't know what dimensions my convolution and stride maps should be to get this to work ( to go from [3 x 1024 x 320] to [16 x 1024 x 320] using convolution).

I am obviously missing something here :) Could anyone, please, let me know what I should do to solve this problem ?

Any help would be appreciated. Thanks!

**Comment by ebarsoum** [comment]
Hi @adaber shape format didn't change, from where did you see that?

**Comment by adaber** [comment]
Hi, ebarsoum

Thanks for replying.

I installed the new CNTK version today and kept my original code that worked with the previous versions. It reported an error on a tensor size and I decided to investigate.

So, keeping everything exactly the same I noticed that my input RGB image/tensor went from [1024x320x3] to [3x1024x320]. I checked this by printing the tensor[0], tensor[1], and tensor[2] elements on the screen.

This is a part of the code I use to create a minibatch source.

`CNTK::ImageTransform scaleTransform;`
`scaleTransform[L"type"] = L"Scale";`
`scaleTransform[L"width"] = imageWidth;`
`scaleTransform[L"height"] = imageHeight;`
`scaleTransform[L"channels"] = imageNumChannels;`


I just checked the code and it seems that the tensor sizes got changed during the minibatch creation step and I don't know why. This is exactly the same code I had used with other CNTK versions.

Also, when I do the following: 

`auto inputImgStreamInfo = inputImgMinibatchSource->StreamInfo(L"features");`
`CNTK::NDShape inputImgShape = inputImgStreamInfo.m_sampleLayout;`

the inputImageShape is [3x1024x320] instead of [1024x320x3].

The same code using an earlier CNTK version produces [1024x320x3].

So, is there anything that was changed with respect to the **minibatch creation** process in Ver. 2.2 that could cause this to happen ? Is there any additional flag or parameter that I should set/reset while creating a minibatch ?

I will triple-check my code to see if it's on my side because I don't want to waste your time but it's exactly the same code which made me post my problem here.

Thanks a lot for your time. Let me know what you think :)

**Comment by adaber** [comment]
Good morning, ebarsoum

I just want to give you a heads-up about a possible solution.

I've added the "transpose" transformation within my minibatch creation function and the tensor dimensions show up in the correct order now [WxHxC].

`CNTK::ImageTransform transposeTransform;`
`transposeTransform[L"type"] = L"Transpose"`;

I haven't tested the whole training process yet but at least my tensor's dimensions are in the correct order now. I will update this thread with the results and will close it if everything goes ok.

Do you happen to know why I didn't have to use the transpose transform for the minibatch creation process using the previous CNTK versions ? Have you made any changes to the minibatch creation/storage logic in the latest version (ver. 2.2) ?

Thanks!

**Comment by adaber** [comment]
The transpose transformation solved the problem. I will close the issue.
Thanks!
