### ISSUE TITLE
distributed learner freezes with 1bitSGD or BlockMomentum

### ISSUE THREAD

**Issue by mrcgds** [Microsoft/CNTK#2596]
Hi,
I am training a SGD network using CNTK 2.1 and his Python 2.7 interface.

To feed data I am using the UserMinibatchSource class, training process is distributed on 4 GPUs;
data are divided between the 4 workers, but obviously they have not the identical number of minibatch.

When a worker finishes his data, a vacant Python dictionary is returned by the next_minibatch method: I have read that CNTK uses this method to report that a worker ends data, and then the training should continue on remaining GPUs. When all the workers finish data, and CNTK receive the vacant dictionary from all of them, it stops the training.

Using this approach the training works well when I use a data_parallel_distributed_learner with 32 bit for quantization.

Switching to 1 bit (1bitSGD) or to a block_momentum_distributed_learner the training phase starts well but, when happens that a worker finishes data and returns the vacant dictionary, the training freezes: the load of remaining GPUs goes to 100% but without processing any new data.

Could you give me any suggestion to fix this problem?
Thanks

**Comment by jaliyae** [comment]
Hi,

We tried reproducing the issue passing an empty minibatch but the trainer continue to work with 1bitSGD. Would it be possible for you to provide us an example repro? Another option, for the empty minibatch, what do you return from the UserMinibatchSource? is it simply an empty dictionary {} or a one with a key but null value?

Thank you
Jaliya

**Comment by jaliyae** [comment]
No response from the user for sometime.
