### ISSUE TITLE
Error with style transfer loss function

### ISSUE THREAD

**Issue by martinezmiranda** [Microsoft/CNTK#2600]
Hi all,

we're working on implementing Style Transfer in CNTK as seen in https://www.cntk.ai/pythondocs/CNTK_205_Artistic_Style_Transfer.html, but following the approach discussed in the https://arxiv.org/abs/1603.08155 paper. 

We're trying to minimize the loss function using VGG-16 intermediate layers for both the content and style images. We define the same loss function as seen in 205. Then, following the paper's approach, we need to use that function to train the model instead of minimizing the loss for each specific content image. To do so we need to replace the content image byte[] by a CNTK placeholder.

When creating the function, we get the error below
 
```
    def ordered_outputs(f, binding):
        _, output_dict = f.forward(binding, f.outputs)
        return [np.squeeze(output_dict[out]) for out in f.outputs] 

    def get_loss_function(self, intermediate_layers, model, 
                          y, content_image, style_image):
        if self.loss_function:
            return self.loss_function
        else:
            content_weight = 5.0
            style_weight = 1.0
            decay = 0.5
            # Now get the activations for the two images
            content_activations = ordered_outputs(intermediate_layers, {y: [[content_image]]})
            style_activations = ordered_outputs(intermediate_layers, {y: [[style_image]]})
            style_output = np.squeeze(model.eval({y: [[style_image]]}))

            # Finally define the loss
            n = len(content_activations)
            n = len(style_activations)
            total = (1-decay**(n+1))/(1-decay) # makes sure that changing the decay does not affect the magnitude of content/style
            loss = (1.0/total * content_weight * content_loss(y, content_image)
                    + 1.0/total * style_weight * style_loss(model, style_output)
                    + total_variation_loss(y))

            for i in range(n):
                loss = (loss
                    + decay**(i+1)/total * content_weight * content_loss(intermediate_layers.outputs[i], content_activations[i])
                    + decay**(n-i)/total * style_weight   *   style_loss(intermediate_layers.outputs[i], style_activations[i]))
            
            self.loss_function = loss

        return self.loss_function
```

> content_activations = ordered_outputs(intermediate_layers, {y: [[content_image]]})
> File "c:\tmp\CNTKStyleTransfer\VGGModelCreator.py", line 108, in ordered_outputs
> _, output_dict = f.forward(binding, f.outputs)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
> result = f(*args, **kwds)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\ops\functions.py", line 755, in forward
> None, device)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\internal\sanitize.py", line 431, in sanitize_var_map
> batch = sanitize_batch(var, batch, seq_starts, device)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
> result = f(*args, **kwds)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\internal\sanitize.py", line 200, in sanitize_batch
> return Value.create(var, batch, seq_starts, device)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
> result = f(*args, **kwds)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\core.py", line 452, in create
> data = [Value._as_best_data_type(var, sample) for sample in data]
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\core.py", line 452, in <listcomp>
> data = [Value._as_best_data_type(var, sample) for sample in data]
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\core.py", line 329, in _as_best_data_type
> sample = asarray(sample, dtype=var.dtype)
> File "C:\Users\jfviz\AppData\Local\conda\conda\envs\amaia_env\lib\site-packages\cntk\core.py", line 671, in asarray
> 'an array'%orig_type)
> ValueError: could not convert instance of type <class 'list'> to an array 

Any idea why this is happening? Thanks in advance

**Comment by cha-zhang** [comment]
seems y is expecting an array rather than a list? Did you try y:content_image directly?

**Comment by liqunfu** [comment]
y passed in to get_loss_function is not the input variable of intermediate_layers. Worked with the team offline. This specific issue is resolved.

**Comment by martinezmiranda** [comment]
Indeed it's solved, thanks for closing in my stead @liqunfu and thanks for your help @cha-zhang
