### ISSUE TITLE
Benchmark for Alexnet on Imagenet

### ISSUE THREAD

**Issue by kunal-bajpai** [Microsoft/CNTK#261]
I am doing a study of various platforms for deep learning and wish to include CNTK in the list. Can I request the dev team to perform a benchmark of training Alexnet on Imagenet data in various configurations like CPU cluster, single machine GPU and multi-machine GPUs?

I cannot do this myself as I do not have access to a GPU enabled machine and the benchmark will be a lot more authoritative if done by the dev team.

**Comment by wolfma61** [comment]
benchmarks should be done on identical hardware with identical and/or optimized model/scenarios for the individual toolsets. 

we published some comparison numbers in our initial announcement. 
https://blogs.technet.microsoft.com/inside_microsoft_research/2015/12/07/microsoft-computational-network-toolkit-offers-most-efficient-distributed-deep-learning-computational-performance/

**Comment by kunal-bajpai** [comment]
Well the idea is to compare performance of different platforms (cpu cluster, gpu cluster, single machine gpu, etc) so I am holding the model (a popular model like alexnet) and dataset constant.

I had seen the link you shared with me before. What I am looking for is data related to the training phase, like a graph of error against number of epochs or time required to train.

**Comment by pkranen** [comment]
Please see for example this http://dlbench.comp.hkbu.edu.hk/ for an independent benchmark on several tasks including CNNs.
