### ISSUE TITLE
CNTK with HDFS

### ISSUE THREAD

**Issue by abuccts** [Microsoft/CNTK#2617]
Hi,

Is there any docs or examples on how to use cntk with hdfs?
Can not read data directly from hdfs using Brainscripts in Examples.

**Comment by eldakms** [comment]
Currently CNTK uses Posix file API for all IO, so there are no specific HDFS readers (this will probably change in the future).
We usually expose HDFS as a normal file system, then everything should work. i.e. you can have a look here for that https://github.com/Microsoft/hdfs-mount

**Comment by rhy-ama** [comment]
Mounting it on a linux host and then sharing it using samba/NFS is one of the alternatives to installing HDP on windows host.

**Comment by abuccts** [comment]
I see, thanks
