### ISSUE TITLE
CNTK freeze

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#2619]
![image](https://user-images.githubusercontent.com/22387152/32774813-debd9780-c970-11e7-969d-10c2b2abc051.png)

After format my computer, I setup some driver and download CNTK, and I run the installation script.
I use Intel Xeon CPU and 1080TI GPU *3, but CNTK was freeze like the screen shot nevertheless I wait more than 10 minutes.

I try removing all contents of the .cntk file and run, but I see the same situation.

How can I fix it?

![image](https://user-images.githubusercontent.com/22387152/32775154-fdbd4d96-c971-11e7-8fe9-a5075d0ed7be.png)

emptying configfile also freezing

**Comment by KeDengMS** [comment]
Can you attach a debugger and check all the threads for more details?

**Comment by Eomtaesan** [comment]
@KeDengMS 
This problem is now solved.
This is caused by window setting that automatically update graphic driver and (CUDA?).
So my card driver version is 388.31 and cuda is 9.0
But cntk does not support 9.0.

After turning off the automatic driver update setting, I solved.
