### ISSUE TITLE
Cannot find a CPU math library

### ISSUE THREAD

**Issue by jplu** [Microsoft/CNTK#262]
Hello,

I'm having an issue to compile CNTK. Here the error I have when I run the "configure" process:

```
../../configure --1bitsgd=yes                                        
Defaulting to --with-buildtype=release
Cannot find a CPU math library.
Please specify --with-acml, --with-mkl, --with-openblas with a path.
```

But I previously installed the "ACML" as recommended, following these steps:

```
tar -xzvf ./acml-5-3-1-ifort-64bit.tgz
sudo ./install-acml-5-3-1-ifort-64bit.sh
export ACML_FMA=0
export LD_LIBRARY_PATH=/usr/local/ACML/ifort64/lib:/usr/local/ACML/ifort64_mp/lib:$LD_LIBRARY_PATH
```

And the LD_LIBRARY_PATH variable is correctly set:

```
/usr/local/cuda/lib64:/usr/local/ACML/ifort64/lib/:/usr/local/ACML/ifort64_mp/lib/:/usr/local/mpi/lib/
```

I'm on Ubuntu 14.04.

**Comment by alexeyo26** [comment]
Hello! Try to rename /usr/local/ACML to /usr/local/acml5.3.1 (and update paths accordingly) It should do the trick. Sorry, it's the current limitations of ```configure``` as described [here](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#expected-component-locations-in-configure-and-makefile-scripts)

Thank you,
Alexey

**Comment by jplu** [comment]
It works.

Thanks a lot.

**Comment by alexeyo26** [comment]
Great to hear and sorry once again for this limitation.

Thank you,
Alexey
