### ISSUE TITLE
Wrong CropType in ImageHandsOn

### ISSUE THREAD

**Issue by Prasandhmcw** [Microsoft/CNTK#2622]
The link provided in the Tutorials in https://docs.microsoft.com/en-us/cognitive-toolkit/hands-on-labs-image-recognition to download the archive (https://github.com/Microsoft/CNTK/blob/fseide/kdd/Tutorials/CNTK_HandsOn_KDD2016.zip) ,
contains a "ImageHandsOn.cntk" within the ImageHandsOn folder that has wrong cropType in line 71.

It was cropType = "random" , which should be cropType = "RandomSide"

Got an Exception stating Invalid crop type , then manually changed it.

Can you please look into this and correct it if its an error ?

**Comment by cha-zhang** [comment]
The scripts in this file was not maintained as it was a talk given at KDD2016. For image hands on examples, please take a look here: 
https://github.com/Microsoft/CNTK/tree/master/Tutorials

**Comment by Prasandhmcw** [comment]
Ok.
