### ISSUE TITLE
Random image trasforms that are in sync inside a composite reader

### ISSUE THREAD

**Issue by nitrif** [Microsoft/CNTK#2636]
I am working on a semantic segmentation tasks where images and pixels masks are stored in separate files, and are read by composite reader:

```
images_source = Base64ImageDeserializer(images_path, StreamDefs(features=StreamDef(field='image', transforms=transforms, is_sparse=False)))
labels_source = Base64ImageDeserializer(labels_path, StreamDefs(labels=StreamDef(field='image', transforms=transforms, is_sparse=False)))
return MinibatchSource([images_source, labels_source], ...)
```

I want to introduce random image transforms(crop,...) that have to be in sync for both inputs. What is the most convenient way to do this? I read somewhere that this is possible to do with UserMinibatchSource, but still haven't found any example.

Thanks,
Nikola

**Comment by n17s** [comment]
Duplicate of #2309
