### ISSUE TITLE
plz help me, how to retrain the model for python

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#2642]
def train():
    features = 2
    width = 89
    height = 103

    # output = cntk.layers.Sequential([
    #     cntk.layers.For(range(30), lambda: [
    #         cntk.layers.Convolution2D(filter_shape=(3, 3), num_filters=256, activation=cntk.ops.relu, pad=True,
    #                                   strides=1, bias=False, init_bias=0)
    #     ]),
    #     cntk.reshape(cntk.layers.Convolution2D(filter_shape=(3, 3), num_filters=1, activation=cntk.ops.relu, pad=True,
    #                                            strides=1, bias=True, init_bias=1), [width * height])
    #
    # ])(input)

    model = cntk.ops.functions.Function.load("0.model", cntk.device.gpu(0))
    input = cntk.ops.input_variable((features, height, width), numpy.float32)
    label = cntk.ops.input_variable(height * width, numpy.float32)
    # ce = cntk.losses.cross_entropy_with_softmax(model, label)
    # pe = cntk.metrics.classification_error(model, label)
    ce = cntk.losses.cross_entropy_with_softmax(model[0], label)
    pe = cntk.metrics.classification_error(model[0], label)
    trainer = cntk.Trainer(model, (ce, pe), [
        cntk.learners.sgd(model.parameters, cntk.learners.learning_rate_schedule(0.01, cntk.learners.UnitType.sample))],
                           [cntk.logging.ProgressPrinter(128)])

    for i in range(1024):
        for j in range(16):
            ary = go(ctypes.c_int(numpy.random.random_integers(177, 297)),
                     ctypes.c_int(numpy.random.random_integers(305, 800)), 1)
        input_data = numpy.zeros([features, height, width], numpy.float32)
        label_data = numpy.zeros(width * height, numpy.float32)
        label_data[numpy.random.random_integers(0, width * height - 1)] = 1
        trainer.train_minibatch({input: input_data, label: label_data})
    trainer.summarize_training_progress()
    trainer.save_checkpoint("1.model")

**you can ignore "go" function.**
in this code
**trainer.train_minibatch({input: input_data, label: label_data})**
error occured
**ValueError: Values for 1 required arguments 'Input('Input3', [#], [2 x 103 x 89])', that the requested output(s) 'Output('aggregateLoss', [], []), Output('Block442_Output_0', [#], [1]), Output('aggregateEvalMetric', [], [])' depend on, have not been provided.**

**Comment by KeDengMS** [comment]
Can you debug it with [this debug manual](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_debug.ipynb)?

**Comment by jeandebleau** [comment]
first, you did not define the input of the model. This is what the error message is saying. You can try: trainer.train_minibatch({model.arguments[0]: input_data, label: label_data}).

**Comment by Eomtaesan** [comment]
@jeandebleau 
wow thank you.
I did not know parameters of model(Function), each as model.arguments[0]
by your replying, I can access the parameter, thank you!
