### ISSUE TITLE
RuntimeError: Batch normalization training on CPU is not yet implemented. : Transferlearning.py with flowers dataset on ResNet18_ImageNet_CNTK.Model - Error 

### ISSUE THREAD

**Issue by ajaysharmahcl** [Microsoft/CNTK#2643]
I am running Transferlearning.py script with flowers dataset and using ResNet18_ImageNet_CNTK.Model that was downloaded from internet. 
I don't have GPU configuration so running it on CPU mode only. I am getting following error.
File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 2804, in train_minibatch_overload_for_minibatchdata
  return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *arg)
RntimeError: Batch normalization training on CPU is not yet implemented.

[CALL STACK]
    > Microsoft::MSR::CNTK::CPUMatrix<float>::  BatchNormalizationForwar
    - Microsoft::MSR::CNTK::Matrix<float>::  BatchNormalizationForward
    - Microsoft::MSR::CNTK::BatchNormEngine<double>::  Forward
    - CNTK::Dictionary::  ~Dictionary (x3)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Dictionary::  ~Dictionary
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfSamplesSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - PyInit__cntk_py (x2)

Kindly help in solving this error or suggest a way to train the flowers dataset that i want to leverage for detection of any flower.
Your quick response will be highly appreciated.

**Comment by ebarsoumMS** [comment]
BN currently isn't support in the CPU, you need to train on the GPU. This will be fixed soon.

**Comment by ajaysharmahcl** [comment]
thank you for responding. is there any tentative closure date of this fix
please?

**Comment by KeDengMS** [comment]
[The change](https://github.com/Microsoft/CNTK/commit/1d3d1e8a2770b65a809f6bf7e6cde49047ffc0c6) has been merged into master.
