### ISSUE TITLE
cntk.ops.gather doesn't support dynamic axis

### ISSUE THREAD

**Issue by mfuntowicz** [Microsoft/CNTK#2646]
I've a Reinforcement Learning scenario where I need to select different values of a tensor for each individual in minibatch. At first sight I thought that [cntk.ops.gather](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.gather) would do the trick, but it doesn't support dynamic axis.

Could it be possible to bring (at least) batch axis support on this operation ? 

Here is the setup, and the output : 
``` python
# This syntax is just here to highlight you the setup
qacted = gather(Output('qvalues', [#], [6]), Input('actions', [#], []))
RuntimeError: Gather operation's right operand doesn't expect to have dynamic axis
```

Thanks, 
Morgan

**Comment by mfuntowicz** [comment]
cc @wilrich-msft @wrichert (Working on the same project)

**Comment by KeDengMS** [comment]
You can unpack_batch/to_batch before and after gather to achieve that.

**Comment by VHellendoorn** [comment]
Sorry to follow up, but could either of you give an example of how to use this? For instance, with `reference = [#] [2, 300]` and `indices = [#] [ ]`, the `gather` function without this trick returns a `Tensor[300]`, which makes sense but won't execute for the above reason. If I `unpack_batch` both arguments first and then `to_batch` the result, however, I get a `Tensor[2, 300]`. Any pointers?

**Comment by delzac** [comment]
Actually i don't get how unpack_batch and to_batch will solve the problem. The output of gather will already have a dynamic batch axis and i can't apply to_batch on it.
