### ISSUE TITLE
Porting the CNTK

### ISSUE THREAD

**Issue by mehhey** [Microsoft/CNTK#265]
Hi,
Has anybody tried to port cntk to nvidia embedded boards like [TK1 ](http://www.nvidia.com/object/jetson-tk1-embedded-dev-kit.html)or [TX1](http://www.nvidia.com/object/jetson-tx1-module.html)? I believe the provided computation power by these boards enables us to run DNN applications on on embedded processors for real-time.

**Comment by wolfma61** [comment]
See issue #266 

unfortunately this is currently not supported
thx
Wolfgang

**Comment by wolfma61** [comment]
Closing this one - see #266
