### ISSUE TITLE
CNTK 2.2 memory leak problem during evalution of a model

### ISSUE THREAD

**Issue by ZeroCool11000** [Microsoft/CNTK#2650]
Hello, I just faced a memory leak problem, during the evaluation of my model into a c++ program.
The classificator was trained with Python (2.7) on a linux machine and afterwards exported and reloaded in a c++ program. Mainly i programmed a server (thrift) because  i want to use this model into a 32 bit program where those needed data are just exchanged. Are there any workarounds ?, my program has to classificate multiple images so it is not possible to stop the program, but reloading the same model doesn't work after each evaluation the memory usage just increases.  

Are there any workarounds ? 
- Setting parameters in my python script (Keras). 
- in my c++ program, reloading does not work !!!

**Comment by ebarsoumMS** [comment]
Dupe.
