### ISSUE TITLE
What's the ETA to be able to build CNTK with VS 2017?

### ISSUE THREAD

**Issue by IvanFarkas** [Microsoft/CNTK#2657]
At this point, one can reasonably expect that **CNTK** source **builds** with **VS 2017** using **CUDA 9**.
I should be able to build CNTK with **VS 2017 only**, even if I need to install the **VC++ 2015.3 v140** toolset as part of the VS 2017 installation.

During the build steps, I am still getting this very disappointing **Warning**:

`
Installation of Visual Studio 2015 Update 3 is a pre-requisite before installation can continue
`

**Build steps as documented:**

Command Prompt
```shell
start powershell -executionpolicy remotesigned

```

Powershell
```powershell
cd C:\ML\CNTK\CNTK\Tools\devInstall\Windows
.\devInstall.ps1 -PyVersion 35 -AnacondaBasePath C:\local\ANA3-411

```

Perhaps next year I have better luck with VS 2017. Maybe **Christmass**? **Which one?** :-(

**Comment by eraoul** [comment]
Strange -- I have VS 2017 (Enterprise edition) and just installed CNTK 2.3 without problems.

**Comment by IvanFarkas** [comment]
Sorry for not being specific.
At this point, one can reasonably expect that CNTC compiles with **VS 2017** using **CUDA 9**.
That is simply not the case.
As indicated in the build procedure, following the steps below gives you the **ERROR**.

Command Prompt
```shell
start powershell -executionpolicy remotesigned

```

Powershell
```powershell
cd C:\ML\CNTK\CNTK\Tools\devInstall\Windows
.\devInstall.ps1 -PyVersion 35 -AnacondaBasePath C:\local\ANA3-411

```

**Comment by larsonmattr** [comment]
I would also appreciate if we could build the CNTK 2.3.1 examples for C++ and UWP with Visual Studio 2017.  My projects may require using VS2017 in the future.

**Comment by IvanFarkas** [comment]
Thx
