### ISSUE TITLE
Wether CNTK can support ARM CPU?

### ISSUE THREAD

**Issue by lm365cn** [Microsoft/CNTK#266]
I want to use CNTK on Nvidia Jetson TX1,CNTK can support the board?

**Comment by wolfma61** [comment]
Unfortunately this is currently not supported 

thx
Wolfgang

**Comment by sunils27** [comment]
because Following up on this I'm interested in using CNTK on a Jetson TX1. Is this supported with the new release? If not, are there any plans?

**Comment by zhouwangzw** [comment]
It is in our plan. First will be support model evaluation on ARM.

**Comment by CIPop** [comment]
> It is in our plan. First will be support model evaluation on ARM.

Model evaluation support would be a great first step!

Is this something that the community can help with? If yes, could you please list some of the issues / steps to solve the problem (assume little to no knowledge of the platform please :) )?

**Comment by gvoysey** [comment]
@zhouwangzw happy to help, here.

**Comment by zhouwangzw** [comment]
@CIPop @gvoysey Thanks for your help! We are currently preparing a branch based on our previous work for Eval on ARM. When it is ready, you can start work from there and we are much appreciated for your help. Please stay tuned!

**Comment by gvoysey** [comment]
@zhouwangzw great.  Do you have an anticipated timeline of the branch being ready for alpha?

**Comment by IvanFarkas** [comment]
Forget TK-1. I'd love to do edge computing with **[Nvidia Jetson TX2](https://developer.nvidia.com/embedded/develop/hardware)**.

**Comment by CIPop** [comment]
@zhouwangzw Any updates here?

**Comment by wolfma61** [comment]
I don't think there will be any updated before we get the next version our (end of July) - but as of now the roadmap when we can have official support for these HW isn't done yet ...

**Comment by wolfma61** [comment]
sorry didn't want to close this one ...

**Comment by ebarsoumMS** [comment]
WinML API that just got announced support ARM.

**Comment by CIPop** [comment]
> WinML API that just got announced support ARM.

Still it will probably not run on Jetson TX1/2 which was the original request.

**Comment by nglee** [comment]
I've been trying to build CNTK on Jetson TX1. The README.md page on the following GitHub repository describes the steps I took.

https://github.com/nglee/CNTK
