### ISSUE TITLE
Nuget CNTK.GPU 2.3.0 Release still pointing to 2.2.0

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#2660]
![image](https://user-images.githubusercontent.com/8396992/33173647-f17d5884-d022-11e7-92c3-aabc93539a62.png)

**Comment by KeDengMS** [comment]
We are experiencing some NuGet upload issues. Will update once it's done.

**Comment by IvoTops** [comment]
Any progress with this?

**Comment by manikjindal** [comment]
CNTK 2.3 GPU NuGet package has been published [here](https://www.nuget.org/packages/CNTK.GPU/2.3.0)

**Comment by IvoTops** [comment]
Muchos gracias
