### ISSUE TITLE
install CNTK V2.3

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#2664]
Hi

I downloaded CNTK V2.3 binary drop for linux GPU and run ./install-cntk.sh. No error occured and everything goes fine during installation process. But when I activate anaconda env and import cntk, the following error occurred:

>    In [1]: import cntk as C
ImportError                               Traceback (most recent call last)
<ipython-input-1-157fe052c41b> in <module>()
----> 1 import cntk as C
/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/__init__.py in <module>()
      8 import numpy as np
      9 
---> 10 from . import cntk_py
     11 
     12 #
/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.py in <module>()
     19         except ImportError:
     20             return importlib.import_module('_cntk_py')
---> 21     _cntk_py = swig_import_helper()
     22     del swig_import_helper
     23 elif _swig_python_version_info >= (2, 6, 0):
/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.py in swig_import_helper()
     18             return importlib.import_module(mname)
     19         except ImportError:
---> 20             return importlib.import_module('_cntk_py')
     21     _cntk_py = swig_import_helper()
     22     del swig_import_helper
/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory

Is NCCL2 new dependency in new version?

regards

**Comment by KeDengMS** [comment]
libnccl.so.2 should be included in the Python wheel. can you check if it's under /home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/libs?

**Comment by hajix** [comment]
The problem was solved by uninstall previous cntk version and re-install it using pip.

Thank for the answer btw @KeDengMS

**Comment by frankibem** [comment]
I'm encountering the same problem. A clean install didn't work either.l

**Comment by KeDengMS** [comment]
@frankibem Can you check if libnccl.so.2 exists in Python package libs folder?

**Comment by frankibem** [comment]
I checked and it does.

**Comment by KeDengMS** [comment]
@frankibem Please check where your libCntk.Core-2.3 comes from. It would find libnccl.so.2 if it's from the Python package libs folder.

**Comment by frankibem** [comment]
Modifying LD_LIBRARY_PATH as suggested in #2683 seems to have fixed this problem.

**Comment by navidnadery** [comment]
ممی جون داداش این libnccl کجاست؟ چرا پیداش نمی کنم؟

**Comment by navidnadery** [comment]
طبق لینک زیر رفتم:
https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-binary-script
 برای پایتونش نصب میشه ولی برای برین اسکریپت کار نمیکنه و خطای زیر رو میده:
error while loading shared libraries: libnccl.so.2
نسخه پایتون رو پاک کردم باز اومدم برا برین اسکریپت نصب کنم نشد بازم:
![image](https://user-images.githubusercontent.com/12444857/36157010-ff3f2f04-10ed-11e8-836e-2544d0b60c40.png)

**Comment by navidnadery** [comment]
The problem was solved! I have previously installed Anaconda3 and it caused the problem. I removed Anaconda and installed the version that is available in CNTK package. It is running installation of CNTK now.
