### ISSUE TITLE
CNTK Python custom loss function

### ISSUE THREAD

**Issue by kviknakjartan** [Microsoft/CNTK#2669]
Is it possible to write a custom loss function that is a function of all outputs in a minibatch or perhaps last N outputs? What about gradients then, will they need to be supplied specifically?

**Comment by hajix** [comment]
You can write your loss function as easy as possible! Check [GAN](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206A_Basic_GAN.ipynb) tutorials and get hint.

**Comment by kviknakjartan** [comment]
Maybe I wasn't clear enough. My problem is that I want the loss L_i for instance i be a function of the outputs y for all instances of a minibatch or L_i=f (y_1,y_2,...,y_N) where N is the number of instances in the minibatch.

**Comment by kviknakjartan** [comment]
This seems to be possible using the UserFunction class, closing the issue
