### ISSUE TITLE
Feature request: CNTK as a nuget package

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/CNTK#267]
It would be awesome to have a nuget package for CNTK available. If full CNTK is not possible (due to the various CUDA dependencies), it would be great to have at least a way of evaluating a model (CPU only) in a package, callable from .NET

**Comment by wolfma61** [comment]
can you give some more details? You want to use the CNTK model evaluation in your own application? 
I assume you would prefer a library like CNTK evaluation module?

thx
Wolfgang

**Comment by ant0nsc** [comment]
Assume I have an environment where I get my CNTK models trained. In my case, the model will be trained off images. I'm using that trained model in applications running in Azure DataLake/Cosmos, written in .NET (F# in my case) When writing that application, I don't want to compile against full CNTK - only against a subset that is necessary to consume a pre-trained model and evaluate it on a new image. Is that enough context?

**Comment by wolfma61** [comment]
this will be available, we need some more internal testing and then make it public 

-- Wolfgang

**Comment by ant0nsc** [comment]
@wolfma61 : Do you have any updates on the nuget package? Let me know if I can help testing.

**Comment by PatrickBue** [comment]
Hi, I would also be interested in a nuget package. Is there a public or internal testing version I can use?

**Comment by zhouwangzw** [comment]
The nuget package has been published for a long time. See https://github.com/Microsoft/CNTK/wiki/NuGet-Package for details. 

Closing the issue.
