### ISSUE TITLE
Packaging CNTK

### ISSUE THREAD

**Issue by Sherif89** [Microsoft/CNTK#268]
> Today you have to install all required prerequisites manually. We work to make a package, that includes the required dependencies and hope to deliver it soon.

Hi, I suggest this package sceme:

- **ACML**: It's for running ACML applications.
- **ACML-devel**: It's for developing ACML applications.
- **libCNTK**: It's for running applications, which dynamically link CNTK.
- **CNTK**: It's for NDL scripts. It depends on libCNTK.
- **CNTK-devel**: It contains the upcoming redesigned C++ API.
- **CNTK-cuda**: It's for using GPUs, which suport cuda.

**Comment by Sherif89** [comment]
CMake support may be necessary for building CNTK and (I don't know how is this done) for easier linking like in OpenCV tutorial:
`cmake_minimum_required(VERSION 2.8)
project( DisplayImage )
find_package( OpenCV REQUIRED )
add_executable( DisplayImage DisplayImage.cpp )
target_link_libraries( DisplayImage ${OpenCV_LIBS} )`

**Comment by wolfma61** [comment]
I'm not sure what you are trying to accomplish, there is a binary only download which gives you all you need to execute CNTK locally

Creating a development environment is a more involved step which we describe in detail in the wiki. it requires different tools for windows and Linux, we are trying to make this easier in the future. for this we are talking to some of the folks responsible for the required tools to get easier access to the packaged components. This is work in progress and we can't give an ETA

thx
Wolfgang

**Comment by Sherif89** [comment]
> 'm not sure what you are trying to accomplish, there is a binary only download which gives you all you need to execute CNTK locally

I think it'd be better, if you could install CNTK like any Linux package. Features:
- Faster spreading: People'd be able to find it easier, if they could see all CNTK packages in the package manager.

- Easier installation.

- Easier development.

**Comment by Sherif89** [comment]
> we are trying to make this easier in the future. for this we are talking to some of the folks responsible for the required tools to get easier access to the packaged components. This is work in progress and we can't give an ETA

I posted on a distribution forum asking for packging CNTK. Should I tell them to wait?

**Comment by wolfma61** [comment]
CNTK is under active development, you will find improvements, new features and bug fixes on a regular basis here on GitHub. we are working also on establishing a more regular cadence of binary drops here on GitHub. 

again - all this is very actively being improved and enhanced. Not sure external packaging is going to give you what you want

**Comment by Sherif89** [comment]
> CNTK is under active development, you will find improvements, new features and bug fixes on a regular basis here on GitHub. we are working also on establishing a more regular cadence of binary drops here on GitHub.

again - all this is very actively being improved and enhanced. Not sure external packaging is going to give you what you want

That's one of the things, I like about it.
What prevents distributions for making a release every few days?

**Comment by wolfma61** [comment]
we will continue to publish binaries here and will improve this as we go

the only thing I can say - make sure you observe the licenses of all the components involved.

**Comment by Sherif89** [comment]
@wolfma61 , you may see this [post](https://forums.opensuse.org/showthread.php/514490-Package-a-project) in OpenSUSE forums. It seems it isn't very hard to make a rpm.
