### ISSUE TITLE
Running CNTK on Linux with 4 gpu array problem

### ISSUE THREAD

**Issue by MotiFreiman** [Microsoft/CNTK#2680]
I'm trying to run the MNIST_Complex_Training.py on a Linux machine with 4 K10 gpus.
I successfully run it using only a single gpu  I got the following error: 
RuntimeError: Acquire: Failed to open lock file /var/lock/CNTK_device_allocation_lock: Permission denied.
A full error logging is below (#1)
However, when I add the following line (at line 41 of MNIST_Complex_Training.py):
C.device.try_set_default_device(C.device.gpu(0))
It runs successfully (and the same is true for gpu #0-#3)

When I tried to run with MPI using the following command: 
mpiexec -n 2 python2.7 MNIST_Complex_Training.py

I got again the following error (with and without adding the try_set_default_device call)
RuntimeError: Acquire: Failed to open lock file /var/lock/CNTK_device_allocation_lock: Permission denied.
A full error logging is below (#2)

System details:
Python vesion: Python 2.7.12
CNTK version: 2.2
GPU information: 
(GPU[0] Tesla K10.G2.8GB, GPU[1] Tesla K10.G2.8GB, GPU[2] Tesla K10.G2.8GB, GPU[3] Tesla K10.G2.8GB, CPU)

Thanks,
Moti

################# 1 - single gpu run output #################

[single_run_failed.txt](https://github.com/Microsoft/CNTK/files/1505742/single_run_failed.txt)

################# 2 - multi gpu run output #################
[multi_run.txt](https://github.com/Microsoft/CNTK/files/1505743/multi_run.txt)

**Comment by KeDengMS** [comment]
Please check if you have other CNTK processes running when hitting RuntimeError: Acquire: Failed to open lock file /var/lock/CNTK_device_allocation_lock: Permission denied. This is a global mutex for GPU allocation.

**Comment by ziqin** [comment]
Please check whether you have write access to `/var/lock` directory.
If you cannot write there like me, have a look at #62.

**Comment by nikitawootten** [comment]
I recently ran into this problem on my machine, running Arch Linux (CNTK version 2.7).

As a temporary workaround, I just created the file (`touch /var/lock/CNTK_device_allocation_lock`) and set loose permissions on it.
