### ISSUE TITLE
cntk-2.3-Pre-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by vickylance** [Microsoft/CNTK#2684]
**Below is what the commands I have executed. But I am getting the above mentioned error.
Please help me.**

I have seen this issue #2055

But it's of no use

C:\Projects\ai-projects\keras-projects\mnist>conda create --name keras
Fetching package metadata .............
Solving package specifications:
Package plan for installation in environment C:\Softwares\Anaconda3\envs\keras:

Proceed ([y]/n)? y

`#`
`# To activate this environment, use:`
`# > activate keras`
`#`
`# To deactivate an active environment, use:`
`# > deactivate`
`#`
`# * for power-users using bash, you must source`
`#`

C:\Projects\ai-projects\keras-projects\mnist>activate keras

(keras) C:\Projects\ai-projects\keras-projects\mnist>pip install cntk-2.3-Pre-cp36-cp36m-win_amd64.whl
**`cntk-2.3-Pre-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.`**

(keras) C:\Projects\ai-projects\keras-projects\mnist>python --version
`Python 3.6.3 :: Anaconda custom (64-bit)`

(keras) C:\Projects\ai-projects\keras-projects\mnist>conda --version
`conda 4.3.30`

(keras) C:\Projects\ai-projects\keras-projects\mnist>anaconda --version
`anaconda Command line client (version 1.6.5)`

(keras) C:\Projects\ai-projects\keras-projects\mnist>pip --version
`pip 9.0.1 from C:\Softwares\Anaconda3\lib\site-packages (python 3.6)`

(keras) C:\Projects\ai-projects\keras-projects\mnist>

**Comment by mx-iao** [comment]
Can you try installing from the official [2.3 release](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python?tabs=cntkpy23])

**Comment by vickylance** [comment]
@mx-iao  Ok I tried to create another anaconda environment according to the documentation and tried to install the official releases.

And it got installed successfully.

Microsoft Windows [Version 10.0.16299.64]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\vkkpp>conda create --name cntk-py36 python=3.6 numpy scipy h5py jupyter
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Softwares\Anaconda3\envs\cntk-py36:

The following NEW packages will be INSTALLED:

    bleach:             2.0.0-py36h0a7e3d6_0
    ca-certificates:    2017.08.26-h94faf87_0
    certifi:            2017.11.5-py36hb8ac631_0
    colorama:           0.3.9-py36h029ae33_0
    decorator:          4.1.2-py36he63a57b_0
    entrypoints:        0.2.3-py36hfd66bb0_2
    h5py:               2.7.1-py36h20531f2_0
    hdf5:               1.8.18-hcf527f2_1
    html5lib:           0.999999999-py36ha09b1f3_0
    icc_rt:             2017.0.4-h97af966_0
    icu:                58.2-ha66f8fd_1
    intel-openmp:       2018.0.0-hd92c6cd_8
    ipykernel:          4.6.1-py36hbb77b34_0
    ipython:            6.2.1-py36h9cf0123_1
    ipython_genutils:   0.2.0-py36h3c5d0ee_0
    ipywidgets:         7.0.5-py36h6314756_0
    jedi:               0.10.2-py36hed927a0_0
    jinja2:             2.9.6-py36h10aa3a0_1
    jpeg:               9b-hb83a4c4_2
    jsonschema:         2.6.0-py36h7636477_0
    jupyter:            1.0.0-py36h422fd7e_2
    jupyter_client:     5.1.0-py36h9902a9a_0
    jupyter_console:    5.2.0-py36h6d89b47_1
    jupyter_core:       4.4.0-py36h56e9d50_0
    libpng:             1.6.32-h140d38e_4
    markupsafe:         1.0-py36h0e26971_1
    mistune:            0.8.1-py36h007b88b_0
    mkl:                2018.0.1-h2108138_4
    nbconvert:          5.3.1-py36h8dc0fde_0
    nbformat:           4.4.0-py36h3a5bc1b_0
    notebook:           5.2.1-py36h4fb2ca6_0
    numpy:              1.13.3-py36ha320f96_0
    openssl:            1.0.2m-h093b818_1
    pandoc:             1.19.2.1-hb2460c7_1
    pandocfilters:      1.4.2-py36h3ef6317_1
    pickleshare:        0.7.4-py36h9de030f_0
    pip:                9.0.1-py36h226ae91_4
    prompt_toolkit:     1.0.15-py36h60b8f86_0
    pygments:           2.2.0-py36hb010967_0
    pyqt:               5.6.0-py36hb5ed885_5
    python:             3.6.3-h3b118a2_4
    python-dateutil:    2.6.1-py36h509ddcb_1
    pyzmq:              16.0.3-py36he714bf5_0
    qt:                 5.6.2-vc14h6f8c307_12
    qtconsole:          4.3.1-py36h99a29a9_0
    scipy:              1.0.0-py36h1260518_0
    setuptools:         36.5.0-py36h65f9e6e_0
    simplegeneric:      0.8.1-py36heab741f_0
    sip:                4.18.1-py36h9c25514_2
    six:                1.11.0-py36h4db2310_1
    sqlite:             3.20.1-h9eeafa9_2
    testpath:           0.3.1-py36h2698cfe_0
    tornado:            4.5.2-py36h57f6048_0
    traitlets:          4.3.2-py36h096827d_0
    vc:                 14-h2379b0c_2
    vs2015_runtime:     14.0.25123-hd4c4e62_2
    wcwidth:            0.1.7-py36h3d5aa90_0
    webencodings:       0.5.1-py36h67c50ae_1
    wheel:              0.30.0-py36h6c3ec14_1
    widgetsnbextension: 3.0.8-py36h933dd4f_0
    wincertstore:       0.2-py36h7fe50ca_0
    zlib:               1.2.11-h8395fce_2

Proceed ([y]/n)? y

python-3.6.3-h 100% |###############################| Time: 0:03:56  94.79 kB/s
certifi-2017.1 100% |###############################| Time: 0:00:00 728.28 kB/s
hdf5-1.8.18-hc 100% |###############################| Time: 0:00:57 475.13 kB/s
libpng-1.6.32- 100% |###############################| Time: 0:00:02 512.72 kB/s
mistune-0.8.1- 100% |###############################| Time: 0:00:00 586.35 kB/s
pyzmq-16.0.3-p 100% |###############################| Time: 0:00:00 726.40 kB/s
h5py-2.7.1-py3 100% |###############################| Time: 0:00:01 668.36 kB/s
qt-5.6.2-vc14h 100% |###############################| Time: 0:03:06 313.54 kB/s
scipy-1.0.0-py 100% |###############################| Time: 0:00:58 232.69 kB/s
jupyter_core-4 100% |###############################| Time: 0:00:00 438.67 kB/s
wheel-0.30.0-p 100% |###############################| Time: 0:00:00 145.02 kB/s
pip-9.0.1-py36 100% |###############################| Time: 0:00:10 243.71 kB/s
ipython-6.2.1- 100% |###############################| Time: 0:00:05 208.77 kB/s
widgetsnbexten 100% |###############################| Time: 0:00:10 166.22 kB/s
ipywidgets-7.0 100% |###############################| Time: 0:00:01  85.50 kB/s
DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Softwares\Anaconda3\envs\cntk-py36', env_name: 'cntk-py36', mode: 'None', used_mode: 'user'
DEBUG menuinst_win32:create(299): Shortcut cmd is C:\Softwares\Anaconda3\python.exe, args are ['C:\\Softwares\\Anaconda3\\cwp.py', 'C:\\Softwares\\Anaconda3\\envs\\cntk-py36', 'C:\\Softwares\\Anaconda3\\envs\\cntk-py36\\python.exe', 'C:\\Softwares\\Anaconda3\\envs\\cntk-py36\\Scripts\\jupyter-notebook-script.py', '%USERPROFILE%']
#
# To activate this environment, use:
# > activate cntk-py36
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


C:\Users\vkkpp>activate cntk-py36

(cntk-py36) C:\Users\vkkpp>pip install https://cntk.ai/PythonWheel/GPU/cntk-2.3-cp36-cp36m-win_amd64.whl
Collecting cntk==2.3 from https://cntk.ai/PythonWheel/GPU/cntk-2.3-cp36-cp36m-win_amd64.whl
  Using cached https://cntk.ai/PythonWheel/GPU/cntk-2.3-cp36-cp36m-win_amd64.whl
Requirement already satisfied: numpy>=1.11 in c:\softwares\anaconda3\envs\cntk-py36\lib\site-packages (from cntk==2.3)
Requirement already satisfied: scipy>=0.17 in c:\softwares\anaconda3\envs\cntk-py36\lib\site-packages (from cntk==2.3)
Installing collected packages: cntk
Successfully installed cntk-2.3

(cntk-py36) C:\Users\vkkpp>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk as C
>>> exit()

(cntk-py36) C:\Users\vkkpp>
