### ISSUE TITLE
How to set minibatch size for sequential data (illegal memory access)

### ISSUE THREAD

**Issue by frankibem** [Microsoft/CNTK#2691]
I'm working with a sequential dataset where the length of each sequence is in the range [2, 29]. From [here](https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-minibatchSize-and-Python-minibatch_size_in_samples-in-CNTK) I understand that the minibatch size (mbs) is the 'number sequence **items/tokens** across the sequences that constitute the minibatch'. I'm trying to perform sequence classification using a bidirectional lstm (similar to that [here](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_202_Language_Understanding.ipynb)) and I'm using ProgressPrinter to log every 10 minibatches with cross validation at the end of each epoch.

When I set mbs = 10, I get the following output (truncated):

>  Minibatch[   1-  10]: loss = 4.398151 * 11, metric = 100.00% * 11;
>  Minibatch[  11-  20]: loss = 4.512497 * 10, metric = 100.00% * 10;
>  Minibatch[  21-  30]: loss = 4.244667 * 10, metric = 90.00% * 10;
>  Minibatch[  31-  40]: loss = 4.419278 * 10, metric = 100.00% * 10;
>  Minibatch[  41-  50]: loss = 4.292654 * 10, metric = 100.00% * 10;
>  Minibatch[  51-  60]: loss = 4.755385 * 11, metric = 100.00% * 11;
>  Minibatch[  61-  70]: loss = 4.519617 * 11, metric = 100.00% * 11;
>  Minibatch[  71-  80]: loss = 4.618088 * 10, metric = 100.00% * 10;
>  Minibatch[  81-  90]: loss = 4.261969 * 10, metric = 90.00% * 10;
>  Minibatch[  91- 100]: loss = 4.603288 * 11, metric = 100.00% * 11;
>  Minibatch[ 101- 110]: loss = 4.258807 * 10, metric = 90.00% * 10;
>  Minibatch[ 111- 120]: loss = 4.814735 * 12, metric = 100.00% * 12;
>  Minibatch[ 121- 130]: loss = 4.713617 * 11, metric = 100.00% * 11;
>  Minibatch[ 131- 140]: loss = 4.447034 * 10, metric = 100.00% * 10;
>  Minibatch[ 141- 150]: loss = 4.381915 * 10, metric = 100.00% * 10;
>  Minibatch[ 151- 160]: loss = 4.393627 * 11, metric = 100.00% * 11;
>  Minibatch[ 161- 170]: loss = 4.400418 * 11, metric = 100.00% * 11;
>  Minibatch[ 171- 180]: loss = 4.282081 * 13, metric = 100.00% * 13;
>  Minibatch[ 181- 190]: loss = 4.331329 * 10, metric = 100.00% * 10;
>  Minibatch[ 191- 200]: loss = 4.428235 * 10, metric = 100.00% * 10;
>  Minibatch[ 201- 210]: loss = 4.366571 * 10, metric = 100.00% * 10;
>  Minibatch[ 211- 220]: loss = 4.040700 * 12, metric = 83.33% * 12;
>  Minibatch[ 221- 230]: loss = 4.373926 * 10, metric = 100.00% * 10;
>  Minibatch[ 231- 240]: loss = 4.025659 * 10, metric = 100.00% * 10;
>  Minibatch[ 241- 250]: loss = 4.726648 * 10, metric = 100.00% * 10;
>  Minibatch[ 251- 260]: loss = 4.253503 * 10, metric = 100.00% * 10;
>  Minibatch[ 261- 270]: loss = 4.207678 * 10, metric = 100.00% * 10;
>  Minibatch[ 271- 280]: loss = 4.441064 * 10, metric = 100.00% * 10;
>  Minibatch[ 281- 290]: loss = 4.390820 * 10, metric = 100.00% * 10;
>  Minibatch[ 291- 300]: loss = 4.436923 * 11, metric = 100.00% * 11;
>  Minibatch[ 301- 310]: loss = 4.850146 * 10, metric = 100.00% * 10;
>  Minibatch[ 311- 320]: loss = 3.662903 * 10, metric = 100.00% * 10;
>  Minibatch[ 321- 330]: loss = 3.502393 * 10, metric = 70.00% * 10;
>  Minibatch[ 331- 340]: loss = 3.795721 * 11, metric = 81.82% * 11;
>  Minibatch[ 341- 350]: loss = 4.569397 * 12, metric = 91.67% * 12;
>  Minibatch[ 351- 360]: loss = 4.899304 * 10, metric = 100.00% * 10;
>  Minibatch[ 361- 370]: loss = 4.135977 * 13, metric = 92.31% * 13;
> Finished Epoch[1 of 80]: [Training] loss = 4.372033 * 399, metric = 96.99% * 399 9.435s ( 42.3 samples/s);
> Finished Evaluation [1]: Minibatch[1-9]: metric = 100.00% * 9;

* Considering that the length of the longest sequence is 29, how do I interprete this output? Note that the number of samples per 10 minibatches is always reported to be in the range [10, 13].
* Despite using the default value of None for max_samples in CrossValidationConfig, it is reporting 9 (there are 84 sequences in that dataset). How to I interpret and fix this?

When I set mbs = 30, it runs for a few epochs with the following output (crashed halfway):
>  Minibatch[   1-  10]: loss = 4.719921 * 22, metric = 100.00% * 22;
>  Minibatch[  11-  20]: loss = 4.649445 * 23, metric = 95.65% * 23;
>  Minibatch[  21-  30]: loss = 4.699832 * 27, metric = 100.00% * 27;
>  Minibatch[  31-  40]: loss = 4.678271 * 25, metric = 100.00% * 25;
>  Minibatch[  41-  50]: loss = 4.720496 * 31, metric = 96.77% * 31;
>  Minibatch[  51-  60]: loss = 4.541201 * 25, metric = 100.00% * 25;
>  Minibatch[  61-  70]: loss = 4.293928 * 29, metric = 96.55% * 29;
>  Minibatch[  71-  80]: loss = 4.753172 * 31, metric = 100.00% * 31;
>  Minibatch[  81-  90]: loss = 4.119446 * 29, metric = 93.10% * 29;
>  Minibatch[  91- 100]: loss = 4.220590 * 27, metric = 92.59% * 27;
>  Minibatch[ 101- 110]: loss = 4.235532 * 27, metric = 92.59% * 27;
>  Minibatch[ 111- 120]: loss = 4.385944 * 26, metric = 96.15% * 26;
>  Minibatch[ 121- 130]: loss = 3.861599 * 27, metric = 81.48% * 27;
>  Minibatch[ 131- 140]: loss = 4.031838 * 27, metric = 96.30% * 27;

and the following error:

> Selected GPU[0] Tesla K80 as the process wide default device.
> -------------------------------------------------------------------
> Build info: 
> 
> 		Built time: Nov 22 2017 21:46:56
> 		Last modified date: Mon Nov 13 23:32:21 2017
> 		Build type: release
> 		Build target: GPU
> 		With 1bit-SGD: no
> 		With ASGD: yes
> 		Math lib: mkl
> 		CUDA version: 9.0.0
> 		CUDNN version: 6.0.21
> 		Build Branch: HEAD
> 		Build SHA1: feade5b1bc1fbe6a8fc13b214f66aa89dac0db53
> 		MPI distribution: Open MPI
> 		MPI version: 1.10.7
> -------------------------------------------------------------------
> CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=cntk-vm ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
> Redirecting log to file /home/username/data/logs/log.txt
> Training 35321 parameters in 83 parameter tensors.
> Traceback (most recent call last):
>   File "train.py", line 165, in <module>
>     'prefix': args.prefix
>   File "train.py", line 135, in main
>     session.train()
>   File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
>     result = f(*args, **kwds)
>   File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/train/training_session.py", line 333, in train
>     super(TrainingSession, self).train(device)
>   File "/home/username/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 3361, in train
>     return _cntk_py.TrainingSession_train(self, computeDevice)
> RuntimeError: CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=cntk-vm ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
> 
> [CALL STACK]
> [0x7fc316e86ebc]                                                       + 0x5a3ebc
> [0x7fc311e41d43]                                                       + 0xb4fd43
> [0x7fc311e7d403]    Microsoft::MSR::CNTK::GPUMatrix<float>::  SetValue  (unsigned long,  unsigned long,  int,  float*,  unsigned long,  Microsoft::MSR::CNTK::DataTransferer*) + 0x183
> [0x7fc311dcd147]    Microsoft::MSR::CNTK::Matrix<float>::  SetValue  (unsigned long,  unsigned long,  int,  float*,  unsigned long,  Microsoft::MSR::CNTK::DataTransferer*) + 0xc7
> [0x7fc317109ec3]    std::pair<std::shared_ptr<Microsoft::MSR::CNTK::Matrix<float> const>,std::shared_ptr<Microsoft::MSR::CNTK::MBLayout>> CNTK::Utils::  GetCNTKImplMatrixAndMBLayoutFromValueObject  <float>(CNTK::Variable const&,  std::shared_ptr<CNTK::Value> const&,  CNTK::NDShape*,  std::shared_ptr<Microsoft::MSR::CNTK::Matrix<float>> const&,  std::shared_ptr<Microsoft::MSR::CNTK::Matrix<float>> const&) + 0xd63
> [0x7fc316fe7604]    Microsoft::MSR::CNTK::UnpackSequenceNode<float>::  BackpropToNonLooping  (unsigned long) + 0x3b4
> [0x7fc316f0ced4]    Microsoft::MSR::CNTK::ComputationNodeNonLooping<float>::  BackpropTo  (unsigned long,  Microsoft::MSR::CNTK::FrameRange const&) + 0x14
> [0x7fc3171ba2ae]    Microsoft::MSR::CNTK::ComputationNode<float>::  Backprop  (Microsoft::MSR::CNTK::FrameRange const&,  bool,  bool) + 0x7e
> [0x7fc317244811]    Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  Backprop  (Microsoft::MSR::CNTK::FrameRange const&,  bool,  bool) + 0xb1
> [0x7fc31706ecf3]    CNTK::CompositeFunction::  Backward  (std::shared_ptr<CNTK::BackPropState> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&) + 0x293
> [0x7fc3170f1cc7]    CNTK::Trainer::  ExecuteForwardBackward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&) + 0x5d7
> [0x7fc3170f2473]    CNTK::Trainer::  TrainLocalMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  bool,  CNTK::DeviceDescriptor const&) + 0xd3
> [0x7fc3170f313b]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&) + 0x4b
> [0x7fc3170f324e]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  CNTK::DeviceDescriptor const&) + 0xae
> [0x7fc316f69931]    CNTK::TrainingSession::  Train  (CNTK::DeviceDescriptor const&) + 0x211
> [0x7fc317acc18b]                                                       + 0x15418b
> [0x7fc3268da5e9]    PyCFunction_Call                                   + 0xf9
> [0x7fc326961bd5]    PyEval_EvalFrameEx                                 + 0x8fb5
> [0x7fc326962166]    PyEval_EvalFrameEx                                 + 0x9546
> [0x7fc326962b49]                                                       + 0x144b49
> [0x7fc326962cd8]    PyEval_EvalCodeEx                                  + 0x48
> [0x7fc3268b8661]                                                       + 0x9a661
> [0x7fc326885236]    PyObject_Call                                      + 0x56
> [0x7fc32695f234]    PyEval_EvalFrameEx                                 + 0x6614
> [0x7fc326962b49]                                                       + 0x144b49
> [0x7fc326961df5]    PyEval_EvalFrameEx                                 + 0x91d5
> [0x7fc326962166]    PyEval_EvalFrameEx                                 + 0x9546
> [0x7fc326962b49]                                                       + 0x144b49
> [0x7fc326962cd8]    PyEval_EvalCodeEx                                  + 0x48
> [0x7fc326962d1b]    PyEval_EvalCode                                    + 0x3b
> [0x7fc326988020]    PyRun_FileExFlags                                  + 0x130
> [0x7fc326989623]    PyRun_SimpleFileExFlags                            + 0x173
> [0x7fc3269a48c7]    Py_Main                                            + 0xca7
> [0x400add]          main                                               + 0x15d
> [0x7fc32593f830]    __libc_start_main                                  + 0xf0
> [0x4008b9]                                                            
> 
> cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)
> cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)
> terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
>   what():  Free in CUDAPageLockedMemAllocator failed: an illegal memory access was encountered (cuda error 77)

* I get the same problem with larger values for mbs as well. 

Searching for [illegal memory access](https://github.com/Microsoft/CNTK/issues?utf8=%E2%9C%93&q=illegal+memory+access) seems to indicate that this is common but there does not seem to be a fix. I'm running CNTK v2.3 (had the same problem in v2.2) on Ubuntu 16.04. 

[GIST](https://gist.github.com/frankibem/c6cce9d4013a5601a64f3f94eb9817e7) with scripts and instructions for reproduction.

**Comment by KeDengMS** [comment]
minibatch size is the total number of samples of all sequences in the minibatch, while the number in loss/metric is the number of labels. You have one label per sequence.

As to the illegal memory access, I tried your GIST in latest CNTK master and could not repro the issue. To debugging GPU errors precisely, please set environment variable CUDA_LAUNCH_BLOCKING=1. Otherwise, CUDA might report error asynchronously.

**Comment by frankibem** [comment]
Thanks for the clarifying the training output. Can you explain why the evaluation output is 9 (vs 84)? 

I've also tried setting CUDA_LAUNCH_BLOCKING=1, but the same error (slightly different call stack). Note that sometimes it runs through a lot of epochs before this happens.

> Selected GPU[0] Tesla K80 as the process wide default device.
> -------------------------------------------------------------------
> Build info: 
> 
> 		Built time: Nov 22 2017 21:46:56
> 		Last modified date: Mon Nov 13 23:32:21 2017
> 		Build type: release
> 		Build target: GPU
> 		With 1bit-SGD: no
> 		With ASGD: yes
> 		Math lib: mkl
> 		CUDA version: 9.0.0
> 		CUDNN version: 6.0.21
> 		Build Branch: HEAD
> 		Build SHA1: feade5b1bc1fbe6a8fc13b214f66aa89dac0db53
> 		MPI distribution: Open MPI
> 		MPI version: 1.10.7
> -------------------------------------------------------------------
> CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=cntk-vm ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
> Redirecting log to file /home/frank/data/logs/log.txt
> Training 35321 parameters in 83 parameter tensors.
> Traceback (most recent call last):
>   File "train.py", line 165, in <module>
>     'prefix': args.prefix
>   File "train.py", line 135, in main
>     session.train()
>   File "/home/frank/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
>     result = f(*args, **kwds)
>   File "/home/frank/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/train/training_session.py", line 333, in train
>     super(TrainingSession, self).train(device)
>   File "/home/frank/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 3361, in train
>     return _cntk_py.TrainingSession_train(self, computeDevice)
> RuntimeError: CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=cntk-vm ; expr=cudaMemcpy(Data(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetValueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
> 
> [CALL STACK]
> [0x7f14f50eeebc]                                                       + 0x5a3ebc
> [0x7f14f00a9d43]                                                       + 0xb4fd43
> [0x7f14f00e5403]    Microsoft::MSR::CNTK::GPUMatrix<float>::  SetValue  (unsigned long,  unsigned long,  int,  float*,  unsigned long,  Microsoft::MSR::CNTK::DataTransferer*) + 0x183
> [0x7f14f00e55b7]    Microsoft::MSR::CNTK::GPUMatrix<float>::  SetValue  (Microsoft::MSR::CNTK::GPUMatrix<float> const&) + 0x37
> [0x7f14f006ddac]    Microsoft::MSR::CNTK::Matrix<float>::  AssignValuesOf  (Microsoft::MSR::CNTK::Matrix<float> const&) + 0x50c
> [0x7f14f52f86f1]    void CNTK::CompositeFunction::  PopulateComputationNodeGradient  <float>(std::pair<CNTK::Variable,std::shared_ptr<CNTK::Value>> const&,  std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>&) + 0x4e1
> [0x7f14f52d1fba]    CNTK::CompositeFunction::  PopulateNetworkGradients  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&) + 0x24a
> [0x7f14f52d6c4b]    CNTK::CompositeFunction::  Backward  (std::shared_ptr<CNTK::BackPropState> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&) + 0x1eb
> [0x7f14f5359cc7]    CNTK::Trainer::  ExecuteForwardBackward  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&) + 0x5d7
> [0x7f14f535a473]    CNTK::Trainer::  TrainLocalMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  bool,  CNTK::DeviceDescriptor const&) + 0xd3
> [0x7f14f535b13b]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>>&,  CNTK::DeviceDescriptor const&) + 0x4b
> [0x7f14f535b24e]    CNTK::Trainer::  TrainMinibatch  (std::unordered_map<CNTK::Variable,std::shared_ptr<CNTK::Value>,std::hash<CNTK::Variable>,std::equal_to<CNTK::Variable>,std::allocator<std::pair<CNTK::Variable const,std::shared_ptr<CNTK::Value>>>> const&,  bool,  CNTK::DeviceDescriptor const&) + 0xae
> [0x7f14f51d1931]    CNTK::TrainingSession::  Train  (CNTK::DeviceDescriptor const&) + 0x211
> [0x7f14f5d3418b]                                                       + 0x15418b
> [0x7f1504b425e9]    PyCFunction_Call                                   + 0xf9
> [0x7f1504bc9bd5]    PyEval_EvalFrameEx                                 + 0x8fb5
> [0x7f1504bca166]    PyEval_EvalFrameEx                                 + 0x9546
> [0x7f1504bcab49]                                                       + 0x144b49
> [0x7f1504bcacd8]    PyEval_EvalCodeEx                                  + 0x48
> [0x7f1504b20661]                                                       + 0x9a661
> [0x7f1504aed236]    PyObject_Call                                      + 0x56
> [0x7f1504bc7234]    PyEval_EvalFrameEx                                 + 0x6614
> [0x7f1504bcab49]                                                       + 0x144b49
> [0x7f1504bc9df5]    PyEval_EvalFrameEx                                 + 0x91d5
> [0x7f1504bca166]    PyEval_EvalFrameEx                                 + 0x9546
> [0x7f1504bcab49]                                                       + 0x144b49
> [0x7f1504bcacd8]    PyEval_EvalCodeEx                                  + 0x48
> [0x7f1504bcad1b]    PyEval_EvalCode                                    + 0x3b
> [0x7f1504bf0020]    PyRun_FileExFlags                                  + 0x130
> [0x7f1504bf1623]    PyRun_SimpleFileExFlags                            + 0x173
> [0x7f1504c0c8c7]    Py_Main                                            + 0xca7
> [0x400add]          main                                               + 0x15d
> [0x7f1503ba7830]    __libc_start_main                                  + 0xf0
> [0x4008b9]                                                            
> 
> cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)
> cudaStreamDestroy failed (PrefetchGPUDataTransferer dtor): an illegal memory access was encountered (cuda error 77)
> terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
>   what():  Free in CUDAPageLockedMemAllocator failed: an illegal memory access was encountered (cuda error 77)

**Comment by frankibem** [comment]
@KeDengMS this issue seems to be sporadic, running to completion sometimes and not on other occasions. Here's another [repository](https://github.com/frankibem/cntk-issue) with instructions. 
- On windows 10 (v2.3.1, CPU-ONLY), the program crashes with no error message. 
- On Ubuntu 16.04 (v2.3.1 CPU-ONLY) it sometimes runs to completion but the epoch statistics are wrong as per #2505. 
- On Ubuntu 16.04 (v2.3.1 GPU), the reported statistics are correct, but it sometimes crashes with the error above and other times it doesn't.

**Comment by frankibem** [comment]
Seems to have been fixed in release 2.5
