### ISSUE TITLE
Boost error during build

### ISSUE THREAD

**Issue by DavidBrayford** [Microsoft/CNTK#2700]
When I try to build CNTK on a Xeon Phi system, the following BOOST_TEST errors with the configure line ../../configure --with-mkl=/lrz/sys/intel/studio2017_u4/compilers_and_libraries_2017.4.196/linux/mkl/ --with-boost=/lrz/sys/libraries/boost/1.58_gcc --asgd=yes --with-protobuf=/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/protobuf --mpi=yes --with-mpi=/lrz/sys/intel/studio2017_u4/impi/2017.3.196
:

/lrz/sys/intel/studio2017_u4/impi/2017.3.196/bin64/mpicxx -c Source/../Tests/UnitTests/ReaderTests/ReaderUtilTests.cpp -o /home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/CNTK/build/release/.build/Source/../Tests/UnitTests/ReaderTests/ReaderUtilTests.o -DHAS_MPI=1 -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DUSE_MKL -DNDEBUG -DNO_SYNC -DASGD_PARALLEL_SUPPORT  -DCNTK_COMPONENT_VERSION="2.3" -DUSE_ZIP -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/CNTKv2LibraryDll/proto -ISource/../Examples/Extensibility/CPP -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -ISource/PerformanceProfilerDll -I/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/protobuf/include -I/lrz/sys/intel/studio2017_u4/compilers_and_libraries_2017.4.196/linux/mkl//include -I/lrz/sys/libraries/boost/1.58_gcc/include -I/usr/include -I/usr/lib/libzip/include -I/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/include -I/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/opencv/include -ISource/Multiverso/include -ITests/EndToEndTests/CNTKv2Library/Common -I/lrz/sys/libraries/boost/1.58_gcc/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF /home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/CNTK/build/release/.build/Source/../Tests/UnitTests/ReaderTests/ReaderUtilTests.d

Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp: In lambda function:
Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp:1173:98: error: ‘BOOST_TEST’ was not declared in this scope
                 BOOST_TEST((s.m_data.empty() && numberOfMinibatches == 1 && numberOfSamples == 0));
                                                                                                  ^
Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp:1185:87: error: ‘BOOST_TEST’ was not declared in this scope
                 BOOST_TEST(((maxMBSize / p.sequenceLength) == numSequencesInTheLastMB));
                                                                                       ^
Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp:1189:96: error: ‘BOOST_TEST’ was not declared in this scope
                 BOOST_TEST((ceil(lastMBSize*1.0 / p.sequenceLength) == numSequencesInTheLastMB));
                                                                                                ^
Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp:1192:106: error: ‘BOOST_TEST’ was not declared in this scope
             BOOST_TEST((numberOfSamples <= epochSize || (numberOfSamples - epochSize) < p.sequenceLength));
                                                                                                          ^
Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp: In member function ‘void Microsoft::MSR::CNTK::Test::PackerTests::TestTruncatedBpttPacker::test_method()’:
Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.cpp:1802:32: error: ‘BOOST_TEST’ was not declared in this scope
     BOOST_TEST(!mb.m_endOfSweep);
                                ^
Makefile:1536: recipe for target '/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/CNTK/build/release/.build/Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.o' failed
make[1]: *** [/home/hpc/pr28fa/di72giz/CNTK_CoolMUC3/CNTK/build/release/.build/Source/../Tests/UnitTests/ReaderTests/ReaderLibTests.o] Error 1

Any suggestions on how I go about resolving this issue?

Regards
David

**Comment by ebarsoumMS** [comment]
Sorry we don't support Xeon Phi. currently.
