### ISSUE TITLE
CNTK 2.3 GPU version NuGet package missing

### ISSUE THREAD

**Issue by kun-attila** [Microsoft/CNTK#2709]
The link on the release page points to the version 2.2. Moreover I can't find in the VS package manager either.

**Comment by IvoTops** [comment]
See #2673. It has been 10 days now. Can somebody PLEASE update the GPU Nuget package for C# also to v2.3 ????

**Comment by manikjindal** [comment]
CNTK 2.3 GPU NuGet package has been published [here](https://www.nuget.org/packages/CNTK.GPU/2.3.0)
