### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hellosaumil** [Microsoft/CNTK#2715]
While running `DetectionDemo.py` under `Examples/Image/Detection` I get the following error:
`TypeError: 'NoneType' object is not subscriptable`

Detailed error:
```
Mean AP = 0.9604
detecting objects in image /notebooks/CNTKApps/Codes/Examples/Image/DataSets/Grocery/../DataSets/Grocery/testImages/WIN_20160803_11_28_42_Pro.jpg
Traceback (most recent call last):
  File "DetectionDemo.py", line 88, in <module>
    regressed_rois, cls_probs = od.evaluate_single_image(eval_model, img_path, cfg)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/utils/od_utils.py", line 75, in evaluate_single_image
    regressed_rois, cls_probs = evaluator.process_image(img_path)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/FasterRCNN/FasterRCNN_eval.py", line 27, in process_image
    out_cls_pred, out_rpn_rois, out_bbox_regr, dims = self.process_image_detailed(img_path)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/FasterRCNN/FasterRCNN_eval.py", line 34, in process_image_detailed
    _, cntk_img_input, dims = load_resize_and_pad(img_path, self._img_shape[2], self._img_shape[1])
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/utils/plot_helpers.py", line 36, in load_resize_and_pad
    return resize_and_pad(img, width, height, pad_value)
  File "/notebooks/CNTKApps/Codes/Examples/Image/Detection/utils/plot_helpers.py", line 39, in resize_and_pad
    img_width = len(img[0])
TypeError: 'NoneType' object is not subscriptable

```

@KeDengMS @spandantiwari @tangyuq @cha-zhang @sayanpa

**Comment by gviscoli** [comment]
Hi,
I have the same issue.
Is there anyone who has solved the problem?

**Comment by KeDengMS** [comment]
It seems img is None, coming from OpenCV in [this line](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/utils/plot_helpers.py#L35). Please check your image file path.

**Comment by gviscoli** [comment]
If I run DetectionDemo.py with Visual Studio, it works fine (see image below).

<img width="584" alt="detectiondemo-vsto" src="https://user-images.githubusercontent.com/34619367/34457641-ed8f401e-edb6-11e7-9a8a-d92c391810d5.png">

If I run DetectionDemo.py with python command line, I get the error.

I think there could be a permission problem, but I am not sure...

**Comment by j-lane7** [comment]
For me, I was getting this error when trying to not only pass a file name with spaces and () but also in a directory with spaces.  I changed both of those and the problem went away.

**Comment by oliver9523** [comment]
I fixed this by updating the hardcoded path in DetectionDemo.py line 67

it originally reads
img_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), r"../DataSets/Grocery/testImages/WIN_20160803_11_28_42_Pro.jpg")

which evaluated the path to "CNTK\CNTK-Samples-2-2\Examples\Image\DataSets\Grocery\../DataSets/Grocery/testImages/WIN_20160803_11_28_42_Pro.jpg"

so I just updated it to 
img_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), r"testImages/WIN_20160803_11_28_42_Pro.jpg")
