### ISSUE TITLE
Not recognizing GPU for Surface Book i7 GeForce GTX 965M 

### ISSUE THREAD

**Issue by mohamedmansour** [Microsoft/CNTK#2716]
Hello, my GPU has 5.2 CUDA capability, and when I do the following:

`print(C.device.all_devices())`

It returns:

`(GPU[0] GeForce GTX 965M, CPU)`

So when I enable it:

```
try:
    C.device.try_set_default_device(C.device.gpu(0))
    print("GPU available.")
except:
    print("GPU unavailable. Using CPU instead.")
```
It always prints:

`GPU unavailable. Using CPU instead.`

Any idea how I can debug further?

**Comment by ArchiDevil** [comment]
Why do you use 1 as GPU index here if you have only one device?

**Comment by e-thereal** [comment]
Adding to archi's comment, the device ID is given with a zero-based index, so you should try gpu(0) instead of gpu(1). Can you please confirm if that solved your issue?
