### ISSUE TITLE
RuntimeError: Batch normalization training on CPU is not yet implemented

### ISSUE THREAD

**Issue by hellosaumil** [Microsoft/CNTK#2722]
Running `CNTK_301_Image_Recognition_with_Deep_Transfer_Learning` on CNTK `v2.3` docker yields to following error.

```
Training transfer learning model for 5 epochs (epoch_size = 1020).
Training 52326 parameters in 2 parameter tensors.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-6d65fd9b7a4f> in <module>()
     25     trained_model = train_model(base_model,
     26                                 flowers_model['num_classes'], flowers_data['training_map'],
---> 27                                 learning_params)
     28     trained_model.save(flowers_model['model_file'])
     29     print("Stored trained model at %s" % flowers_model['model_file'])

<ipython-input-10-f3b8840f83d0> in train_model(model_details, num_classes, train_map_file, learning_params, max_images)
     39         while sample_count < epoch_size:  # loop over minibatches in the epoch
     40             data = minibatch_source.next_minibatch(min(minibatch_size, epoch_size - sample_count), input_map=input_map)
---> 41             trainer.train_minibatch(data)                                    # update model with it
     42             sample_count += trainer.previous_minibatch_sample_count          # count samples processed so far
     43             progress_printer.update_with_trainer(trainer, with_metric=True)  # log progress

~/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/train/trainer.py in train_minibatch(self, arguments, outputs, device, is_sweep_end)
    179             if contains_minibatch_data:
    180                 updated = super(Trainer, self).train_minibatch_overload_for_minibatchdata(
--> 181                     arguments, device)
    182             else:
    183                 updated = super(Trainer, self).train_minibatch(arguments, is_sweep_end,

~/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py in train_minibatch_overload_for_minibatchdata(self, *args)
   2848 
   2849     def train_minibatch_overload_for_minibatchdata(self, *args):
-> 2850         return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
   2851 
   2852     def train_minibatch(self, *args):

RuntimeError: Batch normalization training on CPU is not yet implemented.
```

Please help. @KeDengMS @spandantiwari @cha-zhang @sayanpa @tangyuq @frankibem

**Comment by hellosaumil** [comment]
Though @KeDengMS said in #2643 that the changes had been merged, I face this error.

**Comment by hellosaumil** [comment]
While running `CNTK_201B_CIFAR-10_ImageHandsOn.ipynb` I also get this error `RuntimeError: Batch normalization training on CPU is not yet implemented.`

```
Training 117290 parameters in 18 parameter tensors.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-478881b3619e> in <module>()
      2                                          reader_test,
      3                                          max_epochs=5,
----> 4                                          model_func=create_basic_model_with_batch_normalization)

<ipython-input-12-30fbdcf544f0> in train_and_evaluate(reader_train, reader_test, max_epochs, model_func)
     56             data = reader_train.next_minibatch(min(minibatch_size, epoch_size - sample_count), 
     57                                                input_map=input_map) # fetch minibatch.
---> 58             trainer.train_minibatch(data)                                   # update model with it
     59 
     60             sample_count += data[label_var].num_samples                     # count samples processed so far

~/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/train/trainer.py in train_minibatch(self, arguments, outputs, device, is_sweep_end)
    179             if contains_minibatch_data:
    180                 updated = super(Trainer, self).train_minibatch_overload_for_minibatchdata(
--> 181                     arguments, device)
    182             else:
    183                 updated = super(Trainer, self).train_minibatch(arguments, is_sweep_end,

~/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py in train_minibatch_overload_for_minibatchdata(self, *args)
   2848 
   2849     def train_minibatch_overload_for_minibatchdata(self, *args):
-> 2850         return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
   2851 
   2852     def train_minibatch(self, *args):

RuntimeError: Batch normalization training on CPU is not yet implemented.
```
@KeDengMS @spandantiwari @cha-zhang @sayanpa @tangyuq @frankibem

**Comment by frankibem** [comment]
Like the error says, training with batch normalization is not yet implemented for CPU. You'll need a GPU to run the entire notebook. According to the [docs](https://www.cntk.ai/pythondocs/layerref.html#id40): 

> Batch normalization currently requires a GPU for training

If you don't have a GPU, you'll have to skip that section for now.

**Comment by hellosaumil** [comment]
@frankibem According to #2643 changes have been merged. But it's fine if I get this feature in 2.4.

I'm new to CNTK and I'm still catching up on few things. Meanwhile, if you can share the details how to compile CNTK directly from the sources, it would be of a great help. Thank You.

**Comment by frankibem** [comment]
I haven't done it before myself but the instructions are [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows) (windows) and [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows) (Linux)

**Comment by hellosaumil** [comment]
@frankibem CNTK is working properly, setup instructions are not needed.

I was hoping if you could connect me with someone who help implement Deep Transfer Learning on CPU.

**Comment by KeDengMS** [comment]
CPU batch normalization training is [available](https://github.com/Microsoft/CNTK/commit/1d3d1e8a2770b65a809f6bf7e6cde49047ffc0c6) in latest master. Please build from source if you need to train BN on CPU.

**Comment by hellosaumil** [comment]
@KeDengMS Thanks for responding. I installed v2.3 py36 CPU docker image few hours back and ran the above codes. It appears that changes are not reflected in the `microsoft/cntk:2.3-cpu-python3.5` docker image. Please help.

**Comment by KeDengMS** [comment]
We'll have a 2.3.1 release soon if you want binary install. Otherwise, please try build from source.

**Comment by hellosaumil** [comment]
@KeDengMS Sorry, but to build from source mean using `pip install <url>`

Thank You.

**Comment by mx-iao** [comment]
@hellosaumil no, to build from source, follow the instructions in this section: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-from-source. `pip install <*.whl>` is for installation from precompiled binaries (see [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-your-machine)). There should be a CNTK 2.3.1 wheel release later today, which will include CPU BN training (you can use `pip install` in this case).

**Comment by hellosaumil** [comment]
@mx-iao Thank you very much for your help.  Appreciate it.

**Comment by hellosaumil** [comment]
I downloaded CNTK `v2.3.1` wheel, Batch Normalization works perfectly.

Thanks @KeDengMS @mx-iao
