### ISSUE TITLE
about C1_DrawBboxesOnImages.py executing problem

### ISSUE THREAD

**Issue by mtkbf** [Microsoft/CNTK#2742]
Dear Experts

When I execute "phyton3 C1_DrawBboxesOnImages.py", under the folder: /CNTK_master/Examples/Image/Detection/utils/annotations.

I encounter following problem:: 
  File "~/CNTK_master/Examples/Image/Detection/FastRCNN/BrainScript/fastRCNN/imdb.py", line 17, in <module>
    from .utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'fastRCNN.utils.cython_bbox'

I can not found cython_bbox.py under entire CNTK_master folder.
Can somebody show me any tip on this problem?
Really appreciated...

Regards,
BF

**Comment by spandantiwari** [comment]
Can you try adding the Examples/Image/Detection/FastRCNN/utils/cython_modules folder to PYTHONPATH environment variable? Also, note that only certain Python versions are supported for Windows and Linux (you can see which from the names of the binaries in that folder).
