### ISSUE TITLE
Arg max returns only flatten index

### ISSUE THREAD

**Issue by MMRohe** [Microsoft/CNTK#2744]
Hello,

as I am working with a network that is supposed to detect object using heatmap I would like to get the maximum value of a (32,32,32) tensors as a the index coordinates (x,y,z).

C.ops.argmax is supposed to do just that but instead of returning the coordinates in (x,y,z) it returns me a flatten index. It would be good if a option to return the coordinates would be available.

I did not find any way to convert a flatten index to a coordinate tensor using cntk, any idea ?

Thanks for your help

**Comment by KeDengMS** [comment]
This is the same semantics as numpy.argmax. To get coordinate, you can do something like this:

    import cntk as C
    import numpy as np
    input_shape = (32,32,32)
    x = C.input_variable(input_shape)
    flatten_index = C.argmax(x)
    coords = []
    for i in range(len(input_shape)):
        count = np.prod(x.shape[i+1:])
        coord = C.floor(flatten_index / count)
        flatten_index = flatten_index - coord * count
        coords.append(coord)
    coords = C.splice(*coords)

**Comment by MMRohe** [comment]
Thanks it is working fine.
