### ISSUE TITLE
Misleading CUDA Version under Docker enviroment

### ISSUE THREAD

**Issue by waltersharpWEI** [Microsoft/CNTK#2747]
I am using the latest CNTK commit install from source based on the official compile document:
System Spec:
CUDA 8.0.0
CUDNN 6.0.21
I build the CNTK on a machine with GPU GTX780
and things works well
![image](https://user-images.githubusercontent.com/29820060/33749388-83cd3920-dc08-11e7-86eb-48fb1c09bd8d.png)

then I pull the image and run it on a TitanX Pascal machine,
It turns out the CUDA version become 9.0.0
![image](https://user-images.githubusercontent.com/29820060/33749434-b11e1a02-dc08-11e7-97d3-5e46bb324587.png)

in fact I didn't install CUDA 9.0.0 on TitanX host machine and never rebuilt the CNTK.

I guess it could be related to nvml problem from Nvidia

**Comment by KeDengMS** [comment]
Seems should call cudaRuntimeGetVersion instead of cudaDriverGetVersion.

**Comment by manikjindal** [comment]
Fixed in CNTK 2.4
