### ISSUE TITLE
When will CNTK support Titan V (Volta)?

### ISSUE THREAD

**Issue by IvanFarkas** [Microsoft/CNTK#2749]
When will **CNTK** support **[Titan V](https://www.nvidia.com/en-us/titan/titan-v/)** ([Volta architecture](https://www.nvidia.com/en-us/data-center/volta-gpu-architecture/))?

**Comment by KeDengMS** [comment]
It's planned for the next release in February.

**Comment by IvanFarkas** [comment]
Fantastic! Thx, Ivan
