### ISSUE TITLE
CNTK_301_Image_Recognition_with_Deep_Transfer_Learning - data error

### ISSUE THREAD

**Issue by IvanFarkas** [Microsoft/CNTK#2750]
Running CNTK 2.3 GPU 1SGD

**CNTK_301_Image_Recognition_with_Deep_Transfer_Learning** step 5 fails with this error:

```
IndexError                                Traceback (most recent call last)
<ipython-input-6-eb7fb2774966> in <module>()
    114 
    115 print('Downloading flowers and animals data-set, this might take a while...')
--> 116 flowers_data = download_flowers_dataset()
    117 animals_data = download_animals_dataset()
    118 print('All data now available to the notebook!')

<ipython-input-6-eb7fb2774966> in download_flowers_dataset(dataset_root)
     86         # Confusingly the training set contains 1k images and the test set contains 6k images
     87         # We swap them, because we want to train on more data
---> 88         write_to_file(flowers_data['training_map'], image_paths[idx_train], image_labels[idx_train])
     89         write_to_file(flowers_data['testing_map'], image_paths[idx_test], image_labels[idx_test])
     90         write_to_file(flowers_data['validation_map'], image_paths[idx_val], image_labels[idx_val])

IndexError: index 6764 is out of bounds for axis 0 with size 11
```

**Comment by hellosaumil** [comment]
@IvanFarkas Hi, I re-ran this notebook. Everything worked fine on `v2.3.1`. 

It seems as if the downloaded dataset might be corrupted? Can try removing existing data files from `/Examples/Image/DataSets/Flowers`? And try downloading it again?

**Comment by IvanFarkas** [comment]
I'll try as soon as v2.3.1 is available to install or I can **build with VS 2017** (**looong time overdue!**).

**Comment by hellosaumil** [comment]
@IvanFarkas It is already available at [Setup Linux Python](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python?tabs=cntkpy231). Just do `pip install <url>`

**Comment by hellosaumil** [comment]
@IvanFarkas Please close this issue if already solved. Thank You.

**Comment by IvanFarkas** [comment]
Since I set the **CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY** environment variable there were some dataset prerequisites needed to be satisfied.
After I did that it ran **successfully**.
