### ISSUE TITLE
Empty FlowersPredictions.txt file after executing CNTK_301_Image_Recognition_with_Deep_Transfer_Learning

### ISSUE THREAD

**Issue by hellosaumil** [Microsoft/CNTK#2753]
Hi, I ran `CNTK_301_Image_Recognition_with_Deep_Transfer_Learning` on `v2.3.1` on CPU.

Everything executed successfully. Though the output wasn't written under `./temp/Output/FlowersPredictions.txt`. 

Only an empty file was created. 

What am I missing here? Please help. Thank You. 

@KeDengMS @cha-zhang @sayanpa @tangyuq @spandantiwari @dongyu888 @frankibem @mx-iao

**Comment by KeDengMS** [comment]
Please uncomment this line to get the output for now:
#np.savetxt(results_file, probs[np.newaxis], fmt="%.3f")

**Comment by hellosaumil** [comment]
Thank you, @KeDengMS. Sorry, I totally missed it.
