### ISSUE TITLE
Documentation request: CHW and HWC layouts

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#276]
I wish to request more information on CHW and HWC layouts. I've heard these terms only within the context of CNTK, so it would be helpful if this terminology was defined, referenced to outside docs, and explained so that we can know the relevance to CPU vs GPU architectures, implementations and performance. I haven't quite connected all the dots. I've been reading the code, wikis and tutorial2. These layouts seem to have more impact than the obvious, possibly because of differences between implementations and old/new code strategies. 

True/false (to confirm and clarify)?

1.  the abbreviations: H=height, W=width, C=channel? 
2.  [Assume RGB image] HWC or CHW means that the image is laid out by color space channel: R1, R2, ..., G1, G2, ..., B1, B2, ... or by pixel as R1, G1, B1, R2, G2, B2, ... respectively? HWC=values laid out as top->bottom, left->right, front->back aka column-major and channel-minor. 
3.  cuDNN/cuBLAS (NV GPU in general) performs better (accuracy or time) on CHW than HWC? Or maybe just less complex coding model?
4.  The master branch only allows the slower legacy HWC format on CPU. Although there is a branch containing a faster, but not fully proven CHW implementation for CPU. (Alexey)
5.  WHC is simply a transpose (rotation about the C axis) of HWC and offers no performance/accuracy benefits in theory?
6.  HWC will eventually be deprecated in CNTK? Currently, it is the only way to use CPU? 
7.  CHW is sometimes referred to "cudnn" in the examples and documentation.
8.  Not all examples can run on CPU? MNIST examples work for sure, but I'm having difficulties with ImageNet (ResNet and AlexNet). Is this the case? If so, will I run into this again with other examples. I also noticed that performance numbers have not been published for CPU only. 

References: 

@Alexey-Kamenev
#186 
#161

**Comment by frankseide** [comment]
For 2., I think it's the other way round; please see below.

For 3., cudnn does not support HWC. That's the reason we had to introduce CHW as a second format, which is now the main format.

For 5., no accuracy difference, but potentially a speed difference due to layout possibly being more efficient for GPUs. And an actual speed difference due to ongoing significant investment of NVidia in cudnn.

For 4. and 8., it is just a matter of time until this will land in master.

All else is correct.

There is some documentation in ConvolutionNodes.h (to which I just added the HWC/CWH monikers), let me copy it here. Maybe we should take this as a starting point for official documentation. However, the legacy HWC format should really just not be used anymore.
```
// -----------------------------------------------------------------------
// ConvolutionNode (convolutionWeights, inputFeature)
// -----------------------------------------------------------------------

// Convolutions (incl. pooling) support two different storage formats:
//
// * legacy ("HWC") mode (CPU and GPU without cudnn): Channels are tuples of scalars
//
//    This follows "high performance convolutional neural networks for document processing" by Kumar Chellapilla, Sidde Puri, and Patrice Simard.
//    Each sample is stored as a column-major matrix (height, width) of float[numChannels] (r00, g00, b00, r10, g10, b10, r01, g01, b01, r11, g11, b11).
//
//     - input :  [C  x W  x H      x T]  or  ARRAY[1..T] OF                ARRAY[1..H]  OF ARRAY[1..W]  OF ARRAY[1..C]
//     - output : [C' x W' x H'     x T]  or  ARRAY[1..T] OF                ARRAY[1..H'] OF ARRAY[1..W'] OF ARRAY[1..C']
//     - filter : [C' x W" x H" x C    ]  or                 ARRAY[1..C] OF ARRAY[1..H"] OF ARRAY[1..W"] OF ARRAY[1..C']
//
// * cudnn ("CHW") mode (GPU only): Channels are planes
//
//     - input :   [W  x H  x C       x T]   or  ARRAY[1..T] OF                 ARRAY[1..C]  OF ARRAY[1..H]  OF ARRAY[1..W]
//     - output :  [W' x H' x      C' x T]   or  ARRAY[1..T] OF ARRAY[1..C'] OF                 ARRAY[1..H'] OF ARRAY[1..W']
//     - filter :  [W" x H" x C  x C'    ]   or                 ARRAY[1..C'] OF ARRAY[1..C]  OF ARRAY[1..H]  OF ARRAY[1..W]
//
// where:
//  - using ' for output and " for filter
//  - T = samples (NVidia calls this N)
//  - W, H = width, height (W', H' for output, W", H" for kernel)
//  - C = input channels
//     - 3 for color images, 1 for B&W images
//     - for hidden layer: dimension of activation vector for each pixel
//  - C' = output channels = dimension of activation vector for each pixel (also called N by NVidia, inconsistently)
```

**Comment by Alexey-Kamenev** [comment]
Let me also explain where those names (`CHW`/`HWC` etc) are coming from. It is essentially the same terminology that is used by [cuDNN](https://developer.nvidia.com/cudnn) (see cuDNN API reference/manual). cuDNN is a very popular library which is supported by all popular DNN toolkits, not just CNTK, so we decided to use the same terminology to simplify migration between the toolkits. Note that cuDNN also uses `N` for a sample in a batch and `D` for the depth dimension used, for example,  in 3D convolutions, so full description of the data layout may look like: `NCHW`. We understand it's not ideal and may sometimes lead to confusion especially for people not familiar with cuDNN but the alternative (e.g. using row-major/column-major terminology) seems to be even more confusing.

For 2. - as Frank said, it's the other way around (`CHW`: `RR...R, GG..G, BB..B`; `HWC`: `RGB, RGB, ... RGB`).

As for CPU: we will have fast implementation of convolutions (including ND convolutions) for CHW format somewhere in the future but I cannot give any timeline. Reference (i.e. slow) implementation is available in my branch (`alexeyk/ndconv`).

**Comment by ldmtwo** [comment]
Thanks. That's very helpful. Can you give me a list of topologies and datasets or simply examples that will run on CPU as is in the current build?

**Comment by Flav1u** [comment]
Since the last post is 3 months old ... I'm just wondering if the CHW format is now supported to run on CPU ?

**Comment by mikhail-barg** [comment]
In case somebody reads this issue, here's a documentation link: https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluate-Image-Transforms#layout-conversion-from-hwc-to-chw

**Comment by ldmtwo** [comment]
That's awesome! Thanks.

Sent by LD's TI-84 calculator
