### ISSUE TITLE
file extension (.dnn, .model, .cmf)

### ISSUE THREAD

**Issue by AnupViAn** [Microsoft/CNTK#2764]
Can you please help me out to understand these file extensions? 
.dnn
.model
.cmf
.ckp
And which file name (trainModel.dnn/trainModel.model/trainModel.cmf) should I use while saving my train model?

z = createModel(...)
z.save(model_filename)

model_filename = ?

**Comment by mx-iao** [comment]
The file extension doesn't matter; it's up to you.  When you use save(), all models are saved to the CNTK v2 model format (see [here](https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-model-format)). So for example, you can do `z.save("my_model.dnn")`. When you reload the model, just make sure you reload from the same filename with the same extension: 
```
from cntk.ops.functions import load_model
z.load_model("my_model.dnn")
```

**Comment by AnupViAn** [comment]
@mx-iao Thank you very much.
