### ISSUE TITLE
How to get the filename that currently ImageDeserializer trying to load it.

### ISSUE THREAD

**Issue by kkc0923** [Microsoft/CNTK#2765]
When I using MinibatchSource with built-in ImageDeserializer, the application looks stuck at specific time. I think that some images has incorrect data and ImageDeserializer may fails to load it. But with my own UserMinibatchSource which uses scikit-image to load image, all of images are loaded correctly and processed. So I want to know  what image is problem and when ImageDeserializer is stuck. Can I get the filename which ImageDeserializer currently trying to load it?

**Comment by eldakms** [comment]
Not sure if this is possible. Try putting verbosity to > 3.

**Comment by kkc0923** [comment]
Thanks for reply.
