### ISSUE TITLE
What does >> in Sequential() mean in CNTK?

### ISSUE THREAD

**Issue by woskii** [Microsoft/CNTK#2768]
I am trying to understand the source code of CNTK. In the python API 'def Sequential' (location: bindings/python/cntk/layers/higher_order_layers.py), there is a line as follows: 
composed_function = reduce(lambda f, g: f >> g, layers, identity)
What does '>>' mean in CNTK?Is it a overload operation in CNTK?I know 'Sequential' is a function that accepts one argument and applies the given `functions` one after another,but how does it work?
I am not sure whether I explain it clearly,any help would be appreciated.

**Comment by bencherian** [comment]
`>>` is overloaded to be the same as applying Sequential on applying two elements, i.e., `f >> g >> h` is the same as `Sequential([f, g, h])`

**Comment by n17s** [comment]
@bencherian  is right, it's just function composition. This allows to compose functions with minimal notation. For example, here's how to do a recurrence where each step is a GRU followed by layer nomalization:
```python
y = C.layers.Recurrence(C.layers.GRU(256) >> C.layers.LayerNormalization())(x)
```

**Comment by woskii** [comment]
Thanks very much！
