### ISSUE TITLE
Sequence2Sequence.py Out of Memory

### ISSUE THREAD

**Issue by wolfshow** [Microsoft/CNTK#2771]
I tried to modify the code for a machine translation task with the vocab size = 60000 and embedding length = 128. But always got out of memory error with GPU in the following function. Does it support this task?
[https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/Python/Sequence2Sequence.py](url)

def create_sparse_to_dense(input_vocab_dim):
    I = Constant(np.eye(input_vocab_dim))
    @Function
    @Signature(InputSequence[SparseTensor[input_vocab_dim]])
    def no_op(input):
        return times(input, I)
    return no_op

**Comment by NoneWait** [comment]
Had you

**Comment by NoneWait** [comment]
Did you solved it?
