### ISSUE TITLE
is there any roadmap for cntk?

### ISSUE THREAD

**Issue by xmm1989218** [Microsoft/CNTK#2787]
is there any roadmap for cntk?

**Comment by eldakms** [comment]
Usually iteration plans are published here:
https://github.com/Microsoft/CNTK/wiki/Iteration-Plans

**Comment by aWeinzierl** [comment]
What does it mean, if there is none? 
For instance, there is no plan for anything beyond October.

**Comment by eldakms** [comment]
Most people are on holidays, I think there will be the next iteration published in January.

**Comment by ebarsoumMS** [comment]
The next version of CNTK 2.4 will have the following:

1. Move to CUDA9, cuDNN7 and VS2017
2. fp16 support
3. Use MKL-DNN, this one gave us a huge boots in CPU performance.
4. Better support to ONNX standard.
5. A lot of additional OPs and bug fixes.

Thanks,
Emad
