### ISSUE TITLE
input shape dimensions different between python and csharp

### ISSUE THREAD

**Issue by franperezlopez** [Microsoft/CNTK#2790]
Hi,

I've got the following issue loading a model which has been processed with keras. I can share the code, but basically I used the Inception model from keras:
```python
K.set_image_data_format('channels_first')
model = InceptionV3(weights="imagenet", include_top=False, input_shape=(IM_CHANNELS, IM_WIDTH, IM_HEIGHT)) #include_top=False excludes final FC layer
```
I'm doing transfer learning (include_top=False), and final layer is a 4-dimensions layer. At the end of the training, I rechecked input & output model dimensions:
![image](https://user-images.githubusercontent.com/1222398/34168673-6936dc7a-e4e5-11e7-853c-aec5c35e51a3.png)

After this, I load the saved model in C#, but to my surprise, the input shape dimensions are `[224,224,3]`. This model can be retrieved from [here](https://1drv.ms/u/s!AriUTSXY-Oo8mYEo6as_EqJi_LFzYA). Nevertheless, I tried to evaluate the model in C#, shaping the image in different ways, but I never got the same evaluation I got in python. 

If I load model in keras using `channels_last` configuration, in python the input dimensions are as expected (`[224,224,3]`), and again, in C# dimensions are swapped (in this case `[3, 224, 224]`)

I think this issue is related with this other one https://github.com/Microsoft/CNTK/issues/2398 , but I wanted to be sure. 

In case you need some demo code, I could do also, but is pretty basic: load the [model](https://1drv.ms/u/s!AriUTSXY-Oo8mYEo6as_EqJi_LFzYA), in python and C#, check input node dimensions and you will notice the differences

Is there any workaround for this bug??

fran

**Comment by ebarsoumMS** [comment]
The input it isn't different as it might seem. CNTK internally is column major, so (224,224,3) column major is the same as (3,224,224) row major. In python API, we reverse all the shapes in order to be similar to other DNN frameworks. The C# binding doesn't do that and is similar to the C++ API.

**Comment by kkc0923** [comment]
@ebarsoumMS 
I have exactly same issue for this.
I trained my network (resnet152) in python, its input shape is 3x224x224 (channel, height, width). And the input shape of loaded network on csharp is 224x224x3. But what is correct order of csharp version?
(height x width x channel) or (width x height x channel)?

It seems that ParallelExtractCHW() is row-major of (channel x height x width), so is it same to (width x height x channel) of column major? Can I consider that all of shape of python is reverted on csharp, like np.transpose(2,1,0) and but safely use same memory-layoued input data regardless python or csharp?

**Comment by ebarsoumMS** [comment]
@kkc0923 if you look at the python API, we actually reverse the shape before passing the parameters to the C++ API, so WHC should be the right one. @liqunfu

**Comment by kkc0923** [comment]
@ebarsoumMS Thank you for reply. Please close this issue :)
