### ISSUE TITLE
Feature request: ImageReader support for multi-dimensional labels

### ISSUE THREAD

**Issue by haixpham** [Microsoft/CNTK#2791]
Currently ImageReader only supports one integer value for label - which is suitable for classification task. But in regression task, we have a vector associated with each image.

I implemented a reader in Python, but obviously it takes more time (twice) in training due to Python's single-thread issue. Do you have plan to extend ImageReader in C++ to support multi-dimensional label?

Thanks

**Comment by eldakms** [comment]
You should be able to combine image and cntk text format deserializers, please have a look at regression sample here (https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Regression). It is in brain script but you can do similar thing in python, giving two deserializers to the minibatch source. Thanks!
