### ISSUE TITLE
[Python] How to get the activation function of a Dense block

### ISSUE THREAD

**Issue by Master76** [Microsoft/CNTK#2792]
I'm working on a job to convert CNTK model to another format, I load the model, and can get the value of W and b for a Dense block easily, but how can I get the activation function?

**Comment by ebarsoumMS** [comment]
Activation is not a stored property to dense block. To find the activation, you can treat the dense block and sub-graph and do a DFS to find the activation. Here an example of DFS on CNTK graph: https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/logging/graph.py

**Comment by Master76** [comment]
@ebarsoumMS Many thanks.
