### ISSUE TITLE
CIFAR-10 example failed with exception: NotifyFunctionValuesMBSizeModified....

### ISSUE THREAD

**Issue by LairMan** [Microsoft/CNTK#280]
Hello,
I have just downloaded and compiled the CNTK (Windows 10, VC++2013) and I'm trying to run the examples. When I run the CIFAR10/01_Conv.cntk  example (on CPU) , it failed with error:

EXCEPTION occurred: NotifyFunctionValuesMBSizeModified: features InputValue operation had its col dimension 64 changed by the reader to 32, but different from MBLayout.

Can someone tell me where is the problem? 

The full log is attached to this post.

[01_Conv_Train_Test.zip](https://github.com/Microsoft/CNTK/files/187709/01_Conv_Train_Test.zip)

**Comment by Alexey-Kamenev** [comment]
Hello,
Does this happen on CPU only? Is it a consistent issue or intermittent?
Thanks and sorry for delay with response.

**Comment by LairMan** [comment]
Hello,
I don't know, what happened but now it works (without any change on my side).
It was consistent so I left this example. Now I'm trying it again and the problem has gone.

I'm very sorry. I'm closing this issue.
