### ISSUE TITLE
Makefile:1538: recipe for target '/root/cntk/build/release/.build/Source/EvalDll/CNTKEval.o' failed

### ISSUE THREAD

**Issue by sk-g** [Microsoft/CNTK#2800]
On building CNTK with .`./../configure --with-cuda=/usr/local/cuda-8.0/ --with-buildtype=release --1bitsgd=yes --asgd=yes ` followed by make all, I get the following error : 
`=-----------------------------------------------------------=
creating /root/cntk/build/release/.build/Source/EvalDll/CNTKEval.o for Linux with build type release
/usr/local/mpi/bin/mpic++ -c Source/EvalDll/CNTKEval.cpp -o /root/cntk/build/release/.build/Source/EvalDll/CNTKEval.o -DHAS_MPI=1 -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DUSE_MKL -DNDEBUG -DNO_SYNC -DCNTK_PARALLEL_TRAINING_SUPPORT -DASGD_PARALLEL_SUPPORT  -DCNTK_COMPONENT_VERSION="2.3.1" -DUSE_ZIP -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/CNTKv2LibraryDll/proto -ISource/../Examples/Extensibility/CPP -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -ISource/PerformanceProfilerDll -I/usr/local/protobuf-3.1.0/include -I/usr/local/mklml/mklml_lnx_2018.0.1.20171007/include -I/usr/local/boost-1.60.0/include -I/usr/local/include -I/usr/local/lib/libzip/include -I/root/opencv-3.1.0/include -I/root/opencv-3.1.0/include -ISource/1BitSGD -ISource/Multiverso/include -ITests/EndToEndTests/CNTKv2Library/Common -I/usr/local/boost-1.60.0/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF /root/cntk/build/release/.build/Source/EvalDll/CNTKEval.d
In file included from Source/ComputationNetworkLib/SpecialPurposeNodes.h:10:0,
                 from Source/SGDLib/DataReaderHelpers.h:9,
                 from Source/SGDLib/SimpleOutputWriter.h:10,
                 from Source/EvalDll/CNTKEval.cpp:18:
Source/ComputationNetworkLib/NonlinearityNodes.h: In member function ‘virtual void Microsoft::MSR::CNTK::TopKNode<ElemType>::BackpropTo(size_t, const Microsoft::MSR::CNTK::FrameRange&)’:
Source/ComputationNetworkLib/NonlinearityNodes.h:520:48: error: lambda capture initializers only available with -std=c++14 or -std=gnu++14 [-Werror]
             std::generate(tmp, tmp + numCols, [i = ElemType(0), dim]() mutable { auto ret = i; i += dim; return ret; });
                                                ^
cc1plus: all warnings being treated as errors
Makefile:1538: recipe for target '/root/cntk/build/release/.build/Source/EvalDll/CNTKEval.o' failed
make[1]: *** [/root/cntk/build/release/.build/Source/EvalDll/CNTKEval.o] Error 1
make[1]: Leaving directory '/root/cntk'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
`

configure output - 
```
root@sanjay-Lenovo-Z50-70:~/cntk/build/release# ../../configure --with-cuda=/usr/local/cuda-8.0/ --with-buildtype=release --1bitsgd=yes --asgd=yes 
Cannot locate a GDK include directory
GPU will be disabled
Found OpenCV at /root/opencv-3.1.0
Found libzip at /usr/local
Cannot locate Kaldi files
Kaldi2Reader will NOT be built.
Found Boost at /usr/local/boost-1.60.0
Found Protocol Buffers at /usr/local/protobuf-3.1.0
Found MPI at /usr/local/mpi
Generating /root/cntk/build/release/Config.make
Generating /root/cntk/build/release/Makefile
run
>make -j $(nproc) all
to build

```
compiler : 
```
root@sanjay-Lenovo-Z50-70:~# dpkg --list | grep compiler
ii  antlr3                                      3.5.2-4                                      all          language tool for constructing recognizers, compilers etc
ii  clang                                       1:3.8-33ubuntu3.1                            amd64        C, C++ and Objective-C compiler (LLVM based)
ii  clang-3.8                                   1:3.8-2ubuntu4                               amd64        C, C++ and Objective-C compiler (LLVM based)
ii  g++                                         4:5.3.1-1ubuntu1                             amd64        GNU C++ compiler
ii  g++-5                                       5.4.1-2ubuntu1~16.04                         amd64        GNU C++ compiler
ii  g++-5-multilib                              5.4.1-2ubuntu1~16.04                         amd64        GNU C++ compiler (multilib support)
ii  g++-multilib                                4:5.3.1-1ubuntu1                             amd64        GNU C++ compiler (multilib files)
ii  gcc                                         4:5.3.1-1ubuntu1                             amd64        GNU C compiler
ii  gcc-5                                       5.4.1-2ubuntu1~16.04                         amd64        GNU C compiler
ii  gcc-5-multilib                              5.4.1-2ubuntu1~16.04                         amd64        GNU C compiler (multilib support)
ii  gcc-multilib                                4:5.3.1-1ubuntu1                             amd64        GNU C compiler (multilib files)
ii  hardening-includes                          2.7ubuntu2                                   all          Makefile for enabling compiler flags for security hardening
ii  libantlr-java                               2.7.7+dfsg-6ubuntu1                          all          language tool for constructing recognizers, compilers etc (java library)
ii  libllvm3.6v5:amd64                          1:3.6.2-3ubuntu2                             amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm3.8:amd64                            1:3.8-2ubuntu4                               amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm4.0:amd64                            1:4.0-1ubuntu1~16.04.2                       amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm4.0:i386                             1:4.0-1ubuntu1~16.04.2                       i386         Modular compiler and toolchain technologies, runtime library
ii  libxkbcommon0:amd64                         0.5.0-1ubuntu2                               amd64        library interface to the XKB compiler - shared library
ii  llvm-3.8                                    1:3.8-2ubuntu4                               amd64        Modular compiler and toolchain technologies
ii  llvm-3.8-dev                                1:3.8-2ubuntu4                               amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-3.8-runtime                            1:3.8-2ubuntu4                               amd64        Modular compiler and toolchain technologies, IR interpreter
ii  ocaml-compiler-libs                         4.02.3-5ubuntu2                              amd64        OCaml interpreter and standard libraries

```

**Comment by Arkoprabho** [comment]
Can you provide details on how you fixed this issue.?

**Comment by sk-g** [comment]
@Arkoprabho read #2754
