### ISSUE TITLE
New installation CNTK: kernel died

### ISSUE THREAD

**Issue by Maxcasa** [Microsoft/CNTK#2801]
Hello,
in a new PC with win 10 I installed:

- Anaconda3-4.1.1-Windows-x86_64
- CNTK 2.3.1 for CPU and Python 3.5
- 
- 

the installation goes OK.

But when I try to run CNTK the kernel died, with the message:
```
C:\local\Anaconda3-4.1.1-Windows-x86_64) C:\local\CNTK-2-3\cntk\Tutorials\NumpyInterop>jupyter qtconsole
Selected CPU as the process wide default device.
-------------------------------------------------------------------
Build info:

                Built time: Dec  5 2017 18:19:12
                Last modified date: Mon Nov 13 23:00:38 2017
                Build type: Release
                Build target: CPU-only
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                Build Branch: HEAD
                Build SHA1: ce72a557b02b30a52c965a237b124688035f720f
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
[JupyterQtConsoleApp] WARNING | kernel died: 3.0020291805267334

```
e.g in the Tutorial FeedForwardNet.py it died at the line 60 "trainer = Trainer(netout, (ce, pe), learner, progress_printer)"

I tried also with the GPU installation and with python 3.6 and nothing changes.

I  run out of ideas.

Thanks,
Massimo

**Comment by ebarsoumMS** [comment]
Can you try import CNTK from python prompt?

**Comment by MMRohe** [comment]
I have exactly the same issue. Did you find a fix to this problem ?

**Comment by Maxcasa** [comment]
Till now, the only solution I found is to install CNTK 2.2
I try both python and jupyter qtconsole.

**Comment by MMRohe** [comment]
Thanks for your answer. I got back to CNTK 2.2 and it indeed "solved" the problem.

So it seems to be a CNTK 2.3 problem. Will stay on 2.2 hoping it will get fixed sometime

**Comment by manikjindal** [comment]
@Maxcasa,@MMRohe Could you please share version information for python, ipython, jupyter and qtconsole in your environment.

**Comment by MMRohe** [comment]
conda 4.3.14
python 3.6.0
anaconda 4.3.1
ipython 5.1.0
QtConsole 4.2.1
jupyer 4.2.1

CNTK 2.2 is working fine but not CNTK 2.3

Thanks for your help

**Comment by manikjindal** [comment]
I am not able to repro the same issue with the posted versions. Could you please try upgrading to CNTK 2.4? Please re-open the issue if you face the same problem.

**Comment by Rov67777** [comment]
CNTK 2.4 is working correctly so you can indeed close the issue
