### ISSUE TITLE
ResNet110_CIFAR10_CNTK: transfer learning - what is the layer name?

### ISSUE THREAD

**Issue by aWeinzierl** [Microsoft/CNTK#2813]
I want to do transfer learning on ResNet110_CIFAR10_CNTK and/or ResNet20_CIFAR10_CNTK.

Unluckily I cannot find the name of the function before the dense layer.

I tried to get the layer using multiple names I retrieved from plotting (for instance, the highlighted one):
![image](https://user-images.githubusercontent.com/20560137/34492993-249c4afe-efea-11e7-9e35-d27ad2917c1a.png)

I tried the name "final_avg_pooling" from the training script:
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/resnet_models.py

And I tried 

    var s4 = _model.FindAllWithName("");

None of these attempts delivered anything useful. I even tried printing the names in python: 

    blocks = c.logging.get_node_outputs( model )
    for l in blocks: print( "  {0} {1}".format( l.name, l.shape ) )
    print("----------------------------------")
    blocks = c.logging.graph.depth_first_search( model, ( lambda x : True ) , depth = 10 )
    for l in blocks: print( "  {0} {1}".format( l.name, l.shape ) )

Claiming that the output was any sorts of useful would a huge exaggeration. Most of the time, I get no name at all and when I get some, they only seem to be variables, which somehow contradicts to the fact that I got only one function when executing the above c# statement.

What is the name I am looking for?

Thank you very much in advance. That really would help me a lot.

**Comment by ebarsoumMS** [comment]
Please check find by name in FastRCNN: https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/FastRCNN/FastRCNN_train.py

**Comment by spandantiwari** [comment]
It is possible that the layer does not have a name. There's a new logging CNTK Python API in CNTK 2.5, that was released last week, called `find_by_uid()`. Could you try using that API with the string "Block122833" and see if that gives you the node you want. As a side note, you might have to use `as_composite()` API to wrap the node before evaluating the abridged model.
