### ISSUE TITLE
Issues in MNIST_Complex_Training.py

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#2815]
Hi,
There are two issues with the MNIST_Complex_Training.py sample.
First, an undefined reference.  Should this be learning_parameter_**schedule**_per_sample?
`[2]  File "MNIST_Complex_Training.py", line 117, in adjust_lr_callback`
`[2]    learner.reset_learning_rate(C.learning_parameter_per_sample(learner.learning_rate() / 2))`
`[2]AttributeError: module 'cntk' has no attribute 'learning_parameter_per_sample'`

Second is just a usability issue where failing to run the script behind mpiexec causes Python (3.6 on Windows) to silently crash here:
`learner = C.train.distributed.data_parallel_distributed_learner(learner)`
while there is a comment immediately preceeding this line, the user may not discover it since there is no stack trace.  I'm not sure whether there is a good way to detect if mpi is running and provide some useful message. Otherwise, I would move the comment about mpi to the boilerplate at the top of the file, along with a warning about the potential for python to crash.

**Comment by mx-iao** [comment]
Updated the deprecated API, thanks!
