### ISSUE TITLE
cntk.Times does not works as expected with multi-dimensional tensors.

### ISSUE THREAD

**Issue by rnrneverdies** [Microsoft/CNTK#2817]
The following operations do not work as I expected. 

```
a = np.random.rand(3,10, 8)
b = np.random.rand(3, 8, 1)
c = cntk.times(a, b)
c.eval().shape    # Expected (3, 10, 1)
```
but this code throws: 

_Times: The 2 leading dimensions of the right operand with shape '[3 x 8]' do not match the left operand's trailing dimensions with shape '[3 x 10 x 8]'_

I expected a [3 x 10 x 1] results with the dot product of the two latest dimensions row by row (note that the real tensor has rank 5, this is just a sample) 

In numpy I can do this by calling

```
np.matmul(a,b).shape    # results in (3, 10, 1)
```

EDIT: This also possible in tensorflow by using `tf.matmul(a, b)`.

How can I achieve this? 
Thanks!

**Comment by rnrneverdies** [comment]
I've found this way to do the matrix multiplication. but it works on CPU only, which is not what I need. 

Is there any other CNTK way to get the same results?

Thoughts? 

```
import numpy as np
import cntk as ct
from cntk.ops.functions import UserFunction

class matmul(UserFunction):
    """
    Custom Matrix Multiplication

    CPU Only.
    Does not work till all dimensions are well known.
    """
    def __init__ (self, left, right, name='user_matmul'):
        super(matmul, self).__init__([left, right], name=name)

    def forward(self, args, device=None, outputs_to_retain=None):
        z = np.matmul(args[0], args[1])
        return args[1], z

    def backward(self, state, root_gradients, other):
        root_gradients = np.swapaxes(root_gradients, -1, -2)
        return np.matmul(state, root_gradients)

    def infer_outputs(self):
        shape = self.inputs[0].shape[:-1] + (self.inputs[1].shape[-1],)
        return [ct.output_variable(shape, np.float32, self.inputs[1].dynamic_axes, name=self.name + '_output_shape')]

def user_matmul(left, right, name=''):
    return ct.as_composite(matmul(left, right), name=name)
```

**Comment by KeDengMS** [comment]
Can you try create a input_variable as below:

    c = C.times(C.input_variable((10,8,)), C.input_variable((8,1)))
    c.eval({c.arguments[0]:b, c.arguments[1]:a})

**Comment by rnrneverdies** [comment]
@KeDengMS thanks for the response.

It will work if the 3 is the dynamic axis. But my matrix's rank is 4, plus the dynamic axis, so it will not work in my case. 

example: (plus dynamic axis)

```
a = C.Parameter(shape=(128, 12, 16, 8))
b = C.input_variable(shape=(128, 12, 8, 1))
c = C.times(a, b)
```

It should return a tensor of `shape=(128, 12, 16, 1)`

This case is throwing the error 

```
ValueError: Times: The 3 leading dimensions of the right operand with shape '[128 x 12 x 8]' do not match the left operand's trailing dimensions with shape '[128 x 12 x 16 x 8]'
```

I've also tried to do this using multiple dynamic axes but I couldn't yet :/

**Comment by KeDengMS** [comment]
The syntax of cntk [times](https://www.cntk.ai/pythondocs/cntk.ops.html#cntk.ops.times) is different from numpy.matmul, and for your case above it would take some manipulations on dynamic axis. The complexity mainly comes from broadcasting along b's batch axis while not to duplication on dimension (128,12). The basic idea is to convert b's batch axis (assuming len is B) in to sequence axis, and then use broadcast_as to broadcast a to that axis:

    # converts a to [128*12], (16,8) with batch axis len of 128*12
    aa = C.to_batch(C.reshape(a, (-1,16,8)))

    # flatten and transpose b to (128*12,B,8,1)
    bbt = C.transpose(C.unpack_batch(C.reshape(b, (-1,8,1))), (1,0,2,3))

    # create batch axis of 128*12, and sequence axis of B
    bbs = C.to_sequence(C.to_batch(bbt))

    # now we have c with batch axis of 128*12, sequence axis of B, and shape of (16x1)
    # note aa would be automatically broadcasted along bbs's sequence axis
    cc = C.times(aa, bbs)

    # swap batch axis and sequence axis of cc, and get the shape back as [B], (128,12,16,1)
    c = C.reshape(C.to_batch(C.transpose(C.unpack_batch(C.sequence.unpack(cc, 0)[0]), (1,0,2,3))), (128,12,16,1))

This is quite clumsy and not performant, but should work better than the numpy user function. Ideally we should have matmul op that broadcast automatically like numpy do.

**Comment by rnrneverdies** [comment]
@KeDengMS Thanks a lot! It worked as np.matmul does. Really helpful! 

closing the issue for now... however, It would be great to have this feature built-in.

**Comment by rnrneverdies** [comment]
@KeDengMS Unfortunately, its performance is worst on a GPU than using the numpy implementation (I'm using a K-80 GPU from Azure DL VM) ~4 times slower on GPU than CPU.

Anyway, thanks a lot.

**Comment by KeDengMS** [comment]
The slowness might come from unrolled batch axis (128x12 here) in matmul in current version. With the ongoing 2.4 release we'll have batchMatMul for that and please try again then to see if there's improvement.

**Comment by rnrneverdies** [comment]
@KeDengMS Thanks for the heads up! I will stay tuned!

**Comment by rnrneverdies** [comment]
Hi @KeDengMS 

I'd like to comment out that this issue is related to our implementation of the Hinton's paper Dynamic Routing between capsules (aka. Capsule Networks) you can find here: https://github.com/southworkscom/CapsNet-CNTK

This particular kind of matrix multiplication is needed in 2 different places: 
https://github.com/southworkscom/CapsNet-CNTK/blob/master/CapsLayer.py#L70
and 
https://github.com/southworkscom/CapsNet-CNTK/blob/master/CapsLayer.py#L107

Could you please take a quick look at this an let me know if batchMatmul would be the right solution for us or not? I'm also interested to know if batchMatmul would broadcast 1-N axes such as numpy does (see [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)) or if we would need to _splice_ those axes after applying the op. 

Thanks!!

**Comment by KeDengMS** [comment]
Thanks for implementing CapsNet for CNTK. I looked at your implementation and it seems easier to use element_times then reduce_sum, instead of matmul. Note that CNTK allows auto broadcasting in tensors, so (1152, 1, 1, 8) * (1152, 10, 16, 8) -> (1152,10, 16, 8), then you can reduce_sum(axis=3) to get (1152,10,16,1). I tried change your script and was able to train at 1110 images/second (previously 79 images/s)

```
input = ct.reshape(input, (1152, 1, 1, 8), name='reshape_input')
u_hat = ct.reduce_sum(W * input, axis=3)

Vj_Transpose = ct.transpose(ct.reshape(Vj, (1, 10, 16, 1)), (0, 1, 3, 2), name='Vj_Transpose')
UV = ct.reduce_sum(ct.reshape(u_hat_stopped, (1152,10,1,16)) * Vj_Transpose, axis=3)
```

**Comment by delzac** [comment]
> 
> 
> The slowness might come from unrolled batch axis (128x12 here) in matmul in current version. With the ongoing 2.4 release we'll have batchMatMul for that and please try again then to see if there's improvement.

@KeDengMS any updates on whether batchMatMul will be coming? I need it for implementing an efficient Transformer (used in BERT and "attention is all you need").

**Comment by KeDengMS** [comment]
@delzac [BatchMatmul](https://github.com/Microsoft/CNTK/commit/15e705da8dea454070c34d88bb8a7e88750dde02) has been added a year ago. Please give it a try.

**Comment by delzac** [comment]
Hi @KeDengMS, thanks for the reply!

I have look through [BatchMatmul](https://github.com/Microsoft/CNTK/commit/15e705da8dea454070c34d88bb8a7e88750dde02) closely. It don't seem to be either what i'm looking for (based on the included test cases) or exposed to the python API?

I hope to get the following:
```
a = C.sequence.input_variable((4, 5, 2))
b = C.sequence.input_variable((4, 2, 3))

c = C.BatchMatMul(a, b)
assert c.shape == (4, 5, 3)
```
If the above code possible at the moment? Cause i'm using C.slice to achieve the effect right now.

I would be happy to submit a PR if its just a case of exposing it in the python api :)

**Comment by KeDengMS** [comment]
No it does not do general BatchMatMul. Instead it only takes batch from dynamic axes (batch/sequence). so C.Times(C.sequence.input_variable(5,2), C.sequence.input_variable(2,3)) would give you output of [#,*](5,3), and it uses batch matmul for acceleration. In the case above you may fold the first dimension 4 into sequence axis with some sequence unpack/reshape/pack hack...

**Comment by delzac** [comment]
Got it! Thanks for the help! :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
