### ISSUE TITLE
Composite MinibatchSource does not work as expected.

### ISSUE THREAD

**Issue by kkc0923** [Microsoft/CNTK#2821]
I tested image to 3 tag network (using cntk sample of resnet152 + sigmoid for final output).

My image_map.txt for ImageDeserializer is like below:
E:\Dataset\image1.jpg	0
E:\Dataset\image2.jpg	0
E:\Dataset\image3.png	0

Then here is my labels_ctf.txt for CTFDeserializer:
|labels 0:1 1:1
|labels 0:1 2:1
|labels 1:1 2:1

Here is my MinibatchSource creation method.
```python
    transforms = [
        C.io.transforms.scale(image_width, image_height, 3, scale_mode='pad')]
    image_source = C.io.ImageDeserializer(image_map_path, C.io.StreamDefs(
        features=C.io.StreamDef(field='image', transforms=transforms)
    ))

    label_source = C.io.CTFDeserializer(labels_ctf_path, C.io.StreamDefs(
        labels=C.io.StreamDef(field='labels', shape=output_shape, is_sparse=True)))

    return C.io.MinibatchSource([label_source, image_source])
```

When I trained this dataset until the loss almost be zero, the evaluated results are not matches.
image1 -> (0, 1, 1)
image2 -> (1, 0, 1)
image3 -> (0, 1, 1)

But when I using my own UserMinibatchSource, the result is matches correctly. Also, if I trained by using each single image (not all 3 images at the same time) via composite minibatchsource, the result is also correctly. Is my setting wrong? or composite minibatchsource has bug? (it looks like the sequence(sample) order does not matching between deserializers)

Thanks.

(my environment : python 3.6.x + cntk 2.3.1 gpu ver.)

**Comment by n17s** [comment]
When you create the MinibatchSource you can specify whether it should randomize the order of the data or not. By default randomize=True, because training works better when the data is randomized. If you want to retrieve the samples in the same order as in your file then pass randomize=False.
