### ISSUE TITLE
the model file has a newer format version than this cntk

### ISSUE THREAD

**Issue by Brandonnogithub** [Microsoft/CNTK#2831]
sorry, i forgot the version is.  I 'm  using cntk2.0beta5 on linux. the bin file is from others.  I can load it by Function::Load  in cntk2.1.  the  fintion in 2.0beta5 is Function::LoadModel, which is different. So I get this error.   Is there any way for me to load it in cntk2.0beta5 or convert this fike to the oldder formay?

**Comment by Brandonnogithub** [comment]
oldder format  sorry

**Comment by Brandonnogithub** [comment]
Read: The model file has a newer format version (27) than this CNTK version can handle (15).

**Comment by ebarsoumMS** [comment]
Why can you use 2.1? Is there a reason that you need to use beta 5? 2.1 can't save a model to older version.

**Comment by Brandonnogithub** [comment]
Because the I use cuda 7.5  but all your release over beta5 is compiled by cuda 8

**Comment by Brandonnogithub** [comment]
I have two computer, one use cuda 7.5 and installed cntk 2.0 beta5
another one use cuda 8 and installed cntk 2.1

**Comment by ebarsoumMS** [comment]
You can install cuda 8 and 7.5 in the same machine, CNTK beta 5 is pretty old.

**Comment by Brandonnogithub** [comment]
the computer with cuda 7.5 is a server. I don't have the permission to install cuda 8.

**Comment by Brandonnogithub** [comment]
Now I needn't to run my program on the server. So this is not a problem for me any more. 
Thanks for your answering.
