### ISSUE TITLE
ModuleNotFoundError: No module named 'cntk._cntk_py' (even after providing Path to CNTK executable in  System variable)

### ISSUE THREAD

**Issue by dhinar1991** [Microsoft/CNTK#2835]
Hi,

I installed CNTK  CPU only for Python 3.6 from this URL ( https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3.1-cp36-cp36m-win_amd64.whl) on Windows7.

When i import it throws error,

> 
> >>> import cntk
> Traceback (most recent call last):
>   File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'cntk._cntk_py'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<pyshell#1>", line 1, in <module>
>     import cntk
>   File "C:\Program Files\Python36\lib\site-packages\cntk\__init__.py", line 10, in <module>
>     from . import cntk_py
>   File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 21, in <module>
>     _cntk_py = swig_import_helper()
>   File "C:\Program Files\Python36\lib\site-packages\cntk\cntk_py.py", line 20, in swig_import_helper
>     return importlib.import_module('_cntk_py')
>   File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: DLL load failed: The specified module could not be found.

I came across these posts  [https://github.com/Microsoft/CNTK/issues/1887](url) and [https://github.com/Microsoft/CNTK/issues/1549](url) and the only clear solution provided was to give Path to the System variable. So i gave,

Path : C:\Program Files\Python\Python36\Lib\site-packages  (this is where CNTK is present)
PYTHONPATH :  C:\Program Files\Python\Python36\Lib\site-packages\cntk\  ( i added a new variable called 'PYTHONPATH' 

This is not helping me. It throws the same error when i try to import. 

This is my Python version
> print (sys.version)
> 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

These are list of .dll files present in my directory of Python.exe

C:\Program Files\Python36>dir/b *.dll
Cntk.BinaryConvolutionExample-2.3.1.dll
Cntk.Composite-2.3.1.dll
Cntk.Core-2.3.1.dll
Cntk.Deserializers.Binary-2.3.1.dll
Cntk.Deserializers.HTK-2.3.1.dll
Cntk.Deserializers.Image-2.3.1.dll
Cntk.Deserializers.TextFormat-2.3.1.dll
Cntk.ExtensibilityExamples-2.3.1.dll
Cntk.ImageWriter-2.3.1.dll
Cntk.Math-2.3.1.dll
Cntk.PerformanceProfiler-2.3.1.dll
libiomp5md.dll
mklml.dll
opencv_world310.dll
python3.dll
python36.dll
vcruntime140.dll
zip.dll
zlib.dll

And it is crashing my Python IDLE. Any other solution for this issue please?

**Comment by jsPlachetka** [comment]
This sounds a lot like the problems I had about two months ago, when I started.

What helped was to set the interpreter to "cntk-py35" (or whatever fits your cntk version).  (I use Eclipse to develop, so it can be set in the project properties).
If you have to add/install other libraries you have to change the active environment from anaconda to cntk-py35 and install then.

Hope that helped.

**Comment by dhinar1991** [comment]
I solved it by reinstalling "Microsoft Visual C++ Redistributable for Visual Studio 2017" from [https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-your-machine](url)
