### ISSUE TITLE
Use sparse data in eval()

### ISSUE THREAD

**Issue by jsPlachetka** [Microsoft/CNTK#2836]
Hi,

I've trained a FFN with sparse data. At the moment every attribute of an instance is one-hot-encoded.
My train() and test() function worked with it, but now I want to check my results with eval() and it crashes.

In earlier versions I used dense data (only numbers), so I could used a numpy array. But ([https://www.cntk.ai/pythondocs/cntk.io.html?highlight=minibatchdata#cntk.io.MinibatchData])) says it "should be either NumPy arrays or a class:"cntk.io.MinibatchData"". So I tried to use this, by creating a reader on my one-hot-encoded, ctf file. The reader is equal to the one I used for the test input. But again, it failed.

`v_reader = ml_utils.create_reader(validate_file, False, input_dim, num_output_classes, True)`

`def create_reader(path, is_training, input_dim, num_label_classes, sparse = False):
        return C.io.MinibatchSource(C.io.CTFDeserializer(path, C.io.StreamDefs(
            #TODO: ggf. muss sparse für labels und features unabhängig gesetzt werden
            labels=C.io.StreamDef(field='labels', shape=num_label_classes, is_sparse=False),
            features=C.io.StreamDef(field='features', shape=input_dim, is_sparse=sparse)
        )), randomize=is_training, max_sweeps=C.io.INFINITELY_REPEAT if is_training else 1)
    #this is similar to one of the tutorials`

`prediction = get_new prediction(v_reader.next_minibatch(1))`

`def get_new_prediction(self, data_instance):
        predictions = self.__model.eval({self.__model.arguments[0]:[data_instance]})
        return predictions[0]`
//no it's not the order of the code but copied from several classes

The Error message says:
`AttributeError: 'dict' object has no attribute 'dtype'`
and comes from 
`...\cntk-py35\lib\site-packages\cntk\core.py", line 346, in _as_best_data_type
    elif sample.dtype in (np.float32, np.float64):`
when the program class eval()

Does anyone know why I get this error and how to solve it?
Or maybe a better/easier way to use eval with sparse data?

Many thanks in advance.

PS: The later data model will probably consist of both, sparse, one-hot-encoded and dense, numeric data. Any advices to do this?

**Comment by jsPlachetka** [comment]
As I'm now working with the real data (it really contains dense and sparse data) I came back to the problem I had with sparse data and eval() before.
The data contains some free text attributes. My program finds the important keywords and creates a CTF entry for sparse data, so it looks like this:
`|ASPARSE 0:01 1:10 ... i:01`
with i = number of keywords
Training and Testing works fine (also controlled if abssum is calculated). Then I wanted to get a new prediction. As mentioned in the [my issue regarding mixed data](https://github.com/Microsoft/CNTK/issues/2868) I managed to combine dense and sparse data in eval - when there is only one entry for the sparse attributes!

So far I've tried to nest the csr_matrices for each keyword in either a csr_matrix or a numpy array. At the moment I add the csr_matrices rowwise via sparse.vstack, but that leads to 
``
for the attribute has only the shape [28] when training (as said that's not the problem).

My first idea was to symple put all csr_matrices in a list (right shape!), but that failed, too. The error says that input has to be either numpy array or csr matrix. 
So I looked at  the eval() doc for further ideas and found this:

> dict: keys are input variable or names, and values are the input data. See forward() for details on passing input data.

The[ documentation for forward()](https://cntk.ai/pythondocs/cntk.ops.functions.html?highlight=eval#cntk.ops.functions.Function.forward) contains an example where the value of the dictionary is a list of csr_matrix objects (third example).
That's quite confusing for me. Did I miss something important? Or is there another way to solve me problem?

**Comment by KeDengMS** [comment]
You should be able to feed the data via a Python list of csr_matrix. Inside the python binding, csr_matrix is converted to csc and passed to C++. If that's not the case, please share your model and script for a repro.

**Comment by jsPlachetka** [comment]
Thanks for the fast reply!
First it seemed to work with the Python list of csr_matrix. I rewrote my code, removed all unneccessary and then it worked.
`def __prepare_data_for_prediction(self, data_instance, mixed_data_structure, categories, num_variants):
       # create data_list_prep out of a ctf row
        data_list_0 = []
        for i in range(len(categories) - 1):
            field_value = data_list_prep[i][data_list_prep[i].find(" "): ]
            if categories[i] == "A1" or categories[i] == "A2":  # Test für multidim
                field_element = []
                fl = field_value.split(" ")
                for field in fl:
                    if field != "":
                        field = field[(field.find(":") + 1):]
                        field = field.replace(" ", "")
                        field = list(field)
                        field_list = [np.float32(j) for j in field]
                        field_e = sparse.csr_matrix((field_list), shape=(1,2))
                        field_element.append(field_e)

            elif mixed_data_structure[categories[i]]:
                field_value = field_value[(field_value.find(":") + 1):]
                field_value = field_value.replace(" ", "")
                field_value = list(field_value)
                field_list = [np.float32(j) for j in field_value]
                field_element = sparse.csr_matrix((field_list), shape=(1, num_variants[categories[i]]))  # .toarray()
            else:
                field_element = np.array([np.float32(field_value)])
            data_list_0.append(field_element)

        return data_list_0`

The prepare function will be changed of course when I start to use real data, but at the moment I preprocess all my data und split them afterwards into train, test and validate.
The list becomes the argument for
`    def get_new_prediction(self, data_instance):
        input_dict = {}
        for i in range(len(data_instance)):
            input_dict[self.__calculated_model.arguments[i]] = data_instance[i]

        predictions = self.__calculated_model.eval(input_dict)
        return predictions[0]`
At the moment I get the following error message:
`  ...\cntk\ops\functions.py", line 631, in eval
    _, output_map = self.forward(arguments, outputs, device=device, as_numpy=as_numpy)
  ...\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
 ...\cntk\ops\functions.py", line 755, in forward
    None, device)
 ...\cntk\internal\sanitize.py", line 431, in sanitize_var_map
    batch = sanitize_batch(var, batch, seq_starts, device)
 ...\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
...\cntk\internal\sanitize.py", line 200, in sanitize_batch
    return Value.create(var, batch, seq_starts, device)
 ...\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
 ...\cntk\core.py", line 466, in create
    True)  # always create a copy in Value
ValueError: Value::Create: The shape '[1 x 2]' of sequence #0 is not compatible with the sample shape '[28]'.`
when evoking eval() 

The input part of the model for the "special" sparse data is at the moment created as the ones for the normal sparse data:
`return C.layers.Embedding(shape)(input_layer)` with shape in number of keywords and input_layer a C.input_variable of the same shape. I've tried several other variants yesterday (as a input_variable per keyword - but none made really sense or workd).

**Comment by jsPlachetka** [comment]
A short update: I've just tried to solve the problem with a minmal example (same data, same model havin only one input with dim 28, so it looks like an all sparse model). For a new prediction it gets the s´data same way as before - a list of 28 sparse csr_matrix objects. This still evokes the error.

**Comment by nmfisher** [comment]
Slightly different problem, but it still relates to sparse tensors so I figure it's close enough to put here.

I've been playing around with this all day, and as far as I can tell, it's impossible to convert a sparse minibatch/tensor back to a sparse scipy matrix.

Simple demo here:
https://github.com/nmfisher/CNTK_sparse_demo/blob/master/Python/Sequence2SequenceOOM.py

There's no problem training or performing inference (e.g. using the original Sequence2Sequence scripts @ https://github.com/Microsoft/CNTK/tree/master/Examples/SequenceToSequence/CMUDict/Python with an enlarged vocabulary).

However, if you want to decode the minibatch (e.g. to compare the text input against the decoded output in the S2S model @ 
https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/Python/Sequence2Sequence.py#L258), it will fail with OOM.

It seems that any attempt to resolve a sparse tensor will go via [_sparse_to_dense_network_cache in sanitize.py] (https://github.com/Microsoft/CNTK/blob/3cf3af5df6d0071f282b6696bcafca9f4838dabd/bindings/python/cntk/internal/sanitize.py#L657), which will try and convert everything via np.eye (failing for obvious reasons).

I've been through all the text-based examples, and it seems they all deal with vocab sizes ~10000, which is small enough that the memory restrictions would never be encountered.

Have I missed something, or is it actually impossible to resolve a sparse tensor/minibatch to a sparse matrix?
 
Happy to be corrected if I've misunderstood something.

**Comment by KeDengMS** [comment]
Yes this is a limitation in converting from sparse Value to numpy. If possible, I'd recommend using [one_hot](https://www.cntk.ai/pythondocs/cntk.ops.html#cntk.ops.one_hot) op in the network, and feed sparse input using dense indices in MinibatchData:
```
import cntk as C
import numpy as np
input_dim =1000000
embed_dim = 100
x = C.sequence.input(())
y = C.layers.Dense(embed_dim)(C.one_hot(x, num_classes=input_dim, sparse_output=True))
y.eval(np.random.rand(5, 20) * (input_dim - 1)) # test batch_size = 5(seq), and each sequence with 20 samples
```

**Comment by nmfisher** [comment]
Thanks for the response. In your example, though, how would I resolve the output of the dense layer back to the original one-hot index? 

More specifically, if x is a sequence of word vocab indices, how would I use the output of y.eval(...) to find out what each word in the sequence was?

**Comment by jsPlachetka** [comment]
@KeDengMS  Could it be that you've forgotten to answer my question?

**Comment by KeDengMS** [comment]
@nmfisher you can do (x+0).eval(mb_data) to get the input one hot index data from minibatch.
@jsPlachetka your model seems to splice sparse input then embed. Can you embed the sparse input first, then splice the dense vector after embed?

**Comment by jsPlachetka** [comment]
Actually it's the other way around. With evoking create_help_layer I embed the sparse variables first and the splice the embeds with the dense variables. I also do this for the sparse fields with more than one entry (|field 0:01 1:01....). For I can't interate over them or adress them otherwise I have no clue how to try your suggestion.

**Comment by KeDengMS** [comment]
@jsPlachetka it would be easier to have a binary model and a few lines of eval code as I shown above. Note that each sparse matrix contains the data for one feature in one batch. For one input variable with dim 28, and batch size of 5, the csr matrix shape should be 5 x 28.

**Comment by jsPlachetka** [comment]
Unfortunatelly I can't load the model file as ".dnn" - so I hope this will work
I've build a minimal example of the eval part of my program which evokes the same error:
`z = C.load_model("model.dnn")

    data_instance = [np.array([np.float32(87)]), sparse.csr_matrix([1,0,0], shape=(1,3)), np.array([np.float32(1016)]), np.array([np.float32(2)]),
                     sparse.csr_matrix([0,1,0,0,0,0,0,0], shape=(1,8)), sparse.csr_matrix([0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], shape=(1,30)),
                     np.array([np.float32(1127)]), np.array([np.float32(0)]), np.array([np.float32(0)]), sparse.csr_matrix([0,1], shape=(1,2)),  sparse.csr_matrix([0,0,1,0,0,0,0,0,0], shape=(1,9)),
                     [sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                      sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                      sparse.csr_matrix([1,0], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                      sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                      sparse.csr_matrix([1,0], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                      sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                      sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),],
                      np.array([np.float32(0)]),
                    [sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)),
                     sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)),
                     sparse.csr_matrix([0,1], shape=(1,2)), sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                     sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([1,0], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),
                     sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2)),sparse.csr_matrix([0,1], shape=(1,2))],
                     np.array([np.float32(1)]),  sparse.csr_matrix([1,0,0,0], shape=(1,4)),np.array([np.float32(37)]),sparse.csr_matrix([0,0,0,0,1], shape=(1,5)),
                      np.array([np.float32(0)]), np.array([np.float32(0)]),
                     sparse.csr_matrix([0,0,0,0,1], shape=(1,5)),sparse.csr_matrix([0,0,1], shape=(1,3)),sparse.csr_matrix([1,0], shape=(1,2)) ]
        
    input_dict = {}
    for i in range(len(data_instance)):
        input_dict[z.arguments[i]] = data_instance[i]

    predictions = z.eval(input_dict)
    print(predictions[0])`
The data is usually loaded from a file and preprocessed in a function.
[model.txt](https://github.com/Microsoft/CNTK/files/1788333/model.txt)

**Comment by nmfisher** [comment]
Fantastic, the (x+0) trick worked! I had tried the identity mapping but that threw the OOM too.

Thanks @KeDengMS

**Comment by KeDengMS** [comment]
@jsPlachetka as I explained earlier, for one input variable with dim 28, and batch size of 5, the csr matrix shape should be one matrix of 5 x 28, not 28 1x5 sparse matrices. Please refer [scipy.sparse.csr_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) to construct a proper shaped matrix.
