### ISSUE TITLE
Using Convolution3D

### ISSUE THREAD

**Issue by neilyim** [Microsoft/CNTK#2838]
**This is not a software bug but more of my question using Convolution3D function
I currently have 3D tensor and would like to try using 3D convolution filter.
The tensor size is 100 by 100 by 100 and filter size is 5 by 5 by 5.
Below is my code:**

from __future__ import print_function 
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import time

import cntk as C
import cntk.tests.test_utils
cntk.tests.test_utils.set_device_from_pytest_env() # (only needed for our build system)
C.cntk_py.set_fixed_random_seed(1) # fix a random seed for CNTK components

input_dim_model = (100, 100, 100)
input_dim = 100 * 100 * 100
num_output_classes = 39

x = C.input_variable(input_dim_model)
y = C.input_variable(num_output_classes)

def create_model(features):
    with C.layers.default_options(init=C.glorot_uniform(), activation=C.relu, pad=False):
            h = features
            h = C.layers.Convolution((5, 5, 5), num_filters=32, pad=True, strides=2, name='first_conv')(h)
            return h

z = create_model(x)

**Then I run this on iPython and got below error:**

Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-6dbc1423aef5>", line 1, in <module>
    h = C.layers.Convolution((5, 5, 5), num_filters=32, pad=(True, True, True),name='first_conv')(x)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 407, in __call__
    return self.clone(CloneMethod.share, arg_map)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 618, in clone
    return super(Function, self).clone(method, substitutions)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 1921, in clone
    return _cntk_py.Function_clone(self, *args)
ValueError: Convolution padding tensor must have rank 1 or the same as the input tensor.
[CALL STACK]
    > Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - CNTK::NDMask::  MaskedCount (x2)
    - CNTK::  Unpooling (x3)
    - CNTK::Function::  ReplacePlaceholders
    - CNTK::  Hardmax
    - CNTK::Function::  ~Function
    - CNTK::Evaluator::  TestMinibatch
    - RtlRunOnceExecuteOnce
    - InitOnceExecuteOnce
    - _crtInitOnceExecuteOnce
    - CNTK::Evaluator::  TestMinibatch
    - CNTK::Function::  RawOutputs
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD

**Please advice
Thanks**

**Comment by arniwesth** [comment]
You can specify reduction_rank=0 in the convolution operator:

h = C.layers.Convolution((5, 5, 5), num_filters=32, pad=True, strides=2, name='first_conv', reduction_rank=0)(h)

Alternatively you can add a depth dimension by reformatting your inputs as (1, 5, 5, 5).

See eg. this answer: [](https://github.com/Microsoft/CNTK/issues/1785#issuecomment-304893864)
or take a look at the API doc for Convolution:[]( https://cntk.ai/pythondocs/cntk.ops.html?highlight=convolution#cntk.ops.convolution) for clarification.

**Comment by neilyim** [comment]
Thanks @arniwesth I guess I need to educate myself better on understanding those functions and their properties.
