### ISSUE TITLE
Multidimensional sequential data for classification 

### ISSUE THREAD

**Issue by ChangXu-O-O** [Microsoft/CNTK#286]
I would like to use LSTM to classify videos in two classes. Every video has a label. Multidimensional float features (fixed dimension) are extracted from every frame of the videos, which are expected to be fed into LSTM. But the problem is that the number of frames of different videos is not the same. This problem is similar to </s> in text. I have no idea how to read the video data with the existing data readers. Could you please help me with that? Thanks.

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
