### ISSUE TITLE
Using sparse and dense data at the same time like in "BrainScript CNTK Text Format Reader -- Simple Example"

### ISSUE THREAD

**Issue by jsPlachetka** [Microsoft/CNTK#2868]
Hi, 

I'm working on a project where an instance consists of both, dense and sparse data, for some attributes are numeric and some are categorial.

My first try was to convert them completely to sparse data, but that caused several Errors while training my model, because the dimension of each field was different and I didn't find a way to tell the Placeholder each individual dimension.

For converting my data I used the information given on [BrainScript CNTK Text Format Reader](https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-cntktextformat-reader). In the "Simple Example" section the input map consists of more than two fields (in Python one ususally only has "label" and "feature") and the dimensions are given explicitly. 
I started to adapt this to Python myself, but according to the Errors I get I'm doing it either completely wrong or I'm missing some important aspects.

My adaption so far:

Every attribute has his own Sample in CTF
|label 0 0 1 0 0 |AGE ... |ATTRIBUTE2 ... |A3 ...
instead of
|label 0 0 1 0 0 |feature ...

`def create_mixed_reader(path, is_training, input_dim, num_label_classes, num_variants, mixed_data_structure):
    
    stream_list = []
    for key in num_variants.keys():
        sub_stream = C.io.StreamDef(field = key, shape = num_variants[key], is_sparse = mixed_data_structure[key])
        stream_list.append(sub_stream)
    
    
    streams = C.io-StreamDefs(
        labels = C.io.StreamDef(field = 'labels', shape= num_label_classes, is_sparse=False),
        age = C.io.StreamDef(field = "AGE", shape= num_variants["AGE"], is_sparse=mixed_data_structure["AGE"]),
        a2 = C.io.StreamDef(field = 'A2', shape = num_variants['A2'], is_sparse=mixed_data_structure['A2']) 
        )
    deserializer = C.io.CTFDeserializer(path, streams)
    
    return C.io.MinibatchSource(deserializer, randomize = is_training, max_sweeps=C.io.INFINITELY_REPEAT if is_training else 1)`

The stream_list was a first attempt, so the streams could change according to the given basic data, but that didn't work because of compatibilty errors. num_variants is a dict with attribute name and its number of variants in the basic data, whereas mixed_data_structure contains information about sparse or not.

and input_map in train
` input_map = {
            label : train_reader.streams.labels,
            feature : {train_reader.streams.age, train_reader.streams.a2}  
        }`

This evokes several Errors in 
` data = train_reader.next_minibatch(self.__minibatch_size, input_map=input_map)`
like:
// my model in module mixed1
`  File "mixed1.py", line 91, in train
    data = train_reader.next_minibatch(self.__minibatch_size, input_map=input_map)
  File "...\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "...\envs\cntk-py35\lib\site-packages\cntk\io\__init__.py", line 340, in next_minibatch
    self._last_mb_data = {key: mb[value] for (key, value) in input_map.items()}
  File "...\envs\cntk-py35\lib\site-packages\cntk\io\__init__.py", line 340, in <dictcomp>
    self._last_mb_data = {key: mb[value] for (key, value) in input_map.items()}
TypeError: unhashable type: 'set'`

Am I missing something important?
Is my attempt completely wrong?
Or is there even an easier way to do something similar like in the BrainScript example, e.g. a way to combine the config file with my Python code (haven't found an example for that so far).

Many thanks for you help in advance.

**Comment by jsPlachetka** [comment]
I just saw that I've forgotten to create learner und trainer - but that doesn't affect to first error. So the first error that gets evoked is
`ValueError: Cannot create an NDArrayView using a view shape '[? x 5]' that has unknown dimensions for any of its axes.
`
when I create the learner (standard code).
I got this error before when I didn't use a Placeholder with the model. But using one would cause errors concerning the unknown/ unfitting input dim again.

**Comment by jsPlachetka** [comment]
I tried to create an input_map where feature itself consits of a dict of substreams (also tried list).
Neither of it works.

The Error Message ends with:
` File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\io\__init__.py", line 340, in <dictcomp>
    self._last_mb_data = {key: mb[value] for (key, value) in input_map.items()}
TypeError: unhashable type: 'dict'`
So changing to strucutre of input_map isn't an option. 
Any suggestions how I can adapt my reader (MinibatchSource)?

**Comment by KeDengMS** [comment]
Neither input_map nor CTF format allows struct. You can have multiple input names in CTF starting with |, and then StreamDef maps those input names to data stream. input_map futher maps StreamDef to input_variable. All these mappings are 1 to 1 mappings. So for the example above you need to declare separate input variables for  label/Age/A2/A3. You may use splice to concat inputs in the graph later if needed.

**Comment by jsPlachetka** [comment]
Thanks for your reply!
Apparently it is necessary to concat the inputs:
`ValueError: Values for 1 required arguments 'Input('feature', [#], [23])', that the requested output(s) 'Output('aggregateLoss', [], []), Output('Block263_Output_0', [#], [1]), Output('aggregateEvalMetric', [], [])' depend on, have not been provided.`
train_minibatch() won't work without feature in input_map

So I tried your suggestion with splice(), assuming you meant the cntk.ops.splice()
` input_map = {
            label : train_reader.streams.labels,
            feature : C.splice(train_reader.streams.age,
                           ...
                            axis = 1)
            }`
but all I've got was `ValueError: could not convert instance of type <class 'cntk.cntk_py.StreamInformation'> to an array`
the doc says, input has to be input tensors, so I might concat the minibatches themselves?!
For I'm not changing the graph after it's creation and before I invoke train_minibatch() this really confuses me.

**Comment by jsPlachetka** [comment]
Okay, got it afte I found the example here [https://www.cntk.ai/pythondocs/Manual_How_to_debug.html?highlight=splice#Does-this-network-do-what-I-think-it-does](https://www.cntk.ai/pythondocs/Manual_How_to_debug.html?highlight=splice#Does-this-network-do-what-I-think-it-does)
(would suggest to put to code also somewhere else)
change the `create_gru_stack()` to only return the embed layer -> runs train() without evoking errors.
strangely I get nan for loss and trainer.test_minibatch fails with 
`ValueError: Values for 23 required arguments 'Input('AGE', [#], [1]), ...])', that the requested output(s) 'Output('aggregateEvalMetric', [], []), Output('Block1355_Output_0', [#], [1])' depend on, have not been provided.` though I've adjusted the test_input_map

**Comment by KeDengMS** [comment]
It seems to be several independent issues. Please try fix the input issue with a network as simple as possible first, and then add more layers to the network and debug NaN loss. For NaN tracing, please use [set_checked_mode](https://www.cntk.ai/pythondocs/cntk.debugging.debug.html#cntk.debugging.debug.set_checked_mode) to find out the node that generates NaN in the first place.

**Comment by jsPlachetka** [comment]
Actually I started to do the first part of your suggestion while waiting for your answer, but couldn't find a reason for the error:
My model only consists of the input (composite/embed) layer and the output layer, no hidden layers anymore.
- train and test reader are build with the same function
- I can use test_reader  in train() and it runs, but not the other way around
- I've switched the base files, which didn't change the result
- after train() I call test() immediately, trainer and criterion_function are class members, so they are reused
So far to the possible reasons I assumed. Then I debugged as deep into the code as I could get.
- the ValueError is evoked by
 `
  def test_minibatch(self, *args):
        return _cntk_py.Evaluator_test_minibatch(self, *args)
`
args  resembles by test_input_map, which is created by the same function as my train_input_map, while self is the trainer. The only odd value is the before mentioned previous_minibatch_loss_average = nan.
All together I don't know what else I can try.
Will continue with the "NAN Problem".

**Comment by KeDengMS** [comment]
To rule out the NaN from input data, can you try use numpy to feed randomly generated data? If NaN is gone, then the network seems to be not the root of NaN.

**Comment by jsPlachetka** [comment]
OK. I had to change my data base anyway. With the new data I get numbers <1 for loss, which I expected.
Unfortunately the problem with my test() method still exists.

Just to make sure I didn't make any mistake with my test():

`def test(self, test_reader, feature=None, label=None):
        utils.print_debug("test")
        if self.__trainer == None:
            self.__set_model_utilities(label)
           #sets lr_schedule, learner, trainer, but the method reuses settings from train() usually for it's part of a Model class
       
        a1 = C.input_variable(1, name="A1")
        #and all the other input_variable
        
       #is also called in train(), but then with the train_reader
        test_input_map = self.__create_input_map(test_reader, label, a1)
        
        test_minibatch_size = 1
        num_samples = 12
        num_minibatches_to_test = num_samples // test_minibatch_size

        test_result = 0.0

        for _ in range (num_minibatches_to_test):
            data = test_reader.next_minibatch(test_minibatch_size, input_map=test_input_map)
            eval_error = self.__trainer.test_minibatch(data)
            test_result = test_result + eval_error

        return test_result`

**Comment by jsPlachetka** [comment]
I'm not sure, but I think I found a solution.
`def test(self, test_reader, feature=None, label=None):
        if self.__trainer == None:
            self.__set_model_utilities(label)
       
        test_summary = self.calculated_model.test(minibatch_source=test_reader,
                        minibatch_size=test_minibatch_size,
                        streams= (test_reader.streams.a1 #and all the other streams of test_reader in their needed order, but without the label stream
                                         )
                        )
        return test_summary['metric']`

Though it works now, I'm still wondering why it wasn't working with test_input_map.
So now I only have to handle to "eval()" part, where eval says it only likes numpy.float32 arrays - great.

**Comment by jsPlachetka** [comment]
For the sake of completeness here's my way to prepare the data for a new prediction (evoking eval()):
Also here sparse and dense data are different:
dense data is in a `np.array([np.float32(field_value)])`
while sparse data is in a `sparse.csr_matrix((field_list), shape=(1, num_of_c))`
with field_list as a list consisting of a 1 and many 0 (like one-hot as a list) and num_of_c the amount of different categories for the attribute.
These arrays have to be mapped to the `model.arguments[i]` in a dictionary (arguments as key)
By evoking eval() with this dictionary everything works.

**Comment by jsPlachetka** [comment]
I actually can't believe that I have to reopen this issue, but I get NaN for `trainer.previous_minibatch_loss_average` again  after I adjusted some columns of my data. (The data the programm worked with previously was just a subset and of course some free text fields had to many variants so that I had to replace them with some descriptive, summarizing categories. CTF looks normal)
My loss function and the trainer look like this at the moment
` self.__loss = C.squared_error(self.calculated_model, label)
        #self.__loss = C.cross_entropy_with_softmax(self.calculated_model, label)
       ...
        self.__trainer = C.Trainer(self.__calculated_model, (self.__loss, self.__label_error), [self.__learner])  # , progress_printer)`
I tried to debug, but didn't cam past the Trainer.train_minibatch() method in the trainer module. So I also tried it with a breakpoint at the loss function code (module losses) for I thought it should be evoked by train_minibatch, but the debugger didn't stop there. That really confuses me.
The actual train method in my programm wasn't changed except for adapting the reader, input_map etc. to the few alterations. But if something went wrong with that I would get "No value provided", "No data for..." or similar, right?

**Comment by KeDengMS** [comment]
Please take a look at the [debug manual](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_debug.ipynb). I'd suggest to start with [set_debug_mode](https://www.cntk.ai/pythondocs/cntk.debugging.debug.html?highlight=set_checked_mode#cntk.debugging.debug.set_checked_mode) to find out which node created NaN first. You can also dump the input/output of nodes by [set_computation_network_trace_level](https://www.cntk.ai/pythondocs/cntk.debugging.debug.html?highlight=trace_level#cntk.debugging.debug.set_computation_network_trace_level).
If you can locate the minibatch data that caused NaN, you may use [eval](https://www.cntk.ai/pythondocs/cntk.ops.functions.html?highlight=eval#cntk.ops.functions.Function.eval) or [grad](https://www.cntk.ai/pythondocs/cntk.ops.functions.html#cntk.ops.functions.Function.grad) to check each function.

**Comment by jsPlachetka** [comment]
Thanks far the fast reply.
The cause seems to be quite at the model's beginning:
After the validation of the network I get an info 

> Memory Sharing: Out of 188 matrices, 105 are shared as 28, and 83 are not shared.
This appears to me to be normal.
Afterwards I get the "abssum" (=the sum for each note?) for my Combined layer
the dense parts sometimes have absSum: 0.000 -> I expected that, for some of my inputs are 0
but with the sparse layers I get 

> absSum:inf
which comes really close to an explanation for loss = nan
The big question is now, how to prevent this

**Comment by KeDengMS** [comment]
absSum is displayed for each node with trace level 1000. Please check your sparse input to see if there are any NaNs. If not, then check the initialization values of parameters used in Times with the sparse input. You may have float overflow that generated NaN.

**Comment by jsPlachetka** [comment]
I've checked my data. There is no NaN in for sparse attributes or even a construct like 0:0*
Afterwards I've taken a close look an times. So far I've been using the implicit construct
`return C.layers.Embedding(shape)(input_layer)`
which matched the dimensions right (shape is the same shape that was used to create input_value as an C.input_variable). By explicitly using C.ops.times() the embed layer suddenly got an Placeholder with negativ dimension, which caused the Embed layer to have the wrong dimension when multiplying it with the input_layer. So `return  C.times(input_layer, C.layers.Embedding(shape=shape))` raised another problem instead of solving one though it sounded logical to check 
When displaying the model that works it is free from "Times", while the other model has them.
![modelmitembedshape_a1](https://user-images.githubusercontent.com/11850125/36088292-e437c288-0fd6-11e8-890a-62d0782c564a.PNG)
![modelmitexplizitemtimes_a1](https://user-images.githubusercontent.com/11850125/36088293-e453067e-0fd6-11e8-8572-90a4b4df0535.PNG)
(AGE is a dense attribut, but it shows the problem)


Or did I miss something essential?

**Comment by jsPlachetka** [comment]
Okay. But that doesn't mean I have to evoke eval() on embed before using times with the input_value, right? (Otherwise I completly missunderstood something)
When using times() the dimension of splice becomes -2 as well, for that's the only dimension value it gets from the input nodes. Unfortunatelly this causes a ValueError when creating the learner.
`opt = cntk_py.sgd_learner(parameters, lr, additional_options)
ValueError: Cannot create an NDArrayView using a view shape '[? x 26]' that has unknown dimensions for any of its axes.`

Is there a way to see the used weights for a layer - couldn't find explicit attributes for them belonging to a layer?

**Comment by jsPlachetka** [comment]
It becomes stranger though it seemed to improve.
I commented the attributes out that have abssum: inf. Surprinsingly not all of my sparse attributes were concerned. Afterwards training worked fine. Also after changing the graph so only sparse inputs use the embedding construct.

So I've taken a closer look an the attributes that "failed". The only "suspicious" thing I found was that they had the highest dimensions in my data (88, 63, 173 and 40). But those values aren't really high in my opinion.
As I wanted to find a hint/difference between the instances that cause inf and those not, I started with one the "broken" attributes and a batch size of 5 and looked whether there was an instance for which the abssum was ok. If not, I removed the used data from my train data. When there was one I switched the batch size to 1 and went over the data again in order to find the correct instance. Curiosly I got "inf" again for all 5 instances.
(I've also tried evoking train() again with the bigger batch size and it had to same result as before - containing a normal abssum. Only when using smaller batch size inf showed up all the time)
That really, really confuses me for the data for a single instance isn't altered. Could my problem be a bug instead?

**Comment by KeDengMS** [comment]
Maybe floating point overflow? What if you change the precision to double? It would be nice to run side by side comparison with numpy results.

**Comment by jsPlachetka** [comment]
I'm not really sure if this comment was meant for me.
My program behaves non-deterministic. My errors come from sparse, one-hot-encoded data (when using arrays this would be a scr sparse matrix) and as far as I know I have no chance to influence whether my abssum is calculated as a float or a double.
