### ISSUE TITLE
TensorBoard test summary error

### ISSUE THREAD

**Issue by rnrneverdies** [Microsoft/CNTK#2878]
Bug report, version CNTK 2.3.1

The _TensorBoardProgressWriter_ python class is causing a fatal error in the method _on_write_test_summary_ line [530](https://github.com/Microsoft/CNTK/blob/1cca6e2c1742fa399e8ec2bab5604a2808530f95/bindings/python/cntk/logging/progress_print.py#L522-L530).

Error caused:
```
AttributeError: 'ProgressWriter' object has no attribute 'summaries'
``` 

Observations:
It seems that where it says "self.summaries" should say "summaries" which is one of the method's arguments. I tried this fix on my side and it seems to work as expected. 

Let me know if it's OK to send a PR.

**Comment by KeDengMS** [comment]
Thanks for the report, please send a PR.
