### ISSUE TITLE
support for scatter_nd_add

### ISSUE THREAD

**Issue by NO-0044** [Microsoft/CNTK#2884]
I want to implement the pointer-generator network detailed in https://github.com/abisee/pointer-generator . It needs to map the attention distribution to vocabulary. The original implementation uses scattter_nd in tensorflow. Since CNTK doesn't support this now, I tried the following:
```
h_att = attention_model(encoded_input.outputs[0], r[0]) 
att_w = h_att.attention_weights 
# att_w: [#,d] [*=e]
# extended_input: [#,e] [voc_size=50k], one_hot
tmp = C.sequence.broadcast_as(C.sequence.unpack(extended_input, padding_value=0, no_mask_output=True), att_w)
# tmp: [#,d] [*=e, voc_size=50k]
att_dist = C.reduce_sum(att_w*tmp, axis=0)
att_dist = C.reshape(att_dist, (), 0, 1, name='att_dist')
# att_dist: [#,d] [voc_size=50k]
```
But although the `extended_input` is just a one-hot sparse matrix, it seems it will create a dense matrix after unpack and broadcast and finally cause gpu out of memory and I can only run it on cpu. Is there any way I can accomplish this?

**Comment by KeDengMS** [comment]
Can you print out the shapes for each operation's output? Is it possible to use [times and TIMES_REDUCE_SEQUENCE_AXIS_WITHOUT_INFERRED_INPUT_RANK](https://www.cntk.ai/pythondocs/cntk.ops.html?highlight=TIMES_REDUCE_SEQUENCE_AXIS_WITHOUT_INFERRED_INPUT_RANK#cntk.ops.times) in place of reduce_sum?

**Comment by NO-0044** [comment]
I have added the shapes of each outputs. Hope it will help.
I tried times at first, like `C.times(att_w, unpacked_extended_input)`, but seems dynamic axis cannot be directly used like this. If I unpacked `att_w` too, seems times doesn't support something like `[#][*=d,*=e] @ [#][*=e,voc_size=50k]`.  So I tried like the implementation of attention that first `broadcast` and use element_times and reduce_sum. Then I guess the broadcast will cause out of memory, since it tries to create a matrix `[#,d][*=e,voc_size=50k]` and seems to be a dense one.

**Comment by KeDengMS** [comment]
> times doesn't support something like [#][*=d,*=e] @ [#][*=e,voc_size=50k]. 

This is fixed in the latest master. To avoid the broadcasting of extended_input, I believe your script can be written as:

```
#att_w: [#,d] (*=e)
#extended_input: [#,e](voc_size)
att_w_unpacked = C.sequence.unpack(att_w, 0, no_mask_output=True)
# att_w_unpacked: [#](*=d, *=e)

extended_input_unpacked, d_mask = C.sequence.unpack(extended_input, 0)
#extended_input_unpacked: [#](*=e, voc_size), in dense

att_dist_unpacked = C.times(att_w_unpacked, extended_input_unpacked)
#att_dist_unpacked: [#],(*=d, voc_size), note this needs latest change of batch matmul to be performant

att_dis = C.to_sequence(att_dist_unpacked, d_mask)
#att_dist: [#,d](voc_size)

```

**Comment by NO-0044** [comment]
After build with the latest version, the times works but there are still some problems.
when use
`att_dist = C.to_sequence(att_dist_unpacked, d_mask)
`
the model can be created but cause runtime error:
`NDShape::TotalSize: TotalSize cannot be determined for a NDShape [*] with one or more dimensions being infeerreddimention or freedimention`
I replace it with 
`att_dist = C.to_sequence_like(att_dist_unpacked,att_w)`
and it works now.

**Comment by KeDengMS** [comment]
Thanks for the solution.
