### ISSUE TITLE
CNTK with float16

### ISSUE THREAD

**Issue by Rov67777** [Microsoft/CNTK#2885]
Hello,

I have tried to use last commited version of CNTK with float16. I have done the following steps to adapt the code:
 - turns input / output to float 16 datatype
 - cast loss and eval functions to float 32 as is suggested in the example https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_ImageNet_Distributed.py
 - use GPU as it is not supposed to be implemented in CPU
 - use the sources from the last commited CNTK versions with cuda 9.0

even though the graph / trainer / loss build correctly I get the following error when trying to train my model :
`RuntimeErorr: FP16 convolution is only supported via cuDNN`

where the ResNet example shown here : https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/Python/TrainResNet_ImageNet_Distributed.py 
is working correctly even with the option fp16

**Comment by KeDengMS** [comment]
You probably have a convolution not supported by cuDNN. Please check [CuDnnConvolutionEngineFactory::IsSupported](https://github.com/Microsoft/CNTK/blob/master/Source/Math/CuDnnConvolutionEngine.cu#L724). If you observed warning on asymmetric padding issue then that's probably the cause.

Note the limitation on padding is something we observed in cuDNN 6.0. @FDecaYed can you comment if this is already handled in cuDNN 7? If so, we may remove the check.

**Comment by FDecaYed** [comment]
From the code it seems that should be the reason cudnn engine is not used. we can confirm that if we have the sizes.
The ability to handle arbitrary asymmetric padding is not in cudnn 7.

**Comment by Rov67777** [comment]
@FDecaYed 
So I have been investigated and the reason the cudnn engine was not used is that I used 3D pooling for which CNTK does not use the cuDNN engine (it would be good to check if cudNN still does not handle 3D pooling, because it seems weird that 3D convolution is supported and not 3D pooling)
