### ISSUE TITLE
cntk23 compiler error (about fp16)

### ISSUE THREAD

**Issue by latifovic** [Microsoft/CNTK#2890]
OS: CentOS 7
Error message:
In file included from Source/Math/Matrix.h:23:0,
from Source/ComputationNetworkLib/ComputationNetwork.h:10,
from Source/ActionsLib/Actions.h:12,
from Source/EvalDll/CNTKEval.cpp:15:
Source/Math/half.hpp:13:39: error: missing binary operator before token "("
#if !defined(CPUONLY) && __has_include("cuda_fp16.h")

when if block removed in cuda_fp16.h (for case of GPU) it compiles

**Comment by KeDengMS** [comment]
cuda_fp16.h is a header from CUDA 9.0. Please follow the instructions in [README.md](https://github.com/Microsoft/CNTK/blob/master/README.md) to setup CUDA 9.0 environment

**Comment by latifovic** [comment]
Hello

Thank you for respond!

I have installed CUDA 9.1 and cuDNN 7 for cuda 9.1 before attempting to compile CNTK 2.3. That should not be problem.

Compiler output:

creating /home/latifovi/cntk/build/release/.build/Source/EvalDll/CNTKEval.o for Linux with build type release
/usr/local/mpi/bin/mpic++ -c Source/EvalDll/CNTKEval.cpp -o /home/latifovi/cntk/build/release/.build/Source/EvalDll/CNTKEval.o -DHAS_MPI=1 -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCUDA_NO_HALF -D__CUDA_NO_HALF_OPERATORS__ -DUSE_CUDNN -DUSE_NCCL -DUSE_MKL -DUSE_MKLDNN -DNDEBUG -DNO_SYNC -DASGD_PARALLEL_SUPPORT  -DCNTK_COMPONENT_VERSION="2.3.1" -DUSE_ZIP -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/CNTKv2LibraryDll/proto -ISource/../Examples/Extensibility/CPP -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -ISource/PerformanceProfilerDll -I/usr/local/protobuf-3.1.0/include -I/usr/local/cuda/include -I/usr/local/cub-1.7.4 -I/usr/local/cuda-9.1/include -I/usr/local/cudnn-7.0/cuda/include -I/usr/local/nccl_2.1.4-1+cuda9.1_x86_64/include -I/usr/local/mklml/mklml_lnx_2018.0.1.20171007/include -I/usr/local/boost-1.60.0/include -I/usr/local/include -I/usr/local/lib/libzip/include -I/home/latifovi/opencv-3.1.0/include -I/home/latifovi/opencv-3.1.0/include -ISource/Multiverso/include -ITests/EndToEndTests/CNTKv2Library/Common -I/usr/local/boost-1.60.0/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF /home/latifovi/cntk/build/release/.build/Source/EvalDll/CNTKEval.d
In file included from Source/Math/Matrix.h:23:0,
                 from Source/ComputationNetworkLib/ComputationNetwork.h:10,
                 from Source/ActionsLib/Actions.h:12,
                 from Source/EvalDll/CNTKEval.cpp:15:
Source/Math/half.hpp:13:39: error: missing binary operator before token "("
#if !defined(CPUONLY) && __has_include("cuda_fp16.h")



Compiler is showing error in the file half.hpp

//
// Copyright (c) 2017, NVIDIA CORPORATION. All rights reserved.
// Licensed under the MIT license. See LICENSE.md file in the project root for full license information.
//
// define half type since __half is device only
// TODO: investigate performance of implementation, function signature and efficiency

#pragma once
#include "../CNTKv2LibraryDll/API/HalfConverter.hpp"
#if !defined(CPUONLY) && __has_include("cuda_fp16.h")
#include <cuda_fp16.h> // ASSUME CUDA9
#else
class alignas(2) __half
{
protected:
    unsigned short __x;
};
#endif

#if defined(__CUDACC__)
#define __CUDA_HOSTDEVICE__ __host__ __device__
#define __INLINE__ __forceinline__
#else
#define __CUDA_HOSTDEVICE__
#define __INLINE__ inline
#endif

#define __FP16_DECL__ __INLINE__ __CUDA_HOSTDEVICE__
class alignas(2) half : public __half {
public:
….
….

**Comment by KeDengMS** [comment]
Note that CNTK is currently built on CUDA 9.0, not 9.1. Please make sure you have following files after installed CUDA 9.0.

/usr/local/cuda-9.0/include/cuda_fp16.h
/usr/local/cuda-9.0/include/cuda_fp16.hpp

**Comment by melrobin** [comment]
I can confirm the compilation error and that those files in the cuda-9.0 directory are present.  Interestingly enough when I change the C++ compiler to 6.4.1 the build breaks farther along than when I use 4.8.5

**Comment by KeDengMS** [comment]
The doc on CNTK setup is kinda outdated. CNTK 2.4 Release is compiled with gcc 5.4.0 on Ubuntu 16.04, using NVidia cuda 9 docker image as base. For other versions, can you try compile some cuda samples?

**Comment by melrobin** [comment]
OK, KeDengMS is right; using gcc 5.4.0 I no longer get the error.
