### ISSUE TITLE
Does CUDNN be used?

### ISSUE THREAD

**Issue by ghb1234** [Microsoft/CNTK#2893]
I have download a gpu supported cntk,and my cudnn version is 5.0.5. But the build version is
-------------------------------------------------------------------
Build info: 

        Built time: Dec  5 2017 18:13:09
        Last modified date: Tue Nov 14 02:53:52 2017
        Build type: release
        Build target: GPU 
        With 1bit-SGD: no
        With ASGD: yes 
        Math lib: mkl 
        CUDA version: 9.0.0
        CUDNN version: 6.0.21
        Build Branch: HEAD
        Build SHA1: ce72a557b02b30a52c965a237b124688035f720f
        MPI distribution: Open MPI 
        MPI version: 1.10.7
-------------------------------------------------------------------
the cudnn version is 6.0.21, when I change the cudnn version to 5.0.5 to cudnn 7.0.5. the build info is still 6.0.21. So does cudnn be used?

**Comment by KeDengMS** [comment]
Yes cuDNN is used. If you are using Python, cuda libs are included in the package so it's independent of the libs you installed locally. In the future we might change to not include cuda libs in Python wheels to reduce distribution size.
