### ISSUE TITLE
Is it possible to write SRU cells in python script using CNTK package？

### ISSUE THREAD

**Issue by noble6emc2** [Microsoft/CNTK#2897]
It seems that CNTK doesn't support SRU cell. I am trying to write one myself, but I cannot find any tutorials online.And I have no idea how to write it.

**Comment by KeDengMS** [comment]
You can implement your own cells. [Here](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_204_Sequence_To_Sequence.ipynb)'s the tutorial for doing that. Please look for lstm_with_attention in this tutorial as an example.

**Comment by noble6emc2** [comment]
Thanks a lot!!! That solves my problem perfectly :)
