### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/CNTK#29]
I would like to point out that identifiers like "[`_FILEUTIL_`](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/Common/Include/fileutil.h#L8)" and "[`__VALLUE_QUANTIZER_H__`](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/Math/ValueQuantizer.h#L2)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mahilleb-msft** [comment]
I guess we should go over these and change them ("grep.exe -r -E -o -h '\<_\w+_\>' Source | sort -u" for starters and change the one we introduce).

**Comment by wolfma61** [comment]
"pragma once" is working for all the compiler (vss, gcc) we are targeting. 
We have header files which only use "pragma once" and no guard-definitions.
We are not copying header files (or having multiple versions of header files) in our projects (if we do, this would be a BUG, they should only reside in one location)

"pragma once" should be used. guard-defines should be removed.

**Comment by elfring** [comment]
How much do you care for [standard compliance](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#23699893 "Is #pragma once part of the C++11 standard?") in your software?
