### ISSUE TITLE
CNTK: Failed to load DLL 'libacml_mp_dll.dll'; Module not found

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#290]
Built using VS 2013 on Win10 and testing Simple2d example:
```
Validating network. 17 nodes to process in pass 2.
Validating network, final pass.
12 out of 25 nodes do not share the minibatch layout with the input data.
Post-processing network complete.
evalNodeNames are not specified, using all the default evalnodes and training criterion nodes.
Allocating matrices for forward and/or backward propagation.
UCIFastReader: Starting at epoch 0, counting lines to determine record count...
 603 records found.
starting epoch 0 at record count 0, and file position 0
already there from last epoch
CNTK: Failed to load DLL 'libacml_mp_dll.dll'.
CNTK: Caught Win32 exception 0xc06d007e: Module not found.
```
libacml_mp_dll.dll is in path Documents\CNTK-master\x64\Release
Any suggestions how to remedy?

**Comment by whitmark** [comment]
I rebuilt the binary and noticed the following warning message:

`Warning	1	warning LNK4199: /DELAYLOAD:libacml_dll.dll ignored; no imports found from libacml_dll.dll	C:\user\username\Documents\CNTK-master\Source\Math\LINK	Math
`

**Comment by whitmark** [comment]
Since the build process went fine on Win 10, I was curious why the libacml_mp_dll.dll could not be found during Simple2d runtime so I made a debug build type and traced the Win32 exception to the sgemm() call within the CPUMatrix method of CPUMatrix.cpp line 4184.

```
#pragma warning(suppress : 4244)
#ifdef USE_ACML
        **sgemm**(BLAS_COLMAJOR transA, transB, m, n, k, alpha, reinterpret_cast<float*>(a.m_pArray), lda, reinterpret_cast<float*>(b.m_pArray), ldb, beta, reinterpret_cast<float*>(c.m_pArray), ldc);
#else
        cblas_sgemm((CBLAS_ORDER) BLAS_COLMAJOR mklTransA, mklTransB, m, n, k, alpha, reinterpret_cast<float*>(a.m_pArray), lda, reinterpret_cast<float*>(b.m_pArray), ldb, beta, reinterpret_cast<float*>(c.m_pArray), ldc);
#endif
```
I followed the instructions in the code and Windows Setup in the wiki regarding the ACML install:

```
#ifdef USE_ACML
// Download ACML 5.3.1 (e.g., acml5.3.1-ifort64.exe) or above
// from http://developer.amd.com/tools/cpu-development/amd-core-math-library-acml/acml-downloads-resources/
// Install the ifort64_mp variant (compiled with intel compiler) of the library
// Set Environment variable ACML_PATH to C:\AMD\acml5.3.1\ifort64_mp or the folder you installed acml
// to point to your folder for the include file and link library
#include <acml.h> // requires ACML 5.3.1 and above

```
And set paths accordingly.

```
ACML_PATH=C:\AMD\acml5.3.1\ifort64_mp
PATH=C:\repos\CNTK-master\x64\Debug (among others)
```
I see the instructions suggests "Download ACML 5.3.1 (e.g., acml5.3.1-ifort64.exe) **or above**".  Don't know if this suggests I should use ACML 6.1 for Windows 10.

Any suggestions?

**Comment by whitmark** [comment]
After much trial and error I was unable to resolve the runtime error of my own CNTK build:
```
CNTK: Failed to load DLL 'libacml_mp_dll.dll'.
CNTK: Caught Win32 exception 0xc06d007e: Module not found.
```
Until I noticed in the windows binary instructions had the following requirements:

> Visual C++ Redistributable Package for Visual Studio 2013
> Visual C++ Redistributable Package for Visual Studio 2012

Sure enough, I had inadvertently removed the VS 2012 redistributable when I removed VS 2012 per the suggestion to not have competing VS versions installed although I have retained VS 2015 for other work.

> _We found that if you have VS 2013 and VS 2012 or VS 2010 installed simultaneously it may cause build failures. Therefore we recommend to have a "clean" installation of Visual Studio 2013._

Once the missing redistributable was installed, the runtime executed simple2d without issue.

Please update "Setup CNTK on Windows" instructions.  Also, is the development team also running a Win10 test bed?

Thanks!

**Comment by alexeyo26** [comment]
Mark, thank you for posting this. I will update instructions, the way you suggest (actually, if you just install a Visual Studio, you automatically get runtimes for the preceding versions; but in your case you were doing manual removals - hence the issues).

And about tested configurations. I plan to post complete configurations we use for testing this week. Shortly, they are Windows 8.1, Windows Server 2012 R2 (same Windows 8.1 kernel) and Ubuntu 14.03 based.

I will close this issue now and thank you a lot once again.
Alexey

**Comment by whitmark** [comment]
Thanks Alexey.

I am surprised there is not a Windows 10 configuration in the mix given recent trends in developer OS use. 

[(http://stackoverflow.com/research/developer-survey-2016#technology-desktop-operating-system )]

Thanks for all you do to make CNTK a great solution!

**Comment by alexeyo26** [comment]
Mark, thank YOU! Of course, we’re planning to start regularly testing on Windows 10,  but believe me, we are a small (but rather energetic ☺) team, so we need to prioritize tasks. So, stay tuned.

And thank you one more time!
Alexey
