### ISSUE TITLE
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by abidmalik1967** [Microsoft/CNTK#2909]
import cntk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amalik/.local/lib/python2.7/site-packages/cntk/__init__.py", line 13, in <module>
    from . import cntk_py
  File "/home/amalik/.local/lib/python2.7/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/amalik/.local/lib/python2.7/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/software/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/amalik/.local/lib/python2.7/site-packages/_cntk_py.so)

-------------------------

How can I get rid of this error?
I  used anaconda2 for installation:

pip install --user https://cntk.ai/PythonWheel/GPU/cntk-2.4-cp27-cp27mu-linux_x86_64.whl

installation was successful. However, accessing cntk is the problem.
Thanks

**Comment by abidmalik1967** [comment]
I updated the libgcc using conda install libgcc, update LD_LIBRARY_PATH as well. Tried every solution that I could find on web.

**Comment by haixpham** [comment]
please build GCC from source with the current compiler on your Linux machine, and set the path to the newly built libstdc++.so.6 in your $PATH

**Comment by abidmalik1967** [comment]
I changed the GCC from 4.8 to GCC 7.XX and it worked.

Thanks,

**Comment by leriomaggio** [comment]
> I updated the libgcc using conda install libgcc, update LD_LIBRARY_PATH as well. Tried every solution that I could find on web.

I solved in this way:

I installed `conda install libgcc` library in my conda virtual environment and then 
changed the $LD_LIRABRY_PATH by appending the path to the `lib` folder of the environment:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/anaconda3/envs/<NAME>/lib
```

Additionally, I also needed to **symlink** the `libfabric.so.1` file: 
```
ln -sf ~/anaconda3/envs/<NAME>/lib/libfabric/libfabric.so.1 ~/anaconda3/envs/<NAME>/lib`

HTH
Valerio

**Comment by YokkaBear** [comment]
> > I updated the libgcc using conda install libgcc, update LD_LIBRARY_PATH as well. Tried every solution that I could find on web.
> 
> I solved in this way:
> 
> I installed `conda install libgcc` library in my conda virtual environment and then
> changed the $LD_LIRABRY_PATH by **appending** the path to the `lib` folder of the environment:
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/anaconda3/envs/<NAME>/lib
> ```
> Additionally, I also needed to **symlink** the `libfabric.so.1` file:
> 
> ```
> ln -sf ~/anaconda3/envs/<NAME>/lib/libfabric/libfabric.so.1 ~/anaconda3/envs/<NAME>/lib
> ```
> HTH
> Valerio



> > I updated the libgcc using conda install libgcc, update LD_LIBRARY_PATH as well. Tried every solution that I could find on web.
> 
> I solved in this way:
> 
> I installed `conda install libgcc` library in my conda virtual environment and then
> changed the $LD_LIRABRY_PATH by **appending** the path to the `lib` folder of the environment:
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/anaconda3/envs/<NAME>/lib
> ```
> Additionally, I also needed to **symlink** the `libfabric.so.1` file:
> 
> ```
> ln -sf ~/anaconda3/envs/<NAME>/lib/libfabric/libfabric.so.1 ~/anaconda3/envs/<NAME>/lib
> ```
> HTH
> Valerio

Thank you dude, that method absolutely works for me, and let my sketch-rnn network to be compiled. thank you very very very much!
