### ISSUE TITLE
Using CNTK to construct a complete speech recognition system 

### ISSUE THREAD

**Issue by denghuiru** [Microsoft/CNTK#291]
Hi ：
I recently research CNTK  for speech recognition, however, I found that in the speech folder, the examples  can only be trained from audio to corresponding phoneme, but not the letters or the word.
So, I wonder whether the CNTK can implement a complete speech recognition from audio to text, if it can, will you tell me how to do it. If it dose not support this process, how to combine acoustic model and language model to construct a complete speech recognition system?
By the way, Dose CNTK support CTC function, a kind of end to end learning method, if not, when will you add this function to CNTK?

**Comment by staplesinLA** [comment]
I'm confused ,too. Have you found sth valueable?
Thanks.

**Comment by rvenkidapathy** [comment]
The current CNTK Speech examples do not cover language and acoustic models nor there are any sections covering "How to use CNTK and covert Speech to text".

**Comment by frankseide** [comment]
That is correct. Until recently, DNN-based ASR systems required a GMM tool chain for creating alignments. We support data formats of HTK and Kaldi.

One step closer to the answer is CTC. It is on the list to be added, I hope for 1.8. Code already exists in branches the repo, but it must be generalized before merging to master.

I am not clear, though, whether one can how one would then get away with not using a Viterbi decoder.

**Comment by Swordsemperor** [comment]
So can CNTK 2.0 do it now??
