### ISSUE TITLE
Cannot initialize Dense layer

### ISSUE THREAD

**Issue by dubvulture** [Microsoft/CNTK#2914]
My current goal is to clone a single layer from an already trained model.

The first problem is that the `clone()` method clones the entire graph from the supplied node which is not what I want.

So I tried cloning it manually (in this case a Dense layer) by retrieving its weights from the node as follows:

```
    node = C.logging.graph.find_by_name(model, 'node')
    C.layers.Dense(node.shape, init=node.W.value, init_bias=node.b.value)
```

Unfortunately this does not work since I get the following error:

```
    TypeError: in method 'random_initializer_with_rank', argument 1 of type 'CNTK::ParameterInitializer const &'
```

**Comment by rnrneverdies** [comment]
To share parameters between models, you can declare the dense layer and then use it on both models:

Example:

```
mydense = C.layers.Dense( ... )

main_model = mydense(input)
other_model= mydense(other_input) 
```

So, main_model and other_model would share the same parmaters. 

Hope that helps.

**Comment by dubvulture** [comment]
Closed.
Duplicate of #2913.
