### ISSUE TITLE
Negative Tensor is difficult to wrap my brain around

### ISSUE THREAD

**Issue by CynsierWang** [Microsoft/CNTK#2916]
` Composite(Sequence[Tensor[200]], Sequence[Tensor[200]]) -> Sequence[Tensor[-3]]
 Composite(Sequence[Tensor[200]], Sequence[Tensor[200]]) -> Sequence[Tensor[-3,1]]`
Why does this shape have a negative dimension ? What does it look like?

**Comment by aWeinzierl** [comment]
This may help: http://danlec.com/st4k#questions/46169811

Would it not be very useful to document such things somewhere?
