### ISSUE TITLE
netstandard 2.0 NuGet package?

### ISSUE THREAD

**Issue by mathias-brandewinder** [Microsoft/CNTK#2917]
As far as I can tell, the NuGet package for `CNTK.CPUOnly` is not .netstandard 2.0 compliant.
Is there a technical reason for that choice, or is it accidental?

**Comment by aaad** [comment]
Look at https://github.com/Microsoft/CNTK/issues/2352 It is planned but posponed since september. I hope they add it in the next release. I think they feel our pressure so we should be patient. ;)

**Comment by mathias-brandewinder** [comment]
@aaad thanks for the pointer - closing this, I didn't search enough :)
