### ISSUE TITLE
Group convolution layer - error!

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#2928]
If I have an input like this:
`x = C.input_variable((2,128)) #input`

And pass it through a convolution layer like this: 
`f = C.layers.Convolution(7, 4, pad=True, bias=False)`

then, all input channels are convolved to produce all output channels.

However, I would like to use the grouping feature with convolution layer as described [here](https://cntk.ai/pythondocs/cntk.layers.layers.html).

But, I get an error with:
`f = C.layers.Convolution(7, 4, pad=True, bias=False,groups=2)`

```
raise ValueError("Convolution: groups > 1, is not currently supported by Convolution layer. For group convolution with groups > 1, use CNTK's low-level convolution node (cntk.convolution).")
ValueError: Convolution: groups > 1, is not currently supported by Convolution layer. For group convolution with groups > 1, use CNTK's low-level convolution node (cntk.convolution).
```

Is there an easy way for me to apply group convolution layer on my input?

**Comment by spandantiwari** [comment]
@arijit17 Currenty the Convolution layer in CNTK does not support group convolution. However the lower-level convolution op (cntk.convolution) supports group convolution. Can you try using the convolution op instead of Convolution layer, as suggested in the error message. Here's a snippet that shows the usage:
```
import cntk as C
x = C.input_variable((16, 64, 64), dtype= np.float32)
conv_map = C.parameter((16, 1, 3, 3), init=C.glorot_uniform())
y = C.convolution(conv_map, x, groups= 16)

```

**Comment by arijit17** [comment]
Hello! It will be really cool if I would have group convolution layer. Any plans of having this in a future release?

**Comment by spandantiwari** [comment]
Not exactly for group convolution, but we have an open item for depth-wise  convolution. But I do not have an ETA for that.

**Comment by arijit17** [comment]
@spandantiwari what do you mean by depth-wise convolution? 
I guess you mean the same thing as written in the latest [release notes example](https://docs.microsoft.com/en-us/cognitive-toolkit/ReleaseNotes/CNTK_2_6_Release_Notes) under "Efficient group convolution".

So, yes, I would like to have is a learn-able version of depth-wise convolution. 
(which is basically the same wish as this guy had in #2521 (see at the top)).
