### ISSUE TITLE
Does cntk really support CUDA 9?

### ISSUE THREAD

**Issue by cqduan** [Microsoft/CNTK#2929]
I update the cntk (2.3) to 2.4. When I use the CUDA 8, the program can't run on the GPU. Then, I update the CUDA, as a result, the python stop working.

OS: windows server 2012R2
GPU: K80

CUDA 8:
\>\>\>cntk.device.all_devices()
(CPU,)

CUDA 9:
\>\>\>cntk.device.all_devices()
Python has stopped working

**Comment by bencherian** [comment]
If you are installing the provided CNTK wheels I believe the relevant CUDA DLLs are distributed in the wheel. You don't need to have CUDA installed. You do however, need to have a driver that supports CUDA 9.
