### ISSUE TITLE
The evaluation results of c# and python are different

### ISSUE THREAD

**Issue by venkateshbam** [Microsoft/CNTK#2937]
We evaluated a set of images using AML Workbench "Image Classification using CNTK" (python) project and C# project with CNTK CPUOnly package, with the same model. We got different results in these two environments.

In python, we used the helpers_cntk.py library method 'runCntkModelImagePaths' to preprocess and evaluate the image.

Similarly, in C# project, we used CNTK C# APIs to evaluate the image and imageReader's, resize and ParallelExtractCHW method to preprocess the image as suggested by the CNTK C# Eval API examples.

But still, the results are not matching between Python and C# projects. Is this expected ? If not can you please guide us with this issue.

**Comment by KeDengMS** [comment]
C#/C++ matrices are column major, while in Python it's row major, so ranks of tensors are reversed and matmul left/right operands are switched in the Python binding call to C++. You can either transpose the input, or adjust matmul orders to get the same results in C# as in Python.

**Comment by venkateshbam** [comment]
Thanks for the quick reply @KeDengMS . I am not making a call to C# binding from Python. I am trying to evaluate the model from C# application itself. 

Both C# application and Python application are using ImageDeserializer with same paramter values for scaling an image to required dimensions and then the miniBatchSource is passed to the model evaluate method. Still, both C# and Python are having different results.
