### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by kingstarcraft** [Microsoft/CNTK#294]
I want to build CNTK with MKL,but there are too many file in math project,I don't know in which files I need to #define USE_MKL.

**Comment by alexeyo26** [comment]
I believe you want to compile on Windows. If yes, look Math project properties, Configuration Properties -> C/C++ -> All Options -> Preprocessor Definitions

**Comment by kingstarcraft** [comment]
Thanks very much

**Comment by alexeyo26** [comment]
Thank you as well. I will close the issue now.
