### ISSUE TITLE
Cannot specify sampleBasedRandomizationWindow=true in MinibatchSource.TextFormatMinibatchSource

### ISSUE THREAD

**Issue by mjmckp** [Microsoft/CNTK#2943]
Attempting to call `MinibatchSource.TextFormatMinibatchSource` from C# (using the `CNTK.GPU` NuGet package, version 2.3.1) with `sampleBasedRandomizationWindow=true` always fails with the following error:
```
System.ApplicationException: MinibatchSourceConfig: randomization window in chunks and randomization window in samples are mutually exclusive options and cannot have non-zero values at the same time.

[CALL STACK]
    > CNTK::Internal::  ToDictionary
    - CNTK::  UniversalLearner
    - CNTK::  CreateCompositeMinibatchSource
    - CSharp_CNTK_DefaultParamInitScale_get (x2)
    - CSharp_CNTK_MinibatchSource_TextFormatMinibatchSourceInternal__SWIG_0
    - 00007FFD1A64D9C5 (SymFromAddr() error: The specified module could not be found.)


   at CNTK.MinibatchSource.TextFormatMinibatchSourceInternal(String dataFilePath, StreamConfigurationVector streamConfigs, UInt64 epochSize, Boolean randomize, UInt64 randomizationWindow, Boolean sampleBasedRandomizationWindow)
```

**Comment by KeDengMS** [comment]
By default randomization_window_in_chunks in MinibatchSource() is not zero, you need to set it zero to use randomization_window_in_samples:
```
randomization_window_in_chunks=0,
randomization_window_in_samples=4*1024*1024,
```

**Comment by mjmckp** [comment]
In that case the underlying implementation of `MinibatchSource.TextFormatMinibatchSource` needs to be fixed to set `randomizationWindowInChunks` to zero when `sampleBasedRandomizationWindow=true`, this doesn't appear to be possible via the .NET api.

**Comment by KeDengMS** [comment]
Yes it's a bug in TextFormatMinibatchSource. In the future TextFormatMinibatchSource would go away and using CTFDeserializer is recommended. Can you use CTFDeserializer instead? 
```
StreamConfigurationVector streams = new StreamConfigurationVector
{
    new StreamConfiguration("feature", 100),
    new StreamConfiguration("label", 10)
};
var deserializerConfiguration = CNTKLib.CTFDeserializer(mapFilePath, streams);
MinibatchSourceConfig config = new MinibatchSourceConfig(new List<CNTKDictionary> { deserializerConfiguration })
{
    MaxSweeps = maxSweeps,
    randomizationWindowInChunks = 0,
    randomizationWindowInSamples = 100000,
};
return CNTKLib.CreateCompositeMinibatchSource(config);
```

**Comment by mjmckp** [comment]
That works, thanks.  Btw, it appears that both `CNTKLib.CreateCompositeMinibatchSource` and `MinibatchSource.TextFormatMinibatchSource` return minibatch sources that produce minibatches with `DataType.Float`.  Can these be configured to produce minibatches with `DataType.Double`, or is this missing from the API?

**Comment by KeDengMS** [comment]
In 2.4 release there is [cast](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.cast). Reader still can only handle float, but you can cast it to double.
