### ISSUE TITLE
Generative Adversarial Nets to train owndata?

### ISSUE THREAD

**Issue by lotuschang** [Microsoft/CNTK#2953]
Hi
How to use GAN by CNTK to train own data?
Thanks very much.

**Comment by KeDengMS** [comment]
Please take a look at GAN Tutorials: [206A Basic GAN](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206A_Basic_GAN.ipynb), [206B DCGAN](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206B_DCGAN.ipynb) and [206C WGAN LSGAN](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_206C_WGAN_LSGAN.ipynb).
