### ISSUE TITLE
Error when loading a BrainScript model in Python

### ISSUE THREAD

**Issue by GhMaRo** [Microsoft/CNTK#2956]
Hi,

I want to load a BrainScript model with Python, but I get the following error:

![cntk_load_error](https://user-images.githubusercontent.com/35937611/36152959-099331b0-10cd-11e8-81ce-5f7c8a28e75f.png)
Does anyone know how to solve this problem?

**Comment by KeDengMS** [comment]
Can you share the model?

**Comment by GhMaRo** [comment]
I can't share my original model, but here is a **very** lightweigth example model which produces the same error:
```
kern 		= Parameter{1, (45:45), init='fromFile', initFromFilePath='C:/kernel45.txt', learningRateMultiplier=0.0}
l1  		= Input{(96:96:1)}
lconv 		= Convolution(kern, l1, 45:45, mapDims = 1)

features 	= Input((96:96:1), tag = "feature")
o2 		= ConvolutionalLayer(1, (1:1), pad=true, stride=(1:1), init="gaussian", bias=true)(features)

diff_conv2 	= o2 - lconv

sqErr  	 	= ReduceSum(diff_conv2.*diff_conv2)

outputNodes 	= (o2)
criterionNodes 	= (sqErr)
```
When I create this model in BrainScript, I get the following model file (unpack the *.zip-file):
[model.zip](https://github.com/Microsoft/CNTK/files/1723556/model.zip)

But when I now want to load this model in Python, this does not work.

**Comment by KeDengMS** [comment]
This model's input to convolution has shape of (96,96,1), while the convolution kernel shape is (1,45,45). I think the problem would go away if you change convolution input shape to (1,96,96) instead of (96,96,1)

**Comment by GhMaRo** [comment]
The problem is, that I would have to change the shape in BrainScript. But BrainScript wants to have the shape (96,96,1), otherwise it cannot create and train the model. And in Python I cannot import the model due to this error.
Another thing is, that in this example "lconv" is not really part of the model...it is only part of the criterion function "sqErr", so this error makes no sense.

**Comment by KeDengMS** [comment]
Can you change lconv kernel to 45:45:1 then?

**Comment by GhMaRo** [comment]
After a reshape of the kernel to 45:45:1 BrainScript still works (trains) but when I want to load the created model in Python, it crashes ("Python has stopped working").
[model.zip](https://github.com/Microsoft/CNTK/files/1725803/model.zip)

**Comment by KeDengMS** [comment]
The second model works fine in 2.4 release, for both Windows and Linux.

**Comment by GhMaRo** [comment]
Ok, thanks. At the moment I'm using version 2.3. So then I will try updating to CNTK 2.4.

**Comment by GhMaRo** [comment]
I updated to CNTK 2.4 and changed the kernel dimension in my original BrainScript network and now the import of the model in Python works! Thank you!
