### ISSUE TITLE
Help on implementing DRAW: Deep Recurrent Attention Writer on CNTK

### ISSUE THREAD

**Issue by delzac** [Microsoft/CNTK#2958]
Hi,

In order to implement DRAW, i would need to pass the output of the previous timestep as an input to the current timestep and i can't think of a way to do this on cntk.

Anyone has any suggestion? Any help will be greatly appreciated!!

![image](https://user-images.githubusercontent.com/19370780/36206348-fe7b1fda-11cc-11e8-92ad-7c7e3f4de925.png)

[Link to original paper](https://arxiv.org/abs/1502.04623)

**Comment by KeDengMS** [comment]
You can get full state in [Recurrence](https://cntk.ai/pythondocs/cntk.layers.sequence.html#cntk.layers.sequence.Recurrence) by setting return_full_state=True. Then you can use [Delay](https://cntk.ai/pythondocs/cntk.layers.sequence.html#cntk.layers.sequence.Delay) to get hidden state from previous timestep.

**Comment by delzac** [comment]
@KeDengMS 

I'm not sure i get you. This was what i attempted.

view = read(image_tensor, **decode**, canvas)
encode = recurrence(lstm)(view)
q = gaussian_distribution(encode)
decode = recurrence(lstm)(q)
write = dense()(decode)
canvas = recurrence(cumsum)(write)

Clearly passing decode in before it is even instantiated cannot be done. I'm not sure if i understood your suggestion correctly.

**Comment by KeDengMS** [comment]
OK it seems your model would have the same sequence length for encode and decode. In that case, I would try write encode/q/decode in one Reccurrence cell. Please take a look at tutorial 204 to check how to implement your own cell.

**Comment by delzac** [comment]
Is that the only way? Its going to be remarkably painful! But not mention, i think, complicated to squeeze so many diverse operations into one step function. :(

**Comment by KeDengMS** [comment]
It may not be as complicated as you thought. For example, you can write Recurrence(plus)(x) to do cumsum on sequence axis of x:
```
import cntk as C
import numpy as np
x = C.sequence.input_variable(())
s = C.layers.Recurrence(C.plus)(x)
s.eval([[0,1,2,3,4]])
```
and you'll get [0, 1, 3, 6, 10]. The cell function takes a form of func(prev_out1, prev_out2, ..., prev_outN, in), and return out1, out2, ... outN.

[Here](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/layers/blocks.py#L261) shows the cell implementation for LSTM. Tutorial 204 is also another example for that.

**Comment by delzac** [comment]
I understand what you are saying, that step functions are simple to write. But that's only if the step functions are simple.

Based on the suggested approach, i would need to combine read, lstm, gaussian distribution sampling, lstm and write operations all into one step function.

And my read and write operations are none trivial. They actually have an attention layer inside each of them.

To combine everything into one step function. omg.

**Comment by KeDengMS** [comment]
I see. To do what you want, we need to implement symbolic loop, or if the loop iteration is not too big just unroll the loop using Python.
