### ISSUE TITLE
CUDA 9.1 support

### ISSUE THREAD

**Issue by bencherian** [Microsoft/CNTK#2961]
Do you know when official CUDA 9.1 support is expected? On Windows, changing the solution to build using CUDA 9.1 seems to work ok and passes the Python tests. Are you just waiting for your internal build systems to update?

**Comment by KeDengMS** [comment]
CUDA 9.1 requires driver version 387+, while CUDA 9.0 is 384+. Yes there are some CI system updates required to support that.

**Comment by arijit17** [comment]
Hello! I use CNTK and TensorFlow in parallel and I need to install for Tnesorflow:

1. CUDA® Toolkit 9.0. 
2. The NVIDIA drivers associated with CUDA Toolkit 9.0.
3. cuDNN v6.0. 

If I install all the above, will by CNTK 2.4 work fine?

**Comment by Arkoprabho** [comment]
@arijit17 Try using dockers. It ensures the dependencies in one doesn't ruin that of others. I started using dockers recently. Its pretty easy to get started with it.

**Comment by ebarsoumMS** [comment]
CNTK 2.4 support cuDNN 7 not 6, TF 1.5 also support cuDNN 7. @bencherian any specific functionality from CUDA 9.1 you need?

**Comment by bencherian** [comment]
@ebarsoumMS I don't need CUDA 9.1 support. If there are plans to move to CUDA 9.1 though it would be nice to know, so we can test appropriate drivers ASAP.

**Comment by ebarsoumMS** [comment]
You can use CUDA9.1 driver with CUDA9.0, if you want to be ready for future update.

**Comment by bencherian** [comment]
Since there appears to be a CUDA 9.2 branch in progress I'm closing this.
