### ISSUE TITLE
Prepending singleton axis with expand_dims

### ISSUE THREAD

**Issue by jsundh** [Microsoft/CNTK#2965]
There doesn't seem to be a way of prepending a singleton axis using the new `expand_dims` operation.

If I understand correctly, the semantics of the `axis` parameter is __insert after__ (add at).
If it instead was __insert at__, that would allow prepending which I think would be pretty nice to have:

```python
i = C.placeholder((7, 5))
C.expand_dims(i, axis=0)  # [1, 7, 5] with "insert at"
```

I understand that such a change wouldn't be backwards compatible and therefore might not be possible to do.

**Comment by rnrneverdies** [comment]
I think it would work if you use -3 for axis value.

```
C.expand_dims(i, axis=-3)  # should be [1, 7, 5] 
```

**Comment by KeDengMS** [comment]
How about ` C.expand_dims(x, axis=-1-len(x.shape))`?

**Comment by jsundh** [comment]
That would work, since I guess you can always ensure that you know the tensor shape. The syntax might be slightly cumbersome, but that's a minor thing.

Thank you for the help.

**Comment by delzac** [comment]
The solution is to use `C.expand_dims(x, axis=C.Axis.new_leading_axis())`
