### ISSUE TITLE
How to correctly append a vector to a rank-3 tensor?

### ISSUE THREAD

**Issue by haixpham** [Microsoft/CNTK#2968]
Let's say I have an image (h, w, 3) and a code vector of length 46. I tried to append the vector to image along the depth dimension to have a new tensor (h, w, 49), as follows:

```python
x = C.input_variable((3, h, w))
v = C.input_variable(46)
new_v = v
for _ in range(h*w-1):
    new_v = C.splice(new_v, v)
new_v = C.reshape(new_v, (h,w,46))
new_v = C.transpose(new_v, (2, 0, 1))
y = C.splice(x, new_v, axis=0)
```

It works if h & w are small, e.g 25. When I replace h & w with bigger value, e.g. 100, this code leads to segmentation fault.

Is there a better and more efficient way to append a vector to a tensor?

Thanks

**Comment by haixpham** [comment]
I found another way that works:

```python
def broadcast_xy(input_vec, h, w):
    assert(h > 0 and w > 0)
    d = input_vec.shape[0]
    x = C.reshape(input_vec, (d, 1, 1))
    t = numpy.zeros((d, h, w), dtype=np.float32)
    y = C.constant(t)
    z = C.reconcile_dynamic_axes(y, x)
    z = z + x
    return z

x = C.input_variable((3, h, w))
v = C.input_variable(46)
new_v = broadcast_xy(v, h, w)
y = C.splice(x, new_v, axis=0)
```

Still, if anyone has any better idea, please share with us. I will leave this issue open for now.

**Comment by KeDengMS** [comment]
Maybe this?
```
C.swapaxes(C.splice(C.swapaxes(x, 0, 2), y, axis=2), 0, 2)
```
