### ISSUE TITLE
Let the dilation parameter in the convolutional layer to be trainable

### ISSUE THREAD

**Issue by mislulu** [Microsoft/CNTK#2982]
Hello everyone ,
I am try to use the trainable dilated convolution to improve my neural network architecture. The dilation parameter in a convolutional layer is a fixed number. How can I let the dilation parameter to be trainable and update after each training iteration? Should I define a userFunction by myself in python? Can anyone give some hints or example?  
Thanks for your kindness!

**Comment by jeandebleau** [comment]
the dilation parameter is an integer value and has bounds constraints. You can currently not directly optimising this type of variable during the training.

Most of the time such parameters are seen as hyper parameters that you can in fact optimise using grid search or other related techniques. Take a look at cntkhypertune, maybe you will find something intersting there.

**Comment by mislulu** [comment]
Thanks for your suggestion.  I just want to define a convolution function using userFunction in python by myself. Then let the dilation parameter to be a float and get training in the same way as the weights and bias. Do you this this idea is unreliable ? As I am a beginner to CNTK and deep learning, so I have such an idea.

**Comment by ebarsoumMS** [comment]
When you change the dilation parameters, you are changing the effective kernel size. Which mean that the shape inference will change and the output size might vary.
