### ISSUE TITLE
Version number shows 0.0.0 after build

### ISSUE THREAD

**Issue by LinkeyLeo** [Microsoft/CNTK#2983]
[](url)
![screenshot from 2018-02-23 18-04-22](https://user-images.githubusercontent.com/10334184/36588769-17a3327e-18c4-11e8-9d86-d1ef5d4a1460.png)

**Comment by leinxx** [comment]
Do you have a solution now>?

**Comment by manikjindal** [comment]
Can you share steps you followed to build?

**Comment by LinkeyLeo** [comment]
just pull the repo, rm the old build except the config.cmake file, and run make.
previous upgrade like this is as normal.

while it works well, but the version number makes my confused.

**Comment by thiagocrepaldi** [comment]
A new versioning mechanism was implemented on the 'configure' script, so you have to regenerate your Config.Make as opposed to re-use it across CNTK versions

**Comment by LinkeyLeo** [comment]
got it, thanks for reply
