### ISSUE TITLE
In what extent is this project related to Java ?

### ISSUE THREAD

**Issue by MickaelBaye** [Microsoft/CNTK#2984]
Hello,

It seems this project has a "Java" tag in his description.
The consequence is that the project appears in Java topic of GitHub : [here](https://github.com/topics/java).
I'm trying to figuring in what extent is related to Java but without success.
I'm probably missing something.

So my questions are : 
 * In what extent is this project related to Java ?
 * Is the "Java" tag a mistake ?

Regards,

**Comment by KeDengMS** [comment]
CNTK has [java bindings](https://github.com/Microsoft/CNTK/tree/9ce69f645574644259281192d8c097b32ffebf35/bindings/java/Swig). Please take a look at an Java example [here](https://github.com/Microsoft/CNTK/blob/073bf1d57995a6bad6e37c70e73db0a4a6027503/Tests/EndToEndTests/EvalClientTests/JavaEvalTest/src/Main.java).
