### ISSUE TITLE
How to generate a seq with specific length by UnfoldFrom()

### ISSUE THREAD

**Issue by ZaberKo** [Microsoft/CNTK#2985]
I want to call `unfold(initial_state,dynamic_axes_like)` to generate a sequence with a given length, like length 2. But seems there is no way to directly do that, and it mast need the `dynamic_axes_like` parameter which i don't know how to feed.

`unfold = UnfoldFrom(H_A_gru_cell)`

**Comment by KeDengMS** [comment]
Please take a look at [this test](https://github.com/Microsoft/CNTK/blob/9ce69f645574644259281192d8c097b32ffebf35/bindings/python/cntk/layers/tests/layers_test.py#L197) that may help you understand the usage.

**Comment by ZaberKo** [comment]
@KeDengMS  How can i create a instance of sequence by myself (for example, create a sequence variable from a ndarray)

**Comment by KeDengMS** [comment]
You may use InferredDimension for static axis in the input variable, while sequence length is automatically taken from input data. For example:
```
import cntk as C
import numpy as np
x = C.sequence.input_variable(shape=(C.InferredDimension))
y = C.layers.Recurrence(C.layers.LSTM(10))(x)
v = y.eval(np.random.rand(16, 100, 20)) # 16 is the batch size, 100 is the sequence length, and 20 is the input dimension
```
