### ISSUE TITLE
CNTK 2.4 Python 3.5 on JupyterLab

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#2991]
Fwiw, while looking for a better Python IDE I stumbled across the JupyterLab and got it working with CNTK 2.4 using Python 3.5 by just installing the lastest JupyterLab 0.31.8 beta release and launching from the Tutorials folder via "jupyter lab".  I only tested on a few tutorials and since its in beta, backup your notebooks.

![image](https://user-images.githubusercontent.com/8396992/36684556-ad69878c-1aee-11e8-9fc0-c1d4710bfea6.png)

**Comment by jaliyae** [comment]
Thank you for sharing this with us.
