### ISSUE TITLE
How can I get the init sequence after the 'unpack' operation?

### ISSUE THREAD

**Issue by NoneWait** [Microsoft/CNTK#2993]
Hi,
I unpack one sequence ( [#,c] [100] ) to ( [#] [*=c, 100] ) ， and now I want to back to the init shape ( [#,c] [100] ) , what should I do?

Thanks.

**Comment by KeDengMS** [comment]
You may use [to_sequence](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.to_sequence) or [to_sequence_like](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.to_sequence_like).
