### ISSUE TITLE
Is is possible to peek inside 'block' functions?

### ISSUE THREAD

**Issue by fwaris** [Microsoft/CNTK#2995]
I have two supposedly equivalent LSTM models - one constructed using .Net API (by mimicking Python code) and the other using Python's (high-level) API.

The two models train differently - the Python model continues to reduce loss after 10 epochs but the .Net model plateaus at a higher loss for the same training time.

I tried to understand any significant differences between the two models by plotting the graphs of both models. The problem is that for the Python model the LSTM layer is an opaque 'block' and I cant really compare it the equivalent set of connections in the .Net model.

Is there a way of plotting the subgraph of the just a block function?

For reference, the two models are attached.

.Net graph:

![l_fs_m bin](https://user-images.githubusercontent.com/289968/36782719-c9aa18a8-1c47-11e8-959e-30689800e1c9.png)

Python graph:
![l_py_m bin](https://user-images.githubusercontent.com/289968/36782726-cf24b3ce-1c47-11e8-98fc-c4b95a4a08e1.png)

**Comment by KeDengMS** [comment]
In Python you may peek inside block function with [depth_first_search](https://cntk.ai/pythondocs/cntk.logging.graph.html#cntk.logging.graph.depth_first_search) with depth = -1. LSTM implementation is [here](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/layers/blocks.py#L261-L297).

As for your issue with .Net vs Python, please note that Python data is row-major and shape is reversed while C#/C++ uses column-major. For example, a input variable in Python with shape [#],(3,224,224) is treated as a column-major tensor of (224, 224, 3, #) in storage for C#/C++. Similar for parameters and constants, and times operands are switched too.
