### ISSUE TITLE
Language Identification by sequence

### ISSUE THREAD

**Issue by simplybarca** [Microsoft/CNTK#2996]
I am new to cntk, I would like to do some language identification by training a neural network using a sequence of phonemes. I don't need to know what is actually being said but I want to classify it using sequence in a way similar to SVM. is it possible to do so in CNTK.

**Comment by KeDengMS** [comment]
We don't have examples/tutorials for this. Please try implement your model in CNTK and let us know if there are any blocking issues.

**Comment by arijit17** [comment]
@simplybarca which paper are you trying to implement?

**Comment by simplybarca** [comment]
I am not trying to implement a paper I am doing my own researd and I have produced a sequence of phonemes for my dataset and I want test n-gram sequence classification  using neural networks.

**Comment by KeDengMS** [comment]
No actionable work items with this issue, closing for now.
