### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/CNTK#30]
[Extra null pointer checks are not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [BaseMatrix::Clear](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/Math/CommonMatrix.h#L314 "BaseMatrix::Clear function")
* [KaldiSequenceTrainingDerivative](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/Readers/Kaldi2Reader/KaldiSequenceTrainingDerivative.cpp#L40 "Destructor for KaldiSequenceTrainingDerivative")
* [HTKMLFReader](https://github.com/Microsoft/CNTK/blob/2462647f625213ffdd3ec97d3290c1f9a31d44f8/Source/Readers/Kaldi2Reader/HTKMLFReader.cpp#L668 "Destructor for HTKMLFReader")

**Comment by frankseide** [comment]
Fixed--thanks! Will land soon.
