### ISSUE TITLE
Is it possible to train a model using sparse weights and dense input ?

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3017]
Hi,

I am trying to train a model on a training set and then dump the values of parameters and then remove certain parameters i.e, removing the connections of that parameter connecting a node.
My question is, "Is it possible to remove certain connection of a network and retrain the sparse network in cntk?"

Thank you

**Comment by KeDengMS** [comment]
For parameter values, you can set/get via [parameter.value](https://cntk.ai/pythondocs/cntk.variables.html#cntk.variables.Parameter.value). However, parameters in CNTK can only be dense.

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing.
