### ISSUE TITLE
dumpnode is crashing in convolutional network

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#302]
In MNIST example 02_Convolution when trying to dumpnode by using this config:

`MNISTDump = [
    action = "dumpnode"
]`

This error appears:

Warning: node name **AllNodes** does not exist in the network. dumping all nodes.

EXCEPTION occurred: Node 'conv1_act.convB' (LearnableParameter operation): Sample [1 x 1 x 16] is not a column vector or matrix (1D or 2D tensor).

[CALL STACK]
    > Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - Microsoft::MSR::CNTK::MatrixBase::  operator=
    - BaseThreadInitThunk
    - RtlUserThreadStart

**Comment by julienlopez** [comment]
I've run into the same issue. Is it a simple way to print the kernels the network learnt with the dumpnode command?

**Comment by yumesmile** [comment]
I have same issue. Do somebody know how to bypass this issue? Thanks

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
