### ISSUE TITLE
Python build requires MPI though mpi=no

### ISSUE THREAD

**Issue by melrobin** [microsoft/CNTK#3028]
CNTK fails to load in Python 2.  Troubleshooting further I found:
[melrobin@scorpion python]$ ldd _cntk_py.so  | grep mpi
        libmpi.so.20 => /usr/local/mpi/lib/libmpi.so.20 (0x00007f5a7f4b3000)
        libopen-rte.so.20 => /usr/local/mpi/lib/libopen-rte.so.20 (0x00007f5a50973000)
        libopen-pal.so.20 => /usr/local/mpi/lib/libopen-pal.so.20 (0x00007f5a5067f000)

cntk_gpu-2.4-cp27-cp27mu-linux_x86_64.whl was built from the make line

**Comment by melrobin** [comment]
Update to a more descriptive title.

**Comment by KeDengMS** [comment]
I suspect it's from [this line](https://github.com/Microsoft/CNTK/blob/master/bindings/python/setup.py#L214) in setup.py. As this line is not in Windows, maybe we can remove it from Linux. @thiagocrepaldi can you take a look?

**Comment by melrobin** [comment]
I did remove that line from setup.py, but unfortunately this did not fix the problem.

**Comment by melrobin** [comment]
I unzipped the wheel file and found:
ldd _cntk_py.so | grep mpi
        libmpi.so.20 => /usr/local/mpi/lib/libmpi.so.20 (0x00007f40a18bf000)
        libopen-rte.so.20 => /usr/local/mpi/lib/libopen-rte.so.20 (0x00007f4072d7f000)
        libopen-pal.so.20 => /usr/local/mpi/lib/libopen-pal.so.20 (0x00007f4072a8b000)

the MPI dependency is still in the main library
