### ISSUE TITLE
error C2220：treat warnings as errors - Object file is not generated (math_functions.h)

### ISSUE THREAD

**Issue by kingstarcraft** [Microsoft/CNTK#303]
I use MKL and VS2013 to bulid CNTK project with CUDA 7.5 in windows 8。when I open the project,the MathCUDA can not be open in VS2013.I modify the MathCUDA.vcxproj :
I replace CUDA_PATH_V7_0,CUDA 7.0.props,cublas64_70.dll.. cudart64_70.dll  and  CUDA 7.0 targets with CUDA_PATH_V7_5 ,CUDA 7.5.props, cublas64_75.dll...cudart64_75.dll and CUDA 7.5 targets 
After filnish this,I have successfully open the MathCUDA project.but when I bulid CNTK,errors arises:
error C2220：treat warnings as errors - Object file is not generated
(math_functions.h  (C:\...\CUDA\v7.5\include))
error MSB3721:command""....CUDA\v7.5\bin\nvcc.exe" ...."....MathCUDA\GPUTensor.cu""exited with code 2
I don‘t want to change the CUDA7.5 to CUDA 7.0,Is there any another way to solve the problem。

**Comment by kingstarcraft** [comment]
I have solved this problem.
In MathCUDA property/CUAD C/C++/Host/Additional Compiler Options, change the /WX to /WX-.

**Comment by mahilleb-msft** [comment]
Closing, as your original problem was solved.
On a related note, today we've changed the way how CNTK supports MKL and merged it into master. Check these set up instructions, specifically in the section on "MKL":
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux
Best, Mark
