### ISSUE TITLE
CNTK Running in Azure Function

### ISSUE THREAD

**Issue by rposener** [microsoft/CNTK#3030]
Hello,

I've been following along and seem to be getting this error running CNTK in an Azure Function (v1 targeting .net 4.6.1).

 ```c#
System.Runtime.InteropServices.SEHException : External component has thrown an exception.
   at CNTK.CNTKLibPINVOKE.Function__Load__SWIG_3(Byte[] jarg1,UInt32 jarg2,HandleRef jarg3)
   at CNTK.Function._Load(Byte[] buffer,UInt32 length,DeviceDescriptor computeDevice)
   at CNTKLibrary.CNTKLibraryManaged..ctor()
```

I have all the DLL's mentioned [here ](https://docs.microsoft.com/en-us/cognitive-toolkit/Archive/EvalDLL-Evaluation-on-Windows) in my bin directly, and logic to add that to the Environment Path.  I also have the app all running in only x64.  Here are the packages I have reference in my C# Function Project:

```xml
<packages>
  <package id="CNTK.CPUOnly" version="2.4.0" targetFramework="net461" />
  <package id="CNTK.Deps.MKL" version="2.4.0" targetFramework="net45" />
  <package id="CNTK.Deps.OpenCV.Zip" version="2.4.0" targetFramework="net45" />
  <package id="Microsoft.Research.CNTK.CpuEval-mkl" version="2.4.0" targetFramework="net461" />
</packages>
```

any advice would be greatly appreciated.

**Comment by rposener** [comment]
I eventually got this working in Azure Functions.  For anyone else looking to do the same, the only way I could get it resolved, was to manually add the C++ DLL's to my solution, and add the DLL's to the Path.  Unfortunately, the example on [this](https://docs.microsoft.com/en-us/cognitive-toolkit/Evaluate-a-model-in-an-Azure-WebApi) page does not work the same in Azure Functions.  Here is how I worked around it, and got it running:

```c#
            string cntkPath = @"D:\home\site\wwwroot\bin\";
            string openCvPath = @"D:\home\site\wwwroot\dll\x64\";
            var paths = pathValue.Split(';').ToList();
            paths.Add(cntkPath);
            paths.Add(openCvPath);
            pathValue = String.Join(";", paths.Distinct().ToArray());
            pathValue += ";" + cntkPath;
            Environment.SetEnvironmentVariable("PATH", pathValue);
```

If anyone has advice to improve how this works in Azure functions, or how to improve the packages (so this pathing is not necessary, would be huge help.

Thanks!

**Comment by KeDengMS** [comment]
Thanks for reporting the issue and share your solution. We will check if there are any update in docs needed for running CNTK in Azure WebAPI.

**Comment by douglas125** [comment]
I would like to evaluate CNTK models (and use other CNTK C# tools) using Azure Functions as well and I cannot. Just being able to upload the .model file (or load from Storage) and evaluate it would already help a lot.

I was hoping to create a project.json file containing:

{
  "frameworks": {
    "net46":{
      "dependencies": {
        "CNTK.CPUOnly": "2.5.1"
      }
    }
   }
}

and have Azure Funtion restore packages and dependencies so I could just include "using CNTK" as normal, but this does not work. I was not able to reproduce @rposener solution.

Thanks for the help.

**Comment by KeDengMS** [comment]
Thanks for the suggestions. We'll look into a way to make CNTK easier to use in Azure Functions.

**Comment by Madrawn** [comment]
For anyone stumbling on this after me
            string pathValue = System.Environment.GetEnvironmentVariable("PATH");
            string cntkPath = @"D:\home\site\wwwroot\bin\";
            string openCvPath = @"D:\home\site\wwwroot\dll\x64\";
            var paths = pathValue.Split(';').ToList();
            paths.Add(cntkPath);
            paths.Add(openCvPath);
            pathValue = string.Join(";", paths.Distinct().ToArray());
            pathValue += ";" + cntkPath;
            System.Environment.SetEnvironmentVariable("PATH", pathValue);

This is copy&past-able. The @rposener code was missing the declaration of "pathValue" and "Enviroment" should be "System.Enviroment" to work out of the box.
