### ISSUE TITLE
Cann't training Fast RCNN on my own dataset.

### ISSUE THREAD

**Issue by KirylLapouski** [Microsoft/CNTK#3032]
When i execute ` run_fast_rcnn.py` that happens.
![image](https://user-images.githubusercontent.com/29763516/37251883-35b2725e-2529-11e8-8f89-a0dda216efeb.png)
This is my config file

```
from easydict import EasyDict as edict

__C = edict()
__C.DATA = edict()
cfg = __C

__C.DATA.DATASET = "YourDataSet"
__C.DATA.MAP_FILE_PATH = "../../DataSets/custom"
__C.DATA.CLASS_MAP_FILE = "class_map.txt"
__C.DATA.TRAIN_MAP_FILE = "train_img_file.txt"
__C.DATA.TEST_MAP_FILE = "test_img_file.txt"
__C.DATA.TRAIN_ROI_FILE = "train_roi_file.txt"
__C.DATA.TEST_ROI_FILE = "test_roi_file.txt"
__C.DATA.NUM_TRAIN_IMAGES = 44
__C.DATA.NUM_TEST_IMAGES = 15
__C.DATA.PROPOSAL_LAYER_SCALES = [4, 8, 12]

__C.roi_min_side_rel = 0.04

__C.roi_max_side_rel = 0.4

__C.roi_min_area_rel = 2 * __C.roi_min_side_rel * __C.roi_min_side_rel

__C.roi_max_area_rel = 0.33 * __C.roi_max_side_rel * __C.roi_max_side_rel

__C.roi_max_aspect_ratio = 4.0

```
I use VOTT to mark my images, and copy output of VOTT to `$CNTK_ROOT$\Examples\Image\DataSets\custom`, After run script `$CNTK_ROOT$\Examples\Image\Detection\utils\annotations\annotations_helper.py`, was generated 5 files:`class_map`, `test_img_file`, `test_roi_file`, `train_img_file`, `train_roi_file`.
Grocery example works fine.
Why it does not use trainig data? Why program informs only about evulating model, but not about training(you can see it on screenshot)?

**Comment by kyoro1** [comment]
Can you check the contents of "Grocery" `$CNTK_ROOT$\\Examples\Image\DataSets\Grocery`?
You may find `positive`, `negative` and `testImages` folders, and will find some images for each folder.

Then, how is your status for your dataset?

I'm not sure the above helps you, but would like to check them at first.

**Comment by KirylLapouski** [comment]
HI, this is Grocery.
![image](https://user-images.githubusercontent.com/29763516/37271504-3b47c1f4-25e4-11e8-97c5-91d113da7b0b.png)
It is custom.
![image](https://user-images.githubusercontent.com/29763516/37271520-49c8cfc0-25e4-11e8-9eee-a12628254bb4.png)
![image](https://user-images.githubusercontent.com/29763516/37271565-7033a14e-25e4-11e8-8a40-fc53d3c03b0b.png)

**Comment by spandantiwari** [comment]
I believe you may have already run training once before. The logic in training script FastRCNN_train.py  is such that training is executed only if a previous trained model does not exist. See this line: 
https://github.com/Microsoft/CNTK/blob/37854b4abbcb906e7e030332a080b71487e098ad/Examples/Image/Detection/FastRCNN/FastRCNN_train.py#L258 

Try deleting/moving the previously written model and then running again.

**Comment by KirylLapouski** [comment]
I already delete this model early, but it does not help. I find this implementation https://bhrnjica.net/2018/02/11/step-by-step-cntk-object-detection-on-custom-dataset-with-python/
