### ISSUE TITLE
How can i make a custom config file for FasterRCNN?

### ISSUE THREAD

**Issue by springkim** [Microsoft/CNTK#3037]
Hello, CNTK developers.

I want run FasterRCNN as other networks.(e.g ResNet, Inception)

But, there is no example on this problem.

In this page [https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/download_model.py](https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/download_model.py) shows existing base models. I think i will use this models on FasterRCNN.

For now, I can run AlexNet, VGG16, VGG19.

Please, Let me know how can i use other network on FasterRCNN.

**Comment by spandantiwari** [comment]
We have examples for Alexnet and VGG networks. For other base networks you will have to make your config file. See the VGG config for example: https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Detection/utils/configs/VGG16_config.py

You will have to do something similar and provide details such as which intermediate layer to use.
