### ISSUE TITLE
How to feed new image to ConvNet CIFAR10 and get result?

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/CNTK#3038]
I've successfully run `Examples\Image\Classification\ConvNet\Python\ConvNet_CIFAR10.py` but I'm not sure how to get the classification for a new image.

I think the first step is to get the features of the new image to get something similar to what is in `Examples\Image\DataSets\CIFAR-10\Test_cntk_text.txt`? For that should i run `Examples\Image\FeatureExtraction\FeatureExtraction.py`?

Is there some guide to follow?

Thanks in advance.

**Comment by KeDengMS** [comment]
Please check out the [how-to-feed-data manual](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_feed_data.ipynb).
