### ISSUE TITLE
Pruning weights using CNTK

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3039]
I am trying to prune certain weights and retrain the network. So far I am able to get the values of weights and make it zero. Now I would like to eliminate those weights from the network and retrain it?  Is there any way I can do it using CNTK? Please let me know
Thanks

**Comment by KeDengMS** [comment]
Please check if the [network optimization manual](https://github.com/Microsoft/CNTK/blob/a40285c90cd3a5d2d131b73d514d3417ae687322/Manual/Manual_How_to_use_network_optimizations.ipynb) fits your need.

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing.

**Comment by vidyatshetty** [comment]
@KeDengMS   I looked into the manual you mentioned. It is a great guide which helps one to optimize the network but I think it doesn't fit my need. I have a weight matrix which has lot of zero in it. I would like it remove those zeros in other words converting dense weight matrix to sparse and then use that weight matrix to retrain the network. Is there any way I can do it using CNTK?. If you could suggest some CNTK examples or any material I could look into that would be really helpful.
Thanks

**Comment by KeDengMS** [comment]
CNTK parameters can only be dense. You can write a [UserLearner](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_use_learners.ipynb) to prune the weights in training, after model is updated with gradient.

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing. This really helped me.
Thanks

**Comment by vidyatshetty** [comment]
@KeDengMS   Thank you for writing. This really helped me.
Please correct me if I am wrong. After pruning the weights of the trained model I would like to retrain the model because when I evaluated the network after pruning without retraining the accuracy of the network was too low. I am confused when you say prune the weights in training? Please let me know if I am forgetting something important.
Thanks

**Comment by KeDengMS** [comment]
If you write a UserLearner, you can decide when and how frequently you prune the weights, right?

**Comment by vidyatshetty** [comment]
@KeDengMS  Yes I got it now. I will follow your suggestion. Thanks for helping me with this.
Thanks
