### ISSUE TITLE
Data parallelism and very large training data set

### ISSUE THREAD

**Issue by shane6lee** [Microsoft/CNTK#305]
I understand that CNTK supports data parallelism on a minibatch basis. Would this allow training a model using a very large data set? I try using an 8.5 G data file in the CNTKTestFile format with MPI on a 3-node cluster (one with 24 G RAM and the other two with 32 G each) and run out of memory. On a single server with 64 G of memory, it uses more than 52 G of memory. How should I configure this?

**Comment by frankseide** [comment]
Quick note upfront: For the speech-recognizer training of Skype Translator, I used 1.4G _samples_, each of which being 160 bytes, ~220 GB of float features. That was using an old version of HTKMLFReader, which efficiently pages data in chunks, such that RAM usage would be a few 10 GBs. Colleagues have setups with over twice that much. So your data set size is not at all outrageous.

Would you mind sharing your specific reader config?

@mahilleb-msft, once we have a response, would you mind having a look at the config & check whether the CNTKTextReader is correctly configured for chunking and distributed reading?

**Comment by jack-unisound** [comment]
the same qustion, I use 78G feats of Kaldi format and run out of memory, my server with 32G of memory.  config file error ?  The error info is:
attempt: releasedata: called when data is not memory, retrying 2-th time of 5 ...
attempt: releasedata: called when data is not memory, retrying 3-th time of 5 ...
attempt: releasedata: called when data is not memory, retrying 4-th time of 5 ...
attempt: releasedata: called when data is not memory, retrying 5-th time of 5 ...
EXCPTION occurred: releasedata: called when data is not memory

How to solve it?

**Comment by frankseide** [comment]
Could you check your setting of 'randomize'? That can be set to "none", "auto", or a numeric randomization-window width. The window width determines memory usage. If you say "auto" it really means "no window, load all into RAM." For speech tasks, I usually use a randomization window of +/-24h, corresponding to 48*3600*100. Could you try:
```
randomize = 17280000
```

**Comment by mahilleb-msft** [comment]
Also, is the data even found? With chunks not found, we would produce the same message, I think, which is something we still need to fix.
Can you double-check your file paths?

**Comment by shane6lee** [comment]
This is what my reader config looks like:
reader = [
	readerType = "CNTKTextFormatReader"
	file = "$DataDir$/cntk_big.txt"
	randomize=17280000
	input = [
		features = [
			dim = $dimension$
			format = "dense"
		]
		labels = [
			dim = 1
			format = "dense"
		]
	]
]

I understand now that I can use 'randomize' to enable chunking. How do I enable  distributed reading?

**Comment by mahilleb-msft** [comment]
@jack-unisound, sure, I'll close this one for now. Please open a new issue for any additional questions you might have.

Thanks, Mark
