### ISSUE TITLE
which pipeline used for distributed System in CNTK?

### ISSUE THREAD

**Issue by SoulDuck** [Microsoft/CNTK#3054]
hello, im new in cntk 

Google Tensorflow used grpc for communicating with each machine ,
but i don't know which pipeline used for distributed System in CNTK 
Can you let me know? 

and  Could you give me some reference or site about Example of Multi Mahcine , Multi GPU?
i already have been to this [site](https://docs.microsoft.com/en-us/cognitive-toolkit/Multiple-GPUs-and-machines) i Cannot find Multi Machine code example.

THANK YOU! :)

**Comment by jaliyae** [comment]
CNTK uses MPI as the communication mechanism for distributed training. To run a distributed training using MPI with more than one machine you can use MPI -host option or --hostfile options. For example, please have a look [here](https://stackoverflow.com/questions/45408699/openmpi-host-and-hostfile-options)
