### ISSUE TITLE
Modifying Variables values between models

### ISSUE THREAD

**Issue by csolorio** [Microsoft/CNTK#3058]
Hi, everyone

I need some help to find a way to modify a _cntk_ variable value that is the output of a model and the input of another(s). Let me detail:

Model 'A' has an input tensor of X shape and outputs a tensor of Y shape.
Model 'B' has an input tensor of Z shape and its output shape doesn't matter. 
While training the A model, the loss functions should use the output of model 'B' (which parameters are fixed). Output tensor shape is irrelevant since I apply any reduction operation with no problem, but what I want to do is to use the model B with inputs of Y shape. I can pad any tensor with X shape using numpy operators but how can I plug such transformation in the variable that is mapped in the model B input? 

Any help is appreciated!

**Comment by jaliyae** [comment]
I am not sure if I understand your requirement completely. Could you have a look at the [GAN example](https://cntk.ai/pythondocs/CNTK_206A_Basic_GAN.html) and see if the 'clone' method would help your situation.

**Comment by csolorio** [comment]
I'm working on a similar tutorial for tests (https://cntk.ai/pythondocs/CNTK_302B_Image_Super-resolution_Using_CNNs_and_GANs.html). The problem in the tutorial is that the output shape of the generator model is 224 x 224, coincidentally the input of the VGG has the same shape. But, If I want to use another generator model with different output shape? I can pad the output with zeros but... How can I do that exactly?

**Comment by jaliyae** [comment]
Could you have a look at the [Pad](https://cntk.ai/pythondocs/cntk.ops.html?highlight=pad#cntk.ops.pad) operation.

**Comment by csolorio** [comment]
Thanks! Just what I need!
