### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wyjzz** [Microsoft/CNTK#306]
what happened?

configparameters: LSTM-NDL_R.cntk:traceLevel=1
<<<<<<<<<<<<<<<<<<<< PROCESSED CONFIG WITH ALL VARIABLES RESOLVED <<<<<<<<<<<<<<<<<<<<
command: speechTrain
precision = float
CNTKModelPath: ../Output/Models/cntkSpeechLSTM.dnn
CNTKCommandTrainInfo: speechTrain : 4
CNTKCommandTrainInfo: CNTKNoMoreCommands_Total : 4
CNTKCommandTrainBegin: speechTrain
NDLBuilder Using CPU
Reading UCI file ../Data/SimpleDataTrain.txt
CNTK: Caught Win32 exception 0xc0000005: Access violation.

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
