### ISSUE TITLE
Custom Function in Python on GPU

### ISSUE THREAD

**Issue by doggy1232** [Microsoft/CNTK#3060]
I have been looking around for a windows based deep learning library that would allow me to implement a custom function that runs on the GPU without building from source code. I choose CNTK because it was made by Microsoft themselves and because in the features list it said this

"Ability to add new user-defined core-components on the GPU from Python" <- Exactly what I need.

I have been looking around a little and all I can find is examples of creating a UserFunction with numpy operations on CPU. I was wondering if there is any example of creating a GPU based user function that could be programmed through CUDA.

An example in C++ would be fine aswell. Or just an explanation of how this might be accomplished would be welcomed.

Thanks! :)

**Comment by doggy1232** [comment]
This is the first time I have ever asked a question on a forum after years of programming. I regret it.
Solved it.

If anyone in the future wants to know how just ask.

**Comment by BMillikan73** [comment]
Can you share how you created a CNTK GPU operation?  I'm trying to do the same.  There seems to be limited information on how to build a user-defined GPU op.

**Comment by DPJep** [comment]
@doggy1232 Can you share how you managed to do this?
