### ISSUE TITLE
CNTK proto\onnx\defs\activation\defs.cpp C2220 Compiled  error 

### ISSUE THREAD

**Issue by dataangel** [Microsoft/CNTK#3062]
1>proto\onnx\defs\activation\defs.cpp : error C2220: 警告被视为错误 - 没有生成“object”文件
1>proto\onnx\defs\activation\defs.cpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
CNTKv2LibraryDll

**Comment by spandantiwari** [comment]
Can you generate the error stack in English and share it?

**Comment by dataangel** [comment]
New text can be solved

**Comment by spandantiwari** [comment]
> New text can be solved
I don't understand. If could you convert the error stack in English, then we can start to help you.

**Comment by dataangel** [comment]
Problem has been solved character problem

**Comment by spandantiwari** [comment]
Glad to hear it. Thanks.
