### ISSUE TITLE
cannot identify cuda 9.1 on windows install

### ISSUE THREAD

**Issue by gallybaba** [Microsoft/CNTK#3068]
Installation of NVidia CUDA 9.0 is a pre-requisite before installation can continue

I get this while running .\DevInstall.ps1 -AnacondaBasePath "F:\anaconda3" -PyVersion 36
from devinstall\windows

I do have cuda 9.1 installed under F:\cuda\toolkit

In the https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-with-script-on-windows it mentions cuda variables are set by cuda windows installer. 

Any help please?

**Comment by bencherian** [comment]
You need to use CUDA 9.0. CUDA 9.1 is not supported yet.

**Comment by KeDengMS** [comment]
Yes CNTK supports CUDA 9.0 only.

**Comment by gallybaba** [comment]
thanks. any eta as to when? I would love to contribute.

**Comment by mirekphd** [comment]
FYI, your have missed an entire version of CUDA, as there is already next one out, CUDA 9.2, stable on Ubuntu 16.04 and experimental on 18.04.
