### ISSUE TITLE
More documentation, examples, demos, and comments for CNTK please!

### ISSUE THREAD

**Issue by shyamalschandra** [Microsoft/CNTK#307]
Hi,

Would you please be able to provide more explanation in the comments for the CNTK code (or at least the papers that are relevant to the underlying theory in the docs on the website), similar to CNTK, for the CNTK tutorials and the general documentation? I have the code running with the binary installation (not the source installation) so I need a way to guide my intuition so that i can build complex deep layered models.

Thanks!

Best regards,
Shyamal Chandra

**Comment by mahilleb-msft** [comment]
Can you check the current documentation / samples / tutorials? Much has been added in the > 15 months. If you find something specific that's missing, please submit a new issue. Thanks!
