### ISSUE TITLE
How to restrict certain parameters from updating while training?

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3071]
I have well trained model and I would like to edit the weights of the model and retrain the model.
while retraining I want only few of the selected parameters(weights) to update and all other weights should be as it is (in other words, the should not be updated) Is there any way I can  restrict weights from updating while retraining using CNTK? Any suggestion would help.
Thanks

**Comment by bencherian** [comment]
Only include the parameters you wish to update in the learner.

**Comment by vidyatshetty** [comment]
@bencherian  Thank you for writing. I understood your suggestion but I am quiet confused how to pass only few parameters to learner?!
This is how usual learner I am using is,
learner = C.sgd(p.parameters ,lr = lr_schedule)
How to include the required parameters only?Could you please give me more details on that ?
Thank you

**Comment by KeDengMS** [comment]
p.parameters is a python list. You can use following code to filter the parameters passed to learner:
```
learner = C.sgd([p for p in p.parameters if your_condition(p)], lr = lr_schedule)
```

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing. That was perfectly something I was looking for. Thank you for saving my time.

**Comment by vidyatshetty** [comment]
@KeDengMS  I followed your instructions and filtered the parameters passed to learner.
`learner = C.sgd([a for a in (p.parameters) if (a.shape == (1000, 20) or a.shape == (1000,1000) or a.shape == (1000,1000) or a.shape == (39,1000)) for(x,y), a in np.ndenumerate(a.value) if(a != 0)] , lr = lr_schedule)`

I got the following error, 

![cntk_error](https://user-images.githubusercontent.com/13535872/38154738-5c776e98-3439-11e8-90ee-f15746713585.PNG)

I believe learner expects the python list as input but I am filtering the parameters and passing one parameter at a time.
Please  let me know what i am missing.
Thank you

**Comment by KeDengMS** [comment]
Can you inspect the list items in the parameter lists passed to sgd? All should be of type Parameter.

**Comment by vidyatshetty** [comment]
@KeDengMS  I inspected the list items in the parameter lists passes to sgd,it is as shown below
![cntk_error_1](https://user-images.githubusercontent.com/13535872/38157158-cd5b860c-3449-11e8-94bb-bd23f194bc07.PNG)

the above values are value of 'a' in the below code,
`learner = C.sgd([a for a in (p.parameters) if (a.shape == (1000, 20) or a.shape == (1000,1000) or a.shape == (1000,1000) or a.shape == (39,1000)) for(x,y), a in np.ndenumerate(a.value) if(a != 0)] , lr = lr_schedule)`

**Comment by KeDengMS** [comment]
Seems not right. Should be a list of Parameters not values. if p is a CNTK function, p.parameters is a list of all parameters in the function.
If you are trying to update only the non-zero values in parameter, you should write your own [UserLearner](https://github.com/Microsoft/CNTK/blob/master/Manual/Manual_How_to_use_learners.ipynb).

**Comment by vidyatshetty** [comment]
@KeDengMS Thank you for writing. I tried writing my own UserLearner and encountered errors so thought of doing it the other way around which seems not right as you suggested. I will work on my own UserLearner 
Thanks

**Comment by KeDengMS** [comment]
Assuming you only want to update parameters above certain threshold:
```
update_mask = C.greater(C.abs(param), threshold)
self.new_parameter[p_shape] = param - eta * self.grad_input[p_shape] * update_mask
```

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing. this was really helpful.
do the above works for learner implemented as a python class or only works with UniversalLearner?
Please let me know
Thank you
