### ISSUE TITLE
installation error on windows 7:fatal error during script execution

### ISSUE THREAD

**Issue by MichaleWong** [Microsoft/CNTK#3074]
I encountered a problem in beginning , the error look like this:
a fatal error during script execution
System.Management.Automation.RuntimeException:.... "Is64BitProcess"......
....
....
error during install operation

Do you know how to fix it? Is that due to my windows  7, does CNTK support win7? I haven't seen any requirement on system version on cntk website

**Comment by MichaleWong** [comment]
![errorcntk](https://user-images.githubusercontent.com/6574543/37958982-823a9d82-31e4-11e8-918c-bd72a1d19a75.JPG)

**Comment by KeDengMS** [comment]
Are you running devInstall.ps1 to build from source for Windows 7? If not, please follow the directions [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-with-script-on-Windows). You may need to upgrade PowerShell version.

**Comment by MichaleWong** [comment]
@KeDengMS  yeah, you're right ,I fix it after update powershell , thank you so much

**Comment by DashHash** [comment]
hi first,
i wanna to ask you about the solution for your problem i faced the same problem while installing cntk
and i didn't find any solution for my problem so, please help me in a clear steps to solve this problem and thank you
