### ISSUE TITLE
C# API Example is too old

### ISSUE THREAD

**Issue by LinkeyLeo** [Microsoft/CNTK#3076]
I follow the cs example then think maybe the api is too old, while after view the library from object browser, I think you should update the C# example

**Comment by KeDengMS** [comment]
Please provide more specific feedback on which examples that use old API.

**Comment by LinkeyLeo** [comment]
The CSExample use the apis location in namespace CNTK, while the full apis are located under CNTK.CNTKLib

**Comment by liqunfu** [comment]
@LinkeyLeo CNTK.CNTKLib is a C# class that includes many methods that do not belong to any C# classes in CNTK name space. It also includes all APIs that are directly exposed by SWIG. 
I think your concern is many about CNTK C# API in general which needs to match Python API w.r.t. usability and matureness. I fully agree with you on this. There is an issue regarding this.    
https://github.com/Microsoft/CNTK/issues/2515
