### ISSUE TITLE
Crop layer

### ISSUE THREAD

**Issue by Hammatt** [Microsoft/CNTK#3085]
Hi, I'm trying to convert a network originally created using cafe to CNTK. I'm having trouble locating an equivalent layer for the [crop](http://caffe.berkeleyvision.org/tutorial/layers/crop.html) layer.

Is there an appropriate layer or will this have to be done some other way?

Thanks.

**Comment by KeDengMS** [comment]
Please try the [crop ops](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.crop_automatic).

**Comment by Hammatt** [comment]
Thanks! [crop_automatic](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.crop_automatic) looks like it was exactly what I was after!

**Comment by Hammatt** [comment]
Hey, sorry to re-open this but I'm getting an error:
```
Validating --> Crop1871 = Crop (ReLU483, ReLU1727) : [26 x 26 x 256 x __noSequenceAxis1], [48 x 24 x 1 x __noSequenceAxis1] -> [48 x 24 x 256 x __noSequenceAxis1] FAILED
Traceback (most recent call last):
  File ".\train.py", line 163, in <module>
    classify_mnist()
  File ".\train.py", line 117, in classify_mnist
    trainer.train_minibatch(data)
  File "E:\Anaconda3\lib\site-packages\cntk\train\trainer.py", line 181, in train_minibatch
    arguments, device)
  File "E:\Anaconda3\lib\site-packages\cntk\cntk_py.py", line 2975, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: Node does not support affine transform for cropping.

[CALL STACK]
    > CNTK::TrainingParameterSchedule<double>::  GetMinibatchSize
    - CNTK::TrainingParameterSchedule<double>::  GetMinibatchSize (x7)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD (x3)
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
```

I'm trying to crop the output of a Convolution2D layer, can this be done?

**Comment by spandantiwari** [comment]
@Hammatt - can you share your code that throws this error. If you can repro using just conv and crop, that would be helpful for quick debugging on our end.

**Comment by Hammatt** [comment]
Hey @spandantiwari , thanks for getting back to me. I've been doing some trial and error and have found that this error goes away when `pad=False` for the Convolution2D layer that it is trying to crop. I believe that everything's related to the resolution of the data I'm working with being too low for the size of the network, it works fine on a cut down small version of my network.

Thanks,
Just to state the answer to the question that I asked when I re-opened: Yes, it is possible to crop the output of a Convolution2D layer.

**Comment by spandantiwari** [comment]
Thanks for letting us know.
