### ISSUE TITLE
CNTK 2-5 script installation on Windows 10 64 bit error

### ISSUE THREAD

**Issue by debadeepta** [Microsoft/CNTK#3089]
trying to install 2.5 on Windows 10 via the script option. See terminal output below. Seems like it is not able to download the python wheel file. I tried to manually download the wheel from the url but that gave me the following error message: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

--------------------
> install.bat -AnacondaBasePath C:\ProgramData\Anaconda3

CNTK Binary Install Script

This script will setup CNTK, the CNTK prerequisites and the CNTK Python environment onto the system.
More help can be found at:
  https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Binary-Script

The script will analyse your machine and will determine which components are required.
The required components will be downloaded in [C:\Users\dedey\Documents\CNTK-everything\CNTK-2-5-Windows-64bit-GPU\Scripts\install\windows\ps\InstallCache]
Repeated operation of this script will reuse already downloaded components.

 - If required VS2015 Runtime will be installed
 - If required MSMPI will be installed
 - Anaconda3 will be installed into [C:\ProgramData\Anaconda3]
 - A CNTK-PY35 environment will be created or updated in [C:\ProgramData\Anaconda3\envs]
 - CNTK will be installed or updated in the CNTK-PY35 environment

1 - I agree and want to continue
Q - Quit the installation process

1
Determining Operations to perform. This will take a moment...

The following operations will be performed:
 * Setup CNTK PythonEnvironment 35
 * Setup/Update CNTK Wheel 35
 * Create CNTKPY batch file

Do you want to continue? (y/n)
y
Performing download operations
Download operations finished

Performing install operations
Setup/Update with wheel: https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl. Please be patient....
Collecting cntk==2.5 from https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl
  HTTP error 404 while getting https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl
  Could not install requirement cntk==2.5 from https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl
Could not install requirement cntk==2.5 from https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl for URL https://cntk.ai/PythonWheel/GPU/cntk-2.5-cp35-cp35m-win_amd64.whl
You are using pip version 8.1.2, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

-------------------------
Update: I found that the whl urls listed on the doc page are just fine and can be downloaded. But the urls differ from what the script is generating. 

3.5 | CPU-Only | https://cntk.ai/PythonWheel/CPU-Only/cntk-2.5-cp35-cp35m-win_amd64.whl
-- | -- | --
  | GPU | https://cntk.ai/PythonWheel/GPU/cntk_gpu-2.5-cp35-cp35m-win_amd64.whl

---------------------------
Update: It seems the function WhlFileInfoFromVersionFile has the wrong reg exp. in line 117. It is ignoring the _gpu part which it should switch on based on the content of $cntkTarget. (I don't know enough powershell to fix this properly but on my local copy changing 'cntk-' to 'cntk_gpu-' resulted in the right url and successful installation.)

**Comment by addf400** [comment]
In path "cntk\Scripts\install\windows\ps", you can open install.ps1 file with a text editor
In line 117, you can see: 

                $cntkVersion = $cntkVersion -replace "^cntk\.", "cntk-"

just change it to 

                $cntkVersion = $cntkVersion -replace "^cntk\.", "cntk_gpu-"

the url just miss "_gpu".

**Comment by KeDengMS** [comment]
Thanks for the report. This bug has been [fixed](https://github.com/Microsoft/CNTK/commit/a5e0912a27dc3b306cde5860e6c5abca062caab3)
