### ISSUE TITLE
Structure a network into blocks

### ISSUE THREAD

**Issue by Arkoprabho** [Microsoft/CNTK#3091]
Is it possible to convert a network into specific blocks. e.g. the VGG network is split into blocks of convolution operation with similar sub-architecture. Now when I save this model to a png file using `cntk.logging.plot(vgg_model, filename='VGG.png')` the output is as shown here (saved the model from Keras for representation's sake)
![VGGModel](https://user-images.githubusercontent.com/16442535/38175309-1f97748a-35f8-11e8-983e-d3bb02fd7b9c.png)

Now this looks a tad bit clumsy. Can we restructure this into a way that combines the individual blocks into this larger block to represent the abstract operation that is undergoing inside the block.
To understand the problem better, one can draw an analogy between this and the name_scope feature in tensorflow, which when viewed in tensorboard is this expandable view, which shows the inner operations inside the scope.

**Comment by KeDengMS** [comment]
When you create the model in Python, you may wrap ops into blocks using as_block() or @C.BlockFunction. Some pretrained models did not do that, if they are converted or trained from BrainScript.
