### ISSUE TITLE
OMP error when using matplotlib 

### ISSUE THREAD

**Issue by min6434** [Microsoft/CNTK#3092]
When I use CNTK and matplotlib.pyplot, it gives omp error described below.

> OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
> OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For moreinformation, please see http://www.intel.com/software/products/support/.
> Aborted (core dumped)
> 

But when I use matplotlib.pyplot alone to display the result, it works fine.
I added codes below to fix the issue, but it seems not a safe choice.
```
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
```
Do anyone know any safe solutions?
I use anaconda python 3.5 with 2.4 CNTK GPU with no 1 bit SGD

**Comment by bencherian** [comment]
This occurs because CNTK distributes its own copy of MKL and Intel OpenMP instead of using the distribution libraries provided by Anaconda that are likely being used by Matplotlib. As long as there are no direct interactions between CNTK computations that use OpenMP and anything that uses OpenMP it should be ok...

**Comment by min6434** [comment]
I don't think they would interact each other, so it should be fine then.
Thank you very much.
If problem happens I should change path setting somehow to use CNTK's OpenMP instead of Anaconda's.
