### ISSUE TITLE
Linking error when importing in Python

### ISSUE THREAD

**Issue by hccheng** [Microsoft/CNTK#3094]
After installation, the following error shows up when importing CNTK with
`python -c "import cntk`

```
ImportError: /usr/local/lib/python2.7/dist-packages/cntk/libs/libCntk.PerformanceProfiler-2.4.so: symbol _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

I've verified that the linked libstdc++.so.6 is up-to-date by:
`ldd /usr/local/lib/python2.7/dist-packages/cntk/libs/libCntk.PerformanceProfiler-2.4.so`
```
	linux-vdso.so.1 =>  (0x00007ffe8fdd8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb9df256000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb9def50000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb9ded39000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb9deb1a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb9de751000)
	/lib64/ld-linux-x86-64.so.2 (0x00005641ea99c000)
```
And then,
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Am I missing something here? Thank you.

**Comment by nmfisher** [comment]
I had a similar problem when installing CNTK for the first time with an older version of libstdc++.so taking priority in my LD_LIBRARY_PATH. 

It's probably not this problem, but it may be worth double-checking that LD_LIBRARY_PATH is actually correctly set in your running python environment.

`python -c 'import os; print(os.environ["LD_LIBRARY_PATH"])'`

Might also be worth compiling a newer version of gcc and linking against that, just to try and narrow down the problem.

**Comment by hccheng** [comment]
Thanks for the suggestions. I have solved the problem by re-installing libstdc++ and gcc-5-base.
[https://packages.ubuntu.com/xenial/libstdc++6](https://packages.ubuntu.com/xenial/libstdc++6)
[https://packages.ubuntu.com/xenial/gcc-5-base](https://packages.ubuntu.com/xenial/gcc-5-base)
I am inclined to believe that this problem has nothing to do with CNTK.
