### ISSUE TITLE
RuntimeError: Plugin not found: 'Cntk.Deserializers.Image-2.5.dll'

### ISSUE THREAD

**Issue by Hammatt** [Microsoft/CNTK#3095]
Hi, I installed CNTK using `pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.5-cp36-cp36m-win_amd64.whl` but i'm getting an error saying 
`RuntimeError: Plugin not found: 'Cntk.Deserializers.Image-2.5.dll'` when I try to train my network.

Did I miss a step during set up?

**Comment by Hammatt** [comment]
I was able to work around this by revering to cntk 2.4 with
`pip install --upgrade --no-deps https://cntk.ai/PythonWheel/CPU-Only/cntk-2.4-cp36-cp36m-win_amd64.whl`

the 2.4 whl is about 70mb but the 2.5 whl is around 8mb making me think that something is probably very wrong with the 2.5 whl file.

**Comment by SamSchrader** [comment]
Thank you Hammatt!

**Comment by KeDengMS** [comment]
Please take a look at the [required packages](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python?tabs=cntkpy25#environment-variables-and-required-packages). CNTK 2.5 moved external dependency libraries outside of Python wheel, thus the size reduction.

**Comment by Hammatt** [comment]
Thanks for getting back to me, that explains a lot.

There was an issue (on my end?) where the dependency libraries were not being added to my PATH system variable probably. For whatever reason doing it through powershell as shown in the instructions meant that only the last thing that i added to the path would be there, + the full system path

I solved this by going into system properties -> environment variables, and then manually adding them both to the user path variable.
