### ISSUE TITLE
input variables have not been provided after I insert debug_model()

### ISSUE THREAD

**Issue by egg-west** [Microsoft/CNTK#3099]
In the beginning, My code runs well. But an error shows when I insert a `z = debug_model(z)` ( the only thing I did ), it says one of the input_variables have not been provided. 

```
ValueError: Values for 1 required arguments 'Input('x_input_variable', [#, *], [60])', that the requested output(s) 'Output('aggregateLoss', [], []), Output('Block4992_Output_0', [#, *], [1]), Output('aggregateEvalMetric', [], [])' depend on, have not been provided.
```

**Comment by KeDengMS** [comment]
After you create the debug_model, you have a clone of z, and thus with new input variables. Using z.arguments[0] makes sure you have the right input variable for feeding data.

**Comment by egg-west** [comment]
Thank you, I understand that.
