### ISSUE TITLE
Enhance the C# wrapper API

### ISSUE THREAD

**Issue by rold2007** [Microsoft/CNTK#310]
The wrapper currently doesn't allow to extract the features input size. I'm currently training my model based on AlexNet (224x224x3 images) but I'm also adapting the model to support other image sizes. At the moment there is no way to know the input size at runtime so I have to hardcode the size in my code. Should I parse the cntk file or will the wrapper API be extended to get more infos about the loaded model ?

**Comment by gaizkan** [comment]
Quick note: The C# wrapper now exposes the GetNodeDimensions, which will provide the input or output layer names and their corresponding dimension.
I will close this issue.
Best regards,
Gaizka
