### ISSUE TITLE
Sparse Matrix multiplication issue

### ISSUE THREAD

**Issue by loripino21** [Microsoft/CNTK#3100]
I am trying to multiply a big dense matrix with an even bigger Sparse matrix:
`auto nodeNewStates = Times(HwModelSingle, HwReduceSumMatrix);`
but the following error is thrown:
`Times: For a sparse right operand 'Input('Input723', [3065077 x 1235763], [])', cannot reduce multiple (2) axes; currently only the leading axis can be reduced for the sparse operand.`
(Even in debug environment the Sparse matrix has 3.7e12 potential coefficients, converting it to dense is not an option. )
What can I do?
What i am trying to do is to Sum certain columns of the left matrix. ReduceSum is not an option because I need to specify which columns to sum among them.
Thanks

**Comment by loripino21** [comment]
I tried to make the sparse matrix squared, this way only one dimension of the input would change, and then I tought to use a simple Splice to get the left columns of the resulting matrix.
Nevertheless always the same error is thrown:
`Times: For a sparse right operand 'Input('Input723', [3065077 x 3065077], [])', cannot reduce multiple (2) axes; currently only the leading axis can be reduced for the sparse operand.`
Left matrix is 20x3065077.

**Comment by loripino21** [comment]
By debugging CNTK source I noticed that the issue is caused by a trailing Axis with "Free Dimension" on the left operand, that causes numReductionAxes to be evaluated to 2. Is there any method to remove that last (I think useless?) axis from left operand?

**Comment by loripino21** [comment]
I tried UnpackBatch but no success.
I tried
`Times(Reshape(HwModelSingle, HwModelSingle->Output().Shape().SubShape(0, 2)), HwReduceSumMatrix)`
and it works in Forward, but fails in Backward ("Sparse inputs are only supported if they are 1d or 2d matrices" which doesn't make sense actually).
Please help!!

**Comment by KeDengMS** [comment]
There's limits for Reshape on sparse. Can you print out the sample shapes and dynamic axes for the left/right/output?

**Comment by loripino21** [comment]
I have changed some code in the mean time. I will close this issue. I will open another and explain better.
