### ISSUE TITLE
CNTK 2.5 binary install -- but msmpi.dll is missing

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#3109]
Newly installed CNTK 2.5 binaries:  First attempt to call CNTK.exe on a brainscript file -- fails due to missing msmpi.dll

What did I forget to do?

**Comment by bencherian** [comment]
You need to have installed MS-MPI as specified in step 2 of the manual install: https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Binary-Manual

That DLL should be on your PATH after the installation.

**Comment by JohnCraigPublic** [comment]
OK! Thanks!  Wow, how did I miss that.
