### ISSUE TITLE
Error while to use CNTK in C#

### ISSUE THREAD

**Issue by neopedro** [Microsoft/CNTK#3111]
Hi everyone, I'm trying to use CNTK in C#, but I got an error while running, I don't what it is. The screenshot may tell the error.

![image](https://user-images.githubusercontent.com/16644771/38556914-ac54ed94-3ca1-11e8-95c8-8f7d429ffe0a.png)

**Comment by neopedro** [comment]
No, I downloaded the Nuget package for CNTK 2.5.

**Comment by thiagocrepaldi** [comment]
Please, provide detailed steps to reproduce your issue

**Comment by chismar** [comment]
@thiagocrepaldi not the one you asked, but encountered similar issue.
VS2017
Fresh .NET 4.6.1 Console App with the code
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var device = CNTK.DeviceDescriptor.CPUDevice;
        }
    }
}

```
Immediately goes to break mode and crashes on this line.
I'm using 2.5 CNTK-CPUOnly nuget package.

**Comment by thiagocrepaldi** [comment]
My Russian skills are not that good :)

Do you have those packages installed on your project ?

<packages>
  <package id="CNTK.CPUOnly" version="2.5" targetFramework="net45" />
  <package id="CNTK.Deps.MKL" version="2.5" targetFramework="net45" />
  <package id="CNTK.Deps.OpenCV.Zip" version="2.5" targetFramework="net45" />
</packages>

Note that you dont need CNTK.CPUOnly package only, but also two other dependency projects. make sure you are using 2.5 for all of them too.

**Comment by chismar** [comment]
That's why I've translated the exception, heh

Yep. Nuget installed all of them. So, as I've said, the issue is that you need to change platform from Any CPU to x64

**Comment by thiagocrepaldi** [comment]
That is odd. Only the "PythonExamples" project has "Any CPU" as platform. All others are "x64" already. I will double check if any script is changing that by accident.
