### ISSUE TITLE
Model from CNTK 2.5 won't load in C++ eval code developed for CNTK RC-2

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#3112]
Hopefully an easy question for the right person.  I developed C++ code based on CNTK release candidate 2 last year -- the code loads a model (computed by Brainscript) and then calls it for evaluation.

Now I updated to CNTK 2.5 and re-created the model using 2.5.   I find that this new model won't load and evaluate using my C++ code.   So, what do I need to update on my C++ code side?  Thanks.

**Comment by KeDengMS** [comment]
Please take a look at [CPP Eval Example](https://github.com/Microsoft/CNTK/tree/master/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCPPEvalExamplesTest).

**Comment by JohnCraigPublic** [comment]
OK -- I had to update the NuGet package to version 2.5 and rebuild my eval code.  Working now.
