### ISSUE TITLE
URL to WHL for CPU only CNTK 2.0 Python 3.5 returns 404

### ISSUE THREAD

**Issue by scrampy** [Microsoft/CNTK#3114]
Hi,

In MS course DAT236x  I'm following https://courses.edx.org/courses/course-v1:Microsoft+DAT236x+1T2018a/courseware/9c859463158d4160bd7f8463ccd705d0/e9430df82b4341b6918643ed3617cf9d/4?activate_block_id=block-v1%3AMicrosoft%2BDAT236x%2B1T2018a%2Btype%40vertical%2Bblock%40b8a24bed6737459b912559ea37f00e4e

Copy/pasting the URL from https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python?tabs=cntkpy20 for Python 3.5 CPU-Only and passing it as an input to pip install throws a 404 error:

```
(C:\users\scrampy\Anaconda3) C:\users\scrampy>pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl
Collecting cntk==2.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl
  HTTP error 404 while getting https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl
  Could not install requirement cntk==2.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl
Could not install requirement cntk==2.0 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl for URL https://cntk.ai/PythonWheel/CPU-Only/cntk-2.0-cp35-cp35m-win_amd64.whl
```

Thanks for your help!

**Comment by thiagocrepaldi** [comment]
Try using latest version (2.5) and keep going on the course. We will work on this issue in the mean time

https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python?tabs=cntkpy25
