### ISSUE TITLE
_cprintf function slow on Linux

### ISSUE THREAD

**Issue by libohanr100** [Microsoft/CNTK#3118]
Hi,

When I used CNTK on Linux, I just found it is slow to use _cprinf in "Source/Common/Include/Basic.h"

The original code is as follows:
>    inline size_t _cprintf(const char* format, va_list args)
    {
    #ifdef _MSC_VER
            return _vscprintf(format, args);
    #elif defined(__UNIX__)
            // TODO: Really??? Write to file in order to know the length of a string?
	    FILE* dummyf = fopen("/dev/null", "wb");
            if (dummyf == NULL)
                perror("The following error occurred in basetypes.h:cprintf");
            int n = vfprintf(dummyf, format, args);
            if (n < 0)
                perror("The following error occurred in basetypes.h:cprintf");
            fclose(dummyf);
            return n;
    #endif
    }

So on linux, it will write file, which will cause slow perf, how about change to this?
> inline size_t _cprintf(const char* format, va_list args)
    {
    #ifdef _MSC_VER
            return _vscprintf(format, args);
    #elif defined(__UNIX__)
            // TODO: Really??? Write to file in order to know the length of a string?
	    int n = vsnprintf(NULL, 0, format, args);
            if (n < 0)
            {
               perror("The following error occurred in basetypes.h:cprintf");
            }
            return n;
    #endif
    }

Thanks

**Comment by KeDengMS** [comment]
Thanks for pointing it out. Please send us a PR for the fix you proposed.

**Comment by libohanr100** [comment]
I've sent a pr https://github.com/Microsoft/CNTK/pull/3124 , how could I finished the PR?

**Comment by libohanr100** [comment]
I've updated the code, could you help review why build failed?
