### ISSUE TITLE
Dropout for RNNs

### ISSUE THREAD

**Issue by bencherian** [Microsoft/CNTK#3120]
Typically dropout in RNNs will use the same dropout mask for all the elements in a sequence. I believe this is not what occurs with the existing dropout op. Is there a way to do this with the existing available ops in CNTK 2.5?

**Comment by KeDengMS** [comment]
Maybe something like this?
```
dp = C.dropout(input_ones, 0.2)
z = C.layers.Recurrence(C.layers.GRU(10) * dp)(C.sequence.input_variable((5)))
```
Note that input_ones has to be fed on every minibatch, or dp won't be re-evaluate and would have a consistent mask.

**Comment by bencherian** [comment]
Thanks for the suggestion. I'll give this a try...would there be a clean way to get rid of this dummy input or replace it with a constant in a model that is saved for inference where dropout would be disabled anyway?

**Comment by KeDengMS** [comment]
You may have a dumpy input of scalar and compute with a constant with the right shape, then use it in dropout. However, the dummy input is needed to make sure every batch you'll have a different dropout mask. CNTK uses timestamps in nodes to prevent unnecessary calculations, so if timestamp is not changed, the dropout mask would only be generated once. Feeding input is the way to bump up timestamps.

Dropout does nothing during inference, and you may clone/edit the model to replace the cell with dropout for inference.
