### ISSUE TITLE
Are there any known problems running CNTK in centOS 7?

### ISSUE THREAD

**Issue by xiezhq-hermann** [Microsoft/CNTK#3125]
I'm currently using CNTK in my centOS server. I have verified the installation successfully and tested prediction of a simple model.
However, the warning reminds me there're no official supports and general testing for centOS. Can anyone tell me the known problems running in centOS, since centOS is more suitable for me to deploy other tasks.

**Comment by thiagocrepaldi** [comment]
There is no known problem. During development, CNTK Team run automated tests on Ubuntu 16.04 machines only, so that is why we recommend it. If it is working on CentOS, enjoy it :)

**Comment by xiezhq-hermann** [comment]
Thanks, very helpful, I'll report it if I encounter any.
