### ISSUE TITLE
CUDA failing with out of memory on "load" (CNTK 2.3.1)

### ISSUE THREAD

**Issue by deischi** [Microsoft/CNTK#3128]
My application is using CNTK only for inference/evaluate.
Initially 4 networks are loaded and evaluate with dummy data. Pseudo-code (repeat 4 times)
```
f = Function::Load("net1")
f->Evaluate()
```
One some machines this results in a Cuda out of memory exception (when loading the 4th network):

```
Selected GPU[0] Quadro K4100M as the process wide default device.
CUDA failure 2: out of memory ; GPU=0 ; hostname=GC4G4J72E ; expr=cudaMemcpy(Dat
a(), pArray, sizeof(ElemType) * GetNumElements(), (matrixFlags & matrixFlagSetVa
lueOnDevice) ? cudaMemcpyDeviceToDevice : cudaMemcpyHostToDevice)
```

On other machines I can load and evaluate 30 network without a problem.

Our development environment is VS 2015, C++, 64bit - so I am kind of stuck with CNTK version 2.3.1.
It seems that there is no problem when I start 2 processes (setting default device to GPU), each loading 3 networks. So putting evaluation out of processes might be a (not very desirable) workaround for me.

Any suggestions what limit is reached here? Even more, what parameter to check or re-configure.
Does CNTK offer a build-in method to load and evaluate our of process?

**Comment by KeDengMS** [comment]
It might be cuDNN using too much workspace memory for convolution, as Quadro K4100M only has 4GB memory. Can you try [force_deterministic](https://cntk.ai/pythondocs/cntk.debugging.html?highlight=force_deter#cntk.debugging.force_deterministic) to test with cuDNN using no workspace? The speed might be slower with this option though.

**Comment by deischi** [comment]
As we are using the C++ API. I assume adding: 
`CNTK::Internal::ForceDeterministicAlgorithms();`
before loading the network is fine to try this.

We will try, "unfortunately" the laptop showing the issue yesterday did not show it today *grrr*

Also, I incorrectly assumed that another problem we have seen, is the one described above. 
On other system we have seen similar behavior - CNTK throwing an exception. That was on systems without development environment, so only the end result was observed. 
That problem seems to go deeper: Cuda seems to be incompatible with McAfee Application Control. Even a trivial Cuda test program fails when App Control is enabled (unless CASP is disabled for the application).

**Comment by KeDengMS** [comment]
Is it possible to try CNTK 2.5.1? We've moved to CUDA 9/cuDNN 7 in latest release. The behavior of CUDA might have some change with version upgrade.

**Comment by deischi** [comment]
I think we can put this issue on ice (at least for now):
- right now we cannot reproduce,
- I mixed up with the the issue with "Cuda vs. App Control"
- we observed this with an older version.

KeDengMS, thanks for your input.
