### ISSUE TITLE
Convert sequence to batch and vice versa

### ISSUE THREAD

**Issue by haixpham** [Microsoft/CNTK#3129]
I'm working on a recurrent regression model, pseudo code like following:

```python
x = C.sequence.input_variable(2)
y = x + 1    # a temp function
```
y is a sequence (in terms of data, a batch of sequences, to be precise). I want to drop the sequence axis.
For example:

```
data = [np.array( [ [1,2], [3,4] ] ), np.array( [ [5,6], [7,8], [9,10] ] ) ]
y_val = y.eval({x: data})
```
data contains 2 sequences, one has length 2, one has length 3. y_val is a list of 2 tensors.

Is there a way to drop sequence axis from y? so that y_val is a single (5x2) tensor.

The reason is I want to use y in a GAN loss, with a static discriminator. The real samples are taken randomly, not from a sequence, hence I cannot match them to y directly.

> Or conversely, is there a way to get the length of sequences in a batch? Because I can then convert the real samples to faux sequences.

Edit: it seems the other way around is simpler: I can extract the sequences from minibatch_source, count the number of sequences and their lengths, and create corresponding sequences from single samples.

TIA!

**Comment by KeDengMS** [comment]
You can count sequence length using something like:
```
z = C.layers.Fold(C.plus)(C.sequence.broadcast_as(1, C.sequence.input_variable(())))
z.eval([[0,1,2],[2,4]])

array([[3.],
       [2.]], dtype=float32)
```
You can also try sequence.unpack, unpack_batch, to_batch to see if you can get the input in the way you need.

**Comment by haixpham** [comment]
Thanks for the suggestion!

I use C.Value.as_sequence() to convert minibatch data to list of numpy arrays and access the data directly. It's a little bit slower, but negligible.

**Comment by KeDengMS** [comment]
Glad to know it helps. BTW I just realized this would be more performant for sequence length:
```
z = C.sequence.reduce_sum(C.sequence.broadcast_as(1,x))
z.eval([[0,1,2],[2,3]])
```

The reason is that Fold/Recurrence/etc works on sequence in a sequential way that requires O(seq_len) CUDA kernel launches, while sequence.reduce_sum takes only one.
