### ISSUE TITLE
Please build CNTK with Visual Studio 2015

### ISSUE THREAD

**Issue by CBrauer** [Microsoft/CNTK#313]
HI,

I find it very discouraging that CNTK does not build with the current shipping version of Visual Studio 2015.  You do work at Microsoft.  Please suffer along with the rest of us.

Charles

**Comment by frankseide** [comment]
We do! (...suffer from not being able to use VS 2013, in this case). VS 2015 is not used because of an external dependency (sorry I forgot which one) that did not support VS 2015. As soon as that dependency works with VS 2015, we will switch.

**Comment by Alexey-Kamenev** [comment]
CUDA 7.5 (and 7.0 that is currently used in CNTK) does not officially support VS 2015.

**Comment by MihailStoyanov** [comment]
I am getting 154 Errors and 496 warnings when I tried building with VS 2015 in release or debug with CPU only, since my laptop has Intel HD Graphics 4000 (without CUDA GPU acceleration)...

How should I proceed?

**Comment by CBrauer** [comment]
You should try https://cran.r-project.org/web/packages/h2o/h2o.pdf.  They are much more friendly to Visual Studio 2015.  I find it very embarrassing that Microsoft researchers do not use Visual Studio 2015.
Charles

**Comment by frankseide** [comment]
It's because one of the libraries we depend on is not compatible. I'd upgrade immediately if we could!
