### ISSUE TITLE
CNTK 2.5 : cntk.load_model() failed on Tesla K40c

### ISSUE THREAD

**Issue by haixpham** [Microsoft/CNTK#3130]
I upgraded some of my machines to CNTK 2.5. Particularly, on a workstation with Tesla K40c, CNTK failed to load_model() and crashed.

Due to work, I downgraded to version 2.4 immediately and the problem went away. I haven't had a chance to test other functionality. Will report back next time I can use that machine to test ver 2.5.

**Comment by thiagocrepaldi** [comment]
As of CNTK 2.5 it is required to install dependencies before running CNTK. Refer to https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Windows-Python?tabs=cntkpy25#environment-variables-and-required-packages or https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-Linux-Python?tabs=cntkpy25

Reopen this issue if that doesn't fix it
