### ISSUE TITLE
Combining Regular and Sequence Inputs

### ISSUE THREAD

**Issue by milannnnn** [Microsoft/CNTK#3134]
Quick question - I have input data that combines both sequential and non-sequential data, where one row of my input data looks like

x = [ a1 ... an | b1 ... bn | s1 ... sn | q1 ... qn ]

where a and b represent non-sequential data, and s and q represent two different flattened sequences (e.g. if s in a sequence of 3-day hourly data, it will be flattened to an array of 72 samples). I want to separate the data so that I train different subnetworks with it (e.g. I use a and b to train an MLP, s to train LSTM1 and q to train LSTM2), and then merge them together and pass through a final dense layer to get the final output.

What would be the best approach for defining and separating these variables (while making s and q sequential), and merging them together at the end?

I was thinking of defining a regular input variable, slicing it into different variables (a, b, s, q), and then switching s and q to sequential, as

```
x = C.input_variable((1, in_dim))
a = C.slice(x, 1, a_start, a_end)
b = C.slice(x, 1, b_start, b_end)
s = C.slice(x, 1, s_start, s_end)
s = C.to_sequence(s)
q = C.slice(x, 1, q_start, q_end)
q = C.to_sequence(q)

# Create different subnetworks:
mlp = MLP(a,b)
lstm1 = LSTM1(s)
lstm2 = LSTM1(q)

# Merge them together:
out = C.splice(mlp, lstm1, lstm2)
```

but when I try this, when splicing the layers back together, I get the "operand XYZ has dynamic axes, that do not match the dynamic axes of operand PQR" error.

**Comment by KeDengMS** [comment]
mlp has no sequence axis. while lstm1/2 have. You may need to run a reduction (sequence.last, or sequence.reduce_mean, etc) on lstm results before splice, or broadcast mlp along sequence axis of lstm1/2.
