### ISSUE TITLE
How to restore model from .ckp file when running the Alexnet example

### ISSUE THREAD

**Issue by woskii** [Microsoft/CNTK#3135]
I am runnig Alexnet example in [Python/AlexNet_ImageNet_Distributed.py](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/AlexNet/Python/AlexNet_ImageNet_Distributed.py) And in the original code, it seems that `checkpoint_config = CheckpointConfig(filename=os.path.join(model_path, model_name)` will check whether there is a .ckp file before and restore from it.

And now I have ran the example for one epoch and got a .ckp file named `AlexNet.model.ckp`. Can I just rerun the same code to restore the pretrained model from this file? What if I want to modify the parameter of trainer such as learner? Will the model in the checkpoint file cover the model I modified?

I don't know whether I understand correctly. Is there some other ways to save and restore the model?

**Comment by KeDengMS** [comment]
checkpoint contains both learner state (momentum, schedule, etc) and model so changing to a different learner than the one used in generating the ckp file may have undefined behaviors.
If you really want to try a different learner after some epoch, I'd suggest use just the model from the checkpoint file by loading checkpoint, and create a new trainer/learner using its model. You can also use save/load to handle the model manually.
One thing to note is that in distributed training, checkpointing only happens on rank 0, while save/load has no such constrain. If the script didn't aware of that, saving from multiple processes might end up corrupting the model on disk.

**Comment by woskii** [comment]
@KeDengMS Thanks a lot.  As you suggested, I use save_model and load_model to save and load model and it goes well now.

**Comment by woskii** [comment]
@KeDengMS Thanks a lot. As you suggested, I use save_model and load_model to save and load model and it goes well now.
