### ISSUE TITLE
Unit Tests MathTests.exe CUDA failure 30: unknown error

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#314]
When running MathTests.exe, screen gets black and this error appears:

`RandomSeedFixture::RandomSeedFixture (GPU): creating curand object with seed 42, sizeof(ElemType)==4`
`RandomSeedFixture::RandomSeedFixture (GPU): creating curand object with seed 42, sizeof(ElemType)==8`
`CUDA failure 30: unknown error ; GPU=0 ; hostname=EPC ; expr=cudaMemcpy(d_res, res, sizeof(long) * 1, cudaMemcpyHostToDevice)`
`CUDA failure 30: unknown error ; GPU=0 ; hostname=EPC ; expr=cudaFree((void*) bufferPtr)`

**Comment by wolfma61** [comment]
Is this reproducable?

some more information ? 
what test is failing? what cuda version, what dirver version, what graphics card, etc?

I have seen similar symptons in the past on low end cards (K600) with limited amount of memory, but it normally succeeded on a second run...

thx
Wolfgang

**Comment by RayFireh** [comment]
Current build (a bit different from previous, but errors are the same, run the MathTest.exe few times)
Windows 7 x64, Visual Studio 2013 Update 5
CUDA 7.5 (older builds were with CUDA 7.0 - also errors)
After pulling from git, have rechecked that in all .vcproj files the architectures are correct (SOME WERE NOT CONSISTENT, like instead of `compute_20,sm_20` just `compute_20,compute_20` was present, or in one file architecture starts from `30` in other from `20`), so tried to make it the same everywhere:
`compute_20,sm_20;compute_30,sm_30;compute_35,sm_35;compute_50,sm_50;`

I haven't tested it on any other hardware (no access to other GPU). It happens all the time, as soon as operations with memory are done. Failed on previous builds and on the current too.

CPU: Q6600
GPU: Nvidia GTX 650Ti 2GB (driver 364.51)
RAM: 8GB

It just goes on until all tests are finished. Screen blanking happens once at the beginning of this section (right after seeds are finished): 
RandomSeedFixture::RandomSeedFixture (GPU): creating curand object with seed 42, sizeof(ElemType)==4
RandomSeedFixture::RandomSeedFixture (GPU): creating curand object with seed 42, sizeof(ElemType)==8
CUDA failure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMemcpy(d_res, res, sizeof(long) * 1, cudaMemcpyHostToDevice)
unknown location(0): fatal error: in "GPUMatrixSuite/GPUSparseTensorShuffleScaleAndAdd": class Microsoft::MSR::CNTK::ExceptionWithCallStack<class std::runtime_error>: CUDA failure
30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMemcpy(d_res, res, sizeof(long) * 1, cudaMemcpyHostToDevice)
c:\installs\cntk\tests\unittests\mathtests\gpusparsematrixtests.cpp(597): last checkpoint
CUDA failure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
unknown location(0): fatal error: in "GPUMatrixSuite/GPUMatrixFileWriteRead": class Microsoft::MSR::CNTK::ExceptionWithCallStack<class std::runtime_error>: CUDA failure 30: unknown
 error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
c:\installs\cntk\tests\unittests\mathtests\matrixfilewritereadtests.cpp(80): last checkpoint: "GPUMatrixFileWriteRead" entry.
CUDA failure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
unknown location(0): fatal error: in "GPUMatrixSuite/GPUMatrix1BitQuantizeFloat": class Microsoft::MSR::CNTK::ExceptionWithCallStack<class std::runtime_error>: CUDA failure 30: unk
nown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
c:\installs\cntk\tests\unittests\mathtests\matrixquantizertests.cpp(397): last checkpoint: "GPUMatrix1BitQuantizeFloat" entry.
CUDA failure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
unknown location(0): fatal error: in "GPUMatrixSuite/GPUMatrix1BitQuantizeDouble": class Microsoft::MSR::CNTK::ExceptionWithCallStack<class std::runtime_error>: CUDA failure 30: un
known error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
c:\installs\cntk\tests\unittests\mathtests\matrixquantizertests.cpp(413): last checkpoint: "GPUMatrix1BitQuantizeDouble" entry.
CUDA failure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
unknown location(0): fatal error: in "GPUMatrixSuite/MatrixChangeModesBetweenDenseAndSparse": class Microsoft::MSR::CNTK::ExceptionWithCallStack<class std::runtime_error>: CUDA fai
lure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
c:\installs\cntk\tests\unittests\mathtests\matrixsparsedenseinteractionstests.cpp(23): last checkpoint: "MatrixChangeModesBetweenDenseAndSparse" entry.
CUDA failure 30: unknown error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
unknown location(0): fatal error: in "GPUMatrixSuite/MatrixSparseTimesDense": class Microsoft::MSR::CNTK::ExceptionWithCallStack<class std::runtime_error>: CUDA failure 30: unknown
 error ; GPU=0 ; hostname=GAMEPC ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)

**Comment by wolfma61** [comment]
@RayFireh 
Thanks for the info, at home I have a gtx750, I think this is the closest match. I will try there

regarding Math, someone found a problem there:
https://github.com/Microsoft/CNTK/issues/353
which we will fix ...
