### ISSUE TITLE
Performing 16 bit inference using C++

### ISSUE THREAD

**Issue by rajat95** [Microsoft/CNTK#3142]
Any inputs on how FP16 can be leveraged when inferring in C++ since 16 bit float is not one of the fundamental types for C++.

**Comment by KeDengMS** [comment]
You may have inputs and outputs in FP32, and use Cast() to convert them to FP16 in the middle.

**Comment by rajat95** [comment]
Thanks. That should work. But I think it would be more convenient to have a way to perform 16 bit inference directly in case we only have a trained model and not the training code. Feel free to close the issue.

**Comment by KeDengMS** [comment]
As you said, the main issue here is that C++ does not have built-in type for 16-bit float. If you are running inference in Python, you can use numpy float16 directly without cast.
