### ISSUE TITLE
Sequence to sequence time series prediction (with attention model)

### ISSUE THREAD

**Issue by milannnnn** [Microsoft/CNTK#3146]
Hey there. I just went through the [sequence to sequence tutorial](https://cntk.ai/pythondocs/CNTK_204_Sequence_To_Sequence.html?highlight=identity), and I was wondering what would be the best way to adapt the encoder, decoder, attention principle for time series prediction, where I would have one or multiple input sequences and an output sequence.

Do I just ditch the embeddings, and remove the hardmax from the greedy model function, or is there something more?

Also, do I need to include sequence start and sequence end characters to my data, as all sequences are of the same length, and they are purely real numbers?

Thanks.

**Comment by KeDengMS** [comment]
You can play with the tutorial to have different variations and see if it fits your need. CNTK supports variant sequence lengths, which is an advantage over other toolkits for RNN. Usually you don't have to define sequence start and sequence end, nor would you need to pad sequences to have the same length.

**Comment by ChaiBapchya** [comment]
If this issue is resolved, can we close it?
