### ISSUE TITLE
How to supply dilation parameters for a Convolution layer in Python?

### ISSUE THREAD

**Issue by Mut1nyJD** [Microsoft/CNTK#3148]
Since dilation can improve the performance of Residual networks for image classification and location and even more so for segmentation networks how do you apply the dilation parameters (as dilation support for Convolutions apparently have been added in CNTK2.3) in the Python API? I couldn't find anything in the Python API CNTK documentation pointing to dilation.

**Comment by KeDengMS** [comment]
There's dilation parameter in the low level [ops.convolution](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.convolution) API. Seems it's not exposed in Layers API yet.

**Comment by spandantiwari** [comment]
The Convolution layer in layers.subpackage does not have a dilation parameter. The dilation parameter is exposed only in the lower level ops.convolution API.

**Comment by spandantiwari** [comment]
@Mut1nyJD It seems we have a doc mistake where we do not list the dilation parameter. I'll recall my previous comment. 

Thanks for pointing this out. You can use the dilation parameter from the [Convolution](https://cntk.ai/pythondocs/cntk.layers.layers.html#cntk.layers.layers.Convolution) API in the layers subpackage. We will fix the doc bug.

**Comment by Mut1nyJD** [comment]
@spandantiwari 
Ah thank you and everybody else with there answers too.  I completely forgot to click at the source button as in the source it is obviously listed as parameter.

**Comment by spandantiwari** [comment]
Well, you shouldn't have to look at the source for the API description. The doc should provide it correctly. Anyway, this doc bug is being fixed. Thanks!
