### ISSUE TITLE
Missing HalfConverter.hpp

### ISSUE THREAD

**Issue by conghuawang** [Microsoft/CNTK#3157]
Missing HalfConverter.hpp in release 2.5.1 "CNTK for Windows v.2.5.1 GPU".
Can't compile with c++

**Comment by KeDengMS** [comment]
Dup of #3005? Seems a missing file in binary zip.

**Comment by conghuawang** [comment]
@thiagocrepaldi 
I follow this steps to setup GPU version in win10_x64
1. Download release package from here https://cntk.ai/dlwg-2.5.1.html
2. Setup env step by step from here(Scripted Install) https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-binary-script
3. In my c++ project, include CNTKLibrary.h, compile and link Cntk.Core-2.5.1.lib with vs2017
4. vs2017 cannt find HalfConvert.hpp. logs below:
   cntklibrary.h(34): fatal error C1083: Cannot open include file: 'HalfConverter.hpp': No such file or directory

**Comment by conghuawang** [comment]
@KeDengMS yes, it's the same problem. I copy HalfConverter.hpp from source code to the binary release to resolve the problem. Thanks!
