### ISSUE TITLE
column-wise slice/subset of input

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#316]
Hi,
I would like to extract the first column of my inputs  (6 of them) and use it as an additional way of clearing the state of a LSTM-type network. 
How can I do it?
I do not see any column-subsetting operator.
I tried to split it from the beginning, in reader
        forgetF= [
            dim = 1  
            start = 0      # Start with first element on line
        ]
        oFeatures = [
            dim = 5  
            start = 1      # Start with first element on line
        ]

and then in NDL
    forgetF= Input(1, tag="feature")
    oFeatures=Input(featDim, tag="feature")

but that does not work. Firstly, I see a worrisome message
3 roots:
        Err = SquareError
        cr = SquareError
        forgetF = InputValue
, so oFeatures are not treated as inputs(?), and then 

About to throw exception 'NotifyFunctionValuesMBSizeModified: oFeatures InputValue operation had its col dimension 10 changed by the reader to 1, but different from MBLayout.'

EXCEPTION occurred: NotifyFunctionValuesMBSizeModified: oFeatures InputValue operation had its col dimension 10 changed by the reader to 1, but different from MBLayout.

[CALL STACK]
    > Microsoft::MSR::CNTK::ComputationNode<float>::  NotifyFunctionValuesMBSizeModified
    - Microsoft::MSR::CNTK::DataReaderHelpers::GetMinibatchIntoNetwork<float>
    - Microsoft::MSR::CNTK::SGD<float>::  TrainOneEpoch
    - Microsoft::MSR::CNTK::SGD<float>::  TrainOrAdaptModel
    - Microsoft::MSR::CNTK::SGD<float>::  Train
    - DoTrainMicrosoft::MSR::CNTK::ConfigParameters,float
    - DoCommands<float>
    - wmainOldCNTKConfig
    - wmain1
    - wmain
    - __tmainCRTStartup
    - wmainCRTStartup
    - BaseThreadInitThunk
    - RtlUserThreadStart

Slawek

**Comment by frankseide** [comment]
Can you clarify what you want to do? So say your sequence has N steps, do you want to store N+1 steps, and then use the first as the initial value of the PastValue?

This can be done using the Gather() operation, which I recently added. Gather() takes two arguments, a flag sequence and a data sequence of equal length. The operation outputs a new sequence which is a subset of samples where all samples have been removed for which the flag is 0.

Please let me know if that is what you want, and I will walk you through how to do it (we have no documentation for Gather() yet).

In order to use a custom starting value for the recurrence, you currently need to use a math trick, saying something like
```
actualPastValue = isFirst * initialValue + (1 - isFirst) * PastValue (x)
```
where isFirst itself would be a PastValue of 0 with an initial value of 1. We will soon have an actual operator that does this, and further, we will allow to pass the initial value directly to the PastValue node. This will take a few more weeks until it becomes available.

**Comment by slaweks17** [comment]
Hi Frank,

Thank you for this early-morning reply [&#X1f60a]

What I want to do:

I want to train an LSTM-style network for time series forecasting. My data sets contain a few dozens to few thousand series, and I have a hope that there is some commonality between them to allow cross-series learning. So, I do a data preparation step (in R) where I create a moving (look-back) window and extract features from there, e.g. assume that my time series is 11 long, the look back and therefore feature vector length is 6, and my max forecasting horizon ad therefore the label vector length is 3, I would get

i1,i2,i3,i4,i5,i6,o7,o8,o9

i2,i3,i4,i5,i6,i7,o8,o9,o10

i3,i4,i,i5,i6,i7,i8,o9,o10,o11

These three lines of data input would be followed by another bunch of lines describing extracted features and outputs of another series and so on.

I want to make sure that the state is zeroed when a change of the series happen, so I was thinking about something like this

0, i1,i2,i3,i4,i5,i6,o7,o8,o9

1, i2,i3,i4,i5,i6,i7,o8,o9,o10

1, i3,i4,i,i5,i6,i7,i8,o9,o10,o11

etc., the new series starting with first column=0. Then, in NDL, I would use this first column to multiply the state vector by it.


Regards,

Slawek




________________________________
Od: Frank Seide <notifications@github.com>
Wysłane: 4 kwietnia 2016 12:37
Do: Microsoft/CNTK
DW: slaweks17
Temat: Re: [Microsoft/CNTK] column-wise slice/subset of input (#316)


Can you clarify what you want to do? So say your sequence has N steps, do you want to store N+1 steps, and then use the first as the initial value of the PastValue?

This can be done using the Gather() operation, which I recently added. Gather() takes two arguments, a flag sequence and a data sequence of equal length. The operation outputs a new sequence which is a subset of samples where all samples have been removed for which the flag is 0.

Please let me know if that is what you want, and I will walk you through how to do it (we have no documentation for Gather() yet).

In order to use a custom starting value for the recurrence, you currently need to use a math trick, saying something like

actualPastValue = isFirst * initialValue + (1 - isFirst) * PastValue (x)


where isFirst itself would be a PastValue of 0 with an initial value of 1. We will soon have an actual operator that does this, and further, we will allow to pass the initial value directly to the PastValue node. This will take a few more weeks until it becomes available.

-

**Comment by frankseide** [comment]
Are the i_n and o_n are scalars, or vectors?

If you have a prepared your data to have fixed window lengths, an alternative is to bypass the built-in recurrence mechanism, and hand-unroll it instead. You could feed your data as concatenated vectors, and then use RowSlice to split it into 11 distinct variables.

If they are still variable-length sequences, you can use the isFirst trick to recreate the 0 or 1 inside NDL, no need to store it in the file. Here is the code:
```
  ZeroesLike (x) = ElementTimes (RowSlice (0, 1, x), Constant (0))
  IsFirst (x) = PastValue (0, ZeroesLike (x), timeStep=1, defaultHiddenActivation=1)
```
(Note: I am working on a future version of NDL, so I hope I got the old NDL syntax right.)

**Comment by slaweks17** [comment]
Hi Frank,

The i_n and o_n are scalars, so yes, every line has the same format, so my thinking was probably what you call "hand-unroll".

RowSlice - yes, this should work, I missed it, because somehow stupidly thought about input vector is row vector, but it is normal vector [&#X1f60a]

Thank you, I will try.


I will also try your trick for the rnn training. I guess, I should use CNTKTextFormatReader, one time series per line, and action="trainRnn", correct?

Regards,

Slawek


________________________________
Od: Frank Seide <notifications@github.com>
Wysłane: 4 kwietnia 2016 15:42
Do: Microsoft/CNTK
DW: slaweks17
Temat: Re: [Microsoft/CNTK] column-wise slice/subset of input (#316)


Are the i_n and o_n are scalars, or vectors?

If you have a prepared your data to have fixed window lengths, an alternative is to bypass the built-in recurrence mechanism, and hand-unroll it instead. You could feed your data as concatenated vectors, and then use RowSlice to split it into 11 distinct variables.

If they are still variable-length sequences, you can use the isFirst trick to recreate the 0 or 1 inside NDL, no need to store it in the file. Here is the code:

  ZeroesLike (x) = ElementTimes (RowSlice (0, 1, x), Constant (0))
  IsFirst (x) = PastValue (0, ZeroesLike (x), timeStep=1, defaultHiddenActivation=1)


(Note: I am working on a future version of NDL, so I hope I got the old NDL syntax right.)

-

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
