### ISSUE TITLE
Missing Test Files

### ISSUE THREAD

**Issue by conghuawang** [Microsoft/CNTK#3173]
OS: Windows10_x64
Build: Source Build from "CNTK-2.5.1"
Problem:
  When I run V2LibraryTest, there is no "Train-28x28_cntk_text.txt" and "cntkSpeechFF.dnn" in source project.
  So, several tests failed.
  Where can I find "Train-28x28_cntk_text.txt" and "cntkSpeechFF.dnn" ?

screen shot below:

![untitled](https://user-images.githubusercontent.com/16575549/39398264-ec709e5a-4b3d-11e8-9959-953a48ed30ee.png)

**Comment by conghuawang** [comment]
OK, "Train-28x28_cntk_text.txt" should install.
Open cmd, cd to "CNTK-2.5.1\Examples\Image\DataSets\MNIST", run "python install_mnist.py"

But I still can't find "cntkSpeechFF.dnn"

Is anyone tell me how to generate "cntkSpeechFF.dnn" from C++?

**Comment by thiagocrepaldi** [comment]
Did you find a solution for your issue ? If so, share it with the community so others can enjoy it too :)

**Comment by conghuawang** [comment]
@thiagocrepaldi 
Yes, I'm now find a solution resolve the issue.

"Train-28x28_cntk_text.txt" could be install as below:
1 Open cmd,
2 cd to "CNTK-2.5.1\Examples\Image\DataSets\MNIST", run "python install_mnist.py"

"cntkSpeechFF.dnn" could be generate by run the example of "Speech/AN4"
1 Compile CNTK.sln with vs2017
2 As "Examples\Speech\AN4\README.md" says, I just run the example as below:
  2.1 Open a cmd
  2.2 cd to "x64\Release"
  2.2 Type and run "CNTK.exe configFile=../../Examples/Speech/AN4/Config/FeedForward.cntk currentDirectory=../../Examples/Speech/AN4/Data"
  2.3 After the example finish. In folder "Examples\Speech\AN4\Output\Models" has "cntkSpeechFF.dnn" generated.
