### ISSUE TITLE
C# Sequence to Class (many to one)

### ISSUE THREAD

**Issue by jchmb** [Microsoft/CNTK#3177]
I am trying to implement a recurrent neural network that takes in a sequence and has a single output. I have seen numerous examples in Python. However, I have not seen a good example in C#, except for one that reads in a file (where the sequences are laid out together with a single label), but this does not tell me how to do it programmatically. How can I do this programmatically in C#? It seems that the C# API lacks support for the Fold operation. Is there any other way to do this? Either I need to:

(1) Fold the sequence input (or intermediate result) into a single output.
(2) Do sequence-to-sequence training and "trick" the Trainer into treating the first **t-1** outputs as delta errors of 0, so that only the last step **t** of the sequence is actually used to perform training (since a delta error of 0 is essentially a no-op).

**Comment by KeDengMS** [comment]
C# does not have high level APIs in Python, like Fold/Recurrence/etc. Is it possible for you to create the model in Python, then load into C# for training?

**Comment by jchmb** [comment]
Unfortunately, no. The company I am working for has the policy that everything needs to be written in C# (don't ask me about it; I also think that it's a silly policy).

Is there no workaround for this in C#? Can I not emulate the same behavior in C# somehow?

**Comment by KeDengMS** [comment]
It is possible to write RNN in C# using low level APIs. @liqunfu may give you some start points.

**Comment by jchmb** [comment]
I did figure out how to write a RNN in C#. I just have not been able to figure out how to make only the last "token" (vector of features representing a single index in a sequence) in a sequence actually count towards the error function. Currently I am creating a classification sequence by repeating the target class to match the length of the input sequence, but I think this introduces unwanted biases.

**Comment by KeDengMS** [comment]
[Sequence.Last](https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L4823)?

**Comment by jchmb** [comment]
I think that returns the last token of a sequence, so I don't think that's what I'm looking for. I need the entire input sequence and a single target.

I do see some related functions, starting with Reduce, that may be relevant. I wouldn't know how to use them, though.
