### ISSUE TITLE
What third party libraries are now included in 2.5.1?

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#3178]
CNTK 2.5.1 is a "Repack of CNTK 2.5 with third party libraries included in the bundle."  Does this repack only extend to the Python Wheel packages?

What about the other third-party libraries in [CNTK Library Evaluation on Windows](https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-library-evaluation-on-windows)?

Visual C++ Redistributable
- Redistributable Package for Visual Studio 2013
- Redistributable Package for Visual Studio 2017

For desktop C++ applications, the following DLLs need to be distributed with your application.
- libiomp5md.dll
- mklml.dll

For using GPU, you need in addition to include the following NVIDIA CUDA related DLLs:
- cublas64_90.dll
- cudart64_90.dll
- cudnn64_7.dll
- curand64_90.dll
- cusparse64_90.dll
- nvml.dll

CNTK NuGet packages are shipping with cuDNN 6
- cudnn64_6.dll.

In the comments section: Since Release 2.2, following dependencies have been added:
- opencv_world310.dll
- zip.dll
- zlib.dll

**Comment by thiagocrepaldi** [comment]
The third party dependencies have been removed from python wheel packages on 2.5.0 release to reduce the size of python packages, but they were re-added on 2.5.1 release. All DLLs mentioned on your message were re-bundled in the python packages (MKL, CUDA and OpenCV), with exception of zip and zlib, which already were in the 2.5.0 python package.

The binary drops and nuget packages always had all dependencies bundled and that was not changed

**Comment by whitmark** [comment]
Thanks @thiagocrepaldi .  So if I am looking to ship CNTK libraries with my C# Windows application that evaluates DNN models, I must still make sure all of the appropriate third-party DLLs are copied into place as I did in 2.5?

Also, if I recall correctly, there were still references that required the Visual C++ Redistributable Package for Visual Studio 2013, has this been resolved?

Thanks.

**Comment by thiagocrepaldi** [comment]
Yes. Which DLLs have you copied ? Maybe we could create a binary drop that makes this packaging simpler.

For the VS Redistributable, it still has the same dependencies of 2.5. However, CNTK 2.6 is on the way (a month or so) and most likely will depend on VS2017 Redistributable only
