### ISSUE TITLE
"Examples\Image\Classification\ResNet\Python" burn my MotherBoard?

### ISSUE THREAD

**Issue by conghuawang** [Microsoft/CNTK#3183]
Hello,
I'm run "Examples\Image\Classification\ResNet\Python" in windows.
But the example burn my motherboard twice!

In "Examples\Image\Classification\ResNet\Python\TrainResNet_CIFAR10.py", when this code is running, my motherboard burn twice: 
train_and_evaluate(reader_train, reader_test, network_name, epoch_size, epochs, args['profiler_dir'], model_dir, args['logdir'], args['tensorboard_logdir'], gen_heartbeat=args['genheartbeat'], fp16=args['fp16'])

My laptop is Alienware 17 R4 with GTX 1080, I can't run CNTK in laptop?

DxDiag infos below:
[DxDiag.txt](https://github.com/Microsoft/CNTK/files/1974688/DxDiag.txt)

**Comment by KeDengMS** [comment]
Sorry to hear what happened to you. CNTK makes maximum use of the GPU and thus it's an extreme test for hardware's thermal designs. If you look at nvidia-smi, you'll find GPU running at 100% when training ResNet20 CIFAR10. If this is a problem, please consider inserting some sleep in the training loop.

**Comment by conghuawang** [comment]
@KeDengMS 
Thanks for your reply. Today I bought a Alienware aurora to use CNTK .
