### ISSUE TITLE
Write action fails. Somehow features are not visible

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#319]
Hi,
I am experiencing a strange failure of write action.
The action is defined as follows

outputPath = "$OutputDir$/SimpleOutput"
outputNodeNames = "labels"

 
nn_Write = [
    action = "write"
    reader = [
        readerType = "UCIFastReader"
        file = "$DataDir$/lstm12dlv.txt"
        randomize = "None"
        verbosity = 1  

        features = [
            dim = 12       
            start = 0      
        ]

        labels = [
            start = 12      
            dim = 12        
  	    labelType = "Regression"
        ]
    ]
]

During execution I am getting:
3 roots:
        Err = SquareError
        cr = SquareError
        labels = InputValue
...
Allocating matrices for forward and/or backward propagation.
starting epoch 0 at record count 0, and file position 0
already there from last epoch

EXCEPTION occurred: Features matrix not found in config file, there should be a section 'features=[...]' in the configuration file.

[CALL STACK]
    > Microsoft::MSR::CNTK::UCIFastReader<float>::  GetMinibatch
    - Microsoft::MSR::CNTK::DataReader::  GetMinibatch
    - Microsoft::MSR::CNTK::DataReaderHelpers::GetMinibatchIntoNetwork<float>
    - Microsoft::MSR::CNTK::SimpleOutputWriter<float>::  WriteOutput
    - DoWriteOutput<float>
    - DoCommands<float>
    - wmainOldCNTKConfig
    - wmain1
    - wmain
    - __tmainCRTStartup
    - BaseThreadInitThunk
    - RtlUserThreadStart

But clearly features section is there.

Regards,
Slawek

**Comment by slaweks17** [comment]
Solved. The problem was that I was too much influenced by the Examples\Other\Simple2d config file, where they save labels. But this was not my intention. I wanted to save the output node of my network while going through my validation set. So, instead of specifying
outputNodeNames = "labels"
I should have specified
outputNodeNames=LSTMoutputW1
as LSTMoutputW1 happens to denote my output node.

I would like to thank Frank Seide for helping me with this issue.

Slawek

**Comment by XiaoWanLINJU** [comment]
but there is nothing about the 'Features'?
