### ISSUE TITLE
Cntk packages do not support OpenMPI 2+; Ubuntu no longer ships 1.*

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#3197]
The documentation tells me: https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-python?tabs=cntkpy251
> CNTK requires OpenMPI 1.10.x to be installed on your system. On Ubuntu 16.04 install it like this:

`sudo apt-get install openmpi-bin`

But the lowest version fopr Ubuntu 17.10 is 2.1.1-6. https://packages.ubuntu.com/artful/openmpi-bin

How can I install CNTK on a modern cloud Ubuntu version?

**Comment by haixpham** [comment]
You would have to download OpenMPI 1.x source code and build it, then set path to its .so. I did this all the time, since I don't have admin right on the training servers.

**Comment by thiagocrepaldi** [comment]
Look at line 46 on CNTK dockerfile for an example on how to compile openmpi 1.10: https://github.com/Microsoft/CNTK/blob/master/Tools/docker/CNTK-GPU-Image/Dockerfile

**Comment by Ark-kun** [comment]
The Dockerfile hack can work in some scenarios, but it's not quite suitable for online Jupyter-like environments (e.g. Google Colab).

**Comment by nskool** [comment]
Are there plans to support CNTK with OpenMPI >=2? Or does the support already exist? The documentation here says 'at least' v1.10 : https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Linux

However, I have not been able to setup cntk with versions >= 1.10. Has this already been fixed?

**Comment by Ark-kun** [comment]
@thiagocrepaldi Looks like this is still not fixed. Does CNTK officially only support legacy systems?

**Comment by nskool** [comment]
Has anyone got CNTK working with OpenMPI >=2 ?

**Comment by TheButlah** [comment]
This should not be closed

**Comment by thiagocrepaldi** [comment]
OpenMPI 2.x is not in the current roadmap, but contributions are really appreciated :)

**Comment by oxihormesis** [comment]
Re: Anyone with CNTK working from OpenMPI >=2?

**Comment by datdinhquoc** [comment]
uh, hey, why close, CNTK is still not working with OpenMPI 2

**Comment by haixpham** [comment]
> uh, hey, why close, CNTK is still not working with OpenMPI 2

You can build OpenMPI 1.x from source and that's it, taking about 10 minutes. No pain no gain!

**Comment by datdinhquoc** [comment]
> > uh, hey, why close, CNTK is still not working with OpenMPI 2
> 
> You can build OpenMPI 1.x from source and that's it, taking about 10 minutes. No pain no gain!

yeah, real pain!
