### ISSUE TITLE
Python bug: `name` not used in parameter names

### ISSUE THREAD

**Issue by nietras** [microsoft/CNTK#3199]
If you write:
```python
net = C.layers.Convolution((3, 3), 128, pad=True, name='Conv1')(input)
```
and then get the parameters of the `net`:
```python
for parameter in net.parameters:
    print(parameter.name, parameter.shape, "\n") 
```
then the `parameter.name` does not have `Conv1` in the name, making parameter debugging and tracing etc. hard. This seems like a clear bug to me.

This is the same for batch normalization too. And it seems other "layers" with parameters too.

CNTK 2.5.1 on Windows 10 in Python 3.6.

**Comment by min6434** [comment]
If you need to use that function right away, try this code, it works for me.
`layer = net.find_by_name('Conv1')`
I use CNTK 2.4 on ubuntu 16.04.
