### ISSUE TITLE
Scaling a input_variable (tensor) with another input_variable (scalar)

### ISSUE THREAD

**Issue by 2wins** [Microsoft/CNTK#3201]
Is it possible to scale a `input_variable` with a scalar that is also `input_variable`?
I think CNTK should provide a type of `Input('Input1', [1])` as well.

Currently, typing `cntk.input_variable(1)` outputs `Input('Input1', [#], [1])` where `#` is the number of samples.

**Comment by haixpham** [comment]
You can use cntk.constant to contain the scalar.

**Comment by 2wins** [comment]
@haixpham As I know, we cannot feed data into `cntk.constant` during network training.

**Comment by bencherian** [comment]
@2wins This doesn't really make sense with the typical concept of minibatching. If you assume that a minibatch is a random sampling of the training dataset, then why would different minibatches have different inputs for this value, but all the samples within the minibatch have the same value?

If you really need to do this for some reason, it's reasonably straightforward to simply replicate your single input value to match the number of samples in your deserializer or whatever other code you are using for your minibatch source.

**Comment by 2wins** [comment]
@bencherian I agree with you partly. Sometimes we need to put a scalar value into the processing.
I hope CNTK provideㄴ an additional argument for `cntk.input_variable` to have its specific shape as well as in a mini-batch form.

**Comment by haixpham** [comment]
@2wins You can assign a scalar to each training sample as part of minibatch data input as @bencherian said, if your scalar(s) is not predetermined.

**Comment by bencherian** [comment]
Another work around if you are running a manual training loop would be to call `cntk.assign` to change the value of a constant prior to the actual training step.

**Comment by 2wins** [comment]
@haixpham @bencherian Thank you all. Using `cnkt.consatnt` with `cntk.assign` together seems best for now.
