### ISSUE TITLE
Compiling on Power 8 (ppc64le)

### ISSUE THREAD

**Issue by jtfogarty** [microsoft/CNTK#3205]
@thiagocrepaldi 

Hi Thiago,  
We are attempting to compile mmlspark on IBM Power 8. We get pass CNTK configuration and dependencies but when we attempt compilation we encountered the below;

fatal error: x86intrin.h: No such file or directory

Any ideas how to resolve this?

Thanks for your help

https://github.com/Azure/mmlspark/issues/303

**Comment by thiagocrepaldi** [comment]
I am not familiar with development on Power8, but each platform has its own development libs/headers.
Did you try https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa ?
