### ISSUE TITLE
CNTK - splice array of tensors

### ISSUE THREAD

**Issue by itamargr** [Microsoft/CNTK#3219]
Hi.

I have an array of unknown number of tensors that I want to splice
When I do:
```
            last_layer_arr = [cntk.softmax(t) for tin tensor_arr]
            united = cntk.splice(last_layer_arr)
```
I get an error massage:

> TypeError: cannot convert list element to CNTK::Variable

Who can I do this splice ?

Thanks, Itamar

**Comment by delzac** [comment]
I think you need to unpack the list. Try C.splice(*last_layer_arr)

**Comment by itamargr** [comment]
Thank you. It worked
