### ISSUE TITLE
OBJECT DETECTION

### ISSUE THREAD

**Issue by JONYJONS** [Microsoft/CNTK#3227]
There is an error in the training stage, when  the input image data (bounding boxes or labes, files)appears a single object,  in CNTK version 2.2.  

The error doesn't appear when there is more than one object in the input image data.

The error message is,
C:\Users\USER\AppData\Local\Programs\Python\Python35\Lib\site-packages\CNTK-Samples-2-2\Examples\Image\Detection\utils\annotations>python annotations_helper.py
Traceback (most recent call last):
  File "annotations_helper.py", line 137, in <module>
    create_map_files(data_set_path, class_dict, training_set=True)
  File "annotations_helper.py", line 75, in create_map_files
    gt_annotations = _load_annotation(abs_img_path, class_dict)
  File "annotations_helper.py", line 59, in _load_annotation
    annotations = np.hstack((bboxes, label_idxs))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by KeDengMS** [comment]
Can you print out shape of bboxes and label_idxs? Seems like a bug in data loading. Please send a PR if you have a fix for this.

**Comment by JONYJONS** [comment]
this  is example of bboxes:

294	705	394	805

This  is for label:

car

Both are TSV files, which bring me to another question is this the only file type that is allowed?

The program gives error only, when there is a single object  in the bboxes
and label.

**Comment by JONYJONS** [comment]
Hi, sorry for the late replay.

The  problem caused because I manually changed the data in the TSV files in the grocery model in faster rcnn,  to use with my data. These files didn't have an automatic new line operator at the end  of a line. This caused the errors when

having only one object.  I used other TSV files and the  problem was solved.






________________________________

**Comment by spandantiwari** [comment]
OK, thanks for letting us know.
