### ISSUE TITLE
CNTK failed when build with permissive- + MSVC on windows

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/CNTK#3228]
Build CNTK with permissive- by msvc failed on windows, one probably fix is considerring using '%lld' in the format string.

Repro:
1.git clone https://github.com/Microsoft/cntk D:\CNTK\src
2.open a clean x64 prompt and browse to D:\CNTK\src
3.set CL=/permissive- /wd4643 /wd4244 /wd4326
4.MSBuild /m /p:Configuration=Release_CpuOnly;Platform=x64 /p:WindowsTargetPlatformVersion= 10.0.16299.0 CNTK.sln /t:Rebuild

Failures:
:\cntk\src\source\common\include\ssematrix.h(1638,20): error C2220:  warning treated as error - no 'object' file generated 
d:\cntk\src\source\common\include\ssematrix.h(1638,20): error C2220:         fprintf(f, "row: %d", i);
d:\cntk\src\source\common\include\ssematrix.h(1638,20): warning C4477:  'fprintf' : format string '%d' requires an argument of type 'int', but variadic argument 1 has type 'unsigned __int64'

**Comment by KeDengMS** [comment]
Thanks for the report. Can you submit a PR to cast i to int in fprintf?

**Comment by PhoebeHui** [comment]
Hi KeDengMS,

I try to summit a fix, but blocked by Permission denied when summit a PR.

F:\CNTK\src> git push --set-upstream origin phoebe/FixIssueWithpermissive-
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': PhoebeHui
Password for 'https://PhoebeHui@github.com':
remote: Permission to Microsoft/cntk.git denied to PhoebeHui.
fatal: unable to access 'https://github.com/Microsoft/cntk/': The requested URL returned error: 403

Then I tried to change to SSH, it continues fails, I just think if I need request some permission from CNTK?
•	git remote -v
•	git remote rm origin
•	git remote add origin git@github.com:Microsoft/CNTK.git

F:\CNTK\src>git push --set-upstream origin phoebe/FixIssueWithpermissive-
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Thanks,
Phoebe

**Comment by KeDengMS** [comment]
Hi Phoebe,

Thanks for your contribution. Please follow [the GitHub instructions](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) to create a PR from your fork.

**Comment by PhoebeHui** [comment]
Thanks you KeDengMs for your guidance! I summited a PR, could you help review?

**Comment by PhoebeHui** [comment]
Thank you KeDengMs for signing off the PR https://github.com/Microsoft/CNTK/pull/3374 !

The CLA signed, how to merge the changes to master? I go through https://help.github.com/articles/merging-a-pull-request/, and found there is no 'Merge pull request' in this page, do I need additional action?

Thanks,
Phoebe

**Comment by KeDengMS** [comment]
@PhoebeHui, thanks for your contribution. The PR has been merged.
