### ISSUE TITLE
Need documentation on dynamic axis 'math'

### ISSUE THREAD

**Issue by fwaris** [Microsoft/CNTK#3230]
It is not clear or intuitive how dynamic axes are resolved across the composition of various operations especially in the case of sequence-to-sequence models with recursion.

In trying to implement the Python Unfold operation in .Net, I end up with the following dynamic axes:
```
{m_staticAxisIdx=2147483647 m_name=L"whereNodeDynamicAxis_conditionVar_ReconcileDynamicAxis3918_Output_0" ...}

```
And a resulting 'axes mismatch' error.

I tried to go through the source to understand but found it difficult to distill the high-level concepts about axes resolution from this exercise. 

I speak for myself but I believe the community will appreciate if someone from the CNTK team is able to document how this all works.

Thanks,

Faisal

**Comment by KeDengMS** [comment]
Here's [the basic concepts for sequence axis](https://cntk.ai/pythondocs/sequence.html). You can also check [Tutorial 303](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_303_Deep_Structured_Semantic_Modeling_with_LSTM_Networks.ipynb) as an example of using different sequence axes.

Some operators can generate new sequence axis, and some operators expects input to have same sequence axis. If you have a mismatch, and the lengths of two sequence axis are the same, you can use [broadcast_as](https://www.cntk.ai/pythondocs/cntk.ops.sequence.html#cntk.ops.sequence.broadcast_as) to let operators treat them as compatible. Note that broadcast_as only get the semantic check to pass, and at runtime, the actual length will be checked again to make sure length matches.

**Comment by fwaris** [comment]
thanks. I will study these and close the issue for now
