### ISSUE TITLE
SWIG director method error on a custom data set - Faster rCNN

### ISSUE THREAD

**Issue by dregala3** [Microsoft/CNTK#3231]
When I run faster rCNN on custom data, I get the following error when I execute
trained_model = train_faster_rcnn(cfg):

Traceback (most recent call last):
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\ops\functions.py", line 1740, in _forward
    state = self.forward(args, outputs, device, outputs_to_retain)
  File ".\utils\rpn\anchor_target_layer.py", line 179, in forward
ValueError: attempt to get argmax of an empty sequence
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File ".\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File ".\FasterRCNN_train.py", line 329, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File ".\FasterRCNN_train.py", line 571, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\train\trainer.py", line 181, in train_minibatch
    arguments, device)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\cntk_py.py", line 2850, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: SWIG director method error.

The code works with microsoft's test data and with one other set of custom data (identifying coke bottles), but not with this current data that I'm working on. I've tried working with the original image sizes as well as increased image sizes of 2000 x 1200 but to no avail. What can be the possible issues with this and how do I resolve it?

**Comment by KeDengMS** [comment]
The real error seems to be `ValueError: attempt to get argmax of an empty sequence`. Please check your data feed. If it's OK, please share a repro.

**Comment by dregala3** [comment]
Thanks for the response @KeDengMS. I have tried 4 other image sets (photos of cars, houses), all of which are giving me the same error. When I trace the error, it seems to be happening in this line (line #179) under anchor_target_layer.py:

 overlaps = bbox_overlaps(
            np.ascontiguousarray(anchors, dtype=np.float),
            np.ascontiguousarray(gt_boxes, dtype=np.float))

Trying to get a print out of anchors right before this line but nothing is printed out. Could it be that all anchors are getting filtered out and so the array becomes empty? I've been playing around with anchor scales at the data config file, anchor_target_layer.py, proposal_layer.py and even the image size at the faster rCNN config file but I'm still getting this error.

Any insights would be appreciated!

**Comment by KeDengMS** [comment]
Yes that means anchors is empty. Please check where it's generated.

**Comment by dregala3** [comment]
@KeDengMS when we went over to debug the code we found that it wasn't the anchors but the ground truth boxes that are empty.

In the forward function in the file anchor_target_layer.py, the gt_boxes are:
array([[[   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.],
        [   0.,  142.,    0.,  142.,    0.]]], dtype=float32)

All of them are labelled background. When the code filters zero padded ground truth boxes out, all of them are removed and the array becomes empty. The anchors are being generated just fine but because there are no gt_boxes, the algorithm doesn't find any overlaps.

**Comment by dregala3** [comment]
@KeDengMS Codes and datasets are in the repository below:
https://github.com/dregala3/ObjectDetect_CNTK_FasterRCNN

**Comment by tjrileywisc** [comment]
I may have perhaps fixed this by recompiling the cython *.pyds in python 3.6 using this repo: https://github.com/MrGF/py-faster-rcnn-windows because I'm no longer seeing this.

**Comment by Ma35131** [comment]
while running frcnn code we are getting this error...Please help to resolve this problem.
we are using 8056 training images.............  

File "run_faster_rcnn.py", line 35, in <module>
    trained_model = train_faster_rcnn(cfg)
  File "/home/bhuvanaj/Desktop/Animal/Detection/FasterRCNN/FasterRCNN_train.py", line 290, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "/home/bhuvanaj/Desktop/Animal/Detection/FasterRCNN/FasterRCNN_train.py", line 328, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "/home/bhuvanaj/Desktop/Animal/Detection/FasterRCNN/FasterRCNN_train.py", line 570, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "/home/bhuvanaj/anaconda3/envs/cntk/lib/python3.6/site-packages/cntk/train/trainer.py", line 181, in train_minibatch
    arguments, device)
  File "/home/bhuvanaj/anaconda3/envs/cntk/lib/python3.6/site-packages/cntk/cntk_py.py", line 3069, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: SWIG director method error.
