### ISSUE TITLE
CNTK failed with error c3861 when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/CNTK#3232]
CNTK failed with error C3861 when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**You can repro this issue as the steps below:**

1. git clone https://github.com/Microsoft/cntk D:\CNTK\src
2. open a clean x64 prompt and browse to D:\CNTK\src
3. set _CL_=/permissive- /wd4643 /wd4244 /wd4326
4. MSBuild /m /p:Configuration=Release_CpuOnly;Platform=x64 /p:WindowsTargetPlatformVersion= 10.0.16299.0 CNTK.sln /t:Rebuild

**Error info:**
D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.cpp(81): error C3861: 'RoundUp': identifier not found
D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.cpp(81): note: 'RoundUp': function was not declared in the template definition context and can be found only via argument-dependent lookup in the instantiation context
D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.cpp(59): note: while compiling class template member function 'size_t Microsoft::MSR::CNTK::DSSMReader<double>::RecordsToRead(size_t,bool)'
D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.cpp(669): note: see reference to class template instantiation 'Microsoft::MSR::CNTK::DSSMReader<double>' being compiled

**Comment by KeDengMS** [comment]
The RoundUp function is defined in DSSMReader.cpp(269), maybe the code needs to be moved before RecordsToRead() for the unreleased vctoolset. Please feel free to submit a PR for this fix.

**Comment by QuellaZhang** [comment]
@KeDengMS Thanks you very much! This issue has gone.
