### ISSUE TITLE
C++ API: How can i set input variable shape?

### ISSUE THREAD

**Issue by fffupeng** [Microsoft/CNTK#3233]
First of all, i am trying to train models on keras with python and save model in '.h5' style. Then ".h5" model can be  tranfer to dnn model.
This is my python code. I can set input shape=(None,None,1) in keras, after this i transfer this model to dnn file which can be used by c++ code.

```
input_shape = (None,None,1)
input_data = Input(shape = input_shape)

def mnist_model(x):
    x = Convolution2D(32,(3,3),padding = 'same',activation = 'relu')(x)
    x = MaxPooling2D((2,2),strides = (2,2))(x)  #14
    x = Convolution2D(64, (3, 3), padding='same', activation='relu')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2))(x) #7
    x = Convolution2D(10, (3, 3), padding='same', activation='relu')(x)
    x = AveragePooling2D((7, 7), strides=(1, 1))(x) #4
    return x
```
In c++ code, the input shape and output shape are shown as follows:
![default](https://user-images.githubusercontent.com/20182561/40771412-da0335b8-64ef-11e8-8e8c-0853e35b2750.png)
how can i set the right shape of input and output when i try to evaluate the dnn model in c++.
The following codes can't work because of the unknown input/output shape.
```
	
	Variable inputVar = m_cur_model->Arguments()[0];
	Variable outputVar = m_cur_model->Output();
	
	ValuePtr inputVal = Value::CreateBatch(inputVar.Shape(), inputData, m_cur_device);

	std::unordered_map<Variable, ValuePtr> inputDataMap = { { inputVar, inputVal } };
	std::unordered_map<Variable, ValuePtr> outputDataMap ={ { outputVar, nullptr } };

	//step 5: Evaluate
	printf("evaluate....");
	m_cur_model->Evaluate(inputDataMap, outputDataMap, m_cur_device);

	printf("get outputVar...");
	ValuePtr p_outputVal = outputDataMap[outputVar];

	// considering batch size, the output is 2D.
	// In fact, batch size = 1.
	vector<vector<float>> outputData;
	p_outputVal->CopyVariableValueTo(outputVar, outputData);
```
Or how can i set the input variable shape?

**Comment by KeDengMS** [comment]
If you created model with FreeDimension, the actual shape is determined when data is fed. Please take a look at [this test](https://github.com/Microsoft/CNTK/blob/5bdaed77b48e61c8eb8ddf50f21bc2013d0f619d/bindings/python/cntk/ops/tests/free_static_axis_test.py) for more understanding of this concept.

**Comment by KeDengMS** [comment]
It's the same concept for Python and C++. `inputVar.Shape()` is not defined, but you can feed data with your desired shape.
