### ISSUE TITLE
gpu docker image not working

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/CNTK#3237]
there is an error in the docker image.

When trying to build, in the section of Kaldi, I get this error:
```
make[3]: Leaving directory '/usr/local/kaldi-c024e8aa/tools/sctk-2.4.9/src/rttm2ctm'
(cd rttmSmooth; make install)
--2018-06-04 06:59:53--  (try: 2)  http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.4.1.tar.gz
Connecting to openfst.cs.nyu.edu (openfst.cs.nyu.edu)|128.122.80.127|:80... 
failed: Connection timed out.
Retrying.

--2018-06-04 07:02:05--  (try: 3)  http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.4.1.tar.gz
Connecting to openfst.cs.nyu.edu (openfst.cs.nyu.edu)|128.122.80.127|:80... failed: Connection timed out.
Retrying.

--2018-06-04 07:04:20--  (try: 4)  http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.4.1.tar.gz
Connecting to openfst.cs.nyu.edu (openfst.cs.nyu.edu)|128.122.80.127|:80... failed: Connection timed out.
Retrying.
```

The issue comes because the correct url to get openfst is http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.4.1.tar.gz

**Comment by thiagocrepaldi** [comment]
That URL is hard-coded inside Kaldi source-code (https://github.com/kaldi-asr/kaldi/archive/c024e8aa.tar.gz), at  tools/Makefile:94

**Comment by thiagocrepaldi** [comment]
I am tracking this issue at https://github.com/kaldi-asr/kaldi/issues/2481

**Comment by thiagocrepaldi** [comment]
Looking at the Kaldi's Makefile, we can see it will fallback to another host that will succeed, allowing the build to succeed. However, we have to wait for the several retries wget try before giving up on the primary host. It took 40 minutes in my machine.

Here is The relevant Makefile snippet:
openfst-$(OPENFST_VERSION).tar.gz:
	wget http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-$(OPENFST_VERSION).tar.gz || \
	wget -T 10 -t 3 http://www.openslr.org/resources/2/openfst-$(OPENFST_VERSION).tar.gz

Using newer versions of Kaldi should decrease the overall wait time when the primary domain is down. I will check this with the team

**Comment by miguelgfierro** [comment]
cool thanks
