### ISSUE TITLE
Evaluate takes longer on second call

### ISSUE THREAD

**Issue by deischi** [Microsoft/CNTK#3239]
I am using the C++ API.

The model takes a ~300x200 image as input, output is a vector of 10 scores.
Evaluation code is as follows (CTimeBlock measure from construction to destruction).
```
	CNTK::Variable inputVar = modelFunc->Arguments()[0];
	CNTK::Variable outputVar = modelFunc->Output();

	CNTK::ValuePtr inputVal;
	{
		CTimeBlock t1("Create");
		inputVal = CNTK::Value::CreateBatch(inputVar.Shape(), inputData, CNTK::DeviceDescriptor::UseDefaultDevice());
	}

	std::unordered_map<CNTK::Variable, CNTK::ValuePtr> inputDataMap = { { inputVar, inputVal } };
	std::unordered_map<CNTK::Variable, CNTK::ValuePtr> outputDataMap = { { outputVar, nullptr } };

	{
		CTimeBlock t1("Evaluate");
		modelFunc->Evaluate(inputDataMap, outputDataMap);
	}

	std::vector<std::vector<float>> outputData;
	CNTK::ValuePtr outputVal = outputDataMap[outputVar];

	{
		CTimeBlock t2("Copy");
		outputVal->CopyVariableValueTo(outputVar, outputData);
	}
```

Interestingly the runtime and memory usage of the evaluation part is highest for the second call.

First execution - I expect that to be slow to load the DLL, and setup everything.

ThreadID 6ea0: [0.001 ms] -  [1] Create (0x0000000108DDF758):  0.37 ms
'worker.exe' (Win32): Loaded 'C:\dev\SystemSource\Binaries\Release\bin\cublas64_80.dll'. Module was built without symbols.
ThreadID 6ea0: [906.452 ms] -  [1] Evaluate (0x0000000108DDF788): 906.17 ms
ThreadID 6ea0: [906.870 ms] -  [1] Copy (0x0000000108DDF7E8):  0.23 ms
ThreadID 6ea0: [907.101 ms] -  [0] vDoWork (0x0000000108DDF7B8): 908.38 ms

Second execution - that is taking ages:
ThreadID 6ea0: [910.072 ms] -  [1] Create (0x0000000108DDF758):  0.46 ms  ( 1.10 Hz)
ThreadID 6ea0: [4231.932 ms] -  [1] Evaluate (0x0000000108DDF788): 3321.53 ms  ( 1.10 Hz)
ThreadID 6ea0: [4232.496 ms] -  [1] Copy (0x0000000108DDF7E8):  0.31 ms  ( 0.30 Hz)
ThreadID 6ea0: [4232.825 ms] -  [0] vDoWork (0x0000000108DDF7B8): **3325.44 ms**  ( 1.10 Hz)

Third and following  - timings get stable (there is slight shift from Evaluate to Copy - but overall time remaings at ~45 ms). 
ThreadID 6ea0: [4235.923 ms] -  [1] Create (0x0000000108DDF758):  0.50 ms  ( 0.30 Hz)
ThreadID 6ea0: [4247.856 ms] -  [1] Evaluate (0x0000000108DDF788): 11.66 ms  ( 0.30 Hz)
ThreadID 6ea0: [4279.833 ms] -  [1] Copy (0x0000000108DDF7E8): 31.79 ms  (62.94 Hz)
ThreadID 6ea0: [4280.042 ms] -  [0] vDoWork (0x0000000108DDF7B8): 47.03 ms  ( 0.30 Hz)

ThreadID 6ea0: [4281.489 ms] -  [1] Create (0x0000000108DDF758):  0.26 ms  (21.81 Hz)
ThreadID 6ea0: [4287.238 ms] -  [1] Evaluate (0x0000000108DDF788):  5.60 ms  (21.99 Hz)
ThreadID 6ea0: [4323.791 ms] -  [1] Copy (0x0000000108DDF7E8): 36.38 ms  (25.39 Hz)
ThreadID 6ea0: [4323.982 ms] -  [0] vDoWork (0x0000000108DDF7B8): 43.81 ms  (21.20 Hz)

If I use "CNTK::Internal::ForceDeterministicAlgorithms()" the peak on the second evaluation disappears, at the cost of higher runtime.
ThreadID 05f8: [0.001 ms] -  [1] Create (0x0000002B3D6FF268):  0.39 ms
'worker.exe' (Win32): Loaded 'C:\dev\SystemSource\Binaries\Release\bin\cublas64_80.dll'. Module was built without symbols.
ThreadID 05f8: [982.988 ms] -  [1] Evaluate (0x0000002B3D6FF298): 982.76 ms
ThreadID 05f8: [983.374 ms] -  [1] Copy (0x0000002B3D6FF2F8):  0.23 ms
ThreadID 05f8: [983.549 ms] -  [0] vDoWork (0x0000002B3D6FF2C8): 984.70 ms

ThreadID 05f8: [985.273 ms] -  [1] Create (0x0000002B3D6FF268):  0.34 ms  ( 1.01 Hz)
ThreadID 05f8: [991.359 ms] -  [1] Evaluate (0x0000002B3D6FF298):  5.93 ms  ( 1.01 Hz)
ThreadID 05f8: [1039.755 ms] -  [1] Copy (0x0000002B3D6FF2F8): 48.23 ms  (119.69 Hz)
ThreadID 05f8: [1039.917 ms] -  [0] vDoWork (0x0000002B3D6FF2C8): 56.24 ms  ( 1.02 Hz)

ThreadID 05f8: [1041.266 ms] -  [1] Create (0x0000002B3D6FF268):  0.25 ms  (17.83 Hz)
ThreadID 05f8: [1046.815 ms] -  [1] Evaluate (0x0000002B3D6FF298):  5.41 ms  (17.86 Hz)
ThreadID 05f8: [1095.642 ms] -  [1] Copy (0x0000002B3D6FF2F8): 48.67 ms  (18.04 Hz)
ThreadID 05f8: [1095.821 ms] -  [0] vDoWork (0x0000002B3D6FF2C8): 55.79 ms  (17.75 Hz)
ThreadID 05f8: [1097.149 ms] -  [1] Create (0x0000002B3D6FF268):  0.22 ms  (17.89 Hz)
ThreadID 05f8: [1102.968 ms] -  [1] Evaluate (0x0000002B3D6FF298):  5.67 ms  (17.89 Hz)
ThreadID 05f8: [1153.092 ms] -  [1] Copy (0x0000002B3D6FF2F8): 49.96 ms  (17.81 Hz)
ThreadID 05f8: [1153.248 ms] -  [0] vDoWork (0x0000002B3D6FF2C8): 57.31 ms  (17.88 Hz)

Can someone explain the peak on the second evaluation? 
Any idea how to avoid that?

Harald

**Comment by deischi** [comment]
The problem can also be seen using the ResNet20 network as it is provided with the examples.

ThreadID 32f0: [1.398 ms] -  [1] Create (0x000000E2637FF2D8):  0.17 ms
'AutoCNSworker.exe' (Win32): Loaded 'C:\dev\SystemSource\Binaries\Release\bin\cublas64_80.dll'. Module was built without symbols.
ThreadID 32f0: [843.188 ms] -  [1] Evaluate (0x000000E2637FF308): 841.60 ms
ThreadID 32f0: [843.575 ms] -  [1] Copy (0x000000E2637FF368):  0.24 ms
ThreadID 32f0: [843.767 ms] -  [0] vDoWork (0x000000E2637FF338): **842.66 ms**

ThreadID 32f0: [844.306 ms] -  [1] Create (0x000000E2637FF2D8):  0.16 ms  ( 1.19 Hz)
ThreadID 32f0: [951.944 ms] -  [1] Evaluate (0x000000E2637FF308): 107.42 ms  ( 1.19 Hz)
ThreadID 32f0: [952.462 ms] -  [1] Copy (0x000000E2637FF368):  0.29 ms  ( 9.19 Hz)
ThreadID 32f0: [952.744 ms] -  [0] vDoWork (0x000000E2637FF338): **108.80 ms**  ( 1.19 Hz)

ThreadID 32f0: [953.622 ms] -  [1] Create (0x000000E2637FF2D8):  0.25 ms  ( 9.16 Hz)
ThreadID 32f0: [956.397 ms] -  [1] Evaluate (0x000000E2637FF308):  2.53 ms  ( 9.14 Hz)
ThreadID 32f0: [956.989 ms] -  [1] Copy (0x000000E2637FF368):  0.36 ms  (225.80 Hz)
ThreadID 32f0: [957.297 ms] -  [0] vDoWork (0x000000E2637FF338):  **4.35 ms**  ( 9.17 Hz)

ThreadID 32f0: [958.108 ms] -  [1] Create (0x000000E2637FF2D8):  0.20 ms  (219.52 Hz)
ThreadID 32f0: [960.739 ms] -  [1] Evaluate (0x000000E2637FF308):  2.42 ms  (223.85 Hz)
ThreadID 32f0: [961.286 ms] -  [1] Copy (0x000000E2637FF368):  0.34 ms  (230.73 Hz)
ThreadID 32f0: [961.593 ms] -  [0] vDoWork (0x000000E2637FF338):  **4.06 ms**  (219.07 Hz)

**Comment by KeDengMS** [comment]
If you are measuring on GPU, please use environment variable CUDA_LAUNCH_BLOCKING=1 to synchronize between GPU and CPU for accurate timing.

**Comment by deischi** [comment]
I have set the variable. Now the timings are "correctly" associated with the calls:

ThreadID 15f0: [1.932 ms] -  [1] Create (0x0000004DAA7FF368):  0.16 ms
'Sworker.exe' (Win32): Loaded 'C:\dev\SystemSource\Binaries\Release\bin\cublas64_80.dll'. Module was built without symbols.
ThreadID 15f0: [887.894 ms] -  [1] Evaluate (0x0000004DAA7FF398): 885.66 ms
ThreadID 15f0: [888.199 ms] -  [1] Copy (0x0000004DAA7FF3F8):  0.17 ms
ThreadID 15f0: [888.372 ms] -  [0] vDoWork (0x0000004DAA7FF3C8): 886.74 ms

ThreadID 15f0: [888.806 ms] -  [1] Create (0x0000004DAA7FF368):  0.11 ms  ( 1.13 Hz)
ThreadID 15f0: [1002.936 ms] -  [1] Evaluate (0x0000004DAA7FF398): **113.97** ms  ( 1.13 Hz)
ThreadID 15f0: [1003.186 ms] -  [1] Copy (0x0000004DAA7FF3F8):  0.11 ms  ( 8.69 Hz)
ThreadID 15f0: [1003.320 ms] -  [0] vDoWork (0x0000004DAA7FF3C8): **114.83** ms  ( 1.13 Hz)

ThreadID 15f0: [1003.723 ms] -  [1] Create (0x0000004DAA7FF368):  0.10 ms  ( 8.70 Hz)
ThreadID 15f0: [1008.550 ms] -  [1] Evaluate (0x0000004DAA7FF398):  4.69 ms  ( 8.70 Hz)
ThreadID 15f0: [1008.785 ms] -  [1] Copy (0x0000004DAA7FF3F8):  0.09 ms  (178.64 Hz)
ThreadID 15f0: [1008.963 ms] -  [0] vDoWork (0x0000004DAA7FF3C8):  5.52 ms  ( 8.70 Hz)

The second call to evaluate takes ages.

**Comment by KeDengMS** [comment]
If `CNTK::Internal::ForceDeterministicAlgorithms()` makes a difference, it's probably due to cudnn convolution algorithm search. Do you have a different batch size in the second call? Algo search happens when convolution input shape changes.

**Comment by deischi** [comment]
All call are with exactly the same arguments.
I see basically the same also with the example "**CNTKLibraryCPPEvalGPUExamples.cpp**. with the following modifications:

`

    FunctionPtr modelFunc = Function::Load(modelFile, device);

	for (int k = 0; k < 10; k++)
	{
		LARGE_INTEGER t1, t2;
		QueryPerformanceCounter(&t1);

[no change]

    outputVal->CopyVariableValueTo(outputVar, outputData);

	QueryPerformanceCounter(&t2);
	LARGE_INTEGER fq;
	QueryPerformanceFrequency(&fq);
	printf("time: %02d %3.2f\n", k, (double(t2.QuadPart) - double(t1.QuadPart)) / double(fq.QuadPart) * 1000.0);

    //PrintOutput<float>(outputVar.Shape().TotalSize(), outputData);
	}`

First call takes longest (I accept that, for initialization), second call to evaluate takes longer then the following (this is what I cannot understand).

**Comment by KeDengMS** [comment]
Can you use Nsight to check what's the diff between the second and third invocation? And please also check if available GPU memory is the same between these two, as cudnn algorithm search is triggered when available GPU memory becomes less.

**Comment by deischi** [comment]
that is a bit difficult - I have never used Nsight. 
It has quite some configuration/parameters - not sure how to run it, so that the output is of any use.

Anyway, the problem is of low priority for me. 
There seems to be no obvious, easy answer. 
We don't need to spend time on further investigation.

**Comment by jaliyae** [comment]
@FDecaYed 

I was abel to repro the issue and do some profiling. I used Resnet18 with CUDA_LAUNCH_BLOCKING =1
![cntk_second_iteration_timing](https://user-images.githubusercontent.com/12703337/42962183-ded75980-8b45-11e8-8cd3-06bcd2f50539.jpg)


as suggested by KeDengMS. The second iteration is taking much longer than the rest of the iterations.

operation                  | iter2 (milliseconds) | iter3 (milliseconds)
forward + backward | 2554.487                 | 184.808
weight update          | 4.335                       | 4.178
total                          | 2558.952                 | 189.056

With node level profiling, as suggested by Ke, we can see that the convolution operations are taking much longer in the second iteration. Please see the attached profile file and the chrome trace output. 

Do you know what is going on?

**Comment by jaliyae** [comment]
Uploading the .json file with a different extension.
[2018-07-19_18-06-11_detail.txt](https://github.com/Microsoft/CNTK/files/2211205/2018-07-19_18-06-11_detail.txt)

**Comment by FDecaYed** [comment]
Yes this is expected behavior.
Because of how graph is generated and memory manger works in CNTK, cudnn algo search actually happens on second iteration(ignoring sized changes which change things). The fisrt iteration, CNTK will initialize the network with minimal memory required. On second iteration, it will use memory left as workspace to try find optimal algorithm.
This is ok for training since lots of iteration happens after these steps. But if your use case just launch the application for several eval, then second iteration may be expensive. But it should still be a lot faster than first iteration anyway

**Comment by jaliyae** [comment]
Thank you Deyu for the explanation. Yes, it is not a concern for training due to many more following iterations. Needs to keep an eye on this for benchmarking though.
