### ISSUE TITLE
Grocery database train_img_file.txt missing

### ISSUE THREAD

**Issue by wajahat57** [Microsoft/CNTK#3243]
Hi 

When running DetectionDemo.py with FasterRCNN, AlexNet base model and Grocery database, I receive the error:
```

 File "C:\CNTK-master\Examples\Image\Detection\utils\od_reader.py", line 89, in _parse_map_files
    with open(img_map_file) as f:
..... DataSets/Grocery\\train_img_file.txt'  FileNotFound Error
```
on checking the corresponding Grocery folder, there is no such file present. 
Redownloaded the dataset, but there is no such file.
Can anyone please suggest where to get this file or how to create one?

Best Regards
Wajahat

**Comment by KeDengMS** [comment]
Maybe run the Grocery [install script](https://github.com/Microsoft/CNTK/blob/release/latest/Examples/Image/DataSets/Grocery/install_grocery.py) first?

**Comment by wajahat57** [comment]
I have done that. It downloaded and unzipped the Grocery dataset. The files were missing.

**Comment by KeDengMS** [comment]
Seems a bug in the code assuming Linux path when you running on Windows. Please change [this](https://github.com/Microsoft/CNTK/blob/0ed295e653421965aa684d8c37fe228b165d3de8/Examples/Image/Detection/utils/annotations/annotations_helper.py#L134) line to:

```
data_set_path = os.path.join(abs_path, "..", "..", "..", "DataSets", "Grocery")
```

I'll create a work item to fix it.

**Comment by wajahat57** [comment]
Thanks. It solved the problem.
