### ISSUE TITLE
Switch between GPU and CPU 

### ISSUE THREAD

**Issue by wajahat57** [Microsoft/CNTK#3251]
Hi 

I am new to CNTK and python.
I have installed cntk-gpu version.

By default, it is configured to use GPU i.e. GTX 1080.
I want to switch it back to CPU.

Is there a way to do it other than uninstalling cntk-gpu and installing cntk
The output of cntk.DeviceDescriptor.all_devices()
is: (GPU[0] GeForce GTX 1080, CPU)

Best Regards
Wajahat

**Comment by bencherian** [comment]
Before running your code, insert the statement `cntk.try_set_default_device(cntk.device.cpu())`

**Comment by wajahat57** [comment]
I have found only:
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
for selecting CPU, and 
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
for enabling GPU works in Windows
NOTE: for multiple GPUs, instead of '0', it will be the number which can be 0,1,2,...

**Comment by ebarsoumMS** [comment]
CUDA_VISIBLE_DEVICES is to hide or not hide CUDA device, but as @bencherian said you can use CPU in your code by adding cntk.try_set_default_device(cntk.device.cpu()) at the top of your Python script.
