### ISSUE TITLE
Gradient check doesn't work?

### ISSUE THREAD

**Issue by kaituoxu** [Microsoft/CNTK#3255]
In directory `CNTK/Tutorials/HelloWorld-LogisticRegression` of the latest CNTK release.
When I run `cntk configFile=lr_bs.cntk`, it works fine.
But when I added `gradientcheck=true` and `precision=double` in this script like below:
```
precision = double
SGD = [
    gradientcheck = true
    ...
]
```
the gradient check failed and logged:
```
###### db######
db Numeric gradient = 1.485961e+06, Error BP gradient = -2.582697e+00

EXCEPTION occurred: cannot pass gradient checker
```
Besides, when I do gradient check in CNTK v2.0, it always fails and shows different exception, such as:
```
EXCEPTION occurred: The slice (0+900) is out of range of the source matrix (1).
```

If gradient check doesn't work, how to check backpropagation implementation in CNTK?

Thanks

**Comment by KeDengMS** [comment]
BrainScript has limited functionality, there also might be bugs in gradient checker in terms of precision. CNTK has Python tests for backprop by comparing with numpy.

**Comment by kaituoxu** [comment]
@KeDengMS Thanks a lot.
