### ISSUE TITLE
what does mbsize and input layer dimension mean in cntk?

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3259]
Hi,

I am using cntk for speaker recognition,
what does mbsize mean in speech example,
`minibatch = data_minibatch_source.next_minibatch(mbsize, input_map = input_map)`
and also I am using 39-dimesional mfcc so what should be the dimension of my input feature vector(input layer dimension)?
Please let me know.
Any suggestion would help
Thank you

**Comment by delzac** [comment]
mb_size is the size of the minibatch that you want to use. In training neural nets, we do not feed in the entire training data all at once.

input_map is a dictionary that contains the mapping of your input_variables to training data. In the case of using minibatchsource, its the name you put in streamdefs. You may want to read [this](https://cntk.ai/pythondocs/Manual_How_to_feed_data.html) to know more.

**Comment by vidyatshetty** [comment]
@delzac  thanks for writing. I am aware that mbsize is number of samples but I am using cntk for speaker recognition problem.  I have set frame_mode= true and if i set mbsize = 8 does it take 8 frames at once? 
also when I am evaluating the model I have code as below,
`mb = test_data_reader.next_minibatch(test_minibatch_size, input_map=test_stream_data)
 eval_error = 1 - trainer.test_minibatch(mb)`
If I give test_minibatch_size = 8 will it take 8 frames or 8 mfc files of 8 speakers? I am confused
If you could provide me more details that would be great.
Thank you

**Comment by delzac** [comment]
I'm not familiar with audio data, but when you print(mb), you would be able to see the shape of the data, perhaps that will help you in your debugging?
