### ISSUE TITLE
Nuget packages don't work under VS2017 with PackageReference setting

### ISSUE THREAD

**Issue by TechnikEmpire** [Microsoft/CNTK#3262]
I was positive that this issue existed already but I could not find it. Creating a new CSproj in Vs2017 with default package management set to `PackageReference` breaks the package. I can add it, but I cannot use or reference it in any way.

Since this issue has been around for a very long time, what's the alternative here? Do I need to build from source (puke) just to be able to use this?

**Comment by vpenades** [comment]
@TechnikEmpire the issue already exists: #2807

**Comment by TechnikEmpire** [comment]
@vpenades Thanks, my bad. Closing in favor of the existing bug.
