### ISSUE TITLE
Faster RCNN for larger images

### ISSUE THREAD

**Issue by dregala3** [Microsoft/CNTK#3265]
I noticed that when I run faster rcnn on large images, the algorithm resizes it into smaller dimensions, leading to a deterioration in image quality and failure of the object detect algorithm. More specifically, I noticed that images with dimensions of around 500x700 work really well as the algorithm does not resize them, but anything more than that results in a blurred out resulting test image.

What arguments or parameters do i need to change to prevent this resizing or to allow the algorithm to accept larger test images?

**Comment by wajahat57** [comment]
I think you need to change the arguments:
__C.IMAGE_WIDTH = 850
__C.IMAGE_HEIGHT = 600 
in FasterRCNN_config.py
in CNTK\Examples\Image\Detection\FasterRCNN

**Comment by dregala3** [comment]
Thank you @wajahat57. I'll try this one. I changed something in the plot_helpers code that got it to work. Follow up question though it might seem idiotic, but do the objects in the training image have to be the same size as the objects in the testing images? Or are there arguments I can modify to indicate the objects in the training images are smaller than the ones in the testing images?

**Comment by wajahat57** [comment]
Size of the objects don't matter much as far as they are big enough to stand down sampling (in Faster RCNN, there is a base network which can down sample the image 6 to 8 times). If your images are too small, even training won't work.
In that case, you will need to change the base net to a network that uses fewer max pooling layers.
Generally, you should not be having such a problem, unless you are implementing Faster RCNN on a very different dataset. 
The second thing that can affect is the aspect ratio of the object hight/width. 
This can be controlled through the ratios argument.

**Comment by dregala3** [comment]
Thanks @wajahat57. I am messing around mostly with anchor sizes but I will check out the aspect ratio too. Isn't it the case that the algorithm draws the same anchor sizes for the train and test images? If so, wouldn't it be better if the objects in your train and test images are the same size?

**Comment by Jayu8** [comment]
Hi @wajahat57, 
What do you mean by adjust the ratios argument?
Do  we have to resize the images to the aspect ratio on the data on our own and corresponding annotations? 
Or does CNTK have a method/argument to resize it according to the aspect ratio?

**Comment by wajahat57** [comment]
No. You have to adjust the arguments regarding the ROIs in the corresponding config file, such as Grocery_config.py if training on Grocery dataset in : 
`CNTK\Examples\Image\Detection\utils\configs`

`# maximum aspect ratio of an ROI vertically and horizontally`
`__C.roi_max_aspect_ratio = 4.0`
and maybe the relative area parameters as well in the same config file.

These arguments might have been better explained in the Fast RCNN paper.

**Comment by wajahat57** [comment]
I think it is for the training images

**Comment by dregala3** [comment]
@wajahat57 i cannot confirm if it's for the training images but it definitely worked for the test images. changing it to a larger size worked in evaluating larger images. thanks a lot!

**Comment by wajahat57** [comment]
welcome
