### ISSUE TITLE
Allow building a C++ lib separately

### ISSUE THREAD

**Issue by KOLANICH** [Microsoft/CNTK#3269]
I mean that now cmake script builds C++ libs as a part of building process of C# libs. What if I don't need C# libs?

**Comment by KeDengMS** [comment]
@davidbrownellMS , do we have a way to make C# build in CMake optional?

**Comment by davidbrownellMS** [comment]
cmake is not fully supported at this time, and its use is restricted to support C# projects (which is a work in progress).

When building on Linux, csharp support is currently disabled during configuration. In the near future, we plan to enable csharp builds during configuration if its dependencies are found on the system (dotnet, swig, and cmake).
