### ISSUE TITLE
Is GPUDirect RDMA supported in CNTK?

### ISSUE THREAD

**Issue by Tagussan** [Microsoft/CNTK#3270]
Hi, CNTK developer team,

Sharing data between nodes is said to be one of bottleneck in distributed machine learning. I'm now studying HPC, so wanted to try GPUDirect RDMA to improve performance. I found that [GPUDirect RDMA is available for CNTK](https://github.com/Microsoft/CNTK/wiki/CNTK_2_0_RC_2_Release_Notes). 

I built CNTK manually, enabling GPUDirect by running configure with --gdr=yes. I tried some examples, e.g., [06_OneConvRegrMultiNode](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/GettingStarted/06_OneConvRegrMultiNode.cntk)

I prepared two identically configured machine and two machines are connected with Infiniband:
CPU: Xeon Silver 4108 @ 1.80GHz x1
GPU: Quadro P2000 x1
Network: Mellanox Infiniband MT27500 (with MLNX_OFED_LINUX 4.3-3 driver)
RAM: 24GB

However, the performance does not improved at all. So I read source code of CNTK and found that some codes calling function to enable CUDA peer access is commented out in master branch: [GPUSparceMatrix.cu](https://github.com/Microsoft/CNTK/blob/master/Source/Math/GPUSparseMatrix.cu#L386) and [GPUMatrix.cu](https://github.com/Microsoft/CNTK/blob/master/Source/Math/GPUMatrix.cu#L379).

Is GPUDirect RDMA not supported in the latest CNTK?

Thank you

**Comment by KeDengMS** [comment]
For distributed training on Linux, CNTK uses NCCL2 now for GPUDirect RDMA.

**Comment by Tagussan** [comment]
@KeDengMS I installed NCCL2 following installation manual. After I run [nccl-test](https://github.com/NVIDIA/nccl-tests) and confimed NCCL2 installation was successful, I run 06_OneConvRegrMultiNode.

However, performance does not change at all. I googled for usage of NCCL2, then I found [this issue](https://github.com/Microsoft/CNTK/issues/1510). 

Is NCCL2 available for multinode training?

**Comment by Tagussan** [comment]
If I use ASGD, performance does not change at all. If SGD is used, NcclComm failed to initialize message appear.

**Comment by Tagussan** [comment]
After I read [this article](https://docs.microsoft.com/en-us/cognitive-toolkit/releasenotes/cntk_2_2_release_notes#system), I tried export NCCL_IB_HCA=mlx4_0 and NCCL2 worked well! 
Thank you!

**Comment by KeDengMS** [comment]
Glad to see. Closing the issue now.
