### ISSUE TITLE
DNN for speaker recognition

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3274]
Hi,

@KeDengMS  I am using cntk for speaker recognition, I am using 39 dimensional mfcc feature. I would like to train 5frames before and 5frames after the current frame at once. I  quiet don't understand how  to implement this in cntk.
`features_data = C.io.HTKFeatureDeserializer(StreamDefs(features = StreamDef(shape = feature_dimension,context=(context,context),scp = feature_file)))`
what does context=(context,context) do?
Please let me know.
Thank you

**Comment by KeDengMS** [comment]
I don't have the answer off-hand, but I'd start by having some very simple data file, and dump the output from it to confirm the behavior. + @vmazalov who may give you a more direct answer.

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing. @vmazalov  Could you please tell me how to train 5frames before and 5frames after the current frame. I am using fully connected 3 dense layer each of which consists of 1000 hidden units.
