### ISSUE TITLE
ValueError: Specified GPU device id (0) is invalid

### ISSUE THREAD

**Issue by hyoeun27** [Microsoft/CNTK#3278]
Examples/Images/TransferLearning/TransferLearning.py

When I implement TransferLearning.py ,
I get error.

Traceback (most recent call last):
  File "TransferLearning.py", line 200, in <module>
    try_set_default_device(gpu(0))
  File "C:\ProgramData\Anaconda2\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\ProgramData\Anaconda2\lib\site-packages\cntk\device.py", line 96, in gpu
    return cntk_py.DeviceDescriptor.gpu_device(device_id)
ValueError: Specified GPU device id (0) is invalid.

[CALL STACK]
    > CNTK::Parameter::  SetValue
    - CNTK::DeviceDescriptor::  GPUDevice
    - CreateDeserializer
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx
    - PyEval_EvalCodeEx
    - PyFunction_SetClosure
    - PyObject_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx
    - PyEval_EvalCodeEx
    - PyEval_GetFuncDesc (x2)
    - PyEval_EvalFrameEx
    - PyEval_EvalCodeEx

===================================

C:\Users\user\CNTK\Tutorials\NumpyInterop>python FeedForwardNet.py
Selected CPU as the process wide default device.
-------------------------------------------------------------------
Build info:

                Built time: Apr 13 2018 22:36:42
                Last modified date: Fri Apr 13 22:27:37 2018
                Build type: Release
                Build target: CPU-only
                With ASGD: yes
                Math lib: mkl
                Build Branch: HEAD
                Build SHA1: 11c82c8019b78323b4f5169a2d8c90fba5ae49da
                MPI distribution: Microsoft MPI
                MPI version: 7.0.12437.6
-------------------------------------------------------------------
Learning rate per minibatch: 0.5
 Minibatch[   1- 128]: loss = 0.614628 * 3200, metric = 29.25% * 3200;
 Minibatch[ 129- 256]: loss = 0.332382 * 3200, metric = 13.31% * 3200;
 Minibatch[ 257- 384]: loss = 0.298804 * 3200, metric = 11.59% * 3200;
 Minibatch[ 385- 512]: loss = 0.271270 * 3200, metric = 10.44% * 3200;
 Minibatch[ 513- 640]: loss = 0.247776 * 3200, metric = 9.03% * 3200;
 Minibatch[ 641- 768]: loss = 0.231605 * 3200, metric = 9.06% * 3200;
 Minibatch[ 769- 896]: loss = 0.229529 * 3200, metric = 8.62% * 3200;
 Minibatch[ 897-1024]: loss = 0.214106 * 3200, metric = 8.25% * 3200;
Finished Epoch[1]: loss = 0.305012 * 25600, metric = 12.45% * 25600 1.198s (21368.9 samples/s);
 error rate on an unseen minibatch 0.040000

===============
I want to use CPU.

**Comment by delzac** [comment]
instead of try_set_default_device(gpu(0)) at line 200, perhaps you can set it to try_set_default_device(cntk.cpu())

**Comment by hyoeun27** [comment]
Thankyou.
I solved problem.

**Comment by hyoeun27** [comment]
Thankyou.
I solved problem.
