### ISSUE TITLE
Is it possible to use maxout layer with cntk?

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3279]
Hi,

I have a model with dense layers. I would like to use maxout layer after the 2nd dense layer. I know how to do it for CNN but I don't know if I can use it with DNN. any suggestion will help me.
Thank you

**Comment by jaliyae** [comment]
You could try a dense layer with C.hardmax as the activation.

**Comment by vidyatshetty** [comment]
@jaliyae Thank you for writing. I will try C.hardmax.
Also, Could you please look into #3274 and suggest something on that.
Thank you

**Comment by KeDengMS** [comment]
https://stats.stackexchange.com/questions/129698/what-is-maxout-in-neural-network/298705#298705

It may be written in CNTK with following:
```
import cntk as C
x = C.input_variable((input_dim))
m1 = C.Dense(maxout_dim)(x)
m2 = C.Dense(maxout_dim)(x)
maxout = C.element_select(C.greater(m1,m2), m1, m2)
```

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing. This was really helpful.
