### ISSUE TITLE
Retraining an existing model

### ISSUE THREAD

**Issue by axonUH** [Microsoft/CNTK#328]
Hi,
I'm interested in re-training a CNTK model with new training data once a model has been set up. For instance, if I run the Simple2D Example (https://github.com/Microsoft/CNTK/tree/master/Examples/Other/Simple2d), the model is placed in the Output/Models folder. (I'm running CNTK using binaries in Windows7). The final model exists as simple.dnn. I would like to re-"train" this model with new training data. At the moment, when I try to re-run the training script, it says "Final model exists: ../Output/Models/blah.dnn ----No further training is necessary." Is it possible to continue training the existing model with new data?

Thanks

**Comment by yzhang87** [comment]
Hi, 

Just change simple.dnn to simple.dnn.0, it will retrain it again.

Basically, if your final model is xxxx.model, the first epoch will start from xxxx.model.0

thansk,

**Comment by ant0nsc** [comment]
Works like a charm - thanks @yzhang87 !

**Comment by axonUH** [comment]
Yes, thanks.
