### ISSUE TITLE
CUDNN failure during distributed learning

### ISSUE THREAD

**Issue by dregala3** [Microsoft/CNTK#3281]
I am executing distributed learning using the FasterRCNN_train code modified by @kyoro1  https://github.com/Microsoft/CNTK/blob/kyiwasak/faster-rcnn-distributed/Examples/Image/Detection/FasterRCNN/FasterRCNN_train.py 
using 2 Tesla K80 GPUs. However, I get the ff. error:

CUDA failure 2: out of memory ; GPU=0 ; hostname=dlvm-nc12 ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * AsMultipleOf(numElements, 2))
Retrying with reduced workspace memory for convolution
CUDA failure 17: invalid device pointer ; GPU=0 ; hostname=dlvm-nc12 ; expr=cudaFree((void*) bufferPtr)
Retrying with reduced workspace memory for convolution
cuDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=dlvm-nc12 ; expr=finder(calgo, algoPerf)
Fall back to use static finder to get the algorithm for convolution
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=dlvm-nc12 ; expr=cudnnConvolutionBackwardData(*m_cudnn, &C::One, *m_kernelT, ptr(kernel), m_outT, ptr(srcGrad), *m_conv, m_backDataAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), accumulateGradient ? &C::One : &C::Zero, m_inT, ptr(grad))
Using base model:   VGG16
lr_per_sample:      [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 1e-05]
Training model for 20 epochs.
Training 136510804 parameters in 32 parameter tensors.
PROGRESS: 0.00%
Traceback (most recent call last):
  File "train_model_multiplegpu.py", line 43, in <module>
    trained_model = train_faster_rcnn(cfg)
  File "C:\dsvm\samples\CNTK-Samples-2-5-1\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "C:\dsvm\samples\CNTK-Samples-2-5-1\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 333, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "C:\dsvm\samples\CNTK-Samples-2-5-1\Examples\Image\Detection\FasterRCNN\FasterRCNN_train.py", line 589, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\train\trainer.py", line 181, in train_minibatch
    arguments, device)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\cntk\cntk_py.py", line 2853, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=dlvm-nc12 ; expr=cudnnConvolutionBackwardData(*m_cudnn, &C::One, *m_kernelT, ptr(kernel), m_outT, ptr(srcGrad), *m_conv, m_backDataAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), accumulateGradient ? &C::One : &C::Zero, m_inT, ptr(grad))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::DataTransferer::  operator= (x3)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)

I use CUDA version 8 and CUDNN version 6. I've tried so many things to get distributed learning to work, including editing my own code to allow for distributed learning and using @kyoro1 's version. None are working and I always get memory failure. The image sizes I use for training aren't even too big. In fact, when I use only one GPU (i.e. when I do not run the code using mpiexec) I don't get any errors. It is only when I try to activate both GPUs that I am getting this issue.

Any idea on how to resolve this? Your thoughts would be much appreciated!

**Comment by kyoro1** [comment]
Hi @dregala3 . Can you provide some information on your environment?

1. cntk version
  --> Is it 2.5.1..?
2. Do you use GPU for computing NMS? [Here](https://github.com/Microsoft/CNTK/blob/85772225630ea7962d4771e05d7067274d228b07/Examples/Image/Detection/FasterRCNN/FasterRCNN_config.py#L145) is the parameter, which should be 
```
__C.USE_GPU_NMS = False
```
This is because GPU NMS function may have some bug at least some months ago, as far as I know.

3. Base Model = AlexNet?
  I have not tried out VGG as base model for Faster R-CNN. So, can you change your base-model to AlexNet?

Also, here is my experiment in May, and I could execute Faster R-CNN with basemodel = AlexNet. Hope it helps:
https://github.com/kyoro1/decode2018/blob/master/2.%20distributed%20learning%20with%20Faster%20R-CNN.ipynb

Finally, my branch is not official implementation in CNTK. I can put my comments as far as I know, but I'm not sure that it can be supported at least by me..

**Comment by dregala3** [comment]
Thank you, @kyoro1! My code started working. However, when I increase the image size (trying Faster RCNN on large images is my primary reason for using multiple GPUs), I would get an error. I understand though that might not be something you have worked on. But if you have, please let me know what I can try to make it work!
