### ISSUE TITLE
Please provide a "Hello World" sample using C# and MLP?

### ISSUE THREAD

**Issue by sdg002** [Microsoft/CNTK#3282]
Hi All,
It would be immensely valuable if the team can provide hello world samples using C# and multi-layer perceptron that demonstrate the following:

1. Do a simple linear classification (1 node)
2. Use a hidden layer to solve the XOR problem.

While these are very elementary from a functional point of view, I believe they would greatly aid in learning the nuts and bolts of the CNTK API before moving on to the the classical MNIST sample.

Thanks,
Sau

**Comment by KeDengMS** [comment]
Would [this test](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/CNTKv2CSharp/CNTKLibraryCSTrainingTest/SimpleFeedForwardClassifierTest.cs) be helpful?

**Comment by sdg002** [comment]
Yes. Much better that MNIST for a starter application. How much data does this test need?

**Comment by KeDengMS** [comment]
The model is simple and data size smaller than MNIST.
