### ISSUE TITLE
Dynamically compute delay

### ISSUE THREAD

**Issue by VHellendoorn** [Microsoft/CNTK#3288]
Is there any way to delay a sequence by a dynamically computed number of steps? Ideally, I would be able to use two sequence inputs, where one provides offsets to delay the hidden state by, as in this toy example:
```python
base_gru = C.layers.GRU(100)
def custom_gru(dh, x):
	o = C.ops.slice(x, 0, -1, 0)
	x = C.ops.slice(x, 0, 0, -1)
	return base_gru(C.sequence.delay(dh, time_step=o), x)

input = C.sequence.input_variable(10, name="input")
offset = C.sequence.input_variable(1, name="offset")
rnn = C.layers.Recurrence(custom_gru)(C.ops.splice(input, offset))
```

**Comment by delzac** [comment]
You cannot put the C.sequence.delay inside the step function. It has to be outside.

Anyhow it looks like you are trying to dynamically pass timesteps from before t -1 into t. This might not be possible, i think.

**Comment by delzac** [comment]
You might want to consider manually rolling.

**Comment by VHellendoorn** [comment]
Thanks for your input. I have been able to make this work by manually looping through steps in the unpacked input sequence, but this means constructing a (possibly) very large explicit computation graph, which gets very slow starting at 100+ nodes. It would be nicer to be able to build dependencies on previous hidden state(s) inside the recurrence, whether it's the previous one or an older one. Doing this with `delay` is perfectly okay even inside the step function: I can replace the `time_step=o` with `time_step=-2` and I will get a recurrence that is conditioned on 3 elements ago instead of the usual 1. If I could make it use an arbitrary (negative) offset through an input variable, that would be great, but since the signature of `delay` expects an `int` I was wondering if there is a work-around. Perhaps `PastValueWindow` could offer something like that?

**Comment by VHellendoorn** [comment]
On second thought, the `time_step=-2` indeed does not work, sorry for that confusion. I suppose the sequence API is not the best way to accomplish this

**Comment by KeDengMS** [comment]
delay is supposed to be literal constant and cannot be computed. You may use sequence.unpack/gather to achieve dynamically computed delay.

**Comment by VHellendoorn** [comment]
Thanks, and do I understand correctly that this cannot be done inside a `Recurrence`?

**Comment by KeDengMS** [comment]
Recurrence can only access sequences in a fixed order. If you need a more dynamic way to access sequence, it is not designed for that.

**Comment by VHellendoorn** [comment]
Great, thanks for the information!
