### ISSUE TITLE
CNTK failed when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/CNTK#3298]
Build CNTK with permissive- by msvc failed with error C2672 error C2780, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**Repro:**
 1.git clone https://github.com/Microsoft/cntk D:\CNTK\src
 2.open a clean x64 prompt and browse to D:\CNTK\src
 3.set CL=/permissive- /wd4643 /wd4244 /wd4326
 4.MSBuild /m /p:Configuration=Release_CpuOnly;Platform=x64 /p:WindowsTargetPlatformVersion=10.0.17134.0 CNTK.sln /t:Rebuild

**Failures:**
d:\cntk\src\source\common\include\stringutil.h(54): error C2672: 'std::tolower': no matching overloaded function found
d:\cntk\src\source\common\include\stringutil.h(63): note: see reference to function template instantiation 'bool Microsoft::MSR::CNTK::AreEqualIgnoreCase<wchar_t>(const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &,const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &)' being compiled
d:\cntk\src\source\math\convolutionengine.h(116): note: see reference to function template instantiation 'bool Microsoft::MSR::CNTK::AreEqualIgnoreCase<std::wstring>(const TString &,const wchar_t *)' being compiled
        with
        [
            TString=std::wstring
        ]
d:\cntk\src\source\common\include\stringutil.h(54): error C2780: '_Elem std::tolower(_Elem,const std::locale &)': expects 2 arguments - 1 provided
c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.14.26428\include\locale(274): note: see declaration of 'std::tolower'

**Comment by PhoebeHui** [comment]
Any updates?

**Comment by davidbrownellMS** [comment]
A fix for this has been checked into master: https://github.com/Microsoft/CNTK/commit/ee2fa5e70d458917a3cd58e7049a5f67470513de.

**Comment by QuellaZhang** [comment]
@davidbrownellMS Thank you very much! this issue has gone.
