### ISSUE TITLE
How to load model in c#. It gives bad image error

### ISSUE THREAD

**Issue by CWD4RKC0D3R** [Microsoft/CNTK#3306]
I tried to save a model via python cntk. When i tried it, it gave me error that onnx doesnt support placeholders. Then i tried it for cntkv2 modelformat. it worked. Then i tried to load data from c# app.
It gave me an error.

"System.BadImageFormatException: 'Could not load file or assembly 'Cntk.Core.Managed-2.5.1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a82c1f3f67b62253' or one of its dependencies. An attempt was made to load a program with an incorrect format."

someone got the same error: [link](https://github.com/Microsoft/CNTK/issues/2250
)

            public void TestSaveAndLoad()
            {
                        int channels = 2;
                        int imageWidth = 40, imageHeight = 40;
                        int[] inputDim = { imageHeight, imageWidth, channels };
                        Variable input = CNTKLib.InputVariable(inputDim, DataType.Float, "Images");
                        Parameter param = new Parameter(inputDim, DataType.Float, CNTKLib.GlorotUniformInitializer(0.1F, 1, 0), DeviceDescriptor.CPUDevice);
                        Function model = CNTKLib.Plus(input, param, "Plus");
                        byte[] buffer = model.Save();                        
                        Function loadedModel = Function.Load(buffer, DeviceDescriptor.CPUDevice);

             }

I tried this code above to test. it gave the same error too. pls fix this.

**Comment by Tixxx** [comment]
Hi @CWD4RKC0D3R  I just tested this code with a simple console app proj and the model was successfully loaded for me. Could you share your project's build configuration? The app has to be built strictly with x64 architecture.

**Comment by TrifonT** [comment]
Instead of compiling your project as "Any CPU", try compiling it as "x64"

**Comment by CWD4RKC0D3R** [comment]
Yeah thank you so much. It works now.

**Comment by JagathPrasad** [comment]
@TrifonT, Thanks for your valuable idea, I was trying with "Any CPU" with "x64" , it was not working.
then I have tried as you have said created the "x64" compiled its working.
