### ISSUE TITLE
error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props" was not found.

### ISSUE THREAD

**Issue by QueyLai** [Microsoft/CNTK#3318]
I downloaded Windows-driver-samples-master.zip and wanted to use the sample project usb/usbview.
I tried to compile this project with Visual Studio Community 2017 Version 15.7.5.
The error message came as follow:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Redirect.14.props(47,3):
error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props" was not found.
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Please help me to solve this problem and build up it to run.
Many thanks.

**Comment by kit1980** [comment]
Is this related to CNTK (deep learning toolkit) or you meant to open this issue in a different repository?

**Comment by QueyLai** [comment]
I don't know about that, I am new here.
So embarrassing ......

**Comment by QueyLai** [comment]
Oh, Thanks for the info.
