### ISSUE TITLE
do parallel LM trainers read the same minibatches?

### ISSUE THREAD

**Issue by alahiri-quora** [Microsoft/CNTK#332]
Hi all,
I was wondering how parallel training works in Language Modeling. Do all of the separate MPI processes make sure they are reading different sequences in, or is there overlapping or is it completely agnostic what other processes are training on for each epoch?
Are there any parameters to control this? E.g., an overlap parameter.

Thanks!
Abhik

**Comment by wolfma61** [comment]
readers have been reworked significantly, but in general are optimized to efficiently distribute the work-load in the distributed scenarios. Currently the reader documentation is located here: https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-Reader-Block, but might be reworked / updated in the future
