### ISSUE TITLE
evaluate  an ResNet-34 models in Python

### ISSUE THREAD

**Issue by height1987** [Microsoft/CNTK#3321]
I am learning BrainScript(ResNet-34) and the config files using the  demo and my own 224x224x3 images. 
script : [https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ResNet/BrainScript/ResNet34_ImageNet1K.cntk](url)

meanfile:[https://github.com/Microsoft/CNTK/blob/master/Examples/Image/DataSets/ImageNet/ImageNet1K_mean.xml](url)

and finally I get the models.
But I can't find  the "XX.dnn" file which needed in many  evaluate demos.
like [https://docs.microsoft.com/en-us/cognitive-toolkit/how-do-i-evaluate-models-in-python](url)

although the demo shows a way to load the BrainScript result ,but i still can't understand how to load the models.Is there any more demo or instruction for my case?
 
thanks! any help would be appreciated.

**Comment by jaliyae** [comment]
The .dnn file is the model you save to a file using model.save() method. The instruction at the page you mentioned says:
"you saved your model in Python using z.save("mycnn.dnn")"

Does this help?

**Comment by height1987** [comment]
@jaliyae Thanks ！ 

I used `cntk configFile=ResNet34_ImageNet1K.cntk`  command to train the models,
where can i use `z.save("mycnn.dnn")` to save the models.
Can i add same command in that   configFile to solve this ?
Or  can i run another python script to save the models  by using the result of `cntk configFile=ResNet34_ImageNet1K.cntk`?

**Comment by height1987** [comment]
@jaliyae Thanks a lot ! 
i to decide to follow your recommendation.
I'm trying to use
 [python script](https://github.com/Microsoft/CNTK/blob/v2.5.1/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10.py) 
to train .
For now, it is running, but i can't find any log which shows the epoch. 
i'm using cpu-only way, How can i know when it will end ?
