### ISSUE TITLE
LMSequenceReader? How to build sentence classification model using LSTM

### ISSUE THREAD

**Issue by 1026112881** [Microsoft/CNTK#333]
Hi,
I want to build a sentence classification model (for example sentiment classification) using LSTM, can anyone give me some examples or some guidance about CNTK? I have read the CNTKbook and the examples of CNTK, but I still don't know how to do with it.

**Comment by alahiri-microsoft** [comment]
LMSequenceReader is for language modeling tasks... I think you're looking for something like the LUSequenceReader. Check out an example for that and see if that works for your input files.
Also, choice of reader depends on how your data is represented in the input file and how you would like it to be processed.

**Comment by 1026112881** [comment]
Hi, I had seen the example in Tests\EndToEndTests\SLU. But seems it aims to label each word in the sentence. What I want is to label each whole sentence. I think they are two kinds of tasks. Or maybe LUSequenceReader has some other application examples which can satify mine?

**Comment by wolfma61** [comment]
This has been dormant for a long while, the CNTKTextFormat-Reader might be solution (https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-CNTKTextFormat-Reader). Please open a new issue if required.
