### ISSUE TITLE
DNN for speaker recognition

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#3330]
@KeDengMS  I am using cntk for speaker recognition system. I am using TIMIT database and designing a system for 20 speakers. I am using direct method DNN for training. My model consists of 3 hidden layers and 1000 hidden units/layer. I have 8 sentences for training and 2 for testing.  However I am not able to get better accuracy for testing data. If I use context window of 20(20 frames left and  20 frames right ) and `frame_mode=False` and `randomize=False` I get accuracy of 70% on test data.

If I set `frame_mode=True` and `randomize=True` for the same context_window=20. I get 5% increase in the accuracy.
How does the context window affects the over-fitting problem?

Also when I use feature_dim=39*195 instead of context window and `frame_mode= True` and `randomize=True` I get 86% accuracy on test data.
What is the best method to train speech data  to get a generalized model?
This has been a blocker for me and not allowing me to make any progress in my work.
Kindly throw some light on the issues I am facing.
Thank you

**Comment by KeDengMS** [comment]
Randomize=True in input data would help generalization, as it would prevent the model to learn from the order of input data. For model tweaking, please take a look at [this tutorial](https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_200_GuidedTour.ipynb) as a general modeling guide.

**Comment by vidyatshetty** [comment]
@KeDengMS  Thank you for writing.  now I understand the  randomize function.
My question is if I try train the model using context window how can I test the model without using context window. When I test the model I want one decision for the 1 speech test file instead of multiple decisions for many sequences of one speech test file. For example if my test file is 3sec long I want to use all to features of 3sec long test file and generate one decision instead of generating multiple decisions. Does cntk allow me to change the size of the input layer while testing or taking average of the multiple decisions of one speech file at testing makes sense? Please let me know.
Thanks
