### ISSUE TITLE
C++ model evaluation with input data already on the GPU

### ISSUE THREAD

**Issue by tblattner** [Microsoft/CNTK#3333]
I have an implementation of evaluating a very large image (~100,000 x 50,000) in which I cut up the image into small tiles (1024 x 1024) and iterate throughout the entire image.

The code forms a pipeline that consists of the following steps: (1) Cut a 1024 x 1024 tile and Z-score normalize on the CPU, (2) Copy the 1024 x 1024 tile into GPU memory (float *), and (3) Use that memory to evaluate the model.

I've sifted through various documentation: https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Library-Native-Eval-Interface

and found an example: https://github.com/Microsoft/CNTK/blob/63ea594456ccce938c215feacca7991c123724fb/Tests/EndToEndTests/EvalClientTests/CNTKLibraryCPPEvalExamplesTest/EvalMultithreads.cpp (line 326)

But I can't seem to find a good example on how to specify GPU memory as input data for evaluation.

How can I pass memory that is already allocated on the GPU that I am managing into CNTK for model evaluation?

**Comment by KeDengMS** [comment]
You can create a [Value](https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L2499) object on GPU, and copy from a CPU Value object. Then, you may use the GPU value object.

**Comment by prashantraina** [comment]
That doesn't answer his question. 
I just took a look at the code and didn't find anything which can do what the OP asked for.
Even Microsoft::MSR::CNTK::GPUMatrix doesn't have a constructor which takes a CUDA pointer.

**Comment by KeDengMS** [comment]
Here's an example in Python, and C#/C++ should be similar:

```
import cntk as C
import numpy as np
z = C.layers.Dense(100)(C.input_variable((500)))
v = C.Value.create(z.arguments[0], np.random.rand(128, 500).astype(np.float32), device=C.gpu(0))
print(v) # you'll see v is created on GPU
z.eval(v)
```

**Comment by tblattner** [comment]
I can make this work, but it will require a special case for CNTK in our code-base. Currently we have the workflow in Caffe2, but our team likes how CNTK is deployed, so I am experimenting to see what would need to be modified to make CNTK function within our workflow.

The workflow that we have setup does the following:
(1) Normalizes a 1024x1024 sub-block that is in CPU memory

(2) Asynchronously copy the sub-block into GPU memory. (This GPU memory is pre-allocated at the start of the program as a memory pool of 1024x1024 sub-blocks)

(3) Evaluate the sub-block with the following code (Caffe2 C++ example):


```
auto tensor = inputBlob->GetMutable<caffe2::TensorCUDA>();
tensor->ShareExternalPointer(data->getGPUTensorData()->get(), sizeof(float) * data->getTensorHeight() * data->getTensorWidth() * data->getBatchSize());
workspace.RunNet(predictNetDef.name());
```


This ShareExternalPointer allows me to pass my GPU memory into the input data that is being used with the evaluation.

Each items: (1), (2), and (3) are running on separate threads.  (2) and (3) spawns N-threads for N-GPUs, so each thread will operate on its designated GPU and send GPU memory to the correct GPU for evaluation.

I would change this workflow to work with CNTK by removing (2), and holding a single piece of memory in (3) that is a 'Value' on the GPU. Then when (3) gets memory it would exist on the CPU, so I would have to copy this data from CPU memory into Value. 

This would remove the pipelining behavior that we had put in place to overlap copying data from CPU-> GPU with evaluation, and would require a compile-time directive to change the behavior of our workflow. If I can have similar functionality as "ShareExternalPointer" in CNTK, then the amount of code to modify would be minimal.

**Comment by KeDengMS** [comment]
You can still do async copy to GPU, by creating the Value object in a separate thread. Actually CNTK readers do this to load input data to memory too.

In C++ you can also pass a GPU pointer directly to NDArray:

https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L712-L720

Then you can create a value object for the NDArray:

https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L2513

**Comment by tblattner** [comment]
Using NDArray is exactly what I have been searching for! It appears to have similar constructs as ShareExternalPointer from Caffe2.

 Thank you!
