### ISSUE TITLE
Symbol Server (pdb files)

### ISSUE THREAD

**Issue by nietras** [microsoft/CNTK#3336]
@davidbrownellMS does CNTK have a publically available symbol server with `pdb`s? 

If not it would be great if this was added for easier debugging. Also see https://github.com/Microsoft/CNTK/issues/3280

cc: @mdabros

**Comment by nightgnomes** [comment]
Same question ina  different way, Is there some way to get a build with PDBs? Is there a nuget I can use for that?

**Comment by thiagocrepaldi** [comment]
Unfortunately, you have to build it from source to get the PDBs :(
