### ISSUE TITLE
How to pause/resume training with C# API?

### ISSUE THREAD

**Issue by kkc0923** [Microsoft/CNTK#3338]
Hi. I wrote simple image classification system by CNTK python API. For the next step, I'm trying to re-write my application via C# API.

But CNTK C# API looks does not have UserMinibatchSource and TrainingSession, so these features needs to be implemented manually. 

For UserMinibatchSource, it can be implemented via Value.CreateBatch() so it is not problem. 

But for TrainingSession, there is no API for temporary saving/loading parameters and learner states for current session.

How to save/load current training state with C# API?

**Comment by KeDengMS** [comment]
Can you try [SaveCheckpoint](https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L5607) and [RestoreFromCheckpoint]? There's an example [here](https://github.com/Microsoft/CNTK/blob/91d990182d14ea06e75e6a1b790982d00ac71170/Tests/EndToEndTests/CNTKv2CSharp/CNTKLibraryCSTrainingTest/SimpleFeedForwardClassifierTest.cs)

**Comment by kkc0923** [comment]
It is answer. Thanks.

**Comment by bhrnjica** [comment]
Here is a complete example, how to save and load cntk model for evaluation.

Also there is an example how to save and load model for re-training.

https://bhrnjica.net/2017/11/26/how-to-save-cntk-model-to-file-in-c/
