### ISSUE TITLE
What's the ETA for CNTK 2.6?

### ISSUE THREAD

**Issue by IvanFarkas** [Microsoft/CNTK#3346]
1. What's the ETA for **CNTK 2.6**, please?
2. What feature set can we expect?
3. Can you update solution and documentation to the latest non-conflicting 3rd party libraries mentioned in the **[Setup CNTK on Windows](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-windows)** document, please?

**Comment by KeDengMS** [comment]
CNTK 2.6 is mainly for better support of ONNX. We are also working on updating to latest cuda/cudnn/nccl versions. Once it's released, setup documents would be updated too.

**Comment by IvanFarkas** [comment]
Fantastic. We all appreciate your hard work.
