### ISSUE TITLE
The dimensional of the input variable is not the same as the stream reader

### ISSUE THREAD

**Issue by nimning** [Microsoft/CNTK#3347]
In the transfer learning tutorial [https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_301_Image_Recognition_with_Deep_Transfer_Learning.ipynb](url)

The stream reader is defined as 

```
def create_mb_source(map_file, image_dims, num_classes, randomize=True):
    transforms = [xforms.scale(width=image_dims[2], height=image_dims[1], channels=image_dims[0], interpolations='linear')]
    return C.io.MinibatchSource(C.io.ImageDeserializer(map_file, C.io.StreamDefs(
            features=C.io.StreamDef(field='image', transforms=transforms),
            labels=C.io.StreamDef(field='label', shape=num_classes))),
            randomize=randomize)
```
where  `'image_dims': (3, 224, 224)`

In the training method, the input variable is defined as the following

```
    minibatch_source = create_mb_source(train_map_file, model_details['image_dims'], num_classes)
    image_input = C.input_variable(model_details['image_dims'])
    label_input = C.input_variable(num_classes)

    # Define mapping from reader streams to network inputs
    input_map = {
        image_input: minibatch_source['features'],
        label_input: minibatch_source['labels']
    }
```

Here, the` image_input` has dimension `(3, 224, 224)`, but the `features` in the `minibatch_source` has dimension `(224,224,3)` as no transformation is done on the image. So, why the dimension is not consistent here?

**Comment by KeDengMS** [comment]
minibatch_source reads data directly into memory in column-major layout, while in Python it's row-major layout, which is essentially a axis-reverted tensor of column-major layout.

**Comment by nimning** [comment]
Thanks!
