### ISSUE TITLE
Difficulty when studying how to use CNTK with limited description provided

### ISSUE THREAD

**Issue by wanghm92** [Microsoft/CNTK#336]
Hi! I am new to CNTK and have been trying to learn to use it for NLP tasks. 
However, I found the "Introduction" document (pdf) and the pages in the "Wiki" are not so complete in terms of giving detailed descriptions for a complete list of variables that require specification, completed list of implemented functions and their interface. For example, the description for LMSequence Reader is somewhat minimal and does not even include the "labels" section for output labels.
Besides, I found it harder to debug with CNTK since some of the debug messages are not very informative for me. (e.g. issue-325)
Could anyone suggest an effective way of learning the usage of CNTK, except exploring the source code?

Thank you very much!

**Comment by wolfma61** [comment]
Presentations: https://docs.microsoft.com/en-us/cognitive-toolkit/Presentations including videos 
Course: Deep Learning Explained: https://www.edx.org/course/deep-learning-explained-microsoft-dat236x
