### ISSUE TITLE
CNTK failed when build with permissive- + MSVC on windows

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/CNTK#3363]
Build CNTK with permissive- by msvc failed on windows, could you help have a look?

Repro:
 1.git clone https://github.com/Microsoft/cntk D:\CNTK\src
 2.open a clean x64 prompt and browse to D:\CNTK\src
 3.set CL=/permissive- /wd4643 /wd4244 /wd4326
 4.MSBuild /m /p:Configuration=Release_CpuOnly;Platform=x64 /p:WindowsTargetPlatformVersion= 10.0.16299.0 CNTK.sln /t:Rebuild

Failures:
    d:\cntk\src\source\readers\dssmreader\dssmreader.cpp(73,28): error C2065:  'RoundUp': undeclared identifier [D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.vcxproj]
       d:\cntk\src\source\readers\dssmreader\dssmreader.cpp(73,28): error C2065:             numberToRead = RoundUp(epochSample, m_randomizeRange) - epochSample; [D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.vcxproj]
       d:\cntk\src\source\readers\dssmreader\dssmreader.cpp(73,28): error C2065:                            ^ [D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.vcxproj]
         d:\cntk\src\source\readers\dssmreader\dssmreader.cpp(73,28): error C3861:  'RoundUp': identifier not found [D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.vcxproj]
       d:\cntk\src\source\readers\dssmreader\dssmreader.cpp(73,28): error C3861:             numberToRead = RoundUp(epochSample, m_randomizeRange) - epochSample; [D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.vcxproj]
       d:\cntk\src\source\readers\dssmreader\dssmreader.cpp(73,28): error C3861:                            ^ [D:\CNTK\src\Source\Readers\DSSMReader\DSSMReader.vcxproj]

**Comment by KeDengMS** [comment]
The RoundUp() function used in this template function shows up [later](https://github.com/Microsoft/CNTK/blob/master/Source/Readers/DSSMReader/DSSMReader.cpp#L261) in the file, which seems to be the cause of this error. Can you try move the definition of RoundUp() in front of the template function?

**Comment by PhoebeHui** [comment]
This issue fixed now.
