### ISSUE TITLE
using CLIWrapper with convolution engine

### ISSUE THREAD

**Issue by mjofenermeter** [Microsoft/CNTK#337]
Hi, 
I'm trying to use the CLIWrapper for the EvalDll to the model created with the example 02_Convolution.cntk. 

 The problem is that I receive the following error:
"Error: Default convolution engine currently supports only HWC/legacy layout."
as the result of applying 
 outputs = model.Evaluate(inputs, "ol.z", 10); 

I understand that the problem is in the format of the input data. 
In the CLIWrapper example:
 dict.Add(key, GetFloatArray(size, maxValue));
the image is an array of 784 (28 x 28) float ->  first line then the second line etc. 

So, my problem is how to change this format to HWC format. Is it a matrix of 28 x 28, a float array of float arrays?

thanks

**Comment by Alexey-Kamenev** [comment]
Can you please try using the latest version from master? I recently added/changed a lot of things wrt convolutions so the new code should work fine in CLIWrapper.

**Comment by mjofenermeter** [comment]
hi,
thanks for your fast answer
I have one good news and one bad news

the good one is that with the new master version I have no problems running the evaluation of the 02_convolution example

the bad news is that I now obtain an error (C++ Runtime Library) in the math.lib when running the 03_convnormbatch exemple:

File: BatchNormalizationEngine.cpp
Line: 21

Expression: std::isfinite(epsilon) && epsilon >0

can you help me on this?

thanks

**Comment by mjofenermeter** [comment]
hi,
please verify if you have to put the initialization of epsilon at TrainingNodes.h
from 0 to 0.00001

   BatchNormalizationNode(DEVICEID_TYPE deviceId, const wstring& name)
		: Base(deviceId, name), m_spatial(false), m_normTimeConst(0), m_blendTimeConst(0), m_epsilon(0.00001), m_useCntkEngine(true), /*mjof from m_epsilon(0) to m_epsilon(0.00001)*/
        m_mbCount(0), m_imageLayoutKind(ImageLayoutKind::CHW)

**Comment by gaizkan** [comment]
@mjofenermeter, Are you still experiencing a runtime error when evaluating 03_ConvBatchNorm in CSEvalClient?
