### ISSUE TITLE
Bind from CNTK.CPU to CNTK.GPU at runtime. 

### ISSUE THREAD

**Issue by olmobrutall** [microsoft/CNTK#3372]
Is it possible to make a library that targets CNTK.CPU and is used by an application that references CNTK.GPU ?. 

As library writer I don't want to take a dependency to GPU because is quite heavy, but I also don't want to remove the possibility of using the GPU for the lucky ones with a GeForce.

Will be awesome if GPU will be more like a Plug-in and not a complete replacement.

**Comment by jaliyae** [comment]
cntk.all_devices() will give available devices and then you can use
some code like below to use GPU or not.

```
from cntk.ops.tests.ops_test_utils import cntk_device
from cntk.cntk_py import DeviceKind_GPU
from cntk.device import try_set_default_device

if cntk_device(device_id).type() != DeviceKind_GPU:
    try_set_default_device(cntk_device(device_id))
```
The device_id is -1 for CPU, and 0 for the first GPU, 1 for the next GPU etc.

**Comment by olmobrutall** [comment]
Sorry, I mean in .Net using nuget. I’m aware you can switch the device there.

My question is about avoiding a reference to a huge nuget Ina library of most of the consumers are going to use only CPU, but still let the other ones use GPU.

**Comment by liqunfu** [comment]
do you mean https://www.nuget.org/packages/CNTK.CPUOnly?

**Comment by davidbrownellMS** [comment]
Hello, @olmobrutall. I see the value in your proposal. The changes required to support this type of functionality would impact a large cross-section of the code base (code, build/test infrastructure, etc.). 

I've created an item to track this work internally, but it isn't active where it currently falls within our backlog. With that said, we love contributions and would be happy to see this implemented with the support of the community.

Thanks!
