### ISSUE TITLE
Having trouble running CNTK with MPI

### ISSUE THREAD

**Issue by naxingyu** [Microsoft/CNTK#3380]
I have two machines both running Windows Server 2016 in the same group, say svr1.corpnet.com and svr2.corpnet.com.
I have MPI7 installed as instructed on the [wiki](https://docs.microsoft.com/en-us/cognitive-toolkit/multiple-gpus-and-machines) and CNTK-1bit in the same folder on two servers.
I have MPI server running using Administrator on both servers. Then login svr1 and tried two methods:
1. mpiexec -hosts 1 svr2.corpnet.com myExe.exe
   It runs successfully.
2. mpiexec -hosts 2 svr1.corpnet.com svr2.corpnet.com myExe.exe
  It says 
  ```
  job aborted:
[ranks] message

[0] fatal error
Fatal error in MPI_Allgather: Other MPI error, error stack:
MPI_Allgather(sbuf=0x00000001340BEB90, scount=129, MPI_CHAR, rbuf=0x000001D7285B6010, rcount=129, MPI_CHAR, MPI_COMM_WORLD) failed
[ch3:sock] failed to connnect to remote process c971ed15-1862-45b9-bdf6-d6503215965e:2
unable to connect to 10.172.134.94 on port 24332, exhausted all endpoints
unable to connect to 10.172.134.94 on port 24332, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.  (errno 10060)

[1-2] terminated
  ```
I am sure that I can ping the servers from each other. It seems a MPI setup issue, not CNTK. But is there anyone in this community happen to have a clue about what is going on?

**Comment by jaliyae** [comment]
This could be due to a firewall blocking incoming connections. Adding a firewall rule might help.

**Comment by naxingyu** [comment]
I've already added the firewall rules. But it didn't help.

**Comment by jaliyae** [comment]
Since this is really regarding getting MS MPI to work in your cluster, I would try with a small MPI program and try to get it working without CNTK. I would check if both machines can execute the MPI program alone and then try to see if the machines are reachable by each other and make sure MPI service is running in both etc.
