### ISSUE TITLE
CPU faster than GPU?

### ISSUE THREAD

**Issue by jhmeijer** [Microsoft/CNTK#339]
Hi,

I changed the Simple2d example to have 20 hidden layers of 50 nodes, and trained it during 1000 epochs.
Using 1 CPU (Intel I7 3.5 GHz) , it took about 17 minutes. (CPU use was about 90% of its max capacity.)
Using 1 GPU (Nvidia Titan X), it took 35 minutes, twice as long. (CPU use was about 20% of its max capacity, so the GPU must have been used somehow.)
Why is the CPU faster than the GPU in this example? Is there that much overhead to using a GPU?  How large does the network and the data set need to be before the GPU shows any benefits?  Or might something have gone wrong during my installation?

I have used the CNTK binary files from beginning February.  I have installed the latest NVIDIA driver. My computer recognizes the GPU card.

Thanks for looking into this.

**Comment by DHOFM** [comment]
There must be a problem with your installation or setup, in all my trainings the GPU ist much faster than the cpu and the evalaution i did on a simple OEM GTX was even faster than the cpu mode. you can run the nvidia-smi tool that shows your GPU Usage during trainig - i do not know your example but it should be about 90% to 100% usage. A Titan X with its Pascal Architecture should run very well.

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
