### ISSUE TITLE
CNTK can't recognize installed protobuf

### ISSUE THREAD

**Issue by alexyakovenkoatconcured** [Microsoft/CNTK#3403]
Hello,
I have a problem with manual building of CNTK at my (Open SuSE) server. For some reason CNTK can't recognize an installed protobuf:

alex@dev32:~/tmp/cntk/build> ../configure --asgd=no --java=no --csharp=no --cuda=no --python=yes --mpi=yes --gdr=no --with-mkl=/home/alex/local/mklml_lnx_2019.0.20180710 --with-protobuf=/usr/local/protobuf-3.1.0/
Invalid Protocol Buffers directory /usr/local/protobuf-3.1.0/

The mystery is that:

/usr/local/protobuf-3.1.0/bin/protoc --proto_path=/home/alex/tmp/cntk/Source/CNTKv2LibraryDll/proto/ --cpp_out=/home/alex/tmp/cntk/Source/CNTKv2LibraryDll/proto/ /home/alex/tmp/cntk/Source/CNTKv2LibraryDll/proto/CNTK.proto

says nothing and creates output files fine.

Thanks for any ideas of how it can be fixed,
Alex

**Comment by BowenBao** [comment]
Hello, CNTK configure checks if there is "lib/libprotobuf.a" under the specified protobuf directory. Can you check if "/usr/local/protobuf-3.1.0/lib/libprotobuf.a" exists on your server?

**Comment by alexyakovenkoatconcured** [comment]
Thanks for the replay. It was the problem:
alex@dev32:~/tmp/cntk/build> ls /usr/local/protobuf-3.1.0/lib/libprotobuf.a
ls: cannot access '/usr/local/protobuf-3.1.0/lib/libprotobuf.a': No such file or directory

but:

alex@dev32:~/tmp/cntk/build> ls /usr/local/protobuf-3.1.0/lib64/libprotobuf.a
/usr/local/protobuf-3.1.0/lib64/libprotobuf.a

... a symlink helped, thanks a lot! :)
Alex
