### ISSUE TITLE
Using CNTK trained model 

### ISSUE THREAD

**Issue by axonUH** [Microsoft/CNTK#341]
Hi,

I'm interested in using a CNTK model once a model has been trained and tested but I could not get my output section to run without a label specification. For instance, if I run the Simple2D Example (https://github.com/Microsoft/CNTK/tree/master/Examples/Other/Simple2d), the model is placed in the Output/Models folder. (I'm running CNTK using binaries in Windows7). The final model exists as simple.dnn. I would like to use this model to process input data. To do this, I ran only the Output section of the simple.cntk Configuration file after training and testing on a standalone basis. Before that, I stripped the labels out of the input file so that there was just pure data. The script seemed to terminate abnormally with "CNTK: Caught Win32 exception 0xc0000005: Access violation." If I restored the labels in the input file, the script runs to completion with no problems. What is the procedure for running a model with only input data without labels?

Thanks

**Comment by dongyu888** [comment]
Are you using the most updated source code? It has the fix if you are using the UCIFastReader.

**Comment by axonUH** [comment]
Thanks. 
It looks like the labels are dummy in that case so I can probably live with it until I work out the compilation (I'm using binaries at the moment).

**Comment by wolfma61** [comment]
axon - looks like your immediate issue is solved. please reopen or open a new issue if you experience any other problem
