### ISSUE TITLE
cntk.mdl missing error in training cntk dnn in AMI example

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#342]
Hello
I'm trying to train a CNTK DNN of AMI in "Examples/Speech/Miscellaneous" directory. I successfully ran "run_sdm.sh" which is required to run "run_sdm_cntk.sh". 

The error happens when I execute scripts/align.sh line in run_sdm_cntk.sh. "align.sh" looks for "cntk.mdl" file in exp_cntk/sdm1/dnn directory (it is hard-coded). The comment in the script said sometimes it is not automatically generated and I need to make sure it should be there. 

The question is when it is not automatically generated, how I can generate it manually? I don't have any clue on this. When I check log file of running, I didn't see any error before this.

I really appreciate it if anyone can give me any clue on this.

**Comment by chenguoguo** [comment]
cntk.mdl is supposed to be a soft link to the CNTK neural network. I guess something happened when the script was checked in. Under your exp_cntk/sdm1/dnn directory, you can simply do "ln -s cntk_model/cntk.nnet.xxx cntk.mdl", where cntk.nnet.xxx is the neural network you want to use.

**Comment by funguy74** [comment]
Thank you for your comment. I changed it with generated cntk.nnet and now it runs again. 

Thanks!
