### ISSUE TITLE
feature_node_name from PretrainedModels

### ISSUE THREAD

**Issue by arturgontijo** [Microsoft/CNTK#3420]
I'm following the tutorial [301](https://cntk.ai/pythondocs/CNTK_301_Image_Recognition_with_Deep_Transfer_Learning.html) and It's working ok.
But when I try to use some other Pretrained model, I can't get the `feature_node_name`.
```
import cntk as C
base_model = {
    'model_file': 'ResNet18_ImageNet_CNTK.model',
    'feature_node_name': 'features',
    'last_hidden_node_name': 'z.x',
    # Channel Depth x Height x Width
    'image_dims': (3, 224, 224)
}
resnet18_model = C.load_model(base_model['model_file'])
feature_node = C.logging.find_by_name(resnet18_model, base_model['feature_node_name'])
print(feature_node) # None
```
- File: [ResNet18_ImageNet_CNTK.model](https://www.cntk.ai/Models/CNTK_Pretrained/ResNet18_ImageNet_CNTK.model)
- Python 3.6.5
- cntk 2.5.1
- Ubuntu 16.04

**Comment by delzac** [comment]
You might want to do C.logging.plot, check if the second last layer has a name. If it doesn't have a name, use its uid. you can access the node by C.logging.find_by_uid

**Comment by arturgontijo** [comment]
> You might want to do C.logging.plot, check if the second last layer has a name. If it doesn't have a name, use its uid. you can access the node by C.logging.find_by_uid

Yeah, using the uid I'm able to get the node.
But I'm pretty sure that, about 15 days ago, the
`feature_node = C.logging.find_by_name(resnet18_model, base_model['feature_node_name'])`
was working well.
Thanks!
