### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by FreedMana** [Microsoft/CNTK#343]
`mpic++ -c Source/SGDLib/SGD.cpp -o /root/leisun/cntk/build/release/.build/Source/SGDLib/SGD.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC  -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/./include/nvidia/gdk -I/usr/local/cub-1.4.1 -I/usr/local/cuda-7.0/include -I/usr/local/cudnn-4.0/cuda/include -I/opt/acml5.3.1/ifort64_mp/include -MD -MP -MF /root/leisun/cntk/build/release/.build/Source/SGDLib/SGD.d
Source/Readers/CNTKTextFormatReader/Indexer.cpp: In member function ‘void Microsoft::MSR::CNTK::Indexer::Build()’:
Source/Readers/CNTKTextFormatReader/Indexer.cpp:145:63: error: expected ‘)’ before ‘PRIi64’
         RuntimeError("Expected a sequence id at the offset %" PRIi64 ", none was found.", offset);
                                                               ^
Source/Readers/CNTKTextFormatReader/Indexer.cpp: In member function ‘bool Microsoft::MSR::CNTK::Indexer::GetNextSequenceId(size_t&)’:
Source/Readers/CNTKTextFormatReader/Indexer.cpp:216:42: error: expected ‘)’ before ‘PRIi64’
                     " at the offset = %" PRIi64 "\n", c, GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/Indexer.cpp:226:42: error: expected ‘)’ before ‘PRIi64’
                     " at the offset = %" PRIi64 "\n", GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/Indexer.cpp:237:30: error: expected ‘)’ before ‘PRIi64’
         " at the offset = %" PRIi64 "\n", GetFileOffset());
                              ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘void Microsoft::MSR::CNTK::TextParser<ElemType>::SetFileOffset(int64_t)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:361:52: error: expected ‘)’ before ‘PRId64’
         RuntimeError("Error seeking to position %" PRId64 " in file %ls", offset, m_filename.c_str());
                                                    ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘Microsoft::MSR::CNTK::TextParser<ElemType>::SequenceBuffer Microsoft::MSR::CNTK::TextParser<ElemType>::LoadSequence(bool, const Microsoft::MSR::CNTK::SequenceDescriptor&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:389:70: error: expected ‘)’ before ‘PRIu64’
             RuntimeError("Did not find the expected sequence id ( %" PRIu64 ") "
                                                                      ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:423:58: error: expected ‘)’ before ‘PRIu64’
                     "WARNING: could not read a row (# %" PRIu64 ")"
                                                          ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:435:66: error: expected ‘)’ before ‘PRIu64’
                     " expected for the current sequence (id = %" PRIu64 ")"
                                                                  ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:445:55: error: expected ‘)’ before ‘PRIu64’
             "INFO: finished loading sequence (id = %" PRIu64 "),"
                                                       ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:459:48: error: expected ‘)’ before ‘PRIu64’
                 "ERROR: While reading input %" PRIu64 ""
                                                ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘bool Microsoft::MSR::CNTK::TextParser<ElemType>::ReadRow(Microsoft::MSR::CNTK::TextParser<ElemType>::SequenceBuffer&, size_t&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:569:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘bool Microsoft::MSR::CNTK::TextParser<ElemType>::GetInputId(size_t&, size_t&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:589:38: error: expected ‘)’ before ‘PRId64’
                 " at the offset = %" PRId64 "\n", c, NAME_PREFIX, GetFileOffset());
                                      ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:621:46: error: expected ‘)’ before ‘PRId64’
                         " at the offset = %" PRId64 "\n", name.c_str(), GetFileOffset());
                                              ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:629:42: error: expected ‘)’ before ‘PRId64’
                     " at the offset = %" PRId64 "\n", GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:647:42: error: expected ‘)’ before ‘PRId64’
                     " at the offset = %" PRId64 "\n", GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:661:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘bool Microsoft::MSR::CNTK::TextParser<ElemType>::ReadDenseSample(std::vector<_RealType>&, size_t, size_t&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:687:63: error: expected ‘)’ before ‘PRId64’
                 RuntimeError("Encountered a sample (size = %" PRId64 ")"
                                                               ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:727:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘bool Microsoft::MSR::CNTK::TextParser<ElemType>::ReadSparseSample(std::vector<_RealType>&, std::vector<int>&, size_t&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:768:53: error: expected ‘)’ before ‘PRIu64’
                     "WARNING: sparse index value(%" PRIu64 ") exceeds the maximum allowed "
                                                     ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:789:42: error: expected ‘)’ before ‘PRId64’
                     " at the offset = %" PRId64 "\n", c, GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:811:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘bool Microsoft::MSR::CNTK::TextParser<ElemType>::ReadUint64(size_t&, size_t&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:873:42: error: expected ‘)’ before ‘PRId64’
                     " at the offset = %" PRId64 "\n", GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:888:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp: In member function ‘bool Microsoft::MSR::CNTK::TextParser<ElemType>::ReadRealNumber(ElemType&, size_t&)’:
Source/Readers/CNTKTextFormatReader/TextParser.cpp:933:46: error: expected ‘)’ before ‘PRId64’
                         " at the offset = %" PRId64 "\n", c, GetFileOffset());
                                              ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:952:46: error: expected ‘)’ before ‘PRId64’
                         " at the offset = %" PRId64 "\n", c, GetFileOffset());
                                              ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:1037:46: error: expected ‘)’ before ‘PRId64’
                         " at the offset = %" PRId64 "\n", c, GetFileOffset());
                                              ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:1056:46: error: expected ‘)’ before ‘PRId64’
                         " at the offset = %" PRId64 "\n", c, GetFileOffset());
                                              ^
Source/Readers/CNTKTextFormatReader/TextParser.cpp:1087:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
make[1]: *** [/root/leisun/cntk/build/release/.build/Source/Readers/CNTKTextFormatReader/Indexer.o] Error 1
In file included from Source/Readers/ExperimentalHTKMLFReader/MLFDataDeserializer.cpp:13:0:
Source/Common/Include/latticearchive.h: In member function ‘void msra::lattices::archive::open(const wstring&)’:
Source/Common/Include/latticearchive.h:1288:32: error: expected ‘)’ before ‘PRIu64’
             if (sscanf(q, "[%" PRIu64 "]%c", &offset, &c) != 1)
                                ^
Source/Readers/ExperimentalHTKMLFReader/MLFDataDeserializer.cpp: In constructor ‘Microsoft::MSR::CNTK::MLFDataDeserializer::MLFDataDeserializer(Microsoft::MSR::CNTK::CorpusDescriptorPtr, const Microsoft::MSR::CNTK::ConfigParameters&, const wstring&)’:
Source/Readers/ExperimentalHTKMLFReader/MLFDataDeserializer.cpp:58:43: error: expected ‘)’ before ‘PRIu64’
         RuntimeError("Label dimension (%" PRIu64 ") exceeds the maximum allowed "
                                           ^
Source/Readers/ExperimentalHTKMLFReader/MLFDataDeserializer.cpp: In constructor ‘Microsoft::MSR::CNTK::MLFSequenceData<ElemType>::MLFSequenceData(size_t)’:
Source/Readers/ExperimentalHTKMLFReader/MLFDataDeserializer.cpp:257:67: error: expected ‘)’ before ‘PRIu64’
             RuntimeError("Number of samples in an MLFSequence (%" PRIu64 ") "
`
i installed necessary components , and can not figure out why it failed.
Thanks.

**Comment by wolfma61** [comment]
this is hard to say ... 

additional information is need, like platforms etc.
check that you installed all the required tools and the correct versions, and the build environment is configured accordingly


You should check the wiki for our supported test/build platforms
https://github.com/Microsoft/CNTK/wiki/Test-Configurations

thx
Wolfgang

**Comment by FreedMana** [comment]
Yes，except for those optional components, i try to use the same software versions.  There are 2 remainning differences in my environment: CentOS 6.7 and Cuda 7.0.
And old CNTK sourcecode  version such as 16-02-08 can be compiled successfully , it states that other necessary components are right? So i can't figure out what to do next?
THANKS!!

**Comment by alexeyo26** [comment]
Try using our [Docking Containers](https://github.com/Microsoft/CNTK/wiki/CNTK-Docker-Containers)

**Comment by wolfma61** [comment]
and again the comment I gave on another discussion, We have a list of supported and tested configurations:
https://github.com/Microsoft/CNTK/wiki/Test-Configurations

**Comment by raaaar** [comment]
Same issue as in #355

**Comment by FreedMana** [comment]
thanks,it's solved by a defining a macro as it mentioned by @raaaar.
