### ISSUE TITLE
How can CNTK be used for online decoding?

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#344]
In audio or speech case, 
what should i do , if I want to use CNTK to do online classification , where features are extracted online, instead of specifying feature script file in the configuration file?
for example, whenever a feature vector is well prepared, it is input to CNTK and output a classification result, not like the batch mode reading in test case.

**Comment by dongyu888** [comment]
For speech recognition you can plug in the CNTKEval dll to your decoder.

**Comment by housebaby** [comment]
I just get to know that you have leave Microsoft and joined Tencent.
Congratulations.
I learned a lot from CNTK.
