### ISSUE TITLE
C#: documentation for more basic operations?

### ISSUE THREAD

**Issue by chrisk477** [Microsoft/CNTK#3440]
Hello,

if this question is inappropriate on this list, I apologize. 

Is there more from-the-ground-up documentation available for CNTK for C#? What I mean by that is that all the available examples seem to use more high-level functions like automated data reading from text files, minibatch data sources etc.

But let's say I have two float[] arrays containing the values for two matrices and want CNTK to simply perform a matrix multiplication and read the results into another C# float[] array.

I know there is the CNTKLib.Times function that takes two parameters of type Variable. But then there seems to be no obvious way to get the data from the C# arrays into the Variable object and out again.

So I can't seem to figure out how to do basic things like that. Is there some documentation or tutorial available for this?

**Comment by bhrnjica** [comment]
you can look at unit tests of this project (http://github.com/bhrnjica/anndotnet). 

Precisely there is a one unit test which does exactly you have asked:
https://github.com/bhrnjica/anndotnet/blob/master/test/anndotnet.unit/tests/DataNormalizationTests.cs 

Moreover there is a one blog post about descriptive statistics using CNTK so it may help as well. https://bhrnjica.net/2018/07/01/descriptive-statistics-and-data-normalization-with-cntk-and-c/

**Comment by chrisk477** [comment]
Thanks a  lot, that's very helpful!

I had a look at the gaussNormalization_test02() test function and even though I know that they have to abstract things like uploading/downloading data to/from GPU memory it seems a bit complicated. Maybe CNTK is a more specialized library than Google's TensorFlow.
