### ISSUE TITLE
error C2440: '<function-style-cast>' : cannot convert from 'initializer-list' to 'std::array<ElemType *,0x02>'

### ISSUE THREAD

**Issue by klmsj** [Microsoft/CNTK#345]
hi,all.
I use  d VS2013 to bulid CNTK project with CUDA 7.5 in windows 7. i  bulid has this error:
Error	1257	error C2440: '<function-style-cast>' : cannot convert from 'initializer-list' to 'std::array<ElemType *,0x02>'	D:\OpenSource\CNTK\Source\Math\GPUMatrix.cu	4277	1	MathCUDA
 

can anybody kown what happen and how to fix this error?

**Comment by wolfma61** [comment]
Hi - 
sounds a little lame, but works for me ;)
although we do not test on Windows 7 (see supported platforms on the wiki)

is this a new install or did you run successful builds before? 

thx
Wolfgang

**Comment by klmsj** [comment]
i update vs2013 to vs2013-update5  ,and build succeeded! ths

**Comment by wolfma61** [comment]
good - glad you figured it out
