### ISSUE TITLE
How to change trained net?

### ISSUE THREAD

**Issue by kfmn** [Microsoft/CNTK#346]
Hello! 
A have trained a feedforward DNN. 
During training I used large input vector (3201 elements) but divided it into two parts using rowSlice. The first part (1240, named features_orig) was used as input for the first layer and the second part (1961, named soft_targets) was used in criterion computation only.

For testing I do not need the second parts and I would like to feed into the network only shorter vectors, corresponding to the first parts. How can I made this with MEL script or somehow else?

The configuration of network is as follows:

CE.BFF.B=LearnableParameter [1961,1]   learningRateMultiplier=1.000000  NeedsGradient=true
CE.BFF.FF.P=Plus ( CE.BFF.FF.T , CE.BFF.B )
CE.BFF.FF.T=Times ( CE.BFF.W , L2.S )
CE.BFF.W=LearnableParameter [1961,2048]   learningRateMultiplier=1.000000  NeedsGradient=true
CE.SM=Plus ( CE.SM1 , CE.unnamed65 )
CE.SM1=CrossEntropyWithSoftmax ( labels , CE.BFF.FF.P )
CE.SM2=CrossEntropyWithSoftmax ( soft_targets , CE.unnamed62 )
CE.unnamed62=ElementTimes ( CE.unnamed63 , CE.BFF.FF.P )
CE.unnamed63=LearnableParameter [1,1]   learningRateMultiplier=0.000000  NeedsGradient=false
CE.unnamed65=ElementTimes ( CE.unnamed66 , CE.SM2 )
CE.unnamed66=LearnableParameter [1,1]   learningRateMultiplier=0.000000  NeedsGradient=false
Err=ErrorPrediction ( labels , CE.BFF.FF.P )
featNorm.xMean=Mean ( features_orig ) [1240]   HasComputed=true
featNorm.xNorm=PerDimMeanVarNormalization ( features_orig , featNorm.xMean , featNorm.xStdDev )
featNorm.xStdDev=InvStdDev ( features_orig ) [1240]   HasComputed=true
features=InputValue [ 3201 ]
features_orig=Slice ( features )
L1.BFF.B=LearnableParameter [2048,1]   learningRateMultiplier=1.000000  NeedsGradient=true
L1.BFF.FF.P=Plus ( L1.BFF.FF.T , L1.BFF.B )
L1.BFF.FF.T=Times ( L1.BFF.W , featNorm.xNorm )
L1.BFF.W=LearnableParameter [2048,1240]   learningRateMultiplier=1.000000  NeedsGradient=true
L1.S=Sigmoid ( L1.BFF.FF.P )
L2.BFF.B=LearnableParameter [2048,1]   learningRateMultiplier=1.000000  NeedsGradient=true
L2.BFF.FF.P=Plus ( L2.BFF.FF.T , L2.BFF.B )
L2.BFF.FF.T=Times ( L2.BFF.W , L1.S )
L2.BFF.W=LearnableParameter [2048,2048]   learningRateMultiplier=1.000000  NeedsGradient=true
L2.S=Sigmoid ( L2.BFF.FF.P )
labels=InputValue [ 1961 ]
logPrior.LogPrior=Log ( logPrior.Prior )
logPrior.Prior=Mean ( labels ) [1961]   HasComputed=true
ScaledLogLikelihood=Minus ( CE.BFF.FF.P , logPrior.LogPrior )
soft_targets=Slice ( features )

Thanks, 
Maxim

**Comment by 1132520084** [comment]
I am also in the trouble, and it do not succeed. I use MEL script to modify the model, thougth it seems that MEL cannot modify the `FeatureNodes` or delete/replace the `input node` . I am not very sure and this is just my point. I hope it may help you.

**Comment by kfmn** [comment]
Thanks for your comment. 
I have found a temporary workaround for the test time but it will not work well for deployment, alas.

**Comment by dongyu888** [comment]
You can use SetProperty function in MEL to change whether a node is a feature node (or criterion node, etc.).

**Comment by kfmn** [comment]
I'm afraid this is not what I need. My network's feature node itself separates long input vectors into 2 shorter ones. And I would like to change the dimensionality of input to use only the first of two.

**Comment by zhangyike** [comment]
@kfmn If you want to delete a node, you have to delete all its higher level dependent nodes before deleting the actual node. So you cannot directly delete input nodes.
Now, I have the same problem with you. And I have not found a practicable solution. If you solved this problem, please tell me your method. Thank you.

**Comment by yzhang87** [comment]
@zhangyike what I have done was dumping the model first and then use a python script to parse all the node related to "input"..

**Comment by zhangyike** [comment]
@yzhang87 Thank you. I have solved the problem by using BS.Network.CloneFunction ().  @kfmn This function can copy the nodes that you needed rather than remove nodes from the original network.
