### ISSUE TITLE
Request: binaries for Linux 64 bit

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#347]
I noticed that there is a binary package for Windows. Can you guys create something like this for Linux and have options to dynamically link it to implementations of cblas.h, such as Intel MKL? I would suggest OpenBLAS, but I'm not as convinced on that.

**Comment by alexeyo26** [comment]
Hello! New binaries will be published soon but they will be with ACML for the time being. See our [Build and test configurations](https://github.com/microsoft/cntk/wiki/Test-Configurations). We plan to add MKL in the future, but focused on some other features for time being.
