### ISSUE TITLE
some problems within building cntk

### ISSUE THREAD

**Issue by smartyfn** [Microsoft/CNTK#3478]
I am new to cntk。I followed the instruction of "https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows", but I met some tough problems:
1: when i first open the cntk.sln solution from the Command Prompt, the imageRecognitionAppCS project does not reference ImageRecognizerLib, so I deleted the reference and added it.
2: After I builded the solution, there were several error message, one is:
`"Error The OutputPath property is not set for project 'ImageRecognitionAppCS.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'"`.
so I changed the configuration from debug to debug_UWP according to the ImageRecognitionAppCS.csproj file,then I rebuiled, 
`"Error LNK1181 cannot open input file 'Cntk.Core_app-2.6.lib'"`
 error message appeard in  both ImageRecognizerLib and CNTKLibraryCPPUWPEvalExamplesTests projects, besides 
` "Error	CS0006 Metadata file 'E:\vigenetech\CNTK\CNTK-master\x64\Release_UWP\ImageRecognizerLib.winmd' could not be found"` 
error message was appeared in imageRecognitionAppCS project 

My OS is Window 10 Enterprise 64 bit(10.0 verson 17134) and IDE is visual studio community 2017(version 15.7.2)
What is the best way to solve them? Any suggestions will be greatly appreciated.

**Comment by smartyfn** [comment]
My OS is Window 10 Enterprise 64 bit(10.0 verson 17134) and IDE is visual studio community 2017(version 15.7.2)

**Comment by mental2008** [comment]
> I am new to cntk。I followed the instruction of "https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows", but I met some tough problems:
> 1: when i first open the cntk.sln solution from the Command Prompt, the imageRecognitionAppCS project does not reference ImageRecognizerLib, so I deleted the reference and added it.
> 2: After I builded the solution, there were several error message, one is:
> `"Error The OutputPath property is not set for project 'ImageRecognitionAppCS.csproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Debug' Platform='x64'"`.
> so I changed the configuration from debug to debug_UWP according to the ImageRecognitionAppCS.csproj file,then I rebuiled,
> `"Error LNK1181 cannot open input file 'Cntk.Core_app-2.6.lib'"`
> error message appeard in both ImageRecognizerLib and CNTKLibraryCPPUWPEvalExamplesTests projects, besides
> ` "Error	CS0006 Metadata file 'E:\vigenetech\CNTK\CNTK-master\x64\Release_UWP\ImageRecognizerLib.winmd' could not be found"`
> error message was appeared in imageRecognitionAppCS project
> 
> My OS is Window 10 Enterprise 64 bit(10.0 verson 17134) and IDE is visual studio community 2017(version 15.7.2)
> What is the best way to solve them? Any suggestions will be greatly appreciated.

Do you solve these problems? I met them when building the solution.
Thanks if you can reply.

**Comment by smartyfn** [comment]
这个build过程非常麻烦，后来解决了。编译成功需要1个小时。
------------------ 原始邮件 ------------------
发件人: "杨凌云"<notifications@github.com>;
发送时间: 2019年7月5日(星期五) 晚上8:46
收件人: "microsoft/CNTK"<CNTK@noreply.github.com>;
抄送: "2981760418"<2981760418@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [microsoft/CNTK] some problems within building cntk (#3478)



 
I am new to cntk。I followed the instruction of "https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-CNTK-on-Windows", but I met some tough problems:
 1: when i first open the cntk.sln solution from the Command Prompt, the imageRecognitionAppCS project does not reference ImageRecognizerLib, so I deleted the reference and added it.
 2: After I builded the solution, there were several error message, one is:
 "Error The OutputPath property is not set for project 'ImageRecognitionAppCS.csproj'. Please check to make sure that you have specified a valid combination of Configuration and Platform for this project. Configuration='Debug' Platform='x64'".
 so I changed the configuration from debug to debug_UWP according to the ImageRecognitionAppCS.csproj file,then I rebuiled,
 "Error LNK1181 cannot open input file 'Cntk.Core_app-2.6.lib'"
 error message appeard in both ImageRecognizerLib and CNTKLibraryCPPUWPEvalExamplesTests projects, besides
  "Error	CS0006 Metadata file 'E:\vigenetech\CNTK\CNTK-master\x64\Release_UWP\ImageRecognizerLib.winmd' could not be found"
 error message was appeared in imageRecognitionAppCS project
 
My OS is Window 10 Enterprise 64 bit(10.0 verson 17134) and IDE is visual studio community 2017(version 15.7.2)
 What is the best way to solve them? Any suggestions will be greatly appreciated.
  
Do you solve these problems? I met them when building the solution.
 Thanks if you can reply.
