### ISSUE TITLE
Compile errors: CentOS 7

### ISSUE THREAD

**Issue by ldmtwo** [Microsoft/CNTK#348]
I'll let the logs speak for themselves. I have no idea what could be wrong, but the code form Mar 11 compiles and later clones do not.

I tried going back to the the installation Wiki and I don't see what I could be missing. I've tried with and without 1bit SGD, MKL, debug/release, OpenCV, LibZip. 

 ../../configure  --1bitsgd=yes --with-mkl=/opt/intel --with-buildtype=release --with-opencv=/home/hadoop/ldmtwo/bin/libzip-1.1.2/opencv-3.0.0/ --with-libzip=/home/hadoop/ldmtwo/bin/libzip-1.1.2/lib

Some sampling of the error log:
```
mpic++ -c Source/CNTK/BrainScript/BrainScriptParser.cpp -o /home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/CNTK/BrainScript/BrainScriptParser.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DUSE_MKL -DNDEBUG -DNO_SYNC  -DUSE_ZIP -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/opt/intel/mkl/include -I/usr/local/lib/libzip/include -I/usr/local/opencv-3.0.0/include -MD -MP -MF /home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/CNTK/BrainScript/BrainScriptParser.d
Source/Readers/CNTKTextFormatReader/TextParser.cpp:1087:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
make[1]: *** [/home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/Readers/ReaderLib/SequencePacker.o] Error 1
make[1]: *** Waiting for unfinished jobs....
mpic++ -c Source/CNTK/BrainScript/BrainScriptTest.cpp -o /home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/CNTK/BrainScript/BrainScriptTest.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DUSE_MKL -DNDEBUG -DNO_SYNC  -DUSE_ZIP -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/opt/intel/mkl/include -I/usr/local/lib/libzip/include -I/usr/local/opencv-3.0.0/include -MD -MP -MF /home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/CNTK/BrainScript/BrainScriptTest.d
Source/Readers/CNTKTextFormatReader/Indexer.cpp: In member function ‘void Microsoft::MSR::CNTK::Indexer::Build()’:
Source/Readers/CNTKTextFormatReader/Indexer.cpp:145:63: error: expected ‘)’ before ‘PRIi64’
         RuntimeError("Expected a sequence id at the offset %" PRIi64 ", none was found.", offset);
                                                               ^
Source/Readers/CNTKTextFormatReader/Indexer.cpp: In member function ‘bool Microsoft::MSR::CNTK::Indexer::GetNextSequenceId(size_t&)’:
Source/Readers/CNTKTextFormatReader/Indexer.cpp:216:42: error: expected ‘)’ before ‘PRIi64’
                     " at the offset = %" PRIi64 "\n", c, GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/Indexer.cpp:226:42: error: expected ‘)’ before ‘PRIi64’
                     " at the offset = %" PRIi64 "\n", GetFileOffset());
                                          ^
Source/Readers/CNTKTextFormatReader/Indexer.cpp:237:30: error: expected ‘)’ before ‘PRIi64’
         " at the offset = %" PRIi64 "\n", GetFileOffset());
                              ^
```

[good_20160311.txt](https://github.com/Microsoft/CNTK/files/218111/good_20160311.txt)
[bad_20160413.txt](https://github.com/Microsoft/CNTK/files/218112/bad_20160413.txt)

**Comment by ldmtwo** [comment]
I can clean and recompile the old code. I tried swapping the make and configure files in case that changed. I'm lost.

**Comment by tz579** [comment]
@ldmtwo Hi! From what I experienced for versions in recent days, compilation could be successful only if I disabled the 1bitsgd. You may try that as well. :)

**Comment by jack-unisound** [comment]
see the macro of    _STDC_FORMAT_MACROS

**Comment by alexeyo26** [comment]
And we now have [Docker Containers](https://github.com/Microsoft/CNTK/wiki/CNTK-Docker-Containers) You may use them to build and run CNTK.

**Comment by wolfma61** [comment]
In addition to Alexey's answer, we listed the supported configuration (what we build and test):
https://github.com/Microsoft/CNTK/wiki/Test-Configurations

**Comment by ldmtwo** [comment]
I found the problem. Take this code for example:
https://github.com/Microsoft/CNTK/blame/8322296eabac5899df10d320fe9313169420b7de/Source/Readers/CNTKTextFormatReader/TextParser.cpp

And this error...
```
mpic++ -c Source/CNTK/BrainScript/BrainScriptParser.cpp -o /home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/CNTK/BrainScript/BrainScriptParser.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DUSE_MKL -DNDEBUG -DNO_SYNC  -DUSE_ZIP -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/opt/intel/mkl/include -I/usr/local/lib/libzip/include -I/usr/local/opencv-3.0.0/include -MD -MP -MF /home/hadoop/ldmtwo/bin/cntk_20160413/cntk/build/release/.build/Source/CNTK/BrainScript/BrainScriptParser.d
Source/Readers/CNTKTextFormatReader/TextParser.cpp:1087:34: error: expected ‘)’ before ‘PRId64’
             " at the offset = %" PRId64 "\n", GetFileOffset());
                                  ^
```

Thanks to @jack-unisound for the suggestion. Looking at the history of the files not compiling, it was after @raaaar added TextParser.cpp and others. I don't know why it's working for other people, but these suggest adding `#define __STDC_FORMAT_MACROS ` or `#define __STDC_FORMAT_MACROS 1` because the default is to not define it. 

http://stackoverflow.com/questions/14535556/why-doesnt-priu64-work-in-this-code
http://stackoverflow.com/questions/8132399/how-to-printf-uint64-t
http://www.leoox.com/?p=229

To test this theory, I modified these files.

 1001  nano Source/Readers/CNTKTextFormatReader/Indexer.cpp
 1002  nano Source/Readers/CNTKTextFormatReader/TextParser.cpp
 1003  nano Source/Readers/ImageReader/ImageDataDeserializer.cpp
 1004  nano Source/Readers/ExperimentalHTKMLFReader/MLFDataDeserializer.cpp
 1005  nano Source/Readers/ReaderLib/SequencePacker.cpp
 1006  nano Source/Common/Include/latticearchive.h

Added this before inttypes was included:
```
#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS 
#endif
```
latticearchive.h already had the definition, so I had to add #ifndef

Versions I'm using:
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

mpic++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

It works! 
`../cntk_sgd/configure  --1bitsgd=yes --with-mkl=/opt/intel --with-buildtype=release`
