### ISSUE TITLE
Is it possible to build a UserDeserializer in C#?

### ISSUE THREAD

**Issue by fldvrees** [microsoft/CNTK#3497]
Hey,

I'm building a YOLO v2 trainer.
The label data of YOLO is a variable list of Bounding box coordinates with a class.
This label data should be converted to a tensor with shape (13,13,125).
Therefore I would like to build my own serializer, like the [UserDeserializer](https://github.com/Microsoft/CNTK/blob/release/2.1/Manual/Manual_How_to_write_a_custom_deserializer.ipynb) in the python API.

Is it possible to do this C#, or do I have to read the labels in a different way?

Thanks in advance!

**Comment by fldvrees** [comment]
I think this is a missing feature in the C# API.
Can anyone confirm?

If this is a missing feature then I would love to help with the implementation.
Does anyone have an idea of what has to be implemented?

**Comment by Maxonfire** [comment]
It seems to me that custom serialization is possible in C#.
Check this https://www.codeproject.com/Articles/1239398/Creating-a-custom-de-serializer

**Comment by fldvrees** [comment]
I don't need this feature anymore, so therefor this feature may be closed.
