### ISSUE TITLE
ImportError: libmpi_cxx.so.1:, the setup of LD_LIBRARY_PATH after install openmpi-bin (Ubuntu18.04) - Solved

### ISSUE THREAD

**Issue by yujianyuanhaha** [Microsoft/CNTK#3499]
1. I am on Ubuntu18.04, Airsim Version 4.18, python version 2.7(from conda virtual machine)
2. I pass the airsim `hello_car.py` successfully running
3. I install the openmpi-bin, where terminal tell me successfully installed, however nothing show up after I check  `echo $LD_LIBRARY_PATH`, **I suppose this is the key for the bug**.
    (a) I later set the PATH by `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu`, and after type `echo $LD_LIBRARY_PATH` got print as `:/usr/lib/x86_64-linux-gnu`.
    (b) by `ls /usr/lib/x86_64-linux-gn/libmpi.so*`, I got `libmpi.so.12  libmpi.so.20  libmpi.so.20.10.1`.

4. I install Airsim by `pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.5-cp27-cp27mu-linux_x86_64.whl `within py2 conda virtual environment, the terminal says it successfully pass.
Currently the bugs shown as 
after type in test ` python -c "import cntk; print(cntk.__version__)"`, error shown as below
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/__init__.py", line 17, in <module>
    from . import cntk_py
  File "/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/cntk_py.py", line 21, in <module>
    _cntk_py = swig_import_helper()
  File "/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/cntk_py.py", line 20, in swig_import_helper
    return importlib.import_module('_cntk_py')
  File "/home/jet/anaconda3/envs/py2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory
```

Several solution I tried so far and would not work:
1. [sudo ln -s /usr/lib/x86_64-linux-gnu/libmpi.so.20.10.1 /usr/lib/x86_64-linux-gnu/libmpi.so.12 ](https://tweaks-tips.blogspot.com/2017/12/microsoft-cntk-libmpi-importerror.html)   
2. ` conda install -c conda-forge openmpi`   

Any idea about where openmpi-bin is located, and how to set up **LD_LIBRARY_PATH**?

**Comment by yujianyuanhaha** [comment]
solution:  
1. fix `libmpi_cxx.so.1` errror  -> follow [refer](https://tweaks-tips.blogspot.com/2017/12/microsoft-cntk-libmpi-importerror.html), `sudo ln -s /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.20 /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.1` and `sudo ln -s /usr/lib/x86_64-linux-gnu/libmpi.so.20.10.1 /usr/lib/x86_64-linux-gnu/libmpi.so.12`  and update the path as `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu`.
2. fix `libmklml.so`. -> install by `conda install -c anaconda mklml` and update path by `export LD_LIBRARY_PATH=/home/jet/anaconda3/envs/py2/lib:$LD_LIBRARY_PATH`.  
It pass import cntk with warning
``` bash
/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/cntk_py_init.py:47: UserWarning: Unsupported Linux distribution (ubuntu-18.04). CNTK supports Ubuntu 16.04 and above, only.
  warnings.warn('Unsupported Linux distribution (%s-%s). CNTK supports Ubuntu 16.04 and above, only.' % (__my_distro__, __my_distro_ver__))
```
However, new problem is `DQNcar.py` cannot run through, with bugs __MemoryError__ as 
```
/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/cntk_py_init.py:47: UserWarning: Unsupported Linux distribution (ubuntu-18.04). CNTK supports Ubuntu 16.04 and above, only.
  warnings.warn('Unsupported Linux distribution (%s-%s). CNTK supports Ubuntu 16.04 and above, only.' % (__my_distro__, __my_distro_ver__))
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Traceback (most recent call last):
  File "DQNcar.py", line 505, in <module>
    agent = DeepQAgent((NumBufferFrames, SizeRows, SizeCols), NumActions, monitor=True)
  File "DQNcar.py", line 270, in __init__
    self._memory = ReplayMemory(memory_size, input_shape[1:], 4)
  File "DQNcar.py", line 35, in __init__
    self._states = np.zeros((size,) + sample_shape, dtype=np.float32)
MemoryError
```


Any body got a idea?

**Comment by yujianyuanhaha** [comment]
solved

**Comment by TarrySingh** [comment]
What was the solution?

**Comment by aidevnn** [comment]
@TarrySingh look at the msg error displayed when you run cntk
`python -c "import cntk; print(cntk.__version__)"`

if you see 
`ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory`

Search in your disk
`find ~ -name libmpi*`

if it exists, thats good, else install 
`conda install openmpi`

Rerun some search to find libmpi* folder.
Compare the differences between extension. Create symlink then export LD_LIBRARY_PATH if needed.

**Comment by sudomachine** [comment]
@yujianyuanhaha 
thank you! the first solution was helpful
