### ISSUE TITLE
Cifar10 convolutional error shapes are not compatible

### ISSUE THREAD

**Issue by mbz** [Microsoft/CNTK#350]
I'm trying to run the example `01_Conv.cntk` from `Examples/Image/Miscellaneous/CIFAR-10` and get the following error. Any idea what's wrong? 

```
Validating --> h1.t = Times(h1.W[64 x 576], pool3[3 x 3 x 64 x * {W=3, H=64, C=3}])
EXCEPTION occurred: h1.t Times operation: Left [64 x 576] and right [3 x 3 x 64] operands' shapes are not compatible.
```

I'm also getting a similar error running `03_ResNet.cntk`

```
Validating --> OutputNodes.t = Times(OutputNodes.W[10 x 64], pool[1 x 1 x 64 x *])
EXCEPTION occurred: OutputNodes.t Times operation: Left [10 x 64] and right [1 x 1 x 64] operands' shapes are not compatible.
```

Thanks

**Comment by Alexey-Kamenev** [comment]
Hello,
Which version are you using? Can you please try the latest version from master?

**Comment by mbz** [comment]
I believe I'm on the latest on master. Can I confirm this?

**Comment by Alexey-Kamenev** [comment]
Yes, can open `01_Convolution.ndl` and look how `h1` layer is defined? If it's:
```
    h1 = DNNImageReLULayer(3, 3, cMap3, hiddenDim, pool3, fc1WScale, fc1BValue)
```
then you have the latest version.

**Comment by mbz** [comment]
Updating CNTK fixed the issue. Thanks.
