### ISSUE TITLE
Is sequence training supported?

### ISSUE THREAD

**Issue by sk210892** [Microsoft/CNTK#351]
Hi,
Is sequence training supported in CNTK?
I am trying to build a neural model for sentiment analysis. Say for example, for IMDB task, we have positive or negative labels for each of the movie review (each review is a paragraph). Is it possible to build such models in CNTK? If yes, which reader should I use?

Thanks!

**Comment by raminia** [comment]
I have a similar issue. I would like to build an experiment to do sequence classification of audio using CNTK. I'm looking for a relevant CNTK example to replicate the network in 
http://deeplearning.net/tutorial/lstm.html which is well summarized in [Figure 2 of that page](https://cloud.githubusercontent.com/assets/2532252/14826744/1ba64328-0b94-11e6-8226-e410688a6804.png). The most relevant example that I found was in the master, under text analysis examples in 
[CNTK Root]\Tests\EndToEndTests\Text\SequenceClassification\Config\seqcla.cntk 
which uses BrainScript. However it has very minimal documentation.

I need to make sure that 
1- the mean pooling over time is well defined under the BrainScript file.
2- The input data is fed properly as sequence.
Could someone point me to the right direction for the BrainScript documentation and related examples? 

Ramin

**Comment by frankseide** [comment]
BrainScript is not released yet. The biggest thing still missing is the documentation. Basically, it is an extension to the current NDL language, in that it now uses a real expression parser. This also allowed to add a few extra things such as conditional expressions (if/then/else), arrays, recursive functions, and lambdas.

**Comment by jordan-at-systran** [comment]
I too am interested in the sequence training in CNTK, for something similar to sentiment analysis.  Is that possible with CNTK using BrainScript?  Are there any examples of this?

Doug

**Comment by cha-zhang** [comment]
We support sequence training with both Python and BrainScript now. Check the Tutorial and Examples folders for such examples. 

I'm closing this issue since this thread is now very old. Feel free to create a new issue if this is not resolved.
