### ISSUE TITLE
Dynamic slicing of a tensor

### ISSUE THREAD

**Issue by christopher5106** [Microsoft/CNTK#3511]
Hi,

I would like to slice a tensor given a dynamic value (coming from a shape).

Is it possible to add this feature ?

**Comment by delzac** [comment]
How about wrapping the slice op into a layer so that you don't have hard code the value.

Something like this:

```
def SliceLayer(whatever_parameter):

    def slice_op(input_tensor):
        return C.slice(input_tensor, 0, whatever_parameter, input_tensor.shape[0])

    return slice_op
```

Work that work for you?

**Comment by christopher5106** [comment]
No, dynamic in the result of a tensor.

whatever parameter = input_tensor[0]

Is not possible currently I think

**Comment by delzac** [comment]
If you want to slice based on the evaluated output value of a network, it seems like what you really need is a dynamic computational graph.

At the moment only pytorch and chainer offers that.

An alternative is to implement some kind of masking through element_select.

**Comment by delzac** [comment]
@christopher5106 I think you might be looking for the ops called [gather](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.gather)

**Comment by christopher5106** [comment]
gather op takes a tensor of indices, while I have only start and end indices which are dynamic. That would work if I had a arange/range in CNTK, which is not the case. The only arange I have is the numpy arange which is static.

**Comment by christopher5106** [comment]
Duplicate of #3010
