### ISSUE TITLE
MathCUDA compile error.

### ISSUE THREAD

**Issue by tendimsol** [Microsoft/CNTK#3525]
Hello,

I have followed all the windows setup steps provided, but cannot compile a  clean CNTK solution.
The problem appears to be versions and CUDA related. I also tried to update to CUDA 10 Toolkit but this does not change the script execution paths etc. 

Please advise what the issue is and when we can expect non c++ based packages for use in UWP apps.
https://blogs.windows.com/buildingapps/2017/08/31/cognitive-toolkit-model-evaluation-uwp/#BGFLfZiO2hFbKb0S.97   < Cannot Replicate plus its split code and and thus limiting from the application dev perspective.

What am I doing wrong? and is this a bug?

Thanks.

![image](https://user-images.githubusercontent.com/13979822/49428093-40bf5b00-f7f9-11e8-8c35-da61899da1b8.png)

![image](https://user-images.githubusercontent.com/13979822/49428068-271e1380-f7f9-11e8-9588-6bf8adf03755.png)

![image](https://user-images.githubusercontent.com/13979822/49428035-12418000-f7f9-11e8-8003-2a402669b3eb.png)

![image](https://user-images.githubusercontent.com/13979822/49428156-63ea0a80-f7f9-11e8-9cb5-b16b604ff12a.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" --use-local-env --cl-version 2017 -Xcompiler /WX -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IC:\Users\TDS\cntk\Source\Common\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -I"c:\local\cub-1.7.4" -I"c:\local\cudnn-9.0-v7.0.5\cuda\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include"   -lineinfo  --keep-dir C:\Users\TDS\cntk\x64\.build\Release_NoOpt\Source\Math\\MathCUDA -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=field_without_dll_interface" -Xcompiler "/wd 4819"   -use_fast_math -DNO_SYNC -DWIN32 -D_WINDOWS -D_USRDLL -DMATH_EXPORTS -DUSE_CUDNN -D_UNICODE -DUNICODE -D"CNTK_VERSION=\"2.6\"" -D"CNTK_VERSION_BANNER=\"2.6+\"" -D"CNTK_COMPONENT_VERSION=\"2.6\"" -DHAS_MPI=1 -DCUDA_NO_HALF -D__CUDA_NO_HALF_OPERATORS__ -Xcompiler "/EHsc /W4 /nologo /Od /FS /Zi  /MD " -o C:\Users\TDS\cntk\x64\.build\Release_NoOpt\Source\Math\\MathCUDA\CuDnnBatchNormalization.cu.obj "C:\Users\TDS\cntk\Source\Math\CuDnnBatchNormalization.cu"" exited with code 2.	MathCUDA	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 9.0.targets	707

**Comment by tendimsol** [comment]
Are there any UWP examples that actually create a model and trainer and execute?

I feel the UWP sample provided is incredibly limiting, and as I dont know c# - rewriting all those functions into the UWP Lib Project .cpp and .h files seems like massive overhead, so I would like to ask my question again about simple dll import into UWP app and use from C#

**Comment by tendimsol** [comment]
obviously the creator felt the same way, which is why they ask you to just pick a pre-existing model. :P

**Comment by jeandebleau** [comment]
it is a compiler error, cuda 9.0 is not compatible with the latest VC2017.

You need to use another toolset. See https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-windows#building-cntk

**Comment by tendimsol** [comment]
cool, thank you.
