### ISSUE TITLE
Is there documentation that explains how to build CNTK from source?

### ISSUE THREAD

**Issue by ghostplant** [Microsoft/CNTK#3526]
Hi. I'd like to build a `CUDA10-native` CNTK binary version on `Linux`, but existing compiling documentations I found are hardly working or up-to-date. Any 
recommended links that could help me with that? Thanks.

**Comment by thiagocrepaldi** [comment]
Cuda 10 will be supported on CNTK 2.7, which should be released by December 2018. Latest CNTK version supports CUDA 9.0, only.
