### ISSUE TITLE
Custom function in C++ example

### ISSUE THREAD

**Issue by DPJep** [Microsoft/CNTK#3531]
I'm trying to implement a MC Dropout layer, where the dropout rate is kept on inference time.

Can anyone give me an exmaple implmentation of 

virtual BackPropStatePtr Forward(const std::vector<ValuePtr>& inputValues,
                                         std::unordered_map<Variable, ValuePtr>& outputs,
                                         const DeviceDescriptor& computeDevice = DeviceDescriptor::UseDefaultDevice(),
                                         const std::unordered_set<Variable>& outputsToRetainBackwardStateFor = {}) = 0;

and 
        CNTK_API virtual void Backward(const BackPropStatePtr& state,
                                       const std::unordered_map<Variable, ValuePtr>& rootGradientValues,
                                       std::unordered_map<Variable, ValuePtr>& backPropagatedGradientValuesForInputs);

**Comment by DPJep** [comment]
More specifically, can one use exisiting functions inside a custom function?

**Comment by DPJep** [comment]
I have tried to port the example from: https://cntk.ai/pythondocs/extend.html with inspiration from: https://github.com/Microsoft/CNTK/blob/987b22a8350211cb4c44278951857af1289c3666/Examples/Extensibility/CPP/UserMatrixMultiplicationOp.h

This seems to compile work for Forward() on CPU devices but on GPU I get 
 page error reading location 0x0000000702800000 (status code 0xC0000022) on the buffer access

Any help on GPU implementation would be much appreciated.

			class MyPlus
				: public Function
			{
			public: 
				static FunctionPtr Create(const Variable& leftOperand, const Variable& rightOperand, const Dictionary& attributes, const std::wstring& name)
				{
					return AsComposite(MakeSharedObject<MyPlus>(leftOperand, rightOperand, attributes, name));
				}

				static FunctionPtr Create(const Variable& leftOperand, const Variable& rightOperand, const std::wstring& name)
				{
					return Create(leftOperand, rightOperand, Dictionary(), name);
				}

				MyPlus(const Variable& leftOperand, const Variable& rightOperand, const Dictionary& attributes = Dictionary(), const std::wstring& name = L"Plus")
					: Function({ leftOperand, rightOperand }, attributes, name)
				{}

				void Backward(const BackPropStatePtr& state,
					const std::unordered_map<Variable, ValuePtr>& rootGradientValues,
					std::unordered_map<Variable, ValuePtr>& backPropagatedGradientValuesForInputs)
				{
					return;
				}

			protected:
				BackPropStatePtr Forward(const std::vector<ValuePtr>& inputValues,
					std::unordered_map<Variable, ValuePtr>& outputs,
					const DeviceDescriptor& computeDevice = DeviceDescriptor::UseDefaultDevice(),
					const std::unordered_set<Variable>& outputsToRetainBackwardStateFor = {}) override
				{

					auto leftOperandData = inputValues[0]->Data();
					auto rightOperandData = inputValues[1]->Data();

					auto& outputValue = outputs[this->Output()];

					if (outputValue == nullptr)
					{
						NDShape AllocShape = leftOperandData->Shape();
						outputValue = MakeSharedObject<Value>(MakeSharedObject<NDArrayView>(DataType::Float, AllocShape, computeDevice));
					}
					auto outputData = outputValue->Data();
					outputData->SetValue(0.0f);
					auto leftBuffer = leftOperandData->DataBuffer<float>();
					auto rightBuffer = rightOperandData->DataBuffer<float>();

					auto outBuffer = outputData->WritableDataBuffer<float>();

					for (size_t i = 0; i < outputData->Shape().TotalSize(); ++i)
						outBuffer[i] = leftBuffer[i] + rightBuffer[i];

					return MakeSharedObject<BackPropState>(this->shared_from_this(), computeDevice);//std::unordered_map<Variable, ValuePtr>({ {Inputs()[0], inputValues[0] } })
				}

				const std::wstring& OpName() const override
				{
					static const std::wstring opName = L"NativeUserTimesOp";
					return opName;
				}

				size_t CurrentVersion() const override { NOT_IMPLEMENTED; }

				void InferOutputs(std::vector<Variable>& outputs) override
				{
					auto leftOperand = Inputs()[0];
					auto rightOperand = Inputs()[1];

					if (leftOperand.Shape().Rank() != rightOperand.Shape().Rank())
						std::runtime_error("Operands must be same rank");

					outputs.push_back(OutputVariable(NDShape({ leftOperand.Shape() }), leftOperand.GetDataType(), leftOperand.DynamicAxes()));
				}

			};

**Comment by bencherian** [comment]
I can't really help with your specific issue, but if you just want to do MC dropout during inference, just add some output variable to the `outputsToRetainBackwardStateFor` argument to `Forward`, use the existing dropout functionality and run the forward pass a few times to get your statistics. You don't need to implement a custom layer.

**Comment by DPJep** [comment]
Thanks. That’s exactly the solution I got to today as well. Good to know it’s correct.
