### ISSUE TITLE
How to add name only layer without any performance degradation?

### ISSUE THREAD

**Issue by kkc0923** [Microsoft/CNTK#3544]
Hi, I want to know how to add name-only layer for further using (re-use part of model, debugging and so on) in Python API.

I found that Activation(activation=identity, name='') can be used this purpose, but I have concern whether it add additional memory consuming or performance degradation.

Thanks.

**Comment by delzac** [comment]
Is [Label ](https://www.cntk.ai/pythondocs/cntk.layers.layers.html#cntk.layers.layers.Label)what you are looking for?

**Comment by kkc0923** [comment]
Oh, it looks what I looking for. Thanks.
