### ISSUE TITLE
Help getting Inception-V3 Brainscript to Work

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#3545]

**Comment by JohnCraigPublic** [comment]
I'm trying to get the Inception-V3 Brainscript to work that is provided by Microsoft on their samples page.  The issue is that it is set up for images of 299x299x3 with 1000 labels.   In my case, my images are 200x200x1 with 192 classes.    So, I set those variables at the top of the Brainscript, but apparently its not that simple.  This issue I get is below.   How can I edit the Brainscript files to work in my case?

[CALL STACK]
    > std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>  
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>   (x10)
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  __autoclassinit2 (x3)
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator= (x2)

EXCEPTION occurred: Convolution operation requires that kernel dim 5 <= input dim 2.

**Comment by delzac** [comment]
It is probably because the "image"/feature map gets progressively "scaled" down deeper in the layers. With a 200 by 200 image, at a certain layer, the feature map is only left with 2px weight/height.

Would recommend that you scale your image up instead of changing the input image dimensions that the model was build for.

**Comment by JohnCraigPublic** [comment]
I was hoping someone might know an easy modification - because I already have a huge amount of data at 200x200 that I used with AlexNet, and wanted to do an apples-to-apples comparison.

**Comment by JohnCraigPublic** [comment]
I re-formed my data for size 299x299 and now all is good.
