### ISSUE TITLE
Running VGG16 on multiple nodes is slower than single node

### ISSUE THREAD

**Issue by chung1204** [Microsoft/CNTK#3553]
I did the distributed training on multi nodes using the code in "/CNTK/Examples/Image/Classification/VGG/Python/Vgg16_ImageNet_Distributed.py"

It works well when using multiple gpu on a single node.

However, they are being trained very slowly when running on multiple nodes

When operating in a multinode, the following commands were used.
"mpiexec --mca btl_tcp_if_include eth0 -hostfile /path_to_hostfile/hostfile python3 /path_to_python_file/Vgg16_ImageNet_Distributed.py"

The btl_tcp_if_include option added because it does not find the rank value when it is not used.

The rest was set up as https://docs.microsoft.com/en-us/cognitive-toolkit/Multiple-GPUs-and-machines#42-running-parallel-training-with-python informed.

I would be grateful if you could provide me with a solution.

**Comment by delzac** [comment]
Probably has to do with your specific hyperparameters (minibatch size might be the most likely culprit). Take a look at #440, it might help.

**Comment by chung1204** [comment]
Thank you for your reply.

The problem was solved by using 1-bit sgd!!
