### ISSUE TITLE
Gaussian error function

### ISSUE THREAD

**Issue by christopher5106** [Microsoft/CNTK#3556]
I would like to have tf.erf under CNTK. Any advice how to implement it ? Thanks

**Comment by delzac** [comment]
Maybe you want to implement this directly in cntk? According to the stackoverflow [post](https://stackoverflow.com/questions/457408/is-there-an-easily-available-implementation-of-erf-for-python), this implementation has a error is less than 1.5 * 10-7 for all inputs. Let me know if you have problems.

```
def erf(x):
    # save the sign of x
    sign = 1 if x >= 0 else -1
    x = abs(x)

    # constants
    a1 =  0.254829592
    a2 = -0.284496736
    a3 =  1.421413741
    a4 = -1.453152027
    a5 =  1.061405429
    p  =  0.3275911

    # A&S formula 7.1.26
    t = 1.0/(1.0 + p*x)
    y = 1.0 - (((((a5*t + a4)*t) + a3)*t + a2)*t + a1)*t*math.exp(-x*x)
    return sign*y # erf(-x) = -erf(x)
```

**Comment by christopher5106** [comment]
Sounds great. Let me try it.

**Comment by delzac** [comment]
You may want to take a look at the library i maintain, its called [cntkx](https://github.com/delzac/cntkx/blob/master/ops/__init__.py#L205). Just updated it with an erf implementation.

**Comment by christopher5106** [comment]
Great, that works similarly as tf.erf !

My layer is : 

class GELU(Layer):
    def __init__(self, **kwargs):
        super(GELU, self).__init__(**kwargs)

    def build(self, input_shape):
        super(GELU, self).build(input_shape)

    def call(self, x):
        # save the sign of x
        positives = K.cast(K.greater_equal(x, 0.), K.dtype(x))
        sign =  positives * 1 + (1. - positives ) * -1
        x = K.abs(x)

        # constants
        a1 =  0.254829592
        a2 = -0.284496736
        a3 =  1.421413741
        a4 = -1.453152027
        a5 =  1.061405429
        p  =  0.3275911

        # A&S formula 7.1.26
        t = 1.0/(1.0 + p*x)
        y = 1.0 - (((((a5*t + a4)*t) + a3)*t + a2)*t + a1)*t* K.exp(-x*x)
        return sign*y # erf(-x) = -erf(x)

    def compute_output_shape(self, input_shape):
        return input_shape

**Comment by delzac** [comment]
I'm glad it worked out for you :)
