### ISSUE TITLE
Network model conversion & dumping with preserved structures

### ISSUE THREAD

**Issue by Determinant** [Microsoft/CNTK#357]
A network model including the trainable parameters is stored in a internal binary format defined by CNTK. However, sometimes, it is a desirable and very useful feature to be able to convert the model into other toolkit formats (such as nnet in Kaldi). At least, it would be quite helpful if there is a simple and direct way of dumping the trained parameters into a human-readable text format for some other use (such as comparing the baselines by manually plugging in the NN trained by CNTK to an existing ASR system).

**Comment by Determinant** [comment]
I know there is `DumpModel` in MEL. However, that will generate a human-readable text that is not easy to parse and convert to other format. It has no explicit indicator of matrix begin/end, but looks more like a log file for browsing the network parameters.

**Comment by dongyu888** [comment]
Does the top level dump command work for you?

**Comment by Determinant** [comment]
Sorry, but could you elaborate on the "top level dump command"? Where is it? I'm still new to CNTK. :)

**Comment by dongyu888** [comment]
Check “dumpnode” command in https://github.com/Microsoft/CNTK/wiki/Top-level-commands

**Comment by Determinant** [comment]
Thanks. It seems that dump command is a shortcut to dumping using MEL. But the dumped parameters are more like logging for humans, which is not very easy to parse and convert into other formats that could be read by other tools. It would be great if there was an output format that is easy to parse, or an ascii alternative format of the current binary model format. (like what `nnet-copy --binary=false` produces in Kaldi)

**Comment by wolfma61** [comment]
The issue has been dormant for a long while. Please open a new issue if you still experience problems in the latest release.
