### ISSUE TITLE
ImageReader plugin not loading after re-building CNTK with ZIP support

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/CNTK#359]
I've re-compiled CNTK with ZIP support for the ImageReader. I built the ZIP libraries as suggested on the Wiki, and I see during the ImageReader build process that it no longer prints out the message "ImageReader will be built without ZIP support". However, when I now run CNTK with a config file that loads images, it fails with the error message "Plugin not found: 'ImageReader.dll'" (thrown in Plugin.Load). 
It fails even for configs that do not use the ZIP file syntax in the mapping file. I turned off ZIP support by changing the `ZLIB_PATH` environment variable, re-built, and ran my image config again - all works fine. I turned ZIP support back on, re-built, ran my image config, and it threw the exception again. 
I verified that `zip.dll`and `zlib1.dll` are available alongside `ImageReader.dll`.
Any suggestions about what could have gone wrong?

For reference, the call stack is

    EXCEPTION` occurred: Plugin not found: 'ImageReader.dll'
    [CALL STACK]
    > Microsoft::MSR::CNTK::DataReader::DataReader<Microsoft::MSR::CNTK::ConfigParameters>  
    - std::make_shared<Microsoft::MSR::CNTK::DataReader,Microsoft::MSR::CNTK::ConfigParameters & __ptr64>  
    - CreateObject<Microsoft::MSR::CNTK::DataReader>  
    - DoTrain<Microsoft::MSR::CNTK::ConfigParameters,float>  
    - DoCommands<float>

**Comment by Alexey-Kamenev** [comment]
Can you verify that you have all dependencies in CNTK binary folder? The easiest way to do that would be using `depends` tool and look into `ImageReader.dll` dependencies.

**Comment by ant0nsc** [comment]
Thanks Alexey. I used `depends`, and it turned out that the DLL was referencing `zlib.dll` rather than `zlib1.dll` that was in the output folder. Don't know how I ended up in that state, but after renaming DLLs the problem was gone. For reference: [`depends` tool Wikipedia page](https://en.wikipedia.org/wiki/Dependency_Walker)

**Comment by ant0nsc** [comment]
I have now done a clean build, and I still get an image reader DLL that depends on `zlib.dll` rather than `zlib1.dll`, because my `zib.dll` references `zlib.dll`. Alexey, is it possible that the build instructions on [the Wiki page](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows) are off? Could it be that the step "rename `zlib.dll` to `zlib1.dll`" should come before building libzip?

**Comment by Alexey-Kamenev** [comment]
Is there any chance you might have any other programs that can be using zlib? Things like cygwin etc... We tested our instructions on several _clean_ machines and it always worked. The name of the dll should be zlib1 (see [zlib FAQ](http://www.zlib.net/DLL_FAQ.txt)) and this is what we get when building libzip in our environment.
