### ISSUE TITLE
Plus broadcasting in C++

### ISSUE THREAD

**Issue by mkompanek** [Microsoft/CNTK#3618]
Hi, I am trying to implement 3D convolution with bias, how ever I cannot make broadcasting work ? What am i doing wrong ?

`	FunctionPtr Convolution3DLayer::Construct(CNTK::Variable input, const CNTK::DeviceDescriptor & device)
	{
		auto id = this->GetId();

		size_t numInputChannels = input.Shape()[input.Shape().Rank() - 1];

		auto convParams = Parameter({ m_kernelSize, m_kernelSize, m_kernelSize, numInputChannels, m_filters }, DataType::Float, GlorotUniformInitializer(), device);
		auto convFunction = Convolution(convParams, input, { m_stride, m_stride, m_stride, numInputChannels });

		auto plusParam = Parameter({ m_filters }, 0.0f, device);

		// Binary elementwise operation Plus: Left operand 'Parameter('Parameter9', [32], [])' shape '[32]' is not compatible with right operand 'Output('Convolution6_Output_0', [91 x 114 x 81 x 32], [*, #])' shape '[91 x 114 x 81 x 32]'.'
		//auto retval = CNTK::Plus(plusParam, convFunction); 

		// throws Reshape: Operand (sub-)dimensions '[32]' incompatible with desired replacement (sub-)dimensions '[3 x 3 x 3 x 1 x 32]'. Number of elements must be the same..
		auto retval = CNTK::Plus(CNTK::Reshape(plusParam, { m_kernelSize, m_kernelSize, m_kernelSize, numInputChannels, m_filters }), convFunction);

		m_paramCount = convParams.Shape().TotalSize() +plusParam.Shape().TotalSize();

		return CNTKU::ActivateByName(convFunction, m_activation, L"Convolution3D_" + id);
	}`

**Comment by elevir** [comment]
@mkompanek hello! 
Dimensions which you want to broadcast must be equals to 1. For example, if you want to broadcast parameter with dimension { 32 } to parameter with dimensions { N, 32 }, you have to reshape first parameter to { 1, 32 }.

**Comment by mkompanek** [comment]
@elevir Thanks a lot !
