### ISSUE TITLE
CSEvalClient problem

### ISSUE THREAD

**Issue by DeepLearningFanatic** [Microsoft/CNTK#362]
Hello:

 I am trying to change around  the CSEvalClient to test and see if it works with simple.cntk. got the following code:

  using (var model = new IEvaluateModelManagedF())
                {
                    // Initialize model evaluator
                    string config = GetFileContents( myPath to simple.cntk);
                    Console.WriteLine(config);
                    model.Init(config);
}...
I changed the String variables in the config to the right location, verified with Console.WriteLine( config) line, but Model.Init(config) throws the following Errors:
 Attempt to access invalid address.
 Attempt to access invalid address.
 Attempt to access invalid address.
Microsoft::MSR::CNTK::GetEval<double>
The specified Module could not be found
Has anyone encounter this issue. 
I was able to train using the CPUOnly  binary, but cant make it work in c#.

Has anyone had this error and was able to fix it:

**Comment by klmsj** [comment]
simple.cntk  is really exist by config path?

**Comment by DeepLearningFanatic** [comment]
It does exists, the GetFileContents() method returns the string of the Content of the cntk file on config variable, which I can see it.

**Comment by BorisJineman** [comment]
I think you need to set the environment's dir.
such as that, if you may check whether the current folder is correctly, you may need to set the "Environment.CurrentDirectory" also to the data folder. 

such as bellow code line,
`Environment.CurrentDirectory = Path.Combine(initialDirectory, @"..\..\Examples\Image\MNIST\Data\");  `

We set the current directory to the ~\Examples\Image\MNIST\Data\ .( only if you run the CSEvalClient directly and does not modify the directorys of the CNTK repo).

**Comment by DeepLearningFanatic** [comment]
Hello Boris, Thank you for your prompt response:

I understood your explanation, However, I still have a problem with CSEvalClient project. Now, this is the Actual error I am Getting. 
![image](https://cloud.githubusercontent.com/assets/18507006/14623342/4ed5b1c0-059f-11e6-8b6c-0171d413ee2d.png)

I think this may be a bug I am getting, the reason being that when I run the cntk confiFile=simple.cntk, it runs smoothly...
![image](https://cloud.githubusercontent.com/assets/18507006/14623276/b3ac1fcc-059e-11e6-88e1-93d5dc15ddbe.png)

Now, I know that my configuration file is being accessed by CSEvalClient because I can see it, when I apply the text visualizer to the Config variable. 
I also Know that the Configuration File simple.cntk does not have any errors, since it works outside of VS 2013. So I was wondering if this is a bug, maybe someone else is having this error, or is it just me being unlucky, and my PC has one of those not supported configurations( I have a Laptop Samsung with intel core i7). Of Note: The CSEvalClient i am using is unchanged, except for the string to my simple.cntk file.

**Comment by gaizkan** [comment]
@DeepLearningFanatic: I am not quite certain what your modifications are, but I was able to run the Simple.cntk using the EvaluateModelMultipleLayers method.
`
        private static void EvaluateModelMultipleLayers()
        {
            try
            {
                Environment.CurrentDirectory = Path.Combine(initialDirectory, @"..\..\Examples\Other\Simple2d\Data\");

                Dictionary<string, List<float>> outputs;

                using (var model = new IEvaluateModelManagedF())
                {
                    // Initialize model evaluator
                    string config = GetFileContents(Path.Combine(Environment.CurrentDirectory, @"..\Config\Simple.cntk"));
                    model.Init(config);

                    // Load model
                    string modelFilePath = Path.Combine(Environment.CurrentDirectory, @"..\Output\Models\Simple.dnn");
                    model.CreateNetwork(string.Format("deviceId=-1\nmodelPath=\"{0}\"", modelFilePath));

                    // Generate random input values in the appropriate structure and size
                    var inputs = GetDictionary("features", 2, 255);

                    // We can preallocate the output structure and pass it in (multiple output layers)
                    outputs = GetDictionary("ScaledLogLikelihood", 2, 1);

                    model.Evaluate(inputs, outputs);
                }

                OutputResults(outputs);
            }
`
What I changed:
* The path to the Simple Data location
* Retrieving the file contents of Simple.cntk
* Specifying the correct model path for Simple.dnn (make sure the model actually exists)
* Specifying the correct input layer (features) with a size 2
* Specifying the correct output layer (ScaledLogLikelihood) with the appropriate size of 2

Best regards,
Gaizka

![image](https://cloud.githubusercontent.com/assets/10653002/14641044/b4197fbc-0644-11e6-8536-96bf19e08e01.png)

**Comment by DeepLearningFanatic** [comment]
@gaizkan: one question, is your cntk the binaries from february, 2016? Or did you compile your own version of cntk?

**Comment by DeepLearningFanatic** [comment]
Ok, Here is how I got it to work:
1-) Re Compiled  the most updated version of CNTK as release_CpuOnly x64, since, as of this date, the Binaries are from February 8, 2016.
2-) also made CSEvalClient release_CpuOnly x64. 

This issue had been addressed before here: C# wrapper - unmatched bracket found in parameters #264

**Comment by gaizkan** [comment]
@DeepLearningFanatic : I am glad to hear you were to run the sample again. As far as your question goes: I usually get the latest from source. I compiled and ran the Debug version.
I will close this comment.
