### ISSUE TITLE
C++, easiest way to decode a CNTK::ValuePtr without providing outputVariable

### ISSUE THREAD

**Issue by liuyw07** [Microsoft/CNTK#3639]
Hi guys, is there a way to decode a CNTK::Value after its construction, without providing a Variable? Right now we have CopyVariableValueTo, which works fine but needs that outputVariable. What if I just constructed a ValuePtr using for example Create(), and I want to see what's inside this ValuePtr? Is there a quick hack to do this?  Something that returns a std::vector<> of some sort together with whatever additional information about this ValuePtr.

Thanks!

**Comment by elevir** [comment]
@liuyw07 hi! 
If you need another way to take data from ValuePtr, you can get `NDArrayViewPtr` from `ValuePtr` by invoking `Data()` and from `NDArrayViewPtr` you can invoke `DataBuffer<T>()` which will return you `const T*`. But make sure, that `ValuePtr` contains data on CPU device, if it isn't you have to copy Data from GPU `ValuePtr` to CPU `ValuePtr` by invoking `CopyFrom` method.
Did I understand you correctly? Or do you need something else from ValuePtr? :)

**Comment by liuyw07** [comment]
Thank you! I think that's good enough, with the raw pointer and data type and shape information of the ValuePtr we should be able to make sense out of the data. Thanks!
