### ISSUE TITLE
CNTK2.7 All in one Wheel

### ISSUE THREAD

**Issue by iadevelop** [Microsoft/CNTK#3647]
Hello.

Im very glad for this new release of CNTK2.7

But actually, pip install cntk-gpu require to install also manually a lot of dll dependencies, where the wheel of CNTK2.6 was all in one with full dependencies.

Is a complete wheel file will be released or do i install all dependencies cudatoolkit/cudnn/mkl/opencv manually?

Thx

**Comment by xgirones** [comment]
How do we install the dependencies?

**Comment by xgirones** [comment]
I solved it by copying them manually from the binary distribution...

**Comment by iadevelop** [comment]
> I solved it by copying them manually from the binary distribution...

I tried the same things.
I downloaded this release : https://cntk.ai/dlwg-2.7.html (1G ...)
And this wheel file : https://cntk.ai/PythonWheel/GPU/cntk_gpu-2.7-cp36-cp36m-win_amd64.whl (94 mb ..)

I opened the .whl file with 7Zip, then i copied the missing 10 dependencies
cublas64_100
cudart64_100
cudnn64_7
curand64_100
cusparse64_100
libiomp5md
mkldnn
mklml
nvml
opencv_world310

in the folder cntk\libs\ of the opened archive.
Finally, i can install the new wheel file with : pip install cntk_gpu-2.7-full-cp36-cp36m-win_amd64.whl

And everything works. This whel can now be reused for differents conda env etc...

I can close the issue.

**Comment by thiagocrepaldi** [comment]
@xgirones workaround is good.
I will double check whether we can repack CNTK 2.7 to include dependencies really soon

**Comment by iadevelop** [comment]
> @xgirones workaround is good.
> I will double check whether we can repack CNTK 2.7 to include dependencies really soon

thx a lot <3

**Comment by thiagocrepaldi** [comment]
We just repacked CNTK 2.7. Enjoy!
