### ISSUE TITLE
Output ONNX model from Brainscript?

### ISSUE THREAD

**Issue by JohnCraigPublic** [microsoft/CNTK#3649]
I have done quite a lot with CNTK -- all work using Brainscript for training and then C++ for inference.    So, how can I convert my various models that I've developed to ONNX?   That is, is there a way for me to do with from Brainscript?  From C++?  Or, you are telling me I have to install and learn Python just to get models over to ONNX?

**Comment by elevir** [comment]
@JohnCraigPublic try following commands in C++:
```
auto model = CNTK::Function::Load(L"path_to_trained_cntk_model.model");
model->Save(L"path_to_trained_onnx_model.onnx", CNTK::ModelFormat::ONNX);
```

**Comment by JohnCraigPublic** [comment]
Hmmm.. crashed on the Save call.   Then I realized I was using CNTK 2.5, so I updated to 2.7 in case 'the latest' is needed for this -- but still crashes....

**Comment by elevir** [comment]
@JohnCraigPublic can you share exception message?

**Comment by JohnCraigPublic** [comment]
exception:

Node 'CrossEntropyWithSoftmax: Output('aux', [240], [, #]), Input('class', [240], [, #]) -> Output('ceAux', [], [])': Unsupported node.

**Comment by delzac** [comment]
#3676

**Comment by JohnCraigPublic** [comment]
thanks delzac
