### ISSUE TITLE
CPU is running  slower

### ISSUE THREAD

**Issue by rodrigoalor** [Microsoft/CNTK#365]
i build a solution for cpu only from the master branch,  when i prove   the examples of  CNN for mnist  the samples per second rate only achieve 40 samples per second,  i find this strange  because when i use the same example using the release 08/ 02/2016  it reached 1000 samples per second or more,
i don't know what i'm  doing  wrong,  or what can i do to achieve more faster training

 i don't have the posibility of use a GPU,  i want to use the master branch because i want to use cntk for regression

**Comment by Alexey-Kamenev** [comment]
Hello,
This is expected for now but will be significantly improved very soon. The reason is we added a ND convolution support to CNTK and on CPU it still uses a reference engine for all types of convolutions. I'm currently working on enabling fast implementations for most commonly used convolution types and hoping to finish it (at least in my branch) somewhere later this week. Let me know if you are interested in that work, I'll let you know once it's ready for testing.

**Comment by rodrigoalor** [comment]
Hello,  I will be waiting for your news, if it's useful I will share my result testing the new implementation as soon as you notify it, thanks so much for the help,  CNTK is awesome!

**Comment by Alexey-Kamenev** [comment]
Can you please try my branch `alexeyk/conv_cpu`? I'm still working on it but overall it should be functional (i.e. you can run that MNIST convo samples just fine). I'm curious what perf will you see.

**Comment by rodrigoalor** [comment]
Hello,   I tested the master branch and reached 40 again  Samples persecond and with your branch 280 samplespersecond using the convolution example from mnist,  if is necessary make this work again only say it. Thank you so much, this improve is really useful for my work.

**Comment by Alexey-Kamenev** [comment]
Good to hear it worked! Can you please sync my branch once again? I've added a small improvement which will hopefully improve perf a bit more. I'm going to merge these changes to master soon, there is still some work that can be done to improve perf even more but I'll do it later.

**Comment by rodrigoalor** [comment]
I tested in other CPU the MNIST sample again in the master branch,  the  previous version of your branch   and  your branch with the new improvement, they reached 47, 480 and 620 respectively.

**Comment by Alexey-Kamenev** [comment]
The change is now in the master. Thanks for the feedback!
