### ISSUE TITLE
CNTKTextFormatReader fails to read anything

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#366]
Hello,
I am trying to use CNTKTextFormatReader. 
My reader section of the train action looks as follows:
reader = [
        readerType = "CNTKTextFormatReader"
        file = $inputFile$
        randomize = "None"
        traceLevel = 2
        
        input = [
	        inputs = [
		    alias = "i"
	            dim = $inputDim$ 
	            format = "dense"
	        ]
	
	        labels = [
		    alias = "o"	        
	            dim = $labelDim$
	            format = "dense"
	        ]
	        
	        level = [
		    alias = "lev"	        
	            dim = 1
	            format = "dense"
	        ]
	    ]
    ]
and first two rows of data are as follows:
1 |i -0.138918023895589 -0.14814345824795 -0.175130838931495 -0.125559008738214 -0.0567980844184431 -0.0575351815381229 -0.0866034638198208 -0.0434121839267557 -0.0287496759806757 -0.0225752040277299 -0.000215789522814884 -0.0881665269853852 0.011502033975228 0.0269085502616059 0 |o -0.056741737081823 -0.0124154282063889 -0.0382507421588597 0.114137746525515 0.0533617600962582 -0.024414560457044 0.0357866385426039 0.0500682446570168 0.0720840239410775 0.045890840514426 0.0869851943344971 0.0834624338550948 |lev 982.587022405312
1 |i -0.091401721166127 -0.118389101849672 -0.0688172716563905 -5.63473366201749e-05 -0.000793444456299894 -0.0298617267379978 0.0133295531550674 0.0279920611011472 0.0341665330540932 0.0565259475590082 -0.0314247899035622 0.0682437710570511 0.0836502873434291 0.056741737081823 0 |o 0.044326308875434 0.0184909949229633 0.170879483607339 0.110103497178081 0.0323271766247789 0.0925283756244271 0.10680998173884 0.1288257610229 0.102632577596249 0.14372693141632 0.140204170936918 0.110550842194096 |lev 928.385610618689
...

But I am getting:
attempt: Unexpected character(' ') while reading a sequence id at the offset = 1
, retrying 2-th time out of 5...
attempt: success after 2 retries

EXCEPTION occurred: CNTKTextFormatReader: While reading 'E:\progs\cif/ls_12o15.txt': NoRandomizer: Expected input to contain samples, but the number of successfully read samples was 0.

Could some kind soul help?
Slawek

**Comment by raaaar** [comment]
You hit an edge case in the reader, it expects a sequence id followed by '\t' or '|' (even though, spaces should be allowed there as well).

**Comment by slaweks17** [comment]
Thank you! You were right: no space between sequence id and the first '|'  .

**Comment by frankseide** [comment]
Is this something that could be caught with a clearer error message?

**Comment by frankseide** [comment]
I just noticed that the retry loop (attempt...) seems wrong here. The retry loop only works when restarting the entire operation, but not on a stateful FILE object.

**Comment by raaaar** [comment]
The retry loop is there to mitigate intermittent HDFS issues (same strategy as in other new readers). Better error messages are in the pipeline, any suggestions on how to improve wording are welcome.
