### ISSUE TITLE
Python's "Sequential" in C++

### ISSUE THREAD

**Issue by adaber** [microsoft/CNTK#3666]
Hi, everyone

The code below can be found in CNTK/Examples/Image/Detection/FastRCNN/FastRCNN_train.py

This is exactly the function I am trying to implement in C++. I got everything working but I am not sure how to implement
```python
 conv_layers = Sequential([fixed_conv_layers, train_conv_layers])
```
in C++. I don't know how to "stack" / "join" two sub-nets coming from the same model. I want to apply Transfer Learning to my encoder-decoder model in the way where I want to "stack" / "join" my pretrained encoder that is cloned and frozen and decoder that is just cloned preserving the pretrained model's weight values.

Is there anyone who could help me with this ?

Thank you!

```python
def clone_conv_layers(base_model, cfg):
    feature_node_name = cfg["MODEL"].FEATURE_NODE_NAME
    start_train_conv_node_name = cfg["MODEL"].START_TRAIN_CONV_NODE_NAME
    last_conv_node_name = cfg["MODEL"].LAST_CONV_NODE_NAME
    if not cfg.TRAIN_CONV_LAYERS:
        conv_layers = clone_model(base_model, [feature_node_name], [last_conv_node_name], CloneMethod.freeze)
    elif feature_node_name == start_train_conv_node_name:
        conv_layers = clone_model(base_model, [feature_node_name], [last_conv_node_name], CloneMethod.clone)
    else:
        fixed_conv_layers = clone_model(base_model, [feature_node_name], [start_train_conv_node_name],
                                        CloneMethod.freeze)
        train_conv_layers = clone_model(base_model, [start_train_conv_node_name], [last_conv_node_name],
                                        CloneMethod.clone)
        conv_layers = Sequential([fixed_conv_layers, train_conv_layers])
    return conv_layers
```

**Comment by delzac** [comment]
What errors or problems are you facing? Its not clear from your description.

**Comment by adaber** [comment]
Hi, delzac

Firstly, thank you for the time you took to respond :)

Sorry for being unclear. I probably shouldn't have written "I got everything working" since there is one part that I am not sure how to implement in C++.

I'll try to be clearer this time.

I will use the following part from the above code to explain what my problem is.

```python
1)     fixed_conv_layers = clone_model(base_model, [feature_node_name], [start_train_conv_node_name],
                                        CloneMethod.freeze)
2)     train_conv_layers = clone_model(base_model, [start_train_conv_node_name], [last_conv_node_name],
                                        CloneMethod.clone)
3)     conv_layers = Sequential([fixed_conv_layers, train_conv_layers])
```
I have managed to implement 1) and 2) in C++ (using the **clone** method) but I am not sure how to implement 3). So, I don't know how to "join" / "stack" **fixed_conv_layers**  and **train_conv_layers** and create one "continuous" network out of these  two sets of layers. 

I hope this makes my question clearer.

Thanks!

**Comment by elevir** [comment]
@adaber hello!
Instead of using `Sequential` you can use `Clone` function with substitution map. For example:
```
auto fixed_conv_layers = CNTK::AsComposite(/*loaded fixed_conv_layers model*/)->Clone(CNTK::ParameterCloningMethod::Freeze);
auto conv_layers = CNTK::AsComposite(/*loaded train_conv_layers model*/)->Clone(CNTK::ParameterCloningMethod::Clone, { { /*loaded train_conv_layers model*/->Arguments()[0], fixed_conv_layers } });
```

**Comment by adaber** [comment]
Hi, elevir

Thanks for your interest and suggestions.

I had already tried what you suggested but I came across some problems. Let me explain what exactly I am trying to achieve.

My model is an encoder-decoder net with skip connections. What I'd like to do is to load a pretrained model, clone and freeze the encoder, clone the decoder preserving the pretrained weight values and "join" these two nets (encoder/decoder).

So, this is what I've tried and the results I've gotten so far:

1) I load the pretrained net
2) Clone and freeze the encoder part using 
```C++
auto frozenEncoder = CNTK::AsComposite(lastPoolEncoder)->Clone(CNTK::ParameterCloningMethod::Freeze, replacements);
```
where "replacements" is used for the input variable (image in this case). This step works okay.

3) Clone the decoder part. This is the part where I have problems with.

My idea is to clone the loaded pretrained net but also to replace the decoder's input layer with the cloned and frozen encoder's output layer. Based on this link (https://stackoverflow.com/questions/48582311/cntk-cloning-a-single-layer), the Clone method should stop cloning once it hits the replacement layer(s). My problem is that when I do this step it seems that it ends up cloning the whole pretrained network. I end up having two Input variables (instead of just one). Even this monster of a network can train :) but it cannot save the model during training because the model contains two nodes with the same name (that's the error I got). This is how I create my final network with a frozen encoder and cloned decoder.

```C++
auto frozenEncPreservedDecNet = CNTK::AsComposite(pretrainedModel)->Clone(CNTK::ParameterCloningMethod::Freeze, replacements);
```
where I tried storing different combinations of the encoder output and decoder input/output variables in replacements but nothing seems to work the way I want it to.


Now, one more thing. If I use the frozen encoder and create a decoder on top of it everything works okay. The only problem is that the decoder weights are randomly initialized in this scenario which is what I am trying to avoid to reduce the training time.

Thank you for taking the time to read this wall of text and let me know if you have any suggestions on how to get this working :)

**Comment by elevir** [comment]
@adaber it is hard to say something about your problem for me, because I can't see a context of code of how you are clonning the model. But, I think you can find a solution from an example of transfer learning on [this page](https://docs.microsoft.com/en-us/cognitive-toolkit/Build-your-own-image-classifier-using-Transfer-Learning), it is python example, but all functions from this example has analogue in C++ CNTK (except find_by_name, on C++ and C# it has another logic, but as I understood, you don't have any problems with layers searching). If you are trying to cut decoder from shared model for encoder/decoder, it can be very usefull article.

> Thank you for taking the time to read this wall of text and let me know if you have any suggestions on how to get this working :)

You're welcome! :)

**Comment by adaber** [comment]
Hi, elevir

Thank you again for taking your time to reply. I really appreciate your suggestions :)

I agree that it's hard to troubleshoot my problem without the actual context. I have just wanted to see what other people's experience is on cloning models using CNTK.

All the examples I found (and the one you suggested) clone their models all the way to the first layer  replacing the input layer. I got that part working.

My main problem is cloning a part of a neural net that starts at the end and ends in the middle of the cloned net. I am not sure if it's because I am doing something wrong or the skip connections (encoder to decoder) make the cloning more complex.

Anyhow, I will keep trying and I might eventually look deeper into the CNTK source code when I have time. I will post here if I find a solution :)

Thanks again for your suggestions and willingness to help!

**Comment by delzac** [comment]
Hi @adaber,

It should be possible to clone from the end of the layer and stop anywhere in the middle of the network.

Unfortunately, because i don't code in c++, i only have sample code in python, you can take a look at it below.

```
import cntk as C
from cntk.layers import Dense
from pprint import pprint


a = C.input_variable(10)
b = Dense(100)(a)
c = Dense(100)(b)
d = Dense(100)(c)

x = C.input_variable(100)
e = d.clone(C.CloneMethod.clone, {c: x})

print(e)
pprint(C.logging.find_all_with_name(e, ''))  # 2-layer network

```

**Comment by adaber** [comment]
Thanks for the comment, delzac. Python is fine :)

Your example looks good and is somewhat straightforward.

What do you think about the following scenario ?

You got a simple UNet (encoder-decoder with skip connections).

Now, you want to do Transfer Learning on your encoder. This means that you want to clone and freeze your pretrained UNet's encoder starting from its last pool layer all the way to the input variable. No problem. I got this working.

What I did initially was just adding a new (randomly initialized) decoder on top of my cloned and frozen encoder and everything worked fine.

Then I decided to try to shorten the training time by using a cloned decoder (instead of the randomly initialized one) which would preserve the pretrained UNet decoder's weight values with the goal of a better starting training point.

So, my approach is to clone the pretrained decoder from the pretrained model's output to the decoder's input layer and replace the decoder's input with the encoder's output. Is this how you would do it ?

I tried this approach but I always end up cloning the whole pretrained network instead of just the decoder part. My created network has two input variables and two instances of some of the layers because of that. So, I am not sure how to "join/stack" my frozen encoder and cloned decoder.

Do the skip connections make this process more complicated ?

What are your thoughts ?

Thanks!

**Comment by delzac** [comment]
Yes i suspect it is the skip connections (and hence layers) from the encoder to the decoder that got cloned over. The clone function is working as intended. The decoder takes input from the bottom of the U and the skip connections, hence its necessary to clone over parts (or all) of the encoder.

If you are cloning both the pretrained encoder and pretrained decoder aren't you using the full model? Unless you do not intend to have your new decoder to have skip connections?

**Comment by adaber** [comment]
Great. That's what I assumed about the skip connections but wasn't sure.

The pretrained model is just a neural net trained on a larger number of training samples of a product.

Once I get images of a new but similar product (lower number of images + the pretrained model's training images are not available), my idea is to apply Transfer Learning on the encoder (clone and freeze) and only clone the decoder preserving the weights and then train the created network using only the new product's training images.

So, I am not exactly just cloning the encoder and decoder (full model). I am cloning and freezing the encoder and only cloning the decoder. So, my approach has been creating a cloned and frozen encoder and a cloned decoder forming the encoder-decoder structure. There may be a better way, though.

It just occurred to me that I might need to replace the skip connection input layers in the cloned decoder with the skip connection output layers from the cloned and frozen encoder while cloning the decoder. Hope this makes sense :)

I hope you, at least, understand what I am trying to do here ( input -> cloned/frozen encoder -> cloned decoder -> output). Let me know what you think.

**Comment by delzac** [comment]
I think i understood what you are trying to do. You can using a full pre-trained UNET model, but you only want to train the decoder weights correct?

Then you should do just that. In your Trainer class, there is an argument where you state the paramters that are want to train. Just exclude all weights that belong to the encoder. This way, you don't need to clone any part of the network at all.

**Comment by adaber** [comment]
This, my friend, is EXACTLY what I was looking for :)

I completely missed that option. I haven't modified the line of code where I create my trainer in a long time and completely overlooked the parameter (a vector of CNTK::Parameter in C++) that's one of the Learner object's arguments where you tell the Learner what weights to train.

Awesome!!!

Elevir and delzac, thanks again for your time and input. I definitely learned some new things from your messages and suggestions.

I will close this thread/issue once I get a chance to test the proposed solution.
