### ISSUE TITLE
How to get 2.7 version of cntk-2.7.jar

### ISSUE THREAD

**Issue by anancds** [microsoft/CNTK#3679]
I want to use the 2.7 version of cntk-2.7.jar, but when I pull the package from the maven central library, I found that it is version 2.4.
![1](https://user-images.githubusercontent.com/4735508/59015473-a3a9b180-8871-11e9-9738-aec588233ed5.PNG)

**Comment by thiagocrepaldi** [comment]
Java binding support has been dropped :( 2.4 release is the last one available
