### ISSUE TITLE
GTC 2016:  Alexey on "Deep Learning in Microsoft with CNTK"

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#368]
Would be useful to share in the wiki Alexey's recent CNTK presentation at Nividia's GTC 2016 at the link below:

[S6843 - Deep Learning in Microsoft with CNTK](http://on-demand.gputechconf.com/gtc/2016/video/S6843.html)

Making the slides available via the wiki would be useful too.

Nicely done Alexey!

**Comment by Alexey-Kamenev** [comment]
Hi Mark,
Thank you! 
Sure, I will upload the slides, just need to find a good place in our Wiki to add a link...

**Comment by whitmark** [comment]
You're welcome.  Hopefully in time there will be more demos on Channel 9. :grin:

**Comment by alexeyo26** [comment]
[Done](https://github.com/Microsoft/CNTK/wiki/Presentations) Slides will be added later. Thank you!

**Comment by alexeyo26** [comment]
And now slides are also there
