### ISSUE TITLE
How to use 16 Bit inference in c++ ?

### ISSUE THREAD

**Issue by ZeroCool11000** [microsoft/CNTK#3693]
Simple question is there any flag to force CNTK to use 16 bit accuracy for inference ? 

Best regards

**Comment by YanYas** [comment]
You can `Cast` the variables to float16 and then cast the output back to float again but I'm not sure you will find much of a speedup. It might be easier to save you model to ONNX and convert it to 16bit using [WinMLTools](https://docs.microsoft.com/en-us/windows/ai/windows-ml/convert-model-winmltools#convert-to-floating-point-16)

**Comment by ebarsoumMS** [comment]
For inference, please use ONNX Runtime (https://github.com/microsoft/onnxruntime ). Float16 on the CPU is simply casted to Float32.

**Comment by ZeroCool11000** [comment]
Ok, thx and if i want to use half precision on the gpu ?

**Comment by ebarsoumMS** [comment]
fp16 on the GPU should work.
