### ISSUE TITLE
Windows binary CUDA problem

### ISSUE THREAD

**Issue by dionysio** [Microsoft/CNTK#37]
I wanted to try the library in CPU mode, I downloaded CNTK-20160126-Windows-64bit-ACML5.3.1-CUDA7.0 binary and set the appropriate environment variable ACML_FMA. When I run CNTK with 'Simple' example which should have CPU support, it crashes and produces error: "The program cant start because cublas_64_70.dll" and "...curand64_70.dll is missing from your computer". Those libraries seem to be CUDA-related...  Should I try to compile the library by myself or is there some other problem here?

**Comment by eldakms** [comment]
Hi dionysio,

We are actively working on the CPU only build. It will be available soon. Thank you!

**Comment by Timmmm** [comment]
For anyone Googling this, contrary to the binary installation instructions you *do* need the CUDA toolkit installed, specifically version 7.0. Download it here: https://developer.nvidia.com/cuda-toolkit-70
