### ISSUE TITLE
"acml.h" not found

### ISSUE THREAD

**Issue by Smilefounder** [Microsoft/CNTK#370]
Hi team,

I got an issue below when trying to compile from VS2013 with the latest source code.
Could you help to advice?

3>CPUSparseMatrix.cpp(33): fatal error C1083: Cannot open include file: 'acml.h': No such file or directory
3>CPUMatrix.cpp(44): fatal error C1083: Cannot open include file: 'acml.h': No such file or directory

![image](https://cloud.githubusercontent.com/assets/3785721/14601934/30930c9a-058f-11e6-84f3-036b7c32dfd9.png)

Regards,

**Comment by Smilefounder** [comment]
My apologize, found the solution from "ACML" in https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows.

**Comment by wangdelp** [comment]
@Smilefounder  Hi, I am encountering the same problem. How do you solve the problem? Thank you.

**Comment by mahilleb-msft** [comment]
@wangdelp please follow the installation procedure here (for ACML specifically and for Windows in general):
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#acml
