### ISSUE TITLE
"write" action fails with generic CUDA exception when miniBatchSize is not specified

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/CNTK#371]
I ran the "write" action on my trained image classifier, images read using the ZIP image reader. In my first attempt, I did not specify the `minibatchSize` parameter, and it gave me a non-actionable CUDA exception:

    cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=SAADSRNRDEV037 ; expr=err
    EXCEPTION occurred: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=SAADSRNRDEV037 ; expr=err
    [CALL STACK]
    > Microsoft::MSR::CNTK::MatrixBase::  operator=

After lots of head-scratching, I added `minibatchSize`, and all worked just fine.

Rather than throwing a CUDA exception, CNTK should tell me that I must specify a `minibatchSize`

**Comment by Alexey-Kamenev** [comment]
Hi Anton,
Good feedback, did you get this error on one of our samples? AFAIR if `minibatchSize` is not set then we will use the whole dataset.

**Comment by ant0nsc** [comment]
Alexey, I started with AlexNet and added a "write" action following the examples in section 6.1.9 of the CNTK book. There is no mention of `minibatchSize` there, unfortunately.

**Comment by ant0nsc** [comment]
@Alexey-Kamenev , @frankseide : I just re-tried with the latest and greatest CNTK. The bug no longer shows. No exception, and in the logs I now see that it using the default `minibatchSize` of 2048:

    Allocating matrices for forward and/or backward propagation.
    Minibatch[0]: ActualMBSize = 2048

The code that had the bug was still using CUDA 7.0, which seems to not have coped with the default of 2048.
