### ISSUE TITLE
request to share snippet on how to predict on single image post training and evaluating your model

### ISSUE THREAD

**Issue by navdeep1604** [microsoft/CNTK#3719]
I ahve trained and evaluated model as model being saved on .model file. I want to now run prediction on single images and store data in json or flat file for classes , object, bounding boxes , also image with bounding boxes. I dont find clear instruction or code with dependencies where i can run on single image and can put on flask . pls help

**Comment by delzac** [comment]
If you are able to train the model, why are you not able to predict on a single image? The code to setup training is more complicated than inference (i.e. prediction).

**Comment by navdeep1604** [comment]
because Prediction file or if you see evaluate , you would be able to see its being built for multiple images and it does evaluation. There is difference between evaluation and predict. We did evaluation but straightforward predict help i cant see where we have to load model and predict and return as images with boxes and save object classes and B boxes in either format. Pls guide

**Comment by navdeep1604** [comment]
this is for Faster Rcnn

**Comment by navdeep1604** [comment]
solved
