### ISSUE TITLE
Wrong error handling in "write" action

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/CNTK#373]
I played around with the `outputNodeNames` parameter in the "write" action. Node names refer to AlexNet.
- `outputNodeNames="OutputNodes.z"`: This works fine, and outputs 1 file.
- `outputNodeNames="OutputNodes.z;labels"`: throws an exception, saying "OutputNodeNames are not specified, using the default outputnodes. EXCEPTION occurred: There is no default output node specified in the network." - which is clearly misleading.
- `outputNodeNames="OutputNodes.z,labels"`: This works fine, and outputs 2 files.

Also, the documentation should be improved. For example, in Sec 3.5.5, it says that `outputnodeNames` is an array of node names - but what separator should I use? Only later in Sec 6, one of the examples shows that ":" should be the separator.

**Comment by frankseide** [comment]
: (colon) is the separator indeed. @alexeyo26, would you mind updating the docs to clarify?

Unfortunately, the configuration parser has known bugs w.r.t. parsing arrays that are hard to fix given its current design. Those will go away if we get around to redesigning it.
