### ISSUE TITLE
Is there any plans for support python?

### ISSUE THREAD

**Issue by shiyemin** [Microsoft/CNTK#374]
Python will be easier for people to do some research. C++ is not good enough.

**Comment by dongyu888** [comment]
Yes. This is being planned.

**Comment by shiyemin** [comment]
Will you please give me a link or branch name so that i can try it?

**Comment by dongyu888** [comment]
It’s being planned but nothing can be tested yet.

**Comment by shiyemin** [comment]
Fine...Thanks!
