### ISSUE TITLE
URL to WHL for CPU only CNTK 2.7 Python 3.6 returns 404 

### ISSUE THREAD

**Issue by colinvsyuan** [microsoft/CNTK#3745]
pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl
Collecting cntk==2.7.post1 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl
  ERROR: HTTP error 404 while getting https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl
  ERROR: Could not install requirement cntk==2.7.post1 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl because of error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl
ERROR: Could not install requirement cntk==2.7.post1 from https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl for URL https://cntk.ai/PythonWheel/CPU-Only/cntk-2.7.post1-cp36-cp36m-linux_x86_64.whl

**Comment by thiagocrepaldi** [comment]
Fixed. Please, retry again
