### ISSUE TITLE
error converting selective search proposals from matlab to CNTK text format 

### ISSUE THREAD

**Issue by jieunko** [microsoft/CNTK#3748]
I am trying to run fast rcnn exampe using pascal voc 2007
However converting matlab to CNTK format keep failing

**Comment by delzac** [comment]
Can you provide more details on what is happening? I think most readers wouldn't know what you are facing.

**Comment by jieunko** [comment]
I figured out the issue
It just couldn't find the .mat proposal in the path...
I changed relative path to absolute path
