### ISSUE TITLE
Compile without CuDNN

### ISSUE THREAD

**Issue by yzhang87** [Microsoft/CNTK#375]
Do we have to use cuDNN for CNTK? I think for some older version, it was not necessary. But now the makefile has:

ifdef CUDA_PATH
MATH_SRC +=\
    $(SOURCEDIR)/Math/GPUMatrix.cu \
    $(SOURCEDIR)/Math/GPUTensor.cu \
    $(SOURCEDIR)/Math/GPUSparseMatrix.cu \
    $(SOURCEDIR)/Math/GPUWatcher.cu \
    $(SOURCEDIR)/Math/MatrixQuantizerGPU.cu \
    **$(SOURCEDIR)/Math/CuDnnCommon.cu** \
    $(SOURCEDIR)/Math/CuDnnConvolutionEngine.cu \
    $(SOURCEDIR)/Math/CuDnnBatchNormalization.cu \
    $(SOURCEDIR)/Math/GPUDataTransferer.cpp \
else

Does it means we cannot disable cuDNN?

thanks

**Comment by alahiri-microsoft** [comment]
there's a ifdef CUDA_PATH at the top. if you don't specify that variable, it will build only CPU version and GPU files are not needed.

**Comment by yzhang87** [comment]
@alahiri-microsoft I mean can we build it with CUDA but without cuDNN? 

thanks,

**Comment by alahiri-microsoft** [comment]
I don't think so.

**Comment by Alexey-Kamenev** [comment]
Hello,
We made cuDNN a required component some time ago. cuDNN can be downloaded directly from NVIDIA website, no registration required (just follow the steps in our setup Wiki),

**Comment by whitmark** [comment]
Is cuDNN 5 RC supported yet?

**Comment by Alexey-Kamenev** [comment]
Not in the master, but I have it in one of my branches, let me know if you are interested. We will migrate to v5 only after its production release.

**Comment by yzhang87** [comment]
Hi @Alexey-Kamenev ,
I see.
BBN found that after they update CNTK from "Apr 11's builds 110e330e5b490c97d4836374ed83fbe642e4f857" to "Apr 20's builds",  they got an cublas error on Tesla K80. Is there any big change for the Math lib between this period?

minibatchiterator: epoch 0: frames [0..14739390] (first utterance at frame 0), data subset 0 of 1, with 1 datapasses
requiredata: determined feature kind as 40-dimensional
CUBLAS failure 14: CUBLAS_STATUS_INTERNAL_ERROR ; GPU=1 ; hostname=babg300.bbn.com ; expr=cublas_gemm(cuHandle, CUBLAS_OP_N, CUBLAS_OP_N, (int) ARows, 1, (int) ACols, &alpha, a.Data()+ offsets[0], (int) ALd, GetOnesVector<ElemType>(ACols, a.GetComputeDeviceId())->Data(), (int) ACols, &beta, Data()+ offsets[1], (int) ARows)



Thanks a lot!

**Comment by mahilleb-msft** [comment]
Closing, the original question was answered.
