### ISSUE TITLE
parallel LSTM with unique  sequences

### ISSUE THREAD

**Issue by Ivashar** [microsoft/CNTK#3757]
Hello, I’m trying to create two parallel LSTM networks connecting at the output through a multiplier. The sequences supplied to the input LSTMs have different lengths, so I create the input as
**features = InputVariable({ inputDim }, false, DataType::Float, L"features", {Axis::NewUniqueDynamicAxis(L"d")});**

В итоге получаю ошибку:
About to throw exception 'PastValue/FutureValue Function 'PastValue: Output('ElementTimes178_Output_0', [128], [d]) -> U
nknown': Input operand 'Output('ElementTimes178_Output_0', [128], [d])' with #dynamic axes != 2 (1 sequence axis and 1 b
atch axis) is not supported.'

std::pair<FunctionPtr, FunctionPtr> LSTMPComponentWithSelfStabilization(Variable input,
	const NDShape& outputShape,
	const NDShape& cellShape,
	const std::function<FunctionPtr(const Variable&)>& recurrenceHookH,
	const std::function<FunctionPtr(const Variable&)>& recurrenceHookC,
	const DeviceDescriptor& device)
{
	
	**auto dh = PlaceholderVariable(outputShape, input.DynamicAxes());** //### ERROR HERE

**problem in input.DynamicAxes ()**

need to build the following:
Seq1(length1) -> LSTM1 -> PoolAvarage1->
................................................................................................MUL(PoolAvarage1,PoolAvarage2) -> Output -> 
Seq2(length2) -> LSTM2 -> PoolAvarage2->

**Comment by haixpham** [comment]
Can you provide equivalent Python code, or a architecture diagram? It's difficult to figure things out from C++ code since I (and probably most people here) don't know the C++ API.

**Comment by Ivashar** [comment]
> Can you provide equivalent Python code, or a architecture diagram? It's difficult to figure things out from C++ code since I (and probably most people here) don't know the C++ API.

**haixpham**, need to do the following
![image](https://user-images.githubusercontent.com/46418550/66880013-4a624380-f004-11e9-9ded-43ea815c293e.png)

thank you in advance

**Comment by delzac** [comment]
Based on what i see here, you will need two different sequence input_variable. It should look something like this in python.

    seq1 = C.Axis.new_unique_dynamic_axis('seq1')
    seq2 = C.Axis.new_unique_dynamic_axis('seq2')
    seq_tensor1 = C.sequence.input_variable(shape=..., sequence_axis=seq1)
    seq_tensor2 = C.sequence.input_variable(shape=..., sequence_axis=seq2)
    reduce_ave1 = model(seq_tensor1)
    reduce_ave2 = model(seq_tensor2)
    output = C.times(reduce_ave1, reduce_ave2)

**Comment by Ivashar** [comment]
Thanks for the answer. This does not work if the length of the input sequences is different. Throws an error.

**Comment by haixpham** [comment]
where was the error thrown in your code?

**Comment by delzac** [comment]
When you say length of the sequence if different do you mean the number of `frames` (aka timesteps) in the sequence?

If so, does your reduce average function reduce over the sequence axis? My answer assumes that. If you reduce average doesn't reduce over the sequence axis, then of course an error would be raised, because you can't times sequences of unequal length.

**Comment by Ivashar** [comment]
About to throw exception 'PastValue/FutureValue Function 'PastValue: Output('ElementTimes177_Output_0', [128], [0]) -> U
nknown': Input operand 'Output('ElementTimes177_Output_0', [128], [0])' with #dynamic axes != 2 (1 sequence axis and 1 b
atch axis) is not supported.'

**Comment by haixpham** [comment]
I see it is thrown at ElementTimes op. So yes like delzac said you need to make sure both inputs have the same length.

**Comment by delzac** [comment]
@Ivashar does your reduce average op reduce over the sequence axis?

**Comment by Ivashar** [comment]
The error is actually different. Here it is: About to throw exception 'Different minibatch layouts detected (difference in sequence lengths or count or start flags)
in data specified for the Function's arguments 'Input (' features1 ', [128], [*, #])' vs. 'Input (' features0 ', [128], [*, #]
) ', though these arguments have the same dynamic axes' [*, #] ''

features0 and features1 are input variables that are created as
for (int k = 0; k <dim; ++ k)
{
{features.push_back (InputVariable ({inputDim}, false, DataType :: Float, L "features" + to_wstring (k)));
}

The lengths of the sequences are really different, but that's what they intended. Each sequence is averaged and then the data goes with the same length.

**Comment by delzac** [comment]
Have you checked to make sure that the number of samples in input1 and number of samples in input2 are the same? Number of samples meaning the minibatch size.

So you are confident that they have the same minibatch size and they do not have any seq axis after the reduce average op, you can call this function `C.reconcile_dynamic_axes` before the `times` op.

**Comment by Ivashar** [comment]
I am sure. It is the same for all sequences. The minipackage size is the same 100%, but the lengths of the sequences are different, but this should not be a hindrance, because they are averaged !!!

for (int k = 0; k < inputData.at(0).size(); ++k) 
		{
			argumentsOut = { { classifierOutputVar, outputValue },
							 { prediction, predictionErrorValue } };

			argumentsIn.clear();

			for (int i = 0; i </* features.size()*/2; ++i)
			{				
				argumentsIn.insert({ features.at(i), 
					       Value::Create(sampleShape, inputData.at(i).at(k), device) });
			}

			labelValue = Value::Create(labelsShape, labelsData.at(k), device);
			argumentsIn.insert({ labels, Value::Create(labelsShape, labelsData.at(k), device) });
		
			trainer->TrainMinibatch(argumentsIn, true, argumentsOut, device);						
			trainLossValue = trainer->PreviousMinibatchLossAverage();

**Comment by haixpham** [comment]
It's a bit confusing here. Can you clarify in minibatches of input1 and input2:
- How many sequences in each minibatch?
- For each pair of sequences in 2 minibatches, are they averaged to the same length?

Remember that CNTK maintains batch axis and sequence axis separately.

**Comment by Ivashar** [comment]
after LSTM, the sequences go through the allocation of the mean.

	FunctionPtr divs = Minus(classifierRoot, classifierRootR);
		divs = Square(divs);
		divs = Sequence::ReduceSum(divs);
		divs = ElementDivide(divs, len);
		divs = Sqrt(divs);

		classifierRoot = Splice({ classifierRootR , divs }, Axis(0));

![image](https://user-images.githubusercontent.com/46418550/66915218-d3f13000-f05b-11e9-9930-0b33a0d4af56.png)
![image](https://user-images.githubusercontent.com/46418550/66915230-dd7a9800-f05b-11e9-88da-7afcd81e21a4.png)
![image](https://user-images.githubusercontent.com/46418550/66915255-ea978700-f05b-11e9-91d4-51ba603e1457.png)

**Comment by delzac** [comment]
And which line of code was the exception raise?

**Comment by Ivashar** [comment]
classifierOut = ElementTimes(classifier.at(0), classifier.at(1));

classifier contains classifierRoot = Splice ({classifierRootR, divs}, Axis (0));
each for its own features

**Comment by Ivashar** [comment]
Derived via AsString (), what is fed to ElementTimes ()
☻►♠BZComposite(Plus): Input('features0', [128], [*, #]) -> Output('Plus365_Output_0', [2], [#])
☻►♠BZComposite(Plus): Input('features1', [128], [*, #]) -> Output('Plus728_Output_0', [2], [#])

**Comment by Ivashar** [comment]
I think this is due to the fact that by default in
features.push_back (InputVariable ({inputDim}, false, DataType :: Float, L "features" + to_wstring (k)));
contains Axis :: DefaultInputVariableDynamicAxes (), so the library expects identical lengths for LSTM if you change how
Axis ax = Axis :: NewUniqueDynamicAxis (to_wstring (k));
features.push_back (InputVariable ({inputDim}, false, DataType :: Float, L "features" + to_wstring (k), {ax})); I get an exception
About to throw exception 'PastValue/FutureValue Function 'PastValue: Output('ElementTimes177_Output_0', [128], [0]) -> U
nknown': Input operand 'Output('ElementTimes177_Output_0', [128], [0])' with #dynamic axes != 2 (1 sequence axis and 1 b
atch axis) is not supported.'

**Comment by delzac** [comment]
Looking at the exception that is thrown, it writes that "_#dynamic axes != 2 (1 sequence axis and 1 batch axis) is not supported."_.

After reduce average, the number of dynamic axes drops to 1. So it seems to makes sense that the exception is thrown? Can you choose a `ElementTimes` function that doesn't require dynamic axes to be equal to 2?

**Comment by Ivashar** [comment]
I am poorly versed in this, you can say the loser. An exception throws at this place

    inline FunctionPtr PastValue(const Variable& operand, size_t offset = 1, const std::wstring& name = L"")
    {
        static const auto defaultInitialState = Constant::Scalar(0.0f);
        return PastValue(operand, defaultInitialState, offset, name);
    }



I don’t understand how to defeat it

**Comment by delzac** [comment]
The reason why an exception is thrown at `About to throw exception 'PastValue/FutureValue Function 'PastValue: ` is because you need a dynamic sequence axis for op. But you have already reduced away the dynamic seq axis so you cannot use this op anymore.

So the question is, why are you passing a non-sequence tensor to an `op` that requires it to be a sequence tensor?

**Comment by Ivashar** [comment]
I myself solved the problem, it was necessary to create input, as
for (int k = 0; k < dim; ++k)
    {
        Axis ax = Axis::NewUniqueDynamicAxis(to_wstring(k));
        features.push_back(InputVariable({ inputDim }, false, DataType::Float, L"features" + to_wstring(k), 
            {ax, Axis::DefaultBatchAxis() }));
    }

thanks to all

**Comment by delzac** [comment]
I'm glad it worked out for you! Do close this issue once you have no other questions to raise :)
