### ISSUE TITLE
Access to network input after network downloading

### ISSUE THREAD

**Issue by yelandgit** [microsoft/CNTK#3766]
I use CNTK-2.7 with python 3.6.8 in Linux Mint
How can I get access to network input after downloading from file? Usually in examples this input has name feature. It's no problem, when I create network, but after downloading I cannot find this array inside network. I see only weights, and bias data

**Comment by akamotaco** [comment]
Usually, you can find the input variables in network.arguments.

```
import cntk as C
model = C.load_model('network_file_name.model')

print(model.arguments)
print(model.inputs)

network_input = model.arguments[0] # first input variable
print(network_input)
```

**Comment by yelandgit** [comment]
thank you for help
