### ISSUE TITLE
MNIST Example - "Undefined function 'Pooling'"

### ISSUE THREAD

**Issue by hwatmos** [Microsoft/CNTK#377]
While going through the CNTK tutorial, most things went well until I tried running the Image\MNIST example. Cntk throws the following error:
"EXCEPTION occurred: Undefined function or macro 'Pooling' in Pooling(inp, "max"..."

Thank you

**Comment by Alexey-Kamenev** [comment]
Hello,
Are you using the latest version from master? There were several major changes recently (ND convolution support etc).

**Comment by hwatmos** [comment]
@Alexey-Kamenev thank you for the comment. I'm using a version which I downloaded from the binaries download at [https://github.com/Microsoft/CNTK/releases](url). I can see that they are from Feb so my guess is that I will have to compile cntk based on the latest master myself; Since it's my first time compiling anything "serious", I'll attempt doing that this weekend and will loop back with the results. Thanks again

**Comment by Alexey-Kamenev** [comment]
Thank you. Let us know if you have any problems compiling the code. There are quite a few steps but they should be very well documented in our Wiki.

**Comment by hwatmos** [comment]
After all, I'll wait and I'll let the pros compile. There may be too much installing to be done for a novice like myself... I'll just skip to the next tutorial for now. Thanks for your help anyways @Alexey-Kamenev

**Comment by Alexey-Kamenev** [comment]
We've just released updated [binaries](https://github.com/Microsoft/CNTK/releases/tag/v1.1).Can you please try again?

**Comment by hwatmos** [comment]
Updated my version with the v1.1 binaries (WIndows GPU) and it works. Thank you very much!

**Comment by jeanfad** [comment]
I presume I can close this issue 

Thanks
