### ISSUE TITLE
Error when exporting model to ONNX: SquaredError: Unsupported node

### ISSUE THREAD

**Issue by mikhail-barg** [microsoft/CNTK#3791]
I'm trying to convert my old CNTK model to ONNX:

```python
import cntk as C
z = C.Function.load("model.800")
z.save("model.800.onnx", format=C.ModelFormat.ONNX)
```
which gives me
```
About to throw exception 'Node 'SquaredError: Input('age', [#, ], [1]), Output('result', [#, ], [1]) -> Output('err', [], [])': Unsupported node.'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Dev\Python3_x64\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
  File "C:\Dev\Python3_x64\lib\site-packages\cntk\ops\functions.py", line 1559, in save
    return super(Function, self).save(filename, format.value, use_external_files_to_store_parameters)
  File "C:\Dev\Python3_x64\lib\site-packages\cntk\cntk_py.py", line 2082, in save
    return _cntk_py.Function_save(self, *args)
RuntimeError: Node 'SquaredError: Input('age', [#, ], [1]), Output('result', [#, ], [1]) -> Output('err', [], [])': Unsupported node.

[CALL STACK]
    > CNTK::TrainingParameterSchedule<double>::  GetMinibatchSize
    - CNTK::  XavierInitializer (x5)
    - CNTK::Function::  Save
    - PyInit__cntk_py (x2)
    - PyEval_EvalFrameDefault
    - Py_CheckFunctionResult
    - PyObject_CallFunctionObjArgs
    - PyEval_EvalFrameDefault
    - Py_CheckFunctionResult
    - PyList_Size
    - PyEval_EvalFrameDefault
```

I'm running it under windows, python 3.6.5, cntk cntk-2.7.post1-cp36-cp36m-win_amd64.whl

Network config in brain script:
```
    BrainScriptNetworkBuilder = {
		imageShape  = 128:100:1
		features = Input(imageShape)	
		age = Input(1)
		model = Sequential(
			ConvolutionalLayer {64, (128:10), activation=ReLU, init='heUniform'} :
			StabilizerLayer{} :
			ConvolutionalLayer {64, (1:3), activation=ReLU, init='heUniform'} :
			StabilizerLayer{} :
			ConvolutionalLayer {64, (1:3), activation=ReLU, init='heUniform'} :
			StabilizerLayer{} :
            		AveragePoolingLayer {(1:87)}:
			DenseLayer {64, activation=ReLU, init='heUniform'}
	        )	
		out = model (features)
		result = DenseLayer {1, activation = ReLU, init = 'heUniform', initValueScale = 85} (out)
		err = SquareError(age, result)
		abs_err = Abs(age - result)
		
		# Special Nodes
		featureNodes    = (features)
		labelNodes      = (age)
		criterionNodes  = (err)
		evaluationNodes = (abs_err)
		outputNodes     = (result)
	}
```

Is there a way for me to use the model via ONNX?

**Comment by delzac** [comment]
Because the `squared_error` op is not exportable to onnx. Why do you have `squared_error` op in your model in the first place? `squared_error` is used as a loss function and shouldn't be used outside of training.

**Comment by JohnCraigPublic** [comment]
Mikhail-Barg -- I have the exact same issue.  I think BrainScript makes it easy/natural to end up with a model that contains this kind of node.   delzac is correct - we don't want this in the model file because one of its inputs in the 'ground truth' which you don't have except at training time.  Now, I wish someone would show me how, in my C++ implementation, to 'remove' that unwanted node and end up with a model that could be exported to ONNX -- because I am not clear on how to do that.

**Comment by mikhail-barg** [comment]
@delzac thanks for the answer. Now when you mention that I too agree that `squared_error` should not be a part of the model. But given that this is the model that I already have, I'd like to double the @JohnCraigPublic 's question — whant can I do about it now? This model has been trained a couple of years ago and I probably don't have all the data needed to re-train it from scratch. Is it possible to somehow "fix" the model to export it?

Btw, even though I do agree that `squared_error` should not be a part of the model, it is not clear to me how to express it in BrainScript. Please see my BS setup above. What should I change there to prevent `squared_error` being in the model? From what I see it is already not in the path to `outputNodes` (otherwise we would not be able to use it for inference in the first place).

**Comment by delzac** [comment]
Yes, you can remove the last layer (i.e. the squared error node/op).

You will need to find the uid of the actual last node that you want. In your case, it would be the second last node of your saved model.

'C.logging.find_all_with_name(model, '')' will give you a list of nodes with their uid. Find the 'last' node that you want.

Then do this, `new_model = C.combine([last_node_actual.owner])`. Complete sample code below.


```
import cntk as C

a = C.input_variable(10)
b = C.layers.Dense(20)(a)
c = C.layers.Dense(30)(b)

print(C.logging.find_all_with_name(c, ''))
print(C.logging.find_by_uid(c, 'Block31'))  # do not include "_Output_0"

last_node_actual = C.logging.find_by_uid(c, 'Block31')
new_model = C.combine([last_node_actual.owner])
print(new_model)
```

**Comment by JohnCraigPublic** [comment]
@mikhail-barg did you try what @delzac suggested?   I would like to do same, but I would like to do it in the C++ environment, not python -- but haven't attempted it quite yet.

**Comment by mikhail-barg** [comment]
Not yet ( I hope to find time to check it maybe this weekend or so.

**Comment by mikhail-barg** [comment]
I finally found time to do some experiments, and was able to export a model. Here's the code that worked for me:

```python
import cntk as C
z = C.Function.load("model.800")

print(C.logging.find_all_with_name(z, ''))
>>> [Combine: Output('abs_err', [#, ], [1]), Output('err', [], []), Output('result', [#, ], [1]) -> Output('abs_err', [#, ], [1]), Output('err', [], []), Output('result', [#, ], [1])]

result_node = C.logging.find_by_name(z, 'result')
new_model = C.combine([result_node])

print(C.logging.find_all_with_name(new_model, ''))
>>> [Combine: Output('result', [#, ], [1]) -> Output('result', [#, ], [1])]

new_model.save("model.800.onnx", format=C.ModelFormat.ONNX)
```
@JohnCraigPublic 

Still now I'm having the problem with loading model in ORT: 
```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException:
[ErrorCode:Fail] Node (out.x.x.x.x.x.x.x.c) Op (Conv) [ShapeInferenceError] Attribute dilations has incorrect size
```

This seem to be same as in this issue: #3671 as my input shape in Netron looks like this: `float32[Sequence,1,1,100,128]`

**Comment by mikhail-barg** [comment]
Anyway, that new problem seem to be unrelated to my original problem, so I'm closing this one.
@delzac thank you for your help!

**Comment by mattans** [comment]
> Yes, you can remove the last layer (i.e. the squared error node/op).
> 
> You will need to find the uid of the actual last node that you want. In your case, it would be the second last node of your saved model.
> 
> 'C.logging.find_all_with_name(model, '')' will give you a list of nodes with their uid. Find the 'last' node that you want.
> 
> Then do this, `new_model = C.combine([last_node_actual.owner])`. Complete sample code below.
> 
> ```
> import cntk as C
> 
> a = C.input_variable(10)
> b = C.layers.Dense(20)(a)
> c = C.layers.Dense(30)(b)
> 
> print(C.logging.find_all_with_name(c, ''))
> print(C.logging.find_by_uid(c, 'Block31'))  # do not include "_Output_0"
> 
> last_node_actual = C.logging.find_by_uid(c, 'Block31')
> new_model = C.combine([last_node_actual.owner])
> print(new_model)
> ```

Hi @delzac, this example really helps, but how can it be applied when one needs replacing an **intermediate** node with another node(s)?
I have in my model a NotEqual node names "NotEqual65492".
NotEqual nodes are not supported in ONNX conversion, and I want to convert my model, so I want to replace this node with 2 nodes: Not(Equal)

The value of the constant is 0:

```
node
NotEqual: Input('*****', [#], [***]) -> Output('NotEqual65492_Output_0', [#], [***])
node.constants[0].value
array(0., dtype=float32)
```

Thank you
