### ISSUE TITLE
How to shrink sequence length?

### ISSUE THREAD

**Issue by faruknane** [microsoft/CNTK#3793]
Hi, I want to shrink the sequence length of my input by 3. In each time step of RNN, I want to give three characters as input to my RNN. 

```
for t = 1, the input will be char[0], char[1], char[2]. 
for t = 2, the input will be char[3], char[4], char[5].
for t = 3, the input will be char[6], char[7], char[8]. 
```
it goes on like that.

Future value and past value help in this case but it doesn't solve the issue. Because the sequence length remains the same. If I use future + past value, it will look like this:

```
for t = 1, the input will be char[0], char[1], char[2]. 
for t = 2, the input will be char[1], char[2], char[3]. 
for t = 3, the input will be char[2], char[3], char[4]. 
```

I thought I can use the slice method with stride = 3. Because sequence length is a dynamic axis, it throws an error. 

my solution would be like this:
```
x = C.sequence.input_variable(vocabsize)
print(x.dynamic_axes[1])
x1 = C.slice(x, 1, 0, x.dynamic_axes[1], 3)
x2 = C.slice(x, 1, 1, x.dynamic_axes[1]+1, 3)
x3 = C.slice(x, 1, 2, x.dynamic_axes[1]+2, 3)

inputx = C.splice(x1,x2,x3)
```

How can I solve this problem? Can't we operate on a dynamic axis? 

@delzac maybe you know this as a master of cntk 😄

**Comment by faruknane** [comment]
Does cntkx.ops.sequence.stride work?
I'm currently reading your function.

**Comment by faruknane** [comment]
Solution:
```
x = C.sequence.input_variable(vocabsize)
px = C.sequence.past_value(x)
fx = C.sequence.future_value(x)

wx = C.splice(px, x, fx)

wx = cntkx.ops.sequence.stride(wx, 3)
```

**Comment by delzac** [comment]
Yup, `cntkx.ops.sequence.stride` is meant to do just that

**Comment by delzac** [comment]
If you don't care about casuality, then you can use `Cx.sequence.window` found [here](https://github.com/delzac/cntkx/blob/master/ops/sequence/__init__.py#L166)
