### ISSUE TITLE
Sequence regression training error in CNTKTextFormatReader

### ISSUE THREAD

**Issue by 1132520084** [Microsoft/CNTK#380]
when I trained a LSTM with a regression work using the CNTKTextFormatReader, the result was not reasonable .I thought there was  some error in the sequence reading in the CNTKTextFormatReader.So I do a test below .
The simple model is **`output = input + Delay(input,timeStep=1)`**,and I want to use to ways to fit it .
1. Using a SIMPLENET which contains two input,the second input is the PastValue of the current `input`. and set the `skipSequenceIds = false`.the result is very good.
2. the second way is using a rnn network which is defined in ndl below . And set `skipSequenceIds = true`,but output value is a same number like this:
        0.29
        0.29
        0.29 

```
    InputDim=1
    HiddenDim=10
    OutputDim=1

    features=Input(InputDim)
    labels=Input(OutputDim)

    features_old1=PastValue(InputDim,features,timeStep=1)

    B0=Parameter(HiddenDim,1)
    W0=Parameter(HiddenDim,InputDim)
    B0_1=Parameter(HiddenDim,1)
    W0_1=Parameter(HiddenDim,InputDim)      

    W1=Parameter(OutputDim,HiddenDim)
    B1=Parameter(OutputDim,1)

    Times1=Times(W0,features)
    Plus1=Plus(Times1,B0)
    Plus1_1=Plus(Plus(Times(W0_1,features_old1),B0_1),Plus1)
    H1=Sigmoid(Plus1_1)     

    Times2=Times(W1,H1)
    Plus2=Plus(Times2,B1)
    #H2=Sigmoid(Plus2)

    SE_me=SquareError(labels,Plus2)     

    FeatureNodes=(features)
    LabelNodes=(labels)
    CriterionNodes=(SE_me)
    EvalNodes=(SE_me)
    OutputNodes=(plus2)
```

does anyone meet the same situation ?

**Comment by raaaar** [comment]
Setting `skipSequenceIds` to true tells the reader to ignore sequences in the input and treat each line as an individual sequence. Also, take a look at #372
