### ISSUE TITLE
Bug?  Error when writing  node values in RNN.  

### ISSUE THREAD

**Issue by Leavingseason** [Microsoft/CNTK#381]
I want to output the hidden nodes' state in RNN from language model.  Firstly I am trying to output some from RNN. I have successfully trained a RNN language model. **But I got an error when outputing values :**  "
Validating --> cr = ClassBasedCrossEntropyWithSoftmax(labels[4 x *], HidAfterSig[200 x *], WHid2Word[200 x 3000], ClassProbBeforeSoftmax[50 x *]) -> [1]
Validating --> Out = TransposeTimes(WHid2Word[200 x 3000], HidAfterSig[200 x *]) -> [3000 x *]

5 out of 14 nodes do not share the minibatch layout with the input data.
Post-processing network complete.
OutputNodeNames are not specified, using the default outputnodes.
Allocating matrices for forward and/or backward propagation.
[CALL STACK]
    >00007FF600E9C4D3 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600EE98AB (SymFromAddr error : Attempt to access invalid address.)
    -00007FF601024B56 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF6010240CD (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600FD0A49 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600FCAAA7 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600F0BE31 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600ED3321 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600ED3768 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF600ED3812 (SymFromAddr error : Attempt to access invalid address.)
    -00007FF601071F63 (SymFromAddr error : Attempt to access invalid address.)
    -BaseThreadInitThunk
    -RtlUserThreadStart

**EXCEPTION occurred: ClassBasedCrossEntropyWithSoftmax (ForwardPropNonLooping()): Encountered a class of size 0. This sample seems to lack an NoInput flag.**
"

my output setting are:
Output = [
    action = "write"

```
minibatchSize = 1
traceLevel = 1
epochSize = 0
recurrentLayer = 1
defaultHiddenActivity = 0.1
rnnType = "CLASSLSTM"


#modelPath="$OutputDir$/Models/rnn.dnn"
#outputNodeNames="cr"
outputPath = "$OutputDir$/CLASSLSTM_Output.txt"     # dump the output as text


reader = [
    readerType = "LMSequenceReader"
    randomize = "none"

    # word class info
    wordclass = "$ModelDir$/vocab.txt"

    # if writerType is set, we will cache to a binary file
    # if the binary file exists, we will use it instead of parsing this file
    # writerType=BinaryReader

    # write definition
    wfile = "$OutputDir$/sequenceSentence.bin"

    # wsize - inital size of the file in MB
    # if calculated size would be bigger, that is used instead
    wsize = 256

    # wrecords - number of records we should allocate space for in the file
    # files cannot be expanded, so this should be large enough. If known modify this element in config before creating file
    wrecords = 1000

    # windowSize - number of records we should include in BinaryWriter window
    windowSize = "$confVocabSize$"

    file = "$DataDir$/$trainFile$"

    # additional features sections
    # for now store as expanded category data (including label in)
    features = [
        # sentence has no features, so need to set dimension to zero
        dim = 0
        # write definition
        sectionType = "data"
    ]

    # sequence break table, list indexes into sequence records, so we know when a sequence starts/stops
    sequence = [
        dim = 1
        wrecords = 2
        # write definition
        sectionType = "data"
    ]

    #labels sections
    labelIn = [
        dim = 1
        labelType = "Category"
        beginSequence = "</s>"
        endSequence = "</s>"

        # vocabulary size
        labelDim = "$confVocabSize$"
        labelMappingFile = "$OutputDir$/sentenceLabels.txt"

        # Write definition
        # sizeof(unsigned) which is the label index type
        elementSize = 4
        sectionType = "labels"
        mapping = [
            # redefine number of records for this section, since we don't need to save it for each data record
            wrecords = 11                
            # variable size so use an average string size
            elementSize = 10
            sectionType = "labelMapping"
        ]

        category = [
            dim = 11
            # elementSize = sizeof(ElemType) is default
            sectionType = "categoryLabels"
        ]
    ]

    # labels sections
    labels = [
        dim = 1
        labelType = "NextWord"
        beginSequence = "O"
        endSequence = "O"

        # vocabulary size
        labelDim = "$confVocabSize$"
        labelMappingFile = "$OutputDir$/sentenceLabels.out.txt"

        # Write definition 
        # sizeof(unsigned) which is the label index type
        elementSize = 4
        sectionType = "labels"
        mapping = [
            # redefine number of records for this section, since we don't need to save it for each data record
            wrecords = 3
            # variable size so use an average string size
            elementSize = 10
            sectionType = "labelMapping"
        ]

        category = [
            dim = 3
            # elementSize = sizeof(ElemType) is default
            sectionType = categoryLabels
        ]
    ]
] 
```

However, **if I change the "action = "write" to action = "eval"**, this setting becomes a test module and works fine. So I think the config is OK. Anyone could help me why the exception occurred when writting? What I need is to output the weights from a trained RNN.

**Comment by wolfma61** [comment]
This issue unfortunately has been dormant for a long while. Please open a new issue if you still experience problems in the latest release.
