### ISSUE TITLE
problem in CNTK installation for Python on Windows

### ISSUE THREAD

**Issue by ashish210111** [microsoft/CNTK#3818]
these are my anaconda and python version.
![image](https://user-images.githubusercontent.com/64783760/81444647-20858f80-9195-11ea-96dc-7ee68f325573.png)
I am taking help from here but not able to install it. Should I use the older versions of python and anaconda to install cntk?

thanks for your help

**Comment by thiagocrepaldi** [comment]
CNTK is not officially being updated to newer versions of conda, but you can certainly try to run it with newer versions. It should work with minimal changes, if any

**Comment by thiagocrepaldi** [comment]
I just noticed you are trying to install CNTK for python 3.6 on a Python 3.7 environment. The issue is not about newer anaconda version, by different python version (3.6 vs 3.7)

Currently CNTK is packaged for python 3.5 and 3.6, but you could try compile it for Python 3.7

**Comment by ashish210111** [comment]
> I
