### ISSUE TITLE
How to get Nightly NuGet package?

### ISSUE THREAD

**Issue by JohnCraigPublic** [microsoft/CNTK#3819]
On this page: https://cntk.ai/nightly-windows.html I see that there is something called 2.8-rc0.dev20200502 -- but how do I get it? 

I'm using VS 2017 and C++

I tried the usual NuGet GUI with "include pre-releases" checked, but these recent nightly packages are not offered.

I tried the NuGet Package Manager with a command like:

Install-Package CNTK.CPUOnly -Version 2.8-rc0.dev20200502

but that fails to find it.    Can somebody give me a quick hint?  Thanks!

**Comment by thiagocrepaldi** [comment]
Hello John, Nuget packages aren't avail;able through  https://cntk.ai/nightly-windows.html anymore. I believe you can still build from source

**Comment by JohnCraigPublic** [comment]
thiagocrepaldi - thanks for your comment.   One or two nightly releases ago, Liqunfu sent me a link where I could download a NuGet package for one of the updates.  That was fantastic -- anyway to have that happen again?  I've never built from source before, and not sure I want to enter that maze.

**Comment by thiagocrepaldi** [comment]
> 
> 
> thiagocrepaldi - thanks for your comment. One or two nightly releases ago, Liqunfu sent me a link where I could download a NuGet package for one of the updates. That was fantastic -- anyway to have that happen again? I've never built from source before, and not sure I want to enter that maze.

Sure, there you go: https://cntk.ai/Nuget/CNTK-Nuget-2.8.0-rc0.dev20200509.zip

How often do you think you will need this kind of drop? Are you a MSFT?

**Comment by JohnCraigPublic** [comment]
I'm not a MSFT.  Perhaps if there was a way to request it from time to time from you?

**Comment by thiagocrepaldi** [comment]
Reopen this as needed and if it gets too often, we can evaluate whether to publish nuget packages once again

**Comment by JohnCraigPublic** [comment]
I just installed nightly package ...0509 in hope that my bug might be fixed.  But no,  still cannot convert an Inception-V3 model from CNTK to ONNX!    Catch this exception:

Error: two nodes with same node name (model.model.pool_2_Output_reshape_to_model.model.pool_2_Output_reshaped_for_conv).
