### ISSUE TITLE
MNIST sample output question

### ISSUE THREAD

**Issue by dersturmbringer** [Microsoft/CNTK#382]
I modified MNIST dataset to output results, in 03_ConvBatchNorm.cntk I changed 
    action = test 
into
    action = write
and added the line
    outputPath = "$OutputDir$/SimpleOutput"    # Dump output as text
at the end of the test = [...] section

I ran cntk and looked into the output file
I was expecting a normalized vector with the highest component for the most likely label for an entry. Instead I see something like this:

-3.29747 1.18707 -0.160588 0.20746 -1.8349 -2.25021 -7.1347 13.3121 -0.655046 0.748616 
0.0882777 4.47525 14.6916 -3.32102 -2.92189 -6.34693 -1.83041 -1.25633 -1.82255 -1.59303 
-3.78701 13.1088 0.994873 -5.25564 1.42544 -1.62925 -3.48105 2.40588 -0.114733 -3.8653 
10.5531 -2.08045 -2.57146 -2.87377 -3.58436 -0.986828 4.89003 -1.15897 -1.97052 0.0216836 
-1.15064 -3.53868 -3.02565 -7.7542 13.3116 -2.85046 -0.930379 -2.76065 -1.25599 9.11912 
-3.34521 13.0117 0.271921 -5.9519 2.36428 -4.12309 -4.49585 4.52694 0.139658 -2.46128 
-6.13088 -0.867915 -2.74134 -5.95456 8.84731 -0.99581 -4.05852 -0.362241 5.28343 6.27024 
-2.76737 -2.27568 0.263278 -3.78987 4.49157 -2.54199 -4.3959 -4.49129 3.27915 12.2156 
-1.63494 -3.77904 -4.32272 -3.26087 -1.91931 9.71316 5.07126 -3.5309 0.709718 2.12436 
-6.23638 -5.18028 -7.98748 -1.67853 7.80996 -0.0350639 -8.66799 0.878808 2.23298 19.1488 
13.5646 -2.44583 -0.296114 -5.98182 -6.19346 -2.76387 0.105223 1.62283 -1.44049 3.06836 

I suppose I could take the highest value for each in order to get the most likely label (and comparing with the test dataset seems this is the case) but what could I do in order to get normalized values ?

**Comment by Alexey-Kamenev** [comment]
Hello,
Sorry for delay with response. What you got is the outputs of the `ol` layer which is defined as:
```
    ol = DNNLayer(h1Dim, labelDim, h1, 1)
```
where `DNNLayer` is defined as:
```
DNNLayer(inDim, outDim, x, parmScale) = [
    W = LearnableParameter(outDim, inDim, init="uniform", initValueScale=parmScale, initOnCPUOnly=true)
    b = LearnableParameter(outDim, 1,     init="uniform", initValueScale=parmScale, initOnCPUOnly=true)
    t = Times(W, x)
    z = Plus(t, b)
]
```
So you got values which are not normalized. If you are interested in probabilities, then you can add a `Softmax` node in .ndl file, for example:
```
    sm = Softmax(ol)
```
And then specify it in your `write` command:
```
...
    action = "write"
    outputNodeNames=sm
```
You should see something like this:
```
0.000061 0.000000 0.000095 0.000936 0.000001 0.000053 0.000000 0.998257 0.000009 0.000587
0.011187 0.000134 0.921179 0.016174 0.000000 0.020549 0.027735 0.000000 0.003042 0.000000
```
