### ISSUE TITLE
Install CNTK from source on Windows using script problem : Python 35 Environment exception

### ISSUE THREAD

**Issue by rajakamil4** [microsoft/CNTK#3821]
Try to install CNTK from source on Windows using script, all succeeded except Python 35 Environment exception with error from conda-windows-cntk-py35-environment.yml. Detail as below

PS C:\DeepLearning\cntk\Tools\devInstall\Windows> .\devInstall.ps1

This script will setup the CNTK Development Environment on your machine.
More help is given by calling get-help .\devInstall.ps1

The script will analyse your machine and will determine which components are required.
The required components will be downloaded into [c:\installCacheCntk]
Repeated operation of this script will reuse already downloaded components.

1 - I agree and want to continue
Q - Quit the installation process

1
Determining Operations to perform. This will take a moment...
Scan System for installed programs
Checking for Visual Studio 2017
Checking for NVidia Cuda 10.0
Checking for NVidia CUDNN 7.3.1 for CUDA 10.0 in c:\local\cudnn-10.0-v7.3.1
Checking for NVidia CUB 1.8.0 in c:\local\cub-1.8.0
Checking for CMake 3.6.2 in C:\Program Files\cmake\bin
Checking for installed MSMPI 70
Checking for installed MSMPI 70 SDK
Checking for Boost 1.60.0 in c:\local\boost_1_60_0-msvc-14.0
Checking for MKLML and MKL-DNN 0.12 CNTK Prebuild in c:\local\mklml-mkldnn-0.12
Checking for SWIG 3.0.10 in c:\local\swigwin-3.0.10
Checking for ProtoBuf 3.1.0 Source in c:\local\src\protobuf-3.1.0
Checking for ProtoBuf 3.1.0 VS17 CNTK Prebuild in c:\local\protobuf-3.1.0-vs17
Checking for zlib / libzip from source in c:\local\src
Checking for ZLib VS17 CNTK Prebuild in c:\local\zlib-vs17
Checking for OpenCV-3.1 in c:\local\Opencv3.1.0
Checking for Anaconda3-4.1.1 in c:\local\Anaconda3-4.1.1-Windows-x86_64
Checking for Python 35 Environment in c:\local\Anaconda3-4.1.1-Windows-x86_64
Checking pre-requisites finished

The following operations will be performed:
 * Creating Python 35 Environment

Do you want to continue? (y/n)
y
Performing download operations
Download operations finished

Performing install operations
Creating Python 35 Environment
Exception caught - function main / failure
System.Management.Automation.RuntimeException: Running [start-process  env create --file "C:\DeepLearning\cntk\scripts\install\windows\conda-windows-cntk-py35-environment.yml" --prefix c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35] failed with exit code [1]

**Comment by rajakamil4** [comment]
![image](https://user-images.githubusercontent.com/27916202/84738708-f9647e00-afdc-11ea-932d-0888a15cb098.png)

The folder is empty

**Comment by rajakamil4** [comment]
Still error eventhough i run it manually as below, please help

C:\local\Anaconda3-4.1.1-Windows-x86_64\Scripts>conda env update --file "C:\DeepLearning\cntk\Scripts\install\windows\conda-windows-cntk-py35-environment.yml" --name "C:\local\Anaconda3-4.3.1-Windows-x86_64\envs\cntk-py35"
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Package missing in current win-64 channels:
  - pyqt 5.6.0 py35ha878b3d_6

**Comment by rajakamil4** [comment]
Successfully install >conda install pyqt=5.6.0

Then successfully update conda env as below
>conda env update --file "C:\DeepLearning\cntk\Scripts\install\windows\conda-windows-cntk-py35-environment.yml" --name "C:\local\Anaconda3-4.3.1-Windows-x86_64\envs\cntk-py35"

**Comment by thiagocrepaldi** [comment]
That looks an intermittent issue. https://anaconda.org/main/pyqt/files does have https://anaconda.org/main/pyqt/5.6.0/download/win-64/pyqt-5.6.0-py35ha878b3d_6.tar.bz2 listed

**Comment by rajakamil4** [comment]
OK thanks
