### ISSUE TITLE
is there any method for depth wise convolution?

### ISSUE THREAD

**Issue by chan0240** [microsoft/CNTK#3823]
HI, I want to make an EfficientNet with CNTK and it is important to add DEPTH-WISE CONVOLUTION layer for computation cost.
But I don't have any idea for using depth-wise convolution.
So, I'm wondering that there is any method for depth-wise convolution.
Please help solving my difficulty.
Thanks you.

**Comment by delzac** [comment]
Just do it yourself? Its fairly trivial to build it.

**Comment by chan0240** [comment]
> Just do it yourself? Its fairly trivial to build it.

Of course. I'm struggling to figure it out.
Could you give me some examples?
I'm confused to set up filter map shape and convolution function parameter.

**Comment by delzac** [comment]
You need to use the `group` argument in the `Convolution2D`. There should be as many groups as there are num of filters.

**Comment by chan0240** [comment]
> You need to use the `group` argument in the `convolution`. There should be as many groups as there are num of filters.

I also expected so, but I was not sure.
I'll try to solve it more.
Thank you for your help!!

**Comment by chan0240** [comment]
> You need to use the `group` argument in the `convolution`. There should be as many groups as there are num of filters.

I have a last question. Is there any argument to change except for 'group' argument?

So confused...

**Comment by delzac** [comment]
> As far as I know, output channels must have same channels as input channels.
Yup, input channel and output channel should be the same.

**Comment by chan0240** [comment]
> > As far as I know, output channels must have same channels as input channels.
> 
> Yup, input channel and output channel should be the same.

If input channel and output channel and group are the same, an error occurs as below(Not exactly the same, but the meaning is similar)
(filter channel * group) must be same as input channel

**Comment by delzac** [comment]
You cannot use the Convolution Layer API. You must use the `convolution` op.

**Comment by chan0240** [comment]
> You cannot use the Convolution Layer API. You must use the `convolution` op.

What it op?
(I think op is naive function not wrapped in  wrapper function.)
And could you explain how I can use `convolution` op in C#?
It seems to be key point to solve this problem.

**Comment by delzac** [comment]
I don't use C#, so i can't help you with that. In Python, its a `convolution` function that we can call that is not under the layer API. You can view it [here](https://github.com/microsoft/CNTK/blob/master/bindings/python/cntk/ops/__init__.py#L357).
