### ISSUE TITLE
Language model: how does CNTK calculate the first word's probability?

### ISSUE THREAD

**Issue by Leavingseason** [Microsoft/CNTK#383]
I am using RNN to build a language model. Suppose I have a LM model already and want to evaluate this sentence:
</ s> we 're talking about years ago </ s> 
I know cntk will calculate each word's occurring probability , starting from the word "we" to the last token "</ s>" . 
Since "we" is the first word of the sentence, how do the RNN model predict its occurring probability?  I think the past hidden layer should set to all zeros, but how about the input X?
In my own implementation, I have tried use "</ s>" as the input, or simply set input to zeros, however the output probability do not match with what CNTK produces.

**Comment by Leavingseason** [comment]
After trying different combinations, I have solved it. The when meet a sequenceBegin symbol, the input is set to <unk>, and the past hidden layer is set to 0.1 (according to your NDL setting, like "defaultHiddenActivity = 0.1")

**Comment by wolfma61** [comment]
not sure why this was reopened ...
