### ISSUE TITLE
CNTK Python wheels are not available as Web App is down

### ISSUE THREAD

**Issue by delzac** [microsoft/CNTK#3838]
Hi,

I'm trying to download the wheel for cntk2.7 but its not available at all.
[https://cntk.ai/PythonWheel/GPU/cntk_gpu-2.7.post1-cp36-cp36m-win_amd64.whl](https://cntk.ai/PythonWheel/GPU/cntk_gpu-2.7.post1-cp36-cp36m-win_amd64.whl)

![image](https://user-images.githubusercontent.com/19370780/104294953-d2324880-54fa-11eb-9f58-37d5c52aef67.png)

@thiagocrepaldi Can fix be fixed? I'm still using cntk.

**Comment by kevin1020** [comment]
have you ever tried to install it with conda? it works for me. btw,  what happened to the web app ? I cant visit it either. Will it be restored?

**Comment by delzac** [comment]
In the end, i copy and paste the cntk folder and files from one envs into a new one.

If anyone has the original wheel, do post it here. I'll be happy to host it.

**Comment by prasanthpul** [comment]
you can get them from https://pypi.org/project/cntk/#files

**Comment by delzac** [comment]
Ahhh, okay got it! I always thought that the PyPI was not updated to the latest.

**Comment by ntw-au** [comment]
This is also affecting us downloading the CPU-only C++ binaries for Linux, which we also are still dependent on. In the event of the web app not being restored, is there a mirror for `CNTK-2-7-Linux-64bit-CPU-Only.tar.gz` available anywhere?
