### ISSUE TITLE
Unable to pull Python wheels from cntk.ai for cntk2.1

### ISSUE THREAD

**Issue by smahesh1** [microsoft/CNTK#3841]
My project has dependencies on CNTK 2.1 which we installed by using the following python wheels:

- https://cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp36-cp36m-win_amd64.whl
- https://cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp36-cp36m-linux_x86_64.whl

However, these seem to be inaccessible at the moment as [this issue](https://github.com/microsoft/CNTK/issues/3838) doesn't seem to be resolved. 

Unfortunately, upgrading to the versions hosted on PyPi break the project, so that's not a feasible solution. Is there any sort of update on whether the website hosting these files will be back up or some other location that hosts the cntk 2.1 wheels?

**Comment by thiagocrepaldi** [comment]
We are addressing this internally and we will update here as soon as we have a decision

**Comment by prasanthpul** [comment]
for right now, you should be able to access via https://www.cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp36-cp36m-win_amd64.whl and https://www.cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp36-cp36m-linux_x86_64.whl.
