### ISSUE TITLE
Usage of pre-trained Caffe models in CNTK?

### ISSUE THREAD

**Issue by aabramovrepo** [Microsoft/CNTK#389]
Hello everyone,

   just curious whether there is a possibility to load pre-trained Caffe models in CNTK?! Thanks!

Best,
Alexey

**Comment by Alexey-Kamenev** [comment]
Hello,
Not yet, but for most popular network architectures this should be doable. We've got a few similar requests and considering writing a tool which would perform a conversion Caffe <-> CNTK.

**Comment by aabramovrepo** [comment]
Thanks for the update! Do you have any idea when such a tool will be available?

**Comment by ngaloppo** [comment]
Ping. Any update on this issue?

**Comment by xdh168** [comment]
Caffe converter is being tested internally and we hope to get this tool ready soon. Thank you for your patience.

**Comment by mphielipp** [comment]
Are you converting Torch models as well?

**Comment by mphielipp** [comment]
Any target date for release of the caffe converter? A popular model I have seen is VGG-Face, have you tried with that model?

**Comment by jnirschl** [comment]
What is the progress on the internal testing of the CNTK <--> Caffe converter?

**Comment by barnandas** [comment]
Any progress on the Caffe to CNTK converter?

**Comment by cstrub** [comment]
Hi,
is there any release date scheduled for the caffe <--> cntk converter?
In my opinion it would be a great feature :)

**Comment by ujjwal-researcher** [comment]
Is there any specific reason for not releasing the converter ? A CNTK <--> Caffe converter will be a great contribution and I am sure many people are looking forward to it.

**Comment by wolfma61** [comment]
closing this one ....
