### ISSUE TITLE
List of input files

### ISSUE THREAD

**Issue by axonUH** [Microsoft/CNTK#392]
Hi,
I'm interested in training a CNTK model with a list of contiguous input files. For instance, if I run the Simple2D Example (https://github.com/Microsoft/CNTK/tree/master/Examples/Other/Simple2d), the input data is specified in the reader block as a single file. (file = "$DataDir$/SimpleDataTrain1.txt"). I have input data in, say 20, files to process, with sequentially numbered  filenames like SimpleDataTrain2, SimpleDataTrain3, ...SimpleDataTrain20.
Is it possible to specify more that 1 input data file to be processed? 

Thanks

**Comment by mahilleb-msft** [comment]
Hi,
  it's not possible in the reader block; but you could concatenate CTF input files in a pre-processing steps.
Please feel free to re-open the issue or open a new issue if this doesn't work for you.

  Best, Mark
