### ISSUE TITLE
In Convolution Network are non-square images and non-square kernels supported?

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#393]
CNTK is silently crashing without any messages (just windows message that app crashed), during first epoch when training on non-square images with non-square convolutional kernels.

So the question is are non-square images supported and are non-square kernels supported?

**Comment by Alexey-Kamenev** [comment]
Hello,
Non-square kernels should work just fine as well as non-square images. Are there any error messages in the log? What convolution engine is used? It should be reported in the log, search for text like `Using cuDNN convolution engine for geometry` though in your case it might be something other than `cuDNN`.

**Comment by RayFireh** [comment]
Thank you. Tried smaller model,  non-square kernels and non-square images do work. Both test were done on CPU only. Closed.
