### ISSUE TITLE
Malloc for CPUOnly in CUDAPageLockedMemAllocator

### ISSUE THREAD

**Issue by darlwen** [Microsoft/CNTK#398]
Hi,

If I choose CPUOnly mode and I use CUDAPageLockedMemAllocator to malloc memory for read data, it won't allocate memory and return nullptr which will make CPUOnly mode fail to run.

Thanks,

**Comment by wolfma61** [comment]
This issue unfortunately has been dormant for a long while. Please open a new issue if you still experience problems in the latest release.
