### ISSUE TITLE
License

### ISSUE THREAD

**Issue by frioux** [Microsoft/CNTK#40]
The license looks like it was written for CNTK, but I *think* that legally it's equivalent to either BSD or MIT.  It would be convenient for developers if you were to adopt one of those, or really almost any license that is well known, instead of writing your own.

Just a thought.

**Comment by alexeyo26** [comment]
Hello,

The license is crafted by our Legal Department. It is really MIT based, compare http://spdx.org/licenses/MIT However we encourage you to check things with your legal professionals to be sure.

Hope it qualifies it.

**Comment by frioux** [comment]
Given that it is *exactly* the same as the MIT License I think that putting "MIT License" above your license would be totally reasonable.

**Comment by frankseide** [comment]
A very reasonable suggestion! We will look into it.

Thanks

Frank

**Comment by frankseide** [comment]
Was somethignchanged?
