### ISSUE TITLE
how to get the useage imformation of some parameters?

### ISSUE THREAD

**Issue by FreedMana** [Microsoft/CNTK#401]
Hello, i'm confused that i don't know how to get specific difinitions of some parameters? 
I met them in Example configs ,but can not figure out how to set them. And both the CNTK wiki and guide book don't mention them. 
For example, 'parallelizationMethod' , 'useBufferedAsyncGradientAggregation' and some others.
Thanks!

**Comment by avader906** [comment]
@cha-zhang Where is the wiki blurb on on the performance impact and/or the use case for useBufferedAsyncGradientAggregation?

@FreedMana parallelizationMethod is explained here: [using CNTK with many GPUs and/or nodes (wiki page)](https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines)

**Comment by wolfma61** [comment]
https://docs.microsoft.com/en-us/cognitive-toolkit/Multiple-GPUs-and-machines
