### ISSUE TITLE
Using Argon with CNTK

### ISSUE THREAD

**Issue by rashee182** [Microsoft/CNTK#402]
There is a section about argon in the handbook but I did not find any relevant examples/scripts or associated binaries/source. So was wondering whether argon is a part of cntk itself or as mentioned in handbook the o/p of cntk (trained acoustic model) is fed to argon?

These are some of the doubts I have :
1.  How argon is integrated with CNTK i.e. need some practical examples of running Argon with CNTK i.e.  the kind of inputs given and outputs produced as result of argon execution.
2.  The handbook refers to some sample scripts. However, couldn’t find those in source depo.
3.  How language model is represented by a file (to be given to Argon as a command line parameter)
4.  Various other parameters required for argon execution eg : WFST compilation parameters, input/output parameters, search parameters
5.  The DecodingGraph.mak ﬁle to generate the Argon decoding graph.
6.  Associated  binary/source.

**Comment by rashee182** [comment]
I found the binaries for argon, but no instructions on usage :)

https://cntk.codeplex.com/downloads/get/1448857

**Comment by staplesinLA** [comment]
i'm confused too . have you got something instructional?
thanks.

**Comment by wolfma61** [comment]
The issue has been dormant for a long while. Please open a new issue if you still experience problems in the latest release.
