### ISSUE TITLE
Speech Example using AN4 database

### ISSUE THREAD

**Issue by rashee182** [Microsoft/CNTK#403]
Does anyone know how are the scp and mlf files generated from the AN4 database provided by CMU. Or for that matter, how can we generate these files for the reader using any generic speech data (raw or wav)

**Comment by eldakms** [comment]
If i'm not mistaken, you have to use HTK tool to do the conversion to htk/mlf/scp files. More information can be found here: http://speech.ee.ntu.edu.tw/homework/DSP_HW2-1/htkbook.pdf

Thanks!

**Comment by frankseide** [comment]
The HTK book tells you about the file format.

The feature files can be created with HTK's HCopy command. HCopy requires an SCP file of a slightly different format. The final SCP file for CNTK can be extracted from that.

For efficiency, you should concatenate all your features into an "archive". You use `HCopy A + B + C + D ARCH` for that, which will just concatenate all feature files, and then a small self-written program to update the SCP file for it.

The MLF file has to be created by an existing speech recognizer. You can train a GMM one with HTK. Then you must use `HVite` to do forced alignment and write out state-level alignments. You then need a tool to map the HTK output format, which lists the names of triphones and their state indices, to senone indices.

Quite an involved process, but unfortunately what it is.
