### ISSUE TITLE
MNIST sample - all output vectors are egual. CPU

### ISSUE THREAD

**Issue by lenkele** [Microsoft/CNTK#404]
I run MNIST sample with 02_Convolution.cntk in CPU.
Then I changed:
#action = test
action="write"

and add:
outputPath="SimpleOutput" # Dump output as text

And I'v got a simple output file where all lines are equal:

-0.336021 -0.553131 0.50853 0.295375 0.000531815 -0.857916 -0.319047 0.257945 0.713921 0.373607 
-0.336022 -0.55313 0.508529 0.295374 0.000531264 -0.857917 -0.319048 0.257946 0.71392 0.373606 
-0.336022 -0.553131 0.508528 0.295375 0.000532366 -0.857916 -0.319047 0.257946 0.71392 0.373606 
-0.336021 -0.553131 0.508531 0.295376 0.000531144 -0.857917 -0.319048 0.257945 0.713921 0.373607 
-0.336021 -0.553131 0.50853 0.295376 0.000531279 -0.857916 -0.319047 0.257945 0.713921 0.373607 

What's wrong??

**Comment by Alexey-Kamenev** [comment]
Responded in #405

**Comment by Alexey-Kamenev** [comment]
Feel free to re-open/create new issue if you still have questions.
