### ISSUE TITLE
Running Text/PennTreebank example with EvalWrapper

### ISSUE THREAD

**Issue by luisvw** [Microsoft/CNTK#407]
How can you run the PennTreebank example using the managed EvalWrapper? My main issues are:

1. How do you convert the text sequence into float/double for the Evaluate methods? The LMSequenceReader used in rnn.cntk can't be added as reference to managed code, so it can't be used to parse a string into the required input.

2. There is no OutputNodes in rnn.cntk as there is the MNIST examples. How do you specify the outputs that is required by EvalWrapper?

Thanks,
Luis

**Comment by virgill1974** [comment]
I´ve encountered the same problem.

**Comment by gaizkan** [comment]
Regarding item 2:
I am working on extending the EvalWrapper to expose the GetNodeDimensions method that will provide the input, output, and specified nodes.
For the case of PennTreeBank's rnn.dnn, the output is named, well, "outputs".
I should be going through the review process in the next few days. Once checked in the CSEvalClient should show how to use it.

Regards,
Gaizka

**Comment by gaizkan** [comment]
Hi luisvw,

A quick note to let you know that the GetNodeDimensions method is now available through the EvalWrapper. I updated some of the examples to show how to use it.

Best regards,
Gaizka

**Comment by gaizkan** [comment]
Regarding item 1:
You would have to perform the transformations that LMSequenceReader does on the text file before it feeds the matrix into the network. Those transformations are not available in the C# wrapper (you would have to implement them).
For example, someone implemented the transforms in F# corresponding to the ImageReader [http://stackoverflow.com/questions/37300946/how-to-use-rgb-image-as-input-for-the-c-sharp-evaldll-wrapper].

I hope this answers your question.
Regards,
Gaizka
