### ISSUE TITLE
Encoding issue when using Plot command

### ISSUE THREAD

**Issue by cartacarta** [Microsoft/CNTK#408]
On Windows bits, when calling action plot to write the .dot file, there are some encoding issues when writing the size of the tensors.  

Example:
  "ce" [ label = "ce [1?]\nCrossEntropyWithSoftmax" ] ;

When calling graphviz the labels on the nodes then look bad.

**Comment by yqwangustc** [comment]
Hi cartcarta, 

I think we should already fixed this problem in a recent commit: 

commit 800adf0a482720792b5b0654edf2b28c1e6a281e
Author: Yongqiang Wang <erw@microsoft.com>
Date:   Fri Apr 15 12:54:19 2016 -0700

    Fixing plot command output issue. Adding one test case for plot command.

Would you please kindly confirm that in your 
Source/ComputationNetworkLib/ComputationNetwork.cpp, you have the following line 

line = msra::strfun::wstrprintf(L" \"%ls\" [ label = \"%ls [%ls%ls]\\n%ls\" ] ;\n",
                                         x->GetName().c_str(), x->GetName().c_str(), **wstring**(x->GetSampleLayout()).c_str(), x->HasMBLayout() ? L" x *" : L"",

Thanks,
Yongqiang

**Comment by cartacarta** [comment]
Hi Yongqiang, yes the issue is now fixed in v1.1.  

Thanks!
Alejandro
cartacarta
