### ISSUE TITLE
Results on simple2D ?

### ISSUE THREAD

**Issue by ucacaxm** [Microsoft/CNTK#409]
Hi,

I'm new in CNTK, thank you for this tools which seems really great!
I have two different questions.

I have solved my 1st problem with a reboot.
I do not know why but the env variables MSMPI_INC/ACML_PATH/etc  were not available in Visual Studio even after close/reopen, a reboot did it.

2) With the pre compiled exe, I run the example2d demo: cntk configFile=../Config/Simple.cntk
and after 5seconds it finishes with an error of ErrorPrediction/Sample = 0.46766169   
Is that means 46% of error ?
I can not test the multigpu.cntk but there should be something I do not understand ?

Minibatch[1-1]: Samples Seen = 603    EvalErrorPrediction: ErrorPrediction/Sample = 0.46766169    CrossEntropyWithSoftmax: CrossEntropyWithSoftmax/Sample = 0.69473677    
Final Results: Minibatch[1-1]: Samples Seen = 603    EvalErrorPrediction: ErrorPrediction/Sample = 0.46766169    CrossEntropyWithSoftmax: CrossEntropyWithSoftmax/Sample = 0.69473677    Perplexity = 2.0031817 

Sorry for the really beginner questions ...
Best
Alex
PS: My first issue solved by a reboot

1) I'm testing CNTK on windows 10, Visual 2013 update 5, with an ATI card (so no CUDA :-(
I have followed the installation from here
https://cntk.codeplex.com/documentation

It does not compile with an error finding  "mpi.h" 
This file is in my computer here  C:\Program Files\Microsoft Compute Cluster Pack\Include

I have added the path in the include properties of the project and now it finds the file
but now I have an error with the function  "MPI_Allreduce" which is not define.
I think I have something wrong in my mpi install but 
In the windows program list, I have :
Microsoft MPI SDK v7.0.12437.6
Microsoft MPI v7 v7.0.12437.6
Microsoft HPC Pack 2012 Client Components
Microsoft Compute Cluster Pack SDK
?

After that I have also an error with the acml.h file which is not found.
I have set the ACML_PATH to the right path: C:\AMD\acml5.3.1\ifort64_mp
I can also add the path in the include dir in the proprieties of the project,
but I think this is not the right way to solve this problem 
?

**Comment by staplesinLA** [comment]
Hey,i'm a beginner too. In my view, yes it's the error prediction rate. But your result seems wired. In my condition, just one epoch can get it to 0.097 and 10 epoch is corresbonding to 0.04 .

**Comment by ucacaxm** [comment]
With the recompiled version of CNTK the results seems ok:

Final Results: Minibatch[1-1]: SamplesSeen = 603    EvalErrorPrediction: ErrorPrediction/Sample = 0.04145937    CrossEntropyWithSoftmax: CrossEntropyWithSoftmax/Sample = 0.096707187    Perplexity = 1.1015378 


I think also I have to remove output/model otherwise the results are wired ...
