### ISSUE TITLE
how to raise training speed?

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#410]
Hello, my question is which parameters can i adjust to get a quicker training speed in a specific working condition.

I trained a regression model based on 10 hours Speech Data (using 3 kinds of features for each utterence), it worked well and used 20 minutes per epoch.   Main related settings are:    minibatchSize=128 ; readMethod=blockRandomize;  randomize=Auto .

When i raised training data to 80 hours (features are the same with 10h) and change minibatchSize to 1280, there come  some questions:
First, in this case CNTK often be killed during the process of reading data before training. My machine has 64G RAM but should be shared with other mates. As it was mentioned by @frankseide that : the randomize can be set to 48 \* 3600 \* 100=17280000 (what's the meaning of 100?) ,  so I changed "Auto" to 17280000.
Next time, CNTK cracked again after 1 epoch while paging data in chunks before epoch 2.  And more surprisingly , it took 3 hours for training one epoch.  It unthinkable when used 10 hours data before.

All experiments are inplemented by single GPU(Tesla k40m). 
80hours GPU information:
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|==================================================|
|    0     82575    C   cntk                                           467MiB |

**Comment by staplesinLA** [comment]
I don't know if the consuming time is normal or not . And if it's not, how can i to adjust it ?
if needs other information, please tell me anytime.
Thanks a lot!

**Comment by staplesinLA** [comment]
I think it again and  the definite multiple relationship of cosuming time between 10hours and 80hours data (20minutes vs 3hours) seems fair. 
What's more important is how to improve it ,except for network complexity and computation complexity , cause i'm not sure the current setting is proper or not.  Otherwise multiple GPU is the last choice.

**Comment by yzhang87** [comment]
Hi,

If you are doing RNN, the training can be speed-up by parallel more utterances. It is a parameter in the reader config: nbruttsineachrecurrentiter=$num$.

**Comment by staplesinLA** [comment]
@yzhang87 thanks. Unfortunately, the network i used is a simple DNN with 3 hidden layers. And that's the reason i'm confused casue it's not complex at all. With the same network typology, 80hours data of 'single feature' just took 22 minutes.
 I tried to do some parallel experiments to find which element can affect final speed, but it would be very time-consuming. So i ask for help here.

**Comment by wolfma61** [comment]
The issue has been dormant for a long while. Please open a new issue if you still experience problems in the latest release.
