### ISSUE TITLE
Cuda Compute 2.1 compatibility may be broken with CNTK 1.1.

### ISSUE THREAD

**Issue by xenmind** [Microsoft/CNTK#411]
Hi,

I've been testing CNTK 1.1 and while it works with CPU, it has stopped working with my GPU (GTS 450). Basically,  it still builds a network, but it doesn't compute metrics like TrainLossPerSample and  SquareError/Sample, and outputs are NAN. I believe that you did upgrade CUDA; have you guys also upgraded cudDNN since CNTK 1?  Does CNTK still support Compute 2.1 GPUs? If not is there a simple way to fix this, or do I have to upgrade my GPU?

Any help would be appreciated!

**Comment by Alexey-Kamenev** [comment]
Hello,
CNTK now requires CUDA 7.5 and cuDNN v4. If you use convolutional nets with cuDNN then yes, you will have to use GPU of CC 3.0 or higher - this is the requirement of cuDNN. However, if you don't use convnets, then you should still be able to train nets on Fermi GPUs.

**Comment by xenmind** [comment]
Thanks for this. I'm using LSTM models, but I guess they also don't work for the same reason?

**Comment by mahilleb-msft** [comment]
Closing, there's now (for quite some time) a run-time check for CC 3.0 or higher in CNTK.
