### ISSUE TITLE
how to add weight noise?

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#414]
Hi,
In http://www.cs.toronto.edu/~fritz/absps/RNN13.pdf, one of the regularization methods used was adding some noise to the weights, from time to time. Can I do it in CNTK?

Cheers,
Slawek

**Comment by dongyu888** [comment]
Yes, set gaussianNoiseInjectStd to some nonzero value in SGD. This will randomly add a Gaussian noise to the gradient (and thus weight).

  <https://github.com/notifications/beacon/AL5PczgqFtgK1YloRhb2xVqO_7kN-M84ks5p8MeKgaJpZM4IR_WK.gif>

**Comment by slaweks17** [comment]
Hi,

Thank you. It seems to be working, i.e. making some difference [😊]

BTW, the documentation states that it works only for gradUpdateType=AdaGrad, but this is not right, correct?

I am not using AdaGrad.


Regards,

Slawek



________________________________
Od: Dong Yu <notifications@github.com>
Wysłane: 28 kwietnia 2016 17:11
Do: Microsoft/CNTK
DW: slaweks17; Author
Temat: Re: [Microsoft/CNTK] how to add weight noise? (#414)

Yes, set gaussianNoiseInjectStd to some nonzero value in SGD. This will randomly add a Gaussian noise to the gradient (and thus weight).

<https://github.com/notifications/beacon/AL5PczgqFtgK1YloRhb2xVqO_7kN-M84ks5p8MeKgaJpZM4IR_WK.gif>
