### ISSUE TITLE
segmentation fault in Linux

### ISSUE THREAD

**Issue by Leavingseason** [Microsoft/CNTK#415]
Hi team, I run successfully in Windows, but today I try to run the same config file in Linux, I got this error:
segmentation fault.

could you help me with this?

[rnnOutput_writeWordAndClassInfo_train_write.txt](https://github.com/Microsoft/CNTK/files/240844/rnnOutput_writeWordAndClassInfo_train_write.txt)

**Comment by uestcbingo** [comment]
I encounter this issue too, did you find a way to solve it?

**Comment by uestcbingo** [comment]
I encountered this issue too, did you find a way to solve it?

**Comment by wolfma61** [comment]
I'm not sure if this has been resolved, but it's been very old. Please try the latest 2.0 release and see if there are still issues. Feel free to open a new issue if needed. Thanks!
