### ISSUE TITLE
is scaleloglikelyhood a reasonable choice for classification?

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#416]
in one of the given examples, a node name of scaled log likelyhood  is defined. Can i use it instead of softmax to decide the predicted label. 
In fact, In one classification task where the number of diffrent classes is highly unbalanced, I found scaled log likelyhood acheives higher f1 score than the softmax.

**Comment by cha-zhang** [comment]
Has this issue been resolved? I'm closing it now because it's been over a year. Feel free to comment and we can reopen it. Thanks!
