### ISSUE TITLE
XOR function in CNTK

### ISSUE THREAD

**Issue by raBpywa** [Microsoft/CNTK#418]
inputs x1 x2
output u
x1	x2	u
0	0	0
0	1	1
1	0	1
1	1	0

how to do it ?
Can anyone help?

**Comment by frankseide** [comment]
Xor (a,b) = a + b - a .* b * Constant (2)

**Comment by frankseide** [comment]
translated into NDL, would be something like:
```
Xor (a,b) = Minus (Plus (a, b), ElementTimes (ElementTimes (a, b), Constant (2)))
```
