### ISSUE TITLE
Linux Instructions needs slight modification

### ISSUE THREAD

**Issue by likewei92** [Microsoft/CNTK#419]
Because the default g++ is now 5.3 in Ubuntu (16.04), cntk does not build as per the linux set up instructions. A simple `export OMPI_CXX=g++-4.8` fixes it, but it took me a while to figure out..

**Comment by likewei92** [comment]
Also I needed to add `-D_FORCE_INLINES` to `CUFLAGS` to make the GPU part build correctly. This is after setting both gcc and g++ to 4.8

**Comment by alexeyo26** [comment]
Hello!
We have recently published [the configurations we use for building and testing of CNTK](https://github.com/Microsoft/CNTK/wiki/Test-Configurations). We try to fix issues for other configurations as much as we can and gladly review related pull requests. However the configuration mentioned above is what we support fully.

As alternative we propose [to install CNTK using Docking Containers](https://github.com/Microsoft/CNTK/wiki/CNTK-Docker-Containers)  to eliminate all factors related to distribution/component version compatibility issues.

Thank you,
Alexey
