### ISSUE TITLE
Error Running Simple2d Example

### ISSUE THREAD

**Issue by tcpowers** [Microsoft/CNTK#42]
I am attempting to run the Simple2d example from the Wiki, but I get the following exception:

> EXCEPTION occurred: ConfigValue (uint64_t): invalid input string

CNTK is installed on machine running CentOS 6.6 and is one of the last versions from when the source code was on codeplex. I have attached the full output here: [run_simple2d.txt](https://github.com/Microsoft/CNTK/files/107569/run_simple2d.txt).

**Comment by wolfma61** [comment]
Hi -
we build test on 64bit versions of Ubuntu as well as Windows10/Server2012R2.

We do not test on CentOS.
