### ISSUE TITLE
Looking  for an example of  RNN for time series

### ISSUE THREAD

**Issue by DeepLearningFanatic** [Microsoft/CNTK#420]
I am looking for sample confingFile for a RNN for Time Series prediction, and one for classification... is there something available?

**Comment by madingo87** [comment]
Me too,
esepcially i'd like to know which kind of reader i need for reading my own build time-series dataset...

**Comment by manashty** [comment]
This is a working Sequence classification using RNN (with LSTM cells).
https://github.com/Microsoft/CNTK/tree/master/Examples/SequenceClassification/SimpleExample/Python
The tutorial is in here:
https://www.cntk.ai/pythondocs/sequence.html#sequence-classification

For time-series prediction, you can find examples in here:
https://notebooks.azure.com/CNTK/libraries/tutorials

**Comment by madingo87** [comment]
Thank you!
