### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mallidi** [Microsoft/CNTK#421]
Hi,

I am facing some error while building cntk. 
This is how I am running configure

~> ./configure --cuda=yes --with-cuda=/opt/NVIDIA/cuda-7.0 --with-gdk=/export/a07/harish/cntk/GDK/usr --with-cub=/export/a07/harish/cntk/CUB/cub-1.4.1 --1bitsgd=yes --with-cudnn=/export/a07/harish/cntk/cudnn-4.0/ --with-kaldi=/export/a07/harish/cntk/kaldi --with-acml=/export/a07/harish/cntk/ACML/acml5.3.1/ifort64 
Defaulting to --with-buildtype=release
Found OpenCV at /usr
Cannot locate libzip files
ImageReader will be built without zip container support.
Generating /export/a07/harish/cntk/CNTK/Config.make
run
>make -j all
to build

which seems to be running successfully 

when I run make, I get the following error

mpic++ -c Source/Readers/ReaderLib/SequencePacker.cpp -o .build/Source/Readers/ReaderLib/SequencePacker.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_ACML -DNDEBUG -DNO_SYNC -DQUANTIZED_GRADIENT_AGGREGATION  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -msse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/export/a07/harish/cntk/GDK/usr/include/nvidia/gdk -I/export/a07/harish/cntk/CUB/cub-1.4.1 -I/opt/NVIDIA/cuda-7.0/include -I/export/a07/harish/cntk/cudnn-4.0//cuda/include -I/export/a07/harish/cntk/ACML/acml5.3.1/ifort64/include -I/export/a07/harish/cntk/kaldi/src -I/export/a07/harish/cntk/kaldi/tools/ATLAS/include -I/export/a07/harish/cntk/kaldi/tools/openfst/include -I/usr/include -ISource/1BitSGD -MD -MP -MF .build/Source/Readers/ReaderLib/SequencePacker.d
Source/Readers/ReaderLib/SequencePacker.cpp: In member function ‘virtual Microsoft::MSR::CNTK::MBLayoutPtr Microsoft::MSR::CNTK::SequencePacker::PackSparseStream(const StreamBatch&, size_t)’:
Source/Readers/ReaderLib/SequencePacker.cpp:155:47: error: expected ‘)’ before ‘PRIu64’
         RuntimeError("Minibatch NNZ count (%" PRIu64 ") exceeds the maximum allowed "
                                               ^
make: *** [.build/Source/Readers/ReaderLib/SequencePacker.o] Error 1

Could you help solve this? Thanks in advance.

**Comment by raaaar** [comment]
Closed by 2627fc1. Please pull and try again.
