### ISSUE TITLE
Using a trained cnn in a c++ aplication

### ISSUE THREAD

**Issue by judav25** [Microsoft/CNTK#424]
Hello, I wanted to ask how to use a cnn that I trained in a c++ application. is this posible right now?
i am working in VS 2015.
thanks!

**Comment by gaizkan** [comment]
Hi judav25,

You can use the Eval.h interface file to access the evaluation engine in C++. I am working on a C++ sample showing how to do that. It should be in the repository in a couple of days.

Regards,

Gaizka

**Comment by DraTeots** [comment]
Even if you are working with unmanaged C++, you can create an interface through unmanaged exports:

https://www.nuget.org/packages/UnmanagedExports
https://sites.google.com/site/robertgiesecke/Home/uploads/unmanagedexports

That is some amount of work, but still doable.

**Comment by judav25** [comment]
hey thanks Gaizka, an example would be great, I don't seem to be able to find this Eval.h in my installation of cntk, but I do see it  in the repository, should i compile by my self cntk to get it, I used the precompiled binaries for my installation. 

Regards,
Judav

**Comment by gaizkan** [comment]
Hi judav25,

Just to let you know the C++ client example has been committed (look in the Source\Extensibility\CPPEvalClient folder)

I will close this issue.

Best regards,

Gaizka
