### ISSUE TITLE
Example/process for iterative deep training

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#425]
Hi all,
I'm interested to train a deep network for binary classification. My instances are (sparse) Boolean features from a very large feature space, and I've had some success training a simple network with up to four hidden layers using hashed input features.
I would like to experiment with training even deeper networks along the lines of Hinton's deep RBMs- training layer by layer.  It seems to me this is possible with some extra work and some network editing. For example - I can train a two layer auto-encoder, strip off the output layer, add a new one, and continue training.
The devil's in the details, though, and I wonder if I could get some guidance on how to best approach this. Are there any existing examples?
Thanks in advance.

**Comment by simra** [comment]
Quick follow-up: I found the speech examples described in the manual and to get up to speed I'm trying to configure the autoencoder example with a ucifastreader input.

Since the inputs and outputs should match I specified the reader as follows, but I get an odd error:
_EXCEPTION occurred: NotifyFunctionValuesMBSizeModified: featOut InputValue operation had its col dimension 25 changed by the reader to 1, but different from MBLayout._

The number 25 happens to match the minibatch size.

`reader = [

		readerType = "UCIFastReader"
		file = "$dataPath$Train.txt"
		miniBatchMode = "partial"		
		verbosity = 1
		randomize="none"
		
		featIn=[
			dim = $dimension$
			start = 0
		]
		featOut=[ 
			dim = $dimension$ 
			start=0 
			labelType=none
		]
	]
	`

**Comment by dongyu888** [comment]
You only need featIn for autoencoder.

**Comment by simra** [comment]
Thanks,
Just to be sure I understand: the network builder specifies this interface:
```
ndlCreateNetwork=[ 
	...
	featIn=Input(featInDim,tag="feature") 
	featOut=Input(featOutDim,tag="feature")
	...
	]
```
my understanding is that I have to define featIn and featOut in my reader.  If I remove featOut from the description above, I see the following output:
_Warning: labels are not specified.
...
EXCEPTION occurred: features and label files must be the same file, use separate readers to define single use files_

**Comment by dongyu888** [comment]
You should replace featOut with featIn and remove the featOut line. When you compute error you just compare it with featIn.

**Comment by simra** [comment]
Ok, I removed the line from the ndl and replaced featOut with featIn.  I'm not certain the topology is correct now, but in any case I still see the same exception.  Here's my reader, which I tried both with and without the labels=[] line.
```
reader = [

		readerType = "UCIFastReader"
		file = "$dataPath$Train.txt"
		miniBatchMode = "partial"		
		verbosity = 1
		randomize="none"
		
		featIn=[
			dim = $dimension$
			start = 0
		]
		labels=[labelType=none]
	]
```

Here's the full autoencoder ndl:
```
dimension=4096

load=ndlMacroDefine 
run=ndlCreateNetwork
ndlMacroDefine=[ 
	MeanVarNorm(x) { 
		xMean = Mean(x) 
		xStdDev = InvStdDev(x) 
		xNorm=PerDimMeanVarNormalization(x,xMean,xStdDev) 
	}
	MSEBFF(x,r,c,labels) { 
		BFF=BFF(x,r,c) 
		MSE=SquareError(labels,BFF) 
	}
] 
ndlCreateNetwork=[ 
	featInDim=$dimension$
	featOutDim=$dimension$ 
	hiddenDim=512 
	bottleneckDim=64 
	featIn=Input(featInDim,tag="feature") 
	#featOut=Input(featOutDim,tag="feature")
	
	featNormIn = MeanVarNorm(featIn) 
	#featNormOut = MeanVarNorm(featOut) 
	L1 = SBFF(featNormIn,hiddenDim,featInDim) 
	L2 = SBFF(L1,bottleneckDim,hiddenDim) 
	L3 = SBFF(L2,hiddenDim,bottleneckDim) 
	#MeanSqErr = MSEBFF(L3, featOutDim, hiddenDim, featNormOut, tag="criterion")
	MeanSqErr = MSEBFF(L3, featOutDim, hiddenDim, featNormIn, tag="criterion") 
	OutputNodes=(MeanSqErr.BFF.FF.P) 
	EvalNodes=(MeanSqErr)
]
```

**Comment by dongyu888** [comment]
Are you using the most recent build and have the old models deleted?

**Comment by simra** [comment]
I'm using the latest release build.  I'll try the latest examples from the repo.

**Comment by simra** [comment]
Quick follow-up: the latest repo examples are unchanged. I don't have a current build yet because I'm not set up with VS2013, so I'm stuck with the latest binary release.

This is the reader I'm trying to convert to UCIFastReader, using my own input samples.
```
reader=[
        # reader to use
        readerType=HTKMLFReader
        readMethod=blockRandomize

        miniBatchMode=Partial
        randomize=Auto
        verbosity=0

        featIn=[
            dim=792
            scpFile=$ScpDir$/TIMIT.train.scp.fbank.fullpath.rnn
        ]

        featOut=[
            scpFile=$ScpDir$/TIMIT.train.scp.fbank.fullpath.rnn
            dim=792
        ]
    ]
```

**Comment by simra** [comment]
Closing out this thread: I resolved the issue by switching to CNTKTextReader.  Thanks for your help!

**Comment by NexYY** [comment]
@simra 
Could you post your solution for the CNTKTextReader, with a small data example, cntk config and network, please?
