### ISSUE TITLE
Error in Trainlosspersample and EvalErrorPerSample

### ISSUE THREAD

**Issue by rodrigoalor** [Microsoft/CNTK#426]
Hello, 
I'm im training  a model using GPU  with the master branch and since the first minibatch   the    Trainlosspersample  and EvalErrorPerSample are equal to 0,  test with MNIST example and the result is the same. What could be the reason?.  when test  the result models  using CPU the  Trainlosspersample  are 0.69 and EvalErrorPerSample = 0.5

**Comment by mahilleb-msft** [comment]
I'm suspecting it might be an older (pre-Kepler) GPU. We only support Kepler-gen and above.
Please let us know the GPU model you're using.

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
