### ISSUE TITLE
Support OSX platform

### ISSUE THREAD

**Issue by tbfly** [Microsoft/CNTK#43]
Will CNTK support OSX platform compile and debug?
That will more portable.

**Comment by tbfly** [comment]
It seems  "acml"   CPU math library is the bottleneck. acml from AMD only provide with Win32/64 and Linux32/64 version.

**Comment by alexeyo26** [comment]
Hello!

For the time being we do NOT plan to support any platform apart from Windows and Linux.

**Comment by DelightRun** [comment]
@tbfly It's Microsoft, LOL.

**Comment by zhouwangzw** [comment]
The direct support for MacOS is something we want to do, and we are appreciated if you or the community are interested. Running CNTK in Docker on MacOS is available now though. see more information here: https://docs.docker.com/docker-for-mac/.
