### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by mehhey** [Microsoft/CNTK#431]
Hi everybody,
Is there anyway that I can see the flow of data through network for different nodes.
I mean in a multilayer network, I want to see the output of hidden layers for my 
input dataset, something like DeepVis for Caffe.

**Comment by wdarling** [comment]
Hi, if you set the tag for any node to "output" then the values for that node will be written out when you do a "write" call.

For example, if your input is x = [1, 2, 3] and then you do:
y = Times(x,x, tag='output')
then following a "write" you will have a file called "output.y" and it will contain [1, 4, 9] (in different formatting of course).

**Comment by yqwangustc** [comment]
You can try the plot command and the document is here 

https://github.com/Microsoft/CNTK/wiki/Plot-command
