### ISSUE TITLE
LSTMP model evaluation

### ISSUE THREAD

**Issue by Turan111** [Microsoft/CNTK#434]
Hi, 

I have evaluated model trained with LSTMP config in AN4 speech example.
Results were very bad:

`Final Results: Minibatch[1-3543]: Samples Seen = 354211    err: ErrorPrediction/Sample = 0.93009534    ce: CrossEntropyWithSoftmax/Sample = 26.906078    Perplexity = 4.8435227e+11`

But  in the training indicators was satisfactory:

`Finished Epoch[ 5 of 50]: [Training Set] TrainLossPerSample = 0.8876372; EvalErrPerSample = 0.27150306; AvgLearningRatePerSample = 0.00024999999; EpochTime=15408.5`

 I noticed that in the model  Rowslice's parameters were not mentioned:

```
Validating --> LSTMoutput1.G4 = RowSlice(LSTMoutput1.wxxpbpwhh[4096 x 1 x *]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.G3 = RowSlice(LSTMoutput1.wxxpbpwhh[4096 x 1 x *]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.Wcfdc = DiagTimes(LSTMoutput1.Wcf[1024], LSTMoutput1.dc[1024]) -> [1024]
Validating --> LSTMoutput1.unnamed152 = Plus(LSTMoutput1.G3[1024 x 1 x *], LSTMoutput1.Wcfdc[1024]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.ft = Sigmoid(LSTMoutput1.unnamed152[1024 x 1 x *]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.bft = ElementTimes(LSTMoutput1.ft[1024 x 1 x *], LSTMoutput1.dc[1024]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.G1 = RowSlice(LSTMoutput1.wxxpbpwhh[4096 x 1 x *]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.Wcidc = DiagTimes(LSTMoutput1.Wci[1024], LSTMoutput1.dc[1024]) -> [1024]
Validating --> LSTMoutput1.unnamed150 = Plus(LSTMoutput1.G1[1024 x 1 x *], LSTMoutput1.Wcidc[1024]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.it = Sigmoid(LSTMoutput1.unnamed150[1024 x 1 x *]) -> [1024 x 1 x *]
Validating --> LSTMoutput1.G2 = RowSlice(LSTMoutput1.wxxpbpwhh[4096 x 1 x *]) -> [1024 x 1 x *]
```

Could it be a problem?
And How to fix it?

**Comment by cha-zhang** [comment]
Has this issue been resolved? I'm closing it now because it's been over a year. Feel free to comment and we can reopen it. Thanks!
