### ISSUE TITLE
ARGON decoder

### ISSUE THREAD

**Issue by Turan111** [Microsoft/CNTK#435]
Hi,

It is written about Argon decoder in CNTK book. Where can I download it? I couldn't find any link.

**Comment by vmazalov** [comment]
It's an internal Microsoft project. I don't think it has been open-sourced.

**Comment by mikekennewick** [comment]
@vmazalov did anything change with this?  On another thread someone mentioned that it might be open sourced but I can't find anything on it.  I am interested in using the Argon decoder or whatever it might have become if possible.  I'm hoping to get a high performance decoder for real time large vocabulary speech recognition.
