### ISSUE TITLE
taking too long to compile

### ISSUE THREAD

**Issue by machomachopadre** [Microsoft/CNTK#436]
Hey everyone 💃 !!!  I had executed _make -j all_ after doing all the necessary steps. However after a while it hung up, output a few errors, wrote a whole lot on the disk for half an hour(i know because of the red flashy thing on my computer) and hung up again. I had to cold reboot it. It rebooted and i followed the SAME steps(i think i had done that earlier too..) as mentioned in the cntk install guide, double checked and tried it again.Hung up after the first few output lines. Is this because of processing power? I have an AMD FX 4800 (or something along those lines) which is 4 cores and 3.8ghz and a gtx 960. I believed this much was enough but..maybe not. PLEASE HELP                        tl;dr : I am having issues with compiling cntk (lot of hanging up) and i think it is because of lack of processing power

grammar police spare me D: D: D:

**Comment by machomachopadre** [comment]
I am a newbie to these forums so mod please tell me where to post this if it isnt right

**Comment by eldakms** [comment]
Hi,

Please see https://github.com/Microsoft/CNTK/issues/117
Try to use a less number of threads, i.e. make -j 2

**Comment by machomachopadre** [comment]
i thought -j2 means 2 threads and j means 1??

**Comment by machomachopadre** [comment]
i thought -j2 means 2 threads and -j means 1??

**Comment by eldakms** [comment]
Not sure what you mean :) In your question above you wrote you use **make -j all**  - this will cause compilation on **all ** available CPUs, sometimes this leads to problems. With **make -j 2** you are limiting compilation on two threads/CPUs, so you won't exhaust all your 4 cores. make -j 1 should also be fine.
