### ISSUE TITLE
ImageReader Section Missing in CNTK Book

### ISSUE THREAD

**Issue by LowerySJ** [Microsoft/CNTK#437]
Hello, documentation for the ImageReader data reader is missing in section 3.4 of the CNTK book -- I'm not trying to pester, just reminding in case it was forgotten.

Thanks and regards

**Comment by Alexey-Kamenev** [comment]
Right, we need to update the book, thank you. While we are gradually migrating from the book to Wiki, it's better to check both places for now (I know, it's not particularly convenient but we'll fix it soon).
