### ISSUE TITLE
DumpModel broken?

### ISSUE THREAD

**Issue by PatrickBue** [Microsoft/CNTK#438]
Hi,

I trained an MNIST model using the most current binaries + example scripts from "CNTK-1-1-Windows-64bit-CPU-Only". Training worked fine, and the accuracy of the model looks good also.
In an MEL script I can load the model, change the topology, and save it again. Just the "DumpModel" command does not seem to work anymore, e.g this produces an error.:
     DumpModel(model1, "$RootDir$/dump_originalModel.txt", includeData =true)

The error is:
     EXCEPTION occurred: Node 'conv1.b.b' (LearnableParameter operation): Sample [1 x 1 x 16] is not a column vector or matrix (1D or 2D tensor).

**Comment by pkranen** [comment]
If you need a quick workaround to be able to inspect your models you can add a try-catch in InputAndParamNodes.cpp at line 280 (DumpNodeInfo method): 

        try
        {
            sprintf(str, "[%lu,%lu]  ", GetAsMatrixNumRows(), GetAsMatrixNumCols());
        }
        catch (...)
        {
            sprintf(str, "[rows,cols,.. shape not supported]  ");
        }

**Comment by ant0nsc** [comment]
Fwiw, related problem(s) have been reported in #624

**Comment by mahilleb-msft** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue. Thanks!
