### ISSUE TITLE
Why is the training speed on multiple machine with multiple-GPUs lower than on single machine with multiple-GPUs ?

### ISSUE THREAD

**Issue by NewEricWang** [Microsoft/CNTK#440]
I ran two DNN parallel training experiments, one delivered on single machine with 2 k40 GPUs, another delivered on two machines where there are 3 k40 GPUs in total. I found the training on multiple machine is 2 times slower than on single machine. These GPUs is same type.  I guess the reason is the communication speed between two machine is limited by the network bandwidth of gigabit Ethernet. Must 10-gigabit Ethernet or InfiniBand be used if I want to speed up by multiple-machine parallel?

**Comment by Alexey-Kamenev** [comment]
What is your DNN architecture? And just to make sure, you do set parallelTrain to true, right?

**Comment by NewEricWang** [comment]
I use 7-layers 1028-nodes DNN. I am sure I set parallelTrain=true. 
I find that the training speed on multiple machines with multiple-GPUs is lower than on single machine with multiple-GPUs.

**Comment by alahiri-microsoft** [comment]
That depends on how you are utilizing the GPU and whether you’re saturating it’s core. Remember that RAM to GPU mem transfers are pretty slow. What is your minibatch size? What is the size of your dataset?

**Comment by staplesinLA** [comment]
Probably minibatch size is too small.

**Comment by Alexey-Kamenev** [comment]
As this is a DNN then communication cost will be pretty high. Try increasing minibatch size as suggested by others or use 1-bit SGD (please read its license first).

**Comment by NewEricWang** [comment]
Thanks a lot!
In my experiment the minibatch size is changed from 256 to 1024 along iteration. I also used 1-bit SGD. 
Now I used a 10-gigabit Ethernet between two machines. I got some speedup when I use multiple-machines compared to single-machine with multiple-GPUs.
