### ISSUE TITLE
CURAND failure 105 whne running on GPU

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#441]
Hi,
Sometimes I am getting this error when starting a training on GPU. When I switch to CPU things are fine. What is it? Overheated graphics card?

Microsoft::MSR::CNTK::GPUMatrix<ElemType>::SetGaussianRandomValue (GPU): creating curand object with seed 1462459807, sizeof(ElemType)==4
CURAND failure 105: (see curand.h & look for curandStatus or CURAND_STATUS_xxx) ; GPU=0 ; hostname=SLAWEKS ; expr=curandGenerateNormal(((curandGenerator_t*) s_curandGenerator)[0], reinterpret_cast<float*>(Data()), GetNumElements(), (float) mean, (float) sigma)

EXCEPTION occurred: CURAND failure 105: (see curand.h & look for curandStatus or CURAND_STATUS_xxx) ; GPU=0 ; hostname=SLAWEKS ; expr=curandGenerateNormal(((curandGenerator_t*) s_curandGenerator)[0], reinterpret_cast<float*>(Data()), GetNumElements(), (float) mean, (float) sigma)

Regards,
Slawek

**Comment by slaweks17** [comment]
Hi,
I just have found that the error appears only when the size of a hidden layer is odd. Maybe GPUs have dislike for odd numbers? :-)

Cheers,
Slawek

**Comment by Alexey-Kamenev** [comment]
You are not far from truth: according to documentation to CURAND function curandGenerateNormal, `CURAND_STATUS_LENGTH_NOT_MULTIPLE` error code (105) is returned when `if the number of output samples is not a multiple of the quasirandom dimension, or is not a multiple of two for
pseudorandom generators`. We should handle this better...
