### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by quicktrick** [Microsoft/CNTK#442]
Hello!  Please excuse my newbie question. I don't have any NVidia GPU in my system (Windows 10). When I try to install CUDA it says that my hardware isn't compatible. I choose "Custom" installation and then I have the following optional components to install:

1. CUDA Samples
2. CUDA Toolkit
3. CUDA Visual Studio Integration
4. GPU Deployment Kit
5. Graphics Driver
6. PhysX System Software

Which components do I need?  Is it enough to check 2nd and 3rd items?

**Comment by alexeyo26** [comment]
Hello! Actually you do not need ANY components. At least not for CNTK. CNTK is using CUDA compatible cards in GPU mode, so if you do not have any, then you need to use CNTK in CPU-only mode.

You can download the corresponding binary release, or build it from sources in CPU-only mode. In this case you don't have to install CUDA and cuDNN.

**Comment by quicktrick** [comment]
Thanks a lot, Alexey!  It would be nice to add your comment to the installation instructions here https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows
