### ISSUE TITLE
Simple Image:Image regression example crashing

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#444]
I'm trying to do a simple Image to Image regression using a single convolutional layer (just to start with) and I'm getting an exception:

NDLBuilder Using GPU 0
Microsoft::MSR::CNTK::GPUMatrix<ElemType>::SetGaussianRandomValue (GPU): creating curand object with seed 1, sizeof(ElemType)==4

[CALL STACK]
    >Microsoft::MSR::CNTK::operator<<<double>
    -Microsoft::MSR::CNTK::GPUSparseMatrix<double>::performElementWiseFunction
    -Microsoft::MSR::CNTK::Matrix<float>::SetGaussianRandomValue
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=

CURAND failure 105: (see curand.h & look for curandStatus or CURAND_STATUS_xxx) ; GPU=0 ; hostname=CSLTP060 ; expr=curandGenerateNormal(((curandGenerator_t_) s_curandGenerator)[0], reinterpret_cast<float_>(m_pArray), GetNumElements(), (float) mean, (float) sigma)
EXCEPTION occurred: CURAND failure 105: (see curand.h & look for curandStatus or CURAND_STATUS_xxx) ; GPU=0 ; hostname=CSLTP060 ; expr=curandGenerateNormal(((curandGenerator_t_) s_curandGenerator)[0], reinterpret_cast<float_>(m_pArray), GetNumElements(), (float) mean, (float) sigma)

The .ndl network is as follows (I'm trying to map the top half of the input to the bottom half):

load=ndlIIMacros
run=DNN

ndlIIMacros = [
    ImageW = 32
    ImageH = 64
    ImageC = 3
    LabelDim = 3

```
conv1WScale = 0.0043
conv1BValue = 0    

features = ImageInput(ImageW, ImageH, ImageC, tag = feature, imageLayout = "cudnn")

featOffs = Const(128)
featScaled = Minus(features, featOffs)    
```

]

DNN=[
    tophalf = RowSlice(0,32,featScaled)
    bottomhalf = RowSlice(32,32,featScaled)

```
# conv1
kW1 = 5
kH1 = 5
cMap1 = 3
hStride1 = 1
vStride1 = 1
# weight[cMap1, kW1 * kH1 * ImageC]
op = ConvReLULayer(tophalf, cMap1, 75, kW1, kH1, hStride1, vStride1, conv1WScale, conv1BValue)

CE = CrossEntropyWithSoftmax(bottomhalf, op, tag = Criteria)
Err = ErrorPrediction(bottomhalf, op, tag = Eval)
OutputNodes = op
```

]

(ConvReLULayer macro taken from the CFAR-10 example with no modification)

The configuration is:

RootDir = "."

ConfigDir = "$RootDir$"
DataDir = "$RootDir$"
OutputDir = "$RootDir$/Output"
ModelDir = "$OutputDir$/Models"

ndlMacros=$ConfigDir$/Macros.ndl

precision=float
deviceId=Auto
prefetch=true

command=Train:Test:Output

traceLevel=1
numMBsToShowResult=500

Train=[
    action=train
    modelPath=$ModelDir$/SimpleThreeLayerCNN

```
 NDLNetworkBuilder=[
    networkDescription=$ConfigDir$/II.ndl
]

SGD=[
    # EpochSize of 0 is all data ... otherwise uses a subset of data...
    epochSize=0
    minibatchSize=1
    learningRatesPerMB=0.003
    momentumPerMB=0.9*20:0.99
    maxEpochs=1
    L2RegWeight=0.03
    dropoutRate=0*5:0.5
]

reader=[
    readerType=ImageReader
    file=images.txt
    randomize=Auto
    features=[
        width=32
        height=64
        channels=3 # RGB
    ]
    labels=[
        labelDim=3
    ]
]    
```

]

Test=[
    action=test
    modelPath=$ModelDir$/II
    # Set minibatch size for testing.
    minibatchSize=1

```
 NDLNetworkBuilder=[
    networkDescription=$ConfigDir$/II.ndl
]

reader=[
    readerType=ImageReader
    file=images.txt
    randomize=None
    features=[
        width=32
        height=64
        channels=3
    ]
    labels=[
        labelDim=3
    ]
]    
```

]

Output=[
    action = "write"
    minibatchSize=1
    modelPath = $ModelDir$/II
    # Parameter values for the reader
    reader = [
        readerType = "ImageReader"
        file =images.txt
        randomize=None
        features=[
            width=32
            height=64
            channels=3
        ]
        labels=[
            labelDim=3
        ]
    ]

```
outputPath = "$OutputDir$/IIPredictedOutput"    # Dump output as text
```

]

(Again largely borrowed from the CFAR-10 example)

Any thoughts?

Thanks

D.

**Comment by dmagee** [comment]
GPU is GFORCE GT 740M in a laptop.

**Comment by Alexey-Kamenev** [comment]
It looks like you've got the same problem as in #441. One possible workaround could be initializing all parameters on CPU instead of GPU by using `initOnCPUOnly=true`

**Comment by dmagee** [comment]
Seems a similar issue yes and the number of unknowns (75) is indeed odd. Where do I put initOnCPUOnly=true? I tried the command line, and various locations in the .cntk file but got the same result. This (among many other things) isn't documented in the cntk book. Thanks!

**Comment by Alexey-Kamenev** [comment]
Sorry for not being clear: this should a parameter in LearnableParameter node:
```
W = LearnableParameter(outDim, inDim, init="uniform", initValueScale=parmScale, initOnCPUOnly=true) 
```
