### ISSUE TITLE
Logistics/Sample error

### ISSUE THREAD

**Issue by Abe533** [Microsoft/CNTK#445]
I have started using CNTK and ran the first regression sample given in the tutorial.
Used April release.
Used the same config. file per tutorial.

The calculated model matched exactly with tutorial results.

However, test results were different with:
EP: SquareError/Sample = 0.011580509 
LR: Logistic/Sample = 42.218785
The input test file matches the one from the tutorial. 
starting with :
3.854499 4.163941 1
1.058121 1.204858 0
.....
Does anyone know what may have caused it?

**Comment by jeanfad** [comment]
We are investigating. I tried the 3-class problem and this one has the same results as reported, please refer to it meanwhile. thanks ! 

Jean

**Comment by wolfma61** [comment]
The issue has been dormant for a long while. Please open a new issue if you still experience problems in the latest release.
