### ISSUE TITLE
how to utilize Kaldi in Cntk?

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#446]
Is that possible to combine kaldi and cntk together to construct a complete ASR system? Like, kaldi as a feature extrator and decoder, cntk as a DNN trainer in the middle.
There is a kaldi2Reader, where to find the efficient usage of it?
Thanks a lot!

**Comment by yzhang87** [comment]
Hi,

You can use kaldi as feature extractor and decoder.
There is a example in the repository:
Examples/Speech/Miscellaneous/AMI/train_cntk2.sh

You can also send me email if you find any problem.

**Comment by staplesinLA** [comment]
@yzhang87 thank you very much. I'm not very famaliar with Kaldi and the AMI corpus is so space-cosuming that can't easily implement. I will try to understand the scripts and try to transplant and test the method for my task.
thanks!

**Comment by yzhang87** [comment]
@staplesinLA ok. I'm not checking this issue page everyday. So if you have any problem plz make sure @my name.

**Comment by staplesinLA** [comment]
Thank you Yu! I modified train_cntk2.sh ,and it worked! 
And then I proceed to train_cntk2_smbr.sh .  But i can't find  "scripts/train_sequence.sh" ,where to find it?
谢谢！

**Comment by JJMEI** [comment]
hello guys ,@staplesinLA can you send me your script  ? mmeijunjie@gmail.com

**Comment by JJMEI** [comment]
hello, @yzhang87  Recently，i'm tring the example AMI , But there are some questions. I don't find the CNTK2.cntk . Then i change the file, but has errors 

CNTK 2.0.beta5.0 (HEAD bf2ce5, Nov 25 2016 15:43:27) on localhost at 2017/01/11 20:13:46

/home/m/cntk/cntk/bin/cntk  configFile=/home/m/kaldi/egs/timit/s5/exp_cntk/Base.config  configFile=/home/m/kaldi/egs/timit/s5/exp_cntk/CNTK2_ndl_deprecated.cntk  DeviceNumber=0  action=TrainDNN  ndlfile=/home/m/kaldi/egs/timit/s5/exp_cntk/dnn_6layer.ndl


[CALL STACK]
[0x77b8f4]                                                            
[0x7cdcc7]          void  DoCommands  <float>(Microsoft::MSR::CNTK::ConfigParameters const&,  std::shared_ptr<Microsoft::MSR::CNTK::MPIWrapper> const&) + 0xf7
[0x77c125]          wmainOldCNTKConfig  (int,  wchar_t**)              + 0x6f5
[0x77e77f]          wmain1  (int,  wchar_t**)                          + 0x7f
[0x75a428]          main                                               + 0xd8
[0x7f7afddccaf5]    __libc_start_main                                  + 0xf5
[0x7656ae]                                                            
EXCEPTION occurred: DisableLegacyUsage: setting Truncated only in reader section are not allowed. Please move Truncated=true/false to the top level section.

do you give me some suggestions?

**Comment by cha-zhang** [comment]
Has this issue been resolved? I'm closing it now because it's been 6 months. Feel free to comment and we can reopen it. Thanks!
