### ISSUE TITLE
How to save checkpoints after e.g every next 50th epoch?

### ISSUE THREAD

**Issue by pwodzu** [Microsoft/CNTK#449]
Hello! First, I would like to thank the whole team for developing the CNTK framework. 

I have the question about the periods of saving the checkpoints during the training process. Is there a possibility to save checkpoint models e.g after every next 50th epoch?

The problem is when large structures can be stored on few gigabytes, and saving models after every epoch takes much space of hard disk. 

Thanks a lot !

Regards,
Piotr

**Comment by dongyu888** [comment]
Just increase the epoch size. It saves for each epoch.
