### ISSUE TITLE
MPI error 782 with DataParallelSGD on LMSequenceReader

### ISSUE THREAD

**Issue by alahiri-quora** [Microsoft/CNTK#450]
Hi all,
Currently I’m getting an MPI error 782 with DataParallelSGD for LMSequenceReader on my branch alahiri/distrib-reading-LMSequenceReader. Something like:

LMSequenceReader: Reading epoch data... 3370 sequences read.
MPI_Waitany, MPI error 782
MPI_Waitany, MPI error 782: Message truncated, error stack:
Message from rank 3 and tag 1 truncated; 1020000 bytes received but buffer size is 48

Any ideas on how to fix this?

Thanks!

**Comment by mahilleb-msft** [comment]
Sorry for the late response. LMSequenceReader is not maintained and it's possible that it doesn't handle distribution correctly. We'd recommend switching to [CNTKTextFormatReader](https://docs.microsoft.com/cognitive-toolkit/brainscript-cntktextformat-reader).

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
