### ISSUE TITLE
Problem when run the "write" action in Examples\Speech\Miscellaneous\TIMIT\

### ISSUE THREAD

**Issue by NWPUYan** [Microsoft/CNTK#455]
I have prepared the data and train the dnn model with the configFile cntk\Examples\Speech\Miscellaneous\TIMIT\AdditionalFiles\TrainSimpleTimit.cntk
but ,after doing the "write" action I can't get the correct output files . The files seem have Error character encoding,just like the following line
   啝? @?6@紻侤?,@肍V@?{@絽]@竬睝?I@箓-@?2@硦@?@宁@贺 @赖^@坯鸃?Y@練

the action config is here

TimitWriteSimple=[
    action=write
    modelPath=Models/TrainSimple.dnn
    # deviceId=-1 for CPU, >=0 for GPU devices 
    deviceId=$DeviceNumber$
    outputNodeNames=ScaledLogLikelihood
    traceLevel=1
    # Parameter values for the reader
    reader=[
      # reader to use
      readerType=HTKMLFReader

```
  features=[
  dim=792
  scpFile=CntkTimit.scp
  ]

]
#outputPath = F:\cntk\Examples\Speech\Miscellaneous\TIMIT\AdditionalFiles\Output\A.txt
writer=[
  wrecords=50000 #Number of records to allocate space for in file
  writerType=HTKMLFWriter
  ScaledLogLikelihood = [
      dim = 183
  scpFile=CntkTimitOutput.scp
      # type=Real           # Must be uppercase Real?
]
]
```

]

but IF I specify the outputPath instead of writer[]，we can get the right output file.

WHY?

**Comment by dongyu888** [comment]
The writer you use is a binary writer. Information inside the file is in binary format.

**Comment by NWPUYan** [comment]
Thanks,but how can I get the output file in normal text format ?

**Comment by cha-zhang** [comment]
Since this issue is very old, I'm closing it. We recommend you to use the new Python API to train and test models, and there you will have all the flexibility to write output files.
