### ISSUE TITLE
Evaluation Client in python

### ISSUE THREAD

**Issue by simsim314** [Microsoft/CNTK#458]
I'm not sure if this is an issue/request/question. 

I would like to use the Evaluation Client (CNTK/Source/Extensibility/CPPEvalClient/CPPEvalClient.cpp) which works very nice in c++ but in python. 

I was looking the repository and it has some python code here (CNTK/contrib/Python/cntk/examples/MNIST/mnist_one_layer.py) but it looks like training not Evaluating. 

So maybe there is alredy python code for the evaluation client? If there isn't maybe someone can add it to the Extensibility directory?

**Comment by mahilleb-msft** [comment]
For CNTK 2.0, there's a Python API. Please check out https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Evaluate-models-in-Python and related pages... Thanks!
