### ISSUE TITLE
SGDLib: Cannot open include file: 'AllReduceDistGradAggregator.h'

### ISSUE THREAD

**Issue by Henry-White** [Microsoft/CNTK#460]
Latest master downloaded. MS VS 2013.
CNTK_ENABLE_1BitSGD=true

6>------ Rebuild All started: Project: SGDLib, Configuration: Release x64 ------
6>  Profiler.cpp
6>  SGD.cpp
1>  GPUSparseMatrix.cu

SGD.cpp(14): fatal error C1083: Cannot open include file: 'AllReduceDistGradAggregator.h': No such file or directory

**Comment by mahilleb-msft** [comment]
@Henry-White: when compiling with 1Bit-SGD support, you need to clone with --recursive (or invoke "git submodule update --init --recursive" to make up for that). See here:
https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD
Can you double-check?

Thanks, Mark

**Comment by Henry-White** [comment]
Done. The command "git submodule update --init --recursive" was unsuccessfully finished but I didn't noticed that. Sorry. Fixed. SGDLib compiled successfully.
Get some fatal errors inside other modules but this is another story...
And thanks any way for giving me right direction :)

**Comment by Henry-White** [comment]
It's seems to be an issue again... Downloaded latest master. After commit I've got the same issue as before. "git submodule update --init --recursive" does not help.
SGD.cpp
```
#include` "AllReduceDistGradAggregator.h"
#include `"BlockMomentumSGD.h"

```
These files are not found. Catalog 1BitSGD has been removed from master.

**Comment by Henry-White** [comment]
Resolved. For a some reason VS-git client has removed 1BitSGD directory and did not synced it with master. Remove and reload was helped.

**Comment by Chunde** [comment]
Hello, I just clone the CNKT, and I have same problem, @Henry-White but I did not see 1BitSGD  source code inside the Respo.

**Comment by Chunde** [comment]
I have the same problem,  and I did not found 1BitSGD  inside the Repos. Seems it has been removed.
