### ISSUE TITLE
About "BS" in example code ...

### ISSUE THREAD

**Issue by helson73** [Microsoft/CNTK#461]
Hi, I am a newbie who just started to use CNTK.
Recently I found some script code looks like "BS.*" in example scripts.
So far I cannot find any information about it in the document named "An Introduction to CNTK".
From its "dot" syntax and the namespace "BS" used in some parts of sourcecode, what I can only guess is : 
1) This thing maybe somewhat Macro defined outside.
2) Maybe it's initial for "BrainScript". 
I am wondering ... anyone knows about it?
Thanks.

**Comment by frankseide** [comment]
Yes, BS stands for BrainScript (what else!). BrainScript is an extension to the current NDL. It is close to being finished, mostly lacking documentation. Stay tuned.
