### ISSUE TITLE
Compilation error on master

### ISSUE THREAD

**Issue by anshumang** [Microsoft/CNTK#464]
Source/Readers/CNTKTextFormatReader/TextConfigHelper.cpp:79:52: error: expected ')' before 'PRIu64'
                 RuntimeError("Sample dimension (%" PRIu64 ") for sparse input '%ls'"

on 1a7ecaecfac93e3b992fa410562871f8a117878e

**Comment by raaaar** [comment]
need to add a missing `#define __STDC_FORMAT_MACROS` before `#include <inttypes.h>`
