### ISSUE TITLE
Evaluating a model gives different results when using different builds

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/CNTK#465]
I have an image classification model, trained using the CNTK binaries from around 2 weeks ago (April 28). Now using the model in my .NET application via the `EvalWrapper`. Just for basic testing, I fed the model with feature values that are constant 255 or constant 0.

- When using the CNTK binaries from April 28, I get two different outputs - as I would expect.
- When using the CNTK binaries straight from master (as of May 11), I get _the same output values_ irrespective of the input feature values.

Is there any known issue with model file backward compatibility? 

Please mail me for test code and model file, don't want to upload the huge thing.

**Comment by ant0nsc** [comment]
Now ran the some images through CNTK commandline, rather than using `EvalWrapper`. Same result: With the latest CNTK build and a model file that comes from a build 2 weeks old, I get exactly the same output values for all of the images in my test set - exactly equal up to the last digit.

My config only has the `write` command essentially, no funny model builders or anything: 

Output1=[
        action=write
        #printValues=false
        outputNodeNames="OutputNodes.z"
        outputPath=$ModelName$_Output1__
        minibatchSize=256
        modelPath=$ModelDir$/$ModelName$
        
        reader=[
            readerType=ImageReader
            file=$DataDir$/Image_labels.tsv
            randomize=None
            features=[
                width=224
                height=224
                channels=3
                cropType=Center
            ]
            labels=[
                labelDim=2
            ]
        ]    
    ]

In the CNTK log file, I see that the model is being loaded, the architecture comes out as expected.

**Comment by Alexey-Kamenev** [comment]
Solved by setting `ACML_FMA` environment variable to 0.

**Comment by ant0nsc** [comment]
Just to provide a bit more of context: One of the machines I was running on has a relatively recent Intel CPU that supports FMA instructions. There's a known bug in the ACML libraries related to FMA instructions - when the bug is hit, all matrix multiplications come out as constant zero, and the network essentially only outputs the bias terms. The magic command (now included in the CTNK setup instructions) disables the use of that codepath in the ACML libraries.
