### ISSUE TITLE
GPU ran out of memory during Testing but not Training

### ISSUE THREAD

**Issue by axonUH** [Microsoft/CNTK#468]
Hi,
While running a Simple2D Example(https://github.com/Microsoft/CNTK/tree/master/Examples/Other/Simple2d), the Training was fine but during Testing the GPU ran out of memory. I had 57 input nodes, 3 hidden layers of 1024 nodes and an output layer with 630 nodes. This ran for about 130 epochs.

A snippet of the log:
<snippet>----------------
CUDA failure 2: out of memory ; GPU=0 ; hostname=xxx ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
EXCEPTION occurred: CUDA failure 2: out of memory ; 
<end snippet>-----------

I expected a resource failure to occur during the Training phase but not the Test phase because I naively assumed that Training would roughly take a super-set of the resources that Testing would incur.

Do you think that this error is explainable and to be expected and if so why?

Thanks

**Comment by Alexey-Kamenev** [comment]
Can you please add minibatchSize to the test section, e.g.:
```
Simple_Demo_Test = [
    action = "test"
    minibatchSize = 32

```

**Comment by axonUH** [comment]
I forgot to indicate that I had set the minibatchSize = 10 when I got the GPU memory crash

**Comment by axonUH** [comment]
Sorry, I mis-read your response. I'll try adding the minibatchSize to the test section as well.

Thanks

**Comment by axonUH** [comment]
The workround was good.

Thanks
