### ISSUE TITLE
Is there any plan to support float16

### ISSUE THREAD

**Issue by helson73** [Microsoft/CNTK#469]
Hi,
I am wondering if there is any plan about supporting 'half' and 'half2' type in the near future.
Thanks.

**Comment by ldmtwo** [comment]
for CPU?

**Comment by helson73** [comment]
@ldmtwo for pascal architecture GPU

**Comment by mahilleb-msft** [comment]
@cha-zhang - can you comment whether / when it's in the plan?

**Comment by cha-zhang** [comment]
We are adding 16bit support for Volta in next iteration. Maybe around September.

**Comment by cha-zhang** [comment]
I'm closing this issue as there is no further actions to be taken. 16bit support will be in our August iteration plan, ETA around mid September.
