### ISSUE TITLE
CNTKTextFormatReader is too verbose reading sparse rows

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#470]
I'm seeing an output like this on every single input row, which is a bit of a perf killer and makes it hard to read the preamble diagnostics.
```
INFO: Finished loading sequence (id = 8339) at offset 11754125 ...
```
I don't see this message when the format is dense, only in sparse format.

**Comment by simra** [comment]
Quick follow-up- this seems like it's a one-time thing. I saw the verbose output on the first run over each dataset, but after that there was no output. I'm not sure what I should expect here.

**Comment by raaaar** [comment]
Trace verbosity does not depend on the input format (dense or sparse) and can be specified in the "reader" config section using "traceLevel". Setting this parameter to 1 (Warning) will suppress all "Info" messages, so that only errors and warnings will be printed out.

**Comment by simra** [comment]
Thanks, I see now I had tracelevel set to 2 in the reader.
