### ISSUE TITLE
Using CPU despite choosing deviceId=auto in Simple2d example

### ISSUE THREAD

**Issue by anshumang** [Microsoft/CNTK#471]
Using gdb, the function DeviceFromConfig() in Source/Include/BestGpu.h runs (which returns -1 used for CPU) instead of Source/Common/BestGpu.cpp.

Can someone pls point me to what I am missing here?

**Comment by mahilleb-msft** [comment]
@anshumang - if you could provide more info to repro this? Please make sure you're using a GPU build and have up-to-date drivers. Also, can you double-check and share the output of nvidia-smi?

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
