### ISSUE TITLE
Microsoft CNTK 1-bit SGD does not work

### ISSUE THREAD

**Issue by NikasZalias** [Microsoft/CNTK#474]
I want to run Speech sample and I'm getting this error

> EXCEPTION occurred: Gradient quantization is unsupported in CNTK binaries built without quantized gradient aggregation support!

I googled this error and found out that the problem is that I don't have 1-bit SGD. Then I opened https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD and made everything that was written, but I'm still getting the same error. 

How to fix this error?

**Comment by amitaga** [comment]
Which platform (Windows vs. Linux) are you using? The error indicates your builds do not include 1-bit SGD - are your sure you did not miss the last step specified in the setup instructions? i.e. 

Windows: Add the Environment Variable CNTK_ENABLE_1BitSGD and set its value to true.
Linux: Pass the option --1bitsgd=yes to the configure command.

Then perform the build as usual.

-Amit

**Comment by NikasZalias** [comment]
I'm using Windows platform. No, I didn't forgot anything. Created environment variable and then recompiled CNTK projects

**Comment by amitaga** [comment]
Did you restart Visual Studio after setting the environment variable, for it to be reflected in the VS environment?

**Comment by NikasZalias** [comment]
No I didn't. I will do it now and inform you in a sec

**Comment by mahilleb-msft** [comment]
Closing assuming this is fixed. Please re-open (or submit a new issue) if this is not the case - thanks!
