### ISSUE TITLE
Ubunt 14.04 (LTS) build error:  error: ‘MPI_Iallreduce’ was not declared in this scope

### ISSUE THREAD

**Issue by ktang2k** [Microsoft/CNTK#48]
Hi, 
This is my first build of CNTK, and I am stuck at the below error message:
**Source/SGDLib/SimpleDistGradAggregator.h:282:186: error: ‘MPI_Iallreduce’ was not declared in this scope**
system: Linux Mint Rosa (based on Ubuntu LTS 14.4). 
CUDA Kit v7.5 (GTX 970) 
I downloaded and installed openmpi, acml, CUB, Cunn per the instructions given on this site. 
Appreciate any suggestions!
Ken

**Comment by gaizkan** [comment]
Hi Ken,

Which version of openmpi are you using? 

You can try the following steps:

cd ~
wget http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.1.tar.gz 
gunzip -c openmpi-1.10.1.tar.gz | tar xf - 
cd openmpi-1.10.1
./configure --prefix=$HOME/mpi
make -j all install 
export PATH=$HOME/mpi/bin:$PATH
 
[Change directory to CNTK repository root, e.g. $HOME/src/CNTK/]
mkdir -p build/release && cd build/release && ../../configure --with-buildtype=release && make -j all
cd .. && mkdir debug && cd debug && ../../configure --with-buildtype=debug && make -j all
export PATH=$PATH:$HOME/src/CNTK/build/debug/bin/

Let us know.
Thanks,
Gaizka

**Comment by alexeyo26** [comment]
Also I spotted you use Cuda 7.5, while the code expects **7.0**, so there might be extra errors, after this one is resolved with such config

**Comment by ktang2k** [comment]
Hi Gaizka,
I did use the openmpi version 1.10.1 and installed it into my home folder as you suggested.
I also tried building as debug as you recommended, and got the same error message.
BR 
Ken

**Comment by ktang2k** [comment]
Hi @alexeyo26 
I am a little uncomfortable installing CUDA kit v7.0 since ver7.5 is working fine with other tools. Do you know if it is safe to install two different versions of the CUDA tool kits?
BTW, when will Microsoft release a binary pkg with CUDA 7.5 for Linux? 
Thanks
Ken

**Comment by rwightman** [comment]
Type 'which mpic++' and ensure it's pointing to the bin folder of your newly built OpenMPI. Make sure your path is set properly with the path to the bin folder of the newer OpenMPI ahead of the path to any other instance on your system so that the correct mpic++ wrapper is called in the build process.

**Comment by ktang2k** [comment]
Hi Ross,
Thank you for the tip! Yeah, it was my mistake. I had my $HOME/mpi/bin 
appended to $PATH, instead of prefixing it.
It works now.
BR
Ken

**Comment by linquanxu** [comment]
@ktang2k  Hi,Ken, I also met the same problem ,which was the 'Source/SGDLib/SimpleDistGradAggregator.h:282:186: error: ‘MPI_Iallreduce’ was not declared in this scope'. I have carefullly checked the path of mpic++,  I am sorry ,but I don't understand what did you do. Could you give me more suggestions? Thank you.

**Comment by ktang2k** [comment]
Hi,
In my case, I had to make sure the correct version of MPI is called by the
builder, by prefixing its lib and bin folders to PATH and LD_LIBRARY_PATH
Ken

**Comment by linquanxu** [comment]
@ktang2k  Hi Ken,Thank you for your reply,My config file (/etc/bash.bashrc) as follows:`export PATH=/usr/local/mpi/bin:/usr/local/MATLAB/R2013a/bin:/usr/local/cuda-7.0/bin:$PATH`,   
 `export  LD_LIBRARY_PATH=/usr/local/mpi/lib:/opt/acml5.3.1/ifort64/lib:/opt/acml5.3.1/ifort64_mp/lib:/usr/local/cudnn-4.0/cuda/lib64:/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH`. but  I got the same error message.How can I solve the problem?

**Comment by ktang2k** [comment]
Hi linquanxu, I could not see why your build would fail.
The only diff I spot is that you are a using system installed mpi. I am
using locally installed (to my home folder) as suggested by the setup
instruction. But I seriously doubt that could be the issue :)
Sorry, I am out of ideas now.
Ken

**Comment by linquanxu** [comment]
@ktang2k  Hi,Key,Thanks again,But issue still exists.I should have check this more clearly.

**Comment by YanMinge** [comment]
Do you solve this issue? I use
OS: ubuntu14.04.4
cude: cuda 7.5.18
openmpi: openmpi-1.10.2
and I also got the same error message.
