### ISSUE TITLE
Segmentation fault when testing CIFAR-10 on linux

### ISSUE THREAD

**Issue by uestcbingo** [Microsoft/CNTK#481]
OS: Ubuntu 14.0.4
CNTK version: latest
GPU: Tesla K80
Description:
I intalled CNTK as suggested including OpenCV3.0.0, zlib and libzip. Examples such as Simple2D and MNist had run succesfully. However, when I was using 03_ResNet.cntk to run CFAR-10 examples, an Segmentation fault occurred after "Starting minibatch loop". And there are no errors in 
03_ResNet_Train_Test.log.
I am considering there might be something wrong with my image reader, but I can't figure it out. Could you please give me some advice? Thank you.

**Comment by Alexey-Kamenev** [comment]
Hello,
This is currently a known issue which happens intermittently in OpenCV and most likely related to a multi-threading bug in OpenCV itself. You can try disabling multi-threading in ImageReader by adding `numCPUThreads=1` to `reader` section, something like that:
```
    reader=[
        readerType="ImageReader"
        file="$DataDir$/cifar-10-batches-py/train_map.txt"
        randomize="auto"
        numCPUThreads=1
```

**Comment by uestcbingo** [comment]
Thank you for the reply, Alexey.
It crashes anyway when I use one thread to read images. Here is the output log.

**Comment by mahilleb-msft** [comment]
Could you re-check with the latest bits?

Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
