### ISSUE TITLE
/home/me/opencv-3.0.0/include/opencv2/opencv.hpp:46:28: opencv/core.hpp: No such file or directory

### ISSUE THREAD

**Issue by machomachopadre** [Microsoft/CNTK#483]
I have got an error while building cntk with make all -j4. As specified in the title the error was:
 /home/me/opencv-3.0.0/include/opencv2/opencv.hpp:46:28: opencv/core.hpp: No such file or directory

The reason I am posting this here(github issues) is because I _had_ compiled and installed opencv following instructions [here](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux). So, I have no clue as to what has caused the error. 

Thanks in advance!!

**Comment by Alexey-Kamenev** [comment]
Hello,
What is the output of CNTK's `./configure` ? Do you happen to have any other versions of OpenCV?

**Comment by machomachopadre** [comment]
The output for ./configure is:
```
[Defaulting to --with-buildtype-release
Found OpenCV at /home/me/opencv-3.0.0
Found libzip at /usr/local
Cannot locate Kaldi files 
Kaldi2Reader will not be built
Generating /home/me/cntk/Config.make
run
>make -j all
to build
```
I had another OpenCV installation but I had deleted it.
Thanks!!

**Comment by machomachopadre** [comment]
I have got it working _without_ opencv but I really want a solution because I need opencv...
Thanks :full_moon_with_face:

**Comment by wolfma61** [comment]
this should be solved in later releases/versions

**Comment by woskii** [comment]
@rushatrai Same error. Did you solve this problem?
