### ISSUE TITLE
Extremely Slow CV Command with Recent Builds

### ISSUE THREAD

**Issue by amirbegan** [Microsoft/CNTK#485]
I've tried using the official release 1.1 precompiled binaries and the train performance seems ok, but running the CV command is extremely slow; it takes hours to evaluate one model against a test set with 2 million records (4 inputs, 1 output, regression).

It is slow using both GPU and CPU.

This is the output to show which build I am using:
Build info:
                Built time: Apr 24 2016 21:47:31
                Last modified date: Mon Apr 18 00:00:12 2016
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
                CUB_PATH: C:\src\cub-1.4.1
                CUDNN_PATH: c:\NVIDIA\cudnn-4.0\cuda
                Build Branch: HEAD
                Build SHA1: 29c065ae7c1c370d8852c283d4e9f1a068ba2233
                Built by svcphil on LIANA-09-w
                Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\

I've picked up the master branch yesterday (2016-05-16) and built my own binaries and it behaves the same (CV unworkable).

I have a build of the master branch from 2016-04-15 and that build does not have the issue (nor did any other previous build I have used, either precompiled or compiled by me).

Could you please confirm if you experience the same?

**Comment by SteFromGer** [comment]
same here. But the test performance is much slower since 1.1 as well.

**Comment by amirbegan** [comment]
Thanks for confirming SteFromGer.

I am surprised no one else is complaining about this, because it makes the latest binaries release (and the current master branch) of cntk pretty much unusable (I can only guess it's perhaps affecting only some specific combo (UCIFastReader + regression?) so not that many people are running into it).

I've attached a simple config that can be used to check for this.

There are two folders, PerfTestNew is generated with cntk 1.1 from 2016-04-25 (https://github.com/Microsoft/CNTK/releases) and PerfTestOld is generated with the binaries released on 2016-02-10.

Data 100,000 records, 4 inputs, 1 output. First I run the "train" command using 001.cntk config, which produces 10 models (10 epochs) and then run the CV command (evaluate 10 models on the same 100,000 dataset).

With the new cntk (1.1) CV took around 7 minutes.

With the release from 2016-02-10 CV took a few seconds (basically finished immediately).

Could someone please look into this?

[perfTest.zip](https://github.com/Microsoft/CNTK/files/288489/perfTest.zip)

**Comment by SteFromGer** [comment]
I am using CNTKTextFormatReader. I have a LSTM recurrent network with 6 Inputs and 3 Output. But I figured out that it doesn’t matter which net type you use, it’s unusable anyway.

**Comment by amirbegan** [comment]
Fix for this issue is to change line 160 (source code for Tag 1.1) in ActionsLib\EvalActions.cpp from:
SimpleEvaluator<ElemType> eval(net, MPIWrapper::GetInstance(), numMBsToShowResult, traceLevel, maxSamplesInRAM, numSubminiBatches);

to:
SimpleEvaluator<ElemType> eval(net, MPIWrapper::GetInstance(), numMBsToShowResult, 0 /* firstMBsToShowResult */, traceLevel, maxSamplesInRAM, numSubminiBatches);
