### ISSUE TITLE
GUI Interface

### ISSUE THREAD

**Issue by Tak-Au** [Microsoft/CNTK#486]
It will be great if somehow there will be GUI interface to build the NN without going through coding; and the GUI will show exactly the structure of the NN.  May be also great if there's template within the GUI so that user can select template without starting from scratch.

**Comment by sguergachi** [comment]
Don't think this is within the scope of this project. But I like this idea as a superset project.

**Comment by pkranen** [comment]
This is indeed outside the scope of the CNTK project.
