### ISSUE TITLE
Speech to text converter

### ISSUE THREAD

**Issue by rashee182** [Microsoft/CNTK#488]
Is there any "speech to text" converter example available in CNTK.
The example given here "\cntk\Examples\Text\PennTreebank" looks like for text recognition only.

**Comment by vmazalov** [comment]
To convert "speech to text" one would need several models (acoustic, language, lexicon, etc.) and a decoder. This is a superset of what CNTK was designed for.

**Comment by rvenkidapathy** [comment]
Is there an example as to how to convert speech to text using CNTK? 
Does theses models are also part of CNTK?
