### ISSUE TITLE
Cannot open include file: 'cuda.h': No such file or directory

### ISSUE THREAD

**Issue by wangdelp** [Microsoft/CNTK#489]
I am using visual studio to compile CNTK. 

I've installed cuda 7.5 and added the path to the system variables, and add the path of include dir and libraray dir to CNTK Project Properties/VC++ Directories/Include Directories, Library Directories, and include dir to CNTK Project Properties/C++/General/Additional Include Directories. But when I compile it, I will encounter errors complaining that: 

Cannot open include file: 'cuda_runtime_api.h': No such file or directory. 
Similarily for other header files: ValueQuantizer.h(8): fatal error C1083: Cannot open include file: 'cuda.h': No such file or directory (MatrixQuantizerCPU.cpp). How could I make visual studio to be able to find those header files? Thank you.

**Comment by mahilleb-msft** [comment]
Normally the CUDA installer should set necessary environment variable itself and you also don’t need to modify project settings (see https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows for details).

  Can you share the value of the CUDA* environment variables? Can you validate the paths they point to exist? Maybe VS hasn’t picked up these environment variables yet, can you try closing and re-opening (or logging out and in again)?

 (Also, I would advise to revert your changes to the VS project settings; as I said it should work out of the box once the environment setup is completed)

**Comment by wangdelp** [comment]
@mahilleb-msft  I've solved the problem, sounds like I need to reboot the machine to have the newly installed cuda to be reflected. Thanks anyway

**Comment by mahilleb-msft** [comment]
Great, closing the issue here then.
Best, Mark
