### ISSUE TITLE
Make sure samples use realistic settings for real-life use

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#49]
The samples use very small data sets, but will serve as the best-practice examples for real-life use. We should review/revise their configurations as to be applicable to large realistic data sets. E.g. while a tiny minibatch size is great for debugging, it is unnecessarily inefficient for parallelization.

**Comment by wolfma61** [comment]
I would prefer a "best practices" section in the wiki. This is an extensive topic and it would be great for the community if our experts can give some more broader advice on the right parameters to use or start with
