### ISSUE TITLE
how to do layer-wise unsupervised pre-training in CNTK for classfication on small-size dataset ?

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#491]
I have a classification task, with only 2000 samples in total for all 8 classes.
I want use lot of other data for unsupervised pre-training?
Is it supported in CNTK? and how?

**Comment by sayanpa** [comment]
The data size for the number of class and deep model seems small. Depending on the number features and the model structure you may end up overfitting. However, CNTK does let you do modeling. You can freeze specific layers in the model and then train a network.

Given this link has been out for a while, I am closing it. Please feel free to re-open as needed.
