### ISSUE TITLE
error in training LM sample with multi-GPU

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#493]
I tried the PennTreebank sample and then modified it to multi-gpu version.After one epoch it stoped.
“EXCEPTION occurred: SetDataLocation [CPUSparseMatrix]: Cannot migrate the matrix between devices because it is a view.”
How to understand it ?
Thanks！

**Comment by mahilleb-msft** [comment]
If the error persists for you, could you retest on the latest bits?
Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
