### ISSUE TITLE
[SOLVED]cntk configFile=../Config/01_OneHidden.cntk not running on ubuntu

### ISSUE THREAD

**Issue by machomachopadre** [Microsoft/CNTK#494]
Hi everyone. I am running CNTK on Ubuntu 14.04 LTS(Trusty Tahr I think?), and after following the tutorial [here](https://github.com/Microsoft/CNTK/wiki/Tutorial2), I try to run:
                                        `cntk configFile=../Config/01_OneHidden.cntk`
and get the following error: _No command 'cntk' found, did you mean:_ and so on so forth.
Please help :pray: :pray: and sorry if this a complete **n00b** mistake. Thanks!!

**Comment by ant0nsc** [comment]
Looks like `cntk` is not on your path. Have a look [at the setup guide](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#quick-test-of-cntk-build-functionality), or directly specify the path to your CNTK executable.

**Comment by machomachopadre** [comment]
i tried your solution and ran... 
`echo "export PATH=$HOME/code/cntk/build/release/bin:$PATH" >> ~/.bashrc`
...but it didn't work.
Thanks for your time!

**Comment by machomachopadre** [comment]
It worked!!! I just had to mount the directory and _then_ do the export path....as I said I'm a **n00b**...but anyway thanks for your help!!

**Comment by machomachopadre** [comment]
mod close this pls

**Comment by ant0nsc** [comment]
@machomachopadre : You can close the issue yourself, no need to summon any moderators :-) Big button at the bottom of the page.

**Comment by machomachopadre** [comment]
Either I am blind or I cant see button :P (still did not find it)
