### ISSUE TITLE
Qestion in Kaldi example.

### ISSUE THREAD

**Issue by FreedMana** [Microsoft/CNTK#498]
Hello, everyone!
I tried the kaldi reader example train_cntk2.sh with CHiME recepi(not with AMI corpus,so i modified it ).
It worked well and I step into train_cntk2_smbr.sh. The program went wrong in Alignment.
Here is the log information:

evaluate: reading 652 frames of 011_011C0201_PED.CH5_SIMU
sym2int.pl: replacing _FLUCTUATE_ with 64
sym2int.pl: replacing _IGNORANCE_ with 64
sym2int.pl: replacing EXISITING with 64
*\* Replaced 3 instances of OOVs with 64
evaluate: writing 652 frames of ark:011_011C0201_PED.CH5_SIMU
evaluate: reading 693 frames of 011_011C0202_PED.CH5_SIMU
evaluate: writing 693 frames of ark:011_011C0202_PED.CH5_SIMU
LOG (compile-train-graphs:main():compile-train-graphs.cc:145) compile-train-graphs: succeeded for 802 graphs, failed for 0
WARNING (align-compiled-mapped:main():align-compiled-mapped.cc:92) No fst for utterance 011_011C0201_PED
evaluate: reading 1069 frames of 011_011C0203_BUS.CH5_SIMU
evaluate: writing 1069 frames of ark:011_011C0203_BUS.CH5_SIMU
WARNING (align-compiled-mapped:main():align-compiled-mapped.cc:92) No fst for utterance 011_011C0202_PED
evaluate: reading 449 frames of 011_011C0204_STR.CH5_SIMU
evaluate: writing 449 frames of ark:011_011C0204_STR.CH5_SIMU
WARNING (align-compiled-mapped:main():align-compiled-mapped.cc:92) No fst for utterance 011_011C0203_BUS
evaluate: reading 373 frames of 011_011C0205_STR.CH5_SIMU
evaluate: writing 373 frames of ark:011_011C0205_STR.CH5_SIMU
WARNING (align-compiled-mapped:main():align-compiled-mapped.cc:92) No fst for utterance 011_011C0204_STR
evaluate: reading 550 frames of 011_011C0206_BUS.CH5_SIMU
evaluate: writing 550 frames of ark:011_011C0206_BUS.CH5_SIMU
.................

How does it happen? I checked the file path and did not find out the problem.Could you give me a hint to solve this?
Thanks!

**Comment by wolfma61** [comment]
I'm not sure if this has been resolved, but it's been very old. Please try the latest 2.0 release and see if there are still issues. Feel free to open a new issue if needed. Thanks!
