### ISSUE TITLE
Tutorial2 missing step to download MNIST data

### ISSUE THREAD

**Issue by skiwi2** [Microsoft/CNTK#499]
When following the following tutorial at https://github.com/Microsoft/CNTK/wiki/Tutorial2#putting-it-all-together I get an error that the Train-28x28.txt data is not present.

After googling a bit I found https://github.com/Microsoft/CNTK/tree/master/Examples/Image/MNIST which suggests to run `python mnist_convert.py` before attempting to run the MNIST cntk.

I suppose that step is missing from the linked part of the Tutorial2 tutorial?
As after running the python command everything works as intended.

**Comment by machomachopadre** [comment]
I was getting the same error and wondering what went wrong. How do we run that script on ubuntu though?
Thanks :bowtie:

**Comment by jeanfad** [comment]
Hi, there is a section about it in the tutorial: https://github.com/Microsoft/CNTK/wiki/Tutorial2#getting-the-data
