### ISSUE TITLE
Newbie need help at "simple3d"

### ISSUE THREAD

**Issue by baciek** [Microsoft/CNTK#504]
As I said I'm new to CNTK (and programming) and I have encounter a lot of simple and silly problems even when I was trying to rewrite a "Simple2d" example. I wanted it to read 3-dimentional input data and work on it - and this is the only diffrence. It still has only one label (dimention = 2, because there are only two possible numbers: 0 or 1). I just can't figureout what's wrong with it.
I'm running it on the GPU version.
Here is the code (I've almost changed nothing in it. I've deleted all the comments to make it shorter):
## simple.cntk:

RootDir = ".."

ConfigDir = "$RootDir$/Config"
DataDir   = "$RootDir$/Data"
OutputDir = "$RootDir$/Output"
ModelDir  = "$OutputDir$/Models"

deviceId = "auto"   #because I have the GPU ver. of library.

command = Simple_Demo_Train:Simple_Demo_Test:Simple_Demo_Output

precision = "float"
traceLevel = 1
modelPath = "$ModelDir$/simple.dnn"
outputNodeNames = ScaledLogLikelihood
###### 
# TRAINING CONFIG
###### 

Simple_Demo_Train = [
    action = "train"

```
SimpleNetworkBuilder = [
    #3 input, 2 50-element hidden, 3 output                     (  ???  )
    layerSizes = 3:50*3:3                                                   #i've changed all the "2" to "3".
    trainingCriterion = "CrossEntropyWithSoftmax"
    evalCriterion = "ErrorPrediction"
    layerTypes = "Sigmoid"
    initValueScale = 1.0
    applyMeanVarNorm = true
    uniformInit = true
    needPrior = true
]

SGD = [

    epochSize = 0 
    minibatchSize = 25  
    learningRatesPerMB = 0.5:0.2*20:0.1
    momentumPerMB = 0.9
    dropoutRate = 0.0
    maxEpochs = 10
]

reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/SimpleDataTrain.txt"
    miniBatchMode = "partial"
    randomize = "auto"
    verbosity = 1  

    features = [
        dim = 3                                               # three-dimensional input data
        start = 0                                             # Start with first element on line
    ]

    labels = [
        start = 3                                            # Skip three elements
        dim = 1                                             # One label dimension
        labelDim = 2                                     # Two labels possible ( 0 or 1 )
        labelMappingFile = "$DataDir$/SimpleMapping.txt"
    ]
]
```

]
###### 
# TEST RESULTS
# (computes prediction error and
# perplexity on a test set and
# writes the output to the console.)
###### 

Simple_Demo_Test = [
    action = "test"

```
# Parameter values for the reader
reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/SimpleDataTest.txt"
    randomize = "none"

    features = [
        dim = 3
        start = 0
    ]

    labels = [
        start = 3
        dim = 1
        labelDim = 2
        labelMappingFile = "$DataDir$/SimpleMapping.txt"
    ]
]
```

]
###### 
# OUTPUT RESULTS
# (Computes the labels for a test set
# and writes the results to a file.)
###### 

Simple_Demo_Output=[
    action = "write"

```
reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/SimpleDataTest.txt"
    randomize = "none"

    features = [
        dim = 3
        start = 0
    ]

    labels = [
        start = 3
        dim = 1
        labelDim = 2
        labelMappingFile = "$DataDir$/SimpleMapping.txt"
    ]
]

outputNodeNames = PosteriorProb : labels    
outputPath = "$OutputDir$/SimpleOutput"     
#outputPath = "-"                           

format = [
    type = "category"                             
    labelMappingFile = "$DataDir$/SimpleMapping.txt" 
    sequenceEpilogue = "\t// %s\n"                   
]
```

]

And here are the "AddOperatorConstant" and "AddOperatorConstantNolnput" files (I don't know if they're needed to run this example):
## AddOperatorConstantNolnput:
# deviceId=-1 for CPU, >=0 for GPU devices, "auto" chooses the best GPU, or CPU if no usable GPU is available

deviceId = "auto"

command = Add_Operator_Constant

precision = "float"
traceLevel = 1
###### 
# NETWORK CONFIG
###### 

run=NDLNetworkBuilder
NDLNetworkBuilder=[
          v1 = Constant(1)
          v2 = Constant(3)                        #i've changed 2 to 3
          ol = Plus(v1, v2)

```
      FeatureNodes=(v1)

      OutputNodes=(ol)
]
```

Add_Operator_Constant = [
    action = "write"
]
## AddOperatorConstant:
# deviceId=-1 for CPU, >=0 for GPU devices, "auto" chooses the best GPU, or CPU if no usable GPU is available

deviceId = "auto"

command = Add_Operator_Constant

precision = "float"
traceLevel = 1
###### 
# NETWORK CONFIG
###### 

run=NDLNetworkBuilder
NDLNetworkBuilder=[
          features = Input(1)
          v2 = Constant(3)                          #i've changed 1 to 3
          ol = Plus(features, v2)

```
      FeatureNodes=(features)
      OutputNodes=(ol)
]
```

Add_Operator_Constant = [
    action = "write"
]

As you can I didn't change much. I have changed the readers (features dim {2 changed to 3}, and the labels.)

When I run this program there's a error (exception):
EXCEPTION OCCURED: NotifyFunctionValuesMBSizeModified: labels InputValue operation had its row dimension 3 changed by the reader to 2.

I don't know what does it mean. I would appreciate any help with running this network for 3-dimentional data.
Thanks.

**Comment by cha-zhang** [comment]
3D convolution is supported and we have an example here: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Video/GettingStarted 

I'm closing this issue since it's too old. Feel free to open a new issue if you still encounter problems.
