### ISSUE TITLE
NN for binary classification: one-node vs two-node outputs

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#505]
I'm attempting to build a network for binary classification.
If I create a network with two nodes as outputs and provide labels in the form of [label, 1-label] I can build a reasonable model.
However if I set my label (and output) dimension to 1 and provide only one label value for each example (since having two is redundant), the network fails to build a reasonable model.  In particular, the error at each iteration is 0:

```
Starting Epoch 1: learning rate per sample = 0.000391  effective momentum = 0.900000  momentum as time constant = 2429.8 samples

Starting minibatch loop.
 Epoch[ 1 of 2]-Minibatch[   1-  10]: CE.SM = -0.00000000 * 2560; Err = 0.00000000 * 2560; time = 1.2743s; samplesPerSecond = 2008.9
 Epoch[ 1 of 2]-Minibatch[  11-  20]: CE.SM = 0.00000000 * 2560; Err = 0.00000000 * 2560; time = 0.7220s; samplesPerSecond = 3545.6
```

I specify my network using the create_1layer.ndl example (with minor revisions).  SMBFF is CrossEntropyWithSoftmax.

```
ndlCreateNetwork=[

    #define basic i/o       
    hiddenDim=$HDim$ # rsim: was 512
    features=Input($dimension$, tag="feature")
    labels=Input($labelDim$, tag="label")

     # define network
     featNorm = MeanVarNorm(features)
     L1 = SBFF(featNorm,hiddenDim,$dimension$)
     CE = SMBFF(L1,$labelDim$,hiddenDim,labels,tag="criterion")
     Err = ErrorPrediction(labels,CE.BFF.FF.P,tag="evaluation")

     # define output (scaled loglikelihood)
     logPrior = LogPrior(labels)     

     ScaledLogLikelihood=Minus(CE.BFF.FF.P,logPrior,tag="output")   
#    PosteriorProb=CE.BFF.FF.P 
]
```

and I'm using CNTKTextReader like so ($labelDim$=1):

```
eader = [
        readerType = "CNTKTextFormatReader"
        file = "$dataPath$Train.txt"
        randomize = "auto"
        maxErrors = 100
     #   traceLevel = 2

        input = [
            features = [
                alias = "F"
                dim = $dimension$
                format = "sparse"
            ]
            labels = [ 
                alias = "L"
                dim=$labelDim$ 
                format="dense" 
            ]
        ]   
    ]
```

I'm sure my difficulty comes from my limited understanding of NDL- maybe I'm using an unnatural evaluation criterion for single-node outputs?

**Comment by wolfma61** [comment]
this issue has been dormant for a long while, there are many more tutorials availabe now. Not looking into too much detail, but perhaps this tutorial is helpful: https://docs.microsoft.com/en-us/cognitive-toolkit/Hands-On-Labs-Language-Understanding

Closing this issue now. I would recommend asking this kind of questions on StackOverflow (see https://docs.microsoft.com/en-us/cognitive-toolkit/Feedback-Channels)
