### ISSUE TITLE
C# evaluation client + wrapper won't evaluate CIFAR-10 examples any more

### ISSUE THREAD

**Issue by LowerySJ** [Microsoft/CNTK#506]
Hi guys. With an earlier version of the CNTK project I was able to use the C# wrapper to evaluate the 01_Conv and 03_ResNet example networks for CIFAR-10. With the latest version of CNTK, I am not able to do this. Using the C# evaluation client provided, I am able to create the IEvaluateModelF variable and then pass it inputs, but no matter which inputs I pass I am given back the same outputs!

This problem does NOT occur for the 01_OneHidden model for the MNIST data. Also, this problem does NOT occur when loading the networks through the native CPP evaluation client. 

I don't have the info of the version for which the C# client was working -- it was from around 21+ days ago. (I'm learning to use git now.)

Also: this problem occurred even when I deleted and retrained the 01_Conv network example using the latest version of CNTK (pulled from official repo earlier today).

Please let me know if there's any other info you might need.

Thanks and regards,

Steve

**Comment by gaizkan** [comment]
Hi LowerySJ,

I would like to make sure you have ACML_FMA set to 0 in your environment variables (there is a bug with the ACML library, causing the output to be constant).

Let me know, we'll go from there.

**Comment by LowerySJ** [comment]
Yes, that worked. Thanks!
