### ISSUE TITLE
Critical CNTK documentation errors

### ISSUE THREAD

**Issue by machomachopadre** [Microsoft/CNTK#507]
[This](https://github.com/Microsoft/CNTK/issues/499) thread has pointed out a fault in the CNTK documentation. Please fix this because it is _very_ misleading for beginners who want to start DL, but are only to be stopped by an error which they think has been caused by _them_. 

There is **another** documentation error too:
In [this](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#quick-test-of-cntk-build-functionality) part of the setup it says you should export the path before mounting the directory- this is wrong, it's common sense- but, for _absolute beginners_  it causes an error(it does not let you run anything because the bin is not in the path and `cntk` is not a recognised command by linux), which they might think they have done because of a mistake somewhere.

Please fix these documentation errors, because these are guides _meant_ for newbies. I understand as it is open-source you might have a few difficulties but at least, try your best! Thanks for reading, and please escalate.

**Comment by machomachopadre** [comment]
could someone acknowledge this at the most?...disappointed with cntk community....

**Comment by jeanfad** [comment]
Hi there is section in the tutorial about getting the data. Thanks, Jean
