### ISSUE TITLE
How to set the values of minibatchSize and  nbrUttsIneachRecurrentIter for LSTM training?

### ISSUE THREAD

**Issue by NewEricWang** [Microsoft/CNTK#511]
I found the appropriate values of minibatchSize and  nbrUttsIneachRecurrentIter will incurred  unexceptional errors in LSTM training.  I can't find any introduction about setup of the two parameters.
Could anybody introduce some empirical methods for setting the two parameters? Thanks!

**Comment by summerqing** [comment]
In my experiment,the two parameters will also affect the parallization effect.

**Comment by wolfma61** [comment]
not sure if this is still an open issue. I would recommend asking this kind of question at StackOverflow ...
(see https://docs.microsoft.com/en-us/cognitive-toolkit/Feedback-Channels)
