### ISSUE TITLE
CNTK.exe has stopped working

### ISSUE THREAD

**Issue by sofeikov** [Microsoft/CNTK#514]
Hi guys,

pretty often when I run training I see this dialog message shown. The funniest part is that if you run several times the same config - you might see this message several times, however, suddenly it might start working without any problem. 

Here is stack I've grabbed from the debugger:

![cntk](https://cloud.githubusercontent.com/assets/6204851/15485970/5bf9f896-213a-11e6-857c-cc5a709ac881.png)

Any suggestions? Please let me know if I can provide you with more useful than debugger stack information. Thanks

**Comment by Alexey-Kamenev** [comment]
Hi Konstantin,
If this happens when you use ImageReader, then it might be related to the issue with OpenCV in multi-threading environment. This was already reported few times, for example, see #481.
Sometimes setting `numCPUThreads=1` might help though it will most like affect the performance.

**Comment by eldakms** [comment]
Yes, this was related to race condition in static initialization in OpenCV 3.0 on Windows. We switched to OpenCV3.1  that properly guards static initialization in version 1.6. Should not happen anymore.
Thank you!

**Comment by navidnadery** [comment]
It happened to me @eldakms , i have used the latest versions, my OpenCV is 3.1 but when i make my convolution network a little big, this error happens to me.
I have 2 Convolution layers with 240 node per each one with filter size 6 and batchSize=100.
But when i use batchSize=20 it is ok and i don't get any error.
But i need to train it with batchSize=100 which stops with bellow error.

More information :
 Problem Event Name:	APPCRASH
  Application Name:	CNTK.exe
  Application Version:	0.0.0.0
  Application Timestamp:	57879db4
  Fault Module Name:	Math.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	57879d38
  Exception Code:	c0000005
  Exception Offset:	000000000022c303
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1065
  Additional Information 1:	c951
  Additional Information 2:	c951c24ae39a09556b947c3b13d3a2ce
  Additional Information 3:	a929
  Additional Information 4:	a929bfa274cb792ac308e3d15aa03544

**Comment by navidnadery** [comment]
I need to use imageLayout = "HWC" because after training I need the network weights in Matlab.
And the error is just happening in imageLayout = "HWC" mode, when I used imageLayout = "cuDNN" it was trained without any error.

Thanks.

**Comment by frankseide** [comment]
"HWC" is an old format that we would like to phase out (it is much slower than "cuDNN" since cudnn libraries do not support it). May I suggest a different route. Can you use Matlab to swap the data into the right format?

**Comment by navidnadery** [comment]
I don't know what is the correct data format in cuDNN mode.
Here is my previous problem which I could not find the correct format.
#104

**Comment by madingo87** [comment]
Same here... im using the ImageReader for my cnn with two convolutional layers.
I have OpenCV 3.1 and the latest CNTK (pulled from master two days ago)
Still the problem occurs, that CNTK (ALMOST everytime!) stops working with the "smallest" cnn layerconfig...

When using JITdebugging the error seems to occur in 
`SequenceDataPtr TransposeTransformer::TypedTranspose<TElementTo>::Apply(ImageSequenceData* inputSequence)` in ImageTransformers.cpp

**Comment by navidnadery** [comment]
Have you tried using another data?
I suggest trying known data in CNTK files.

**Comment by madingo87** [comment]
Tanks for the reply! 
Training with just a small collection of my original training data works fine... And using the whole trainingset has been working two times... strangely it worked these times and after changing and again reseting the Network and SGD Parameter it didn't!

The images of the whloe trainingset are all the same size (210x210x4) and all in BGRA...
Any other suggestions?
