### ISSUE TITLE
Max Error Rate for Early Stopping

### ISSUE THREAD

**Issue by IkennaOkafor** [Microsoft/CNTK#515]
I have been reading through all the documentation on CNTK and early stopping criterion. I was wondering does CNTK have support to stop training once a certain error prediction Rate threshold has been crossed?

**Comment by dongyu888** [comment]
There is no option for this right now. You can either implement an option inside CNTK or have a script monitor and stop the process.

**Comment by wolfma61** [comment]
perhaps the crossvalidation class is what you are looking for?

https://docs.microsoft.com/en-us/python/api/cntk.train.training_session.crossvalidationconfig
