### ISSUE TITLE
2D labels

### ISSUE THREAD

**Issue by bulatGH** [Microsoft/CNTK#516]
I was wondering if there is a way to use 2D images as labels?

**Comment by lofrank** [comment]
I'm also interested in this. Don't know how to do, too.

**Comment by mahilleb-msft** [comment]
@pkranen - would you know?

**Comment by spandantiwari** [comment]
@bulatGH What do you mean by using 2D images as labels? Do you mean something like semantic segmentation of images where each pixel is assigned a label? Or is it something else?

**Comment by bulatGH** [comment]
@spandantiwari, Yes, something like semantic segmentation or U-nets.

**Comment by spandantiwari** [comment]
Great. We are working on an example of semantic segmentation. Please track issue #1613 for that request.
