### ISSUE TITLE
The Train-28x28.txt not found

### ISSUE THREAD

**Issue by xmuhcd** [Microsoft/CNTK#517]
i understand that this may be not an issue and can be a dumb question. 
After compiling the CNTK, I tried to test it using the mnist example, but not train data is found in the folder ..\Data. It seems I should find it online myself.  I googled it, but not find a txt format dataset so far.  Does anyone know where I can find the Train-28x28.txt? 

Many thanks!

PS: I am using VS2013 on windows 10.

**Comment by machomachopadre** [comment]
Hi,
You have to run `python mnist_convert.py` in the CNTK/Examples/Image/MNIST/ directory(which means you have to use _cd_ command). Error in their tutorial 2 documentation.
Cheers 🍻 🍻

**Comment by xmuhcd** [comment]
Hello @machomachopadre ,

Many thanks! For windows, I just run mnist_convert_python3.py instead of mnist_convert.py. mnist_convert.py did not do any job as I tried.  mnist_convert_python3.py did the right job. 

Thanks!

Best

**Comment by machomachopadre** [comment]
No problem
