### ISSUE TITLE
Times(x,y) sometimes gives only zeroes for some shapes of x,y

### ISSUE THREAD

**Issue by HartmutMaennel** [Microsoft/CNTK#519]
Not sure under which conditions this happens, but here is a small repro case:
(This example does not do anything useful, it is just to demonstrate the problem)
Rename the ...cntk.txt and ....ndl.txt files by removing the .txt, put all files in the same folder.
Train a model with
mkdir Models
cntk configFile=Test.cntk

Run it on the test file test5.txt (which consists of the first 5 lines of the training file test7.txt), writing out the values of the 4 hidden nodes by
cntk configFile=Write.cntk fileName="test5.txt"
This gives a file write_output.hidden with 5 lines of 4 numbers each, they look random enough to be plausible.

Now run it on the test file test6.txt (which has one more line from the training file) by
cntk configFile=Write.cntk fileName="test6.txt"
This gives a file write_output.hidden with 6 lines of 4 numbers each, but all are 0.000000
(even though the first 5 lines should be the same as in the last case, and looking at write_output.w1 and write_output.features you can see that the inputs to hidden=Times(w1,features) were not zero)

The problem does not seem to occur if I change the number of hidden nodes from 4 to 3.
I see this on a recent build (May 18, built with Visual Studio)

[test5.txt](https://github.com/Microsoft/CNTK/files/279426/test5.txt)
[test6.txt](https://github.com/Microsoft/CNTK/files/279428/test6.txt)
[test7.txt](https://github.com/Microsoft/CNTK/files/279427/test7.txt)
[write.cntk.txt](https://github.com/Microsoft/CNTK/files/279476/write.cntk.txt)
[test.cntk.txt](https://github.com/Microsoft/CNTK/files/279436/test.cntk.txt)
[Test.ndl.txt](https://github.com/Microsoft/CNTK/files/279437/Test.ndl.txt)

**Comment by frankseide** [comment]
If this happens in CPU mode, it may be a known bug in the ACML library with the new Intel AVX instructions, which leads to zero matrix products. In that case, please try:
```
set ACML_FMA=0
```
and run CNTK with that variable set.

If that solves it for you, you'd want to bake this variable into your system environment. The easiest is by running this command from an elevated Admin shell:
```
setx ACML_FMA 0
```

**Comment by HartmutMaennel** [comment]
Thanks a lot! Yes, that solved the problem.
