### ISSUE TITLE
Cuda not in makefile.config

### ISSUE THREAD

**Issue by machomachopadre** [Microsoft/CNTK#523]
I have been having issues with cntk: namely it has not been using the gpu. I have verified my cuda installation by running the cuda test. Besides I also have caffe running perfectly on my gpu. I found makefile.config does not have any cuda or cudnn paths. How do I fix this? 
Thanks :bowtie:

**Comment by dongyu888** [comment]
Have you followed the steps in https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux?

**Comment by machomachopadre** [comment]
Yes, thats why i am asking

**Comment by mahilleb-msft** [comment]
Please paste your complete "./configure" output and Config.make contents if you're still having this issue.

Thanks, Mark

**Comment by wolfma61** [comment]
closing this now, if you still experience this issue with the latest bit and following the instructions for Linux build on https://docs.microsoft.com/en-us/cognitive-toolkit/Setup-development-environment, please open a new issue with the information requested from mahilleb-msft ... thx
