### ISSUE TITLE
Where is Test-28x28_cntk_text.txt?

### ISSUE THREAD

**Issue by lofrank** [Microsoft/CNTK#524]
I'm trying to run this cntk file, which is for E2E test for CNTKTextFormatReader.

https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/CNTKTextFormatReader/Examples/Image/MNIST/Config/01_OneHidden.cntk
        _readerType = "CNTKTextFormatReader"
        file = "$DataDir$/Test-28x28_cntk_text.txt"_

Test-28x28_cntk_text.txt is referred as the input file, but I can't find it in this repo.

Would you please commit this file?

I tried to write one by myself, but the error rate is very high (0.8974) after training, which is abnormal.
My file:
_|labels  0 0 0 0 1 0 0 0 0 0	|features  ...
|labels  0 0 0 1 0 0 0 0 0 0	|features ..._

Thanks

**Comment by jeanfad** [comment]
Hi, Under examples/image/mnist there are python scripts to fetch the data and prepare it for the reader.https://github.com/Microsoft/CNTK/tree/master/Examples/Image/MNIST/AdditionalFiles

thanks,
Jean

**Comment by lofrank** [comment]
@jeanfad 
Thanks for your suggestion.
But that script will only generate Train-28x28.txt file, but not Test-28x28_cntk_text.txt.
The format of them is different, the later is for CNTKTextFormatReader.

**Comment by aayushgarg** [comment]
You can find the files here: https://github.com/Microsoft/CNTK/tree/master/Tests/EndToEndTests/Image/Data

**Comment by lofrank** [comment]
@aayushgarg 
Thanks so much, that's it.
I didn't find it because the file name is different from the one in the cntk config file.

**Comment by 256zib** [comment]
Hi!
But i have files Test-28x28_cntk_text.txt and Train-28x28_cntk_text.txt
When i runing project CSEvalClient, i have error in funtion EvaluateMultipleModels in line int expected = int.Parse(line.Substring(0, line.IndexOf('\t'))); System.ArgumentOutOfRangeException
In this files not '\t' symbol. 
How to solve this problem?

Thanks
