### ISSUE TITLE
invalid property "MultiSeq"

### ISSUE THREAD

**Issue by FreedMana** [Microsoft/CNTK#525]
Hello,everyone. When i tried the smbr sample, there is a EXCEPTION in model edit stage.
It states "Invalid property, MultiSeq, is not supported" .  My CNTK version is the latest.
 I find some information in the code.
 `else if (EqualCI(value,       "multiSeq"))  fprintf(stderr, "'multiSeq' tag is defunct.\n");
285         }` 
So if it is defunct, what should I do to replace it?

BTW, is there a way to get the descriptions of "DummyCriterion , seqTrainDeriv, seqTrainObj"?  I haven't
seen them before.
Thanks!

**Comment by dongyu888** [comment]
You can remove that line in the MEL file. This flag is no longer needed.

 

Thanks,

 

Dong Yu (俞栋)

**Comment by FreedMana** [comment]
@dongyu888 thanks ,already removed.
