### ISSUE TITLE
 CNTK APIs supporting Python, C++ and C# bindings?

### ISSUE THREAD

**Issue by whitmark** [Microsoft/CNTK#527]
Earlier CNTK presentations (e.g., NIPS 2015) suggested support was coming for Python and C# but since 5/16/2016 I see references to Python and C++.  What about support for C#?

https://github.com/Microsoft/CNTK/wiki/CNTK-FAQ

**Comment by gaizkan** [comment]
That was a typo, the wiki page has been updated. The bindings will include .Net interfaces.
