### ISSUE TITLE
Tutorial 1 Issues (Wiki)

### ISSUE THREAD

**Issue by baogorek** [Microsoft/CNTK#529]
In regards to https://github.com/Microsoft/CNTK/wiki/Tutorial, I found the following things that might trip someone up:
1. $dimension$ must have failed to resolve in the article. It appears in two cases and I believe I hard coded it to 2 both times so that the code would work.
2. The "Command Test" section was written for a configuration file that uses ClassificationError as an evaluation node, but the actual node presented in the configuration (earlier in the article) is a SquareError node. This seems to be mixing the regression and classification frameworks.
3. I assume action = dumpnode should really be action = "dumpnode"
4. When I originally ran the code, I got an error that I was missing modelPath. I figured out how to add one but that should probably be in there as well.

Thanks for the tutorial. I wanted to propose changes via the pull request mechanism, but I'm not a git expert and I wasn't sure how to work with the wiki that way.

**Comment by jeanfad** [comment]
Thanks for the feedback, we will address the comments.

Jean

**Comment by jeanfad** [comment]
Hi, 

1- Please, use the file referenced here, the snippets in the tutorial are meant to explain various aspects, but the final configuration file is the one to run: https://github.com/Microsoft/CNTK/wiki/Tutorial#putting-it-all-together 
2- fixed
3- it works both ways
4- could not reproduce the error, it run for me directly.

Thanks,
Jean

**Comment by baogorek** [comment]
FYI, here's the error message I get if I comment out the modelPath line in the config file:
EXCEPTION occurred: configparameters: required parameter missing: linreg.cntk:linregTrain:modelPath

I now understand the separation between the discussion in the earlier sections and the "putting it all together" section. Truth be told, I didn't make it all the way through the article before trying things out. I still think the safest bet is to keep the NDL blocks consistent throughout, or at least describe why something changed. But that's just my opinion.

It's a really good tutorial.

**Comment by baogorek** [comment]
Oh sorry I just noticed there is a modelPath specified in the final configuration file.
