### ISSUE TITLE
cpu only binary + compiler errors

### ISSUE THREAD

**Issue by ramankarthik15** [Microsoft/CNTK#53]
Hello,

I cannot find the CPU only binary in the binary downloads link
https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration

While compiling the source from scratch I observe type qualifier errors as:

In file included from Source/Common/Include/latticearchive.h(25),
                 from Source/SequenceTrainingLib/latticeforwardbackward.cpp(11):
Source/Common/Include/simplesenonehmm.h(294): error #858: type qualifier on return type is meaningless
      const size_t getnumsenone() const
.....

**Comment by frankseide** [comment]
That compiler message is certainly correct, I will fix this as part of the next commit I make—thanks!

However, we don’t see that error here, so you seem to be using a different compiler.

Could you share your compiler version? We use gcc 4.8.4.

**Comment by wolfma61** [comment]
@ramankarthik15 - the binary download issue is tracked in a different issue, could you repro with gcc 4.8.4?

**Comment by ramankarthik15** [comment]
GCC works fine. Type qualified errors were observed with non gcc compilers
