### ISSUE TITLE
Minus sign missing in Constant

### ISSUE THREAD

**Issue by HartmutMaennel** [Microsoft/CNTK#531]
If I use "factor = Constant(-2.0)" in a ndl file, the constant that is used is 2.0.
There is an easy workaround: It works correctly when adding a space between "Constant(" and the minus sign.

**Comment by frankseide** [comment]
Yikes. We are upgrading to a new parser for network descriptions. This kind of errors should not happen anymore then.

**Comment by mahilleb-msft** [comment]
Re-opening for now, so we can close when the new parser is merged,  or this behavior is documented in the Wiki.

**Comment by FreedMana** [comment]
Yes，i also found it before. As a workround, I often use Negate() to get the right value.

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
