### ISSUE TITLE
Getting wrong values on MNIST (02_Convolution)

### ISSUE THREAD

**Issue by maurelioredfox** [Microsoft/CNTK#532]
I'm trying to output the results of mnist, but i'm getting wrong values, and when I create and test the network I get an low error rate:

Final Results: Minibatch[1-625]: SamplesSeen = 10000    err: ErrorPrediction/Sample = 0.0086    ce: CrossEntropyWithSoftmax/Sample = 0.030831677    Perplexity = 1.0313119

but when I try to output values it's almost always wrong (usually 4 or 5), here's the code i'm using for output:

eval = [
    action = "write"
    minibatchSize = 16

```
NDLNetworkBuilder = [
    networkDescription = "$ConfigDir$/02_Convolution.ndl"
]

reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/eval.txt"
    randomize = "none"

    features = [
        dim = 784
        start = 0
    ]
]

outputPath = "$OutputDir$/result"     # Path to write to. ".NODENAME" will be appended.

format = [
    type = "category"
    labelMappingFile = "$DataDir$/labelsmap.txt"
]
```

]

I'm using CNTK 1.1, GPU enabled

here is the input i'm using, it contains some values from Test-28x28.txt
[eval.txt](https://github.com/Microsoft/CNTK/files/285637/eval.txt)

**Comment by sofeikov** [comment]
Try removing this line

```
NDLNetworkBuilder = [
    networkDescription = "$ConfigDir$/02_Convolution.ndl"
]
```

Did the trick for me
