### ISSUE TITLE
Crash if cannot open file during training

### ISSUE THREAD

**Issue by leonardoaraujosantos** [Microsoft/CNTK#533]
Hi guys I detect that cntk crash during training if somehow it cannot open a file on the mini-batch

Starting minibatch loop.
 Epoch[28 of 30]-Minibatch[   1- 500, 64.02%]: SamplesSeen = 32000; TrainLossPerSample =  0.07223191; EvalErr[0]PerSample = 0.02271875; TotalTime = 518.9356s; SamplesPerSecond = 61.7
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStackstd::runtime_error'
  what():  Cannot open file '/mnt/fs3/QA_analitics/Apical_CNN_training_data/hs/front/n/717578_f_a5.bmp'
Aborted (core dumped)

---

Build info: 

```
    Built time: Apr 25 2016 04:32:40
    Last modified date: Mon Apr 25 04:09:36 2016
    Build type: release
    Build target: GPU
    With 1bit-SGD: no
    Math lib: acml
    CUDA_PATH: /usr/local/cuda-7.5
    CUB_PATH: /usr/local/cub-1.4.1
    CUDNN_PATH: /usr/local/cudnn-4.0
    Build Branch: HEAD
    Build SHA1: 29c065ae7c1c370d8852c283d4e9f1a068ba2233
    Built by philly on f3f64d5eed9a
    Build Path: /home/philly/jenkins/workspace/CNTK-Build-Linux
```

The funny thing is that the file exist and can be opened manually

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
