### ISSUE TITLE
Memory Corruption in ImageReader

### ISSUE THREAD

**Issue by nslay** [Microsoft/CNTK#535]
I've been playing with CNTK using AlexNet modified to use a zip file database of png files. I've spent the entire day looking at a crash on Linux. I can't tell you specifically _where_ in the code the crash happens, but I can tell you that it happens in ImageTransformer when CNTK is creating mini batches (anything to do with resize). It seems to happen in OpenMP parallel sections. Setting `OMP_NUM_THREADS=1` will get it past the minibatch setup phase and start training. No backtrace is ever the same but always involves somewhere in the ImageTransformer portion of ImageReader.

Some things I looked at:

1. This was initially raising asserts in OpenCV `cv::resize` where `area()` was somehow 0 or negative. I tried using newer versions of libpng since the above problem can be caused by empty images. I thought maybe somehow images read from the zip file were erroneously returned as empty. Then I tried to enable `-DBUILD_PNG="ON"` in OpenCV to prevent any kind of problem with the numerous versions of libpng my system has. At some point here, item (1) stopped happening. I also tried OpenCV 3.1.0 which has the same exact problem.
2. `opal_memory_ptmalloc2_malloc` popped up a lot at the top of backtraces. I recompiled OpenMPI using `--without-memory-manager` since a possibly non-thread-safe memory allocator could cause any number of related problems. That restored GNU `malloc` as the global memory allocator for operator `new`. GNU `malloc` now prints out two obvious "memory corruption" messages on the console when running CNTK. Worth noting, that the OpenMPI `opal_memory_ptmalloc2_malloc` source code comments insists that it is thread-safe.
3. I ran CNTK through valgrind but it didn't catch the source of the memory corruption.

The same setup works on Windows.

I'm using all the same versions of software mentioned in the CNTK wiki with the exception of GCC which is 4.9.1.

**Comment by nslay** [comment]
Now, I think item (1) vanished because I did something silly and commented out 2-3 assert lines in `cv::resize`. I put those back.

I noticed that Dr.Memory now supports 64 bit applications. Last time I checked, it only supported 32 bit applications. I went ahead and ran the debug build of CNTK through Dr.Memory and it did manage to catch something that might be useful! To be fair to valgrind, I didn't realize valgrind's output might end up in the CNTK log file since it was printing out warnings like it normally does on stdout. I'm running valgrind again.

I also attached a CNTK run without any memory debugger. It triggers an assert in CNTK before even reaching OpenCV's asserts.

[AlexNet_Train_Test.log.NoMemoryChecker.txt](https://github.com/Microsoft/CNTK/files/291268/AlexNet_Train_Test.log.NoMemoryChecker.txt)
[AlexNet_Train_Test.log.drmemory3.txt](https://github.com/Microsoft/CNTK/files/291271/AlexNet_Train_Test.log.drmemory3.txt)

**Comment by eldakms** [comment]
Hi nslay,

It seems the clone function does not produce the contiguous memory, even though it states it does ...  http://docs.opencv.org/2.4/modules/core/doc/basic_structures.html?highlight=clone#mat-clone 

Could you please provide a small repro (your config and a couple of files that reproduce the crash)?
Thank you very much!

**Comment by nslay** [comment]
I can reproduce the crash with the 03_ResNet.cntk example found here:
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Miscellaneous/CIFAR-10

**Comment by nslay** [comment]
Attached are my configuration files. I took them from ImageNet example folder and modified them a little. Unfortunately, I'm not sure if I can share my data. 

A little about my data:
I used zlib/contrib/minizip library to store png-compressed RGB image patches in a zip file. All the patches were resampled to be 224x224 to match AlexNet's input size.
I used 7-zip to verify that I can access the archive and look at files. CNTK on Windows seems to work just fine with my archive. 

[AlexNet.cntk.txt](https://github.com/Microsoft/CNTK/files/293897/AlexNet.cntk.txt)
[AlexNet.ndl.txt](https://github.com/Microsoft/CNTK/files/293898/AlexNet.ndl.txt)

Thanks for looking at this issue.

I sought our other examples that use ImageReader to see if they crash. As noted above, 03_ResNet.cntk crashes with the same "memory corruption" messages from GNU `malloc`.

**Comment by eldakms** [comment]
We run 03_ResNet.cntk example as part of our continuous build both for Linux and Windows and have not seen this crash before.

I'm still trying to reproduce it. I changed the assert to an explicit exception in case when the buffer is not continuous, but it never fires for me. I will do full profile on our tests.
Thank you!

**Comment by nslay** [comment]
Thanks for your continued investigation.

I am currently building GCC 4.8.5 to see if that's any different than 4.9.1. ImageReader is filled with lots of moving and I remember reading some other CNTK issues were CNTK developers noted that buggy move semantics can cause a lot of problems.

Why 4.8? CUDA 7.5 doesn't like GCC 5.x. And GCC 4.7 can't build CNTK. Hopefully 4.8 will do the trick.

**Comment by nslay** [comment]
03_ResNet.cntk works with GCC 4.8.5.

That's good for me, bad for maintainers. We still don't know why CNTK was crashing.

That could mean a couple things:
* There is a bug in GCC 4.9.1
* CNTK code using C++11 features is not completely C++11 compliant (Could be due to potentially incomplete/buggy C++11 support in GCC 4.8).

**Comment by eldakms** [comment]
There could be a problem if your OpenCV compiled with a different version of compiler from CNTK. 
When we switch to 4.9.1 we will run extensive tests. I'm closing the issue for now.

**Comment by nslay** [comment]
Every package was compiled with the same compiler.

**Comment by nslay** [comment]
Oh I misread. Fair enough.

Hey thanks a lot for looking at this! Let me know if you need any help isolating this problem in the future.

Hopefully you'll be able to migrate to 5.x with CUDA 8.

**Comment by eldakms** [comment]
Thanks!
