### ISSUE TITLE
Exception when training big data

### ISSUE THREAD

**Issue by FreedMana** [Microsoft/CNTK#536]
Hi everyone.  I try use cntk to train a regression DNN with 100h data.  In case of memory lack, i set randomized = 1728000. 
Now it always fails after one epoch, the error is : 
"EXCEPTION occurred: requirerandomizedchunk: requested utterance outside in-memory chunk range".

Is it still a memory problem? Or are there some parameters related to this?Thanks!!

**Comment by eldakms** [comment]
Could you please provide your config/log? are you using HTKMLFReader?
Thank you!

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
