### ISSUE TITLE
Write command only gives first column of parameters

### ISSUE THREAD

**Issue by HartmutMaennel** [Microsoft/CNTK#537]
Example:
Remove .txt from Net{.cntk, .ndl}.txt, run

mkdir Models
cntk configFile=Net.cntk

The file write_output.w1 correctly shows a [4,1] matrix w1, but write_output.w2 only shows the first column of the [2,4] matrix  w2.
Similar for the [1,2] constant in write_output.c.
An easy workaround is to inspect the parameters with the dumpnode command instead, but maybe it would be better to either output the full matrix with write or to disable write for parameters/constants to avoid confusion.

[Net.ndl.txt](https://github.com/Microsoft/CNTK/files/288581/Net.ndl.txt)
[Net.cntk.txt](https://github.com/Microsoft/CNTK/files/288582/Net.cntk.txt)
[data.txt](https://github.com/Microsoft/CNTK/files/288583/data.txt)

**Comment by Henry-White** [comment]
I've got the same issue (https://github.com/Microsoft/CNTK/issues/495).

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
