### ISSUE TITLE
Don't understand what is happening here

### ISSUE THREAD

**Issue by Klaminite** [Microsoft/CNTK#538]
1>------ Build started: Project: MathCUDA, Configuration: Debug x64 ------
2>------ Build started: Project: Common, Configuration: Debug x64 ------
3>------ Build started: Project: ActionsLib, Configuration: Debug x64 ------
4>------ Build started: Project: SequenceTrainingLib, Configuration: Debug x64 ------
1>C:\Users\PotatoeVsFish\Source\Repos\cntk\Source\Math\MathCUDA.vcxproj(198,5): error : CNTK requires the NVIDIA CUB library to build. Please see https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#cuda for installation instructions.
5>------ Build started: Project: ComputationNetworkLib, Configuration: Debug x64 ------
5>  stdafx.cpp
2>  TimerUtility.cpp
3>  TrainActions.cpp
5>  SpecialPurposeNodes.cpp
4>  parallelforwardbackward.cpp
2>  MPIWrapper.cpp
2>  fileutil.cpp
4>  latticeNoGPU.cpp
4>  latticeforwardbackward.cpp
2>  File.cpp
5>  ReshapingNodes.cpp
2>  ExceptionWithCallStack.cpp
4>  Generating Code...
4>  SequenceTrainingLib.vcxproj -> C:\Users\PotatoeVsFish\Source\Repos\cntk\x64\Debug\SequenceTrainingLib.lib
2>  Eval.cpp
6>------ Build started: Project: SGDLib, Configuration: Debug x64 ------
5>  InputAndParamNodes.cpp
3>  NDLNetworkBuilder.cpp
6>  stdafx.cpp
6>  SGD.cpp
2>  DataWriter.cpp
5>  ComputationNodeScripting.cpp
2>  DataReader.cpp
6>SGD.cpp(14): fatal error C1083: Cannot open include file: 'AllReduceDistGradAggregator.h': No such file or directory
6>  Profiler.cpp
6>  Generating Code...
7>------ Build started: Project: ReaderLib, Configuration: Debug x64 ------
2>  Config.cpp
2>  Generating Code...
5>  ComputationNode.cpp
7>  TruncatedBpttPacker.cpp
7>  SequenceRandomizer.cpp
3>  OtherActions.cpp
7>  SequencePacker.cpp
2>  Common.vcxproj -> C:\Users\PotatoeVsFish\Source\Repos\cntk\x64\Debug\Common.lib
8>------ Build started: Project: Math, Configuration: Debug x64 ------
8>  stdafx.cpp
8>  BatchNormalizationEngine.cpp
8>  ConvolutionEngine.cpp
8>  CPURNGHandle.cpp
8>  CPUSparseMatrix.cpp
5>  ComputationNetworkScripting.cpp
8>CPUSparseMatrix.cpp(33): fatal error C1083: Cannot open include file: 'acml.h': No such file or directory
8>  CUDAPageLockedMemAllocator.cpp
7>  ReaderShim.cpp
3>  EvalActions.cpp
7>  FramePacker.cpp
7>  PackerBase.cpp
8>  CPUMatrix.cpp
7>  BlockRandomizer.cpp
5>  ComputationNetworkEvaluation.cpp
8>  MatrixQuantizerCPU.cpp
8>  MatrixQuantizerImpl.cpp
7>  NoRandomizer.cpp
3>  SpecialPurposeActions.cpp
8>CPUMatrix.cpp(44): fatal error C1083: Cannot open include file: 'acml.h': No such file or directory
8>  NoGPU.cpp
8>  Matrix.cpp
7>  ChunkRandomizer.cpp
5>  ComputationNetworkEditing.cpp
7>  ChunkCache.cpp
3>  SimpleNetworkBuilder.cpp
8>  QuantizedMatrix.cpp
7>  Bundler.cpp
8>  RNGHandle.cpp
8>  TensorView.cpp
5>  ComputationNetworkBuilder.cpp
7>  Generating Code...
3>  NetworkFactory.cpp
7>  ReaderLib.vcxproj -> C:\Users\PotatoeVsFish\Source\Repos\cntk\x64\Debug\ReaderLib.lib
3>  NetworkDescriptionLanguage.cpp
5>  ComputationNetworkAnalysis.cpp
3>  Generating Code...
5>  ComputationNetwork.cpp
5>  BestGpu.cpp
5>  Generating Code...
3>  ActionsLib.vcxproj -> C:\Users\PotatoeVsFish\Source\Repos\cntk\x64\Debug\ActionsLib.lib
5>  ComputationNetworkLib.vcxproj -> C:\Users\PotatoeVsFish\Source\Repos\cntk\x64\Debug\ComputationNetworkLib.lib
9>------ Build started: Project: CNTK, Configuration: Debug x64 ------
9>          1 file(s) moved.
9>  tests.cpp
9>  stdafx.cpp
9>  ModelEditLanguage.cpp
9>  CNTK.cpp
9>  BrainScriptTest.cpp
9>  BrainScriptParser.cpp
9>  BrainScriptEvaluator.cpp
9>  Generating Code...
9>LINK : fatal error LNK1104: cannot open file 'SGDLib.lib'
========== Build: 5 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========

I'm really excited but at the same time frustrated because I want to start developing my own A.I. using this. *sadface*

Any help is much appreciated.

**Comment by mahilleb-msft** [comment]
@Klaminite, can you follow the setup procedure documented here:
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows
If you want to use 1Bit-SGD, also see this page:
https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD

From your build log, I can see that you're trying to do a GPU build with 1Bit-SGD, but several build dependencies aren't found yet:
ACML, NVidia CUB, and the header for 1Bit-SGD.

Also, make sure that Visual Studio sees the environment variable you set up pointing to the build dependencies by restarting VS, or sign out and signing in again.

Best, Mark

**Comment by mahilleb-msft** [comment]
@Klaminite: I'm closing the issue here, assuming things are working now.

Thanks, Mark
