### ISSUE TITLE
Error when running CIFAR-10 example

### ISSUE THREAD

**Issue by kaishijeng** [Microsoft/CNTK#54]
I use the following command to download CIFAR-10 dataset
      python CIFAR_convert.py  

Then issue the following command to run it

 cntk configFile=01_Conv.config configName=01_Conv

However there is an error from log below which complains labelsmap.txt can't be found. How do you create labelsmap.txt?

<<<<<<<<<<<<<<<<<<<< PROCESSED CONFIG WITH ALL VARIABLES RESOLVED <<<<<<<<<<<<<<<<<<<<
command: Train Test 
precision = float
CNTKModelPath: ./Output/Models/01_Convolution
CNTKCommandTrainInfo: Train : 30
CNTKCommandTrainInfo: CNTKNoMoreCommands_Total : 30
CNTKCommandTrainBegin: Train
NDLBuilder Using CPU
Reading UCI file ./Train.txt

[CALL STACK]
  /home/fc/src/CNTK/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::PrintCallStack()  + 0xbf  )  [0x7f178c7c90ff]
  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::runtime_error>(char const*, ...)  + 0xdd  )  [0x43332d]
  /home/fc/src/CNTK/bin/../lib/UCIFastReader.so ( void Microsoft::MSR::CNTK::UCIFastReader<float>::InitFromConfig<Microsoft::MSR::CNTK::ConfigParameters>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0xfed )  [0x7f1787b9813d]
  /home/fc/src/CNTK/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DataReader<float>::DataReader<Microsoft::MSR::CNTK::ConfigParameters>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x48e )  [0x7f178c7c101e]
  cntk                           (                                                   )  [0x6436b1]
  cntk                           (                                                   )  [0x648470]
  cntk                           (                                                   )  [0x48a9ec]
  cntk                           (                                                   )  [0x42cd99]
  cntk                           (                                                   )  [0x42d3e8]
  cntk                           (                                                   )  [0x421288]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf5  )  [0x7f178b528ec5]
  cntk                           (                                                   )  [0x424e07]
EXCEPTION occurred: label mapping file ./labelsmap.txt not found, can be created with a 'createLabelMap' command/action

**Comment by Alexey-Kamenev** [comment]
Hello,
labelsmap.txt contains mapping between the labels in the data file and 0-based class id. Using createLabelMap is one option, however, in that particular case of CIFAR-10, it's easier to just copy the file from Examples\Image\MNIST\Data\labelsmap.txt as both MNIST and CIFAR-10 have the same number of classes. I'll add the file to the repo.

**Comment by amyrebullar** [comment]
Email.activeted

**Comment by amyrebullar** [comment]
Activeted my maps in basic

**Comment by kaishijeng** [comment]
I will try it.

Thanks

**Comment by wolfma61** [comment]
@kaishijeng - are there outstanding issue?

thx
Wolfgang
