### ISSUE TITLE
calling EvallDll without a file path

### ISSUE THREAD

**Issue by julienlopez** [Microsoft/CNTK#540]
Hi,

I'm using the EvallDll to run a CNTK network in my C++ program.

The problem is that currently I have to create the network with a file path, but I'd like to avoid providing the network file as is with my executable.

Is there a way to accomplish this? Like creating the network with the raw data, so that I can decouple loading and creating the network.

**Comment by gaizkan** [comment]
Hi julienlopez,

You don't have to provide a file path to CreateNetwork, you can also provide the configuration itself. If you look at the CSEvalClient in `EvaluateNetworkSingleLayerNoInput` (although in C#, it is the same for C++), it loads the *content* of the file (which contains the network definition) and passes that as a string to CreateNetwork. 

Let me know if this addresses your question.

Gaizka

**Comment by julienlopez** [comment]
Ok, I'll give it a try, but does this only work with cntk text files? Is it possible to feed it trained binary files?

**Comment by gaizkan** [comment]
The CreateNetwork will work with network definition files (text files), but not with the deserialized binary model.
Currently there is no public interface available for passing the model's file content (serialized model) to the evaluation interface.

Would you elaborate on the need to decouple the model loading from the evaluation engine?

Gaizka

**Comment by julienlopez** [comment]
Well, the idea would be be to be able to use stored trained model (either directly in the exe file, or retrieving them from a server) without having to write temporary files.

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
