### ISSUE TITLE
somthing about SLU  example 

### ISSUE THREAD

**Issue by esun-w** [Microsoft/CNTK#541]
i  am trying the SLU example, with my own data and setting.
the cntk configfile is just as follows:

precision="float"
deviceId = 0
command=LSTMTest
traceLevel=1
stderr=tt.txt
wordContext=-2:  -1  :  0

modelPath=$ExpDir$/cntkdebug.dnn

LSTMTrain=[
    action=train
    makeMode=false
    SimpleNetworkBuilder=[
        rnnType=LSTM

```
    layerSizes=12117:50:300:300:5

    lookupTableOrder=3
    recurrentLayer=2:3:4
    defaultHiddenActivity = 0.1
    trainingCriterion=crossentropywithsoftmax
    evalCriterion=crossentropywithsoftmax
]


SGD=[

    maxEpochs=20   #00
    learningRatesPerSample=0.1
]

reader=[

    readerType=LUSequenceReader
    nbruttsineachrecurrentiter=10    #this specifies using maximum of 10 sentences for each minibatch.
    file=$DataDir$/train4crf.txt
    unk="<unk>"

      features=[
        dim=0
      ]

      labelIn=[
        labelType=Category
        beginSequence="BOS"
        endSequence="EOS"

        token=$DataDir$/input.txt
      ]
      labels=[
        labelType=Category

        token=$DataDir$/output.txt
      ]
]
```

]

topoplot = [
    action = "plot"
    outputdotFile = "$ExpDir$/lstm.model.dot" 

```
outputFile="$ExpDir$/lstm.model.jpg" 

renderCmd="dot.exe -Tjpg <IN> -o<OUT>"
```

]

LSTMTest=[
    action=write

```
epochSize=0
recurrentLayer=2:3:4
defaultHiddenActivity=0.1
outputNodeNames=outputs:labels

reader=[
  readerType=LUSequenceReader

  file=$DataDir$/test4crf_video.txt

  features=[
    dim=0 
  ]
  labelIn=[
    labelType=Category
    beginSequence="BOS"
    endSequence="EOS"
    token=$DataDir$/input.txt
  ]
  labels=[
    labelType=Category
    token=$DataDir$/output.txt
  ]
]

writer=[
    writerType=LUSequenceWriter

    outputs=[
        file=$OutDir$/output.rec.txt
        token=$DataDir$/output.txt
    ]
    labels=[
        file=$OutDir$/output.lbl.txt
        token=$DataDir$/output.txt
    ]
]
```

]

i want to do sequence lebleing task, but my output is strange, some log is just as follows:
0000000015283650: {[AutoName57 Value[300 x 1 x *1]] }
00000000152836F0: {[AutoName66 Value[300 x 1 x *1]] }
0000000015283790: {[AutoName67 Value[300 x 1 x *1]] }
0000000015283830: {[AutoName72 Value[300 x 1 x *1]] }
00000000152838D0: {[AutoName73 Value[300 x 1 x *1]] }
0000000015283970: {[AutoName74 Value[300 x 1 x *1]] }
0000000015283A10: {[AutoName75 Value[300 x 1 x *1]] }

BatchLUSequenceParser: Parsing input data...
BatchLUSequenceParser: Parsed 2 lines with a total of 22+2 tokens.
S S S S S S S B M M E S 
O O O O O O O O O O O O 
S S S S S S S B M M E 
O O O O O O O O O O O 
BatchLUSequenceParser: Parsing input data...
BatchLUSequenceParser: Parsed 0 lines with a total of 0+0 tokens.
EnsureDataAvailable: No more data.
Total Samples Evaluated = 23

Action "write" complete.

**COMPLETED**

the output file:
O O O O O O O O O O O O 
O O O O O O O O O O O 

the lebel file:
S S S S S S S B M M E S 
S S S S S S S B M M E S
i do not hnow why the output is "O O O O O O O O O O O O"  and   "O O O O O O O O O O O" , i think the output is total wrong, which is not as i expect, anyone can explain why?
this is SLU exmaple, 

thanks

**Comment by wolfma61** [comment]
The issue has been dormant for a long while and CNTK improved significantly since then. Please open a new issue if you still experience problems in the latest release.
