### ISSUE TITLE
rnn.cntk

### ISSUE THREAD

**Issue by uredkar** [Microsoft/CNTK#545]
I am getting the following errors, while runing cntk\Examples\Text\PennTreebank.
Output dir has models and Write.TrainNodeClassBasedCrossEntropy. Not sure what this example is showing? Some details on what the expected output will help me. 
Thanks in advance

LMSequenceReader: Label mapping will be created internally on the fly because the labelMappingFile was not found: ../Output/sentenceLabels.txt
LMSequenceReader: Label mapping will be created internally on the fly because the labelMappingFile was not found: ../Output/sentenceLabels.out.txt

**Comment by mahilleb-msft** [comment]
I believe this to be a warning type message only. Could you let us know what the actual error is you're running into / and which configuration?
(Please note our updated lists of samples here - https://www.microsoft.com/en-us/cognitive-toolkit/features/model-gallery/. [LMSequenceReader](https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-LM-Sequence-Reader) is being deprecated.)

Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
