### ISSUE TITLE
New version of CNTK can't find zlib.dll when using ImageReader for training, old version could

### ISSUE THREAD

**Issue by LowerySJ** [Microsoft/CNTK#549]
Hello. With an older version of CNTK, I have been able to call CNTK from the command prompt to run .cntk config files that use the ImageReader reader successfully. For example, I have been able to train and use the 03_ResNet.cntk example provided for CIFAR-10. With the most recent version of CNTK pulled from github and freshly built, I am not able to do this. When I run

cntk configFile=03_ResNet.cntk

I get the following message:

> The program can't start because zlib.dll is missing from your computer. Try reinstalling the program to fix this problem. <

I have not altered the environmental variable ZLIB_PATH or the zip folder in any way. I set up the environmental variables according to the [wiki page](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-your-machine). Moreover, using the older version of CNTK (which I have in a separate folder and have not touched) I am still able to call .cntk files that use ImageReader successfully, so it seems like there is nothing is wrong with the zlib.dll files..

Also, no other programs are using zlib.

Could you guys please recommend anything?

**Comment by Alexey-Kamenev** [comment]
Hi Stephen,
Can you please verify what is the name of the zlib DLL? Is it zlib.dll or zlib**1**.dll? If the former then try renaming it to the latter and try again.

**Comment by LowerySJ** [comment]
Alexey, thanks for the fast response. The problem was on my end though.

For those who might look this up later:

The zlib DLL was named correctly. The problem was that when I was running CNTK from the command prompt, I was accidentally replacing the path environment variable with the CNTK directory, rather than appending the CNTK directory or just calling it with the full file path.
