### ISSUE TITLE
Tutorial 2 Issues

### ISSUE THREAD

**Issue by baogorek** [Microsoft/CNTK#551]
There are major issues impacting the ability to follow [Tutorial 2 on the wiki](https://github.com/Microsoft/CNTK/wiki/Tutorial2):
1. **Broken links**
   - "The network definition" ("Putting it all Together" section)
   - "The macros" ("Putting it all Together" section)
   - The file "Shared.bs" ("The Network Definition" section)
2. **Problems downloading the data**
   - The python script to get the data didn't work for me without downloading [uci_to_cntk_text_format_converter.py](https://github.com/Microsoft/CNTK/blob/master/Source/Readers/CNTKTextFormatReader/uci_to_cntk_text_format_converter.py) separately.
   - The directories are hard-coded and I ended up having to run the code line by line with custom changes.
3. **Instructions flip between BrainScript and NDL**
   - BrainScript and NDL language compete with each other throughout the article. In section "The Network Definition", the reader is directed to the BrainScript file "Shared.bs" (via a broken link), but in the code directly below the reader sees "# DNNSigmoidLayer and DNNLayer are defined in Macros.ndl." Of course, Macros.ndl uses NDL and is linked to later in the article.
   - To make things more confusing, I read on the [BrainScript page](https://github.com/Microsoft/CNTK/wiki/BrainScript-Network-Builder) that "NDLNetworkBuilder is now deprecated."

**Comment by frankseide** [comment]
My bad, will be fixed first thing Monday morning.

**Comment by esun-w** [comment]
do you have a Complete example about SLU？ my example about SLU is always wrong, but the example here is not complete. thanks a lot

**Comment by esun-w** [comment]
do you have a Complete example about SLU？ my example about SLU is always wrong, but the example here is not complete. thanks a lot  @frankseide

**Comment by quicktrick** [comment]
@frankseide, please, give more description on model editing in BrainScript. Thanks in advance!

**Comment by mahilleb-msft** [comment]
wrt Model Editing, please check out https://docs.microsoft.com/en-us/cognitive-toolkit/BrainScript-Model-Editing.
Also, our full list of examples is now available at https://www.microsoft.com/en-us/cognitive-toolkit/features/model-gallery/.

**Comment by mahilleb-msft** [comment]
(I believe Tutorial2 has been retired since the issue was posted - @sayanpa - what would be the best replacement - in Python / in BrainScript?)

**Comment by sayanpa** [comment]
All our tutorials are located under CNTK/Tutorials. CNTK 202/204 are recommended Language/Text related tutorials. Our recommendation is to move to the Python API that are maintained.

There is a SLU Hands on tutorials using BrainScript, that is slated to be deprecated. Closing this issue given it was asked over a year ago, please open a new one for additional information.
