### ISSUE TITLE
SLU EXAMPLE

### ISSUE THREAD

**Issue by esun0087** [Microsoft/CNTK#553]
when i see baseline.windows.cpu.txt; 
the path is Tests\EndToEndTests\Text\SLU
the output is 
BatchLUSequenceParser: Parsing input data...
BatchLUSequenceParser: Parsed 5 lines with a total of 92+5 tokens.
O O O O O O O O O O O O O O O O O O O O O 
O O O O O O O O O O O O O O O O O O 
O O O O O O O O O O O O O O O 
O O O O O O O O O O O O O O O O O O 
O O O O O O O O O O O O O O O O O O O 
BatchLUSequenceParser: Parsing input data...
BatchLUSequenceParser: Parsed 0 lines with a total of 0+0 tokens.
EnsureDataAvailable: No more data.
Total Samples Evaluated = 91

why the output label is the same??????
can any one tell me ?

**Comment by esun0087** [comment]
@mahilleb-msft can you give a good example for SLU ? 
thanks a lot

**Comment by mahilleb-msft** [comment]
Would you mind checking out our example list at https://www.microsoft.com/en-us/cognitive-toolkit/features/model-gallery/ ? Many have been added within the last year. Please let us know if you're still looking for a specific example.

Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
