### ISSUE TITLE
Problem using BlockMomentumSGD

### ISSUE THREAD

**Issue by jaurora** [Microsoft/CNTK#555]
Hello,

I am running CNTK with BlockMomentumSGD on 1 GPU, and got an error message “About to throw exception 'BlockMomentumSGD is not enabled in this version.” The CNTK is 1bitSGD enabled.

The error seems “CNTK_PARALLEL_TRAINING_SUPPORT” was not defined (from SGD.cpp):

```
    if (configParallelTrain.Exists(L"BlockMomentumSGD"))
    {
```
# ifndef CNTK_PARALLEL_TRAINING_SUPPORT

```
        InvalidArgument("BlockMomentumSGD is not enabled in this version.\n");
```

Could anyone help?

Thanks,
Jie

**Comment by yqwangustc** [comment]
Hi, 

Are you building CNTK for Linux and Windows ? 

Would you kindly check whether the environment variable CNTK_ENABLE_1BitSGD has been set to true ? (more details see https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD )  

Thanks,
Yongqiang

**Comment by jaurora** [comment]
I am building CNTK on Windows. The environment variable
CNTK_ENABLE_1BitSGD has been set to true.

Thanks,
Jie

On Mon, Jun 6, 2016 at 4:15 PM, Yongqiang Wang <notifications@github.com>
wrote:

> Hi,
>
> Are you building CNTK for Linux and Windows ?
>
> Would you kindly check whether the environment variable
> CNTK_ENABLE_1BitSGD has been set to true ? (more details see
> https://github.com/Microsoft/CNTK/wiki/Enabling-1bit-SGD )
>
> Thanks,
> Yongqiang
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/CNTK/issues/555#issuecomment-224117176>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGLM46nugfYisyD3-87PPwlFFhjlaN_iks5qJKolgaJpZM4IvYpl>
> .
>



-- 
Jie Zhu
PhD Candidate
Climate and Space Sciences and Engineering
University of Michigan

**Comment by mahilleb-msft** [comment]
Please make sure that your VS instance sees %CNTK_ENABLE_1BitSGD% being set to true. If in doubt, close VS and restart it. If it still doesn't work, would you let us know your VS version and commit you're on? [Potentially also try with VS2015.3 and latest master].

Thanks, Mark

**Comment by mahilleb-msft** [comment]
Closing, please feel to re-open or file a new issue, if this issue persists for you. Thanks!
