### ISSUE TITLE
EvalDll Linux support is missing

### ISSUE THREAD

**Issue by nslay** [Microsoft/CNTK#556]
Actually, this issue could be two smaller issues:
1) Where Visual Studio generates nice neat .lib files used for linking everything, the Linux Makefiles glue a bunch of object files together when linking. The Linux build could be made to generate .a files much like the Visual Studio build and then use that to link cntk and EvalDll.
2) If you do manage to take care of (1), EvalDll does not cleanly compile on Linux due to a missing include somewhere (Basics.h) and C++ standard violations that Visual Studio has always ignored: Using members of a templated parent class with unresolved template arguments.

Of course, (2) could bypass (1) and just link everything like it does the cntk binary. I chose to solve (1) since it seems easier to `ar` everything up in the .build directory thanks to the .build directory's hierarchical structure. That's not exactly the same though since I don't have separate `Math.a` and `MathCUDA.a` for example. But it works. Then I made EvalDll an external CMake project that would link `libEvalDll.so`. This is ugly since I had to tell CMake to also link it with MPI, CUDA, OpenCV, etc... even though I don't directly use those dependencies in my work.

My solution exists outside of CNTK aside of the source modifications in EvalDll. If given a little time, I could update `Makefile` and/or `configure` to do this and request a merge.

**Comment by gaizkan** [comment]
Hi nslay,

I will be looking at making an EvalDLL library for Linux (along with tests and examples) in the near future. I do encourage you to continue and submit a pull request.

**Comment by mahilleb-msft** [comment]
There's now also evaluation for Linux, please check out https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Evaluation-Overview.
