### ISSUE TITLE
Question of using CNTKTextFormatReader

### ISSUE THREAD

**Issue by wrluo** [Microsoft/CNTK#557]
Hi,

I am new to CNTK and meet some difficulties when I organizing my data. So I come to see if someone can help me.

In my part, I have a bunch of sequential data, each line represent a period. X represents features and Y represents labels. For example,
According the first period information |X 1 2 3, I will get the label |Y 4 5 6
According the first two periods information 
|X 1 2 3
|X 7 8 9
I will get the label |Y 10 11 12.

In such condition, should I organize the txt file in the following way when using CNTKTextFormatReader?
0 |X 1 2 3 |Y 4 5 6
 |X 7 8 9 |Y 10 11 12
 |X ... |Y ...
 ...

Looking forward for your help~

**Comment by raaaar** [comment]
I'm a little confused as to how many X's and Y's you have in each period. Assuming there's one feature sample and one label for each period, you input can look something like this:

```
1 |X 1 2 3 |Y 4 5 6
2 |X 7 8 9 |Y 10 11 12
3 |X ... |Y ...
```
Or, equivalently (dropping the sequence id prefixes):
```
|X 1 2 3 |Y 4 5 6
|X 7 8 9 |Y 10 11 12
|X ... |Y ...
```
In both these snippets, each line would be interpreted as a separate sequence.

**Comment by wrluo** [comment]
@raaaar thank you for your help! 

Actually I only have one X and Y in each period.

For the sequence, I would like to regard every 240 periods(lines) as one sequence. So my txt file looks like

0 |X 1 2 3 |Y 4 5 6
 |X 7 8 9 |Y 10 11 12
 |X . . . |Y . . .
. . .
1 |X . . . |Y . . .
 |X . . . |Y . . .
 |X . . . |Y . . .
. . .

I want to use every sequence to train the network as an online learning process. 
For example, let's take the first sequence above. At first, I want to give first period's feature X| 1 2 3 to network and make a prediction. Compare prediction with label |Y 4 5 6 and update network's parameters. 
Then suppose network has the memory of the first period (I am not sure if CNTK will do this), I give the network with second period's information |X 7 8 9 and make a prediction. But this time network give prediction according to the first two periods' information. Again compare prediction with label |Y 10 11 12 and update network's parameters. 
Until the last period of such sequence.

Then use another sequence to train the network again.

Any idea about how to organize the txt file?

**Comment by cmarschner** [comment]
You should just prefix every line with the sequence ID
0 |X 1 2 3 |Y 4 5 6
0 |X 7 8 9 |Y 10 11 12
0 |X . . . |Y . . .
0 . . .
1 |X . . . |Y . . .
1  |X . . . |Y . . .
1 |X . . . |Y . .
...

**Comment by mahilleb-msft** [comment]
Closing; please re-open if the answer isn't sufficient for you.
