### ISSUE TITLE
regression task fail in test and write

### ISSUE THREAD

**Issue by yeli7289** [Microsoft/CNTK#559]
I am trying to do speech enhancement with DNN, my input feature size are 440 and so does my output size 440. I use a 3 layers dnn to train it. My problem happens at the testing procedure.
This is the error message, I have no idea why this occur.

```
starting epoch 0 at record count 0, and file position 0
already there from last epoch
CNTK: Caught Win32 exception 0xc0000094: Integer division by zero.
```

and when I write out the estimated value of the testing data, i got a bunch of zero...
Do anyone got the same error?

This is my config file

```
command = train:test:write
precision = "float"
modelPath = "$ModelDir$/SE.dnn"
ndlMacros = "$ConfigDir$/Macros.ndl"
stderr = "$OutputDir$/dnn01_out"
traceLevel=1
numMBsToShowResult=500

train = [
    action = "train"

    NDLNetworkBuilder = [
        networkDescription = "$ConfigDir$/dnn.ndl"
    ]

    SGD = [
        epochSize = 0
        minibatchSize = 32
        learningRatesPerMB = 0.1
        momentumPerMB = 0
        maxEpochs = 100
    ]

    # Note: this reader crashes if randomization is turned on.
    reader = [
        readerType = "UCIFastReader"
        # training file
        file = "$DataDir$/Train.txt"

        features = [
            dim = 440
            start = 0
        ]

        labels = [
            dim = 440
            start = 440
            labelType = "regression"
        ]
    ]    
]

test = [
    action = "test"
    minibatchSize = 16

    reader = [
        readerType = "UCIFastReader"
        file = "$DataDir$/Test.txt"

        features = [
            dim = 30
            start = 0
        ]

        labels = [
            dim = 30
            start = 20
            labelType = "regression"
        ]
    ]    
]
```

My dnn.ndl file

```
run = DNN

DNN = [
    IDim = 440
    HDim = 1024
    ODim = 440

    features= InputValue(IDim)
    labels = InputValue(ODim)

    # DNNSigmoidLayer and DNNLayer are defined in Macros.ndl
    h1 = DNNSigmoidLayer(IDim, HDim, features)
    h2 = DNNSigmoidLayer(HDim, HDim, h1)
    h3 = DNNSigmoidLayer(HDim, HDim, h2)
    o = DNNLayer(HDim, ODim, h3)

    ER = SquareError(labels, o)
    err = SquareError(labels, o)


    # Special Nodes
    FeatureNodes = (features)
    LabelNodes = (labels)
    CriteriaNodes = (ER)
    EvalNodes = (err)
    OutputNodes = (o)
]
`
```

**Comment by CPostelnicu** [comment]
Your input file may be malformed. At least this was the problem in my case. 

See this also: https://github.com/Microsoft/CNTK/issues/292

**Comment by yeli7289** [comment]
[https://drive.google.com/open?id=0Bwutiof-2na6Wks2OXFTNGx1SHM](url)

**Comment by yeli7289** [comment]
![image](https://cloud.githubusercontent.com/assets/14809576/16012882/597a283c-3159-11e6-8c8a-0fff155d8a5a.png)

**Comment by yeli7289** [comment]
This is my training data. Each line represents a data, first 5 are input and last 5 are output/
![image](https://cloud.githubusercontent.com/assets/14809576/16012914/7d1b248a-3159-11e6-8ce7-db657f461f68.png)

This is my testing.

![image](https://cloud.githubusercontent.com/assets/14809576/16012941/9ab97622-3159-11e6-80d7-d4625c7f1604.png)

Are these wrong?

**Comment by CPostelnicu** [comment]
You need to specify features and labels.
Check this:
https://github.com/Microsoft/CNTK/wiki/UCI-Fast-Reader
"notice two sub-blocks named features and labels. These names are used by the data readers to match the computation node in your network and the data loaded from the files. If simple network builders are used to create your network, features and labels are the standard names of the feature and label nodes, respectively. If you defined your network using the NDL network builder you need to make sure these names matches the corresponding nodes in your network."

Here they don't specify a schema for UCIFastReader. I guess it should be similar to CNTKTextFormatReader (that I was using). In short:  try to add something like

```
 |features 100:3 123:4 |labels 8 |features 0 1 2 3 4 5 6 7 8 9
|labels 0 1.1 22 0.3 14 54 0.06 0.7 1.8 9.9 |features 123917 |labels 1134:1.911 13331:0.014
```

...and so on.

Check here the details: https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader 

I have no idea if this will work for UCIFastReader. Try to find the schema for that one.

**Comment by yeli7289** [comment]
Thanks @CPostelnicu, I think i have found out the problem, ''/r/n" instead of "/n".
This representation should works too.
Thank you

**Comment by frankseide** [comment]
Could you let us know which file needed to be changed to/from \r\n vs. \n? We should fix that code to accept both.
