### ISSUE TITLE
The issue with several 2D inputs has still not been resolved

### ISSUE THREAD

**Issue by bulatGH** [Microsoft/CNTK#561]
I downloaded the new CNTK 1.5 binaries and found out that the issue with several 2D inputs has not been yet resolved.

As an example, I have the following in my network properties:

"ndlInputMacros = [
    imageW = 27
    imageH = 27
    labelDim = 2

```
features1 = ImageInput(imageW, imageH, 1, imageLayout=$imageLayout$)
features2 = ImageInput(imageW, imageH, 1, imageLayout=$imageLayout$)
```

....
FeatureNodes = (features1, features2)"

But I got the error "features2 InputValue operation had its row dimension 729 changed by the reader to 27"

Although, I circumvented this issue using some internal reshaping, it would be very good to have an opportunity to use several 2D images as input.

**Comment by zhouwangzw** [comment]
Could you please try with the latest CNTK release? CNTK has been intensively developed and extended in the last year, and the CNTK V2 API gives your more flexibility to control how to feed data. If you still run into problems, please open an new issue.
