### ISSUE TITLE
ndl file debug

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#563]
Hello

I have a general question on how to debug ndl network builder. When network gets complicated, I want to check intput/output/hidden layers sizes from time to time (or any other internal parameter). Is there any convenient way to accomplish this in CNTK?

**Comment by frankseide** [comment]
The dimensions of the layers can be gotten from the validation output. Is that what you are looking for?

**Comment by funguy74** [comment]
Do you mean log file for CNTK running?  If all the necessary information on ndl results can be checked on this (including error messages), it would be fine. I'm trying to figure out what would be efficient way to debug networks generated from ndl in CNTK. I was curious if there's any tool to check ndl file itself ( without running cntk).
