### ISSUE TITLE
Is there a way to check node's elements while training

### ISSUE THREAD

**Issue by wrluo** [Microsoft/CNTK#565]
Hi,

I wonder if there is some ways which can output node's elements while training. For example,

activation = Softmax(matrix);

I can only get the sum of each element in 'activation' when set EvalNode(activation). But this can not meet my requirement when debug. Is there a way to output each element of activation when traing?

Best regards,
Larry

**Comment by zhouwangzw** [comment]
CNTK V2 API (C++/Pyhton) provides more flexibility to control training. Please try with the latest CNTK release. If you have questions, please open a new issue.
