### ISSUE TITLE
Dynamic Axis Exception

### ISSUE THREAD

**Issue by RafaelDrumond** [Microsoft/CNTK#569]
Hi,

I am having some trouble using cntk. I built a RNN network to classify some sequences of input data.
I used CNTKTextFormatReader with sequence ids, and I am getting this exception: 

`EXCEPTION occurred: Dynamic axis layout '*1' is shared between inputs 'features' and 'labels', but layouts generated from the input data are incompatible on this axis. Are you using different sequence lengths? Did you consider adding a DynamicAxis() to the Input nodes?`

My input layer has the size of my feature dimension, and my output has the size of my labels dimension. I can't find anything about Dynamic Axis on the tutorials and guides. Can someone help me? How do I add a Dynamic Axis to my input layer?

(If I don't sequence IDs I don't get this error)

Just in case here's the complete output of the error:
```
`[CALL STACK]

[0x7f592d95938b]    Microsoft::MSR::CNTK::ReaderShim<float>::  GetMinibatch  (Microsoft::MSR::CNTK::StreamMinibatchInputs&) + 0x61b

[0x7f592d92adc1]    Microsoft::MSR::CNTK::DataReader::  GetMinibatch  (Microsoft::MSR::CNTK::StreamMinibatchInputs&) + 0x61

[0x79637b]          bool Microsoft::MSR::CNTK::DataReaderHelpers::  GetMinibatchIntoNetwork  <float>(Microsoft::MSR::CNTK::IDataReader&,  std::shared_ptr<Microsoft::MSR::C
NTK::ComputationNetwork>,  std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>,  bool,  bool,  Microsoft::MSR::CNTK::StreamMinibatchInputs&,  unsigned long&,  std::shared_ptr<Microsoft::MSR::CNTK::MPIWrapper> const&) + 0x2b

[0x7ade92]                                                            

[0x7ba634]          void  DoEval  <float>(Microsoft::MSR::CNTK::ConfigParameters const&) + 0x8c4

[0x5f5fd4]          void  DoCommands  <float>(Microsoft::MSR::CNTK::ConfigParameters const&,  std::shared_ptr<Microsoft::MSR::CNTK::MPIWrapper> const&) + 0xd44

[0x5968e4]          wmainOldCNTKConfig  (int,  wchar_t**)              + 0xbf4

[0x596f77]          wmain1  (int,  wchar_t**)                          + 0x87

[0x58b4f8]          main                                               + 0xd8

[0x7f592c4fbec5]    __libc_start_main                                  + 0xf5

[0x58f2e4]                                                            

EXCEPTION occurred: Dynamic axis layout '*1' is shared between inputs 'features' and 'labels', but layouts generated from the input data are incompatible on this axis. Are you using different sequence lengths? Did you consider adding a DynamicAxis() to the Input nodes?
`
```

**Comment by frankseide** [comment]
Could you explain a little more about the nature of your task? I presume you are using sequential data, where each training example consists of multiple consecutive samples? E.g. a line of text ?

What the message says is that your features and your labels have different numbers of samples.

This situation occurs e.g. in sequence-to-sequence modeling, or in sequence classification (multi-token sequence -> single-token class label).

If this is your situation, you can look at the corresponding examples: [seq-to-seq](https://github.com/Microsoft/CNTK/tree/master/Examples/SequenceToSequence), [seq-classification](https://github.com/Microsoft/CNTK/tree/master/Tests/EndToEndTests/Text/SequenceClassification).

If this is not your situation, you may either have a bug in your input file, or we will need to modify your network.

**Comment by RafaelDrumond** [comment]
That is correct. As you said, I have multiples samples in each example (so I am using sequence ids, with a label after the features of the first line of each id), but each example has an arbitrary amount of lines (but each line has the same number of features).

Thanks, I will look into those examples.

**Comment by frankseide** [comment]
Here is an example ([link](https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/Config/G2P.cntk)) that uses two different axes, one for input and one for labels.

    inputAxis = DynamicAxis()
    rawInput  = if useCNTKTextFormatReader && !isAutoencoder
                then Input (inputVocabDim, dynamicAxis=inputAxis, tag='feature')
                else Input (inputVocabDim,                        tag='feature')
    rawLabels = if useCNTKTextFormatReader && !isAutoencoder
                then Input (labelVocabDim, tag='label')
                else rawInput

**Comment by RafaelDrumond** [comment]
I am not getting this error anymore. But that means SimpleNetworkBuilder can't deal with this case right?

Thanks for the help!

**Comment by frankseide** [comment]
Yeah, SimpleNetworkBuilder only contains the most basic of configurations, but none that use different dynamic axes.
