### ISSUE TITLE
Reader resizing modes

### ISSUE THREAD

**Issue by leonardoaraujosantos** [Microsoft/CNTK#570]
Hello, guys could you tell me what is the resizing procedure that the ImageReader does during the training/prediction?

For instance digits support the following modes
Squash
Crop
Fill
Half Crop Half Fill

The idea being that we can maintain the input aspect ratio or not

How does  CNTK handle this?

![squash](https://cloud.githubusercontent.com/assets/898383/15959698/ddbf982e-2ef3-11e6-8111-8abe9e3f2f59.png)
![cropmode](https://cloud.githubusercontent.com/assets/898383/15959592/65057ad4-2ef3-11e6-9b27-cf61475cc4cc.png)
![fill](https://cloud.githubusercontent.com/assets/898383/15959593/650a4be0-2ef3-11e6-8a9f-de8ee8ca251f.png)
![halfcrophalffill](https://cloud.githubusercontent.com/assets/898383/15959594/650b0526-2ef3-11e6-8d9f-8d87c7791ee1.png)

Below is the configuration ImageReader block
reader=[
        readerType="ImageReader"
        # Map file which maps images to labels using the following format:
        # <full path to image><tab><numerical label (0-based class id)>
        # Example:
        # C:\Data\ImageNet\2012\train\n01440764\n01440764_10026.JPEG<tab>0
        file="$DataDir$/train.txt"
        # Randomize images before every epoch. Possible values: None, Auto. Default: Auto.
        randomize="Auto"
        features=[
            # Below are the required parameters.
            width=112
            height=112
            channels=3
            # Below are the optional parameters.
            # Possible values: Center, Random, MultiView10. Default: Center
            cropType="Random"
            # Horizontal random flip, will be enabled by default if cropType=Random
            #hflip="true"
            # Crop scale ratio. Examples: cropRatio=0.9, cropRatio=0.7:0.9. Default: 1.
            cropRatio=0.46666:0.875
            # Crop scale ratio jitter type.
            # Possible values: None, UniRatio, UniLength, UniArea. Default: UniRatio
            jitterType="UniRatio"
            # Interpolation to use when scaling image to width x height size.
            # Possible values: nearest, linear, cubic, lanczos. Default: linear.
            interpolations="Linear"
            # Stores mean values for each pixel in OpenCV matrix XML format.
            #meanFile="$ConfigDir$/ImageNet1K_mean.xml"
        ]
        labels=[
            labelDim=4
        ]
    ]

**Comment by eldakms** [comment]
Hi leonardoaraujosantos,
the applied transforms are described here : https://github.com/Microsoft/CNTK/wiki/Image-reader.

You can pick up which transforms to apply using the new interface described here:
https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers

Feel free to implement and contribute your transforms. If you feel that the documentation can be more detailed, please reopen the bug with your suggestions.
Thank you very much!
