### ISSUE TITLE
How to concatenate two well trained network

### ISSUE THREAD

**Issue by xqustc** [Microsoft/CNTK#574]
Hi everyone,
I have trained two networks. And I want to concatenate them together to merge into a bigger one.
The output of the first network is fed into the second network. I tried model editing language, but it seemed only one model could be loaded at a time. 
So does anyone know how to do this? Thank you!

**Comment by zhouwangzw** [comment]
You should be able to do that using the CNTK V2 API. If you have questions with the latest CNTK release, please open a new issue.
