### ISSUE TITLE
Expressions for error estimation functions

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#575]
It would be great to see the mathematical expressions used for each of the error estimation function in wiki. Because it is not clear how each error is calculated and it makes difficult to estimate model performance. For example CrossEntropyWithSoftmax is clear from its name (a lot of info available), square error is clear too (however two possibilities exist), ErrorPrediction is not clear at all (written it calculates error rates) which exact rates? Sum of difference from required and received? Correct classification and wrong? so if in binary problem output is 0.1 0.2 and 0.1 0.9 it is assumed that both outputs are the same, since the second output is always bigger?

Summarizing: I hope to see mathematical expressions for all possible cryptic names inside .ndl files.

**Comment by frankseide** [comment]
We need to complete the documentation of the nodes. For your specific case, you can see an alternative way of writing `CrossEntropyWithSoftmax()` and `ErrorPrediction()` in the [sequence-to-sequence example](https://github.com/Microsoft/CNTK/blob/master/Examples/SequenceToSequence/CMUDict/Config/G2P.cntk), where they are written using the formula directly in the BrainScript. These are the formulas (I simplified compared to the actual sample w.r.t. something unrelated to your question):

    ce   = ReduceLogSum (z) - TransposeTimes (labelSequence,          z)
    errs = BS.Constants.One - TransposeTimes (labelSequence, Hardmax (z))

`ReduceLogSum(z)` computes the *log sum.j (log sum exp z.j)* over all elements of `z`, and `Hardmax (z)` determines the maximum element of `z` and replaces it with a 1, and all other elements with a 0 (i.e. a one-hot encoding of the maximum element).

**Comment by dongyu888** [comment]
Majority of the nodes and their mathematical forms (both forward and backward computation) are documented in the CNTK book. Only the most recently added ones are not there.
