### ISSUE TITLE
Prebuilt binaries, or, better, installer

### ISSUE THREAD

**Issue by lostmsu** [Microsoft/CNTK#577]
Please, make a prebuilt distribution package. That would greatly lower entry barrier.

**Comment by frankseide** [comment]
We just released a prebuilt 1.5 [here](https://github.com/Microsoft/CNTK/releases). It's a ZIP file, not a full installer. Is that what you are looking for?

**Comment by lostmsu** [comment]
@frankseide , yeah, did not notice it. Perhaps it should be highlighted in the README.md

**Comment by frankseide** [comment]
Thanks, I forwarded the suggestion (to improve discoverability of the prebuilt binaries).

**Comment by esun0087** [comment]
can git us a simple and complete example about SLU ? @frankseide

**Comment by frankseide** [comment]
We added a Download link on the sidebar.

Does this sample help? [[https://github.com/Microsoft/CNTK/tree/master/Examples/Text/Miscellaneous/SLU]]
