### ISSUE TITLE
Run multiple ConfigFiles

### ISSUE THREAD

**Issue by SteFromGer** [Microsoft/CNTK#579]
Hello,

I am pretty new to CNTK and I got my first issue I couldn’t solve on my own or with the help of github issues. I am wondering, how to run more than one ConfigFile at once.
So, I have a time series Simple Feed Forward net, which takes about 1 hour to train and test. Quite the same setup like the simple2d example.  To optimize the network topology or rather to get a feeling for the different parameters I would like to run a lot of different ConfigFiles. Therefore I would like to combine a lot of different ConfigFiles so that I don’t need to run CNTK every hour. 
 I tried to combine different ConfigFiles and setup the “command” line to the various train parts and I also tried to have more than one command line. I set the modelpath correctly for every part. Anyway it doesn’t work.
Is there another way to run a bunch of ConfigFiles at once (I imagine a script that calls all ConfigFiles) or rather does CNTK provide this kind of function?

**Comment by SteFromGer** [comment]
ok sorry, found the solution in https://github.com/Microsoft/CNTK/wiki/Command-line-parsing-rules

**Comment by SteFromGer** [comment]
Sorry for the confusing messages, I thought I found a solution, but it doesn’t work like proposed here https://github.com/Microsoft/CNTK/wiki/Command-line-parsing-rules
I am still trying to run a lot of different config files next to one another. As far as I understood, the following set up should work. But anyhow CNTK only run the last Config and stops afterwards.  

So I have the standard Simple2d config and 2 additional config files containing the following 2 lines:

ConfigFile : Simple_test1
```
OutputDir = "$RootDir$/Output_test_1"
Simple_Demo_Train =[SGD=[maxEpochs = 3]]
```
ConfigFile : Simple_test2
```
OutputDir = "$RootDir$/Output_test_2"
Simple_Demo_Train =[SGD=[maxEpochs = 4]]
```

I was expecting that after running the command: 

CNTK ConfigFile=..\Config\Simple.cntk+..\Config\Simple_test1.cntk+..\Config\Simple_test2.cntk

I will get the Output result of all 3 config files, but I only got the results from Simple_test2.cntk and it stops.

Can someone tell me why it doesnt work like that and what I can do to get what I want :)

**Comment by dongyu888** [comment]
If you want to run against different configuration files one by one, you should just put them into a simple shell command file, in which each line is a "cntk configFile= ....." 

Alternatively, you will need to put all the configs into a single configuration file and each config has its own command block. Inside this combined file, you can specify "command=config1:config2:config3" to run these ocnfigs one by one.

**Comment by SteFromGer** [comment]
Thank you, I wasn’t familiar with batch files, so I didn’t know how to use them. Took me a while to understand how it works. The problem for your alternative is, that the name of the log file gets to long so I had to change the relevant part in the code that cntk doesn’t use the command names as log file names.
