### ISSUE TITLE
Will there be an interactive Python (C#, ...) interface for CNTK?

### ISSUE THREAD

**Issue by enricoschroeder** [Microsoft/CNTK#580]
Hi CNTK Team,

I'm currently experimenting with the preliminary Python interface (located under the 'contrib' directory in the current master). I noticed that what's there is non-interactive, meaning that's basically just a different approach to defining your network configuration files (it generates a Brainscript description of the defined network and launches CNTK,exe as a subprocess).

In the FAQ here on Github you say "_Around August 2016 we plan to release the new CNTK APIs supporting both Python, C++, and .Net (C#) bindings, so you will be able to configure your networks, create new nodes, as well as programmatically feed the data from your own Python, C++, and .Net programs._” 

Does this mean that a different API is coming that will allow to directly feed data in-memory from e.g. Python to CNTK and execute training on a per-batch basis via a function call? Or will it work the same as the current Python interface?

Thanks in advance

**Comment by cmarschner** [comment]
It will be a different API that will talk to CNTK's core directly. The functions that set up the network will largely stay the same, and tensors will also be defined in row major form (on the Python side) for Numpy compatibility.
