### ISSUE TITLE
EXCEPTION occurred: error opening file './Output/Models/ResNet_18': Permission denied

### ISSUE THREAD

**Issue by MouHMY** [Microsoft/CNTK#583]
Dear CNTK team,

I downloaded the pre-trained model "ResNet_18.model" and tried to run the **_ResNet_18.cntk_**, unfortunately, an exception occurred shown below.
I tried to modify the permission of "ResNet_18.model" as read-write, but still failed with this error.
Any idea about this? Thanks very much.

...
Action "train" complete.
###### 
# Action "edit"
###### 

**_attempt: error opening file './Output/Models/ResNet_18': Permission denied, retrying 2-th time out of 5...
attempt: error opening file './Output/Models/ResNet_18': Permission denied, retrying 3-th time out of 5...
attempt: error opening file './Output/Models/ResNet_18': Permission denied, retrying 4-th time out of 5...
attempt: error opening file './Output/Models/ResNet_18': Permission denied, retrying 5-th time out of 5..._**

[CALL STACK]
    > Microsoft::MSR::CNTK::attempt<<lambda_ea8d945bb8ef4e5e33b8d51ed12553d0>>  
    - Microsoft::MSR::CNTK::File::  Init
    - Microsoft::MSR::CNTK::ComputationNetwork::Read<float>  
    - Microsoft::MSR::CNTK::MELScript<float>::  CallFunction
    - Microsoft::MSR::CNTK::MELScript<float>::  ParseValue
    - Microsoft::MSR::CNTK::ConfigParser::  Parse
    - Microsoft::MSR::CNTK::MELScript<double>::  FileParse
    - DoEdit<float>  
    - DoCommands<float>  
    - wmainOldCNTKConfig
    - wmain1
    - wmain
    - __tmainCRTStartup
    - BaseThreadInitThunk
    - RtlUserThreadStart

**_EXCEPTION occurred: error opening file './Output/Models/ResNet_18': Permission denied_**

**Comment by frankseide** [comment]
Could you please first verify to manually create the file, if you have not yet. Assuming that works, my hunch is that the current directory set incorrectly, that `./` is not what you think it is.

The log logs all config three times, including twice with variables instantiated. Could you check whether the pathnames have been expanded correctly?

You can also try to pass in an absolute path, typically the examples have a variable `RootDir` that you can set on the command line. Or just modify the config directly to use an absolute path inside.

**Comment by wolfma61** [comment]
Unfortunately there hasn't been a reply by the user
if this issue still persists with the latest bits, please open a new issue ...
