### ISSUE TITLE
How to build a network for Lunar Lander?

### ISSUE THREAD

**Issue by demoacct** [Microsoft/CNTK#585]
Hi,

I am new to CNTK, and I am having problems on how to build a network which will try to simulate the [lunar lander](https://en.wikipedia.org/wiki/Lunar_lander_%28disambiguation%29) game. We have seen that [Encog](https://github.com/encog/encog-dotnet-core/tree/master/ConsoleExamples/Examples/Lunar) was able to build a similar simulation and we would like to build it using CNTK. 

As far as I know here are some of the network details needed:
**3 inputs:**
Distance
Velocity
Fuel

**1 output**
Thrust or No thrust

The problem is that the network's output is constantly used to help train the neural network. i.e., Distance = 1000, Velocity = 0, Fuel = 80 and the network's output is, say, 0 (No thrust). So with the output 0 it will recalculate the next input. In other words, the training data set is not readily available as I have seen in most of the examples rather it is calculated after each training cycle or each new set of input is fed to the network, and produces an output.

Any ideas on this would be of great help.

Thanks.

**Comment by frankseide** [comment]
Sorry to disappoint--This situation where the training data is generated dynamically is not generally supported by the current version of CNTK. Around end of August, we plan to release a library version that allows you to call CNTK functions from Python (or C++). Then you will have full control.

It may be possible to wing it by implementing `class LanderSimulator` as a recurrent network (with fixed parameters). You would have to run this network for a fixed number of time steps (i.e. keep a game-over or win state you may have reached earlier until all steps have passed), and then use the final state as a supervision signal for all time steps (by spreading it backwards through another recurrence that runs right-to-left).

That recurrence of the actual game would look something like this:

    # state from previous time step, and initial values
    previousVelocity = PastValue (0, Velocity, defaultHiddenActivation=0)
    previousAltitude = PastCalue (0, Altitude, defaultHiddenActivation=10000)
    pastFuel = PastValue (0, Fuel, defaultHiddenActivation=10)

    # updates
    Velocity1 = previousVelocity - Gravity
    Altitude = Clip (previousAltitude + Velocity1, 0, 10000000)

    isThrusting = (thrust .* Greater (pastFuel, Constant (0)))
    Velocity2 = Velocity1 + isThrusting .* Thrust
    Fuel = pastFuel - isThrusting
    Velocity = Clip (Velocity2, -TerminalVelocity, TerminalVelocity)

We would need to add flags whether the game is even still running, or already won/lost. Not super-trivial.

**Comment by demoacct** [comment]
Thanks for letting me know about a workaround. Is it possible to reference the CNTK libraries and create the LanderSimulator using C# instead? I have no experience in C++ which would be hard for me to directly implement it there.

**Comment by frankseide** [comment]
Ah. The code I wrote above is in the CNTK configuration language ("BrainScript").

The way to run CNTK jobs is to provide a configuration file that basically contains configuration parameters for data reading, network description, and SGD hyper parameters. What I showed above was a snipped of the network description.

With the current version of CNTK, you would train your model by running the CNTK command-line tool, which will interpret the network description in the format like above (what I wrote above is only the lunar lander code itself, but not the actual network). Once the model is trained, you can do inference from C#. But training currently requires the CNTK cmd-line tool and our network-description language.

Around end of August, we will have a librarified version of CNTK that allows to access all its key components through APIs. Initially those will probably be for C++ and Python, with C# (.Net) likely being next.

**Comment by wolfma61** [comment]
The current version of CNTK (2.0) support Python and C++ as APIs for training tasks.
Native languages (C#) will be available most likely in the next few month (?Autumn? 2017?)
