### ISSUE TITLE
How to create meanfile?

### ISSUE THREAD

**Issue by sofeikov** [Microsoft/CNTK#587]
Hi guys,

May I please ask you to explain me how do I obtain and later use a mean file for my training set? I saw mean file from ImageNet was used in some config files. How do I build my own?

Regards,
Konstantin

**Comment by yuxiaoguo** [comment]
Indeed, meanfile is provided with the example of ResNet. You can find it here.
[ImageNet1K_mean.xml](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Miscellaneous/ImageNet/ResNet)

**Comment by sofeikov** [comment]
Hi

I saw this file. However, this file is build for images of different dimensions. That is why I was asking how do I get my own file for my training set that have a different image size? The one that can be found on the link is for 224x224 images.

Thanks

**Comment by yuxiaoguo** [comment]
For CNTK mean-file, you can just sum up all the images, then divide the total image size (every pixel and channel have a mean value). About xml exporter, opencv provides a tool that could convert matrix into xml.
Hope my answer will help.

**Comment by Alexey-Kamenev** [comment]
Actually, you may not even need that file. In many cases you can just subtract a constant value, like 128, from the input. Or, to be more certain, you can compute mean/variance on your images (or a reasonably sized subset of thereof) and use either single mean value or 3 values (mean per channel). What CNTK uses (per-pixel mean) is really an overkill.

**Comment by sofeikov** [comment]
Hi Alexey,

I think you're right. Eventually we just went for subtracting 128 from the data in NDL file.

I think we could close the issue.

Thanks,
Konstantin
