### ISSUE TITLE
Wrong cropType by default

### ISSUE THREAD

**Issue by sofeikov** [Microsoft/CNTK#588]
Hi guys,

I've got a problem with crop type that is used be default. As far as I understand, the crop type that used be default is supposed to be `center`. However, when you do not specify the crop type, it uses `MultiView10`. Maybe it is not the case, but I've got ten results per image when do a `write `action.

Am I getting something wrong?

Thanks,
Konstantin

**Comment by Alexey-Kamenev** [comment]
Hi Konstantin,
Which version are you using? I thought we have fixed this bug, it was reported a month or so ago.

**Comment by sofeikov** [comment]
Hi Alexey,
to be honest, probably you're right and I'm using kind of old binaries. Technically, I started using CNTK about a month ago. I'll update my binaries tomorrow and let you know - probably we'll just close the issue.

Anyway, glad you were aware of the problem.

Thanks,
Konstantin

**Comment by eldakms** [comment]
I am closing this bug. Feel free to reopen if the problem still exists. Thanks!
