### ISSUE TITLE
When will Brainscript resnet examples be available?

### ISSUE THREAD

**Issue by LowerySJ** [Microsoft/CNTK#590]
Hello, everyone. CNTK developers, when, if at all, do you anticipate providing more Brainscript example networks, particularly resnets? It looks like you just provide one in the Tutorial folder and a single hidden layer example for MNIST right now. 

Thanks!

**Comment by frankseide** [comment]
Yes, we plan to update all examples to BrainScript. This will happen over the next few days, but I don't have a precise ETA.

**Comment by wolfma61** [comment]
CNTK 2.0 has a much larger set of samples. 
Most new samples are now done with Python, Jupyter notebooks are also a great source for information.
