### ISSUE TITLE
How  to solve " called when data is not memory"

### ISSUE THREAD

**Issue by longjewel** [Microsoft/CNTK#592]
I'm trying to learn CNTK, and it would be fantastic if someone could answer these questions for me. 
When I try to run \Examples\Speech\AN4 in the release of (CNTK) supports Windows , the tips are bellow :+1: attempt: releasedata: called when data is not memory, retrying 2-th time out of 5.  How do  I solve the  issue?

**Comment by wolfma61** [comment]
Please try with the latest released bits of CNTK, that issue should be solved.
If you still experience problems, please open a new issue with a complete repro-scenario.
