### ISSUE TITLE
UCIFastReader is much slower than CNTKTextFormatReader

### ISSUE THREAD

**Issue by bulatGH** [Microsoft/CNTK#597]
When CNTKTextFormatReader is used, training takes almost 3 times longer. As far as I see, the issue is that CNTK  empties its memory and downloads again the training data every epoch when CNTKTextFormatReader is used. Is this an expected behavior? 

Another thing is that I do not get the phrase:
?? retries for ?? elements (??%) to ensure window condition.
Does it mean that window condition is no longer ensured?

**Comment by raaaar** [comment]
The answer to the first question is yes, this behavior is expected. If you know upfront that the dataset fits in memory, you can set the `keepDataInMemory` to true in the reader config section to avoid re-reading the input anew for each epoch ([here's an example](https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader#extended-example)).

Regarding the "window condition" output, it's was some debugging info related to the randomization scheme implemented in UCIFast. CNTKTextFormatReader uses a different implementation.
