### ISSUE TITLE
Random output instead of sortet list

### ISSUE THREAD

**Issue by Woife91** [Microsoft/CNTK#600]
Hi, 

I'm struggling with the following issue: I have whole images and a twoclass-problem. Training and testing works fine, but the write section prints unexpected output. I want to have two files, one with the original labels and one with the output of the net. Items in the label-file have the same order as in the testfile. The problem is that in the output-file (.ol.z) the order has changed and I do not have any connection between the two files. Of course I set "randomize = none". I have the additional parameters in the features-section because without the number of samples increased by a factor 10.

I hope you guys can help me with that, thank you in advance :) I attached the file with the write-section, but if train, test, or the ndl-file should be required to solve my issue, please let me know.

[example.txt](https://github.com/Microsoft/CNTK/files/318034/example.txt)

**Comment by frankseide** [comment]
The way you configured it, the outputs must match, which is what you expected but did not observe.

I suspect the problem could be the `NDLNetworkBuilder` section in your "write" command. I don't think this should be there. Somehow it snuck into an example, where it was ignore for a year until we enabled on-the-fly model editing. Your system may just be creating a fresh, untrained model in the "write" section, which would lead to random outputs. I need to confirm this, and add a note to the BrainScript conversion guidelines.

Would you mind trying to remove it, and instead just specify your `modelPath` (if not already specified outside of the "write" section)?

**Comment by Woife91** [comment]
Removing the NDLNetworkBuilder solved the problem, thank you. I also have it in the test command and I don't think it causes any problems. Should I remove it anyways or in other words, does it have to be there?

**Comment by frankseide** [comment]
Please remove it everywhere except train actions.

I hope it's OK for you that I go ahead and close the Issue.
