### ISSUE TITLE
Understanding output liklihoods ( MNIST example )

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#601]
In my "write" action that I added to my MNIST config file, I put:   type = "real"  so that I get 10 real values out.   I ran the network on an input image of a "5" and the result is:

-4.921455 -4.302909 -6.866016 2.374373 -1.392200 15.632916 2.906811 -4.122224 -1.551317 1.944227

So, we can see that "5" is the highest score.  All good.  My question is:  is there a formula or a way to understand these 10 values such that I could turn them into a "likelihood" or other understandable statistical measure?  That is, I'd like to say something like "with 92% likelihood, it is a 5" -- or something like that.   In particular, as a practical matter, I'd like a rational way of detecting a measure of 'distance' to the 2nd best choice -- how sure are we that this is a 5 and not a 6?  That type of thing.  Thanks.

**Comment by JohnCraigPublic** [comment]
I have a feeling that I'm asking to get softmax numbers instead of values from the last layer.  Just need a pointer if that's right, and how to get those values....

**Comment by frankseide** [comment]
Typically, what would be written out is the input to the softmax function. Let's call that `z`. You can modify your network to include the actual Softmax values as well:

    P = Softmax (z, tag="output")

and then output 'P'. That would be the posterior probability for class *k* given your input, which is exactly the probability you want (a value of 92% would, at least theoretically, mean that if you get a lot of examples that all output 92%, the error rate over that set would be 92%--never works that nicely in reality though).

I am not sure if you are using a custom network descripton (`NDLNetworkBuilder` or `BrainScriptNetworkBuilder`) or `SimpleNetworkBuilder`. If `SimpleNetworkBuilder`, (`z` would be called `HLast`, I think), that might already be there under the variable name `PosteriorProb`, so you can just output that instead.

**Comment by JohnCraigPublic** [comment]
I'm using the original 02_Convolution.ndl supplied with the MNIST example.  That file has

    OutputNodes = (ol)

When I output in my 'write' action, is it taken from whatever is defined as "OutputNodes" in the ndl file?
If I change the ndl as regards output, I should not need to re-train, correct?

**Comment by frankseide** [comment]
Unfortunately, this network does not have the Softmax output. Let us try two ways of getting it in. First, if you were to retrain, you'd add this:

    ol = DNNLayer(h1Dim, labelDim, h1, 1)
    p = Softmax (ol)
    outputNodes = (p)

Since you already have the model, we can try to edit the mode on the fly. Could you please try to add this section to your "write" section:

    BrainScriptNetworkBuilder = [
        network = BS.Network.Load ("$modelPath$")
        p = Softmax (ol)
        outputNodes = (p)
    ]

I have not tested this configuration, please let me know if it works.

This requires the latest 1.5 binary.

**Comment by JohnCraigPublic** [comment]
Frank - it doesn't look like the "editing on the fly" attempt works -- got the error that "cntk.core.bs" does not exist.

**Comment by frankseide** [comment]
Umm... Could you please check whether that file exists in the folder where your CNTK binary is? It should be copied there as part of the build process. I hope it did not accidentally get stripped in the 1.5 package...

**Comment by frankseide** [comment]
I verified that it is present in both Windows and Linux distributions. Did you copy the cntk binary elsewhere?

**Comment by JohnCraigPublic** [comment]
In the meantime, I did your other suggestion and added the Softmax to the ndl file and re-trained the network, and now its nice -- I'm getting the probabilities for each of the 10 classes.  So, that's good for me.

 I'll also try to get some time to look around for cntk.core.bs and let you know....

**Comment by JohnCraigPublic** [comment]
Frank - hmm.. the cntk.core.bs is indeed sitting there right next to the executable ( cntk.exe ).   -- maybe because: I've added that folder to my path, and I run the executable from the "Data" folder of the MNIST sample -- so perhaps that's it -- I will try running from the folder of the executable....

ok, hmmm, just tried that too, and still says error opening cntk.core.bs  -- 

Well, its OK for me Frank, I have it working the other way, so feel free to close this thread unless you want me to keep trying on this approach....

**Comment by JohnCraigPublic** [comment]
aha!  #606 mentions this, and a possible solution...

**Comment by frankseide** [comment]
Yes, copying CNTK.core.bs over should work. Please try that, although there is definitely a bug there and this should not be necessary. Unfortunately, I cannot repro the problem.

**Comment by frankseide** [comment]
OK, it was a bug that only shows with Windows 7. I posted the fix in #606.

I hope it's OK if I close this Issue.
