### ISSUE TITLE
CNTK load model not thread safe?

### ISSUE THREAD

**Issue by PatrickBue** [Microsoft/CNTK#602]
Hi,

I am trying to use CNTK (CPU-only at this point) within another MS-internal application that creates two copies of a model and executes these in parallel.
The models are loaded in parallel - but even if I am using different filenames (copies of the same model), running the models later throws an `System.AccessViolationException `error. I ran some experiments and all points to CNTK not being thread-safe.

Is there a way to make CNTK thread-safe? Thanks!

**Comment by frankseide** [comment]
Unfortunately, CNTK is not thread-safe at this point in time. There are a few global variables. I also don't think that CNTK sets CUDA contexts on a per-call basis.

For the librarification, slated for late August, this is something we will need to address.

**Comment by quicktrick** [comment]
Hello!

@gaizkan wrote at https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview#current-limitations

> However, it is possible to load multiple models in the same process and query each model using a single thread.

Could you please give an example how to do that?

**Comment by gaizkan** [comment]
Hi, 

I have added an example for multi-model evaluation to the CSEvalClient. 
Let me know if this works for you. Otherwise, you'll have to wait for the librarification mentioned by Frank.

**Comment by quicktrick** [comment]
Hi @gaizkan!

Thanks a lot for the example!  In fact I've already solved this problem for six trained networks which work together in my application. But thanks anyway, your code is a sample of good programming practice and I'll make some changes in my own code according to yours.
