### ISSUE TITLE
write action doesn't work with CompositeDataReader

### ISSUE THREAD

**Issue by hunterlang** [Microsoft/CNTK#603]
DoWriteOutput in EvalActions.cpp tries to set the "randomize" variable of the reader configuration to "None", but "None" isn't a false value for bool types in the config (Config.h L264). I think it should be "false" instead.

**Comment by frankseide** [comment]
Indeed! Thanks! Would you like to submit a pull request, or should we fix this internally?

**Comment by eldakms** [comment]
Fix was integrated into master.
