### ISSUE TITLE
Building with CNTKCustomMKL. Error: Cannot open include file: 'acml.h': No such file or directory

### ISSUE THREAD

**Issue by quicktrick** [Microsoft/CNTK#605]
(I'm sorry, but after some further investigation I've changed this message a little, so it differs from that was sent by email first).

Hello!  Yesterday I wrote about an issue #598 occured when building CNTK with CNTKCustomMKL.  Today I found some more issues.

When building CNTK on GPU then everything is OK.  But when building on **CpuOnly** (!) it doesn't build without ACML_PATH set up, even if CNTK_MKL=1 and CNTK_MKL_PATH is set up as well.  If ACML_PATH is set up then the build is successful.

Could you please look into this? ( @mahilleb-msft )

**Comment by mahilleb-msft** [comment]
Yes, I will take a look.

**Comment by mahilleb-msft** [comment]
@quicktrick - which commit are you on? Can you try on latest master? (There was another fix I merged in yesterday).

Thanks, Mark

**Comment by quicktrick** [comment]
Hi Mark!

Everything is alright now.  Thanks a lot!

**Comment by mahilleb-msft** [comment]
Great, good to hear that! Closing this one.
Best, Mark
