### ISSUE TITLE
With BrainScriptNetworkBuilder: Error opening file 'cntk.core.bs' 

### ISSUE THREAD

**Issue by elcombato** [Microsoft/CNTK#606]
I always get this error when I use the `BrainScriptNetworkBuilder`. Even if I run the provided example [CNTK/Examples/Tutorial/lr_bs.cntk](https://github.com/Microsoft/CNTK/blob/master/Examples/Tutorial/lr_bs.cntk)

With `SimpleNetworkBuilder` everything works fine. The Windows PATH variable contains the cntk directory with `CNTK.exe` and `cntk.core.bs`.

I use the prebuild binaries v1.5

**Comment by Henry-White** [comment]
Just copy \x64\Release\CNTK.core.bs into your "config"-directory. It would be enough.

**Comment by frankseide** [comment]
It already does exactly that in the C++ code. There is something wrong with determining the executable path.

        if (sourceOfNetwork[0] == '[') // if [ ] form then we turn it into ComputationNetwork by constructing a ComputationNetwork from it
            sourceOfNetwork = L"new ComputationNetwork " + sourceOfNetwork;
        let sourceOfBS = msra::strfun::wstrprintf(L"include \'cntk.core.bs\'\n" // include our core lib. Note: Using lowercase here to match the Linux name of the CNTK exe.
            L"deviceId = %d\n"            // deviceId as passed in
            L"precision = '%ls'\n"        // 'float' or 'double'
            L"network = %ls",             // source code of expression that evaluates to a ComputationNetwork
            (int)deviceId, ElemTypeName<ElemType>(), sourceOfNetwork.c_str());
        let expr = BS::ParseConfigDictFromString(sourceOfBS, L"BrainScriptNetworkBuilder", move(includePaths));

**Comment by frankseide** [comment]
Could you let me know your OS version? At one place, we have two code paths for processing directory names, one for Windows 7 and one for Windows 8+. We are al running under Windows 8 or 10, and that seems to work just fine.

**Comment by frankseide** [comment]
OK, discovered a bug in the Windows 7 version. If you compile yourself, you can make this change in Source/Common/File.cpp, line ~177, from:

        hr = PathRemoveFileSpec(&path[0]);

to:

        hr = PathRemoveFileSpec(&path[0]) ? S_OK : S_FALSE;

Change will be in master in a few hours. Hope you are OK if I close this.
