### ISSUE TITLE
results different with GPU and CPU

### ISSUE THREAD

**Issue by scimg** [Microsoft/CNTK#608]
I am running the tutorial on [https://github.com/Microsoft/CNTK/wiki/Tutorial](url), with CNTK-1-5-Windows-64bit-GPU 
When setting deviceId=-1 (use CPU), the result seems correct with

    Final Results: Minibatch[1-1]: err = 0.00688694 * 500; lr = 0.02909403 * 500

and the content in "LR_reg.dnn.__AllNodes__.txt"
 
    b=LearnableParameter [1,1]   learningRateMultiplier=1.000000  NeedsGradient=true 
     -12.3975649 
     #################################################################### 
    err=SquareError ( labels , p ) 
    features=InputValue [ 2 ] 
    labels=InputValue [ 1 ] 
    lr=Logistic ( labels , p ) 
    p=Sigmoid ( p.z ) 
    p.z=Plus ( p.z.PlusArgs[0] , b ) 
    p.z.PlusArgs[0]=Times ( w , features ) 
    w=LearnableParameter [1,2]   learningRateMultiplier=1.000000  NeedsGradient=true 
     2.40208316 2.66412544 
     ####################################################################

However, when setting deviceId=0 (use GPU), the result is different and seems not correct

    Final Results: Minibatch[1-1]: err = 0.00000000 * 500; lr = 0.00000000 * 500

and the content in "LR_reg.dnn.__AllNodes__.txt"
 
    b=LearnableParameter [1,1]   learningRateMultiplier=1.000000  NeedsGradient=true 
     -0.0214618798 
     #################################################################### 
    err=SquareError ( labels , p ) 
    features=InputValue [ 2 ] 
    labels=InputValue [ 1 ] 
    lr=Logistic ( labels , p ) 
    p=Sigmoid ( p.z ) 
    p.z=Plus ( p.z.PlusArgs[0] , b ) 
    p.z.PlusArgs[0]=Times ( w , features ) 
    w=LearnableParameter [1,2]   learningRateMultiplier=1.000000  NeedsGradient=true 
     -0.0357309394 0.0298095457 
     ####################################################################

**Comment by JohnCraigPublic** [comment]
See closed question #591 -- may be the same thing.

**Comment by scimg** [comment]
Thank you for sharing. That seems something about the compute capability of the gpu.
