### ISSUE TITLE
Does cntk support cuda 7.5?

### ISSUE THREAD

**Issue by holmes2016** [Microsoft/CNTK#61]
I would like to build cntk with cuda 7.5 and vs2013 on windows 10. However, the MathCUDA project cannot be loaded. The error message says, "The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.0.props" was not found." I wonder if I have to install cuda 7.0 in order to build the solution.
Thanks

**Comment by Alexey-Kamenev** [comment]
Hello,
CNTK currently supports 7.0 only but I think it should be easy to modify it to compile with 7.5
Try doing the following: open Source\Math\MathCUDA.vcxproj and change following lines:
1. CUDA_PATH_V7_0 to CUDA_PATH_V7_5
2. $(VCTargetsPath)\BuildCustomizations\CUDA 7.0.props to $(VCTargetsPath)\BuildCustomizations\CUDA 7.5.props
3. $(VCTargetsPath)\BuildCustomizations\CUDA 7.0.targets to $(VCTargetsPath)\BuildCustomizations\CUDA 7.5.targets

Hope this helps, let me know if you still have problems compiling the code.

**Comment by holmes2016** [comment]
Many thanks, Alexey,
I got another problem. The EvaDll project cannot be loaded due to an error, "$(UsesCuda) evaluates to "" instead of a boolean". Do you have any idea about it?
Thanks,

**Comment by Alexey-Kamenev** [comment]
Hmm, I don't know what's the problem yet, however, if everything else builds fine, you can still run CNTK even without EvalDll (which is really just a sample demonstrating how to load trained models). I know it's not ideal but hopefully will unblock you for now.

**Comment by jfslocum** [comment]
I built CNTK with CUDA 7.5. Here are the changes I made:

In ActionsLib.vcxproj, MathCUDA.vcxproj, and Math.vcxproj, there are a number of references to CUDA dll's, e.g. "cudart64_70.dll". Change the "70" version suffix to "75" , e.g. "cudart64_75.dll'


In MathCUDA.vcsproj, change the CudaPath attribute from "$(CUDA_PATH_V7_0)" to "$(CUDA_PATH_V7_5)". There is a reference to "CUDA 7.0.props" - change this to "CUDA 7.5.props". Similarly, change "CUDA 7.0.targets" to "CUDA 7.5.targets".

You can download a copy of my files here: https://www.dropbox.com/sh/7cbuxz2rde9gjxe/AADPaPS5UtovRuQFbBfnb3W7a?dl=0

**Comment by holmes2016** [comment]
Great! Thanks a lot. Actually I haven't gotten a successful build yet. I have another mess - both vs2012 and vs2013 installed on my machine, where I also run theano. Not sure if the issue of having two compilers has been addressed.

**Comment by jfslocum** [comment]
I have VS 2013 and 2015 on my machine. I think I did the build with 2013? What problem are you having with your build?

**Comment by holmes2016** [comment]
After applied the changes made in your project files, I still got the following when build math project:
Error	1	error MSB4062: The "Nvda.Build.CudaTasks.SanitizePaths" task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\Nvda.Build.CudaTasks.v7.5.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.5.targets	160	9	MathCUDA
Error	2	error C2440: '<function-style-cast>' : cannot convert from 'initializer-list' to 'std::array<size_t,0x02>' (TensorView.cpp)	c:\users\jlu\projects\cntk\source\math\TensorView.h	32	1	Math

**Comment by jfslocum** [comment]
Sorry, no idea what's going on there.

**Comment by holmes2016** [comment]
No problem. I guess it is related to my VS and cuda setup. But my theano is able to run with cuda 7.5.
Thanks

**Comment by mradmila** [comment]
We will be adding support for CUDA 7.5 within the next month.

**Comment by holmes2016** [comment]
Cool! Thanks

**Comment by rold2007** [comment]
It seems like CUDA 7.5 support was added as of April 5th 2016.
https://github.com/Microsoft/CNTK/wiki/News#april-2016
