### ISSUE TITLE
Varying size input images

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#610]
In an image classification problem, the input images may have varying pixel dimensions.  I guess I plan to enlarge all images to smallest square image, and then resize down to whatever final resolution I want to train my network with.

But, does anyone have something more to say about this?  

1) Is it possible to leave the images having varying pixel dimensions?
2) Will it confuse or weaken the results obtainable if many of the images have blank regions near 2 or more of the edges of the original image?  (because the image had to be 'squared-up')

Thanks!

**Comment by ant0nsc** [comment]
Answers to your questions: 
1) yes
2) in my experience, significant whitespace around the image can well have an impact on accuracy. What I'm doing in my work is to first crop away anything that is just plain white, and then feed the rest into CNTK.

There is actually no need to do the pre-processing you describe above, you can have CNTK do all that for you. Here's a rough description of the steps it will use for all input images:

1. Cropping (taking a sub-image out of the full image): if you specify `cropType=Center`, it will pick a sub-image from the center of the image, its size determined by the `cropRatio` (0.8 will give you an image that has width/height that is 80% of the original). Other options are `random`, `multiview10`
2. The output of step 1 is then re-sized to the size given by the `width` and `height` parameters, which will be your network input size
3. Subtract the mean, if you have any
4. Optionally transpose the image

**Comment by JohnCraigPublic** [comment]
I'm connecting CNTK to my imaging app, so I have all the tools to do the image transform things on my side - so I've already set that up.   Curious about your answer "yes" to my query about using images of varying sizes -- I start with images of varying sizes and then you crop, resize operations to get them all to the same size to feed CNTK.   What I was asking is if that can be avoided, and we simply feed CNTK images of varying sizes.  Are you meaning 'yes' to that?  Thanks.

**Comment by frankseide** [comment]
No, it cannot be done. The image dimensions are static dimensions which are constant for a network. Otherwise, it would be impossible, or at best inefficient, to pack multiple randomly selected images into minibatches.

**Comment by JohnCraigPublic** [comment]
Another interesting query is 'what size do images need to be' for an image classification task?   My native images are in the range of 1500 x 2000 to 3000 x 3000 -- and so I surely plan to down-size them -- but to what size?    If I have N classes in my classification problem, and M total images in my training set, then the image size should be P x P pixels -- how to choose P?   Probably independent of M, but maybe related to N, but all a bit vague, isn't it?  Or has somebody got a theory?

**Comment by JohnCraigPublic** [comment]
My planned approach: I'm going to look thru a bunch of my images, and downsize them to 40x40, to 80x80, to 250x250, and so on -- and I'm going to determine a good size need for *me* to be able to do the classification accurately -- and then use the assumption that if I can do it at that size, the network can do it too.

**Comment by frankseide** [comment]
One thing came to mind: You can always mask. If you can read (or generate) a pixel mask (a [W x H] tensor of 0 or 1 values) in parallel with your input (or, in the extreme, generate it from a "transparent" color directly in the network), and do an element-wise multiplication with it (probably at every layer), you can use any size. This may be helpful with images of similar but not identical aspect ratios. This may be better than forcing the aspect ratio to be the same through squashing or stretching (I would still rescale all images to roughly the same size so you get proper minibatching).

It may be easier to just crop to the same aspect ratio.

(Sorry, I am not an image specialist and cannot answer the question on pixel size; I would just follow what everyone else is doing.)
