### ISSUE TITLE
Undefined function or macro 'DynamicAxis' in DynamicAxis()

### ISSUE THREAD

**Issue by ZhangZhengchen** [Microsoft/CNTK#612]
Hi, I'm trying to build a network handling the sequence data. The input is a line of text, the features are word vectors of each word in the line. The output is a label of the whole line. So I need the DynamicAxis as shown in the sequence classification example. But when I use 

t = DynamicAxis()
features=Input(featDim, dynamicAxis=t, tag='features')
labels=Input(labelDim, tag='labels')

in my config file, I met the error: 

[CALL STACK]
    > Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
    - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=

EXCEPTION occurred: Undefined function or macro 'DynamicAxis' in DynamicAxis()

The version used is CNTK-1-5-Windows-64bit-GPU binary

Any suggestions? Thank you!

**Comment by frankseide** [comment]
I suspect your version is not up to date. Have you tried the latest binary (1.5)? Please find the download link under Downloads on the sidebar.

**Comment by ZhangZhengchen** [comment]
Hi frankseide,

Thank you for your reply. I confounded the BrainScriptNetworkBuilder with NDLNetworkBuilder. Now the problem is solved. Thanks again.
