### ISSUE TITLE
CNTK ; CIFAR-10;  Plugin not found: 'ImageReader.dll'

### ISSUE THREAD

**Issue by suzukiR** [Microsoft/CNTK#613]
I try to do CIFAR-10 in CNTK
I built ImageReader in cntk.sln , created ImageReader.dll and put it to Release folder containing cntk.exe   
but after config running, output_log expressed 「EXCEPTION occurred: Plugin not found: 'ImageReader.dll'」 
I don't know cause. Please tell me this solutions and cause.

other sample programs(simple2d,MNIST) was success at building and running.

**Comment by eldakms** [comment]
Could it be that you are missing zlib? See here:
https://github.com/Microsoft/CNTK/issues/359

**Comment by suzukiR** [comment]
Thank you !
Tentatively, when renamed  zlib1.dll→zlib.dll in Release folder,
that EXCEPTION message is disappeared.

**Comment by wangdelp** [comment]
@suzukiR Thank you, that solves my problem.

**Comment by frankseide** [comment]
So I will close the issue if you don't mind. Please reopen if needed.

**Comment by huishaoli** [comment]
could you please tell me how to creat the imageReader.dll?
