### ISSUE TITLE
Node that changes batch size

### ISSUE THREAD

**Issue by hunterlang** [Microsoft/CNTK#617]
Is it possible to have a node change the batch size dimension?

I'm implementing ROIPooling, which for each item along the `batch_size` dimension of its input should create `R` items in the `batch_size` dimension of its output. So if the input to the node is `W x H x C x N`, the output would be `W x H x C x (N*R)`. Until now I've hacked this by setting `W x H x C x N x R` as the output shape, but now I want to feed the output of this node into a fully-connected layer, and there should only be `W*H*C` input features.

**Comment by wolfma61** [comment]
There has been a lot of changes since then. Please take a look at the latest 2.0 release and the extended documentation, for example: https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-minibatchsize-and-python-minibatch_size_in_samples-in-cntk
