### ISSUE TITLE
different results between 2 same experiments

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#619]
Now i try to train a LSTM network.
First I trained a model  ("lstm1.dnn.")which have a good result .
Then I tried to reproduce it to get a model   lstm2.dnn.

Both 2 experiments started with the initial network  "lstm1.dnn.0" and  "lstm2.dnn.0".
I dumped the value  and of course there is no difference bettwen them (except some tiny distinctions of Mean).
It's strange when I use a same configFile to train "lstm2", it always  gets a NAN error which forces me to turn down the learning rate. And the performance is not as good as the older one.

How is that about? because of the randomization of data reading?

**Comment by frankseide** [comment]
Did the configurations differ in any way?

If you run the same job twice, you should get identical outputs as long as you run on the same hardware, use CNTK 1.5+, do not use data parallelism, do not restart from checkpoint, and do not use one of the convolution functions. (Data parallelism and convolution functions have minor non-determinism from random summation order of float values. Before CNTK 1.5, there were more functions with such minor non-determinism. I did observe that instable recurrent models can differ as much as to converge or diverge. Restarting from checkpoint does not restore some inner state correctly in a few select nodes, which we are working to fix.)

Data reading by default uses the same random seeds and will thus give you the same result each time you run.

**Comment by staplesinLA** [comment]
@frankseide  Yes, you are right. The same job would get identical outputs ,i have tried it before.
In this situation , all the configurations are the same and the cntk is version 1.5 . 
Will the tiny computing error of Mean and InvStdDev bettwen 2 process be the reason? 
I will check all things again and try to  reproduce it . 
Thanks !

**Comment by staplesinLA** [comment]
BTW,  if i want to use multiple GPUs to accelerate the training (1-bit or BM SGD) , which parameters are the most effective ?
In DNN , i usually multiply the minibatchSize with the number of GPUs, the speedup is evident.  
Now in LSTM ,  minibatchSize =16 ,  nbruttsineachrecurrentiter = 16,randomize=3456000 .
 I changes mbSize to 64 and the speed doesn't  increase at all.
Is there any experiences to help?  Thank you! @frankseide

**Comment by frankseide** [comment]
You are using truncated BPTT, right? The configuration is a little weird in that minibatchSize really defines your truncation length, and the minibatch size is the product of MB size and number of parallel utterances, i.e. 256 in your case.

To get a speed-up with truncated BPTT, you would instead have to increase the number of parallel utterances.

BTW you can find some information about these two methods [here](https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines).

>In DNN , i usually multiply the minibatchSize with the number of GPUs, the speedup is evident.

For 1-bit, don't do that. If you can do that without harming convergence, then you started out with too small a minibatch size in the first place for the 1-GPU case, which you should tune first. I.e., first find out what your maximum minibatch size is that still allows you to train and converge well. And then keep using that MB size for data-parallel training (which will lead to half the MB size being used on each worker in the case of 2 GPUs). I would also then try the auto-adjust option for MB size, as shown in section 2.1.2 in the above wiki page. This is less critical for 2 GPUs in-box, but important once you scale out beyond machines.

**Comment by staplesinLA** [comment]
@frankseide Hi，Frank！ I follow your advice and it works now!Thank your!
And I found the difference between 3 different times experiments of one same config. 
I dump the nodes value of  these initial models (suppose they are named as "lstm1.dnn.0","lstm2.dnn.0" and "lstm2.dnn.0").
All nodes name are exactly same except some of PreCompute nodes.
For example , the value of "featNormIn.xStdDev=InvStdDev ( featIn ) [1799]   HasComputed=true "  of
 "lstm1.dnn.0"  is about 0.1 lower than those values in "lstm2.dnn.0" and "lstm3.dnn.0".
The same issue happened in node "featNormOut.xStdDev = InvStdDev(featTrain)".
Is there a possible bug for  function InvStdDev ?
