### ISSUE TITLE
make lock-file location in CrossProcessMutex.h configurable

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#62]
CrossProcessMutex.h uses a file for a global lock inside /var/lock. That location cannot be universally be assumed to be writeable in all environments for all users. It should be changed to some place that is, or changeable through a config variable.

```
CrossProcessMutex(const std::string& name)
    : m_fd(-1),
      m_fileName("/var/lock/" + name)
{
}
```

**Comment by frankseide** [comment]
We probably also want to change the lock file name to something without DBN.exe in the name, as that was meant to allow coexistence of CNTK on a single server with an old internal Windows-only tool that is no longer in use.

**Comment by nslay** [comment]
How about using an environment variable?
```
CrossProcessMutex(const std::string& name)
    : m_fd(-1)
{
  const char * const envLockDir = getenv("CNTK_LOCK_DIR");
  if (envLockDir != NULL)
    m_fileName = envLockDir + ('/' + name);
  else
    m_fileName = "/var/lock/" + name;
}
```
If you insist on a setting in the configuration file, that could simply use `putenv` to expose this variable to CrossProcessMutex.

**Comment by wolfma61** [comment]
This should have stayed open - this is a PR in process

**Comment by timolohrenz** [comment]
even after the latest news, this would be a mandatory feature for all users which have no access to /var/lock.
