### ISSUE TITLE
Problem with convolution in BrainScript

### ISSUE THREAD

**Issue by pwodzu** [Microsoft/CNTK#622]
Hi,

I am sorry if my question is trivial. I have the problem with convolution defined in BrainScript (definition in NDL works well). According to documentation (https://github.com/Microsoft/CNTK/wiki/Convolution) the signature of Convolution method is:

Convolution(w, input,
            {kernel dimensions}, 
            mapCount = {map dimensions}, 
            stride = {stride dimensions}, 
            sharing = {sharing flags},
            autoPadding = {padding flags (boolean)},
            lowerPad = {lower padding (int)},
            upperPad = {upper padding (int)},
            maxTempMemSizeInSamples = 0,
            imageLayout = "cudnn") 

I want to perform the convolution with the Image (width = 100, height = 100, channels = 3) given as the input. Kernel size is (5 x 5 x 3), zeroPadding is turned on, the vStride and hStride are 1 and as the result convolution should return 32 feature maps (100 x 100 x 32).

I was using below code but i have to change the name of parameter from  "mapCount" to "mapDims" (as it is in the CNTK.core.bs file). There is no error in documentation? During the validation of CN structure I get feature maps with dimensions (100 x 100 x 96). 

W = LearnableParameter(32, 75, init = "gaussian", initValueScale = wScale)
c = Convolution(W, featScaled, (5:5:3), mapDims=32, stride = (1:1:1), autoPadding=true, sharing = (false:false:false), imageLayout = "cudnn")

Console returns this error:
EXCEPTION occurred: Convolution weight matrix conv1.c.W should have dimension [960000, 75] which is [kernelCount, kernelWidth * kernelHeight * inputChannels]

How to perform the convolution properly?

**Comment by pwodzu** [comment]
I solve my problem by specyfying the 3rd dimension of stride and turning off the sharing property.

W = LearnableParameter(32, 75, init = "gaussian", initValueScale = wScale)
c = Convolution(W, featScaled, (5:5:3), mapDims=32, stride = (1:1:32), autoPadding=true, sharing = (false:false:false), imageLayout = "cudnn")

**Comment by frankseide** [comment]
Thanks for reporting this. It seems there is an inconsistency between the NDL and BS defaults. I will have a look.
