### ISSUE TITLE
Error: 'Microsoft.MSR.CNTK.Extensibility.Managed.NodeGroup' does not contain a definition for 'nodeInput'

### ISSUE THREAD

**Issue by quicktrick** [Microsoft/CNTK#623]
Last master, Release_CpuOnly, EvalWrapper.dll
```
Error	'Microsoft.MSR.CNTK.Extensibility.Managed.NodeGroup' does not contain a definition for 'nodeInput'
Error	'Microsoft.MSR.CNTK.Extensibility.Managed.NodeGroup' does not contain a definition for 'nodeOutput'
```
After I copied some older build from another machine (Release (GPU) from 2016-06-17), the errors disappeared.

**Comment by gaizkan** [comment]
The NodeGroup struct was redefined to be more .Net compliant by not having the "node" prefix. So where you were using "NodeGroup.nodeInput" replace it with "NodeGroup.Input" and similar for "Output"

Let me know if this fixes it.

**Comment by quicktrick** [comment]
Yes it is. It works now. I didn't think that the code that had been working previously couldn't work for such a reason. :)  Thanks @gaizkan!

**Comment by frankseide** [comment]
If you don't mind, I will close this issue. Thanks!
