### ISSUE TITLE
Step-wise function for a Replicator Neural Network

### ISSUE THREAD

**Issue by NexYY** [Microsoft/CNTK#628]
Hi,
I couldn't find any information about step-wise function support in CNTK. Is there a way to implement such? I currently need one for implementing a Replicator Neural Network for my bachelor thesis.

**Comment by dongyu888** [comment]
What do you mean by Step-wise? I think it can be implemented using macros as a combination of plus, ReLU, etc. but some step-wise operations have gradient of 0 almost everywhere and cannot be well trained.

**Comment by NexYY** [comment]
Hi, here's a example of what I mean by step-wise function:

Page 4 - http://neuro.bstu.by/ai/To-dom/My_research/Papers-0/For-research/D-mining/Anomaly-D/KDD-cup-99/NN/dawak02.pdf

**Comment by dongyu888** [comment]
If eq 3 is what you want, isn’t it just sum of several Tanh functions? You can just write a simple macro to implement it.

**Comment by NexYY** [comment]
But how would I implement this in BrainScript? The first two terms are fairly easy:
```
`# 1 / 2
half = Constant(1) / Constant(2)
`
```
```
# 1/(k-1)
secondTerm = Constant(1) / Times(Constant(2), Minus ($k$, 1, tag=''), outputRank=1, tag='')
```

But for the sum, I need to apply a function in before of suming the elements.
Usually I would use Reduction or Control Flow features for this procedure, however according to [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) these are yet not implemented. (6. Reductions, 7. Control flow)

Is there any other way of implementing the tanh sum over N-1 Elements?

**Comment by dongyu888** [comment]
You can use loops to do that, e.g., 

 

Sums[n:1:N] = if n==1 then f(x[n]) else Sums[n-1]+ f(x[n])

 

Sums[N] will be the final sum you want.
