### ISSUE TITLE
Problem about feature's dimension setting in HTKMLFreader.

### ISSUE THREAD

**Issue by oscarzbz** [Microsoft/CNTK#630]
I had already taken a close look the example Speech\AN4.
Till now, there was still a doubt about this example.
In the configfile the features setting of HTKMLFreader is as below:

> features = [
>             dim = 363
>             type = "real"
>             scpFile = "$DataDir$/glob_0000.scp"
>         ]

It said the dimension of the feature(the input dimension of the input data) is 363.
But the samplesize which was defineded in the chunkfile is 132,that said the dimension of the input vector is only 33.
The magical thing is "it works".
Is there anyone who know this.
THANKS
Oscar Zhang

**Comment by dongyu888** [comment]
Each frame has 33 dims, when you use 363 as the dim, it will expand to 11 frames (5+1+5) automatically.

**Comment by oscarzbz** [comment]
UH..........how about the first frame and the last frame, in other words ,ones if the "sliding window" go beyond the utterance, how the reader deal with the “offside” frame?

**Comment by dongyu888** [comment]
.repeat.


Thanks,
Dong Yu (俞栋)Sent from my smart phone. Please forgive my typos. 

<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Oscar Zhang <notifications@github.com> </div><div>Date: 6/28/16  18:22  (GMT-08:00) </div><div>To: Microsoft/CNTK <CNTK@noreply.github.com> </div><div>Cc: Dong Yu <dongyu888@hotmail.com>, Comment <comment@noreply.github.com> </div><div>Subject: Re: [Microsoft/CNTK] Problem about feature's dimension setting in HTKMLFreader. (#630) </div><div>
</div>-------- Original message --------From: Oscar Zhang <notifications@github.com> Date: 6/28/16  18:22  (GMT-08:00) To: Microsoft/CNTK <CNTK@noreply.github.com> Cc: Dong Yu <dongyu888@hotmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Microsoft/CNTK] Problem about feature's dimension setting in HTKMLFreader. (#630) 
UH..........how about the first frame and the last frame, in other words ,ones if the "sliding window" go beyond the utterance, how the reader deal with the “offside” frame?

**Comment by oscarzbz** [comment]
I’m truly grateful for your help ^_^
