### ISSUE TITLE
Allocate too much memory when evaluation using models with LSTM structures

### ISSUE THREAD

**Issue by ghrj** [Microsoft/CNTK#631]
I used a model based on LSTM structures for Speech Recognition and found cntk would allocate memory for all frames of one utterance. If one utterance has 1000 frames, It seems that cntk will keep all the results computed from first layer to the last. Could cntk improve the evaluation  to reduce memory cost?

**Comment by dongyu888** [comment]
You should use truncated BPTT, setting truncated to true and adjust minibatchsize to the truncation size as well as nbruttsineachrecurrentiter to the number of parallel utterances. See  <https://github.com/Microsoft/CNTK/wiki/HTKMLF-Reader> https://github.com/Microsoft/CNTK/wiki/HTKMLF-Reader

 

You need to make sure putting them outside of the reader and sgd block (i.e., shared by both sgd and reader). I think we also have example setups in the repository.

**Comment by ghrj** [comment]
Thanks for your prompt reply. I think I didn't make it clear that I used these tricks you refered to in training. The problem of consuming too much memory occurred during decoding. One cell in the LSTM layer only takes the input of current frame and  the activation and the state of one frame before as input. But evaluation interface seems to keep all information before current frame. 
My network is kind of big. So keeping all information of one utterance makes the decoding painful. Is there any method to resolve this problem?

**Comment by dongyu888** [comment]
Wayne had a fix some time ago and it should work if it’s uni-directional LSTM and you set the minibatchsize to some small value?

**Comment by ghrj** [comment]
Thanks, I will have a try with the latest version.
