### ISSUE TITLE
EvaluateMultipleModels exception with files Train-28x28_cntk_text

### ISSUE THREAD

**Issue by 256zib** [Microsoft/CNTK#632]
Hi!
I downloaded files Test-28x28_cntk_text.txt and Train-28x28_cntk_text.txt
When i runing project CSEvalClient, i have error in funtion EvaluateMultipleModels in line int expected = int.Parse(line.Substring(0, line.IndexOf('\t'))); System.ArgumentOutOfRangeException
In this files not '\t' symbol. 
How to solve this problem?

Thanks

**Comment by gaizkan** [comment]
Hi,
The format on the Test-28x28_cntk.txt file is different than the Test-28x28.txt file. Before (Test-28x28.txt ) the first number was the label index followed by the feature data (all delimited by tab character). The current file (Test-28x28_cntk.txt ) uses the [CNTK Text Format Reader](https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader) file format.
I will update the CSEvalClient to reflect the new format and file.
Thanks,
Gaizka

**Comment by 256zib** [comment]
Thanks!

Thanks it just what I thought :+1:
