### ISSUE TITLE
Problem with FlattenDimensions function

### ISSUE THREAD

**Issue by pwodzu** [Microsoft/CNTK#636]
I try to use the FlattenDimensions input [100 x 100 x 32 x *] as below
 y = FlattenDimensions(inp, 10000, 32) 

Unfortunatelly, I get the exception:
 [CALL STACK]

> Microsoft::MSR::CNTK::ComputationNetwork:: ValidateNode
> - Microsoft::MSR::CNTK::ComputationNetwork:: ValidateNodes
> - Microsoft::MSR::CNTK::ComputationNetwork:: ValidateNetwork
> - Microsoft::MSR::CNTK::ComputationNetwork:: CompileNetwork
> - Microsoft::MSR::CNTK::ComputationNetwork:: ConstructFromRoots
> - Microsoft::MSR::CNTK::ComputationNetwork:: ComputationNetwork
> - std::make_sharedMicrosoft::MSR::CNTK::ComputationNetwork,std::shared_ptr<Microsoft::MSR::ScriptableObjects::IConfigRecord const & __ptr64>
> - Microsoft::MSR::ScriptableObjects::MakeRuntimeObjectMicrosoft::MSR::CNTK::ComputationNetwork
> - :: operator ()
> - std::_Callable_obj<,0>::_ApplyXstd::shared_ptrMicrosoft::MSR::ScriptableObjects::Object,std::shared_ptrMicrosoft::MSR::ScriptableObjects::IConfigRecord
> - std::_Func_implstd::_Callable_obj<<lambda_56a46857eb9bf0001b5ffab01c6f03ed,0>,std::allocatorstd::_Func_classstd::shared_ptr<Microsoft::MSR::ScriptableObjects::Object,std::shared_ptrMicrosoft::MSR::ScriptableObjects::IConfigRecord>,std:: shared_pt
> - std::_Func_classstd::shared_ptrMicrosoft::MSR::ScriptableObjects::Object,std::shared_ptrMicrosoft::MSR::ScriptableObjects::IConfigRecord:: operator ()
> - Microsoft::MSR::BS:: Evaluate
> - :: operator ()
> - std::_Callable_obj<,0>::_ApplyXMicrosoft::MSR::ScriptableObjects::ConfigValuePtr
> - std::_Func_implstd::_Callable_obj<<lambda_a048d19f5114b6bccccaea8ea1203939,0>,std::allocatorstd::_Func_classMicrosoft::MSR::ScriptableObjects::ConfigValuePtr,Microsoft::MSR::ScriptableObjects::ConfigValuePtr>:: _Do_call

EXCEPTION occurred: SmallVector: index overflow

How to use FlattenDimensions properly?

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.
