### ISSUE TITLE
Cuda 7.5 vs 8.0 with pre-compiled binaries? 

### ISSUE THREAD

**Issue by PeterGriffioen** [Microsoft/CNTK#644]
The documentation is explicit on requiring Cuda 7.5 to be installed for the development environment. However is Cuda 8.0 ok if only using the pre-compiled binaries or is this likely to cause issues? I've just installed a Nvidea GTX1080 on my workstation which seems to work OK with the pre-compiled GPU version of CNTK but perhaps not as fast as I expected. My laptop with a NVidea GTX960M on Cuda 7.5 is just as fast.  Should I install Cuda 7.5 over the shipped Cuda 8.0  on the workstation?

Thanks in advance.

**Comment by PeterGriffioen** [comment]
Well as far as I can tell, the cntk binary for GPU doesn't seem to care if Cuda 8.0 instead of 7.5 is installed. I supposedly have installed cuda 7.5 (as per the instructions on the Winodws setup page) using default install of the 7.5 driver. The graphic driver version changed to a prior version, but the NVidea software is still reporting Nvidea Cuda (NVCuda.dll) version 8.0. Hmm. Regardless the software works. 

The GPU-Z software gave an insight as to why the Laptop is as fast as the Workstation. The i7 on the laptop is much faster than the 5-yr old i7 on the workstation. The laptop GPU get to 86% loading for about 50% of the time on one of my test runs. On the same run, the workstation GPU (the  nice GTX1080) gets to 50% loading about 10% of the time. Thus the CPU is the bottleneck but for bigger problems (which are what I hope to implement) the workstation has way more GPU headroom.

**Comment by PeterGriffioen** [comment]
The only recommendation I'd make to installing the Cuda 7.5 driver is that if you plan on also installing Visual Studio 2013 (which is free btw), install VS Studio 2013 first as the Cuda 7.5 driver install also sets up the development environment for VS2013.

**Comment by PeterGriffioen** [comment]
I've re-opened this as I've just realised that models with convolution (eg MNIST 02_Convolution.cntk) will not converge on this machine. See https://github.com/Microsoft/CNTK/issues/655

DeviceQuery shipped with Cuda 7.5 reports:

CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1080"
  CUDA Driver Version / Runtime Version          8.0 / 7.5
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 8192 MBytes (8589934592 bytes)
MapSMtoCores for SM 6.1 is undefined.  Default to use 128 Cores/SM
MapSMtoCores for SM 6.1 is undefined.  Default to use 128 Cores/SM
  (20) Multiprocessors, (128) CUDA Cores/MP:     2560 CUDA Cores
  GPU Max Clock rate:                            1734 MHz (1.73 GHz)
  Memory Clock rate:                             5005 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 5 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = GeForce GTX 1080
Result = PASS

So is "CUDA Driver Version / Runtime Version 8.0 / 7.5" ok or do I need to somehow get " CUDA Driver Version / Runtime Version   7.5 / 7.5" installed on my workstation as it is on my laptop?

**Comment by PeterGriffioen** [comment]
OK so I can answer my question here with the aid of frankseide (MS). While I tried to install older Cuda drivers, NVidia recognised that my card is newer and installed the newer drivers anyway. It seems these Pascal card and the older drivers don't mix.  They also need cuDDn 5.0 whereas CNTK currently only supports cuddn 4.0. (See Issue #655). So it seems that the Pascal NVidia cards don't work correctly with the current CNTK but frankseide (MS) assures me that soon enough, it will. They have development machines working with it now. Can't wait....

**Comment by oxrider** [comment]
@PeterGriffioen Can you elaborate on how you made the CNTK work with your gtx1080? I've been trying to make it work but always throws CURAND_STATUS_LAUNCH_FAILURE (CURAND 201) error. Thank you a lot!

**Comment by PeterGriffioen** [comment]
@oxrider I was just using the supplied compiled CNTK executable as of about 1 month ago. I haven't tried the latest version as I've been busy with other things and I'm waiting for the fix. It only worked with simple NNets and failed to converge when the model contained convolution.

**Comment by oxrider** [comment]
@PeterGriffioen Thank you a lot :)

**Comment by oxrider** [comment]
@PeterGriffioen Which binary were you using?

**Comment by PeterGriffioen** [comment]
Built time: Jun  6 2016 13:19:04
		Last modified date: Sat Jun  4 21:28:41 2016
		Build type: Release
		Build target: GPU
		With 1bit-SGD: no
		CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
		CUB_PATH: c:\src\cub-1.4.1
		CUDNN_PATH: c:\NVIDIA\cudnn-4.0\cuda
		Build Branch: HEAD
		Build SHA1: b7ed8dc9e5cd8ab35f4badae86dd42e93e9f2564
		Built by svcphil on Philly-Pool2
		Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\

And here's my banged-together front end (in VB .Net) to run the models quickly showing a 2 layer NNet working on the GPU.. It doens't converge if convolution is used.

![image](https://cloud.githubusercontent.com/assets/18395419/17551764/4e252360-5f3f-11e6-908d-b25d8b3cbc79.png)

**Comment by oxrider** [comment]
hmm... I'm using the same executable but is getting some error the simplest example... I guess I'll have to wait for the new release also

**Comment by PeterGriffioen** [comment]
I have a MSI 1080 and I specifically did not install any drivers or software supplied with it. All of the drivers and software related to the card were downloaded from NVidia directly. It appears your error is from a NVidia library so this may be relevant.

**Comment by oxrider** [comment]
I'm using a ASUS 1080 and am also using drivers from NVidia. I've managed to borrow a 980Ti from my friend so my CNTK is up and running fast :D
