### ISSUE TITLE
Simple Example for LSTM based chart forecasting.

### ISSUE THREAD

**Issue by dmitrydnk** [Microsoft/CNTK#647]
Hello.

Can you please add ana simple example of forecasting charts based on LSTM. I found a piece of code in https://github.com/Microsoft/CNTK/wiki/Tutorial2 , but it's not enough to understand for me, how it;s work with chart forecasting. Others examples are more for text and voice recognition.

If it's possible can you an example for forecasting some mathematical function, 
for example f(t) = sin(t) / t .
as a train data i want to values like
1 | t 1 | f 0.84
2 | t 1.1 | f 0.81
....

Thanks.

**Comment by zpbappi** [comment]
I have just pushed a very simple setup for learning and predicting `sin(x)/x` using LSTM+CNTK [here](https://github.com/zpbappi/simple-cntk-lstm). It is using a very basic setup with just one LSTM unit and is _nowhere-near-well_ in prediction. But, I hope it would help you building a meaningful network. :)

Training (train.txt) and validation (validate.txt) data are pre-generated using the python script included in the repo. Test (test.txt) data is manually entered.

**Comment by drcrook1** [comment]
Be great if there were a python version of this.

**Comment by zpbappi** [comment]
@drcrook1 you can use [this](https://github.com/Microsoft/CNTK/blob/v2.0/Tutorials/NumpyInterop/FeedForwardNet.py) example as reference for generating the data using numpy and [this](https://github.com/Microsoft/CNTK/blob/v2.0/Examples/SequenceClassification/SimpleExample/Python/SequenceClassification.py) example as a reference to use LSTM from python. These examples (and many more) are available [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Examples).

**Comment by chrispugmire** [comment]
Sadly zpbappi's example code doesn't use sequenced data (the data file is a list of sequences each with one point), so it's basically broken and should not be used as a guide for doing LSTM in c#,  If someone could correct it that would be awesome as a good example would be very useful.
