### ISSUE TITLE
Image Caption by CNTK

### ISSUE THREAD

**Issue by suzukiR** [Microsoft/CNTK#649]
I'd like to make ImageCaption by CNTK.
For example CaptionBot provided with Microsoft.
I know consturuct of caption whitch is composed of  CNN and LSTM.

I have two questions.
①Now, Can We make ImageCaption by using CNTK ?
②if answer  of  question1  is yes we can , please tell me an outline to implement it.

I saw this issues 
"How to implement image captioning? #238(https://github.com/Microsoft/CNTK/issues/238)"
Now, Not changed it ?

**Comment by frankseide** [comment]
Hi, sorry for not responding earlier. Today it should indeed be possible. CNTK can now read data from multi-modal data streams.

Do you have a specific model in mind?

**Comment by suzukiR** [comment]
Thank you reply!

I'd like to make ImageCaption System by CNTK now.
I have been trying two approaches. but too difficult.
①show and tell (https://arxiv.org/abs/1411.4555)
②Rich Image Caption in the Wild
(http://www.cvfoundation.org/openaccess/content_cvpr_2016_workshops/w12/papers/Tran_Rich_Image_Captioning_CVPR_2016_paper.pdf)

model-①
![show and tell model](https://cloud.githubusercontent.com/assets/20038618/17166814/32529b1c-5414-11e6-898b-d1f3e6f83e9a.png)

model-②
![rich image caption in the wild](https://cloud.githubusercontent.com/assets/20038618/17166876/941d9464-5414-11e6-95a0-546ce9847504.PNG)

Can We make Image Caption System by CNTK ?
even trivial things information, anything, please tell me.

**Comment by sumitsony** [comment]
I am also trying. Let me know, should you make some substantial progress. Thanx
