### ISSUE TITLE
Generative text models

### ISSUE THREAD

**Issue by simra** [Microsoft/CNTK#652]
I found this blog post on LSTM-based character-by-character generation really interesting:
http://karpathy.github.io/2015/05/21/rnn-effectiveness/
I'd love to try something similar with CNTK but I'm not sure where to start with respect to creating input sequences.  In my particular case I'm interested to build a generative model for code.  Any pointers would be most appreciated.  I'd be happy to contribute a sample back if we can get it to work on some OSS code base.

**Comment by wolfma61** [comment]
The Tutorials as well as the Samples section in the documentation are a good starting point.
https://docs.microsoft.com/en-us/cognitive-toolkit/tutorials
https://docs.microsoft.com/en-us/cognitive-toolkit/Examples
