### ISSUE TITLE
How to create a random permutation matrix?

### ISSUE THREAD

**Issue by hsiao06** [Microsoft/CNTK#653]
As title, is it possible to create a random permutation matrix under CNTK? I'm looking for a way to do the following equivalent Matlab code:

A = eye( N );
idx = randperm(N);
A = A(idx, :);

The random permutation matrix is then used to permute a vector.

Although it's possible to create these matrices before and load them into CNTK, I'm looking for a better way to do that since I would like to experiment with multiple permutation matrices and dimension, etc. It would be a lot easier if it can be done in CNTK

Thanks!

**Comment by hsiao06** [comment]
It seems that CNTK cannot generate these permutation matrices. I tried to generate them first and load them into CNTK with the following command:

permute[i:1..numCopies] = Parameter(cellDim, cellDim, learningRateMultiplier=0.0, init='fromFile', initFromFilePath='/tmp/p' + i + '.txt');

but CNTK complains 

EXCEPTION occurred while evaluating: exp_cntk/sstNO/nn.ndl(62): operator + cannot be applied to these operands

so I assume array index cannot be used to specify a file name? If that's the case, I'm afraid I'm stuck and I really need some help. Thanks...

**Comment by joshuastobaugh57** [comment]
I'm learning as much as possible by reading? Deep stuff

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release, Python supports makes many of these problems a lot easier to solve.

If you still run into problems, please open a new issue.
