### ISSUE TITLE
How to input 3D image

### ISSUE THREAD

**Issue by comboy99** [Microsoft/CNTK#654]
Hi, I'm trying to use our data (many MRI data) to CNTK.
In common, MRI format is usually .nii, or .img and when we see the raw data it is 3 dimensional data and I can convert the data to tiff format (stacked 2D data). however, I don't know it is possible to input tiff format to cntk. even though i read imagereader wiki page, there is no detailed description.
So, how to input 3d image data to cntk?

**Comment by KolyaIvankov** [comment]
I'm not a pro of CNTK, but let me have a guess. So, the input data for the CNTK is 1-dimensional. If your data in effect consists of pixels, you'll just need to transform these array of pixels into a string (for each shot). There is an [example](https://msdn.microsoft.com/en-us/library/aa969817(v=vs.100).aspx) of how to (de)code a tiff file to get a bitmap, and out of this bitmap you can get a CNTK-understandable text file.
