### ISSUE TITLE
Convolution on Nvidia GTX1080 not converging

### ISSUE THREAD

**Issue by PeterGriffioen** [Microsoft/CNTK#655]
I have a problem with cntk GPU maintaining high errors throughout the run on the MNIST  02_Convolution.cntk example. I suspect this is related to https://github.com/Microsoft/CNTK/issues/644.

CNTK (gpu) on my workstation quite happily makes the 01_OneHidden.cntk example and other non-convolution models I've made. CNTK (cpu) works well with all models. 

I have followed all of the steps on the Setup for Windows page to the best of my ability, without installing the optional sections.
 
My workstation has a new Nvidia GTX1080 installed. It says it has cuda 8.0 installed no matter how many times I try to overwrite cuda 7.5 as per the instructions on the setup page. Regardless the cuda 7.5 program deviceQuery, which was compiled on the workstation, runs with a positive result.

CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1080"
  CUDA Driver Version / Runtime Version          8.0 / 7.5
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 8192 MBytes (8589934592 bytes)
MapSMtoCores for SM 6.1 is undefined.  Default to use 128 Cores/SM
MapSMtoCores for SM 6.1 is undefined.  Default to use 128 Cores/SM
  (20) Multiprocessors, (128) CUDA Cores/MP:     2560 CUDA Cores
  GPU Max Clock rate:                            1734 MHz (1.73 GHz)
  Memory Clock rate:                             5005 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 5 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = GeForce GTX 1080
Result = PASS

All models work fine on my laptop which is native cuda 7.5.

My questions are:
1) is this a "CUDA Driver Version / Runtime Version 8.0 / 7.5" problem?
2) Has anyone got a  GeForce GTX 1080 successfully running models?

**Comment by PeterGriffioen** [comment]
The silence is deafening! After some more digging, it seems that CNTK uses cuDNN 4.0. 

From the NVidia developers page (login required): 
"If you are using cuDNN with a Pascal (GTX 1080, GTX 1070), version 5 or later is required."
==========================================================

Thus it appears that CNTK CANNOT work with the latest and fastest consumer GPUs available. I find this out after weeks of developing front-end data extraction and model-running code based on CNTK and then spending $1200AUD (of my personal money)  specifically on a graphics card to run CNTK. Not happy!

Any word on when these card will be supported?

**Comment by frankseide** [comment]
We are running cudnn 5 internally already. I will ask the team when this is slated for release, or alternatively, if there is a branch you can use until then.

**Comment by PeterGriffioen** [comment]
Hey thanks heaps. Sorry to sound so disappointed but I was really getting into CNTK, got committed and then suddenly wondered if I'd gone the wrong path. As long as it's coming soonish I'll be happy enough. All of my tools are Windows based and I'm adding DL models to those. I'm happy to use your executables for modelling  and the EvalWrapper for applying the models rather than making a full integrated product myself. So as long as those are also kept up to date I'd be very appreciative. For the moment I'll prototype on laptop which works well. Thanks again.

**Comment by frankseide** [comment]
BTW AFAIK the change was relatively simple. One needs to upgrade the project to cuDNN 5 (I don't know how to do that) and then do minor fixes in a handful of places where NVidia has changed the function prototypes.

**Comment by PeterGriffioen** [comment]
Well that would be great if it could be implemented easily because according to NVidia, there are large performance gains to be had by going to 5.0/5.1.

**Comment by chrisbasoglu** [comment]
cuDNN 5.0 support will hit source code on July 29 (or very near to it).  It will hit binary drops a few weeks after that.

**Comment by DanielMerget** [comment]
@chrisbasoglu Is this already in master by now (or any update on the date)? Can't wait to use my 1080s with CNTK ;-)

**Comment by chrisbasoglu** [comment]
We are working on it.  CuDNN5 includes some changes that if not worked around properly cause a perf degradation in certain situations.  If it were not for that, this would have already been released.  I expect about 1 more week.

Chris

**Comment by oxrider** [comment]
@chrisbasoglu Is it out by now? Can't wait to use my 1080 :) 
BTW is there a branch I could use if I don't mind the performance degradations? I would love to start utilizing my 1080 by now. 

Thank you very much! And thank you for this amazing project!

**Comment by chrisbasoglu** [comment]
We are currently on target for a 8/19 release.  For an unsupported peak in a branch, look at: mahilleb/CuDnn5Test off of master.

Chris
