### ISSUE TITLE
Problem about HTKMLFwriter.

### ISSUE THREAD

**Issue by oscarzbz** [Microsoft/CNTK#656]
Hellow all. I have already trained a CN with the data (htk format) produced by myself. The next, I want to put the CN into actual use with CNTK. I have already tryed the HTKMLFreader.
The NDL snippet is as below:

>     W = Parameter(labelDim, hiddenDimcnn, init="uniform", initValueScale=1);
>     b = Parameter(labelDim, 1,         init="fixedValue", value=0);
>     LSTMoutputW = Plus(Times(W, h1_d), b);
> 
>     ce = CrossEntropyWithSoftmax(labels, LSTMoutputW);
>     err = ErrorPrediction(labels, LSTMoutputW);
>     
>     logPrior = LogPrior(labels)
>     scaledLogLikelihood = Minus(LSTMoutputW, logPrior)
>     
>     # Special Nodes
>     FeatureNodes = (features)
>     LabelNodes = (labels)
>     CriterionNodes = (ce)
>     EvalNodes = (err)
>     OutputNodes = (scaledLogLikelihood)
 
The Config file snippet is as below:

> 	    writer=[
> 		        writerType="HTKMLFWriter"
> 	        	LSTMoutputW =[
> 			      dim=8
> 		       	scpFile="$DataDir$/20160706write.scp"
> 		        ]
>      	]

Next, I got the chunk file and then plotted it. And ........problem appeared.
Numbers in same dimension and different frames in chunk file (outputted by HTKMLFwriter) were all the same.
Is there anybody can tell me ,how to write the computational result of a new data through CNTK?

**Comment by frankseide** [comment]
Two questions: (1) do you have evidence that the model trained well, e.g. objective converging? And (2) is this on CPU or GPU?

There are known bugs in (a) the ACML library with newer Intel CPUs and (b) NVidia's GPU jitter for compute capability < 3.0, which both manifest as the same value being output for all inputs.

If you run on CPU, please set an environment variable ACML_FMA=0. If you run on GPUs, please use a newer GPU of compute capability 3.0 or higher.

**Comment by oscarzbz** [comment]
⊙_⊙！ Thanks alot ,it really helps.
