### ISSUE TITLE
Question with Tutorial1

### ISSUE THREAD

**Issue by epslong** [Microsoft/CNTK#658]
I'm attaching the config file I'm trying out with the tutorial 1. But when running it, I kept running into the error saying "Exception occurred: TrainOrAdaptModel: No criterion node was specified". This is a confusing error message because the criterion node has been specified in the config file. 

Please help. Thanks! 

[LogisticsRegressionSimple.txt](https://github.com/Microsoft/CNTK/files/355784/LogisticsRegressionSimple.txt)

**Comment by chrisbasoglu** [comment]
This usually occurs when you are running the new config files in the tutorial against an old binary.  Can you try the latest binary or update your source?
