### ISSUE TITLE
how to disable the dump information when using managed evaluation interface?

### ISSUE THREAD

**Issue by goodtogood** [Microsoft/CNTK#659]
it always prints a lot dump messages when running c# evaluation  example , how to disable this ?

> .....
> 114 out of 192 nodes do not share the minibatch layout with the input data.
> 
> Post-processing network complete.
> 
> 
> 
> Allocating matrices for forward and/or backward propagation.
> 
> Memory Sharing Structure:
> 
> ......

THX

**Comment by gaizkan** [comment]
Normally when running CNTK.exe you can add, to the command line, a switch for redirecting the [output](https://github.com/Microsoft/CNTK/wiki/Top-level-configurations#stderr). However, we currently don't have that switch in the evaluation engine. We have added a similar feature as part of our requirements for a future release.

**Comment by goodtogood** [comment]
OK, I got it .
THX
