### ISSUE TITLE
what's the effect of changing 'nbruttsineachrecurrentiter' during training

### ISSUE THREAD

**Issue by staplesinLA** [Microsoft/CNTK#661]
If i change the nbruttsineachrecurrentiter between epoches,  except for speedup , will it bring some other effects to final performance ?

**Comment by staplesinLA** [comment]
I trained a regressionRNN network(truncated= false) to predict frame-level states . 
I found that start training with nbruttsineachrecurrentiter=1 and nbruttsineachrecurrentiter=16 will get totally different two MSE range . And  i changed 1 to 16 in midway (like stop training in epoch 1 and restart it  ), the MSE will follow tha former range. 
Could anyone explain the relations among 'Truncated''MBsize'and 'nbruttsineachrecurrentiter' in CKTK RNN? Cuz i'm not sure they are the exactly the same with those in papers .

**Comment by dongyu888** [comment]
MBSize means truncation size and nbruttsineachrecurrentiter means number of parallel sequences in the same minibatch.

**Comment by staplesinLA** [comment]
@dongyu888 thanks!  So if set Truncated to false, the MBsize will be ingored and the shorter parallel sentences will be padded with zeroes??

**Comment by vmazalov** [comment]
MBSize will not be ignored, the reader will try to pack whole sequences within the MBSize constraint, possibly packing several sequences in the same channel.

BTW, nbruttsineachrecurrentiter config is not available in all readers. Speech readers have it, and some other readers.
