### ISSUE TITLE
CNTK evaluation library (EvalDLL.dll, CreateNetwork on Windows) example or documentation error.

### ISSUE THREAD

**Issue by Henry-White** [Microsoft/CNTK#662]
Hello,
I suppose it's an example or documentation error. If you try to call CreateNetwork only with path (as pointed out in the CPPEvalClient.cpp) it will return an error "permission denied", but if you try to use full path to model with file_name, like "c:\cntk\output\simple.dnn". 
If it's known bug this issue could be closed.

**Comment by gaizkan** [comment]
Thank you for the feedback. 
The example converts the relative path to a full path based on the current working directory. As a clarification for other users looking at this issue. The path must be an absolute path, examples of valid paths:
\\MyBox\MyFolder\model.dnn
C:\MyFolder\model.dnn

Mapped drives do not convert properly to full paths, so you wouldn't be able to leverage them. Example of invalid paths:
Z:\MyFolder\model.dnn    (where Z is a mapped drive)

A relative path will not work either. Examples of (invalid) relative paths:
.\MyFolder\model.dnn

Another clarification is that CreateNetwork must be passed a string containing the "modelPath=<filepath>" attribute specifying the model's file path.

The documentation has been clarified with regards to this last point.

Thanks.
