### ISSUE TITLE
How to specify a threshold-based accuracy metric for evaluating a regression problem via the CNTK executable?

### ISSUE THREAD

**Issue by CPostelnicu** [Microsoft/CNTK#664]
Hi, 

I am training a convolutional network for a regression problem. I am using the CNTK executable to evaluate the model. I would like my output error count to express the equivalent of: 

`sum((labels-predictions)<THRESHOLD)`

 i.e. how many predictions fall within an "acceptable" distance from the threshold.  

For my particular problem, both "labels" and "predictions" are 1 column vectors the length of the test set.

Is there a way to / How could I modify my configuration file to express this?

(I tried: 

`err = SumElements(Minus(labels, predictions)<Const(0.1))`, 

which resulted in
_EXCEPTION occurred: Undefined function or macro '<Const' in <Const(0.1)_.)

**Comment by zpbappi** [comment]
In the version I am using (1.5 release), it is called `Constant`, instead of `Const`. I am not sure which version you have. But from the error message, it seems like you don't have the `Const` either. Try changing it to `Constant`.

**Comment by CPostelnicu** [comment]
I am using 1.5 release. The same exception message is triggered with `Constant `instead of `Const`.

Probably the issue has to do with getting boolean values from a vector using "<".  Is this currently expressible via NDL functions?

**Comment by zpbappi** [comment]
Yes. `Less`, `Greater`, etc. functions are there.

Regards,
Zp Bappi
Senior Developer | Readify
m: +61 469 390 795 | e: zpbappi@readify.net | w: readify.net

**Comment by CPostelnicu** [comment]
I had got confused because Less/ LessThan are not listed in the [book](https://github.com/Microsoft/CNTK/blob/master/Documentation/CNTK-TechReport/lyx/CNTKBook-20160217..pdf). (Is there an updated version of the documentation?)

 I get the same error. Tried both Less and LessThan.  Did you work with these? Because if they worked for you, maybe there is something wrong with my current installation. 

So far I have succesfully used ""LessThan" within the SGD block to configure early stopping (`reduceLearnRateIfImproveLessThan` - type params). No problems there.

**Comment by zpbappi** [comment]
I just tried. 
```
err = SumElements(Less(Minus(labels, h), Constant(0.1)))
```
and
```
err = SumElements(Less(labels - h, Constant(0.1)))
```
both variants work. I tried using current master branch source code (built in my machine) and also the latest release 1.5. Both work without any issue.

For function reference, [Full Function Reference](https://github.com/Microsoft/CNTK/wiki/Full-Function-Reference) is a good start. But, once you get familiar with functions and BrainScripts, you can always check the source [here](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) for available functions. Please keep in mind, that it is in master branch only. Does not necessary mean that it is available in the latest release.

**Comment by CPostelnicu** [comment]
Thanks a lot!
