### ISSUE TITLE
MNIST example with no effect

### ISSUE THREAD

**Issue by snurkabill** [Microsoft/CNTK#666]
Hi, 

I've tried to run MNIST example from 1.5 release and it didn't do anything, even with original setup -> The example runs, there is 30 epochs, no parameteres changed, form original script, at all. Problem is, that error is still around 0.89 (89%) - which is for MNIST model with no performance. 

I ran it on windows 10 with CPU-only 1.5 release (I also tried GPU version even I don't have GPU here).

On second PC (with GPU, windows 8.1) it runs well on GPU and CPU. 

What am I doing wrong? Any advice? I've tried many things and now I am hopeless.

**Comment by JohnCraigPublic** [comment]
Maybe its the  "setx ACML_FMA 0" thing as discussed in #638  ?

**Comment by snurkabill** [comment]
that's it, thanks! 

setx ACML_FMA 0 and reboot helps.

**Comment by JohnCraigPublic** [comment]
you could 'close' this issue...
