### ISSUE TITLE
EvalDll.dll for 32-bit?

### ISSUE THREAD

**Issue by JohnCraigPublic** [Microsoft/CNTK#667]
I wrote a test program to use EvalDll to evaluate the MNIST model and got it working.  But, it has to be built in "release" and "x64" in order to work.   I was hoping to call EvalDll from a 32-bit application that I have.   Is there a 32-bit version of EvalDll available?   Thanks.

**Comment by frankseide** [comment]
We do not support building for 32 bit. You could try to just create a 32-bit version of the Visual Studio Solution and see whether it builds (you'd also need to get 32-bit versions of the dependencies, i.e ACML or MKL etc.).
