### ISSUE TITLE
How to describe the concatenation of multiple layers?

### ISSUE THREAD

**Issue by tensor5375** [Microsoft/CNTK#668]
I want to describe concatenation of multiple layers like below.
https://cloud.githubusercontent.com/assets/20441090/16806589/066396ec-4950-11e6-950d-09edf72f1b06.png

How can I do?

**Comment by zpbappi** [comment]
You are probably looking for `Slice` and `RowStack`.

Assuming you have 4 input features and 2 output dimensions and you want to split the input features into two parts (say, 2 features in both partitions), here is an example network definition for the picture you referred to:
```
features = Input(4)
labels = Input(2)

input1 = Slice(0, 2, features)
input2 = Slice(2, 4, features)

b1 = Parameter(2, 1, init="uniform")
w1 = Parameter(2, 2)
h1 = w1 * input1 + b1

b2 = Parameter(2, 1, init="uniform")
w2 = Parameter(2, 2)
h2 = w2 * input2 + b2

w = Parameter(2, 4)
b = Parameter(2, 1, init="uniform")
h = w * RowStack((h1:h2)) + b

ce = SquareError(h, labels)

criterionNodes = (ce)
```

**Comment by tensor5375** [comment]
Thanks for your excellent reply!
I'll try it.
Really thanks.
