### ISSUE TITLE
Wrong demo "03_ConvBatchNorm.config "   in MNIST data

### ISSUE THREAD

**Issue by nejyeah** [Microsoft/CNTK#67]
Error "EXCEPTION occurred: Undefined function or macro 'ConvReLUBNLayer' in ConvReLUBNLayer(featScaled, cMap1, 25, kW1, kH1, hStride1, vStride1, 10)"

In the network defined file "03_ConvBatchNorm.ndl", It says:
```
# ConvReLUBNLayer is defined in Macros.ndl
conv1 = ConvReLUBNLayer(featScaled, cMap1, 25, kW1, kH1, hStride1, vStride1, 10)
```

Actually, The function "ConvReLUBNLayer"  is not defined in the "Macros.ndl"!!!

**Comment by Alexey-Kamenev** [comment]
Hello,
Thank you, we aware of that problem, the fix will be merged soon (tomorrow most likely).

**Comment by yefeng-zheng** [comment]
I also ran into this problem. Actually, several examples couldn't run. Another example is CIFAR-10. I couldn't run 03_ResNet.config and 04_ResNet_56.config. Do you have any plan to fix this too? Thanks!

**Comment by Alexey-Kamenev** [comment]
Can you please sync with the latest master and try again MNIST 03_ConvBatchNorm sample?

**Comment by yefeng-zheng** [comment]
I just tried. Yes, MNIST 03_ConvBatchNorm works now.

Just want to know. Have you fixed the problem in running sample CIFAR-10 03_ResNet.config and 04_ResNet_56.config? Thanks!

**Comment by frankseide** [comment]
Yefeng, i you still have problems with the ResNet configs, would you mind opening a separate Issue for it?
