### ISSUE TITLE
Error opening file exception when running CPPEvalClient.exe and similar issues with CSEvalClient and failing unit tests

### ISSUE THREAD

**Issue by devinbostIL** [Microsoft/CNTK#670]
Hi,

I've configured CNTK with all of the recommended libraries (with exactly matching versions) as specified here: [(https://github.com/Microsoft/CNTK/wiki/Test-Configurations)]
So far, I've been very happy with CNTK, and I've been able to enable GPU acceleration and SGD and successfully build the models from all of the examples that I've attempted to build models from. 

I am, however, getting a number of the unit tests to fail; and when I try to run either CPPEvalClient.exe or CSEvalClient.exe, both of them crash during execution and for different reasons.

I've noticed only a few types of outputs for the failed tests. I have included the outputs here. I've also noticed that some of them specify missing files. 

Has anyone here seen any of these issues before? 
Also, where should I look to start to debug these?

![cntk_failing_unit_tests](https://cloud.githubusercontent.com/assets/19719649/16864320/eb3bad9a-4a18-11e6-9ea3-a29e4c3dfa28.PNG)
[cntk_crash_1.txt](https://github.com/Microsoft/CNTK/files/365235/cntk_crash_1.txt)
[cntk_crash_2.txt](https://github.com/Microsoft/CNTK/files/365236/cntk_crash_2.txt)
[MatrixInnerProductOfMatrices_failure.txt](https://github.com/Microsoft/CNTK/files/365240/MatrixInnerProductOfMatrices_failure.txt)
[CNTKTextFormatReader_Simple_dense.txt](https://github.com/Microsoft/CNTK/files/365243/CNTKTextFormatReader_Simple_dense.txt)
[HTKDeserializersSimpleDataLoop_failure.txt](https://github.com/Microsoft/CNTK/files/365248/HTKDeserializersSimpleDataLoop_failure.txt)
[HTKMLFReaderSimpleDataLoop_failure.txt](https://github.com/Microsoft/CNTK/files/365251/HTKMLFReaderSimpleDataLoop_failure.txt)

**Comment by devinbostIL** [comment]
Update: I noticed that I had forgotten to set the CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY environment variable, so I set that and all but one of the tests passed. (Please see attached file.)
[CNTKTextFormatReader_1x10_MI_1_dense.txt](https://github.com/Microsoft/CNTK/files/365307/CNTKTextFormatReader_1x10_MI_1_dense.txt)

I also noticed that CPPEvalClient.exe and CSEvalClient.exe are still crashing for the same reasons as in my initial post, however.

**Comment by zhouwangzw** [comment]
The CPPEvalClient.exe and CSEvalClient.exe require that the model file ../../Examples/Image/MNIST/Data/../Output/Models/01_OneHidden exist. You can run the example in <CNTK>/Examples/Image/MNIST to create the model. See readme.md there for details.

**Comment by zhouwangzw** [comment]
You also need additional models to run all examples in CSEvalClient. Please see the "<description>" part in Examples/Evaluation/CSEvalClient/Program.cs for details.

**Comment by gaizkan** [comment]
@devinbostIL, If I understand correctly, you can now run all Unit Tests (except for 1) as well as CPPEvalClient, and CSEvalClient?

The one unit test is failing with "CUDA failure 46:"

If you have the latest from Master, could you run CNTK.exe and provide the output header (it should contain information regarding your CPU/GPU).

Thanks.

**Comment by devinbostIL** [comment]
Hi Gaizka,

I still am unable to run CPPEvalClient, and I still am unable to run CSEvalClient; however, you're correct in that all unit tests except that first unit test are passing. I will gladly send you the CNTK.exe output headers in the morning when I'm in front of my computer.

Devin G. Bost
Senior Software Engineer
Imagine Learning
P  801.377.5071  |  C  503.473.1773
devin.bost@imaginelearning.com
www.imaginelearning.com<http://<br/>www.imaginelearning.com>

Sent from mobile

**Comment by devinbostIL** [comment]
I have confirmed that the MNIST files do exist:
![mnist_files](https://cloud.githubusercontent.com/assets/19719649/16880558/15216c44-4a73-11e6-9b66-dda6ba9a2277.PNG)

**Comment by devinbostIL** [comment]
Here is my CNTK header (as requested):
[CNTK_header.txt](https://github.com/Microsoft/CNTK/files/366535/CNTK_header.txt)

**Comment by zhouwangzw** [comment]
@devinbostIL: Are you running CPPEvalClient.exe from command line? Could you please try with ".\CPPEvalClient.exe", instead of "CPPEvalClient.exe" to start? 
I think there is a bug in retrieving path when launching the program without any path prefix. We will look into it. As workarund you can run the program with a path prefix, before the bug is fixed.

**Comment by devinbostIL** [comment]
Thanks for the help. Here's the output of running ".\CPPEvalClient.exe":
[CNTK_header_2.txt](https://github.com/Microsoft/CNTK/files/366563/CNTK_header_2.txt)

**Comment by devinbostIL** [comment]
Here's the output of running ".\CPPEvalClient.exe" from that same directory location:
[CNTK_header_2.txt](https://github.com/Microsoft/CNTK/files/366567/CNTK_header_2.txt)

**Comment by devinbostIL** [comment]
@zhouwangzw It appears that there are two separate issues: the first involving the path bug that you mentioned, and the second involving something else. 
Regarding the something else, I have attached the output of running ".\CSEvalClient.exe" from the same directory.
[CNTK_CSEvalClient_Crash.txt](https://github.com/Microsoft/CNTK/files/366580/CNTK_CSEvalClient_Crash.txt)

**Comment by devinbostIL** [comment]
Here's a better picture of the output of running CSEvalClient:
![corrupt_memory_cntk_1](https://cloud.githubusercontent.com/assets/19719649/16898364/104199b6-4b94-11e6-949b-d900864807d3.PNG)

**Comment by gaizkan** [comment]
Hi Devin,

You are still using ACML. Multi-model is not supported for ACML, please re-compile using MKL.

Refer to: [Setup MKL](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-your-machine) on how to do this.

Thanks,
Gaizka

**Comment by zhouwangzw** [comment]
@devinbostIL  The bug regarding path prefix in CPPEvalClient.exe has been fixed and checked into master. It should work when you start CPPEvalClient.exe without any path fix.

**Comment by devinbostIL** [comment]
Wonderful. Thank you!

Devin G. Bost
Senior Software Engineer
Imagine Learning
P  801.377.5071  |  C  503.473.1773
devin.bost@imaginelearning.com<mailto:devin.bost@imaginelearning.com>
www.imaginelearning.com<http://www.imaginelearning.com/>

[Imagine Learning]<http://www.imaginelearning.com/>

**Comment by devinbostIL** [comment]
After switching to MKL, in CSEvalClient.Program, if I comment out 
> EvaluateImageClassificationModel();
the program does not crash now. 

I have attached the output.

[CSEvalClient_Success_7-19-2016.txt](https://github.com/Microsoft/CNTK/files/371996/CSEvalClient_Success_7-19-2016.txt)

**Comment by gaizkan** [comment]
Hi Devin,

When running in the IDE, are you selecting a _CpuOnly configuration? (Debug_CpuOnly or Release_CpuOnly) Remember that Eval right now is supported only on the CPU.
The message:

    About to throw exception 'SelectDevice: Attempted to change device selection from -1 to -4 (-4 means 'auto').'
    Error: SelectDevice: Attempted to change device selection from -1 to -4 (-4 means 'auto').

is a possible indication of this.

With regards to the `EvaluateImageClassificationModel` can you post the log up to the point where it crashes?

Thanks,
Gaizka

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.
