### ISSUE TITLE
Gradient check failed?

### ISSUE THREAD

**Issue by leo603221** [Microsoft/CNTK#671]
I run the example "01_OneHidden.cntk" on windows with new version CNTK binary, it works fine. 
But when I change the setting as follows:

```
deviceId = -1
precision = "double"
SGD = [
      gradientCheck = true
]
```

some of the parameters can't pass gradientcheck, as follows:

```
dol.w Numeric gradient = 1.089973e-006, Error BP gradient = -7.956320e-006
EXCEPTION occurred: cannot pass gradient checker
```

Did anyone have the same problem with me?  
Or my setup of CNTK is not correct?

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.
