### ISSUE TITLE
Operands' shapes are not compatible

### ISSUE THREAD

**Issue by huy302** [Microsoft/CNTK#673]
I'm running the MNIST sample on CNN with Batch Norm, with the input data resized to 21x21 instead of 28x28, got the error

> EXCEPTION occurred: h1.t Times operation: Left [128 x 1568] and right [5 x 5 x 32] operands' shapes are not compatible.

My config file is as follow (copied from 03_ConvBatchNorm.ndl, with imageW and imageH set to 21 instead of 28)

```
# macros to include
load = ndlMnistMacros

# the actual NDL that defines the network
run = DNN

ndlMnistMacros = [
    imageW = 21
    imageH = 21
    labelDim = 10

    features = ImageInput(imageW, imageH, 1, imageLayout=$imageLayout$)
    featScale = Constant(0.00390625)
    featScaled = Scale(featScale, features)
    labels = InputValue(labelDim)

    scValue = 1
    # Batch normalization time constant (normalizationTimeConstant). blendTimeConstant is set through .cntk file.
    bnTimeConst = 1024

    convWScale = 10
    convBValue = 0
]

DNN = [
    # conv1
    kW1 = 5
    kH1 = 5
    cMap1 = 16
    hStride1 = 1
    vStride1 = 1
    # weight[cMap1, kW1 * kH1 * inputChannels]
    # ConvBNReLULayer is defined in Macros.ndl
    conv1 = ConvBNReLULayer(featScaled, cMap1, 25, kW1, kH1, hStride1, vStride1, convWScale, convBValue, scValue, bnTimeConst)

    # pool1
    pool1W = 2
    pool1H = 2
    pool1hStride = 2
    pool1vStride = 2
    pool1 = MaxPooling(conv1, pool1W, pool1H, pool1hStride, pool1vStride, imageLayout=$imageLayout$)

    # conv2
    kW2 = 5
    kH2 = 5
    cMap2 = 32
    hStride2 = 1
    vStride2 = 1
    # weight[cMap2, kW2 * kH2 * cMap1]
    conv2 = ConvBNReLULayer(pool1, cMap2, 400, kW2, kH2, hStride2, vStride2, convWScale, convBValue, scValue, bnTimeConst)

    # pool2
    pool2W = 2
    pool2H = 2
    pool2hStride = 2
    pool2vStride = 2
    pool2 = MaxPooling(conv2, pool2W, pool2H, pool2hStride, pool2vStride, imageLayout=$imageLayout$)

    h1Dim = 128
    fcWScale = 1
    fcBValue = 0
    # DnnBNReLULayer is defined in Macros.ndl
    h1 = DnnBNReLULayer(1568, h1Dim, pool2, fcWScale, fcBValue, scValue, bnTimeConst)
    ol = DNNLayer(h1Dim, labelDim, h1, 1)

    ce = CrossEntropyWithSoftmax(labels, ol)
    err = ErrorPrediction(labels, ol)

    # Special Nodes
    FeatureNodes = (features)
    LabelNodes = (labels)
    CriterionNodes = (ce)
    EvalNodes = (err)
    OutputNodes = (ol)
]
```

I guess the number 1568 is incorrect, however I have no clue on how to change it

Thanks
## 

Huy

**Comment by mfuntowicz** [comment]
Hi Huy, 

You correctly guessed that the parameter 1568 is incorrect. I'll try to explain how to compute this parameter : 

Your CNN looks like : 
- Your input : [21 * 21 * 3]
- Convolutional Layer, which give more depth or spatiality to your input : 
 - [21 * 21 * cMap1] => [21 * 21 * 16] 
- Pooling Layer, which, with your settings, divide the shape width and height by a factor of 2 : 
 - [21 * 21 * 16]  => [10 * 10 * 16]
- Convolutional Layer
 - [10 * 10 * 16] => [10 * 10 * 32]
- Pooling Layer, with your settings, divide the shape width and height by a factor of 2, again : 
 - [10 * 10 * 32] => [5 * 5 * 32]
- Full Connected Layer, each of the [5 * 5 * 32] features will be connected to this layer.
 - So you have: 5 * 5 * 32 features = **800**
 - In the initial case, with [28 * 28 * 3] input, it ends up with a shape [7 * 7 * 32] => **1586**

Hope it helps :)
Morgan

**Comment by huy302** [comment]
Hi Morgan

That explanation is exactly what I'm looking for
Could someone update the tutorial to include that?
I'm pretty sure many will face the same problem :)

Thanks

**Comment by frankseide** [comment]
We should switch this sample to BrainScript and then use these formulas explicitly.
