### ISSUE TITLE
Output PosteriorProb for MNIST example

### ISSUE THREAD

**Issue by huy302** [Microsoft/CNTK#674]
I would like to output predicted PosteriorProb form the model built in the MNIST example (03_ConvBatchNorm.cntk)
So I created a new action as follow

    Output=[
        action = "write"

        # Parameter values for the reader
        reader = [
            readerType = "CNTKTextFormatReader"
            file = "$TestFile$"
            input = [
                features = [
                    dim = $inputDim$
                    format = "dense"
                ]
                labels = [
                    dim = $outputDim$
                    format = "dense"
                ]
            ]
        ]

        outputNodeNames = PosteriorProb : labels
        outputPath = "$OutputDir$/SimpleOutput"

        format = [
            type = "category"
        ]
    ]

However, there is no PosteriorProb node to output
What is the node name that output PosteriorProb? and how do I figure it out? Is there a document on this?

Thanks

--
Huy

**Comment by JohnCraigPublic** [comment]
You may be asking the same thing that I asked in closed issue #601.    You want to get probabilities as output from a softmax operator on the last layer.  See #601 -- maybe it helps.

**Comment by huy302** [comment]
wow that is exactly what I'm looking for
Thanks for sharing

Cheers :)
