### ISSUE TITLE
Didn't anyone notice? The stack trace is broken.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#677]
Am I the only one who sees this?

> [CALL STACK]
> 
> > Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
> > -BaseThreadInitThunk
> > -RtlUserThreadStart
> 
> [CALL STACK]
>     > Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
>     - BaseThreadInitThunk
>     - RtlUserThreadStart
> 
> EXCEPTION occurred: Invalid command-line option '--help'.

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.

**Comment by Ark-kun** [comment]
Can you explain the rationale for polluting the issue tracker with duplicate issues?

Right now the only rationale I see is someone's commitment to mass-close hundreds of bugs in couple of weeks. If that's the reason, that's bad news for the project. Sweeping problems under the carpet or making them "disappear" would only make things worse.

P.S. And yes, this issue is still there and everyone sees it every time they make a mistake.

**Comment by wolfma61** [comment]
@Ark-kun - please let us know your suggestion. Call-Stacks work fine with recent build (and did so before). Your issue didn't contain any info on how to reproduce. 

If you can reproduce this with the latest build, please open a new issue with a repo case

thank you

**Comment by Ark-kun** [comment]
>Call-Stacks work fine with recent build (and did so before). 
I've never seen it working. 
Not in cntk.exe. (Previously, even running cntk.exe --help produced a crash and stack trace which was wrong.)
Not in BrainScript.
Not in python either.

Can you please show me a **correct** C++ call stack repro?

**Comment by Ark-kun** [comment]
@wolfma61 
I've just tested this in version 2.2 in python:

```
import cntk as c
c.sequence.reduce_sum(c.constant(0))
```

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-9-cfef45fc63e2> in <module>()
>       1 import cntk as c
> ----> 2 c.sequence.reduce_sum(c.constant(0))
> 
> C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.py in wrapper(*args, **kwds)
>      67     @wraps(f)
>      68     def wrapper(*args, **kwds):
> ---> 69         result = f(*args, **kwds)
>      70         map_if_possible(result)
>      71         return result
> 
> C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\sequence\__init__.py in reduce_sum(seq, name)
>     627     from cntk.cntk_py import sequence_reduce_sum
>     628     seq = sanitize_input(seq, get_data_type(seq))
> --> 629     return sequence_reduce_sum(seq, name)
>     630 
>     631 
> 
> ValueError: Axis::OperandSequenceAxis() sentinel cannot be resolved if the operand 'Placeholder('Placeholder25', [], [])' has no sequence axis or > 1 ordered dynamic axes.
> 
> [CALL STACK]
>     > CNTK::NDMask::  MaskedCount
>     - CNTK::NDMask::  MaskedCount (x3)
>     - CNTK::  Unpooling (x3)
>     - CNTK::Function::  ReplacePlaceholders
>     - CNTK::  Hardmax
>     - CNTK::Function::  ~Function
>     - CNTK::Evaluator::  TestMinibatch
>     - RtlRunOnceExecuteOnce
>     - InitOnceExecuteOnce
>     - _crtInitOnceExecuteOnce
>     - CNTK::Evaluator::  TestMinibatch
>     - CNTK::Function::  InitOutputs

Does this C++ call stack look correct?

**Comment by Ark-kun** [comment]
By the way, just a quick search of "TracingGPUMemoryAllocator::operator" in issues finds at least 20 matches.
https://github.com/Microsoft/CNTK/search?utf8=%E2%9C%93&q=TracingGPUMemoryAllocator%3A%3Aoperator&type=Issues
