### ISSUE TITLE
Docker build CPU & GPU Failing

### ISSUE THREAD

**Issue by Bren077s** [Microsoft/CNTK#678]
I have been trying to install both the cpu and gpu version of CNTK with the Dockerfiles, and they both end with the same error.

`creating /cntk/build/cpu/release/.build/Source/../Tests/UnitTests/EvalTests/EvalExtendedTests.o for Linux with build type release
mpic++ -c Source/../Tests/UnitTests/EvalTests/EvalExtendedTests.cpp -o /cntk/build/cpu/release/.build/Source/../Tests/UnitTests/EvalTests/EvalExtendedTests.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DCPUONLY -DNDEBUG -DNO_SYNC  -DUSE_OPENBLAS -DUSE_ZIP -msse4.1 -mssse3 -std=c++0x -fopenmp -fpermissive -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/usr/local/openblas/include -I/usr/local/lib/libzip/include -I/usr/local/opencv-3.1.0/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF /cntk/build/cpu/release/.build/Source/../Tests/UnitTests/EvalTests/EvalExtendedTests.d
In file included from Source/../Tests/UnitTests/EvalTests/EvalExtendedTests.cpp:6:0:
Source/../Tests/UnitTests/EvalTests/stdafx.h:26:36: fatal error: boost/test/unit_test.hpp: No such file or directory
 #include <boost/test/unit_test.hpp>
                                    ^
compilation terminated.
make[1]: *** [/cntk/build/cpu/release/.build/Source/../Tests/UnitTests/EvalTests/EvalExtendedTests.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/cntk'
make: *** [all] Error 2
The command '/bin/sh -c git clone --depth=1 -b master https://github.com/Microsoft/CNTK.git . &&     mkdir -p build/cpu/release &&     cd build/cpu/release &&     ../../../configure --with-openblas=/usr/local/openblas &&     make -j"$(nproc)" all &&     cd ../../.. &&     mkdir -p build-mkl/cpu/release &&     cd build-mkl/cpu/release &&     ../../../configure --with-mkl=/usr/local/CNTKCustomMKL &&     make -j"$(nproc)" all' returned a non-zero code: 2`

I have been trying to build the image with this command: 'docker build -f Dockerfile-CPU .' for cpu and this command: 'docker build -f Dockerfile-GPU .' for gpu. Any ideas why the Dockerfiles aren't working for me?

**Comment by zhouwangzw** [comment]
This is probably because the Dockerfile does not include the Boost. We are going to fix it. We are going to fix it. As workaround, you can comment out the following line in Makefile
Line 818:  ALL += $(UNITTEST_EVAL)  
Line 843:  ALL += $(UNITTEST_READER)
Line 876:  ALL += $(UNITTEST_NETWORK)
Line 907:  ALL += $(UNITTEST_MATH)

Thanks,
Zhou

**Comment by zhouwangzw** [comment]
The issue has been fixed in master. Please try again.

**Comment by Bren077s** [comment]
Okay, so I ran `docker build -t cntk -f Dockerfile-GPU .` and this time got a new error:

`building /cntk/build/gpu/release/bin/cppevalclient for Linux with build type release
mpic++  -rdynamic -L/cntk/build/gpu/release/lib -Wl,-rpath,'$ORIGIN/../lib' -Wl,-rpath,/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cudnn/cuda/lib64 -Wl,-rpath,/usr/local/openblas/lib -Wl,-rpath,/usr/local/opencv-3.1.0/lib -Wl,-rpath,/usr/local/opencv-3.1.0/release/lib -o /cntk/build/gpu/release/bin/cppevalclient
/cntk/build/gpu/release/.build/Source/../Examples/Evaluation/CPPEvalClient/CPPEvalClient.o -leval -lcntkmath
/usr/bin/ld: warning: libnvidia-ml.so.1, needed by /cntk/build/gpu/release/lib/libeval.so, not found (try using -rpath or -rpath-link)
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlDeviceGetPciInfo_v2'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlDeviceGetComputeRunningProcesses'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlDeviceGetMemoryInfo'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlDeviceGetUtilizationRates'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlShutdown'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlInit_v2'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlSystemGetProcessName'
/cntk/build/gpu/release/lib/libeval.so: undefined reference to 'nvmlDeviceGetHandleByIndex_v2'
collect2: error: ld returned 1 exit status
make[1]: *** [/cntk/build/gpu/release/bin/cppevalclient] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/cntk'
make: *** [all] Error 2
The command '/bin/sh -c git clone --depth=1 -b master https://github.com/Microsoft/CNTK.git . &&     mkdir -p build/gpu/release &&     cd build/gpu/release &&     ../../../configure --with-cuda=/usr/local/cuda --with-cudnn=/usr/local/cudnn --with-openblas=/usr/local/openblas &&     make -j"$(nproc)" all &&     cd ../../.. &&     mkdir -p build-mkl/gpu/release &&     cd build-mkl/gpu/release &&     ../../../configure --with-cuda=/usr/local/cuda --with-cudnn=/usr/local/cudnn --with-mkl=/usr/local/CNTKCustomMKL &&     make -j"$(nproc)" all' returned a non-zero code: 2
`

**Comment by Bren077s** [comment]
Just an extra note. Dockerfile-CPU is working.

**Comment by zhouwangzw** [comment]
This is a known [issue](https://github.com/Microsoft/CNTK/issues/629). You can find a workaround there too. Basically you need to comment out the following lines 71-74 in /Tools/docker/Dockerfile-GPU:  
RUN wget -O gdk.run -q      http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/cuda_346.46_gdk_linux.run && \
    chmod +x gdk.run && \
    ./gdk.run --silent && \
    rm gdk.run

We will provide a fix to the file soon.

**Comment by Bren077s** [comment]
Oh yes. I remember looking at that issue before. Thanks for all your help. Everything is working great now.
