### ISSUE TITLE
Load previously trained model

### ISSUE THREAD

**Issue by Palkos83** [Microsoft/CNTK#680]
Hi.

I was attempting to load previously trained model to train it further with new data set.
Sadly I was not able to figure out how to do it.
The configuration file either thinks it should build the model from scratch and then assumes no training is needed or fails to use the combination of MEL and Train command.

Is it possible to retrain already trained mode?
If so how this can be done?

Many thanks.

**Comment by dongyu888** [comment]
The simplest way is to rename the model file to xyz.dnn.0 if your final model is xyz.dnn

**Comment by Palkos83** [comment]
Many thanks for help.
Sadly this do not seem to work for me either.
So I run the first training all fine and I ended up with 3 files in my Models folder
1 DeepQNetwork.
2 DeepQNetwork.0
3 DeepQNetwork.cpk (by the way - what is this file for?)

I removed the .0 one and rename DeepQNetwork -> DeepQNetwork.0 as you suggested.

In my config file I have model path set to:
modelPath = "$ModelDir$/DeepQNetwork.0"

and the training task

train = [
    action = "train"

  NDLNetworkBuilder = [
        networkDescription = "Network.ndl"
    ]  
    
    SGD = [
        epochSize = 60000
        minibatchSize = 32
        learningRatesPerMB = 0.1*5:0.3
        momentumPerMB = 0*10:0.7
        maxEpochs = 1
    ]
    
   reader = [
        readerType = "CNTKTextFormatReader"        
        file = "$DataDir$/QLearningMinibatch.txt"
        input = [
        features = [
            dim = 40320
                format = "dense"
        ]
        labels = [
                dim = 4
                format = "dense"
            ]
        ]
    ]    
]

Ignore the SDG settings for now, I know they have no sense, I try to get the workflow to work first.

Now when I try to run this the output is:

**Comment by zpbappi** [comment]
> In my config file I have model path set to:
modelPath = "$ModelDir$/DeepQNetwork.0"

You don't need to do this step. I think the idea is to let CNTK believe that the training was terminated after first epoch. That's why it will resume the training with after the 1st epoch, but with your new data set and an already trained model. Nice trick :+1:

**Comment by dongyu888** [comment]
Right. The modelPath should still be "$ModelDir$/DeepQNetwork”.

 

BTW, .ckp is the checkpoint file which contains information to resume training from the current checkpoint. In your case, you can delete that file before training with the new data.

**Comment by Palkos83** [comment]
Works like a dream now. Removal of the ckp file seemed to help.
Many thanks. Great stuff!
