### ISSUE TITLE
A clean install of NVIDIA new driver will uninstall GDK?

### ISSUE THREAD

**Issue by benfre** [Microsoft/CNTK#682]
After I did a clean install of new NVIDIA driver, the build failed,
`..\Common\BestGpu.cpp(24): fatal error C1083: Cannot open include file: 'nvml.h': No such file or directory`
Checking the GDK folder, it is gone. I am not sure if it caused by the clean install.

To repair this, 

- run CUDA installer, 
- select GDK and display driver, reboot after finished
- reinstall new display driver.

**Comment by alexeyo26** [comment]
Thank you a lot! - I will add this to our FAQ
