### ISSUE TITLE
About writting output of DNN

### ISSUE THREAD

**Issue by bansungmin** [Microsoft/CNTK#684]
Hi.
After training denoising autoencder (DAE), output of DAE is obtained with below config file.
I set the output file name as *.lmf, but the saved output is named as *.lmf$$.
I don't know what is wrong.
I runned all scripts with binary file 'cntk' in CNTK Binary Download(CNTK-20151208-Linux-64bit-ACML5.3.1-CUDA7.0).

  1 stderr=$ExpDir$/WriteBottleneck_clean_log
  2 command=TIMIT_WriteBottleneck
  3
  4 precision=float
  5
  6 ##################
  7 #  WRITER CONFIG #
  8 ##################
  9 TIMIT_WriteBottleneck=[
 10     action=write
 11
 12     modelPath=$ExpDir$/cntkSpeech.dnn
 13
 14     # deviceId=-1 for CPU, >=0 for GPU devices
 15     deviceId=$DeviceNumber$
 16
 17     traceLevel=1
 18
 19     # notation xxx:yyy*3:zzz is equivalent to xxx:yyy:yyy:yyy:zzz
 20     outputNodeNames=MeanSqErr.BFF.FF.P
 21
 22     # Parameter values for the reader
 23     reader=[
 24       # reader to use
 25       readerType=HTKMLFReader
 26       featIn=[
 27         dim=280
 28         scpFile=$WorkDir$/scp/inp.scp
 29         type=Real
 30       ]
 31     ]
 32     writer=[
 33     writerType=HTKMLFWriter
 34     MeanSqErr.BFF.FF.P = [
 35         dim=40
 36         scpFile=$WorkDir$/scp/out.scp
 37        type=Real
 38     ]
 39    ]
 40 ]

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.
