### ISSUE TITLE
Missing AN4Corpus directory (and iVector) after switching to Intel MKL / pulling latest

### ISSUE THREAD

**Issue by devinbostIL** [Microsoft/CNTK#689]
Hi,

After switching to the Intel custom MKL, I'm getting:

> "The system cannot find the file specified: "C:/src/cntk/Examples/iVector" and 
> "The system cannot find the path specified: "C:/src/cntk/Examples/Speech/AN4Corpus/v0"
in a number of my unit tests. I pulled latest from Git and still am experiencing the issue. 
[cntk_output_and_env_var.txt](https://github.com/Microsoft/CNTK/files/370276/cntk_output_and_env_var.txt)
[HTKIVectorSequence_crash_1.txt](https://github.com/Microsoft/CNTK/files/370277/HTKIVectorSequence_crash_1.txt)
[HTKMLFReaderSimpleDataLoop3_crash_1.txt](https://github.com/Microsoft/CNTK/files/370278/HTKMLFReaderSimpleDataLoop3_crash_1.txt)

It seems interesting to me that it's looking for the AN4Corpus directory under Speech when I don't remember that directory ever having existed. I noticed in the bash script [for testing Speech](https://github.com/Microsoft/CNTK/blob/be59404c2bdd5d98af5c6e673132e7aec9217348/Tests/EndToEndTests/Speech/DNN/SequenceTraining/run-test) that it appears to be testing for the existence of the environment variable from the ReaderFixture in ReaderTestHelper.h , and the test implies that this directory is not part of the CNTL repository, but it's not clear to me if the AN4Corpus directory is supposed to be the same as the AN4 directory located in Examples or not. If so, then what should the v0 directory under AN4Corpus be pointing to?

**Comment by eldakms** [comment]
Currently, ivector tests require some internal test data. For now, you can ignore them. In the future, we will put these into a separate test category.

**Comment by eldakms** [comment]
Regarding AN4Corpus/v0, it should contain data of the AN4 data set (i.e. from here http://www.speech.cs.cmu.edu/databases/an4). We are not allowed to distribute it.
I'm closing the issue for now, feel free to reopen. Thanks!
