### ISSUE TITLE
fail to add 1bit-SGD code to an existing CNTK repository clone

### ISSUE THREAD

**Issue by denghuiru** [Microsoft/CNTK#69]
After execute command "git submodule update --init --recursive" ,  there is no 1bit-SGD code in  Source/1BitSGD  directory of the CNTK repository. Will you please tell me how to solve this problem?

**Comment by alexeyo26** [comment]
Hello!

Two questions:
1) Were your current directory the root of your local CNTK repository?
2) If yes, could you share git command output?

Thank you,
Alexey

**Comment by wolfma61** [comment]
Also - there should be a .getmodules file in the root of your CNTK repo. What is the content of that file?

thx
Wolfgang

**Comment by mahilleb-msft** [comment]
@denghuiru is your issue solved? Please let us know if this still needs to be kept open...

Best, Mark

**Comment by wolfma61** [comment]
@denghuiru - please reopen with the requested information if you are still experiencing problems
