### ISSUE TITLE
Randomization in CNTK

### ISSUE THREAD

**Issue by snurkabill** [Microsoft/CNTK#693]
Hello there, 

How to make sure that training is stochastic every time? I've tried "randomize = true" in SGD section of config, but results are the same. 

Just to make the question complete, randomization of network initialization (such as weights and biases) is done using randomSeedOffset? I didn't try this yet, I am focusing on randomized training and can't figure out how. CNTK intro pdf seems to be deprecated, there is None vs Auto switcher which doesn't work anymore.

**Comment by wolfma61** [comment]
The documentation contains various references to randomization in the configuration, reader, etc...
