### ISSUE TITLE
CNTK training on multiple input files

### ISSUE THREAD

**Issue by huy302** [Microsoft/CNTK#695]
Just wonder if we can train a network model using multiple input files.
As for now, I need to merge multiple training samples into a huge file.

Another question is, can we continue to train an existing network model with new training samples?
Thanks

**Comment by dongyu888** [comment]
I think those questions have been asked by others. You might want to search the issues section.

**Comment by huy302** [comment]
Thanks for the tip,

According to Ark-kun's post on #106 seems like there is a way to train on multiple input files, however it was not fully supported at that time.
I just wonder if it has been improved since then

**Comment by mcdickenson** [comment]
@dongyu888 @huy302 Any updates on whether this is now supported?

**Comment by eldakms** [comment]
Please have a look at deserializer composition - https://github.com/Microsoft/CNTK/wiki/Deserializers-and-Transforms
Thank you!

**Comment by mcdickenson** [comment]
Thanks @eldakms
