### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by nichongjia** [Microsoft/CNTK#696]
Source/CNTKv2LibraryDll/API/CNTKLibrary.h:1153:122: error: converting to ‘const std::unordered_set<CNTK::Variable>’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = CNTK::Variable; _Hash = std::hash<CNTK::Variable>; _Pred = std::equal_to<CNTK::Variable>; _Alloc = std::allocator<CNTK::Variable>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<CNTK::Variable>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<CNTK::Variable>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<CNTK::Variable>]’

const std::unordered_set<Variable>& outputsToRetainBackwardStateFor = {}) = 0;
                                                                                                                          ^
make: *** [.build/Source/CNTKv2LibraryDll/Common.o] Error 1

**Comment by eldakms** [comment]
This is fixed on master. Please use gcc 4.8.
Thanks!
