### ISSUE TITLE
C# EvalWrapper to support GPU?

### ISSUE THREAD

**Issue by huy302** [Microsoft/CNTK#697]
Hi there,

I know from the tutorial that it is not supported
However, do we have a plan to support it soon?
I'm spoiled by GPU performance and can't go back to the good old CPU :)

Thanks

**Comment by zhouwangzw** [comment]
It is correct that current C# EvalWrapper only supports CPU. It is planned to support GPU but I cannot give you concret time yet. 

Thanks,

**Comment by zhouwangzw** [comment]
We have just released the beta version of CNTK Library .NET/C# Eval API, which supports GPU too. https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta8.0.

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to reopen if needed.
