### ISSUE TITLE
semantic segmentation with CNTK? 

### ISSUE THREAD

**Issue by HasseneKhelil** [Microsoft/CNTK#703]
Hi, 

i am wondering if there is an example of 2D labeling with CNTK for the purpose of pixelwise classfication or semantic segmentation. It would be also useful to have an adequate cost function.

Thank you

**Comment by spandantiwari** [comment]
We will offer a semantic segmentation example soon. Please stay tuned.

**Comment by spandantiwari** [comment]
Please track issue #1613 for this request. Closing this one as duplicate.
