### ISSUE TITLE
k-fold cross-validation

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#704]
Default CNTK configuration setting looks only allowing single separate cross validation data. I'm wondering if there is any way we can do k-fold cross-validation. As you know, 10-fold cross validation is commonly used.

**Comment by dongyu888** [comment]
No, you will need to specify different sets and run the training 10 times. You can do this with a script.

**Comment by funguy74** [comment]
Script you mean CNTK configuration file? or BrainScript? Is there any reference I can see for this?

**Comment by zpbappi** [comment]
I would say a Bash/Shell/Batch/PowerShell script which will use different config file each time for different CV sets. It is exactly as if you have 10 different configs for 10 different CV files and running them 10 times manually, one after another. Instead, write a helper script (in any scripting you prefer) to do the same thing automatically.

_Note_: it would probably save you a lot of time and trouble if you re-use the common portion of your config file by including a common BS file in all the `k` config files.

**Comment by frankseide** [comment]
You can pass a pathname fragment through the CNTK command line into a variable and construct subset pathnames that way.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sun, Jul 24, 2016 at 6:36 PM -0700, "Zp Bappi" <notifications@github.com<mailto:notifications@github.com>> wrote:


I would say a Bash/Shell/Batch/PowerShell script which will use different config file each time for different CV sets. It is exactly as if you have 10 different configs for 10 different CV files and running them 10 times manually, one after another. Instead, write a helper script (in any scripting you prefer) to do the same thing automatically.

Note: it would probably save you a lot of time and trouble if you re-use the common portion of your config file by including a common BS file in all the k config files.

-

**Comment by funguy74** [comment]
Thanks for good explanation. I fully understand how to implement k-fold cross validation. I'll close this thread.

**Comment by frankseide** [comment]
BTW many (not all) of the file-reading operations support pipes, in a Perl-like syntax. You can use filenames like this:

    xxxFile = "cat datafile | awk '{if (NR % 10 == 3) {print}}' |"

where the final `|` tells it to treat the pathname as a command line and read its output. The example above (warning: untested blog-post code) would read every 10th line of a line-oriented `datafile`, beginning with the 3rd line.

This works in both Windows and Linux, but if you want to use a UNIX-style shell in Windows, you may need to put full pathnames of the EXEs, depending on your setup.
