### ISSUE TITLE
Is there any deconvolution layer with batch normalization?

### ISSUE THREAD

**Issue by pinzhang10** [Microsoft/CNTK#708]
@dongyu888 

Hi, I am building an image segmentation network. Since the DeconvReLULayer is supported by CNTK now. I am wondering if there is any deconvolution layer with batch normalization?

If I used several layers of ConvBNReLULayer and then several layers of DeconvReLULayer ,  will it cause the training to slow down due to the DeconvReLULayer ?

Thank you!

**Comment by zhouwangzw** [comment]
Please try with the latest CNTK release. If you still have the same problem, please open a new issue.
