### ISSUE TITLE
About 'PastValue()' and 'Delay()'

### ISSUE THREAD

**Issue by bansungmin** [Microsoft/CNTK#709]
Hello, everyone. 
I have tried to use a recurrent node using 'PastValue()' and 'Delay()' as you can see below NDL file.
This NDL file is just intended to check the usage of 'PastValue()' and 'Delay()'.
But it doesn't work properly showing below error message. 
How can I resolve this problem?

Thank you

################## NDL file ##################

    load=ndlMacroDefine
    run=ndlCreateNetwork

    ndlMacroDefine=[
    # Macro definitions
        DelayNode(x)
        {
                D=Delay(x, delayInput=Dout, delayTime=1)
        }

    MeanVarNorm(x)
    {
                xMean = Mean(x)
        xStdDev = InvStdDev(x)
        xNorm=PerDimMeanVarNormalization(x,xMean,xStdDev)
    }

    # Mean Square Error FeedForward
    MSEBFF(x,r,c,labels)
    {
        BFF=BFF(x,r,c)
        MSE=SquareError(labels,BFF)
    }
    ]

    ndlCreateNetwork=[

        #define basic i/o
        featInDim=40;
        featOutDim=40;
        hiddenDim=40;
        featIn=Input(featInDim,tag=feature);
        featOut=Input(featOutDim,tag=feature);

         # define network

         L1 = SBFF(featIn,hiddenDim,featInDim);
         L2 = SBFF(L1,hiddenDim,hiddenDim);

        #L2_delay = PastValue(hiddenDim, L2, timeStep=1);
         L2_delay = Delay(hiddenDim, L2, delayTime=1);

         L3 = SBFF(L2_delay,hiddenDim,hiddenDim);
         L4 = SBFF(L3,hiddenDim,hiddenDim);
         MeanSqErr = MSEBFF(L4, featOutDim, hiddenDim, featOut,tag=criteria);
         OutputNodes=(MeanSqErr.BFF.FF.P);
         EvalNodes=(MeanSqErr);

    ]

################## Error message ##################

feature set 1: requirerandomizedchunk: paging in randomized chunk 47 (frame range [4223764..4314313]), 48 resident in RAM
requiredata: 110 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 48 (frame range [4314314..4404383]), 49 resident in RAM
requiredata: 110 utterances read
feature set 1: requirerandomizedchunk: paging in randomized chunk 48 (frame range [4314314..4404383]), 49 resident in RAM
requiredata: 110 utterances read
getbatch: getting randomized frames [256..512] (256 frames out of 256 requested) in sweep 0; chunks [0..0] -> chunk window [0..49)
Time to advance mbiter = 0.000172

Starting minibatch loop.
getbatch: getting randomized frames [512..768] (256 frames out of 256 requested) in sweep 0; chunks [0..0] -> chunk window [0..49)
Time to advance mbiter = 0.000168
Total Minibatch read time = 0.001217

[CALL STACK]
  /local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::PrintCallStack()  + 0xbf  )  [0x7fcac80b2f8f]
  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::invalid_argument>(char const*, ...)  + 0xdd  )  [0x43cb1d]
  /local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so (                                           + 0xe325d)  [0x7fcac805125d]
  /local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::GPUMatrix<float>::SetValue(Microsoft::MSR::CNTK::GPUMatrix<float> const&)  + 0x25  )  [0x7fcac8051f15]
  /local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::Matrix<float>::SetValue(Microsoft::MSR::CNTK::Matrix<float> const&, Microsoft::MSR::CNTK::MatrixFormat)  + 0x8b  )  [0x7fcac800f85b]
  cntk                           (                                                   )  [0x54d14c]
  cntk                           (                                                   )  [0x54d1ec]
  cntk                           (                                                   )  [0x625b5e]
  cntk                           (                                                   )  [0x627c1a]
  cntk                           (                                                   )  [0x6a38b5]
  cntk                           (                                                   )  [0x6a8549]
  cntk                           (                                                   )  [0x6aa323]
  cntk                           (                                                   )  [0x4b08ee]
  cntk                           (                                                   )  [0x4febbf]
  cntk                           (                                                   )  [0x432499]
  cntk                           (                                                   )  [0x432ab8]
  cntk                           (                                                   )  [0x424698]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf5  )  [0x7fcac6ebdec5]
  cntk                           (                                                   )  [0x428497]
EXCEPTION occurred: Can't resize a externally managed matrix
-------------------------------------------------------------------
Usage: cntk configFile=yourConfigFile
For detailed information please consult the CNTK book
"An Introduction to Computational Networks and the Computational Network Toolkit"
-------------------------------------------------------------------

**Comment by frankseide** [comment]
Could you let us know the version?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Jul 21, 2016 at 11:52 PM -0700, "bansungmin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, everyone.
I have tried to use a recurrent node using 'PastValue()' and 'Delay()' as you can see below NDL file.
This NDL file is just intended to check the usage of 'PastValue()' and 'Delay()'.
But it doesn't work properly showing below error message.
How can I resolve this problem?

Thank you

################## NDL file ##################

load=ndlMacroDefine
run=ndlCreateNetwork

ndlMacroDefine=[
# Macro definitions
    DelayNode(x)
    {
            D=Delay(x, delayInput=Dout, delayTime=1)
    }

MeanVarNorm(x)
{
            xMean = Mean(x)
    xStdDev = InvStdDev(x)
    xNorm=PerDimMeanVarNormalization(x,xMean,xStdDev)
}

# Mean Square Error FeedForward
MSEBFF(x,r,c,labels)
{
    BFF=BFF(x,r,c)
    MSE=SquareError(labels,BFF)
}
]

ndlCreateNetwork=[

    #define basic i/o
    featInDim=40;
    featOutDim=40;
    hiddenDim=40;
    featIn=Input(featInDim,tag=feature);
    featOut=Input(featOutDim,tag=feature);

     # define network

     L1 = SBFF(featIn,hiddenDim,featInDim);
     L2 = SBFF(L1,hiddenDim,hiddenDim);

    #L2_delay = PastValue(hiddenDim, L2, timeStep=1);
     L2_delay = Delay(hiddenDim, L2, delayTime=1);

     L3 = SBFF(L2_delay,hiddenDim,hiddenDim);
     L4 = SBFF(L3,hiddenDim,hiddenDim);
     MeanSqErr = MSEBFF(L4, featOutDim, hiddenDim, featOut,tag=criteria);
     OutputNodes=(MeanSqErr.BFF.FF.P);
     EvalNodes=(MeanSqErr);

]


################## Error message ##################

feature set 1: requirerandomizedchunk: paging in randomized chunk 47 (frame range [4223764..4314313]), 48 resident in RAM
requiredata: 110 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 48 (frame range [4314314..4404383]), 49 resident in RAM
requiredata: 110 utterances read
feature set 1: requirerandomizedchunk: paging in randomized chunk 48 (frame range [4314314..4404383]), 49 resident in RAM
requiredata: 110 utterances read
getbatch: getting randomized frames 256..512<256%20frames%20out%20of%20256%20requested> in sweep 0; chunks [0..0] -> chunk window [0..49)
Time to advance mbiter = 0.000172

Starting minibatch loop.
getbatch: getting randomized frames 512..768<256%20frames%20out%20of%20256%20requested> in sweep 0; chunks [0..0] -> chunk window [0..49)
Time to advance mbiter = 0.000168
Total Minibatch read time = 0.001217

[CALL STACK]
/local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DebugUtil::PrintCallStack() + 0xbf ) [0x7fcac80b2f8f]
cntk ( void Microsoft::MSR::CNTK::ThrowFormattedstd::invalid_argument(char const*, ...) + 0xdd ) [0x43cb1d]
/local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( + 0xe325d) [0x7fcac805125d]
/local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::GPUMatrix::SetValue(Microsoft::MSR::CNTK::GPUMatrix const&) + 0x25 ) [0x7fcac8051f15]
/local/sungmin.ban/toolkit/CNTK/lib_bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::Matrix::SetValue(Microsoft::MSR::CNTK::Matrix const&, Microsoft::MSR::CNTK::MatrixFormat) + 0x8b ) [0x7fcac800f85b]
cntk ( ) [0x54d14c]
cntk ( ) [0x54d1ec]
cntk ( ) [0x625b5e]
cntk ( ) [0x627c1a]
cntk ( ) [0x6a38b5]
cntk ( ) [0x6a8549]
cntk ( ) [0x6aa323]
cntk ( ) [0x4b08ee]
cntk ( ) [0x4febbf]
cntk ( ) [0x432499]
cntk ( ) [0x432ab8]
cntk ( ) [0x424698]
/lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main + 0xf5 ) [0x7fcac6ebdec5]
cntk ( ) [0x428497]

EXCEPTION occurred: Can't resize a externally managed matrix

Usage: cntk configFile=yourConfigFile
For detailed information please consult the CNTK book

"An Introduction to Computational Networks and the Computational Network Toolkit"

-

**Comment by bansungmin** [comment]
I didn't compile sorce code but used binary file 'cntk' in 'CNTK-20151208-Linux-64bit-ACML5.3.1-CUDA7.0'.
Maybe, 'PastValue()' and 'Delay()' do not work in this version?

**Comment by frankseide** [comment]
The issue you ran into has been fixed a few months back. Please try with a latest binary, cf. [https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration].

May I close this issue, and could you reopen in case it still does not work with the latest binaries?
