### ISSUE TITLE
Testing data without label

### ISSUE THREAD

**Issue by parvanesh** [Microsoft/CNTK#71]
Hello All,

If my testing dataset, does not include lable, what kind of configurtion shoud I apply? Is there any functionality like this, enabled right now? when I remove the label configurtion in my test action code, compiler gives the error as: "EXCEPTION occurred: features and label files must be the same file, use separate readers to define single use files"

**Comment by dongyu888** [comment]
To compute test error rate you do need to have the labels. If you don't have labels then you probably want is just write out some internal node's values to files from which you can compute error rate by yourself. If that's the case, you should use the "write" command.

**Comment by wolfma61** [comment]
I assume dong clarified this issue, otherwise please open this with new information
