### ISSUE TITLE
BrainScriptNetworkBuilder for AutoEncoder

### ISSUE THREAD

**Issue by panchekha** [Microsoft/CNTK#712]
Hi, I am trying to setup a simple 1D AutoEncoder example and running into the non-descriptive error:

> Training criterion node(s):
> CNTK: Caught Win32 exception 0xc0000005: Access violation.**

I have 252 x 1 vector for training  which I am reducing to auto encoding 64 x 1 element layer and expanding back to 252 x 1 that does square root error with input. If I replace model with something trivial - it works. Everything is defined in one file. Can you see what is wrong here?

RootDir = "."
ConfigDir = "$RootDir$"
DataDir = "$RootDir$"
OutputDir = "$RootDir$/Output"
ModelDir = "$OutputDir$/Models"
FeatureLen = 252

deviceId = -1

command = TRAIN

precision = "float"
traceLevel = 1
NumCPUThreads=1
modelPath = "$ModelDir$/simple.dnn"

TRAIN = [
    action = "train"  
    BrainScriptNetworkBuilder = [

```
    inDim=252       
    neckDim=64

    features = Input (inDim) 
    match    = (features)

    W0 = Parameter (neckDim, inDim)
    b0 = Parameter (neckDim, 1) 
    L1 = Sigmoid ((W0 * features + b0)) 

    W1 = Parameter (inDim, neckDim )
    b1 = Parameter (inDim, 1) 
    L2 = (W1 * L1 + b1) 

    err  = SquareError (L2, match)

     # root nodes
    featureNodes    = (features)
    labelNodes      = (match)
    criterionNodes  = (err)
    evaluationNodes = (err)
    outputNodes     = (L1)
]

SGD = [
    epochSize = 0 
    minibatchSize = 100
    learningRatesPerMB = 0.1
    momentumPerMB = 0.8
    dropoutRate = 0.9
    maxEpochs = 500
]

# Parameter values for the reader
reader = [
    readerType = "UCIFastReader"
    file = "$DataDir$/features.csv"
    miniBatchMode = "partial"
    randomize = "auto"
    verbosity = 1  
customDelimiter=","

    features = [
        dim = $FeatureLen$     
        start = 0      
    ]

    labels = [
        start = $FeatureLen$      # Skip two elements
        dim = 1        # One label dimension
        labelDim = 2   # Two labels possible
        labelMappingFile = "$DataDir$/labelmap.txt"
    ]
]
```

]

features.csv is a coma delimited file with 252 elements, plus "1" at the end as a dummy label

Thank you,
Alexey

**Comment by panchekha** [comment]
To be exact, the following seems to be one continuous output  with error:

> Post-processing network complete.
> class Microsoft::MSR::CNTK::ComputationNetwork [
>   b0 : LearnableParameter [
> SGD using CPU.
> 
> Training criterion node(s):
> CNTK: Caught Win32 exception 0xc0000005: Access violation.

**Comment by frankseide** [comment]
Your config looks good, I suspect some system error (although an access violation is never an acceptable error).

Could you confirm which version this is? Is it self compiled?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Jul 22, 2016 at 6:30 PM -0700, "panchekha" <notifications@github.com<mailto:notifications@github.com>> wrote:


To be exact, the following seems to be one continuous output with error:

Post-processing network complete.
class Microsoft::MSR::CNTK::ComputationNetwork [
b0 : LearnableParameter [
SGD using CPU.

Training criterion node(s):
CNTK: Caught Win32 exception 0xc0000005: Access violation.

-

**Comment by panchekha** [comment]
Thank you very much for picking the thread!

I believe it is pre-built binary which I downloaded from the CNTK site. I did test that I can build it and run from source but I think I am using the pre-made build.

Here is what it prints at the start:
Build info:

                Built time: Feb  8 2016 00:30:51
                Last modified date: Sun Feb  7 16:50:51 2016
                Build type: Unknown
                Build target: Unknown
                With 1bit-SGD: no
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0
                CUB_PATH: C:\src\cub-1.4.1
                CUDNN_PATH: C:\NVIDIA\cudnn-4.0\cuda
                Build Branch: HEAD
                Build SHA1: 2f9a48c71dc0a6097498cb7e90ac3b151ab536dd
                Built by svcphil on DPHAIM-22
                Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\

Thank you,
Alexey

**Comment by frankseide** [comment]
Built in February, that's rather old. Would you mind trying to update to the latest downloadable binary? Maybe that solves it already.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Jul 22, 2016 at 8:31 PM -0700, "panchekha" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much for picking the thread!

I believe it is pre-built binary which I downloaded from the CNTK site. I did test that I can build it and run from source but I think I am using the pre-made build.

Here is what it prints at the start:
Build info:

            Built time: Feb  8 2016 00:30:51
            Last modified date: Sun Feb  7 16:50:51 2016
            Build type: Unknown
            Build target: Unknown
            With 1bit-SGD: no
            CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0
            CUB_PATH: C:\src\cub-1.4.1
            CUDNN_PATH: C:\NVIDIA\cudnn-4.0\cuda
            Build Branch: HEAD
            Build SHA1: 2f9a48c71dc0a6097498cb7e90ac3b151ab536dd
            Built by svcphil on DPHAIM-22
            Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\


Thank you,
Alexey

-

**Comment by panchekha** [comment]
You are totally correct.  New binary from the Jul 14 2016 build does not have this problem.
Thank you very much!

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)
