### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by steve-asdf** [Microsoft/CNTK#714]
Hi,

I would like to use cntk on Windows 10 (x64) but have a problem.

I downloaded the binary build for windows, but get an error when the program is attempting to load a dll... However, this is done from within the folder that the dll is actually in! This is the command line output:

C:\Users\test\Documents\cntk\cntk>dir
 Volume in drive C has no label.
 Volume Serial Number is 0C90-2940

 Directory of C:\Users\test\Documents\cntk\cntk

24/07/2016  08:08    <DIR>          .
24/07/2016  08:08    <DIR>          ..
24/07/2016  07:31           234,496 BinaryReader.dll
24/07/2016  07:31            69,949 CNTK.core.bs
24/07/2016  07:31         3,764,736 CNTK.exe
24/07/2016  07:31           380,928 CNTKTextFormatReader.dll
24/07/2016  07:31           351,744 CompositeDataReader.dll
24/07/2016  07:31           182,272 DSSMReader.dll
24/07/2016  07:31         2,873,344 EvalDll.dll
24/07/2016  07:31             5,850 EvalDll.lib
24/07/2016  07:31         1,219,584 EvalWrapper.dll
24/07/2016  07:31           537,600 HTKDeserializers.dll
24/07/2016  07:31           676,864 HTKMLFReader.dll
24/07/2016  07:31           445,952 ImageReader.dll
24/07/2016  07:31         1,177,288 libiomp5md.dll
24/07/2016  07:31           286,720 LibSVMBinaryReader.dll
24/07/2016  07:31           347,136 LMSequenceReader.dll
24/07/2016  07:31           340,480 LUSequenceReader.dll
24/07/2016  07:31         2,329,600 Math.dll
24/07/2016  07:31        14,569,472 mkl_cntk_p.dll
24/07/2016  07:31        44,814,336 opencv_world310.dll
24/07/2016  07:31           186,368 SparsePCReader.dll
24/07/2016  07:31           330,240 UCIFastReader.dll
24/07/2016  07:31            76,288 zip.dll
24/07/2016  07:31            77,824 zlib1.dll
              23 File(s)     75,279,071 bytes
               2 Dir(s)  78,770,675,712 bytes free

C:\Users\test\Documents\cntk\cntk>set PATH=C:\Users\test\Documents\cntk\cntk;%PATH%

C:\Users\test\Documents\cntk\cntk>cntk configFile=C:\Users\test\Documents\CNTK_Tests\tutorial01\tutorial01.cntk
-------------------------------------------------------------------
Build info:

                Built time: Jul 14 2016 07:04:57
                Last modified date: Fri Jul  8 02:53:05 2016
                Build type: Release
                Build target: CPU-only
                With 1bit-SGD: no
                Math lib: mkl
                Build Branch: HEAD
                Build SHA1: 72bee394bf461e8f6f0feb593a8416c05f481957
                Built by svcphil on Philly-Pool1
                Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
-------------------------------------------------------------------
CNTK: Failed to load DLL 'Math.dll'.
CNTK: Caught Win32 exception 0xc06d007e: Module not found.

--------------------------------------------------------------------

Can anyone offer any advice?

Steve.

**Comment by wolfma61** [comment]
Hi ... 
I just retried on my machine with the 1.6 binaries, and it worked. (which of course doesn't help you)

Did you follow all the steps described in the install-windows.txt file, a common mistake are that the visual studio redist modules are not installed? 

if I look at a dependency walker I see these dependencies on math.dll:

=== C:\testcntk\cntk\math.dll ===

  Dependencies:
    KERNEL32.dll
    MSVCP120.dll
    dbghelp.dll
    MSVCR120.dll
    VCOMP120.DLL
    cudnn64_4.dll

so these should be resolvable on your system??

Wolfgang

**Comment by steve-asdf** [comment]
Hi, 

Thank you very much for trying it!

I have visual studio 2015 community installed, and the 2012 and 2013 redistributable packages are both present. I am using the cpu only version of cntk. 

Could you tell me what tool you used to find the dependencies?

Steve.

**Comment by wolfma61** [comment]
I used the sysinternals dependency walker
I hope this is the correct link: http://dependencywalker.com/

I will try the cpu only version ...

**Comment by wolfma61** [comment]
hmmm - worked as expected

dependencies on MATH.DLL:

  Dependencies:
    KERNEL32.dll
    MSVCP120.dll
    dbghelp.dll
    MSVCR120.dll
    VCOMP120.DLL

**Comment by steve-asdf** [comment]
Hi,

Thanks very much for the advice; I had omitted the mpi install... everything's fine now.

Best regards,

Steve.
