### ISSUE TITLE
Deep RNN with UCIFastReader

### ISSUE THREAD

**Issue by yeli7289** [Microsoft/CNTK#716]
Hello I am now implement a noise cancellation regression task in deep-rnn model. In order to keep the time-sequence order in each speech utterances in training the rnn model, I have to read the feature files one by one. In my understanding, cntk only provide HTKMLFReader to perform the task.
Since I am not familiar with HTK, I decide to write my features of 2000 utterances into 2000 .txt files and write a batch to read the files one by one to and run cntk to update the weights of the rnn model and another for loop outside of it to act as the epoch. 
I use UCIFastReader to read my data, can someone give me some feedback of my approach.
Thank you.
This is my train section in the config file, in each file (utterances), I run one epoch.
![capture1](https://cloud.githubusercontent.com/assets/14809576/17143509/7bc78c4c-5321-11e6-9ca4-8c9d54de4d96.PNG)
This is for copy the model so when I train the next file, it will update base on the previous trained model.
![capture2](https://cloud.githubusercontent.com/assets/14809576/17143511/7bd0fba6-5321-11e6-9f26-b0ff74164ffa.PNG)
This is my ndl file for deep rnn
![capture3](https://cloud.githubusercontent.com/assets/14809576/17143510/7bceb1de-5321-11e6-839e-5dd79228fa78.PNG)

**Comment by frankseide** [comment]
I think UCIFastReader is not able to read sequences. The new [CNTKTextFormatReader](https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader) can do that.

But it is also not too hard to convert the data to HTK format, which is described on [the CNTK Wiki](https://github.com/Microsoft/CNTK/wiki/HTKMLF-Reader).

CNTKTextFormatReader may be quicker to get to work, but if you use very large data sets (e.g. 1 billion samples, as we do for speech), it will be too slow.

**Comment by yeli7289** [comment]
Thanks @frankseide 
UCIFastReader is not able to read sequence, is that means that the pastValue and delay function doesn't work on it?

**Comment by frankseide** [comment]
Yes. UCIFastReader can only deliver independent samples, it has no concept of sequences.

Technically it would deliver "sequences" of length 1. If you apply PastValue() to that, you will always get the default context value.

Note that there is a [conversion script](https://github.com/Microsoft/CNTK/blob/master/Scripts/uci2ctf.py) from UCI to CNTK text format. You could use that as a start to convert your UCI data. You would still have to add the sequence information in, but it may be easy.

@dongyu888, could you quickly confirm that it is indeed true that UCIFastReader does not support sequences?

**Comment by yeli7289** [comment]
I think it probably don't support because I cannot lower my MSE during training.
Thanks for your reply,  I will try out either CNTK text format or HTK instead.
