### ISSUE TITLE
Out of memory during test

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#718]
We are training a relatively big CNN based on a modified MNIST sample. Training performed well, but test command fails with out of memory:

> [CALL STACK]
> [0x7f788d8cb2d7]                                                       + 0x29d2d7
> [0x7f788d8f68d4]    float* Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  Allocate  <float>(int,  unsigned long,  unsigned long) + 0x44
> [0x7f788d8f6c34]    Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize  (unsigned long,  unsigned long,  bool) + 0xc4
> [0x7f788d875e65]    Microsoft::MSR::CNTK::Matrix<float>::  Resize  (unsigned long,  unsigned long,  unsigned long,  bool) + 0xd5
> [0x5dfd19]          Microsoft::MSR::CNTK::ComputationNode<float>::  BeginForwardProp  () + 0x409
> [0x7e6556]          Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp  (Microsoft::MSR::CNTK::FrameRange const&) + 0x56
> [0x7e839c]          Microsoft::MSR::CNTK::ComputationNetwork::  ForwardProp  (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>) + 0x7c
> [0x63a81c]
> [0x65a842]          void  DoEval  <float>(Microsoft::MSR::CNTK::ConfigParameters const&) + 0x752
> [0x5fbcb4]          void  DoCommands  <float>(Microsoft::MSR::CNTK::ConfigParameters const&,  std::shared_ptr<Microsoft::MSR::CNTK::MPIWrapper> const&) + 0xd44
> [0x59bedc]          wmainOldCNTKConfig  (int,  wchar_t)              + 0xc8c
> [0x59c5e7]          wmain1  (int,  wchar_t)                          + 0x87
> [0x590628]          main                                               + 0xd8
> [0x7f788c57cf45]    __libc_start_main                                  + 0xf5
> [0x594414]
> EXCEPTION occurred: CUDA failure 2: out of memory ; GPU=0 ; hostname=deeplearning ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
> 

Same problem happens when switching from GPU to CPU:

> [CALL STACK]
> [0x7f2c0aee13c0]    Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::PrintCallStack(unsigned long, bool) + 0x60
> [0x5944ed]          AllocationFailureHandler()                         + 0xd
> [0x7f2c0a3c2dcb]    operator new(unsigned long)                        + 0x3b
> [0x7f2c0a3c2ea9]    operator new[](unsigned long)                      + 0x9
> [0x7f2c0acf62e3]    Microsoft::MSR::CNTK::CPUMatrix<float>::Resize(unsigned long, unsigned long, bool) + 0x103
> [0x7f2c0adef67f]    Microsoft::MSR::CNTK::GemmConvolutionEngine<float>::ForwardCore(Microsoft::MSR::CNTK::Matrix<float> const&, Microsoft::MSR::CNTK::Matrix<float> const&, Microsoft::MSR::CNTK::Matrix<float>&, Microsoft::MSR::CNTK::Matrix<float>&) + 0x41f
> [0x861c7c]          Microsoft::MSR::CNTK::ConvolutionNode<float>::ForwardProp(Microsoft::MSR::CNTK::FrameRange const&) + 0xbc
> [0x7e65d3]          Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::ForwardProp(Microsoft::MSR::CNTK::FrameRange const&) + 0xd3
> [0x7e839c]          Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>) + 0x7c
> [0x63a81c]
> [0x65a842]          void DoEval<float>(Microsoft::MSR::CNTK::ConfigParameters const&) + 0x752
> [0x5fbcb4]          void DoCommands<float>(Microsoft::MSR::CNTK::ConfigParameters const&, std::shared_ptr<Microsoft::MSR::CNTK::MPIWrapper> const&) + 0xd44
> [0x59bedc]          wmainOldCNTKConfig(int, wchar_t)                 + 0xc8c
> [0x59c5e7]          wmain1(int, wchar_t)                             + 0x87
> [0x590628]          main                                               + 0xd8
> [0x7f2c09aa4f45]    __libc_start_main                                  + 0xf5
> [0x594414]
> 
> EXCEPTION occurred: std::bad_alloc

What's puzzling me is that everything is just fine during the training, which should require not less memory than test.

We are using CNTK built from the source (one day old checkout), running on Ubuntu Server 14.04.4, 16GB RAM. Is there anything else I should provide to help investigating this issue?

**Comment by dongyu888** [comment]
Which reader are you using? Is it possible the mbSize is larger in the test case?

**Comment by mikhail-barg** [comment]
Thanks for quick feedback! For both train and test we are using `CNTKTextFormatReader` with exactly same settings except for the file names. 
But your answer pointed me to the right direction - we had `minibatchSize` set to 1024 in the `test` command setup, compared to 32 in the `train`. 
When set to 32, test passes well. Thanks again!

**Comment by housebaby** [comment]
@dongyu888  when run train_cntk2.sh in AMI example, I have the same problem. But I did not set the mbSize. What the mbSize should be set ? 

DeviceNumber=$DeviceNumber$
command=$action$

numCPUThreads=$numThreads$
precision=float

write=[
    action=write
    modelPath=$modelName$
    outputNodeNames=ScaledLogLikelihood

    # deviceId=-1 for CPU, >=0 for GPU devices
    deviceId=$DeviceNumber$
    traceLevel=1

    printValues=true

    reader=[
      # reader to use
      readerType=Kaldi2Reader
      readMethod=blockRandomize
      frameMode=false
      miniBatchMode=Partial
      randomize=Auto
      verbosity=0
      features=[
            dim=$featDim$
            scpFile=$inputCounts$
            rx=$inputFeats$
      ]

    ]
    writer=[
      # reader to use
      writerType=Kaldi2Reader
      readMethod=blockRandomize
      frameMode=false
      miniBatchMode=Partial
      randomize=Auto
      verbosity=0
      ScaledLogLikelihood=[
        dim=$labelDim$
        Kaldicmd="ark:-"
            scpFile=$inputCounts$
      ]
    ]

]

**Comment by mikhail-barg** [comment]
Try setting `minibatchSize` to something reasonably small, like 32, and if it works, then try gradually increase the value. As far as I understand CNTK tries to process `minibatchSize` samples from input as a single SIMD operation, so it should fit in RAM.

**Comment by dongyu888** [comment]
The best value varies. You can try setting minibatchSize to a small value like 128 to see whether you still get the same error. If the problem persists it might indicate some bugs. Are you using the most updated version?
