### ISSUE TITLE
How to train on multiple machines

### ISSUE THREAD

**Issue by huy302** [Microsoft/CNTK#720]
I know this questions has been asked before, but despite going through all the replies, I can't seem to figure out what is wrong. I setup cntk with 1-bit SGD (1.6) on 2 machines (with 1 GPU on each) and would like to parallel train on both, so I did the following:
1. install MS-MPI from cntk\prerequisites
2. run smpd –d on both machines
3. on machineA, execute the following: mpiexec -hosts 2 machineA_IP 1 machineB_IP 1 cntk configFile=myconfig.cntk

It seems to be able to connect to both machines, but then it hangs on machineA while loading the network. The console stops outputting and just do nothing else. I think it's trying to connect to machineB but failed somehow.

Has anyone experience the same issue?

Thanks

**Comment by junjieqian** [comment]
You may need to specify the port, according to "https://technet.microsoft.com/en-us/library/cc947675.aspx".

**Comment by huy302** [comment]
Hi,

Thank you for your reply
I did specified some random ports, but nothing happens :(

**Comment by wolfma61** [comment]
there is a more detailed explanation of parallel training (current link https://docs.microsoft.com/en-us/cognitive-toolkit/multiple-gpus-and-machines)

please open a new issue if you are (still?) experiencing this problem
