### ISSUE TITLE
CNN for feature extraction

### ISSUE THREAD

**Issue by navidnadery** [Microsoft/CNTK#721]
Hi
# I'm trying to do an experiment with CNTK using Convolutional Neural Networks (CNNs) for speech Processing, i have 1 in 127 input and 1 in 26 in target , and the network must learn target pattern.
## I have changed 02_Convolution.cntk from MNIST to bellow

rootDir = ".."
configDir = "$rootDir$/Config"
dataDir   = "$rootDir$/Data"
outputDir = "$rootDir$/Output"
modelDir  = "$outputDir$/Models"

deviceId = -1

command = train:dumpNodeInfo

precision = "float"
modelPath = "$modelDir$/02_Convolution"

traceLevel = 1
numMBsToShowResult = 500
###### 
# TRAINING CONFIG
###### 

train = [
    action = "train"

```
NDLNetworkBuilder = [
    imageLayout = "cudnn"
    initOnCPUOnly = true
    ndlMacros = "$configDir$/Macros.ndl"
    networkDescription = "$ConfigDir$/02_Convolution.ndl"
]

SGD = [
    epochSize = 60000
    minibatchSize = 1
    learningRatesPerMB = 0.1*5:0.3
    momentumPerMB = 0*10:0.7
    maxEpochs = 15
]

reader = [
    readerType = "CNTKTextFormatReader"
    file = "$DataDir$/logPow.txt"
    input = [
            features = [
            alias = "p"
            dim = 127
            format = "dense"
            ]
            labels  = [
            alias = "l"
                dim = 26
                format = "dense"
            ]
    ]
]    
```

]
###### 
# Dump CONFIG
###### 

dumpNodeInfo=[
    action=dumpnode
    modelPath="$ModelDir$/02_Convolution"
    printValues=true
]
## i also have changed 02_Convolution.ndl to bellow

load = ndlMnistMacros
run = DNN

ndlMnistMacros = [
    imageW = 1
    imageH = 127
    labelDim = 26

```
features = ImageInput(imageW, imageH, 1, imageLayout=$imageLayout$)
featScale = Constant(0.00390625)
featScaled = Scale(featScale, features)
labels = InputValue(labelDim)
```

]

DNN=[
    kW1 = 1
    kH1 = 5
    cMap1 = 16
    hStride1 = 1
    vStride1 = 1
    conv1 = Conv2DReLULayer(featScaled, cMap1, 25, kW1, kH1, hStride1, vStride1, 10, 1)

```
pool1W = 1
pool1H = 2
pool1hStride = 1
pool1vStride = 2
pool1 = MaxPooling(conv1, pool1W, pool1H, pool1hStride, pool1vStride, imageLayout=$imageLayout$)

kW2 = 1
kH2 = 5
cMap2 = 32
hStride2 = 1
vStride2 = 1
conv2 = ConvNDReLULayer(pool1, kW2, kH2, cMap1, 400, cMap2, hStride2, vStride2, 10, 1)

pool2W = 1
pool2H = 2
pool2hStride = 1
pool2vStride = 2
pool2 = MaxNDPooling(conv2, pool2W, pool2H, pool2hStride, pool2vStride, imageLayout=$imageLayout$)

h1Dim = 128
h1 = DNNImageSigmoidLayer(1, 7, cMap2, h1Dim, pool2, 1)
ol = DNNLayer(h1Dim, labelDim, h1, 1)

ce = CrossEntropyWithSoftmax(labels, ol)
errs = ErrorPrediction(labels, ol)

FeatureNodes = (features)
LabelNodes = (labels)
CriterionNodes = (ce)
EvalNodes = (errs)
OutputNodes = (ol)
```

]
## I haven't changed Macros.ndl file
# Problem is when i want to run it, it errors "NotifyFunctionValuesMBSizeModified: features InputValue operation had its row dimension 784 changed bu the reader to 127"

Where should i change? I think the problem is from Macros.ndl but where exactly?!

Thanks regard

**Comment by wolfma61** [comment]
This issue has been dormant for a long while, please check out the latest CNTK release. If you still run into problems, please open a new issue.
