### ISSUE TITLE
Building custom CNTK MKL lib

### ISSUE THREAD

**Issue by rashee182** [Microsoft/CNTK#722]
@mahilleb-msft : Referring to issue
https://github.com/Microsoft/CNTK/issues/new
Going through some previous comments on this issue
"If you want extend the usage of MKL or use a different version of the MKL SDK, you should be able to build your own version of the custom library with your version of the MKL SDK (it is a pretty straight forward process, we will supply our scripts as a blueprint) and you build CNTK with that version. This should be possible with very minimal changes to the build config (couple of lines)"

Can you provide directions on how to build the custom CNTK MKL lib using a different version of MKL SDK

**Comment by wolfma61** [comment]
the readme.md files recipe inside Dependencies\CNTKCustomMKL should work also for other MKL versions
