### ISSUE TITLE
1-bit SGD not enabled

### ISSUE THREAD

**Issue by rold2007** [Microsoft/CNTK#723]
I just "upgraded" to CNTK 1.6. When I launched a training with cntk.exe I noticed that the output log says that 1-bit SGD is **not** enabled. I downloaded "CNTK-1-6-Windows-64bit-GPU-1bit-SGD.zip" so I expect SGD to be **enabled**. At the end of each epoch it seems like SGD is saving a checkpoint. So I'm wondering if SGD is activated or not...

Here's the log:
-------------------------------------------------------------------
Build info: 

		Built time: Jul 14 2016 07:10:07
		Last modified date: Fri Jul  8 10:29:39 2016
		Build type: Release
		Build target: GPU
		**With 1bit-SGD: no**
		Math lib: mkl
		CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
		CUB_PATH: C:\src\cub-1.4.1
		CUDNN_PATH: c:\NVIDIA\cudnn-4.0\cuda
		Build Branch: HEAD
		Build SHA1: 72bee394bf461e8f6f0feb593a8416c05f481957
		Built by svcphil on DPHAIM-24
		Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
-------------------------------------------------------------------
.
.
.
**SGD: Saving checkpoint model** '[hidden]'

**Comment by alexeyo26** [comment]
Hello! It is **indeed** the version with 1bit-SGD **enabled**.  We just re-checked and re-tested. The console message `With 1bit-SGD: no` is the result of some build system misconfiguration, that does **not** affect the functionality. We're fixing it now.

Thank you a lot for spotting this and sorry for the confusion.

I'll leave the issue open for a day in case there is more follow-up
