### ISSUE TITLE
Is there a way to see the gradient of all param during each epoch

### ISSUE THREAD

**Issue by wrluo** [Microsoft/CNTK#725]
Hi,

I would like to see the **sum of gradient of all param** in my network in each epoch in order to decide when to stop training. I am wondering if there is a way to output such thing to console in each epoch?

Best regards

**Comment by frankseide** [comment]
No, we don't have that. You would have to write C++ code. You can look at SGD.cpp for the loop that calls UpdateWeights(). You'd need to create a matrix of size (1,1), and then there is a way to add all elements of an entire matrix into this (1,1) matrix. You probably can reporpose parts of `struct CriterionAccumulator::Accumulate()` for that. Sorry I don't have a better answer.
