### ISSUE TITLE
CNTK compile Error on RedHat Linux

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#729]
I tried to install CNTK on redhat linux (6.7).  Due to some restriction of library installation, I installed some libraries needed for CNTK installation in my locals. So, my Config.make becomes like this:

> BUILDTYPE=release
> MATHLIB=mkl
> MKL_PATH=/home/sr3/jaey1.kim/tools/CNTKCustomMKL
> MKL_THREADING=parallel
> CNTK_CUSTOM_MKL_VERSION=1
> CUDA_PATH=/apps/cuda/cuda7.5
> GDK_PATH=/home/sr3/jaey1.kim/local
> CUB_PATH=/apps/cuda/cub-1.4.1
> CUDNN_PATH=/home/sr3/jaey1.kim/tools/cudnn-4.0
> KALDI_PATH=/home/sr3/jaey1.kim/tools/kaldi-trunk
> OPENCV_PATH=/apps/OpenCV/OpenCV-3.1.0_cuda

Previously, when I install CNTK in Ubuntu, I haven't had any issue but now, I have following compile errors:

> mpic++ -c Source/Math/CUDAPageLockedMemAllocator.cpp -o .build/Source/Math/CUDAPageLockedMemAllocator.o -D_POSIX_SOURCE -D_XOPEN_SOURCE=600 -D__USE_XOPEN2K -std=c++11 -DUSE_CUDNN -DUSE_MKL -DNDEBUG -DNO_SYNC  -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -DHAVE_OPENFST_GE_10400 -msse4.1 -mssse3 -std=c++0x -fopenmp -**fpermissive** -fPIC -Werror -fcheck-new -Wno-error=literal-suffix -g -O4 -ISource/Common/Include -ISource/CNTKv2LibraryDll -ISource/CNTKv2LibraryDll/API -ISource/Math -ISource/CNTK -ISource/ActionsLib -ISource/ComputationNetworkLib -ISource/SGDLib -ISource/SequenceTrainingLib -ISource/CNTK/BrainScript -ISource/Readers/ReaderLib -I/home/sr3/jaey1.kim/local/mpi/include -I/home/sr3/jaey1.kim/local/include/nvidia/gdk -I/apps/cuda/cub-1.4.1 -I/apps/cuda/cuda7.5/include -I/home/sr3/jaey1.kim/tools/cudnn-4.0/cuda/include -I/home/sr3/jaey1.kim/tools/CNTKCustomMKL/1/include -I/home/sr3/jaey1.kim/tools/kaldi-trunk/src -I/home/sr3/jaey1.kim/tools/kaldi-trunk/tools/ATLAS/include -I/home/sr3/jaey1.kim/tools/kaldi-trunk/tools/openfst/include -I/apps/OpenCV/OpenCV-3.1.0_cuda/include -ISource/Readers/CNTKTextFormatReader -MD -MP -MF .build/Source/Math/Matrix.d
> In file included from Source/Math/BlockHandlerSSE.h:11:0,
>                  from Source/Math/BlockHandlerSSE.cpp:10:
> Source/Math/BlockMultiplierMatrixUtil.h: In function 'ScalarT* Microsoft::MSR::CNTK::CreateAlignedMatrix(int, int, ScalarT, int)':
> Source/Math/BlockMultiplierMatrixUtil.h:84:85: **error: there are no arguments to'aligned_alloc' that depend on a template parameter, so a declaration of 'aligned_alloc' must be available [-Werror=permissive]**
>          ScalarT* ret = (ScalarT*) aligned_alloc(alignment, sizeof(ScalarT) * (m * n));

This type error generating "there are no arguments to some function that depend on a template parameter..." comes from 2 phase lookup. What I found for solutions are

1) -fpermissive make this as warning to go over. Clearly, there is -fpermissive option in the mpic++ compile above but in some how, it is not working now. ( I don't know why). 

2) Second solution is to provide explicit name space such as Base::aligned_alloc ..  I tried std:: but it complained that aligned-alloc is not included in std

So, could you give me any suggestion to fix this problem? For example, I like to try second method by providing explicit name space of aligned_alloc. For that case, what name space I need to provide?

Or, if you have any other suggestion, I will be really appreciating it.

**Comment by funguy74** [comment]
I went around this error by removing option '-Werror'. This option makes all warning into errors during compilation. I'm not sure this is correct way of resolving this issue.

**Comment by junjieqian** [comment]
'aligned_alloc' is redefined in "Source/Math/BlockMultiplierPlatform.h". It has several dependences in Linux, such as C++11 and glibc 2.16, according to "http://linux.die.net/man/3/aligned_alloc". You may want to start from there.

**Comment by funguy74** [comment]
I got another error on **aligned_alloc** for compilation.

> Source/../Tests/UnitTests/MathTests/../../../Source/Math/BlockMultiplierMatrixUtil.h: In instantiation of 'ScalarT* Microsoft::MSR::CNTK::CreateAlignedMatrix(int, int, ScalarT, int) [with ScalarT = short int]':
> Source/../Tests/UnitTests/MathTests/../../../Source/Math/BlockMultiplier.h:595:55:   required from 'static Microsoft::MSR::CNTK::BlockMultiplier<BlockHandlerT>::ScalarAT* Microsoft::MSR::CNTK::BlockMultiplier<BlockHandlerT>::CreateMatrixA(int, int, Microsoft::MSR::CNTK::BlockMultiplier<BlockHandlerT>::ScalarAT) [with BlockHandlerT = Microsoft::MSR::CNTK::BlockHandlerSSE; Microsoft::MSR::CNTK::BlockMultiplier<BlockHandlerT>::ScalarAT = short int]'
> Source/../Tests/UnitTests/MathTests/BlockMultiplierTests.cpp:96:50:   required from 'void Microsoft::MSR::CNTK::TEST::TestMultiplierSub(int, int, int, MultiplierT&, int, ScalarCT) [with ScalarAT = short int; ScalarBT = short int; ScalarCT = int; MultiplierT = Microsoft::MSR::CNTK::BlockMultiplier<Microsoft::MSR::CNTK::BlockHandlerSSE>]'
> Source/../Tests/UnitTests/MathTests/BlockMultiplierTests.cpp:137:104:   required from 'void Microsoft::MSR::CNTK::TEST::TestMultiplierSub(int, int, int, int, ScalarCT) [with ScalarAT = short int; ScalarBT = short int; ScalarCT = int; MultiplierT = Microsoft::MSR::CNTK::BlockMultiplier<Microsoft::MSR::CNTK::BlockHandlerSSE>]'
> Source/../Tests/UnitTests/MathTests/BlockMultiplierTests.cpp:144:96:   required from here
> **Source/../Tests/UnitTests/MathTests/../../../Source/Math/BlockMultiplierPlatform.h:13:69: error: 'aligned_alloc' was not declared in this scope**
>  #define ALIGNED_ALLOC(bytes,alignment) aligned_alloc(alignment,bytes)

I couldn't find any solution to avoid this error. I tried to include cstdlib library or used feature test macros described in the link above (_ISOC11_SOURCE) but nothing works. Could you give me any idea how to approach this issue?

**Comment by funguy74** [comment]
It comes from old version of glibc library. I resolved it using higher than 2.17 version.

**Comment by karaf** [comment]
We are using CentOS release 6.8, this error can be solved by modification Source/Math/BlockMultiplierPlatform.h:
--- a/Source/Math/BlockMultiplierPlatform.h
+++ b/Source/Math/BlockMultiplierPlatform.h
@@ -10,7 +10,8 @@
 #else
 #ifdef __GNUC__
 #include <stdlib.h>
-#define ALIGNED_ALLOC(bytes,alignment) aligned_alloc(alignment,bytes)
+#include <malloc.h>
+#define ALIGNED_ALLOC(bytes,alignment) memalign(alignment,bytes)
 #define ALIGNED_FREE(ptr) free(ptr)
 //#define FORCEINLINE __attribute__((always_inline)) 
 #define FORCEINLINE inline
