### ISSUE TITLE
remove code dup of SimpleOutputWriter::WriteOutput()

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#73]
There are two nearly identical versions of this functions. They do differ in one specific aspect, which I believe is a bug (I added a BUGBUG comment). Best fix this by pulling all shared code into a shared function.

**Comment by wolfma61** [comment]
currently we don't track 'todo' and 'bug' comments as issues in github ... I understand the concern, but looking at todo's and bug comments in the code, it seems like overkill ...
