### ISSUE TITLE
Profile compute performance

### ISSUE THREAD

**Issue by championoaks** [Microsoft/CNTK#732]
What's the best way to profile compute and memory for a particular network? I would like to document average images/sec for scoring or training. 

Any suggestions?

**Comment by junjieqian** [comment]
You may want to give a try to Intel PAT (https://github.com/intel-hadoop/PAT/tree/master/PAT).

**Comment by championoaks** [comment]
I am running CNTK on Windows and wondering if anybody has done any  CNTK instrumentation(ETW) to report throughput(images/sec) for a particular run.

**Comment by championoaks** [comment]
From comments it seems there is intention of enhancing "ProgressTracing" implementation. Can it be modified to use ETW for windows builds?

**Comment by wolfma61** [comment]
Windows Event Tracing is currently no on the roadmap as a tracing/logging option
