### ISSUE TITLE
The neural networks's results are different for different accounts and computers

### ISSUE THREAD

**Issue by 256zib** [Microsoft/CNTK#733]
The neural networks's results are different for different accounts and computers. I have a three labels (classes) in model. On computer this model was trining on , I have a result "6.231499 -6.724119 4.726861" (true result)  and on the other computer I have a result "1.672395 -1.918028 3.984715" ( false result).  If I will login to learning computer with another account then I get false result too (1.672395 -1.918028 3.984715) . As I can see the results are bounded to the account of learning machine. How this issue can be fixed ?

Thanks :)

**Comment by frankseide** [comment]
Is the difference that one runs GPU and one does not? You can see in the log output.

Could you also let us know which version of CNTK this is, and if it is older than 1 month, please try with the latest binary? In the past, there were differences between GPU and CPU computation for convolution. There were also two bugs in external libraries in the past: On CPU, the ACML BLAS library on certain Intel CPUs, and on the GPU, GPUs with compute capability less than 3.0, were known to return zeroes for certain operations.

**Comment by zhouwangzw** [comment]
Since the thread has been dormant for a long time, and CNTK has published multiple releases since then. Please try with the latest CNTK release. If you still run into problems, please open a new issue.
