### ISSUE TITLE
There is a probability of logical error

### ISSUE THREAD

**Issue by dautovri** [Microsoft/CNTK#735]
[CNTK/Source/ComputationNetworkLib/SpecialPurposeNodes.cpp](https://github.com/Microsoft/CNTK/blob/master/Source/ComputationNetworkLib/SpecialPurposeNodes.cpp#L98)

line 98 - 101
```
else if (timeRange.second == timeRange.first+1)
            fprintf(stderr, "%d", (int)timeRange.first);
else if (timeRange.second == timeRange.first + 1)
            fprintf(stderr, "%d..%d", (int)timeRange.first, (int)timeRange.second-1);
```

**Comment by frankseide** [comment]
Indeed. Thanks! Will fix it right away (will land with the next thing I merge into master).
