### ISSUE TITLE
Does Evaluation Interface input support involve last hidden layer's output s(t-1)?

### ISSUE THREAD

**Issue by pkumc** [Microsoft/CNTK#736]
As we know, RNN model calculate output at time _t_ based on both current features and last time _t-1_ hidden layer's output _s(t-1)_.
Now in CNTK's Evaluation Interface, it seems that the input only contains features. How can I add _s(t-1)_ to evaluate method's input? I trained a RNN model offline, and plan to load the trained model online to evaluate a new instance's output. And I need to maintain the hidden layer's state by myself. How to let the evaluate method takes _s(t-1)_ as input as well as features? Thank you!

**Comment by zhouwangzw** [comment]
The current Eval interface does not support s(t-1) as input, as the s(t-1) is usually managed by the model itself. Do you have any particular use case which requires to main this state by application?

**Comment by pkumc** [comment]
I have already discussed this issue with you last week by email. Thanks for your reply.
