### ISSUE TITLE
Inconsistent Model Evaluation or missing a step?

### ISSUE THREAD

**Issue by chrubiofa** [Microsoft/CNTK#739]
Hello, I am using the CSEvalClient and EvalWrapper to process a model that was created based from the LTSM ATIS example.

What I suspect to be the problem is that I don't have a forget gate that tells the network that a new document is coming in. I used the ATIS example as a starting point, but I have deviated from the example data significantly as I apply the process to our use case. 

So my question is; How do I setup a forget date in the training data? And/Or - how do I pass a forget gate into the model as I am running a new document through? Or should I just reload the model for each request?

The process is similar as in each row of the training data represents a specific word in the sentence however, network understands when the next document comes in and a new set of sentences is starting.

Attached are the cntk model(s) and an example of the  training data I am using. I don't expect that these examples would reproduce the results but are provided more for review purposes.

[example.cntk.txt](https://github.com/Microsoft/CNTK/files/402770/example.cntk.txt)
[example.sparse.txt](https://github.com/Microsoft/CNTK/files/402771/example.sparse.txt)
[example.label.txt](https://github.com/Microsoft/CNTK/files/402774/example.label.txt)

My question is; do I need to reload the model before each request or am I missing a step in resetting the model (forget gate?)

The model I built uses the ATIS example pattern, with different data inputs and outputs. 

The problem comes when running the loaded model a second time. The second time through I get different results using the same input as the first pass. The first pass produces the expected outputs but the second pass, produces different outputs.

The pseudo code of I am using with the model.

Thank you.

```

using (var model = new IEvaluateModelManagedF())
{
   Dictionary<int,string> labels = LoadLabels() // Loads the output labels IE: 0 == Apple, 1 == Orange etc.
   model.CreateNetwork(string.Format("modelPath=\"{0}\"", model), deviceId: -1);
   while (true) {
             string consoleInput = "ABCD DEFG"; // read from the console for testing....
             foreach( string word in consoleInput.Split( ' ' ) ) {
               Dictionary<string, List<float>> inputs = GetInputs(  word ); // sets inputs up IE: input[10] = 1 for RED, input[11] = 1 for Orange etc...
               var outputs = model.Evaluate( inputs, "outputs" );
               int guess = 0;
                if (outputs.Max() > 0)
                  guess = outputs.IndexOf( outputs.Max() );
                  System.Console.WriteLine( string.Format( "{1}\t({0}) ", label[ guess ], word.ToUpper() ));
             }
             //
             // First pass returns correct ouptput, second pass returns incorrect output.
             //
   }
}
```

**Comment by zhouwangzw** [comment]
The new CNTK V2 API should allow you to do it. Could you please have a try? And if you run into problems, please open a new issue.
