### ISSUE TITLE
Regarding Error of missing parameter 

### ISSUE THREAD

**Issue by Yandychang1** [Microsoft/CNTK#741]
I cloned and compiled CNTK. When I try to run the simple.cntk config file it returns the attached error. It appears to be missing a parameter required for "train"
![screenshot 2016-08-05 00 26 13](https://cloud.githubusercontent.com/assets/3850113/17426376/15a4d7f4-5aa5-11e6-92df-fd6852d870f4.png)

Any idea on how to get around this?... Tried other files and get the same  error....

**Comment by dongyu888** [comment]
What’s your command line?

**Comment by Yandychang1** [comment]
CNTK  configfile= simple.cntk

**Comment by Yandychang1** [comment]
Was There any parameters that used to not be required before that are required now? I installed it before and it used to work, I stopped playing around with it, then decided to try it again. The old version gives the same error, I re-compiled the new version and get the same error.

**Comment by frankseide** [comment]
Did you try to remove the space between = and the config filename?

**Comment by Yandychang1** [comment]
That did the job... Thank you very much
