### ISSUE TITLE
Denoising Convolutional Autoencoder for generic 2D input data

### ISSUE THREAD

**Issue by kestrelm** [Microsoft/CNTK#744]
Hello,

I apologize if this sounds like a trivial question but I could not find the required documentation on the wiki.

In another framework, I already have my own Denoising Convolutional Autoencoder running. Here is what it does:

Input - N samples of 2D matrices

My code runs some noise operation on them. It then proceeds to run the normal denoising convolutional autoencoder network to reconstruct the original values.

My question is in CNTK, is this possible? My inputs are not images. In the examples/tutorials provided, the input shapes were just 1D vectors and so were the labels. Is there any example where I can read in generic 2D ( or 3D ) data and use it in a convolutional network?

I am ok with writing code to convert my current data format into the text reader format of CNTK. Any pointers/tips will be appreciated.

Thanks!

**Comment by dongyu888** [comment]
Check  <https://github.com/Microsoft/CNTK/blob/ed3b28802edb9e1bc055820b8db40ce07a815396/Examples/Image/MNIST/Config/04_DeConv.ndl> Examples/Image/MNIST/Config/04_DeConv.ndl

**Comment by kestrelm** [comment]
@dongyu888 Hello, thanks a lot for the pointers. I noticed that in the sample:

    mse = SquareError(featScaled, deconv1)
    #err = ErrorPrediction(labels, ol)

So the labels isn't actually used ( even though it is defined as dimension 10 earlier on).

The line:

deconv1 = DeconvReLULayer(unpool1, kW1, kH1, imageC, 25, cMap1, hStride1, vStride1, lpad1, upad1, wScale1, bValue1)

will contain the reconstructed image in my case? (obviously with more modifications to the script but I am talking about the general concepts/ideas)

**Comment by dongyu888** [comment]
Yes.

**Comment by pkranen** [comment]
We have a new example for deconvolution which builds a simple auto encoder for MNIST images in both Python and BrainScript. Please check these links:

[Examples/Image/GettingStarted/07_Deconvolution_PY.py](https://github.com/Microsoft/CNTK/blob/master/Examples/Image/GettingStarted/07_Deconvolution_PY.py)

[https://github.com/Microsoft/CNTK/wiki/Image-Auto-Encoder-Using-Deconvolution-And-Unpooling](https://github.com/Microsoft/CNTK/wiki/Image-Auto-Encoder-Using-Deconvolution-And-Unpooling)
