### ISSUE TITLE
CPPEvalClient for multiple images

### ISSUE THREAD

**Issue by JSPhine** [Microsoft/CNTK#745]
Hi!
I have a question concerning the CPPEvalClient:

I would like to use it a trained network to classify new images. I understand how to classify a single image but I'm struggling to classify multiple images without relying on a for-loop that calls 
`model->Evaluate(inputLayer, outputLayer);`
for each seperate image?

Can I add the image vectors directly to the inputLayer? Specifically, how should the keys be assigned for the different images using 
`inputLayer.insert(MapEntry(inputLayerName, &inputs));` ?
If it would work that way, what should I consider when I extract the output of each image from the outputLayer?

Thanks a lot in advance!
JSphine

**Comment by zhouwangzw** [comment]
The current EvalDll interface only supports to clarify one image at a time. For multiple images you have to go through a for-loop. We have noted your requirements, and will consider to support it in the future release.

Thanks,

Zhou

**Comment by zhouwangzw** [comment]
I am closing this issue. Please feel free to reopen it if you have further questions.
