### ISSUE TITLE
How to setup a forget gate.

### ISSUE THREAD

**Issue by chrubiofa** [Microsoft/CNTK#746]
I am using the ATIS.cntk as the baseline for a model I created. The problem is, after training - if I pass data into the model for testing, I get inconsistent results. The first time the model is loaded correctly, it works as expected however, when I pass the same input in a second time, I get different output. 

So I am wondering if I am not indicating a forget gate and was wondering how do you setup a forget date in the training data? And/Or - how do I pass a forget gate into the model as I am running a new document through? Or, is it expected that I just reload the model for each document to get correct results?

Thank you.

**Comment by dongyu888** [comment]
I think the state is cleared after seeing a special sentence start or end symbol which is used by the reader to provide the MBLayout info?

**Comment by frankseide** [comment]
This should work. How are you testing it, with a "write" command or through EvalDLL?

**Comment by chrubiofa** [comment]
I am using the EvalDLL, I provided additional information in issue #739, inconsistent Model Evaluation or missing a step. I guess, is the forget gate the first input or last input, I have modified the data so I want to make sure that I am not going to far off the deep end. My first jump into ML.

**Comment by frankseide** [comment]
No, the sequence boundaries are handled automatically by CNTK. It is not meant to be of user's concern.

I forwarded the question internally. I suspect a configuration issue. Maybe if you could post how you are calling the EvalDLL from your code?

**Comment by chrubiofa** [comment]
Thank you.

If I am understanding,The first column of the training data is the sequence number
Sequence Number--->0<------	|PW4 1:1	|PW3 1:1
In the .cntk file, I don't see any logic to pick up this column. Is this what you mean when you say it is being handled internally? 

This is the how I am calling the EvalDLL from the code.  

using (var model = new IEvaluateModelManagedF())
{
   Dictionary<int,string> labels = LoadLabels() // Loads the output labels IE: 0 == Apple, 1 == Orange etc.
   model.CreateNetwork(string.Format("modelPath=\"{0}\"", model), deviceId: -1);
   while (true) {
             string consoleInput = "ABCD DEFG"; // read from the console for testing....
             foreach( string word in consoleInput.Split( ' ' ) ) {
               Dictionary<string, List<float>> inputs = GetInputs(  word ); // sets inputs up IE: input[10] = 1 for RED, input[11] = 1 for Orange etc...
               var outputs = model.Evaluate( inputs, "outputs" );
               int guess = 0;
                if (outputs.Max() > 0)
                  guess = outputs.IndexOf( outputs.Max() );
                  System.Console.WriteLine( string.Format( "{1}\t({0}) ", label[ guess ], word.ToUpper() ));
             }
             //
             // First pass returns correct ouptput, second pass returns incorrect output.
             //
   }
}

**Comment by frankseide** [comment]
OK, a possible explanation is that it treats both repetitions as one long sequence. I think that's what you mean with forget gate--how does it know to reset before the second invocation? This would have to be accomplished through program logic, not through passing special data or modifying the model.

I am not super-knowledgable of the EvalDLL and thus do not know how to signal EvalDLL about the reset. I will need to leave this to some other colleague to respond.

BTW sequence packing is conceptually explaned in detail in this [slide deck](https://github.com/Microsoft/CNTK/wiki/ppt/LATAM_Frank_Seide_CNTK,%202016-5-19,%20Print.pptx), slides 33ff. CNTK manages variable-length sequences for you, including boundary conditions, but focussing on the training case.

**Comment by chrubiofa** [comment]
Frank,

I think that is the correct question, how to reset the model before the second invocation.

Thank you for helping to clarify.

Chris.

**Comment by zhouwangzw** [comment]
Hi, Chris,

we are looking into it and will get back to you soon. 

Thanks, 
Zhou

**Comment by zhouwangzw** [comment]
Hi, Chris,

Sont kindly wrote an example how to use eval interface to evaluate an RNN model, and his example is available as PR request [here](https://github.com/Microsoft/CNTK/pull/770/files). Would it help to resolve your issue? 

Thanks,
Zhou

**Comment by chrubiofa** [comment]
Zhou, thank you for the update. I reviewed Song's implementation and it did indeed provide a forward pass which seems to be working. I am training the model and will see how it comes along. 
Regards,
Chris.
