### ISSUE TITLE
Is GTX1080 going to be supported soon?

### ISSUE THREAD

**Issue by oxrider** [Microsoft/CNTK#747]
Is GTX1080 going to be supported soon? And is there a workaround currently available to somehow use GTX1080 on CNTK?

**Comment by DanielMerget** [comment]
For a temporary solution/workaround, see PR #771 and Issue #655

**Comment by kestrelm** [comment]
Any news on when the official binary releases will be ready? @chrisbasoglu mentioned that it would be ready for a 8/19 release but I haven't seen any official updates on the github page yet. I have a gtx 1060 that is ready to run CNTK whenever they push out the update. Thanks!

**Comment by chrisbasoglu** [comment]
likely 8/25 or 8/26

**Comment by chrisbasoglu** [comment]
Ok.  Its out as source in master. official binaries and notifications will happen on 8/29 (we are taking the opportunity to go to cudnn 5.1).

**Comment by kestrelm** [comment]
@chrisbasoglu Hello, thank you for releasing the 1.7 binaries for the 10 series cards! Can I just run your released binary or do I need to build from source if I have a gtx 1060? 

If I am running your released binary directly, do I need to install CUDA 8?

Thanks!

**Comment by chrisbasoglu** [comment]
>>Can I just run your released binary
yes

>>do I need to install CUDA 8
You should not need to.  You may get better perf with CUDA 8 and maybe some Pascal specific fixes, however -- so you may wish to install it (if you do use CUDA 8, then you will need to build from source).  Note that CUDA 8 is still a release candidate, not final release.  We won't officially support CUDA 8 until it is a final release.

**Comment by n17s** [comment]
Also see [this how do I](https://github.com/Microsoft/CNTK/wiki/Avoid-the-error-CURAND-failure-201) if you get a weird curand error.
