### ISSUE TITLE
Running in parallel on one machine with one GPU

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#748]
Hi,
According to GPU-Z, when I run my training, the GPU is 30-40% busy. I can start another cntk process and run something else concurrently, and then the GPU utilization goes up, as expected, to say 80%. If this measurements are correct, would it be possible to parallelize one learning in this context? So, say two cntk processes cooperating on the same task (hopefully using 1bit-SGD. BTW, do I need to run Windows Server for this?)

Regards,
Slawek

**Comment by frankseide** [comment]
In principle yes. E.g. you could run MPI with 2 processes. I believe you don't need Windows Server, just the runtime (the [binary download page](https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration) has the link).

However, if you are only using 40% of the GPU, it means there is an unintended CPU bottleneck. One could also see whether that bottleneck could be reduced. Are you reading data from the network? Are you decompressing images?

**Comment by slaweks17** [comment]
Yes, CPU is maxed. I believe that the bottleneck is CNTKTextFormat reader. I do regression on input and output vectors. Things seems to be much faster with UCI Fast reader.

**Comment by slaweks17** [comment]
I mean one thread of CPU is maxed.

**Comment by slaweks17** [comment]
An update:
I used to have randomize="None" in my config's SGD part, and when I changed to randomize=true it appears that the whole dataset goes to RAM (the CNTK process grows to 25 GBs) and now the speed is much better, the GPU runs around 80-85% according to GPU-Z.
So, it was I/O, although I would not think the disk is particularly slow, it is Samsung SSD 850 Evo :-)
What would have happened if the dataset was a few times larger? It would not fit in RAM.

Cheers,
Slawek

**Comment by n17s** [comment]
You could try changing the value for the parameter chunkSizeInBytes in the reader. The default of 32MB might not be suitable for your disk. If you see a difference please let us know.

**Comment by eldakms** [comment]
If you do not specify "keepDataInMemory=true" in the reader, only part of the data resides in memory. Actually how much - can be specified using "randomizationWindow=<numberOfSamples>".  When the training reaches the end of this data a new chunk is fetched into the memory and randomized. The more memory you have - the bigger your randomization window can be.

**Comment by n17s** [comment]
We need to do a better job at picking names. randomizationWindow is a poor choice. Being able to read the dataset in chunks has nothing to do with whether you are randomizing or not.

**Comment by eldakms** [comment]
We always read data in chunks, no matter if it uses randomization or not.

**Comment by n17s** [comment]
Hmm, I hadn't had my coffee yet :-) All I meant to say was being able to specify how much of the dataset resides in memory has nothing to do with randomization. randomizationWindow is less intuitive than, say,  "memoryBudget". In the meantime I have updated the CNTK Text Format Reader wiki page to indicate that randomizationWindow also controls how much data resides in memory.

**Comment by slaweks17** [comment]
But, Sirs, clearly the system behavior changed dramatically: when randomize was="None" CNTK process was small, say a bunch of MBs, and was slow, and the disk was busy all the time. When I changed to randomize=true, CNTK appears to have cached the whole 40GB-on-disk data set, and grows to 26GB of RAM, and there appear to be no disk activity afterwards. I did not specify keepDataInMemory=true.

**Comment by eldakms** [comment]
Hi slaweks17,

Let me explain why you see this behavior.
To be IO efficient the input data in the reader is always read in chunks.
1) in case "randomize = true". The reader reads as many chunks as necessary to fill randomizationWindow ( which is given in samples). Then it randomizes this window and gives the data to the network. As training progresses the samples of the beginning of the window get dropped and the reader reads new data (asynchronously, so called chunk prefetch) to fill the randomizationWindow and randomizes it again, etc. So it is a rolling window of randomization so to say. All the time the reader keeps the randomized window in memory.
I guess, in your case you do not set randomizationWindow and the default value for it is the whole data.
2) in case "randomize = false". The reader does not need to randomize, so it reads only a single chunk and gives its samples (sequences) to the network. When the data of the chunk is exhausted the reader reads the next chunk (currently synchronously, does not support chunk prefetch yet, it is on the list). So at any point in time the reader has only a single chunk in memory.  If you know that your data fits in memory and you run several epochs over this data you can set "keepDataInMemory" to true.

**Comment by slaweks17** [comment]
Thank you!

**Comment by frankseide** [comment]
@n17s, to clarify `randomizationWindow` is the number of samples that we randomly sample from. This window is shifted across the corpus. That corpus is prerandomized on chunk level. The chunk size and randomization window are not the same. Rather, the randomization window is meant to be significantly larger than the chunk size.

Note that because chunks are read consecutively from disk, and we don't want to require users to prerandomize their data, we must assume that the samples within a single chunk are correlated. E.g. think of multiple turns of a speech conversation, or a situation where multiple slightly different corpora are concatenated. Hence one would not just want to read a single chunk, randomly sample from it until all samples are exhausted, then move on with the next sample etc., as that would adapt your model to one chunk, then to the next, etc., not leading to a good global optimum.
