### ISSUE TITLE
Stack input frames as rows of matrix ?

### ISSUE THREAD

**Issue by creatorscan** [Microsoft/CNTK#750]
I am trying to find, if there is any possibility to stack input frames of speech signal into matrix rows ? And, sum element-wise over all rows ?  Can I use Delay and Plus to perform this operation ?

Is there any function which is currently implemented to handle this problem ?

**Comment by cha-zhang** [comment]
You can use splice in the latest Python API. 

I'm closing this issue since it's been very old. Please open a new issue if problem persists.
