### ISSUE TITLE
GPU slower than CPU?

### ISSUE THREAD

**Issue by oxrider** [Microsoft/CNTK#751]
Hi, I'm new to CNTK and am trying with the Simple2D sample with the pre-compiled v1.6 binary for Windows. 
When I run the sample on my CPU (i7-6700K) it reaches >40k samples per second, but when I run it on my GPU (GTX980Ti) it only reaches ~35k samples per second. Am I doing anything wrong?

**Comment by n17s** [comment]
This network is too small to benefit from GPU training. When the network is
small, the cost of transfering data to/from the GPU overshadows the benefit
of faster execution.

Try replacing the 50 hidden units in the network with 500 and you should
probably observe that the GPU is faster than the CPU.

-Nikos
