### ISSUE TITLE
Error:InnerProductOfMatrices

### ISSUE THREAD

**Issue by RubickH** [Microsoft/CNTK#752]
Hi, I'm new to CNTK and I want to edit my own ResNet.

I wanted to modify the demo named ResNet_18 in the ImageNet folder. The original network added the DNNLayer like this:

```
pool5 = AveragePooling(rn4_3, pool2W, pool2H, pool2hs, pool2vs, imageLayout = "cudnn")

    ol = DnnLayer(cMap4, labelDim, pool5, fcWScale, 0)`
```

I wanted to reduce the number of layers in the network, so I changed the code like this:

```
pool5 = AveragePooling(rn2_2, pool2W, pool2H, pool2hs, pool2vs, imageLayout = "cudnn")

    ol = DnnLayer(28, labelDim, pool5, fcWScale, 0)
```

However, I came to the Error showed below:

> Starting Epoch 1: learning rate per sample = 1.000000  effective momentum = 0.900000  momentum as time constant = 9.5 samples
> BlockRandomizer::StartEpoch: epoch 0: frames [0..59600](first sequence at sample 0), data subset 0 of 1
> 
> Starting minibatch loop.
> 
> [CALL STACK]
>     > Microsoft::MSR::CNTK::Matrix<float>::  AssignInnerProductOfMatrices
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  operator=
>     - Microsoft::MSR::CNTK::Matrix<float>::  __autoclassinit2
>     - BaseThreadInitThunk
>     - RtlUserThreadStart
> 
> EXCEPTION occurred: InnerProductOfMatrices: Matrices a and b should have same dimension.

Could anyone please help me solve this problem?

Thanks in advance!

**Comment by zhouwangzw** [comment]
Have you tried with the latest release 2.0 of CNTK? If you still run into problems with the latest release, please open a new issue.
