### ISSUE TITLE
Is it possible to use a (trainable) vector/matrix to set "defaultHiddenActivation" in PastValue or FutureValue ?

### ISSUE THREAD

**Issue by hspark84** [Microsoft/CNTK#754]
Hi,

I'm trying to code NTM using CNTK. 

I'd like to set trainable memory bias as "defaultHiddenActivation" in PastValue function.

Is it possible to use a (trainable) vector/matrix to set "defaultHiddenActivation" in PastValue or FutureValue ?

**Comment by frankseide** [comment]
This is not directly available, but with a trick. Is this a global vector you want to train, or does it depend on the sequence?

If it is a global vector, you can do something like this:

    # global vector you want to train
    gv = Parameter (dim, 1)
    # inside recurrence over x(t)
    pb = PastValue (0, x)
    pb1 = BS.Boolean.If (BS.Loop.IsFirst (x), gv, pb)

What `If()` does is select from two inputs based on whether a condition variable is 0 (false) or 1 (true).

If it depends on the sequence, it's a little more complex, I will respond when you confirm.

**Comment by hspark84** [comment]
It is a global vector.  

Thank you for sharing your trick. I will try it right now !!
