### ISSUE TITLE
Training data generation on the fly

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#755]
Dealing with a large dataset with N samples. During training it is necessary to supply a pair of arbitrary samples to the net, so total of NxN samples theoretically could be given to the net. Generating all possible combinations into one data set is impossible as it will not fit on any reasonable storage available here.

So any example of supplying arbitrary samples from data file (in other words generating training data on the fly) (I am trying to use CNTK Python wrapper as a more flexible alternative)?

**Comment by frankseide** [comment]
Stock CNTK cannot do this at present. You would have to create a new `Deserializer` class in C++.

In about a month, you will be able to access and drive CNTK through a Python API, where you will be able to use Python iterators as data sources. This will be the solvution your problem. Sorry that we will not have a good answer earlier.

**Comment by zhouwangzw** [comment]
The CNTK V2 API in C++ and Python allows you to feed data and control training in your own application. If you still run into problems, please open a new issue.
