### ISSUE TITLE
Binary data format for classification/regression

### ISSUE THREAD

**Issue by RayFireh** [Microsoft/CNTK#756]
Dealing with large dataset with a lot of classes (for classification), a lot of samples and a lot of features (dense matrix) per sample, each feature is a float value (32 bits = 4 bytes).
When dataset is encoded into CNTK text format (like. |labels 0 0 0 1 ... |features 1.1232858394 ...) then for one float value ~12 bytes are wasted (so dataset grows minimum 4 times without classes, and when labels are added it gets even bigger), so question remains the same as here:
[https://github.com/Microsoft/CNTK/issues/433]

Any way to encode data into binary format readable by CNTK? (Numpy format maybe?)

**Comment by frankseide** [comment]
HTK feature format would work for dense vectors.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Aug 13, 2016 at 1:03 AM -0700, "RayFireh" <notifications@github.com<mailto:notifications@github.com>> wrote:


Dealing with large dataset with a lot of classes (for classification), a lot of samples and a lot of features (dense matrix) per sample, each feature is a float value (32 bits = 4 bytes).
When dataset is encoded into CNTK text format (like. |labels 0 0 0 1 ... |features 1.1232858394 ...) then for one float value ~12 bytes are wasted (so dataset grows minimum 4 times without classes, and when labels are added it gets even bigger), so question remains the same as here:
[#433<https://github.com/Microsoft/CNTK/issues/433>]

Any way to encode data into binary format readable by CNTK? (Numpy format maybe?)

-

**Comment by zhouwangzw** [comment]
Closing the issue. If you still have the  problem with the latest CNTK release, please open a new issue.
