### ISSUE TITLE
Exception error in MNIST Example

### ISSUE THREAD

**Issue by zairah10** [Microsoft/CNTK#759]
Hi,

I am new to CNTK, just started yesterday. I was trying the MNIST example and modified the 01_OneHiden.cntk to add the output file write operation, like so,
###### 
# TEST CONFIG
###### 

test = [
    action = "test"
    minibatchSize = 1024    # reduce this if you run out of memory

```
evalNodeNames = ce:errs:top5Errs

Output = [
action = "write"
mnibatch = 16
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/Test-28x28_cntk_text.txt"
        input = [
            features = [
                dim = 784
                format = "dense"
            ]
            labels = [
                dim = 10
                format = "dense"    
        ]
    ]
    format = [
        type = "category"
        labelMappingFile = "$DataDir$/labelsmap.txt"
    ]
    outputPath = "output.txt"
]
```

]

On running this file using the command, cntk configFile=../Config/01_OneHidden.cntk, the training completes successfully but I get an error in testing phase. 

EXCEPTION occured: configparameters: required parameter missing: 01_OneHidden.cntk:test:reader

Can someone help me debug this. I am also looking for some documentation on CNTK. I have been able to find only the example tutorials.

Thank you.

**Comment by mikhail-barg** [comment]
You seem to manage to mess your config somehow. As far as I see, you've mixed the "test" and "write" actions. I think you could just diff your current config to the one from example and see what went wrong.

Regarding documentation, it's rather sparse and lacking, but it exists — see wiki (https://github.com/Microsoft/CNTK/wiki) and menu at right

**Comment by frankseide** [comment]
Yes, it seems your Output section somehow moved into the test section. 'test' and 'Output' should both be on the outermost nesting level.

Some relevant documentation would be here: https://github.com/Microsoft/CNTK/wiki/CNTK-usage-overview, and also these three: https://github.com/Microsoft/CNTK/wiki/Config-File-Overview, https://github.com/Microsoft/CNTK/wiki/Train%2C-Test%2C-Eval, and https://github.com/Microsoft/CNTK/wiki/Top-level-configurations.

We will also review these docs in light of your question and try to clarify.

**Comment by zairah10** [comment]
Hi, 

I removed the output part that I had written. Now it works fine, but how do I save the output? Right now after running the 'cntk configFile=../Config/01_OneHidden.cntk' command it get this in my output folder,

<img width="514" alt="1" src="https://cloud.githubusercontent.com/assets/7130568/17756398/78c3b0be-6494-11e6-8d24-fdd4468e4c24.PNG">


and inside the Model folder I have,

<img width="369" alt="2" src="https://cloud.githubusercontent.com/assets/7130568/17756404/86c15cb6-6494-11e6-9d3a-2b8ab773279b.PNG">


But what I want is the result to be saved in the output. If I test on lets say an image of #3 then I should see something like a result.txt with 3 in it. 

Can I please get some help with this. 
Also, does the MNIST example work with only single digit numbers as input? 

Thank you for the help.

**Comment by zairah10** [comment]
Ok I found this tutorial, https://github.com/Microsoft/CNTK/wiki/CNTK-usage-overview. The last section speaks about how to use the trained model in your own code. Is it mandatory to use C#, does it support any other languages?

**Comment by n17s** [comment]
C++ is also supported. Take a look here:
https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview

**Comment by mikhail-barg** [comment]
> But what I want is the result to be saved in the output. 
You will need to add a "write" command to your config. It's described here: https://github.com/Microsoft/CNTK/wiki/Top-level-commands
You should add it as a separate command, no need to mix it with test command.
