### ISSUE TITLE
CNTK GPU EXE on non-GPU machines

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#76]
There seems to be a problem with running a GPU binary on non-GPU machines. I suggest to make MathCUDA a DLL that gets delay-loaded (which will fail in absence of CUDA drivers/libs, something we can catch and interpret as 0 GPUs available).

**Comment by wolfma61** [comment]
And what do we do then? It is a no-gpu machine and we do CPU-only execution?

We have (will have) CPU only binaries. I think it is ok to expect people to run CPU-only in the absences of a GPU.

**Comment by frankseide** [comment]
No need. IfMathCUDA does not load, it is equivalent to not having a GPU.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Tue, Feb 2, 2016 at 2:08 AM -0800, "Wolfgang Manousek" <notifications@github.com<mailto:notifications@github.com>> wrote:


And what do we do then? It is a no-gpu machine and we do CPU-only execution?

We have (will have) CPU only binaries. I think it is ok to expect people to run CPU-only in the absences of a GPU.

-

**Comment by wolfma61** [comment]
we have cpu (only) binaries for a long time ... closing
