### ISSUE TITLE
Converting DNN models Text format to CNTK model format

### ISSUE THREAD

**Issue by sandeepkothinti** [Microsoft/CNTK#761]
Hi, i would like to convert a dnn model which is pretrained using RBM-CD1 using Kaldi to CNTK dnn format. If I can write all the weights and bias parameters in the same format that CNTK dumps any dnn model, is it possible to use LoadModel() from MEL to convert this parameters to CNTK dnn? That would be really helpful as CNTK doesnt support any generative pretraining methods. 
Thanks in advance

**Comment by Howliang** [comment]
Thanks @sandeepkothinti That is something I am interested in either. I am also wondering if there is way to convert CNTK model to Kaldi DNN models. Or any idea if any fellow have tried before.
Besides, I am wondering if there is any scripts or commands that can make it possible to display the details in CNTK models? Just like the gmm-copy / nnet-am-copy command in Kaldi to tell what structure / token inside the final.mdl (Kaldi model format).

Thanks,
Hao

**Comment by cha-zhang** [comment]
https://docs.microsoft.com/en-us/cognitive-toolkit/How-do-I-Read-Things-in-Python

Closing since it's too old. Feel free to open a new issue.
