### ISSUE TITLE
mapCount seems to be replaced by mapDims

### ISSUE THREAD

**Issue by Martlgap** [Microsoft/CNTK#762]
Hey Guys, 
I was struggling a lot with the keyword mapCount inside the Convolution Function in Brainscript. CNTK reportes me an error "function does not have an optional argument 'mapCount'". 

On the wikipedia Page for Brainscript Convolution Function is the keyword mapCount listed. But CNTK is not working when using mapCount inside a config File. It should be replaced by mapDims. Maybe someone can correct this on the wiki-page so other users don´t have to find out themselves how to fix the issue. 
THX Martin

**Comment by pkranen** [comment]
Thanks for reporting! I fixed the wiki.
