### ISSUE TITLE
RecurrentLSTMPStack inputDim

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#763]
I am looking at the definition of the `RecurrentLSTMPStack` in `CNTK.core.bs`. One of the input parameters is `inputDim`. However, the parameter is not used anywhere in `RecurrentLSTMPStack` definition. Is it intentional or it is a bug?

For example, in the "ATIS" example, this parameter is set explicitly to be a well defined number (`embDim`), which then seems to be ignored inside `RecurrentLSTMPStack`.

Thank you!

**Comment by frankseide** [comment]
It has become unnecessary. The latest version no longer requires it.

**Comment by svml** [comment]
Thank you for your reply! 

Could you please let me know if you would you recommend using the latest master or the latest release (v1.6, which I am using)?

**Comment by frankseide** [comment]
Maybe use 1.6 and wait for 1.7, which is coming soon.
