### ISSUE TITLE
How to have character data admitted by CNTKTextFormatReader?

### ISSUE THREAD

**Issue by slaweks17** [Microsoft/CNTK#765]
Hi,
Is there any way of putting a character data on the CNTKTextFormatReader record? I do not want to use it for training, I just want to have in in one place, so later, I can use it in post-processing
So, what I would like to see, but CNTK objects, is e.g.
1 |i  1.2 0 2.3 |o 0.12 |nyb San_Jose 2010-02-03
1 |i  1.2 0 2.4 |o 0.13 |nyb San_Jose 2010-02-04
...
The stuff after |nyb should not be parsed by CNTK. I know that if my |nyb was a numeric vector then I could make it - CNTK would read it, but I would not use it in training.  But how to deal with non-numerics?

Regards,
Slawek

**Comment by eldakms** [comment]
You can use comments. As a sample please see i.e. here 
https://github.com/Microsoft/CNTK/blob/master/Tests/UnitTests/ReaderTests/Data/CNTKTextFormatReader/ref_data_with_escape_sequences.txt

**Comment by eldakms** [comment]
I cannot find any documentation on this. I will put an item on our backlog. Effectively if you put "|# blabla" everything till the next | is considered as comment. in your case you can do  

1 |i 1.2 0 2.3 |o 0.12 |#nyb San_Jose 2010-02-03
 1 |i 1.2 0 2.4 |o 0.13 |#nyb San_Jose 2010-02-04

So <nyb San_Jose 2010-02-03> and <nyb San_Jose 2010-02-04> will be ignored.
Hope this helps.

**Comment by n17s** [comment]
The tutorial at KDD 2016 had an example with comments in the input
https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Language-Understanding
Also, make sure the comments do not themselves contain any vertical bar characters.

**Comment by slaweks17** [comment]
Thank you!
