### ISSUE TITLE
Is it possible to get and use best model name after CV command?

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#769]
We are using `cv` command to find best model, it works fine. But after the model is found I need to manually change config file to specify found model for `write` command.

I'd like to avoid this step and somehow be able to run `write` command for the best model automatically. Is there a way to do this?

**Comment by dongyu888** [comment]
You may need to parse the cv output and rename the best model. Then launch the write command.

**Comment by mikhail-barg** [comment]
Yes, I understand that. Actually I found that I can override the model name via command line configuration, so it more or less works for me. Thanks.
