### ISSUE TITLE
Export the parameter of network

### ISSUE THREAD

**Issue by RubickH** [Microsoft/CNTK#772]
Hi!

I successfully ran cntk to solve my problem, however, I want to export the result to TF so that I can run this network on a mobile phone.

I noticed that the models saved are all binary files, and I wonder how I could export it to TF.

Thanks in advance!

**Comment by frankseide** [comment]
Would the "dumpNode" command work for you?

https://github.com/Microsoft/CNTK/wiki/Top-level-commands#dumpnode-command

**Comment by frankseide** [comment]
And, what would be the preferred format you would want to write it out? (we won't write TF or Pickle files from our C++ code, I guess, but what intermediate format would make it easy for you to ingest?)

**Comment by RubickH** [comment]
Thanks @frankseide !

But I am not quite sure how I could use the command 'dumpnode'.

I took the demo 01_OneHidden in the folder MNIST as an example, and changed the codes like this:

command = train:test:dumpnode

and added this after the 'test' action:

```
dumpnode = [
	action = "dumpnode"
	modelPath = "$ModelDir$/01_OneHidden.ckp"
	outputFile = "$OutputDir$"
]
```
However, it didn't work. Could you please show me an example of this command?

Thanks a lot!

**Comment by frankseide** [comment]
Oh yes. The `.ckp` file is not the model. It contains secondary information needed for restarting, such as the state of the momentum accumulators. The model file is `"$ModelDir$/01_OneHidden"`.

**Comment by mfuntowicz** [comment]
@frankseide [HDF5](https://en.wikipedia.org/wiki/Hierarchical_Data_Format) would be a good choice  I think. 
With that container, you can store hierarchical data the same way it appear in the Brainscript :

- hdf5file/
 - conv1
    - c
    - b
 - conv2
    - c 
    - b

etc.




In addition you can add meta data (like shape, etc.) what do you think ?

**Comment by RubickH** [comment]
Thanks everybody, I got it!

**Comment by frankseide** [comment]
Does it work for you now? If so, would you mind closing the Issue? Thanks!

**Comment by snaik-microsoft** [comment]
I am also looking for  a way to dump entire model in a readable text file.
@RubickH did you find a way to do it?

**Comment by vmazalov** [comment]
@snaik-microsoft, if the node name is not specified, the DumpNode command should dump the whole model.

**Comment by irjudson** [comment]
Is there any way to export something like PMML (http://dmg.org/pmml/v4-1/GeneralStructure.html) ?
Does that make sense?

**Comment by cha-zhang** [comment]
I'm not sure if this has been resolved. Given it's over 8 months old, I'm closing it. Please open a new issue if needed. Thanks!
