### ISSUE TITLE
Pre-Build (v1.6) Not Working on Simple2D

### ISSUE THREAD

**Issue by soroush361** [Microsoft/CNTK#775]
Hi,
## I'm new to CNTK. I downloaded "CNTK-1-6-Windows-64bit-GPU.zip" and extracted that. I also installed all files in "prerequisites" folder. I also did another step and add "cntk" folder to "Path" system environment variable. Now when I run "cntk configFile=..\Config\Sample.cntk" on "Simple2D\Data" it just shows the message below either GPU or CPU mode:

Build info:

```
            Built time: Jul 14 2016 07:16:29
            Last modified date: Wed Jul 13 07:16:25 2016
            Build type: Release
            Build target: GPU
            With 1bit-SGD: no
            Math lib: mkl
            CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
            CUB_PATH: c:\src\cub-1.4.1
            CUDNN_PATH: c:\NVIDIA\cudnn-4.0\cuda
            Build Branch: HEAD
            Build SHA1: 72bee394bf461e8f6f0feb593a8416c05f481957
            Built by svcphil on cntk-muc00
            Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
```

---

and nothing happens. I realized that CNTK runs and consume about 14% of CPU resources.
My pc is asus ROG51 (Core i7 6700K CPU and two Titan X GPU) and the os is windows 10.

Thanks in advanced.

**Comment by frankseide** [comment]
In the very first run, the CUDA driver sometimes just-in-time-compiles CUDA kernels. This is then cached by the driver, so it will not happen for subsequent runs. This precompilation may take 1..2 minutes. Could you try waiting for a few min? If it still hangs, it's a different problem.

**Comment by soroush361** [comment]
Thanks for reply.

I actually waited for about one hour without any success.
I also installed the latest Nvidia driver.

**Comment by wolfma61** [comment]
Hi - 

I have no strong idea what is going on ... 
you installed the latest Nvidia drivers you said ... can you execute
NVidia-smi.exe in C:\Program Files\NVIDIA Corporation\NVSMI and post the output?
Can't promise that this will help, but to get some more info ... thx

Wolfgang

**Comment by soroush361** [comment]
I executed NVidia-smi.exe and no message print out. I ran it through cmd. Also added argument "-L" in order to list my GPUs and again stucked without any messages.
Is it my GPUs problem? I actually can run Caffe (Windows version) program and it work ok on a single GPU.

**Comment by soroush361** [comment]
Hey,

After installing Cuda 8.0.27 my problem gone away. Both cntk and Nvidi-smi.exe worked correctly.
