### ISSUE TITLE
 AllReduceDistGradAggregator error

### ISSUE THREAD

**Issue by such87** [Microsoft/CNTK#78]
If I build with 1bitsgd=yes I get the following error:

Source/SGDLib/SGD.cpp:13:41: fatal error: AllReduceDistGradAggregator.h: No such file or directory

I do not see  AllReduceDistGradAggregator.h anywhere in the repository.

I am not using Kaldi and ACML. Building with MKL.

Please let me know what I maybe doing wrong..

**Comment by mazeLinx** [comment]
I encounter the same issue when I update my code to the latest master. Any suggestions to solve this?

**Comment by frankseide** [comment]
Our latest master had a botched submodule dependency yesterday. Please get latest and try again.

**Comment by Henry-White** [comment]
Latest master downloaded today. MS VS 2013.
CNTK_ENABLE_1BitSGD=true

6>------ Rebuild All started: Project: SGDLib, Configuration: Release x64 ------
6> Profiler.cpp
6> SGD.cpp
1> GPUSparseMatrix.cu

SGD.cpp(14): fatal error C1083: Cannot open include file: 'AllReduceDistGradAggregator.h': No such file or directory

The latest master does not contain these headers:
#include "AllReduceDistGradAggregator.h"
#include "BlockMomentumSGD.h"

**Comment by Henry-White** [comment]
Done. The command "git submodule update --init --recursive" was unsuccessfully finished but I didn't noticed that.
