### ISSUE TITLE
Efficient way to obtain product of two matrix sequences ?

### ISSUE THREAD

**Issue by hspark84** [Microsoft/CNTK#780]
Hi, all.

I'd like to get product of two matrix sequences efficiently.
(Actually, one is a matrix sequence, and the other is a vector sequence)

In 'https://github.com/Microsoft/CNTK/wiki/Times-and-TransposeTimes', it said that times of two matrix sequences is not efficient as it will launch a separate GEMM invocation for every time step.

It takes long time to train my model on this account.

Do you have any idea about efficient way to obtain product of two matrix sequences ?

**Comment by cha-zhang** [comment]
Hi, I'm closing this issue as it has been too old. If the issue remains unsolved in the latest CNTK, please open a new issue for this.
