### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load .../CNTKCustomMKL-Linux/1/x64/parallel/libmkl_cntk_p.so

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#781]
Hello,

I have compiled CNTK for Linux, but I am not able to run it due to the following error (the error appears when I try to run cntk):

`Intel MKL FATAL ERROR: Cannot load .../CNTKCustomMKL-Linux/1/x64/parallel/libmkl_cntk_p.so`

Could you please let me know what could possibly be going wrong with CNTKCustomMKL? For example, was it compiled with some specific version of some library and now it expects it? I do not get any other error messages - just this single line of text.

Thank you!

P.S. "..." stand for the beginning of the full path to the library

**Comment by svml** [comment]
I have just tried to compile and run a small program using CNTKCustomMKL-Linux libraries, and it worked fine with both parallel and sequential libraries. Which seems to indicate that the problem is with how CNTK is compiled/linked.

**Comment by wangdelp** [comment]
Hi, did you solve this problem? I've encountered the same problem, but I do not know where to get the libmkl_cntk_p.so shared library. Sounds like it can be built from teh shell file make_binary_drop_linux, but it said on teh top of this file that the file can only be run in Microsoft Internal Environment.

**Comment by wangdelp** [comment]
I've found the libmkl_cntk_p.so in the CNTK binary release and add that to the $LD_LIBRARY_PATH, now it works.

**Comment by ZhipengHan** [comment]
I got the same issue. Because I use "fish".
After I change back to "bash", the command: _source "/home/username/cntk/active_cntk"_ works.
