### ISSUE TITLE
MNIST convolution network example gives 89% errors

### ISSUE THREAD

**Issue by ValleZ** [Microsoft/CNTK#782]
binaries from https://cntk.ai/dlwg-1.6.html
example https://github.com/Microsoft/CNTK/tree/master/Examples/Image/MNIST
CNTK.exe  configFile=../Config/02_Convolution.cntk
....
BlockRandomizer::StartEpoch: epoch 0: frames [0..10000](first sequence at sample 0), data subset 0 of 1
Minibatch[1-10]: errs = 88.650% \* 10000; ce = 2.30309835 \* 10000
Final Results: Minibatch[1-10]: errs = 88.650% \* 10000; ce = 2.30309835 \* 10000; perplexity = 10.00513391

Action "test" complete.

**COMPLETED**

01_OneHidden works fine.

environment - Win10Pro, GTX 1070.

**Comment by frankseide** [comment]
Could you confirm that you have a CUDA card with compute capability >= 3.0?

**Comment by frankseide** [comment]
GTX 1070, sorry. It should be >= 3.0.

**Comment by ValleZ** [comment]
Same issue with 03_ConvBatchNorm.cntk

-------------------------------------------------------------------
Build info:

                Built time: Jul 14 2016 07:16:29
                Last modified date: Wed Jul 13 07:16:25 2016
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
                CUB_PATH: c:\src\cub-1.4.1
                CUDNN_PATH: c:\NVIDIA\cudnn-4.0\cuda
                Build Branch: HEAD
                Build SHA1: 72bee394bf461e8f6f0feb593a8416c05f481957
                Built by svcphil on cntk-muc00
                Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
-------------------------------------------------------------------
-------------------------------------------------------------------
Build info:

                Built time: Jul 14 2016 07:16:29
                Last modified date: Wed Jul 13 07:16:25 2016
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
                CUB_PATH: c:\src\cub-1.4.1
                CUDNN_PATH: c:\NVIDIA\cudnn-4.0\cuda
                Build Branch: HEAD
                Build SHA1: 72bee394bf461e8f6f0feb593a8416c05f481957
                Built by svcphil on cntk-muc00
                Build Path: c:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\
-------------------------------------------------------------------
-------------------------------------------------------------------
GPU info:

                Device[0]: cores = 2880; **computeCapability = 6.1**; type = "GeForce GTX 1070"; memory = 8192 MB
-------------------------------------------------------------------

**Comment by ValleZ** [comment]
Ah, I see why. I have only CUDA v8.0 installed. CUDA v7.5 is not installed and doesn't support GTX 1070. The bug is still valid though - cntk must fail fast in this case and tell that CUDA was not found.

**Comment by frankseide** [comment]
It seems CUDA 8 is not upwards-compatible, then?

We are working hard on getting cudnn 5 in. I expect new binaries to land in a matter of days.

**Comment by ValleZ** [comment]
Thank you! Hopefully new binaries will work fine.
CUDA v8.0 is in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0 while folder v7.5 doesn't exist on my desktop. 
Expected behavior is that CNTK must not use nonexisting software without an error message.

**Comment by frankseide** [comment]
I personally would expect runtimes like this to be upwards compatible. I.e. a program compiled against 7.5 should just run with any CUDA runtime newer than 7.5. Or if it does not, I would expect the CUDA runtime to throw an error, which we would pass on.

01_ does not use cudnn, while 02_ and 03_ do, and cudnn has changed. So for the non-cudnn, 8 is upwards compatible. With CUDA 8, you probably have cudnn 5 installed, is that possible? Maybe it is the cudnn5 runtime that is not upwards compatible (CNTK is currently built against cudnn 4).

**Comment by ValleZ** [comment]
There is CUDA_PATH environment variable which says where CUDA is located. nvcc is also in PATH env variable. I expect any SDK what uses CUDA is able to locate it given any method (PATH, CUDA_PATH) and don't have hardcoded path to CUDA v7.5. This is the best case of course. Probably CUDA itself IS backward compatible, I don't know.

In the worst case whenever an SDK uses a harcoded path to anything it should expect there may be no such path and in that case instead pretending everything is okay the SDK should tell that there is a major issue, especially it is not only about path but also about related components like the cudnn it is compiled against.

Nvidia says cudnn is part of CUDA. probably the latest CUDA uses latest cudnn which is 5.1.

**Comment by frankseide** [comment]
CUDA_PATH is only used for compiling and linking the executable. The program itself will simply try to use CUDA APIs, and if it fails, fall back to the GPU. On Windows we use delay-loading, and catch the error if the CUDA DLLs fail to load. I think on Linux the GPU build will not start without CUDA being installed. However, the CUDA APIs are not really version-constrained. I.e., we don't ask the driver for a 7.5 runtime. We just as for, e.g. a cudaContext, and as long as all CUDA API functions we call are present in whichever version is installed, it will pass.

**Comment by e-thereal** [comment]
@ValleZ Maybe I can clear up some potential confusion about paths and CNTK. There are no hard coded paths in CNTK. The build info output you showed lists the configuration of the system that was used to build the binary version of CNTK and is just of interest to the developers. Those paths are not the paths where libraries are expected when you run CNTK. You don't even need CUDA, CUB, or cuDNN to be installed. The binary package already includes all the necessary libraries. You only need to have a recent CUDA driver installed (but not the CUDA Toolkit itself).

While it's still possible that CNTK is loading the wrong libraries for some reason, I think it's more likely that there is a different problem. Can you confirm that the CUDA 8 libraries are loaded and not the libraries that come with the binary package?

**Comment by frankseide** [comment]
There is a quirk in this. Some of the CUDA libraries (cuBLAS, cuDNN) are versioned. The CNTK binary comes with copy of the NVidia libraries of the version of the SDK we built it with. Those libs behaves like any other consumer (self-written code) of the CUDA driver, and in the past this worked fine, but it is possible that there are incompatibilities between the 7.5 libs and the driver that comes with CUDA 8.

**Comment by cha-zhang** [comment]
Close this issue since it is too old. New MNIST examples are here: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Classification
