### ISSUE TITLE
R Sqared in CNTK?

### ISSUE THREAD

**Issue by Worldexe** [Microsoft/CNTK#784]
I am making regression with cntk toolkit and it'd be very convinient to be able to use R^2 as evaluation node (or criterion).
Is it possible?

**Comment by mfuntowicz** [comment]
Hi, 

You can use Brainscript to compute the R² function : 

```
RSquared(Y_true, Y_pred) = [
    mean  = Mean(Y_true)
    num   = Y_true - Y_pred
    denum = Y_true - mean 

    value = 1 - (Sum(num * num) / Sum(denum * denum))
].value
```

You'll be able to use it as output node, or criterion node :)
Morgan

**Comment by Worldexe** [comment]
Yeah, thanks!
I tried to do it myself, but I was stuck at Mean() function. I did not know it already defined, I tried re-create it with Length() and something went wrong (it did not complain about tensor sizes mismatch, but I was always getting NaN as result).

**Comment by Worldexe** [comment]
Ookay, soory, I was too fast to report =)
Your solution complains about Sum() function.
The closest alternative I see is ` #Sum (x) = FoldL (Plus, 0, x)` in CNTK.core.bs, but it is not active.
Also, there is `SumElements()` function, but I am not sure what it does.
Can you clarify what should be there?

**Comment by frankseide** [comment]
Sorry, what would you like to accomplish? Could you write your specific formula here?

To use square error, just write

    diff = pred - labelValues
    diff2 = ReduceSum (diff .* diff)
    criterionNodes = (diff2)

Is this what you want, or something more complex?

**Comment by n17s** [comment]
@fseide He is trying to do this
https://en.wikipedia.org/wiki/Coefficient_of_determination#Definitions

**Comment by Worldexe** [comment]
R squared (aka Coefficient of determination): https://en.wikipedia.org/wiki/Coefficient_of_determination
@mfuntowicz provided correct formula, it just does not compile.

**Comment by mfuntowicz** [comment]
ReduceSum should do the job, sorry for my mistake

**Comment by Worldexe** [comment]
```
      value = 1 - (ReduceSum(num * num) / ReduceSum(denum * denum))
                1                       ^
EXCEPTION occurred while evaluating: Config.bs(6): operator / cannot be applied to these operands
```
Still does not compile.
I suppose that `1` constant also should be written as `Constant(1)`.

**Comment by Worldexe** [comment]
Ookay, here I am again =)
I managed to fix some problems with vector dimensions; my code looks like this:
```
RSquared(Y_true, Y_pred) = [
    mean  = Mean(Y_true)

    res   = Minus(Y_true, Y_pred)
    tot   = Minus(Y_true, mean)

    resSq = CNTK2.Square(res)
    totSq = CNTK2.Square(tot)

    resSum = CNTK2.ReduceSum(resSq)
    totSum = CNTK2.ReduceSum(totSq)

    totSumRec = Reciprocal(totSum)

    value = ConstantTensor(1, (1)) - resSum * totSumRec
]
```

But, look at this:
```
Validating --> rs.mean = Mean (parameter_to_learn) : [1 x *] -> [1]
Validating --> rs.value.MinusArgs[0] = LearnableParameter() :  -> [1]
Validating --> rs.res = Minus (parameter_to_learn, output_layer) : [1 x *], [1 x *] -> [1 x *]
Validating --> rs.resSq = ElementTimes (rs.res, rs.res) : [1 x *], [1 x *] -> [1 x *]
Validating --> rs.resSum = ReduceElements (rs.resSq) : [1 x *] -> [1 x *]
Validating --> rs.tot = Minus (parameter_to_learn, rs.mean) : [1 x *], [1] -> [1 x *]
Validating --> rs.totSq = ElementTimes (rs.tot, rs.tot) : [1 x *], [1 x *] -> [1 x *]
Validating --> rs.totSum = ReduceElements (rs.totSq) : [1 x *] -> [1 x *]
Validating --> rs.totSumRec = Reciprocal (rs.totSum) : [1 x *] -> [1 x *]
Validating --> rs.value.MinusArgs[1] = Times (rs.resSum, rs.totSumRec) : [1 x *], [1 x *] -> [1 x 1 x *]
Validating --> rs.value = Minus (rs.value.MinusArgs[0], rs.value.MinusArgs[1]) : [1], [1 x 1 x *] -> [1 x 1 x *]
```

Look: `Validating --> rs.resSum = ReduceElements (rs.resSq) : [1 x *] -> [1 x *]`; I think it should look like this: `Validating --> rs.resSum = ReduceElements (rs.resSq) : [1 x *] -> [1]`.
Because of that, there are incorrect dimensions later and all it does not work.

How can I fix it? I tried explicitly `Reshape()`, but it does not work either.

**Comment by mikhail-barg** [comment]
What do you think of

```
    BrainScriptNetworkBuilder = [


	RSquared(yTrue, yPred) = [
		ytMean = Mean(yTrue)
		
		totErr = yTrue - ytMean
		totErrSq = totErr .* totErr
		ssTot = SumElements(totErrSq)
		ssTotRec = Reciprocal(ssTot)
		
		resErr = yPred - ytMean
		resErrSq = resErr .* resErr
		ssRes = SumElements(resErrSq)
		

		value = ConstantTensor(1, (1)) - ssRes .* ssTotRec
	].value


	data1 = Input(1)
	data2 = Input(1)
	res = RSquared(data1, data2)

	featureNodes = (data1)
	labelNodes = (data2)
	criterionNodes = (res)
	evaluationNodes = (res)
	outputNodes = (res)
    ]

```
which gives
```
Validating --> res.value.MinusArgs[0] = LearnableParameter() :  -> [1]
Validating --> data2 = InputValue() :  -> [1 x *]
Validating --> data1 = InputValue() :  -> [1 x *]
Validating --> res.ytMean = Mean (data1) : [1 x *] -> [1]
Validating --> res.resErr = Minus (data2, res.ytMean) : [1 x *], [1] -> [1 x *]
Validating --> res.resErrSq = ElementTimes (res.resErr, res.resErr) : [1 x *], [1 x *] -> [1 x *]
Validating --> res.ssRes = SumElements (res.resErrSq) : [1 x *] -> [1]
Validating --> res.totErr = Minus (data1, res.ytMean) : [1 x *], [1] -> [1 x *]
Validating --> res.totErrSq = ElementTimes (res.totErr, res.totErr) : [1 x *], [1 x *] -> [1 x *]
Validating --> res.ssTot = SumElements (res.totErrSq) : [1 x *] -> [1]
Validating --> res.ssTotRec = Reciprocal (res.ssTot) : [1] -> [1]
Validating --> res.value.MinusArgs[1] = ElementTimes (res.ssRes, res.ssTotRec) : [1], [1] -> [1]
Validating --> res = Minus (res.value.MinusArgs[0], res.value.MinusArgs[1]) : [1], [1] -> [1]
```

In general I just changed `ReduceSum` to `SumElements`, because [ReduceSum documentation](https://github.com/Microsoft/CNTK/wiki/Reduction-Operations) says 

> If the input is a sequence, reduction is performed separately for every sequence item. These operations do not support reduction over sequences.

And `SumElements` just does not have any documentation.

**Comment by Worldexe** [comment]
`SumElements` works, thanx.
Wish there were more docs for BS functions.
