### ISSUE TITLE
Confusion  about  the CNTK asynchronous forward computation algorithm in the CNTKBook.

### ISSUE THREAD

**Issue by drawfish** [Microsoft/CNTK#785]
![image](https://cloud.githubusercontent.com/assets/5672211/17917066/8b484522-69eb-11e6-8bbb-2e24a275c222.png)

When I  am reading the CNTKBook,  I have confusion about the asynchronous forward computation algorithm (Algorithm 2.3) : p is the node's parent and all the children of  p have finished their computation. It makes sence that we should move p from waitting queue to ready queue, but not the node.

**Comment by dongyu888** [comment]
Yes, you are right, it should be p.

**Comment by drawfish** [comment]
Thanks! @dongyu888
