### ISSUE TITLE
GetEvalF error LNK2019

### ISSUE THREAD

**Issue by 3xCode** [Microsoft/CNTK#786]
When i use "/cntk/Examples/Evaluation/CPPEvalClient/CPPEvalClient.cpp"
Does anyone has ever meet the question? My IDE is VS2013

**Comment by zhouwangzw** [comment]
@3xCode If you are building CppEvalClient using pre-built CNTK binaries, please make sure the directory containing EvalDll.lib is included in the library path of your project. If you are build it with CNTK source, please first build the EvallDll project, or build the cntk.sln which should automatically build the EvallDll and CppEvalClient project.

Let me know if you have further questions.

Thanks,
Zhou

**Comment by 3xCode** [comment]
hi @zhouwangzw thx :)，I have already set include path,the library path and the additional Dependencies with "EvalDll.lib" .
another error->"error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl Microsoft::MSR::CNTK::GetEvalF(class Microsoft::MSR::CNTK::IEvaluateModel<float> * *)" (__imp_?GetEvalF@CNTK@MSR@Microsoft@@YAXPAPAV?$IEvaluateModel@M@123@@Z) "

when i use Depends.exe open the EvalDll.dll, here is the result:
image[http://img.bbs.csdn.net/upload/201608/24/1471974663_277202.png](url)

**Comment by zhouwangzw** [comment]
@3xCode I cannot access the image above: 404 Page not found.
When did you get the error, e.g. using cntk.sln or the project CPPEalClient.vcxproj, or using your own project? Is the EvalDll.dll and other dependent dll in the same directory as the EvalDll.lib?

**Comment by 3xCode** [comment]
@zhouwangzw  thank you and you can put the url into the browser`s url field to access.it works.  i copy the code /cntk/Examples/Evaluation/CPPEvalClient/CPPEvalClient.cpp to my own project. The lib and dll are in the same directory.The Depends.exe says that it finds different CPU type.My CPU is i7.

**Comment by 3xCode** [comment]
@zhouwangzw  thanks.I put the EvalDll.dll (and other dlls  in cntk folder )in to C:/Windows/system32  then set the VC++ director that include path : "/cntk/Include",the library path :"/cntk/cntk",the linker->Additional dependency package :"EvalDll.lib".(CNTK for Windows v.1.6 CPU only),did i miss something?

**Comment by zhouwangzw** [comment]
@3xCode It looks like that you are using pre-built EvalDll binaries in your own project. Are EvalDll.lib available in \cntk\cntk? (I also assuming you are using "\" for path in VC settings.) Could you please also share the command line (including options) for compiler and linker? You can find them in the project property->c/c++->CommandLine and linker->CommandLine.

ps. we do not recommend to put all CNTK binaries into C:\Windows\system32. Instead you can add your cntk directory to your PATH variable.

Thanks,
Zhou

**Comment by 3xCode** [comment]
@zhouwangzw thanks.
**c/c++->CommandLine:**
/Yu"stdafx.h" /GS /analyze- /W3 /Zc:wchar_t /ZI /Gm /Od /sdl /Fd"Debug\vc120.pdb" /fp:precise /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_LIB" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /Oy- /MDd /Fa"Debug\" /EHsc /nologo /Fo"Debug\" /Fp"Debug\CNTK.pch" 
**linker->CommandLine:**
/OUT:"H:\sunyang\workspace\CNTK\Debug\CNTK.exe" /MANIFEST /NXCOMPAT /PDB:"H:\sunyang\workspace\CNTK\Debug\CNTK.pdb" /DYNAMICBASE "EvalDll.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEBUG /MACHINE:X86 /INCREMENTAL /PGD:"H:\sunyang\workspace\CNTK\Debug\CNTK.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"Debug\CNTK.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /TLBID:1

**Comment by zhouwangzw** [comment]
@3xCode  As seen from the command line, it looks like that you are building the project with 32bit X86 target.  CNTK Eval requires X64 as the target platform, as described in Wiki [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview).

Thanks,
Zhou

**Comment by 3xCode** [comment]
hi @zhouwangzw  you are great!
Thanks very much! It works. :) 
Best wishes,
sunyang

**Comment by 3xCode** [comment]
hi @zhouwangzw you are great!
Thanks very much! It works. :) 
Best wishes,
Sun

**Comment by zhouwangzw** [comment]
@3xCode You are welcome. :-)

I am closing this issue. Please feel free to reopen it if you have further questions.
