### ISSUE TITLE
cannot find -lzip

### ISSUE THREAD

**Issue by rakesh-sbm** [Microsoft/CNTK#787]
I followed the instructions as it is, and resolved many dependency problems, but couldn't find anything on it. Any help ?
----------------------------------------------------------

mpic++  -rdynamic -shared -L/rsbm/CNTK/CNTK_Master/build/release/lib -L/usr/local/cuda-7.5/lib64 -L/rsbm/Misc/cudnn/cudnn-4.0/cuda/lib64 -L/rsbm/sw-installations/openmpi-1.10.3/lib -L/rsbm/Misc/CNTKCustomMKL/1/x64/parallel -L/rsbm/sw-installations/opencv-3.1.0/lib -L/rsbm/sw-installations/opencv-3.1.0/release/lib -Wl,-rpath,'$ORIGIN' -Wl,-rpath,/usr/local/cuda-7.5/lib64 -Wl,-rpath,/rsbm/Misc/cudnn/cudnn-4.0/cuda/lib64 -Wl,-rpath,/rsbm/sw-installations/openmpi-1.10.3/lib -Wl,-rpath,/rsbm/Misc/CNTKCustomMKL/1/x64/parallel -Wl,-rpath,/rsbm/sw-installations/opencv-3.1.0/lib -Wl,-rpath,/rsbm/sw-installations/opencv-3.1.0/release/lib -o /rsbm/CNTK/CNTK_Master/build/release/lib/ImageReader.so /rsbm/CNTK/CNTK_Master/build/release/.build/Source/Readers/ImageReader/Exports.o /rsbm/CNTK/CNTK_Master/build/release/.build/Source/Readers/ImageReader/ImageConfigHelper.o /rsbm/CNTK/CNTK_Master/build/release/.build/Source/Readers/ImageReader/ImageDataDeserializer.o /rsbm/CNTK/CNTK_Master/build/release/.build/Source/Readers/ImageReader/ImageTransformers.o /rsbm/CNTK/CNTK_Master/build/release/.build/Source/Readers/ImageReader/ImageReader.o /rsbm/CNTK/CNTK_Master/build/release/.build/Source/Readers/ImageReader/ZipByteReader.o -lcntkmath -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lzip
/usr/bin/ld: cannot find -lzip
collect2: error: ld returned 1 exit status
make[1]: *** [/rsbm/CNTK/CNTK_Master/build/release/lib/ImageReader.so] Error 1
make[1]: Leaving directory `/rsbm/CNTK/CNTK_Master'
make: *** [all] Error 2

**Comment by eldakms** [comment]
Hi Rakesh,

Have you built the libzip as described here? 
https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#building-libzib

try running "configure --with-libzip" to see whether the configuration tool points to the correct directory where you have libzip installed.

**Comment by rakesh-sbm** [comment]
Yes, I did. I installed libzip-1.1.2 in a custom directory, and the path to the <custom_dir>/lib is added to LD_LIBRARY_PATH... still I get the error.

**Comment by rakesh-sbm** [comment]
strangely it worked after i installed it in the /usr/local instead of in the custom directory..
