### ISSUE TITLE
CNTK and MKL, compilation issue after pull (was ok in Jully)

### ISSUE THREAD

**Issue by ucacaxm** [Microsoft/CNTK#791]
Hi,

I compiled CNTK in July without any problem.
I did an git pull this morning and now it complains about MKL when compiling Math.vcxproj ?
I do not use any custom MKL.

error : CNTK custom MKL location not specified, see https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#optional-mkl for instructions.	D:\alex\lib\CNTK\Source\Math\Math.vcxproj	229	5	Math

Thanks,
alex

**Comment by alexeyo26** [comment]
Hello!

CNTK now uses MKL - ACML support is deprecated. You need just to install MKL as described here: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#mkl

**Comment by ucacaxm** [comment]
Thanks, I was on the page but I though that everything after
"OPTIONAL. Setting all required environment variables in batch mode"
was optional.

Sorry for the stupid question

**Comment by alexeyo26** [comment]
No, no stupid at all - we need to make the section clearer. Will do,

I will close this issue now. Thank you.
