### ISSUE TITLE
Continue training from a previously saved model

### ISSUE THREAD

**Issue by navidnadery** [Microsoft/CNTK#793]
How can i do this on bellow page: "point your continued training to that folder."

https://github.com/Microsoft/CNTK/wiki/Continue-training-from-a-previously-saved-model

Thanks @frankseide and @dongyu888  from your answer

**Comment by frankseide** [comment]
This just refers to your `modelPath`. The models of the continued training must be in a folder that is different from the original training. You copy the starting model to that new folder and make it look like it is restarting from checkpoint.

(Alternatively to a new folder, you can also just use a different model name in the same folder.)

**Comment by navidnadery** [comment]
Thank frank, you explained completely but I couldn't reach what i wanted to do with this code!
Instead I used another trick, I just renamed the file "01_Convolution" which is my final network to "01_Convolution.10" and changed the maxEpochs to 11 so it continued.

First I trained my network with maxEpochs=10 , but after that i wanted to continue it to upper epochs.
