### ISSUE TITLE
Keras backend

### ISSUE THREAD

**Issue by fchollet** [Microsoft/CNTK#797]
I wasn't sure how to contact anyone working on CNTK, so I'm opening an issue here.
I was reading this comment:

https://github.com/Microsoft/CNTK/blob/9d6345b2fa794c38b4f02f71631ea71401b97362/Tests/EndToEndTests/Speech/QuickE2E/cntk.cntk#L26

`# This version shows an experimental function-composition based approach to network declaration, similar to Keras.`

Would there be any interest on your part in developing a CNTK backend for Keras? I know that quite a few Keras users are on Windows, and they are relying on Theano as a backend for now. But being able to build models in Python with the Keras API and run them using CNTK could be a game-changer for many windows-using deep learning practitioners. Lots of Keras+Windows users would switch.

Thoughts?

**Comment by jeanfad** [comment]
Hi François, 

 We definitely have interest in developing a CNTK Keras backend, it is actually part of our plans. We are now working on the Python API for CNTK v2, and we plan to build on top of it a Keras backend. 

Please find below a list of people involved in CNTK v2:
Willi Richert
Amit Agarwal
Frank Seide
My self

Best Regards,
Jean Baptiste

**Comment by fchollet** [comment]
Sounds great! Let me know if you need any help in the future.

**Comment by jeanfad** [comment]
Thanks, we will !

**Comment by fcivardi** [comment]
I agree that it will be really a game-changer for Windows user.  I started learning deeplearning (!) with Keras on Theano, because it's really easy to make experiments there. Now, Keras can work on Tensorflow for Linux users, but Windows users?

**Comment by wangdelp** [comment]
That's really useful. 
@jeanfad what's the major difference between CNTK V2 vs V1? I am trying to add some new ops based on current ops available in CNTK python interface, is it better to use CNTK V2 or V1? Thank you.

**Comment by frankseide** [comment]
CNTK V2.

**Comment by wangdelp** [comment]
@frankseide thanks, frank. I have developed some new ops using CNTK python V2, is there a way to register the new ops so that I can use the op name directly in .cntk config files? Or do I need to compile the model architecture using python scripts? Thank you.

**Comment by oak-tree** [comment]
Hey!
Any updates on CNTK as backend for `keras`?
Thanks!

**Comment by karthiksn** [comment]
+1, really interested in this! 👍

**Comment by leo-gan** [comment]
IMHO, absence of Keras support is very-very bad for CNTK. It's the first priority issue!

**Comment by fcivardi** [comment]
Any news about Keras support?

**Comment by teochenglim** [comment]
+1 cntk Keras on Windows and Linux

**Comment by JulesVerny** [comment]
Don't we [I would prefer] mean a Keras Front end API, being much simpler than CNTK, with CNTK back end. Personally  my ideal would be a C# Keras API front end to NN networks, so I could integrate NN technology into system solutions.

**Comment by josaum** [comment]
Any news about Keras support?

**Comment by lukeyeager** [comment]
See https://github.com/fchollet/keras/pull/6800

**Comment by JimSEOW** [comment]
Please check the latest .NET CNTK [links](https://github.com/Microsoft/CNTK/issues/960#issuecomment-306508050)

**Comment by n17s** [comment]
Closing this. The Keras CNTK backend has been merged to fchollet/keras master
