### ISSUE TITLE
multi task learning (MTL)

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#798]
TIMIT config contains an example of multi-task learning. I want to know it can be applied to kaldi2reader as well. Also, is it possible to use multiple readers for a single config for MTL? 

If there is any reference CNTK code (ndl or brain script) based on kaldi2reader, it would be great.

**Comment by dongyu888** [comment]
I believe the kaldi2reader and htkmlfreader shares the same basic reader features. Yu Zhang can confirm.

 

In HTKMLFReader you can use multiple readers. E.g., 

 

reader=[

      # reader to use

      readerType=HTKMLFReader

      readMethod=blockRandomize

      miniBatchMode=Partial

      randomize=Auto

      verbosity=0  

 

      net.features=[

          dim=$_baseFeatDim$

          contextWindow=$_leftFeatContext$:$_rightFeatContext$ 

          scpFile="$DataFolder$/train_data/train_ymag.scp"

      ]

 

      net.x1mag=[

          dim=$_baseTargetDim$

          contextWindow=$_leftTargetContext$:$_rightTargetContext$         

          scpFile="$DataFolder$/train_data/train_x1mag.scp"

      ]

 

      net.x2mag=[

          dim=$_baseTargetDim$

          contextWindow=$_leftTargetContext$:$_rightTargetContext$         

          scpFile="$DataFolder$/train_data/train_x2mag.scp"

      ]

 

      net.ymag=[

          dim=$_baseTargetDim$

          contextWindow=$_leftTargetContext$:$_rightTargetContext$         

          scpFile="$DataFolder$/train_data/train_ymag.scp"

      ]

    ]

**Comment by funguy74** [comment]
Thanks for your quick answer. One more question is that is it okay to use feature type input as output label in MTL? For example, HTK gets two types of input: scp and mlf. Usually, scp is for feature description and mlf is for label. For MTL, is it okay to direct scp type input for MTL output label?

**Comment by dongyu888** [comment]
Yes, there is no distinction between features and labels actually. In the example I copied in last post, everything is scp.

**Comment by funguy74** [comment]
Thank you for clarification. Can I ask you one more thing? I haven't seen 'contextWindow' in tutorial. Tutorial only describes symmetric context implicitly by setting dim. I'm wondering it enables asymmetric context window.

**Comment by dongyu888** [comment]
Yes, this enables asymmetric context window. I am not sure whether this is also available in Kaldi2Reader though.

**Comment by funguy74** [comment]
Thanks for your answers. I'll close this thread.

**Comment by datavizweb** [comment]
I came across this thread while searching for contextWindow. This is not documented in the wiki, however  is useful.
