### ISSUE TITLE
Edit CNTK book and online document to reflect the new changes.

### ISSUE THREAD

**Issue by dongyu888** [Microsoft/CNTK#8]
Edit CNTK book and online document to reflect the new changes, esp. new nodes we enabled, the config to run parallel training, and the new programmer's guide.

**Comment by mohamedmansour** [comment]
Please do, the book is really great, would be nice to see the new additions in it!

**Comment by wolfma61** [comment]
major work is going into the Wiki and the wiki right now, the PDF is not kept in sync.
The Wiki is also being enhanced with tutorial sections etc.

**Comment by wolfma61** [comment]
see tracking issue #36
