### ISSUE TITLE
Plugin not found: 'CNTKTextFormatReader.dll'

### ISSUE THREAD

**Issue by FanChengYi** [Microsoft/CNTK#801]
when I try to run the example of Simple2D,the exception occurded,"Plugin not found: 'CNTKTextFormatReader.dll'".what's the matter? 
thanks

**Comment by dongyu888** [comment]
This means the reader CNTKTextFormatReade used in the sample cannot be found. Typically it means you did not compile this reader or did not copy 'CNTKTextFormatReader.dll' along with the main program.

**Comment by FanChengYi** [comment]
I did it after compiling the reader.
Thank you very much!
