### ISSUE TITLE
Faster model loading

### ISSUE THREAD

**Issue by PatrickBue** [Microsoft/CNTK#802]
Hi,

I am setting up a web service using a AlexNet CNTK for a customer. Because of a tight deadline I have to load the model every time an image is uploaded (the code is in python and just calls cntk.exe). Is there a way to skip the initial checks or somehow else make the model loading faster?

Thanks,
Patrick

**Comment by n17s** [comment]
Is it running on Windows?

**Comment by PatrickBue** [comment]
Yes.

**Comment by n17s** [comment]
Sorry, I do not know of a simple way to do it. I would modify this https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CPPEvalClient/CPPEvalClient.cpp
to continuously read data from stdin and have the python driver write the inputs to your .exe's stdin.

**Comment by PatrickBue** [comment]
Hi Nikos, thanks for your help!
