### ISSUE TITLE
ImageParameter(...) function

### ISSUE THREAD

**Issue by adaber** [Microsoft/CNTK#804]
Hello,

Sorry if this question doesn't belong to this section/forum. Feel free to close/remove it if so.

I've tried to find a description of the function ImageParameter(...) but couldn't find it anywhere. I can definitely guess what it does but it'd be great if someone could provide a full explanation of this function or a link to it.

Thanks!

**Comment by dongyu888** [comment]
This was the old way to specify a tensor used for image. It should have 3 or more parameters [imageWidth, imageHeight, imageChannels] plus other optional parameters (learningRateMultiplier=[1|0|float], init=[uniform|gaussian|fixedvalue], initValueScale=[1|float], value=[0|float]).

 

It has been replaced by ParameterTensor in the new version and in brainscript. ParameterTensor is more flexible.

**Comment by adaber** [comment]
Thank you for the quick response, dongyu. It's very appreciated!

**Comment by frankseide** [comment]
This is the documentation: https://github.com/Microsoft/CNTK/wiki/Parameters-And-Constants#parametertensor

For your desired case, you would say

    p = ParameterTensor {(imageWidth:imageHeight:imageChannels)}

I am curious, what are you using it for? Which operation requires you to specify the image dimensions directly?

**Comment by adaber** [comment]
Hi, frankseide

Thanks for the link.

I am working on an image classification system using CNN and was looking at the CIFAR-10 macros/examples and noticed that function.  It can be found in Macros.ndl. I've tried to find a description of it online but couldn't find any.

P.S. A random find. It seems that the "first part" link (Tutorial2 page, Introduction section) is broken. https://github.com/Microsoft/CNTK/wiki/Tutorial2.

The "first part" link points to https://.../CNTK-Docu-Private... instead of https://.../CNTK...

**Comment by n17s** [comment]
Thanks. It's now fixed.
