### ISSUE TITLE
Tutorial for using a trained model ?

### ISSUE THREAD

**Issue by golgel** [Microsoft/CNTK#806]
Hello, I am new to the CNTK and I was wondering if there is a tutorial that shows how to use a trained network model (for example the penntreebank rnn)? I get the gist from training it but can I also use the .config to provide sentences/words as Input and see the output of the model? Is there a tutorial for this?

**Comment by junjieqian** [comment]
https://github.com/Microsoft/CNTK/wiki/BS-Model-Editing explains the related issue.

**Comment by frankseide** [comment]
Or are you just looking for the ["write" action](https://github.com/Microsoft/CNTK/wiki/Top-level-commands#write-command)? The first Tutorial has an [example here](https://github.com/Microsoft/CNTK/wiki/Tutorial#command-output).

**Comment by golgel** [comment]
I missed the write action in the tutorial, thanks.

With the regular penntreebank example:

- Is there a way to get the perplexity in a seperate file during the validation?

- When the RNN is fully trained and I write something to the rnn with the write command (</s> this is a test sentence </s>) I get the output from each neuron in the last layer. Is there currently a way to see with which probability the rnn predicted each word in the sentence?

**Comment by cha-zhang** [comment]
I hope this has been resolved. I'm closing it now since it's very old. Examples on evaluating a model can be found here: 
https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation
