### ISSUE TITLE
Image reader

### ISSUE THREAD

**Issue by Arminea** [Microsoft/CNTK#807]
Hi, I'm trying to use Image reader. At this time I have a dataset of 64x64 images but I would like to use a dataset of images with various sizes. My questions are

1. Do I need any external preprocessing, for resizing images?
2. If not, which parameters of the Image reader should I use?

I'm asking because a mean file is used by image reader and I assume that this file is made of resized images.
My last question is about label dimension. I want to perform binary classification. In tutorial there is `LDim` set to `1` but when I set a label dimension to `1` I get an exception
`EXCEPTION occurred: Image 'D:\CNTK\data\dir_train.zip@\Image1_.png' has invalid class id '1'. Expected label dimension is '1'`
so I had to set label dimension to `2`.

`3`. Is my label dimension correct for binary classification of images?

**Comment by frankseide** [comment]
For the label dimension, CNTK internally thinks of labels as one-hot vectors. `labelDim` must be equal to the number of classes. If you have 2 classes, then the label is a 2-dimensional vector with a 1 at the position of the correct class.

**Comment by pkranen** [comment]
The mean file is optional, you can also just uncomment or remove that line in the config. In that case you might want to subtract a constant value from your features for normalization in your network definition, for example

`featNorm = features - Constant (114)`

A constant value works fine for large image corpora like ImageNet for example. If you want to use a mean file then yes it computed as the average over all resized images in your training set.

**Comment by eldakms** [comment]
Philipp explained that perfectly. I have also updated the error message to be more descriptive (on latest master). Thank you!

**Comment by Arminea** [comment]
@pkranen How do you determine the constant value for normalization?

**Comment by pkranen** [comment]
It's the global average over all pixels and color channels of all image in your training set. For ImageNet we use 114 as the constant (RGB values range from 0 to 255).

**Comment by frankseide** [comment]
Note that the impact of this is not on the model's expressiveness (a constant offset can be compensated by the first layer's bias), but for training convergence (the first layer's matrix' gradient is input*gradient^T, an additive constant on the input will affect the gradient in a non-beneficial way)

With that in mind, assuming a mean of 128 will get you quite far already, compared to not normalizing it at all.

**Comment by n17s** [comment]
Closing this. Feel free to reopen if necessary.
