### ISSUE TITLE
DSSM/CDSSM tutorial?

### ISSUE THREAD

**Issue by budhiraja** [Microsoft/CNTK#808]
I look through previous issues and wiki pages but couldn't find a tutorial or example of DSSM/CDSSM? Is there one available?

**Comment by n17s** [comment]
For a DSSM example that takes images and compares them the following example is the closest we have
https://github.com/Microsoft/CNTK/wiki/Layers-Reference#parameter-sharing
In most cases however you want separate parameters for the two subnets so you will need to have two separate instances of Sequential(). If you have text data you should use cntk text format reader with two input streams as explained here:
https://github.com/Microsoft/CNTK/wiki/CNTKTextFormat-Reader#a-few-real-world-examples

**Comment by jplu** [comment]
Is it possible to have a tutorial of DSSM in the hands-on labs section in [tutorials](https://github.com/Microsoft/CNTK/wiki/Tutorials) or at least a full example of a simple use case in the [example](https://github.com/Microsoft/CNTK/wiki/Examples) page?

**Comment by frankseide** [comment]
I asked a colleague who did DSSM to create a "How Do I..." page. But it may take a few days.

**Comment by jplu** [comment]
Super! Thanks.

**Comment by jplu** [comment]
Any update for the tutorial?

**Comment by budhiraja** [comment]
Any update for the tutorial?

**Comment by Anikacyp** [comment]
Any update for the tutorial???

**Comment by sayanpa** [comment]
Here is a link to the tutorial:
https://docs.microsoft.com/en-us/cognitive-toolkit/how-do-i-train-models-in-brainscript#train-a-dssm-or-a-convolutional-dssm-model. We do not have a python equivalent. Happy to take in contribution.
