### ISSUE TITLE
dump node value during training

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#809]
I want to dump node outputs to file/standard output during network training for debugging purpose. Is there any way to achieve this in CNTK? I can find some commands like dump/dumpnode but they looks like dumping node structures (not node output).

**Comment by vmazalov** [comment]
Take a look at the Write command: https://github.com/Microsoft/CNTK/wiki/Top-level-commands

**Comment by frankseide** [comment]
One is the TraceNode, e.g.

    TraceState (h, what) = Transpose (Trace (Transpose (h), say=what, logFirst=10, logFrequency=100, logGradientToo=false, onlyUpToRow=9, onlyUpToT=3, format=[ type = "real" ; transpose = false ; precisionFormat = ".4" ]))
    TraceDense (h, what) = Trace (h, say=what, logFirst=10, logFrequency=100, logGradientToo=false, onlyUpToRow=21, onlyUpToT=25, format=[ type = "real" ; transpose = false ; precisionFormat = ".4" ])
    TraceDenseTransposed (h, what) = Trace (h, say=what, logFirst=10, logFrequency=100, logGradientToo=false, onlyUpToRow=9, onlyUpToT=25, format=[ type = "real" ; transpose = true ; precisionFormat = ".4" ])
    TraceOneHot (h, what) = Trace (h, say=what, logFirst=10, logFrequency=100, logGradientToo=false, format=[ type = "category" ; transpose = false ])
    TraceSparse (h, what) = Trace (h, say=what, logFirst=10, logFrequency=100, logGradientToo=false, format=[ type = "sparse" ; transpose = false ])

Instead of e.g. saying

    y = Sigmoid (z)

you say

    y = TraceDense (Sigmoid (z), "y")

There is also a debugging facility to select nodes for logging during training, e.g. in the SGD block say

    traceNodeNamesReal = y:z

likewise `traceNodeNamesCategory` and `traceNodeNamesSparse`.

Both methods have some issues, which is the reason they are not official.

**Comment by funguy74** [comment]
Thanks for your answer. For TraceDense, can I use it in ndl? or is it for brainscript only?
For traceNodeNamesReal , if we like to log three nodes y1,y2,y3, then the rule is

 traceNodeNamesReal =y1:y2:y3 --> is it right?

**Comment by frankseide** [comment]
TraceNode is only defined in BrainScript. `traceNodeNamesReal` works for both. Your syntax is correct.

**Comment by funguy74** [comment]
I added traceNodeNamesReal in ndl file but I don't see any logging in log output. Does it appear any other place?

**Comment by frankseide** [comment]
It should be in the SGD block. Could you let me know the actual node name?

```
    SGD(const ConfigRecordType& configSGD)
        : SGDParams(configSGD, sizeof(ElemType)),
          // TODO: The next few do not belong into SGD any more than the network or reader we operate on. Either move network and reader in here, or move these out.
          m_modelPath((const wstring&) configSGD(L"modelPath")),
          m_keepCheckPointFiles(configSGD(L"keepCheckPointFiles", false)),
          m_trainCriterionNodeName((const wstring&) configSGD(L"trainCriterionNodeName", L"")),
          m_evalCriterionNodeName ((const wstring&) configSGD(L"evalCriterionNodeName", L"")),
          m_traceNodeNamesReal    (configSGD(L"traceNodeNamesReal",     ConfigRecordType::Array(stringargvector()))),
          m_traceNodeNamesCategory(configSGD(L"traceNodeNamesCategory", ConfigRecordType::Array(stringargvector()))),
          m_traceNodeNamesSparse  (configSGD(L"traceNodeNamesSparse",   ConfigRecordType::Array(stringargvector()))),
```

**Comment by funguy74** [comment]
I tested it for AN4 example with LSTM ndl

I run in the AN4 data directory: cntk configFile=../Config/LSTM-NDL.cntk

I added following line in SGD block of LSTM-NDL.cntk:
 traceNodeNamesReal =LSTMoutput1

Is it correct? I still don't see any logging.

**Comment by cha-zhang** [comment]
I'm not sure if this has been resolved, but it's been very old. Please try the latest 2.0 release and see if there are still issues. Feel free to open a new issue if needed. Thanks!
