### ISSUE TITLE
Static analysis of CNTK with PVS-Studio

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [Microsoft/CNTK#81]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the Computational Network Toolkit project.

Here is the link to the article about it: http://www.viva64.com/en/b/0372/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by veikkoeeva** [comment]
@SvyatoslavRazmyslov Or can I add here that if you could check [Orleans](https://github.com/dotnet/orleans) while at it? :)

**Comment by SvyatoslavRazmyslov** [comment]
@veikkoeeva I am already writing an article about Orleans :-) I will publish it in the nearest future.

**Comment by frankseide** [comment]
Thank you so much! Let me go through and address the issues that you have not submitted yet.

**Comment by frankseide** [comment]
I have addressed all issues called out in the article, it will land soon. Thanks again!
