### ISSUE TITLE
How to enable multiple GPUs in training acoustic model?

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#811]
A script "train_cntk2.sh" is given in example of AMI
How should I modify the script to enable multiple GPUs training?
The core part in "train_cntk2.sh" is as follows:
## training command ##
$cn_gpu configFile=${expdir}/Base.config configFile=${expdir}/CNTK2.cntk DeviceNumber=0 action=TrainDNN ndlfile=$ndlfile
echo "$0 successfuly finished.. $dir"

cntk_string="$cn_gpu configFile=$config_write DeviceNumber=0 modelName=$cnmodel labelDim=$labelDim featDim=$featDim action=$action ExpDir=$expdir numThreads=$nthead"
scripts/decode_cntk2.sh  --nj 1 --cmd run.pl  --acwt 0.0833 --class-frame-counts "$class_frame_counts" \
$graphdir $datadir/eval $expdir/decode_ami_fsh.o3g.kn.pr1-7.2 "$cntk_string" || exit 1;

**Comment by vmazalov** [comment]
Take a look at the parallelTrain section in https://github.com/Microsoft/CNTK/wiki/SGD-Block

**Comment by frankseide** [comment]
Or the hands-on tutorials:
https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Image-Recognition#task-6-parallel-training
https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Language-Understanding#task-5-parallel-training
