### ISSUE TITLE
Image Hands-On Lab

### ISSUE THREAD

**Issue by fcivardi** [Microsoft/CNTK#813]
I think a python script is missing, the one downloading and unzipping the CIFAR-10 dataset. There are just the commands for Linux:

wget -rc http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
tar xvf www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
python CifarConverter.py cifar-10-batches-py

**Comment by eldakms** [comment]
Hi fcivardi,

Which version are you using? In the latest 1.7 GPU binary drop for Linux there is CifarDownload script that does that. It is in cntk/Examples/Image/Miscellaneous/cifar-10/CifarDownload. Readme in the same folder describes how to run it.
Thanks!

**Comment by fcivardi** [comment]
Thank you, I was looking here: CNTK-master\Tutorials\ImageHandsOn and I couldn't find it (there is only the converter there). As you said, it's in cntk/Examples/Image/Miscellaneous/cifar-10/CifarDownload.
I'm using the latest 1.7 GPU binary for Windows. 
Thanks!

**Comment by eldakms** [comment]
I'm closing this then. Thanks!

**Comment by frankseide** [comment]
I just checked. The script is in the repo in the Tutorials folder: https://github.com/Microsoft/CNTK/blob/master/Tutorials/ImageHandsOn/CifarConverter.py

@fcivardi, could you confirm that it is not there in the binary distribution? @eldakms, maybe our binary packer script does not copy it?

**Comment by eldakms** [comment]
I think we are talking about CifarDownload? :)

**Comment by fcivardi** [comment]
Yes, in the new tutorial folder for ImageHandsOn there is only CifarConverter.py, not CifarDownload.py (which can be found in the old tutorial).  To make life simple, I suggest to put both in ImageHandsOn as well ;-)

**Comment by fcivardi** [comment]
Btw, thanks for the new tutorials, they are great!

**Comment by frankseide** [comment]
You don't need CifarDownload.py for the ImageHandsOn,.

**Comment by fcivardi** [comment]
I wrongly thought it was only for Linux, not for Windows.
