### ISSUE TITLE
DICOM Images

### ISSUE THREAD

**Issue by fcivardi** [Microsoft/CNTK#815]
I need to work on DICOM medical images. I see there is a Python library to read them. What should I do in order to feed CNTK? convert them into a more common format?
Thanks

**Comment by frankseide** [comment]
That would be mthe easiest way. The CifarConverter.py script in the ImageHandsOn converts images from a custom format to PNG. You can use that, I guess.

**Comment by fcivardi** [comment]
Vielen Dank, und bis bald in Atlanta!
