### ISSUE TITLE
Python example error: OSError 

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#818]
I tried to run python example but I got following errors when I run logreg.py. Can I get some hint what it is?

> jaey1.kim@ubuntu:~/work/tmp/cntk/contrib/Python/cntk/examples/LogReg$ python logreg.py 
> Traceback (most recent call last):
>   File "logreg.py", line 73, in <module>
>     print(train_eval_logistic_regression_from_file())
>   File "logreg.py", line 56, in train_eval_logistic_regression_from_file
>     input_map=train_reader.map(X, alias='I', dim=2).map(y, alias='L', dim=3))
>   File "../../../cntk/context.py", line 690, in train
>     action_name = action_name)
>   File "../../../cntk/context.py", line 423, in _call_cntk
>     stderr=subprocess.STDOUT)
>   File "/home/jaey1.kim/anaconda2/lib/python2.7/subprocess.py", line 567, in check_output
>     process = Popen(stdout=PIPE, _popenargs, *_kwargs)
>   File "/home/jaey1.kim/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/home/jaey1.kim/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by cha-zhang** [comment]
Sorry we didn't answer your question at that time. I'm closing it since it's too old. If you have new questions, please open a new issue. Thanks!
