### ISSUE TITLE
BatchNormalization CPU - CloneFunction - Frozen parameters

### ISSUE THREAD

**Issue by mfuntowicz** [Microsoft/CNTK#819]
Hi guys !

I'm trying to train a model based on ResNet using Transfer Learning with the lastest CNTK build 1.7 and CloneFunction.

Everything goes right (Loading model/ Preprocessing / Validating). But when it comes to training, CNTK complains about BatchNormalization nodes which doesn't support training on CPU as it is not implemented yet (argh).

As I've cloned the subgraph of ResNet with frozen params, I was wondering if a trick may exists to overcome the "BN training on CPU is not yet implemented" in this particular case ? 

Thanks, 
Morgan

```
[CALL STACK]
    > Microsoft::MSR::CNTK::Matrix<float>::  BatchNormalizationForward
    - Microsoft::MSR::CNTK::GPUMatrix<double>::  MaskColumnsValue
...
EXCEPTION occurred: Batch normalization training on CPU is not yet implemented.
```

**Comment by pkranen** [comment]
Cloning ResNet models should work fine with newer bits. Please try the latest. Closing this issue, please open a new one if the problem remains with newer bits.
