### ISSUE TITLE
"needGradient" vs "needsGradient" vs "computeGradient"

### ISSUE THREAD

**Issue by frankseide** [Microsoft/CNTK#82]
These are inconsistent. We should settle on one (but keep the current for back compat).

MEL:
        if (EqualInsensitive(propName, "computeGradient", "needsGradient"))
NDL:
            bool needGradient = node->GetOptionalParameter("needGradient", "false");

**Comment by dongyu888** [comment]
a fix with the new feature of per learnable parameter learning rate scale has been pushed to dongyu/needsGradientChange branch. Waiting for the BrainScript side change (from Frank Seide) before merging it to master.
