### ISSUE TITLE
Semantic segmentation?

### ISSUE THREAD

**Issue by bulatGH** [Microsoft/CNTK#820]
Hi, I was wondering if you implemented semantic segmentation? Or maybe there is a way to provide 2D images as networks output?

**Comment by e-thereal** [comment]
I think the easiest way to do that is to use to image readers, one for the input and one for the label image and to ignore label field. If you have multiple output classes, you might have to transform your label image into a 1-of-N encoding for each pixel, if you want to use a per-pixel softmax. I've sucessfully used a similar approach for semantic segmenation of multiple organs in 3D CT images, with a custom reader, but you should be able to get the same thing in 2D with just the readers provided.

**Comment by bulatGH** [comment]
Thank you for the answer, I was also thinking if it would be reasonable to convert segmentation into a vector and make predictions using it.

Actually, I was wondering if you have released your code sample for 3D image segmentation?

**Comment by e-thereal** [comment]
Everything is still work in progress so we haven't released any code yet.

**Comment by cha-zhang** [comment]
2D images as network output is doable with composite readers today. Since this thread is very old, I'm closing it. 

We haven't made a segmentation example yet but we will soon. Please follow our iteration plan for when it will be coming.
