### ISSUE TITLE
C# Evaluation wrapper - CNTK model format newer than library version

### ISSUE THREAD

**Issue by mfuntowicz** [Microsoft/CNTK#821]
Hi, 

I'm using the 1.7 version of the C# EvalWrapper, but when I load the model (trained with 1.7 binary release) I got : 

Exception levée : 'Microsoft.MSR.CNTK.Extensibility.Managed.CNTKInvalidArgumentException' dans EvalWrapper.dll

Informations supplémentaires : Read: The model file has a newer format version (14) than this CNTK version can handle (9).

(The CNTK model version 9 correspond to the ComputationNetwork.h on tag v1.6)

It's a problem with the Nuget package ?

**Comment by zhouwangzw** [comment]
@mfuntowicz The error indicates that the Eval version you are using is too old. Could you please have a double check that you are using the 1.7 Eval Nuget Package? For safety, you might want to uninstall the existing package from your solution, and re-install the 1.7 Eval Nuget package from the nuget server as specified in Wiki: https://www.nuget.org/packages/Microsoft.Research.CNTK.CpuEval-mkl/

If you still have the same problem, could you please post the screen short showing the Nuget package information of your project? You can get it by right clicking on your project->Manage Nuget Packages-> click on "Microsoft CNTK Eval CPUOnly-mkl NuGet..", and the right pane showing the information of the Nuget package.

Thanks,
Zhou

**Comment by mfuntowicz** [comment]
I uninstalled nuget package, cleaned project, reinstalled and recompiled to check as you mentioned, still the error about model version.


Strange things: Information provided on the "Manage Nuget Packages" are not concording each others, see : 

![image](https://cloud.githubusercontent.com/assets/2241520/18313819/b6a7c92e-7510-11e6-919c-a41ddc05c663.png)

![image](https://cloud.githubusercontent.com/assets/2241520/18313830/c135498e-7510-11e6-88a4-707e9f3fa169.png)

**Comment by zhouwangzw** [comment]
@mfuntowicz You likely need to click the "update " button, right to the "Version: 1.6.0", to update the currently being used Nuget version from 1.6 to 1.7.

Thanks,
Zhou

**Comment by mfuntowicz** [comment]
The update button currently uninstall 1.7 to install 1.6.

(Sorry in French)
```
Package 'Microsoft.Research.CNTK.CpuEval-mkl.1.7.0' supprimé de 'packages.config'
Désinstallation réussie de « Microsoft.Research.CNTK.CpuEval-mkl.1.7.0 » de Kuka.IntelligenceNetwork
Ajout du package 'Microsoft.Research.CNTK.CpuEval-mkl.1.6.0' au dossier 'C:\Users\Morgan\Workspace\Kuka\Kuka\packages'
Package 'Microsoft.Research.CNTK.CpuEval-mkl.1.6.0' ajouté au dossier 'C:\Users\Morgan\Workspace\Kuka\Kuka\packages'
Package 'Microsoft.Research.CNTK.CpuEval-mkl.1.6.0' ajouté à 'packages.config'
Installation réussie de « Microsoft.Research.CNTK.CpuEval-mkl 1.6.0 » sur Kuka.IntelligenceNetwork
Suppression du package 'Microsoft.Research.CNTK.CpuEval-mkl.1.7.0' du dossier 'C:\Users\Morgan\Workspace\Kuka\Kuka\packages'
```

The details for the 1.6 package are really strange as it is reported as the version 1.7 (and the 1.7 version on Nuget reports as 1.6 in details)

![image](https://cloud.githubusercontent.com/assets/2241520/18314570/e59212b4-7513-11e6-92cf-6a1b8ea22deb.png)

Both versions throw the same error about model version newer than the eval library

**Comment by zhouwangzw** [comment]
@mfuntowicz You might want to choose "1.7" in the drop down list, right to "version" and left to "update", and then click on "update". It is not very clear to see whether you can choose the version there. Otherwise, I would suggest to uninstall the nuget for the SOLUTION by Tools-> Nuget Package Manager -> Manage Nuget Packages for Solutions -> Select the CNTK Eval package and click on "manage"-> uncheck the Solution. After that, please re-build your solution again, and you should get build errors, as the Eval NuGet package is not available. Then, try to re-install the 1.7 version of NuGet package.

Thanks,
Zhou

**Comment by mfuntowicz** [comment]
I'll try with a blank project to see if it's working.

I'll let you know @zhouwangzw 

Thanks for your help !

**Comment by mfuntowicz** [comment]
Hi @zhouwangzw 

I finally get it working, but only on a fresh on a computer with a fresh install of Windows. It never worked on my laptop by upgrading the dependency ... Very strange, but not related to CNTK :).

Thanks for your help anyway :)
Morgan
