### ISSUE TITLE
unrequired boost dependencies

### ISSUE THREAD

**Issue by jbalma** [Microsoft/CNTK#825]
Unnecessary boost dependencies have been added to the Makefile for the ImageReader library which are break old builds and are redundant given the same functionality is available in C++ 11 standard library under <random> using the same syntax. This forces users to build boost and is a significant change from previous versions of CNTK's ImageReader library.

Changes are only needed to the Makefile and Source/Readers/ImageReader/Exports.cpp|h

**Comment by n17s** [comment]
This is indeed very unfortunate. The boost dependency is something we debated a lot about and we would have preferred to avoid it but unfortunately we could not find a better way. We need access to a cross-platform implementation of various probability distributions. C++11 provides cross-platform random engines but not cross-platform distributions.

**Comment by mahilleb-msft** [comment]
Cf. @n17s's comment, this dependency is here to stay... Closing the issue...

**Comment by veikkoeeva** [comment]
A curious lurker, what kind of cross-platform distributions are the issue? Looking at [<random>](http://en.cppreference.com/w/cpp/header/random), therere are various distributions. I don't know if those are lacking on some or all platforms, but I'd be curious to know, though.
