### ISSUE TITLE
How to write output of tensor node ?

### ISSUE THREAD

**Issue by cartacarta** [Microsoft/CNTK#828]
How can I output the values of a tensor node like this one:
output.conv.b = LearnableParameter() :  -> [1 x 1 x 5] 

I tried using the Write command with output nodes like this:
outputNodeNames = output.conv.b

But it only outputs the first value.  I know that I can get the full tensor if I use action = "dumpNode", but I am trying to learn how to get any type of value during evaluation for debugging purposes (the bias tensor is just an example).

Do I need to slice or convert that output.conv.b as part of the model and then output that? or is there any syntax that would allow me to get a particular slice in the write command?

Thanks!
Alejandro

**Comment by frankseide** [comment]
This was a bug which was recently fixed (I think it is not merged yet into master). It ignored the column dimension of tensors without batch axis.

**Comment by cartacarta** [comment]
Got it. Thank you for the clarification.
