### ISSUE TITLE
does the cntk\MNIST identification call dll interface in that?

### ISSUE THREAD

**Issue by nyav** [Microsoft/CNTK#829]
Excuse me, does the cntk\MNIST identification call dll interface in that?
C:\cntk\Examples\Image\MNIST\Config\02_Convolution_ndl_deprecated.cntk
How to load, the number of training a good pinch, use c++ to write a DLL interface identification

请问cntk\MNIST的识别调用dll接口在那?
C:\cntk\Examples\Image\MNIST\Config\02_Convolution_ndl_deprecated.cntk
如何加载,训练好的数捏，用c++写个识别dll接口

**Comment by zhouwangzw** [comment]
@nyav Sorry, I do not completly understand your question. Are you asking how to use C++ to call CNTK Eval to evaluate a pre-trained model? The wiki page [here ](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview) provides an overview how to evaluate a CNTK model, and the [C++ Evaluation interface page](https://github.com/Microsoft/CNTK/wiki/Native-Evaluation-Interface) describes the C++ interface in details. You can also find code examples [here](https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation).
