### ISSUE TITLE
where is the cublas_64_70.dll?

### ISSUE THREAD

**Issue by haixinguan** [Microsoft/CNTK#83]
I use the CNTK, with only CPU PC, but can not work, it needs cublas_64_70.dll, and also curand64_70.dll, etc, is there some other lib should be installed?

**Comment by Ark-kun** [comment]
I think you need to install the CUDA 7.0 (even though your PC does not support it).
Alternatively you can build the CPU-only version of CNTK.

**Comment by PatrickBue** [comment]
Hi, I had the same problem. Even when using CPU only, I had to install Cuda 7.0 + VS2013.

**Comment by frankseide** [comment]
Hi, thanks for letting us know! We are tracking this as Issue #76, so I will close this one.
