### ISSUE TITLE
Using speech feature vectors as input for the CPP EvalDll client example

### ISSUE THREAD

**Issue by rashee182** [Microsoft/CNTK#830]
I am trying to evaluate a pre trained acoustic model using the Eval Dll API. The MNIST example provides an array of random numbers as input to the model. Is there an example which shows how the feature vectors (e.g from the AN4 example) can be provided as an input to the trained model for evaluation

**Comment by zhouwangzw** [comment]
There is no exsting example about AN4 usage in Eval. We are very appreciated if you could help to create such an example and submit it per pull request. 

Thanks,
Zhou

**Comment by rashee182** [comment]
I am not familiar with how inputs are transformed during training by HTKMLFReader.
I am looking for something on the lines of "EvaluateImageClassificationModel" example i.e evaluating a model trained using HTKMLFReader.

**Comment by rashee182** [comment]
@wolfma61 - I was going through the Azure example you posted for evaluation recently.
Can you please help illustrate the usage of Eval API for evaluating an acoustic model eg trained using AN4 dataset

**Comment by zhouwangzw** [comment]
Closing it. Please open a new one, if you still have the problem.
