### ISSUE TITLE
Building model without providing any action(data)

### ISSUE THREAD

**Issue by snurkabill** [Microsoft/CNTK#831]
Hello, 

is it possible to create CNTK model (so, some binary file) without providing any action(data)? I just need to create model based on settings I provide in cntkConfig. So far I needed some dataReader to have complete "action" in cntkConfig.

My usecase is to create model and then use second config file to train it.

Thanks

**Comment by frankseide** [comment]
Can you try to set the number of epochs to 0?

(Or use any epoch number and kill the process after it has written a .0 model file, which is the model right after creation with random initialization.)

**Comment by snurkabill** [comment]
I can, but what if I don't have yet prepared data, and I need to create model? (I only know data dimension and target dimension)

**Comment by frankseide** [comment]
I implemented the following, does that solve your problem? It creates the model but just writes it out to `outputModelPath`. (This same action really meant for constructing new models by cloning and modifying old ones, hence it is an `edit` action.)

It is still in a branch, and will land in a few days in the master source code:

```
command = speechCreate:speechTrain
...
speechCreate = {
    action = "edit"

    outputModelPath = "$modelPath$.initial"

    # define network using BrainScript
    BrainScriptNetworkBuilder = {
        ...
    }
}

speechTrain = {
    action = "train"

    # load previously created model from file as the starting model for this training
    BrainScriptNetworkBuilder = (BS.Network.Load("$modelPath$.initial"))
    ...
}
```

**Comment by snurkabill** [comment]
awesome! It looks like nicely done separtion of creation phase and training phase. 

Now I can generate configFile with only edit part and then regenerate it for training. Thank you for your time.
