### ISSUE TITLE
Possible GRU Implementation Mismatch

### ISSUE THREAD

**Issue by wormusmaximus** [Microsoft/CNTK#834]
The GRU function definition listed at this [page](https://github.com/Microsoft/CNTK/wiki/GRUs-on-CNTK-with-BrainScript) does not match the implementation inside [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs). Is this just a simplified version for easier understanding or has the [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) not been updated.

**Comment by wdarling** [comment]
Hi,

Yes the code listed on the page you link to is a simplified version for easier understanding of the GRU. In particular, the implementation in CNTK.core.bs has the full function signature to allow stabilization, projection of the cell dimension to a different output dim, etc., and it supports an auxiliary input to allow support for attention models.

William
