### ISSUE TITLE
Multiply-GPUs training stopped unexpectedly when training AM with train_cntk2.sh in AMI example

### ISSUE THREAD

**Issue by housebaby** [Microsoft/CNTK#835]
@frankseide @dongyu888 
I am training acoustic model on my dataset (over 2000h) with 2 GPUs with train_cntk2.sh from AMI example
$mpibin -n 2 $cn_gpu configFile=${expdir}/Base.config configFile=${expdir}/CNTK2.cntk action=TrainDNN ndlfile=$ndlfile

The training process stopped unexpectedly with no information about how the error occurs.
Is it due to memory  problem?
/////////////////////////////////////////////////////////////////////
MPIWrapper: initializing MPI
MPIWrapper: initializing MPI
ping [requestnodes (before change)]: 2 nodes pinging each other
ping [requestnodes (before change)]: 2 nodes pinging each other
ping [requestnodes (before change)]: all 2 nodes responded
requestnodes [MPIWrapper]: using 2 out of 2 MPI nodes (2 requested); we (0) are in (participating)
ping [requestnodes (after change)]: 2 nodes pinging each other
ping [requestnodes (before change)]: all 2 nodes responded
requestnodes [MPIWrapper]: using 2 out of 2 MPI nodes (2 requested); we (1) are in (participating)
ping [requestnodes (after change)]: 2 nodes pinging each other
ping [requestnodes (after change)]: all 2 nodes responded
mpihelper: we are cog 0 in a gearbox of 2
ping [mpihelper]: 2 nodes pinging each other
ping [mpihelper]: all 2 nodes responded
ping [requestnodes (after change)]: all 2 nodes responded
mpihelper: we are cog 1 in a gearbox of 2
ping [mpihelper]: 2 nodes pinging each other
ping [mpihelper]: all 2 nodes responded
Redirecting stderr to file exp_cntk//log/train_cntk_TrainDNN.logrank0

Redirecting stderr to file exp_cntk//log/train_cntk_TrainDNN.logrank1

WARNING: A process refused to die despite all the efforts!
This process may still be running and/or consuming resources.

Host: 10
PID: 17541

**mpiexec noticed that process rank 0 with PID 17540 on node 10 exited on signal 9 (Killed).**

./train_cntk2.sh successfuly finished..
/////////////////////////////////////////////////////////////////////
The log file "exp_cntk//log/train_cntk_TrainDNN.logrank0" ends  with following information:

"requiredata: 850 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 7234 (frame range [653154321..653244662]), 7235 resident in RAM
requiredata: 239 utterances read
feature set 0: requirerandomizedchunk: paging in randomized chunk 7235 (frame range [653244663..653335468]), 7236 resident in RAM"

**Comment by JJMEI** [comment]
hello ,do you find the file CNTK2.cntk？

**Comment by cha-zhang** [comment]
Close since it's too old. Feel free to reopen a new issue if needed.
