### ISSUE TITLE
Prefetch for HTKMLFReader

### ISSUE THREAD

**Issue by abbasov** [Microsoft/CNTK#836]
Hi,

Can I use --prefetch option for the "HTKMLFReader" (readMethod = "blockRandomize") same as in UCI Fast Reader? If not, could you add this opportunity to CNTK next release.

Thanks

**Comment by mahilleb-msft** [comment]
Hi @abbasov,
HTKMLFReader is superseded by a new reader, HTKDeserializers, which supports chunk and minibatch prefetching. 
Could you take a look at https://github.com/Microsoft/CNTK/wiki/Understanding-and-Extending-Readers and see if would be possible for you to switch?

Best, Mark

**Comment by n17s** [comment]
Closing.
