### ISSUE TITLE
Regression on images

### ISSUE THREAD

**Issue by akarsakov** [Microsoft/CNTK#837]
Hello,

I would like to train the model for prediction region of interest on image. I solved this task using keras+theano and I have dataset for it. Now I am trying to port network architecture and retrain model using CNTK.
I read [this](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluate-Image-Transforms) tutorial and prepared similar configuration file. 
My task is prediction 4 coordinates (normalized by weight or height). As I can see rmse is not decreasing while training and model predicts always zeros. But if I use quite simple architecture (it commented in configuration file) it works well. 
Most probably I have mistake in configuration file, but I can't figure out where it is. Could you please help me with this issue?
[config.zip](https://github.com/Microsoft/CNTK/files/469473/config.zip)
[log.txt](https://github.com/Microsoft/CNTK/files/469474/log.txt)

**Comment by mfuntowicz** [comment]
Hi @akarsakov, 

I looked at your config file (.cntk) and your last layer uses a ReLU Activation, which is not necessary the best for a final layer. Can you try to change the final layer to a linear one ?

`ol = DenseLayer {labelDim, activation=ReLU, init="gaussian", initValueScale=1.697} (d1)
ol = LinearLayer {labelDim, init="gaussian", initValueScale=1.697} (d1)
`

You can also change the initialization method to a heNormal (init='heNormal') which might reduce the gradient vanish.

Finally, I would recommand you to change your learningRatePerMB to learningRatesPerSample (let's try 0.0005) and momentumPerMB to momentumAsTimeConstant (let's put 1024 here).

Let us know if you can see any improvements
Morgan

**Comment by akarsakov** [comment]
@mfuntowicz Thank you for your help! 
It works. I tuned some parameters and got pretty good results. I'm so sorry for late response. Issue should be closed.
