### ISSUE TITLE
Possible bug with negative slice indices in the Matrix<ElemType>::ShiftBy method.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#84]
Possible bug with negative slice indices in the Matrix<ElemType>::ShiftBy method.
https://github.com/Microsoft/CNTK/blob/master/Source/Math/Matrix.cpp#L622

Either I don't understand the slicing semantics or something strange is going on here.
* `numShift` is positive.
* At the end of the first loop `i == -numShift` wjich is a negative number
* `Matrix<ElemType> out = ColumnSlice(i, 1);` creates a slice at negative index.

Additionally,
* The loop `for (size_t i = 0; i < min(GetNumCols(), -numShift); i++)` never executes since `min(GetNumCols(), -numShift)` == `-numShift` < 0

**Comment by frankseide** [comment]
It seems that this function is not used. I suggest to remove it.

**Comment by wolfma61** [comment]
removed the function in matrix classes
this has been pushed into master
