### ISSUE TITLE
UWP App using CNTK EvalDLL and Native C++ Image Pre-processing APIs

### ISSUE THREAD

**Issue by jhalakpatel** [Microsoft/CNTK#841]
Hi,

I am writing a UWP App which can use native C++ EvalDLL to perform Image Classification.

I have already successfully written a C++ Console application to perform Image Classification using ResNet_34 model (here is the issue i opened while working on that #805) which uses C# .Net Framework based Image Preprocessing APIs mentioned in #160 

Current Status with UWP App:
With the UWP App, I am able to successfully build and run [https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CPPEvalClient](MNIST CppEvalClient Example)

**Issue:**
- I am looking forward get some native C++ Image Pre-Processing APIs which can be used in a UWP App, as UWP wont let me use .NET Framework based APIs such as System.Drawing.dll which are used in given example [https://github.com/Microsoft/CNTK/tree/master/Examples/Evaluation/CSEvalClient](ImageClassificationModel Function).
-  I also want to confirm whether EvalDll.dll work fine with UWP apps. Also can you confirm whether the [https://www.nuget.org/packages/Microsoft.Research.CNTK.CpuEval-mkl](CNTK MKL Nuget 1.7) works with UWP apps.

Thanks in Advance.

**Comment by zhouwangzw** [comment]
@jhalakpatel Unfortunatelly we have not tried run EvalDll with UWP apps yet. This is one of features we want to support, but not get it done yet. If you want have a try, we are very appreciated and please let us know if you have any questions. I think the key point is to enable UWP apps to load all CNTK native dependency dlls.

Regarding the image preprocessing APIs, are you able to use OpenCV? CNTK ImageReader (also in C++) is using OpenCV for image preprocessing. See [here](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#optional-opencv) for details.

Thanks,
Zhou

**Comment by jhalakpatel** [comment]
Ok Thanks. Currently I have converted .NET framework dependencies to corresponding .NET CORE functionality for UWP apps in my previous soultion. The modified Image PreProcessing logic in C# (using Windows.Storage and Windows.Graphics.Imaging) works for me. But eventually i will be rewriting the preprocessing logic using OpenCV in native c++ environment.

**Comment by zhouwangzw** [comment]
I am closing it and feel free to re-open it if needed.
Thanks for using CNTK.

Zhou
