### ISSUE TITLE
Load pre-trained word embedding vectors into CNTK

### ISSUE THREAD

**Issue by hongjiedai** [Microsoft/CNTK#842]
Hi

Is there any tutorial about loading pre-trained word embedding model, such as Glove or word2vec, into CNTK?

**Comment by junjieqian** [comment]
You may refer to the example presented in this [link](https://github.com/Microsoft/CNTK/blob/3b7dcc1ac84debf2128d97064a7e3c41b7437de1/bindings/python/doc/examples.rst), or this [link](https://github.com/Microsoft/CNTK/blob/3b7dcc1ac84debf2128d97064a7e3c41b7437de1/bindings/python/doc/gettingstarted.rst).

**Comment by hongjiedai** [comment]
Thank you for the link.
I read it and found that it requires to write Python code.

Is it possible to set the load of embedding info in the configuration file without programming?

**Comment by benfre** [comment]
I read from here [EmbeddingLayer](https://github.com/Microsoft/CNTK/wiki/Layers-Reference#embeddinglayer), it has parameter 'embeddingPath' to a file. But I didn't find any information about the format of this file.

**Comment by wdarling** [comment]
The format is a plain-text file with numbers in the shape of your embedding matrix. So, if your embedding expects a 4x5 matrix, your file should look like:

1 2 3 4 5
6 7 8 9 10
11 12 13 14 15
16 17 18 19 20

William

**Comment by hongjiedai** [comment]
I got it. It seems work.

Thank you for the [link](https://github.com/Microsoft/CNTK/wiki/Layers-Reference#embeddinglayer). 

As mentioned by Willliam, the file format follows the shape of the embedding matrix.
The example file shown in https://github.com/Microsoft/CNTK/blob/3b7dcc1ac84debf2128d97064a7e3c41b7437de1/bindings/python/doc/examples.rst demonstrates the file format.
