### ISSUE TITLE
SequenceToSequence example not working with 1.7 release

### ISSUE THREAD

**Issue by virueh** [Microsoft/CNTK#845]
When I try to run the SequenceToSequence\CMUDict example with the newest 1.7 release (windows, CPU only), I get the following exception at the end of the log file:

`EXCEPTION occurred: NotifyFunctionValuesMBSizeModified: rawLabels InputValue operation had its col dimension 143 changed by the reader to 1, but different from MBLayout.`

With the 1.6 release it seems to be working fine.

**Comment by rafael-aero** [comment]
Same problem here!

**Comment by wdarling** [comment]
To fix this change the line in the readers "rawInput = $lmSequenceReaderInputDef$" to "rawLabels = $lmSequenceReaderInputDef$". That being said, the newest release standardizes on the CNTKTextFormatReader which is much faster than the older LMSequenceReader. You should update to that version.

**Comment by rafael-aero** [comment]
Thanks! I'll give it a try then... Is this planned to be fixed in future releases?

**Comment by cha-zhang** [comment]
Has this been resolved. It's been a long time and I'm closing this issue. Feel free to open a new one if you have other issues.
