### ISSUE TITLE
ParameterTensor{} Wiki

### ISSUE THREAD

**Issue by Martlgap** [Microsoft/CNTK#846]
Hey, 

In the wiki FullFunctionReference->ParameterTensor{} Page there is a optional Parameter called: 
"initValue" mentioned. 
I got errors when I use: 
ParameterTensor(outMap ,init='uniform', initValue=0.05, learningRateMultiplier=1.0)

After checking the source code it should be: 
ParameterTensor(outMap ,init='uniform', value=0.05, learningRateMultiplier=1.0)

So the parameter-name "initValue" should be replaced by "value" right? 

Thanks
Martin

**Comment by frankseide** [comment]
We streamlined it, it was a bit redundant before. Is your binary the latest? This should work starting from 1.7. Older versions require you to use two variables:

    init='fixedValue', value = ...

**Comment by Martlgap** [comment]
Thanks for your reply. I don´t use the latest binary. So that might be the problem. But I need my binary version, due to some personal changes. 

Thanks! :)
