### ISSUE TITLE
Some post build event fails (I have the fix but cannot push into repo)

### ISSUE THREAD

**Issue by kikish** [Microsoft/CNTK#85]
Hi,

When compiling the CNTK, some post-build events fail because some macros relating to paths are not in quotes.

Math and MathCUDA must use the OutputPath macro in quotes.

ComputationNetworkLib, SGDLib, CNTK, EvalDll and ActionsLib must use the TargetPath macro in quotes.

ImageReader must use quotes for both source and destination directories parameters of the xcopy command.

Regards.

Arezki.

These modifications works for me but I don't have the rights to push to this repo.

Regards,

Arezki.

**Comment by kikish** [comment]
Hi,

Same problem with the Math Project;

Regards.

Arezki

**Comment by frankseide** [comment]
Would you mind submitting a pull request? Thanks!!

**Comment by frankseide** [comment]
Or commit to a fork and point me to it? I'd love to merge these.

**Comment by wolfma61** [comment]
closed - since it is marked as merged
