### ISSUE TITLE
Debug Version of Sept 1,2016 CNTK executable throws exception in creation of reader object

### ISSUE THREAD

**Issue by Dharmakayaman** [Microsoft/CNTK#850]
I created a debug version of the CNTK executable with the intent of studying the flow of the code for the simplest example, Simple2d, with the simplest configuration file, Simple.cntk....my command line data for the debugger is as follows:
configFile=C:/src/cntk/Examples/Other/Simple2d/Config/Simple.cntk 1>out2.txt 2>&1
What I am finding is that an execption gets thrown in TrainActions.cpp, at the point of the following call:
 auto dataReader = CreateObject<DataReader>(config, L"reader");
I would be grateful if there is anyone that can tell me that i have made an obvious error, or that this indicates a bug in the debug version of the code?

**Comment by zhouwangzw** [comment]
@Dharmakayaman On Linux or Windows? On Windows, you need to have reader dlls in the same directory as the cntk.exe. On Linux, you should have reader .so files in the lib directory which is parallel to the bin directory that has the cntk executable. The Simple.cntk needs CNTKTextFormatReader.dll or CNTKTextFormatReader.so.

**Comment by Dharmakayaman** [comment]
Dear Zhou Wang, My code is on windows and the reader dlls are all in the same directory as cntk.exe...My release version works fine...no problems..I am wondering if there is something about the debug version that is inconsistent with the assumptions in inherent in the Simple.cntk file? In the case of the relase version I ran it from the command line..in the case of the Debug version, I run it from the Visual Studio 2013 interface, with command line arguments set as in my earlier message...From the debugger I can see that at least some of the inpur quantities from the Simple.cntk file are being ingested properly...for example the number of samples in a mini-batch is consistent with what i see in the debugger...

**Comment by Dharmakayaman** [comment]
Dear Zhou Wang and others,
I have resolved my problem...this required creating a file SimpleDebug.cntk that has the following assignment at the top:
RootDir = "C:/src/cntk/Examples/Other/Simple2d"....this solved the problem...when the release app was used from the commandline...the locations of various files was computed correctly....I apologize for this oversight, but it shows that all the files and associated comments must be understood and examined carefullly so that they can be modified when necessary
