### ISSUE TITLE
build failure on tip

### ISSUE THREAD

**Issue by championoaks** [Microsoft/CNTK#853]
Trying to build with MKL a CPU only version of tip, observe these failures. 

'AllReduceDistGradAggregator.h': No such file or directory
The command "xcopy /D /I /Y ".....*.dll" ".....":VCEnd" exited with code 9009.	
 LNK1181: cannot open input file 'SGDLib.lib'	

 1.6 version was a breeze, but with latest build i see these failures

**Comment by junjieqian** [comment]
Please refer to Issue 460, https://github.com/Microsoft/CNTK/issues/460
