### ISSUE TITLE
what is the deeply or really  meaning of "  readMethod=blockRandomize "

### ISSUE THREAD

**Issue by Jaquier** [Microsoft/CNTK#855]
From the book of   "An Introduction to Computational Networks and the Computational Network Toolkit",
blockRandomize divides the data into large blocks and then randomizes the order of the blocks and the order of the data within the block.

But I run AutoEncoder model two times, all are the same except time. I doubt the functions of blockRandomize.

why the  MeanSqErr.MSE are all the same? 

Time  1: 
 Epoch[ 1 of 25]-Minibatch[   1-  10]: MeanSqErr.MSE = 851.39990234 \* 2560; time = 0.2134s; samplesPerSecond = 11994.5
 Epoch[ 1 of 25]-Minibatch[  11-  20]: MeanSqErr.MSE = 804.69541016 \* 2560; time = 0.2097s; samplesPerSecond = 12206.9
 Epoch[ 1 of 25]-Minibatch[  21-  30]: MeanSqErr.MSE = 785.02363281 \* 2560; time = 0.2091s; samplesPerSecond = 12243.1
 Epoch[ 1 of 25]-Minibatch[  31-  40]: MeanSqErr.MSE = 788.50761719 \* 2560; time = 0.2113s; samplesPerSecond = 12117.5
......................
Time 2:
 Epoch[ 1 of 25]-Minibatch[   1-  10]: MeanSqErr.MSE = 851.39990234 \* 2560; time = 0.1112s; samplesPerSecond = 23026.8
 Epoch[ 1 of 25]-Minibatch[  11-  20]: MeanSqErr.MSE = 804.69541016 \* 2560; time = 0.1095s; samplesPerSecond = 23385.8
 Epoch[ 1 of 25]-Minibatch[  21-  30]: MeanSqErr.MSE = 785.02363281 \* 2560; time = 0.1097s; samplesPerSecond = 23345.9
 Epoch[ 1 of 25]-Minibatch[  31-  40]: MeanSqErr.MSE = 788.50761719 \* 2560; time = 0.1096s; samplesPerSecond = 23367.3
...........................................

So I want to know the reason, did blcokRandomize work ?

**Comment by cha-zhang** [comment]
Likely your learning rate is not set correctly. 

This is very old and I'm closing it. If you still have issue with a similar problem, please feel free to open a new issue.
