### ISSUE TITLE
example to edit a model using brainscript

### ISSUE THREAD

**Issue by jian16** [Microsoft/CNTK#856]
Is there an example to edit a model using brainscript?

Thanks,
Jian Jiao

**Comment by junjieqian** [comment]
There is a [wiki page](https://github.com/Microsoft/CNTK/wiki/BS-Model-Editing) explaining BS.Network.Edit() to edit network. The usage example is [here](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs).

**Comment by jian16** [comment]
Got it. thanks.
