### ISSUE TITLE
Plugin not found error

### ISSUE THREAD

**Issue by championoaks** [Microsoft/CNTK#859]
I am running Alexnet using self built binaries(CPU only) and it consistently fails with the error "Plugin not found ImageReader.dll" 

I checked and LoadLibrary is returning a null pointer @ Plugin class Load method
        m_dllName += L".dll";
        m_hModule = LoadLibrary(m_dllName.c_str());

The Imagereader DLL gets built and copied to the same folder as CNTK binary and is present. I have tried both Release and debug builds. The CNTK Binary folder is in the path. I never ran into this failure and is puzzling me out. I even added the DLL as a reference to CNTK project hoping it would somehow help. Even copied DLL to system32 folder, still same failure.

**Comment by yuxiaoguo** [comment]
In my experience, it's beacuse of zlib.dll or zlib1.dll. You can try rename zlib.dll to zlib1.dll or reverse. Then, you problem may solve.

**Comment by championoaks** [comment]
I checked using dependency walker and seems my ImageReader binary is linking to zlib.dll instead. Renaming it solves the issue.

**Comment by huishaoli** [comment]
Could you tell me where or how to get the imageReader.dll?

**Comment by yuxiaoguo** [comment]
@huishaoli If you built CNTK from source, it should be generated after Source/Reader/ImageReader complied.
