### ISSUE TITLE
Network description using C++

### ISSUE THREAD

**Issue by svml** [Microsoft/CNTK#860]
Hello,

According to Frank Seide's presentation at the Microsoft Faculty Summit 2016, network descriptions in CNTK can _"soon"_ been done using C++. Could you please let me know if it is already possible?

While, BrainScript is great, I am not sure how to use it to create a customized version of a neural network. For example, I am interested in applying some operation on the matrix of parameters if I see a specific kind of input given to the network during training. Could you please let me know if it is possible to implement using BrainScript (and what matrix operations are supported)?

I.e. `if( Condition(featureVector) ) { ApplyOperation(WMatrix); }`

Thank you very much for your help!

**Comment by svml** [comment]
Nobody knows if CNTK networks can be described in C++? :(

**Comment by frankseide** [comment]
Sorry for the late response. CNTK will gain a library API with version 2. The beta for the V2 API is scheduled for October. It will allow you to create custom operations, where you provide a custom forward and backward function. You can also break your network into pieces, and execute them separately, while manually connecting them. That is another way of cutting in custom code.

To give you a first glimpse on what the C++ (and Python) API it will look like, you can have a look at the CNTKv2LibraryDll project and V2LibraryTests. Expect, however, breaking changes until the beta.

**Comment by svml** [comment]
Thank you very much, Frank, for the information :) That sounds promising - I will certainly have a look CNTKv2LibraryDll and V2LibraryTests.

**Comment by n17s** [comment]
Beta has been released. Closing. Feel free to reopen.
