### ISSUE TITLE
GPU memory error for brainscript conversion

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#861]
I converted ndl file into brainscript but I got memory error for it. The exactly same input/output/network size are used both for ndl/bs. The following is the error message I got. 

Really, I'm not sure the issue because I monitored GPU memory while it is running but I don't see any memory overflow( total 12G MEM but used mem size was always below 6G from nvidia-smi) . Is there any idea for this? Or is there any way to avoid this (except decreasing numUttsPerMinibatch )?

> [CALL STACK]
> [0x7f7a9f5bab77]                                                       + 0x5a4b77
> [0x7f7a9f5e5604]    float\* Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::  Allocate  <float>(int,  unsigned long,  unsigned long) + 0x44
> [0x7f7a9f5e5964]    Microsoft::MSR::CNTK::GPUMatrix<float>::  Resize  (unsigned long,  unsigned long,  bool) + 0xc4
> [0x7f7a9f559045]    Microsoft::MSR::CNTK::Matrix<float>::  Resize  (unsigned long,  unsigned long,  unsigned long,  bool) + 0xd5
> [0x5f5829]          Microsoft::MSR::CNTK::ComputationNode<float>::  BeginForwardProp  () + 0x409
> [0x81ad8d]          Microsoft::MSR::CNTK::ComputationNetwork::SEQTraversalFlowControlNode::  BeginForwardProp  () + 0x6d
> [0x81c236]          Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::  ForwardProp  (Microsoft::MSR::CNTK::FrameRange const&) + 0x56
> [0x81e07c]          Microsoft::MSR::CNTK::ComputationNetwork::  ForwardProp  (std::shared_ptrMicrosoft::MSR::CNTK::ComputationNodeBase) + 0x7c
> [0x784020]          void Microsoft::MSR::CNTK::ComputationNetwork::  ForwardProp  std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase,std::allocatorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>>>(std::vectorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase,std::allocatorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>> const&) + 0x60
> [0x7afb72]          Microsoft::MSR::CNTK::SGD<float>::  TrainOneEpoch  (std::shared_ptrMicrosoft::MSR::CNTK::ComputationNetwork,  std::shared_ptrMicrosoft::MSR::CNTK::ComputationNetwork,  std::shared_ptrMicrosoft::MSR::CNTK::ComputationNodeBase const&,  int,  unsigned long,  Microsoft::MSR::CNTK::IDataReader_,  double,  unsigned long,  std::vectorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase,std::allocatorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>> const&,  std::vectorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase,std::allocatorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>> const&,  std::vectorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase,std::allocatorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>> const&,  std::vectorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase,std::allocatorstd::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>> const&,  Microsoft::MSR::CNTK::StreamMinibatchInputs_,  std::lis[0x7b5bcf]          Microsoft::MSR::CNTK::SGD<float>::  TrainOrAdaptModel  (int,  std::shared_ptrMicrosoft::MSR::CNTK::ComputationNetwork,  bool,  std::shared_ptrMicrosoft::MSR::CNTK::ComputationNetwork,  std::shared_ptrMicrosoft::MSR::CNTK::ComputationNodeBase,  Microsoft::MSR::CNTK::IDataReader_,  Microsoft::MSR::CNTK::IDataReader_) + 0x197f
> [0x7b7ff2]          Microsoft::MSR::CNTK::SGD<float>::  Train  (std::shared_ptrMicrosoft::MSR::CNTK::ComputationNetwork,  int,  Microsoft::MSR::CNTK::IDataReader_,  Microsoft::MSR::CNTK::IDataReader_,  int,  bool) + 0x152
> [0x64e6ab]          void  DoTrain  Microsoft::MSR::CNTK::ConfigParameters,float(Microsoft::MSR::CNTK::ConfigParameters const&) + 0x39b
> [0x5fb1e0]          void  DoCommands  <float>(Microsoft::MSR::CNTK::ConfigParameters const&,  std::shared_ptrMicrosoft::MSR::CNTK::MPIWrapper const&) + 0x9c0
> [0x5aedec]          wmainOldCNTKConfig  (int,  wchar_t**)              + 0x9ec
> [0x5b1197]          wmain1  (int,  wchar_t**)                          + 0x87
> [0x5a62d8]          main                                               + 0xd8
> [0x7f7a9df5dec5]    __libc_start_main                                  + 0xf5
> [0x5aa594]
> EXCEPTION occurred: CUDA failure 2: out of memory ; GPU=1 ; hostname=ubuntu ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) \* numElements)

**Comment by e-thereal** [comment]
Can you please provide the NDL and the BS script? Thank you.

**Comment by funguy74** [comment]
I tested ordinary 5layer lstm (for AMI corpus). I know there is lstm library but for later modification, I need to design my own. Anyway, the following BS script is what I tested and got the above memory error. For ndl, I didn't attach because I used reference lstm ndl. 


```
#define basic i/o
base_featdim=80
row_slicestart=800
feat_dim=880
label_dim=3902

cellDim=1024
hiddenDim=512


    # Macro definitions
    LogPrior(labels) = {
        Prior=Mean(labels)
        LogPrior=Log(Prior)
    }.LogPrior


    LSTMPComponent(inputDim, outputDim, cellDim, inputx) = {
        Wxo = ParameterTensor{(cellDim:inputDim), init='uniform', initValueScale=1}
        Wxi = ParameterTensor{(cellDim:inputDim), init='uniform', initValueScale=1}
        Wxf = ParameterTensor{(cellDim:inputDim), init='uniform', initValueScale=1}
        Wxc = ParameterTensor{(cellDim:inputDim), init='uniform', initValueScale=1}

        bo = ParameterTensor{cellDim, init='fixedValue', value=0.0}
        bc = ParameterTensor{cellDim, init='fixedValue', value=0.0}
        bi = ParameterTensor{cellDim, init='fixedValue', value=0.0}
        bf = ParameterTensor{cellDim, init='fixedValue', value=0.0}

        Whi = ParameterTensor{(cellDim:outputDim), init='uniform', initValueScale=1}
        Wci = ParameterTensor{cellDim, init='uniform', initValueScale=1}


        Whf = ParameterTensor{cellDim:outputDim, init='uniform', initValueScale=1}
        Who = ParameterTensor{cellDim:outputDim, init='uniform', initValueScale=1}
        Whc = ParameterTensor{cellDim:outputDim, init='uniform', initValueScale=1}
        Wcf = ParameterTensor{cellDim, init='uniform', initValueScale=1}
        Wco = ParameterTensor{cellDim, init='uniform', initValueScale=1}

        Wmr = ParameterTensor{outputDim:cellDim, init='uniform', initValueScale=1}

        dh = PastValue(outputDim, output, timeStep=1)
        dc = PastValue(cellDim, ct, timeStep=1)


        Wxix = Wxi*inputx
        Whidh = Whi*dh
        Wcidc = Wci.*dc

        it = Sigmoid ( Wxix + bi + Whidh + Wcidc)

        Wxcx = Wxc*inputx
        Whcdh = Whc*dh        
        bit = it.*Tanh(Wxcx + Whcdh + bc)
        
        Wxfx = Wxf * inputx
        Whfdh = Whf * dh
        Wcfdc = Wcf .* dc

        ft = Sigmoid(Wxfx + bf + Whfdh + Wcfdc)

        bft = ft .* dc
        ct = bft + bit

        Wxox  = Wxo * inputx
        Whodh = Who * dh
        Wcoct = Wco .* ct

        ot = Sigmoid( Wxox + bo + Whodh + Wcoct)
        mt = ot .* Tanh(ct)


        output = Wmr * mt

    }.output


    features=Input(feat_dim, tag='feature')
    labels=Input(label_dim, tag='label')
    feashift=RowSlice(row_slicestart, base_featdim, features)      # shift 5 frames right (x_{t+5} -> x_{t} )
    featNorm = FeatureMVNLayer{}(feashift)


    layers[l:1..5] =
        if l == 1
        then LSTMPComponent(base_featdim, hiddenDim, cellDim, featNorm)
        else LSTMPComponent(hiddenDim, hiddenDim, cellDim, layers[l-1])

    W = Parameter(label_dim, hiddenDim, init='uniform', initValueScale=1)
    b = Parameter(label_dim,1, init='fixedValue', value=0)
    LSTMoutputW = Plus(Times(W, layers[5]), b)


    cr = CrossEntropyWithSoftmax(labels, LSTMoutputW,tag='criterion')
    Err = ErrorPrediction(labels,LSTMoutputW,tag='evaluation')

    logPrior = LogPrior(labels)
    ScaledLogLikelihood=Minus(LSTMoutputW,logPrior,tag='output')


```

**Comment by cha-zhang** [comment]
Close because it is very old. If the latest 2.0 release still has issue, please open a new issue.
