### ISSUE TITLE
Proper way to specify a scalar constant

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#863]
Hello, here's the question — how to specify a scalar constant in BS?

We've been using `ConstantTensor(1, (1))` which gives a `[1]` node, but in [current docs](https://github.com/Microsoft/CNTK/wiki/Full-Function-Reference) it's said to be deprecated.

We tried to use `Constant(1)`, but it makes `[1 x 1]` node. This seem to go from the definition in [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) which explicitly defines shape to be a 2-tensor:

```
Constant(val, rows = 1, cols = 1, tag='') = Parameter(rows, cols, learningRateMultiplier = 0, initValue = val)
Parameter {outputDim, inputDim, ... } = new ComputationNode [ operation = 'LearnableParameter' ; initFilterRank = 0 ; initOutputRank = 1 ; shape = new TensorShape [ dims = (outputDim : inputDim) ] /*plus the function args*/ ]
```

First of all, we'd like to know is there any difference between `[1]` and `[1 x 1]` nodes. 
And second — how to specify a constant of `[1]` dimensions?

**Comment by n17s** [comment]
I believe the way to do this now is to be on the latest master and specify it as in all other programming languages : 1 
See for example the definition of hamming loss [in this wiki page](https://github.com/Microsoft/CNTK/wiki/Train-a-multilabel-classifier)

The difference between a [1] and a [1x1] is unfortunate and exists in other framewords such as numpy.

**Comment by mikhail-barg** [comment]
@n17s  Thanks for the answer, but unfortunately, if I specify 
`value = 1 - ssRes .* ssTotRec` 
instead of 
`value = ConstantTensor(1, (1)) - ssRes .* ssTotRec` 
I get the following error:

```
                value = 1 - ssRes .* ssTotRec
            ^ 0
EXCEPTION occurred while evaluating: BrainScriptNetworkBuilder(14): config member has wrong type (N9Microsoft3MSR17ScriptableObjects5BoxOfINS1_7WrappedIdEEEE), expected a N9Microsoft3MSR4CNTK19ComputationNodeBaseE
```

**Comment by frankseide** [comment]
@n17s is right--using a scalar constant directly is now supported in the latest master branch. We plan to cut an update to the binary tomorrow (1.7.1) which will have this. Until then, please continue to use `ConstantTensor(val, (1))`, which will continue to do the right thing. `ConstantTensor()` is actually a BrainScript wrapper around LearnableParameter.

**Comment by mikhail-barg** [comment]
Thanks for the answer! For now v1.7.1 is still unavailable and current master fails to build (see #869), so I am still unable to check if it works.

**Comment by mikhail-barg** [comment]
Sorry for not checking this for too long. All OK, thanks!
