### ISSUE TITLE
Use models CNTK_MODEL_VERSION_2 with  CNTK 1.7

### ISSUE THREAD

**Issue by ivan-alles** [Microsoft/CNTK#865]
I have a lot of convnets similar to MNIST example, all created with CNTK from february 2016 (CNTK_MODEL_VERSION_2).

I would like to use them with the new CNTK (v.1.7) on CPU. I can load and run the models, but they produce wrong predictions. I found that the problem is in the MaxPooling layer, LegacyConvolutionEngine::ForwardPoolingCore(). If I replace 

```
            out.AssignMaxPoolingResult(in, m_inT.c(), m_inT.w(), m_inT.h(), m_inT.w() * m_inT.h() * m_inT.c(),
                                       m_outT.w(), m_outT.h(), m_outT.w() * m_outT.h() * m_outT.c(),
                                       m_kernelT.w(), m_kernelT.h(), m_strideT.w(), m_strideT.h());
```

with 
```
            out.AssignMaxPoolingResult(in, m_inT.w(), m_inT.h(), m_inT.c(), m_inT.w() * m_inT.h() * m_inT.c(),
                m_outT.h(), m_outT.c(), m_outT.w() * m_outT.h() * m_outT.c(),
                m_kernelT.h(), m_kernelT.c(), m_strideT.h(), m_strideT.c());
```

the model works correctly.

Essentially, I need to remap dimensions: h -> c, w -> h, c -> w.

Is it a bug in CNTK? If yes, is my change a correct fix for it? 
If it is not a bug, how else can I convert my models (more than 20) into a new format, so that they will work with the unpatched CNTK?

**Comment by frankseide** [comment]
It is a bug fix in CNTK... For a while, CNTK used two different memory layouts for images, one to support NVidia cuDNN, and one to support an older existing CNTK implementation. This was eventually stratified by explicitly including a layout parameter. The V2 file format probably does not have this.

There is unfortunately not a good answer. We do have a conversion for some other (similar) issue. If you look at ModelEditLanguage.h, you see an example where a specific conversion operation is hard-coded based on type. You may be able to do something like this, but I am not sure.

```
    else if (EqualInsensitive(name, "LoadModelWithName"))
    {
        size_t numFixedParams = 2, numOptionalParams = 1;
        if (params.size() > numFixedParams + numOptionalParams || params.size() < numFixedParams)
            RuntimeError("Invalid number of parameters. Valid parameters: LoadModelWithName(modelName, modelFileName, [format=cntk]). newly loaded model always becomes the new default.");

        std::wstring modelFormat = GetOptionalModelFormat(params, numFixedParams);

        auto cn = make_shared<ComputationNetwork>(CPUDEVICE);
#if 1 // support for a specific kind of legacy format, for the sole purpose of allowing users to convert (=load & save) them
        if (modelFormat == L"cntk_legacy_no_tensorlib")
        {
            cn->Read<ElemType>(params[1]);
            for (auto node : cn->FeatureNodes())
                node->SetDims(TensorShape(node->GetSampleMatrixNumRows()), node->HasMBLayout()); // pre-tensorlib InputValues had incorrect tensor dimensions
            cn->CompileNetwork();
        }
        else
#endif
```

**Comment by ivan-alles** [comment]
Thank you for your reply. I already managed to convert the models to v14. But obviously they are still written with the legacy (HWC) layout, so I still need my patch. 

This is ok for me, provided that this patch does not influence new models in cudnn format that I'm going to create and use in future. The patch is in LegacyConvolutionEngine, so I assume the cudnn-format models will not use this code. It that correct?

**Comment by frankseide** [comment]
There are still some use cases (sparse convolution currently requires HWC), but it does not seem to conflict with your use case.
