### ISSUE TITLE
RNN One to Many Example ( Image Captioning etc. )

### ISSUE THREAD

**Issue by kestrelm** [Microsoft/CNTK#867]
Hello,

Is there a simple example on how to setup a One to Many RNN case for uses in say an Image Captioning application? How should one go about doing it using your CNTK API?

Thanks!

**Comment by sumitsony** [comment]
any luck man @kestrelm I too need some help.

**Comment by cha-zhang** [comment]
Please check our CNTK tutorial for an example for image captioning. 
https://www.cntk.ai/Tutorials/CVPR2017/CVPR_2017_Tutorial_final.pdf 
https://www.youtube.com/watch?v=lBof7SfWGzU
