### ISSUE TITLE
How to normalize a matrix

### ISSUE THREAD

**Issue by luyamalu** [Microsoft/CNTK#870]
hi,I want to normalize a matrix which is got from the output of the deep network through BFF.And I want to use the following formula to process it.
C'=(C-Min)/(Max-Min)
Can you tell me how to do it?
Thank you a million!

**Comment by frankseide** [comment]
Could you try this:

    Cmax = ReduceMax (C)
    Cmin = ReduceMin (C)
    Cnormalized = (C - Cmin) .* Reciprocal (Cmax - Cmin)

**Comment by luyamalu** [comment]
OK,thank you very much!
