### ISSUE TITLE
Regression model with ImageReader

### ISSUE THREAD

**Issue by 256zib** [Microsoft/CNTK#871]
Hi!

How can i get regression result with the type ImageReader?
I whant to finde points on the face. I can use text file with byts, how to show in https://github.com/Microsoft/CNTK/issues/422, but it is not conveniently.
Can i use train_map.txt with format for example: D:\DataSet\image.jpg 1.0, 200.5?
where 1.0, 200.5 is a point x,y
I tried various options, but I did not succeed :(

**Comment by pkranen** [comment]
Please see here for an example: [https://github.com/Microsoft/CNTK/wiki/Train-a-regression-model-on-images](https://github.com/Microsoft/CNTK/wiki/Train-a-regression-model-on-images)
