### ISSUE TITLE
compile problem on RedHat: aligned_alloc

### ISSUE THREAD

**Issue by bottle-watch** [Microsoft/CNTK#875]
Hello, I know someone has asked similar problem before in the following link:
https://github.com/Microsoft/CNTK/issues/729

I updated my glibc to 2.18 and check the header file that it indeed has the function aligned_alloc(). I also check my c++ version. 
However, it is still reporting the error that:

Source/Math/BlockMultiplierMatrixUtil.h:84:85: error: there are no arguments to'aligned_alloc' that depend on a template parameter, so a declaration of 'aligned_alloc' must be available [-Werror=permissive]

Any idea to start from? Thanks!

**Comment by junjieqian** [comment]
glibc 2.19 works fine on my Ubuntu machine.

**Comment by bottle-watch** [comment]
Could you please paste the header file for the part of aligned_alloc from glibc 2.19? thanks!

**Comment by junjieqian** [comment]
The part from stdlib.h is,
`#ifdef __USE_ISOC11
/* ISO C variant of aligned allocation.  */
extern void *aligned_alloc (size_t __alignment, size_t __size)
     __THROW __attribute_malloc__ __attribute_alloc_size__ ((2)) __wur;
#endif`

**Comment by bottle-watch** [comment]
#ifdef __USE_ISOC11
/* ISO C variant of aligned allocation.  */
extern void *aligned_alloc (size_t __alignment, size_t __size)
     __THROW __attribute_malloc__ __attribute_alloc_size__ ((2)) __wur;
#endif

this is pasted from stdlib.h from glibc 2.18. they look the same ...

**Comment by junjieqian** [comment]
This is only definition, and I do not think this part has been changed since 2.12. Can you try using glibc 2.19 or higher version?

**Comment by bottle-watch** [comment]
I just compiled glibc 2.19 with gcc 4.8.1 and then added the include and library path of the newly built glibc2.19 to Makefile ... It is giving me the same warning message ...

**Comment by junjieqian** [comment]
Can you try using g++ 4.8.4, which is recommended? Sorry for keep you trying different versions, but I have not encountered this problem before.

**Comment by bottle-watch** [comment]
I tried g++ 4.9.3, but it is still giving me same errors. So I just removed -Werror ... I got the following ne w error. Could you help with it? 

```
Source/CNTKv2LibraryDll/API/CNTKLibrary.h:1948:122: error: converting to 'const std::unordered_set<CNTK::Variable>' from initializer list would use explicit constructor 'std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = CNTK::Variable; _Hash = std::hash<CNTK::Variable>; _Pred = std::equal_to<CNTK::Variable>; _Alloc = std::allocator<CNTK::Variable>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<CNTK::Variable>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<CNTK::Variable>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<CNTK::Variable>]'
                                                   const std::unordered_set<Variable>& outputsToRetainBackwardStateFor = {}) = 0;
```

**Comment by junjieqian** [comment]
This is discussed in [issue 862](https://github.com/Microsoft/CNTK/issues/862).

**Comment by bottle-watch** [comment]
Great. Thanks ;)
