### ISSUE TITLE
Trained Network File Formats

### ISSUE THREAD

**Issue by embeddetech** [Microsoft/CNTK#879]
First a general question then the specific...

I'm trying to call the CIFAR-10 regression example (06_RegressionSimple) and evaluate the network with other data in C# using the C# wrapper, i.e.:

                using (var model = new IEvaluateModelManagedF())
                {
                    model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: -1);
                    var inDims = model.GetNodeDimensions(NodeGroup.Input);
                }

With modelFilePath=@"C:\dnn\CNTK-master\Examples\Image\Miscellaneous\CIFAR-10\Output\Models\06_RegressionSimple.cmf", an exception is thrown at var inDims=...

General question: Can you explain the different network output file formats (.model,, .dnn, .cmf), or even better refer me to the documentation area that covers that?

Specific question for this problem: Is the 06_RegressionSimple.cmf the correct file to use to evaluate the network with the C# wrapper? No other files are generated when I train the CIFAR data except the .ckp file.

Thanks!!!

**Comment by MikalaiDrabovich** [comment]
I was able to save trained models in a text format - maybe this can be helpful (see my fork)

**Comment by zhouwangzw** [comment]
The suffix of model file is not relevant. They have the same CNTK Model file format. 

If the 06_RegressionSimple.cmf is created when you trained the model, it is the correct file to use for Eval. Would you mind to share more details about the exception, e.g. call stacks or log?

**Comment by embeddetech** [comment]
Hi zhouwangzw,
Sorry for the delay, I didn't see the response. I was able to resolve the issue. The first runtime exception was due to missing dependencies of the EvalDll.dll dll. After that, it was crashing at this line:

var inDims = model.GetNodeDimensions(NodeGroup.Input);

...because the line immediately before it:

model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: 0);

...didn't have the outputNodeNames specified. When I changed it to this:

const string outputLayerName = "ol";
var desiredOutputLayers = new List<string>() { /*hiddenLayerName,*/ outputLayerName };
model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: 0, outputNodeNames: desiredOutputLayers);

Then the GetNodeDimensions(NodeGroup.Input) was able to be called successfully. So I'm guessing there's a default 'outputNodeNames' value that was invalid for this particular network. 

Using the code below, I was able to evaluate the CIFAR10 network on the CNTK-master\Examples\Image\Miscellaneous\ImageNet\ResNet\zebra.jpg zebra picture:

        public System.Windows.Media.Color Evaluate(string imageFileName)
        {
            try
            {

                Dictionary<string, List<float>> outputs;
                using (var model = new IEvaluateModelManagedF())
                {
                    // Desired output layers
                    const string outputLayerName = "ol";

                    var desiredOutputLayers = new List<string>() { outputLayerName };
                    model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), deviceId: 0, outputNodeNames: desiredOutputLayers);

                    // Generate random input values in the appropriate structure and size
                    var inDims = model.GetNodeDimensions(NodeGroup.Input);
                    
                    Bitmap bmp = new Bitmap(Bitmap.FromFile(imageFileName));

                    var resized = bmp.Resize(32, 32, true);
                    var resizedCHW = resized.ParallelExtractCHW();
                    var inputs = new Dictionary<string, List<float>>() { {inDims.First().Key, resizedCHW } };

                    // We request the output layer names(s) and dimension, we'll get both the hidden layer and the output layer
                    var outDims = model.GetNodeDimensions(NodeGroup.Output);

                    // We can preallocate the output structure and pass it in (multiple output layers)
                    outputs = new Dictionary<string, List<float>>()
                    {
                        { outputLayerName, GetFloatArray(outDims[outputLayerName], 1) }
                    };
                    model.Evaluate(inputs, outputs);
                }

                OutputResults(outputs);

            }
            catch (CNTKException ex)
            {
                Console.WriteLine("Error: {0}\nNative CallStack: {1}\n Inner Exception: {2}", ex.Message, ex.NativeCallStack, ex.InnerException != null ? ex.InnerException.Message : "No Inner Exception");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: {0}\nCallStack: {1}\n Inner Exception: {2}", ex.Message, ex.StackTrace, ex.InnerException != null ? ex.InnerException.Message : "No Inner Exception");
            }   
            return Colors.White;
        }
