### ISSUE TITLE
How the SCP file amd MLF files looks like while usong HTKMLFReader as DataReader

### ISSUE THREAD

**Issue by lekshmispeech** [Microsoft/CNTK#882]
Hi,
When i came to know i can reuse my HTK files in CNTK with the help of HTKMLFReader. In the CNTK_Book it is mentioned that the SCP file and MLF files should looks like

The SCP file formfcc features looks like:
**train-dr1-fcjf0-si1027.mfc=//hostname/data/TIMIT/mfc/train/dr1/fcjf0/train-dr1-fcjf0-si1027.mfc[0,306]**
The MLF file is
**#!MLF!#
"train-dr1-fcjf0-si1027.rec"
0 200000 h#_s2 -136.655975 h# -589.680481 h#
200000 400000 h#_s3 -145.780716**
It is mentioned that we need to edit HCopy command to get the desired output (as mentioned above).
My question is how we will get this format of files after execution HTK commands? Please help me to go further.

**Comment by hajix** [comment]
Hi
you must execute `Hcopy -C HCopyTimit.config -S ScriptFile.txt` where `HCopyTimit.config` is a valid HCopy config file and `ScriptFile.txt` is a valid HCopy script file, which is something similar like:
`/home/username/path2timit/TIMIT/train/dr1/fcjf0/si1027.rec Features/train_dr1_fcjf0_si1027.mfc
...`

After feature extraction phase, you need to pass .scp and .mlf file to `HTKMLFReader`. For example: 
```
reader = [
        # reader to use
        readerType = HTKMLFReader

        miniBatchMode = Partial
        randomize = Auto

        features = [
            dim = 792
            scpFile = $DataDir$/CNTK_TIMIT_TRAIN.scp
        ]

        labels = [
            mlfFile = $DataDir$/CNTK_TIMIT_TRAIN.mlf
            labelDim = 61
            labelMappingFile = $DataDir$/map.txt
        ]
]

```

**Comment by lekshmispeech** [comment]
Hi Hajix,

Thank you for your reply. I will try the same, but I have one more doubt.
In the _HTLMLFReader_ labels section what will be the content in _map.txt_ . Whether it is a list of states? If so, how we will get the states alone from HTK.

Can you please help , I am in a critical situation.

Thanks
Lekshmi

**Comment by cha-zhang** [comment]
Sorry this has been very old. I hope your issue has been resolved by now. If it is not, feel free to open a new issue.
