### ISSUE TITLE
Kaldi2Reader, CUDA out of memory on long utterances

### ISSUE THREAD

**Issue by CharlesZha** [Microsoft/CNTK#883]
I'm using CNTK for a task very similar to the last stage of `Examples/Speech/Miscellaneous/AMI/train_dnn_cntk.sh`, where CNTK reads utterance features, calculate posterior probabilities using a trained model, and pipe the output to another process. The configuration file used is `cntk_config/CNTK2_write.cntk`.

I've noticed two scenarios where CNTK would crash with an error message "CUDA failure 2: out of memory".

(I'm using the binary release of CNTK 1.7 with 1-bit SGD. traceGPUMemoryAllocations is turned on.)

The first one is when an utterance is very long. For example, when the first input utterance has a length of 84563 frames, CNTK allocates a lot of memory, seen in the log file as allocating many matrices with 84563 columns. This quickly exhausts all GPU memory, even on a Tesla K80 with 12GB memory, and then CNTK quits before doing any calculations.

Seems like the natural solution would be reading the utterance in chunks, so I've tried using different config options, such as `minibatchSize`, `randomize`, `nbruttsineachrecurrentiter` and `truncated`, but none of them seems to persuade CNTK to not allocate memory for the entire utterance at once.

The second scenario is when each utterance is not very long, but a later one is longer than an earlier one. As seen in the log file, whenever a new utterance to be read is longer than all those before it, CNTK allocates memory for the new length, but does not seem to free memory used for previous utterances. This also eventually lead to an out of memory error. Is this a bug in CNTK or Kaldi2Reader?

The two log files are attached.
[logfiles.zip](https://github.com/Microsoft/CNTK/files/502646/logfiles.zip)

**Comment by jingyonghou** [comment]
Just remove the utterances with long duration or split the long utterances to segments. CNTK will allocate max_utterance_frames * nbruttsineachrecurrentiter GPU memory if you set the truncated to false and for BLSTM, the truncated must set to false according to DongYu's  previous answer.

**Comment by n17s** [comment]
Closing. Feel free to reopen.
