### ISSUE TITLE
Memory management and avoiding crashes during multiple item evaluations / multithreading

### ISSUE THREAD

**Issue by LowerySJ** [Microsoft/CNTK#884]
Hello, CNTK community. I'm trying to figure out how to put CNTK into a C# data processing pipeline. 

For the CNTK network evaluation block I see I have two techniques:
1. Passing multiple items in a single C# eval.dll call, as described here: #589. 
2. Creating multiple instances of the CNTK model and running them on separate threads, as described in [the wiki](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluate-Multiple-Models). 

When I pass too many items (technique 1) I get crashes with an error deep in the Math Library. Is there any built-in functionality for determining the best way to go about this or do I have to figure it out on my own? 

I figured I would write a module to load a network and evaluate one item and estimate the system resources that took and based on that information determine the best way to use techniques 1 and 2 to evaluate all my items. 

Any thoughts? Thanks for any help.

[Cowabunga!](https://www.youtube.com/watch?v=s0z8S2ZjSmc)

**Comment by zhouwangzw** [comment]
You need to decide by yourself which method to use for evaluate multiple items. It is very dependent on your application scenario and system configuraiton. Please note the method 1 only works with Eval interface that does not support sparse input. We are currently working on CNTK V2, which provides better support both on batch input and multiple threads evaluation. The V2 beta will be released in a couple of weeks.

**Comment by LowerySJ** [comment]
Ok thank you. I'll leave post open if anyone else wants to add.

**Comment by zhouwangzw** [comment]
The new CNTK Library Eval API supports parallel evaluation with parameter sharing. You can find examples: [here](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Eval-Examples#examples-for-evaluating-multiple-requests-in-parallel).

**Comment by zhouwangzw** [comment]
I am closing the issue. Please feel free to re-open it if needed.
