### ISSUE TITLE
imageShape = 32:32:3 OR imageShape = 3:32:32

### ISSUE THREAD

**Issue by lvfb** [Microsoft/CNTK#885]
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Miscellaneous/CIFAR-10/ConvNet.cntk  line 16:
```
# Training without BN
TrainConvNet = {
    action = "train"

    BrainScriptNetworkBuilder = {
        imageShape = 32:32:3
        labelDim = 10
```
**imageShape = 32:32:3 OR imageShape = 3:32:32 ?**

See : 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Miscellaneous/CIFAR-10/CifarDownload_py3.py line 14:
```
def readBatch(src, outFmt):
    with open(src, 'rb') as f:
        d = cp.load(f,  encoding="latin1")
        # Note: most of the frameworks use spatial-major (aka NCHW) input format:
        # R0..RN,G0..GN,B0..BN
        # There are 2 possible options in CNTK:
        # 1. If CNTK is built with cuDNN then 'cudnn' (i.e. NCHW format) should be used.
        # 2. Otherwise, legacy CNTK 'NHWC' format should be used. As CIFAR-10 dataset comes in 
        #   NCHW format, it has to be converted to CNTK legacy format first.
        data = d['data']
        if outFmt == 'cudnn':
            feat = data
```
**If CNTK is built with cuDNN then 'cudnn' (i.e. NCHW format) should be used.**
Is "**imageShape = 3:32:32** " Right?

**Comment by cha-zhang** [comment]
Consider the legacy format obsolete. For cntk files, see the following as an example: 
https://github.com/Microsoft/CNTK/blob/master/Examples/Image/Classification/ConvNet/ConvNet_CIFAR10.cntk

**Comment by cha-zhang** [comment]
Leave a comment

**Comment by lvfb** [comment]
Hi , cha-zhang
I think 32:32:3 should be W:H:C .
I wonder  know 
```
    reader = {
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/Train_cntk_text.txt"
		randomize = true
		keepDataInMemory = true     # cache all data in memory 	 
        input = {
            features = { dim = 3072 ; format = "dense" }
            labels   = { dim = 10 ;   format = "dense" }
        }
    }
```
features = { dim = 3072 ; format = "dense" } , in Train_cntk_text.txt , format is W:H:C or **C:H:W ?**

**Comment by cha-zhang** [comment]
Sorry for the confusion. This has to do with how the order is parsed in cuDNN and CNTK. NCHW in cuDNN means width first, then height, then channels, then samples. In contrast, CNTK uses column scan order, so W:H:C means width first, then height, then channels. Therefore specifying 32:32:3 in the CNTK configure file is consistent with CHW in cuDNN.

**Comment by lvfb** [comment]
I think :

in Train_cntk_text.txt  ,
1 to 1024 byte is **channel 1** ,   1024+1 to 1024 x 2 byte is **channel 2**  ,   1024 x 2+1 to 1024 x 3 byte is **channel 3**  
and in 1 to 1024 byte ,
1 to 32 byte is **column 1** , 32+1 to 32 x 2 byte is **column 2** , ... ... , 32 x 31+1 to 32 x 32 byte is **column 32**

Is it right ?

**Comment by cha-zhang** [comment]
Train_cntk_tex.txt is a text file. Open it and you will see first row as: 

|labels 0 0 0 0 0 0 1 0 0 0 |features 59 43 50 68 98 119 139 145 149 149 

Here 59 is the red color of pixel (1,1), 43 is red color of pixel (1,2), etc. So in 1 to 1024 numbers, 1 to 32 is row 1, not column 1.

**Comment by lvfb** [comment]
>  in 1 to 1024 numbers, 1 to 32 is row 1, not column 1.
but see  https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CSEvalClient/Program.cs line 507:
` var resizedCHW = resized.ParallelExtractCHW();`
and see https://github.com/Microsoft/CNTK/blob/master/Examples/Evaluation/CSEvalClient/CntkBitmapExtensions.cs line 110:
```
            Parallel.For(0, imageHeight, (int h) =>
            {
                Parallel.For(0, imageWidth, (int w) =>
                {
                    Parallel.For(0, 3, (int c) =>
                    {
                        features[channelStride * c + imageWidth * h + w] = rgbValues[mapPixel(h, w, c)];
                    });
                });
            });
```
because of  **features[channelStride * c + imageWidth * h + w] = rgbValues[mapPixel(h, w, c)];**
so i think **in 1 to 1024 numbers, 1 to 32 is  column 1, not row 1.**

**Comment by lvfb** [comment]
thanks
