### ISSUE TITLE
How HTK fileswork with CNTK

### ISSUE THREAD

**Issue by lekshmispeech** [Microsoft/CNTK#888]
Hi 
Can anybody help me on steps to give HTK file as input to CNTK.

Please help!!!! i am in confusion.

Thanks in Advance

**Comment by arijit17** [comment]
Did you figure out how to do it?

**Comment by staplesinLA** [comment]
Use HTKMLFReader.

**Comment by cha-zhang** [comment]
It's been a while since last comment. Issue will be closed.
