### ISSUE TITLE
ArcCos Function

### ISSUE THREAD

**Issue by embeddetech** [Microsoft/CNTK#889]
There are sin/cos trig functions available for brainscript:

https://github.com/Microsoft/CNTK/wiki/Full-Function-Reference

However there don't appear to be ArcSin/ArcCos, is it possible for this to be available? Or can someone show me how I can implement it myself? I am trying to perform regression training for a 3D unit vector. For my loss function I'd like to take the ArcCos of the dot product between the truth vector and the output vector, so that the angle between the truth and output is minimized.

**Comment by benfre** [comment]
I don't know how to implement ComputationNode in source code. You might have to write in c++, and add to CNTK.core.bs

I think SquareError would be another good choice for your problem. If the angle between two unit vector are very small that is same as the distance is short. And the gradient are easy to calculate.

**Comment by frankseide** [comment]
Unary operations are quite easy to implement. Basically, look for Cosine in the source code, and follow its pattern. It will only require a few lines of addition. These are the lines that define cosine. Just duplicate them and adapt:

    # CNTK.core.bs:
    Cosine(x, tag='') = new ComputationNode [ operation = 'Cosine' ; inputs = _AsNodes (x) /*plus the function args*/ ]

    # NonlinearityNodes.h:
    DeclareUnaryElementWiseWithOpCodeNode(Cosine,          Cosine,          ElementwiseProductWithCosDerivative,                       binaryWithInputGradient);

    # ComputationNetworkBuilder.cpp:
   else if (nodeType == OperationNameOf(CosineNode))                           return New<CosineNode<ElemType>>(forward<_Types>(_Args)...);

    # TensorOps.h:
    DefUnaryOp(Cosine, cos_(a));
    DefBinaryOp(ElementwiseProductWithCosDerivative, a * -sin_(b)); // note: b = input for cos()

    # CommonMatrix.h:
    opSigmoid, opTanh, opSqr, opSqrt, opExp, opLog, opLinearRectifier, opCosine, opSin,
    opElementwiseProductWithCosDerivative, opElementwiseProductWithSinDerivative,
    # and:
    Macro(Cosine);            \
    Macro(ElementwiseProductWithCosDerivative);                       \

**Comment by benfre** [comment]
Cool! 
It helps me a lot to understand this part of the code. I will continue learning, not able to do a pull request for now.

**Comment by embeddetech** [comment]
Thanks again, Frank! Very helpful.
