### ISSUE TITLE
I want to test CNTK with percentage value and threshold of percentage

### ISSUE THREAD

**Issue by k20001014** [Microsoft/CNTK#890]
hello.

i'm testing with CNTK binaries.

I have 20,000 images(10 classes * 2000 samples) for evaluating.

when I exacute CNTK, I got a result as below.

'Err = 0.13870000 * 20000'. (Is this result of TOP1 ?)
class 0 : err 0.01
class 1 : err 0.21
.....
class 9 : err 0.02

**but I want to apply threshold of percentage value. (by softmax) like below**

for example) IF Test(Evaluation) 3 images.

Input image#1(class 0) -> CNTK output ->class 0 : 40%(max), class 1 : 5%, .... class 9 : 8%,
Input image#2(class 0) -> CNTK output ->class 0 : 30%(max), class 1 : 2%, .... class 9 : 3%,
Input image#3(class 0) -> CNTK output ->class 0 : 5%, class 1 : 40%(max), .... class 9 : 13%,

If I set threshold of percentage = upper 0%
the result is... Err 1/3 =>0.33
correct => 2(image#1,2)
incorrect => 1 (image#3)

If I set threshold of percentage = upper 35% ( I want to test CNTK like this)
the result is...  **Err : 1/2 => 0.5 and NoCount : 1/3 => 0.33**
correct => 1(image#1),
incorrect => 1 (image#3), 
**no-count** => 1 (image#2, because max percentage is under 35%, skipping for evaluation)

is it possible with CNTK binaries?

**Comment by n17s** [comment]
This should be pretty easy to do outside CNTK, e.g. in python. Take a look at the new beta release and feel free to reopen if necessary.
