### ISSUE TITLE
what version of Kaldi was used to produce 1.7.2 Linux binaries?

### ISSUE THREAD

**Issue by mdeisher** [Microsoft/CNTK#893]
I'm seeing the following error when using the CNTK 1.7.2 binary Linux release.

cntk: symbol lookup error: /home/mdeisher/cntk-1.7.2/cntk//lib/Kaldi2Reader.so: undefined symbol: _ZN5kaldi6MatrixIfE6ResizeEiiNS_16MatrixResizeTypeE

Apparently my version of Kaldi is not compatible.  So the question is: what version of Kaldi is required?  And could the dependency libkaldi-*.so be provided in the binary package to prevent issues like this?

Thanks!

--Mike

**Comment by yzhang87** [comment]
Could you use "ldd" to show where the Kaldi2Reader.so linked to? 
btw, did you add your kaldi shared lib into LD_PATH_LIBARARY?

**Comment by mdeisher** [comment]
Yes.  See the attached report.  Thanks.
[report.txt](https://github.com/Microsoft/CNTK/files/512141/report.txt)

**Comment by yzhang87** [comment]
Thanks, I'll take a look.

My Kaldi used for CNTK was a very old version: 

------------------------------------------------------------------------
r4941 | chenguoguo | 2015-03-04 13:33:30 -0500 (Wed, 04 Mar 2015) | 1 line

trunk: fixing broken links in KWS documentation

You can try it first.

**Comment by yzhang87** [comment]
@mdeisher I tested it over latest Kaldi and CNTK (today). It works fine. Would you mind to build it from scratch? It is easier to find the problem.

**Comment by mdeisher** [comment]
I will if go back to that if necessary.  The reason I'm trying to use the binary package in the first place is that I was having difficulty compiling Kaldi2Reader.so with CNTK.

**Comment by mdeisher** [comment]
@yzhang87  I rebuilt both from source as you suggested.  Now it is running.  Thanks!
