### ISSUE TITLE
How do I implement a custom function?

### ISSUE THREAD

**Issue by markisus** [Microsoft/CNTK#902]
I want to implement a custom function. In other frameworks like Caffe and Torch you can do this by implementing the "forwards" and "backwards" pass for computing the function and gradient respectively. 

Is there an analogous concept in CNTK?

**Comment by e-thereal** [comment]
The easiest way is to implement the custom function from CNTK primitives. See the function reference for what is already provided (https://github.com/Microsoft/CNTK/wiki/Full-Function-Reference). Otherwise, one of the CNTK developers might be able to help you.

**Comment by e-thereal** [comment]
If you can't write your function using CNTK primitives, you can implement your own function in CNTK using C++. See this issue of how to do it (#889).

**Comment by XiaoWanLINJU** [comment]
i want to concat two matrix or vector, but there is no concat function??

**Comment by XiaoWanLINJU** [comment]
BTW, do you guys know how to implement CNN with multi-size kernel? I mean despite the outputchannel, the kernel width or height have different size.

**Comment by e-thereal** [comment]
@XiaoWanLINJU please creata a new issue when you question is not related to the current issue.

To your question:
You can use Splice for that. E.g. if you have a 4x1 vector A and a 3x1 vector B you can concatinate them using Splice((A:B), axis = 1), where axis is a 1-based index defining the axis that is used to concatinate.

**Comment by n17s** [comment]
With the V2 realease you can also create a new Function in Python or C++ and implement the forward and backward operations there.
