### ISSUE TITLE
activation of simple2D

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#903]
If I change labels of simple2D 0 to -1 (label 1 -> 1 (same) , label 0 -> -1 (changed) )
I think that when I use these activation (Sigmoid, ReLU), I cant reach right learning, because Sigmoid and ReLU cant represent negative number ( -1 ). But I run this and see that can be reach low error.
Why is it can learning?

( In CNTK, does not apply any activation in last output layer? )

**Comment by n17s** [comment]
The relu activation is applied at the intermediate layers. The final layer does not use relu.
