### ISSUE TITLE
Illegal instruction (core dumped) after successful build

### ISSUE THREAD

**Issue by Bibo-Joshi** [Microsoft/CNTK#906]
Hi there,

somehow I can't really get CNTK to work on my Ubuntu machine. I managed to follow the installation instructions as provided here: [https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux](url). Several errors occurred, but got past them and run the make command without any errors. Still, when I try to run one of the provided examples, I get an error message. Here is the output that I got trying to run the Speech/AN4 example:

```
CNTK 1.7.2+ (master 5c18f2, Oct 10 2016 15:38:26) on localhost at 2016/10/11 08:34:18

cntk  configFile=../Config/FeedForward.cntk
Illegal instruction (core dumped)
```

Looks similar with other examples.
Of course I did some research on the error, but couldn't find any solution.
I'd appreciate any help :)
Kind regards,

Bibo

**Comment by rockcat** [comment]
Same problem here. Ran install and then :+1: 
paul@ELDERBERRY:~/Programs/cntk/Tutorials/HelloWorld-LogisticRegression$ cntk configFile=lr_bs.cntk makeMode=false command=Train
CNTK 2.0.beta11.0 (HEAD bc81f3, Feb 10 2017 11:12:06) on ELDERBERRY at 2017/02/12 17:34:25

cntk  configFile=lr_bs.cntk  makeMode=false  command=Train
Illegal instruction (core dumped)

I have an NVIDIA 1050TI with cuda 8 installed

**Comment by templain** [comment]
I built CNTK Docker Image(used tools/docker/CNTK-CPUOnly-Image/Dockerfile ) and it finished without error,  but I got the same error message while executing tutorials in training steps.

My PC is ASUS K53U(with AMD E-350 Processor).

For example, /cntk/Tutorials/HelloWorld-LogisticRegression/lr_bs.cntk failed and core dumped.

# cntk configFile=lr_bs.cntk
....
Model has 9 nodes. Using CPU.

Training criterion:   lr = Logistic
Evaluation criterion: err = SquareError

Training 3 parameters in 2 parameter tensors.

Illegal instruction (core dumped)

And I got following backtrace using the gdb command. 

# gdb cntk core.25502
...
(gdb) bt
#0  0x00007fba2f30ce0b in Microsoft::MSR::CNTK::TensorOpIteration<float, Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18, Microsoft::MSR::CNTK::TensorOpWithFn(ElemType, std::array<ElemType*, N>, ElemType, const OPFN&, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&) [with ElemType = float; OPFN = Microsoft::MSR::CNTK::CPUMatrix<
ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18; long unsigned int N = 2ul]::__lambda7, 2ul, true, -1, 0>::Loop(float, std::array<float*, 2ul>, float, const Microsoft::MSR::CNTK::CPUMatrix<float>::__lambda18 &, const Microsoft::MSR::CNTK::__lambda7 &, c
onst Microsoft::MSR::CNTK::SmallVector<unsigned long> &, const std::array<Microsoft::MSR::CNTK::SmallVector<long>, 2ul> &, const Microsoft::MSR::CNTK::SmallVector<unsigned long> &, const std::array<Microsoft::MSR::CNTK::SmallVector<long>, 2ul> &) (beta=<optimized out>, pointers=..., alpha=<unavailable>, opfn=..., 
    reductionOp=..., regularOpDims=..., regularStrides=..., 
    reducingOpDims=..., reducingStrides=...)
    at Source/Math/CPUMatrixImpl.h:6890
#1  0x00007fba2f561475 in TensorOpWithRegularLoop<float, Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18, Microsoft::MSR::CNTK::TensorOpWithFn(ElemType, std::array<ElemType*, N>, ElemType, const OPFN&, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&) [with ElemType = float; OPFN = Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, 
const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18; long unsigned int N = 2ul]::__lambda7, 2ul, 0> (
    reducingStrides=..., reducingOpDims=..., regularStrides=..., 
    regularOpDims=..., reductionOp=..., opfn=..., alpha=1, pointers=..., 
    beta=0) at Source/Math/CPUMatrixImpl.h:6987
#2  TensorOpWithFnAndReduction<float, Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18, Microsoft::MSR::CNTK::TensorOpWithFn(ElemType, std::array<ElemType*, N>, ElemType, const OPFN&, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&) [with ElemType = float; OPFN = Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::Ele
mentWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18; long unsigned int N = 2ul]::__lambda7, 2ul> (reductionOp=..., 
    reducingStrides=..., reducingOpDims=..., regularStrides=..., 
    regularOpDims=..., offsets=..., opfn=..., alpha=1, pointers=..., beta=0)
    at Source/Math/CPUMatrixImpl.h:7016
#3  Microsoft::MSR::CNTK::TensorOpWithFn<float, Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18, 2ul>(float, std::array<float*, 2ul>, float, const Microsoft::MSR::CNTK::CPUMatrix<float>::__lambda18 &, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<unsigned long, 2ul> &, const Microsoft::MSR::CNTK::SmallVector<unsigned long> &, const std::array<Microsoft::MSR::CNTK::SmallVector<long>, 2ul> &, const Microsoft::MSR::CNTK::SmallVector<unsigned long> &, const std::array<Microsoft::MSR::CNTK::SmallVector<long>, 2ul> &) (
    beta=0, pointers=..., alpha=1, opfn=..., reductionOp=<optimized out>, 
    offsets=..., regularOpDims=..., regularStrides=..., reducingOpDims=..., 
    reducingStrides=...) at Source/Math/CPUMatrixImpl.h:7048
#4  0x00007fba2f5e960f in Microsoft::MSR::CNTK::CPUMatrix<float>::TensorOp (
    this=<optimized out>, beta=beta@entry=0, a=..., alpha=alpha@entry=1, 
    op=op@entry=Microsoft::MSR::CNTK::opSigmoid, 
    reductionOp=reductionOp@entry=Microsoft::MSR::CNTK::opSum, offsets=..., 
    regularOpDims=..., regularStrides=..., reducingOpDims=..., 
    reducingStrides=...) at Source/Math/CPUMatrixImpl.h:7089
#5  0x00007fba2f97420c in Microsoft::MSR::CNTK::Matrix<float>::TensorOp (
    this=0x2ee16e8, beta=0, a=..., alpha=1, 
    op=op@entry=Microsoft::MSR::CNTK::opSigmoid, 
    reductionOp=reductionOp@entry=Microsoft::MSR::CNTK::opSum, offsets=..., 
    regularOpDims=..., regularStrides=..., reducingOpDims=..., 
    reducingStrides=...) at Source/Math/Matrix.cpp:5937
#6  0x00007fba2f9a3bfe in Microsoft::MSR::CNTK::TensorView<float>::DoUnaryOpOf
    (this=this@entry=0x7ffe8ab4cf60, beta=beta@entry=0, a=..., 
    alpha=alpha@entry=1, op=op@entry=Microsoft::MSR::CNTK::opSigmoid, 
    reductionOp=reductionOp@entry=Microsoft::MSR::CNTK::opSum)
    at Source/Math/TensorView.cpp:249
#7  0x0000000000b2fffe in Microsoft::MSR::CNTK::UnaryElementWiseWithOpCodeNodeBase<float, (Microsoft::MSR::CNTK::ElementWiseOperator)8, (Microsoft::MSR::CNTK::ElementWiseOperator)46, (Microsoft::MSR::CNTK::GradientOperationType)3>::ForwardProp (this=0x2edb728, fr=...)
    at Source/ComputationNetworkLib/NonlinearityNodes.h:55
#8  0x0000000000c6abe4 in Microsoft::MSR::CNTK::ComputationNetwork::PARTraversalFlowControlNode::ForwardProp (node=
    std::shared_ptr (count 17, weak 1) 0x2edb728, fr=...)
    at Source/ComputationNetworkLib/ComputationNetworkEvaluation.cpp:148
#9  0x00000000009694e3 in operator() (node=..., __closure=<optimized out>)
    at Source/ComputationNetworkLib/ComputationNetwork.h:178
#10 std::_Function_handler<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&), void Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > >(std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&)::{lambda(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&) (__functor=..., __args#0=...)
    at /usr/include/c++/4.8/functional:2071
#11 0x0000000000974187 in operator() (
    __args#0=std::shared_ptr (count 17, weak 1) 0x2edb728, this=0x7ffe8ab4d350)
    at /usr/include/c++/4.8/functional:2471
#12 Microsoft::MSR::CNTK::ComputationNetwork::TravserseInSortedGlobalEvalOrder<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > >(std::vect---
or<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::function<void (std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&)> const&) (this=this@entry=0x2c40178, 
    nodes=std::vector of length 2, capacity 2 = {...}, action=...)
    at Source/ComputationNetworkLib/ComputationNetwork.h:170
#13 0x000000000097436e in Microsoft::MSR::CNTK::ComputationNetwork::ForwardProp<std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > > (
    this=0x2c40178, nodes=std::vector of length 2, capacity 2 = {...})
    at Source/ComputationNetworkLib/ComputationNetwork.h:177
#14 0x0000000000a86675 in Microsoft::MSR::CNTK::SGD<float>::TrainOneEpoch (
    this=this@entry=0x2c3fd38, 
    net=std::shared_ptr (count 6, weak 0) 0x2c40178, 
    refNet=std::shared_ptr (count 6, weak 0) 0x2c40178, 
    refNode=std::shared_ptr (empty) 0x0, epochNumber=epochNumber@entry=0, 
    epochSize=epochSize@entry=4611686018427387903, 
    trainSetDataReader=trainSetDataReader@entry=0x2c41c28, 
    learnRatePerSample=learnRatePerSample@entry=0.039999999105930328, 
    tunedMBSize=tunedMBSize@entry=25, 
    featureNodes=std::vector of length 2, capacity 2 = {...}, 
    labelNodes=std::vector of length 1, capacity 1 = {...}, 
    criterionNodes=std::vector of length 1, capacity 1 = {...}, 
    evaluationNodes=std::vector of length 1, capacity 1 = {...}, 
Python Exception <class 'IndexError'> list index out of range: 
inputMatrices=inputMatrices@entry=0x2c41e80, learnableNodes=std::list, 
Python Exception <class 'IndexError'> list index out of range: 
smoothedGradients=std::list, 
smoothedCounts=std::vector of length 2, capacity 2 = {...}, 
epochCriterion=..., 
epochEvalErrors=std::vector of length 1, capacity 1 = {...}, prefixMsg="", 
maxNumberOfSamples=maxNumberOfSamples@entry=18446744073709551615, 
totalMBsSeenBefore=totalMBsSeenBefore@entry=0, 
tensorBoardWriter=std::shared_ptr (empty) 0x0)
at Source/SGDLib/SGD.cpp:1249
#15 0x0000000000a8d6de in Microsoft::MSR::CNTK::SGD<float>::TrainOrAdaptModel (
this=this@entry=0x2c3fd38, startEpoch=startEpoch@entry=0, 
net=std::shared_ptr (count 6, weak 0) 0x2c40178, 
networkLoadedFromCheckpoint=networkLoadedFromCheckpoint@entry=true, 
refNet=std::shared_ptr (count 6, weak 0) 0x2c40178, 
refNode=std::shared_ptr (empty) 0x0, 
trainSetDataReader=trainSetDataReader@entry=0x2c41c28, 
validationSetDataReader=validationSetDataReader@entry=0x0)
at Source/SGDLib/SGD.cpp:646
#16 0x0000000000a90982 in Microsoft::MSR::CNTK::SGD<float>::Train (
this=this@entry=0x2c3fd38, 
net=std::shared_ptr (count 6, weak 0) 0x2c40178, 
deviceId=deviceId@entry=-1, 
trainSetDataReader=trainSetDataReader@entry=0x2c41c28, 
validationSetDataReader=validationSetDataReader@entry=0x0, 
startEpoch=startEpoch@entry=0, loadNetworkFromCheckpoint=true)
at Source/SGDLib/SGD.cpp:80
#17 0x00000000009616c9 in DoTrain<Microsoft::MSR::CNTK::ConfigParameters, float> (config=...) at Source/ActionsLib/TrainActions.cpp:126
#18 0x00000000008ef750 in DoCommands<float> (config=..., 
mpi=std::shared_ptr (empty) 0x0) at Source/CNTK/CNTK.cpp:279
#19 0x000000000084ee35 in wmainOldCNTKConfig (argc=argc@entry=2, 
argv=argv@entry=0x2c14e00) at Source/CNTK/CNTK.cpp:746
#20 0x000000000084f4cf in wmain1 (argc=argc@entry=2, argv=argv@entry=0x2c14e00)
at Source/CNTK/CNTK.cpp:805
#21 0x00000000007ff938 in main (argc=2, argv=<optimized out>)
at Source/CNTK/CNTK.cpp:915


(gdb) frame 0
#0  0x00007fba2f30ce0b in Microsoft::MSR::CNTK::TensorOpIteration<float, Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18, Microsoft::MSR::CNTK::TensorOpWithFn(ElemType, std::array<ElemType*, N>, ElemType, const OPFN&, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, N>&) [with ElemType = float; OPFN = Microsoft::MSR::CNTK::CPUMatrix<ElemType>::TensorOp(ElemType, const Microsoft::MSR::CNTK::CPUMatrix<ElemType>&, ElemType, Microsoft::MSR::CNTK::ElementWiseOperator, Microsoft::MSR::CNTK::ElementWiseOperator, const std::array<long unsigned int, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&, const Microsoft::MSR::CNTK::SmallVector<long unsigned int>&, const std::array<Microsoft::MSR::CNTK::SmallVector<long int>, 2ul>&) [with ElemType = float]::__lambda18; long unsigned int N = 2ul]::__lambda7, 2ul, true, -1, 0>::Loop(float, std::array<float*, 2ul>, float, const Microsoft::MSR::CNTK::CPUMatrix<float>::__lambda18 &, const Microsoft::MSR::CNTK::__lambda7 &, c
onst Microsoft::MSR::CNTK::SmallVector<unsigned long> &, const std::array<Microsoft::MSR::CNTK::SmallVector<long>, 2ul> &, const Microsoft::MSR::CNTK::SmallVector<unsigned long> &, const std::array<Microsoft::MSR::CNTK::SmallVector<long>, 2ul> &) (beta=<optimized out>, pointers=..., alpha=<unavailable>, opfn=..., 
    reductionOp=..., regularOpDims=..., regularStrides=..., 
    reducingOpDims=..., reducingStrides=...)
    at Source/Math/CPUMatrixImpl.h:6890
6890	        else if (alpha != 1)

**Comment by pkranen** [comment]
Please try again with the latest setup instructions and the 2.0 code. Closing this issue, please open a new isuue if the problem still occurs with 2.0 bits. Thanks.
