### ISSUE TITLE
Is the implement of LSTM in CNTK used truncated bptt? 

### ISSUE THREAD

**Issue by jingyonghou** [Microsoft/CNTK#908]
I find when I used sentence-by-sentence training in CNTK（When I trained a LSTM）, it need two parameters: minibatchSize and numUttsPerMinibatch.  Is the implement of LSTM in CNTK used truncated bptt? Is the minibatchSize means maximum steps errors can be backpropagated through time?

**Comment by n17s** [comment]
No, minibatch size is the number of tokens that  will be sent to the GPU to be processed as a whole. numUttsPerMinibatch is the number of sentences that will be processed in parallel. To do bptt for, say, 20 steps you need to specify two different options: truncated=true and truncationLength=20
