### ISSUE TITLE
Unable to run MNIST Example 02_Convolution.config

### ISSUE THREAD

**Issue by fwaris** [Microsoft/CNTK#91]
I get an out of memory error (on 2GB NVidia GeoForce mobile card).
Can it be configured to reduce less memory (assuming it is truly a memory error.
Here is the part of the log file where the error shows up. 

Post-processing network complete.
evalNodeNames are not specified, using all the default evalnodes and training criterion nodes.
starting epoch 0 at record count 0, and file position 0
already there from last epoch
RandomOrdering: 1989 retries for 10000 elements (19.9%) to ensure window condition
RandomOrdering: recached sequence for seed 0: 2334, 3830, ...

[CALL STACK]
    >Microsoft::MSR::CNTK::operator<<<double>
    -Microsoft::MSR::CNTK::GPUSparseMatrix<double>::performInplaceFunction
    -Microsoft::MSR::CNTK::GPUMatrix<float>::Resize
    -Microsoft::MSR::CNTK::Matrix<float>::Resize
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -Microsoft::MSR::CNTK::MatrixBase::operator=
    -BaseThreadInitThunk
    -RtlUserThreadStart

CUDA failure 2: out of memory ; GPU=0 ; hostname=FAI-HP2 ; expr=cudaMalloc((void**)&m_pArray,sizeof(ElemType)*m_elemSizeAllocated)
EXCEPTION occurred: CUDA failure 2: out of memory ; GPU=0 ; hostname=FAI-HP2 ; expr=cudaMalloc((void**)&m_pArray,sizeof(ElemType)*m_elemSizeAllocated)

**Comment by dongyu888** [comment]
CNN does consume a lot of memory. you can try adding

    shareNodeValueMatrices=true

to the top of the config file to reduce memory usage. If that's not enough you will need to reduce the minibatchSize in the config.

**Comment by Alexey-Kamenev** [comment]
Hello,
Are you using cuDNN-enabled build? I was able to train 02_Convolution sample of my GTX 765M (2GB) just fine.
In addition to what Dong said, try setting maxTempMemSizeInSamples to 1 in your config files, that should help in case you are not using cuDNN.

**Comment by fwaris** [comment]
Unfortunately changing the suggested values (and event setting mb size to 1) I still see out of memory error. I will look into using the cuDNN version.

**Comment by mradmila** [comment]
Please reopen this issue if it still persists after trying cuDNN.
