### ISSUE TITLE
I want to change the CUDA_PATH v7.5 to v8.0

### ISSUE THREAD

**Issue by k20001014** [Microsoft/CNTK#912]
hello.

i'm testing with GTX 1080, so I installed CUDA 8.0/cudnn-5.1.

but when I exactute CNTK-1-7-2 I got an error 'CURAND failure 201' and i saw the log as below
-----------------------------------
Build info : 
...
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
.....
-------------------------------------

I'm using CNTK, binary....    Is it possible, change the CUDA_PATH....??

**Comment by alexeyo26** [comment]
Hello!

The binaries are compiled with  CUDA 7.5. We're working on moving our system to CUDA 8 and will announce when done. 

In the meantime if you want to work with CUDA 8 you need to build from sources.

Thank you,
Alexey

**Comment by k20001014** [comment]
hello alexeyo26.

thank you for answering. i'm waiting for binaries of CUDA 8.

thanks
