### ISSUE TITLE
ATIS.cntk example with mpiexec on 2 GPU crashes

### ISSUE THREAD

**Issue by RalfBendzko** [Microsoft/CNTK#913]
Hi,
I'm evaluating cntk ('CNTK 1.7.2 (HEAD d1ad5f, Oct  1 2016 14:30:48)') on Windows 10 with 2 gtx970 GPU and found it quite impressive.
While I run through the provided examples with only CPU or with one GPU everything worked fine.

Then I tried 'mpiexec -np 2 %cntk%' with ATIS.cntk configFile, after adopting it in accordance to https://github.com/Microsoft/CNTK/wiki/Multiple-GPUs-and-machines. Now the example crashes after the first epoch with 
'CNTK: Caught Win32 exception 0xc0000005: Access violation.'

The stack ends with
'Model has 61 nodes. Using GPU 1.
Training criterion:   cr = CrossEntropyWithSoftmax
Evaluation criterion: errs = ClassificationError
Training 1005127 parameters in 18 parameter tensors.
Finished Epoch[ 1 of 20]: [Training] cr = 0.40189179 * 36006; errs = 8.254% * 36006; totalSamplesSeen = 36006; learningRatePerSample = 0.0099999998; epochTime=8.5101s
CNTK: Caught Win32 exception 0xc0000005: Access violation.
job aborted:
[ranks] message
[0] terminated
[1] process exited without calling finalize
---- error analysis -----
[1] on DESKTOP-NPQAHQ4
C:\AI\cntk\cntk\cntk ended prematurely and may have crashed. exit code 1
---- error analysis -----'

What do I wrong here?

Ralf

**Comment by eldakms** [comment]
Hi Ralf,

Sorry for that, this has been fixed on the latest master. Please pull and rebuild.
(Potentially also increasing minibatch size should help - the error due to the first empty minibatch for one of the workers).
Thank you very much for reporting this!
