### ISSUE TITLE
StackoverflowException when try to create network for the pre trained ResNet_152.model

### ISSUE THREAD

**Issue by mayuanyang** [Microsoft/CNTK#917]
Hi 

I got StackoverFlowException when try to create the network from ResNet_152.model, 

```
 using (var model = new IEvaluateModelManagedF())
            {
                model.CreateNetwork(string.Format("modelPath=\"{0}\"", query.ModelFilePath), deviceId: -1);
```

any thought?

**Comment by zhouwangzw** [comment]
What is your ModelFilePath? Currently, the modelPath has to be specified as a full path. In the CSEvalClient example, the relative path is combined with the current working directory to build the full path.

**Comment by mayuanyang** [comment]
hi, the same setting to load a smaller resnet model is working fine, just res152 has this problem, thanks

**Comment by pkranen** [comment]
Please try again with updated models and recent binaries. Closing this issue, feel free to reopen if problems remain with latest bits.
