### ISSUE TITLE
why does the DNN training so slow when dump the log info by using the parameter of 'stderr'? 

### ISSUE THREAD

**Issue by HintDf** [Microsoft/CNTK#918]
Is it a bug? 

I have a way to solve it by writing a external tool to invoke CNTK, read and dump the log info without the stderr para. And I wonder to know if there is a easier way to dump log without writing another tool?

**Comment by n17s** [comment]
Can you provide a concrete example with timings on your machine.

**Comment by pkranen** [comment]
Closing this one since no details were provided. Please try with latest bits and open a new issue if required.
