### ISSUE TITLE
The same matrix has been transferred between different devices for many times

### ISSUE THREAD

**Issue by Alan-Lee123** [Microsoft/CNTK#920]
When I use RNN, (like the G2P.cntk in the Sequence to Sequence Example), I often encounter a warning like
WARNING: The same matrix with dim [1, 8] has been transferred between different devices for 20 times
What the warning means? What can I do to avoid this.

**Comment by n17s** [comment]
This comes from here: https://github.com/Microsoft/CNTK/blob/master/Source/Math/Matrix.cpp#L915
Are your inputs sparse and what kind of operations do you do on them?

**Comment by Alan-Lee123** [comment]
No, my input is not sparse. I just use CLASSLSTM in SimpleNetworkBuilder.
![image](https://cloud.githubusercontent.com/assets/11437976/19877568/5451a4da-a01b-11e6-8d30-f6cb1aa33cd4.png)

**Comment by cha-zhang** [comment]
This thread has been too old and it's unclear if the issue remain in the latest CNTK 2.0. I'm closing this now. Please reopen a new issue if needed. Thanks!
