### ISSUE TITLE
How to run image/fastrcnn example?

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#922]
How to run image/fastrcnn example?

Which dataset to use?

Thks

PB

**Comment by cha-zhang** [comment]
We are preparing a blog on that. Maybe ready in a week.

**Comment by pmfcdb** [comment]
Ok, thanks! I'm looking forward to it!

**Comment by pmfcdb** [comment]
FastRCNN
https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Detection/FastRCNN
