### ISSUE TITLE
BS Model Editing with Node Names Containing "_"

### ISSUE THREAD

**Issue by pozhijisi** [Microsoft/CNTK#923]
On the Wiki page "BS Model Editing", there is a section named "Problems with node names with . [ and ]".

In that section, you say we should replace the characters by "_".

I have a node name containing "_". Will that be confusing if I use the name directly? Is there a way to handle this?

**Comment by frankseide** [comment]
_ does not need to be replaced. E.g. a name like `X_1[2]` would be have to be changed to `X_1_2_`
