### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by zpmmehrdad** [Microsoft/CNTK#925]
hi guy...
i have 5000 images and 5 category labels.
how can i create a model from directory of images?
i want to use c# code.
please help me.

**Comment by e-thereal** [comment]
I don't think you can do it from C# yet. AFAIK, you can only evaluated a trained model using the C# interface but not create and train new models. There is a beta C++ and Python interface for creating and training models, so there is hope that there will be a C# interface sometime as well. For now, I'd go the BrainScript way. Have you taken a lookt at some of the image classification examples? You might be able to achieve what you want following some of those examples. E.g., have a look at this tutorial: https://github.com/Microsoft/CNTK/wiki/Hands-On-Labs-Image-Recognition

**Comment by zpmmehrdad** [comment]
thank you @e-thereal

**Comment by zpmmehrdad** [comment]
@e-thereal  what is the best tools for create model?

**Comment by zpmmehrdad** [comment]
@e-thereal what is the best of tools for create model from directory ?

**Comment by cha-zhang** [comment]
Check the Python script under https://github.com/Microsoft/CNTK/tree/master/Examples/Image/DataSets/CIFAR-10/install_cifar10.py. It will teach you how to create the map files needed for image reader.

**Comment by zpmmehrdad** [comment]
@cha-zhang thank

**Comment by zpmmehrdad** [comment]
@cha-zhang thanks
