### ISSUE TITLE
EXCEPTION occurred: Plugin not found: 'CNTKTextFormatReader.dll'

### ISSUE THREAD

**Issue by zhiqinzhu123** [Microsoft/CNTK#926]
I meet this problem when I excute examples of ->Image-> GettingStarted->01_OneHidden.cntk and 02_OneConv.cntk.
Do any body know how to solve it ?

**Comment by e-thereal** [comment]
The error indicates that the specified DLL could not be found. Can you check if CNTKTextFormatReader.dll is in the same directory as the CNTK.exe? Also, are you using the pre-built binaries or have you built CNTK from source?

**Comment by zhiqinzhu123** [comment]
I built CNTK from the source myself,  I have check there is no CNTKTextFormatReader.dll in the same directory of the CNTK.exe.

**Comment by e-thereal** [comment]
Did you build the entire solution without errors? Under Reader Plugins, if have a project called CNTKTextFormatReader. Can you please check if this project builds successfully?

**Comment by zhiqinzhu123** [comment]
Finally get it thanks a lot!
