### ISSUE TITLE
Changing learning rate reduces error. Bonus!

### ISSUE THREAD

**Issue by PeterGriffioen** [Microsoft/CNTK#927]
Why does changing the LearningRatePerSample produce such a marked reduction in error? I see these kinds of reductions resulting from the learning rate transitioning, as seen here at epoch 200. The relevant control is

learningRatesPerSample = 0.001x50:0.0005x150:0.0001
(note substitute the asterisk for x. Not used here as seems to do weird things with text formatting)

Will I converge sooner if I change the rate often?

![reduced](https://cloud.githubusercontent.com/assets/18395419/19553512/41c73a92-9700-11e6-9712-fc04586b531d.png)

**Comment by cha-zhang** [comment]
You may, but there is a risk. A small learning rate tends to trap the model to local minimum. So the typical practice is to use a larger learning rate, train until the error doesn't decrease much from epoch to epoch, and then drop the learning rate by a factor of 2-10.

**Comment by PeterGriffioen** [comment]
Yes, I agree with that. But obviously changing the learning rate is causing the software to re-assess some other parameters which in (in this case) reduces the error rate. What operation is being performed at the change that isn't being done epoch to epoch?

**Comment by cha-zhang** [comment]
Changing the learning rate should not cause the software to re-assess other parameters, unless your network configuration sets to do so.

**Comment by n17s** [comment]
When the learning rate becomes smaller the model stops bouncing around. The technical term is that the update has less variance. There is a lot of work in the optimization literature for reducing the variance of SGD. Halving the learning rate is a simple way of achieving this goal.
