### ISSUE TITLE
Inconsistency in CNTK-CPUOnly-Image Dockerfile with GitHub repo structure

### ISSUE THREAD

**Issue by ahfant** [Microsoft/CNTK#928]
The docker file contains the following commands

RUN cd Examples/Image/Miscellaneous/CIFAR-10 && \
    python CifarDownload.py && \
    python CifarConverter.py cifar-10-batches-py && \
    cd ../../../..

RUN cd Examples/Image/MNIST/AdditionalFiles && \
    python mnist_convert.py && \
    cd ../../../..

but this is no longer valid in the master: see
https://github.com/Microsoft/CNTK/tree/master/Examples/Image

**Comment by mahilleb-msft** [comment]
Hi @ahfant, thanks for reporting this! A fix is on a branch and will soon be merged into master.

Best, Mark

**Comment by mahilleb-msft** [comment]
This one should be fixed, closing.
