### ISSUE TITLE
The link to the CNTK book errors

### ISSUE THREAD

**Issue by ericwj** [Microsoft/CNTK#929]
After downloading the CNTK book, there are several problems. There might be a problem with the link on Github, or the problem is with the Microsoft Research website and the publication being referred to.

Here's the [link](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/CNTKBook-20150805.pdf) which I found after following this [link](http://research.microsoft.com/apps/pubs/?id=226641) on the Github wiki main page.

The first is that the link appears to be outdated. The URL points to a document from August 5, 2015. The website actually states the latest version is from October 1, 2016.

The second is because the request for the PDF file actually downloads a HTML page that is the response to a 404 error instead of a PDF page.

The third is that this HTML document is opened as a PDF document after which Edge tries to open it as such.

**Comment by n17s** [comment]
The CNTK book is no longer being updated. The most up to date information is on the github wiki and the sites it points to (e.g. cntk.ai/pythondocs)
