### ISSUE TITLE
Error in FastRCNN example in script A2_RunCntk.py

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#932]
Hello,

I was trying to run FastRCNN example, step A2_RunCntk.py and this error occured :

"Creating virgin network.

[CALL STACK]
  network = new ComputationNetwork {
            2
          criterionNodes  = (ce)
                             1
          ce = CrossEntropyWithSoftmax(roiLabels, z, axis = 1)
                                      0                     ^
EXCEPTION occurred. while evaluating: BrainScriptNetworkBuilder(25): function does not have an optional argument 'axis'
Time running cntk [s]: 3.394
Traceback (most recent call last):
  File "C:\Users\cvig\Documents\CNTK-1-7-2-Windows-64bit-GPU\cntk\Examples\Image\Detection\FastRCNN\A2_RunCntk.py", line 50, in <module>
    assert pid.returncode == 0, "ERROR: cntk ended with exit code {}".format(pid.returncode)
AssertionError: ERROR: cntk ended with exit code 1"

The complete execution of script is here:
[error01.txt](https://github.com/Microsoft/CNTK/files/544826/error01.txt)

Paulo Brito

**Comment by pkranen** [comment]
This requires a more recent build, it has only been added to CNTK.core.bs recently. See [here ](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs#L458).
