### ISSUE TITLE
Pixelwise classification using CNTK

### ISSUE THREAD

**Issue by rold2007** [Microsoft/CNTK#933]
Hello,

I would like to use CNTK for pixelwise classification of images (like [SegNet](http://mi.eng.cam.ac.uk/projects/segnet/)). I haven't found a ready-to-use network architecture in the examples folder to do such a task. I have used AlexNet's model for binary classification of images successfully but I am not sure where to start to make this kind of network evolve to generate a pixelwise output.
Could anyone point me in the right direction ?
Is it a good idea to start from AlexNet for this ?
In case it is relevant, I am currently only doing binary classification, but I would be interested in a solution with also (potentially) supports multi-class.

Also, from what I could understand, to generate the pixelwise output I'll need to feed the ground truth (which I don't have right now) of the same size as my training images in input. Creating the ground truth of 10k+ images is a huge task, is there a way to produce pixelwise output without a pixelwise ground truth as input ?
If the ground truth images are compulsory, for a start I could do some tests using the [CamVid](http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamSeq01/) or [KITTI](http://www.cvlibs.net/datasets/kitti/eval_road.php) datasets but I would be happy if I wouldn't have to produce all those ground truth images...

Thanks !

**Comment by cha-zhang** [comment]
We are preparing examples for pixelwise classification (segmentation), please stay tuned.

**Comment by rold2007** [comment]
@cha-zhang Thanks a lot ! Is there any timeframe, 1 week, 1 month ?

**Comment by cha-zhang** [comment]
No firm timeframe yet, but definitely longer than 1 week. We need to prepare a few other examples before moving to the segmentation task.

**Comment by pksorensen** [comment]
@cha-zhang  Any update on this? :)

**Comment by cha-zhang** [comment]
Not yet. It’s holiday season and everything moves slowly…

**Comment by dimadim** [comment]
@cha-zhang Can CNTK do pixelwise classification of images like SegNet now? Is there any examples? Thank you )

**Comment by cha-zhang** [comment]
The key components should have already been there. We are still working on the examples.

**Comment by pksorensen** [comment]
An example like SegNet would be cool :)

**Comment by matiasmolinas** [comment]
Any update?

**Comment by ldenoue** [comment]
Anything now?
