### ISSUE TITLE
CNTK 1.7.2 bin dist: Out of memory [Test action, CPU]

### ISSUE THREAD

**Issue by avader906** [Microsoft/CNTK#936]
CNTK 1.7.2 binary installation

Test data is normalized to (-1;1) on inputs and {0,1} on the label. 56GB text file.

Test action on a trained model (40mio samples, 156 inputs and 1 category label).
The train action was successful on GPU using appropriate minibatchSize

Test action failed on GPU with access error #935 
Test action was ran on CPU using all cores through MS MPI

mpiexec.exe -np 12 \localcntk\cntk\CNTK.exe configfile=../config/margo_testset_test.cntk deviceId=-1

During the run the system runs out of physical memory (>50GB).

PS: using -np 6 system runs out of memory. seems that minibatchSize is not taken into account in Test action - or that readers on all threads are trying to load entire datafile

PS2: running \localcntk\cntk\CNTK.exe configfile=../config/margo_testset_test.cntk deviceId=-1
results in CNTK: Caught Win32 exception 0xc0000005: Access violation. (same as #935 on GPU)

tracelevel 2 dump before the crash:

INFO: Finished loading sequence (id = 22006) at offset 33543079 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22007) at offset 33544604 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22008) at offset 33546129 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22009) at offset 33547656 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22010) at offset 33549180 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22011) at offset 33550697 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22012) at offset 33552219 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
INFO: Finished loading sequence (id = 22013) at offset 33553739 in the input file (D:/testData_binaryp.txt), successfull
y read 1 out of expected 1 rows.
CNTK: Caught Win32 exception 0xc0000005: Access violation.

Config file:
###### 
# PARAMETERS
###### 

RootDir = ".."
ConfigDir = "$RootDir$/Config"
# DataDir = "$RootDir$/Data"

DataDir = "D:"
OutputDir = "$RootDir$/Output"
ModelDir = "$OutputDir$/Models"

deviceId = -1 
command = Test_Test
# Parameters

precision = "float"
parallelTrain = false
numCPUThreads = 0
modelPath = "$ModelDir$/multigputest.dnn"
# Error loging
# stderr = "$OutputDir$/log"

traceGPUMemoryAllocations=0         #trace memory usage
traceLevel = 1                      #0 (limited output), 1 (medium output) and 2 (verbose output)
###### 
# TEST RESULTS
# (computes prediction error and
# perplexity on a test set and
# writes the output to the console.)
###### 

Test_Test=[
    action = "test"
    minibatchSize = 12
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/testData_binaryp.txt"
        randomize = false
        keepDataInMemory = false
        input = [
            features = [
                alias = "i"
                dim = 156  
                format = "dense"
            ]
            labels = [
                alias = "o"
                dim = 1
                format = "dense"
            ]
        ]
    ]
]

**Comment by e-thereal** [comment]
I can only comment on the out of memory problem. Have you taken a look at the troubleshooting section? In particular this page: https://github.com/Microsoft/CNTK/wiki/Troubleshoot-CNTK#although-the-model-was-trained-with-a-larger-set-than-the-evaluation-set-cntk-runs-out-of-memory-during-evaluation

**Comment by avader906** [comment]
Thank you for your reply and documentation pointer. 

As per original post and config file, changing minibatchSize still leads to the same issue. 
minibatchSize=1 or 2 leads to the same problem. 
- using cntk CPU only gives CNTK: Caught Win32 exception 0xc0000005: Access violation
- using CNTK GPU only gives CNTK: Caught Win32 exception 0xc0000005: Access violation
- using mpi CPU only the system runs out of memory if several threads are specified

If necessary I can enclose matlab code to generate the test dataset. The issue seems to be in the CNTKTextFormatReader, or rather how it is used inside the Test action. Somehow CNTK tries to load entire dataset or the reader leaks memory. The host is windows 2012 r2 server.

**Comment by avader906** [comment]
Easier example to provoke CNTK: Caught Win32 exception 0xc0000005: Access violation while running "Test" action with CPU:

Simple XOR model:

RootDir = ".."
ConfigDir = "$RootDir$/Config"
DataDir = "D:"
OutputDir = "$RootDir$/Output"
ModelDir = "$OutputDir$/Models"
deviceId = -1 

command = xor_Train:xor_Test:xor_DumpNodeInfo

precision = "float"
parallelTrain = false
modelPath = "$ModelDir$/gpu_xor.dnn"
traceGPUMemoryAllocations=0
traceLevel = 1

xor_Train=[
    action = "train"
    BrainScriptNetworkBuilder = [
        features = Input (2)
        labels   = Input (1)
        b1 = Parameter (2, 1) 
        w1 = Parameter (2, 2)
	b2 = Parameter (1, 1)
	w2 = Parameter (1, 2)

        h1 = Sigmoid (w1 * features + b1)    
	o  = Sigmoid (w2 * h1 + b2)
			
	ce = CrossEntropy (labels, o)
	err = ErrorPrediction(labels,o)
		
        featureNodes    = (features)
        labelNodes      = (labels)
        criterionNodes  = (ce)	
        evaluationNodes = (err)	
        outputNodes     = (o)
    ] 

    SGD = [
        epochSize = 0 
        minibatchSize = 50  #50 is entire file
        maxEpochs = 5000
        learningRatesPerSample = 0.04
    ]

    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/xor.txt"
		randomize = false
        input = [
            features = [
				alias = "i"
                dim = 2        
                format = "dense"
            ]
            labels = [
				alias = "o"
                dim = 1
                format = "dense"
            ]
        ]
    ]
]

xor_Test=[
    action = "test"
	minibatchSize = 2
    reader = [
        readerType = "CNTKTextFormatReader"
        file = "$DataDir$/xor.txt"
		randomize = false
        input = [
            features = [
				alias = "i"
                dim = 2        
                format = "dense"
            ]
            labels = [
				alias = "o"
                dim = 1
                format = "dense"
            ]
        ]
    ]
]

xor_DumpNodeInfo = [
    action = "dumpNode"
	modelPath = "$ModelDir$/gpu_xor.dnn"
    outputFile = "$OutputDir$/dump_gpu_xor"
    printValues = true
]

and the data file (50 lines)

|i 0.000000 1.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 1.000000 1.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 0.000000 1.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 1.000000 |o 0.000000
|i 0.000000 0.000000 |o 0.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 1.000000 1.000000 |o 0.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 1.000000 |o 0.000000
|i 0.000000 1.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 1.000000 0.000000 |o 1.000000
|i 1.000000 1.000000 |o 0.000000
|i 1.000000 1.000000 |o 0.000000
|i 0.000000 0.000000 |o 0.000000
|i 0.000000 0.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 1.000000 1.000000 |o 0.000000
|i 1.000000 0.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000
|i 0.000000 1.000000 |o 1.000000

**Comment by mfuntowicz** [comment]
Hi avader906,

It's seems very related to something @zhouwangzw fixed in the commit b019f33e1597afdc62d2dab6af1de75693b48064

**Comment by avader906** [comment]
b019f33 is included in the 2.0 beta branch (just released). I will test the binary to confirm. In 1.7.2 i can only get the SquareError loss function to work when labels are 1dim binary {0,1} or continious (0,1) - logistic and ce - i get dump either in test/eval or directly in training.
