### ISSUE TITLE
BatchNormalization Implementation with Matlab

### ISSUE THREAD

**Issue by Martlgap** [Microsoft/CNTK#937]
Hi guys, 

I am currently working on a super-resolution problem with CNTK. I modified the source code of CNTK's Image Reader (Branch: Master from around June) , to be able to read images as labels. 

I created a Matlab Script, which does the same as CNTKs "write" action. In my case the network structure is just a few convolutional layers. I use the DumpNodeFile to get the learned parameters for the convolutions in Matlab. 

I managed to get exactly the same outputs in Matlab as I got from "write" in CNTK. 

Now I would like to implement BatchNormalization in the Matlab Script. So in the CNTK config I added a BatchNormalization between two convolutions. I ended up using the formular from the documentation: 

`m = mean (input)
var = variance (input)`

`inputNorm = (input - mean)/sqrt (epsilon + var)
output = gamma * inputNorm + beta`

I used the learned runningMean for m and the learned runningVariance as var in my Matlab Code.

But this gave me not the same results. I figured in the source code, that "var" is actually divided by the minibatchSize and the product of dimensions of the input image. So I modified the line in Matlab and divide the runningVariance by the number of pixels of the image which is input for BatchNormalization and divide it by the MiniBatchSize I used for Training. But unfortunately that doesn´t give me better results either. My Matlab output is still different from the CNTK output. I tested my Matlab Implementation with different network structures and different image dimensions to be sure it works for all possible configuration. So I think the problem with BatchNormalization must be inside the BatchNormalization formular I use.

Does anybody has a more detailed documentation of the BatchNormalization implementation in CNTK? Or can tell me what additional steps I have to perform, to get the same results with Matlab?
I suggest it is just another division or multiplication of parameters. But I don´t know what could be the solution. 

Thanks, 
Martin

**Comment by n17s** [comment]
I believe at some point CNTK  storing the inverse of the variance in the batchNormalization node. Try multiplying by sqrt(x) where x is  what you thought the variance is. Not sure if it will work though.

**Comment by Martlgap** [comment]
Thanks for reply. Unfortunately not working in my case. For me the solution was to create a pre and post processing tool in Matlab, which extract patches with a specific size (dependent on the training image size), put them as input for CNTKs Write Action and then composes the output patches together to get the image in original dimensions. That seems to be the easier way for me, I don´t need to struggle with Implementations in CNTK anymore and can use Image with any dimensions in the Write Function. :)
