### ISSUE TITLE
augmentationextent expection

### ISSUE THREAD

**Issue by lahiruts** [Microsoft/CNTK#94]
Hi,
Can anyone tell me some information about this error? I am using Kaldi2Reader.
EXCEPTION occurred: augmentationextent: model vector size not multiple of input features

Thanks,
Lahiru

**Comment by frankseide** [comment]
The reader can automatically argument neighbor frames. You tell it to do so by specifying a feature dimension that is a multiple of the actual feature dimension found in the data file. E.g. if you use 40 features, specifying the dimension as 840 tells the reader to augment 10 frames on each side (total window of 21 frames i.e. 84 total values).

Sent from Outlook<http://aka.ms/Ox5hz3>




On Fri, Feb 5, 2016 at 7:09 PM -0800, "lahiruts" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Can anyone tell me some information about this error? I am using Kaldi2Reader.
EXCEPTION occurred: augmentationextent: model vector size not multiple of input features

Thanks,
Lahiru

-

**Comment by frankseide** [comment]
Typo: total 840 values of course.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Fri, Feb 5, 2016 at 11:27 PM -0800, "Frank Seide" <fseide@microsoft.com<mailto:fseide@microsoft.com>> wrote:

The reader can automatically argument neighbor frames. You tell it to do so by specifying a feature dimension that is a multiple of the actual feature dimension found in the data file. E.g. if you use 40 features, specifying the dimension as 840 tells the reader to augment 10 frames on each side (total window of 21 frames i.e. 84 total values).

Sent from Outlook<http://aka.ms/Ox5hz3>




On Fri, Feb 5, 2016 at 7:09 PM -0800, "lahiruts" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Can anyone tell me some information about this error? I am using Kaldi2Reader.
EXCEPTION occurred: augmentationextent: model vector size not multiple of input features

Thanks,
Lahiru

-

**Comment by wolfma61** [comment]
@lahiruts: 
I assume this has been solved with Frank's reply. 
If you did run into further problems, please open a new issue 

thx
Wolfgang
