### ISSUE TITLE
Out of box make on Ubuntu 16 unsigned int vs CNTK::DataType

### ISSUE THREAD

**Issue by gbolcer** [Microsoft/CNTK#940]
greg@salt:~/git/cntk$ uname -a
Linux salt 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

greg@salt:~/git/cntk$ git branch
* master

greg@salt:~/git/cntk$ ./configure --with-openblas
Defaulting to --with-buildtype=release
Found OpenCV at /usr
Found libzip at /usr
Cannot locate Kaldi files
Kaldi2Reader will NOT be built.
Found Boost at /usr
Found Protocol Buffers at /usr/local/protobuf-3.1.0
Generating /home/greg/git/cntk/Config.make
run
>make -j $(nproc) all
to build

Source/CNTKv2LibraryDll/Function.cpp: In static member function ‘static CNTK::FunctionPtr CNTK::Function::LoadModel(CNTK::DataType, const wstring&, const CNTK::DeviceDescriptor&)’:
Source/CNTKv2LibraryDll/Function.cpp:216:87: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘CNTK::DataType’ [-Werror=format=]
                                 restoredFunction->Outputs()[0].GetDataType(), dataType);
                                                                                       ^
Source/CNTKv2LibraryDll/Function.cpp:216:87: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘CNTK::DataType’ [-Werror=format=]
Source/CNTKv2LibraryDll/Function.cpp: In static member function ‘static CNTK::FunctionPtr CNTK::PrimitiveFunction::Deserialize(const CNTK::Dictionary&, const std::unordered_map<std::__cxx11::basic_string<wchar_t>, CNTK::Variable>&, const CNTK::DeviceDescriptor&)’:
Source/CNTKv2LibraryDll/Function.cpp:1053:130: error: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘CNTK::PrimitiveOpType’ [-Werror=format=]
                         "(%s).", opKey.c_str(), op, GetVersionsString<PrimitiveFunction>(s_serializationVersion, version).c_str());
                                                                                                                                  ^

**Comment by mfuntowicz** [comment]
I get exactly the same error.

I'm running Ubuntu 16.10, trying to compile with CUDA 8 (and updated cudnn) but it's seems to not be related to cuda here.

**Comment by mfuntowicz** [comment]
I was able to compile CNTK on Ubuntu 16.10, by wrapping casting to the underlying typ. 
For example: 

Variable.cpp::331 => 
`static_cast<std::underlying_type<DataType>::type>(dataType)`

**Comment by gbolcer** [comment]
Thanks, will give it a try.  So, probably just an implicit type conversion diff across platforms then.

**Comment by zhouwangzw** [comment]
@gbolcer What gcc version are you using? The CNTK currently is complied with gcc 4.8.4.

**Comment by gbolcer** [comment]
I was going to try with the flags: -D_FORCE_INLINES

greg@salt:~/git$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
greg@salt:~/git$

**Comment by raaaar** [comment]
Fixed by 3b12541.
