### ISSUE TITLE
Cuda 8.0 support

### ISSUE THREAD

**Issue by Mikoor** [Microsoft/CNTK#943]
Hi guys,

I am very happy that you announced V 2.0 Beta 1 Release. However I am not sure if it supports CUDA 8.0 already. Browsing setup instructions I found following lines, which means it still refers CUDA 7.5 binaries.

setx      CUDA_PATH "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\ **_v7.5_**
setx      CUDA_PATH_V7_5 "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5"

As far as I know CUDA 8.0 is production release (not RC) 

When do you think, you can release full CUDA 8.0 support. We use multiple GTX 1080 gpus and we need to make sure its fully supported by CNTK (Cognitive Toolkit). #747 

Thanks for any info.

Best regards,
Miro

**Comment by wolfma61** [comment]
you can compile with CUDA8 already. 
It will be default in one of the next refreshes

**Comment by wolfma61** [comment]
One more note, please make sure you also updated the cudnn version also ...

**Comment by tuzzer** [comment]
Do you mind showing me how to compile CNTK from source with CUDA 8?

I am using Ubuntu 16.04.
