### ISSUE TITLE
Reinforcement learning example

### ISSUE THREAD

**Issue by WG-** [Microsoft/CNTK#944]
Question, I read that CNTK now supports reinforcement learning. I dove into the documentation and examples but cannot find anything about this. Can somebody point me to the correct documentation/examples and if that is not yet available point me to the header files which defines it? In addition, if there is no documentation/examples yet, is it planned to create this?

**Comment by sayanpa** [comment]
Hi WG,
Thanks for your interest. We are working in putting together a tutorial for reinforcement learning. This should be available in next week or two.
Thanks,
Sayan

**Comment by sayanpa** [comment]
Please checkout our beta2.0. We released a tutorial in Jupyter notebooks. You can find it under bindings/Python/tutorials in Github.
