### ISSUE TITLE
Always installs to system partition (c: drive)

### ISSUE THREAD

**Issue by MikeWise2718** [Microsoft/CNTK#946]
I like to keep my system partition (usually the c: drive) as clean as possible ,as it makes it easier to reinstall windows when I need to. It also makes backups easier. However I ran the new powershell install scripts today after unzipping into the d: partition, and they created several new directories (c:\repos and c:\local) in the root of c:. 

This is kind of annoying - if not exactly a bug. Can we make this an option?

**Comment by wolfma61** [comment]
sure, sounds reasonable to make them into parameters
I will look into this for one of the refreshes. The location of the AnacondaInstall can already be configured with the option 
  [parameter(Mandatory=$false)]
  [string] $AnacondaBasePath = "C:\local\Anaconda3-4.1.1-Windows-x86_64",

**Comment by MikeWise2718** [comment]
Great. Thanks for the quick response.

It is also missing uninstall guidance (I think). A simple list of what it did would enable a confident manual uninstall. Shall I enter that as a separate issue?

**Comment by wolfma61** [comment]
the only 'permanent changes' are installation of the VC runtimes (which I would assume is existing on most machines) and the MSMPI bits. The rest is contained in the CNTK directory and in the Python environment ... but you are probably right. I will add more information about this...
