### ISSUE TITLE
install.ps1 -execute is giving error (Cannot index into a null array)

### ISSUE THREAD

**Issue by abbas-zaidi** [Microsoft/CNTK#947]
Exception caught - function main / failure - End time [10/26/2016 16:33:02]
System.Management.Automation.RuntimeException: Cannot index into a null array.
   at System.Management.Automation.ArrayReferenceNode.GetValue(Object target, Object index, ExecutionContext context)
   at System.Management.Automation.ArrayReferenceNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, ExecutionContext contex
t)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputP
ipe, ArrayList& resultList, ExecutionContext context)

**Comment by wolfma61** [comment]
can you give us some more information?

at what point did this exception occure in the script? 

can you try to run ..\install.ps1 -verbose and post the output ?

**Comment by abbas-zaidi** [comment]
VERBOSE: Calling Operation: [VerifyRegistryKeyNameData]: []
VERBOSE:
Name                           Value

----                           -----

RegData                        1

Function                       VerifyRegistryKeyNameData

Key
Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\11.0\VC\Runt...
RegName                        Installed



VERBOSE: [VerifyRegistryKeyNameData]:
[Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\11.0\VC\Runtimes\x64]:[Installed] == [1]
returned [True]
VERBOSE: Calling Operation: [VerifyRegistryKeyNameData]: []
VERBOSE:
Name                           Value

----                           -----

RegData                        1

Function                       VerifyRegistryKeyNameData

Key
Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\12.0\VC\Runt...
RegName                        Installed



VERBOSE: [VerifyRegistryKeyNameData]:
[Registry::HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\12.0\VC\Runtimes\x64]:[Installed] == [1]
returned [True]
VERBOSE: Calling Operation: [VerifyRegistryKeyName]: []
VERBOSE:
Name                           Value

----                           -----

Function                       VerifyRegistryKeyName

Key                            Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MPI

RegName                        Version



VERBOSE: [VerifyRegistryKeyName]: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MPI]:[Version] returned [False]
VERBOSE: Calling Operation: [VerifyDirectory]: []
VERBOSE:
Name                           Value

----                           -----

Path                           C:\local\Anaconda3-4.1.1-Windows-x86_64

Function                       VerifyDirectory



VERBOSE: [VerifyDirectory]: [C:\local\Anaconda3-4.1.1-Windows-x86_64] returned [False]
VERBOSE: Calling Operation: [VerifyDirectory]: []
VERBOSE:
Name                           Value

----                           -----

Path                           C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34

Function                       VerifyDirectory



VERBOSE: [VerifyDirectory]: [C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34] returned [False]
VERBOSE: Calling Operation: [VerifyWheelDirectory]: []
VERBOSE:
Name                           Value

----                           -----

Function                       VerifyWheelDirectory

WheelDirectory                 C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\Lib\site-packages\cntk

ForceUpdate                    False



VERBOSE: [VerifyWheelDirectory]: [C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\Lib\site-packages\cntk]
returned [False]
VERBOSE: Calling Operation: [VerifyFile]: []
VERBOSE:
Name                           Value

----                           -----

Path                           C:\Abbas\CNTK\cntk\scripts\cntkpy34.bat

Function                       VerifyFile



VERBOSE: [VerifyFile]: [C:\Abbas\CNTK\cntk\scripts\cntkpy34.bat] returned [False]
VERBOSE: Calling Operation: [VerifyRegistryKeyName]: []
VERBOSE:
Name                           Value

----                           -----

Function                       VerifyRegistryKeyName

Key                            Registry::HKEY_LOCAL_MACHINE\SOFTWARE\GitForWindows

RegName                        CurrentVersion



VERBOSE: [VerifyRegistryKeyName]: [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\GitForWindows]:[CurrentVersion] returned
[False]
VERBOSE: Calling Operation: [VerifyDirectory]: []
VERBOSE:
Name                           Value

----                           -----

Path                           c:\repos\cntk

Function                       VerifyDirectory



VERBOSE: [VerifyDirectory]: [c:\repos\cntk] returned [False]

**Comment by wolfma61** [comment]
looks like the output got cut off ... can you attach a file, or the later line of the ouput?
what version of windows, what version of powershell?

**Comment by abbas-zaidi** [comment]
Windows version is Windows 7 Enterprise (Service Pack 1) and version of powershell is what comes in Windows 7 by default probably v1.0. PFA the full output from verbose. I did some debugging and the exception is occuring at the following line in _download.ps1 script in function _DownloadItem_:

`$func = $item["Function"]`

the reason is there are no `$downloadItem in $item.Download` in the function _DownloadOperations_. When i printed the `($item).Keys`, i get the below result:
_Action Name Info ShortName Verification_

PFA the full verbose output. 
[verbose_output.txt](https://github.com/Microsoft/CNTK/files/554960/verbose_output.txt)

**Comment by wolfma61** [comment]
Thank you for investigating this.
On Windows 7 you might want to update your Powershell version. There have been changes inside Powershell in handling of arrays (of arrays) etc, and it looks like this is what is effecting you here. For a powershell upgrade try these links:
https://www.microsoft.com/en-us/download/details.aspx?id=50395 
https://www.microsoft.com/de-de/download/details.aspx?id=40855 

A word of caution: We are not testing Windows7 for CNTK. I don't think there is anything preventing Win7 execution in the core of CNTK, but again, this isn't tested ...

Sorry about the trouble, but I hope this gets you going ...

thx
Wolfgang
