### ISSUE TITLE
Issue with protobuf using Docker GPU Image

### ISSUE THREAD

**Issue by rahul-anand** [Microsoft/CNTK#949]
There should be installation code for installing protobuf in Docker file for GPU.

Currently installation is failing at ./configure for installing CNTK via Docker

**Comment by mahilleb-msft** [comment]
Hi @rahul-anand, thanks for reporting this. A fix is available and will soon be merged to master (probably tomorrow).

Best, Mark

**Comment by honnibal** [comment]
Fix works for me, thanks.
