### ISSUE TITLE
Binaries for CPU-only machine don't work

### ISSUE THREAD

**Issue by CBrauer** [Microsoft/CNTK#95]
Hey  Guys,

The binaries download assumes I want to run the GPU version. I don't.

The download For CPU-only machine shows: "CNTK-20160126-Windows-64bit-ACML5.3.1-CUDA7.0.zip",
and when I run: "cntk configFile=../Config/Simple.config" from the "Simple2d\Data" directory I get:

"The program can't start because cublas64_70 is missing from your computer.

I just wanted to run a demo program to see if it works.  No cigar!

Charles

**Comment by frankseide** [comment]
Hi, thanks! We have gotten this feedback a few times. This is supposed to work (by delay-loading those CUDA DLLs and falling back to CPU only when delay-loading fails). I opened Issue #76 to track it. I hope it's OK for you if I close this Issue in reference to that other one.

Thanks!

Frank
