### ISSUE TITLE
Error in .\install.ps1 -execute 

### ISSUE THREAD

**Issue by jykim** [Microsoft/CNTK#951]
I'm getting this error in both my desktop and laptop (Surface Book)

Any guess?

---
This script will setup the CNTK prequisites and the CNTK Python environment onto the machine.
More help is given by calling get-help .\installer.ps1

The script will analyse your machine and will determine which components are required.
The required components will be downloaded in [C:\Install\cntk\Scripts\windows\InstallCache]
Repeated operation of this script will reuse already downloaded components.

- If required VS2012 Runtime and VS2013 Runtime will be installed
- If required MSMPI will be installed
- If required the Git-tool will be installed
- CNTK source will be downloaded in [c:\repos\cntk]
- Anaconda3 will be installed into [C:\local\Anaconda3-4.1.1-Windows-x86_64]
- A CNTK-PY34 environment will be created in [C:\local\Anaconda3-4.1.1-Windows-x86_64\envs]

1 - I agree and want to contiue
Q - Quit the installation process

1
Determining Operations to perform

The following operations will be performed:
 * Install MSMPI
 * Install Anaconda3-4.1.10
 * Setup CNTK PythonEnvironment 3.4
 * Setup CNTK Wheel
 * Create CNTKPY34 batch file
 * Clone CNTK from Github repository

Do you want to continue? (y/n)
y
Performing download operations
Downloading [https://repo.continuum.io/archive/Anaconda3-4.1.1-Windows-x86_64.exe], please be patient....
End binary download!
Download operations finished

Performing install operations
Installing MSMPI ....
Installing Anaconda3-4.1.1. This will take several minutes. Please be patient ....
Setting up CNTK-PY34 environment. Please be patient....
Setting up CNTK Wheel environment. Please be patient....
Cloning CNTK (branch v2.0.beta1.0) repository....
Exception caught - function main / failure - End time [10/26/2016 09:09:20]
System.InvalidOperationException: This command cannot be run due to the error: The operation was canceled by the user.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
PS C:\Install\cntk\Scripts\windows>

**Comment by mahilleb-msft** [comment]
Hey, thanks for reporting this. Could it be that you accidentally closed a window when the script was trying to clone the CNTK Git repository? The message say "operation was canceled by the user". Right now, the git clone would go to c:\repos\cntk, you might want to remove that path, if's already partially checked out and try to rerun.

**Comment by jykim** [comment]
Thanks, I reran the install and it seems to complete this time.

Now, when I try to run the first example, I get the following error.

Any guess? I'm not sure if it's the installation issue, or just clashing with my existing Python (Anaconda) installation...

p.s I did run the following command before trying it
C:\local\cntk\scripts\cntkpy34.bat

----
PS C:\repos\CNTK\bindings\python\examples> python NumpyInterop\FeedForwardNet.py
Traceback (most recent call last):
  File "NumpyInterop\FeedForwardNet.py", line 10, in <module>
    from cntk.device import cpu, set_default_device
ImportError: No module named 'cntk'

**Comment by jykim** [comment]
I created a new issue on this.

https://github.com/Microsoft/CNTK/issues/954
