### ISSUE TITLE
Missing str.format() call in CNTK_103B Python binding tutorial notebook

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/CNTK#953]
If you look at the [CNTK_103B notebook](https://github.com/Microsoft/CNTK/blob/master/bindings/python/tutorials/CNTK_103B_MNIST_FeedForwardNetwork.ipynb) in the `Evaluation / Testing` section you will notice that their is a call to `print()` that's missing a call to `str.format()`:
```python3
print("Test data from file {0} successfully read", path)
```
should be:
```python3
print("Test data from file {0} successfully read".format(path))
```

**Comment by mahilleb-msft** [comment]
Thanks for reporting. Will integrate the suggested change soon!

Best, Mark
