### ISSUE TITLE
Error training on own dataset

### ISSUE THREAD

**Issue by AndreaPisoni** [Microsoft/CNTK#957]
Get this error after creating the ROIs:

```File "A1_GenerateInputROIs.py", line 121, in <module>
    boxesStr += getCntkRoiCoordsLine(rect, cntk_padWidth, cntk_padHeight)
  File "C:\local\cntk\Examples\Image\Detection\FastRCNN\cntk_helpers.py", line 165, in getCntkRoiCoordsLine
    assert xrel <= 1.0, "Error: xrel should be <= 1 but is " + str(xrel)
AssertionError: Error: xrel should be <= 1 but is 25.402```

**Comment by AndreaPisoni** [comment]
I found this is due to creating own bounding boxes and having said boxes go out of the picture.

**Comment by jaypaddy** [comment]
I too ran into a similar issue. 
"AssertionError: Error: xrel should be <= 1 but is 16.377"
Appreciate guidance.

**Comment by leangdamang** [comment]
Hi I'm having the same issue - is there any resolution to this? I used VoTT to create the bounding boxes.
