### ISSUE TITLE
why excute cntk.exe(2.0) no response?

### ISSUE THREAD

**Issue by cxf2015** [Microsoft/CNTK#958]
why excute cntk.exe(2.0) no response?

**Comment by mahilleb-msft** [comment]
Hi @cxf2015,
which download did you use?
Did you follow the instructions here: https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration or did install in other ways? (if so how).

Thanks, Mark

**Comment by cxf2015** [comment]
@mahilleb-msft 
in my dos command line i input CNTK.exe long time pass but no response, why?

**Comment by raaaar** [comment]
See #959. Closing this as a duplicate.
