### ISSUE TITLE
Empty console. Command prompt freezes

### ISSUE THREAD

**Issue by andreyiva111** [Microsoft/CNTK#959]
Hy.
I built (releas, x64) cntk solution and try to run its. At the command prompt i go to example Simple2D/Data (cd c:\src\cntk\example\other\simple2d\data) After i run cntk.exe with cntk configFile=../Config/Simple.cntk (\src\cntk\x64\release\cntk.exe configfile=../Config/Simple.cntk)
BUT command prompt freezes. Nothing happens. 
(When I tried CNTK Binary, after run cntk.exe go information about config  file, about training network, ...)
Pleas, help me.

**Comment by andreyiva111** [comment]
![freez](https://cloud.githubusercontent.com/assets/22227545/19765614/fa488a98-9c51-11e6-9acf-540de8748277.png)

**Comment by mahilleb-msft** [comment]
Hey @andreyiva111, sorry that it doesn't work. Right now our recommended Windows version would be Windows 8.1 upwards, cf. https://github.com/Microsoft/CNTK/wiki/Test-Configurations.

Are you using an NVidia GPU (which one)? If not, you can try to build Release_CpuOnly (no CUDA / GPU dependencies at all), CNTK.exe will then be in the x64\Release_CpuOnly folder.

Best, Mark

**Comment by andreyiva111** [comment]
Thank you for answer, mahilleb-msft.
 I'm sorry, it's my fault, I did not see the description of the configurations.
Now i have windows 7.

Yes, i using NVidia GPU (gigbyte geforce gtx 780)

I tryed build Release_CpuOnly, but I have the same error. Command prompt freezes.

Me need update for windows 10?

**Comment by raaaar** [comment]
CNTK v2 deadlocks on Win 7. I've seen this before and will try to get it fixed. Meanwhile, if you want to work around this, please comment out lines 903 and 909 containing locks in CNTKLibrary.h (https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L903, https://github.com/Microsoft/CNTK/blob/master/Source/CNTKv2LibraryDll/API/CNTKLibrary.h#L909) and recompile.

**Comment by andreyiva111** [comment]
Thenk you very match, raaaar. It is work for me. I commented this lines and rebuilt cntk sol. Now all work!

But i have one more question from this forum topic https://github.com/Microsoft/CNTK/issues/965
I update Power shell, how mahilleb-msft say me. And cntk binary downloaded with out errors! But when i am trying runig learnig console freeze. Mb and for this proble do you have solution?

Again Thenk You very match!

**Comment by raaaar** [comment]
Same reason, binary is built with the code that leads to a deadlock. A fix will be published in the next binary release.

**Comment by andreyiva111** [comment]
Ok, thank you so much!
