### ISSUE TITLE
16bit PNG Images for ImageReader

### ISSUE THREAD

**Issue by Martlgap** [Microsoft/CNTK#961]
Hey guys, 
is there an option to get 16bit .png Images into CNTK with the ImageReader?
I figured out, that when I give a 16bit png image into the reader, it is interpreted as constant zero values for every pixel. In my case the 16bit png has pixel values of 255. 

Any Idea on how this could work? What do I need to configure? 

Best regards, 
Martin

**Comment by eldakms** [comment]
Could you please post your config (and sample data if possible)?

Thanks!

**Comment by cha-zhang** [comment]
CNTK ImageReader use OpenCV to load the images. Have you tried loading your images directly with OpenCV?

**Comment by Martlgap** [comment]
Here is my Train Section: 

> Train1=[
    action="train"
    modelPath="$ModelDir$/PaperNetwork_V3"
	BrainScriptNetworkBuilder = [
        include "$configDir$/macros_V1.bs"
        include "$configDir$/PaperNetwork_V1.bs"
    ]
    SGD = [
        epochSize = 5000 #0
        minibatchSize = 512
		learningRatesPerSample = 0.001
        #learningRatesPerMB = 0.0001
        momentumPerMB = 0.9
        maxEpochs = 5
	]
    reader=[
        readerType=ImageReader
        file=$DataDir$\02_Train\labels.txt
        randomize = "auto"
		grayscale = true
		verbosity = 2
        features=[
            # Below are the required parameters.
            width=33
            height=33
            channels=1
        ]
        labels=[
			labeldim = 0
            labelwidth=21
            labelheight=21
            labelchannels=1
        ]
    ]    
] >

and my Write Section: 
> Write1=[ 
	action = "write" 
	modelPath="$ModelDir$/PaperNetwork_V3"
	epochSize = 1
	minibatchSize = 1
	# Parameter values for the reader 
	reader=[
        readerType=ImageReader
        file=$DataDir$\04_Test\labels.txt
        randomize = "none"
		grayscale = true
        features=[
            # Below are the required parameters.
            width=33
            height=33
            channels=1
        ]
		labels=[
			labeldim = 0
            labelwidth=21
            labelheight=21
            labelchannels=1
        ]
	]    
	outputNodeNames = "ol.out:out1.out:out2.out:labelScaled:featScaled" # 
	# Select the nodes to print. If this is not given, the nodes tagged as "output" are printed instead. 
	outputPath = "$OutputDir$/Output" # Path to write to.
]

This is preSection: 

> precision="float"
deviceId="Auto"
labelType="image"
parallelTrain="false"
numCPUThreads = 1
command=Train1:DumpNodeInfo1:Write1 #CrossValidation1:
#stderr="$OutputDir$/stdReport"
traceLevel=2
firstMBsToShowResult = 10
#numMBsToShowResult=10

The BrainScript File: 

> imageW = 33
imageH = 33
imageC = 1
labelW = 21
labelH = 21
labelC = 1
features = ImageInput(imageW, imageH, imageC, imageLayout="cudnn")
labels = ImageInput(labelW, labelH, labelC, imageLayout="cudnn")
# Normalization of Features and Labels to Values -1..1
featBiased = features - Constant(127.5)
labelBiased = labels - Constant(255.5)
featScaled = Constant(1/127.5) .* featBiased
labelScaled = Constant(1/255.5) .* labelBiased
# Convolution1 Shrinking Size of Image with Stride: 1
kW1 = 9
kH1 = 9
kC1 = 1
outMap1 = 256
inWCount1 = kW1*kH1*kC1
hStride1 = 1
vStride1 = 1
out1 = Conv1(featScaled, outMap1, inWCount1, kW1, kH1, kC1, hStride1, vStride1)
# Convolution2 Shrinking Size of Image with Stride: 1
kW2 = 1
kH2 = 1
kC2 = 256
outMap2 = 128
inWCount2 = kW2*kH2*kC2
hStride2 = 1
vStride2 = 1
out2 = Conv2(out1, outMap2, inWCount2, kW2, kH2, kC2, hStride2, vStride2)
# Convolution3 Shrinking Size of Image with Stride: 1
kW3 = 5
kH3 = 5
kC3 = 128
outMap3 = 1
inWCount3= kW3*kH3*kC3
hStride3 = 1
vStride3 = 1
ol = Conv3(out2, outMap3, inWCount3, kW3, kH3, kC3, hStride3, vStride3
mse = SquareError(labelScaled, ol) * Constant(1/labelW/labelH)
# Special Nodes
featureNodes = (features)
labelNodes = (labels)
criterionNodes = (mse)
outputNodes = (ol)

I edited the CNTK Source Code, so that I am able to read Images as Labels. That modification works perfect with 8bit png images. So It should not be dependent on that. 

Attached is a pair of Feature and Label. 
![feature_1_00000001](https://cloud.githubusercontent.com/assets/20643017/19776765/b94be700-9c75-11e6-97d0-07d4948f3c41.png)
![label_1_00000001](https://cloud.githubusercontent.com/assets/20643017/19776794/c82ffa22-9c75-11e6-8a79-2e532f5b0e95.png)

Do you need any other information?

**Comment by Martlgap** [comment]
@cha-zhang, how can I load Images directly with OpenCV?

**Comment by cha-zhang** [comment]
Can you write a simple program with OpenCV, just read your png file and exit? If OpenCV can't load your image, then the current CNTK ImageReader won't work.

**Comment by Martlgap** [comment]
Thank you, I looked into the source Code and into the doc of cv::imread(). There must be a flag set to CV_LOAD_IMAGE_ANYDEPTH to be able to read more than 8bit depth. I ll modify my Source Code and check if that solves the problem. Will report that tomorrow.

**Comment by Martlgap** [comment]
I modified the source Code that it is able to read 16bit png by adding the flag cv::IMREAD_ANYDEPTH to the function. 
This works now perfect. (I ll close the topic hereby) Thank you for your help! 
Cheers

**Comment by n17s** [comment]
Would you be interested in sending us a patch/pull request?

**Comment by Martlgap** [comment]
Yes, at the moment I am quite busy, but I ll send you a patch. I ll take the recent CNTK Version and update the code, a UnitTest is enough? Or do you require end-to-end tests additionally?

**Comment by eldakms** [comment]
Unit tests are sufficient. Thanks!

**Comment by fcivardi** [comment]
@Martlgap : Hi, I'm working with 16bit png images as well. Did you fix the code on Github? If not, where and how should I modify it? 
Thanks, Francesco

**Comment by Martlgap** [comment]
Hey @fcivardi , 
sorry for late response. 

I modified this line (300) in Source/Readers/ImageReader/ImageDataDeserializer.cpp
`return cv::imread(path, grayscale ? cv::IMREAD_GRAYSCALE : cv::IMREAD_COLOR);`
into:
`return cv::imread(path, grayscale ? cv::IMREAD_GRAYSCALE | cv::IMREAD_ANYDEPTH : cv::IMREAD_COLOR | cv::IMREAD_ANYDEPTH);`

and also for the zipbytereader: 

`cv::Mat img = cv::imdecode(contents, grayscale ? cv::IMREAD_GRAYSCALE : cv::IMREAD_COLOR);`
into->
`img = cv::imdecode(cv::Mat(1, (int)size, CV_8UC1, contents.data()), grayscale ? cv::IMREAD_GRAYSCALE | cv::IMREAD_ANYDEPTH : cv::IMREAD_COLOR | cv::IMREAD_ANYDEPTH);`

That should fix the problem. 

Best regards, 
Martin
