### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by cxf2015** [Microsoft/CNTK#964]
why i use vs2013 compiling CNTK2.0  show error like below? how to repare this error?

TensorView.cpp(242): error C2440: “<function-style-cast>”: 无法从“initializer-list”转换为“std::arrayMicrosoft::MSR::CNTK::TensorShape,0x02”
1>          class“std::arrayMicrosoft::MSR::CNTK::TensorShape,0x02”的构造函数声明为“explicit”
1>          TensorView.cpp(234): 编译类 模板 成员函数“void Microsoft::MSR::CNTK::TensorView<float>::DoUnaryOpOf(ElemType,const Microsoft::MSR::CNTK::TensorView<ElemType> &,ElemType,Microsoft::MSR::CNTK::ElementWiseOperator,Microsoft::MSR::CNTK::ElementWiseOperator)”时
1>          with
1>          [
1>              ElemType=float
1>          ]
1>          e:\test\cntk\cntk2.0-src\cntk-2.0.beta1.0\source\math\TensorView.h(93): 参见对正在编译的函数 模板 实例化“void Microsoft::MSR::CNTK::TensorView<float>::DoUnaryOpOf(ElemType,const Microsoft::MSR::CNTK::TensorView<ElemType> &,ElemType,Microsoft::MSR::CNTK::ElementWiseOperator,Microsoft::MSR::CNTK::ElementWiseOperator)”的引用
1>          with
1>          [
1>              ElemType=float
1>          ]
1>          TensorView.cpp(391): 参见对正在编译的类 模板 实例化“Microsoft::MSR::CNTK::TensorView<float>”的引用

**Comment by cha-zhang** [comment]
Are you using VS2013 update 5?

**Comment by cxf2015** [comment]
microsoft visual sdudio ultimate 2013

**Comment by cxf2015** [comment]
microsoft visual sdudio ultimate 2013  版本12.0.21005.1REL



发自网易邮箱大师
On 10/28/2016 12:06, Cha Zhang wrote:

Are you using VS2013 update 5?

**Comment by alexeyo26** [comment]
Seems like you do NOT have Update 5 installed. Please, get it at https://www.microsoft.com/en-us/download/details.aspx?id=48129

**Comment by cxf2015** [comment]
thank you! and i will try ^V^

2016-10-28 

cxfmail 



发件人：Alexey Orlov <notifications@github.com>
发送时间：2016-10-28 13:16
主题：Re: [Microsoft/CNTK] who can help me? (#964)
收件人："Microsoft/CNTK"<CNTK@noreply.github.com>
抄送："cxf2015"<cxfmail@126.com>,"Author"<author@noreply.github.com>

Seems like you do NOT have Update 5 installed. Please, get it at https://www.microsoft.com/en-us/download/details.aspx?id=48129
