### ISSUE TITLE
Not install binary gpu

### ISSUE THREAD

**Issue by andreyiva111** [Microsoft/CNTK#965]
I followed all the instructions of this page https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Configuration
But i have error -> System.Management.Automation.RuntimeException: Method invocation failed because [System.Management.Automation.JobState] doesn't contain a method named 'ToUpper'.

![help_2](https://cloud.githubusercontent.com/assets/22227545/19796071/55567d30-9cea-11e6-815f-eabe5e09bd07.png)

![help_3](https://cloud.githubusercontent.com/assets/22227545/19796075/59cdf15e-9cea-11e6-9ca8-2b9671673e2d.png)

![help_4](https://cloud.githubusercontent.com/assets/22227545/19796079/5db829a6-9cea-11e6-8ad7-91be4af77fd2.png)

**Comment by mahilleb-msft** [comment]
Hey,
  it seems like your on an older Powershell version (v2?) which we unfortunately don't support. (Also, which OS are you on?).

  Would updating to PSv4 or PSv5 be an option for you? Those would be compatible for running the script.
https://www.microsoft.com/en-us/download/details.aspx?id=40855  - Windows Management Framework 4.0
https://www.microsoft.com/en-us/download/details.aspx?id=50395 - Windows Management Framework 5.0

  Sorry for the inconvenience,

  Mark

**Comment by andreyiva111** [comment]
Thank you for answer, mahilleb-msft.
I'm sorry, it's my fault, I did not see the description of the configurations.
Now i have windows 7.

very sad. now me need update for Windows 10?

**Comment by wolfma61** [comment]
Hi -
we don't test or support CNTK on Windows 7. The mentioned Powershell upgrade to version4 or version5 will probably let you install CNTK, but you might see other issues on Windows7. Again, we haven't tested on that platform. The update to Windows10 is what I would recommend here. 
thx
Wolfgang
