### ISSUE TITLE
fatal error LNK1104: cannot open file CNTKLibrary-2.0.lib

### ISSUE THREAD

**Issue by brendahuo** [Microsoft/CNTK#967]
Hi,

I am having this error while trying to build CNTK (CPU only) solution on windows. The complete output is attached here. Could anyone help advise how I could fix this? Thanks a lot in advance.

[errorlog.txt](https://github.com/Microsoft/CNTK/files/558160/errorlog.txt)

**Comment by raaaar** [comment]
This was in your output: 

21>C:\src\cntk\Source\CNTKv2LibraryDll\CNTKv2LibraryDll.vcxproj(195,5): warning : CNTKv2LibraryDll requires Protocol Buffers to build. Please see https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows#protobuf for installation instructions.

**Comment by brendahuo** [comment]
Thanks a lot @raaaar . Indeed there was an error I did not notice while building protobuf. Works perfectly now.

**Comment by brendahuo** [comment]
Actually though the "debug" build ran successfully, I encountered this error while running "release" build. From my understanding it has to do with protobuf too but I could not figure out how to fix it, and why it only happens in "release". Could anyone advise? Thanks!

> libprotobuf.lib(descriptor.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in BackCompat.obj

**Comment by raaaar** [comment]
'MT_StaticRelease' means that the -Dprotobuf_MSVC_STATIC_RUNTIME=OFF was not specified when building the protobuf lib. Please remove "release" folder ("nmake clean" works as well) and rebuild the Release version of the library.

**Comment by brendahuo** [comment]
Thank you very much again @raaaar , sorry I guess I missed the line. It works great now in release too.
