### ISSUE TITLE
Speech/Miscellaneous/TIMIT/config/README.txt

### ISSUE THREAD

**Issue by arijit17** [Microsoft/CNTK#968]
Hi!

If I want to try the example given in the readme.txt:
https://github.com/Microsoft/CNTK/blob/master/Examples/Speech/Miscellaneous/TIMIT/config/README.txt

I understand I should modify globals.cntk, and I change WorkDir to, e.g. C:\src\cntk\Examples\Speech\Miscellaneous\TIMIT\
What should ExpDir be?

In the readme.txt, I don't understand what is meant by:
"all SCP files (lists of files) in "lib/scp" to point to your feature files".
Where are the feature files? How can I get them?

Best Regards,
Arijit

**Comment by jingyonghou** [comment]
I think you should take some time to learn how to extract feature using HTK's HCopy tool, so you could understand the sentence meaning.

**Comment by arijit17** [comment]
Thanks for your suggestion. 
I'm not a speech recognition researcher. But I only wish to play with these example codes. Is there any quick tutorial that would allow me to get started quickly with these examples?

**Comment by junjieqian** [comment]
There are two tutorials: 1. in Example/ ; 2. in bindings/python/. You may find more useful information in Wiki/How do I ... section.
