### ISSUE TITLE
Datasets with incomplete data?

### ISSUE THREAD

**Issue by dathbe** [Microsoft/CNTK#975]
One of the data sets I'd like to use has 89 features, but some data points are missing information.  For example, a typical dataset looks like:
`.5 0 2.38 -1 .8 .28 .3`
But sometimes one ore more data points are unavailable:
`.5 0 2.38 -1 null .28 .3`
CNTK (unsurprisingly) won't take the data set with the "null" in there.  What's the best way to represent the missing information?  Is there a character that signifies to CNTK that the data is missing?

If I leave it blank (i.e., leave a double space), CNTK will run, but it does warn me that the data point is short one feature.  I don't know whether it is skipping the 5th feature like it should, or whether it is moving the 6th feature into the 5th spot and treating the final feature as null.  

I could, alternatively, replace "null" with an arbitrary number (e.g., 0, -1, -9999), but those numbers have real significance in the data set, and I don't want to throw off the model by doing so.

**Comment by n17s** [comment]
CNTK does not support missing values. The best thing to do is to try different strategies to deal with this for example: replace null with the average value of that feature. eplace null with the most frequent value of that feature. replace null with 0. Apart from that, it almost always helps to append an additional feature binary feature that indicates whether the value was missing or not.
