### ISSUE TITLE
Tensor with multiple types?

### ISSUE THREAD

**Issue by dhiegorp** [Microsoft/CNTK#976]
Hi! I'm trying to use a dataset that is a vector of numerical and alphanumerical features. 
I tried to use this dataset on cntk, using the CNTKTextFormatReader and I got some errors. 
Is there a way to use this or I have to transform string data to a numerical type equivalent? ParameterTensors accepts only 'float types' or other types can be used natively?

**Comment by n17s** [comment]
Yes you need to separate the numeric features from the text features. You should create separate streams in a CTF file:
|numerics 0.9 3.141 1.414 -2.718 |strings 1:1 42:1 |labels 45:1

**Comment by dhiegorp** [comment]
Thanks a lot, I'll try it!
