### ISSUE TITLE
FastRCNN with CSEvalClient?

### ISSUE THREAD

**Issue by pmfcdb** [Microsoft/CNTK#977]
Hi,

How can I  use the FastRCNN model with the CSEvalClient project? 

Thks,

**Comment by pkranen** [comment]
Please take a look at the branch [pkranen/csevalFastrcnn](https://github.com/Microsoft/CNTK/tree/pkranen/csevalFastrcnn), specifically in [Examples/Evaluation/CSEvalClient/Program.cs](https://github.com/Microsoft/CNTK/commit/7eefb18dce9a6f8bf4e020f0dde37acb403e16dd). It shows how to use Fast R-CNN from the CSEvalClient. Note that it does not yet contain the ROI generation from C# and also the image preprocessing should be done as in the ImageDeserializer, i.e. preserve aspect ration while scaling and pad the remaining pixels with 114 per channel.
