### ISSUE TITLE
CPPEvalClient Object Detection example using Fast-R-CNN

### ISSUE THREAD

**Issue by jhalakpatel** [Microsoft/CNTK#978]
Hi,

Is it possible to provide CPPEvalClient Object Detection example using F-RCNN. 
It will be great if it includes Pre-Processing stage as well.

Thanks,
Jhalak

**Comment by pkranen** [comment]
We're preparing object detection for the eval clients, can't promise pre- and post-processing at this point.

**Comment by pkranen** [comment]
Please take a look at the branch [pkranen/csevalFastrcnn](https://github.com/Microsoft/CNTK/tree/pkranen/csevalFastrcnn), specifically in [Examples/Evaluation/CSEvalClient/Program.cs](https://github.com/Microsoft/CNTK/commit/7eefb18dce9a6f8bf4e020f0dde37acb403e16dd). It shows how to use Fast R-CNN from the CSEvalClient (CPPEvalClient works similarly). Note that it does not yet contain the ROI generation from C# and also the image preprocessing should be done as in the ImageDeserializer, i.e. preserve aspect ration while scaling and pad the remaining pixels with 114 per channel.

**Comment by zhouwangzw** [comment]
Closing it. Please open a new one, if you still have the problem.

**Comment by brunovollmer** [comment]
Short Question: Did you found a way to generate the ROI's in C#?
