### ISSUE TITLE
[WinError 2] with A2_RunCntk.py using FastRCNN (python 3.4)

### ISSUE THREAD

**Issue by awscodu** [Microsoft/CNTK#980]
I'm using a custom data set with the correct ROIs etc. but it keeps returning this FileNotFoundError after a clean install of python  and its cntk libraries.

It has something to do with line 41 [pid = subprocess.Popen(cmdStr, cwd = cntkFilesDir)  ]... but i havent changed it from the example.

`2016-11-01 01:31:11
PARAMETERS: datasetName = humvee
PARAMETERS: cntk_nrRois = 2000
cntk.exe configFile=C:/cntk/Examples/Image/Detection/FastRCNN/proc/humvee_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:/cntk/Examples/Image/Detection/FastRCNN/proc/humvee_2000/cntkFiles/ NumLabels=3 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=6000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=6000
Traceback (most recent call last):
  File "C:\cntk\Examples\Image\Detection\FastRCNN\A2_RunCntk.py", line 41, in <module>
    pid = subprocess.Popen(cmdStr, cwd = cntkFilesDir)
  File "C:\Users\taylo\Anaconda3\envs\cntk\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Users\taylo\Anaconda3\envs\cntk\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

(cntk) C:\Users\taylo>`

**Comment by awscodu** [comment]
I copied the command over to my windows command prompt and ended up getting this error...
`EXCEPTION occurred: error opening file '../../../../../PretrainedModels/AlexNet.model': No such file or directory`
I added the file, changed the directory in the cntk file, but with no success and the same error.

**Comment by JackSnoop** [comment]
I'm also having this issue with just the standard supplied data set, I have tried on multiple computers with a variation in the setups, (one is cpu only, the others have been gpu and cpu), I am getting the exact same feedback from the console apart from obviously the drives being my local ones, and it being the standard "grocery" data set.
I have tried copying the command over to cmd but that didn't work for me either.
any help would be great.

**Comment by pkranen** [comment]
Do you have the folder that contains cntk.exe in your PATH? Should be <cntkroot>/x64/Release if you use a regular gpu release build from source.

**Comment by JackSnoop** [comment]
Yes, after looking through folders I can see that the .exe is there, and within the path.
from my understanding, correct me if i'm wrong, the A1 generate ROIs wouldn't work if I didn't have that in the path, whereas the cntk will run the A1 step fine every time, it is just step A2 that doesn't work and because of this A3 won't run either.

**Comment by pkranen** [comment]
cntk.exe is only required in the A2 script, the others are independent of it. In the log above you see the actual cntk.exe call with its arguments: 

```
cntk.exe configFile=C:/cntk/Examples/Image/Detection/FastRCNN/proc/humvee_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:/cntk/Examples/Image/Detection/FastRCNN/proc/humvee_2000/cntkFiles/ NumLabels=3 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=6000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=6000
```
Please try to run this separately from a standard command prompt and report the error (if any). (You'd need to copy-paste from your log of course to get the correct paths for the config etc.)

**Comment by JackSnoop** [comment]
Hi,

Tried once again from both python and cmd, python inevitably failed, but running it from cmd prompt worked this time using the cpu only build, will try with the gpu build and report back, I'm assuming must have been a user error when copying from python to cmd on the first try.

**Comment by awscodu** [comment]
JackSnoop did you install the binary or did you build the source code? I believe the solution to our problem is building the source code. The binaries mess with our PATHs.

**Comment by JackSnoop** [comment]
Hi awscodu,

I built it using the binary, I am inclined to agree with you for this specific issue, though your workaround of using cmd to run it worked both on the cpu only build and the gpu build I have done so thanks!
I will try building using my own images and see if I can fix it before running everything again.

**Comment by awscodu** [comment]
Glad to see that its working for someone else! Be careful when you config for your own file though, in the python it doesn't make it clear what data set type you should set it as and you will have to change  bunch of subsequent settings as a result.

**Comment by JackSnoop** [comment]
Hi,

So I started a fresh with the latest update (release 2 beta 5) which seems to have given me a similar issue to before where A1 will run, then when I get to A2, I hit the same issue, tried to fix with checking all the paths, everything looked correct to me, compared the paths to a previous build (release 2 beta 3) that worked and they are identical. I went through and tried using anaconda based in cmd, and just a standard cmd, with all failing in various different ways as shown below.

**Using conda prompt -** 

(cntk) C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN>python a2_RunCntk.py
--------------------------------------------------------------
2016-11-28 14:12:09
PARAMETERS: datasetName = grocery
PARAMETERS: cntk_nrRois = 2000
cntk.exe configFile=C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/ NumLabels=17 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=34000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=34000
Traceback (most recent call last):
  File "a2_RunCntk.py", line 41, in <module>
    pid = subprocess.Popen(cmdStr, cwd = cntkFilesDir)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Using anaconda within cmd -** 

(C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34) C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN>python A2_RunCntk.py
Traceback (most recent call last):
  File "A2_RunCntk.py", line 5, in <module>
    import PARAMETERS
  File "C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN\PARAMETERS.py", line 2, in <module>
    from cntk_helpers import *
  File "C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN\cntk_helpers.py", line 5, in <module>
    import selectivesearch
  File "C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN\selectivesearch\__init__.py", line 1, in <module>
    from .selectivesearch import selective_search
  File "C:\Users\asus\Documents\cntk\cntk\Examples\Image\Detection\FastRCNN\selectivesearch\selectivesearch.py", line 3, in <module>
    from past.builtins import cmp
ImportError: No module named 'past'

**Using standard cmd prompt -** 

Using cmd in Win10, it starts the process then a pop up comes up asking which program to use, told it to use python, it then fails. 
Tried this previously on Win7 and it just worked when trying it in standard cmd on an old build, but with the latest build this no longer works. 

If anyone has any ideas of a work around, would be great.

**Comment by awscodu** [comment]
I'm doing a fresh install of the new repository and I will update you over the weekend if I find another workaround

**Comment by harewei** [comment]
I'm currently using GPU version release 2 beta 5 with binary script install.  there is no cntk.exe under C:\local\cntk\x64, but there is one in C:\local\cntk\cntk

Anyway, I'm having the exact same issue as the original poster.  Please tell me if someone has managed to solve this problem.  I followed the exact step by step instruction from [https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#summary](url)

**Comment by jsloan-honeycombcorp** [comment]
I'm seeing the same problem as @harewei with error: No module named 'past' in ...\FastRCNN\selectivesearch\selectivesearch.py", line 3

```(cntk) d:\local\cntk\Examples\Image\Detection\FastRCNN>cntk
-------------------------------------------------------------------
Build info:

                Built time: Dec 12 2016 08:59:14
                Last modified date: Mon Dec 12 04:13:01 2016
                Build type: Release
                Build target: GPU
                With 1bit-SGD: no
                With ASGD: yes
                Math lib: mkl
                CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
                CUB_PATH: c:\src\cub-1.4.1
                CUDNN_PATH: C:\local\cudnn-8.0-windows10-x64-v5.1
                Build Branch: HEAD
                Build SHA1: e6a8577fa5ecd2f47d9b055b531d3e4b6258ba80 (modified)
                Built by svcphil on liana-08-w
                Build Path: C:\jenkins\workspace\CNTK-Build-Windows\Source\CNTK\```

**Comment by Joracosu** [comment]
I spend two weeks with this same issue and I am getting crazy. What is the solution for this???
When I run the command 'python A2_RunCNTK.py', I allways get the same error no matter what CNTK build I have (GPU or CPU, release or debug) and no matter if I use cmd or PowerShell or GitBash:

--------------------------------------------------------------
2017-01-08 13:03:00
PARAMETERS: datasetName = grocery
PARAMETERS: cntk_nrRois = 2000
cntk.exe configFile=C:\src\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/fastrcnn.cntk currentDirectory=C:\src\cntk\Examples\Image\Detection\FastRCNN/proc/grocery_2000/cntkFiles/ NumLabels=17 NumTrainROIs=2000 TrainROIDim=8000 TrainROILabelDim=34000 NumTestROIs=2000 TestROIDim=8000 TestROILabelDim=34000
Traceback (most recent call last):
  File "a2_runcntk.py", line 41, in <module>
    pid = subprocess.Popen(cmdStr, cwd = cntkFilesDir)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py34\lib\subprocess.py", line 1111, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system can not found the specified file

The error comes from the file 'subprocess.py' of the Anaconda's Lib path. The code is as follow:
hp, ht, pid, tid = _winapi.CreateProcess(executable, args, None, None, int(not close_fds), creationflags, env, cwd, startupinfo)

What and where is the 'specified' file???? How can I fix this??

NOTE: I use Windows10 64bit

**Comment by harewei** [comment]
To anyone who still have the same issue as the OP, refer to #1242 
basically set PATH=c:\local\cntk\cntk;%PATH% in cmd so cntk.exe can be detected.  there's nothing wrong with your subprocess.py at all.  took me a few hours of searching around because both the error message and tutorial were extremely ambiguous...

**Comment by pkranen** [comment]
Correct (as posted in my reply above from November 8th and as stated in the [Setup section](https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN#setup) of the Fast R-CNN tutorial: "The tutorial further assumes that the folder where cntk.exe resides is in your PATH environment variable."). Small comment: The path (in your case `c:\local\cntk\cntk`) depeds on where you install/build cntk and hence might differ for other users. You need to add the folder that contains `cntk.exe` to your path.

**Comment by pkranen** [comment]
Regarding the message _No module named 'past'_ please run `pip install future` in your CNTK python environment.
