### ISSUE TITLE
Sparse inputs in Python

### ISSUE THREAD

**Issue by mKaloer** [Microsoft/CNTK#982]
Hi,

I am aware that only dense NumPy inputs are supported in the current version of the Python wrapper. However, I wonder if there is any workaround that allows me to use sparse matrices in some other way. For example, I see in the examples (e.g. [seqcla.py](https://github.com/Microsoft/CNTK/blob/master/contrib/Python/cntk/examples/LSTM/seqcla.py)) that readers do support sparse inputs in Python, but my dataset is too large to store on disk. I've digged into the code but fail to find out whether there is a way to create some kind of sparse input object (without that necessarily being a sparse SciPy matrix). 

Is there some reasonable workaround, or do I have to use dense matrices for now?

Thanks

**Comment by wolfma61** [comment]
Sparse Tensors are supported in Python https://cntk.ai/pythondocs/concepts.html?highlight=sparse

For follow up questions I would recommend open a new issue ...
