### ISSUE TITLE
I got a Error message when i installed CNTK-2-0-beta1

### ISSUE THREAD

**Issue by k20001014** [Microsoft/CNTK#984]
I installed CNTK-2-0 following step as below link...

https://github.com/Microsoft/CNTK/wiki/Automated-binary-install#installation-steps-for-windows

....

Step3.
PS C:\...Scripts\windows> .\install.ps1        <-- when I  enter the this commender

The following operation will be performed:
 * Install VS2012 Runtime
 * Install MSMPI
 ....
 * Clone CNTK from Github repository

Do you want to continue? <y/n>
y <-- I enter the 'y'

but I got error messages...

Performing download operations
Exception caught - function main / failure - End time [MM/DD/YYYY hh:mm:ss]
System.Management.Automation.RuntimeException: null
  Location : System.Management.Automation.ArrayReferenceNode.GetValue<Object target, Object index, ExecutionContext context>
  Location : System.Management.Automation.ArrayReferenceNode.Execute<Array input, Pipe outputPipe, ExecutionContext context>
  Location : System.Management.Automation.AssignmentStatementNode.Execute<Array input, Pipe outputPipe, ExecutionContext context>
  Location : System.Management.Automation.StatementListNode.ExecuteStatement<ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context>

i'm in step3...
how can I go step4...

**Comment by hzhengran** [comment]
I got the same issue

**Comment by wolfma61** [comment]
Hi -

The error has shown up on older Powershell versions.
What version of Powershell is installed on your system? ($PSVersionTable.psversion)
it should at least be 3, better version 4.
https://www.microsoft.com/en-us/download/details.aspx?id=40855

Hope this helps
Wolfgang

**Comment by wolfma61** [comment]
I'm closing this. If you encounter the same problem, please also see issue #994 
Please reopen if necessary

**Comment by k20001014** [comment]
thank you for answering.
