### ISSUE TITLE
No module named 'examples' 

### ISSUE THREAD

**Issue by amotupal** [Microsoft/CNTK#985]
I am following the tutorial from the page `_https://www.cntk.ai/pythondocs/gettingstarted.html#getting-started_` but when I run the program python is throwing the following error
Traceback (most recent call last):
  File "ExFullyConnectedClassifierNet.py", line 6, in <module>
    from examples.common.nn import fully_connected_classifier_net
ImportError: No module named 'examples'

I am using this on Windows 10 64 bit. Did I miss something here?
I am able to access cntk module without any issue.

**Comment by sayanpa** [comment]
can you please try activating the CNTK python env. Also described in section here: https://github.com/Microsoft/CNTK/wiki/CNTK-Binary-Download-and-Manual-Installation - Step 2.

Did you succeed in running through the setup steps (https://www.cntk.ai/pythondocs/setup.html). 

We have rolled out a doc fix to clarify this in the getting started page. This will be updated in the next day or two.

**Comment by wolfma61** [comment]
closing - if you still have the same issue in beta2, please reopen

**Comment by arijit17** [comment]
This does not work for me as well! I'm using latest n' greatest Windows 10, 64 bit. Getting this error:

(cntk-py34) C:\src\cntk\bindings\python>python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Dec  1 2015, 11:39:45) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import cntk
>>> import cntk.ops as C
>>> from cntk.learner import sgd
>>> from cntk.utils import get_train_loss
>>> from examples.common.nn import fully_connected_classifier_net
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'examples'
>>>

I'm using latest n' greatest build from source, and I checked that every example given here (https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows) works!

**Comment by GopikrishnanSasikumar** [comment]
@arijit17 go to your anaconda/envs/cntk-py34/Lib//site-packages there must be a folder Examples.If it is there check the import code whether the folder name is correct,e is capital in Examples.In my case there was no folder named Examples and the cntk binary package I downloaded doesnot contain certain folders.So I downloaded it from (https://github.com/microsoft/CNTK) and manually copied the example folder to the above said location.It worked.
