### ISSUE TITLE
Got error when executing automated binary install

### ISSUE THREAD

**Issue by hzhengran** [Microsoft/CNTK#986]
I'm following the instructions at 
[https://github.com/Microsoft/CNTK/wiki/Automated-binary-install#installation-steps-for-windows](https://github.com/Microsoft/CNTK/wiki/Automated-binary-install#installation-steps-for-windows ). 
But got error in step 3. It seems the download fails immediately.

The error msg is:

```
The following operations will be performed:
 * Install MSMPI
 * Install Anaconda3-4.1.10
 * Setup CNTK PythonEnvironment 3.4
 * Setup CNTK Wheel
 * Create CNTKPY34 batch file
 * Clone CNTK from Github repository

Do you want to continue? (y/n)
y
Performing download operations
Exception caught - function main / failure - End time [11/02/2016 10:58:02]
System.Management.Automation.RuntimeException: Cannot index into a null array.
   at System.Management.Automation.ArrayReferenceNode.GetValue(Object target, Object index, ExecutionContext context)
   at System.Management.Automation.ArrayReferenceNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, ExecutionContext contex
t)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputP
ipe, ArrayList& resultList, ExecutionContext context)
```

Anyone can help? Thanks!

**Comment by blair0011** [comment]
I am getting the same error. Can anyone help?

**Comment by wolfma61** [comment]
Hi -

The error has shown up on older Powershell versions.
What version of Powershell is installed on your system? ($PSVersionTable.psversion)
it should at least be 3, better version 4.
https://www.microsoft.com/en-us/download/details.aspx?id=40855

Hope this helps
Wolfgang

**Comment by blair0011** [comment]
I'm running 5.1.14393.206 i.e. Windows 10 Anniversary Edition.

**Comment by wolfma61** [comment]
@blair0011 
hmmm. unfortunately nothing I have encountered then before ...

please try the following
start powershell and changed in the directory with the install.ps1 script

enter: start-transcript log.txt
.\install.ps1 -verbose

now the script will run ... once it has stopped/error-ed type

stop-transcript

please upload the log file to this issue

there is also a beta2 available now with changes to the installer, although nothing specific addressing this issue.
You could try beta2 and see if this changes anything (it needs to get 'unzipped' in a different directory)

thx
Wolfgang

**Comment by hzhengran** [comment]
aha, i update to PowerShell4 and it worked fine!
Thank you @wolfma61 !
