### ISSUE TITLE
how to evaluate lstm model like 'ATIS.slot.lstm' use c++?

### ISSUE THREAD

**Issue by cxf2015** [Microsoft/CNTK#987]
how to evaluate lstm model like 'ATIS.slot.lstm' use c++(EvalDll.dll)?

**Comment by cxf2015** [comment]
@cha-zhang @raaaar

**Comment by zhouwangzw** [comment]
You can use extended Eval interface: CNTKEvalExtended which supports RNN models.

**Comment by cxf2015** [comment]
@zhouwangzw can i compile that if i have no CUDA

**Comment by zhouwangzw** [comment]
You can build Eval (including extended Eval) without CUDA by using CPUONLY flavor. The EvalDll.dll included in the CNTK binary drop supports the extended Eval too.

**Comment by cxf2015** [comment]
@zhouwangzw thank you! 
do you have any example codes to evaluate RNN models?

**Comment by zhouwangzw** [comment]
@cxf2015 There is an example in branch zhouwang/pr899, based on the pull request from @weisong. Please look into that [CPPEvalExtendedClient.cpp] https://github.com/Microsoft/CNTK/blob/zhouwang/pr899/Examples/Evaluation/CPPEvalExtendedClient/CPPEvalExtendedClient.cpp) for how to evaluate a RNN model. The example will be integrated into master very soon.

**Comment by cxf2015** [comment]
@zhouwangzw thank you

**Comment by zhouwangzw** [comment]
The example is now in master and will be included in the next binary download too.
