### ISSUE TITLE
How to calculate the average activation of a unit within a minibatch?

### ISSUE THREAD

**Issue by e-thereal** [Microsoft/CNTK#988]
I've found two operations that come very close to what I want. The ReduceElements operation can be used to reduce along different axis of a single tensor except for the axis that spans different samples of a minibatch. In comparison, the SumElements operation calculates a sum over all elements of a minbatch, thereby also summing over all samples within the minibatch. I would like to be able to calculate the sum of the same element of a tensor for all samples of a mini-batch. This would allow me to calculate the average activation of a hidden unit and in turn would allow to specify a sparsity term for the hidden units. Is there any way to accomplish this in CNTK? And if so, how would I do it?
Thanks!

**Comment by n17s** [comment]
Have you looked into how [layerNormalization](https://github.com/Microsoft/CNTK/wiki/Layers-Library-Reference#batchnormalization-layernormalization-stabilizer) works?

**Comment by e-thereal** [comment]
@n17s Thank you for your reply. Yes I have looked at layerNormalization. The LayerNormalization() function calculates the mean over all elements of a sample but I need it the other way round (the mean over all samples of a minibatch for each element). The closest thing to what I want is BatchNormalization. However, BatchNormalization only calculates the mean over samples internally and does not expose the calculated mean in order to use it independendly of the normalized output. Since BatchNormalization is implemented as a dedicated ComputationNodeNonLooping class and not using BrainScript (as is the case for LayerNormalization()), I don't see a way to just have the mean calculation without creating a new node type in CNTK based on the implementation on BatchNormalization. However, it seems that the ReduceElementsNode would be a much better starting point, because it is already very close to what I want to achieve. Maybe it just needs to be implemented as a ComputationNodeNonLooping, similar to the SumElementsNode, but I just don't quite understand the implementation of both nodes and I'm afraid I'm not able to make the necessary changes myself.

**Comment by n17s** [comment]
Yes it is impossible to get to the mean activation from the batchNormalizationNode. It hides this from you. One option would be to use the V2 API where reductions can be used with the batch axis. In Python:
```python
avg = C.reduce_mean(x, axis=C.Axis.default_batch_axis())
``` 
and in C++
```cpp
avg = ReduceMean(x, Axis::DefaultBatchAxis());
```
