### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Nagarc** [Microsoft/CNTK#989]
I have installed by following the instructions given here and I can see it is successful as below
Performing install operations
Cloning CNTK (branch v2.0.beta1.0) repository....
Cloning CNTK (branch v2.0.beta1.0) repository.... ** Exit Code **:(128)
Install operations finished

CNTK v2 Python install complete.

To activate the CNTK Python environment and set the PATH to include CNTK, start
a command shell and run
   C:\local\cntk\scripts\cntkpy34.bat

Please checkout examples in the CNTK repository clone here:
    c:\repos\cntk\bindings\python\examples
but I cante any thing under repos folder...is something changed?

**Comment by junjieqian** [comment]
It seems first step does not success, as 

> "Cloning CNTK (branch v2.0.beta1.0) repository.... ** Exit Code **:(128)"

**Comment by sayanpa** [comment]
Hi Naga, Can you delete the directory C:\repos and rerun the installer script please. The cloning should resume. Thanks.

**Comment by Nagarc** [comment]
I think CNTK dont support intel processor .. cntk-2.0.beta1.0-cp34-cp34m-win_amd64.whl...i found this is the issue with my system..I will go for azure... Thanks for the reply
