### ISSUE TITLE
TracingGPUMemoryAllocator

### ISSUE THREAD

**Issue by HarryCLucas** [Microsoft/CNTK#99]
I'm running CNTK on my Surface Pro 3, with i7 and 8GB RAM. Being a Surface, it doesn't have a discrete GPU, so I'm a bit puzzled about why I get this error when running the CSEvalClient. 

`[CALL STACK]
    >Microsoft::MSR::CNTK::TracingGPUMemoryAllocator::operator=
    -00007FFAAF611F8A (SymFromAddr error : Attempt to access invalid address.)
    -00007FFAAF6125E3 (SymFromAddr error : Attempt to access invalid address.)
    -Microsoft::MSR::CNTK::GetEval<double>
    -00007FFA670EBCC3 (SymFromAddr error : The specified module could not be found.)

Error: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Microsoft.MSR.CNTK.Extensibility.Managed.IEvaluateModelManaged<float>.Init(String config)
   at Microsoft.MSR.CNTK.Extensibility.Managed.CSEvalClient.Program.Main(String[] args) in C:\CNTKDepends\CNTK\Source\Extensibility\CSEvalClient\Program.cs:line 48
 No Inner Exception
Press <Enter> to terminate.`

I also get an SEHException when running the wrapper on my own code. 

Any advice?

Thanks!

**Comment by frankseide** [comment]
It could be a known bug where the code cannot be loaded if certain CUDA DLLs are missing, which should have been delay-loaded, combined with the C# wrapper somehow masking the error.

The first thing to try would be to use a CPU-only build and see if the problem persists.

Independently, we should also review the C# wrapper whether it catches C++ exceptions correctly, will look at that tomorrow.

Thanks for reporting this!

Sent from Outlook<http://aka.ms/Ox5hz3>

_____________________________

**Comment by wolfma61** [comment]
@HarryCLucas: 
Are you still stuck here?
Did you try the CPU_Only build/binaries?

thx
Wolfgang

**Comment by frankseide** [comment]
The failure is a dup of Issue #76, which is not reported correctly by C# wrapper prototype. I opened a separate issue regarding the C# wrapper as Issue #115.

**Comment by wolfma61** [comment]
with this we can probably close this issues
thx
Wolfgang

**Comment by rvenkidapathy** [comment]
I am doing eval in Speech examples. 
I get the following  error when I do 'eval'

[CALL STACK]
    > 000000013FB11EB1 (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FC7E43D (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FC7D9FD (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FBE05FC (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FBCC921 (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FBDFAC9 (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FBC6AFC (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FB24F34 (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FAE728E (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FAE797C (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FAE7C4B (SymFromAddr() error: Attempt to access invalid address.)
    - 000000013FD13593 (SymFromAddr() error: Attempt to access invalid address.)



My config file 

# Note: This sample uses the deprecated NdlNetworkBuilder.
#       An updated version using BrainScript is coming soon.
#       Please find updated samples on Github, https://github.com/Microsoft/CNTK/tree/master/Examples /...
#
# Parameters can be overwritten on the command line
# for example: cntk configFile=myConfigFile RootDir=../.. 
# For running from Visual Studio add
# currentDirectory=$(SolutionDir)/<path to corresponding data folder> 
RootDir = ".."

ConfigDir = "$RootDir$/Config"
DataDir = "$RootDir$/Data"
OutputDir = "$RootDir$/Output"
ModelDir = "$OutputDir$/Models"

# deviceId = -1 for CPU, >=0 for GPU devices, "auto" chooses the best GPU, or CPU if no usable GPU is available
deviceId = -1

command = speechTrain

precision = "float"
traceLevel = 1
modelPath = "$ModelDir$/cntkSpeechLSTM.dnn"
parallelTrain = true

#######################################
#  TRAINING CONFIG                    #
#######################################

frameMode = false
truncated = true

speechTrain = [
    action = "eval"
    nbrUttsIneachRecurrentIter = 16
    
    NDLNetworkBuilder = [
        networkDescription = "$ConfigDir$/lstmp-3layer-opt.ndl"
    ]
    
    SGD = [
        epochSize = 0
        minibatchSize = 16
        learningRatesPerMB = 0.5
        numMBsToShowResult = 10
        momentumPerMB = 0:0.9
        maxEpochs = 4
        keepCheckPointFiles = true       
    ]
    
    reader = [
        readerType = "HTKMLFReader"
        readMethod = "blockRandomize"
        miniBatchMode = "partial"
        randomize = "auto"
        verbosity = 0
        
        features = [
            dim = 363
            type = "real"
            scpFile = "$DataDir$/glob_0000.scp"
        ]
        
        labels = [
            mlfFile = "$DataDir$/glob_0000.mlf"
            labelMappingFile = "$DataDir$/state.list"
            labelDim = 132
            labelType = "category"
        ]
    ]
	
	dumpnode=[
    action = "dumpnode"
    modelPath = "$ModelDir$/cntkSpeechLSTM.dnn"
    outputFile = "$OutputDir$/modeltext/dump"
]
]

**Comment by ShagReza** [comment]
I'm trying to run an speech example and I get these errors:

0007FF7D9513FDO (symFormatAdress () error: Attempt to access invalid address

what should I do?
