### ISSUE TITLE
Is deconvolution actually supported in CNTK 1.7?

### ISSUE THREAD

**Issue by mikhail-barg** [Microsoft/CNTK#990]
Hello, I've been wondering, what's the actual status of Deconvoluion support in CNTK.
Quick search shows just a few related places, which seem to contradict with each other.
For example [CNTK_1_6_Release_Notes](https://github.com/Microsoft/CNTK/wiki/CNTK_1_6_Release_Notes) says that Deconvolution is supported, and references the 4th MNIST example which has been moved to "[Deprecated](https://github.com/Microsoft/CNTK/tree/master/Examples/Image/Deprecated)" folder recently.

Docs for the [Convolution](https://github.com/Microsoft/CNTK/wiki/Convolution) function list `transpose` parameter, but the [ConvolutionalLayer{}](https://github.com/Microsoft/CNTK/wiki/Layers-Reference#convolutionallayer) docs does not list it and in [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/master/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) this parameter is marked with "# TODO: support this".

So could you please clarify the situation?

**Comment by pkranen** [comment]
I fixed the deconvolution example in NDL here [https://github.com/Microsoft/CNTK/tree/pkranen/deconvNdl/Examples/Image/Deprecated](https://github.com/Microsoft/CNTK/tree/pkranen/deconvNdl/Examples/Image/Deprecated), please use the updated ndl file and the Macros file for now. I will follow up with a brain script version later.

**Comment by pkranen** [comment]
You can find a simple deconvolution example in brain script [here](https://github.com/Microsoft/CNTK/blob/pkranen/deconvBS/Examples/Image/Classification/ConvNet/Deconv_MNIST.cntk). Note that you also need the updated [CNTK.core.bs](https://github.com/Microsoft/CNTK/blob/pkranen/deconvBS/Source/CNTK/BrainScript/CNTKCoreLib/CNTK.core.bs) file, the changes are both in the branch [pkranen/deconvBS](https://github.com/Microsoft/CNTK/tree/pkranen/deconvBS).
