### ISSUE TITLE
save_model(model, model_dir + "/slu.cmf", True)  generatesRuntimeError error

### ISSUE THREAD

**Issue by jerryjguo** [Microsoft/CNTK#991]
In the LanguageUnderstanding.py example, how do we save the trained model? I tried "save_model(model, model_dir + "/slu.cmf", True) ".  But I got RunTime error.

==========================================
from cntk.persist import *
 
reader = create_reader(data_dir + "/atis.train.ctf")
model = create_model()
# train
train(reader, model, max_epochs=2)

save_model(model, model_dir + "/slu.cmf", True)  
==========================================
...........
    save_model(model, model_dir + "/slu.cmf", True)
  File "/usr/lib64/python3.4/site-packages/cntk/persist.py", line 21, in save_model
    root_op.save_model(filename, use_legacy_format)
  File "/usr/lib64/python3.4/site-packages/cntk/utils/swig_helper.py", line 52, in wrapper
    result = f(*args, **kwds)
  File "/usr/lib64/python3.4/site-packages/cntk/ops/functions.py", line 394, in save_model
    return super(Function, self).save_model(filename, use_legacy_format)
  File "/usr/lib64/python3.4/site-packages/cntk/cntk_py.py", line 1101, in save_model
    return _cntk_py.Function_save_model(self, modelFile, useLegacyModelFormat)
RuntimeError: All placeholders of a Function must be bound before performing a Forward computation on the Function!

**Comment by wolfma61** [comment]
there have been many changes and improvement since this issue was created, If this still occurs with the most recent released version, please reopen (or create a new issue) with sufficient information to reproduce the problem
