### ISSUE TITLE
EXEC : error : invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by kyu899** [Microsoft/CNTK#992]
I am trying to build CNTK solution.
Most of things are done, however, Python binding fails.
The error messages are as follows:

26>------ Build started: Project: PythonBindings, Configuration: Release_CpuOnly x64 ------
26>  Building for Python version '34', extra path is C:\Anaconda3
23>  NetworkTests.vcxproj -> C:\repos\CNTK\x64\Release_CpuOnly\NetworkTests.exe
26>  Using CNTK sources at 'C:\repos\CNTK\Source'
26>  Using CNTK libs at 'C:\repos\CNTK\x64\Release_CpuOnly'
26>  C:\Anaconda3\lib\site-packages\setuptools-17.1.1-py3.4.egg\setuptools\dist.py:294: UserWarning: The version specified ('2.0.beta1.0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
26>  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
26>     or: setup.py --help [cmd1 cmd2 ...]
26>     or: setup.py --help-commands
26>     or: setup.py cmd --help
26>  
26>EXEC : error : invalid command 'bdist_wheel'
26>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.MakeFile.Targets(38,5): error MSB3073: The command ".\vsbuild.bat "C:\repos\CNTK\x64\Release_CpuOnly\" "false" "false" "c:\local\swig" "" "" "C:\Anaconda3" """ exited with code 1.
22>  Finished generating code
22>  CNTK.vcxproj -> C:\repos\CNTK\x64\Release_CpuOnly\CNTK.exe

I followed every step presented in [https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows](url) except one thing: 
setx PATH C:\repos\CNTK\x64\Release_CpuOnly;%PATH%
The above command returns error message: 
"ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
Type "SETX /?" for usage."
So I run setx PATH "C:\repos\CNTK\x64\Release_CpuOnly;%PATH%" and got any error.

So I want to know how to deal with the error "EXEC : error : invalid command 'bdist_wheel'"

Thanks.

**Comment by mahilleb-msft** [comment]
Hm, you may be missing the "wheel" package.
Could you try "pip install wheel" in your Python environment?
It may be missing from the documentation (will look into that).

**Comment by kyu899** [comment]
Dear mahilleb,
Thank you. It works.
