### ISSUE TITLE
Running Examples: No module named cntk.device

### ISSUE THREAD

**Issue by khuangaf** [Microsoft/CNTK#993]
Hi, I got the error when trying to run the examples after activate-cntk:
`steeve@steeve-X550VC:~/repos/cntk/bindings/python/examples$ python NumpyInterop/FeedForwardNet.py 
Traceback (most recent call last):
  File "NumpyInterop/FeedForwardNet.py", line 10, in <module>
    from cntk.device import cpu, set_default_device
ImportError: No module named cntk.device`

I was wondering which version of python should I use?
And the following is my pythonpath variable:
For python2:
` 
>>> print(sys.path)
['', '/home/steeve/anaconda2/lib/python27.zip', '/home/steeve/anaconda2/lib/python2.7', '/home/steeve/anaconda2/lib/python2.7/plat-linux2', '/home/steeve/anaconda2/lib/python2.7/lib-tk', '/home/steeve/anaconda2/lib/python2.7/lib-old', '/home/steeve/anaconda2/lib/python2.7/lib-dynload', '/home/steeve/anaconda2/lib/python2.7/site-packages', '/home/steeve/anaconda2/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg', '/home/steeve/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg']
`

For Python3:
`['', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages']`
Hope you can give me some advice on how to solve it!

**Comment by n17s** [comment]
check the other thread you commented on.
