### ISSUE TITLE
Cloning CNTK - The system cannot find the file specified

### ISSUE THREAD

**Issue by Birky** [Microsoft/CNTK#994]
Hey all, after executing the _.\install.ps1 -execute_ everything worked except the repository cloning it ends with the following message:

> Cloning CNTK (branch v2.0.beta1.0) repository....
> Exception caught - function main / failure - End time [11/03/2016 17:37:45]
> System.InvalidOperationException: This command cannot be run due to the error: The system cannot find the file specified
> .
>    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

I run PowerShell as Administrator, but the result is still the same, what can be the problem?

**Comment by wolfma61** [comment]
Hi -
The error message looks like the GIT executable can't be found. 

was Git installed on your machine? is there a GIT.EXE in c:\Program Files\Git\bin\
I think the install found an existing git.exe (in a different location), and is now trying to call it at the 'wrong' location. 

The easiest workaround for you (if you have git installed), from a command prompt:

c:
md \repos
cd repos
clone --branch v2.0.beta1.0 --recursive https://github.com/Microsoft/CNTK

if you have move to our beta2, replace the v2.0.beta1.0 with v2.0.beta2.0

I hope this helps. 

Wolfgang

**Comment by wolfma61** [comment]
The method of git invocation has been changed in https://github.com/Microsoft/CNTK/commit/f4d3df38afa29258bfb1b9b0576cc5e4e7299f5b
