### ISSUE TITLE
Installation error: Python error

### ISSUE THREAD

**Issue by khuangaf** [Microsoft/CNTK#995]
When I was trying to use binary to install cntk on my windows as I followed the guide in this webpage:
https://github.com/Microsoft/CNTK/wiki/Automated-binary-install#installation-steps-for-windows

I bumped into this error when I type:
`.\install.ps1 -execute`

```
Fatal Python error: Py_Initialize: unable to load the file system codec
  File "C:\Python27\Lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax
```

Can anyone help me solve this?

**Comment by junjieqian** [comment]
Can you try some steps described in [link](http://stackoverflow.com/questions/5694706/py-initialize-fails-unable-to-load-the-file-system-codec). It seems due to the platform, that python cannot find the file system codec.

**Comment by wolfma61** [comment]
no follow-up for a long time, please open a new issue if you experience this in a more recent CNTK installation
